### PR TITLE
Ensure compiled script module object remains rooted while it's being passed around.

### LINKED ISSUE #33930: Spidermonkey assertion failure in script module tests
To reproduce:
1. `./mach build -d --debug-mozjs`
2. `./mach test-wpt /html/semantics/scripting-1/the-script-element/module/charset-01.html --headless --pref js.mem.gc.zeal.level=2 --pref js.mem.gc.zeal.frequency=1 --timeout-multiplier 10`

```
  ▶ CRASH [expected OK] /html/semantics/scripting-1/the-script-element/module/charset-01.html
  │
  │ [46250] Assertion failure: this->flags() == 0, at /Users/jdm/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a02aaf1/mozjs-sys/mozjs/js/src/gc/Cell.h:798
  │ #01: js::gc::CellWithTenuredGCPointer<js::gc::Cell, js::Shape>::headerPtr() const[/Users/jdm/src/servo/target/debug/servo +0x325b5d0]
  │ #02: JSObject::shape() const[/Users/jdm/src/servo/target/debug/servo +0x325b538]
  │ #03: JSObject::zoneFromAnyThread() const[/Users/jdm/src/servo/target/debug/servo +0x325c9ec]
  │ #04: void CheckIsMarkedThing<JSObject>(JSObject*)[/Users/jdm/src/servo/target/debug/servo +0x3ea96f0]
  │ #05: bool js::gc::IsAboutToBeFinalizedInternal<JSObject>(JSObject*)[/Users/jdm/src/servo/target/debug/servo +0x3ea7890]
  │ #06: bool js::gc::IsAboutToBeFinalizedUnbarriered<JSObject>(JSObject*)[/Users/jdm/src/servo/target/debug/servo +0x328d1fc]
  │ #07: js::ContextChecks::checkObject(JSObject*)[/Users/jdm/src/servo/target/debug/servo +0x328d138]
  │ #08: js::ContextChecks::check(JSObject*, int)[/Users/jdm/src/servo/target/debug/servo +0x328cf64]
  │ #09: void JSContext::checkImpl<JS::Handle<JSObject*>>(JS::Handle<JSObject*> const&)[/Users/jdm/src/servo/target/debug/servo +0x3367944]
  │ #10: void JSContext::check<JS::Handle<JSObject*>>(JS::Handle<JSObject*> const&)[/Users/jdm/src/servo/target/debug/servo +0x3307240]
  │ #11: JS::GetRequestedModulesCount(JSContext*, JS::Handle<JSObject*>)[/Users/jdm/src/servo/target/debug/servo +0x36e1cdc]
  │ #12: script::script_module::ModuleTree::resolve_requested_module_specifiers::h17c9a105c9297e2d[/Users/jdm/src/servo/target/debug/servo +0x18e8ea4]
  │ #13: script::script_module::ModuleTree::fetch_module_descendants::hf5ca59690645afc4[/Users/jdm/src/servo/target/debug/servo +0x18ea034]
  │ #14: script::script_module::fetch_inline_module_script::hb561b34d445417b1[/Users/jdm/src/servo/target/debug/servo +0x18f2558]
  │ #15: script::dom::htmlscriptelement::HTMLScriptElement::prepare::h9e22d83627e5f96b[/Users/jdm/src/servo/target/debug/servo +0x17c53a0]
  │ #16: script::dom::servoparser::ServoParser::tokenize::heaea0d014c146041[/Users/jdm/src/servo/target/debug/servo +0x293940c]
  │ #17: script::dom::servoparser::ServoParser::do_parse_sync::hea8a96169749944d[/Users/jdm/src/servo/target/debug/servo +0x1a19f14]
  │ #18: script::dom::servoparser::ServoParser::parse_sync::_$u7b$$u7b$closure$u7d$$u7d$::hedb5d4e9f345254f[/Users/jdm/src/servo/target/debug/servo +0x2939144]
  │ #19: profile_traits::time::profile::h2ac76a067ec15d02[/Users/jdm/src/servo/target/debug/servo +0x2814268]
  │ #20: script::dom::servoparser::ServoParser::parse_sync::h7a734adc755b40cd[/Users/jdm/src/servo/target/debug/servo +0x1a19e58]
  │ #21: script::dom::servoparser::ServoParser::resume_with_pending_parsing_blocking_script::h2b0012ecf0c058d2[/Users/jdm/src/servo/target/debug/servo +0x1a18824]
  │ #22: script::dom::document::Document::process_pending_parsing_blocking_script::h16b37df4bf9371b3[/Users/jdm/src/servo/target/debug/servo +0x1d9c554]
  │ #23: script::dom::document::Document::pending_parsing_blocking_script_loaded::h37a0ffd62a139238[/Users/jdm/src/servo/target/debug/servo +0x1d9c1a4]
  │ #24: script::dom::htmlscriptelement::finish_fetching_a_classic_script::ha73b25c002a1c7d9[/Users/jdm/src/servo/target/debug/servo +0x17c1ea8]
  │ #25: _$LT$script..dom..htmlscriptelement..ClassicContext$u20$as$u20$net_traits..FetchResponseListener$GT$::process_response_eof::h023489c2f7f0e0ef[/Users/jdm/src/servo/target/debug/servo +0x17c28d8]
  │ #26: _$LT$net_traits..FetchResponseMsg$u20$as$u20$net_traits..Action$LT$T$GT$$GT$::process::h58d33dd94f120f6a[/Users/jdm/src/servo/target/debug/servo +0x1b04bc8]
  │ #27: _$LT$script..network_listener..ListenerTask$LT$A$C$Listener$GT$$u20$as$u20$script..task..TaskOnce$GT$::run_once::hbe018d4d0d9f60d3[/Users/jdm/src/servo/target/debug/servo +0x167e0bc]
  │ #28: _$LT$script..task..CancellableTask$LT$T$GT$$u20$as$u20$script..task..TaskOnce$GT$::run_once::h387fac75b8079091[/Users/jdm/src/servo/target/debug/servo +0x2b4bb3c]
  │ #29: _$LT$T$u20$as$u20$script..task..TaskBox$GT$::run_box::hbf200ddc5cabfffb[/Users/jdm/src/servo/target/debug/servo +0x2b41ac8]
  │ #30: script::script_thread::ScriptThread::handle_msg_from_script::hfe246203c6a9c606[/Users/jdm/src/servo/target/debug/servo +0x1c89cb0]
  │ #31: script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::h35b31570ee56774f[/Users/jdm/src/servo/target/debug/servo +0x1d60030]
  │ #32: script::script_thread::ScriptThread::profile_event::h32695ef59e304f53[/Users/jdm/src/servo/target/debug/servo +0x1d60294]
  │ #33: script::script_thread::ScriptThread::handle_msgs::hec628a3a244bb0b0[/Users/jdm/src/servo/target/debug/servo +0x1c868ec]
  │ #34: script::script_thread::ScriptThread::start::h8c37a5f179cd619b[/Users/jdm/src/servo/target/debug/servo +0x1c81794]
  │ #35: _$LT$script..script_thread..ScriptThread$u20$as$u20$script_layout_interface..ScriptThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h3bc5df425fb59188[/Users/jdm/src/servo/target/debug/servo +0x1d5cfb4]
  │ #36: profile_traits::mem::ProfilerChan::run_with_memory_reporting::h3ce5b8175ef7571c[/Users/jdm/src/servo/target/debug/servo +0x1695118]
  │ #37: _$LT$script..script_thread..ScriptThread$u20$as$u20$script_layout_interface..ScriptThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::h014687a022785493[/Users/jdm/src/servo/target/debug/servo +0x1d5cdd4]
  │ #38: std::sys_common::backtrace::__rust_begin_short_backtrace::h1761d2c738176faa[/Users/jdm/src/servo/target/debug/servo +0x287e8a0]
  │ #39: std::thread::Builder::spawn_unchecked_::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h872595b16260976b[/Users/jdm/src/servo/target/debug/servo +0x1e577f0]
  │ #40: _$LT$core..panic..unwind_safe..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::hcbbd241c3a5a125a[/Users/jdm/src/servo/target/debug/servo +0x2674bf4]
  │ #41: std::panicking::try::do_call::h41b6a21c6b4fab4b[/Users/jdm/src/servo/target/debug/servo +0x1668200]
  │ #42: __rust_try[/Users/jdm/src/servo/target/debug/servo +0x166f214]
  │ #43: std::panicking::try::h5a8a1f4d43787b1e[/Users/jdm/src/servo/target/debug/servo +0x1667e14]
  │ #44: std::thread::Builder::spawn_unchecked_::_$u7b$$u7b$closure$u7d$$u7d$::h41a152f6a7544d3d[/Users/jdm/src/servo/target/debug/servo +0x1e55678]
  │ #45: core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::habab686d5cc78d6d[/Users/jdm/src/servo/target/debug/servo +0x296db88]
  │ #46: std::sys::pal::unix::thread::Thread::new::thread_start::hb184f2abd415aef7[/Users/jdm/src/servo/target/debug/servo +0x778b40c]
  │ #47: _pthread_start[/usr/lib/system/libsystem_pthread.dylib +0x6f94]
```

### LINKED ISSUE #33933: Crash in module script test
```
  ▶ CRASH [expected TIMEOUT] /html/semantics/scripting-1/the-script-element/module/dynamic-import/propagate-nonce-inline-module.html
  │
  │ Caught signal 11 in thread "Script(1,1)"
  │    0: backtrace::backtrace::libunwind::trace
  │              at /Users/jdm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.74/src/backtrace/libunwind.rs:116:5
  │       backtrace::backtrace::trace_unsynchronized
  │              at /Users/jdm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.74/src/backtrace/mod.rs:66:5
  │    1: <servoshell::backtrace::Print as core::fmt::Debug>::fmt
  │              at /Users/jdm/src/servo/ports/servoshell/backtrace.rs:65:13
  │    2: core::fmt::rt::Argument::fmt
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/fmt/rt.rs:165:63
  │       core::fmt::write
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/fmt/mod.rs:1168:21
  │    3: std::io::Write::write_fmt
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/io/mod.rs:1835:15
  │    4: servoshell::backtrace::print
  │              at /Users/jdm/src/servo/ports/servoshell/backtrace.rs:18:5
  │    5: servoshell::crash_handler::install::handler
  │              at /Users/jdm/src/servo/ports/servoshell/crash_handler.rs:36:21
  │    6: __simple_esappend
  │    7: _ZN2js2gc6detail18CellHasStoreBufferEPKNS0_4CellE
  │              at /Users/jdm/src/servo/target/debug/build/mozjs_sys-adc986b3e7b8a715/out/build/dist/include/js/HeapAPI.h:635:10
  │    8: _ZN2js2gc6detail18CellHasStoreBufferEPKNS0_4CellE
  │              at /Users/jdm/src/servo/target/debug/build/mozjs_sys-adc986b3e7b8a715/out/build/dist/include/js/HeapAPI.h:635:10
  │    9: _ZN2js2gc15IsInsideNurseryEPKNS0_4CellE
  │              at /Users/jdm/src/servo/target/debug/build/mozjs_sys-adc986b3e7b8a715/out/build/dist/include/js/HeapAPI.h:642:10
  │   10: _ZN2js2gc15IsInsideNurseryEPKNS0_11TenuredCellE
  │              at /Users/jdm/src/servo/target/debug/build/mozjs_sys-adc986b3e7b8a715/out/build/dist/include/js/HeapAPI.h:647:3
  │   11: _ZNK2js2gc11TenuredCell9isTenuredEv
  │              at /Users/jdm/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a02aaf1/mozjs-sys/mozjs/js/src/gc/Cell.h:238:5
  │   12: _ZNK2js2gc11TenuredCell5arenaEv
  │              at /Users/jdm/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a02aaf1/mozjs-sys/mozjs/js/src/gc/Cell.h:469:3
  │   13: _ZNK2js2gc11TenuredCell17zoneFromAnyThreadEv
  │              at /Users/jdm/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a02aaf1/mozjs-sys/mozjs/js/src/gc/Cell.h:487:59
  │   14: _ZNK8JSObject17zoneFromAnyThreadEv
  │              at /Users/jdm/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a02aaf1/mozjs-sys/mozjs/js/src/vm/JSObject.h:300:21
  │   15: _ZL18CheckIsMarkedThingI8JSObjectEvPT_
  │              at /Users/jdm/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a02aaf1/mozjs-sys/mozjs/js/src/gc/Marking.cpp:2486:23
  │   16: _ZN2js2gc28IsAboutToBeFinalizedInternalI8JSObjectEEbPT_
  │              at /Users/jdm/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a02aaf1/mozjs-sys/mozjs/js/src/gc/Marking.cpp:2540:3
  │   17: _ZN2js2gc31IsAboutToBeFinalizedUnbarrieredI8JSObjectEEbPT_
  │              at /Users/jdm/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a02aaf1/mozjs-sys/mozjs/js/src/gc/Marking.h:75:10
  │   18: _ZN2js13ContextChecks11checkObjectEP8JSObject
  │              at /Users/jdm/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a02aaf1/mozjs-sys/mozjs/js/src/vm/JSContext-inl.h:90:5
  │   19: _ZN2js13ContextChecks5checkEP8JSObjecti
  │              at /Users/jdm/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a02aaf1/mozjs-sys/mozjs/js/src/vm/JSContext-inl.h:83:7
  │   20: _ZN9JSContext9checkImplIJN2JS6HandleIP8JSObjectEEEEEvDpRKT_
  │              at /Users/jdm/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a02aaf1/mozjs-sys/mozjs/js/src/vm/JSContext-inl.h:207:33
  │   21: _ZN9JSContext5checkIJN2JS6HandleIP8JSObjectEEEEEvDpRKT_
  │              at /Users/jdm/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a02aaf1/mozjs-sys/mozjs/js/src/vm/JSContext-inl.h:214:5
  │   22: _ZN2JS24GetRequestedModulesCountEP9JSContextNS_6HandleIP8JSObjectEE
  │              at /Users/jdm/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a02aaf1/mozjs-sys/mozjs/js/src/vm/Modules.cpp:231:7
  │   23: script::script_module::ModuleTree::resolve_requested_module_specifiers
  │              at /Users/jdm/src/servo/components/script/script_module.rs:573:26
  │   24: script::script_module::ModuleTree::fetch_module_descendants
  │              at /Users/jdm/src/servo/components/script/script_module.rs:718:37
  │   25: script::script_module::fetch_inline_module_script
  │              at /Users/jdm/src/servo/components/script/script_module.rs:1755:13
  │   26: script::dom::htmlscriptelement::HTMLScriptElement::prepare
  │              at /Users/jdm/src/servo/components/script/dom/htmlscriptelement.rs:840:21
  │   27: script::dom::servoparser::ServoParser::tokenize
  │              at /Users/jdm/src/servo/components/script/dom/servoparser/mod.rs:613:13
  │   28: script::dom::servoparser::ServoParser::do_parse_sync
  │              at /Users/jdm/src/servo/components/script/dom/servoparser/mod.rs:550:9
  │   29: script::dom::servoparser::ServoParser::parse_sync::{{closure}}
  │              at /Users/jdm/src/servo/components/script/dom/servoparser/mod.rs:532:16
  │   30: profile_traits::time::profile
  │              at /Users/jdm/src/servo/components/shared/profile/time.rs:146:15
  │   31: script::dom::servoparser::ServoParser::parse_sync
  │              at /Users/jdm/src/servo/components/script/dom/servoparser/mod.rs:524:9
  │   32: script::dom::servoparser::ServoParser::resume_with_pending_parsing_blocking_script
  │              at /Users/jdm/src/servo/components/script/dom/servoparser/mod.rs:333:13
  │   33: script::dom::document::Document::process_pending_parsing_blocking_script
  │              at /Users/jdm/src/servo/components/script/dom/document.rs:2608:13
  │   34: script::dom::document::Document::pending_parsing_blocking_script_loaded
  │              at /Users/jdm/src/servo/components/script/dom/document.rs:2594:9
  │   35: script::dom::htmlscriptelement::finish_fetching_a_classic_script
  │              at /Users/jdm/src/servo/components/script/dom/htmlscriptelement.rs:320:13
  │   36: <script::dom::htmlscriptelement::ClassicContext as net_traits::FetchResponseListener>::process_response_eof
  │              at /Users/jdm/src/servo/components/script/dom/htmlscriptelement.rs:404:17
  │   37: <net_traits::FetchResponseMsg as net_traits::Action<T>>::process
  │              at /Users/jdm/src/servo/components/shared/net/lib.rs:344:31
  │   38: <script::network_listener::ListenerTask<A,Listener> as script::task::TaskOnce>::run_once
  │              at /Users/jdm/src/servo/components/script/network_listener.rs:122:13
  │   39: <script::task::CancellableTask<T> as script::task::TaskOnce>::run_once
  │              at /Users/jdm/src/servo/components/script/task.rs:114:13
  │   40: <T as script::task::TaskBox>::run_box
  │              at /Users/jdm/src/servo/components/script/task.rs:57:9
  │   41: script::script_thread::ScriptThread::handle_msg_from_script
  │              at /Users/jdm/src/servo/components/script/script_thread.rs:2551:17
  │   42: script::script_thread::ScriptThread::handle_msgs::{{closure}}
  │              at /Users/jdm/src/servo/components/script/script_thread.rs:2016:46
  │   43: script::script_thread::ScriptThread::profile_event
  │              at /Users/jdm/src/servo/components/script/script_thread.rs:2276:13
  │   44: script::script_thread::ScriptThread::handle_msgs
  │              at /Users/jdm/src/servo/components/script/script_thread.rs:2007:26
  │   45: script::script_thread::ScriptThread::start
  │              at /Users/jdm/src/servo/components/script/script_thread.rs:1459:15
  │   46: <script::script_thread::ScriptThread as script_layout_interface::ScriptThreadFactory>::create::{{closure}}::{{closure}}
  │              at /Users/jdm/src/servo/components/script/script_thread.rs:849:25
  │   47: profile_traits::mem::ProfilerChan::run_with_memory_reporting
  │              at /Users/jdm/src/servo/components/shared/profile/mem.rs:91:9
  │   48: <script::script_thread::ScriptThread as script_layout_interface::ScriptThreadFactory>::create::{{closure}}
  │              at /Users/jdm/src/servo/components/script/script_thread.rs:847:17
  │   49: std::sys_common::backtrace::__rust_begin_short_backtrace
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:155:18
  │   50: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/thread/mod.rs:542:17
  │   51: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panic/unwind_safe.rs:272:9
  │   52: std::panicking::try::do_call
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:559:40
  │   53: ___rust_try
  │   54: std::panicking::try
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:523:19
  │   55: std::panic::catch_unwind
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panic.rs:149:14
  │       std::thread::Builder::spawn_unchecked_::{{closure}}
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/thread/mod.rs:541:30
  │   56: core::ops::function::FnOnce::call_once{{vtable.shim}}
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
  │   57: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/alloc/src/boxed.rs:2063:9
  │       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/alloc/src/boxed.rs:2063:9
  │       std::sys::pal::unix::thread::Thread::new::thread_start
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys/pal/unix/thread.rs:108:17
  └   58: __pthread_joiner_wake
```
Reproduced under `--pref js.mem.gc.zeal.level=2 --pref js.mem.gc.zeal.frequency=1 --headless --timeout-multiplier=10` with a debug mozjs build.

### PR DESCRIPTION
**Pull request by jdm**
The existing code relied on storing a raw JS pointer inside of a Heap object that was was not stored in a rooted location while potential GC operations were subsequently invoked. These changes ensure that it's always rooted and the Heap value is only constructed inside of a rooted location.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #33930 and fix #33933.
- [x] There are tests for these changes

### CODE REVIEW

File: components/script/script_module.rs [hunk 1]
```diff
@@ -1707,22 +1716,24 @@ pub(crate) fn fetch_inline_module_script(
...
         module_script_text,
         &url,
         options.clone(),
     );
 
-    match compiled_module {
-        Ok(record) => {
+    match compiled_module_result {
+        Ok(_) => {
             module_tree.append_handler(
```
Comment (jdm) [inline components/script/script_module.rs:1731]: This is the operation that can trigger GCs, as exposed by #33928.

**Review by sagudev — APPROVED** [review]
