### PR TITLE
libservo: Expose `WebViewPoint` / `WebViewRect` and use them for the API

### LINKED ISSUE #40152: webdriver: Coordinates for headed window is seriously wrong
**Describe the bug:**

This causes tons of failure in headed window, which doesn't happen for headless mode. For example, `key_events.py` fully pass for headless, but has only 2/94 pass for headed.

https://github.com/user-attachments/assets/73c82cac-3984-4adc-8747-9a1b47e76500

**To Reproduce:**
`./mach test-wpt -r tests\wpt\tests\webdriver\tests\classic\perform_actions\key_events.py --product servodriver`

**Platform:**
All.

### PR DESCRIPTION
**Pull request by mrobinson**
This change exposes two new data types in the API, which allow embedders
to supply coordinates in either page pixels or device pixels. In
particular, WebDriver wants to give coordiantes to the API in page
pixels. This prevents the embedder from having to do these conversions
and makes it harder to misuse the API.

Testing: This should fix WebDriver conformance tests that are run in headed mode.
Fixes: #40152

### CODE REVIEW

**Comment by yezhizhen** [comment]
Unit test compilation is failing.

**Comment by mrobinson** [comment]
They should be compiling and passing now.

**Review by yezhizhen — COMMENTED** [review]
Need to change `egl` as well.

File: components/shared/embedder/lib.rs [hunk 1]
```diff
@@ -42,11 +42,89 @@ use style_traits::CSSPixel;
...
 pub use crate::input_events::*;
 pub use crate::webdriver::*;
 
+/// A point in a `WebView`, either expressed in device pixels or page pixels.
+/// Page pixels are CSS pixels, which take into account device pixel scale,
+/// page zoom, and pinch zoom.
+#[derive(Clone, Copy, Debug, Deserialize, MallocSizeOf, PartialEq, Serialize)]
+pub enum WebViewPoint {
+    Device(DevicePoint),
+    Page(Point2D<f32, CSSPixel>),
```
Comment (yezhizhen) [inline components/shared/embedder/lib.rs:59]: Just curious why is it called "page pixel". Is it a convention?

**Review by yezhizhen — APPROVED** [review]

**Review by yezhizhen — APPROVED** [review]
Tested and indeed works now for headed mode.

File: components/shared/embedder/lib.rs (hunk 1 above)
Comment (mrobinson) [reply components/shared/embedder/lib.rs:59]: I was thinking a pixel on the page, but maybe CssPixel would be a better name?
