### PR TITLE
webdriver: Enable `pointerMove` to perform smooth transition over specified duration

### LINKED ISSUE #42950: PointerMove with long duration blinks to the end position if action sequence only have one tick
**Describe the bug:**
Video explains better. This is a pointermove of duration 2 seconds. 

https://github.com/user-attachments/assets/4a329dbe-ffb5-45a3-9499-e852c9954ecc

**To Reproduce:**
Add following to a wdspec test.
```python
def test_long_move(session, mouse_chain, test_actions_page):
    point = {"x": 250, "y": 250}

    mouse_chain.pointer_move(point["x"], point["y"], origin="viewport", duration=2000).perform()
    import time
    time.sleep(15)
```

**Platform:**
All

### PR DESCRIPTION
**Pull request by yezhizhen**
Enable `pointerMove` to perform a smooth transition over specified duration.

- Sync move/scroll interval with default tick duraiton in testdriver: https://github.com/servo/servo/blob/a60a8b1b4d2ba39bde4ae777262b05d14ed48855/tests/wpt/tests/resources/testdriver-actions.js#L34-L38
- Fully process all pending pointer moves within this tick. This is one of the conditions that is [required](https://w3c.github.io/webdriver/#dfn-perform-a-pointer-move:~:text=There%20are%20no%20pending%20asynchronous%20waits%20arising%20from%20the%20last%20invocation%20of%20the%20dispatch%20tick%20actions%20steps%2E) to finish this tick. Previously, the pending move events might be processed in next Tick, if they have long duration.

https://github.com/user-attachments/assets/8692086f-32bb-45f3-ae0c-a072f68e1e84

https://github.com/user-attachments/assets/35af99a9-889b-41c1-91e2-55f22ad453a1

Testing: Added a WPT test. I'm surprised it is not covered by existing tests, given the huge behaviour difference.
Fixes: https://github.com/servo/servo/issues/42950
Part of https://github.com/servo/servo/issues/41620

### CODE REVIEW

**Comment by yezhizhen** [comment]
Before fix: Blinks to end at the end of duration.
Now: Gradually moves.

https://github.com/user-attachments/assets/efcd6b2d-7fa1-4583-822c-e532cf649258 

https://github.com/user-attachments/assets/e25f6763-a26b-4324-9a0b-58a37669d5c8

```python
def test_long_move(session, mouse_chain, test_actions_page):
    point = {"x": 250, "y": 250}

    mouse_chain.pointer_move(point["x"], point["y"], duration=2000).perform()
    import time
    time.sleep(15)
```

This sucks.. The improvement is huge, but none of the existing test passes..

**Comment by yezhizhen** [comment]
Adding a test. We can assert more than 10 mousemove, with changing coordinates.

**Comment by yezhizhen** [comment]
Reported bug: https://github.com/SeleniumHQ/selenium/issues/12736

Interesting. It seems chromedriver/safaridriver is not spec-compliant, and also blinks. They both only get 2 `mousemove` events eventually, failing the new test.
[Safaridriver](https://github.com/web-platform-tests/wpt/actions/runs/22579230742/job/65406450039?pr=58169#step:11:64)
[Chromedriver](https://github.com/web-platform-tests/wpt/pull/58169/checks?check_run_id=65407053002#:~:text=FAIL%20Mousemove%20should%20transition%20smoothly%20over%20specified%20duration%20%2D%20assert%5Fgreater%5Fthan%3A%20Should%20have%20more%20than%2010%20mousemove%20events%20over%20500ms%20expected%20a%20number%20greater%20than%2010%20but%20got%202)

File: components/webdriver_server/actions.rs [hunk 1]
```diff
@@ -525,6 +531,9 @@ impl Handler {
 
         // Step 8. If duration is greater than 0 and inside any implementation-defined bounds,
         // asynchronously wait for an implementation defined amount of time to pass.
+
+        // Asynchronously wait means do not block browser to process event loop.
+        // In the context of Servo, it means block the webdriver server thread.
```
Comment (mrobinson) [inline components/webdriver_server/actions.rs:536]: Should this say:


```suggestion
        // In the context of Servo, it means not blocking the webdriver server thread.
```

?

**Review by mrobinson — COMMENTED** [review]
Seems reasonable to me, but I'll wait for the resolution of the issue with the test.

File: components/webdriver_server/actions.rs (hunk 1 above)
Comment (yezhizhen) [reply components/webdriver_server/actions.rs:536]: No. That's why we sleep the server thread right below.

Comment (yezhizhen) [inline components/webdriver_server/actions.rs:536]:
```suggestion
        // In the context of Servo, it means blocking the webdriver server thread.
```

**Comment by yezhizhen** [comment]
> Seems reasonable to me, but I'll wait for the resolution of the issue with the test.

I don't know who we can find to resolve this. The test seems fairly straightforward :(
The smooth move is part of spec, but only Firefox has implemented this.
And chromedriver team never responded: https://github.com/SeleniumHQ/selenium/issues/12736

**Review by mrobinson — APPROVED** [review]
