### PR TITLE
net: use system certificates

### LINKED ISSUE #32903: Certificate error connecting to servo.org
**Describe the bug:**

Trying to visit servo.org I get the message:

```
error trying to connect: invalid peer certificate: UnknownIssuer
```

image

Guessing servo needs the ability to use the system root CA.

Workaround (not really practical / safe), click `Allow cert temporarily` a lot.

**To Reproduce:**

Download servo on windows, run it, and see the above in the default window opening `https://servo.org`

**Platform:**

Windows 10 21H2 (OS Build 19044.4529)
AMD Ryzen 9 3900X 12-Core Processor
Servo Windows Zip 2024-07-31
SHA 756523fc9ec695644133787b5d768e172fe4657b0263490115c7a818418bd41d

### PR DESCRIPTION
**Pull request by Narfinger**
This changes the certificate verifier to use rustls_platform_verifier under the hood.

**Note**: The rustls-platform-verifier has specific instructions for android and currently we fall back to the webpki roots for this platform.

Testing: This was tested on linux, macos and ohos and the rest in the CI.
Fixes: Should fix https://github.com/servo/servo/issues/32903 and partially https://github.com/servo/servo/issues/35227

### CODE REVIEW

**Review by yezhizhen — APPROVED** [review]
This is really nice feature.

File: components/net/connector.rs [hunk 1]
```diff
@@ -171,28 +170,67 @@ where
...
             CACertificates::Default => rustls::RootCertStore {
                 roots: webpki_roots::TLS_SERVER_ROOTS.to_vec(),
             },
-            CACertificates::Override(root_cert_store) => root_cert_store,
-        };
+            CACertificates::Override(root_certs) => {
+                let mut root_cert_store = rustls::RootCertStore::empty();
+                for cert in root_certs {
+                    if root_cert_store.add(cert).is_err() {
+                        log::error!("Could not add certificate");
```
Comment (yezhizhen) [inline components/net/connector.rs]: Let's log the specific error and certificate.

File: components/net/resource_thread.rs [hunk 2]
```diff
@@ -63,13 +63,20 @@ use crate::request_interceptor::RequestInterceptor;
...
-    Ok(root_cert_store)
+
+    let certs = rustls_pemfile::certs(&mut pem)
+        .filter_map(|cert| {
+            if let Err(e) = cert {
+                log::error!("Could not load certificate ({e}). Ignoring it.");
+                None
+            } else {
+                Some(cert.unwrap())
+            }
```
Comment (jdm) [inline components/net/resource_thread.rs]:
```suggestion
            cert.inspect_err(|e| log::error!("Could not load certificate ({e}). Ignoring it.")).ok()
```

File: components/net/connector.rs [hunk 3]
```diff
@@ -171,28 +170,67 @@ where
...
 impl CertificateVerificationOverrideVerifier {
+    #[cfg(not(target_os = "android"))]
     fn new(
-        ca_certficates: CACertificates,
+        ca_certficates: CACertificates<'static>,
         ignore_certificate_errors: bool,
         override_manager: CertificateErrorOverrideManager,
     ) -> Self {
-        let root_cert_store = match ca_certficates {
+        let crypto_provider = Arc::new(rustls::crypto::aws_lc_rs::default_provider());
```
Comment (jdm) [inline components/net/connector.rs]: Right now we make embedders choose a crypto provider (https://github.com/servo/servo/blob/b00a76427aed5f2b4c9f9f182965f4f75962a9a8/ports/servoshell/lib.rs#L49-L52). I think we should use https://docs.rs/rustls/latest/rustls/crypto/struct.CryptoProvider.html#method.get_default here instead of forcing one provider.

**Review by jdm — APPROVED** [review]
Thanks for doing this!

File: components/net/connector.rs (hunk 3 above)
Comment (jdm) [reply components/net/connector.rs]: More details at https://docs.rs/rustls/latest/rustls/crypto/struct.CryptoProvider.html#using-the-per-process-default-cryptoprovider

**Comment by webbeef** [comment]
Does that change prevent embedders to use the webpki roots on platforms other than Android?

**Comment by Narfinger** [comment]
Currently, as I understand it, you can still override the certificates as an embedder.
The current thing will use the webpki roots on android. With modifications to the android code (https://docs.rs/rustls-platform-verifier/latest/rustls_platform_verifier/#android) it will use the platform certificates in addition to the webpki roots.

**Comment by webbeef** [comment]
> Currently, as I understand it, you can still override the certificates as an embedder.

How? I could only find the `certificate_path` option to configure a custom store, but that's different than choosing to use the webpki root certs. I hope I'm missing something!

**Comment by Narfinger** [comment]
Oh I thought that is what you meant. With this PR there is the option to use a custom store via "certificate_path". Otherwise it will use the certificate system from the platform. If it doesn't have any way to get certificates from the platform it will fall back to webpki roots.

Can you explain the reason why an embedder would want the webpki roots specifically instead of relying on the platform which gives better security guarantees?

**Comment by webbeef** [comment]
> Can you explain the reason why an embedder would want the webpki roots specifically instead of relying on the platform which gives better security guarantees?

Because the platform does not necessarily give better security guarantees, and you may not want to be tied to the OS policy on that front. Firefox by default ships with its own roots, and can be setup to also lookup OS provided ones (useful for enterprise deployments).

It would be better to have an explicit toggle (eg. a pref) to control that behavior.

**Comment by Narfinger** [comment]
Ok I added a way to just use the webpki verifier.
One question remains: Currently, if you override the certificate store, it is given as additional roots in the platform verifier. I think this is ok because if the platform has revocations than we should honor them but if you have some input into it that would be good.

**Comment by webbeef** [comment]
> Ok I added a way to just use the webpki verifier.

Thanks!

> One question remains: Currently, if you override the certificate store, it is given as additional roots in the platform verifier. I think this is ok because if the platform has revocations than we should honor them but if you have some input into it that would be good.

That looks reasonable to me.

File: components/net/connector.rs [hunk 4]
```diff
@@ -171,30 +174,46 @@ where
...
+                    .expect("Could not initialize platform certificate verifier"),
+            ),
+            CACertificates::WebPKI => {
+                let root_store = Arc::new(rustls::RootCertStore::from_iter(
+                    webpki_roots::TLS_SERVER_ROOTS.iter().cloned(),
+                ));
+
+                rustls::client::WebPkiServerVerifier::builder(root_store)
+                    .build()
+                    .expect("G") as Arc<dyn ServerCertVerifier>
```
Comment (mukilan) [inline components/net/connector.rs]: The message here probably needs to be fixed.

Comment (Narfinger) [reply components/net/connector.rs]: Fixed. Thanks for noticing!
