### PR TITLE
Use gstreamer on UWP targets

### LINKED ISSUE #27531: All media manual tests fail on HL2
https://www.joshmatthews.net/hl2-test/media.html works fine in desktop UWP, but none of the tests produce any sound on a hololens 2.

### LINKED ISSUE #27532: Support outputting GST_DEBUG to a log file from UWP app
Right now it gets piped through the integrated logging mechanism, but for release builds it would be useful to have it be independent.

### PR DESCRIPTION
**Pull request by jdm**
This fixes a regression that cause our arm64 builds to use the dummy media stack by default. Oops.

Fix #27531. Fix #27532.

### CODE REVIEW

File: support/hololens/ServoApp/ServoControl/Servo.cpp [hunk 1]
```diff
@@ -281,6 +281,10 @@ Servo::Servo(std::optional<hstring> initUrl, hstring args, GLsizei width,
   sServo = this; // FIXME;
 
   auto current = ApplicationData::Current();
+  auto gstLog = std::wstring(current2.LocalFolder().Path()) + L"\\gst.log";
```
Comment (CYBAI) [inline support/hololens/ServoApp/ServoControl/Servo.cpp:284]:
```
         C:\Users\task_1596769352\repo\support\hololens\ServoApp\ServoControl\Servo.cpp(290,30): error C2065: 'current2': undeclared identifier [C:\Users\task_1596769352\repo\support\hololens\ServoApp\ServoApp.vcxproj]
```
