### PR TITLE
script: Use stylo dom apis for querySelector/querySelectorAll

### LINKED ISSUE #41105: CSS `:scope` selector in `querySelectorAll()` doesn't work alongside commas in the selector (which results in `jQuery.find()` breaking)
**Describe the bug:**
`:scope` is used extensively by `jQuery.find()` whenever you query a disconnected set of DOM elements (such as those created from `var a = $("<b><p></p></b>")` and the like) and if you use a comma in the selector, then the whole selector breaks when passed to `querySelectorAll`

**To Reproduce:**
Test case.
```html
<!doctype html>
<body>
<div id=AAA>
<script>
let p = document.createElement('p')
p.innerHTML = `<b></b>`;
[...p.querySelectorAll(
    `:scope b, :scope p`
)].forEach(e=>AAA.innerText+=e.outerHTML)
</script>
```
This prints `<b></b>` in Firefox and nothing in Servo.

**Platform:**
Windows 10.

### PR DESCRIPTION
**Pull request by simonwuelker**
Stylo has ready-to-use apis for `Node::querySelector` and `Node::querySelectorAll`. We currently instead set up our own selector queries, which is neither as correct nor as performant, so this change makes servo use the stylo interfaces instead.

This change contains a fair amount of unsafe code - review with caution!

Notably, this makes the tab component from the astro framework work correctly in servo (https://starlight.astro.build/components/tabs/). I've seen that (broken) component on multiple websites.

Fixes https://github.com/servo/servo/issues/41105
Testing: New tests start to pass

### CODE REVIEW

File: components/script/dom/bindings/root.rs [hunk 1]
```diff
@@ -101,6 +101,15 @@ where
         assert_in_layout();
         self.value.is::<U>()
     }
+
+    /// Get a reference to the internal value.
+    ///
+    /// ## SAFETY
+    /// This function effectively circumvents all the safety provided by `LayoutDom` as it allows
+    /// performing arbitrary (potentially mutating) operations on the value. Use with caution!
+    pub(crate) unsafe fn as_ref(self) -> &'dom T {
```
Comment (mrobinson) [inline components/script/dom/bindings/root.rs:110]: I'm not sure this has to be unsafe. It's pub(crate) which means it cannot be called from layout (the real danger as layout accesses nodes from multiple threads). In addition, this consumes the `LayoutDom`, which is great, because it ensure that `LayoutDom` can't later be passed to layout.

File: components/script/layout_dom/element.rs [hunk 2]
```diff
@@ -77,6 +78,11 @@ impl<'dom> ServoLayoutElement<'dom> {
         ServoLayoutElement { element: el }
     }
 
+    /// Returns the interior of this element as a `LayoutDom`.
+    pub(crate) fn to_layout_js(self) -> LayoutDom<'dom, Element> {
+        self.element
+    }
```
Comment (mrobinson) [inline components/script/layout_dom/element.rs:87]: This should probably have a bit more documentation saying that this should never be exposed to layout.


Rename suggestion to make it more closely match the return type:

```suggestion
    /// Returns the interior of this element as a `LayoutDom`.
    pub(crate) fn to_layout_dom(self) -> LayoutDom<'dom, Element> {
        self.element
    }
```

File: components/script/layout_dom/node.rs [hunk 3]
```diff
@@ -70,7 +75,7 @@ impl fmt::Debug for ServoLayoutNode<'_> {
 }
 
 impl<'dom> ServoLayoutNode<'dom> {
-    pub(super) fn from_layout_js(n: LayoutDom<'dom, Node>) -> Self {
+    pub(crate) fn from_layout_js(n: LayoutDom<'dom, Node>) -> Self {
```
Comment (mrobinson) [inline components/script/layout_dom/node.rs:78]: Nit: Maybe a good moment to rename this as well and fix the parameter name.


```suggestion
    pub(crate) fn from_layout_js(node: LayoutDom<'dom, Node>) -> Self {
```

File: components/script/layout_dom/node.rs [hunk 4]
```diff
@@ -100,6 +105,39 @@ impl<'dom> ServoLayoutNode<'dom> {
...
+            SelectorParser::parse_author_origin_no_namespace(selector, &UrlExtraData(document_url));
+
+        // Step 2. If selector is failure, then throw a "SyntaxError" DOMException.
+        let Ok(selector_list) = selector_or_error else {
+            return Err(Error::Syntax(None));
+        };
+
+        // Step 3. Return the result of match a selector against a tree with selector
+        // and node’s root using scoping root node.
+        query_selector::<ServoLayoutElement<'dom>, Q>(
```
Comment (mrobinson) [inline components/script/layout_dom/node.rs]: Do you know if this uses multiple threads or not?

File: components/script/layout_dom/document.rs [hunk 5]
```diff
@@ -39,6 +40,22 @@ impl<'ld> ::style::dom::TDocument for ServoLayoutDocument<'ld> {
...
         self.document.style_shared_lock()
     }
+
+    fn elements_with_id<'a>(&self, id: &AtomIdent) -> Result<&'a [ServoLayoutElement<'ld>], ()>
+    where
+        Self: 'a,
+    {
+        let elements_with_id = self.document.elements_with_id(&id.0);
+
+        // SAFETY: ServoLayoutElement is known to have the same layout and alignment as LayoutDom<Element>
```
Comment (mrobinson) [inline components/script/layout_dom/document.rs:50]: Spooky, but it makes sense. Is it possible to use a compile time assertion that the sizes of the two data structures are the same?

File: components/script/layout_dom/node.rs [hunk 6]
```diff
@@ -100,6 +105,39 @@ impl<'dom> ServoLayoutNode<'dom> {
             .map(LayoutDom::upcast)
             .map(ServoLayoutElement::from_layout_js)
     }
+
+    /// <https://dom.spec.whatwg.org/#scope-match-a-selectors-string>
+    pub(crate) fn scope_match_a_selectors_string<Q>(
```
Comment (mrobinson) [inline components/script/layout_dom/node.rs]: Nit: suggestion small rename for a bit of clarity that probably have helped me when reading this.

```suggestion
    pub(crate) fn scope_match_a_selectors_string<Query>(
```

**Review by mrobinson — COMMENTED** [review]
Great stuff! Perhaps other want to look at this too.

File: components/script/layout_dom/element.rs (hunk 2 above)
Comment (simonwuelker) [reply components/script/layout_dom/element.rs:87]: The names `to_layout_js` and `from_layout_js` are used on other types of the layout DOM as well (`ServoShadowRoot`, `ServoLayoutDocument`, `ServoLayoutElement`) so I'd prefer to keep them consistent for now and then rename them all at once in a followup if that's okay with you.

File: components/script/layout_dom/node.rs (hunk 3 above)
Comment (simonwuelker) [reply components/script/layout_dom/node.rs:78]: As explained in my other comment (https://github.com/servo/servo/pull/42991#discussion_r2878899727) I'm happy to clean this part of the code up a bit, but I'd prefer to do so in a followup.

Comment (mrobinson) [reply components/script/layout_dom/node.rs:78]: Sure.

**Comment by jdm** [comment]
Note to self: check if #42976 triggers new asserts in this code.

File: components/script/layout_dom/node.rs (hunk 4 above)
Comment (simonwuelker) [reply components/script/layout_dom/node.rs]: I don't know for certain but from quickly glancing at the code it doesn't seem to use threads. The DOM node we pass to `query_selector` is also not required to implement `Send` or `Sync`

File: components/script/layout_dom/document.rs (hunk 5 above)
Comment (simonwuelker) [reply components/script/layout_dom/document.rs:50]: Sure. We already depend on `static_assertions` via stylo, so I'll use that.

Comment (simonwuelker) [reply components/script/layout_dom/document.rs:50]: Unfortunately that doesn't work because these types are generic and [`generic_const_exprs`](https://github.com/rust-lang/rust/issues/76560) is not stable yet.

**Comment by simonwuelker** [comment]
> Note to self: check if #42976 triggers new asserts in this code.

I've tested this and the new asserts do indeed trigger.  The call to `to_layout` fails because we're not in layout at that point - is `with_layout_state` (from #42976) a correct fix for that problem?

**Comment by jdm** [comment]
Yes, that should do it.

**Review by jdm — APPROVED** [review]

File: components/script/dom/bindings/root.rs (hunk 1 above)
Comment (simonwuelker) [reply components/script/dom/bindings/root.rs:110]: Nothing prevents someone from calling this method on a different thread in `script` though. `pub(crate)` doesn't really give us any safety guarantees.

`LayoutDom` itself is not `Send`. But its possible to wrap a `LayoutDom<Node>` in a `ServoLayoutNode` (safe) which is `Send`, then pass it to another thread (safe), call `get_jsmanaged` on it (safe) and then use `as_ref` to obtain a reference to the node. At that point we have multiple references to a non-sync value on diferent threads, so *something* we did has to be marked as `unsafe`. All the steps that exist so far are safe, so let's make `as_ref` unsafe.
