### PR TITLE
Dedupe syn, quote and unicode-xid

### LINKED ISSUE #19786: Update style-derive to syn 0.12
Potentially this could allow builds of servo on nightly to get the improved error messages and other semantics which come from the new span system and `proc-macro` APIs.

`synstructure` has been updated already, although the API has changed since the last version which style-derive used. If there are any APIs or new features which you need in `synstructure` to help port the derives over, let me know. Ideally I'd like to make the `cg` module in style-derive unnecessary, as the features you need are in `synstructure`.

cc @nox

### LINKED ISSUE #20497: Tracking issue for syn 0.13 + quote 0.5 in Servo and dependencies
Do avoid increasing the number versions of syn in Servo’s dependency graph, we should coordinate landing this in various repository at around the same time. So far:

* [x] https://github.com/servo/html5ever/pull/341
* [x] https://github.com/servo/rust-cssparser/pull/217
* [x] https://github.com/servo/string-cache/pull/203
* [x] FIXME: add other affected crates

Ideally, before anything is merged we should have a branch of Servo that uses `[patch.crates-io]` in the root `Cargo.toml` to use all of the relevant PR branches, and check that everything builds with minimal duplication (crates with the same name) in `Cargo.lock`.

### LINKED ISSUE #20609: Build error with custom Webrender
Trying to build Servo with custom Webrender and Webrender_Api results in 2 build errors. 

```
error[E0432]: unresolved import `webrender_api::ScrollEventPhase`
  --> components/compositing/compositor.rs:39:37
   |
39 | use webrender_api::{LayoutVector2D, ScrollEventPhase, ScrollLocation};
   |                                     ^^^^^^^^^^^^^^^^ no `ScrollEventPhase` in the root

error[E0204]: the trait `Copy` may not be implemented for this type
   --> components/compositing/compositor.rs:193:17
    |
193 | #[derive(Clone, Copy)]
    |                 ^^^^
...
202 |     phase: ScrollEventPhase,
    |     ----------------------- this field does not implement `Copy`

error: aborting due to 2 previous errors

```

Looks like `ScrollEventPhase` was removed in https://github.com/servo/webrender/pull/2629.

### PR DESCRIPTION
**Pull request by Eijebong**
Dupe num-traits instead...

Fixes #20609
Fixes #20497
Fixes #19786
Closes #20564

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20649)

### CODE REVIEW

**Comment by glennw** [comment]
This is the reftest diff for ```background-color-049.xht```. All the diffs I've looked at so far look similar.

The different black box below is drawn via the Ahem CSS testing font. If that's failing to load or using an incorrect glyph, that could explain the difference there. It seems that the missing text description glyphs in the sentences above are likely to be the same problem.

Test image:

screenshot_20180420_094341

Reference image:

screenshot_20180420_094404

**Comment by glennw** [comment]
OK, I fixed the shaping code to use the updated harfbuzz nominal glyph function. That appears to fix the issue above. Let's see what else is broken! :fearful: 

@bors-servo try

**Comment by glennw** [comment]
Updated test expectations with one new PASS.

@bors-servo try

**Comment by glennw** [comment]
Added another new PASS test update.

@bors-servo try

**Comment by glennw** [comment]
@Eijebong @nox OK, hopefully that fix and the two new PASS expectations have sorted out the reftest issues. The windows failure above is:

```
   Compiling malloc_size_of_derive v0.0.1 (file:///C:/buildbot/slave/windows-msvc-dev/build/components/malloc_size_of_derive)
error: failed to run custom build command for `cssparser v0.23.5`
process didn't exit successfully: `c:\buildbot\slave\windows-msvc-dev\build\target\geckolib\debug\build\cssparser-6590ed163f1f9625
```

I'm not sure if that's something network / intermittent or a genuine build error?

**Comment by glennw** [comment]
If there's any other reftest issues that I've missed from the logs, let me know!

**Comment by Eijebong** [comment]
@glennw That seems like the failure in #20564

File: components/gfx/text/shaping/harfbuzz.rs [hunk 1]
```diff
@@ -418,7 +418,7 @@ unsafe impl Sync for FontFuncs {}
 lazy_static! {
     static ref HB_FONT_FUNCS: FontFuncs = unsafe {
         let hb_funcs = hb_font_funcs_create();
-        hb_font_funcs_set_glyph_func(hb_funcs, Some(glyph_func), ptr::null_mut(), None);
+        hb_font_funcs_set_nominal_glyph_func(hb_funcs, Some(glyph_func), ptr::null_mut(), None);
```
Comment (khaledhosny) [inline components/gfx/text/shaping/harfbuzz.rs]: If you implement `nominal_glyph_func`, then you should also implement `variation_glyph_func`, otherwise you lose support for Unicode Variation Selectors.

**Comment by glennw** [comment]
@nox @Eijebong What's the status of this at the moment - do we know what the cause is / have a fix for the MSVC compile error?

File: components/gfx/text/shaping/harfbuzz.rs (hunk 1 above)
Comment (glennw) [reply components/gfx/text/shaping/harfbuzz.rs]: @khaledhosny Thanks for the info!

I know very little about harfbuzz - the old code that I am porting from ignored the variation parameter in the deprecated glyph callback function.

Does that mean that we weren't previously handling this case anyway? If that's the case we could land this first and do the variation changes as a separate piece of functionality if we're not already supporting it.

Or will this change mean we're losing some *existing* functionality?

Comment (khaledhosny) [reply components/gfx/text/shaping/harfbuzz.rs]: Sounds about right, old code didn’t handle it indeed.

**Comment by Eijebong** [comment]
@glennw We're not sure what's causing this but we're seeing stack overflows on both h5e and cssparser which are both using the same trick with syn. It might be that syn is just using more stack than before but it doesn't make any sense to me because we cannot reproduce it on any of our machines :(

**Comment by Eijebong** [comment]
@nox Since you took care of that, could you close the issues that were referenced in the original commit ?

**Comment by nox** [comment]
I closed the one that I actually fixed. Things are still duplicated, I only made the WR bump land.

**Comment by Eijebong** [comment]
@bors-servo try

Just want to be sure that it wasn't updating procedural-masquerade that fixed it

**Comment by Eijebong** [comment]
> {"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-011.html", "line": 39712, "action": "test_result", "expected": "PASS"}

Unrelated

**Comment by Eijebong** [comment]
@bors-servo try

Please work

**Comment by Eijebong** [comment]
@bors-servo try

Please be magically fixed

**Comment by SimonSapin** [comment]
@bors-servo r+

Thanks!
