### PR TITLE
Make name content attributes consistently atoms and put them in rare_data for fast access

### LINKED ISSUE #25570: Handle element names consistently
Some SetName methods are make_setter!, some are make_atomic_setter!, and HTMLIFrameElement has its own DomRefCell<DOMString> reflecting its name. This inconsistency is a contributing factor in #25057, and cleaning it up is necessary to make a #25548 that won't crash.

I had changed the Element parent class to make names atoms in #25548, reflecting them in rare_data for lookup speed, but I had neglected to consider the differences between different Element subclasses there, and now that I look at all the specific ways different elements use names, a sweep to unify them all seems to be in order.

### PR DESCRIPTION
**Pull request by pshaughn**
All codepaths setting the name content attribute now use an atom, which is also stored in rare_data for direct lookup by a get_name method. 

Paralleling the get_name method, I added a get_id method, which makes some internal id-lookup cases nicer.

A new test tests for a name setter on every HTML element type. In addition to its overt and upstreamable purpose of checking IDL property reflection semantics, for us this test also hits some Servo assertions that make sure the name is an atom in every case. If the test doesn't crash, even a failed test case still has the attribute as an atom rather than some other type. The failed cases are for elements that we have unimplemented or completely stubbed; I added a few missing name IDL properties to otherwise implemented elements.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #25570 and make progress on #25057

- [X] There are tests for these changes

### CODE REVIEW

**Comment by pshaughn** [comment]
I am sure this will have some idlharness test result changes, and I wouldn't be surprised if filling in the name setter has had other effects.
@bors-servo try=wpt

**Comment by pshaughn** [comment]
That one /css/css-transforms/animation/perspective-interpolation.html crash looks scary. Other new failures are probably because we were only "accidentally" passing before, but of course I'll have to look through them all to be sure.

**Comment by pshaughn** [comment]
Oh, I was reading upwards from the bottom and missed the known-intermittents header, that one test already has an intermittency issue filed for it. Now to look at all the real new failures...

**Comment by pshaughn** [comment]
Once I was reading the right part of the results, it was all new passes and completely consistent with what I changed. I notice the CI test harness does a better job of extracting results from a timed-out test than I get running on the command line; the _mozilla test I added is not actually necessary for CI purposes.

**Comment by pshaughn** [comment]
I believe this is ready to roll out.
@bors-servo try

**Comment by jdm** [comment]
That's #23290.

File: components/script/dom/element.rs [hunk 1]
```diff
@@ -1388,11 +1388,27 @@ impl Element {
...
         let name = &self.parsed_name(name);
-        self.attrs
+        let maybe_attribute = self
+            .attrs
             .borrow()
             .iter()
             .find(|a| a.name() == name)
-            .map(|js| DomRoot::from_ref(&**js))
+            .map(|js| DomRoot::from_ref(&**js));
+        fn id_and_name_must_be_atoms(name: &LocalName, maybe_attr: &Option<DomRoot<Attr>>) -> bool {
```
Comment (jdm) [inline components/script/dom/element.rs]: We probably need a `#[cfg(debug_assertions)]` to avoid warnings about an unused function in builds without them enabled.

**Review by jdm — APPROVED** [review]
Thanks for doing this work! I'm impressed by how many places ended up needing to be modified.

**Comment by jdm** [comment]
Sorry, I was wrong about how the debug_assert macro is treated by the compiler:
```
error[E0425]: cannot find function `id_and_name_must_be_atoms` in this scope
    --> components/script/dom/element.rs:1425:23
     |
1425 |         debug_assert!(id_and_name_must_be_atoms(name, &maybe_attribute));
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
```

**Comment by jdm** [comment]
This needs a `mach fmt`.

**Comment by pshaughn** [comment]
The spec sometimes explicitly excludes the empty-string from being a possible name and sometimes doesn't; there aren't WPT tests on the subject so I don't know what browsers do in various name="" cases, and empty-string handling here might not be great.

**Comment by pshaughn** [comment]
I don't know what that means but it sounds like something a rebase might fix.

**Comment by jdm** [comment]
@bors-servo r+
Yeah, those failures are mysterious :(
