### PR TITLE
indexeddb: Support enabling IndexedDB after startup

### LINKED ISSUE #39175: IndexedDB tests panic under servodriver
`./mach test-wpt /IndexedDB/abort-in-initial-upgradeneeded.any.html --headless --product servodriver`

```
pid:46328 called `Result::unwrap()` on an `Err` value: Io(Custom { kind: NotFound, error: SendInvalidDest }) (thread Script(1,4), at components/script/dom/idbopendbrequest.rs:292)
 0:06.20 pid:46328    0: backtrace::backtrace::libunwind::trace
 0:06.20 pid:46328              at /Users/jdm/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.75/src/backtrace/libunwind.rs:117:9
 0:06.20 pid:46328       backtrace::backtrace::trace_unsynchronized
 0:06.20 pid:46328              at /Users/jdm/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.75/src/backtrace/mod.rs:66:14
 0:06.20 pid:46328    1: <servoshell::backtrace::Print as core::fmt::Debug>::fmt
 0:06.20 pid:46328              at /Users/jdm/src/alt-servo/ports/servoshell/backtrace.rs:65:13
 0:06.21 pid:46328    2: core::fmt::rt::Argument::fmt
 0:06.21 pid:46328              at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/fmt/rt.rs:173:76
 0:06.21 pid:46328       core::fmt::write
 0:06.21 pid:46328              at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/fmt/mod.rs:1465:25
 0:06.22 pid:46328    3: std::io::default_write_fmt
 0:06.22 pid:46328              at /Users/jdm/.rustup/toolchains/1.89.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/io/mod.rs:639:11
 0:06.22 pid:46328    4: std::io::Write::write_fmt
 0:06.22 pid:46328              at /Users/jdm/.rustup/toolchains/1.89.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/io/mod.rs:1954:13
 0:06.22 pid:46328    5: servoshell::backtrace::print
 0:06.22 pid:46328              at /Users/jdm/src/alt-servo/ports/servoshell/backtrace.rs:18:5
 0:06.22 pid:46328    6: servoshell::panic_hook::panic_hook
 0:06.22 pid:46328              at /Users/jdm/src/alt-servo/ports/servoshell/panic_hook.rs:40:17
 0:06.24 pid:46328    7: core::ops::function::Fn::call
 0:06.24 pid:46328              at /Users/jdm/.rustup/toolchains/1.89.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:79:5
 0:06.27 pid:46328    8: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
 0:06.27 pid:46328              at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/alloc/src/boxed.rs:1980:9
 0:06.27 pid:46328       std::panicking::rust_panic_with_hook
 0:06.27 pid:46328              at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:841:13
 0:06.27 pid:46328    9: std::panicking::begin_panic_handler::{{closure}}
 0:06.27 pid:46328              at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:706:13
 0:06.27 pid:46328   10: std::sys::backtrace::__rust_end_short_backtrace
 0:06.27 pid:46328              at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/sys/backtrace.rs:168:18
 0:06.27 pid:46328   11: __rustc::rust_begin_unwind
 0:06.27 pid:46328              at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:697:5
 0:06.27 pid:46328   12: core::panicking::panic_fmt
 0:06.27 pid:46328              at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/panicking.rs:75:14
 0:06.27 pid:46328   13: core::result::unwrap_failed
 0:06.27 pid:46328              at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/result.rs:1761:5
 0:06.29 pid:46328   14: core::result::Result<T,E>::unwrap
 0:06.29 pid:46328              at /Users/jdm/.rustup/toolchains/1.89.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:1167:23
 0:06.29 pid:46328       script::dom::idbopendbrequest::IDBOpenDBRequest::open_database
 0:06.29 pid:46328              at /Users/jdm/src/alt-servo/components/script/dom/idbopendbrequest.rs:292:14
 0:06.33 pid:46328   15: <script::dom::idbfactory::IDBFactory as script_bindings::codegen::GenericBindings::IDBFactoryBinding::IDBFactory_Binding::IDBFactoryMethods<script::dom::bindings::codegen::DomTypeHolder::DomTypeHolder>>::Open
 0:06.33 pid:46328              at /Users/jdm/src/alt-servo/components/script/dom/idbfactory.rs:61:17
 0:06.35 pid:46328   16: script_bindings::codegen::GenericBindings::IDBFactoryBinding::IDBFactory_Binding::open::{{closure}}::{{closure}}
 0:06.35 pid:46328              at /Users/jdm/src/alt-servo/target/debug/build/script_bindings-fc6cd77d21b4544a/out/Bindings/IDBFactoryBinding.rs:165:72
 0:06.35 pid:46328   17: script_bindings::codegen::GenericBindings::IDBFactoryBinding::IDBFactory_Binding::open::{{closure}}
 0:06.35 pid:46328              at /Users/jdm/src/alt-servo/target/debug/build/script_bindings-fc6cd77d21b4544a/out/Bindings/IDBFactoryBinding.rs:125:33
 0:06.35 pid:46328   18: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
 0:06.35 pid:46328              at /Users/jdm/.rustup/toolchains/1.89.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:305:21
 0:06.35 pid:46328   19: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
 0:06.35 pid:46328              at /Users/jdm/.rustup/toolchains/1.89.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
 0:06.36 pid:46328   20: std::panicking::catch_unwind::do_call
 0:06.36 pid:46328              at /Users/jdm/.rustup/toolchains/1.89.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:589:40
 0:06.36 pid:46328   21: ___rust_try
 0:06.36 pid:46328   22: std::panicking::catch_unwind
 0:06.36 pid:46328              at /Users/jdm/.rustup/toolchains/1.89.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:552:19
 0:06.36 pid:46328       std::panic::catch_unwind
 0:06.36 pid:46328              at /Users/jdm/.rustup/toolchains/1.89.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:359:14
 0:06.36 pid:46328   23: mozjs::panic::wrap_panic
 0:06.36 pid:46328              at /Users/jdm/.cargo/git/checkouts/mozjs-dd2a25693c61d87d/af903e0/mozjs/src/panic.rs:22:11
 0:06.36 pid:46328   24: script_bindings::codegen::GenericBindings::IDBFactoryBinding::IDBFactory_Binding::open
 0:06.36 pid:46328              at /Users/jdm/src/alt-servo/target/debug/build/script_bindings-fc6cd77d21b4544a/out/Bindings/IDBFactoryBinding.rs:125:5
 0:06.39 pid:46328   25: CallJitMethodOp
 0:06.39 pid:46328              at /Users/runner/work/mozjs/mozjs/mozjs-sys/./src/jsglue.cpp:669:10
 0:06.41 pid:46328   26: script_bindings::utils::generic_call
 0:06.41 pid:46328              at /Users/jdm/src/alt-servo/components/script_bindings/utils.rs:405:5
 0:06.44 pid:46328   27: script_bindings::utils::generic_method
 0:06.44 pid:46328              at /Users/jdm/src/alt-servo/components/script_bindings/utils.rs:425:5
 0:06.44 pid:46328   28: __ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
 0:06.44 pid:46328   29: __ZN2js9InterpretEP9JSContextRNS_8RunStateE
 0:06.44 pid:46328   30: __ZN2js9RunScriptEP9JSContextRNS_8RunStateE
 0:06.44 pid:46328   31: __ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
 0:06.44 pid:46328   32: __ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
 0:06.44 pid:46328   33: __ZN2js9fun_applyEP9JSContextjPN2JS5ValueE
 0:06.44 pid:46328   34: __ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
 0:06.45 pid:46328   35: __ZN2js9InterpretEP9JSContextRNS_8RunStateE
 0:06.45 pid:46328   36: __ZN2js9RunScriptEP9JSContextRNS_8RunStateE
 0:06.45 pid:46328   37: __ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEENS3_IP8JSObjectEENS2_13MutableHandleINS2_5ValueEEE
 0:06.45 pid:46328   38: __Z16JS_ExecuteScriptP9JSContextN2JS6HandleIP8JSScriptEENS1_13MutableHandleINS1_5ValueEEE
 0:06.46 pid:46328   39: mozjs::rust::wrappers::JS_ExecuteScript
 0:06.46 pid:46328              at /Users/jdm/.cargo/git/checkouts/mozjs-dd2a25693c61d87d/af903e0/mozjs/src/rust.rs:1228:51
 0:06.49 pid:46328   40: script::dom::globalscope::GlobalScope::evaluate_script_on_global_with_result
 0:06.49 pid:46328              at /Users/jdm/src/alt-servo/components/script/dom/globalscope.rs:2886:26
 0:06.51 pid:46328   41: script::dom::html::htmlscriptelement::HTMLScriptElement::run_a_classic_script
 0:06.51 pid:46328              at /Users/jdm/src/alt-servo/components/script/dom/html/htmlscriptelement.rs:1110:14
 0:06.51 pid:46328   42: script::dom::html::htmlscriptelement::HTMLScriptElement::execute
 0:06.51 pid:46328              at /Users/jdm/src/alt-servo/components/script/dom/html/htmlscriptelement.rs:1061:22
 0:06.53 pid:46328   43: script::dom::servoparser::ServoParser::resume_with_pending_parsing_blocking_script
 0:06.53 pid:46328              at /Users/jdm/src/alt-servo/components/script/dom/servoparser/mod.rs:371:16
 0:06.55 pid:46328   44: script::dom::document::Document::process_pending_parsing_blocking_script
 0:06.55 pid:46328              at /Users/jdm/src/alt-servo/components/script/dom/document.rs:2238:18
 0:06.55 pid:46328   45: script::dom::document::Document::pending_parsing_blocking_script_loaded
 0:06.55 pid:46328              at /Users/jdm/src/alt-servo/components/script/dom/document.rs:2222:14
 0:06.55 pid:46328   46: script::dom::html::htmlscriptelement::finish_fetching_a_classic_script
 0:06.55 pid:46328              at /Users/jdm/src/alt-servo/components/script/dom/html/htmlscriptelement.rs:317:22
 0:06.55 pid:46328   47: <script::dom::html::htmlscriptelement::ClassicContext as net_traits::FetchResponseListener>::process_response_eof
 0:06.55 pid:46328              at /Users/jdm/src/alt-servo/components/script/dom/html/htmlscriptelement.rs:467:9
 0:06.57 pid:46328   48: <net_traits::FetchResponseMsg as net_traits::Action<T>>::process
 0:06.57 pid:46328              at /Users/jdm/src/alt-servo/components/shared/net/lib.rs:374:30
 0:06.59 pid:46328   49: <script::network_listener::ListenerTask<A,Listener> as script::task::TaskOnce>::run_once
 0:06.59 pid:46328              at /Users/jdm/src/alt-servo/components/script/network_listener.rs:118:25
 0:06.61 pid:46328   50: <script::task::CancellableTask<T> as script::task::TaskOnce>::run_once
 0:06.61 pid:46328              at /Users/jdm/src/alt-servo/components/script/task.rs:155:24
 0:06.61 pid:46328   51: <T as script::task::TaskBox>::run_box
 0:06.61 pid:46328              at /Users/jdm/src/alt-servo/components/script/task.rs:106:14
 0:06.63 pid:46328   52: script::script_thread::ScriptThread::handle_msg_from_script
 0:06.63 pid:46328              at /Users/jdm/src/alt-servo/components/script/script_thread.rs:2019:22
 0:06.63 pid:46328   53: script::script_thread::ScriptThread::handle_msgs::{{closure}}
 0:06.63 pid:46328              at /Users/jdm/src/alt-servo/components/script/script_thread.rs:1514:65
 0:06.63 pid:46328   54: script::script_thread::ScriptThread::profile_event
 0:06.63 pid:46328              at /Users/jdm/src/alt-servo/components/script/script_thread.rs:1736:13
 0:06.63 pid:46328   55: script::script_thread::ScriptThread::handle_msgs
 0:06.63 pid:46328              at /Users/jdm/src/alt-servo/components/script/script_thread.rs:1505:32
 0:06.63 pid:46328   56: script::script_thread::ScriptThread::start
 0:06.63 pid:46328              at /Users/jdm/src/alt-servo/components/script/script_thread.rs:1053:20
 0:06.63 pid:46328   57: <script::script_thread::ScriptThread as layout_api::ScriptThreadFactory>::create::{{closure}}::{{closure}}
 0:06.63 pid:46328              at /Users/jdm/src/alt-servo/components/script/script_thread.rs:444:39
 0:06.66 pid:46328   58: profile_traits::mem::ProfilerChan::run_with_memory_reporting
 0:06.66 pid:46328              at /Users/jdm/src/alt-servo/components/shared/profile/mem.rs:146:9
 0:06.66 pid:46328   59: <script::script_thread::ScriptThread as layout_api::ScriptThreadFactory>::create::{{closure}}
 0:06.66 pid:46328              at /Users/jdm/src/alt-servo/components/script/script_thread.rs:442:40
 0:06.67 pid:46328   60: std::sys::backtrace::__rust_begin_short_backtrace
 0:06.67 pid:46328              at /Users/jdm/.rustup/toolchains/1.89.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:152:18
 0:06.70 pid:46328   61: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
 0:06.70 pid:46328              at /Users/jdm/.rustup/toolchains/1.89.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/mod.rs:559:17
 0:06.72 pid:46328   62: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
 0:06.72 pid:46328              at /Users/jdm/.rustup/toolchains/1.89.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
 0:06.74 pid:46328   63: std::panicking::catch_unwind::do_call
 0:06.74 pid:46328              at /Users/jdm/.rustup/toolchains/1.89.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:589:40
 0:06.74 pid:46328   64: ___rust_try
 0:06.74 pid:46328   65: std::panicking::catch_unwind
 0:06.74 pid:46328              at /Users/jdm/.rustup/toolchains/1.89.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:552:19
 0:06.74 pid:46328       std::panic::catch_unwind
 0:06.74 pid:46328              at /Users/jdm/.rustup/toolchains/1.89.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:359:14
 0:06.74 pid:46328       std::thread::Builder::spawn_unchecked_::{{closure}}
 0:06.74 pid:46328              at /Users/jdm/.rustup/toolchains/1.89.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/mod.rs:557:30
 0:06.98 pid:46328   66: core::ops::function::FnOnce::call_once{{vtable.shim}}
 0:06.98 pid:46328              at /Users/jdm/.rustup/toolchains/1.89.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
 0:06.98 pid:46328   67: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
 0:06.98 pid:46328              at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/alloc/src/boxed.rs:1966:9
 0:06.98 pid:46328       std::sys::pal::unix::thread::Thread::new::thread_start
 0:06.98 pid:46328              at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/sys/pal/unix/thread.rs:107:17
 0:06.98 pid:46328   68: __pthread_deallocate
```

Blocks #34683.

### PR DESCRIPTION
**Pull request by jdm**
The servodriver harness requires preference-gated web platform features to be toggleable at any point in the browsing session's lifetime, rather than at startup. To support toggling IndexedDB, we need to ensure the IDB manager thread is always started.

Testing: Verified when running `./mach test-wpt /IndexedDB --headless --product servodriver`. We don't run servodriver in CI yet.
Fixes: #39175

### CODE REVIEW

File: components/net/indexeddb/idb_thread.rs [hunk 1]
```diff
@@ -224,9 +224,6 @@ impl IndexedDBManager {
 
 impl IndexedDBManager {
     fn start(&mut self) {
-        if !pref!(dom_indexeddb_enabled) {
```
Comment (yezhizhen) [inline components/net/indexeddb/idb_thread.rs:227]: Should we also remove `dom_indexeddb_enabled` from prefs.rs?

Comment (jdm) [reply components/net/indexeddb/idb_thread.rs:227]: Nope! It still controls whether the DOM interfaces are exposd to web content.

**Review by yezhizhen — APPROVED** [review]
