### PR TITLE
storage: Fix WebStorage SQLite writes until schema migration is implemented

### LINKED ISSUE #41299: Linux/Android/OHOS: localStorage is not local (does not persist after restart)
Prior issue: https://github.com/servo/servo/issues/35758

This had been fixed by [#35761](https://github.com/servo/servo/pull/35761), but was later happening again after https://github.com/servo/servo/pull/39653/, where we ported it from naive JSON to sqlite3.

cc @arihant2math

### PR DESCRIPTION
**Pull request by janvarga**
This PR fixes WebStorage SQLite writes by switching to `UPDATE` and `INSERT` as a
temporary fallback.

The previous `UPSERT` statement assumes a `UNIQUE` or `PRIMARY KEY` constraint
on `key`, which is not yet guaranteed by the current schema and causes write
failures. Using `UPDATE` and `INSERT` avoids this issue until a proper schema
migration is implemented.

A TODO is left to switch back to `UPSERT` once the schema is updated.

Testing: Manual testing only. This issue primarily manifests when the
application does not shut down cleanly (which is common on Android). In that
case, `save()` is not invoked and persistence relies entirely on `set()`,
making this difficult to reliably cover with automated tests.

Fixes: #41299

### CODE REVIEW

**Review by yezhizhen — COMMENTED** [review]
> Using INSERT OR REPLACE avoids this issue

Doesn't this also assume Unique/Primary key constraint? How is the behaviour different.

If key is not unique/primsry key, they both insert duplicate entries?

**Comment by janvarga** [comment]
Good catch, thanks for spotting this. I had overlooked that `INSERT OR REPLACE` has a problem too.

I’ve switched the implementation to a transactional `DELETE` and `INSERT`. That avoids schema migration or potentially losing existing data by creating a new table, even though that may not be a major concern in practice at the moment. I do think the schema should be revisited (for example, storing origin information as well), but that likely needs more discussion.

For now, I think this fallback is acceptable despite the performance cost. I’m also not entirely sure we still need the `save()` path in the long term, currently, it makes testing in unit tests problematic.

**Comment by janvarga** [comment]
We could also create a new non unique index for `key` column to improve perf, but as I said, it would be better to change the schema long term.

**Comment by janvarga** [comment]
Just to complete the picture, the current SQL in `set()` fails with:
`Parse error: ON CONFLICT clause does not match any PRIMARY KEY or UNIQUE constrain`

**Comment by janvarga** [comment]
There's also the option to execute `UPDATE` first and if that updates zero rows, execute `INSERT`:
`UPDATE data SET value = ? WHERE key = ?`
if affected_rows == 0 {
  `INSERT INTO data (key, value) VALUES (?, ?);`
}

I can rework it that way if you prefer that.

File: components/storage/webstorage/engines/sqlite.rs [hunk 1]
```diff
@@ -78,8 +78,10 @@ impl WebStorageEngine for SqliteEngine {
 
     fn set(&mut self, key: &str, value: &str) -> Result<(), Self::Error> {
         // update or insert
+        // TODO: Replace this with `ON CONFLICT(key) DO UPDATE` once the schema
+        // guarantees a UNIQUE/PRIMARY KEY constraint on `key`.
         self.connection.execute(
-            "INSERT INTO data (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value=excluded.value;",
+            "INSERT OR REPLACE INTO data (key, value) VALUES (?, ?);",
```
Comment (yezhizhen) [inline components/storage/webstorage/engines/sqlite.rs]: > This PR fixes WebStorage SQLite writes by switching to DELETE and INSERT as a
temporary fallback.

Btw, you are still using the old commit.

**Review by yezhizhen — CHANGES_REQUESTED** [review]

File: components/storage/webstorage/engines/sqlite.rs (hunk 1 above)
Comment (janvarga) [reply components/storage/webstorage/engines/sqlite.rs]: Force pushed the right one.

**Review by yezhizhen — APPROVED** [review]
> There's also the option to execute `UPDATE` first and if that updates zero rows, execute `INSERT`: `UPDATE data SET value = ? WHERE key = ?` if affected_rows == 0 { `INSERT INTO data (key, value) VALUES (?, ?);` }
> 
> I can rework it that way if you prefer that.

I like the alt better as it won't change `rowid` and probably more efficient.

**Comment by janvarga** [comment]
> I like the alt better as it won't change `rowid` and probably more efficient.

Ok, reworked.

**Review by yezhizhen — APPROVED** [review]
Thanks for the rework. I tested on the phone and it works!
