### PR TITLE
Prevent crashing when a link tag has two or more in-flight requests (fix for issue #15101)

### LINKED ISSUE #15101: <link> elements need to clear any previous stylesheet before loading a new one
assertion failed: self.stylesheet.borrow().is_none()
### Servo Version:
Servo 0.0.1-f010fb5
### Backtrace:
```

WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(0), index: FrameIndex(0) } iterated after closure.
WARNING: <Constellation>: Frame FrameId { namespace_id: PipelineNamespaceId(0), index: FrameIndex(0) } iterated after closure.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }>: stop_parsing not implemented, full speed ahead!
WARNING: <Constellation>: Pipeline (0,1) has no parent.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) }>: Message sent to closed pipeline (1,5).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) }>: Message sent to closed pipeline (1,5).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) }>: Message sent to closed pipeline (1,5).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) }>: Message sent to closed pipeline (1,5).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) }>: Message sent to closed pipeline (1,5).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) }>: Message sent to closed pipeline (1,5).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) }>: Message sent to closed pipeline (1,5).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) }>: Message sent to closed pipeline (1,5).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) }>: Message sent to closed pipeline (1,5).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) }>: Message sent to closed pipeline (1,5).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) }>: Message sent to closed pipeline (1,5).
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) }>: freeze sent to nonexistent pipeline
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: freeze sent to nonexistent pipeline
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(7) }>: stop_parsing not implemented, full speed ahead!
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(7) }>: Panic hook called.
ERROR: assertion failed: self.stylesheet.borrow().is_none()

stack backtrace:
   0:        0x10bfe70de - backtrace::backtrace::trace::hf62db13292993b7b
   1:        0x10bfe73ec - backtrace::capture::Backtrace::new::hd6fb6e83f9059b0d
   2:        0x10bf1f0f4 - constellation::constellation::log_entry::h19b052c781087594
   3:        0x10bf1e102 - <constellation::constellation::FromCompositorLogger as log::Log>::log::h36228ba81e93d85d
   4:        0x10cf38fc1 - log::__log::h2e9b720ead5e7b53
   5:        0x10b335660 - servo::main::{{closure}}::he0211114582e5524
   6:        0x10cf806e4 - std::panicking::rust_panic_with_hook::h33761bada49f3713
   7:        0x10b50e594 - std::panicking::begin_panic::h5871bdf0eba452a7
   8:        0x10baa2f8c - <script::stylesheet_loader::StylesheetContext as net_traits::FetchResponseListener>::process_response_eof::hbaa185f211e49eef
   9:        0x10ba50c3d - <script::network_listener::ListenerRunnable<A, Listener> as script::script_thread::Runnable>::handler::h0eac68b229ae0c48
  10:        0x10ba59272 - <script::script_thread::CancellableRunnable<T> as script::script_thread::Runnable>::handler::hb7e5f8f53abfd37a
  11:        0x10ba76f28 - script::script_thread::ScriptThread::handle_msg_from_script::hbe22e1fbcff75733
  12:        0x10ba6f695 - script::script_thread::ScriptThread::handle_msgs::{{closure}}::h994055b9195ea3dd
  13:        0x10ba6a925 - script::script_thread::ScriptThread::handle_msgs::h3e82c4a9be9c120b
  14:        0x10b562ae7 - std::panicking::try::do_call::h317093b315bfb0b1
  15:        0x10cf815fa - __rust_maybe_catch_panic
  16:        0x10b72b22a - <F as alloc::boxed::FnBox<A>>::call_box::he06e05fd65345e4b
  17:        0x10cf7f664 - std::sys::imp::thread::Thread::new::thread_start::he1b44499d44cc4a4
  18:     0x7fff9f3b0aaa - _pthread_body
  19:     0x7fff9f3b09f6 - _pthread_start
```
This report was generated by the browser.html issue reporter.

### PR DESCRIPTION
**Pull request by SwagColoredKitteh**
The `HTMLLinkElement::set_stylesheet` function now checks whether there already is a stylesheet, and if there is, calls `Document::invalidate_stylesheets` after modifying `self.stylesheet`.

This PR also includes a minimal WPT that causes the panic.

This is fundamentally a timing issue, so while this fix prevents the crash, it does not fix the underlying issue. Making a &lt;link&gt; element send a second request before the first can finish and then getting the two stylesheet responses out-of-order will apply the wrong stylesheet, as demonstrated with https://gist.github.com/SwagColoredKitteh/2c24c7fac635445042eda4a30e10420e.

r? @emilio

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15101 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15145)

### CODE REVIEW

**Comment by jdm** [comment]
The way we handle the timing issue in other code like XMLHttpRequest is to store a monotonically-increasing id in the element and the network load context, and compare them in the implementation of PreInvoke.

**Comment by SwagColoredKitteh** [comment]
Alright, should I add that to this PR? Is there also a way to write a WPT that checks for these out-of-order responses?

**Comment by jdm** [comment]
You could write a test that first loads a resource that has a [3 second response delay](http://wptserve.readthedocs.io/en/latest/pipes.html#trickle), then immediately loads a second one with no delay, then waits for 4 seconds and queries the computed style of an element that would be affected.

File: components/script/dom/htmllinkelement.rs [hunk 1]
```diff
@@ -79,11 +79,16 @@ impl HTMLLinkElement {
     }
 
     pub fn set_stylesheet(&self, s: Arc<Stylesheet>) {
-        assert!(self.stylesheet.borrow().is_none());
-        *self.stylesheet.borrow_mut() = Some(s);
+        let mut sheet = self.stylesheet.borrow_mut();
+        let must_invalidate = sheet.is_some();
```
Comment (emilio) [inline components/script/dom/htmllinkelement.rs]: I think we don't need to call `invalidate_stylesheets` here, since the stylesheet loader will do it right after calling `set_stylesheet`.

Remove this code and maybe add a note about it?

**Review by emilio — CHANGES_REQUESTED** [review]

File: components/script/dom/htmllinkelement.rs (hunk 1 above)
Comment (SwagColoredKitteh) [inline components/script/dom/htmllinkelement.rs]: It might be better to just leave the assert there as it is and do what @jdm suggested, which would fix the underlying issue instead of clear the symptoms. That assert will continue to be useful to find timing issues such as what caused this issue in the first place.

Comment (emilio) [inline components/script/dom/htmllinkelement.rs]: Note that we still need to support setting a stylesheet when it is loaded and the href changes, or at least (probably preferably?) add support for unsetting it and `invalidate_stylesheets` after the href changes.

So yeah, let's keep the assertion there, let's add the load counter, and also let's move this `must_invalidate` logic to `handle_stylesheet_url`, and unset the stylesheet there.

**Comment by SwagColoredKitteh** [comment]
Did what @jdm suggested, out-of-order stylesheet responses for the same element should be handled correctly now. There are also 2 tests which verify that this works correctly. These tests do time out, even though they should not, though. Added exceptions for those timeouts in the inis files.

**Comment by jdm** [comment]
#15159 was filed for followup investigation into the timeouts.

File: components/script/dom/htmllinkelement.rs [hunk 2]
```diff
@@ -37,6 +37,15 @@ use stylesheet_loader::{StylesheetLoader, StylesheetContextSource, StylesheetOwn
 
 unsafe_no_jsmanaged_fields!(Stylesheet);
 
+#[derive(JSTraceable, PartialEq, Clone, Copy, HeapSizeOf)]
+pub struct GenerationId(u32);
```
Comment (emilio) [inline components/script/dom/htmllinkelement.rs]: nit: Maybe `RequestGenerationId`?

File: components/script/stylesheet_loader.rs [hunk 3]
```diff
@@ -85,9 +85,21 @@ pub struct StylesheetContext {
...
+    /// A token which must match the generation id of the `HTMLLinkElement` for it to load the stylesheet.
+    generation_id: GenerationId,
 }
 
-impl PreInvoke for StylesheetContext {}
+impl PreInvoke for StylesheetContext {
+    fn should_invoke(&self) -> bool {
+        // We must first check whether the generations of the context and the element match up,
+        // else we risk applying the wrong stylesheet when responses come out-of-order.
+        let gen = self.elem.root()
```
Comment (emilio) [inline components/script/stylesheet_loader.rs]: We should invoke the callback always, just not set the stylesheet if the generation doesn't match. Otherwise we will lose track of the pending load count, which means we'll never fire the load event.

Comment (emilio) [inline components/script/stylesheet_loader.rs]: Also, `elem` may be a `<style>` element where there's an `@import`, or the load could be for an `@import` rule in general, in which case the generation id doesn't matter. So we should do the check in `process_response_eof`, an we should check that `StylesheetContextSource` is a `LinkElement`.

Note that the imports can theoretically have the same race if mutated from CSSOM before the load finishes, but we don't expose that right now to the web, so it can't happen, so no need to worry about this in this PR.

File: components/script/stylesheet_loader.rs [hunk 4]
```diff
@@ -215,13 +227,17 @@ impl<'a> StylesheetLoader<'a> {
                 integrity_metadata: String) {
         let url = source.url();
         let document = document_from_node(self.elem);
+        let gen = self.elem.downcast::<HTMLLinkElement>()
```
Comment (emilio) [inline components/script/stylesheet_loader.rs]: Similarly, you can't rely on this being a `HTMLLinkElement`.

**Review by emilio — CHANGES_REQUESTED** [review]

File: components/script/stylesheet_loader.rs (hunk 3 above)
Comment (emilio) [inline components/script/stylesheet_loader.rs]: Actually, the above comment may be the reason why the tests timeout :)

**Comment by SwagColoredKitteh** [comment]
Fixed issue #15159 and made sure that style elements with imports do not crash servo by not assuming that some downcasts always succeed, also did a few cleanups.

File: components/script/stylesheet_loader.rs [hunk 5]
```diff
@@ -143,24 +146,32 @@ impl FetchResponseListener for StylesheetContext {
...
-                                                        media.take().unwrap(),
-                                                        Some(&loader),
-                                                        win.css_error_reporter(),
-                                                        ParserContextExtraData::default()));
-                    if elem.downcast::<HTMLLinkElement>().unwrap().is_alternate() {
-                        sheet.set_disabled(true);
+                    let link = elem.downcast::<HTMLLinkElement>().unwrap();
+                    // We must first check whether the generations of the context and the element match up,
+                    // else we risk applying the wrong stylesheet when responses come out-of-order.
+                    let should_continue = match self.request_generation_id {
```
Comment (emilio) [inline components/script/stylesheet_loader.rs]: let's give this variable a meaningful name, something like:

```rust
let is_applicable_stylesheet_load =
    self.request_generation_id.map_or(true, |id| id == link.get_request_generation_id());
```

(or other name if you want, I'm pretty bad at it :))

File: components/script/stylesheet_loader.rs [hunk 6]
```diff
@@ -143,24 +146,32 @@ impl FetchResponseListener for StylesheetContext {
...
+                        Some(gen) => gen == link.get_request_generation_id(),
+                        None      => true,
```
Comment (emilio) [inline components/script/stylesheet_loader.rs]: nit: I don't think we use to indent fat arrows visually. In any case, you may be able to write this in a more compact way with `map_or`, as I did above.

**Review by emilio — APPROVED** [review]
Looks great! I have one minor request, after that this is good to go :)

Thanks for fixing this @SwagColoredKitteh!

**Comment by emilio** [comment]
Also, travis seems to be complaining about the manifest order, you need to fix that I think: etc/ci/manifest_changed.sh

**Comment by emilio** [comment]
@bors-servo r+

Thanks for doing this! :)

**Comment by SwagColoredKitteh** [comment]
@emilio My pleasure! I had a lot of fun searching around the codebase and figuring out what went wrong. :D
