### PR TITLE
Default is top-to-bottom if unset, not bottom-to-top

### LINKED ISSUE #14745: Gradients render in the wrong direction
Notice the `Sign Up` and `Sign up for GitHub` buttoms.

Servo:
screen shot 2016-12-27 at 4 04 41 pm
Firefox:
screen shot 2016-12-27 at 4 05 53 pm

### PR DESCRIPTION
**Pull request by DominoTree**
Reverse linear gradient direction if not explicitly specified to match expected default behavior

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #14745 (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14746)

### CODE REVIEW

**Comment by cbrewster** [comment]
Could we add a ref test for this?

**Comment by DominoTree** [comment]
Yeah, I can add a test

**Comment by DominoTree** [comment]
I added a test, it required a bit of boilerplate, not sure if we should put it into a macro or something.

**Comment by cbrewster** [comment]
Here is how to add a new reftest: https://github.com/servo/servo/tree/master/tests/wpt#writing-new-tests

File: tests/unit/style/parsing/image.rs [hunk 1]
```diff
@@ -32,6 +38,12 @@ fn test_linear_gradient() {
 
     // Parsing without <angle> and <side-or-corner>
     assert_roundtrip_with_context!(Image::parse, "linear-gradient(red, green)");
+
+    // AngleOrCorner::None should become AngleOrCorner::Angle(Angle(PI)) when parsed
```
Comment (shinglyu) [inline tests/unit/style/parsing/image.rs]: Maybe add a link to the spec in the comment. Or at least make clear that `PI` means "top-to-bottom". :)

**Review by shinglyu — CHANGES_REQUESTED** [review]

**Comment by shinglyu** [comment]
For the reftest, you can create two htmls, the test html could be a gradient box with the default, the reference html can be a gradient box that was explicitly set as `to bottom`. The two should render exactly the same.

To begin with, you can put the test in `tests/wpt/mozilla/tests/css`, these are servo-specific tests that are hard or impossible to upstream. But later you might want to upstream that to wpt and pull the new wpt test into servo.

**Comment by KiChjang** [comment]
Pulling from upstream WPT should really only be done by @Ms2ger or @jgraham. Please wait for them to update WPT when you have submitted and merged tests upstream.

**Comment by DominoTree** [comment]
Added reftests to existing linear-gradient parsing tests in `tests/wpt/mozilla/tests/css`

**Comment by emilio** [comment]
Looks great to me, thanks.

@bors-servo r+

**Comment by jdm** [comment]
@bors-servo: retry
* #14323
