### PR TITLE
Fix supports rule parsing issues with <any-value>

### LINKED ISSUE #15482: Various issues around conditions for syntax accepted by @supports
[This can be tested with `alert(CSS.supports(cond));`]

There are several issues:
* It rejects `!important` when the property is a shorthand. e.g. `(background: none !important)` returns false, but it should return true.
* It incorrectly accepts conditions without parens. There are several cases which it returns true while it should return false:
  * `(color: green) and (color: green) or (color: green)` - correct form is `((color: green) and (color: green)) or (color: green)`
  * `not (color: rainbow) and not (color: iridescent)` - correct form is `(not (color: rainbow)) and (not (color: iridescent))`
  * <del>`color: green` - correct form is `(color: green)`</del> (This is a Gecko issue)

Spec: https://drafts.csswg.org/css-conditional-3/#at-supports

(Servo also accepts unbalanced brackets inside the condition, which Gecko doesn't accept, but Blink accepts. This is probably a question to the spec.)

### PR DESCRIPTION
**Pull request by upsuper**
This eventually fixes #15482, as well as several reftests in mozilla-central which were added for [bug 883987](https://bugzilla.mozilla.org/show_bug.cgi?id=883987).

The new function should probably be moved into cssparser crate at some point.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17792)

### CODE REVIEW

File: components/style/stylesheets/supports_rule.rs [hunk 1]
```diff
@@ -125,21 +125,18 @@ impl SupportsCondition {
...
                     })
                 })
             }
-            Token::Function(_) => {
-                let result: Result<_, ParseError> = input.parse_nested_block(|i| Ok(consume_all(i)));
-                result.unwrap();
-                Ok(SupportsCondition::FutureSyntax(input.slice_from(pos).to_owned()))
+            Token::Function(name) => {
+                let content = input.parse_nested_block(|i| parse_any_value(i))?;
+                Ok(SupportsCondition::FutureSyntax(format!("{}({})", name, content)))
```
Comment (SimonSapin) [inline components/style/stylesheets/supports_rule.rs]: This needs to use `serialize_identifier` for the function name. Why not keep using `slice_from` with a wider range, though?

Comment (upsuper) [inline components/style/stylesheets/supports_rule.rs]: hmm, I thought it would be useful to have a `parse_any_value` returning the value parsed... but yeah, probably in this case it is better to just keep using `slice_from` in the callsites.

**Comment by upsuper** [comment]
@SimonSapin updated

File: components/style/stylesheets/supports_rule.rs [hunk 2]
```diff
@@ -129,20 +129,16 @@ impl SupportsCondition {
         match input.next()? {
             Token::ParenthesisBlock => {
                 input.parse_nested_block(|input| {
-                    // `input.try()` not needed here since the alternative uses `consume_all()`.
-                    parse_condition_or_declaration(input).or_else(|_| {
-                        consume_all(input);
-                        Ok(SupportsCondition::FutureSyntax(input.slice_from(pos).to_owned()))
-                    })
-                })
+                    input.try(|i| parse_condition_or_declaration(i).map(|_| ()))
```
Comment (SimonSapin) [inline components/style/stylesheets/supports_rule.rs]: `.map(|_| ())` here drops a `SupportsCondition::Parenthesized` or `SupportsCondition::Declaration`, and replaces it with `()` that is eventually replaced with `SupportsCondition::FutureSyntax`. Is that the desired behavior?

Comment (upsuper) [inline components/style/stylesheets/supports_rule.rs]: No. Fixed...

**Comment by SimonSapin** [comment]
Thanks!

@bors-servo r+
