### PR TITLE
Don't run scripts while DOM tree is undergoing mutations

### LINKED ISSUE #34465: Crash on m.baidu.com: Attempt to use script or layout while DOM not in a stable state
**Describe the bug:**

Backtrace:
```
assertion `left == right` failed: Attempt to use script or layout while DOM not in a stable state
  left: 1
 right: 0 (thread Script(1,1), at components/script/dom/document.rs:3559)
   0: trace
             at /Users/jschwender/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.74/src/backtrace/libunwind.rs:116:5
      trace_unsynchronized<servoshell::backtrace::{impl#0}::fmt::{closure_env#1}>
             at /Users/jschwender/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.74/src/backtrace/mod.rs:66:5
      fmt
             at /Users/jschwender/Dev/servo/ports/servoshell/backtrace.rs:65:13
   1: core::fmt::rt::Argument::fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/fmt/rt.rs:165:63
      core::fmt::write
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/fmt/mod.rs:1168:21
   2: write_fmt<std::io::stdio::StderrLock>
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/io/mod.rs:1835:15
   3: print
             at /Users/jschwender/Dev/servo/ports/servoshell/backtrace.rs:18:5
   4: panic_hook
             at /Users/jschwender/Dev/servo/ports/servoshell/panic_hook.rs:40:17
   5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/alloc/src/boxed.rs:2077:9
      std::panicking::rust_panic_with_hook
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:799:13
   6: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:664:13
   7: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:171:18
   8: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   9: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
  10: core::panicking::assert_failed_inner
  11: assert_failed<u32, u32>
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:363:5
  12: ensure_safe_to_run_script_or_layout
             at /Users/jschwender/Dev/servo/components/script/dom/document.rs:3559:9
      reflow
             at /Users/jschwender/Dev/servo/components/script/dom/window.rs:1978:9
  13: layout_reflow
             at /Users/jschwender/Dev/servo/components/script/dom/window.rs:2083:9
      resolved_style_query
             at /Users/jschwender/Dev/servo/components/script/dom/window.rs:2186:13
  14: script::dom::cssstyledeclaration::CSSStyleDeclaration::get_property_value
  15: GetPropertyValue
             at /Users/jschwender/Dev/servo/components/script/dom/cssstyledeclaration.rs:408:9
  16: {closure#0}
             at /Users/jschwender/Dev/servo/target/medium/build/script-b2037f917b00edfe/out/Bindings/CSSStyleDeclarationBinding.rs:231:33
      {closure#0}
             at /Users/jschwender/Dev/servo/target/medium/build/script-b2037f917b00edfe/out/Bindings/CSSStyleDeclarationBinding.rs:211:33
  17: call_once<(), dyn core::ops::function::FnMut<(), Output=()>>
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:305:13
      call_once<(), &mut dyn core::ops::function::FnMut<(), Output=()>>
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panic/unwind_safe.rs:272:9
      do_call<core::panic::unwind_safe::AssertUnwindSafe<&mut dyn core::ops::function::FnMut<(), Output=()>>, ()>
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:559:40
      try<(), core::panic::unwind_safe::AssertUnwindSafe<&mut dyn core::ops::function::FnMut<(), Output=()>>>
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:523:19
      catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<&mut dyn core::ops::function::FnMut<(), Output=()>>, ()>
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panic.rs:149:14
      wrap_panic
             at /Users/jschwender/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/18ab014/mozjs/src/panic.rs:22:11
  18: getPropertyValue
             at /Users/jschwender/Dev/servo/target/medium/build/script-b2037f917b00edfe/out/Bindings/CSSStyleDeclarationBinding.rs:211:5
  19: CallJitMethodOp
             at /Users/runner/work/mozjs/mozjs/mozjs-sys/src/jsglue.cpp:642:10
  20: generic_call<false>
             at /Users/jschwender/Dev/servo/components/script/dom/bindings/utils.rs:524:5
  21: __ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  22: __ZN2js9InterpretEP9JSContextRNS_8RunStateE
  23: __ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  24: __ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  25: __ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
  26: __ZN2js3jit14InvokeFunctionEP9JSContextN2JS6HandleIP8JSObjectEEbbjPNS3_5ValueENS3_13MutableHandleIS8_EE
  27: __ZN2js3jit25InvokeFromInterpreterStubEP9JSContextPNS0_30InterpreterStubExitFrameLayoutE
[2024-12-03T10:47:31Z ERROR servoshell::panic_hook] assertion `left == right` failed: Attempt to use script or layout while DOM not in a stable state
      left: 1
     right: 0

```

**To Reproduce:**
`./mach run https://m.baidu.com`

**Platform:**
Tested on OpenHarmony, MacOS and Linux.

### PR DESCRIPTION
**Pull request by jdm**
When manipulating the DOM tree we always want web content to only see stable states after any mutations are applied. We introduced script/layout blockers in https://github.com/servo/servo/commit/14b0de30dbf90793c3b6c9017e4c65df9281c5ae to catch cases where an unstable DOM could be exposed to web content, and this PR addresses several cases where the conditions were violated.

First, we introduce a new virtual method that elements can hook—the [post-connection steps](https://dom.spec.whatwg.org/#concept-node-post-connection-ext). These are executed after all DOM mutations are finished, so it's safe to execute scirpts from them. `children_changed`'s execution time is less well-defined, but we can use `add_delayed_task` to ensure that the script executes ASAP once the DOM mutations have stabilized, which avoids any observable behaviour changes.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #34465
- [x] There are tests for these changes

### CODE REVIEW

**Comment by jdm** [comment]
Given https://github.com/whatwg/html/issues/10828 I think the new failures will be addressed by moving the iframe element's bind_to_tree logic to post_connected_steps instead.

**Comment by jdm** [comment]
This is finally ready for review.

File: components/script/dom/htmlscriptelement.rs [hunk 1]
```diff
@@ -1188,25 +1188,29 @@ impl VirtualMethods for HTMLScriptElement {
...
         }
-        if !self.parser_inserted.get() && self.upcast::<Node>().is_connected() {
-            self.prepare(CanGc::note());
+
+        if self.upcast::<Node>().is_connected() && !self.parser_inserted.get() {
+            let script = Trusted::new(self);
+            document_from_node(self).add_delayed_task(task!(ScriptPrepare: move || {
+                let this = script.root();
+                this.prepare(CanGc::note());
+            }));
```
Comment (simonwuelker) [inline components/script/dom/htmlscriptelement.rs:1202]: Without the context of this PR it is not immediately obvious why `add_delayed_task` is used here (the spec says to execute the post-connection steps immediately), maybe add a short comment explaining why its necessary.

**Review by simonwuelker — APPROVED** [review]
