### PR TITLE
Fix a crash in WebGPU when WebGPU is disabled

### LINKED ISSUE #30843: Crash in WebGPU with WebGPU disabled
https://thorium.rocks/misc/webgpu-test/ crashes when WebGPU is disabled

```
Failed to get WebGPU channel: Disconnected (thread Script(1,1), at components/script/dom/htmlcanvaselement.rs:273)
   0: servo::backtrace::print
             at /home/user/Desktop/servo/ports/servoshell/backtrace.rs:18:5
   1: servo::main2::main::{{closure}}
             at /home/user/Desktop/servo/ports/servoshell/main2.rs:101:21
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2021:9
      std::panicking::rust_panic_with_hook
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:735:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:609:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
   5: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   6: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   7: core::result::unwrap_failed
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1652:5
   8: core::result::Result<T,E>::expect
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1034:23
   9: script::dom::htmlcanvaselement::HTMLCanvasElement::get_or_init_webgpu_context
             at /home/user/Desktop/servo/components/script/dom/htmlcanvaselement.rs:273:23
  10: <script::dom::htmlcanvaselement::HTMLCanvasElement as script::dom::bindings::codegen::Bindings::HTMLCanvasElementBinding::HTMLCanvasElement_Binding::HTMLCanvasElementMethods>::GetContext
             at /home/user/Desktop/servo/components/script/dom/htmlcanvaselement.rs:377:25
  11: script::dom::bindings::codegen::Bindings::HTMLCanvasElementBinding::HTMLCanvasElement_Binding::getContext::{{closure}}::{{closure}}
             at /home/user/Desktop/servo/target/debug/build/script-041747a9d657cdf5/out/Bindings/HTMLCanvasElementBinding.rs:792:133
  12: script::dom::bindings::codegen::Bindings::HTMLCanvasElementBinding::HTMLCanvasElement_Binding::getContext::{{closure}}
             at /home/user/Desktop/servo/target/debug/build/script-041747a9d657cdf5/out/Bindings/HTMLCanvasElementBinding.rs:767:33
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:305:13
  14: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panic/unwind_safe.rs:271:9
  15: std::panicking::try::do_call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  16: __rust_try
  17: std::panicking::try
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  18: std::panic::catch_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
  19: mozjs::panic::wrap_panic
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs/src/panic.rs:22:11
  20: script::dom::bindings::codegen::Bindings::HTMLCanvasElementBinding::HTMLCanvasElement_Binding::getContext
             at /home/user/Desktop/servo/target/debug/build/script-041747a9d657cdf5/out/Bindings/HTMLCanvasElementBinding.rs:767:5
  21: CallJitMethodOp
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs/src/jsglue.cpp:623:10
  22: script::dom::bindings::utils::generic_call
             at /home/user/Desktop/servo/components/script/dom/bindings/utils.rs:529:5
  23: script::dom::bindings::utils::generic_method
             at /home/user/Desktop/servo/components/script/dom/bindings/utils.rs:545:5
  24: _Z12CallJSNativeP9JSContextPFbS0_jPN2JS5ValueEEN2js10CallReasonERKNS1_8CallArgsE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:486:13
      _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:580:12
  25: _ZL12InternalCallP9JSContextRKN2js13AnyInvokeArgsENS1_10CallReasonE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:647:10
      _ZN2js13CallFromStackEP9JSContextRKN2JS8CallArgsENS_10CallReasonE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:652:10
      _ZN2js9InterpretEP9JSContextRNS_8RunStateE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:3395:16
  26: _ZL31MaybeEnterInterpreterTrampolineP9JSContextRN2js8RunStateE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:400:10
      _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:458:13
  27: _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEENS3_IP8JSObjectEENS_16AbstractFramePtrENS2_13MutableHandleINS2_5ValueEEE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:845:13
      _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEENS3_IP8JSObjectEENS2_13MutableHandleINS2_5ValueEEE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:877:10
  28: _ZN2js12ModuleObject7executeEP9JSContextN2JS6HandleIPS0_EE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/builtin/ModuleObject.cpp:1284:10
  29: _ZL21InnerModuleEvaluationP9JSContextN2JS6HandleIPN2js12ModuleObjectEEENS1_13MutableHandleINS1_8GCVectorIS5_Lm0ENS3_17SystemAllocPolicyEEEEEmPm
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Modules.cpp:1498:10
  30: _ZN2js14ModuleEvaluateEP9JSContextN2JS6HandleIPNS_12ModuleObjectEEENS2_13MutableHandleINS2_5ValueEEE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Modules.cpp:1284:13
  31: script::script_module::ModuleTree::execute_module
             at /home/user/Desktop/servo/components/script/script_module.rs:510:22
  32: script::dom::htmlscriptelement::HTMLScriptElement::run_a_module_script
             at /home/user/Desktop/servo/components/script/dom/htmlscriptelement.rs:1120:21
  33: script::dom::htmlscriptelement::HTMLScriptElement::execute
             at /home/user/Desktop/servo/components/script/dom/htmlscriptelement.rs:1032:17
  34: script::dom::document::Document::process_deferred_scripts
             at /home/user/Desktop/servo/components/script/dom/document.rs:2523:17
  35: script::dom::document::Document::deferred_script_loaded
             at /home/user/Desktop/servo/components/script/dom/document.rs:2508:9
  36: script::script_module::ModuleOwner::notify_owner_to_finish
             at /home/user/Desktop/servo/components/script/script_module.rs:933:21
  37: script::script_module::ModuleTree::append_handler::{{closure}}
             at /home/user/Desktop/servo/components/script/script_module.rs:349:21
  38: <script::script_module::ModuleTree::append_handler::fetched_resolve<F> as script::task::TaskOnce>::run_once
             at /home/user/Desktop/servo/components/script/task.rs:24:17
  39: <T as script::task::TaskBox>::run_box
             at /home/user/Desktop/servo/components/script/task.rs:57:9
  40: <script::script_module::ModuleHandler as script::dom::promisenativehandler::Callback>::callback
             at /home/user/Desktop/servo/components/script/script_module.rs:868:9
  41: script::dom::promisenativehandler::PromiseNativeHandler::callback
             at /home/user/Desktop/servo/components/script/dom/promisenativehandler.rs:53:13
  42: script::dom::promisenativehandler::PromiseNativeHandler::resolved_callback
             at /home/user/Desktop/servo/components/script/dom/promisenativehandler.rs:58:9
  43: script::dom::promise::native_handler_callback
             at /home/user/Desktop/servo/components/script/dom/promise.rs:311:56
  44: _Z12CallJSNativeP9JSContextPFbS0_jPN2JS5ValueEEN2js10CallReasonERKNS1_8CallArgsE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:486:13
      _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:580:12
  45: _ZL12InternalCallP9JSContextRKN2js13AnyInvokeArgsENS1_10CallReasonE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:647:10
      _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:679:8
  46: _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_S5_NS2_13MutableHandleIS4_EE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Interpreter.h:116:10
      _ZL18PromiseReactionJobP9JSContextjPN2JS5ValueE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/builtin/Promise.cpp:2244:10
  47: _Z12CallJSNativeP9JSContextPFbS0_jPN2JS5ValueEEN2js10CallReasonERKNS1_8CallArgsE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:486:13
      _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:580:12
  48: _ZL12InternalCallP9JSContextRKN2js13AnyInvokeArgsENS1_10CallReasonE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:647:10
      _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:679:8
  49: _Z20JS_CallFunctionValueP9JSContextN2JS6HandleIP8JSObjectEENS2_INS1_5ValueEEERKNS1_16HandleValueArrayENS1_13MutableHandleIS6_EE
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs-sys/mozjs/js/src/vm/CallAndConstruct.cpp:53:10
  50: mozjs::rust::wrappers::JS_CallFunctionValue
             at /home/user/.cargo/git/checkouts/mozjs-0f28a5f34a8f25e0/47ca02c/mozjs/src/rust.rs:1080:51
  51: script::dom::bindings::codegen::Bindings::PromiseBinding::PromiseJobCallback::Call
             at /home/user/Desktop/servo/target/debug/build/script-041747a9d657cdf5/out/Bindings/PromiseBinding.rs:321:18
  52: script::dom::bindings::codegen::Bindings::PromiseBinding::PromiseJobCallback::Call_
             at /home/user/Desktop/servo/target/debug/build/script-041747a9d657cdf5/out/Bindings/PromiseBinding.rs:305:18
  53: script::microtask::MicrotaskQueue::checkpoint
             at /home/user/Desktop/servo/components/script/microtask.rs:118:37
  54: script::script_thread::ScriptThread::perform_a_microtask_checkpoint
             at /home/user/Desktop/servo/components/script/script_thread.rs:4044:13
  55: script::script_thread::ScriptThread::handle_msgs
             at /home/user/Desktop/servo/components/script/script_thread.rs:1675:13
  56: script::script_thread::ScriptThread::start
             at /home/user/Desktop/servo/components/script/script_thread.rs:1448:15
  57: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}::{{closure}}
             at /home/user/Desktop/servo/components/script/script_thread.rs:842:25
  58: profile_traits::mem::ProfilerChan::run_with_memory_reporting
             at /home/user/Desktop/servo/components/shared/profile/mem.rs:91:9
  59: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}
             at /home/user/Desktop/servo/components/script/script_thread.rs:840:17
  60: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:154:18
  61: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:529:17
  62: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panic/unwind_safe.rs:271:9
  63: std::panicking::try::do_call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  64: __rust_try
  65: std::panicking::try
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  66: std::panic::catch_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:528:30
  67: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
  68: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys/unix/thread.rs:108:17
  69: start_thread
             at ./nptl/pthread_create.c:444:8
  70: __GI___clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
[2023-12-08T12:56:01Z ERROR servo::main2] Failed to get WebGPU channel: Disconnected
[2023-12-08T12:56:01Z ERROR script::dom::bindings::error] Error at :0:0 uncaught exception: undefined
```

### PR DESCRIPTION
**Pull request by lucasMontenegro**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #30843

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

File: components/constellation/constellation.rs [hunk 1]
```diff
@@ -2043,42 +2043,37 @@ where
...
-            FromScriptMsg::RequestAdapter(response_sender, options, ids) => {
-                let adapter_request = WebGPURequest::RequestAdapter {
-                    sender: response_sender,
-                    options,
-                    ids,
-                };
-                if webgpu_chan.0.send((None, adapter_request)).is_err() {
-                    return warn!("Failed to send request adapter message on WebGPU channel");
-                }
+            FromScriptMsg::RequestAdapter(response_sender, options, ids) => match webgpu_chan {
```
Comment (gterzian) [inline components/constellation/constellation.rs:2065]: So in this PR you want to update not the handling of this message, but of the `FromScriptMsg::GetWebGPUChan` below. 

Updating this message too would be a nice follow-up actually. You could open an issue, and then a PR for it too.

**Review by gterzian — CHANGES_REQUESTED** [review]
Thanks for your contribution!

File: components/constellation/constellation.rs (hunk 1 above)
Comment (lucasMontenegro) [reply components/constellation/constellation.rs:2065]: So, I'm not allowed to change the handling of `FromScriptMsg::RequestAdapter` ??  I don't think I can do that and get it to compile.

Comment (gterzian) [reply components/constellation/constellation.rs:2065]: Ah yes, I see what you mean, and actually the other message handling doesn't need to change because the option can be passed through as is... thanks for pointing it out!

File: components/constellation/constellation.rs [hunk 2]
```diff
@@ -2043,42 +2043,37 @@ where
...
+                None => warn!("Failed to send request adapter message, missing WebGPU channel"),
```
Comment (gterzian) [inline components/constellation/constellation.rs:2066]: Filed a follow-up https://github.com/servo/servo/issues/30895

**Review by gterzian — APPROVED** [review]
LGTM, thanks for the contrib!

**Comment by lucasMontenegro** [comment]
Thank you @gterzian 🥳🎉

**Comment by gterzian** [comment]
@lucasMontenegro You're welcome. We have a zullip chat by the way, in case you have any question: https://servo.zulipchat.com/
