### PR TITLE
compositor: Do not wait for animation termination to take screenshots

### LINKED ISSUE #36931: WPT Reftest related to Infinite Animations always Timeout
**Describe the bug:**
Some Reftest related to CSS Animation / Image Animation is suffering from Timeout. As stated in https://github.com/servo/servo/pull/36286#issuecomment-2864964960, this is because servo will wait for animations to be finished before it will take a screenshot. Below is a list of WPT Test that is having the same cause.

- /css/css-animations/
  - animate-with-background-color-oklch-001.html
  - animation-delay-008.html
  - animation-delay-009.html
  - animation-offscreen-to-onscreen.html
  - animation-opacity-pause-and-set-time.html
  - animation-transform-pause-and-set-time.html
  - display-none-to-display-block.html
  - flip-running-animation-via-variable.html
  - jump-start-animation-before-phase.html
- /html/semantics/embedded-content/the-img-element/animated-image-update.tentative.html

**To Reproduce:**
build servo and run the above listed wpt tests with `./mach test-wpt ....`

### PR DESCRIPTION
**Pull request by mrobinson**
WPT tests are expected to create screenshots as soon as everything is
loaded. If an animation is happening adding the "reftest-wait" class to
the root element is appropriate way to delay the screenshot. Previously, the
test harness was waiting for all animations to finish, but that is just
leading to many timeouts. Removing that code fixes the timeouts.

Two Servo-specific tests are also updated as they were written with
Servo's previous behavior in mind.

Testing: There are test result updates for this change. Many TIMEOUTS now either correctly
PASS OR FAIL.
Fixes: #36931.

### CODE REVIEW

File: components/compositing/compositor.rs [hunk 1]
```diff
@@ -1424,13 +1412,13 @@ impl IOCompositor {
...
 
         if opts::get().wait_for_stable_image {
-            // The current image may be ready to output. However, if there are animations active,
-            // continue waiting for the image output to be stable AND all active animations to complete.
-            if self.animations_or_animation_callbacks_running() {
-                return Err(UnableToComposite::NotReadyToPaintImage(
-                    NotReadyToPaint::AnimationsActive,
-                ));
-            }
+            //// The current image may be ready to output. However, if there are animations active,
```
Comment (jdm) [inline components/compositing/compositor.rs]: Can we remove this code instead?

**Review by jdm — APPROVED** [review]

File: components/compositing/compositor.rs (hunk 1 above)
Comment (mrobinson) [reply components/compositing/compositor.rs]: Oh, yes. 🤦 Sorry. This is definitely not what I meant to do.
