### PR TITLE
Remove failure breaks from webgpu thread

### LINKED ISSUE #32621: webgpu thread exits if requestDevice/requestAdapter fails
The main loop is `break`ed at:

https://github.com/servo/servo/blob/a730469b704878da9b484b0018f369438ce08851/components/webgpu/wgpu_thread.rs#L635

https://github.com/servo/servo/blob/a730469b704878da9b484b0018f369438ce08851/components/webgpu/wgpu_thread.rs#L688

### PR DESCRIPTION
**Pull request by sagudev**
Only breaking of main loop for thread exit is allowed.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #32621

- [x] There are tests for these changes in WebGPU CTS

### CODE REVIEW

**Comment by sagudev** [comment]
there are failures in `webgpu:api,operation,adapter,requestDevice:limit,out_of_range:*`, but before it was timeout, so it's still improvement. We need to raise TypeError in some cases of errors instead of only OperationError, but that will be done as a follow up, as we also need to get wgpu errors on js side (wgpu errors need to be serializable, there is already PR in wgpu for that).

File: components/webgpu/wgpu_thread.rs [hunk 1]
```diff
@@ -694,10 +694,6 @@ impl WGPU {
                             })
                             .map_err(|e| e.to_string());
 
-                        if response.is_err() {
-                            break;
-                        }
-
```
Comment (mrobinson) [inline components/webgpu/wgpu_thread.rs:700]: Would it make sense to match this error response and `warn!()` as we do when the send immediately following it fails?

**Review by mrobinson — APPROVED** [review]

File: components/webgpu/wgpu_thread.rs (hunk 1 above)
Comment (sagudev) [reply components/webgpu/wgpu_thread.rs:700]: No, because we send the error (or Ok(...)) to script (dom), where error get's handled (promise reject), while IPC errors does not get handled at all (apart from printing warning).
