### PR TITLE
Moved Canvas rendering to a single thread.

### LINKED ISSUE #13879: Crash trying to view http://slither.io/
I tried the latest Servo nightly build on Fedora. When I go to http://slither.io/ , I get:

called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } } (thread CanvasThread, at ../src/libcore/result.rs:799)
called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } } (thread Constellation, at ../src/libcore/result.rs:799)
ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }
ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }
called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } } (thread CanvasThread, at ../src/libcore/result.rs:799)
ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }
called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } } (thread CanvasThread, at ../src/libcore/result.rs:799)
called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } } (thread CanvasThread, at ../src/libcore/result.rs:799)
ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }
ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } } (thread CanvasThread, at ../src/libcore/result.rs:799)

ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }
called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } } (thread CanvasThread, at ../src/libcore/result.rs:799)
ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }
called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } }) (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }, at ../src/libcore/result.rs:799)
ERROR:servo: called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })
called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 104, message: "Connection reset by peer" } } (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }, at ../src/libcore/result.rs:799)
ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 104, message: "Connection reset by peer" } }
thread panicked while panicking. aborting.
Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }"
stack backtrace:
   0:     0x564defdcb22d - backtrace::backtrace::trace::h6ac07ced1b846a59
   1:     0x564defdcb8b2 - backtrace::capture::Backtrace::new::h1d3339ed08c7f861
   2:     0x564deea56084 - servo::install_crash_handler::handler::hbcbca0a8e3e6b31d
   3:     0x7f4fd768e76f - <unknown>
   4:     0x564df04b6440 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:     0x564df04b6282 - std::panicking::begin_panic::hf6c488cee66e7f17
   6:     0x564df04b61c0 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   7:     0x564df04b6141 - rust_begin_unwind
   8:     0x564df04f295f - core::panicking::panic_fmt::h9af671b78898cdba
   9:     0x564def00f590 - core::result::unwrap_failed::h3ea0c9548cd89371
  10:     0x564def025884 - drop::h7183d462065227d2
  11:     0x564df04bea06 - __rust_maybe_catch_panic
  12:     0x564def36523f - script::dom::bindings::codegen::Bindings::CanvasRenderingContext2DBinding::CanvasRenderingContext2DBinding::_finalize::hdef3933267ad4772
  13:     0x564def95373c - _ZNK2js5Class10doFinalizeEPNS_6FreeOpEP8JSObject
                        at /home/servo/buildbot/slave/linux-nightly/build/target/release/build/mozjs_sys-661d4efe7c7ca939/out/dist/include/js/Class.h:815
                         - 8JSObject8finalizeEPN2js6FreeOp
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsobjinlines.h:85
                         - _ZN2js2gc5Arena8finalizeI8JSObjectEEmPNS_6FreeOpENS0_9AllocKindEm
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsgc.cpp:447
  14:     0x564def930eda - FinalizeTypedArenas<JSObject>
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsgc.cpp:505
  15:     0x564def93307a - FinalizeArenas
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsgc.cpp:539
  16:     0x564def933cb0 - 2js2gc10ArenaLists16forceFinalizeNowEPNS_6FreeOpENS0_9AllocKindENS1_14KeepArenasEnumEPPNS0_5Arena
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsgc.cpp:2720
  17:     0x564def933de6 - 2js2gc10ArenaLists11finalizeNowEPNS_6FreeOpENS0_9AllocKindENS1_14KeepArenasEnumEPPNS0_5Arena
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsgc.cpp:2702
                         - 2js2gc10ArenaLists30queueForegroundObjectsForSweepEPNS_6FreeOp
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsgc.cpp:2839
  18:     0x564def93eb66 - 2js2gc9GCRuntime22beginSweepingZoneGroupERNS_26AutoLockForExclusiveAccess
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsgc.cpp:5127
  19:     0x564def942ad3 - 2js2gc9GCRuntime15beginSweepPhaseEbRNS_26AutoLockForExclusiveAccess
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsgc.cpp:5215
  20:     0x564def944766 - 2js2gc9GCRuntime23incrementalCollectSliceERNS_11SliceBudgetEN2JS8gcreason6ReasonERNS_26AutoLockForExclusiveAccess
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsgc.cpp:5937
  21:     0x564def94543f - 2js2gc9GCRuntime7gcCycleEbRNS_11SliceBudgetEN2JS8gcreason6Reason
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsgc.cpp:6174
  22:     0x564def945831 - 2js2gc9GCRuntime7collectEbNS_11SliceBudgetEN2JS8gcreason6Reason
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsgc.cpp:6287
  23:     0x564def945b20 - 2js2gc9GCRuntime2gcE18JSGCInvocationKindN2JS8gcreason6Reason
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsgc.cpp:6354
  24:     0x564defa648a5 - _ZN9JSRuntime14destroyRuntimeEv
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/vm/Runtime.cpp:430
  25:     0x564def8f954c - _ZN9JSContextD2Ev
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscntxt.cpp:892
  26:     0x564def8f9b71 - js_delete_poison<JSContext>
                        at /home/servo/buildbot/slave/linux-nightly/build/target/release/build/mozjs_sys-661d4efe7c7ca939/out/dist/include/js/Utility.h:392
                         - _ZN2js14DestroyContextEP9JSContext
                        at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscntxt.cpp:133
  27:     0x564deee23861 - drop_contents::h00b5aac0381269ef
  28:     0x564deeee46fa - std::panicking::try::do_call::h61045ac6c938f9b9
  29:     0x564df04bea06 - __rust_maybe_catch_panic
  30:     0x564def044a44 - _<F as alloc..boxed..FnBox<A>>::call_box::h901e0ed8b85ec2e2
  31:     0x564df04b4a00 - std::sys::thread::Thread::new::thread_start::h50b05608a499d2b2
  32:     0x7f4fd7c3a5c9 - start_thread
  33:     0x7f4fd775cf6c - __clone
  34:                0x0 - <unknown>
Illegal instruction (core dumped)

### PR DESCRIPTION
**Pull request by Brody-Eastwood**
Implements the "Subsequent Steps" part of the [NCSU Canvas rendering project.](https://github.com/servo/servo/wiki/Canvas-rendering-project)

I moved most of the functionality from CanvasPaintThread to CanvasData, so CanvasPaintThread essentially just pulls the info out of the message and calls a method on a particular CanvasData element. 

I ran into some awkwardness with the fact that one can only take a single mutable reference from a hashmap, though. DrawImageInOther is not really possible to do with only one reference at a time, so it awkwardly still lives in CanvasPaintThread, basically. I also would've preferred to take the reference at the top as soon as I get the CanvasId, since that looks cleaner than having them all start with "canvas_paint_thread.canvases.get_mut[&canvas_id].unwrap()" but that makes trying to take the second reference for DrawImageInOther fail to compile. I'm definitely open to suggestions on how to make that less gross.

The timed single-canvas drawing improved in performance from around ~2.2ms to around ~1.7ms. Slither.io runs better and doesn't crash, but I'm not having it crash on my copy from before these changes, so I don't know if that's new behavior or not.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach build-geckolib` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13879 and #10381.

- [X] There are tests for these changes (added in the initial steps)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20680)

### CODE REVIEW

File: components/canvas/canvas_data.rs [hunk 1]
```diff
@@ -0,0 +1,969 @@
...
+    /// An old webrender image key that can be deleted when the next epoch ends.
+    old_image_key: Option<webrender_api::ImageKey>,
+    /// An old webrender image key that can be deleted when the current epoch ends.
+    very_old_image_key: Option<webrender_api::ImageKey>,
+    pub canvas_id: CanvasId,
+}
+
+impl<'a> CanvasData<'a> {
+    pub fn new(size: Size2D<i32>,
+           webrender_api_sender: webrender_api::RenderApiSender,
```
Comment (emilio) [inline components/canvas/canvas_data.rs]: nit: Indentation is odd here.

File: components/canvas/canvas_data.rs [hunk 2]
```diff
@@ -0,0 +1,969 @@
...
+            webrender_api: webrender_api,
+            image_key: None,
+            old_image_key: None,
+            very_old_image_key: None,
+            canvas_id: canvas_id,
+        }
+    }
+
+    pub fn draw_image(&self, image_data: Vec<u8>, image_size: Size2D<f64>,
+                  dest_rect: Rect<f64>, source_rect: Rect<f64>,
```
Comment (emilio) [inline components/canvas/canvas_data.rs]: nit: And here.

File: components/canvas/canvas_data.rs [hunk 3]
```diff
@@ -0,0 +1,969 @@
...
+    }
+
+    pub fn quadratic_curve_to(&self,
+                          cp: &Point2D<AzFloat>,
+                          endpoint: &Point2D<AzFloat>) {
+        self.path_builder.quadratic_curve_to(cp, endpoint)
+    }
+
+    pub fn bezier_curve_to(&self,
+                       cp1: &Point2D<AzFloat>,
```
Comment (emilio) [inline components/canvas/canvas_data.rs]: And in a bunch of these, please format them using the common style:

```rust
pub fn bezier_curve_to(
    &self,
    cp1: &Point2D<AzFloat>,
    // ...
) {
```

File: components/canvas/canvas_data.rs [hunk 4]
```diff
@@ -0,0 +1,969 @@
...
+    pub fn set_global_composition(&mut self, op: CompositionOrBlending) {
+        self.state.draw_options.set_composition_op(op.to_azure_style());
+    }
+
+    pub fn create(size: Size2D<i32>) -> DrawTarget {
+        DrawTarget::new(BackendType::Skia, size, SurfaceFormat::B8G8R8A8)
+    }
+
+    pub fn recreate(&mut self, size: Size2D<i32>) {
+        // TODO: clear the thread state. https://github.com/servo/servo/issues/17533
```
Comment (emilio) [inline components/canvas/canvas_data.rs]: This probably needs a different comment now?

File: components/canvas/canvas_paint_thread.rs [hunk 5]
```diff
@@ -2,1137 +2,279 @@
...
+                            CanvasMsg::Create(creator, size, webrenderer_api_sender, antialias) => {
+                                let canvas_id = canvas_paint_thread.create_canvas(
+                                    size,
+                                    webrenderer_api_sender,
+                                    antialias
+                                );
+                                creator.send(canvas_id).unwrap();
+                            },
+                            CanvasMsg::Recreate(size, canvas_id) =>{
+                                canvas_paint_thread.canvases.get_mut(&canvas_id).unwrap().recreate(size);
```
Comment (emilio) [inline components/canvas/canvas_paint_thread.rs]: nit: `[&canvas_id]` instead of `get_mut(..).unwrap()` should be nicer and give a better error message.

File: components/constellation/constellation.rs [hunk 6]
```diff
@@ -2286,11 +2286,18 @@ impl<Message, LTF, STF> Constellation<Message, LTF, STF>
...
-                                              opts::get().enable_canvas_antialiasing, self.canvas_id.clone());
-        if let Err(e) = response_sender.send((sender, self.canvas_id.clone())) {
+        let sender = self.canvas_chan.clone();
+        let (canvas_id_sender, canvas_id_receiver) = ipc::channel::<CanvasId>().unwrap();
+
+        sender.send(CanvasMsg::Create(canvas_id_sender,
+                                      *size,
+                                      webrender_api,
+                                      opts::get().enable_canvas_antialiasing
+                                      )).unwrap();
```
Comment (emilio) [inline components/constellation/constellation.rs]: nit: Indentation here looks weird too.

**Review by emilio — COMMENTED** [review]
Looks good overall, though I haven't looked into a lot of the details yet. Thanks for working on this!

Probably it would've been nice to split the patch so that code moves are split from the rest... Otherwise is harder to review :(

File: components/canvas/canvas_paint_thread.rs (hunk 5 above)
Comment (Brody-Eastwood) [reply components/canvas/canvas_paint_thread.rs]: I wanted to do that, but I got error `error[E0596] : cannot borrow immutable indexed content as mutable`

Once you said that, I tried seeing if it would work now that I'm not pulling out a local reference, but it still did it.

I do agree that the way I did it is ugly, though.

File: components/canvas/canvas_data.rs (hunk 4 above)
Comment (Brody-Eastwood) [reply components/canvas/canvas_data.rs]: Oh. I didn't even really look at the code I was moving. Looking at that issue, it seems like it was fixed last year and the comment snuck its way back in. Should I just remove it?

File: components/canvas/canvas_data.rs (hunk 3 above)
Comment (Brody-Eastwood) [reply components/canvas/canvas_data.rs]: Thanks, I wasn't quite sure what the common style was since it was kinda inconsistent. I'm more than happy to move all this over to that, though.

**Comment by Brody-Eastwood** [comment]
Oh. For the first part, Josh had us squash all the commits, and we had a really hard time with it, so I just decided to do it in one commit from the beginning this time. Didn't think about how it would look while reviewing.

Also, it looks like the builds that failed are because I call unwrap in constellation. I'm going to fix the rest of the stuff later today, but I've gone ahead and pushed a fix to that so that we can see if the rest of it succeeds.

**Comment by SimonSapin** [comment]
Thanks for your PR. I’m attending a three-day training until Wednesday so I may take a while to review, sorry about that.

Regarding squashing commits, it’s a balance. You might make many commits while initially working on and debugging something, and keeping every one of those is not necessarily useful. But if a piece of work (that still belongs in the same PR) can be split into separate logical steps (preferably where intermediate steps compile and pass tests), it can be meaningful to make separate commits for those. (In particular, keeping moves to another file separate from another change makes smaller diffs.) That can be done after the fact by editing commit history (for example with `git rebase -i`) but if it’s difficult don’t worry about it too much.

**Comment by Brody-Eastwood** [comment]
I don't think I'd be able to edit the history into making the move separate from the changes anymore. They blur together pretty hard now.

I've pushed edits that address the indentation problems emilio mentioned (but I haven't done anything about the hash map awkwardness or the weird comment because of the reasons in those replies).

File: components/canvas/canvas_paint_thread.rs (hunk 5 above)
Comment (emilio) [reply components/canvas/canvas_paint_thread.rs]: Ah, right... what about a `canvas_paint_thread.canvas(canvas_id)` function, which internally does:

```rust
self.canvases.get_mut(&canvas_id).expect("Bogus canvas id")
```

That should avoid some of the ugliness.

File: components/canvas/canvas_data.rs (hunk 4 above)
Comment (Brody-Eastwood) [reply components/canvas/canvas_data.rs]: Ended up deciding to just remove it. I looked back at the issue and it has been closed since last July (also the code immediately below it does what it says it needs to do). Pretty sure that comment just snuck back in at some point. Just pushed that alongside the hashmap changes.

File: components/canvas/canvas_paint_thread.rs (hunk 5 above)
Comment (Brody-Eastwood) [reply components/canvas/canvas_paint_thread.rs]: Done. Thanks for the idea, that looks dramatically better. Pushed it alongside removing the outdated comment.

File: components/canvas/canvas_paint_thread.rs [hunk 7]
```diff
@@ -2,1137 +2,280 @@
...
+                    dest_rect,
+                    source_rect,
+                    smoothing_enabled,
+                )
+            },
+            Canvas2dMsg::DrawImageSelf(
+                    image_size,
+                    dest_rect,
+                    source_rect,
+                    smoothing_enabled
```
Comment (emilio) [inline components/canvas/canvas_paint_thread.rs]: nit: indentation.

File: components/canvas_traits/canvas.rs [hunk 8]
```diff
@@ -16,12 +16,13 @@ pub enum FillRule {
     Evenodd,
 }
 
-#[derive(Clone, Deserialize, MallocSizeOf, PartialEq, Serialize)]
+#[derive(Clone, Deserialize, Eq, Hash, MallocSizeOf, PartialEq, Serialize)]
```
Comment (emilio) [inline components/canvas_traits/canvas.rs]: nit: derive `Copy`? It's just a number anyway. That allows its users more flexibility.

File: components/canvas/canvas_paint_thread.rs [hunk 9]
```diff
@@ -2,1137 +2,280 @@
...
-
-impl ToAzureStyle for RGBA {
-    type Target = Color;
 
-    fn to_azure_style(self) -> Color {
-        Color::rgba(self.red_f32() as AzFloat,
-                    self.green_f32() as AzFloat,
-                    self.blue_f32() as AzFloat,
-                    self.alpha_f32() as AzFloat)
+    fn canvas(&mut self, canvas_id: &CanvasId) -> &mut CanvasData<'a> {
```
Comment (emilio) [inline components/canvas/canvas_paint_thread.rs]: If you make `CanvasId` copy, you don't need to add references to avoid `clone()`, which would read nicer IMO.

File: components/canvas/canvas_paint_thread.rs [hunk 10]
```diff
@@ -2,1137 +2,280 @@
...
+        self.canvases.get_mut(&canvas_id).expect("Bogus canvas id")
```
Comment (emilio) [inline components/canvas/canvas_paint_thread.rs]: Otherwise, this `&` isn't necessary.

File: components/canvas/canvas_paint_thread.rs [hunk 11]
```diff
@@ -2,1137 +2,280 @@
...
+            },
+            Canvas2dMsg::DrawImageInOther(
+                    other_canvas_id,
+                    image_size,
+                    dest_rect,
+                    source_rect,
+                    smoothing
+            ) => {
+                let mut image_data = self.canvas(&canvas_id).read_pixels(
+                            source_rect.to_i32(),
```
Comment (emilio) [inline components/canvas/canvas_paint_thread.rs]: nit: indentation here looks borked to.

File: components/script/dom/canvasrenderingcontext2d.rs [hunk 12]
```diff
@@ -371,20 +371,17 @@ impl CanvasRenderingContext2D {
...
             let msg = CanvasMsg::Canvas2d(Canvas2dMsg::DrawImageInOther(
-                self.ipc_renderer.clone(),
                 self.get_canvas_id(),
                 image_size,
                 dest_rect,
                 source_rect,
-                smoothing_enabled,
-                sender),
+                smoothing_enabled
+                ),
```
Comment (emilio) [inline components/script/dom/canvasrenderingcontext2d.rs]: nit: This paren looks somewhat out of place. Either move the `DrawImageInOther(..` to the next line and indent the argumetns, or put this paren on the previous level and do `), context.get_canvas_id());`. Though not a terrible fan of that one :)

**Review by emilio — APPROVED** [review]
Alright, this looks great to me with those comments addressed, this looks like a great step in the right direction, thanks so much for working on this!

@SimonSapin, hopefully you don't mind me stealing the review, if you want to chime in please do :)

File: components/script/dom/canvasrenderingcontext2d.rs (hunk 12 above)
Comment (Brody-Eastwood) [reply components/script/dom/canvasrenderingcontext2d.rs]: Went with the first option.

File: components/canvas_traits/canvas.rs (hunk 8 above)
Comment (Brody-Eastwood) [reply components/canvas_traits/canvas.rs]: Done.

File: components/canvas/canvas_paint_thread.rs (hunk 9 above)
Comment (Brody-Eastwood) [reply components/canvas/canvas_paint_thread.rs]: Also done.

File: components/canvas/canvas_paint_thread.rs (hunk 7 above)
Comment (Brody-Eastwood) [reply components/canvas/canvas_paint_thread.rs]: I totally know how I missed that one. Mixed it up with the next block. Fixed.

File: components/canvas/canvas_paint_thread.rs (hunk 11 above)
Comment (Brody-Eastwood) [reply components/canvas/canvas_paint_thread.rs]: Ditto. Fixed.

**Comment by Brody-Eastwood** [comment]
Just pushed the changes to those last few nits.

**Comment by emilio** [comment]
@bors-servo r+

Thank you!
