### PR TITLE
servoshell: Revert #38307 to fix resize bug

### LINKED ISSUE #38369: Resizing servoshell stretches things in weird ways
https://github.com/user-attachments/assets/0122fc3b-3cef-4400-8a59-20b73a819962

### PR DESCRIPTION
**Pull request by yezhizhen**
Also added some comments to make things clear.
For details, see https://github.com/servo/servo/issues/38369#issuecomment-3138378527

Testing: Tested on X11 Ubuntu, Wayland Ubuntu, macOS, Windows.
Fixes: #38369

Co-authored-by: minghuaw <michael.wu1107@gmail.com>

### CODE REVIEW

File: ports/servoshell/desktop/minibrowser.rs [hunk 1]
```diff
@@ -409,6 +409,8 @@ impl Minibrowser {
                 let rect = Box2D::from_origin_and_size(Point2D::origin(), size);
                 if rect != webview.rect() {
                     webview.move_resize(rect);
+                    // rect right now is just viewport size, which is required by `OffscreenRenderingContext`
+                    // See https://github.com/servo/servo/issues/38369#issuecomment-3138378527
```
Comment (mrobinson) [inline ports/servoshell/desktop/minibrowser.rs]:
```suggestion
                    // `rect` is sized to just the WebView viewport, which is required by 
                    // `OffscreenRenderingContext` See:
                    // <https://github.com/servo/servo/issues/38369#issuecomment-3138378527>
```

**Review by mrobinson — APPROVED** [review]

**Comment by yezhizhen** [comment]
Just repushed as there was an additional space from suggestions failing the Lint.
