### PR TITLE
Correctly paint the CSS canvas’ background

### LINKED ISSUE #25559: Root element background extents are wrong in layout_2020
It looks like root element background extents aren't including page margins and don't cover the page viewport.

This shows a white page:
```
<body style="background: green;"></body>
```

This shows a green page with 8 pixel white borders on the top and right:
```
<body style="background: green;">
    <div style="height: 10000px;"></div>
</body>
```

This shows a completely green page. This is what I would expect for all test cases:
```
<body style="background: green;">
    <div style="height: 10000px;"></div>
</body>
```

### LINKED ISSUE #26444: Panic on wikipedia page
Loading https://en.wikipedia.org/wiki/Section_20A in layout-2020 panics:
```
called `Option::unwrap()` on a `None` value (thread StyleThread#1, at /Users/joshmatthews/src/servo-tmp/components/layout_2020/dom_traversal.rs:451)
   0: backtrace::backtrace::trace_unsynchronized
   1: <servo::backtrace::Print as core::fmt::Debug>::fmt
   2: core::fmt::write
   3: std::io::Write::write_fmt
   4: servo::backtrace::print
   5: servo::main::{{closure}}
   6: std::panicking::rust_panic_with_hook
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::panicking::panic
  10: core::option::Option<T>::unwrap
  11: <T as layout::dom_traversal::NodeExt>::layout_data_mut
  12: <T as layout::dom_traversal::NodeExt>::unset_boxes_in_subtree
  13: layout::dom_traversal::traverse_element
  14: layout::dom_traversal::traverse_children_of
  15: layout::dom_traversal::NonReplacedContents::traverse
  16: layout::flow::construct::<impl layout::flow::BlockContainer>::construct
  17: layout::flow::construct::IntermediateBlockContainer::finish
  18: layout::flow::construct::BlockLevelJob<Node>::finish
  19: layout::flow::construct::<impl layout::flow::BlockContainer>::construct::{{closure}}
  20: <rayon_croissant::consumer::MapfoldReduceFolder<Accumulator,Mapfold,OutputConsumer> as rayon::iter::plumbing::Folder<Input>>::consume
  21: rayon::iter::plumbing::Folder::consume_iter
  22: rayon::iter::plumbing::Producer::fold_with
  23: rayon::iter::plumbing::bridge_producer_consumer::helper
  24: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
  25: rayon_core::join::join_context::call_b::{{closure}}
  26: rayon_core::job::StackJob<L,F,R>::run_inline
  27: rayon_core::join::join_context::{{closure}}
  28: rayon_core::registry::in_worker
  29: rayon_core::join::join_context
  30: rayon::iter::plumbing::bridge_producer_consumer::helper
  31: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
  32: rayon_core::join::join_context::call_b::{{closure}}
  33: rayon_core::job::StackJob<L,F,R>::run_inline
  34: rayon_core::join::join_context::{{closure}}
  35: rayon_core::registry::in_worker
  36: rayon_core::join::join_context
  37: rayon::iter::plumbing::bridge_producer_consumer::helper
  38: rayon::iter::plumbing::bridge_producer_consumer
  39: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
  40: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
  41: rayon::iter::plumbing::bridge
  42: <rayon::vec::IntoIter<T> as rayon::iter::ParallelIterator>::drive_unindexed
  43: <rayon_croissant::MapfoldReduce<Accumulator,Input,Mapfold,Init,Reduce> as rayon::iter::ParallelIterator>::drive_unindexed
  44: rayon::iter::collect::special_extend
  45: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
  46: rayon::iter::from_par_iter::collect_extended
  47: rayon::iter::from_par_iter::<impl rayon::iter::FromParallelIterator<T> for alloc::vec::Vec<T>>::from_par_iter
  48: rayon::iter::ParallelIterator::collect
  49: layout::flow::construct::<impl layout::flow::BlockContainer>::construct
  50: layout::flow::construct::IntermediateBlockContainer::finish
  51: layout::flow::construct::BlockLevelJob<Node>::finish
  52: layout::flow::construct::<impl layout::flow::BlockContainer>::construct::{{closure}}
  53: <rayon_croissant::consumer::MapfoldReduceFolder<Accumulator,Mapfold,OutputConsumer> as rayon::iter::plumbing::Folder<Input>>::consume
  54: rayon::iter::plumbing::Folder::consume_iter
  55: rayon::iter::plumbing::Producer::fold_with
  56: rayon::iter::plumbing::bridge_producer_consumer::helper
  57: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
  58: rayon_core::join::join_context::call_b::{{closure}}
  59: rayon_core::job::StackJob<L,F,R>::run_inline
  60: rayon_core::join::join_context::{{closure}}
  61: rayon_core::registry::in_worker
  62: rayon_core::join::join_context
  63: rayon::iter::plumbing::bridge_producer_consumer::helper
  64: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
  65: rayon_core::join::join_context::call_a::{{closure}}
  66: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  67: std::panicking::try::do_call
  68: __rust_try
  69: std::panicking::try
  70: std::panic::catch_unwind
  71: rayon_core::unwind::halt_unwinding
  72: rayon_core::join::join_context::{{closure}}
  73: rayon_core::registry::in_worker
  74: rayon_core::join::join_context
  75: rayon::iter::plumbing::bridge_producer_consumer::helper
  76: rayon::iter::plumbing::bridge_producer_consumer
  77: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
  78: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
  79: rayon::iter::plumbing::bridge
  80: <rayon::vec::IntoIter<T> as rayon::iter::ParallelIterator>::drive_unindexed
  81: <rayon_croissant::MapfoldReduce<Accumulator,Input,Mapfold,Init,Reduce> as rayon::iter::ParallelIterator>::drive_unindexed
  82: rayon::iter::collect::special_extend
  83: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
  84: rayon::iter::from_par_iter::collect_extended
  85: rayon::iter::from_par_iter::<impl rayon::iter::FromParallelIterator<T> for alloc::vec::Vec<T>>::from_par_iter
  86: rayon::iter::ParallelIterator::collect
  87: layout::flow::construct::<impl layout::flow::BlockContainer>::construct
  88: layout::flow::construct::IntermediateBlockContainer::finish
  89: layout::flow::construct::BlockLevelJob<Node>::finish
  90: layout::flow::construct::<impl layout::flow::BlockContainer>::construct::{{closure}}
  91: <rayon_croissant::consumer::MapfoldReduceFolder<Accumulator,Mapfold,OutputConsumer> as rayon::iter::plumbing::Folder<Input>>::consume
  92: rayon::iter::plumbing::Folder::consume_iter
  93: rayon::iter::plumbing::Producer::fold_with
  94: rayon::iter::plumbing::bridge_producer_consumer::helper
  95: rayon::iter::plumbing::bridge_producer_consumer
  96: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
  97: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
  98: rayon::iter::plumbing::bridge
  99: <rayon::vec::IntoIter<T> as rayon::iter::ParallelIterator>::drive_unindexed
 100: <rayon_croissant::MapfoldReduce<Accumulator,Input,Mapfold,Init,Reduce> as rayon::iter::ParallelIterator>::drive_unindexed
 101: rayon::iter::collect::special_extend
 102: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
 103: rayon::iter::from_par_iter::collect_extended
 104: rayon::iter::from_par_iter::<impl rayon::iter::FromParallelIterator<T> for alloc::vec::Vec<T>>::from_par_iter
 105: rayon::iter::ParallelIterator::collect
 106: layout::flow::construct::<impl layout::flow::BlockContainer>::construct
 107: layout::flow::construct::<impl layout::flow::BlockFormattingContext>::construct
 108: layout::formatting_contexts::IndependentFormattingContext::construct
 109: layout::flow::root::construct_for_root_element
 110: layout::flow::root::BoxTreeRoot::construct
 111: layout_thread::LayoutThread::handle_reflow::{{closure}}
 112: core::ops::function::FnOnce::call_once
 113: rayon_core::thread_pool::ThreadPool::install::{{closure}}
 114: rayon_core::registry::Registry::in_worker_cold::{{closure}}::{{closure}}
 115: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::call::{{closure}}
 116: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
 117: std::panicking::try::do_call
 118: __rust_try
 119: std::panicking::try
 120: std::panic::catch_unwind
 121: rayon_core::unwind::halt_unwinding
 122: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
 123: rayon_core::job::JobRef::execute
 124: rayon_core::registry::WorkerThread::execute
 125: rayon_core::registry::WorkerThread::wait_until_cold
 126: rayon_core::registry::WorkerThread::wait_until
 127: rayon_core::registry::main_loop
 128: rayon_core::registry::ThreadBuilder::run
 129: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
 130: std::sys_common::backtrace::__rust_begin_short_backtrace
 131: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
 132: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
 133: std::panicking::try::do_call
 134: __rust_try
 135: std::panicking::try
 136: std::panic::catch_unwind
 137: std::thread::Builder::spawn_unchecked::{{closure}}
 138: core::ops::function::FnOnce::call_once{{vtable.shim}}
 139: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
 140: std::sys::unix::thread::Thread::new::thread_start
 141: _pthread_start
```
This looks the immediate panic would be fixed by a commit in #26414.

### PR DESCRIPTION
**Pull request by SimonSapin**
https://drafts.csswg.org/css-backgrounds/#special-backgrounds
    
Fixes https://github.com/servo/servo/issues/25559
Closes https://github.com/servo/servo/pull/26121, as it is an alternative.
Fixes https://github.com/servo/servo/issues/26444.

### CODE REVIEW

**Comment by SimonSapin** [comment]
At the moment this PR has the same test expectation changes as https://github.com/servo/servo/pull/26121. It passes a couple more tests, but has some remaining regressions on my machine.

@bors-servo try=wpt-2020

* These two tests dynamically set `display: none` to the root element. They hang without output, I haven’t investigated them yet.
  ```
  ▶ TIMEOUT [expected PASS] /css/css-backgrounds/background-color-root-propagation-002.html
  ▶ TIMEOUT [expected PASS] /css/css-backgrounds/background-color-body-propagation-006.html
  ```

* A transform on the root element is not applied to the positioning area of the canvas’s background images. @mrobinson Would calling `build_reference_frame_if_necessary` on the root `StackingContext` be appropriate here?

  Also, the *painting area* is a rectangle in the top-level (un-transformed) coordinate space, but the display item’s `bounds` rect is in local (transformed) coordinates. So we may need to take the axis-aligned bounding box of the inverse-transformed rect.

  ```
  ▶ FAIL [expected PASS] /css/css-transforms/transform-translate-background-002.html
  ▶ FAIL [expected PASS] /css/css-transforms/transform-translate-background-001.html
  ```

**Comment by mrobinson** [comment]
> A transform on the root element is not applied to the positioning area of the canvas’s background images. @mrobinson Would calling build_reference_frame_if_necessary on the root StackingContext be appropriate here?

This depends: Is the other content on the page transformed? If it is, the correct solution would likely be to assign the background display item the correct reference frame as its spatial node. If the rest of the page content is not transformed (but should be), then I think appropriate thing would be to create a new reference frame at the the top level.

File: components/layout_2020/display_list/stacking_context.rs [hunk 1]
```diff
@@ -244,7 +244,107 @@ impl StackingContext {
...
+        //
+        // `f32` has 24 bits of mantissa.
+        // 20 bits of magnitude leaves a few bits of precision
+        // for `background-position` computation to be accurate
+        // to more than a device pixel on very high DPI.
+        const BIG: f32 = (1u32 << 20) as f32;
+        let painting_area = &LayoutRect::new(
+            LayoutPoint::new(-BIG / 2., -BIG / 2.),
+            LayoutSize::new(BIG, BIG),
+        );
```
Comment (SimonSapin) [inline components/layout_2020/display_list/stacking_context.rs:336]:
```
  ▶ CRASH [expected FAIL] /_mozilla/css/mix_blend_mode_a.html
  │ 
  │ error: XDG_RUNTIME_DIR not set in the environment.
  │ libEGL warning: No hardware driver found, falling back to software rendering
  │ [2020-05-07T12:17:09Z ERROR webrender::render_task] Attempting to create a render task of size 1048576x1048576
  │ explicit panic (thread WRRenderBackend#0, at /root/.cargo/git/checkouts/webrender-c3596abe1cf4f320/4ba17a6/webrender/src/render_task.rs:37)
```

Ok so using a huge rectangle might not be a good idea if WebRender wants to actually allocate that many pixels.

Comment (SimonSapin) [reply components/layout_2020/display_list/stacking_context.rs:336]: Minimized reproduction:

```html
<html style="background: white">
<body style="mix-blend-mode: difference">
```

Comment (SimonSapin) [reply components/layout_2020/display_list/stacking_context.rs:336]: The same panic happens for different inputs on `master`. I’ve filed https://github.com/servo/servo/issues/26463.

**Comment by jdm** [comment]
@mrobinson Do you want to review Simon's change here?

File: components/layout_2020/display_list/stacking_context.rs [hunk 2]
```diff
@@ -244,7 +244,107 @@ impl StackingContext {
...
+        } else {
+            // The root element has `display: none`,
+            // or the canvas background is taken from `<body>` which has `display: none`
+            return;
+        };
+
+        macro_rules! debug_panic {
+            ($msg: expr) => {
+                if cfg!(debug_assertions) {
+                    panic!($msg)
```
Comment (mrobinson) [inline components/layout_2020/display_list/stacking_context.rs:266]: Maybe emit a warning for release mode so that it's obvious something is wrong?

File: components/layout_2020/flow/root.rs [hunk 3]
```diff
@@ -38,6 +40,10 @@ pub struct BoxTree {
     /// Contains typically exactly one block-level box, which was generated by the root element.
     /// There may be zero if that element has `display: none`.
     root: BlockFormattingContext,
+
+    /// https://drafts.csswg.org/css-backgrounds/#special-backgrounds
+    #[serde(skip)]
```
Comment (mrobinson) [inline components/layout_2020/flow/root.rs:45]: Is there some reason to not simply implement `Serialize` and `Deserialize` on `CanvasBackground`?

File: components/layout_2020/flow/root.rs [hunk 4]
```diff
@@ -53,10 +59,14 @@ pub struct FragmentTree {
     root_fragments: Vec<ArcRefCell<Fragment>>,
 
     /// The scrollable overflow of the root of the fragment tree.
```
Comment (mrobinson) [inline components/layout_2020/flow/root.rs:61]: This comment might need a small update to reflect the fact that this is for all of the root fragments.

File: components/layout_2020/flow/root.rs [hunk 5]
```diff
@@ -359,3 +375,72 @@ impl FragmentTree {
...
+
+/// https://drafts.csswg.org/css-backgrounds/#root-background
+#[derive(Clone)]
+pub(crate) struct CanvasBackground {
+    pub style: Option<Arc<ComputedValues>>,
+
+    /// The element whose style we have above
+    pub from_element: OpaqueNode,
+
+    pub root_element: OpaqueNode,
```
Comment (mrobinson) [inline components/layout_2020/flow/root.rs:387]: A doc comment might be useful here explaining the distinction between this element and `from_element`.

File: components/layout_2020/flow/root.rs [hunk 6]
```diff
@@ -359,3 +375,72 @@ impl FragmentTree {
...
+            style: if let Display::GeneratingBox(_) = style.clone_display().into() {
+                Some(style)
+            } else {
+                None
+            },
+        }
+    }
+}
+
+fn iter_child_nodes<'dom, Node>(parent: Node) -> impl Iterator<Item = Node>
```
Comment (mrobinson) [inline components/layout_2020/flow/root.rs:435]: Is this duplicated from `components/layout_2020/dom_traversal.rs` on purpose?

File: components/script/dom/node.rs [hunk 7]
```diff
@@ -3439,12 +3439,18 @@ impl Into<LayoutElementType> for ElementTypeId {
     #[inline(always)]
     fn into(self) -> LayoutElementType {
```
Comment (mrobinson) [inline components/script/dom/node.rs:3440]: Nice.

**Comment by mrobinson** [comment]
Sure. I'm happy to review this. I took a look at this and made a few comments. In general, this all looks good to me. I seem to have found one case where the rendering may not be what is expected. The issue with the infinite rect approach is that this is not always enough to cover the entire canvas. Here's an example:

```html
<style>
html {
    transform: rotateY(90deg);
    background: blue;
}

div {
    transform: rotateY(90deg);
    width: 100px;
    height: 100px;
    background-color: pink;
}
</style>

<html>
    <div>Test</div>
</html>
```

This renders completely blue in Firefox, but no background is rendered with your change (I think).

**Comment by mrobinson** [comment]
I should mention that this case is pretty weird. It seems totally reasonable to land this change and gradually cover all of the unusual edge cases (r=me).

File: components/layout_2020/display_list/stacking_context.rs (hunk 2 above)
Comment (SimonSapin) [reply components/layout_2020/display_list/stacking_context.rs:266]: CI runs WPT with debug assertions. Do we expect people who do manual testing to look at a warning log?

File: components/layout_2020/flow/root.rs (hunk 3 above)
Comment (SimonSapin) [reply components/layout_2020/flow/root.rs:45]: `ComputedValues` doesn’t implement `Serialize`, but I can push the `skip` attribute down to that field of `CanvasBackground`.

File: components/layout_2020/display_list/stacking_context.rs (hunk 2 above)
Comment (mrobinson) [reply components/layout_2020/display_list/stacking_context.rs:266]: Emitting a warning in release mode might be interesting if, for instance, this bug became quite common but only for pages on the web. If you feel like this isn't useful though, feel free to ignore this.

File: components/layout_2020/flow/root.rs (hunk 6 above)
Comment (SimonSapin) [reply components/layout_2020/flow/root.rs:435]: No, I meant to move it there and forget to remove the original :)

**Comment by SimonSapin** [comment]
> This renders completely blue in Firefox, but no background is rendered with your change (I think).

I’ve changed `background-color` to be painted outside of any transform, which should fix this specific case. That leaves `background-image` though.

I’ve also done an attempt at the "proper" inverse transform of the painting area rectangle instead of an arbitrary huge rect, which means we shouldn’t hit https://github.com/servo/servo/issues/26463 unless the document is actually huge. However in doing so I seem to have broken transforms (many WPT failures) so that still needs investigating.

File: components/layout_2020/display_list/stacking_context.rs [hunk 8]
```diff
@@ -464,22 +470,24 @@ impl BoxFragment {
...
         // WebRender reference frames establish a new coordinate system at their origin
         // (the border box of the fragment). We need to ensure that any coordinates we
         // give to WebRender in this reference frame are relative to the fragment border
         // box. We do this by adjusting the containing block origin.
         let mut new_containing_block_info = containing_block_info.clone();
-        if established_reference_frame {
-            new_containing_block_info.rect.origin =
-                (-relative_border_rect.origin.to_vector()).to_point();
+
+        if let Some(reference_frame_data) = &reference_frame_data {
```
Comment (mrobinson) [inline components/layout_2020/display_list/stacking_context.rs:599]: Perhaps this could all be part of a method called `build_reference_frame_if_necessary(containing_block_info, new_containing_block_info)`. It might be good to isolate all of the complications of setting up the ReferenceFrame into one method.

**Comment by SimonSapin** [comment]
> However in doing so I seem to have broken transforms (many WPT failures) so that still needs investigating.

Alright, you gave me the correct lead on Matrix to fix this bug. This uncovered another pre-existing bug, for which I added a separate commit. And I also introduced another bug in passing, now fixed as well. I think this should be in pretty good shape now.

@bors-servo try=wpt-2020

**Review by mrobinson — APPROVED** [review]
Thanks! These changes look good.
