### PR TITLE
layout: Display User Agent Controls widget for video element.

### LINKED ISSUE #31414: Media controls are not included in layout
With #31412 applied, open https://au.gmented.com/p/video/test.html. With `--legacy-layout` there are media controls that appear. When using layout 2020, they do not appear. These controls rely on a special shadow host setup in the legacy layout implementation (https://github.com/servo/servo/blob/4849ba901efab9304d71b316ec9e0d7e98e1993b/components/layout/construct.rs#L707-L709). I'm not really clear where the right place to slot this into the new layout engine is.

### LINKED ISSUE #40452: Media controls for `video` is not displayed
**Describe the bug:**
The media controls for `HTMLVideoElement` is not displayed, while for `HTMLAudioElement` they can be seen.

Initial hint to find root case of it: `video` is treated as [replaced elements](https://drafts.csswg.org/css-display/#replaced-element) in Servo, while `audio` is still not yet.

See https://html.spec.whatwg.org/multipage/rendering.html#embedded-content-rendering-rules

**To Reproduce:**
```
<!DOCTYPE html>
<audio id="audio" controls></audio>
<video id="video" controls></video>
```

Permalink to test : [here](https://www.software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Caudio%20id%3D%22audio%22%20controls%3E%3C%2Faudio%3E%0A%3Cvideo%20id%3D%22video%22%20controls%3E%3C%2Fvideo%3E)

Chrome:
Image

Servo: 

Image

**Platform:**
Ubuntu 22.04

### PR DESCRIPTION
**Pull request by rayguo17**
Add Contents::ReplacedWithWidget for video elements with UA control widget, to allow Traverse into the children of video element during Box Tree Construction, Generate IndependentFormattingContextContent::ReplacedWithWidgets, to store both the `ReplacedContents` and `BlockFormattingContext`. During fragment tree generation process, first layout the Image Fragment, and then Layout the Inner  Controls BlockFormattingContext. Doing this allow us to determine the size of Inner Controls widget based on the size of the Image Fragment. Minor Fix: ::before/::after pseudo elment should be suppress for replaced element.

Testing: Should show the controls widget for `<video controls></video>`, and should not affect any existing WPT test. Since how to display UA widget of Video Element is not defined in the spec, expectedly there has no existing WPT test that testing this.
Fixes https://github.com/servo/servo/issues/40452
Fixes https://github.com/servo/servo/issues/31414

### CODE REVIEW

**Comment by rayguo17** [comment]
cc @xiaochengh @jdm @tharkum

File: components/layout/dom_traversal.rs [hunk 1]
```diff
@@ -284,6 +286,19 @@ impl Contents {
...
     ) -> Self {
         if let Some(replaced) = ReplacedContents::for_element(node, context) {
+            if let Some(element) = node.as_element() {
+                if let Some(shadow_root) = element.shadow_root() {
+                    if shadow_root.is_ua_widget() {
+                        context
+                            .image_resolver
+                            .video_content
+                            .lock()
+                            .insert(node.opaque(), replaced);
```
Comment (Loirooriol) [inline components/layout/dom_traversal.rs]: Instead of this HashMap, why not store the ReplacedContents inside the ReplacedWithWidget?

Comment (rayguo17) [reply components/layout/dom_traversal.rs]: The direct reason is that, I have not found a good way of storing the ReplacedContents inside the Box Tree (which i believe should be somewhere in the IndependentFormattingContextContents).

**Comment by tharkum** [comment]
Be honest more interesting how it will be unified with `audio` media controls, because now you added `video_content` (which have image fragment), but will be also usable with `audio`?

Right now `video` element is treated as [replaced elements](https://drafts.csswg.org/css-display/#replaced-element) in Servo, while audio is still not yet.

**Comment by rayguo17** [comment]
In the method this PR proposed, `<audio>` would be treated the same as `<video>` during BOX Tree generation. Only that `Audio` would not create a Image Fragment because there has no item in `Video_Content` as it does not have image.

File: components/script/dom/shadowroot.rs
Comment (tharkum) [inline components/script/dom/shadowroot.rs:639]: Should new method should be unified with others as well?
`#[expect(unsafe_code)] + unsafe { ... }`

File: components/script/dom/shadowroot.rs [hunk 2]
```diff
@@ -620,6 +620,8 @@ impl VirtualMethods for ShadowRoot {
 pub(crate) trait LayoutShadowRootHelpers<'dom> {
     fn get_host_for_layout(self) -> LayoutDom<'dom, Element>;
     fn get_style_data_for_layout(self) -> &'dom CascadeData;
+    #[allow(clippy::wrong_self_convention)]
```
Comment (tharkum) [inline components/script/dom/shadowroot.rs]: Can we use `&self` here to remove `clippy::wrong_self_convention`?

File: components/layout/dom_traversal.rs [hunk 3]
```diff
@@ -84,6 +84,8 @@ pub(super) enum Contents {
     /// Example: an `<img src=…>` element.
     /// <https://drafts.csswg.org/css2/conform.html#replaced-element>
     Replaced(ReplacedContents),
+    /// A video element with widget.
```
Comment (tharkum) [inline components/layout/dom_traversal.rs]: /// Example: an `<video controls>` element.

File: components/layout/dom_traversal.rs [hunk 4]
```diff
@@ -84,6 +84,8 @@ pub(super) enum Contents {
...
+    ReplacedWithWidget(NonReplacedContents),
```
Comment (tharkum) [inline components/layout/dom_traversal.rs]: AS an option - may be use `ReplacedWithWidget(ReplacedContents, NonReplacedContents),`, so later it will be possible to use this information in layout Box/Fragment construction?

File: components/layout/dom_traversal.rs [hunk 5]
```diff
@@ -284,6 +286,19 @@ impl Contents {
...
+            if let Some(element) = node.as_element() {
+                if let Some(shadow_root) = element.shadow_root() {
+                    if shadow_root.is_ua_widget() {
+                        context
+                            .image_resolver
+                            .video_content
+                            .lock()
+                            .insert(node.opaque(), replaced);
+                        let non_replaced_contents = NonReplacedContents::OfElement;
+                        return Self::ReplacedWithWidget(non_replaced_contents);
```
Comment (tharkum) [inline components/layout/dom_traversal.rs]: return Self::ReplacedWithWidget(replaced, NonReplacedContents::OfElement);

File: components/layout/dom_traversal.rs [hunk 6]
```diff
@@ -307,7 +322,9 @@ impl Contents {
 
     pub(crate) fn non_replaced_contents(self) -> Option<NonReplacedContents> {
         match self {
-            Self::NonReplaced(contents) | Self::Widget(contents) => Some(contents),
+            Self::NonReplaced(contents) |
+            Self::Widget(contents) |
+            Self::ReplacedWithWidget(contents) => Some(contents),
```
Comment (tharkum) [inline components/layout/dom_traversal.rs]: Self::ReplacedWithWidget(_, contents) => Some(contents),

File: components/layout/formatting_contexts.rs [hunk 7]
```diff
@@ -94,6 +94,12 @@ impl IndependentFormattingContext {
                 non_replaced_contents
             },
             Contents::NonReplaced(non_replaced_contents) => non_replaced_contents,
+            Contents::ReplacedWithWidget(non_replaced_contents) => {
```
Comment (tharkum) [inline components/layout/formatting_contexts.rs]: Introduce `IndependentFormattingContextContents::ReplacedWithWidget`, so everything will looks better?

           Contents::ReplacedWithWidget(replaced_content, non_replaced_content) => {
                base_fragment_info.flags.insert(FragmentFlags::IS_REPLACED | FragmentFlags::IS_WIDGET);
                return Self {
                    base: LayoutBoxBase::new(base_fragment_info, node_and_style_info.style.clone()),
                    contents: IndependentFormattingContextContents::ReplacedWithWidget(replaced_content, non_replaced_content),
                };
            },

File: components/layout/formatting_contexts.rs [hunk 8]
```diff
@@ -269,6 +275,35 @@ impl IndependentFormattingContext {
         preferred_aspect_ratio: Option<AspectRatio>,
         lazy_block_size: &LazySize,
     ) -> CacheableLayoutResult {
+        if self
```
Comment (tharkum) [inline components/layout/formatting_contexts.rs]: Replace this block to new match enum`IndependentFormattingContextContents::ReplacedWithWidget`?

File: components/script/dom/shadowroot.rs
Comment (rayguo17) [reply components/script/dom/shadowroot.rs:639]: I just found this function is actually not calling unsafe function, perhas we can remove the expect(unsafe_code)?

File: components/script/dom/shadowroot.rs (hunk 2 above)
Comment (rayguo17) [reply components/script/dom/shadowroot.rs]: good point, this can compile!

**Comment by rayguo17** [comment]
Thanks for the suggestion @tharkum ! 
I introduced `IndependentFormattingContextContents::ReplacedWithWidget(ReplacedContents, BlockFormattingContext)`, so that it can layout the Image Fragment then layout the inner controls widget related elements.

File: components/layout/dom_traversal.rs [hunk 9]
```diff
@@ -84,6 +84,9 @@ pub(super) enum Contents {
     /// Example: an `<img src=…>` element.
     /// <https://drafts.csswg.org/css2/conform.html#replaced-element>
     Replaced(ReplacedContents),
+    /// A video element with widget.
```
Comment (tharkum) [inline components/layout/dom_traversal.rs]: line 87 could be remove

File: components/layout/dom_traversal.rs [hunk 10]
```diff
@@ -284,6 +287,14 @@ impl Contents {
         context: &LayoutContext,
     ) -> Self {
         if let Some(replaced) = ReplacedContents::for_element(node, context) {
+            if let Some(element) = node.as_element() {
+                if let Some(shadow_root) = element.shadow_root() {
+                    if shadow_root.is_ua_widget() {
+                        let non_replaced_contents = NonReplacedContents::OfElement;
+                        return Self::ReplacedWithWidget(replaced, non_replaced_contents);
```
Comment (tharkum) [inline components/layout/dom_traversal.rs]: As suggestion to combine into 1 line (naming of `NonReplacedContents` is enougth to understand what it is)
` return Self::ReplacedWithWidget(replaced, NonReplacedContents::OfElement);`

File: components/layout/formatting_contexts.rs [hunk 11]
```diff
@@ -94,6 +95,26 @@ impl IndependentFormattingContext {
                 non_replaced_contents
             },
             Contents::NonReplaced(non_replaced_contents) => non_replaced_contents,
+            Contents::ReplacedWithWidget(replaced_contents, non_replaced_contents) => {
```
Comment (tharkum) [inline components/layout/formatting_contexts.rs:93]: How about to move to line 92 after `Contents::Replaced`?

File: components/layout/formatting_contexts.rs [hunk 12]
```diff
@@ -94,6 +95,26 @@ impl IndependentFormattingContext {
...
+                base_fragment_info
+                    .flags
+                    .insert(FragmentFlags::IS_REPLACED | FragmentFlags::IS_WIDGET);
+                // Since the display insdie for video element is always flow, we can continue here.
```
Comment (tharkum) [inline components/layout/formatting_contexts.rs]: I am suggesting do not use `video` here, because `audio` element also could be replaced element, may be replaced to `media` atleast.

Update: I found below your comment `// For replaced with widget, we use the block formatting context's layout style.` so may be use here smth like if it makes sense `// For replaced with widget, use block formatting context since the display inside is always flow.`

`insdie` -> `inside`

File: components/layout/formatting_contexts.rs [hunk 13]
```diff
@@ -277,6 +304,22 @@ impl IndependentFormattingContext {
                 &self.base,
                 lazy_block_size,
             ),
+            IndependentFormattingContextContents::ReplacedWithWidget(replaced, bfc) => {
+                let mut layout_result = replaced.layout(
```
Comment (tharkum) [inline components/layout/formatting_contexts.rs]: `layout_result` -> `replaced_layout`

File: components/script/dom/shadowroot.rs [hunk 14]
```diff
@@ -642,6 +643,11 @@ impl<'dom> LayoutShadowRootHelpers<'dom> for LayoutDom<'dom, ShadowRoot> {
         unsafe { &self.unsafe_get().author_styles.borrow_for_layout().data }
     }
 
+    #[inline]
+    fn is_ua_widget(&self) -> bool {
+        self.unsafe_get().is_user_agent_widget()
```
Comment (tharkum) [inline components/script/dom/shadowroot.rs:648]: Is it Ok to use insafe without #[expect(unsafe_code)] + unsafe { ..} ?

File: components/script/layout_dom/element.rs [hunk 15]
```diff
@@ -1014,6 +1014,15 @@ impl<'dom> ThreadSafeLayoutElement<'dom> for ServoThreadSafeLayoutElement<'dom>
     }
 
     fn with_pseudo(&self, pseudo_element: PseudoElement) -> Option<Self> {
+        /*
+            https://drafts.csswg.org/css-pseudo/#generated-content:
+            Also as with regular child elements, the ::before and ::after pseudo-elements
+            are suppressed when their parent, the originating element, is replaced.
+        */
+        if self.has_local_name(&local_name!("video")) && pseudo_element.is_before_or_after() {
```
Comment (tharkum) [inline components/script/layout_dom/element.rs:1022]: Why did you add this part? How is it affecting visual presentation (with/without)?

**Review by tharkum — COMMENTED** [review]
BTW, dynamically enabling and disabling media controls will change the layout position/size of the `video` element with valid `src ="..."`? A media controls will be inside `video` or outside?

File: components/script/dom/shadowroot.rs (hunk 14 above)
Comment (rayguo17) [reply components/script/dom/shadowroot.rs:648]: the function `unsafe_get` is not really unsafe, i wonder why the naming though..?

File: components/script/layout_dom/element.rs (hunk 15 above)
Comment (rayguo17) [reply components/script/layout_dom/element.rs:1022]: This line is to address the wpt test: `tests/wpt/tests/css/css-pseudo/pseudo-replaced-elements.html`. Previously, since we never traverse into the child of Replaced element, we will not have problem with it.

Comment (rayguo17) [reply components/script/layout_dom/element.rs:1022]: Without it, 
```
video::before {
 content: "X",
 display: block,
 width: 10%
}
```
would show an 'X' inside the `<video>` element, while the expected behaviour is not showing the 'X'.

File: components/layout/formatting_contexts.rs (hunk 12 above)
Comment (rayguo17) [reply components/layout/formatting_contexts.rs]: Changed as suggested.

File: components/layout/formatting_contexts.rs (hunk 11 above)
Comment (rayguo17) [reply components/layout/formatting_contexts.rs:93]: I think it make sense with name ordering.

File: components/layout/dom_traversal.rs (hunk 10 above)
Comment (rayguo17) [reply components/layout/dom_traversal.rs]: Make sense!

File: components/script/dom/shadowroot.rs (hunk 14 above)
Comment (rayguo17) [reply components/script/dom/shadowroot.rs:648]: Maybe @jdm, do you know something about the naming?

**Comment by rayguo17** [comment]
> BTW, dynamically enabling and disabling media controls will change the layout position/size of the `video` element with valid `src ="..."`? A media controls will be inside `video` or outside?

That is a good point, media controls should be encapsulated inside 'video', and the size of replaced contents should solely depends on the Image fragment but not the widget related fragments. The key point to this is the function `IndependentFormattingContextContent::compute_inline_content_size`. Newest commit should have address this issue.

File: components/layout/dom_traversal.rs (hunk 9 above)
Comment (rayguo17) [reply components/layout/dom_traversal.rs]: Done

File: components/layout/formatting_contexts.rs (hunk 13 above)
Comment (rayguo17) [reply components/layout/formatting_contexts.rs]: Done

File: components/layout/dom_traversal.rs (hunk 1 above)
Comment (rayguo17) [reply components/layout/dom_traversal.rs]: @Loirooriol Btw, now i switched to a method that does not need to include this HashMap.

**Comment by rayguo17** [comment]
cc @yezhizhen.

File: components/script/dom/shadowroot.rs (hunk 14 above)
Comment (jdm) [reply components/script/dom/shadowroot.rs:648]: https://github.com/servo/servo/blob/660238a94c417d709cc99ec3d6cc6d0bfe4fc272/components/shared/layout/wrapper_traits.rs#L196-L198

**Comment by tharkum** [comment]
@rayguo17 < LGTM, except one minor comment about the following function, lets add `unsafe`  block around body of function because we are moving from safe to unsafe block and need to mark it.
```
    fn is_ua_widget(&self) -> bool {
        unsafe { self.unsafe_get().is_user_agent_widget() }
```

and please fill a issue to handle "media controls should be encapsulated inside 'video', and the size of replaced contents should solely depends on the Image fragment but not the widget related fragments" so it will not be forget.

File: components/script/dom/shadowroot.rs (hunk 14 above)
Comment (jdm) [reply components/script/dom/shadowroot.rs:648]: That's the idea. I think it's less helpful for methods that we use all over the place, like unsafe_get.

**Comment by rayguo17** [comment]
> @rayguo17 < LGTM, except one minor comment about the following function, lets add `unsafe` block around body of function because we are moving from safe to unsafe block and need to mark it.
> 
> ```
>     fn is_ua_widget(&self) -> bool {
>         unsafe { self.unsafe_get().is_user_agent_widget() }
> ```
> 
> and please fill a issue to handle "media controls should be encapsulated inside 'video', and the size of replaced contents should solely depends on the Image fragment but not the widget related fragments" so it will not be forget.
> 
> Note: I haven't permissions to add "+1", so someone else should review it also...

I am still hesitate on adding unsafe block around the `self.unsafe_get().is_user_agent_widget()`, as both `unsafe_get()` and `is_user_agent_widget()` functions are not mark with `unsafe`. A similar example can be seen at: 
https://github.com/servo/servo/blob/215e43e3e0602a4879b58cabcb45b24d3b4dd745/components/script/dom/element.rs#L1410-L1417

Where the function `style_attribute` has a `unsafe` block because `borrow_for_layout` is `unsafe`, while function `local_name` has no `unsafe` block. 

Would you mind explain a bit more why this should be mark with unsafe? @tharkum

**Comment by tharkum** [comment]
> > @rayguo17 < LGTM, except one minor comment about the following function, lets add `unsafe` block around body of function because we are moving from safe to unsafe block and need to mark it.
> > ```
> >     fn is_ua_widget(&self) -> bool {
> >         unsafe { self.unsafe_get().is_user_agent_widget() }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and please fill a issue to handle "media controls should be encapsulated inside 'video', and the size of replaced contents should solely depends on the Image fragment but not the widget related fragments" so it will not be forget.
> > Note: I haven't permissions to add "+1", so someone else should review it also...
> 
> I am still hesitate on adding unsafe block around the `self.unsafe_get().is_user_agent_widget()`, as both `unsafe_get()` and `is_user_agent_widget()` functions are not mark with `unsafe`. A similar example can be seen at:
> 
> https://github.com/servo/servo/blob/215e43e3e0602a4879b58cabcb45b24d3b4dd745/components/script/dom/element.rs#L1410-L1417
> 
> Where the function `style_attribute` has a `unsafe` block because `borrow_for_layout` is `unsafe`, while function `local_name` has no `unsafe` block.
> 
> Would you mind explain a bit more why this should be mark with unsafe? @tharkum

Thanks for explanation. I didn't check it carefully before...

**Review by tharkum — APPROVED** [review]

**Review by jdm — APPROVED** [review]

**Comment by rayguo17** [comment]
Thank you for reviewing! @tharkum
