### PR TITLE
servoshell: Unset `webdriver_port` when scheduling shutdown

### LINKED ISSUE #40972: Cannot shutdown Servo with webdriver command
**Describe the bug:**
Starting from some point, cannot shutdown Servo through webdriver command. This blocks code coverage development for WPT.

Can be 8c24a80a04fc447d110cd38bae6c8c810664e855

**Platform:**
Desktop

### PR DESCRIPTION
**Pull request by yezhizhen**
This is the minimal possible changes after I've tried several approaches. The original problem is tricky after multi-window support, as we want to shutdown normally while not panic after no window is open to support Servodriver.

Testing: 
1. We no longer panic on https://github.com/servo/servo/blob/f0ed7506cd28701107239241154ae40b738effe4/tests/wpt/tests/webdriver/tests/classic/close_window/close.py#L87
2. Wpt can end normally instead of always **"Max retry exceeded to normally shut down. Killing instead."**

Fixes: https://github.com/servo/servo/issues/40972#issuecomment-3594308162

### CODE REVIEW

File: ports/servoshell/running_app_state.rs [hunk 1]
```diff
@@ -164,7 +164,7 @@ pub(crate) struct RunningAppState {
 
     /// Whether or not program exit has been triggered. This means that all windows
     /// will be destroyed and shutdown will start at the end of the current event loop.
-    exit_scheduled: Rc<Cell<bool>>,
+    exit_scheduled: Cell<bool>,
```
Comment (yezhizhen) [inline ports/servoshell/running_app_state.rs:167]: This `Rc` was likely wrongly added when copy-pasting the https://github.com/servo/servo/blob/f0ed7506cd28701107239241154ae40b738effe4/ports/servoshell/running_app_state.rs#L163 above.

**Review by mrobinson — APPROVED** [review]
Thanks for the fix!
