### PR TITLE
layout: Lay out collapsed table rows and columns, but don't paint them

### LINKED ISSUE #37421: panic: Should only call `scrollable_overflow()` after calculating overflow (at components/layout/fragment_tree/box_fragment.rs:202)
Minimal testcase:

```html
<!DOCTYPE html>
<style>
  #container {
    display: inline-table;
    visibility: collapse;
  }
</style>
<div id="container">
  <textarea id="textarea"></textarea>
</div>
<script>
  onload = _ => textarea.scrollTo();
</script>
```

System: Linux
Version: Servo 0.0.1-73c286423
Command: `./servo/servo`

```
Should only call `scrollable_overflow()` after calculating overflow (thread Script(1,1), at components/layout/fragment_tree/box_fragment.rs:202)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::option::expect_failed
   8: layout::fragment_tree::box_fragment::BoxFragment::reachable_scrollable_overflow_region
   9: <layout::layout_impl::LayoutThread as script_layout_interface::Layout>::query_scrolling_area
  10: script::dom::window::Window::scrolling_area_query
  11: script::dom::node::Node::scroll_area
  12: script::dom::element::Element::has_overflow
  13: script::dom::element::Element::scroll
  14: script_bindings::codegen::GenericBindings::ElementBinding::Element_Binding::scroll::{{closure}}
  15: mozjs::panic::wrap_panic
  16: script_bindings::codegen::GenericBindings::ElementBinding::Element_Binding::scroll
  17: CallJitMethodOp
  18: script_bindings::utils::generic_call
  19: script_bindings::utils::generic_method
  20: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  21: _ZN2js9InterpretEP9JSContextRNS_8RunStateE
  22: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  23: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  24: _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
  25: _ZN2JS4CallEP9JSContextNS_6HandleINS_5ValueEEES4_RKNS_16HandleValueArrayENS_13MutableHandleIS3_EE
  26: script::dom::event::inner_invoke
  27: script::dom::event::invoke
  28: script::dom::event::Event::dispatch
  29: <T as script::task::TaskBox>::run_box
  30: script::script_thread::ScriptThread::handle_msg_from_script
  31: script::script_thread::ScriptThread::handle_msgs::{{closure}}
  32: script::script_thread::ScriptThread::handle_msgs
  33: std::sys::backtrace::__rust_begin_short_backtrace
  34: core::ops::function::FnOnce::call_once{{vtable.shim}}
  35: std::sys::pal::unix::thread::Thread::new::thread_start
  36: start_thread
             at ./nptl/pthread_create.c:447:8
  37: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
```

### PR DESCRIPTION
**Pull request by mrobinson**
It's expected that script queries be able to interact with collapsed
table rows and columns, so this change starts laying them out. They
still do not affect table dimensions, nor are they painted.

This does not fix all interaction with collapsed rows and columns. For
instance, setting scroll offsets of contained scrolling nodes does not
work properly. It does fix the panic though, which is the most important
thing.

Testing: this change includes a new WPT crash test.
Fixes: #37421.

### CODE REVIEW

**Review by yezhizhen — COMMENTED** [review]
I think you forgot to commit the new test.

**Review by Loirooriol — COMMENTED** [review]
The test is missing.

A concern that I had was that laying out the contents can create overflow, which will now be observed by a scrollable ancestor:

```html
<!DOCTYPE html>
<div id="scroller" style="height: 100px; overflow: scroll; scrollbar-width: none">
  <div style="display: table-row; visibility: collapse">
    <div style="min-width: 1px; height: 150px;"></div>
  </div>
</div>
<script>document.write(scroller.scrollHeight)</script>
```

Was 100, now it's 150.

But turns out that other browsers don't agree: Blink says 100, Gecko says 150. So I guess it's fine.

**Comment by mrobinson** [comment]
> The test is missing.

I've added the test now.
> 
> A concern that I had was that laying out the contents can create overflow, which will now be observed by a scrollable ancestor:

Now I also zero out the overflow for `visibility: collapse` box fragments, which should fix the testcase you included. This still doesn't allow scrolling of any scroll nodes inside `visibility: collapse` subtrees, but I think that's a bigger fix that could be handled separately.

File: components/layout/fragment_tree/box_fragment.rs [hunk 1]
```diff
@@ -291,6 +293,15 @@ impl BoxFragment {
                 acc.union(&scrollable_overflow_from_child)
             });
 
+        // If this is fragment has `visibility: collapse` we still want to calculate
+        // overflow for all children (handled above), but it also makes sense that it
+        // doesn't contribute any overflow to its ancestors. This behavior matches Chrome,
+        // but not Firefox.
+        if self.style.get_inherited_box().visibility == ComputedVisibility::Collapse {
```
Comment (Loirooriol) [inline components/layout/fragment_tree/box_fragment.rs]: Shouldn't this check `FragmentFlags::IS_COLLAPSED`?

File: tests/wpt/tests/css/css-tables/table-collapsed-row-or-column-crash.html [hunk 2]
```diff
@@ -0,0 +1,19 @@
+<!DOCTYPE html>
+<div style="display: table; visibility: collapse">
```
Comment (Loirooriol) [inline tests/wpt/tests/css/css-tables/table-collapsed-row-or-column-crash.html:5]: You can add `<link rel="help" href="https://github.com/servo/servo/issues/37421">` for context.

File: components/layout/fragment_tree/box_fragment.rs (hunk 1 above)
Comment (mrobinson) [reply components/layout/fragment_tree/box_fragment.rs]: Yes, you're right. I've fixed this.

File: tests/wpt/tests/css/css-tables/table-collapsed-row-or-column-crash.html (hunk 2 above)
Comment (mrobinson) [reply tests/wpt/tests/css/css-tables/table-collapsed-row-or-column-crash.html:5]: Added.

File: components/layout/fragment_tree/box_fragment.rs [hunk 3]
```diff
@@ -291,6 +292,15 @@ impl BoxFragment {
                 acc.union(&scrollable_overflow_from_child)
             });
 
+        // If this is fragment has `visibility: collapse` we still want to calculate
+        // overflow for all children (handled above), but it also makes sense that it
+        // doesn't contribute any overflow to its ancestors. This behavior matches Chrome,
+        // but not Firefox.
```
Comment (Loirooriol) [inline components/layout/fragment_tree/box_fragment.rs]: An then the comment isn't entirely correct, because elements other than table tracks can also get `visibility: collapse` (it just behaves as `hidden`).

Maybe something like

```suggestion
        // Prevent contents of collapsed table tracks from contributing to scrollable overflow.
        // This behavior matches Chrome, but not Firefox.
        // See https://github.com/w3c/csswg-drafts/issues/12689
```

**Review by Loirooriol — APPROVED** [review]
