### PR TITLE
fetch: implement multipart/form-data parsing for Request::formData()

### LINKED ISSUE #25106: MIME handling of multipart form data isn't working in several cases
WPT fetch/api/response/response-consume.html fails several cases by getting "Inappropriate MIME-type for Body" thrown by script/body.rs. The comment at https://github.com/servo/servo/blob/master/components/script/body.rs#L187 is probably relevant.

Other cases are failing on ReadableStream, but this seems entirely disjoint from that.

### PR DESCRIPTION
**Pull request by Taym95**
Testing: More test passed in `fetch/api/abort/request.any.js.ini`

fixes: #25106

### CODE REVIEW

**Comment by jdm** [comment]
FYI: https://github.com/servo/servo/issues/25106#issuecomment-3717257741 suggests a dependency we could potentially use instead of writing all the parsing routines.

**Comment by Taym95** [comment]
> FYI: [#25106 (comment)](https://github.com/servo/servo/issues/25106#issuecomment-3717257741) suggests a dependency we could potentially use instead of writing all the parsing routines.

Ah good to knew, I will look at it

**Comment by atouchet** [comment]
> > FYI: [#25106 (comment)](https://github.com/servo/servo/issues/25106#issuecomment-3717257741) suggests a dependency we could potentially use instead of writing all the parsing routines.
> 
> Ah good to knew, I will look at it

It's a bit unfortunate how many old duplicate dependencies the `textnonce` crate adds.

File: components/script/body.rs [hunk 1]
```diff
@@ -900,22 +906,182 @@ fn run_blob_data_algorithm(
...
+        );
+
+        if let Some(boundary) = mime.get_param(mime::BOUNDARY) {
+            let closing_boundary = format!("--{}--", boundary.as_str()).into_bytes();
+            let trimmed_bytes = bytes.strip_suffix(b"\r\n").unwrap_or(&bytes);
+            if trimmed_bytes == closing_boundary {
+                let formdata = FormData::new(None, root, can_gc);
+                return Ok(FetchedData::FormData(formdata));
+            }
+        }
```
Comment (jdm) [inline components/script/body.rs:1057]: I'm guessing read_multipart_body does not work when there's only a closing boundary value and nothing else?

File: components/script/body.rs [hunk 2]
```diff
@@ -900,22 +906,182 @@ fn run_blob_data_algorithm(
...
+                    .trim_matches('"')
+                    .to_owned(),
+            );
+        }
+        if let Some(index) = cd.find("filename*=UTF-8''") {
+            let start = index + "filename*=UTF-8''".len();
+            return Some(
+                cd.get(start..)
+                    .unwrap_or_default()
+                    .trim_matches('"')
```
Comment (jdm) [inline components/script/body.rs]: From my reading (https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Content-Disposition) there's no quotes expected in this syntax so we shouldn't trim them.

File: components/script/body.rs [hunk 3]
```diff
@@ -900,22 +906,182 @@ fn run_blob_data_algorithm(
...
+            let v = v.strip_suffix('"').unwrap_or(v);
+            return Some(v.to_string());
+        }
+    }
+    None
+}
+
+fn extract_filename_from_content_disposition(headers: &HeaderMap) -> Option<String> {
+    let cd = headers.get(CONTENT_DISPOSITION)?.to_str().ok()?;
+    if cd.contains("filename") {
```
Comment (jdm) [inline components/script/body.rs]: It looks like this check is redundant and we could just fall through the if let blocks instead.

File: components/script/body.rs [hunk 4]
```diff
@@ -900,22 +906,182 @@ fn run_blob_data_algorithm(
...
+                    .unwrap_or_default()
+                    .trim_matches('"')
+                    .to_owned(),
+            );
+        }
+    }
+    None
+}
+
+fn decode_utf8_without_bom(bytes: &[u8]) -> String {
```
Comment (jdm) [inline components/script/body.rs]: Could we replace this with [`UTF_8.decode_with_bom_removal`](https://docs.rs/encoding_rs/latest/encoding_rs/struct.Encoding.html#method.decode_with_bom_removal) instead?

File: components/script/body.rs [hunk 5]
```diff
@@ -900,22 +906,182 @@ fn run_blob_data_algorithm(
...
+    can_gc: CanGc,
+) -> Fallible<()> {
+    for node in nodes {
+        match node {
+            Node::Part(part) => {
+                append_form_data_entry_from_part(root, formdata, &part.headers, part.body, can_gc)?;
+            },
+            Node::File(file_part) => {
+                let body = fs::read(&file_part.path)
+                    .map_err(|_| Error::Type("Inappropriate MIME-type for Body".to_string()))?;
```
Comment (jdm) [inline components/script/body.rs]: This error message looks wrong.

File: tests/wpt/meta/fetch/api/response/response-consume.html.ini [hunk 6]
```diff
@@ -1,21 +1,6 @@
 [response-consume.html]
-  [Consume response's body: from text with correct multipart type to formData]
-    expected: FAIL
-
   [Consume response's body: from text with correct multipart type to formData with BOM]
```
Comment (jdm) [inline tests/wpt/meta/fetch/api/response/response-consume.html.ini]: Can we figure out what's going on with the remaining failures in this file?

File: components/script/Cargo.toml [hunk 7]
```diff
@@ -38,6 +38,7 @@ aes-gcm = { workspace = true }
 aes-kw = { workspace = true }
 app_units = { workspace = true }
 argon2 = { workspace = true }
+
```
Comment (jdm) [inline components/script/Cargo.toml]:
```suggestion
```

**Review by jdm — CHANGES_REQUESTED** [review]
Looking good so far!

File: components/script/body.rs (hunk 2 above)
Comment (Taym95) [reply components/script/body.rs]: If I don't trim this test is failing:

```
Unexpected Results
------------------
/fetch/api/response/response-consume.html
  FAIL Consume response's body: from multipart form data blob to formData - assert_equals: Retrieve and verify response's 6th entry name property expected "file2" but got "\"file2\""
```

File: tests/wpt/meta/fetch/api/response/response-consume.html.ini (hunk 6 above)
Comment (Taym95) [reply tests/wpt/meta/fetch/api/response/response-consume.html.ini]:
```
/fetch/api/response/response-consume.html
  FAIL Consume response's body: from FormData to blob - assert_equals: Blob body type should be computed from the response Content-Type expected "multipart/form-data; boundary=---------------------------19653830722749924525" but got "multipart/form-data;boundary=---------------------------19653830722749924525"
``

it looks like failing because of extra space after `;` in  parsing and reserializing the header

Comment (Taym95) [reply tests/wpt/meta/fetch/api/response/response-consume.html.ini]: this test should be fixed by https://github.com/servo/servo/pull/42041#discussion_r2720125122


but this test :

```
/fetch/api/response/response-consume.html
  FAIL Consume response's body: from FormData to blob - assert_equals: Blob body type should be computed from the response Content-Type expected "multipart/form-data; boundary=---------------------------19653830722749924525" but got "multipart/form-data;boundary=---------------------------19653830722749924525"
```

it looks like failing because of extra space after `;` in  parsing and reserializing the header

Comment (Taym95) [reply tests/wpt/meta/fetch/api/response/response-consume.html.ini]: fixed this test also

File: components/script/body.rs (hunk 1 above)
Comment (Taym95) [reply components/script/body.rs:1057]: Yes it did not work

**Review by jdm — APPROVED** [review]

**Comment by sebsebmc** [comment]
Nice job, I took a look at this a long time ago and it's very underspecified. The other browsers all disagree on how strict the parsing for this should be.
