### PR TITLE
Fix running servoshell and unit tests through a symlink

### LINKED ISSUE #30536: servoshell and unit tests crash if target directory is symlinked
I recently symlinked my target directory to another filesystem, to exclude it from my backups,

```
% ls -l target
lrwxrwxrwx 1 delan users 25 Sep 28 15:34 target -> /cuffs/build/servo/target
```

but this breaks servoshell and unit tests.

```
% target/debug/servo
thread 'main' panicked at 'Can't read file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', ports/servoshell/resources.rs:78:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```
% ./mach test-unit ports/servoshell/prefs.rs -- -- --test-threads 1
NOTE: Entering nix-shell etc/shell.nix
      Timing report saved to /cuffs/code/servo/target/cargo-timings/cargo-timing-20231011T093548Z.html
    Finished test [unoptimized + debuginfo] target(s) in 0.68s
     Running unittests main.rs (target/debug/deps/servo-ee8531062619dcd4)

running 2 tests
test prefs::test_invalid_prefs_from_command_line_panics ... FAILED
test prefs::test_parse_pref_from_command_line ... FAILED

failures:

---- prefs::test_invalid_prefs_from_command_line_panics stdout ----
thread 'prefs::test_invalid_prefs_from_command_line_panics' panicked at 'Can't find file: prefs.json: Os { code: 2, kind: NotFound, message: "No such file or directory" }', components/embedder_traits/resources.rs:116:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'prefs::test_invalid_prefs_from_command_line_panics' panicked at 'Message should describe the problem', ports/servoshell/prefs.rs:120:5

---- prefs::test_parse_pref_from_command_line stdout ----
thread 'prefs::test_parse_pref_from_command_line' panicked at 'Once instance has previously been poisoned', /home/delan/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:30:16


failures:
    prefs::test_invalid_prefs_from_command_line_panics
    prefs::test_parse_pref_from_command_line

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 3 filtered out; finished in 0.00s

error: test failed, to rerun pass `-p servoshell --bin servo`
```

### PR DESCRIPTION
**Pull request by delan**
Servo relies on several external files in /resources/, and the loading of these resources is delegated to the embedder. In this repo, libsimpleservo compiles them in with include_bytes!(), while the other three (servoshell, gstplugin, and unit tests) try to read them from the filesystem at runtime.

Our current logic for searching for the resources directory tries to accommodate both local dev in this repo (../../resources relative to servo, or a further ancestor in the case of unit tests) and nightly builds (resources relative to servo, or Resources relative to a further ancestor in the case of macOS):

1. let _path_ = the current executable path
2. canonicalise _path_, resolving any symlinks
3. let _path_ = parent of _path_
4. try _path_/resources
5. try _path_/Resources
6. go to step 3

But this fails if target is symlinked to another filesystem, like I recently did to exclude it from my backups:

```
% ls -l target
lrwxrwxrwx 1 delan users 25 Sep 28 15:34 target -> /cuffs/build/servo/target
```

This patch adds (or replaces those with, for unit tests) a few steps as follows:

7. let _path_ = the current directory
8. try _path_/resources
9. let _path_ = parent of _path_
10. go to step 8

The new logic:

* allows servoshell and unit tests to be run with a symlinked target directory
* does not require any special environment variables, so you can run target/debug/servo in e.g. renderdoc
* does not affect the behaviour of our nightly releases

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #30536

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

File: components/embedder_traits/resources.rs [hunk 1]
```diff
@@ -49,6 +44,25 @@ pub fn sandbox_access_files_dirs() -> Vec<PathBuf> {
         .sandbox_access_files_dirs()
 }
 
+pub fn filename(file: Resource) -> &'static str {
```
Comment (mrobinson) [inline components/embedder_traits/resources.rs:47]: Perhaps this could be a function on the enum itself:

```rust
impl Resource {
    pub fn filename(&self) -> &'static str {
        ....
    }
}

File: components/embedder_traits/resources.rs [hunk 2]
```diff
@@ -85,38 +136,10 @@ fn resources_for_tests() -> Box<dyn ResourceReaderMethods + Sync + Send> {
...
-            let mut path = env::current_exe().unwrap();
-            path = path.canonicalize().unwrap();
-            while path.pop() {
-                path.push("resources");
-                if path.is_dir() {
-                    break;
-                }
-                path.pop();
-            }
+            let file = filename(file);
```
Comment (mrobinson) [inline components/embedder_traits/resources.rs:139]: This would just be: 

```suggestion
            let file = resource.filename();
```

**Review by mrobinson — APPROVED** [review]
Looks good with one small suggestion before landing.

File: ports/gstplugin/resources.rs [hunk 3]
```diff
@@ -6,38 +6,18 @@
...
 
-lazy_static! {
-    static ref CMD_RESOURCE_DIR: Mutex<Option<String>> = Mutex::new(None);
+lazy_static::lazy_static! {
+    static ref CMD_RESOURCE_DIR: Mutex<Option<PathBuf>> = Mutex::new(None);
 }
 
 struct ResourceReader;
 
-fn filename(file: Resource) -> &'static str {
```
[the remark this answers is not in the document]
Comment (delan) [reply ports/gstplugin/resources.rs:22]: thanks!

File: components/embedder_traits/resources.rs (hunk 1 above)
Comment (delan) [reply components/embedder_traits/resources.rs]: done in 73c665011e20accdd7c4af0833f4e15086aaa88f

File: components/embedder_traits/resources.rs (hunk 2 above)
Comment (delan) [reply components/embedder_traits/resources.rs]: done in 73c665011e20accdd7c4af0833f4e15086aaa88f

**Comment by delan** [comment]
I had to change the logic used for unit tests, because the current executable path was getting implicitly canonicalised. #30509 will simplify this by baking in the resources for unit tests anyway, it’s just we can’t do that in this patch.
