### PR TITLE
touch: Stop flinging if no scroll happened

### LINKED ISSUE #41026: Unable to fling in some scenarios.
**Describe the bug:**
Unable to fling in some scenarios.

**To Reproduce:**
Open the[ Mossel Mall category page](https://m.huaweimossel.com/#/pages/sort/sort), fling works normally, fling to the bottom. but after clicking on categories such as "美酒[Wine]," the fling feature becomes ineffective.

**Platform:**
openharmony

### PR DESCRIPTION
**Pull request by kongbai1996**
If no scroll happened, we would stop flinging if there is any.
Extract the functionality to `fn stop_fling_if_needed`.
Testing: There are currently no related test cases for the modifications made to fling.
Fixes: #41026

### CODE REVIEW

**Comment by jschwe** [comment]
I think you might need to add a bit more explanation about the background. I'd like to understand better what is happening.

File: components/compositing/webview_renderer.rs [hunk 1]
```diff
@@ -785,6 +785,9 @@ impl WebViewRenderer {
                 scroll_result.external_scroll_id,
                 scroll_result.hit_test_result.clone(),
             );
+        } else {
+            // No scroll happened, so if we were flinging, stop the fling.
```
Comment (yezhizhen) [inline components/compositing/webview_renderer.rs]:
```suggestion
```
This is self-explanatory.

**Review by yezhizhen — COMMENTED** [review]
> I think you might need to add a bit more explanation about the background. I'd like to understand better what is happening.

The background is listed in issue. I adjusted title/text a bit.

> Testing: There are currently no related test cases for the modifications made to fling.

I will add webdriver support for touch in a few days.

**Review by yezhizhen — APPROVED** [review]

**Comment by kongbai1996** [comment]
> I think you might need to add a bit more explanation about the background. I'd like to understand better what is happening.

When the fling reaches the bottom and there is no more distance to scroll, if the fling is not ended and `observing_frames_for_fling` is set to false, then it will never be possible to add a FlingRefreshDriverObserver here,https://github.com/servo/servo/blob/ad134e166d96c7e4fc919ec6615e119459bca318/components/compositing/touch.rs#L674-L681 which will prevent subsequent flings.
