### PR TITLE
Fix resize event is not fired for window in headless mode

### LINKED ISSUE #15621: Resize event is not fired when resizing window in headless mode
Compare:
```html
<script>
window.onresize = function() { console.log("resize event"); }
window.resizeTo(200, 200);
console.log("called resizeTo");
</script>
```
```
$ ./mach run foo.html
called resizeTo
resize event
```
```
$ ./mach run foo.html --headless
called resizeTo
```

### PR DESCRIPTION
**Pull request by dralley**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #15621
- [x] There are tests for these changes

### CODE REVIEW

**Comment by dralley** [comment]
The test is a little flaky -- when I just leave it alone, it  times out, when I click on the window that is opened up then it passes.

**Comment by jdm** [comment]
To be sure you're testing the headless code, please run the test with `--headless`.

**Comment by dralley** [comment]
@jdm It passes in headless mode consistently.

**Comment by dralley** [comment]
Looks there are some unknown failures

File: ports/glutin/headless_window.rs [hunk 1]
```diff
@@ -196,8 +211,8 @@ impl WindowMethods for Window {
                 self.context.context,
                 buffer.as_mut_ptr() as *mut _,
                 gl::UNSIGNED_BYTE,
-                self.context.width as i32,
-                self.context.height as i32,
+                self.context.width.get() as i32,
+                self.context.height.get() as i32,
             );
             assert_ne!(ret, 0);
```
Comment (jdm) [inline ports/glutin/headless_window.rs:217]: This assertion is now firing because we're calling OSMesaMakeCurrent with a size that is different than the original size the context was created with. I think we will need to recreate the context when resizing the headless window.

**Review by jdm — DISMISSED** [review]

**Comment by dralley** [comment]
I'll hold off on changing anything until after the surfmanup PR merges, because that looks like it changes a bunch of the osmesa context code.

File: ports/glutin/headless_window.rs [hunk 2]
```diff
@@ -27,6 +27,8 @@ pub struct Window {
     animation_state: Cell<AnimationState>,
     fullscreen: Cell<bool>,
     device_pixels_per_px: Option<f32>,
+    inner_size: Cell<Size2D<i32, DeviceIndependentPixel>>,
```
Comment (dralley) [inline ports/glutin/headless_window.rs:30]: Copied from ```headed_window.rs```

**Comment by dralley** [comment]
@jdm Updated, hopefully this should fix it.

**Comment by jdm** [comment]
```
  ▶ TIMEOUT [expected OK] /webdriver/tests/get_element_rect/get.py
  │ 
  │ Failed to resize: Failed (thread main, at ports/glutin/headless_window.rs:84)
  │ stack backtrace:
  │    0: servo::backtrace::print
  │    1: servo::main::{{closure}}
  │    2: std::panicking::rust_panic_with_hook
  │              at src/libstd/panicking.rs:515
  │    3: rust_begin_unwind
  │              at src/libstd/panicking.rs:419
  │    4: core::panicking::panic_fmt
  │              at src/libcore/panicking.rs:111
  │    5: core::option::expect_none_failed
  │              at src/libcore/option.rs:1268
  │    6: <servo::headless_window::Window as servo::window_trait::WindowPortsMethods>::set_inner_size
  │    7: servo::browser::Browser<Window>::handle_servo_events
  │    8: servo::app::App::handle_events
  │    9: servo::app::App::run
  │   10: servo::main
  │   11: std::rt::lang_start::{{closure}}
  │   12: std::rt::lang_start_internal::{{closure}}
  │              at src/libstd/rt.rs:52
  │       std::panicking::try::do_call
  │              at src/libstd/panicking.rs:331
  │       std::panicking::try
  │              at src/libstd/panicking.rs:274
  │       std::panic::catch_unwind
  │              at src/libstd/panic.rs:394
  │       std::rt::lang_start_internal
  │              at src/libstd/rt.rs:51
  │   13: main
  │   14: __libc_start_main
```

**Comment by dralley** [comment]
Why would it fail to resize?  Should I just recreate the entire ```WebrenderSurfman``` object then?

**Comment by jdm** [comment]
@asajeffrey Where's the code in surfman that controls resizing the surfaces we use for the headless backend?

**Comment by asajeffrey** [comment]
The code for resizing a headless window is https://github.com/asajeffrey/surfman-chains/blob/b949a240d73ef86d3c4bd22bc3d93933fac21ee9/surfman-chains/lib.rs#L219

It would be useful to know why that's failing, e.g. the error that caused the panic.

**Comment by asajeffrey** [comment]
Ah, it could be https://github.com/asajeffrey/surfman-chains/blob/b949a240d73ef86d3c4bd22bc3d93933fac21ee9/surfman-chains/lib.rs#L232. Are we passing in width or height less than 1px?

**Comment by jdm** [comment]
@dralley Could you add some logging to help figure out what's going on? You can run the tests that are failing with `./mach test-wpt --timeout-multiplier=4 --headless webdriver`.

**Comment by dralley** [comment]
I'll try to figure it out when I get some spare time (not as much of it at the moment as 2 weeks ago)

**Comment by dralley** [comment]
When I try to run the tests I get a bunch of ConnectionRefused errors and assertion failures that look like this

```  │ E           AssertionError: assert 'Content-Type' in {'cache-control': 'no-cache', 'content-length': '14', 'content-type': 'application/json; charset=utf-8', 'date': 'Fri, 01 May 2020 03:54:48 GMT'}
```

**Comment by jdm** [comment]
What if you run `./mach test-wpt --timeout-multiplier=4 --headless /webdriver/tests/get_element_rect/get.py`?

**Comment by dralley** [comment]
@asajeffrey yes, it looks like the test is setting the ```new_size``` to 0x0

```
 0:05.10 pid:469525 [ports/glutin/headless_window.rs:84] self.inner_size.get() = 800x600
 0:05.10 pid:469525 [ports/glutin/headless_window.rs:85] new_size = 0x0
```

**Comment by jdm** [comment]
One workaround might be to always clamp the size to a 1x1 minimum in headless mode.

**Comment by dralley** [comment]
Should I move forwards with that workaround or is there a more "proper" solution?

**Comment by jdm** [comment]
Let's give the workaround a try.

**Comment by dralley** [comment]
@jdm Pushed.  However, that created web-platform-tests PR needs to be renamed -- I probably should have pushed that in a separate PR.

**Comment by jdm** [comment]
https://community-tc.services.mozilla.com/tasks/MZPrUEYERC6aFlVHiMw99A/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FMZPrUEYERC6aFlVHiMw99A%2Fruns%2F0%2Fartifacts%2Fpublic%2Ffiltered-wdspec-errorsummary.log shows a bunch of timeouts now. I wonder if we never reset the window size to a non-1x1 size?

**Comment by dralley** [comment]
Possibly - how would I resolve that?

**Comment by jdm** [comment]
1. reproduce the problem by running the tests locally
1. store a new member in the constellation for the original window size and set it during construction
1. add a new ResetWindowSize message to WebDriverCommandMsg
1. send a [ResetWindowSize message](https://github.com/servo/servo/blob/master/components/webdriver_server/lib.rs#L715-L719) from the webdriver server as part of `handle_new_session`
1. handle the ResetWindowSize message in the constellation by sending a [EmbedderMsg::ResizeTo](https://github.com/servo/servo/blob/033156b96125deec10706b9e03643ce2938864a0/components/constellation/constellation.rs#L4379-L4382) with the default window size
1. see if that affects the test results

**Comment by mrobinson** [comment]
I have rebased this change and made some minor edits, creating a fake event queue, in case future events need to be pushed to the queue.

**Review by mrobinson — APPROVED** [review]
It looks like this is good to go, modulo a test which seems to be failing for every PR. I'll try sending it to the MQ.
