### PR TITLE
layout: Fix ordering of padding, border, and margin in inline BiDi

### LINKED ISSUE #6092: Incorrect layout for inline-block elements in RTL flows
In this test case, the div should appear at the top right of the page.  In Servo it does not appear anywhere on-screen:

``` html
<html>
  <head>
    <style>
      body { direction: rtl; }
      div {
        display: inline-block;
        border: 1px solid red;
        width: 100px;
        height: 100px;
      }
    </style>
  </head>
  <body>
    <div></div>
  </body>
</html>
```

This is probably caused by similar issues to #6006.

### PR DESCRIPTION
**Pull request by d-desiatkin**
Previously visual order of inline box elements was not maintained in Layout 2020.
https://drafts.csswg.org/css-writing-modes-4/#bidi-fragment-boxes
2.4.5.2. Box Model of Reordering-induced Box Fragments

This commit adds naive implementation and allows following WPT tests to pass:
https://wpt.fyi/results/css/CSS2/box?label=master&product=chrome%5Bexperimental%5D&product=edge%5Bexperimental%5D&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&product=servo&aligned

Probably we still can have some problems. Especially related to vertical writing modes. 
That issues I would like to solve in the separate commits.

Manual testing on local machine on following folder provided following results:
tests/wpt/tests/css/CSS2
Ran 6261 tests finished in 1425.6 seconds.
  • 8 ran as expected.
  • 65 tests failed unexpectedly
  • 35 tests passed unexpectedly
  
That is fairly unexpected. Will see what github actions will provide.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] There are tests for these changes

### CODE REVIEW

File: components/layout_2020/flow/inline/mod.rs [hunk 1]
```diff
@@ -92,6 +92,7 @@ use serde::Serialize;
 use servo_arc::Arc;
 use style::computed_values::text_wrap_mode::T as TextWrapMode;
 use style::computed_values::vertical_align::T as VerticalAlign;
+use style::computed_values::direction::T as ComputedCSSDircetion;
```
Comment (nicoburns) [inline components/layout_2020/flow/inline/mod.rs:95]: You have a typo here. `Dircetion` instead of `Direction`

Comment (d-desiatkin) [reply components/layout_2020/flow/inline/mod.rs:95]: TY. Will fix

Comment (d-desiatkin) [reply components/layout_2020/flow/inline/mod.rs]: Fixed. Want to ask what is the policy here. I like to solve small typos by git amend and rewriting the original commit with forced push. Is it okay here? Or would you prefer to have separate commit?

Comment (nicoburns) [reply components/layout_2020/flow/inline/mod.rs]: Either is fine! CI deals with force pushes to branches, and we squash merge so extra commits disappear anyway.

File: components/layout_2020/flow/inline/mod.rs [hunk 2]
```diff
@@ -727,15 +728,27 @@ impl<'layout_dta> InlineFormattingContextLayout<'layout_dta> {
...
                 inline_box_state.pbm.border.inline_start +
                 inline_box_state.pbm.margin.inline_start.auto_is(Au::zero);
             self.current_line_segment
                 .line_items
-                .push(LineItem::LeftInlineBoxPaddingBorderMargin(
-                    inline_box.identifier,
-                ));
+                .push(match css_direction {
+                        ComputedCSSDirection::Ltr => {
+                            LineItem::LeftInlineBoxPaddingBorderMargin(inline_box.identifier)
```
Comment (Loirooriol) [inline components/layout_2020/flow/inline/mod.rs:745]: I think these should be renamed to `InlineStartBoxPaddingBorderMargin` and `InlineEndBoxPaddingBorderMargin` or such, then you wouldn't need to check the direction here.

Instead, https://github.com/servo/servo/blob/bd37d5496d747c7106b2d8d73dca1212421d82b4/components/layout_2020/flow/inline/line.rs#L379-L389 should just swap if the direction doesn't match the containing block.

**Review by Loirooriol — CHANGES_REQUESTED** [review]

File: components/layout_2020/flow/inline/mod.rs (hunk 2 above)
Comment (d-desiatkin) [reply components/layout_2020/flow/inline/mod.rs:745]: I don't think that it is proper change. Because if we change order of items in inline_items container. Then inline boxes borders could potentially participate in general procedure of text runs and inline items bidi reordering.
I believe that we will need it in the future to pass this test.
image

Comment (d-desiatkin) [reply components/layout_2020/flow/inline/mod.rs:745]: Currently there are multiple problems why this test fail. Issues with white space collapsing. Issues with inline boxes borders reordering. I need to investigate but my current idea is that borders should also participate in reordering procedure.

Comment (d-desiatkin) [reply components/layout_2020/flow/inline/mod.rs:745]: So can we have some talk regarding this issue? 
I will need to prepare for such talk. Will reread documentation once again and make some notes.

I understand that in the Draft authors explicitly talk about fragments. And initially I have idea of implementing it near the place that you suggest. TBH I haven't find exactly the place that you stated in comment.

So we just need to understand will boxes ever participate in reordering process together with text_runs

Comment (d-desiatkin) [reply components/layout_2020/flow/inline/mod.rs:745]: @Loirooriol

Comment (d-desiatkin) [reply components/layout_2020/flow/inline/mod.rs:745]: image

Comment (d-desiatkin) [reply components/layout_2020/flow/inline/mod.rs:745]: So currently there is some confusion in specs I believe. It would be cool if CSS committee can decide where should we apply bidi reordering and clearly state that. Theoretically it could be done on fragments level purely. Or we need more clearly define 2 separate procedures.
I.E text_runs bidi reordering and box fragments reordering as a separate term.

Comment (d-desiatkin) [reply components/layout_2020/flow/inline/mod.rs:745]: @Loirooriol Look into Zulip.
Maybe I should to the opposite and extract this from fragment level to inline_items level?

Comment (d-desiatkin) [reply components/layout_2020/flow/inline/mod.rs:745]: I can experiment tomorrow by adding control symbols to each inline item. Instead of simple copy of the last bidi level. And look into general behavior

Comment (Loirooriol) [reply components/layout_2020/flow/inline/mod.rs:745]: > I don't think that it is proper change. Because if we change order of items in inline_items container

I'm confused, I didn't mean to reorder anything? I will push the change that I meant.

**Review by mrobinson — APPROVED** [review]

**Comment by Loirooriol** [comment]
> These changes fix https://github.com/servo/servo/issues/6092 https://github.com/servo/servo/issues/7681 https://github.com/servo/servo/issues/14750

Please don't claim to fix layout 2013 specific bugs that have already been fixed in layout 2020.

**Review by Loirooriol — APPROVED** [review]
