### PR TITLE
script: Fix "RefCell already borrowed" for DOMString in DataTransfer.getData

### LINKED ISSUE #44599: panic: RefCell already borrowed (thread Script#1, at components/script_bindings/domstring.rs:341)
Minimal testcase:

```html
<!DOCTYPE html>
<script>(new DataTransfer()).getData("");</script>
```

System: Linux
Version: Version: Servo 0.1.0-111ff0602
Command: `./servo/servoshell`

```
RefCell already borrowed (thread Script#1, at components/script_bindings/domstring.rs:341)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::panic_with_hook
   3: std::panicking::panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: __rustc::rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::cell::panic_already_borrowed::do_panic::runtime
   8: core::cell::panic_already_borrowed
   9: script_bindings::domstring::DOMString::ensure_rust_string
  10: <script_bindings::domstring::DOMString as core::clone::Clone>::clone
  11: script_bindings::codegen::GenericBindings::DataTransferBinding::DataTransfer_Binding::getData::{{closure}}
  12: mozjs::panic::wrap_panic
  13: script_bindings::codegen::GenericBindings::DataTransferBinding::DataTransfer_Binding::getData
  14: CallJitMethodOp
  15: script_bindings::utils::generic_call
  16: script_bindings::utils::generic_method
  17: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  18: _ZN2js9InterpretEP9JSContextRNS_8RunStateE
  19: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  20: _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEENS3_IP8JSObjectEENS2_13MutableHandleINS2_5ValueEEE
  21: _Z16JS_ExecuteScriptP9JSContextN2JS6HandleIP8JSScriptEENS1_13MutableHandleINS1_5ValueEEE
  22: script::dom::global_scope_script_execution::evaluate_script
  23: script::dom::global_scope_script_execution::<impl script::dom::globalscope::GlobalScope>::run_a_classic_script
  24: script::dom::html::htmlscriptelement::HTMLScriptElement::execute
  25: script::dom::html::htmlscriptelement::HTMLScriptElement::prepare
  26: script::dom::servoparser::ServoParser::parse_sync
  27: <script::dom::servoparser::ParserContext as script::network_listener::FetchResponseListener>::process_response_eof
  28: script::script_thread::ScriptThread::handle_msg_from_script
  29: script::script_thread::ScriptThread::handle_msgs::{{closure}}
  30: script::script_thread::ScriptThread::handle_msgs
  31: std::sys::backtrace::__rust_begin_short_backtrace
  32: core::ops::function::FnOnce::call_once{{vtable.shim}}
  33: std::sys::thread::unix::Thread::new::thread_start
  34: start_thread
             at ./nptl/pthread_create.c:447:8
  35: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
```

### PR DESCRIPTION
**Pull request by SimonSapin**
`match_domstring_ascii!` presumably borrows that RefCell, and `.clone()` borrows it again.

Testing: adding a new crashtest
Fixes: https://github.com/servo/servo/issues/44599

### CODE REVIEW

**Comment by Narfinger** [comment]
Mhhh. I don't quite like the syntax but I don't know what would be better. Can you write a comment for people unfamiliar with this syntax?
Also there might be more cases of similar errors. Can you check that?
Also it might be a good idea to add to the documentation of match_domstring_ascii that it borrows the refcell.

**Comment by SimonSapin** [comment]
The same flow control could be done with more familiar syntax if the labelled block is extracted into a function or closure, and `break` replaced by `return`. But I’m not sure it’s worth the verbosity

I looked at all 25 uses of `match_domstring_ascii!`, none of them access the string while it’s being matched. I’ll add a comment

**Comment by SimonSapin** [comment]
I’ve replaced the `break`’ing out of a block with an `Option`, what do you think?

**Comment by Narfinger** [comment]
Yeah I think I like this more. Thanks!

File: components/script/dom/datatransfer/datatransfer.rs [hunk 1]
```diff
@@ -188,15 +188,21 @@ impl DataTransferMethods<crate::DomTypeHolder> for DataTransfer {
...
+                Some("text/uri-list")
             },
-            _ => format.clone(),);
+            _ => None,
+        );
+        let type_ = if let Some(t) = type_override {
+            DOMString::from(t)
+        } else {
+            format.clone()
+        };
```
Comment (mrobinson) [inline components/script/dom/datatransfer/datatransfer.rs]: This could possibly be:


```suggestion
        let type_ = type_override
            .map(DOMString::from)
            .unwrap_or_else(|| format.clone);
```

**Review by mrobinson — APPROVED** [review]

File: components/script/dom/datatransfer/datatransfer.rs (hunk 1 above)
Comment (SimonSapin) [reply components/script/dom/datatransfer/datatransfer.rs]: Subjectively, when code is needed in both branches anyway I don’t find that using methods with callbacks is better than matching. But in this case I reduced this line to just `unwrap_or_else` by moving `DOMString::from` to where the option is created. (Also took the opportunity to add a comment)
