### PR TITLE
Fix hashchange only queue when fragment actually changes

### LINKED ISSUE #41304: `hashchange` shouldn't fire when the new hash is exactly the same as the old
**Describe the bug:**
See title.

**To Reproduce:**
Test case
```html
<!doctype html>
<a href="#foo">CLICK THIS</a>
<h1 id="Y">You clicked it 0 times</h1>
<script>
  let P = 0
window.onhashchange = () => {
  Y.innerText = `You clicked it ${++P} times`
}
</script>
```
Click the link three times. The message stops at 1 on Firefox but keeps counting up on Servo.

**Platform:**
Win 10

### PR DESCRIPTION
**Pull request by Taym95**
Fix hashchange only queue when fragment actually changes

Testing: tested it manually for now. 
Fixes: #41304

### CODE REVIEW

File: components/script/dom/window.rs [hunk 1]
```diff
@@ -2998,25 +2998,45 @@ impl Window {
...
+                // DOM manipulation task source given document's relevant global object to fire an event named hashchange at
+                // document's relevant global object, using HashChangeEvent, with the oldURL attribute initialized to the
+                // serialization of oldURL and the newURL attribute initialized to the serialization of entry's URL.
+                let old_fragment = doc.url().fragment().map(ToOwned::to_owned);
+                let new_fragment = load_data.url.fragment().map(ToOwned::to_owned);
+
+                if old_fragment != new_fragment {
+                    let webdriver_sender_for_task = webdriver_sender.clone();
+                    let task = task!(hashchange_event: move || {
+                        println!("hashchange task: firing hashchange old_url={} new_url={}", old_url, new_url);
```
Comment (simonwuelker) [inline components/script/dom/window.rs]: there's a leftover println here

Comment (Taym95) [reply components/script/dom/window.rs]: Ah yes that was debug println

**Comment by Taym95** [comment]
actually I will try to add test for this

**Review by TimvdLippe — APPROVED** [review]
