### PR TITLE
make sure proper frame tree is sent when iframes change

### LINKED ISSUE #18101: Link hitboxes do not move when scrolling page
Steps to reproduce:

1. Load web page that scrolls vertically and has clickable links near the bottom of the page.
2. Scroll down the page.
3. Try to click a link.
4. The link doesn't work properly.

I believe this is a recent regression as I do not recall running into this issue previously. Tested in Windows 10.

### PR DESCRIPTION
**Pull request by paulrouget**
We ran into a hittest issue because the frame tree was not correctly updated after #17425.

The frame tree should be updated on tab change (via send_frame_tree) or when the frame sub tree changes and it's the active one (via update_frame_tree_if_active).

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #18101 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18149)

### CODE REVIEW

File: components/constellation/constellation.rs [hunk 1]
```diff
@@ -2923,12 +2913,25 @@ impl<Message, LTF, STF> Constellation<Message, LTF, STF>
...
-                    browsing_context_id = pipeline.browsing_context_id;
+                    top_level_browsing_context_id = pipeline.top_level_browsing_context_id;
                     break;
                 },
             }
         }
 
+        // Only send the frame tree if it's the active one or if no frame tree
+        // has been sent yet.
+        if self.active_browser_id == None || Some(top_level_browsing_context_id) == self.active_browser_id {
```
Comment (cbrewster) [inline components/constellation/constellation.rs]: nit: `self.active_browser_id.is_none()`

File: components/constellation/constellation.rs [hunk 2]
```diff
@@ -2923,12 +2913,25 @@ impl<Message, LTF, STF> Constellation<Message, LTF, STF>
...
+            self.send_frame_tree(top_level_browsing_context_id);
+        }
+
+    }
+
+    // Send the current frame tree to compositor
```
Comment (cbrewster) [inline components/constellation/constellation.rs]: nit: `///`

File: components/constellation/constellation.rs [hunk 3]
```diff
@@ -2908,12 +2898,12 @@ impl<Message, LTF, STF> Constellation<Message, LTF, STF>
         })
     }
 
-    // Send the current frame tree to compositor
-    fn send_frame_tree(&mut self, top_level_browsing_context_id: TopLevelBrowsingContextId) {
+    // Re-send the frame tree to the compositor.
```
Comment (cbrewster) [inline components/constellation/constellation.rs]: nit: `///`

**Review by cbrewster — APPROVED** [review]
LGTM.
