### PR TITLE
Forward CSP violations from load_whole_resource to parent event loop

### LINKED ISSUE #37027: Propagate CSP violations from `load_whole_resource` to the parent global scope to handle `worker-src` violations
**Describe the bug:**
No `worker-src` violations fire, since we don't report the CSP violations in the listener in `fetch::load_whole_resource`.

**To Reproduce:**
Implement the handler of `FetchResponseMsg::ProcessCspViolations(requestId, violations)`. Here, we cannot use the `global: &GlobalScope` as supplied, since that points to the globalscope of the worker. Instead, the CSP violations should be reported to the `current_global` which created the worker. However, you cannot pass in the `current_global`, since that lives outside of the thread (for example in `DedicatedWorkerGlobalScope::run_worker_scope`). Therefore, we need to send a message from the worker to the `parent_event_loop_sender` to be able to pass on the CSP violations.

To test: run `./mach test-wpt tests/wpt/tests/content-security-policy/worker-src/`

**Platform:**
n/a

Part of #4577

### PR DESCRIPTION
**Pull request by TimvdLippe**
Any CSP violations happening when loading a worker should be reported
on the global of the document that creates the worker. Since workers
run in different threads, we can't pass in this parent global into
the worker global scope. Instead, we need to send a message to the
parent event loop to report it on the correct global.

Part of https://github.com/servo/servo/issues/4577
Fixes https://github.com/servo/servo/issues/37027

### CODE REVIEW

File: components/script/dom/dedicatedworkerglobalscope.rs [hunk 1]
```diff
@@ -178,6 +178,22 @@ impl QueuedTaskConversion for DedicatedWorkerScriptMsg {
...
+}
+
+impl CspViolationsProcessor for DedicatedWorkerCspProcessor {
+    fn process_csp_violations(&self, violations: Vec<Violation>) {
+        self.parent_event_loop_sender
+            .send(CommonScriptMsg::ReportCspViolations(
+                self.pipeline_id,
+                violations,
+            ))
+            .unwrap();
```
Comment (jdm) [inline components/script/dom/dedicatedworkerglobalscope.rs]: Instead of unwrapping the error, let's ignore it with `let _ = ..`.

File: components/script/dom/workerglobalscope.rs [hunk 2]
```diff
@@ -690,6 +692,7 @@ impl WorkerGlobalScope {
                     reports_chan.send(ProcessReports::new(reports));
                 });
             },
+            CommonScriptMsg::ReportCspViolations(..) => {},
```
Comment (jdm) [inline components/script/dom/workerglobalscope.rs]: This seems surprising. What happens if a worker spawns another worker but that second worker is blocked by CSP? Does this line mean we silently drop that violation report?

File: components/script/fetch.rs [hunk 3]
```diff
@@ -337,11 +337,16 @@ fn fill_headers_with_metadata(r: DomRoot<Response>, m: Metadata, can_gc: CanGc)
     r.set_redirected(m.redirected);
 }
 
+pub(crate) trait CspViolationsProcessor {
+    fn process_csp_violations(&self, violations: Vec<Violation>);
+}
+
 /// Convenience function for synchronously loading a whole resource.
-pub(crate) fn load_whole_resource(
+pub(crate) fn load_whole_resource<P: CspViolationsProcessor>(
```
Comment (jdm) [inline components/script/fetch.rs]: We can use `dyn` instead of a generic type here. That will reduce code size and the performance difference is not important here.

File: components/script/dom/workerglobalscope.rs (hunk 2 above)
Comment (TimvdLippe) [reply components/script/dom/workerglobalscope.rs]: I thought that `CommonScriptMsg` could also be sent from the parent to the child worker. E.g. if a window creates a worker, then the window can also send `CommonScriptMsg::ReportCspViolations` to that worker. I didn't know any use case for it, hence I hadn't implemented this method yet. Is my understanding wrong for `CommonScriptMsg`? I will search for a WPT test that has nested workers to see if we can test this.

Comment (TimvdLippe) [reply components/script/dom/workerglobalscope.rs]: Can confirm that we should have implemented this. Latest amend does so and also adds a WPT test (this was untested as far as I know)

File: components/script/dom/workerglobalscope.rs [hunk 4]
```diff
@@ -701,3 +707,9 @@ impl WorkerGlobalScope {
             .cancel_all_tasks_and_ignore_future_tasks();
     }
 }
+
+struct WorkerCspProcessor {}
```
Comment (jdm) [inline components/script/dom/workerglobalscope.rs]: This means we will receive no violation reports when importScripts is blocked by CSP. Shouldn't we store a way to communicate with the WorkerGlobalScope here? I think a DomRoot will do the trick.

**Review by jdm — COMMENTED** [review]
The new test is great! I just want to make sure I understand the intention behind WorkerCspProcessor, since it looks suspicious.

File: components/script/dom/workerglobalscope.rs (hunk 4 above)
Comment (TimvdLippe) [reply components/script/dom/workerglobalscope.rs]: Sure, I thought doing things incrementally here as I wasn't sure where this would be used yet. Added it and updated test expectations.

**Review by jdm — APPROVED** [review]

**Comment by TimvdLippe** [comment]
Uh oh, are these generated tests potentially flaky?

**Comment by TimvdLippe** [comment]
Can confirm that when running `./mach test-wpt content-security-policy/gen/top.http-rp/worker-src-none/worker-import-data.https.html --rerun=2` the first test always passes and the second test always fails. Probably related to cleaning up some test data results

**Comment by TimvdLippe** [comment]
We appear to suffer from similar issues as Firefox has with worklets. Therefore, I updated the test infrastructure to add a tiny timeout. With that, I can't observe any failures anymore.

**Review by jdm — APPROVED** [review]
Good find!
