### PR TITLE
script: Pass more information to the `MouseEvent` constructor

### LINKED ISSUE #37601: Major benchmark regression after 3774ef00d48fb9a6fdcb87fcea4750ba3c5fe147
On my usual benchmark setup (https://browserbench.org/Speedometer2.1), the score starting from that change is ~20, compared to ~52 before.

cc @mrobinson

### PR DESCRIPTION
**Pull request by mrobinson**
- Instead of eagerly computing `pageX` and `pageY`, collect the offset
  from the content's initial containing block in the compositor and pass
  that information through to `MouseEvent`. This prevents a layout flush
  that was happening when eagerly trying to fetch `Document` scroll
  offsets.
- Pass keyboard modifiers properly to `MouseEvent`.
- Now all this information is stored and passed as `Point2D` (typed) and
  `Modifiers` which greatly reduces the amount of arguments that need to
  be passed around.

Testing: It is difficult to test input events as they require WebDriver which
isn't completely working yet. I have manually run Speedometer 2.1 and I have
verified that this fixes the regression from #37601.
Fixes: #37601.

### CODE REVIEW

File: components/compositing/compositor.rs [hunk 1]
```diff
@@ -336,11 +336,23 @@ impl ServoRenderer {
...
                     pipeline_id,
-                    point_in_viewport: item.point_in_viewport.to_untyped(),
-                    point_relative_to_item: item.point_relative_to_item.to_untyped(),
+                    point_in_viewport: Point2D::from_untyped(item.point_in_viewport.to_untyped()),
+                    point_relative_to_initial_containing_block: Point2D::from_untyped(
+                        point_in_initial_containing_block,
+                    ),
+                    point_relative_to_item: Point2D::from_untyped(
+                        item.point_relative_to_item.to_untyped(),
+                    ),
```
Comment (mrobinson) [inline components/compositing/compositor.rs:355]: This dance needs to happen because WebRender deals with `LayoutPixel`, but `script` and `stylo` deal with `CSSPixel`. These are the same.

File: components/script/dom/pointerevent.rs [hunk 2]
```diff
@@ -247,6 +234,10 @@ impl PointerEventMethods<crate::DomTypeHolder> for PointerEvent {
     ) -> DomRoot<PointerEvent> {
         let bubbles = EventBubbles::from(init.parent.parent.parent.parent.bubbles);
         let cancelable = EventCancelable::from(init.parent.parent.parent.parent.cancelable);
+        let page_point = Point2D::new(
+            window.ScrollX() + init.parent.clientX,
+            window.ScrollY() + init.parent.clientY,
+        );
```
Comment (mrobinson) [inline components/script/dom/pointerevent.rs:240]: There's no way of getting around a layout flush in this case, but it is much less common.

**Review by mukilan — APPROVED** [review]
