### PR TITLE
Adjust CSP for top-level image documents

### LINKED ISSUE #38180: Unexpected CSP blocking load for some images
STR:
Load https://pholiota.us-west.host.bsky.network/xrpc/com.atproto.sync.getBlob?did=did%3Aplc%3Af25qr3njhaoeolu46vylylju&cid=bafkreif2gljqvaunuxoo3dtynzbudmx4jimh2jguxypg76l3gvrf2ajkki with `./mach run https://pholiota.us-west.host.bsky.network/xrpc/com.atproto.sync.getBlob?did=did%3Aplc%3Af25qr3njhaoeolu46vylylju&cid=bafkreif2gljqvaunuxoo3dtynzbudmx4jimh2jguxypg76l3gvrf2ajkki` 

This fails in Servo with this error logged:
`[2025-07-20T05:19:03Z WARN  net::fetch::methods] Request blocked by CSP`

@TimvdLippe do you understand why? This url loads fine in Firefox and Brave.

### PR DESCRIPTION
**Pull request by webbeef**
Allows loading of document images even when they have a sandbox CSP rule to align with other browsers.

Testing: No wpt failures: https://github.com/webbeef/servo/actions/runs/16403138806
Fixes: #38180

### CODE REVIEW

**Comment by webbeef** [comment]
Patch from @TimvdLippe in https://github.com/servo/servo/issues/38180#issuecomment-3094617799

File: components/script/dom/servoparser/mod.rs [hunk 1]
```diff
@@ -1001,11 +1000,11 @@ impl FetchResponseListener for ParserContext {
...
                 },
                 Some(_) => {},
-                None => {},
+                None => parser.document.set_csp_list(csp_list),
             },
             (mime::TEXT, mime::XML, _) |
             (mime::APPLICATION, mime::XML, _) |
-            (mime::APPLICATION, mime::JSON, _) => {},
+            (mime::APPLICATION, mime::JSON, _) => parser.document.set_csp_list(csp_list),
             (mime::APPLICATION, subtype, Some(mime::XML)) if subtype == "xhtml" => {},
```
Comment (jdm) [inline components/script/dom/servoparser/mod.rs]: We should use the CSP result in the branch as well.

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
I'm having trouble imagining how we can write an automated test for top-level pages like this, so let's merge it.

**Comment by TimvdLippe** [comment]
Can we test this by having a WPT test include an iframe which only loads the image. The image has CSP headers and then we check the iframe contents if it loaded?

**Comment by jdm** [comment]
Hmm, that does sound plausible. Probably not something that could be upstrramer, but at least a regression test under the mozilla directory.

**Comment by jdm** [comment]
https://github.com/servo/servo/pull/38191
