### PR TITLE
Handle all `white-space` values when intrinsically sizing an IFC

### LINKED ISSUE #33335: Wrong min-content size for `white-space: nowrap`
```html
<!DOCTYPE html>
<div style="width: 0">
  <div style="display: inline-block; border: solid; white-space: nowrap">
    A B C D E F G H I J K L M N O P Q R S T U V W X Y Z</td>
  </div>
</div>
```

| | |
| - | - |
| Expected |  |
| Actual |  |

https://github.com/servo/servo/blob/7e493ba865ef7e748ce3b14d59117315a0ec8aee/components/layout_2020/flow/inline/mod.rs#L2344

### PR DESCRIPTION
**Pull request by Loirooriol**
There were various cases like `text-wrap-mode: nowrap` and
`white-space-collapse: break-spaces` that weren't handled well.

Fixes #33335

flexbox_flex-formatting-interop.html fails now because we don't support
`table-layout: fixed`.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #33335
- [X] There are tests for these change

### CODE REVIEW

File: components/fonts/glyph.rs [hunk 1]
```diff
@@ -446,6 +446,11 @@ pub struct GlyphStore {
     /// Whether or not this glyph store contains only glyphs for whitespace.
     is_whitespace: bool,
 
+    /// Whether or not this glyph store ends with whitespace glyphs.
+    /// Typically whitespace glyphs are placed on a separate store,
```
Comment (mrobinson) [inline components/fonts/glyph.rs:450]:
```suggestion
    /// Typically whitespace glyphs are placed in a separate store,
```

File: components/layout_2020/flow/inline/mod.rs [hunk 2]
```diff
@@ -2345,31 +2350,33 @@ impl<'layout_data> ContentSizesComputation<'layout_data> {
...
                                 continue;
                             }
                         }
 
                         self.commit_pending_whitespace();
                         self.add_inline_size(advance);
-                        self.had_content_yet = true;
+                        if can_wrap && run.glyph_store.ends_with_whitespace() {
+                            self.line_break_opportunity();
+                        }
```
Comment (mrobinson) [inline components/layout_2020/flow/inline/mod.rs:2379]: Does this only happen with `WhiteSpaceCollapse::BreakSpaces`? If so, it might be nice to leave a comment here as that is really what allows the line break opportunity after white space.

File: components/layout_2020/flow/inline/mod.rs [hunk 3]
```diff
@@ -2408,25 +2414,26 @@ impl<'layout_data> ContentSizesComputation<'layout_data> {
     }
 
     fn line_break_opportunity(&mut self) {
+        self.pending_whitespace.min_content = Au::zero();
```
Comment (mrobinson) [inline components/layout_2020/flow/inline/mod.rs:2417]: This is white space that is hanging right? I would put a comment. Note that we don't always properly hang white space in layout yet.

File: components/layout_2020/flow/inline/text_run.rs [hunk 4]
```diff
@@ -245,17 +249,17 @@ impl TextRunSegment {
...
                 }
 
                 slice.end = whitespace.start;
             }
 
             // If there's no whitespace and `word-break` is set to `keep-all`, try increasing the slice.
             // TODO: This should only happen for CJK text.
-            let can_break_anywhere = text_style.word_break == WordBreak::BreakAll ||
-                text_style.overflow_wrap == OverflowWrap::Anywhere ||
-                text_style.overflow_wrap == OverflowWrap::BreakWord;
```
Comment (mrobinson) [inline components/layout_2020/flow/inline/text_run.rs:257]: Oof. Thanks for this cleanup,.

File: tests/wpt/tests/css/css-text/white-space/break-spaces-with-word-break-001.html [hunk 5]
```diff
@@ -0,0 +1,24 @@
+<!DOCTYPE html>
+<meta charset="utf-8">
+<title>CSS Text Test: white-space:break-spaces + word-break:keep-all</title>
+<link rel="author" title="Oriol Brufau" href="mailto:obrufau@igalia.com">
+<link rel="help" href="https://drafts.csswg.org/css-text-4/#valdef-white-space-collapse-break-spaces">
+<link rel="help" href="https://drafts.csswg.org/css-text-4/#valdef-word-break-keep-all">
+<link rel="match" href="../../reference/ref-filled-green-100px-square.xht">
+<meta name="assert" content="break-spaces + keep-all do allow a break after space.">
```
Comment (mrobinson) [inline tests/wpt/tests/css/css-text/white-space/break-spaces-with-word-break-001.html:8]:
```suggestion
<meta name="assert" content="break-spaces + keep-all does allow a break after space.">
```

This is a nit obviously, but it made me consider something I never have before. The result of an expression with "plus" is singular and the result of an "and" expression is plural.

**Review by mrobinson — APPROVED** [review]
Nice!

File: components/layout_2020/flow/inline/mod.rs (hunk 2 above)
Comment (Loirooriol) [reply components/layout_2020/flow/inline/mod.rs:2379]: Yes, the condition can hold in other cases but they are handled above with a `continue`, so by this point the condition should only be true for `WhiteSpaceCollapse::BreakSpaces`.

File: components/layout_2020/flow/inline/mod.rs (hunk 3 above)
Comment (Loirooriol) [reply components/layout_2020/flow/inline/mod.rs:2417]: Yes, either hanging (e.g. `white-space: pre-wrap`) or removed (e.g. `white-space: normal`).
If the space needs to be included, then `commit_pending_whitespace()` should be called first.

File: tests/wpt/tests/css/css-text/white-space/break-spaces-with-word-break-001.html (hunk 5 above)
Comment (Loirooriol) [reply tests/wpt/tests/css/css-text/white-space/break-spaces-with-word-break-001.html:8]: Makes sense. I just copied this from another test.

**Comment by Loirooriol** [comment]
There was a windows-specific unit test that needed to pass the new parameter.
