### PR TITLE
script: replace load_whole_resource with async fetch when constructing a worker

### LINKED ISSUE #39621: Replace synchronous load_whole_resource in worker initialization
https://github.com/servo/servo/blob/9e380614eef25828bfab9c106870e619791fffa3/components/script/dom/dedicatedworkerglobalscope.rs#L521-L543

The current implementation will probably make solving #39619 more complicated. I'd like to try a model where we start an asynchronous fetch and then enter the regular worker event loop (https://github.com/servo/servo/blob/9e380614eef25828bfab9c106870e619791fffa3/components/script/dom/dedicatedworkerglobalscope.rs#L584-L591), and we move the existing code that handles the response into the `process_response_eof` handler of the `FetchResponseListener` implementation.

Useful model pieces:
* starting a fetch: https://github.com/servo/servo/blob/9e380614eef25828bfab9c106870e619791fffa3/components/script/fetch.rs#L244-L263
* handling the asynchronous response: https://github.com/servo/servo/blob/9e380614eef25828bfab9c106870e619791fffa3/components/script/dom/xmlhttprequest.rs#L102

I would expect unchanged test results for `./mach test-wpt tests/wpt/tests/workers` (but any unexpected results from tests in workers/modules can be ignored until #39619 is fixed).

### PR DESCRIPTION
**Pull request by Gae24**
Testing: no behaviour changes in tests result should happen
Fixes: #39621

### CODE REVIEW

**Comment by Gae24** [comment]
Fetch was implemented for `WorkerGlobalScope`, since it could be reused for `ServiceWorker` and `importScripts` too.

Needs more work:
```
   0: servoshell::backtrace::print
             at /servo/ports/servoshell/backtrace.rs:18:5
   1: servoshell::panic_hook::panic_hook
             at /servo/ports/servoshell/panic_hook.rs:40:17
   2: core::ops::function::Fn::call
             at /.rustup/toolchains/1.89.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79:5
   3: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/alloc/src/boxed.rs:1980:9
      std::panicking::rust_panic_with_hook
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:841:13
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:699:13
   5: std::sys::backtrace::__rust_end_short_backtrace
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/sys/backtrace.rs:168:18
   6: __rustc::rust_begin_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:697:5
   7: core::panicking::panic_fmt
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/panicking.rs:75:14
   8: script_bindings::inheritance::Castable::is
             at /servo/components/script_bindings/inheritance.rs:24:9
   9: script_bindings::inheritance::Castable::downcast
             at /servo/components/script_bindings/inheritance.rs:47:17
  10: script::dom::globalscope::GlobalScope::task_manager
             at /servo/components/script/dom/globalscope.rs:2798:14
  11: script::dom::dedicatedworkerglobalscope::DedicatedWorkerGlobalScope::replace_worker
             at /servo/components/script/dom/dedicatedworkerglobalscope.rs:598:14
  12: <script::dom::dedicatedworkerglobalscope::AutoWorkerReset as core::ops::drop::Drop>::drop
             at /servo/components/script/dom/dedicatedworkerglobalscope.rs:92:14
  13: core::ptr::drop_in_place<script::dom::dedicatedworkerglobalscope::AutoWorkerReset>
             at /.rustup/toolchains/1.89.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:799:1
  14: script::dom::dedicatedworkerglobalscope::DedicatedWorkerGlobalScope::handle_mixed_message
             at /servo/components/script/dom/dedicatedworkerglobalscope.rs:674:13
  15: <script::dom::dedicatedworkerglobalscope::DedicatedWorkerGlobalScope as script::dom::abstractworkerglobalscope::WorkerEventLoopMethods>::handle_event
             at /servo/components/script/dom/dedicatedworkerglobalscope.rs:232:14
  16: script::dom::abstractworkerglobalscope::run_worker_event_loop
             at /servo/components/script/dom/abstractworkerglobalscope.rs:88:26
  17: script::dom::dedicatedworkerglobalscope::DedicatedWorkerGlobalScope::run_worker_scope::{{closure}}::{{closure}}
             at /servo/components/script/dom/dedicatedworkerglobalscope.rs:538:33
  18: profile_traits::mem::ProfilerChan::run_with_memory_reporting
             at /servo/components/shared/profile/mem.rs:146:9
  19: script::dom::dedicatedworkerglobalscope::DedicatedWorkerGlobalScope::run_worker_scope::{{closure}}
             at /servo/components/script/dom/dedicatedworkerglobalscope.rs:530:22
  20: std::sys::backtrace::__rust_begin_short_backtrace
             at /.rustup/toolchains/1.89.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:152:18
  21: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /.rustup/toolchains/1.89.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:559:17
  22: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /.rustup/toolchains/1.89.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
  23: std::panicking::catch_unwind::do_call
             at /.rustup/toolchains/1.89.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:589:40
  24: __rust_try
  25: std::panicking::catch_unwind
             at /.rustup/toolchains/1.89.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:19
      std::panic::catch_unwind
             at /.rustup/toolchains/1.89.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:359:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /.rustup/toolchains/1.89.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:557:30
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /.rustup/toolchains/1.89.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/alloc/src/boxed.rs:1966:9
      std::sys::pal::unix::thread::Thread::new::thread_start
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/sys/pal/unix/thread.rs:107:17
  28: start_thread
  29: __GI___clone3
Attempting to interact with DOM objects after JS runtime has shut down. (thread WW:web-platform.test:8000/workers/constructors/Worker/does-not-exist.js, at /servo/components/script_bindings/inheritance.rs:24)
```

**Comment by Gae24** [comment]
many of the tests failing uses Worker's `onmessage` and `postmessage`.
Need to investigate more.

**Comment by Gae24** [comment]
@jdm we need to delay all incoming `DOMMessage` until fetch is complete.

**Comment by jdm** [comment]
> @jdm we need to delay all incoming `DOMMessage` until fetch is complete.

Makes sense!

File: components/script/dom/workers/dedicatedworkerglobalscope.rs [hunk 1]
```diff
@@ -704,27 +626,42 @@ impl DedicatedWorkerGlobalScope {
         )
     }
 
+    pub(crate) fn fire_queued_messages(&self, can_gc: CanGc) {
+        for msg in self.queued_worker_tasks.borrow_mut().drain(..) {
```
Comment (jdm) [inline components/script/dom/workers/dedicatedworkerglobalscope.rs]: Let's collect a vector before starting this loop. I think the borrow_mut is still active when we call the method with the CanGc argument, which is a borrow hazard.

File: components/script/dom/workers/workerglobalscope.rs [hunk 2]
```diff
@@ -101,6 +114,166 @@ pub(crate) fn prepare_workerscope_init(
...
+    }
+
+    fn process_response_chunk(&mut self, _request_id: RequestId, mut chunk: Vec<u8>) {
+        self.body_bytes.append(&mut chunk);
+    }
+
+    fn process_response_eof(
+        &mut self,
+        _request_id: RequestId,
+        _response: Result<ResourceFetchTiming, NetworkError>,
```
Comment (jdm) [inline components/script/dom/workers/workerglobalscope.rs]: We need to handle the case where the response is an error at this point. This can happen if the request is aborted or the connection is interrupted.

**Review by jdm — APPROVED** [review]
Really great work! Thank you for fixing this wart :)

**Comment by jdm** [comment]
Once the test-tidy issue is fixed this can merge!
