### PR TITLE
fix RefCell already borrowed panic in readablestream

### LINKED ISSUE #40894: RefCell already borrowed @ readablestream.rs:1645
I got a "Servo crashed!" with RefCell already borrowed while playing around on maps.bing.com

The web site actually worked surprisingly well until the crash.

To repro:
Go to maps.bing.com
Use the scroll wheel to zoom in-out, hold down ctrl to rotate, it'll crash within a few seconds.

Platform:
Version: Servo 0.0.2-82ef0523b
Linux Mint 22.2 Zara (Ubuntu noble)
Linux 6.17.9 + amdgpu

I wasn't able to cut and paste the crash dump from the servo window, but it's a very easy repro.

### PR DESCRIPTION
**Pull request by Taym95**
fixes an intermittent RefCell already borrowed panic in the ReadableStream implementation by tightening the borrow scope of ReadableStream::reader in the error and cancel.

Testing: super hard to make crash test for this.

Fixes: #40894

### CODE REVIEW

File: components/script/dom/readablestream.rs [hunk 1]
```diff
@@ -1171,29 +1171,35 @@ impl ReadableStream {
...
+            }
+        };
+
+        if let Some(reader) = byob_reader {
+            // Perform ! ReadableStreamBYOBReaderErrorReadIntoRequests(reader, e).
+            reader.error_read_into_requests(e, can_gc);
+            return;
         }
+
+        // If reader is undefined, return.
```
Comment (yezhizhen) [inline components/script/dom/readablestream.rs:1201]:
```suggestion
```

File: components/script/dom/readablestream.rs [hunk 2]
```diff
@@ -1171,29 +1171,35 @@ impl ReadableStream {
...
+            match reader_ref.as_ref() {
+                Some(ReaderType::BYOB(reader)) => reader.get(),
+                _ => None,
+            }
+        };
+
+        if let Some(reader) = byob_reader {
+            // Perform ! ReadableStreamBYOBReaderErrorReadIntoRequests(reader, e).
+            reader.error_read_into_requests(e, can_gc);
+            return;
```
Comment (yezhizhen) [inline components/script/dom/readablestream.rs]:
```suggestion
```

**Review by yezhizhen — APPROVED** [review]
Thanks! Only lint and one redundant comment.

File: components/script/dom/readablestream.rs (hunk 1 above)
Comment (Taym95) [reply components/script/dom/readablestream.rs:1201]: that's the spec text.

Comment (yezhizhen) [reply components/script/dom/readablestream.rs:1201]: It's at the end of function tho

Comment (Taym95) [reply components/script/dom/readablestream.rs:1201]: I knew but better to keep spec text, this was just moved around.
