### PR TITLE
script: Support SVG <use> elements with fragment identifiers

### LINKED ISSUE #10951: Map and zooming tools are not rendered on openstreetmap
From ssh://github.com/mozilla/servo
   ca29192..77cb2ca  master     -> origin/master
   d9dc6dd..fc1e4c8  auto       -> origin/auto
- fb5fa4d...84a128b try        -> origin/try  (forced update)
  Updating ca29192..77cb2ca

[ludo@Oulanl servo]$ ./mach run --release http://www.openstreetmap.org
ERROR:js::rust: Error at http://www.openstreetmap.org/assets/application-6acb3ade0c3d81c622fed4391615eb0bc8bafc9a3b1d2ed22edbc4ad58f776bf.js:24:25930: i is undefined

ERROR:js::rust: Error at http://piwik.openstreetmap.org/piwik.js:36:946: J.name is undefined

ERROR:js::rust: Error at http://www.openstreetmap.org/assets/index-8145a65c8ea791c70d09224ce507f438960420f2e013c81ee2cd4e555eb89e18.js:6:25477: OSM.router is undefined

screenshot from 2016-05-01 07-11-53

### PR DESCRIPTION
**Pull request by WaterWhisperer**
implements support for SVG <use> elements that reference other elements within the same document using fragment identifiers.

Testing: image
Fixes: #10951

### CODE REVIEW

**Comment by jdm** [comment]
We should check the impact of this PR after https://github.com/servo/servo/pull/40692 merges.

**Comment by jdm** [comment]
Sorry this took so long—if you rebase against the latest main branch, we can now check if this changes any test results.

File: components/script/dom/svg/svgsvgelement.rs [hunk 1]
```diff
@@ -81,6 +87,62 @@ impl SVGSVGElement {
...
+        let document = self.upcast::<Node>().owner_doc();
+        let referenced_element = document.GetElementById(id)?;
+        let referenced_node = referenced_element.upcast::<Node>();
+        let has_svg_ancestor = referenced_node
+            .inclusive_ancestors(crate::dom::node::ShadowIncluding::No)
+            .any(|ancestor| ancestor.downcast::<SVGSVGElement>().is_some());
+        if !has_svg_ancestor {
+            return None;
+        }
+        let can_gc = crate::script_runtime::CanGc::note();
```
Comment (jdm) [inline components/script/dom/svg/svgsvgelement.rs]: We should take a `CanGc` argument for this method (and all of its transitive callers) instead: https://book.servo.org/architecture/borrow_hazard.html

File: components/script/dom/svg/svgsvgelement.rs [hunk 2]
```diff
@@ -81,6 +87,62 @@ impl SVGSVGElement {
...
+        let _ = root_node.AppendChild(&cloned_node, can_gc);
+
+        Some(cloned_node)
+    }
+
+    fn cleanup_cloned_nodes(&self, cloned_nodes: &[DomRoot<Node>]) {
+        if cloned_nodes.is_empty() {
+            return;
+        }
+        let can_gc = crate::script_runtime::CanGc::note();
```
Comment (jdm) [inline components/script/dom/svg/svgsvgelement.rs]: Same note about a CanGc argument.

File: components/script/dom/svg/svgsvgelement.rs [hunk 3]
```diff
@@ -81,6 +87,62 @@ impl SVGSVGElement {
...
+        let href = use_element.get_string_attribute(&local_name!("href"));
+        let href_view = href.str();
+        let id_str = href_view.strip_prefix("#")?;
+        let id = DOMString::from(id_str);
+        let document = self.upcast::<Node>().owner_doc();
+        let referenced_element = document.GetElementById(id)?;
+        let referenced_node = referenced_element.upcast::<Node>();
+        let has_svg_ancestor = referenced_node
+            .inclusive_ancestors(crate::dom::node::ShadowIncluding::No)
+            .any(|ancestor| ancestor.downcast::<SVGSVGElement>().is_some());
```
Comment (jdm) [inline components/script/dom/svg/svgsvgelement.rs]:
```suggestion
            .any(|ancestor| ancestor.is::<SVGSVGElement>());
```

File: components/script/dom/svg/svgsvgelement.rs [hunk 4]
```diff
@@ -81,6 +87,62 @@ impl SVGSVGElement {
         };
     }
 
+    fn process_use_elements(&self) -> Vec<DomRoot<Node>> {
+        let mut cloned_nodes = Vec::new();
+        let root_node = self.upcast::<Node>();
+
+        for node in root_node.traverse_preorder(crate::dom::node::ShadowIncluding::No) {
```
Comment (jdm) [inline components/script/dom/svg/svgsvgelement.rs]: Can you add an import for ShadowIncluding instead of using the full path here?

File: components/script/dom/svg/svgsvgelement.rs [hunk 5]
```diff
@@ -81,6 +87,62 @@ impl SVGSVGElement {
...
+            .inclusive_ancestors(crate::dom::node::ShadowIncluding::No)
+            .any(|ancestor| ancestor.downcast::<SVGSVGElement>().is_some());
+        if !has_svg_ancestor {
+            return None;
+        }
+        let can_gc = crate::script_runtime::CanGc::note();
+        let cloned_node = Node::clone(
+            referenced_node,
+            None,
+            crate::dom::node::CloneChildrenFlag::CloneChildren,
```
Comment (jdm) [inline components/script/dom/svg/svgsvgelement.rs]: Let's import this as well.

File: components/script/dom/svg/svgsvgelement.rs [hunk 6]
```diff
@@ -64,14 +66,18 @@ impl SVGSVGElement {
...
         let Ok(xml_source) = self
             .upcast::<Node>()
             .xml_serialize(TraversalScope::IncludeNode)
         else {
+            self.cleanup_cloned_nodes(&cloned_nodes);
             *self.cached_serialized_data_url.borrow_mut() = Some(Err(()));
             return;
         };
 
+        self.cleanup_cloned_nodes(&cloned_nodes);
```
Comment (jdm) [inline components/script/dom/svg/svgsvgelement.rs]: One slight improvement:
```rust
let cloned_nodes = self.process_use_elements();
let serialize_result = self.upcast::<Node>().xml_serialize(TraversalScope::Include);
self.cleanup_clones(&cloned_nodes);

let Ok(xml_source) = serialize_result else {
    ...
};
```

**Review by jdm — CHANGES_REQUESTED** [review]
Looking really good so far!

File: components/script/dom/svg/svgsvgelement.rs (hunk 4 above)
Comment (WaterWhisperer) [reply components/script/dom/svg/svgsvgelement.rs]: Sure

**Review by jdm — APPROVED** [review]
