### PR TITLE
[WebDriver: Release Action] Fix panic by work around buggy spec

### LINKED ISSUE #37579: (Regression) [WebDriver] Almost all key related tests in perform_actions panics
**Describe the bug:**
For example, https://github.com/servo/servo/blob/9dc1dde7cb293ce872a5a3ec8d43a1eb5b08b1a4/tests/wpt/tests/webdriver/tests/classic/perform_actions/key.py#L14-L16

**To Reproduce:**
`./mach test-wpt -r  .\tests\wpt\tests\webdriver\tests\classic\perform_actions\key.py --product servodriver`

But any other `key_*.py` also panics

### PR DESCRIPTION
**Pull request by yezhizhen**
1. Narrow the lifetime of `input_cancel_list` to avoid Runtime multiple BorrowMut error.
2. Work around the buggy spec by removing matching item in `input_cancel_list` when dispatch `keyUp` and `mouseUp`. See https://github.com/servo/servo/issues/37579#issuecomment-2990762713

Testing: All WebDriver WPT test.
Fixes: #37579

### CODE REVIEW

**Comment by yezhizhen** [comment]
cc @xiaochengh

File: components/webdriver_server/actions.rs [hunk 1]
```diff
@@ -327,6 +327,22 @@ impl Handler {
     fn dispatch_keyup_action(&self, source_id: &str, action: &KeyUpAction) {
         let session = self.session().unwrap();
 
+        // Remove the last matching keyUp from `[input_cancel_list]` due to bugs in spec
```
Comment (yezhizhen) [inline components/webdriver_server/actions.rs:330]: This is complete & sound: we won't remove anything if this is invoked by `release action`, as the `input_cancel_list` has already been cleared.

File: components/webdriver_server/lib.rs [hunk 2]
```diff
@@ -1758,12 +1758,17 @@ impl Handler {
...
 
         // Step 6. Let undo actions be input cancel list in reverse order.
-        let mut input_cancel_list = session.input_cancel_list.borrow_mut();
-        let undo_actions: ActionsByTick = input_cancel_list
-            .drain(..)
-            .rev()
-            .map(|(id, action_item)| HashMap::from([(id, action_item)]))
-            .collect();
+
+        let undo_actions: ActionsByTick = {
```
Comment (xiaochengh) [inline components/webdriver_server/lib.rs]: I think we can simply do
```rust
let undo_actions: ActionsByTick = session.input_cancel_list.borrow_mut()
            .drain(..)
            .rev()
            .map(|(id, action_item)| HashMap::from([(id, action_item)]))
            .collect();
```

**Review by xiaochengh — COMMENTED** [review]
LGTM with a nit

**Review by xiaochengh — APPROVED** [review]
