### PR TITLE
Gamepad: Implement gamepad buttons to be array, removing GamepadList

### LINKED ISSUE #44333: Gamepad: `buttons` should be Array, but is GamepadList instead
**Describe the bug:**
See: https://developer.mozilla.org/en-US/docs/Web/API/Gamepad/buttons

**To Reproduce:**
```html
<!doctype html>
<script>
    window.addEventListener("gamepadconnected", (e) => B.innerText=`Connected at ${Date.now()}`);
    setInterval(() => {
        let b = navigator.getGamepads()[0]?.buttons
        if (b) {
            A.innerText = b.constructor.name + ' ' + Array.isArray(b)
        }
    },500)
</script>
<pre id="B"></pre>
<pre id="A"></pre>
```
Servo
Image
Firefox
Image

**Platform:**
Windows 10

### PR DESCRIPTION
**Pull request by rovertrack**
Replaced `GamepadButtonList` interface with a frozen array of gamepad buttons to match the gamepad webidl specification.

Testing: No idlharness tests possible since the values can't be accessed without a real gamepad.
Fixes: #44333

### CODE REVIEW

**Comment by mrobinson** [comment]
@rovertrack The `Testing` field should not contain a screenshot, but describe the automated tests that test this change.

File: components/script/dom/gamepad/gamepad.rs [hunk 1]
```diff
@@ -64,7 +67,7 @@ impl Gamepad {
         connected: bool,
         timestamp: f64,
         mapping_type: String,
-        buttons: &GamepadButtonList,
+        buttons: RootVec<GamepadButton>,
```
Comment (Gae24) [inline components/script/dom/gamepad/gamepad.rs]: I think we should simply inline what `GamepadButtonList` did.
Replace the argument type with `&[&GamepadButton]`.

File: components/script/dom/gamepad/gamepad.rs [hunk 2]
```diff
@@ -80,7 +83,8 @@ impl Gamepad {
             timestamp: Cell::new(timestamp),
             mapping_type,
             axes: HeapBufferSource::default(),
-            buttons: Dom::from_ref(buttons),
+            frozen_buttons: CachedFrozenArray::new(),
+            buttons,
```
Comment (Gae24) [inline components/script/dom/gamepad/gamepad.rs]:
```suggestion
            buttons: buttons.iter().map(|button| Dom::from_ref(*button)).collect(),
```

File: components/script/dom/gamepad/gamepad.rs [hunk 3]
```diff
@@ -194,6 +208,34 @@ impl Gamepad {
...
+            GamepadButton::new(window, false, false, can_gc), // Top button in left cluster
+            GamepadButton::new(window, false, false, can_gc), // Bottom button in left cluster
+            GamepadButton::new(window, false, false, can_gc), // Left button in left cluster
+            GamepadButton::new(window, false, false, can_gc), // Right button in left cluster
+            GamepadButton::new(window, false, false, can_gc), // Center button in center cluster
+        ];
+        standard_buttons
+            .iter()
+            .map(|button| Dom::from_ref(&**button))
+            .collect()
```
Comment (Gae24) [inline components/script/dom/gamepad/gamepad.rs]: I'm not sure we should skip what was done before:

```
rooted_vec!(let buttons <- standard_buttons.iter().map(DomRoot::as_traced));
buttons.r()
```

File: components/script/dom/gamepad/gamepad.rs [hunk 4]
```diff
@@ -279,7 +321,7 @@ impl Gamepad {
             if normalized_value.is_finite() {
                 let pressed = normalized_value >= BUTTON_PRESS_THRESHOLD;
                 // TODO: Determine a way of getting touch capability for button
-                if let Some(button) = self.buttons.IndexedGetter(button_index as u32) {
+                if let Some(button) = self.buttons.get(button_index) {
                     button.update(pressed, /*touched*/ pressed, normalized_value);
```
Comment (Gae24) [inline components/script/dom/gamepad/gamepad.rs:325]: Here we need to do `self.frozen_buttons.clear()`, since the frozen value doesn't reflect the buttons state anymore.

**Review by Gae24 — CHANGES_REQUESTED** [review]

File: components/script/dom/gamepad/gamepad.rs (hunk 1 above)
Comment (rovertrack) [reply components/script/dom/gamepad/gamepad.rs]: done made it use this inline type

File: components/script/dom/gamepad/gamepad.rs (hunk 2 above)
Comment (rovertrack) [reply components/script/dom/gamepad/gamepad.rs]: done thanks

File: components/script/dom/gamepad/gamepad.rs (hunk 3 above)
Comment (rovertrack) [reply components/script/dom/gamepad/gamepad.rs]: ok

File: components/script/dom/gamepad/gamepad.rs (hunk 4 above)
Comment (rovertrack) [reply components/script/dom/gamepad/gamepad.rs:325]: totally missed it 😓 , thanks

**Comment by rovertrack** [comment]
Thanks @Gae24 , all suggested improvements have been made 
now the `init_button` returns buttons and the conversion to inline with `rooted_vec!` happens in the constructor itself!

File: components/script/dom/gamepad/gamepad.rs [hunk 5]
```diff
@@ -194,6 +212,30 @@ impl Gamepad {
         self.gamepad_id
     }
 
+    /// Initialize the standard buttons for a gamepad.
+    /// <https://www.w3.org/TR/gamepad/#dfn-initializing-buttons>
+    pub(crate) fn init_buttons(window: &Window, can_gc: CanGc) -> Vec<DomRoot<GamepadButton>> {
```
Comment (Gae24) [inline components/script/dom/gamepad/gamepad.rs]:
```suggestion
    fn init_buttons(window: &Window, can_gc: CanGc) -> Vec<DomRoot<GamepadButton>> {
```

**Review by Gae24 — APPROVED** [review]
Thanks!

File: components/script/dom/gamepad/gamepad.rs (hunk 5 above)
Comment (rovertrack) [reply components/script/dom/gamepad/gamepad.rs]: Copy pasted this from Gamepadlist.rs!
Thanks

**Review by Gae24 — APPROVED** [review]

**Comment by rovertrack** [comment]
is there any changes to be done on this @jdm?

**Comment by Gae24** [comment]
> is there any changes to be done on this @jdm?

Actually could you check if `tests/wpt/tests/gamepad/idlharness-manual.html` cover these changes?

File: components/script_bindings/webidls/Gamepad.webidl [hunk 6]
```diff
@@ -13,7 +13,7 @@ interface Gamepad {
     readonly attribute DOMHighResTimeStamp timestamp;
     readonly attribute DOMString mapping;
     readonly attribute Float64Array axes;
-    [SameObject] readonly attribute GamepadButtonList buttons;
+    readonly attribute any buttons;
```
Comment (rovertrack) [inline components/script_bindings/webidls/Gamepad.webidl:16]: I think instead of the suggested "any" this must be  `FrozenArray<GamepadButton>`so it checks the type of the buttons in https://github.com/servo/servo/blob/9189fe06a55f698f6b1568a319e81c3d6b409659/tests/wpt/tests/resources/idlharness.js#L528-L530

Comment (jdm) [reply components/script_bindings/webidls/Gamepad.webidl:16]: Our webidl codegen doesn't support `FrozenArray` types.

**Comment by jdm** [comment]
>Replaced the Gamepadbuttonlist type with any to implement Frozenarray - [components/script_bindings/webidls/Gamepad.webidl](https://github.com/servo/servo/compare/main...rovertrack:servo:issue-44333?expand=1#diff-767297ef2367651676f4a6ddb744d4881aae666c8010b5057c91c0a002b91143)
made the buttons usage in [components/script/dom/gamepad/gamepad.rs](https://github.com/servo/servo/compare/main...rovertrack:servo:issue-44333?expand=1#diff-0a2fca7bd112e59953f69889bd3f47e40c42079c3a58bee7fd452fc512f246a5) be implemented with CachedFrozenArray so that the buttons are cached frozen_buttons. replacing dependency of Gamepadbuttonlist
Implemented a init_buttons same as the one with Gamepadlist.rs to remove, Removed Gampadbuttonlist completely

> Tested with a physical controller 
servo:
Screenshot 2026-04-19 211908

I'm editing the original description to include a more clear commit message (since it will be used for the squashed commits). Here's the original message for posterity.

**Comment by rovertrack** [comment]
> > Replaced the Gamepadbuttonlist type with any to implement Frozenarray - [components/script_bindings/webidls/Gamepad.webidl](https://github.com/servo/servo/compare/main...rovertrack:servo:issue-44333?expand=1#diff-767297ef2367651676f4a6ddb744d4881aae666c8010b5057c91c0a002b91143)
> > made the buttons usage in [components/script/dom/gamepad/gamepad.rs](https://github.com/servo/servo/compare/main...rovertrack:servo:issue-44333?expand=1#diff-0a2fca7bd112e59953f69889bd3f47e40c42079c3a58bee7fd452fc512f246a5) be implemented with CachedFrozenArray so that the buttons are cached frozen_buttons. replacing dependency of Gamepadbuttonlist
> > Implemented a init_buttons same as the one with Gamepadlist.rs to remove, Removed Gampadbuttonlist completely
> 
> > Tested with a physical controller
> > servo:
> 
> Screenshot 2026-04-19 211908
> I'm editing the original description to include a more clear commit message (since it will be used for the squashed commits). Here's the original message for posterity.

Thanks @jdm.

File: components/script_bindings/webidls/Gamepad.webidl (hunk 6 above)
Comment (rovertrack) [reply components/script_bindings/webidls/Gamepad.webidl:16]: Thanks for the clarity 🙂

**Comment by rovertrack** [comment]
@jdm Merge Failed due to `GamePadButtonList` being present in tests while this PR completely removes it, I have updated the PR to remove the test expectations!

**Comment by jdm** [comment]
Excellent, thanks! This just needs to be rebased against main and run `./mach update-manifest` again.

**Comment by rovertrack** [comment]
> Excellent, thanks! This just needs to be rebased against main and run `./mach update-manifest` again.

Rebased and updated the manifest!

**Comment by rovertrack** [comment]
Thanks @Gae24.
