### PR TITLE
paint: Propogate input event dispatch failure to Servo to resolve deadlock

### LINKED ISSUE #43379: Deadlock when hit-test fails as embedder not informed
**Describe the bug:**
The comment in https://github.com/servo/servo/issues/43136#issuecomment-4031702204 is not fully implemented. In this case, when hit-test fails, the WebDriver hangs as embedder is not notified.

**To Reproduce:**
Change duration to 200.

https://github.com/servo/servo/blob/3c9221c3b54a8b0a493286407c12017c835e598a/tests/wpt/tests/touch-events/pinch-zoom-change.html#L46

**Platform:**
All.

### PR DESCRIPTION
**Pull request by yezhizhen**
`dispatch_input_event_with_hit_testing` already returns a `bool` to indicate whether the dispatch failed.
However, for some reason this was used nowhere. When it fails, embedder is not informed.
This is fine for embedder as right now it only handles keyboard shortcuts for headed window,
but a disaster for WebDriver as it is synchornously waiting for the feedback.

Testing: Several tests no longer CRASH.
Fixes: #43379

### CODE REVIEW

File: components/servo/webview.rs [hunk 1]
```diff
@@ -491,16 +492,23 @@ impl WebView {
...
+                .inner()
                 .servo
                 .paint()
-                .notify_input_event(self.id(), event);
+                .notify_input_event(self.id(), event)
+            {
+                return InputEventOutcome {
+                    id: event_id,
+                    result: InputEventResult::HitTestFailed,
+                };
```
Comment (yezhizhen) [inline components/servo/webview.rs]: I tried to directly do
```rust
self.delegate().notify_input_event_handled(
                    self.clone(),
                    event_id,
                    InputEventResult::default(),
                );
```
However, this would create another deadlock as `InputEventId` is not returned yet, which is used to create the response receiver. And when it's created, it is too late as `notify_input_event_handled` executes earlier and didn't send any response.

**Review by yezhizhen — COMMENTED** [review]
<details>
<summary> Debug log </summary>

```
id:22972 [components\webdriver_server\actions.rs:290:9] "Waiting.." = "Waiting.."
 3:23.64 pid:22972 [2026-03-18T06:34:02Z ERROR servo::webview] Sent InputEventAndId { event: MouseMove(MouseMoveEvent { point: Page((400.0, 4.0)), is_compatibility_event_for_touch: false }), id: InputEventId(0) }:InputEventId(0)
 3:23.64 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Servoshell: InputEventId(0)
 3:23.64 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Received InputEventId(0)
 3:23.64 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Notify InputEventId(0)
 3:23.64 pid:22972 [components\webdriver_server\actions.rs:294:9] "All done." = "All done."
 3:23.64 pid:22972 [components\webdriver_server\actions.rs:290:9] "Waiting.." = "Waiting.."
 3:23.64 pid:22972 [2026-03-18T06:34:02Z ERROR servo::webview] Sent InputEventAndId { event: MouseButton(MouseButtonEvent { action: Down, button: Left, point: Page((400.0, 4.0)) }), id: InputEventId(1) }:InputEventId(1)
 3:23.64 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Servoshell: InputEventId(1)
 3:23.67 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Received InputEventId(1)
 3:23.67 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Notify InputEventId(1)
 3:23.67 pid:22972 [components\webdriver_server\actions.rs:294:9] "All done." = "All done."
 3:23.67 pid:22972 [components\webdriver_server\actions.rs:290:9] "Waiting.." = "Waiting.."
 3:23.67 pid:22972 [2026-03-18T06:34:02Z ERROR servo::webview] Sent InputEventAndId { event: MouseButton(MouseButtonEvent { action: Up, button: Left, point: Page((400.0, 4.0)) }), id: InputEventId(2) }:InputEventId(2)
 3:23.67 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Servoshell: InputEventId(2)
 3:23.70 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Received InputEventId(2)
 3:23.70 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Notify InputEventId(2)
 3:23.70 pid:22972 [components\webdriver_server\actions.rs:294:9] "All done." = "All done."
 3:23.87 pid:22972 [components\webdriver_server\actions.rs:290:9] "Waiting.." = "Waiting.."
 3:23.87 pid:22972 [components\webdriver_server\actions.rs:294:9] "All done." = "All done."
 3:23.87 pid:22972 [components\webdriver_server\actions.rs:290:9] "Waiting.." = "Waiting.."
 3:23.88 pid:22972 [2026-03-18T06:34:02Z ERROR servo::webview] Sent InputEventAndId { event: Touch(TouchEvent { event_type: Down, touch_id: TouchId(2), point: Page((200.0, 200.0)), cancelable: true }), id: InputEventId(3) }:InputEventId(3)
 3:23.88 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Servoshell: InputEventId(3)
 3:23.88 pid:22972 [2026-03-18T06:34:02Z ERROR servo::webview] Sent InputEventAndId { event: Touch(TouchEvent { event_type: Down, touch_id: TouchId(3), point: Page((210.0, 210.0)), cancelable: true }), id: InputEventId(4) }:InputEventId(4)
 3:23.88 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Servoshell: InputEventId(4)
 3:23.89 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Received InputEventId(3)
 3:23.89 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Notify InputEventId(3)
 3:23.89 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Received InputEventId(4)
 3:23.89 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Notify InputEventId(4)
 3:23.89 pid:22972 [components\webdriver_server\actions.rs:294:9] "All done." = "All done."
 3:23.90 pid:22972 [2026-03-18T06:34:02Z ERROR servo::webview] Sent InputEventAndId { event: Touch(TouchEvent { event_type: Move, touch_id: TouchId(2), point: Page((197.6, 197.6)), cancelable: true }), id: InputEventId(5) }:InputEventId(5)
 3:23.90 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Servoshell: InputEventId(5)
 3:23.90 pid:22972 [2026-03-18T06:34:02Z ERROR servo::webview] Sent InputEventAndId { event: Touch(TouchEvent { event_type: Move, touch_id: TouchId(3), point: Page((230.0, 230.0)), cancelable: true }), id: InputEventId(6) }:InputEventId(6)
 3:23.90 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Servoshell: InputEventId(6)
 3:23.92 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Received InputEventId(5)
 3:23.92 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] No sender for InputEventId(5)
 3:23.92 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Received InputEventId(6)
 3:23.92 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] No sender for InputEventId(6)
 3:23.92 pid:22972 [2026-03-18T06:34:02Z ERROR servo::webview] Sent InputEventAndId { event: Touch(TouchEvent { event_type: Move, touch_id: TouchId(2), point: Page((195.05, 195.05)), cancelable: true }), id: InputEventId(7) }:InputEventId(7)
 3:23.92 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Servoshell: InputEventId(7)
 3:23.94 pid:22972 [2026-03-18T06:34:02Z ERROR servo::webview] Sent InputEventAndId { event: Touch(TouchEvent { event_type: Move, touch_id: TouchId(2), point: Page((192.65, 192.65)), cancelable: true }), id: InputEventId(8) }:InputEventId(8)
 3:23.94 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Servoshell: InputEventId(8)
 3:23.94 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Received InputEventId(8)
 3:23.94 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] No sender for InputEventId(8)
 3:23.95 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Received InputEventId(7)
 3:23.95 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] No sender for InputEventId(7)
 3:23.95 pid:22972 [2026-03-18T06:34:02Z ERROR servo::webview] Sent InputEventAndId { event: Touch(TouchEvent { event_type: Move, touch_id: TouchId(2), point: Page((190.1, 190.1)), cancelable: true }), id: InputEventId(9) }:InputEventId(9)
 3:23.95 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Servoshell: InputEventId(9)
 3:23.95 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Received InputEventId(9)
 3:23.95 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] No sender for InputEventId(9)
 3:23.97 pid:22972 [2026-03-18T06:34:02Z ERROR servo::webview] Sent InputEventAndId { event: Touch(TouchEvent { event_type: Move, touch_id: TouchId(2), point: Page((187.7, 187.7)), cancelable: true }), id: InputEventId(10) }:InputEventId(10)
 3:23.97 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Servoshell: InputEventId(10)
 3:23.97 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] Received InputEventId(10)
 3:23.97 pid:22972 [2026-03-18T06:34:02Z ERROR servoshell::running_app_state] No sender for InputEventId(10)
 3:23.99 pid:22972 [2026-03-18T06:34:03Z ERROR servo::webview] Sent InputEventAndId { event: Touch(TouchEvent { event_type: Move, touch_id: TouchId(2), point: Page((185.3, 185.3)), cancelable: true }), id: InputEventId(11) }:InputEventId(11)
 3:23.99 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Servoshell: InputEventId(11)
 3:23.99 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Received InputEventId(11)
 3:23.99 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] No sender for InputEventId(11)
 3:24.00 pid:22972 [2026-03-18T06:34:03Z ERROR servo::webview] Sent InputEventAndId { event: Touch(TouchEvent { event_type: Move, touch_id: TouchId(2), point: Page((182.75, 182.75)), cancelable: true }), id: InputEventId(12) }:InputEventId(12)
 3:24.00 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Servoshell: InputEventId(12)
 3:24.00 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Received InputEventId(12)
 3:24.00 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] No sender for InputEventId(12)
 3:24.02 pid:22972 [2026-03-18T06:34:03Z ERROR servo::webview] Sent InputEventAndId { event: Touch(TouchEvent { event_type: Move, touch_id: TouchId(2), point: Page((180.35, 180.35)), cancelable: true }), id: InputEventId(13) }:InputEventId(13)
 3:24.02 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Servoshell: InputEventId(13)
 3:24.02 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Received InputEventId(13)
 3:24.02 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] No sender for InputEventId(13)
 3:24.03 pid:22972 [2026-03-18T06:34:03Z ERROR servo::webview] Sent InputEventAndId { event: Touch(TouchEvent { event_type: Move, touch_id: TouchId(2), point: Page((177.8, 177.8)), cancelable: true }), id: InputEventId(14) }:InputEventId(14)
 3:24.03 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Servoshell: InputEventId(14)
 3:24.03 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Received InputEventId(14)
 3:24.03 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] No sender for InputEventId(14)
 3:24.05 pid:22972 [2026-03-18T06:34:03Z ERROR servo::webview] Sent InputEventAndId { event: Touch(TouchEvent { event_type: Move, touch_id: TouchId(2), point: Page((175.4, 175.4)), cancelable: true }), id: InputEventId(15) }:InputEventId(15)
 3:24.05 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Servoshell: InputEventId(15)
 3:24.05 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Received InputEventId(15)
 3:24.05 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] No sender for InputEventId(15)
 3:24.07 pid:22972 [2026-03-18T06:34:03Z ERROR servo::webview] Sent InputEventAndId { event: Touch(TouchEvent { event_type: Move, touch_id: TouchId(2), point: Page((173.0, 173.0)), cancelable: true }), id: InputEventId(16) }:InputEventId(16)
 3:24.07 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Servoshell: InputEventId(16)
 3:24.07 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Received InputEventId(16)
 3:24.07 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] No sender for InputEventId(16)
 3:24.10 pid:22972 [2026-03-18T06:34:03Z ERROR servo::webview] Sent InputEventAndId { event: Touch(TouchEvent { event_type: Move, touch_id: TouchId(2), point: Page((170.45, 170.45)), cancelable: true }), id: InputEventId(17) }:InputEventId(17)
 3:24.10 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Servoshell: InputEventId(17)
 3:24.10 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Received InputEventId(17)
 3:24.10 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] No sender for InputEventId(17)
 3:24.10 pid:22972 [2026-03-18T06:34:03Z ERROR servo::webview] Sent InputEventAndId { event: Touch(TouchEvent { event_type: Move, touch_id: TouchId(2), point: Page((170.0, 170.0)), cancelable: true }), id: InputEventId(18) }:InputEventId(18)
 3:24.10 pid:22972 [components\webdriver_server\actions.rs:290:9] "Waiting.." = "Waiting.."
 3:24.10 pid:22972 [components\webdriver_server\actions.rs:294:9] "All done." = "All done."
 3:24.10 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Servoshell: InputEventId(18)
 3:24.10 pid:22972 [components\webdriver_server\actions.rs:290:9] "Waiting.." = "Waiting.."
 3:24.10 pid:22972 [2026-03-18T06:34:03Z ERROR servo::webview] Sent InputEventAndId { event: Touch(TouchEvent { event_type: Up, touch_id: TouchId(2), point: Page((170.0, 170.0)), cancelable: true }), id: InputEventId(19) }:InputEventId(19)
 3:24.10 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Servoshell: InputEventId(19)
 3:24.10 pid:22972 [2026-03-18T06:34:03Z ERROR servo::webview] Sent InputEventAndId { event: Touch(TouchEvent { event_type: Up, touch_id: TouchId(3), point: Page((230.0, 230.0)), cancelable: true }), id: InputEventId(20) }:InputEventId(20)
 3:24.10 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Servoshell: InputEventId(20)
 3:24.10 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Received InputEventId(18)
 3:24.10 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] No sender for InputEventId(18)
 3:24.15 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Received InputEventId(19)
 3:24.15 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Notify InputEventId(19)
 3:24.15 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Received InputEventId(20)
 3:24.15 pid:22972 [2026-03-18T06:34:03Z ERROR servoshell::running_app_state] Notify InputEventId(20)
 3:24.15 pid:22972 [components\webdriver_server\actions.rs:294:9] "All done." = "All done."
```

</details>

Will remove the debug log commit after the review.

**Comment by yezhizhen** [comment]
The result looks promising :)
https://github.com/servo/servo/actions/runs/23231730334/job/67526897529

**Comment by stevennovaryo** [comment]
Looks like it is the one that is affecting https://github.com/servo/servo/pull/43231#discussion_r2944743288.

**Comment by yezhizhen** [comment]
> Looks like it is the one that is affecting [#43231 (comment)](https://github.com/servo/servo/pull/43231#discussion_r2944743288).

What a coincidence :)

File: components/paint/painter.rs [hunk 2]
```diff
@@ -1299,10 +1299,14 @@ impl Painter {
...
+            .unwrap_or_default()
     }
 
-    pub(crate) fn notify_input_event(&mut self, webview_id: WebViewId, event: InputEventAndId) {
+    pub(crate) fn notify_input_event(
+        &mut self,
+        webview_id: WebViewId,
+        event: InputEventAndId,
+    ) -> bool {
         if let Some(webview_renderer) = self.webview_renderers.get_mut(&webview_id) {
```
Comment (mrobinson) [inline components/paint/painter.rs]: I think you can use `is_some_and(|webview|)` here to simplify this:


```suggestion
        elf.webview_renderers.get_mut(&webview_id).is_some_and(|webview_renderer|)
```

File: components/paint/webview_renderer.rs [hunk 3]
```diff
@@ -503,37 +513,45 @@ impl WebViewRenderer {
...
         }
+        let mut reached_constellation = true;
         // When the event is touchmove, if the script thread is processing the touch
         // move event, we skip sending the event to the script thread.
         // This prevents the script thread from stacking up for a large amount of time.
         if !self.touch_handler.is_handling_touch_move_for_touch_id(
             self.touch_handler.current_sequence_id,
             event.touch_id,
-        ) && self.send_touch_event(render_api, event, id) &&
-            event.is_cancelable()
```
Comment (mrobinson) [inline components/paint/webview_renderer.rs:513]: Hrm. Shouldn't you return false if the if-condition is false? I think you might just want to initialize `reached_constellation` to `false` or etter yet, do an early return false here.

File: components/servo/webview.rs [hunk 4]
```diff
@@ -491,16 +492,23 @@ impl WebView {
             .notify_scroll_event(self.id(), scroll, point);
     }
 
-    pub fn notify_input_event(&self, event: InputEvent) -> InputEventId {
+    pub fn notify_input_event(&self, event: InputEvent) -> InputEventOutcome {
         let event: InputEventAndId = event.into();
         let event_id = event.id;
-
+        log::error!("Sent {:?}:{:?}", event, event_id);
```
Comment (mrobinson) [inline components/servo/webview.rs]: Please remove this.

File: components/servo/webview.rs [hunk 5]
```diff
@@ -491,16 +492,23 @@ impl WebView {
             .notify_scroll_event(self.id(), scroll, point);
     }
 
-    pub fn notify_input_event(&self, event: InputEvent) -> InputEventId {
```
Comment (mrobinson) [inline components/servo/webview.rs:502]: Instead of returning a different return value, I think the thing to do here is to asynchronously call `Webview::notify_input_event_handled`. That will ensure that event handling always happens in the same way, which I think is important for people using the API.

File: components/servo/webview_delegate.rs [hunk 6]
```diff
@@ -870,7 +870,8 @@ pub trait WebViewDelegate {
 
     /// An input event passed to this [`WebView`] via [`WebView::notify_input_event`] has been handled
     /// by Servo. This allows post-procesing of input events, such as chaining up unhandled events
-    /// to parent UI elements.
+    /// to parent UI elements, unblocking WebDriver server
+    /// which may be synchronously waiting for response.
```
Comment (mrobinson) [inline components/servo/webview_delegate.rs]: Let's remove references to WebDriver here, which might be confusing to people who are just using Servo, but have no idea what a WebDriver is.

**Review by mrobinson — CHANGES_REQUESTED** [review]
Looks like a great start, but I think we want event handling to always work in the same way no matter how the input event failed. I think you can do this by storing events that failed to send in a vector and then waking up the event loop inside the call to `WebView::notify_input_event`. Then during the next wakeup, for each of the stored event ids, we would report that they were handled (but not Consumed). Maybe we need a new `InputEventResult`.

File: components/servo/webview_delegate.rs (hunk 6 above)
Comment (stevennovaryo) [inline components/servo/webview_delegate.rs]:
```suggestion
    /// to parent UI elements, unblocking WebDriver server which may be synchronously 
    /// waiting for response.
```
Tiny nit to ensure that the formatting consistent between lines.

File: components/paint/webview_renderer.rs (hunk 3 above)
Comment (yezhizhen) [reply components/paint/webview_renderer.rs:513]: Nice catch!

File: components/servo/webview.rs (hunk 5 above)
Comment (yezhizhen) [reply components/servo/webview.rs:502]: Do we leave this as a follow-up then?

**Review by stevennovaryo — APPROVED** [review]
I guess in the long term it would be nice to have uniques error flag/enum for input event error within WebviewRenderer, aside from grouping it as a `HitTestFailed`.

File: components/servo/webview.rs (hunk 5 above)
Comment (mrobinson) [reply components/servo/webview.rs:502]: Hrm. I think we should probably not wait. I can help to implement this if you like.

Comment (yezhizhen) [reply components/servo/webview.rs:502]: I want to try out first then. 
I guess you mean insert here, and try to wake up the waker too:
https://github.com/yezhizhen/servo/blob/0901b34ddb6b30d5997547e4d4c177451caf891f/components/servo/webview.rs#L506-L509

And then, handle the leftover from last round here https://github.com/servo/servo/blob/8d153761f9f538c4f8642d20c63fcd677b476e9a/ports/servoshell/running_app_state.rs#L411

Comment (yezhizhen) [reply components/servo/webview.rs:502]: Emm. But we don't need to wake up the waker?
We can just handle the vector at the end of current spin?

Comment (yezhizhen) [reply components/servo/webview.rs:502]: I will try implementing this without wake first.

Comment (mrobinson) [reply components/servo/webview.rs:502]: Hrm. I think the issue is that `WebView::notify_input_event` might be called independently of whether the Servo event loop is spinning or not. In that case the event loop will need to spin at some point in the future and the only way to guarantee that is to actually wake up the event loop.

Comment (yezhizhen) [reply components/servo/webview.rs:502]: Make sense. I was only thinking about WebDriver, where `WebView::notify_input_event` is guaranteed to be called within the spin here https://github.com/servo/servo/blob/479a9b6be3c3c8fc8a8c2a2475ad253ebe72b559/components/servo/servo.rs#L193

Let's do wake then, as it might become useful in the future.

**Comment by yezhizhen** [comment]
Let's give this a shot.

**Comment by yezhizhen** [comment]
@mrobinson Can you check again? You asked to make some change that doesn't make real difference here instead of doing in follow-up. And I did.

This fixes all testdriver tests that use **pinch zoom** utility function. I need that to fix touch chain. New test added by Steven in another PR also needs this.

File: components/shared/embedder/input_events.rs [hunk 7]
```diff
@@ -33,6 +39,8 @@ bitflags! {
         /// behavior (such as keybindings) when the WebView has already consumed the event for its
         /// own purpose.
         const Consumed = 1 << 1;
+        /// Whether or not the input event failed to dispatch.
```
Comment (mrobinson) [inline components/shared/embedder/input_events.rs]: It would be good to explain why an event fails to dispatch. 


```suggestion
        /// Whether or not the input event failed to dispatch. This can happen when an event
        /// is sent while Servo is shutting down or when it is in an intermediary state. Typically
        /// these events should be considered to be consumed.
```

File: components/servo/servo.rs [hunk 8]
```diff
@@ -158,6 +158,8 @@ struct ServoInner {
     /// and deinitialization of the JS Engine. Multiprocess Servo instances have their
     /// own instance that exists in the content process instead.
     _js_engine_setup: Option<JSEngineSetup>,
+    /// [`InputEventId`]s that failed to send.
+    residue_events: RefCell<Vec<ResidueEvent>>,
```
Comment (mrobinson) [inline components/servo/servo.rs]: Just a nit here: I think "residue" is a bit mystery, so I prefer that we spell this out very explicitly since the idea is a little tricky:

```suggestion
    /// [`InputEventId`]s that have been handled, but for which the embedder has
    /// not been notified yet.
    pending_handled_input_events: RefCell<Vec<ResidueEvent>>,
```

File: components/shared/embedder/input_events.rs [hunk 9]
```diff
@@ -14,6 +15,11 @@ use crate::WebViewPoint;
 #[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize)]
 pub struct InputEventId(usize);
 
+pub struct ResidueEvent {
+    pub event_id: InputEventId,
+    pub webview_id: WebViewId,
+}
```
Comment (mrobinson) [inline components/shared/embedder/input_events.rs]:
```suggestion
pub struct PendingHandledInputEvent {
    pub event_id: InputEventId,
    pub webview_id: WebViewId,
}
```

I also think this data structure should move into `components/servo/servo.rs` as it's only used there.

File: components/servo/servo.rs [hunk 10]
```diff
@@ -956,6 +978,10 @@ impl Servo {
     pub(crate) fn javascript_evaluator_mut<'a>(&'a self) -> RefMut<'a, JavaScriptEvaluator> {
         self.0.javascript_evaluator.borrow_mut()
     }
+
+    pub(crate) fn add_residue_event(&self, residue_event: ResidueEvent) {
```
Comment (mrobinson) [inline components/servo/servo.rs]:
```suggestion
    pub(crate) fn add_pending_handled_input_event(&self, residue_event: ResidueEvent) {
```

File: components/paint/paint.rs [hunk 11]
```diff
@@ -91,7 +91,7 @@ pub struct Paint {
 
     /// An [`EventLoopWaker`] used to wake up the main embedder event loop when the renderer needs
     /// to run.
-    pub(crate) event_loop_waker: Box<dyn EventLoopWaker>,
+    pub event_loop_waker: Box<dyn EventLoopWaker>,
```
Comment (mrobinson) [inline components/paint/paint.rs]: Instead of making this public, please store a copy of the `event_loop_waker` on `Servo` as it's likely we will need it there in the future as well. Then expose a getter that the `WebView` can access.

File: components/paint/paint.rs [hunk 12]
```diff
@@ -786,12 +786,14 @@ impl Paint {
             .save_capture(capture_path, CaptureBits::all());
     }
 
-    pub fn notify_input_event(&self, webview_id: WebViewId, event: InputEventAndId) {
+    /// Returning `false` means this is not going to reach constellation/script,
+    /// and we need to directly notify Embedder that input event is handled.
```
Comment (mrobinson) [inline components/paint/paint.rs]: Nit:

```suggestion
    /// Returning `false` means this is not going to reach the Constellation,
    /// and we need to directly notify the embedder that input event is handled.
```

**Review by mrobinson — COMMENTED** [review]
Nice work. I would like to suggest a few minor changes:

File: components/shared/embedder/input_events.rs (hunk 7 above)
Comment (yezhizhen) [reply components/shared/embedder/input_events.rs]: > ... intermediary state

I think you mean intermediate?

File: components/paint/paint.rs (hunk 12 above)
Comment (yezhizhen) [reply components/paint/paint.rs]: Thanks. I think this should not be plural tho :D
Constellations->Constellation

Comment (mrobinson) [reply components/paint/paint.rs]: Yes, well spotted. I've corrected the suggestion.

File: components/shared/embedder/input_events.rs (hunk 7 above)
Comment (mrobinson) [reply components/shared/embedder/input_events.rs]: Yes, indeed.

**Comment by yezhizhen** [comment]
Thanks for review. Please check https://github.com/servo/servo/pull/43381/changes/8fca267f4955c6fa7566bed6b549af819811962c and https://github.com/servo/servo/pull/43381/commits/f6c7b61b6ffb7e83efe931458f2e07d7fc54acf5

File: components/servo/webview.rs [hunk 13]
```diff
@@ -502,19 +503,27 @@ impl WebView {
...
+                .notify_input_event(self.id(), event)
+            {
+                self.inner()
+                    .servo
+                    .add_pending_handled_input_event(PendingHandledInputEvent {
+                        event_id,
+                        webview_id,
+                    });
+                self.inner().servo.event_loop_waker().wake();
+            }
```
Comment (mrobinson) [inline components/servo/webview.rs]: Instead of calling `inner()` three times, do you mind putting it in an instance variable?

**Review by mrobinson — APPROVED** [review]
Thank you!

File: components/servo/webview.rs (hunk 13 above)
Comment (yezhizhen) [reply components/servo/webview.rs]: Done in https://github.com/servo/servo/pull/43381/commits/2e2070c596dd6ba80d88ac32180cd507799af339. Saved the call 4 times!
