### PR TITLE
layout: Treat `<audio>` as replaced and do not display when there is no `controls` attribute

### LINKED ISSUE #40693: `<audio>` should be treat as replaced_content when exposing user_agents.
As per the [spec](https://html.spec.whatwg.org/multipage/rendering.html#embedded-content-rendering-rules)
> The [audio](https://html.spec.whatwg.org/multipage/media.html#the-audio-element) element, when it is [exposing a user interface](https://html.spec.whatwg.org/multipage/media.html#expose-a-user-interface-to-the-user), is [expected](https://html.spec.whatwg.org/multipage/rendering.html#expected) to be treated as a [replaced element](https://drafts.csswg.org/css-display/#replaced-element) about one line high, as wide as is necessary to expose the user agent's user interface features.

Currently, we treat `<audio>` as a Block in Flow formatting Context. 
With the below test case,
```
<audio src="">
hello world</audio>
```
the hello world would be shown, while the expected behaviour is not.

### LINKED ISSUE #41183: panic: already mutably borrowed at atomic_refcell-0.1.13/src/lib.rs:155
This is flaky, I'm relying on https://github.com/fred-wang/servo-fuzzing/blob/main/parallelize.sh to reproduce. I'm getting multiple assertion failures, sometimes in `StyleThread` sometimes in `ScriptThread`:

Minimal testcase:

```html
<!DOCTYPE html>
<style>
  audio:after { content: url(data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAIAAABt+uBvAAAAAXNSR0IArs4c6QAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wDGhYvCNVA1EIAAAAZdEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAjklEQVR42u3QIQEAMAgAsHNNVspTgARY1BZh0ZWP3VcgSJAgQYIECRKEIEGCBAkSJEgQggQJEiRIkCBBCBIkSJAgQYIECUKQIEGCBAkSJAhBggQJEiRIkCAECRIkSJAgQYIEIUiQIEGCBAkShCBBggQJEiRIEIIECRIkSJAgQYIQJEiQIEGCBAlCkCBBdwaeugIthHvZ+AAAAABJRU5ErkJggg==); }
</style>
<script>
  onload = _ => object.style = "text-transform: uppercase";
</script>
<object id="object"><audio controls><source src="about:blank"></audio></object>
```

System: Linux
Version: Version: Servo 0.0.3-224ca771c
Command: `./parallelize.sh ./servo/servo testcase.html`

```
already mutably borrowed (thread StyleThread#2, at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/atomic_refcell-0.1.13/src/lib.rs:155)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::panic_with_hook
   3: std::panicking::panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: __rustc::rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::panic_display
   8: layout::layout_box_base::LayoutBoxBase::inline_content_sizes
   9: core::cell::lazy::LazyCell<T,F>::really_init
  10: layout::flow::<impl layout::formatting_contexts::IndependentFormattingContext>::layout_float_or_atomic_inline
  11: layout::flow::BlockContainer::layout
  12: layout::flow::BlockFormattingContext::layout
  13: layout::formatting_contexts::IndependentFormattingContext::layout
  14: layout::positioned::HoistedAbsolutelyPositionedBox::layout
  15: rayon::iter::plumbing::bridge_producer_consumer::helper
  16: layout::positioned::HoistedAbsolutelyPositionedBox::layout_many
  17: layout::positioned::PositioningContext::layout_collected_children
  18: layout::flow::BlockLevelBox::layout
  19: rayon::iter::plumbing::bridge_producer_consumer::helper
  20: layout::flow::BlockContainer::layout
  21: layout::flow::BlockFormattingContext::layout
  22: layout::formatting_contexts::IndependentFormattingContext::layout
  23: layout::flow::<impl layout::formatting_contexts::IndependentFormattingContext>::layout_float_or_atomic_inline
  24: layout::flow::BlockContainer::layout
  25: layout::flow::BlockLevelBox::layout::{{closure}}
  26: layout::flow::BlockLevelBox::layout
  27: rayon::iter::plumbing::bridge_producer_consumer::helper
  28: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  29: rayon_core::registry::WorkerThread::wait_until_cold
  30: rayon_core::registry::ThreadBuilder::run
  31: std::sys::backtrace::__rust_begin_short_backtrace
  32: core::ops::function::FnOnce::call_once{{vtable.shim}}
  33: std::sys::thread::unix::Thread::new::thread_start
```

### PR DESCRIPTION
**Pull request by Loirooriol**
Add an important UA style to ensure that `<audio>` isn't displayed at all when it doesn't have the `controls` attribute. This matches Gecko, Blink and WebKit.

When it does have the attribute, then treat it as replaced. For example, this means that it won't stretch by default if it's block-level, that it will be atomic if inline-level, and that it won't generate boxes for its children (including `::before` and `::after`).

Previously we were generating `::before` and `::after`, but there was a bug: if they had some replaced content, the controls of the `<audio>` would be duplicated, and also appear on the pseudo-element. Then, since the various boxes for the controls would be backed by the same elements, Servo could panic because of a double borrow. This is now avoided.

Testing: Some WPT are now passing, also adding a new crashtest. There is one failure about `innerText`, but the test is probably wrong, now we match other browsers.
Fixes: #40693
Fixes: #41183

### CODE REVIEW

File: components/script/layout_dom/element.rs [hunk 1]
```diff
@@ -995,6 +995,9 @@ pub struct ServoThreadSafeLayoutElement<'dom> {
 impl<'dom> ServoThreadSafeLayoutElement<'dom> {
     /// The shadow root this element is a host of.
     pub fn shadow_root(&self) -> Option<ServoShadowRoot<'dom>> {
+        if !self.pseudo_element_chain.is_empty() {
+            return None;
+        }
```
Comment (Loirooriol) [inline components/script/layout_dom/element.rs]: The context for this change is https://github.com/servo/servo/blob/b2aa0ac859e2921e944bd970d0590c96424206dc/components/layout/formatting_contexts.rs#L93

There are various other methods in `ServoThreadSafeLayoutElement` and `ServoThreadSafeLayoutNone` which are ignoring the `pseudo_element_chain`, should be investigated in a follow-up.

**Comment by Loirooriol** [comment]
Actually, better just treat it as replaced after all.

**Comment by rayguo17** [comment]
With this change, the test-case given in https://github.com/servo/servo/issues/40693 should be also fixed, if i understand correctly.

**Review by mrobinson — APPROVED** [review]
