### PR TITLE
Move click event trigger from embedding layer to `ScriptThread`

### LINKED ISSUE #35395: Webdriver mouse down/up pairs should generate a click event
Our logic to trigger a click event currently lives in the embedding layer: https://github.com/servo/servo/blob/84006ba76d1d6d7f64104d4c708e83610d6938df/ports/servoshell/desktop/headed_window.rs#L263-L274

This seems like the wrong layer of abstraction for a core feature of the web (ie. `click` event handlers won't trigger without this logic). Additionally, this logic is required to allow webdriver tests that rely on `click` events to pass.

### PR DESCRIPTION
**Pull request by yezhizhen**
1. Move click event trigger from embedding layer to `ScriptThread`
2. Previously, the logic is to trigger click event at same position as `MouseButtonAction::Up` if `MouseButtonAction::Up` is within 10px of `MouseButtonAction::Down`, in embedding layer. This PR ~~removes the condition~~ moves the check to `ScriptThread`.

Testing: tested for webdriver with self written test case. Perform actions of pointermove, pointerdown, pointerup in sequence. Click event can now be triggered.
Fixes: #35395 

cc @xiaochengh @jdm 

For `MAYBE? TODO:` part I added, should we do it? I read the [spec](https://w3c.github.io/uievents/#event-type-click), it doesn't specify we have to implement MDN's way.

If we should work in the MDN's way, it also should be fixed in another PR, as this PR doesn't regress anything. Also I am not sure what is the best way to do it. 
Should I handle it in https://github.com/servo/servo/blob/4d4f94936f8859f039497df370083fd7ea35fb00/components/script/dom/document.rs#L1296-L1297?

### CODE REVIEW

File: components/script/script_thread.rs [hunk 1]
```diff
@@ -3316,7 +3316,29 @@ impl ScriptThread {
...
+                    pressed_mouse_buttons: event.pressed_mouse_buttons,
+                    active_keyboard_modifiers: event.active_keyboard_modifiers,
+                    event: InputEvent::MouseButton(MouseButtonEvent {
+                        action: MouseButtonAction::Click,
+                        button: mouse_button_event.button,
+                        point: mouse_button_event.point,
+                    }),
+                });
+            }
+        }
```
Comment (mrobinson) [inline components/script/script_thread.rs:3341]: We also want to preserve the behavior where if you move the mouse too much, a `click` event should not be fired right?

Comment (yezhizhen) [reply components/script/script_thread.rs:3341]: Actually this is neither specified in spec nor MDN.
MDN says should fire as long as "pressed and released" within same element. For details, check "// MAYBE? TODO:" part in code change.

Comment (mrobinson) [reply components/script/script_thread.rs:3341]: We should likely be storing a handle to the element  that received the down event.

**Comment by yezhizhen** [comment]
@mrobinson @jdm  I also have some follow up commits to fix #35666. Do you think it should be added to this PR tho?

File: components/script/script_thread.rs (hunk 1 above)
Comment (jdm) [reply components/script/script_thread.rs:3341]: I would prefer to maintain the existing behaviour in this PR.

**Comment by jdm** [comment]
> @mrobinson @jdm I also have some follow up commits to fix #35666. Do you think it should be added to this PR tho?

I would prefer to keep that change in a separate PR.

**Comment by xiaochengh** [comment]
Do we have a principle which UI events are triggered at which layers?

**Review by mrobinson — COMMENTED** [review]
Is it possible to remove `MouseButtonAction::Click` as well with this change?

**Comment by jdm** [comment]
> Is it possible to remove `MouseButtonAction::Click` as well with this change?

Not without further changes to the egl port, which synthesizes click events from touch events I believe.

**Comment by yezhizhen** [comment]
> Do we have a principle which UI events are triggered at which layers?

From my understanding, most UI events are fired from `script/dom/document.rs`, tho target can be Element/Window/Document.

**Comment by xiaochengh** [comment]
I don't get it. Shouldn't most of the UI events triggered from the compositor?

**Comment by mrobinson** [comment]
> I don't get it. Shouldn't most of the UI events triggered from the compositor?

I think that `click` is a special case. Most UI events map one-to-one to device events, and thus it is easy for an embedder to simply send the events to Servo. `click` is only supposed to be fired after receiving another event (`mouseup`) and only when certain conditions are met in a `Document`. I think that is why, in this case, it is unreasonable for the embedder to trigger this event. I believe that the philosophy we should follow with the Servo API is "Send Servo your raw events, and it will interpret them for the web."

File: components/script/script_thread.rs (hunk 1 above)
Comment (xiaochengh) [reply components/script/script_thread.rs:3342]: +1. If possible, let's do exactly one thing (move where the event is triggered) in one PR.

**Comment by mrobinson** [comment]
> In this way, `click`, `auxclick`, `dblclick` and `contextmenu` should all be triggered on the script thread. Are we already doing that other than for `click`?

Yes, I think we are, though it seems like `dblclick` depends on getting `Click` events from the embedder (which we would elminate here) and we do not have support for `auxclick`.

File: components/script/script_thread.rs (hunk 1 above)
Comment (yezhizhen) [reply components/script/script_thread.rs:3342]: > I would prefer to maintain the existing behaviour in this PR.

Do you mean revert point 2,3 in commit message? But since we already moved the logic to `ScriptThread`, that would require passing the distance check as a extra parameter tho, which changes a lot of things (and other unrelated `InputEvent`) in the way. And it will still be removed soon after this.

Comment (xiaochengh) [reply components/script/script_thread.rs:3342]: All browsers maintain some non-standard behaviors to some degree. A behavior being non-standard does not trivially imply it should be removed or changed as long as it's bug-free. Such changes often require much more considerations.

Let's keep the existing behavior in this PR even though that makes the code diff larger. In this way, the behavior diff is actually smaller and easier to review.

File: components/script/script_thread.rs [hunk 2]
```diff
@@ -3322,7 +3336,45 @@ impl ScriptThread {
...
+        // But spec doesn't specify this https://w3c.github.io/uievents/#event-type-click
+
+        // Servo-specific: Trigger if within 10px of the down point
+        if let InputEvent::MouseButton(mouse_button_event) = event.event {
+            if let (Some(mouse_down_button), MouseButtonAction::Up) =
+                (self.mouse_down_button.get(), mouse_button_event.action)
+            {
+                let pixel_dist = self.relative_mouse_down_point.get() - mouse_button_event.point;
+                let pixel_dist = (pixel_dist.x * pixel_dist.x + pixel_dist.y * pixel_dist.y).sqrt();
+                if mouse_down_button == mouse_button_event.button && pixel_dist < 10.0 {
```
Comment (yezhizhen) [inline components/script/script_thread.rs:3364]: Originally, this is also scaled by `hidpi_scale_factor`. I don't know how to properly add that logic here tho, as this part also handles mobile event now.

File: components/script/script_thread.rs (hunk 1 above)
Comment (yezhizhen) [reply components/script/script_thread.rs]: > ..., which changes a lot of things (and other unrelated `InputEvent`) in the way. 

Eventually it turns out this is not true, which is good.

**Review by jdm — APPROVED** [review]
This looks good! Thanks for fixing this.

**Comment by yezhizhen** [comment]
I know this is merged. But after pondering, should `relative_mouse_down_point` be tied with `Document` instead of `ScriptThread`?

Otherwise, we might 
1. Trigger mouse down in one tab/iframe
2. Move to another. But that context is still around.

@jdm @xiaochengh

**Comment by jdm** [comment]
I thought about that when reading the code. I'm not sure it matters, because the user would need to still perform a second mouse down action before another mouse up, which would reset the state.

**Comment by yezhizhen** [comment]
What if I mouse down in one iframe, and then drag by 8px to another pipeline, and then release?
Or with WebDriver: pointerdown, switch to another tab/window, pointerup within 10px of `relative_mouse_down_point`? (A bit contrived example)

**Comment by xiaochengh** [comment]
@yezhizhen I feel like this can be left as an open issue to discuss.

With mouse, we probably want to avoid such behaviors. But with touch, we probably need such behaviors since touch coordinates are not accurate.
