### PR TITLE
script: Fix MutationObserver to use `Dom` instead of `DomRoot`

### LINKED ISSUE #40602: MutationObserver and related code shouldn't store DomRoot values
Using DomRoot in fields of heap-allocated DOM objects risks creating unbreakable cycles between GC-owned values. In this case:
* https://github.com/servo/servo/blob/813280860e5c6caa1af84dd3dc811f5073711c66/components/script/dom/mutationobserver.rs#L33-L34
* https://github.com/servo/servo/blob/59526928afc81c840f9890eb0a653b16e8128ba6/components/script/dom/mutationobserver.rs#L55-L56

We should use `Dom` values in these fields instead, and any code that returns values to callers should do the [Dom->DomRoot](https://doc.servo.org/script_bindings/root/struct.Dom.html#method.as_rooted) conversion at that point. We'll need to mark RegisteredObserver as `#[cfg_attr(crown, crown::unrooted_must_root_lint::must_root)]` to allow `./mach build --use-crown` to pass, too.

### PR DESCRIPTION
**Pull request by WaterWhisperer**
converts MutationObserver's record_queue and node_list, as well as RegisteredObserver's observer field, to use Dom<T> instead.

Testing: `./mach build --use-crown` pass locally
Fixes #40602

### CODE REVIEW

File: components/script/dom/mutationobserver.rs [hunk 1]
```diff
@@ -347,24 +351,36 @@ impl MutationObserverMethods<crate::DomTypeHolder> for MutationObserver {
...
+            .collect();
         self.record_queue.borrow_mut().clear();
         records
     }
 
     /// <https://dom.spec.whatwg.org/#dom-mutationobserver-disconnect>
     fn Disconnect(&self) {
         // Step 1
-        let mut nodes = self.node_list.borrow_mut();
-        for node in nodes.drain(..) {
```
Comment (Taym95) [inline components/script/dom/mutationobserver.rs:367]: used to drain the nodes but this changes the original implementation

File: components/script/dom/mutationobserver.rs [hunk 2]
```diff
@@ -347,24 +351,36 @@ impl MutationObserverMethods<crate::DomTypeHolder> for MutationObserver {
...
+        let nodes: Vec<DomRoot<Node>> = self
```
Comment (Taym95) [inline components/script/dom/mutationobserver.rs]:
```suggestion
        let nodes = self
```
explicit type really needed?

File: components/script/dom/mutationobserver.rs (hunk 1 above)
Comment (WaterWhisperer) [reply components/script/dom/mutationobserver.rs]: using drain will cause a crown linting error
Image

Comment (WaterWhisperer) [reply components/script/dom/mutationobserver.rs:367]: using drain will cause a crown linting error
截图 2025-11-13 22-23-05

Comment (Taym95) [reply components/script/dom/mutationobserver.rs:367]: Ah this is the same code since now you call `self.node_list.borrow_mut().clear();`

**Review by Taym95 — APPROVED** [review]
