### PR TITLE
layout: Force outside ::marker to establish a BFC

### LINKED ISSUE #34040: Overlapping Elements on Wikipedia
**Describe the bug:**
Visiting Wikipedia, I see that some text overlaps with an image. Refer to the screenshot.
Screenshot from 2024-10-28 11-06-44

**To Reproduce:**
Visit https://en.wikipedia.org. This problem occurs no matter what the window's dimensions are, so I didn't have to resize it to any particular size.

**Platform:**
Observed this on Linux and macOS.

### LINKED ISSUE #37222: List markers float on the right when preceded by a element with float layout
Testcase:
```html
<!DOCTYPE html>
<html>
<body>
    <div style="float:left">
    </div>
    <ul>
        <li>
            Foobar
        </li>
        <li>
            Foobar
        </li>
        <li>
            Foobar
        </li>
    </ul>
</body>
</html>
```

Servo:

Image

Firefox:

Image

Reduced from http://j2c.py.gy

### PR DESCRIPTION
**Pull request by Loirooriol**
Even though we were continuing the parent BFC, we weren't updating the SequentialLayoutState to have the correct containing block info. That caused problem in the presence of floats.

This patch establishes an independent BFC, which avoids the problem. This seems reasonable since outside markers are out-of-flow-ish, and it matches Firefox. Blink implements them as inline-blocks, so they should also establish a BFC.

Testing: Adding new tests. Some still fail because of a different issue. Also, adding an expectation for several existing tests that were missing it.
Fixes: #37222

### CODE REVIEW

File: components/layout/flow/mod.rs [hunk 1]
```diff
@@ -308,7 +308,7 @@ pub(crate) struct CollapsibleWithParentStartMargin(bool);
 pub(crate) struct OutsideMarker {
     pub list_item_style: Arc<ComputedValues>,
     pub base: LayoutBoxBase,
-    pub block_container: BlockContainer,
+    pub bfc: BlockFormattingContext,
```
Comment (mrobinson) [inline components/layout/flow/mod.rs]: Nit: Let's avoid the abbreviation for clarity:

```suggestion
    pub block_formatting_context: BlockFormattingContext,
```

**Review by mrobinson — APPROVED** [review]
Looks like the two failures are unrelated.

**Comment by Loirooriol** [comment]
Can you check the test changes? Several existing tests had no expectation
