### PR TITLE
layout: Add placeholders for text carets after finishing a line

### LINKED ISSUE #41338: Carets do not render on leading newlines in <textarea>
**Describe the bug:**
While working on #41330 I encountered yet more issues with how carets are rendered.
Carets do not render in the last two leading newlines of a `<textarea>`, if any. 

Here are various examples:
```
Hello,

World!
{1}
{2}
```

```
{3}
{4}
```

```

Hi there!
{5}
```

The current hypothesis is this:
* Rendering fails on on one linebreak seemingly because `TextRunSegment` has one too few `GlyphRun`s.
* In some cases rendering fails because the linebreak is deferred
* This seems to add up to two missing caret positions?

**To Reproduce:**
1. Open Servoshell like `./mach run 'data:text/html,<textarea cols=50 rows=10>'`
2. Enter one linebreak. The caret is now gone

Note: These failures to render the caret is in almost all cases currently masked by the bugs addressed by #41330

**Platform:**
NixOS 25.11.20251117.89c2b23 (Xantusia) x86_64, Mesa/Gnome/Wayland

### PR DESCRIPTION
**Pull request by mrobinson**
Instead of readily adding a strut for text carets when processing a line
break, wait until a line is finished. This allows placing a strut on the
final line. In addition to fixing #41338 this will also make it possible
to handle line breaks as a separate kind of text run item so that we can
preserve shaping results between layouts.

In addition, some changes are made in script to ensure that these placeholders
are never placed for non-textual input elements.

Testing: This change adds a Servo-specific WPT test. Caret rendering isn't specified.
Fixes: #41338

### CODE REVIEW

File: components/script/dom/html/input_element/mod.rs [hunk 1]
```diff
@@ -2008,6 +1999,8 @@ impl VirtualMethods for HTMLInputElement {
 
                         *self.input_type.borrow_mut() =
                             InputType::new_from_atom(attr.value().as_atom());
+                        self.is_textual_or_password
+                            .set(self.input_type().is_textual_or_password());
```
Comment (SimonSapin) [inline components/script/dom/html/input_element/mod.rs:2003]: This is in the `attribute_mutated` method of the `VirtualMethods` trait. Is that called when initially creating an element from HTML parsing?

File: components/layout/flow/inline/mod.rs [hunk 2]
```diff
@@ -786,6 +797,10 @@ struct InlineContainerState {
     /// is vertical).
     pub baseline_offset: Au,
 
+    /// The primary font used for this container, if one exists. This is the font that is
+    /// used when not falling back.
+    default_font: Option<FontRef>,
```
Comment (SimonSapin) [inline components/layout/flow/inline/mod.rs:802]: What does “not falling back” mean here?

File: components/layout/flow/inline/mod.rs [hunk 3]
```diff
@@ -1606,31 +1629,52 @@ impl InlineFormattingContextLayout<'_> {
...
+            self.ifc
+                .shared_selection
+                .clone()
+                .map(|shared_selection| TextRunOffsets {
+                    shared_selection,
+                    character_range: line_start_offset..line_start_offset + 1,
+                })
+        else {
+            return;
+        };
```
Comment (SimonSapin) [inline components/layout/flow/inline/mod.rs:1646]: Small nit, feel free to ignore

Since we have `let Some(…) = ` unwrapping the `Option` anyway, calling `map` is slightly more verbose than necessary:

```suggestion
        let Some(shared_selection) = self.ifc.shared_selection.clone() else {
            return;
        };
        let offsets = TextRunOffsets {
            shared_selection,
            character_range: line_start_offset..line_start_offset + 1,
        };
```

**Review by SimonSapin — APPROVED** [review]
A few questions but looks good overall

File: components/layout/flow/inline/mod.rs (hunk 2 above)
Comment (mrobinson) [reply components/layout/flow/inline/mod.rs:802]: That means using a fallback font. I write this comment to make this a bit clearer.

File: components/layout/flow/inline/mod.rs (hunk 3 above)
Comment (mrobinson) [reply components/layout/flow/inline/mod.rs]: Oh, good point. I'll make this change.

File: components/script/dom/html/input_element/mod.rs (hunk 1 above)
Comment (mrobinson) [reply components/script/dom/html/input_element/mod.rs:2003]: Yes, I believe it is called when the attribute is processed by the parser. There is one more case, which is when there is no `type` attribute specified at all. In that case this method will not be called.
