### PR TITLE
Fix Servo taking a long time to start on MacOS after a recompile

### LINKED ISSUE #30717: Servo takes a long time to start on MacOS after a recompile
Servo takes a *long* time to start directly after a recompilation on MacOS. A bit of debugging reveals that this is caused by the generation of the GStreamer plugin cache. Subsequent executions still take a while to load, but much less time.

cc @atbrakhi

### PR DESCRIPTION
**Pull request by atbrakhi**
With [#405](https://github.com/servo/media/pull/405) changes in `servo/media` we move initialization of the media engine to a background thread. This allows GStreamer plugin cache initialization to happen off the main thread. This PR updates the `init` function in `libservo` to adapt the behavior of `init_with_backend`

Co-authored-by: Martin Robinson <mrobinson@igalia.com>

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #30717

### CODE REVIEW

**Comment by atbrakhi** [comment]
Draft, because we should merge it after [Initialize media in the background](https://github.com/servo/media/pull/405) is merged.

File: components/servo/lib.rs [hunk 1]
```diff
@@ -112,24 +112,26 @@ mod media_platform {
...
+                &gstreamer_plugins::GSTREAMER_PLUGINS,
+            ) {
+                Ok(b) => b,
+                Err(e) => {
+                    eprintln!("Error initializing GStreamer: {:?}", e);
+                    std::process::exit(1);
+                },
+            };
+            backend
+        });
```
Comment (mrobinson) [inline components/servo/lib.rs:134]: This could be a little bit simpler:

```suggestion
            match GStreamerBackend::init_with_plugins(
                plugin_dir,
                &gstreamer_plugins::GSTREAMER_PLUGINS,
            ) {
                Ok(b) => b,
                Err(e) => {
                    eprintln!("Error initializing GStreamer: {:?}", e);
                    std::process::exit(1);
                },
            }
        });
```

Comment (atbrakhi) [reply components/servo/lib.rs]: thanks. Done in [a99fd2f](https://github.com/servo/servo/pull/30726/commits/a99fd2fd889e39a9df2b394dc4d533b8fc869b28)

**Review by mrobinson — APPROVED** [review]
