### PR TITLE
layout: Ensure IFC for abspos with inline-level original display

### LINKED ISSUE #39017: Layout: BoxTree construction with absolutely positioned `::before` pseudo element
**Describe the bug:**

The way a `::before` pseudo element is handled during the construction of BoxTree seems to be different from FireFox as shown in the screenshots below. 

```html
<!DOCTYPE html>
<style>
  div::before { content: "___"; position: absolute; }
  div {
    text-align: center;
  }
</style>
<div>words</div>
```

| servo | FireFox |
|-------|--------|
|Image|Image|

First, apologies that my wording may be incorrect given my limited knowledge on layout. With my limited knowledge about how layout works, I have some rough guess on the root cause, and I'd like to seek for guidance on proper way to resolve this.

In [`BlockContainerBuilder::handle_absolutely_positioned_element`](https://github.com/servo/servo/blob/00c1f79a1d018608c381695d7bcaf0e32e3cd5ae/components/layout/flow/construct.rs#L583), the `::before` pseudo element would be placed into `block_level_boxes` even though all other elements in the `<div>` are inline-level only; however, changing `div::before` to `div::after` in the code snippet below would "correctly" place the `::after` pseudo element into the `inline_formatting_context_builder` and would yield the same rendering as FireFox. 

Forcing the `::before` to be placed in the `inline_formatting_context_builder` would fix this. So my initial thought is that in [`traverse_children_of`](https://github.com/servo/servo/blob/00c1f79a1d018608c381695d7bcaf0e32e3cd5ae/components/layout/dom_traversal.rs#L121), before calling [`traverse_eager_pseudo_element(PseudoElement::Before, ...)`](https://github.com/servo/servo/blob/00c1f79a1d018608c381695d7bcaf0e32e3cd5ae/components/layout/dom_traversal.rs#L126), first take an iteration over the children that are not out of flow and determine whether they are all inline-level content. If they are all inline level content, the `TraversalHandler` should somehow initialize the corresponding `inline_formatting_context_builder` before traversing the `::before` pseudo element.

I've tried reading the spec but got more confused. The spec (https://www.w3.org/TR/css-display-3/#block-container) states that

> A block container that contains only inline-level content establishes a new [inline formatting context](https://www.w3.org/TR/css-display-3/#inline-formatting-context).

and

> Absolute positioning or floating an element [blockifies](https://www.w3.org/TR/css-display-3/#blockify) the box’s display type.

I'm not sure if an absolutely positioned `::before` pseudo element is still considered as the "content" here, and thus not sure whether it's proper to treat the case shown above as inline-content-only.

I'd like to seek advice on whether my analysis is correct (I'm really confused by the spec itself) and what an ideal solution would look like (eg. this might introduce changes to `TraversalHandler`, should it simply separate the handler for regular element and pseudo element?)

**To Reproduce:**
./mach run link-to-the-example-HTML-above

**Platform:**
macOS 15.6, servo commit 00c1f79a1d018608c381695d7bcaf0e32e3cd5ae

### PR DESCRIPTION
**Pull request by Loirooriol**
Absolutely positioned elements get blockified, but their static position still depends on the original display. Therefore, if we encounter an abspos with an inline-level original display, we will now ensure that it's handled in an inline formatting context. This way its static position will correctly take into account things like `text-align`.

Testing: Several WPT tests are now passing.
Fixes: #39017

### CODE REVIEW

File: components/script/layout_dom/element.rs [hunk 1]
```diff
@@ -615,6 +615,12 @@ impl<'dom> style::dom::TElement for ServoLayoutElement<'dom> {
                 return true;
             }
 
+            if new_box.position.is_absolutely_positioned() &&
+                old_box.original_display != new_box.original_display
+            {
+                return true;
+            }
+
```
Comment (mrobinson) [inline components/script/layout_dom/element.rs:623]: Oh, nice catch. Maybe this was causing other issues as well.

**Review by mrobinson — APPROVED** [review]
