### PR TITLE
 layout: Disable the speculation of block formatting contexts' inline sizes if the block formatting contexts have negative margins.

### LINKED ISSUE #13299: Wrong block width when using negative margins and overflow
The width of a `display: block` element with styles such as:

```css
div {
  width: auto;
  margin-left: -20px;
  margin-right: -20px;
  overflow: auto;
}
```

will be wrong in Servo. It will be 40px narrower than the same block with `overflow: visible`. This problem happens with all `overflow` values other than `visible`.

Here’s a reduced test case:
http://fvsch.com/code/bugs/servo-negative-margins-width/

- Expected behavior: in each section, all blue blocks should have the same width.
- Actual result: in each section, only the first block (`overflow:visible`) has the correct width, all others are too short.

Tested with Servo Nightly 0.0.1-e3d946b (2016-09-16 I think?).

### PR DESCRIPTION
**Pull request by pcwalton**
The heuristics that determine how and whether floats flow into the
margins are not valid in that case.

Closes #13299.

r? @notriddle

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13302)

### CODE REVIEW

File: components/layout/block.rs [hunk 1]
```diff
@@ -1666,33 +1666,41 @@ impl BlockFlow {
...
-                            self.fragment.margin.inline_end);
-                    self.fragment.border_box.size.inline =
-                        self.fragment.border_box.size.inline -
-                        speculated_left_float_size -
-                        speculated_right_float_size;
-                }
-            }
-            FormattingContextType::None | FormattingContextType::Other => {}
+            FormattingContextType::None | FormattingContextType::Other => return,
+            FormattingContextType::Block => {}
```
Comment (notriddle) [inline components/layout/block.rs]: Nit: `if self.formatting_context_type() != FormattingContextType::Block { return } `

**Review by notriddle — APPROVED** [review]
You can r=notriddle if you think it's better with the match. Otherwise, LGTM.

File: tests/wpt/mozilla/tests/css/block_formatting_context_negative_margins_a.html [hunk 2]
```diff
@@ -0,0 +1,88 @@
+<!DOCTYPE html>
+<html><head>
+<!-- Original URL: http://fvsch.com/code/bugs/servo-negative-margins-width/ -->
```
Comment (notriddle) [inline tests/wpt/mozilla/tests/css/block_formatting_context_negative_margins_a.html]: You need to add `<link rel="match" href="block_formatting_context_negative_margins_ref.html">`

File: tests/wpt/mozilla/tests/css/block_formatting_context_negative_margins_ref.html [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+</head>
+<body>
+
+<main>
+    <h1>Servo test case: wrong block width with negative margins and overflow</h1>
+
+    <section>
+        <h2>With <code>width: auto</code></h2>
+        <p>The following blocks have negative margins on the sides. They
+ should end up being as large as the red container, with their left and
```
Comment (notriddle) [inline tests/wpt/mozilla/tests/css/block_formatting_context_negative_margins_ref.html]: Trailing whitespace.

File: tests/wpt/mozilla/tests/css/block_formatting_context_negative_margins_a.html [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+</head>
+<body>
+
+<main>
+    <h1>Servo test case: wrong block width with negative margins and overflow</h1>
+
+    <section>
+        <h2>With <code>width: auto</code></h2>
+        <p>The following blocks have negative margins on the sides. They
+ should end up being as large as the red container, with their left and
```
Comment (notriddle) [inline tests/wpt/mozilla/tests/css/block_formatting_context_negative_margins_a.html]: Trailing whitespace.

**Review by notriddle — CHANGES_REQUESTED** [review]
Tidy found a couple problems with the test code.

**Comment by notriddle** [comment]
@pcwalton You still don't have the `<link rel="match">` in your reftest. It's going to fail on the `MANIFEST.json`.

**Review by notriddle — APPROVED** [review]
