### PR TITLE
libservo: Allow responding to auxiliary `WebView` open requests asynchronously

### LINKED ISSUE #41220: `WebViewDelegate::request_open_auxiliary_webview` should become asynchronous
Currently `WebViewDelegate::request_open_auxiliary_webview` expects a synchronous reply with a `WebView`. This doesn't work so well with windowing libraries like `winit`, when the popup should open in a new system window (necessary for WebDriver). The issue is that to create a new toplevel window, `winit` needs access to a `&ActiveEventLoop` which is only available on window callbacks. We do not have access to this inside the delegate method, so it would be ideal to store the request and answer it asynchronously during the `winit` event loop callback.

### PR DESCRIPTION
**Pull request by mrobinson**
This change renames the `WebView::request_open_auxiliary_webview` to
`WebView::request_create_new` and allows responding to it
asynchronously. A new `CreateNewWebViewRequest` is exposed that keeps
the response sender alive as long as it is not dropped. If dropped
without a response, the original request is denied with `None`.

This also makes the API a bit harder to misuse, because the public
`WebViewBuilder::new_auxiliary` factory is no longer exposed, in favor
of `CreateNewWebViewRequest::builder`. This makes it impossible to
create an auxiliary `WebView` without a corresponding request. This
still isn't the idea API, which would be to make creating an auxiliary
`WebView` and normal `WebView` exactly the same, but it's an
improvement.

This will allow opening auxiliary `WebView`s in new toplevel platform
windows in servoshell. That will be handled in a followup. In addition,
the `CreateNewWebViewRequest` can eventually hold the arguments passed
to `window.open`.

Testing: Corresponding changes are made in servoshell, which means that
this is tested by the WPT calling `window.open`.
Fixes: #41220.

### CODE REVIEW

File: components/servo/webview.rs [hunk 1]
```diff
@@ -730,26 +754,30 @@ pub struct WebViewBuilder {
...
             delegate: Rc::new(DefaultWebViewDelegate),
+            create_new_webview_responder: None,
         }
     }
 
-    pub fn new_auxiliary(servo: &Servo, rendering_context: Rc<dyn RenderingContext>) -> Self {
-        let mut builder = Self::new(servo, rendering_context);
-        builder.auxiliary = true;
+    pub(crate) fn new_for_create_request(
+        servo: Servo,
```
Comment (mukilan) [inline components/servo/webview.rs]: Does this need to be a by-value parameter? Making it a reference will keep the method consistent with `Self::new` which anyway clones the handle internally.

**Review by mukilan — APPROVED** [review]
Nice!

File: components/servo/webview.rs (hunk 1 above)
Comment (mrobinson) [reply components/servo/webview.rs]: Sure. I've done this.
