### PR TITLE
layout: Always treat SVG elements as replaced content.

### LINKED ISSUE #40900: `<svg>` reports inconsistent sizes
```html
<!DOCTYPE html>
<svg style="border: 3px solid"></svg>
<script>
let el = document.querySelector("svg");
document.body.append(el.clientWidth + " " + el.clientWidth);
</script>
```

The result is `0 300`.

### LINKED ISSUE #42291: panic: index out of bounds: the len is 2 but the index is 2 (thread Script#1, at components/shared/paint/display_list.rs:473)
This is different to https://github.com/servo/servo/issues/42215 as it does not invole attachRoot.

Minimal testcase:

```html
<!DOCTYPE html>
<style>
  animate {
    display: inline-table;
    transform: translateZ(0);
  }
</style>
<svg><animate id="animate"></animate></svg>
<script>
  onload = _ => document.getElementById("animate").scrollIntoView();
</script>
```

System: Linux
Version: Version: Servo 0.0.4-c60c646f3
Command: `./servo/servo`

```
index out of bounds: the len is 2 but the index is 2 (thread Script#1, at components/shared/paint/display_list.rs:473)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::panic_with_hook
   3: std::panicking::panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: __rustc::rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::panic_bounds_check
   8: paint_api::display_list::ScrollTree::cumulative_node_transform
   9: layout::query::root_transform_for_layout_node
  10: <layout::layout_impl::LayoutThread as layout_api::Layout>::query_box_area
  11: script::dom::window::Window::box_area_query_without_reflow
  12: script::dom::node::Node::border_box
  13: script::dom::element::Element::scroll_into_view_with_options
  14: <script::dom::element::Element as script_bindings::codegen::GenericBindings::ElementBinding::Element_Binding::ElementMethods<script::dom::bindings::codegen::DomTypeHolder::DomTypeHolder>>::ScrollIntoView
  15: script_bindings::codegen::GenericBindings::ElementBinding::Element_Binding::scrollIntoView::{{closure}}
  16: mozjs::panic::wrap_panic
  17: script_bindings::codegen::GenericBindings::ElementBinding::Element_Binding::scrollIntoView
  18: CallJitMethodOp
  19: script_bindings::utils::generic_call
  20: script_bindings::utils::generic_method
  21: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  22: _ZN2js9InterpretEP9JSContextRNS_8RunStateE
  23: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  24: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  25: _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
  26: _ZN2JS4CallEP9JSContextNS_6HandleINS_5ValueEEES4_RKNS_16HandleValueArrayENS_13MutableHandleIS3_EE
  27: script::dom::event::inner_invoke
  28: script::dom::event::invoke
  29: script::dom::event::Event::dispatch
  30: <T as script::task::TaskBox>::run_box
  31: script::script_thread::ScriptThread::handle_msg_from_script
  32: script::script_thread::ScriptThread::handle_msgs::{{closure}}
  33: script::script_thread::ScriptThread::handle_msgs
  34: std::sys::backtrace::__rust_begin_short_backtrace
  35: core::ops::function::FnOnce::call_once{{vtable.shim}}
  36: std::sys::thread::unix::Thread::new::thread_start
  37: start_thread
             at ./nptl/pthread_create.c:447:8
  38: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
```

### PR DESCRIPTION
**Pull request by jdm**
The current implementation treats an SVG element that needs a new serialized tree as non-replaced content, so we attempt to lay out all of the children. If serialization is successful, subsequent layouts treat the SVG as replaced content and ignore the children, but the children's layout data is never cleaned up. This means that layout queries against those children can return stale data, which can lead to unexpected results. By always treating SVG elements as replaced content, we remove this footgun and improve consistency.

Testing: New crashtest added. It doesn't make sense to upstream this because our SVG implementation is very nonstandard.
Fixes: #42291
Fixes: #40900

### CODE REVIEW

**Review by mukilan — APPROVED** [review]

**Review by yezhizhen — APPROVED** [review]
https://github.com/servo/servo/runs/63494868071

Result looks good.

**Comment by Loirooriol** [comment]
This fixes #40900 too

File: components/layout/replaced.rs [hunk 1]
```diff
@@ -267,33 +267,35 @@ impl ReplacedContents {
...
-                return None;
+                None
             },
             Some(Err(_)) => {
                 // Don't attempt to serialize if previous attempt had errored.
-                return None;
+                None
             },
-            Some(Ok(svg_source)) => svg_source,
+            Some(Ok(svg_source)) => Some(svg_source),
```
Comment (Loirooriol) [inline components/layout/replaced.rs]: Maybe just `Some(result) => result.ok(),`

**Review by Loirooriol — APPROVED** [review]

**Comment by yezhizhen** [comment]
Any reason we can't proceed with this?

**Review by mrobinson — APPROVED** [review]

**Comment by mrobinson** [comment]
I'm going to go ahead and land this one as it fixes a crash.

**Comment by Loirooriol** [comment]
Needs to update test expectations: https://github.com/servo/servo/runs/63494868071

**Comment by mrobinson** [comment]
Looks like some more tests pass. I have updated expectations.

**Comment by Loirooriol** [comment]
I think you forgot to update, it's still failing

**Comment by mrobinson** [comment]
Okay. I'm not sure what happened, but I've updated the results now.
