### PR TITLE
Unify background placement code

### LINKED ISSUE #16657: Respect background-repeat, -size properties for gradients
Background gradients should vary depending on the value of `background-repeat` and `background-size`.

Manual testcase:

The gradient should be displayed four times.

```html
<!DOCTYPE html>
<html>

<head>
    <style>
        div {
            background-image: linear-gradient(45deg, red, green, blue);
            background-size: 25%;
            border: 2px solid #92b901;
            background-repeat: repeat;
        }
    </style>
</head>

<body>

    <div>
        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna
        aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl
        ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie
        consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit
        praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
    </div>

</body>

</html>
```

### LINKED ISSUE #19482: Better support for CSS backgrounds
This web site contains a couple of custom CSS backgrounds: http://lea.verou.me/css3patterns/

While some backgrounds are being displayed correctly, most backgrounds have bugs of varying severity.

Screenshot of the page in Firefox (everything fine):

screenshot_20171204_192949

Screenshot in servo as of commit e4dba3abef2a4941c5a4d95d58ae0b864ad10961 :

screenshot_20171204_192925

### LINKED ISSUE #19577: Implement background-clip correctly for image backgrounds
Images with background-clip are off.

[Source](https://gist.github.com/pyfisch/d45929d0c53adb2b82690fd64de2b518)
Servo:
background-clip-servo
Firefox (expected rendering):
background-clip-firefox

### LINKED ISSUE #19626: Wrong linear-gradient rendering
Go to https://engineering.instagram.com/let-your-code-type-hint-itself-introducing-open-source-monkeytype-a855c7284881
Link to Github is rendering incorrect. Underline is made with linear-gradient.
link servo

### PR DESCRIPTION
**Pull request by pyfisch**
Merges the implementations for background-image placement
from gradients and images. Add missing parts and fix bugs.

Now supported are the CSS properties:

* background-attachment (except for local value, see #19650)
* background-clip
* background-origin
* background-position-x/y
* background-repeat
* background-size

It should be noted that backgrounds are not clipped to
rounded border corners.
(This was done before but worked only in simple cases)
See: #19649

This solves the following issues:
closes #19626
closes #16657
closes #19482 (examples from http://lea.verou.me/css3patterns/ are rendered perfectly but the round border is completely ignored now)
closes #19577

- `./mach build -d` does not report any errors
- `./mach test-tidy` does not report any errors

I enabled a few tests with the first commit but I have written about a dozen manual tests I will try to turn into ref tests either before or after this patch lands.

@bors-servo try

The relationship between the different inputs is visualized in this flowchart:
flowchart-background

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19651)

### CODE REVIEW

File: components/layout/display_list_builder.rs [hunk 1]
```diff
@@ -1024,6 +1041,176 @@ fn convert_ellipse_size_keyword(keyword: ShapeExtent,
...
+        *size = Au(0);
+        *tile_spacing = Au(0);
+        return;
+    }
+
+    // Per the spec, if the space available is not enough for two images, just tile as
+    // normal but only display a single tile.
+    if image_size * 2 >= *size {
+        tile_image(position,
+                                        size,
```
Comment (emilio) [inline components/layout/display_list_builder.rs]: nit: Indentation here is off.

File: components/layout/display_list_builder.rs [hunk 2]
```diff
@@ -1184,172 +1362,103 @@ impl FragmentDisplayListBuilding for Fragment {
...
-                Size2D::new(bounds.size.width,
-                            Au::from_f64_px(bounds.size.width.to_f64_px() / image_aspect_ratio))
-            }
-
-            (BackgroundSize::Contain, true) | (BackgroundSize::Cover, false) => {
-                Size2D::new(Au::from_f64_px(bounds.size.height.to_f64_px() * image_aspect_ratio),
-                            bounds.size.height)
-            }
+    fn compute_background_placement(&self,
+                                    state: &mut DisplayListBuildState,
```
Comment (emilio) [inline components/layout/display_list_builder.rs]: nit: Maybe indenting these using block indentation, like:

```rust
fn compute_background_placement(
    &self,
    state: &mut ...,
) -> (Rect<Au>, Size2D<Au>, Size2D<Au>, Rect<Au>) {
```

is nicer. We should reformat this file to that style eventually anyway.

File: components/layout/display_list_builder.rs [hunk 3]
```diff
@@ -1184,172 +1362,103 @@ impl FragmentDisplayListBuilding for Fragment {
...
+                                    style: &ComputedValues,
+                                    absolute_bounds: Rect<Au>,
+                                    intrinsic_size: Option<Size2D<Au>>,
+                                    index: usize)
+                                    -> (Rect<Au>,
```
Comment (emilio) [inline components/layout/display_list_builder.rs]: nit: Maybe a struct would be nicer instead of a tuple? It's not clear what each field means without looking at the function implementation.

**Review by emilio — COMMENTED** [review]
This looks like a pretty neat cleanup!

Haven't gone through the math yet, but looks nice overall.

**Comment by pyfisch** [comment]
Fixed nits.

**Comment by pyfisch** [comment]
Another bug is that `background-attachment: fixed` is scrolled with the window contents while it should stay attached to the viewport. (This was *not* broken by this PR) See these two tests:
* servo/webrender#1301 https://staktrace.github.io/moz-pages/bug/1368496/
* servo/tests/wpt/web-platform-tests/css/css-backgrounds/background-attachment-fixed.html

Can you give me an example how to accomplish the fixed positioning? The webrender issue mentions push_clip_and_scroll_info but how exactly is it used here?

**Comment by emilio** [comment]
> Can you give me an example how to accomplish the fixed positioning? The webrender issue mentions push_clip_and_scroll_info but how exactly is it used here?

Probably @glennw or @kvark can :)

**Comment by kvark** [comment]
Also cc @mrobinson

File: components/layout/display_list_builder.rs [hunk 4]
```diff
@@ -1024,6 +1028,194 @@ fn convert_ellipse_size_keyword(keyword: ShapeExtent,
...
+    *tile_spacing = (size_remaining - space_for_middle_tiles) / (num_middle_tiles + 1);
+}
+
+/// Tile an image
+fn tile_image(position: &mut Au,
+              size: &mut Au,
+              absolute_anchor_origin: Au,
+              image_size: Au) {
+    // Avoid division by zero below!
+    if image_size == Au(0) {
```
Comment (emilio) [inline components/layout/display_list_builder.rs]: I think it'd make sense to comment why the outparams are sane in this case, or why it doesn't matter..

File: components/layout/display_list_builder.rs [hunk 5]
```diff
@@ -1024,6 +1028,194 @@ fn convert_ellipse_size_keyword(keyword: ShapeExtent,
...
+/// For a given area and an image compute how big the
+/// image should be displayed on the background.
+fn compute_background_image_size(bg_size: BackgroundSize<LengthOrPercentageOrAuto>,
+                                 bounds_size: Size2D<Au>,
+                                 intrinsic_size: Option<Size2D<Au>>)
+                                 -> Size2D<Au> {
+    let own_size = if let Some(size) = intrinsic_size {
+        size
+    } else {
+        return match bg_size {
```
Comment (emilio) [inline components/layout/display_list_builder.rs]: This may be cleaner with `match intrinsic_size { ...`, but no strong preference I guess

File: components/layout/display_list_builder.rs [hunk 6]
```diff
@@ -1184,172 +1367,100 @@ impl FragmentDisplayListBuilding for Fragment {
...
+            css_clip.size.width);
+        tile_image_axis(
+            bg_repeat.1,
+            &mut bounds.origin.y,
+            &mut bounds.size.height,
+            &mut tile_size.height,
+            &mut tile_spacing.height,
+            pos_y,
+            css_clip.origin.y,
+            css_clip.size.height);
```
Comment (emilio) [inline components/layout/display_list_builder.rs]: nit: Paren on the next line, here and in the rest of the calls using this format.

File: components/layout/display_list_builder.rs [hunk 7]
```diff
@@ -1184,172 +1367,100 @@ impl FragmentDisplayListBuilding for Fragment {
...
+
+        return BackgroundPlacement { bounds, tile_size, tile_spacing, css_clip }
```
Comment (emilio) [inline components/layout/display_list_builder.rs]: nit: No need for `return`.

**Review by emilio — COMMENTED** [review]
This looks fine to me. Not sure if you want to wait for the fixed image stuff or land this before, or prefer review from @glennw / @kvark / @mrobinson.

File: components/layout/display_list_builder.rs (hunk 5 above)
Comment (pyfisch) [reply components/layout/display_list_builder.rs]: I am not sure if understand this. `match bg_size { ...` matches on the CSS property `background-size`. Maybe you meant I should replace `own_size` with `intrinsic_size`?

Comment (mbrubeck) [reply components/layout/display_list_builder.rs]: As a replacement for `if let Some(size) = intrinsic_size` on line 1050

Comment (pyfisch) [reply components/layout/display_list_builder.rs]: Thanks. Will change it.

**Comment by pyfisch** [comment]
Force pushed the fixed nits.

**Comment by pyfisch** [comment]
> This looks fine to me. Not sure if you want to wait for the fixed image stuff or land this before, or prefer review from @glennw / @kvark / @mrobinson.

I'd like to land this as is.

File: components/layout/display_list_builder.rs [hunk 8]
```diff
@@ -1024,6 +1028,201 @@ fn convert_ellipse_size_keyword(keyword: ShapeExtent,
...
+
+/// For a given area and an image compute how big the
+/// image should be displayed on the background.
+fn compute_background_image_size(bg_size: BackgroundSize<LengthOrPercentageOrAuto>,
+                                 bounds_size: Size2D<Au>,
+                                 intrinsic_size: Option<Size2D<Au>>)
+                                 -> Size2D<Au> {
+    match intrinsic_size {
+        None => {
+            match bg_size {
```
Comment (emilio) [inline components/layout/display_list_builder.rs]: Well, I would've keep the early return, just using `match`, but it's not a big deal, this looks fine too, thanks!

File: components/layout/display_list_builder.rs [hunk 9]
```diff
@@ -1024,6 +1028,201 @@ fn convert_ellipse_size_keyword(keyword: ShapeExtent,
...
+/// Tile an image
+fn tile_image(position: &mut Au,
+              size: &mut Au,
+              absolute_anchor_origin: Au,
+              image_size: Au) {
+    // Avoid division by zero below!
+    // Images with a zero width or height are not displayed.
+    // Therefore the positions do not matter and can be left unchanged.
+    // NOTE: A possible optimization is not to build
+    // display lists in this case at all.
```
Comment (emilio) [inline components/layout/display_list_builder.rs]: nit: `s/display lists/display items/`

**Review by emilio — APPROVED** [review]
Ok, let's land it as soon as that nit is addressed :)

**Comment by emilio** [comment]
Mind filing issues for the remaining bits @pyfisch? Thanks a lot!

**Comment by pyfisch** [comment]
> nit: s/display lists/display items/

done.

I've opened #19650, #19669, #19672 for the remaining bits. Anything missing?

**Comment by pyfisch** [comment]
Travis failure is: `oci runtime error: exec failed: container_linux.go:265: starting container process caused "could not create session key: disk quota exceeded"`

**Comment by emilio** [comment]
Yeah, same failure happened over #19668. We don't gate on travis though, so should be gtg, thanks!

@bors-servo r+

**Comment by pyfisch** [comment]
Sorry for the failing tests. My computer is really slow at running them all. Are there options to speed up `./mach test-wpt`? I just saw that the builders run  `test-wpt --release --processes 24 --total-chunks 2 --this-chunk 1 --always-succeed`. Are the tests much faster with release builds and what number of processes should be used on a quad-core Laptop? Are the other parameters relevant?

At some point I was allowed to start bors with

@bors-servo try

but this doesn't work anymore. (Or does it?)

**Comment by emilio** [comment]
It does! And those tests are unexpected passes, so we need to mark them passing, not fixing anything :)

**Comment by pyfisch** [comment]
> so we need to mark them passing, not fixing anything :)

Bad word choice on my side. I meant to mark them as passing by deleting the metadata files.

**Comment by pyfisch** [comment]
All tests passed. (Except on Mac where some builders failed.)

@emilio Can you please approve?

**Comment by emilio** [comment]
Sure thing! Thanks a lot @pyfisch!

@bors-servo r+

**Comment by CYBAI** [comment]
@pyfisch Congrats!!!!!!
