### PR TITLE
net: Relax the SVG content type detection logic.

### LINKED ISSUE #40630: Cannot display svg file
**Describe the bug:**
I open **[TPAC 2025 official website](https://www.w3.org/2025/11/TPAC/schedule.html)**. But it is awkward that the banner on the top is not shown. But rest looking pretty good!

```
<img 
  alt="TPAC 2025, 10–14 November, hybrid meeting" 
  src="images/banner.svg" 
  height="121" 
  width="480">
```

**To Reproduce:**
`./mach run -r https://www.w3.org/2025/11/TPAC/schedule.html`

**Platform:**
Any.

### PR DESCRIPTION
**Pull request by mukilan**
The current logic fails when the `Content-Type` header includes the character encoding other parameters like `qs`.

Fixes: #40630

### CODE REVIEW

File: components/net/image_cache.rs [hunk 1]
```diff
@@ -95,7 +95,15 @@ fn decode_bytes_sync(
     content_type: Option<Mime>,
     fontdb: Arc<fontdb::Database>,
 ) -> DecoderMsg {
-    let image = if content_type == Some(mime::IMAGE_SVG) {
+    let is_svg_document = content_type.is_some_and(|content_type| {
```
Comment (TimvdLippe) [inline components/net/image_cache.rs:98]: Nit: use https://github.com/servo/servo/blob/cae6350af7c734444ddd4a238f2c47d70cecc3c5/components/shared/net/mime_classifier.rs#L243 instead

Comment (TimvdLippe) [reply components/net/image_cache.rs:98]: Hm wait that skips images instead. Not sure if that works, but maybe we can consolidate logic

Comment (mukilan) [reply components/net/image_cache.rs:98]: Right, `mime_classifier` was unused in Servo when SVG support was added and it didn't do SVG image detection correctly.
https://servo.zulipchat.com/#narrow/channel/263398-general/topic/.60net.2Fmime_classifier.60.20module.20appears.20to.20be.20unused

**Comment by TimvdLippe** [comment]
Can we add a WPT test for this, given none started passing with this fix?

**Comment by mukilan** [comment]
I've added a new WPT test in [5cc962e](https://github.com/servo/servo/commit/5cc962efe8dfa6a6c73f27f0be00cbc097dddd7f)

**Review by TimvdLippe — APPROVED** [review]

**Review by yezhizhen — APPROVED** [review]
❤️
