### PR TITLE
LocalStorage: Add table initialisation for in memory databases

### LINKED ISSUE #41485: LocalStorage: In memory databases aren't initialised correctly
When creating an in memory database for localstorage, the database tables aren't created as they are for databases on disk, see the code snippet below

```rust
impl SqliteEngine {
    pub fn new(db_dir: &Option<PathBuf>, _pool: Arc<ThreadPool>) -> rusqlite::Result<Self> {
        let connection = match db_dir {
            Some(path) => {
                let path = path.join("webstorage.sqlite");
                Self::init_db(&path)?
            },
            None => Connection::open_in_memory()?,
        };
        // Initialize the database with necessary pragmas
        for pragma in DB_PRAGMAS.iter() {
            let _ = connection.execute(pragma, []);
        }
        Ok(SqliteEngine { connection })
    }

    pub fn init_db(path: &PathBuf) -> rusqlite::Result<Connection> {
        if let Some(parent) = path.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        let connection = Connection::open(path)?;
        for pragma in DB_INIT_PRAGMAS.iter() {
            let _ = connection.execute(pragma, []);
        }
        connection.execute("CREATE TABLE IF NOT EXISTS data (id INTEGER PRIMARY KEY AUTOINCREMENT, key TEXT, value TEXT);", [])?;
        Ok(connection)
    }
}
```

This led to the following error when localstorage would attempt to save
```
 ERROR storage::webstorage::engines::sqlite] localstorage save error: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("no such table: data"))
```

### PR DESCRIPTION
**Pull request by leo030303**
Fixes #41485
Added a unit test.

### CODE REVIEW

**Comment by yezhizhen** [comment]
cc @janvarga Can you also review this pls? I somehow cannot request you from UI.

File: components/storage/webstorage/engines/sqlite.rs [hunk 1]
```diff
@@ -33,11 +33,15 @@ impl SqliteEngine {
...
+    pub fn init_db(path_opt: Option<PathBuf>) -> rusqlite::Result<Connection> {
+        let connection = if let Some(path) = path_opt {
+            if let Some(parent) = path.parent() {
+                let _ = std::fs::create_dir_all(parent);
+            }
+            Connection::open(path)?
+        } else {
+            Connection::open_in_memory()?
+        };
         for pragma in DB_INIT_PRAGMAS.iter() {
```
Comment (janvarga) [inline components/storage/webstorage/engines/sqlite.rs]: It seems that all `DB_PRAGMAS` and `DB_INIT_PRAGMAS` currently apply without errors to an in-memory database. However, some of these pragmas don’t really make sense in that context, so it might be worth having a separate, explicit list for in-memory databases.

That said, I think this patch is good as is. I would just consider adding a TODO about potentially splitting the pragma lists in the future.

I also assume this was manually tested (ideally, we would have at least a basic unit test for this).

File: components/storage/webstorage/engines/sqlite.rs [hunk 2]
```diff
@@ -33,11 +33,15 @@ impl SqliteEngine {
         Ok(SqliteEngine { connection })
     }
 
-    pub fn init_db(path: &PathBuf) -> rusqlite::Result<Connection> {
-        if let Some(parent) = path.parent() {
-            let _ = std::fs::create_dir_all(parent);
-        }
-        let connection = Connection::open(path)?;
+    pub fn init_db(path_opt: Option<PathBuf>) -> rusqlite::Result<Connection> {
```
Comment (janvarga) [inline components/storage/webstorage/engines/sqlite.rs]: nit: you can still pass `PathBuf` as a ref in `Option`?

nit: not sure if `path_opt` is idiomatic in rust/servo, it can be just `path`?

Comment (leo030303) [reply components/storage/webstorage/engines/sqlite.rs]: Makes sense

File: components/storage/webstorage/engines/sqlite.rs (hunk 1 above)
Comment (leo030303) [reply components/storage/webstorage/engines/sqlite.rs]: This was manually tested originally but I added a simple unit test to check the in memory database works, and from looking into those pragmas I think the only ones relevant to in memory databases are cache_size and encoding, the rest appear to be related to when and how disk writes happen, so I have those split now

**Comment by janvarga** [comment]
Looks good,I especially appreciate the new test.

One thing I noticed while looking at this again is that it’s not entirely clear why we need an in-memory SQLite database at all. `WebStorageEnvironment` already keeps all key value pairs in memory via its `data` field. It seems like a future refactoring could avoid creating a `WebStorageEngine` entirely when `config_dir` is `None`.

It might be worth adding a TODO to capture this potential simplification.

File: components/storage/webstorage/engines/sqlite.rs [hunk 3]
```diff
@@ -22,24 +22,36 @@ impl SqliteEngine {
...
+    pub fn init_db(db_path: Option<&PathBuf>) -> rusqlite::Result<Connection> {
+        let connection = if let Some(path) = db_path {
+            if let Some(parent) = path.parent() {
+                let _ = std::fs::create_dir_all(parent);
+            }
+            Connection::open(path)?
+        } else {
+            Connection::open_in_memory()?
+        };
+        if db_path.is_some() {
```
Comment (janvarga) [inline components/storage/webstorage/engines/sqlite.rs]: nit: we don't have to check if `db_path` is `None` twice?
The pragmas could be executed in the first if/else?

**Review by arihant2math — APPROVED** [review]

File: components/storage/webstorage/engines/sqlite.rs (hunk 3 above)
Comment (leo030303) [reply components/storage/webstorage/engines/sqlite.rs]: Makes sense

**Comment by janvarga** [comment]
Thank you.

**Review by yezhizhen — APPROVED** [review]
Thanks all!
