### PR TITLE
script: Implement `frame-ancestors` CSP check

### LINKED ISSUE #36468: intermittent failure in  /content-security-policy/frame-ancestors/frame-ancestors-path-ignored.window.html
```
OK /content-security-policy/frame-ancestors/frame-ancestors-path-ignored.window.html

    FAIL [expected PASS] subtest: A 'frame-ancestors' CSP directive with a URL that includes a path should be ignored.

    assert_unreached: The IFrame should have been blocked (or cross-origin). It wasn't. Reached unreachable code
```

### PR DESCRIPTION
**Pull request by TimvdLippe**
Requires communication between the script thread and the constellation to be able to retrieve the origin of a cross-origin document. However, in the fast-path where the document resides in the same script-thread, we use the `frame_element` instead.

If no CSP list is active, then we skip all this logic, to have a minimal impact on document navigation.

Part of #4577
Fixes #36468

### CODE REVIEW

File: components/script/dom/security/csp.rs [hunk 1]
```diff
@@ -156,6 +165,66 @@ impl CspReporting for Option<CspList> {
...
+        let mut parent_navigable_origins = vec![];
+        loop {
+            // Same-origin parents can go via their own script-thread (fast-path)
+            if let Some(container_element) = window_proxy.frame_element() {
+                let container_document = container_element.owner_document();
+                let parent_origin = Url::parse(
+                    &container_document
+                        .origin()
+                        .immutable()
+                        .ascii_serialization(),
```
Comment (mrobinson) [inline components/script/dom/security/csp.rs:189]: This is the only thing that stuck out to me. Is this the right thing to do for opaque origins?

**Review by mrobinson — APPROVED** [review]

File: components/script/dom/security/csp.rs (hunk 1 above)
Comment (TimvdLippe) [reply components/script/dom/security/csp.rs:189]: Yeah I was wondering about that as well. Step 6.2. of https://w3c.github.io/webappsec-csp/#frame-ancestors-navigation-response requires this. I think this currently doesn't happen for opaque origins as they then don't have iframes contained that can have a `frame-ancestors` CSP directive applied.
