### PR TITLE
paint: Track whether script is handling touchmove per `TouchId`

### LINKED ISSUE #42921: Only touchmove of one pointer is handled
**Describe the bug:**
We use the test from https://github.com/servo/servo/pull/42289#issuecomment-3838895081 again.

When we have simultaneous move from two pointers, only one touchmove event is handled in script.

### PR DESCRIPTION
**Pull request by yezhizhen**
As titled. The change is prepared a while ago to eliminate dead code, 
but the test case added requires change from `testdriver-actions.js`: 
https://github.com/web-platform-tests/wpt/pull/57607 just landed by latest wpt-sync: https://github.com/servo/servo/pull/42925.

Part of https://github.com/servo/servo/issues/41923

Testing: Added a WPT test.
Fixes: https://github.com/servo/servo/issues/42921

### CODE REVIEW

File: components/paint/touch.rs [hunk 1]
```diff
@@ -229,16 +229,29 @@ impl TouchHandler {
         }
     }
 
-    pub(crate) fn set_handling_touch_move(&mut self, sequence_id: TouchSequenceId, flag: bool) {
+    pub(crate) fn set_handling_touch_move_for_touch_id(
+        &mut self,
+        sequence_id: TouchSequenceId,
+        touch_id: TouchId,
+        flag: bool,
```
Comment (TimvdLippe) [inline components/paint/touch.rs]: The name flag is non-descriptive. Instead, introduce an enum with name `TouchIdTacking::{Track,Remove}`

**Review by TimvdLippe — APPROVED** [review]
1 nit about naming. The rest LGTM
