### PR TITLE
servoshell: Remove redundant `WindowEvent::Resized` handler

### LINKED ISSUE #38255: servoshell: Tab bar dissapears when resizing the window
**Describe the bug:**
The tab bar dissapears when resizing a window on servoshell. You can see the broken behaviour in the video below, which is checked out at the latest commit. The bug doesn't exist when I check out to the commit before this PR https://github.com/servo/servo/pull/38174 which I think is what introduced the bug.

https://github.com/user-attachments/assets/0900e844-7304-4ce0-9fb8-8d649341505a

**To Reproduce:**
Resize the window.

**Platform:**
Fedora 42 on Framework 13

### PR DESCRIPTION
**Pull request by yezhizhen**
They are redundant as marked in #38174 as rendering related rect already updated in `minibrowser::update`. As a result, we are able to remove `window_rendering_context` and `inner_size` fields from `struct Window`.

Testing: No regression/behaviour change in all tests running with headed window.
Fixes: https://github.com/servo/servo/issues/38255#issuecomment-3117642340

### CODE REVIEW

File: ports/servoshell/desktop/headed_window.rs [hunk 1]
```diff
@@ -681,13 +671,6 @@ impl WindowPortsMethods for Window {
             WindowEvent::CloseRequested => {
                 state.servo().start_shutting_down();
             },
-            WindowEvent::Resized(new_inner_size) => {
-                if self.inner_size.get() != new_inner_size {
-                    self.inner_size.set(new_inner_size);
-                    // `WebView::move_resize` was already called in `Minibrowser::update`.
-                    self.window_rendering_context.resize(new_inner_size);
```
Comment (yezhizhen) [inline ports/servoshell/desktop/headed_window.rs:688]: The comment was added in #38174, but back then we didn't remove the handler, which performs redundant platform-dependent update and causes trouble.

It was already updated in following, which is always correct and works for all platforms as it collects available size at real time.
https://github.com/servo/servo/blob/056b1538c0324b4fdabf7d58a62506add9d10ef1/ports/servoshell/desktop/minibrowser.rs#L407-L413

**Comment by yezhizhen** [comment]
I don't know why I ran the label test which is headless anyway.. But all 71 tests in [set.py](https://github.com/servo/servo/blob/main/tests/wpt/tests/webdriver/tests/classic/set_window_rect/set.py) are as good as ever for headed window.

**Review by mrobinson — APPROVED** [review]
