### PR TITLE
layout: Create box slots for anonymous modern layout boxes serially

### LINKED ISSUE #42022: Intermittent CRASH in `/css/css-display/display-contents-dynamic-flex-002-inline.html`
https://github.com/servo/servo/actions/runs/21156356722/job/60842304852
https://github.com/servo/servo/actions/runs/21154072538/job/60835787330

```
Stable unexpected results (1): 
  ▶ CRASH [expected FAIL] /css/css-display/display-contents-dynamic-flex-002-inline.html
  │   → Traceback (most recent call last):
  │   →   File "/a/servo/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 1167, in run_func
  │   →     self.result = True, self.func(self.protocol, self.url, self.timeout)
  │   →                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/a/servo/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 1384, in _screenshot
  │   →     protocol.testdriver.run(url, self.wait_script)
  │   →   File "/a/servo/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 670, in run
  │   →     test_driver_message = self.get_next_message(url, script_resume, test_window)
  │   →                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/a/servo/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 714, in get_next_message
  │   →     return self._get_next_message_classic(url, script_resume)
  │   →            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/a/servo/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 721, in _get_next_message_classic
  │   →     return self.parent.base.execute_script(script_resume, asynchronous=True, args=[strip_server(url)])
  │   →            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/a/servo/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 80, in execute_script
  │   →     return method(script, args=args)
  │   →            ^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/a/servo/servo/tests/wpt/tests/tools/webdriver/webdriver/client.py", line 780, in execute_async_script
  │   →     return self.send_session_command("POST", "execute/async", body)
  │   →            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/a/servo/servo/tests/wpt/tests/tools/webdriver/webdriver/client.py", line 650, in send_session_command
  │   →     return self.send_command(method, url, body, timeout)
  │   →            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/a/servo/servo/tests/wpt/tests/tools/webdriver/webdriver/client.py", line 588, in send_command
  │   →     response = self.transport.send(
  │   →                ^^^^^^^^^^^^^^^^^^^^
  │   →   File "/a/servo/servo/tests/wpt/tests/tools/webdriver/webdriver/transport.py", line 230, in send
  │   →     response = self._request(method, uri, payload, headers, timeout=timeout)
  │   →                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/a/servo/servo/tests/wpt/tests/tools/webdriver/webdriver/transport.py", line 265, in _request
  │   →     response = self.connection.getresponse()
  │   →                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/root/.local/share/uv/python/cpython-3.11.13-linux-x86_64-gnu/lib/python3.11/http/client.py", line 1395, in getresponse
  │   →     response.begin()
  │   →   File "/root/.local/share/uv/python/cpython-3.11.13-linux-x86_64-gnu/lib/python3.11/http/client.py", line 325, in begin
  │   →     version, status, reason = self._read_status()
  │   →                               ^^^^^^^^^^^^^^^^^^^
  │   →   File "/root/.local/share/uv/python/cpython-3.11.13-linux-x86_64-gnu/lib/python3.11/http/client.py", line 294, in _read_status
  │   →     raise RemoteDisconnected("Remote end closed connection without"
  │   → http.client.RemoteDisconnected: Remote end closed connection without response
  │ 
  │ already mutably borrowed (thread StyleThread#1, at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/atomic_refcell-0.1.13/src/lib.rs:155)
  │    0: servoshell::backtrace::print
  │    1: servoshell::panic_hook::panic_hook
  │    2: std::panicking::panic_with_hook
  │    3: std::panicking::panic_handler::{{closure}}
  │    4: std::sys::backtrace::__rust_end_short_backtrace
  │    5: __rustc::rust_begin_unwind
  │    6: core::panicking::panic_fmt
  │    7: <script::layout_dom::node::ServoThreadSafeLayoutNode as layout::dom::NodeExt>::ensure_inner_layout_data
  │    8: <script::layout_dom::node::ServoThreadSafeLayoutNode as layout::dom::NodeExt>::box_slot
  │    9: layout::construct_modern::ModernContainerJob::finish
  │   10: rayon::iter::plumbing::Folder::consume_iter
  │   11: rayon::iter::plumbing::bridge_producer_consumer::helper
  │   12: rayon_core::join::join_context::{{closure}}
  │   13: rayon_core::registry::in_worker
  │   14: rayon::iter::plumbing::bridge_producer_consumer::helper
  │   15: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  │   16: rayon_core::registry::WorkerThread::wait_until_cold
  │   17: rayon_core::join::join_context::{{closure}}
  │   18: rayon_core::registry::in_worker
  │   19: rayon::iter::plumbing::bridge_producer_consumer::helper
  │   20: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
  │   21: rayon::iter::extend::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
  │   22: layout::construct_modern::ModernContainerBuilder::finish
  │   23: layout::flexbox::FlexContainer::construct
  │   24: layout::formatting_contexts::IndependentFormattingContext::construct
  │   25: layout::flow::construct::BlockLevelJob::finish
  │   26: rayon::iter::plumbing::Folder::consume_iter
  │   27: rayon::iter::plumbing::bridge_producer_consumer::helper
  │   28: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
  │   29: rayon::iter::collect::collect_with_consumer
  │   30: rayon::iter::extend::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
  │   31: layout::flow::construct::BlockContainerBuilder::finish
  │   32: layout::flow::construct::<impl layout::flow::BlockContainer>::construct
  │   33: layout::flow::construct::BlockLevelJob::finish
  │   34: rayon::iter::plumbing::Folder::consume_iter
  │   35: rayon::iter::plumbing::bridge_producer_consumer::helper
  │   36: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
  │   37: rayon::iter::collect::collect_with_consumer
  │   38: rayon::iter::extend::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
  │   39: layout::flow::construct::BlockContainerBuilder::finish
  │   40: layout::flow::construct::<impl layout::flow::BlockContainer>::construct
  │   41: layout::formatting_contexts::IndependentFormattingContext::construct
  │   42: layout::flow::root::BoxTree::construct
  │   43: rayon_core::thread_pool::ThreadPool::install::{{closure}}
  │   44: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  │   45: rayon_core::registry::WorkerThread::wait_until_cold
  │   46: rayon_core::registry::ThreadBuilder::run
  │   47: std::sys::backtrace::__rust_begin_short_backtrace
  │   48: core::ops::function::FnOnce::call_once{{vtable.shim}}
  │   49: std::sys::thread::unix::Thread::new::thread_start
  │   50: <unknown>
  └   51: <unknown>
```

### PR DESCRIPTION
**Pull request by mrobinson**
Modern layout (flex / grid) children box trees are constructed in
parallel, so the box slot must be procured serially before this parallel
pass. This change fixes a regression #41951 where this box slot was
created during the parallel part of the layout.

Testing: This fixes a flaky crash in
`css/css-display/display-contents-dynamic-flex-002-inline.html` and probably
other flexbox tests. I verified this locally by running the test with
`--repeat-until-unexpected`.
Fixes: #42022

### CODE REVIEW

File: components/layout/construct_modern.rs [hunk 1]
```diff
@@ -204,43 +203,49 @@ impl<'a, 'dom> ModernContainerBuilder<'a, 'dom> {
...
+            self.info
+                .with_pseudo_element(self.context, PseudoElement::ServoAnonymousBox)
+                .expect("Should always be able to construct info for anonymous boxes.")
+        })
+    }
+
     fn wrap_any_text_in_anonymous_block_container(&mut self) {
         let runs = std::mem::take(&mut self.contiguous_text_runs);
+
+        // There is no text run or they all only contain document white space characters, do nothing.
```
Comment (Loirooriol) [inline components/layout/construct_modern.rs]: If you are moving this outside, i would add "If":

```suggestion
        // If there is no text run or they all only contain document white space characters, do nothing.
```

**Review by Loirooriol — APPROVED** [review]

**Comment by Loirooriol** [comment]
The linked https://github.com/servo/servo/issues/41591 seems unrelated

**Comment by mrobinson** [comment]
> The linked #41591 seems unrelated

I had transposed two numbers. I have fixed the link.

File: components/layout/construct_modern.rs (hunk 1 above)
Comment (mrobinson) [reply components/layout/construct_modern.rs]: Fixed.
