### PR TITLE
xpath: Replace `nom` with hand-written parsing rules

### LINKED ISSUE #38552: XPath does not report failure for expression `...`
**Describe the bug:**
In other browsers, we would get `Uncaught DOMException: Document.evaluate: The expression is not a legal expression`.

**To Reproduce:**
`./mach run -r <following-file> --pref=dom_xpath_enabled`

```html
<button id="check">evaluate invalid xpath</button>
<script>
  document.getElementById('check').addEventListener('click', () => {    
    const result3 = document.evaluate("...", document.getElementById("check"), null, null, null).iterateNext();
    console.log(result3);
    console.log(result3 instanceof Element);
  });
</script>
```

### LINKED ISSUE #38553: XPath evaluates to current node for expression `..`
**Describe the bug:**
We should retrieve the parent node with `..` as xpath. Instead, we still retrieve current node.

**To Reproduce:**
`./mach run -r <following-file> --pref=dom_xpath_enabled`

```html
<button id="check">evaluate xpath for parent </button>
<script>
  document.getElementById('check').addEventListener('click', () => {    
    const result2 = document.evaluate("..", document.getElementById("check"), null, null, null).iterateNext();
    console.log(result2);
  });
</script>
```

### LINKED ISSUE #39596: XPath namespace resolver callbacks are called too often
```html
<!DOCTYPE html>
<body>
    <script>
    let resolverCalls = 0;
    document.evaluate("/foo:bar", document.documentElement, () => {
      resolverCalls++;
      return "http://www.w3.org/1999/xhtml";
    });
    console.log(resolverCalls)
    </script>
</body>
```
Firefox logs `1` (good), servo logs `2` (bad).

### LINKED ISSUE #39602: Consider replacing nom with hand-written parsing rules for XPath
I'm not a big fan of `nom` because it is hard to debug and causes extremely cryptic compiler errors.

But the bigger problem is that `nom`s parsing model relies on repeatedly trying parser functions and seeing if they succeed. That means that input is potentially parsed multiple times before the correct approach is found, and that is fundamentally incompatible with https://github.com/servo/servo/issues/39596. We would have to use something like a seperate pass over the `Expr` AST so prefixes are only resolved once. I'd prefer not to.

The parser in gecko (https://searchfox.org/firefox-main/source/dom/xslt/xpath/txExprLexer.cpp, https://searchfox.org/firefox-main/source/dom/xslt/xpath/txExprParser.cpp) does not look that bad.

 `nom` is only used in two places, `xpath` and `cookie`, so it would be fairly easy to get rid of.

### PR DESCRIPTION
**Pull request by simonwuelker**
The new parser is more verbose, but also more correct and easier to reason about. Apologies for the size of the change, I don't think there's an alternative to swapping out the entire parser at once.

Testing: Covered by existing tests, new tests also start to pass
Fixes https://github.com/servo/servo/issues/38552
Fixes https://github.com/servo/servo/issues/38553
Fixes https://github.com/servo/servo/issues/39596
Closes https://github.com/servo/servo/issues/39602
Part of https://github.com/servo/servo/issues/34527

### CODE REVIEW

File: components/xpath/src/tokenizer.rs [hunk 1]
```diff
@@ -0,0 +1,557 @@
...
+                return Ok(token);
+            } else {
+                return Ok(Token::CName(CNameToken {
+                    prefix: None,
+                    local_name: ncname,
+                }));
+            }
+        }
+
+        match self.remaining.chars().next().unwrap() {
```
Comment (jdm) [inline components/xpath/src/tokenizer.rs]: Is there any chance we panic here?

File: components/xpath/src/tokenizer.rs [hunk 2]
```diff
@@ -0,0 +1,557 @@
...
+            '|' => {
+                self.remaining = &self.remaining[1..];
+                Ok(Token::Union)
+            },
+            '+' => {
+                self.remaining = &self.remaining[1..];
+                Ok(Token::Operator(OperatorToken::Add))
+            },
+            other => {
+                println!("Illegal character: {other:?}");
```
Comment (jdm) [inline components/xpath/src/tokenizer.rs]: Use a log instead?

File: components/xpath/src/parser.rs [hunk 3]
```diff
@@ -2,732 +2,608 @@
...
+            self.advance(1);
+
+            if name_token.local_name == "*" {
+                NodeTest::Wildcard
+            } else {
+                let namespace = name_token
+                    .prefix
+                    .map(|prefix| {
+                        self.resolve_qualified_name(prefix)
+                            .inspect_err(|e| println!("{e:?}"))
```
Comment (jdm) [inline components/xpath/src/parser.rs]: Use a log?

**Review by jdm — APPROVED** [review]
Nice rewrite!

**Comment by simonwuelker** [comment]
Thanks for the review!

File: components/xpath/src/tokenizer.rs (hunk 1 above)
Comment (TimTheBig) [reply components/xpath/src/tokenizer.rs]: an expect would be nice to explain why

Comment (simonwuelker) [reply components/xpath/src/tokenizer.rs]: `consume_single_token` is only called when the input is nonempty. I'll document this behaviour.

**Comment by yezhizhen** [comment]
Thanks for fixing this!
