### PR TITLE
script: Focus on mousedown instead of mouse click according to spec

### LINKED ISSUE #38588: Focusing step should be triggered by mousedown instead of click
According to [spec](https://w3c.github.io/uievents/#handle-native-mouse-down-id) we should follow title.

For following example, focusing is done at mouse down for Firefox/Edge.

**To Reproduce:**
```html
<!DOCTYPE html>
<html lang="en">
<body>
  <h2>Edit Area</h2>
  <textarea placeholder="Start typing here..."></textarea>
</body>
</html>
```

**Platform:**
All.

### PR DESCRIPTION
**Pull request by yezhizhen**
- Focus on mousedown instead of mouse click according to [spec](https://w3c.github.io/uievents/#handle-native-mouse-down)
- Refactor to follow spec closer and make things more clear.
- Add some spec link.
- Remove some dead spec link.

Still some preparation before implementing #38435.
Testing: No regression in WebDriver & WPT. But update some outdated test.
Fixes: #38588

### CODE REVIEW

File: components/script/dom/document.rs [hunk 1]
```diff
@@ -1596,44 +1588,65 @@ impl Document {
...
         ));
 
-        // https://html.spec.whatwg.org/multipage/#run-authentic-click-activation-steps
         let activatable = el.as_maybe_activatable();
         match event.action {
+            // https://w3c.github.io/uievents/#handle-native-mouse-click
             MouseButtonAction::Click => {
                 el.set_click_in_progress(true);
-                dom_event.fire(node.upcast(), can_gc);
+                dom_event.dispatch(node.upcast(), false, can_gc);
```
Comment (yezhizhen) [inline components/script/dom/document.rs:1596]: We already set event's `trusted` to `true` in `for_platform_mouse_event`. And spec wants dispatch. 

Below changes are similar.

**Comment by yezhizhen** [comment]
Emm it seems we cannot run both linux-wpt and webdriver wpt....

[`Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run`](https://github.com/servo/servo/actions/runs/16870926686)

**Comment by yezhizhen** [comment]
Before change:

https://github.com/user-attachments/assets/fdb08f29-3e24-4dd0-a5dc-66b9dcf8d244

After change:

https://github.com/user-attachments/assets/cdfb63e6-bab1-49dd-b586-c66c2d47f9f3

**Review by mrobinson — APPROVED** [review]

**Comment by yezhizhen** [comment]
> Testing: No regression in WebDriver & WPT.

The webdriver run before this PR: https://github.com/yezhizhen/servo/actions/runs/16868337637
Webdriver run after this PR: https://github.com/servo/servo/pull/38589#issuecomment-3173316370

Some unstable expectations are outdated for a while and should probably be updated.
