### PR TITLE
devtools: Fix `worker` targets in debugger tab

### LINKED ISSUE #36727: Devtools: Fix url parsing for worker urls
Currently after https://github.com/servo/servo/pull/36562 We url looking like this in the source panel:

Example 1:

Image

Example 2: 

Image

See the top level url, 
For example 1: `blob:https://charming.daz.cat/f7974aee-8918-443b-9e60-012f2987de6f` 

and  for example 2: 
thread 1: `blob:http://127.0.0.1:3000/a2d509c4-8992-4d48-8233-65b09cfea00c`  
thread 2: `http://localhost:3000/worker.js`

Ideally top level url should be:
For example 1: `f7974aee-8918-443b-9e60-012f2987de6f`  

and for example 2: 
thread 1 top-level url:  `a2d509c4-8992-4d48-8233-65b09cfea00c`
thread 2 top-level url: `worker.js`

Functionality wise, this is not an issue and it works fine, but we need to investigate how url is being parsed.

### PR DESCRIPTION
**Pull request by atbrakhi**
Firefox DevTools client determines target type by checking if the actor contains specific substring. For workers it [requires](https://searchfox.org/firefox-main/source/devtools/client/fronts/watcher.js#65) `/workerTarget` in the actor name to create a `WorkerTargetFront`.

Testing: Manual testing
Fixes: #36727 and #37012

Screenshot 2026-04-06 at 21 47 59

### CODE REVIEW

**Comment by atbrakhi** [comment]
Dear reviewers and readers, let me present the real culprit behind this long-pending issue. The client-side expectations from the worker (and a few other actors) are slightly different.

The Firefox DevTools client expects the exact string `/workerTarget`, while we were sending `worker` all this time.
The biggest mystery was why it seemed to work briefly before, as seen in the screenshot in [this issue](https://github.com/servo/servo/issues/36727) that I reported last year. I was able to reproduce the exact same behavior from last year when sending the actor name `workerTarget`, where the behavior was again flaky, as you can see in the screenshot below (there is no blob URL on the left, but there is one under the main thread on right, which is also not entirely correct).

Screenshot 2026-04-06 at 22 04 45

So we need to make sure we are using `/workerTarget` as worker actor name as that seems to be the real culprit behind the inconsistent worker behavior.

**Review by jdm — APPROVED** [review]
Excellent find!

File: components/devtools/actor.rs [hunk 1]
```diff
@@ -160,7 +160,15 @@ impl ActorRegistry {
     /// create new names without registering an actor.
     pub fn new_name<T: Actor>(&self) -> String {
         let suffix = self.next.fetch_add(1, Ordering::Relaxed);
-        format!("{}{}", Self::base_name::<T>(), suffix)
+        let base = Self::base_name::<T>();
+
+        // Firefox DevTools client requires "/workerTarget" in actor name to recognize workers
+        // <https://searchfox.org/firefox-main/source/devtools/client/fronts/watcher.js#65>
+        if base.contains("WorkerTarget") {
+            format!("/workerTarget{}", suffix)
```
Comment (eerii) [inline components/devtools/actor.rs:168]: Leaving a note here for the future. The `base_name` function would ideally be part of the `Actor` trait, and we could have the default implementation, and one specific one for `WorkerTarget`. However, that would make `Actor` not [dyn compatible](https://doc.rust-lang.org/nightly/reference/items/traits.html#r-items.traits.dyn-compatible). I ran into this before with the `name` refactoring, and there are ways around it, but it would require more restructuring. So it would be nice to clean in the future but definitely not a priority :)
