### PR TITLE
Fix Intermittent CRASH in AudioBuffer

### LINKED ISSUE #31065: /webaudio/the-audio-api/the-audiobuffer-interface/audiobuffer-copy-channel.html
- https://github.com/servo/servo/actions/runs/7485934353/job/20376153919
- https://github.com/servo/servo/actions/runs/7485934353/job/20376153140
- https://github.com/servo/servo/actions/runs/7485772975/job/20376603752
- https://github.com/servo/servo/actions/runs/7485772975/job/20376604801

```
  ▶ CRASH [expected OK] /webaudio/the-audio-api/the-audiobuffer-interface/audiobuffer-copy-channel.html
  │ 
  │ ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
  │ ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
  │ ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
  │ ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
  │ ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
  │ ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
  │ ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
  │ ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
  │ AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
  │ source slice length (8) does not match destination slice length (0) (thread Script(1,1), at components/script/dom/bindings/typedarrays.rs:75)
  │    0: servo::backtrace::print
  │    1: servo::main2::main::{{closure}}
  │    2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
  │              at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2021:9
  │       std::panicking::rust_panic_with_hook
  │              at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:735:13
  │    3: std::panicking::begin_panic_handler::{{closure}}
  │              at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:609:13
  │    4: std::sys_common::backtrace::__rust_end_short_backtrace
  │              at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
  │    5: rust_begin_unwind
  │              at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
  │    6: core::panicking::panic_fmt
  │              at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
  │    7: core::slice::<impl [T]>::copy_from_slice::len_mismatch_fail
  │              at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/slice/mod.rs:3605:13
  │    8: script::dom::bindings::typedarrays::HeapFloat32Array::copy_data_to
  │    9: <script::dom::audiobuffer::AudioBuffer as script::dom::bindings::codegen::Bindings::AudioBufferBinding::AudioBuffer_Binding::AudioBufferMethods>::CopyFromChannel
  │   10: script::dom::bindings::codegen::Bindings::AudioBufferBinding::AudioBuffer_Binding::copyFromChannel::{{closure}}
  │   11: mozjs::panic::wrap_panic
  │   12: script::dom::bindings::codegen::Bindings::AudioBufferBinding::AudioBuffer_Binding::copyFromChannel
  │   13: CallJitMethodOp
  │   14: script::dom::bindings::utils::generic_method
  │   15: _Z12CallJSNativeP9JSContextPFbS0_jPN2JS5ValueEEN2js10CallReasonERKNS1_8CallArgsE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:486:13
  │       _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:580:12
  │   16: _ZL12InternalCallP9JSContextRKN2js13AnyInvokeArgsENS1_10CallReasonE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:647:10
  │       _ZN2js13CallFromStackEP9JSContextRKN2JS8CallArgsENS_10CallReasonE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:652:10
  │       _ZN2js9InterpretEP9JSContextRNS_8RunStateE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:3395:16
  │   17: _ZL31MaybeEnterInterpreterTrampolineP9JSContextRN2js8RunStateE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:400:10
  │       _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:458:13
  │   18: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:612:13
  │   19: _ZL12InternalCallP9JSContextRKN2js13AnyInvokeArgsENS1_10CallReasonE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:647:10
  │       _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:679:8
  │   20: _ZN2js13PromiseObject6createEP9JSContextN2JS6HandleIP8JSObjectEES7_b
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/builtin/Promise.cpp:2872:15
  │   21: _ZL18PromiseConstructorP9JSContextjPN2JS5ValueE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/builtin/Promise.cpp:2783:7
  │   22: _Z12CallJSNativeP9JSContextPFbS0_jPN2JS5ValueEEN2js10CallReasonERKNS1_8CallArgsE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:486:13
  │       _Z23CallJSNativeConstructorP9JSContextPFbS0_jPN2JS5ValueEERKNS1_8CallArgsE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:502:8
  │       _ZL17InternalConstructP9JSContextRKN2js16AnyConstructArgsENS1_10CallReasonE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:708:14
  │   23: _ZN2js18ConstructFromStackEP9JSContextRKN2JS8CallArgsENS_10CallReasonE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:755:10
  │       _ZN2js9InterpretEP9JSContextRNS_8RunStateE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:3380:16
  │   24: _ZL31MaybeEnterInterpreterTrampolineP9JSContextRN2js8RunStateE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:400:10
  │       _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:458:13
  │   25: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:612:13
  │   26: _ZL12InternalCallP9JSContextRKN2js13AnyInvokeArgsENS1_10CallReasonE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:647:10
  │       _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:679:8
  │   27: _ZN2js3jit14InvokeFunctionEP9JSContextN2JS6HandleIP8JSObjectEEbbjPNS3_5ValueENS3_13MutableHandleIS8_EE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/jit/VMFunctions.cpp:526:10
  │   28: _ZN2js3jit25InvokeFromInterpreterStubEP9JSContextPNS0_30InterpreterStubExitFrameLayoutE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/jit/VMFunctions.cpp:550:8
  │   29: <unknown>
  │   30: <unknown>
  │   31: <unknown>
  │   32: <unknown>
  │   33: _ZL8EnterJitP9JSContextRN2js8RunStateEPh
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/jit/Jit.cpp:104:5
  │       _ZN2js3jit13MaybeEnterJitEP9JSContextRNS_8RunStateE
  │              at /home/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7184f65/mozjs-sys/mozjs/js/src/jit/Jit.cpp:213:10
  │   34: <unknown>
  │ mozilla::detail::MutexImpl::~MutexImpl: pthread_mutex_destroy failed: Device or resource busy
  │ Caught signal 11thread panicked while processing panic. aborting.
  │ Redirecting call to abort() to mozalloc_abort
  └ 
```

### PR DESCRIPTION
**Pull request by gterzian**
FIX https://github.com/servo/servo/issues/31065

These changes fix a regression introduced by https://github.com/servo/servo/pull/30990. The previous code was using `extend_from_slice` on the vec, while the new code using the typed array is using `copy_from_slice` on the underlying slice, hence the crash caused by the empty vec.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #31065 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

File: components/script/dom/audiobuffer.rs [hunk 1]
```diff
@@ -262,7 +262,7 @@ impl AudioBufferMethods for AudioBuffer {
         let cx = GlobalScope::get_cx();
         let channel_number = channel_number as usize;
         let offset = start_in_channel as usize;
-        let mut dest = Vec::with_capacity(destination.len());
+        let mut dest = vec![0.0_f32; bytes_to_copy];
```
Comment (gterzian) [inline components/script/dom/audiobuffer.rs:265]: Note: the previous code was using `extend_from_slice` on the vec, while the new code is using `copy_from_slice` on the underlying slice, hence the crash.

**Comment by gterzian** [comment]
`./mach run --pref dom.svg.enabled http://vuejs.github.io/vue-hackernews/`

seems to work pretty well, except it doesn't scroll. No errors.

**Comment by mrobinson** [comment]
Would it be possible to include a summary of what these changes do in the PR message, so that it is easier to read the repository history?

**Review by jdm — APPROVED** [review]
