### PR TITLE
Set navigation start value according to navigation timing spec

### LINKED ISSUE #17651: navigationStart value is incorrect
We currently initialize the value that is returned by PerformanceTiming.navigationStart during ScriptThread::load. This means that it represents the time at which we have already received the initial response from the network. This disagrees with the definition of https://www.w3.org/TR/navigation-timing/#dom-performancetiming-navigationstart.

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #17651

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17735)

### CODE REVIEW

**Comment by jdm** [comment]
This seems more complicated than necessary. The value for navigation start would make more sense as the time at which the fetch was initiated by the thread that communicates with the network thread, rather than the time at which the fetch algorithm starts executing on the network thread.

File: components/script/script_thread.rs [hunk 1]
```diff
@@ -181,6 +185,8 @@ impl InProgressLoad {
             is_visible: true,
             url: url,
             origin: origin,
+            navigation_start: 0,
+            navigation_start_precise: 0.,
```
Comment (jdm) [inline components/script/script_thread.rs]: Why don't we store the values here? No need to for any of the constellation to be aware of the timing code at all.

**Review by jdm — CHANGES_REQUESTED** [review]

File: components/script/script_thread.rs (hunk 1 above)
Comment (ferjm) [inline components/script/script_thread.rs]: I am not sure what you mean with storing the values here, they are already stored in `InProgressLoad` during the handling of the constellation message to script that notifies about the start of the navigation. Anyway, I agree that the constellation does not need to be aware of the timing code, so I am removing that part. Thanks!

Comment (jdm) [inline components/script/script_thread.rs]: To rephrase my question - why don't we get the current time here and store it immediately, instead of waiting for the constellation? This both simplifies the code and gives us a more accurate initial time.

Comment (ferjm) [inline components/script/script_thread.rs]: Ok, thank you for rephrasing the question. I added the constellation code trying to address your suggestion of setting the navigation start time as the time at which the thread that communicates with the network thread initiates the fetch. Setting navigation start during `InProgressLoad` construction does not vary the value significantly, but it indeed simplifies the code, so I'll change it as you suggests. Thanks for the feedback and apologies for the back and forth.

File: components/script/dom/window.rs [hunk 2]
```diff
@@ -184,8 +184,8 @@ pub struct Window {
     history: MutNullableJS<History>,
     custom_element_registry: MutNullableJS<CustomElementRegistry>,
     performance: MutNullableJS<Performance>,
-    navigation_start: u64,
-    navigation_start_precise: f64,
+    navigation_start: DOMRefCell<u64>,
+    navigation_start_precise: DOMRefCell<f64>,
```
Comment (jdm) [inline components/script/dom/window.rs]: These can be `Cell` instead.

**Review by jdm — APPROVED** [review]
This looks fine with a simple change. Sorry my descriptions suggested more complexity than was necessary!
