### PR TITLE
script: Allow any valid CSS color for color input values

### LINKED ISSUE #42117: `<input type=color>` likely accepts `#+1+2+3` as `value`
**Describe the bug:**
- rust-lang/rust-clippy#16213

https://github.com/servo/servo/blob/cdf8dad62c4b74eda2716ecaefa9dface3e8e124/components/script/dom/html/htmlinputelement.rs#L2785-L2790

**To Reproduce:**
I haven't tested (yet), but I'm 90% sure this should repro:

```html
<input type=color value="#+1+2+3">
```
Which is the color `#010203`

**Platform:**
Irrelevant

### PR DESCRIPTION
**Pull request by simonwuelker**
Testing: New tests start to pass
Closes: https://github.com/servo/servo/issues/42117

### CODE REVIEW

File: components/script/dom/html/htmlinputelement.rs [hunk 1]
```diff
@@ -2550,6 +2559,103 @@ impl HTMLInputElement {
...
+    /// <https://html.spec.whatwg.org/multipage/#update-a-color-well-control-color>
+    fn update_a_color_well_control_color(&self, element_value: &mut DOMString) {
+        // Step 1. Assert: element is an input element whose type attribute is in the Color state.
+        debug_assert_eq!(self.input_type(), InputType::Color);
+
+        // Step 2. Let value be the result of running these steps:
+        // Step 2.1 If element's dirty value flag is true, then return the result of getting an attribute
+        // by namespace and local name given null, "value", and element.
+        // FIXME: If we do this then things break
+        // Step 3. Return element's value.
```
Comment (TimvdLippe) [inline components/script/dom/html/htmlinputelement.rs]: Nit:
```suggestion
        // Step 2.2. Return element's value.
```

File: components/script/dom/html/htmlinputelement.rs [hunk 2]
```diff
@@ -2550,6 +2559,103 @@ impl HTMLInputElement {
...
+        color.components.1 = color.components.1.clamp(0.0, 1.0);
+        color.components.2 = color.components.2.clamp(0.0, 1.0);
+
+        // Step 4.3 If element's alpha attribute is not specified, then set htmlCompatible to true.
+        if !has_alpha {
+            html_compatible = true;
+        }
+
+        // Step 5. Otherwise:
+        // NOTE: This is unreachable
```
Comment (TimvdLippe) [inline components/script/dom/html/htmlinputelement.rs]: Is this a spec bug? I do see `display-p3` in the failing WPT tests, so I think we are missing something here?

>   [Testing '#ffffff;' with color space 'display-p3' and with alpha (setAttribute("value"))]

Edit: Okay, I missed your other notes. Instead of these, please mark them as TODO and state that it should be implemented once colorspace is suppored

File: tests/wpt/meta/html/semantics/forms/the-input-element/color.window.js.ini [hunk 3]
```diff
@@ -128,9 +125,6 @@
   [Testing '#0F0F0F' with color space 'display-p3' and with alpha (value)]
     expected: FAIL
 
-  [Testing '#fff' with color space 'limited-srgb' and  without alpha (setAttribute("value"))]
-    expected: FAIL
-
   [Testing '#fff' with color space 'limited-srgb' and  without alpha (value)]
```
Comment (TimvdLippe) [inline tests/wpt/meta/html/semantics/forms/the-input-element/color.window.js.ini:128]: What's the reason that the previous test is now passing, but these ones aren't?

**Review by TimvdLippe — APPROVED** [review]

File: tests/wpt/meta/html/semantics/forms/the-input-element/color.window.js.ini (hunk 3 above)
Comment (simonwuelker) [reply tests/wpt/meta/html/semantics/forms/the-input-element/color.window.js.ini:128]: they use the `limited-srgb` colorspace (or other non-default ones), and we don't support the `colorspace` attribute yet, so these get serialized incorrectly.

Comment (simonwuelker) [reply tests/wpt/meta/html/semantics/forms/the-input-element/color.window.js.ini:128]: What I said is wrong, limited-srgb is the default. But we don't implement other things that this test needs, like the `colorSpace` IDL attribute on HTMLInputElement. I'll fix these in a followup.
