### PR TITLE
fix: bring back connection method to fix WebGL texture error

### LINKED ISSUE #35356: WebGL demo crashes and `libEGL` warnings when running servo
The [TWGL tunner demo](https://demo.servo.org/experiments/twgl-tunnel/) crashes with the below backtrace

```
assertion `left == right` failed
  left: 1281
 right: 0 (thread main, at /home/mukilan/.cargo/git/checkouts/surfman-d15b9f3e86c2e263/a8079ee/src/platform/generic/egl/surface.rs:420)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::assert_failed_inner
   8: core::panicking::assert_failed
   9: surfman::platform::generic::egl::surface::EGLBackedSurface::to_surface_texture
  10: surfman::platform::unix::x11::surface::<impl surfman::platform::unix::x11::device::Device>::create_surface_texture
  11: surfman::platform::generic::multi::surface::<impl surfman::platform::generic::multi::device::Device<Def,Alt>>::create_surface_texture
  12: <webrender_traits::rendering_context::SurfmanRenderingContext as webrender_traits::rendering_context::RenderingContext>::create_texture
  13: <canvas::webgl_mode::inprocess::WebGLExternalImages as webrender_traits::WebrenderExternalImageApi>::lock
  14: <webrender_traits::WebrenderExternalImageHandlers as webrender_api::image::ExternalImageHandler>::lock
  15: webrender::renderer::gpu_cache::<impl webrender::renderer::Renderer>::prepare_gpu_cache
  16: webrender::renderer::Renderer::render_impl
  17: webrender::renderer::Renderer::render
  18: profile_traits::time::profile
  19: compositing::compositor::IOCompositor::composite_specific_target
  20: compositing::compositor::IOCompositor::composite
  21: compositing::compositor::IOCompositor::perform_updates
  22: servo::Servo::handle_events
  23: servoshell::desktop::app::App::handle_events
  24: servoshell::desktop::app::App::handle_events_with_winit
  25: <servoshell::desktop::app::App as winit::application::ApplicationHandler<servoshell::desktop::events_loop::WakerEvent>>::user_event
  26: winit::platform_impl::linux::x11::EventLoop<T>::run_on_demand
  27: servoshell::desktop::events_loop::EventsLoop::run_app
  28: servoshell::desktop::cli::main
  29: std::sys::backtrace::__rust_begin_short_backtrace
  30: std::rt::lang_start::{{closure}}
  31: std::rt::lang_start_internal
  32: main
  33: __libc_start_call_main
  34: __libc_start_main_alias_2
  35: _start
[2025-02-07T05:56:59Z ERROR servoshell::panic_hook] assertion `left == right` failed
      left: 1281
     right: 0
Caught signal 6 in thread "main"
   0: servoshell::backtrace::print
   1: servoshell::crash_handler::install::handler
   2: <unknown>
   3: clock_nanosleep@@GLIBC_2.17
   4: nanosleep
   5: std::thread::sleep
   6: <script::script_runtime::JSEngineSetup as core::ops::drop::Drop>::drop
   7: core::ptr::drop_in_place<core::option::Option<script::script_runtime::JSEngineSetup>>
   8: core::ptr::drop_in_place<servoshell::desktop::app::App>
   9: servoshell::desktop::cli::main
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: std::rt::lang_start::{{closure}}
  12: std::rt::lang_start_internal
  13: main
  14: __libc_start_call_main
  15: __libc_start_main_alias_2
  16: _start
Servo was terminated by signal 6
```

There doesn't seem to be any other issues for normal websites like servo.org. However, these warnings seem to be new and they are printed  *always* when running servo.

```
main on  HEAD (07aa4ce) (BISECTING) [$?] is 📦 v0.0.1 via 🐍 v3.11.11 via 🦀 v1.83.0
❯ ./mach run -r
NOTE: Entering nix-shell ./shell.nix
libEGL warning: egl: failed to create dri2 screen
libEGL warning: failed to get driver name for fd -1

libEGL warning: MESA-LOADER: failed to retrieve device information

libEGL warning: failed to get driver name for fd -1
```

**To Reproduce:**
1. `./mach build -r`
2. `./mach run -r  "https://demo.servo.org/experiments/twgl-tunnel/"`

**Platform:**
I've only tested this on NixOS 24.11 (KDE Plasma 6.2.5, X11) with nixpkgs at 030ba1976b7c0e1a67d9716b17308ccdab5b381e. 
I have both dGPU and integrated GPU (Intel® UHD Graphics). I think my system is using the latter.

**Additional information**

`git bisect` show that this issue was introduced by  07aa4ce093547974800564f8231b3530721b1de9 (#35251). 

cc: @wusyong

### PR DESCRIPTION
**Pull request by wusyong**
Looks like it needs to be the same EGLDisplay on Linux to share the texture.
I brought back `connection` with `Option` as return value. Because the `NativeConnection` also require either x11 or wayland display. I need some time to figure out how to do it in GTK demo.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #35356 (GitHub issue number if applicable)

### CODE REVIEW

File: components/compositing/compositor.rs [hunk 1]
```diff
@@ -408,7 +408,9 @@ impl IOCompositor {
             version_string,
         };
 
-        compositor.assert_gl_framebuffer_complete();
+        let gl = &compositor.webrender_gl;
+        println!("Running on {}", gl.get_string(gleam::gl::RENDERER));
+        println!("OpenGL Version {}", gl.get_string(gleam::gl::VERSION));
```
Comment (wusyong) [inline components/compositing/compositor.rs:413]: I added helper print here when the compositor is initialized.
It should be eaiser to get our GL infor when opening tickets.

Also could we remove the assert here, because platforms like GTK's GLArea won't attach the buffers until rendering. It's tricky to create compositor in this way.

Comment (mukilan) [reply components/compositing/compositor.rs:413]: I suppose these `println` should be `info!` to avoid printing this for all embedders. We can always request the reporter to run with `RUST_LOG=info` if we suspect the issue is with GL.

**Review by mukilan — CHANGES_REQUESTED** [review]
Thank you! This does fix the WebGL crash for me. However, the libEGL warnings are still present. They were not there before the rendering context changes.

```
libEGL warning: egl: failed to create dri2 screen
libEGL warning: failed to get driver name for fd -1

libEGL warning: MESA-LOADER: failed to retrieve device information

libEGL warning: failed to get driver name for fd -1
```

EDIT: the warnings can be investigated and fixed in a different PR though.

File: components/compositing/compositor.rs (hunk 1 above)
Comment (mukilan) [reply components/compositing/compositor.rs:413]: > Also could we remove the assert here, because platforms like GTK's GLArea won't attach the buffers until rendering

I am not sure, but @mrobinson or @jdm might now more about this.

Comment (wusyong) [reply components/compositing/compositor.rs]: I'll remove it and work in other PRs instead. The prints have changed to info logs

**Review by mukilan — APPROVED** [review]
