### PR TITLE
compositor/layout: Rely on layout for fine-grained input event hit testing

### LINKED ISSUE #25282: Hit testing infra scares me
In both 2013 and 2020, we store `OpaqueNode` values in the layout tree, which WR sends us back when a click happens. Unfortunately, on the script side, we just treat those as `UntrustedNodeAddress` to get a `&Node` out of them. AFAIK, there is no guarantee that the nodes corresponding to the `OpaqueNode` tokens from the layout tree are still alive when we pointer cast them.

Cc @jdm @SimonSapin

### LINKED ISSUE #26608: WebRender hit testing return spurious results for 3d transformed cube
Test case:

```html
<style>
  .cube-container {
    width: 300px;
    height: 300px;
  }

  .cube-side {
    position: absolute;
    width: 300px;
    height: 300px;
    transform-origin: 150px 150px -150px;
    transform-style: preserve-3d;
  }
  .cube-side-1 { background-color: firebrick; transform: rotateX(0deg) rotateY(0deg); }
  .cube-side-2 { transform: rotateX(90deg) rotateY(0deg); }
  .cube-side-3 { transform: rotateX(180deg) rotateY(0deg); }
  .cube-side-4 { transform: rotateX(270deg) rotateY(0deg); }
  .cube-side-5 { transform: rotateX(0deg) rotateY(90deg); }
  .cube-side-6 { transform: rotateX(0deg) rotateY(-90deg); }

  .cube-container:hover .cube-side-1 {
    background-color: pink;
  }
</style>

<div class="cube-container">
      <div class="cube-side cube-side-1"></div>
      <div class="cube-side cube-side-2"></div>
      <div class="cube-side cube-side-3"></div>
      <div class="cube-side cube-side-4"></div>
      <div class="cube-side cube-side-5"></div>
      <div class="cube-side cube-side-6"></div>
</div>
```

**Expected behavior:** Hovering on the cube should turn the contents pink.
**Observed behavior:** Hovering on the cube turns the contents pink, but so does hovering on other random parts of the page.

### LINKED ISSUE #38090: --device-pixel-ratio breaks hit testing
Setting --device-pixel-ratio to a value that deviates from the system hidpi factor breaks hit testing. I wonder if this is related to the fact that --device-pixel-ratio no longer affects the servoshell UI scale?

Minimal repro as of Servo fcb2a4cd95a19c8ef43f73c1c116117785a61cc4:

1. Set your system hidpi factor to 1.5 (`Xft.dpi: 144`)
2. `servo --device-pixel-ratio=4 https://servo.org`
3. Scroll down to the Donate button
4. Try to click the middle of the button

Image

### PR DESCRIPTION
**Pull request by mrobinson**
Before, the compositor was responsible for doing the hit testing during
input events within a page. This change moves that hit testing to
layout.  With this change, epoch mismatches are no longer a bit deal and
we can simply ignore them, as the Constellation and Script will take
care of ignoring hit tests against scroll nodes and browsing contexts
that no longer exist. This means that hit testing retry support can be
removed.

Add the concept of a Script `HitTest` that transforms the coarse-grained
renderer hit test into one that hit tests against the actual layout
items.

Testing: Currently we do not have good tests for verifying the behavior of
input events, but WebDriver tests should cover this.
Fixes: This is part of #37932.
Fixes: #26608.
Fixes: #25282.
Fixes: #38090.

### CODE REVIEW

File: components/compositing/compositor.rs [hunk 1]
```diff
@@ -286,57 +274,33 @@ impl ServoRenderer {
...
-        pipeline_id: Option<WebRenderPipelineId>,
         details_for_pipeline: impl Fn(PipelineId) -> Option<&'a PipelineDetails>,
-    ) -> Result<Vec<CompositorHitTestResult>, HitTestError> {
+    ) -> Vec<CompositorHitTestResult> {
         // DevicePoint and WorldPoint are the same for us.
         let world_point = WorldPoint::from_untyped(point.to_untyped());
-        let results =
-            self.webrender_api
-                .hit_test(self.webrender_document, pipeline_id, world_point, flags);
+        let results = self.webrender_api.hit_test(
```
Comment (kongbai1996) [inline components/compositing/compositor.rs:284]: What is the reason we cannot completely remove the hit test from the compositor?

Comment (mrobinson) [reply components/compositing/compositor.rs:284]: The renderer will need to do hit testing to:
 - Do renderer-side scrolling ie be able to scroll without direct input from layout. This is important for scroll latency.
 - Map WebView viewport coordinate points into the coordinate space of the iframe that does the actual hit test while handling input events. In addition, it's important that input events are directed toward the frame / browsing context that they are over and not just currently focused browsing context.

Comment (kongbai1996) [reply components/compositing/compositor.rs:284]: > In addition, it's important that input events are directed toward the frame / browsing context that they are over and not just currently focused browsing context.

I believe that input events will only occur in the currently focused browsing context.

Comment (kongbai1996) [reply components/compositing/compositor.rs:284]: > * Do renderer-side scrolling ie be able to scroll without direct input from layout. This is important for scroll latency.

It is beneficial for the renderer's scrolling to be handled in a separate webRender backend thread because the tasks of the script thread are indeed quite heavy.

File: components/compositing/compositor.rs [hunk 2]
```diff
@@ -286,57 +274,33 @@ impl ServoRenderer {
...
             .iter()
             .filter_map(|item| {
                 let pipeline_id = item.pipeline.into();
                 let details = details_for_pipeline(pipeline_id)?;
 
-                // If the epoch in the tag does not match the current epoch of the pipeline,
-                // then the hit test is against an old version of the display list.
-                match details.most_recent_display_list_epoch {
-                    Some(epoch) => {
-                        if epoch.as_u16() != item.tag.1 {
```
Comment (kongbai1996) [inline components/compositing/compositor.rs:330]: If we remove this validation, we will need to perform an out-of-bounds check when subsequently retrieving the `hit_test_item`. 
[```let info = &details.hit_test_items[item.tag.0 as usize];```](https://github.com/servo/servo/pull/38480/files#diff-298fb10624a335ffd15f99b3752e7af7ad4604c8ce3f7b00387207815ac7c296L347)

Comment (kongbai1996) [reply components/compositing/compositor.rs:330]: We previously removed this validation internally, and there was a probability of encountering an out-of-bounds exception when hit_test_items did not match.

File: components/compositing/compositor.rs (hunk 1 above)
Comment (mrobinson) [reply components/compositing/compositor.rs:284]: > > In addition, it's important that input events are directed toward the frame / browsing context that they are over and not just currently focused browsing context.
> 
> I believe that input events will only occur in the currently focused browsing context.

Each `<iframe>` is a browsing context. If an `<iframe>` is focused and you click a mouse button with the cursor outside the `<iframe>` the event should go to the parent frame.

Comment (kongbai1996) [reply components/compositing/compositor.rs:284]: > Each `<iframe>` is a browsing context. If an `<iframe>` is focused and you click a mouse button with the cursor outside the `<iframe>` the event should go to the parent frame.

Alright, I understand.

**Comment by kongbai1996** [comment]
This seems to incur additional performance overhead. Can we perform a secondary hit test in the layout only when there is an epoch mismatch?

File: components/compositing/compositor.rs (hunk 1 above)
Comment (kongbai1996) [reply components/compositing/compositor.rs:284]: This seems to incur additional performance overhead. Can we perform a secondary hit test in the layout only when there is an epoch mismatch?

File: components/compositing/compositor.rs (hunk 2 above)
Comment (mrobinson) [reply components/compositing/compositor.rs:330]: Great point. Now that we are not using the `HitTestInfo` items for storing the node we can fit the `Cursor` and the `ExternalScrollId` into the hit test tag itself. This allows us to remove the `HitTestInfo` data structure entirely and removes the possibility of epoch mismatch completely. A followup change will move `Cursor` handling to script so that the tag will only be used to store the `ExternalScrollId`. I think this addresses your concerns.

File: components/compositing/compositor.rs (hunk 1 above)
Comment (mrobinson) [reply components/compositing/compositor.rs:284]: For the moment this is the case, but once `Cursor` handling moves to layout, we will only need to make `WebRender` hit test items for scrollable nodes. This will greatly reduce the amount of hit testing done in WebRender and restore performance.

File: components/shared/compositing/tests/compositor.rs [hunk 3]
```diff
@@ -24,55 +23,58 @@ fn add_mock_scroll_node(tree: &mut ScrollTree) -> ScrollTreeNodeId {
...
+                scroll_sensitivity: AxesScrollSensitivity {
+                    x: ScrollType::Script | ScrollType::InputEvents,
+                    y: ScrollType::Script | ScrollType::InputEvents,
+                },
+                offset: LayoutVector2D::zero(),
+                offset_changed: Cell::new(false),
+            }),
+        ),
+        external_id,
     )
```
Comment (Loirooriol) [inline components/shared/compositing/tests/compositor.rs]: Nit: can avoid the extra indentation:

```suggestion
    let id = tree.add_scroll_tree_node(
        parent.as_ref(),
        SpatialTreeNodeInfo::Scroll(ScrollableNodeInfo {
            external_id,
            content_rect: Size2D::new(200.0, 200.0).into(),
            clip_rect: Size2D::new(100.0, 100.0).into(),
            scroll_sensitivity: AxesScrollSensitivity {
                x: ScrollType::Script | ScrollType::InputEvents,
                y: ScrollType::Script | ScrollType::InputEvents,
            },
            offset: LayoutVector2D::zero(),
            offset_changed: Cell::new(false),
        }),
    );
    let external_id = ExternalScrollId(num_nodes as u64, pipeline_id);
    (id, external_id)
```

**Review by Loirooriol — APPROVED** [review]

**Comment by jdm** [comment]
I'm really excited about removing this footgun from Servo. Great work @kongbai1996 @mrobinson and @Loirooriol !

**Comment by kongbai1996** [comment]
A page swipe issue was discovered on the openharmony device. The issue was not present before this commit, but it was reproduced after the commit. I am currently trying to identify which part of the logic is causing this, but I have not found it yet. The test page is attached.
[Todo.zip](https://github.com/user-attachments/files/21935026/Todo.zip)

**Comment by mrobinson** [comment]
@kongbai1996 Can you confirm whether or not the issue is with hit testing happening during pipeline transitions leading to event dispatch failing: https://github.com/servo/servo/pull/38590/files#diff-95aa2eb890fe794918afdadfb6a89e026ec80222ceb8e5a21768d528e9ce036c ?

**Comment by kongbai1996** [comment]
> Can you confirm whether or not the issue is with hit testing happening during pipeline transitions leading to event dispatch failing:

No, there are still issues in this PR.

File: components/layout/display_list/mod.rs [hunk 4]
```diff
@@ -396,27 +390,6 @@ impl DisplayListBuilder<'_> {
...
-        &mut self,
-        style: &ComputedValues,
-        tag: Option<Tag>,
-        auto_cursor: Cursor,
-    ) -> HitInfo {
-        use style::computed_values::pointer_events::T as PointerEvents;
-
-        let inherited_ui = style.get_inherited_ui();
-        if inherited_ui.pointer_events == PointerEvents::None {
-            return None;
```
Comment (kongbai1996) [inline components/layout/display_list/mod.rs:409]: This logic is missing.

Comment (mrobinson) [reply components/layout/display_list/mod.rs:409]: It's here: https://github.com/servo/servo/blob/main/components/layout/display_list/hit_test.rs#L247

Comment (kongbai1996) [reply components/layout/display_list/mod.rs:409]: It's too late; the hit test information sent to webrender did not include this logic.
