### PR TITLE
script_bindings/libservo: Fix build script to use `uv` to build instead of `python3`

### LINKED ISSUE #42527: Build warnings from uv/python
**Describe the bug:**

Likely aftermath from #42340

```
PS D:\servo> ./mach build -r
Building `release` build with crown disabled (no JS garbage collection linting).
warning: script_bindings@0.0.1: `uv ["run", "python"]` failed with error: Failed to generate package metadata for `servo==0.0.1 @ virtual+.`
warning: script_bindings@0.0.1: `uv` not found - Falling back to the default python! If the build fails, please install uv and make sure it is in your PATH or make sure to provision a python environment >= python 3.11.
warning: libservo@0.0.1: `uv ["run", "python"]` failed with error: Failed to generate package metadata for `servo==0.0.1 @ virtual+.`
warning: libservo@0.0.1: `uv` not found - Falling back to the default python! If the build fails, please install uv and make sure it is in your PATH or make sure to provision a python environment >= python 3.11.
```

### PR DESCRIPTION
**Pull request by yezhizhen**
- Redirect stdin to null device when testing Python command. This fixes the issue with Windows.
- Use `--frozen` for both test command and actual command used in build. This is what we've been doing for `mach`.

Before this PR, uv fails due to the missing `--frozen` and we fall back to python3 in CI for various platforms.

Fixes: #42527

### CODE REVIEW

**Comment by jschwe** [comment]
Also remember to apply the same change in the other build script (libservo)

**Comment by yezhizhen** [comment]
> Also remember to apply the same change in the other build script (libservo)

We already have it for libservo. It shows in #42527 probably because the error from script_bindings bubbles to libservo.

I don't know why try-label & try for Windows still both have warnings. But it is gone for me locally. Probably security rule only uses local build script in CI?

**Comment by yezhizhen** [comment]
> Probably security rule only uses local build script in CI

Yeah it seems CI checkout at #42306. I don't know how that is determined tho.

**Comment by jschwe** [comment]
No, build.rs will be checked out correctly. Only CI files will be from main. The log output might be a bit confusing, though since there are two commits mentioned.

**Comment by yezhizhen** [comment]
> No, build.rs will be checked out correctly. Only CI files will be from main. The log output might be a bit confusing, though since there are two commits mentioned.

True. I don't know why CI is like that. But the order of warning in CI is different from #42527 too.

The problem is fixed in my local build tho.

**Comment by sagudev** [comment]
> > Also remember to apply the same change in the other build script (libservo)
> 
> We already have it for libservo. It shows in #42527 probably because the error from script_bindings bubbles to libservo.
> 
> I don't know why try-label & try for Windows still both have warnings. But it is gone for me locally. Probably security rule only uses local build script in CI?

Errors should not be able to bubble down into libservo. So I suspect this will not really fix it.

What I am really interested in is what causes `Failed to generate package metadata for `servo==0.0.1 @ virtual+`. Bad/old uv.lock?

File: components/script_bindings/build.rs
Comment (jschwe) [inline components/script_bindings/build.rs]: Can you try what happens if we add `--frozen` after `run`?

File: components/servo/build.rs [hunk 1]
```diff
@@ -59,8 +59,8 @@ fn try_python_command(program: &str, args: &[&str]) -> Result<(), String> {
 /// Note: This function should be kept in sync with the version in `components/script_bindings/build.rs`
 fn find_python() -> Command {
     // Test uv first - if it works, create a FRESH command to return
-    let uv_result =
-        try_python_command("uv", &["run", "python"]).inspect_err(|e| println!("cargo:warning={e}"));
+    let uv_result = try_python_command("uv", &["run", "--frozen", "python"])
+        .inspect_err(|e| println!("cargo:warning={e}"));
     if uv_result.is_ok() {
         let mut cmd = Command::new("uv");
         cmd.args(["run", "python"]);
```
Comment (yezhizhen) [inline components/servo/build.rs]: https://github.com/servo/servo/actions/runs/21902078794/job/63232762891?pr=42532#step:10:52

Added `--frozen` to Python testing command, which fixed the early return. But I think we need it for real command too? Right now the real command has problem.
```suggestion
        cmd.args(["run", "--frozen", "python"]);
```

Comment (yezhizhen) [reply components/servo/build.rs]: Yeah seems so. We use it for mach.

**Comment by yezhizhen** [comment]
https://github.com/servo/servo/actions/runs/21902729761/job/63234962121#step:11:426

Problem fixed for both Linux and Windows.

**Review by jschwe — APPROVED** [review]
