### PR TITLE
Make layout build a display list when the highlighted DOM node changed

### LINKED ISSUE #37500: Devtools highlighting is broken
Highlighting elements from the devtools does not work anymore (as of ef5e9b5f4dfcf9face95ba01b648f194084a4262).

The script side of things seems to work fine. I've bisected this to 23acb623c887a095e8c6b1e2db10ca1398614945, cc @mrobinson .

### PR DESCRIPTION
**Pull request by simonwuelker**
Highlights from the devtools trigger reflows. Previously, incremental layout would notice that nothing about the box tree changed and skip generating a new display list. This caused the highlights to never be painted.

Forcing a new DL in this case makes reflows that happen *while* there is a highlighted DOM node (which did not change since the last reflow) slightly less efficient. We could check if the highlighted node changed and only force a new display list if it did, but I'm not sure if `OpaqueNode`s can be compared like that. It also seems like a very niche issue.

Testing: This is hard to test for, so there are no tests.
Fixes https://github.com/servo/servo/issues/37500.

### CODE REVIEW

**Comment by delan** [comment]
> We could check if the highlighted node changed and only force a new display list if it did, but I'm not sure if OpaqueNodes can be compared like that. It also seems like a very niche issue.

This seems like a good idea. I think that’s the exact use case for OpaqueNode no? In fact, the only operation valid on an OpaqueNode is checking its identity.

File: components/layout/layout_impl.rs [hunk 1]
```diff
@@ -648,6 +648,12 @@ impl LayoutThread {
             &snapshot_map,
         );
 
+        if reflow_request.highlighted_dom_node.is_some() {
+            // Need to manually force layout to build a new display list regardless of whether the box tree
+            // changed or not.
+            self.need_new_display_list.set(true);
+        }
+
```
Comment (mrobinson) [inline components/layout/layout_impl.rs]: We shouldn't always build a display list if there is a highlighted DOM node. Instead, we should detect when the highlight has changed and only in that case force the creation of a new display list. This will prevent the creation of unnecessary display lists when the highlight isn't changing.

You may need to cache the previously-highlighted DOM node in layout to make this work.

**Review by mrobinson — CHANGES_REQUESTED** [review]
Thanks for the fix. I think this should be a bit more involved in order to prevent the creation of unnecessary display lists.

**Comment by simonwuelker** [comment]
> This seems like a good idea. I think that’s the exact use case for OpaqueNode no? In fact, the only operation valid on an OpaqueNode is checking its identity.

I wasn't sure if `OpaqueNode`s can be compared across reflows. Looks like they can, so I implemented the smarter approach now.

File: components/layout/layout_impl.rs [hunk 2]
```diff
@@ -698,6 +710,7 @@ impl LayoutThread {
         let node_to_image_animation_map =
             std::mem::take(&mut *layout_context.node_image_animation_map.write());
 
+        self.previous_highlighted_dom_node.set(reflow_request.highlighted_dom_node);
```
Comment (mrobinson) [inline components/layout/layout_impl.rs]: I think you should probably move this to `build_display_list()` as it's theoretically possible for a non-display-list-building reflow (for instance, for a script query) to happen which means that no display list is sent when `previous_highlighted_dom_node` and then none is sent later when a display list is actually requested.

File: components/layout/layout_impl.rs [hunk 3]
```diff
@@ -181,6 +181,11 @@ pub struct LayoutThread {
     /// Debug options, copied from configuration to this `LayoutThread` in order
     /// to avoid having to constantly access the thread-safe global options.
     debug: DebugOptions,
+
+    /// Tracks the node that was highlighted by the devtools during the last reflow.
+    ///
+    /// If this changed, then we need to create a new display list.
+    previous_highlighted_dom_node: Cell<Option<OpaqueNode>>,
```
Comment (mrobinson) [inline components/layout/layout_impl.rs]: Very tiny English nit:

```suggestion
    previously_highlighted_dom_node: Cell<Option<OpaqueNode>>,
```

**Review by mrobinson — CHANGES_REQUESTED** [review]
Thanks! Just a couple quick suggestions here.

File: components/layout/layout_impl.rs (hunk 2 above)
Comment (simonwuelker) [reply components/layout/layout_impl.rs]: Oh I see. I suppose it makes sense that a layout query would ignore `LayoutThread::need_new_display_list`.

**Review by Loirooriol — COMMENTED** [review]
You need `./mach fmt`

**Review by mrobinson — APPROVED** [review]
Looks great. Thanks!
