### PR TITLE
Fix: Add support for stylesheet MIME type quirk in quirks mode

### LINKED ISSUE #36324: Stylesheet loading quirk is missing
From https://html.spec.whatwg.org/multipage/#link-type-stylesheet:

```
Quirk: If the document has been set to [quirks mode](https://dom.spec.whatwg.org/#concept-document-quirks), has the [same origin](https://html.spec.whatwg.org/#same-origin) as the [URL](https://url.spec.whatwg.org/#concept-url) of the external resource, and the [Content-Type metadata](https://html.spec.whatwg.org/#content-type) of the external resource is not a supported style sheet type, the user agent must instead assume it to be [text/css](https://html.spec.whatwg.org/#text/css).
```

We are missing support for this quirk in https://github.com/servo/servo/blob/cf3ad2de774c8f8022135b0a9d466c197d961aa2/components/script/stylesheet_loader.rs#L164-L167 . There does not appear to be a test verifying that this feature works (ie. a same-origin stylesheet loaded with a non-text/css mime type), only one verifying that the feature fails correctly (https://github.com/servo/servo/blob/main/tests/wpt/tests/html/links/stylesheet/quirk-origin-check.html). We should [add a new test](https://book.servo.org/hacking/testing.html#add-a-new-test) based on that one that verifies the positive condition.

### PR DESCRIPTION
**Pull request by sakupi01**
This PR implements the HTML spec quirk for stylesheets: https://html.spec.whatwg.org/multipage/#link-type-stylesheet

The implementation adds a check in `stylesheet_loader.rs` to handle this quirk condition correctly, and adds a new WPT test to verify that same-origin non-CSS MIME type resources are properly treated as CSS in quirks mode.

Testing: Added a new WPT test (`quirk-origin-check-positive.html`) that verifies the positive case for this quirk. 
Fixes: https://github.com/servo/servo/issues/36324

### CODE REVIEW

File: components/script/stylesheet_loader.rs [hunk 1]
```diff
@@ -164,7 +165,8 @@ impl FetchResponseListener for StylesheetContext {
             let is_css = metadata.content_type.is_some_and(|ct| {
                 let mime: Mime = ct.into_inner().into();
                 mime.type_() == mime::TEXT && mime.subtype() == mime::CSS
-            });
+            }) || (document.quirks_mode() == QuirksMode::Quirks &&
+                document.url().origin() == metadata.final_url.origin());
```
Comment (mrobinson) [inline components/script/stylesheet_loader.rs:169]: Do you mind linking to the specification and quoting the specification text here?

**Review by mrobinson — DISMISSED** [review]
Nice!

File: components/script/stylesheet_loader.rs (hunk 1 above)
Comment (sakupi01) [reply components/script/stylesheet_loader.rs]: No, I don't! 
Added them here: [Add: spec link](https://github.com/servo/servo/pull/36338/commits/30ec85d2ba5aad233d588ce80f0dcf6d0196b6a2)

File: components/script/stylesheet_loader.rs [hunk 2]
```diff
@@ -164,7 +165,12 @@ impl FetchResponseListener for StylesheetContext {
             let is_css = metadata.content_type.is_some_and(|ct| {
                 let mime: Mime = ct.into_inner().into();
                 mime.type_() == mime::TEXT && mime.subtype() == mime::CSS
-            });
+            }) || (
+                // Quirk: If the document has been set to quirks mode, has the same origin as the URL of the external resource, and the Content-Type metadata of the external resource is not a supported style sheet type, the user agent must instead assume it to be text/css.
+                // <https://html.spec.whatwg.org/multipage/#link-type-stylesheet>
+                document.quirks_mode() == QuirksMode::Quirks &&
+                    document.url().origin() == metadata.final_url.origin()
```
Comment (jdm) [inline components/script/stylesheet_loader.rs:172]: Please use https://doc.servo.org/script/dom/document/struct.Document.html#method.origin instead!

**Comment by jdm** [comment]
One formatting error that you can resolve with `./mach fmt` but otherwise this is good to merge!

**Comment by sakupi01** [comment]
@jdm 

Thanks for checking & reporting! 
Fixed in: [Fix: wpt test-tidy error](https://github.com/servo/servo/pull/36338/commits/a1362ef41ebef66c8a0f4fb4258f82482ab62031)

**Review by jdm — APPROVED** [review]

**Comment by sakupi01** [comment]
@jdm Sorry, the review request was my mistake!
