### PR TITLE
indexeddb: make put() overwrite existing SQLite records

### LINKED ISSUE #43707: put() on IDBObjectStore throws when it should update existing record
as of 84eff13a2577083f0a308d063ad70100beee34da, the repro below throws InvalidStateError if served via http:// or https:// and loaded twice:

```html
<!doctype html><meta charset="utf-8"><script>
const db = indexedDB.open("db");
db.onupgradeneeded = event => {
    db.result.createObjectStore("store", {keyPath: "key"});
};
db.onsuccess = event => {
    const tx = db.result.transaction("store", "readwrite");
    tx.objectStore("store").put({key: "value"});
};
</script>
```

`[2026-03-27T06:55:12Z ERROR script::dom::bindings::error] Error at :0:1 InvalidStateError: The object is in an invalid state.`

as of 2ee93de65d13a1c00f158d3b1c48280c398c0047 (2026-03-26), it throws another kind of error:

`[2026-03-27T06:59:15Z ERROR script::dom::indexeddb::idbrequest] Error in IndexedDB operation: SqliteFailure(Error { code: ConstraintViolation, extended_code: 1555 }, Some("UNIQUE constraint failed: object_data.object_store_id, object_data.key"))`

### PR DESCRIPTION
**Pull request by Taym95**
indexeddb: make put() overwrite existing SQLite records

Testing: more indexeddb test should pass.
Fixes: #43707

Fixes: part of #40983

### CODE REVIEW

**Review by arihant2math — APPROVED** [review]
LGTM

**Review by TimvdLippe — APPROVED** [review]
Approving on their behalf

File: components/script/dom/indexeddb/idbobjectstore.rs [hunk 1]
```diff
@@ -267,157 +267,145 @@ impl IDBObjectStore {
...
         }
-        // For paths that did not need key-path extraction/injection above, clone `value` here.
-        let cloned_value = match maybe_modified_cloned_value {
-            Some(cloned_value) => cloned_value,
-            None => structuredclone::write(cx.into(), value, None)?,
+
+        // Step 9. Let targetRealm be a user-agent defined Realm.
+        // Step 10. Let clone be a clone of value in targetRealm during transaction.
+        // Rethrow any exceptions.
+        let cloned_value = structuredclone::write(cx.into(), value, None)?;
```
Comment (gterzian) [inline components/script/dom/indexeddb/idbobjectstore.rs:318]: Here you might want to implement https://www.w3.org/TR/IndexedDB-3/#clone, or note an explicit todo otherwise. (setting transaction activity can be local only in clone)

**Review by gterzian — COMMENTED** [review]
LGTM
