### PR TITLE
Fix scroll root of absolutely positioned elements

### LINKED ISSUE #13530: Scroll frames should not be containing blocks for position:absolute descendants
In this testcase, the cyan circle should not scroll with the scroll frame contents: https://jsfiddle.net/mstange/r96r1pqh/1/

Additionally, it should not be clipped by the scroll frame. And it should be composited in the same opacity group as the scrolled contents.

``` html
<!DOCTYPE html>
<html lang="en">
<meta charset="utf-8">
<title>Opacity does not create a containing block for position:absolute descendants, the clip on the opacity should only apply to the descendants that have opacity as their containing block, and all elements in the opacity should share the same opacity group.</title>

<style>

.scrollbox {
  margin-left: 100px;
  width: 300px;
  height: 400px;
  overflow: auto;
  border: 1px solid black;
}

.scrolledContent {
  padding: 200px 0;
  height: 1000px;
}

.opacity {
  opacity: 0.8;
}

.layer {
  height: 40px;
  margin: 10px;
  border: 1px solid rgba(0, 0, 0, 0.3);
}

.bottom {
  background-color: blue;
}

.middle {
  background-color: cyan;
  position: absolute;
  top: 50px;
  left: 30px;
  width: 150px;
  height: 150px;
  border-radius: 100%;
}

.top {
  background-color: magenta;
  position: relative;
  z-index: 1;
  margin-left: -50px;
}

</style>

<div class="scrollbox">
  <div class="scrolledContent opacity">
    <div class="layer bottom"></div>
    <div class="layer middle"></div>
    <div class="layer top"></div>
  </div>
</div>
```

### PR DESCRIPTION
**Pull request by mrobinson**
Absolutely positioned elements should be given the scroll root of their
containing block and not necessarily the scroll root of their parent.
This fixes several CSS tests, though others are still failing pending a
similar fix for inherited clipping rectangles.

Fixes #13530.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16146)

### CODE REVIEW

**Comment by mrobinson** [comment]
@pcwalton or @glennw r?

**Comment by glennw** [comment]
Nice one!

@bors-servo r+

**Comment by jdm** [comment]
@bors-servo: retry
* #13480

File: components/layout/display_list_builder.rs [hunk 1]
```diff
@@ -1931,12 +1938,19 @@ impl BlockFlowDisplayListBuilding for BlockFlow {
...
+        state.containing_block_scroll_root_id = original_containing_block_scroll_root;
         state.current_stacking_context_id = parent_stacking_context_id;
     }
 
     fn setup_scroll_root_for_block(&mut self, state: &mut DisplayListBuildState) -> ScrollRootId {
-        let containing_scroll_root_id = state.current_scroll_root_id;
+        // If this block is absolutely positioned, we should be clipped and positioned by
+        // the scroll root of our nearest ancestor that establishes a containing block.
+        let containing_scroll_root_id = match self.positioning() {
+            position::T::absolute => state.containing_block_scroll_root_id,
```
Comment (emilio) [inline components/layout/display_list_builder.rs]: @mrobinson do we need something similar for `position: fixed`? (keeping track of the root containing block?) Or is that handled somewhere else?

> If the element has 'position: fixed', the containing block is established by the viewport in the case of continuous media or the page area in the case of paged media.

Comment (mrobinson) [inline components/layout/display_list_builder.rs]: @emilio Oh wow! I didn't realize that. Right now position:fixed is handled by WebRender. It works for transformations which establish a containing block, but not other cases. It sounds like we need to add some pieces in Servo.

Comment (emilio) [inline components/layout/display_list_builder.rs]: Ok, that's about what I expected, I would have been very confused otherwise :). Thanks for the answer! :)
