### PR TITLE
canvas: fix unrecognized offscreen webgl context

### LINKED ISSUE #43540: OffscreenCanvas: `getContext('webgl')` doesn't work
**Describe the bug:**
Servo throws an `Unrecognized OffscreenCanvas context type` error when running `getContext('webgl')`, but not when running `getContext('2d')`.

**To Reproduce:**
```html
<!doctype html>
<script>
let d = (new OffscreenCanvas(1,1)).getContext('2d') // Works
let gl = (new OffscreenCanvas(1,1)).getContext('webgl') // Throws
</script>
```
The above does not throw in Firefox or Chrome

**Platform:**
Servo latest, Windows 10

### PR DESCRIPTION
**Pull request by niyabits**
fix unrecognized type error on `OffscreenCanvas`

Testing: existing WPT:
- `tests/wpt/webgl/tests/conformance/offscreencanvas`
- `tests/wpt/webgl/tests/conformance2/offscreencanvas`

Fixes: #43540

### CODE REVIEW

**Comment by niyabits** [comment]
Creating a draft PR with compiler errors because I need some help.

@jdm I looked at the `get_or_init_webgl_context` implementation in [`htmlcanvaselement.rs`](https://github.com/servo/servo/blob/main/components/script/dom/html/htmlcanvaselement.rs#L257-L257).

As part of [getting the context](https://html.spec.whatwg.org/multipage/canvas.html#offscreen-context-type-webgl) step, I need to pass a `&Window` type.

It does not exist for the offscreen canvas.

```rust
        let window = self.global();
        let canvas =
            RootedHTMLCanvasElementOrOffscreenCanvas::OffscreenCanvas(DomRoot::from_ref(self));
        let size = self.get_size();
        let attrs = Self::get_gl_attributes(cx, options, can_gc)?;
        let context = WebGLRenderingContext::new(
            &window,
            &canvas,
            WebGLVersion::WebGL1,
            size,
            attrs,
            can_gc,
        )?;
```

Do we need to create a `OffscreenCanvasRenderingContextWebGL` like we have for 2D?
https://github.com/servo/servo/blob/b5d454eca0e82f4bad8dfaa15c4fcedfc1df6f02/components/script/dom/canvas/2d/offscreencanvasrenderingcontext2d.rs#L39

And use that as a context instead?

**Comment by jdm** [comment]
Actually the code at https://github.com/servo/servo/blob/38f77f4bfb124b925b79812843e711989e6e743b/components/script/dom/webgl/webglrenderingcontext.rs#L308 and https://github.com/servo/servo/blob/38f77f4bfb124b925b79812843e711989e6e743b/components/script/dom/webgl/webglrenderingcontext.rs#L234 needs to be changed to accept a `&GlobalScope`, then https://github.com/servo/servo/blob/38f77f4bfb124b925b79812843e711989e6e743b/components/script/dom/webgl/webglrenderingcontext.rs#L244 needs to be rewritten to downcast the global to a Window or WorkerGlobalScope. Then we'll need to add https://github.com/servo/servo/blob/38f77f4bfb124b925b79812843e711989e6e743b/components/script/dom/window.rs#L680-L684 to WorkerGlobalScope, as well as https://github.com/servo/servo/blob/38f77f4bfb124b925b79812843e711989e6e743b/components/script/dom/window.rs#L382-L384.

**Comment by jdm** [comment]
I think you will need to add a webgl_chan member to https://github.com/servo/servo/blob/38f77f4bfb124b925b79812843e711989e6e743b/components/shared/constellation/from_script_message.rs#L459, and then you can access it from WorkerGlobalScope::new. Then you can add a webgl_chan argument to https://github.com/servo/servo/blob/38f77f4bfb124b925b79812843e711989e6e743b/components/script/dom/workers/workerglobalscope.rs#L88 and get it from the globals at the callsites by (again) downcasting them to Window or WorkerGlobalScope.

**Comment by niyabits** [comment]
@jdm While calling `prepare_workerscope_init` here:
https://github.com/servo/servo/blob/2a1290a591920fc693d6d64eb805d12c6fef0826/components/script/dom/workers/serviceworkerregistration.rs#L131

Expects a `WebGLChan`, 
But the method on `Window` type returns a `Option<WebGLCommandSender>`
https://github.com/servo/servo/blob/38f77f4bfb124b925b79812843e711989e6e743b/components/script/dom/window.rs#L680-L684

How should I go about returning `WebGLChan` from Window or changing the `WorkerGlobalScopeInit` to take a `WebGLCommandSender` instead?

**Comment by jdm** [comment]
That's fun! I suggest adding a temporary method to Window to return the WebGLChan until #44193 is fixed.

**Comment by niyabits** [comment]
Thanks for the help @jdm!
Everything compiles with offscreen webgl and the tests are partially running now :) 

That said, I still need to work on some stuff:
I used `unwrap` quite liberally on the downcast while I tried to get the changes compile. 
I will revisit the error handling.

In the `draw_offscreen_canvas` function in `CanvasState` we need to specify arms for webgl in the match.
I have added a comment and I will revisit them tomorrow.
https://github.com/servo/servo/blob/d11fc3a1c6d274330c60589acf3a398ac006fcd8/components/script/dom/canvas/2d/canvas_state.rs#L674-L675
 
Same for the `RenderingContext::Placeholder(ref context)` in the `draw_html_canvas_element` function,
https://github.com/servo/servo/blob/d11fc3a1c6d274330c60589acf3a398ac006fcd8/components/script/dom/canvas/2d/canvas_state.rs#L781-L785

I copied an unsafe method and implemented it on the `OffscreenCanvas` struct.
`get_gl_attributes`

I think this should be okay, although, I am not sure if there is a better way.

<details>
<summary>Test Result Summary</summary>

`tests/wpt/webgl/tests/conformance/offscreencanvas`
```
Ran 12 tests finished in 14.8 seconds.
  • 0 ran as expected.
  • 6 tests crashed unexpectedly
  • 6 tests unexpectedly okay
  • 5 tests had unexpected subtest results
```
`tests/wpt/webgl/tests/conformance2/offscreencanvas`
```
Ran 8 tests finished in 11.0 seconds.
  • 0 ran as expected.
  • 6 tests crashed unexpectedly
  • 2 tests unexpectedly okay
  • 1 tests had unexpected subtest results
  ```
  
<details>

File: components/script/dom/workers/worker.rs [hunk 1]
```diff
@@ -245,7 +245,13 @@ impl WorkerMethods<crate::DomTypeHolder> for Worker {
             }
         }
 
-        let init = prepare_workerscope_init(global, Some(devtools_sender), Some(worker_id));
+        let window = global.downcast::<Window>().unwrap();
```
Comment (jdm) [inline components/script/dom/workers/worker.rs]: This isn't a safe assumption, so we'll need to do:
```rust
let webgl_chan = global.downcast::<Window>().and_then(|window| window.webgl_chan_value())`
```
and probably file a followup issue about exposing the webgl_chan method on GlobalScope.

File: components/script/dom/workers/serviceworkerregistration.rs [hunk 2]
```diff
@@ -126,9 +126,12 @@ impl ServiceWorkerRegistration {
             pipeline_id: global.pipeline_id(),
         };
 
+        // TODO:  handle error better
+        let window = global.downcast::<Window>().unwrap();
```
Comment (jdm) [inline components/script/dom/workers/serviceworkerregistration.rs]: Same as previous; use and_then until we can fix GlobalScope.

File: components/script/dom/canvas/offscreencanvas.rs [hunk 3]
```diff
@@ -175,6 +204,68 @@ impl OffscreenCanvas {
...
+        }
+        if let Some(ctx) = self.context() {
+            return match *ctx {
+                OffscreenRenderingContext::WebGL2(ref ctx) => Some(DomRoot::from_ref(ctx)),
+                _ => None,
+            };
+        }
+        let global = self.global();
+        // TODO: Better error handling
+        let window = global.downcast::<Window>().unwrap();
```
Comment (jdm) [inline components/script/dom/canvas/offscreencanvas.rs]: Same here.

File: components/script/dom/canvas/offscreencanvas.rs [hunk 4]
```diff
@@ -175,6 +204,68 @@ impl OffscreenCanvas {
...
+    ) -> Option<DomRoot<WebGLRenderingContext>> {
+        if let Some(ctx) = self.context() {
+            return match *ctx {
+                OffscreenRenderingContext::WebGL(ref ctx) => Some(DomRoot::from_ref(ctx)),
+                _ => None,
+            };
+        }
+        let global = self.global();
+        // TODO: Better error handling
+        let window = global.downcast::<Window>().unwrap();
```
Comment (jdm) [inline components/script/dom/canvas/offscreencanvas.rs]: And here.

File: components/script/dom/canvas/2d/canvas_state.rs [hunk 5]
```diff
@@ -699,6 +699,13 @@ impl CanvasState {
                         self.state.borrow().transform,
                     ));
                 },
+                OffscreenRenderingContext::WebGL(ref _context) => {
+                    // TODO send canvas message?
```
Comment (jdm) [inline components/script/dom/canvas/2d/canvas_state.rs]: Try duplicating the BitmapRenderer branch here, which will call https://github.com/servo/servo/blob/38f77f4bfb124b925b79812843e711989e6e743b/components/script/dom/webgl/webglrenderingcontext.rs#L2068. That will be slow (it performs a readback operation from the GPU) but it should probably work.

File: components/script/dom/canvas/2d/canvas_state.rs [hunk 6]
```diff
@@ -808,6 +815,13 @@ impl CanvasState {
                                 self.state.borrow().transform,
                             ));
                         },
+                        OffscreenRenderingContext::WebGL(ref _context) => {
+                            // TODO send canvas message
```
Comment (jdm) [inline components/script/dom/canvas/2d/canvas_state.rs]: Same here—let's read the image data and draw that.

**Comment by jdm** [comment]
Exciting! This is looking really good!

File: components/script/dom/canvas/offscreencanvas.rs [hunk 7]
```diff
@@ -217,24 +217,37 @@ impl OffscreenCanvas {
...
-
-        // Step 2. Set this's context mode to WebGL Renderer.
-        *self.context.borrow_mut() =
-            Some(OffscreenRenderingContext::WebGL(Dom::from_ref(&*context)));
-
-        // Step 3. Return context.
-        Some(context)
+        self.global()
+            .downcast::<Window>()
+            .and_then(|window| {
```
Comment (jdm) [inline components/script/dom/canvas/offscreencanvas.rs:229]: Aha, we can file a followup issue about updating WebGLRenderingContext::new to accept a `&GlobalScope` argument instead.

File: components/script/dom/canvas/2d/canvas_state.rs [hunk 8]
```diff
@@ -700,11 +700,35 @@ impl CanvasState {
                     ));
                 },
                 OffscreenRenderingContext::WebGL(ref _context) => {
-                    // TODO send canvas message?
+                    let Some(snapshot) = context.get_image_data() else {
+                        return Ok(());
```
Comment (jdm) [inline components/script/dom/canvas/2d/canvas_state.rs]: In all of these new branches we need to rename `_context` to `context` so we're referring to the right context (the unfortunate risk of shadowing names!)

File: components/script/dom/canvas/offscreencanvas.rs (hunk 7 above)
Comment (niyabits) [reply components/script/dom/canvas/offscreencanvas.rs:229]: I have filed an issue :) 
https://github.com/servo/servo/issues/44213

**Comment by niyabits** [comment]
We could potentially merge this after #44214
I could rebase and replace all the `webgl_chan_value()` with `webgl_chan()`

Alternatively, we could do another cleanup PR or do cleanup in #44214 :)

**Comment by jdm** [comment]
Let's merge this as is :)

**Review by jdm — APPROVED** [review]
