### PR TITLE
Fix "Tried to use SpatialId before it was defined" layout panic

### LINKED ISSUE #19281: internal error: entered unreachable code: Tried to use WebRender SpatialId before it was defined.
Found with modified domato.

Testcase (happens with textarea as well):
```html
<style>
html{overflow:auto;width:0;transform:translate(0)}
html,input{text-overflow:ellipsis}
</style>
<input>
```

```gdb
VMware, Inc.
softpipe
3.3 (Core Profile) Mesa 17.3.0-devel
internal error: entered unreachable code: Tried to use WebRender ClipId before it was defined. (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }, at components/layout/webrender_helpers.rs:276)
stack backtrace:
   0:     0x557f0e3661b4 - backtrace::backtrace::libunwind::trace
                        at .cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace<closure>
                        at .cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:     0x557f0e35b50f - backtrace::capture::{{impl}}::new
                        at .cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:     0x557f0d8645de - servo::main::{{closure}}
                        at ports/servo/main.rs:130
   3:     0x557f140a9556 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x557f140a93e4 - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x557f140a92e9 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x557f11c46478 - layout::webrender_helpers::{{impl}}::convert_to_webrender::{{closure}}
                        at components/layout/webrender_helpers.rs:276
   7:     0x557f11b5c20e - layout::webrender_helpers::{{impl}}::convert_to_webrender
                        at components/layout/webrender_helpers.rs:281
   8:     0x557f11b5be77 - layout::webrender_helpers::{{impl}}::convert_to_webrender
                        at components/layout/webrender_helpers.rs:240
   9:     0x557f0f0bb070 - layout_thread::{{impl}}::compute_abs_pos_and_build_display_list::{{closure}}
                        at components/layout_thread/lib.rs:1032
  10:     0x557f0ef83a51 - profile_traits::time::profile<(),closure>
                        at /shared/dev/rust/servo/components/profile_traits/time.rs:125
  11:     0x557f0f0ba2d5 - layout_thread::{{impl}}::compute_abs_pos_and_build_display_list
                        at components/layout_thread/lib.rs:961
  12:     0x557f0f0c1c2e - layout_thread::{{impl}}::perform_post_main_layout_passes
                        at components/layout_thread/lib.rs:1613
  13:     0x557f0f0c1504 - layout_thread::{{impl}}::perform_post_style_recalc_layout_passes
                        at components/layout_thread/lib.rs:1597
  14:     0x557f0f0be2ee - layout_thread::{{impl}}::handle_reflow
                        at components/layout_thread/lib.rs:1315
  15:     0x557f0f0b82bd - layout_thread::{{impl}}::handle_request_helper::{{closure}}
                        at components/layout_thread/lib.rs:698
  16:     0x557f0ef836a3 - profile_traits::time::profile<(),closure>
                        at /shared/dev/rust/servo/components/profile_traits/time.rs:125
  17:     0x557f0f0b6fcf - layout_thread::{{impl}}::handle_request_helper
                        at components/layout_thread/lib.rs:695
  18:     0x557f0f0b5e1b - layout_thread::{{impl}}::handle_request
                        at components/layout_thread/lib.rs:641
  19:     0x557f0f0b5133 - layout_thread::{{impl}}::start
                        at components/layout_thread/lib.rs:554
  20:     0x557f0f0b1ef9 - layout_thread::{{impl}}::create::{{closure}}::{{closure}}
                        at components/layout_thread/lib.rs:314
  21:     0x557f0ef81a79 - profile_traits::mem::{{impl}}::run_with_memory_reporting<closure,fn(profile_traits::mem::ReportsChan) -> script_layout_interface::message::Msg,script_layout_interface::message::Msg,std::sync::mpsc::Sender<script_layout_interface::message::Msg>>
                        at /shared/dev/rust/servo/components/profile_traits/mem.rs:63
  22:     0x557f0f0b2493 - layout_thread::{{impl}}::create::{{closure}}
                        at components/layout_thread/lib.rs:313
  23:     0x557f0f2f763a - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /checkout/src/libstd/sys_common/backtrace.rs:134
  24:     0x557f0efc95d3 - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:400
  25:     0x557f0f2c039a - std::panic::{{impl}}::call_once<(),closure>
                        at /checkout/src/libstd/panic.rs:296
  26:     0x557f0f22ccc2 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panicking.rs:480
  27:     0x557f140b069c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  28:     0x557f0f22c2fc - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:459
  29:     0x557f0f2f9635 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panic.rs:361
  30:     0x557f0efc93fb - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:399
  31:     0x557f0f03b4f3 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /checkout/src/liballoc/boxed.rs:762
  32:     0x557f140a826b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:772
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:24
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  33:     0x7fd3b54db493 - start_thread
  34:     0x7fd3b4e00abe - __clone
  35:                0x0 - <unknown>
ERROR:servo: internal error: entered unreachable code: Tried to use WebRender ClipId before it was defined.
Pipeline failed in hard-fail mode.  Crashing!
thread panicked while processing panic. aborting.
Servo exited with return value 1
```

### LINKED ISSUE #22826: Could not load the requested page: Unexpected scheme
This is the error I get when I click on the facebook logo.

Could not load the requested page: Unexpected scheme

### LINKED ISSUE #24895: Login page for Microsoft accounts panics (Tried to use WebRender SpatialId before it was defined.)
```
godot:master-servo jdm$ ./mach run http://account.microsoft.com
[2019-11-28T19:35:15Z ERROR script::dom::bindings::error] Error at :0:0 SecurityError: The operation is insecure.
[2019-11-28T19:35:15Z ERROR script::dom::bindings::error] Error at :0:0 SecurityError: The operation is insecure.
Tried to use WebRender SpatialId before it was defined. (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }, at src/libcore/option.rs:1187)
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/jdm/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.38/src/backtrace/libunwind.rs:88
      backtrace::backtrace::trace_unsynchronized
             at /Users/jdm/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.38/src/backtrace/mod.rs:66
   1: backtrace::backtrace::trace
             at /Users/jdm/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.38/src/backtrace/mod.rs:53
   2: backtrace::capture::Backtrace::create
             at /Users/jdm/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.38/src/capture.rs:164
   3: backtrace::capture::Backtrace::new
             at /Users/jdm/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.38/src/capture.rs:128
   4: servo::main::{{closure}}
             at ports/glutin/main2.rs:142
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:468
   6: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
   7: rust_begin_unwind
             at src/libstd/panicking.rs:302
   8: std::panicking::begin_panic
   9: std::panicking::begin_panic
  10: core::option::Option<T>::expect
             at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/libcore/option.rs:347
  11: layout::display_list::webrender_helpers::<impl layout::display_list::items::DisplayItem>::convert_to_webrender
             at components/layout/display_list/webrender_helpers.rs:92
  12: layout::display_list::webrender_helpers::<impl layout::display_list::items::DisplayList>::convert_to_webrender
             at components/layout/display_list/webrender_helpers.rs:68
  13: layout_thread::LayoutThread::compute_abs_pos_and_build_display_list::{{closure}}
             at components/layout_thread/lib.rs:1237
  14: profile_traits::time::profile
             at components/profile_traits/time.rs:147
  15: layout_thread::LayoutThread::compute_abs_pos_and_build_display_list
             at components/layout_thread/lib.rs:1113
  16: layout_thread::LayoutThread::perform_post_main_layout_passes
             at components/layout_thread/lib.rs:1926
  17: layout_thread::LayoutThread::perform_post_style_recalc_layout_passes
             at components/layout_thread/lib.rs:1906
  18: layout_thread::LayoutThread::tick_animations
             at components/layout_thread/lib.rs:1776
  19: layout_thread::LayoutThread::tick_all_animations
             at components/layout_thread/lib.rs:1732
  20: layout_thread::LayoutThread::handle_request_helper
             at components/layout_thread/lib.rs:821
  21: layout_thread::LayoutThread::handle_request
             at components/layout_thread/lib.rs:748
  22: layout_thread::LayoutThread::start
             at components/layout_thread/lib.rs:646
  23: <layout_thread::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}::{{closure}}
             at components/layout_thread/lib.rs:369
  24: profile_traits::mem::ProfilerChan::run_with_memory_reporting
             at components/profile_traits/mem.rs:88
  25: <layout_thread::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}
             at components/layout_thread/lib.rs:367
  26: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/libstd/sys_common/backtrace.rs:136
  27: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/libstd/thread/mod.rs:469
  28: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/libstd/panic.rs:316
  29: std::panicking::try::do_call
             at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/libstd/panicking.rs:287
  30: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:81
  31: std::panicking::try
             at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/libstd/panicking.rs:265
  32: std::panic::catch_unwind
             at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/libstd/panic.rs:395
  33: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/libstd/thread/mod.rs:468
  34: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/libcore/ops/function.rs:227
  35: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/liballoc/boxed.rs:942
  36: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/1bd30ce2aac40c7698aa4a1b9520aa649ff2d1c5/src/liballoc/boxed.rs:942
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  37: <unknown>
  38: <unknown>
```

### PR DESCRIPTION
**Pull request by jdm**
In the case where an element uses `text-overflow: ellipsis` and causes overflow, we create a TruncatedFragment that wraps the original overflowing fragment. When collecting stacking contexts for the truncated fragment, https://github.com/servo/servo/pull/18510 addressed the case where the wrapped fragment wouldn't be processed, but neglected the case where that fragment ends up creating a new stacking context. When that happens, the TruncatedFragment would be stuck with the updated scrolling/clipping information based on the new stacking context, but it would be a child of the parent stacking context. Since the new scrolling/clipping nodes do not exist in the display list until the new stacking context display item is created, this led to the observed panic.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #24895 and fix #19281 and fix #22826. 
- [x] There are tests for these changes

### CODE REVIEW

File: components/layout/display_list/builder.rs [hunk 1]
```diff
@@ -606,9 +606,15 @@ impl Fragment {
...
-                .collect_stacking_contexts_for_blocklike_fragment(state),
+            SpecificFragmentInfo::TruncatedFragment(ref mut info) => {
+                let _ = info
+                    .full
+                    .collect_stacking_contexts_for_blocklike_fragment(state);
+                // To ensure the caller updates this fragment's stacking context
+                // appropriately based on the un-truncated fragment's status,
+                // we don't pass on the result of collecting stacking contexts.
+                false
+            },
```
Comment (SimonSapin) [inline components/layout/display_list/builder.rs]: I’m not very familiar with this source file, and unfortunately there is no doc-comment explaining what this boolean represents. Still, this change looks reasonable if it fixes a panic.

File: tests/wpt/mozilla/tests/mozilla/text-overflow-ellipsis-stacking-context.html [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+  .woo {
+      min-width: 1px;
+      overflow: hidden;
+      text-overflow: ellipsis;
+      box-sizing: border-box;
+      padding-left: 0.25em;
+      display: inline-block;
+  }
+
+  .animate {
```
Comment (SimonSapin) [inline tests/wpt/mozilla/tests/mozilla/text-overflow-ellipsis-stacking-context.html]: The name of `.animate` seems misleading since there is no animation.

File: tests/wpt/mozilla/tests/mozilla/text-overflow-ellipsis-stacking-context.html [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+      transform: translateX(1px);
+      display: inline-block;
+  }
```
Comment (SimonSapin) [inline tests/wpt/mozilla/tests/mozilla/text-overflow-ellipsis-stacking-context.html]: There’s quite a bit going on here. Is all of it necessary to reproduce the panic without the Rust code change, or could this test be reduced?

Comment (jdm) [reply tests/wpt/mozilla/tests/mozilla/text-overflow-ellipsis-stacking-context.html]: This is actually reduced as much as possible. Any change to the CSS rules or properties causes the panic to disappear.

Comment (jdm) [reply tests/wpt/mozilla/tests/mozilla/text-overflow-ellipsis-stacking-context.html]: Nevermind, I was able to make it more clear and renamed the classes as well.

File: components/layout/display_list/builder.rs (hunk 1 above)
Comment (jdm) [reply components/layout/display_list/builder.rs]: Yep. This was all guesswork on my part; nobody is on the team who understands this code any more.

**Comment by SimonSapin** [comment]
I’ve pushed an amended commit with `./mach update-manifest`

@bors-servo r+

**Comment by jdm** [comment]
@bors-servo retry
#24726
