### PR TITLE
script: Report target padding and desired sizes for ResizeObserver notifications

### LINKED ISSUE #32549: Fix DOMRect calc in ResizeObserverEntry
Part of https://github.com/servo/servo/issues/31182 (see `observe.html`). 

Relevant tests: all those testing `contentRect.top` or `contentRect.left`, such as 

https://github.com/servo/servo/blob/fef1337da0f5bfed27225972e33d8c94d38bfbb3/tests/wpt/tests/resize-observer/observe.html#L266

Code is at: https://github.com/servo/servo/blob/70982dfa5aaf176a46308aa4075128e8edd53da2/components/script/dom/resizeobserver.rs#L127

Currently it is wrong, by using `box_size.origin.x`, instead it should calculate the distance between `origin` and the viewport. 

For example, for `x`, the [spec says](https://drafts.fxtf.org/geometry-1/#rectangle-x-coordinate) to calculate the "The horizontal distance between the viewport’s left edge and the rectangle’s [origin](https://drafts.fxtf.org/geometry-1/#rectangle-origin)."

-----

To make these calculations, I think we need to use the viewport found on the `WindowSizeData` stored at https://github.com/servo/servo/blob/70982dfa5aaf176a46308aa4075128e8edd53da2/components/script/dom/window.rs#L243

and accessible via https://github.com/servo/servo/blob/70982dfa5aaf176a46308aa4075128e8edd53da2/components/script/dom/window.rs#L2298

and using the available [`box_size`](https://github.com/servo/servo/blob/70982dfa5aaf176a46308aa4075128e8edd53da2/components/script/dom/resizeobserver.rs#L110) and/or the available `box_size.origin`. 

These are all using measurements from https://docs.rs/euclid/latest/euclid/index.html, but it is not clear how to exactly get to "the distance between".

### PR DESCRIPTION
**Pull request by jdm**
We were not following the specification for computing the values of the content rect. Additionally, any non-content-box observer would get confused because we never stored the correct size, leading to infinite notifications when the latest size didn't match the last observed size.

Testing: Various tests now pass.
Fixes: #32549
Fixes: #40107

### CODE REVIEW

File: components/script/dom/resizeobserver.rs [hunk 1]
```diff
@@ -171,23 +174,48 @@ fn create_and_populate_a_resizeobserverentry(
...
 
+    // Step 7. If target is not an SVG element or target is an SVG element with an associated CSS layout box do these steps:
+    let use_padding = *target.namespace() != ns!(svg) || target.has_css_layout_box();
+    let (padding_top, padding_left) = if use_padding {
+        // Step 7.1. Set this.contentRect.top to target.padding top.
+        // Step 7.2. Set this.contentRect.left to target.padding left.
+        target
+            .upcast::<Node>()
+            .padding_top_and_left()
+            .unwrap_or_default()
```
Comment (mrobinson) [inline components/script/dom/resizeobserver.rs]: Is this supposed to trigger a layout? In IntersectionObserver we are not, so it's a bit strange that ResizeObserver does.

File: components/script/dom/window.rs [hunk 2]
```diff
@@ -2620,6 +2620,23 @@ impl Window {
         )
     }
 
+    /// Do the same kind of query as `Self::padding_top_and_left_query`, but do not force a reflow.
+    /// This is used for things like `IntersectionObserver` which should observe the value
+    /// from the most recent reflow, but do not need it to reflect the current state of
+    /// the DOM / style.
+    pub(crate) fn padding_top_and_left_query_without_reflow(
```
Comment (mrobinson) [inline components/script/dom/window.rs]: If this is only used here, I guess it doesn't need to be `pub(crate)`. I'm not sure if you plan was to use this in `ResizeObsever` though...

File: components/layout/query.rs [hunk 3]
```diff
@@ -68,6 +69,20 @@ fn root_transform_for_layout_node(
     Some(scroll_tree.cumulative_node_to_root_transform(scroll_tree_node_id))
 }
 
+pub(crate) fn process_padding_top_and_left_request(
+    node: ServoThreadSafeLayoutNode<'_>,
+) -> Option<(Au, Au)> {
```
Comment (mrobinson) [inline components/layout/query.rs]: Nit, I think it's a bit friendlier just to return the entire padding everywhere and name this a `padding_query`.

**Review by mrobinson — COMMENTED** [review]
Just a few comments...

File: components/layout/query.rs [hunk 4]
```diff
@@ -68,6 +69,20 @@ fn root_transform_for_layout_node(
...
+    let fragments = node.fragments_for_pseudo(None);
+    let fragment = fragments.first()?;
+    match fragment {
```
Comment (Loirooriol) [inline components/layout/query.rs]: Nit: both cases use Some, so this could be `Some(match...)` to avoid repeating

**Review by mrobinson — APPROVED** [review]
