### PR TITLE
libservo: Expose a single `InputEvent` type and pass it to script

### LINKED ISSUE #35393: Webdriver mouse button conversion is broken
This code is incorrect: https://github.com/servo/servo/blob/d733abfca02cdb9fd2af4f0d82ff050e25f71829/components/webdriver_server/actions.rs#L84-L92

The [MouseButton enum](https://doc.servo.org/embedder_traits/enum.MouseButton.html) is defined values that are used as a bitmask to allow multiple button presses to be recorded together (introduced in be3cb00c775f7adff864200512f54ec8d8090a09). The WebDriver mouse buttons are unrelated to these values, so we can't just perform an equality check—we need an explicit conversion step instead.

### PR DESCRIPTION
**Pull request by mrobinson**
This change exposes a single `InputEvent` type and now there is only a
single delegate method for this `WebViewDelegate::notify_input_event`.

- Clipboard events are now handled as `EditingAction` inpute events. In
  the future this can include things like "Select All", etc.

In addition, many parts of the dance to pass these events can now be
simplified due to this abstraction.

- All forwarded events are handled the same way in the `Constellation`,
  though they may carry an optional hit test (for events that have a
  `point`) which affects which `Pipeline` they are sent to.
- In the `ScriptThread` we now accept these `InputEvents` and use them
  everywhere. Now all "compositor events" are "input events".
- This allows removing several data structures which are no longer
  necessary.
- We no longer inform the embedder when an event was handled by a
  WebView as that was only important for a MDI feature that will
  no longer be so important the full-featured `WebView` API.

Co-authored-by: Mukilan Thiyagarajan <mukilan@igalia.com>
Signed-off-by: Martin Robinson <mrobinson@igalia.com>

Fixes #35393.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because they don't change behavior and input handling is already covered by existing tests.

### CODE REVIEW

File: components/script/script_thread.rs [hunk 1]
```diff
@@ -3318,75 +3277,12 @@ impl ScriptThread {
...
-                button,
-                point,
-                mouse_event_type,
-                node_address,
-                point_in_node,
-                pressed_mouse_buttons,
-                can_gc,
-            )
-        }
-    }
```
Comment (mrobinson) [inline components/script/script_thread.rs:3356]: These methods have been moved inline and now call the `Document` methods directly. That avoids an extra lookup of `Document` and the `unsafe` bits are just in a single line now.

File: components/script/dom/node.rs [hunk 2]
```diff
@@ -1420,6 +1421,15 @@ pub(crate) unsafe fn from_untrusted_node_address(candidate: UntrustedNodeAddress
...
 
+/// If the given untrusted node address represents a valid DOM node in the given runtime,
+/// returns it.
+#[allow(unsafe_code)]
+pub(crate) unsafe fn from_untrusted_compositor_node_address(
+    candidate: CompositorUntrustedNodeAddress,
+) -> DomRoot<Node> {
+    DomRoot::from_ref(Node::from_untrusted_compositor_node_address(candidate))
+}
+
```
Comment (mrobinson) [inline components/script/dom/node.rs:1432]: We had to make a new version of functions in this file because the `webrender_traits` (really should be called `compositor_traits`) crate has its own version of `UntrustedNodeAddress` and now we are passing hit test results straight through to the `ScriptThread` from the compositor.

File: components/servo/webview.rs [hunk 3]
```diff
@@ -310,68 +309,30 @@ impl WebView {
...
-            .on_touch_event(event_type, id, point);
-    }
-
-    pub fn notify_wheel_event(&self, delta: WheelDelta, point: DevicePoint) {
-        self.inner()
-            .compositor
-            .borrow_mut()
-            .on_wheel_event(delta, point);
-    }
-
```
Comment (mrobinson) [inline components/servo/webview.rs:340]: Now there is just `WebView::notify_input_event`. I haven't touched `notify_scroll_event` yet, as I suspect that this will turned into an API like `scroll()`.

File: ports/servoshell/desktop/app_state.rs [hunk 4]
```diff
@@ -526,13 +526,6 @@ impl WebViewDelegate for RunningAppState {
         self.inner_mut().need_present = true;
     }
 
-    fn notify_event_delivered(&self, webview: servo::WebView, event: CompositorEventVariant) {
-        if let CompositorEventVariant::MouseButtonEvent = event {
-            webview.raise_to_top(true);
-            webview.focus();
-        }
-    }
-
```
Comment (mrobinson) [inline ports/servoshell/desktop/app_state.rs:535]: This was a feature used for the MDI WebView experiment. I've removed it because we are gradually moving to a model where the embedder manages focus and draw order itself and each `WebView` is a separate "widget."

**Review by mukilan — APPROVED** [review]

**Review by wusyong — APPROVED** [review]
lgtm. Loosks like most events are the same. It shouldn't be too difficult to update from embedder side.

**Comment by mrobinson** [comment]
> lgtm. Loosks like most events are the same. It shouldn't be too difficult to update from embedder side.

Yep, our idea is that for the moment the events are the same, but if we ever need to change anything or add a field we don't have to modify many places in the code.

File: components/shared/script/lib.rs [hunk 5]
```diff
@@ -476,64 +474,16 @@ pub enum AnimationState {
...
-            CompositorEvent::GamepadEvent(..) => CompositorEventVariant::GamepadEvent,
-            CompositorEvent::ClipboardEvent(..) => CompositorEventVariant::ClipboardEvent,
-        }
-    }
+pub struct ConstellationInputEvent {
+    /// The hit test result of this input event, if any.
+    pub hit_test_result: Option<CompositorHitTestResult>,
+    /// The pressed mouse button state of the constellation when this input
+    /// event was triggered.
+    pub pressed_mouse_buttons: u16,
```
Comment (jschwe) [inline components/shared/script/lib.rs:484]: Could this be a newtype / bitfield instead?

**Review by jschwe — APPROVED** [review]
LGTM, only one minor nit that can also be addressed seperatly / made into an issue.

File: components/constellation/constellation.rs [hunk 6]
```diff
@@ -2893,57 +2878,91 @@ where
...
-                MouseButtonEvent(
-                    event_type,
-                    button,
-                    point,
-                    node_address,
-                    point_in_node,
-                    self.pressed_mouse_buttons,
-                )
+        match event.action {
+            MouseButtonAction::Click | MouseButtonAction::Down => {
```
[the remark this answers is not in the document]
Comment (jdm) [reply components/constellation/constellation.rs:2895]: Oh, I just saw the code in forward_input_event that looks like it resets this.

File: ports/servoshell/desktop/app_state.rs (hunk 4 above)
Comment (wusyong) [reply ports/servoshell/desktop/app_state.rs:535]: I just noticed this is removed. How do we focus webview after this PR?

Comment (wusyong) [reply ports/servoshell/desktop/app_state.rs:535]: Just saw #35454. I suppose real fix is to make webview can be focused instead of just elements.

Comment (mrobinson) [reply ports/servoshell/desktop/app_state.rs:535]: > I just noticed this is removed. How do we focus webview after this PR?

Focus should be handled by the embedder. So in minibrowser, focus switches when switching tabs. This code was just for the MDI experiment that isn't used any longer.
