### PR TITLE
Return the highest priority error from the descendant instead of return the very first one

### LINKED ISSUE #25436: Investigate failure of /html/semantics/scripting-1/the-script-element/module/error-type-1.html after module script landed
Before the IndexSet fix, we will get this failure intermittently. But, I can reproduce this failure consistently.

For merging #23545 first, marked it as FAIL in that PR and fix it separately.

```
1 unexpected results that are NOT known-intermittents:
  ▶ Unexpected subtest result in /html/semantics/scripting-1/the-script-element/module/error-type-1.html:
  │ FAIL [expected PASS] network error has higher priority than parse error
  │   → assert_equals: expected 3 but got 4
  │ 
  │ @http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/module/error-type-1.html:16:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1984:25
  └ Test.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:2025:32

```

_Originally posted by @Manishearth in https://github.com/servo/servo/pull/23545#issuecomment-571051685_

### PR DESCRIPTION
**Pull request by CYBAI**
The test failed because we didn't return the highest priority error (which is network error in this case).

As Manish mentioned in https://github.com/servo/servo/issues/25436#issuecomment-571065323, that's because we're using the Promise.all trick to signal loads.

If we can avoid relying on Promise.all, maybe we don't need to do a complex logic like this; instead, ideally, we should always finish the module load immediately when we hit network failure so that we don't even need to do the `max()` comparison.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #25436 
- [x] There are tests for these changes

### CODE REVIEW

**Comment by CYBAI** [comment]
The failure is #25522

File: components/script/script_module.rs [hunk 1]
```diff
@@ -651,12 +652,12 @@ impl ModuleTree {
 
             // 8-4.
             if child_parse_error.is_some() {
-                return child_parse_error;
+                errors.push(child_parse_error.unwrap());
```
Comment (jdm) [inline components/script/script_module.rs]: Let's use `if let Some` instead of is_some and unwrap.

File: components/script/script_module.rs [hunk 2]
```diff
@@ -651,12 +652,12 @@ impl ModuleTree {
...
             }
         }
 
         // Step 9.
-        return None;
+        return errors.iter().max().map(|err| err.clone());
```
Comment (jdm) [inline components/script/script_module.rs]: We should be able to do `errors.into_iter().max()` instead.

**Review by jdm — CHANGES_REQUESTED** [review]
Looks sensible!

File: components/script/script_module.rs (hunk 2 above)
Comment (CYBAI) [reply components/script/script_module.rs]: Thanks for the hint!!! I finally understand the difference between `into_iter()` and `iter()` 😍 That's what I want!

**Comment by jdm** [comment]
@bors-servo retry
* #25558
