### PR TITLE
script: Update the rendering when receiving IPC messages instead of just reflowing

### LINKED ISSUE #34303: CSS transitions triggered via script do not work
Given the following page:

```html
<!DOCTYPE html>
<style>
    body { margin: 0; }
    #one, #two, #three { font-size: 30px; width: 500px; height: 50px; }
    #container {
        position: absolute;
        background-color: transparent;
        box-shadow: none;
        transition: all .5s;
        outline: solid;
    }

    #one {
        transition: all .5s ease-in-out;
    }

    #container:hover, #container.on  {
        background-color: green;
    }

    #container:hover > #one, #container.on > #one {
        height: 0px;
    }
</style>

<div id="container">
    <div id="one" style="background: blue;"></div>
    <div id="two">two</div>
    <div id="three">three</div>
</div>

<script>
    setInterval(() => container.classList.toggle("on"), 3000);
</script>

```

Every three seconds, the "on" class is toggled on the container, which should trigger two transitions. This does not transition, instead the change happens instantly. However, the same style changes happen on hovering, which does work. Note that that ":hover" pseudo class never seems to be removed which is #34302.

### PR DESCRIPTION
**Pull request by mrobinson**
This change brings the `ScriptThread` closer to the specification and fixes
two issues:

1. A reflow of all `Document`s is currently done unconditionally after
   receiving IPC messages in the `ScriptThread`. Reflowing without first
   updating the animation timeline can lead to transitions finshing as
   soon as they start (because it looks like time advancement is
   measured between calls to `update-the-rendering`).
2. Fix an issue where not all `Pipeline`s were updated during *update
   the rendering*. The previous code only took into account top level
   frames and their children. It's not guaranteed that a particular
   `ScriptThread` is managing any top level frames, depending on the
   origins of those frames. We should update the rendering of those
   non-top-level iframes regardless.

   The new code attempts to order the frames according to the
   specification as much as possible without knowing the entire frame
   tree, without skipping any documents managed by the `ScriptThread` in
   question.

In addition, `Documents` is pulled out the `script_thread.rs` and
renamed to `DocumentCollection`. 

In general, these issues were always noticeable because they depend
on the order of operations in the `ScriptThread` and when IPC messages
arrive. It's difficult to test them, but it should make things work consistently
in one particular timing case.

Signed-off-by: Martin Robinson <mrobinson@igalia.com>

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #34303.
- [x] There are no new tests for these changes as transitions are covered by existing tests. In order to observe this issue a very particular timing situation has to happen where the transition has to be triggered by a reflow after receiving an IPC message. This isn't possible to guarantee with a WPT tests, so this is verified via manual testing.

### CODE REVIEW

File: components/script/script_thread.rs [hunk 1]
```diff
@@ -1606,31 +1532,31 @@ impl ScriptThread {
...
+        // > list.
+        //
+        // > If there are two documents A and B that both have the same non-null container
+        // > document C, then the order of A and B in the list must match the
+        // > shadow-including tree order of their respective navigable containers in C's
+        // > node tree.
+        //
+        // > In the steps below that iterate over docs, each Document must be processed in
+        // > the order it is found in the list.
+        let documents_in_order = self.documents.borrow().documents_in_order();
```
Comment (gterzian) [inline components/script/script_thread.rs:1550]: I don't understand which documents we would miss before. Are we talking about cross origin iframes? Should there rendering not be updated in the script-thread managing them?

File: components/script/document_collection.rs [hunk 2]
```diff
@@ -0,0 +1,177 @@
...
+}
+
+/// A tree representation of [`Document`]s managed by the [`ScriptThread`][st], which is used
+/// to generate an ordered set of [`Document`]s for the *update the rendering* step of the
+/// HTML5 specification.
+///
+/// FIXME: The [`ScriptThread`][st] only has a view of [`Document`]s managed by itself,
+/// so if there are interceding iframes managed by other `ScriptThread`s, then the
+/// order of the [`Document`]s may not be correct. Perhaps the Constellation could
+/// ensure that every [`ScriptThread`][st] has the full view of the frame tree.
```
Comment (gterzian) [inline components/script/document_collection.rs:130]: In the "interceding iframes" case, does the ordering actually matter from the perspective of "update the rendering"? Or where we filtering out documents and not updating their rendering?

**Review by gterzian — CHANGES_REQUESTED** [review]
I am doubtful of this change, because running the "update the rendering" steps at the end of each iteration of the script-thread seems to be a step backwards in terms of spec compatibility. 

On the other hand, the doc ordering changes may be useful, but I would like to understand them more before approving this(see questions in comment). 

Also, not doing a reflow at the end of each iteration of the script-thread is also a good idea, since it should only happen as the almost final step of updating the rendering. But that change combined with running all the update the rendering steps at each iteration means we are actually not progressing in terms of spec compat.

The problem here seem to be doing reflows without first having run "[update animations and send events](https://drafts.csswg.org/web-animations-1/#update-animations-and-send-events)"(step 11 of update the rendering), and to fix this we should not be swapping a reflow for a full "update the rendering", but instead we should be noting more rendering ops and only reflowing as part of "update the rendering".   

I think a more acceptable change would be to indeed move the reflow to the "update the rendering part", and then either:

1. note a rendering opportunity after each message(see comment below), or
2. introduce a new compositor message to tell the script-thread to note a rendering opportunity and ensure this message is sent "often enough". 

2 is in fact where we should be going architecturally. 

If we go for 1 for now, we should remove all other calls to `ScriptThread::note_rendering_opportunity` and `rendering_opportunity` since they would become redundant. 

Actually come to think of it, this would I think also require queuing the task but without tying it to a specific pipeline, which means sending a new variant of a script message to the script thread to run the steps(could be batched to allow for other messages to be handled before), and make run we run a micro task checkpoint after.

File: components/script/script_thread.rs [hunk 3]
```diff
@@ -1694,6 +1620,14 @@ impl ScriptThread {
 
             // TODO(#31871): Update the rendering: consolidate all reflow calls into one here?
 
+            // > Step 22: For each doc of docs, update the rendering or user interface of
+            // > doc and its node navigable to reflect the current state.
+            let window = document.window();
+            let pending_reflows = window.get_pending_reflow_count();
+            if document.is_fully_active() && pending_reflows > 0 {
+                window.reflow(ReflowGoal::Full, ReflowReason::PendingReflow, can_gc);
+            }
```
[the remark this answers is not in the document]
Comment (mrobinson) [reply components/script/script_thread.rs:1629]: In this end, these extra forced reflows were unnecessarily, so I've removed them. I think they were left over from a time when reflows were not queued properly.

File: components/script/script_thread.rs [hunk 4]
```diff
@@ -1694,6 +1620,14 @@ impl ScriptThread {
 
             // TODO(#31871): Update the rendering: consolidate all reflow calls into one here?
 
+            // > Step 22: For each doc of docs, update the rendering or user interface of
```
[the remark this answers is not in the document]
Comment (mrobinson) [reply components/script/script_thread.rs:1623]: Great. This is what I've tried to do here.

**Comment by gterzian** [comment]
@mrobinson So I've thought about this a bit more, I propose the following:

- Add a new `RenderingOp` variant to [`MainThreadScriptMsg`](https://github.com/servo/servo/blob/bba3bc6ac2dd8c28d365a5f30d32da838f78286e/components/script/script_thread.rs#L287)
- [`rendering_opportunity`](https://github.com/servo/servo/blob/bba3bc6ac2dd8c28d365a5f30d32da838f78286e/components/script/script_thread.rs#L1703) should not take a `PipelineId`, instead it should just send this new `RenderingOp` message, if one was not sent already(so batch with a boolean for the whole script-thread).
- `update_the_rendering` is run when the message is received(and sets batching boolean to false). 
- We call `rendering_opportunity` [here](https://github.com/servo/servo/blob/bba3bc6ac2dd8c28d365a5f30d32da838f78286e/components/script/script_thread.rs#L2020). 
- We remove all current use of `rendering_opportunity` and `note_rendering_opportunity`. 
- As a follow-up, we look into replacing `MainThreadScriptMsg::RenderingOp` with a message from the compositor. 

This deals with the current problem, while still moving us in the right direction(and calling `note_rendering_opportunity` from various places in the dom is not really a sustainable solution either).

**Comment by mrobinson** [comment]
I think I have managed to work my head around what the issue is. We cannot simply note a rendering opportunity for each IPC message because noting a rendering opportunity triggers an IPC message itself! This leads to an infinite loop of updates. What I've done instead is to follow your original suggestion which is to note a rendering opportunity for other types of messages. This is still wrongish -- as rendering opportunities should be noted when specific things change and not so unconditionally. It's strictly less wrong than before, as it actually is using *update the rendering* to do the work rather than a simple reflow.

In addition, I've added a guard in *update the rendering* to avoid doing so much work when multiple pipelines queue them at once. This should mitigate some of the extra work that would have been doing by queuing an update for every message and I think this is also more correct.

I see this change as part one. The next part would be to actually note rendering opportunities in the right situations (partially done, but not complete). This is trickier and deserves a longer look, as it's important not to cause an infinite loop of updates which is fairly easy to do.

File: components/script/document_collection.rs (hunk 2 above)
Comment (mrobinson) [reply components/script/document_collection.rs:130]: Hrm. It's unclear to me if it matters or not. I'm not sure what kind of behavior the WPT suites are testing and if they are testing complex situations involving iframes nested with different origins. Exactly following the spec here would require a lot of tricky synchronization between different `ScriptThread`s (and potentially different processes) though.

File: components/script/script_thread.rs (hunk 1 above)
Comment (mrobinson) [reply components/script/script_thread.rs:1562]: Here's an example of a document we should miss:

```
Top Level Frame (Script Thread 1)
  - IFrame1 (Script Thread 2)
  - IFrame2 (Script Thread 2)
```

We would miss `Iframe1` and `Iframe2` in this case because they aren't top-level frames and they also aren't children of any Documents managed by `Script Thread 2`.

Comment (gterzian) [reply components/script/script_thread.rs:1562]: Ok, thanks for the explanation.

File: components/script/script_thread.rs [hunk 5]
```diff
@@ -1958,16 +1903,24 @@ impl ScriptThread {
...
 
             // https://html.spec.whatwg.org/multipage/#event-loop-processing-model step 6
             // TODO(#32003): A microtask checkpoint is only supposed to be performed after running a task.
             self.perform_a_microtask_checkpoint(can_gc);
+
+            // TODO: Currently all events handled here always trigger a rendering
+            // opportunity, but this isn't correct. Rendering opportunities should only be
+            // triggered when appropriate and then this line of code should be removed.
+            if let Some(pipeline_id) = pipeline_id {
+                ScriptThread::note_rendering_opportunity(pipeline_id);
```
Comment (gterzian) [inline components/script/script_thread.rs:1922]: I suggest instead trying to, at the end of `handle_msgs`:

- call `update_the_rendering`
- call `perform_a_microtask_checkpoint`(and remove the call [here](https://github.com/servo/servo/pull/34486/files#diff-2c5948584719622eef023c56cdf90e8278971f2f2eda26e7fd0485a24c32be3cR1916)

and see if this fixes your problem. 

I think it's better to do it like that then using `ScriptThread::note_rendering_opportunity` here, and also the way we currently use `ScriptThread::note_rendering_opportunity` in various places is hacky. 

You can then also remove the guard you added, and simply rely on the fact that `handle_msgs` runs [potentially many messages](https://github.com/servo/servo/blob/24984ed9e2890d3f51ec6c5e32337c247b4eb020/components/script/script_thread.rs#L1857) for each call to update the rendering(since this is done once at the end and see ). 

If updating the rendering at the end does not solve your problem, you could do it at the beginning, so at https://github.com/servo/servo/blob/24984ed9e2890d3f51ec6c5e32337c247b4eb020/components/script/script_thread.rs#L1720

Worse case you can do it at the beginning, and at the end. 

I suggest experimenting with this first, and then there are some clean-ups that can be done but I can tell you about it later(it's essentially about removing stuff like https://github.com/servo/servo/blob/24984ed9e2890d3f51ec6c5e32337c247b4eb020/components/script/script_thread.rs#L1793 and any noting of rendering opportunities which would not be necessary anymore).

Lastly, we may still need to ensure `handle_msgs` is woken-up with a message, if running the update the rendering steps like suggested appears to create timeout(which would be because the task queuing of noting the rendering opportunity turns out to be important to wake up the script-thread, but since most noting of those are now done from within a message handling, I don't think this will be the case).

Comment (gterzian) [reply components/script/script_thread.rs:1922]: Actually what I wrote about the microtask is incorrect(I've since edited it), we should leave the current checkpoint in place, because it covers taks run before as part of the `sequential` loop, and we should simply add a new checkpoint after updating the rendering, since that must be done in a task, which in our case is simulated by making sure we do a checkpoint after running the steps. You might want to make that checkpoint condition on an update of the rendering having taken place.

**Review by gterzian — COMMENTED** [review]
As per our discussion on zulip, here is a hopefully correct summary of the problem and the options we have:

When writing "now", you mean the current state of your PR, right? 

So I don't know exaxctly what the problem is, but I saw the timeouts and your comments that this was causing lags for animation. 

So let's go back to the beginning:

As I understand it, the original problem was running a reflow without having "updated the rendering", because the updating of the animation timeline is done as part of those steps. 

So I assume the problem was:  
1.  a message is handled by the script-thread that "starts the animation"(I don't know what the exact mechanism here is), 
2. and then at the end of `handle_msgs` would would always do a reflow, which was "too early", because it would happen before having run the update the rendering steps. 

So this problem in theory can be solved by :
1. moving the reflow to the (almost) last step of "update the rendering", which is actually what the spec mandates, and:
2. "noting a rendering opp" as part of "starting an animation". 

But in practice, I think other things in Servo rely on having this reflow call happen at the end of `handle_msgs`, hence we get side-effects like lags in scrolling. 

So this means we can try to fix the problem by not only moving reflow to "update the rendering", but also doing an "update the rendering" at the end of `handle_msgs`(as opposed to only noting a rendering opp when the animation starts). 

Now "doing an update the rendering" could mean actually running the steps right then and there, or rather "noting a rendering opportunity", which sends a message(a task message) to the script-thread which will be handled at the next wake-up of `handle_msgs`. 

I think both are options, and in both cases, since we would be noting rendering opportunities or immediately running the steps at the end of each call to `handle_msgs`, we should remove all other noting of rendering opportunities since they would not be needed anymore(they would have by definition happened as part of a message handling earlier in the same `handle_msgs` call). 

At this point, I think we might as well call "update the rendering" right then and there at the end of `handle_msgs`, and remove the other noting of rendering opportunities, because it seems more simple to do without the extra message sending.

Now a final point is that some steps that are now part of updating the rendering, used to be done on their own but using a kind of prioritization mechanism at the start of `handle_msgs`, and I tried to maintain that with [`rendering_update_already_prioritized`](https://github.com/servo/servo/blob/24984ed9e2890d3f51ec6c5e32337c247b4eb020/components/script/script_thread.rs#L1719).

So perhaps instead of running the steps at the end of `handle_msgs`, we might need to do it at the beginning, and perhaps even once both at the beginning and at the end. This might seem inefficient, but I think it's ok because `handle_msgs` handles any number of message, so there a kind of batching going on already. Finding out the right solution requires some experimentation.

File: components/script/script_thread.rs [hunk 6]
```diff
@@ -2018,40 +1967,9 @@ impl ScriptThread {
...
-                // be driven by the compositor on an as-needed basis instead, to
-                // minimize unnecessary work.
-                window.reflow(
-                    ReflowGoal::Full,
-                    ReflowReason::MissingExplicitReflow,
-                    can_gc,
-                );
-            }
-        }
+        // If any message triggered a rendering opportunity, then update the rendering now.
```
Comment (gterzian) [inline components/script/script_thread.rs:1970]: I think the "if" is incorrect, rather we are always running these steps(unless there are animations running and we didn't receive a tick animation message).

File: components/script/script_thread.rs [hunk 7]
```diff
@@ -2018,40 +1967,9 @@ impl ScriptThread {
...
+        self.update_the_rendering(compositor_requested_update_the_rendering, can_gc);
+        self.perform_a_microtask_checkpoint(can_gc);
```
Comment (gterzian) [inline components/script/script_thread.rs:1972]: Note sure if it could be noticeable, but we should make this conditional on the `update_the_rendering` steps actually having run because this should only happen after a task(which running the steps are simulating here). Can be a TODO with a link to https://github.com/servo/servo/issues/32003 for now.

File: components/script/script_thread.rs [hunk 8]
```diff
@@ -1611,34 +1537,47 @@ impl ScriptThread {
...
+
+        // TODO: The specification says to filter out non-renderable documents,
+        // as well as those for which a rendering update would be unnecessary,
+        // but this isn't happening here.
+
+        // If we aren't explicitly running rAFs, this update wasn't requested by the compositor,
+        // and we are running animations, then wait until the compositor tells us it is time to
+        // update the rendering.
+        if !should_run_rafs && !requested_by_compositor && any_animations_running {
+            return;
```
Comment (gterzian) [inline components/script/script_thread.rs:1554]: Would it not be better to only filter out docs with running animations when this update wasn't requested by the compositor, and still update other docs?

**Review by gterzian — APPROVED** [review]
LGTM, with some questions and some comments.

I've noted some potential follow-ups at https://github.com/servo/servo/issues/31242#issuecomment-2527440407

> whether we actually need to run update the rendering in a task

We don't have to run it in a "task" in the sense of [`MainThreadScriptMsg::Common(CommonScriptMsg::Task`](https://github.com/servo/servo/blob/f5fdbd70d0706b71f2fbbf7990e95cea820f6eae/components/script/script_thread.rs#L2591), but as done in the PR I do think we should simulate a task-like environment and run the microtask checkpoints(because for a example a promise resolved in a raf callback should run before any other later tasks). Whether we should cancel the update of the rendering if the document for which it was initially schedules becomes inactive, like would happen if it was queued as a task, I am not sure.

File: components/script/script_thread.rs [hunk 9]
```diff
@@ -1611,34 +1537,47 @@ impl ScriptThread {
...
+            .any(|(_, document)| document.animations().running_animation_count() != 0);
+
+        // TODO: The specification says to filter out non-renderable documents,
+        // as well as those for which a rendering update would be unnecessary,
+        // but this isn't happening here.
+
+        // If we aren't explicitly running rAFs, this update wasn't requested by the compositor,
+        // and we are running animations, then wait until the compositor tells us it is time to
+        // update the rendering.
+        if !should_run_rafs && !requested_by_compositor && any_animations_running {
```
[the remark this answers is not in the document]
Comment (mrobinson) [reply components/script/script_thread.rs:1553]: Okay. I've done this.

File: components/script/script_thread.rs (hunk 6 above)
Comment (mrobinson) [reply components/script/script_thread.rs:1970]: You're right. I've updated this comment.

File: components/script/script_thread.rs (hunk 7 above)
Comment (mrobinson) [reply components/script/script_thread.rs:1972]: Okay. I've gone ahead and done that here.

File: components/script/script_thread.rs (hunk 8 above)
Comment (mrobinson) [reply components/script/script_thread.rs:1554]: I think that makes sense eventually, but we currently do not handle partial updates of the document tree very well. The main issue is that we don't have a complete picture of the tree so we don't know how to propagate updates correctly now as there may be missing iframes. This is why we end up having to update every single `Document` always.

Comment (gterzian) [reply components/script/script_thread.rs]: Ok, thanks for the info.
