### PR TITLE
script/dom: Remove unused creator-related methods from WindowProxy.

### LINKED ISSUE #41835: WindowProxy::has_creator_url is wrong
https://github.com/servo/servo/blob/1442e9fbc556aface888fca4c837d3486924aa4e/components/script/dom/windowproxy.rs#L435-L437

It should be checking `self.creator_url` instead of `self.creator_base_url`.

### PR DESCRIPTION
**Pull request by TimurBora**
Methods were unused and removed from the HTML spec.

Testing: Verified with ./mach build and ./mach test-unit. Without errors or warnings.
Fixes: #41835

### CODE REVIEW

File: components/script/dom/windowproxy.rs [hunk 1]
```diff
@@ -423,28 +423,10 @@ impl WindowProxy {
...
-        self.creator_base_url.is_some()
-    }
-
-    /// <https://html.spec.whatwg.org/multipage/#creator-url>
-    pub(crate) fn creator_url(&self) -> Option<ServoUrl> {
-        self.creator_url.clone()
-    }
-
     pub(crate) fn has_creator_url(&self) -> bool {
         self.creator_base_url.is_some()
```
Comment (Taym95) [inline components/script/dom/windowproxy.rs]: has_creator_url should be `self.creator_url.is_some()` or rename to `has_creator_base_url`

Comment (TimurBora) [reply components/script/dom/windowproxy.rs]: I searched for has_creator_url and it seems that it's unused, maybe just delete this function?

Comment (Taym95) [reply components/script/dom/windowproxy.rs]: Yes if not used just remove it

Comment (TimurBora) [reply components/script/dom/windowproxy.rs]: Okay, I removed this

Comment (TimurBora) [reply components/script/dom/windowproxy.rs]: Oh, I'm too quick, must to remove expect too

**Review by Taym95 — APPROVED** [review]
