### PR TITLE
script: Use InputEvent for input events

### LINKED ISSUE #36398: `input` Event Fired by Input Element has `Event` Interface Instead of `InputEvent` Interface
**Describe the bug:**

From [4.10.5.5 Common event behaviors](https://html.spec.whatwg.org/#common-input-element-events):

> When the [input](https://w3c.github.io/uievents/#event-type-input) and [change](https://html.spec.whatwg.org/#event-change) events [apply](https://html.spec.whatwg.org/#concept-input-apply) (which is the case for all [input](https://html.spec.whatwg.org/#the-input-element) controls other than [buttons](https://html.spec.whatwg.org/#concept-button) and those with the [type](https://html.spec.whatwg.org/#attr-input-type) attribute in the [Hidden](https://html.spec.whatwg.org/#hidden-state-(type=hidden)) state), the events are fired to indicate that the user has interacted with the control. The [input](https://w3c.github.io/uievents/#event-type-input) event fires whenever the user has modified the data of the control. The [change](https://html.spec.whatwg.org/#event-change) event fires when the value is committed, if that makes sense for the control, or else when the control [loses focus](https://html.spec.whatwg.org/#unfocus-causes-change-event). In all cases, the [input](https://w3c.github.io/uievents/#event-type-input) event comes before the corresponding [change](https://html.spec.whatwg.org/#event-change) event (if any).

But we are still using [Event](https://dom.spec.whatwg.org/#event) interface instead of [InputEvent](https://w3c.github.io/uievents/#inputevent). Therefore, several attributes is missing or has an unexpected value. 

**To Reproduce:**

For the given input element,
```html
<input style="width: 100px; background-color: aquamarine;" id="testInput">

<script>
    const input = document.getElementById('testInput');

    input.addEventListener('input', (event) => {
        console.log(event.composed);
        console.log(event.data);
        console.log(event.toString());
    });
</script>
```

Typing `a` inside the element yield the following.

| **Servo** | **Firefox** |
|----|-----|
|<pre>false<br/>undefined<br/>[object Event]</pre>     |  <pre>true<br/>a<br/>[object InputEvent]</pre> |

**Platform:**
Ubuntu 24.04 LTS

### PR DESCRIPTION
**Pull request by excitablesnowball**
Use `InputEvent` for text input and set appropriate values for the `composed`, `data`, `isComposing`, and `inputType` attributes. Use a placeholder for `dataTransfer` attribute and `getTargetRanges` function, as they are only applicable to contenteditable, which isn't implemented.

Testing: I added two tests under `tests/wpt/mozilla/tests/input-events` based on the similarly named ones for contenteditable under `tests/wpt/tests/input-events`.
Fixes: https://github.com/servo/servo/issues/36398

### CODE REVIEW

**Comment by excitablesnowball** [comment]
Rebased to fix merge conflict.

File: components/script/textinput.rs [hunk 1]
```diff
@@ -742,7 +821,7 @@ impl<T: ClipboardProvider> TextInput<T> {
             KeyReaction::TriggerDefaultAction
         } else {
             self.insert_char('\n');
-            KeyReaction::DispatchInput
+            KeyReaction::DispatchInput(None, IsComposing::NotComposing, InputType::InsertLineBreak)
```
Comment (jdm) [inline components/script/textinput.rs:825]: Why is the event's data null here?

File: components/script/textinput.rs [hunk 2]
```diff
@@ -1047,30 +1140,48 @@ impl<T: ClipboardProvider> TextInput<T> {
...
+                        Some(c.to_string()),
+                        IsComposing::NotComposing,
+                        InputType::InsertText,
+                    );
                 }
                 if matches!(key, Key::Named(NamedKey::Process)) {
-                    return KeyReaction::DispatchInput;
+                    return KeyReaction::DispatchInput(
+                        None,
+                        IsComposing::NotComposing,
```
Comment (jdm) [inline components/script/textinput.rs]: Since the Process key is part of using an IME, I think we this event to be composing here: `true if this event is dispatched during a [dead key](https://w3c.github.io/uievents/#keys-dead) sequence or while an [input method editor](https://w3c.github.io/uievents/#input-method-editor) is active (such that [composition events](https://w3c.github.io/uievents/#events-compositionevents) are being dispatched)`

File: components/script/textinput.rs [hunk 3]
```diff
@@ -1047,30 +1140,48 @@ impl<T: ClipboardProvider> TextInput<T> {
...
             })
             .unwrap()
     }
 
     pub(crate) fn handle_compositionend(&mut self, event: &CompositionEvent) -> KeyReaction {
-        self.insert_string(event.data().str());
-        KeyReaction::DispatchInput
+        let ch = event.data().str();
+        self.insert_string(ch.as_ref());
+        KeyReaction::DispatchInput(
```
Comment (jdm) [inline components/script/textinput.rs:1169]: Hmm, https://w3c.github.io/uievents/#events-composition-input-events says we shouldn't dispatch an input event after compositionend. Let's file a followup issue for that.

**Review by jdm — APPROVED** [review]
Sorry for the delay—this is really great work!

File: components/script/textinput.rs (hunk 1 above)
Comment (excitablesnowball) [reply components/script/textinput.rs:825]: I found it counterintuitive too, but https://w3c.github.io/input-events/#overview indicates null in this case. I confirmed it's also null in both Firefox and Chromium.

File: components/script/textinput.rs (hunk 2 above)
Comment (excitablesnowball) [reply components/script/textinput.rs]: Good catch. I'll update this.

File: components/script/textinput.rs (hunk 3 above)
Comment (jdm) [reply components/script/textinput.rs:1169]: https://github.com/servo/servo/issues/40509
