### PR TITLE
Use Heap instead of UnsafeCell in DOM reflectors

### LINKED ISSUE #15085: Promise rooting is not sound
The second commit in #15080 exposes a crash that involves a `TrustedPromise` value that has been garbage collected by the time we try to turn it into a stack root once more. The backtrace shows a nursery GC occurring, which means that our trace hooks don't get called. The promise object is nursery-allocated, I guess, which would explain why it's GCed during the minor collection.

### PR DESCRIPTION
**Pull request by jdm**
The previous `Reflector` implementation did not use post barriers, so we could crash when storing nursery objects in a `Reflector` structure that were later moved out of the nursery.

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15085
- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15118)

### CODE REVIEW

**Comment by Ms2ger** [comment]
I noticed that `trace_reflector` calls `CallUnbarrieredObjectTracer`; would that need to be changed as well?

**Comment by jdm** [comment]
You are correct. I have updated the code to account for that.

**Comment by Ms2ger** [comment]
I don't see anything wrong with this, but would feel more comfortable if you had someone from the SM GC side have a look too. (Feel free to take this as r+ either way.)

**Comment by jdm** [comment]
```
10:31 <jonco> jdm: this means you're using the equivalent of JS::Heap<> to store the reflector object right?
10:31 <jdm> jonco: yes
10:31 <jonco> jdm: that sounds good
```
@bors-servo: r=Ms2ger

**Comment by jonco3** [comment]
Using Heap is the right thing to do here.  I have minimal knowledge of rust, but this looks good to me.

File: components/script/dom/bindings/reflector.rs [hunk 1]
```diff
@@ -34,44 +33,41 @@ pub fn reflect_dom_object<T, U>(
...
+        assert!(!object.is_null());
+        self.object.set(object);
     }
 
     /// Return a pointer to the memory location at which the JS reflector
     /// object is stored. Used to root the reflector, as
     /// required by the JSAPI rooting APIs.
-    pub fn rootable(&self) -> *mut *mut JSObject {
-        self.object.get()
+    pub fn rootable(&self) -> &Heap<*mut JSObject> {
```
Comment (KiChjang) [inline components/script/dom/bindings/reflector.rs]: Should this be `&mut` instead?

Comment (jdm) [inline components/script/dom/bindings/reflector.rs]: I argue that we can discuss that separately, since the changes here achieve the same effect as previously existed.
