### PR TITLE
layout: Prevent DomRefCell::borrow from being used in layout code

### LINKED ISSUE #42962: TSAN: data race between DomRefCell::borrow_for_layout and Node::implemented_pseudo_element
**Describe the bug:**

It looks like a race when doing `self.rare_data.borrow()` in `implemented_pseudo_element()`, which internally does a write and races with `borrow_for_layout()` (read). 
Perhaps `borrow_for_layout()` should also be used in `implemented_pseudo_element`?

<details><summary>TSAN output</summary>

```
WARNING: ThreadSanitizer: data race (pid=94900)
  Write of size 8 at 0x7f8195995de0 by thread T68:                                                                                                                                                                                                                                                                  
    #0 script::dom::node::Node::implemented_pseudo_element::heaef34dc549e2d9f script.3ba971434b5f1a03-cgu.13 (servo+0x80b6a2e) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)                                                                                                                                  
    #1 _$LT$script..layout_dom..element..ServoLayoutElement$u20$as$u20$style..dom..TElement$GT$::inheritance_parent::hcc613a0c7daf7772 <null> (servo+0x80feb58) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #2 _$LT$script..layout_dom..element..ServoLayoutElement$u20$as$u20$style..dom..TElement$GT$::inheritance_parent::hcc613a0c7daf7772 <null> (servo+0x80feb58) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #3 style::sharing::checks::parents_allow_sharing::h4f905594a12d360c layout.4e1e7d2ff031ed0b-cgu.05 (servo+0x5bd6444) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #4 style::sharing::checks::parents_allow_sharing::h4f905594a12d360c layout.4e1e7d2ff031ed0b-cgu.05 (servo+0x5bd6444) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #5 style::sharing::StyleSharingCache$LT$E$GT$::test_candidate::hc85e5ce22a2330f0 layout.4e1e7d2ff031ed0b-cgu.02 (servo+0x5c1b59d) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #6 uluru::LRUCache$LT$T$C$_$GT$::lookup::hd166f1650c418f41 layout.4e1e7d2ff031ed0b-cgu.05 (servo+0x5bd7752) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #7 style::sharing::StyleSharingTarget$LT$E$GT$::share_style_if_possible::h51e2609cd74d9ec0 layout.4e1e7d2ff031ed0b-cgu.02 (servo+0x5c1dff6) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #8 style::traversal::compute_style::h484a5014a63131a6 layout.4e1e7d2ff031ed0b-cgu.15 (servo+0x5fcc20d) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #9 _$LT$layout..traversal..RecalcStyle$u20$as$u20$style..traversal..DomTraversal$LT$E$GT$$GT$::process_preorder::h117607e6f1ce1379 layout.4e1e7d2ff031ed0b-cgu.03 (servo+0x5c6f04d) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #10 style::parallel::style_trees::h2264691272ea704d layout.4e1e7d2ff031ed0b-cgu.11 (servo+0x5ea22f5) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #11 std::panicking::catch_unwind::do_call::h2396707920eeb933 layout.4e1e7d2ff031ed0b-cgu.11 (servo+0x5e83594) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #12 __rust_try layout.4e1e7d2ff031ed0b-cgu.11 (servo+0x5eb5915) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #13 _$LT$rayon_core..job..HeapJob$LT$BODY$GT$$u20$as$u20$rayon_core..job..Job$GT$::execute::h8d8f17b02c94933d layout.4e1e7d2ff031ed0b-cgu.11 (servo+0x5eab213) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #14 _$LT$rayon_core..job..JobFifo$u20$as$u20$rayon_core..job..Job$GT$::execute::ha0371ad0a6fa159b <null> (servo+0xddaa2aa) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #15 rayon_core::registry::WorkerThread::wait_until_cold::h18cb7425c58752f1 <null> (servo+0xdd96259) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #16 rayon_core::registry::ThreadBuilder::run::hbab89a606676fdeb <null> (servo+0xdd97313) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #17 std::sys::backtrace::__rust_begin_short_backtrace::h6dd98904b7f85572 <null> (servo+0xd9ee9e3) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #18 std::panicking::catch_unwind::do_call::hbd50cb1d5daede97 style.b3d83ac50c946e06-cgu.08 (servo+0xd9eeb20) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #19 __rust_try style.b3d83ac50c946e06-cgu.08 (servo+0xda47da5) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #20 core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h1e971a4b1f8e6359 style.b3d83ac50c946e06-cgu.08 (servo+0xd9ef822) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #21 _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::h92b5e89db84291cd std.ecc95164bc41e8c8-cgu.15 (servo+0xe4ee1db) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #22 std::sys::thread::unix::Thread::new::thread_start::hcca98f01e2303f61 std.ecc95164bc41e8c8-cgu.13 (servo+0xe4d143a) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)

  Previous read of size 8 at 0x7f8195995de0 by thread T67:
    #0 script::dom::bindings::cell::DomRefCell$LT$T$GT$::borrow_for_layout::he9f6fe52ab8a51be script.3ba971434b5f1a03-cgu.06 (servo+0x6e830af) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)                                                                                                                  
    #1 _$LT$script..layout_dom..node..ServoLayoutNode$u20$as$u20$style..dom..TNode$GT$::traversal_parent::h361f244861f8b7b1 <null> (servo+0x80f88ec) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #2 _$LT$script..layout_dom..element..ServoLayoutElement$u20$as$u20$style..dom..TElement$GT$::traversal_parent::h786f51ab5c07035c <null> (servo+0x80fe869) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #3 style::traversal::compute_style::h484a5014a63131a6 layout.4e1e7d2ff031ed0b-cgu.15 (servo+0x5fcbcc7) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #4 _$LT$layout..traversal..RecalcStyle$u20$as$u20$style..traversal..DomTraversal$LT$E$GT$$GT$::process_preorder::h117607e6f1ce1379 layout.4e1e7d2ff031ed0b-cgu.03 (servo+0x5c6f04d) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #5 style::parallel::style_trees::h2264691272ea704d layout.4e1e7d2ff031ed0b-cgu.11 (servo+0x5ea22f5) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #6 std::panicking::catch_unwind::do_call::h2396707920eeb933 layout.4e1e7d2ff031ed0b-cgu.11 (servo+0x5e83594) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #7 __rust_try layout.4e1e7d2ff031ed0b-cgu.11 (servo+0x5eb5915) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #8 _$LT$rayon_core..job..HeapJob$LT$BODY$GT$$u20$as$u20$rayon_core..job..Job$GT$::execute::h8d8f17b02c94933d layout.4e1e7d2ff031ed0b-cgu.11 (servo+0x5eab213) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #9 _$LT$rayon_core..job..JobFifo$u20$as$u20$rayon_core..job..Job$GT$::execute::ha0371ad0a6fa159b <null> (servo+0xddaa2aa) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #10 rayon_core::registry::WorkerThread::wait_until_cold::h18cb7425c58752f1 <null> (servo+0xdd9648a) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #11 rayon_core::registry::ThreadBuilder::run::hbab89a606676fdeb <null> (servo+0xdd97313) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #12 std::sys::backtrace::__rust_begin_short_backtrace::h6dd98904b7f85572 <null> (servo+0xd9ee9e3) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #13 std::panicking::catch_unwind::do_call::hbd50cb1d5daede97 style.b3d83ac50c946e06-cgu.08 (servo+0xd9eeb20) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #14 __rust_try style.b3d83ac50c946e06-cgu.08 (servo+0xda47da5) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #15 core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h1e971a4b1f8e6359 style.b3d83ac50c946e06-cgu.08 (servo+0xd9ef822) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #16 _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::h92b5e89db84291cd std.ecc95164bc41e8c8-cgu.15 (servo+0xe4ee1db) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #17 std::sys::thread::unix::Thread::new::thread_start::hcca98f01e2303f61 std.ecc95164bc41e8c8-cgu.13 (servo+0xe4d143a) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)

  Thread T68 'StyleThread#2' (tid=94980, running) created by thread T55 at:
    #0 pthread_create <null> (servo+0x3d039ea) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)                                                                                                                                                                                                                  
    #1 std::sys::thread::unix::Thread::new::h9e6796ae0d9eac64 <null> (servo+0xe4d1939) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #2 style::global_style_data::thread_spawn::h3a32ccfc479ee55a <null> (servo+0xda17cc8) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #3 rayon_core::registry::Registry::new::h68c89ff9f91a3de2 style.b3d83ac50c946e06-cgu.08 (servo+0xd9d8045) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #4 rayon_core::thread_pool::ThreadPool::build::h6e89a9bdbc945f5c style.b3d83ac50c946e06-cgu.15 (servo+0xdcea387) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #5 core::ops::function::FnOnce::call_once::h593388b9f440ef0b style.b3d83ac50c946e06-cgu.08 (servo+0xd9effb9) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #6 std::sync::poison::once::Once::call_once_force::_$u7b$$u7b$closure$u7d$$u7d$::h029b48621b8ccabb layout.4e1e7d2ff031ed0b-cgu.05 (servo+0x5bb52db) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #7 std::sys::sync::once::futex::Once::call::h66248e2a938d6e81 <null> (servo+0xe4ad6b2) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #8 _$LT$layout..layout_impl..LayoutThread$u20$as$u20$layout_api..Layout$GT$::reflow::hf253d8b625f2a277 <null> (servo+0x5bf07d5) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #9 script::dom::window::Window::reflow::h6a48d9f774bddd5e script.3ba971434b5f1a03-cgu.13 (servo+0x80d5b17) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #10 script::dom::document::Document::update_the_rendering::haefa9a86e88d3b26 script.3ba971434b5f1a03-cgu.08 (servo+0x7480cce) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #11 script::dom::window::Window::allow_layout_if_necessary::h46ac9ca754672880 script.3ba971434b5f1a03-cgu.13 (servo+0x80cccc5) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #12 script::dom::document::Document::finish_load::h26e6e6f772520f74 script.3ba971434b5f1a03-cgu.08 (servo+0x74732cc) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #13 script::dom::servoparser::ServoParser::parse_sync::hcf922ad8cd542d27 (.llvm.8586235623097226802) script.3ba971434b5f1a03-cgu.15 (servo+0x8554c87) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #14 _$LT$script..dom..servoparser..ParserContext$u20$as$u20$script..network_listener..FetchResponseListener$GT$::process_response_eof::hb8e0de426bc423d7 <null> (servo+0x8456a16) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #15 script::script_thread::ScriptThread::pre_page_load::h3e317613efaaa619 script.3ba971434b5f1a03-cgu.12 (servo+0x7e2c69b) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #16 script::script_thread::ScriptThread::spawn_pipeline::h586b5172482c17e2 script.3ba971434b5f1a03-cgu.12 (servo+0x7e2d27c) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #17 script::script_thread::ScriptThread::handle_msgs::hd03914cbb0647650 script.3ba971434b5f1a03-cgu.12 (servo+0x7e2679c) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #18 script::script_thread::ScriptThread::start::h7b14880509fef892 script.3ba971434b5f1a03-cgu.12 (servo+0x7e4fa5a) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #19 profile_traits::mem::ProfilerChan::run_with_memory_reporting::ha032bd28c04b6a71 script.3ba971434b5f1a03-cgu.01 (servo+0x61a1bd1) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #20 std::sys::backtrace::__rust_begin_short_backtrace::h148816ca88827874 <null> (servo+0x69afb19) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #21 std::panicking::catch_unwind::do_call::h10454d5138df6568 script.3ba971434b5f1a03-cgu.04 (servo+0x69b67e7) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #22 __rust_try script.3ba971434b5f1a03-cgu.04 (servo+0x6ad2f15) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #23 core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h927eeb954f4683c6 script.3ba971434b5f1a03-cgu.04 (servo+0x69d0002) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #24 _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::h92b5e89db84291cd std.ecc95164bc41e8c8-cgu.15 (servo+0xe4ee1db) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #25 std::sys::thread::unix::Thread::new::thread_start::hcca98f01e2303f61 std.ecc95164bc41e8c8-cgu.13 (servo+0xe4d143a) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)

  Thread T67 'StyleThread#1' (tid=94979, running) created by thread T55 at:
    #0 pthread_create <null> (servo+0x3d039ea) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)                                                                                                                                                                                                                  
    #1 std::sys::thread::unix::Thread::new::h9e6796ae0d9eac64 <null> (servo+0xe4d1939) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #2 style::global_style_data::thread_spawn::h3a32ccfc479ee55a <null> (servo+0xda17cc8) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #3 rayon_core::registry::Registry::new::h68c89ff9f91a3de2 style.b3d83ac50c946e06-cgu.08 (servo+0xd9d8045) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #4 rayon_core::thread_pool::ThreadPool::build::h6e89a9bdbc945f5c style.b3d83ac50c946e06-cgu.15 (servo+0xdcea387) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #5 core::ops::function::FnOnce::call_once::h593388b9f440ef0b style.b3d83ac50c946e06-cgu.08 (servo+0xd9effb9) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #6 std::sync::poison::once::Once::call_once_force::_$u7b$$u7b$closure$u7d$$u7d$::h029b48621b8ccabb layout.4e1e7d2ff031ed0b-cgu.05 (servo+0x5bb52db) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #7 std::sys::sync::once::futex::Once::call::h66248e2a938d6e81 <null> (servo+0xe4ad6b2) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #8 _$LT$layout..layout_impl..LayoutThread$u20$as$u20$layout_api..Layout$GT$::reflow::hf253d8b625f2a277 <null> (servo+0x5bf07d5) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #9 script::dom::window::Window::reflow::h6a48d9f774bddd5e script.3ba971434b5f1a03-cgu.13 (servo+0x80d5b17) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #10 script::dom::document::Document::update_the_rendering::haefa9a86e88d3b26 script.3ba971434b5f1a03-cgu.08 (servo+0x7480cce) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #11 script::dom::window::Window::allow_layout_if_necessary::h46ac9ca754672880 script.3ba971434b5f1a03-cgu.13 (servo+0x80cccc5) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #12 script::dom::document::Document::finish_load::h26e6e6f772520f74 script.3ba971434b5f1a03-cgu.08 (servo+0x74732cc) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #13 script::dom::servoparser::ServoParser::parse_sync::hcf922ad8cd542d27 (.llvm.8586235623097226802) script.3ba971434b5f1a03-cgu.15 (servo+0x8554c87) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #14 _$LT$script..dom..servoparser..ParserContext$u20$as$u20$script..network_listener..FetchResponseListener$GT$::process_response_eof::hb8e0de426bc423d7 <null> (servo+0x8456a16) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #15 script::script_thread::ScriptThread::pre_page_load::h3e317613efaaa619 script.3ba971434b5f1a03-cgu.12 (servo+0x7e2c69b) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #16 script::script_thread::ScriptThread::spawn_pipeline::h586b5172482c17e2 script.3ba971434b5f1a03-cgu.12 (servo+0x7e2d27c) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #17 script::script_thread::ScriptThread::handle_msgs::hd03914cbb0647650 script.3ba971434b5f1a03-cgu.12 (servo+0x7e2679c) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #18 script::script_thread::ScriptThread::start::h7b14880509fef892 script.3ba971434b5f1a03-cgu.12 (servo+0x7e4fa5a) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #19 profile_traits::mem::ProfilerChan::run_with_memory_reporting::ha032bd28c04b6a71 script.3ba971434b5f1a03-cgu.01 (servo+0x61a1bd1) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #20 std::sys::backtrace::__rust_begin_short_backtrace::h148816ca88827874 <null> (servo+0x69afb19) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #21 std::panicking::catch_unwind::do_call::h10454d5138df6568 script.3ba971434b5f1a03-cgu.04 (servo+0x69b67e7) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #22 __rust_try script.3ba971434b5f1a03-cgu.04 (servo+0x6ad2f15) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #23 core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h927eeb954f4683c6 script.3ba971434b5f1a03-cgu.04 (servo+0x69d0002) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #24 _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::h92b5e89db84291cd std.ecc95164bc41e8c8-cgu.15 (servo+0xe4ee1db) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)
    #25 std::sys::thread::unix::Thread::new::thread_start::hcca98f01e2303f61 std.ecc95164bc41e8c8-cgu.13 (servo+0xe4d143a) (BuildId: 3f9859618bbb40bff505052c58cc3d753b8d83b3)

SUMMARY: ThreadSanitizer: data race script.3ba971434b5f1a03-cgu.13 in script::dom::node::Node::implemented_pseudo_element::heaef34dc549e2d9f
```

</details>

**To Reproduce:**
I used the following TSAN suppressions on linux (to exclude other known races):

```
race:libgallium-25.3.5.so
race:libvulkan_nouveau.so
race:lang_find_or_insert
race:apply_selector_flags
```

```
 export TSAN_OPTIONS="suppressions=$HOME/Dev/servo/etc/tsan_supressions.txt"
./mach build --release --with-tsan
./mach run --release --with-tsan
```

This occurred when loading servo.org/blog., 

**Platform:**
Linux Fedora.

### PR DESCRIPTION
**Pull request by jdm**
DomRefCell::borrow inside of layout code is risky because it leads to memory races if the code is ever called from layout worker threads. This can be caught via TSAN, but we can also catch it deterministically in CI by using our existing thread state debug assertions correctly.

Testing: Existing WPT test coverage is sufficient.
Fixes: #42962

### CODE REVIEW

**Comment by jdm** [comment]
Try run: https://github.com/servo/servo/actions/runs/22609386406

**Comment by jdm** [comment]
I recommend reading this PR with whitespace changes turned off.

**Comment by jdm** [comment]
We could catch problems like #42963 as well by introducing a similar DomCell type.

File: components/script/dom/bindings/cell.rs
Comment (mukilan) [inline components/script/dom/bindings/cell.rs:112]: Perhaps we can add `Panics if this is called from anywhere other than the script thread` to match the documentation of `borrow_for_layout` . Also maybe we can provide a hint to use to `borrow_for_layout` i.e "Use `borrow_for_layout` if the borrowed data might used during layout"

File: components/layout/layout_impl.rs [hunk 1]
```diff
@@ -222,6 +223,28 @@ impl LayoutFactory for LayoutFactoryImpl {
...
+}
+
+impl Drop for ThreadStateRestorer {
+    fn drop(&mut self) {
+        thread_state::exit(ThreadState::LAYOUT);
+        thread_state::enter(ThreadState::SCRIPT);
+    }
+}
+
+fn with_layout_state<R>(f: impl FnOnce() -> R) -> R {
```
Comment (mukilan) [inline components/layout/layout_impl.rs:254]: Maybe we can add some documentation here about when to use `with_layout_state`. Also, since we can still miss the cases where layout workers call `DomRefCell::borrow()` without entering the correct state using this method, I wonder if we can add documentation somewhere to teach new authors to use this idiom.

**Review by mukilan — APPROVED** [review]
Nice!

File: components/layout/layout_impl.rs [hunk 2]
```diff
@@ -222,6 +223,28 @@ impl LayoutFactory for LayoutFactoryImpl {
     }
 }
 
+struct ThreadStateRestorer;
+
+impl ThreadStateRestorer {
+    fn new() -> Self {
+        thread_state::exit(ThreadState::SCRIPT);
+        thread_state::enter(ThreadState::LAYOUT);
+        Self
```
Comment (jschwe) [inline components/layout/layout_impl.rs:235]: Is this costly (e.g. TLS access)? Could we guard the implementation behind `cfg(debug_assertions)`?

File: components/script/dom/node.rs [hunk 3]
```diff
@@ -2112,8 +2112,15 @@ impl<'dom> LayoutNodeHelpers<'dom> for LayoutDom<'dom, Node> {
         unsafe { OpaqueNode(self.get_jsobject() as usize) }
     }
 
+    #[expect(unsafe_code)]
     fn implemented_pseudo_element(&self) -> Option<PseudoElement> {
-        self.unsafe_get().implemented_pseudo_element()
+        unsafe {
+            self.unsafe_get()
```
Comment (jschwe) [inline components/script/dom/node.rs:2118]: Unrelated to this PR, but why is `unsafe_get` a safe function?

Comment (jdm) [reply components/script/dom/node.rs:2118]: I don't have a good answer for why the unsafe is in the name instead of in the type system. I think we could potentially rename it to something more clear, but it's meant to represent that it should only be called by code that is implementing the LayoutWhateverHelpers traits, since it exposes methods that could be unsafe to call in layout's worker threads.

File: components/layout/layout_impl.rs (hunk 2 above)
Comment (jdm) [reply components/layout/layout_impl.rs:235]: Yes.

**Comment by jdm** [comment]
@simonwuelker Do you have a preference for merging this change or #42991 first?

**Comment by simonwuelker** [comment]
Let's merge this one first.

**Comment by jdm** [comment]
Womp womp!
```
  │ assertion failed: thread_state::get().is_script() (thread StyleThread#1, at components/script_bindings/root.rs:450)
  │    0: servoshell::backtrace::print
  │    1: servoshell::panic_hook::panic_hook
  │    2: std::panicking::panic_with_hook
  │    3: std::panicking::panic_handler::{{closure}}
  │    4: std::sys::backtrace::__rust_end_short_backtrace
  │    5: __rustc::rust_begin_unwind
  │    6: core::panicking::panic_fmt
  │    7: core::panicking::panic
  │    8: script_bindings::root::assert_in_script
  │    9: <script::dom::bindings::root::LayoutDom<script::dom::element::Element> as script::dom::element::LayoutElementHelpers>::each_custom_state_for_layout
  │   10: <script::layout_dom::element::ServoLayoutElement as selectors::tree::Element>::match_non_ts_pseudo_class
  │   11: selectors::matching::matches_simple_selector
  │   12: selectors::matching::matches_complex_selector_internal
  │   13: style::selector_map::SelectorMap<style::stylist::Rule>::get_matching_rules
  │   14: style::selector_map::SelectorMap<style::stylist::Rule>::get_all_matching_rules
  │   15: style::rule_collector::RuleCollector<E>::collect_stylist_rules
  │   16: style::rule_collector::RuleCollector<E>::collect_all
  │   17: style::stylist::Stylist::push_applicable_declarations
  │   18: style::style_resolver::StyleResolverForElement<E>::match_primary
  │   19: style::style_resolver::StyleResolverForElement<E>::resolve_primary_style
  │   20: style::style_resolver::StyleResolverForElement<E>::resolve_style
  │   21: style::style_resolver::StyleResolverForElement<E>::resolve_style_with_default_parents
  │   22: style::traversal::compute_style
  │   23: <layout::traversal::RecalcStyle as style::traversal::DomTraversal<E>>::process_preorder
  │   24: style::parallel::style_trees
  │   25: style::driver::traverse_dom::{{closure}}
  │   26: rayon_core::scope::ScopeBase::execute_job_closure
  │   27: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
  │   28: rayon_core::registry::WorkerThread::wait_until_cold
  │   29: rayon_core::registry::ThreadBuilder::run
  │   30: std::sys::backtrace::__rust_begin_short_backtrace
  │   31: core::ops::function::FnOnce::call_once{{vtable.shim}}
  │   32: std::sys::thread::unix::Thread::new::thread_start
  │   33: <unknown>
  └   34: <unknown>
```
https://github.com/servo/servo/blob/45f1bdbf41d70529496d32635f34b4a49eb44c50/components/script/dom/element.rs#L1540-L1541
https://github.com/servo/servo/blob/45f1bdbf41d70529496d32635f34b4a49eb44c50/components/script/dom/element.rs#L352-L354

**Comment by jdm** [comment]
```
 │ assertion failed: thread_state::get().is_script() (thread StyleThread#1, at components/script_bindings/root.rs:450)
  │    0: servoshell::backtrace::print
  │    1: servoshell::panic_hook::panic_hook
  │    2: std::panicking::panic_with_hook
  │    3: std::panicking::panic_handler::{{closure}}
  │    4: std::sys::backtrace::__rust_end_short_backtrace
  │    5: __rustc::rust_begin_unwind
  │    6: core::panicking::panic_fmt
  │    7: core::panicking::panic
  │    8: script_bindings::root::assert_in_script
  │    9: <script::layout_dom::element::ServoLayoutElement as selectors::tree::Element>::has_custom_state
  │   10: selectors::matching::matches_simple_selector
  │   11: selectors::matching::matches_complex_selector_internal
  │   12: style::selector_map::SelectorMap<style::stylist::Rule>::get_matching_rules
  │   13: style::selector_map::SelectorMap<style::stylist::Rule>::get_all_matching_rules
  │   14: style::rule_collector::RuleCollector<E>::collect_stylist_rules
  │   15: style::rule_collector::RuleCollector<E>::collect_all
  │   16: style::stylist::Stylist::push_applicable_declarations
  │   17: style::style_resolver::StyleResolverForElement<E>::match_primary
  │   18: style::style_resolver::StyleResolverForElement<E>::resolve_primary_style
  │   19: style::style_resolver::StyleResolverForElement<E>::resolve_style
  │   20: style::style_resolver::StyleResolverForElement<E>::resolve_style_with_default_parents
  │   21: style::traversal::compute_style
  │   22: style::parallel::style_trees
  │   23: style::driver::traverse_dom::{{closure}}
  │   24: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
  │   25: rayon_core::registry::WorkerThread::wait_until_cold
  │   26: rayon_core::registry::ThreadBuilder::run
  │   27: std::sys::backtrace::__rust_begin_short_backtrace
  │   28: core::ops::function::FnOnce::call_once{{vtable.shim}}
  │   29: std::sys::thread::unix::Thread::new::thread_start
  │   30: <unknown>
  └   31: <unknown>
```
https://github.com/servo/servo/blob/45f1bdbf41d70529496d32635f34b4a49eb44c50/components/script/dom/element.rs#L5110-L5112
We need to call `self.each_custom_state_for_layout` from that code instead.
