### PR TITLE
layout: Place statically positioned absolutes in IFCs at their hypothetical box position

### LINKED ISSUE #19879: Icons rotate incorrectly
URL: http://hn.premii.com/#

The `bubble` icons don't rotate correctly in Servo.

image

Note: Servo is built with bc7dd644f6

Tested in `macOS 10.12.6`

### PR DESCRIPTION
**Pull request by mrobinson**
Absolutes need to be placed at their hypothetical position as if the
`position` value was static. This position differs based on the value they
had before blockification. The code for placing absolutes was taking
into account the original display for the inline value, but not for the
block value. A static `display: block` box would placed at a new block
position past the end of the linebox.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #19879.
- [x] There are tests for these changes

### CODE REVIEW

File: components/layout_2020/dom_traversal.rs [hunk 1]
```diff
@@ -89,6 +89,7 @@ where
     }
 }
 
+#[derive(Debug)]
```
Comment (mrobinson) [inline components/layout_2020/dom_traversal.rs:92]: I've also added `Debug` support to some classes which should help to debug these issues in the future.

File: components/layout_2020/flow/line.rs [hunk 2]
```diff
@@ -523,31 +522,34 @@ impl AbsolutelyPositionedLineItem {
...
-            },
-            Display::Contents => {
-                panic!("display:contents does not generate an abspos box")
-            },
-            Display::None => {
-                panic!("display:none does not generate an abspos box")
-            },
-        };
+            } else {
+                // After the bottom of the line at the start of the inline formatting context.
```
Comment (Loirooriol) [inline components/layout_2020/flow/line.rs:546]: I was thinking whether it could appear at a different position, e.g. if there is a float and the abspos would establish an independent formatting context even with `position: static`, or if it has `clear: both`.
But other browsers don't seem to do this, so looks good.

**Review by Loirooriol — APPROVED** [review]
