### PR TITLE
Register iframes with the devtools

### LINKED ISSUE #34816: Creating a worker inside <iframe> panics when devtools are enabled
To reproduce:

`./mach run https://rateyourmusic.com --pref dom.shadowdom.enabled --devtools=6080`

Related to / Part of #34320

```
assertion failed: pipelines.get(&pipeline).is_some() (thread Devtools, at components/devtools/lib.rs:298)
error loading script blob:https://challenges.cloudflare.com/426d79a3-1b66-4e17-b67f-816c27e4f57c
   0: servoshell::backtrace::print
             at /home/alaska/servo/ports/servoshell/backtrace.rs:18:5
   1: servoshell::panic_hook::panic_hook
             at /home/alaska/servo/ports/servoshell/panic_hook.rs:40:17
   2: core::ops::function::Fn::call
             at /home/alaska/.rustup/toolchains/1.83.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79:5
   3: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/alloc/src/boxed.rs:2468:9
      std::panicking::rust_panic_with_hook
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:809:13
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:667:13
   5: std::sys::backtrace::__rust_end_short_backtrace
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/sys/backtrace.rs:170:18
   6: rust_begin_unwind
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   7: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   8: core::panicking::panic
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:148:5
   9: devtools::run_server::handle_new_global
             at /home/alaska/servo/components/devtools/lib.rs:298:13
  10: devtools::run_server
             at /home/alaska/servo/components/devtools/lib.rs:648:19
  11: devtools::start_server::{{closure}}
             at /home/alaska/servo/components/devtools/lib.rs:131:28
  12: std::sys::backtrace::__rust_begin_short_backtrace
             at /home/alaska/.rustup/toolchains/1.83.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:154:18
  13: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /home/alaska/.rustup/toolchains/1.83.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:538:17
  14: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/alaska/.rustup/toolchains/1.83.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
  15: std::panicking::try::do_call
             at /home/alaska/.rustup/toolchains/1.83.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:557:40
  16: __rust_try
  17: std::panicking::try
             at /home/alaska/.rustup/toolchains/1.83.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:520:19
      std::panic::catch_unwind
             at /home/alaska/.rustup/toolchains/1.83.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:358:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /home/alaska/.rustup/toolchains/1.83.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:537:30
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /home/alaska/.rustup/toolchains/1.83.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/alloc/src/boxed.rs:2454:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/alloc/src/boxed.rs:2454:9
      std::sys::pal::unix::thread::Thread::new::thread_start
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/sys/pal/unix/thread.rs:105:17
  20: start_thread
  21: __GI___clone3
```

### PR DESCRIPTION
**Pull request by simonwuelker**
Previously, the devtools didn't know about<iframe>s. 
They either ignored messages coming from iframes or crashed.

This reverts https://github.com/servo/servo/pull/34032 and then filters out non-tab globals in the "listTabs" message to the root actor to ensure that iframes and workers don't show up in the devtools tab list.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #34816
- [X] These changes do not require tests because we don't have devtools tests

### CODE REVIEW

File: components/shared/devtools/lib.rs [hunk 1]
```diff
@@ -84,6 +84,7 @@ pub enum ScriptToDevtoolsControlMsg {
         (BrowsingContextId, PipelineId, Option<WorkerId>),
         IpcSender<DevtoolScriptControlMsg>,
         DevtoolsPageInfo,
+        bool, // is_top_level_global
```
Comment (jdm) [inline components/shared/devtools/lib.rs:87]: Let's make this a field of DevtoolsPageInfo.

**Review by jdm — APPROVED** [review]
