### PR TITLE
RadioNodeList liveness

### LINKED ISSUE #25415: RadioNodeList should be a live view
The concept of a live NodeList appears in several places, much like the concept of a live HTMLCollection. Currently, the only kind of live NodeList we have is for a ParentNode's children. Three other cases need a live one: the labels of a labelable element (issue #25391), the result of Document.getElementsByName (issue #25147), and RadioNodeList. [querySelectorAll and MutationRecord have NodeLists but are not meant to be live]

https://html.spec.whatwg.org/multipage/forms.html#dom-form-nameditem step 1 and https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#dom-htmlformcontrolscollection-nameditem step 4 are the two places where a RadioNodeList can be created; both specify that it's live, so RadioNodeList should always be live.

The two specifications for what the RadioNodeList exposes do not seem identical at first glance, and the implementation might need two different states to cover them both:
"all the listed [form-associated] elements, whose form owner is the form element, that have either an id attribute or a name attribute equal to name, with the exception of input elements whose type attribute is in the Image Button state, in tree order."
" a live view of the HTMLFormControlsCollection object, further filtered so that the only nodes in the RadioNodeList object are those that have either an id attribute or a name attribute equal to name. The nodes in the RadioNodeList object must be sorted in tree order."

### PR DESCRIPTION
**Pull request by pshaughn**
When the named getter of a form's .elements gets a list, that list is now a live view into the form, passing a WPT test that removes a node and then looks at the list again.

---

- [X] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [X] These changes fix #25415 (GitHub issue number if applicable)

- [X] There are tests for these changes

### CODE REVIEW

**Comment by pshaughn** [comment]
There are still more test failures than I'd expect. It might be better to leave this one unmerged until I've looked into them more.

**Comment by KiChjang** [comment]
Just making sure, is there any overlap between this PR and #22264?

**Comment by pshaughn** [comment]
I was unaware of #22264, @KiChjang. I've been treating the different subcases of live NodeLists as different problems and have been working on them in this, #25424, and #25428. It looks like I've been following a very different strategy from you, and #25424 passes some tests that #22264 doesn't.

I understand that you might feel you have priority on this and that I should step away from it to let you keep working on your version. If you do feel that way, let me know and I'll back off; I didn't intend to invalidate anyone else's work.

**Comment by pshaughn** [comment]
Related issues that this change from static to live doesn't solve: #25429 (an element is staying gettable too long because it's not leaving the past names map), #21495 (an element with a `form=` attribute that appears earlier on the page than the form with that ID isn't getting into form.controls), #12978 (named getter can't get an element named addEventListener), #25036 (getOwnPropertyDescriptor doesn't find an element even when the named getter does)

**Comment by pshaughn** [comment]
It occurs to me that, since this is always looking at form.controls and the past names map and never at the DOM tree directly, it could be optimized with a cursor like #22264 without even needing a mutation observer. It would just need to invalidate or repair the cursor on every code path that changes form.controls or the past names map.

**Comment by pshaughn** [comment]
This push fixes the one bug I had that is within the purview of the list-getting itself (I wasn't excluding input type=image on the check that had to exclude it); it does not take into account the idea of using a cursor for performance.

File: components/script/dom/nodelist.rs [hunk 1]
```diff
@@ -100,20 +105,22 @@ impl NodeList {
...
         } else {
-            panic!("called as_simple_list() on a children node list")
+            panic!("called as_radio_list() on a non-radio node list")
         }
     }
 
     pub fn iter<'a>(&'a self) -> impl Iterator<Item = DomRoot<Node>> + 'a {
         let len = self.Length();
+        // There is room for optimization here in non-simple cases,
+        // as calling Item repeatedly on a live list can involve redundant work.
```
Comment (Manishearth) [inline components/script/dom/nodelist.rs]: File a followup for this?

File: components/script/dom/htmlformelement.rs [hunk 2]
```diff
@@ -265,43 +330,23 @@ impl HTMLFormElementMethods for HTMLFormElement {
...
-                        (child.has_attribute(&local_name!("name")) &&
-                            child.get_string_attribute(&local_name!("name")) == name)
-                    {
-                        candidates.push(DomRoot::from_ref(&*child.upcast::<Node>()));
-                    }
-                }
-            }
+        if candidates_length == 0 {
+            candidates = RadioNodeList::new_images(&window, self, name.clone());
+            candidates_length = candidates.Length();
```
Comment (Manishearth) [inline components/script/dom/htmlformelement.rs]: we could use a separate function that just returns if there are zero, 1, or more (returning the element if it's one)

**Review by Manishearth — APPROVED** [review]
We should probably have a followup filed to move everything to mutation observers

**Review by Manishearth — APPROVED** [review]
We should probably have a followup filed to move everything to mutation observers
