### PR TITLE
Fix missing settings in script module requests

### LINKED ISSUE #36592: Script module requests are missing several settings
https://github.com/servo/servo/blob/5e2d42e94459af76c8752fef934a7dde8ac5b41a/components/script/script_module.rs#L1756

It's missing these settings: https://github.com/servo/servo/blob/5e2d42e94459af76c8752fef934a7dde8ac5b41a/components/script/fetch.rs#L414-L416

### PR DESCRIPTION
**Pull request by elomscansio**
This PR resolves [#36592](https://github.com/servo/servo/issues/36592) by updating the `RequestBuilder` used in `script_module.rs` to include:
- `insecure_requests_policy`
- `has_trustworthy_ancestor_origin`
- `policy_container`

These fields are critical for enforcing proper fetch behavior under modern web security models, and were previously omitted from module script requests.

This change ensures that scripts loaded via `<script type="module">` or dynamic `import()` correctly reflect the calling document’s security environment.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #36592

- [X] There are tests for these changes

### CODE REVIEW

File: components/script/script_module.rs [hunk 1]
```diff
@@ -1760,7 +1760,12 @@ fn fetch_single_module_script(
         .integrity_metadata(options.integrity_metadata.clone())
         .credentials_mode(options.credentials_mode)
         .referrer_policy(options.referrer_policy)
-        .mode(mode);
+        .mode(mode)
+        .insecure_requests_policy(document.clone().unwrap().insecure_requests_policy())
```
Comment (elomscansio) [inline components/script/script_module.rs:1764]: i thought of adding the settings fields in ScriptFetchOptions but that won't conform with https://html.spec.whatwg.org/multipage/webappapis.html#script-fetch-options

Comment (jdm) [inline components/script/script_module.rs:1764]: We should use the policy container of the global scope here instead of the document, since we don't always have a document (which is why the unwrap was necessary).

Comment (elomscansio) [reply components/script/script_module.rs]: done

**Comment by elomscansio** [comment]
the failing test is a lot

**Comment by jdm** [comment]
Oh, this is super interesting! By including the policy container, we now cause the Content-Security-Policy directives in these tests to be applied like they are supposed to ([like this one](https://github.com/servo/servo/blob/c792e6db7c3f72b5294a2041311d71aab207357d/tests/wpt/tests/html/semantics/scripting-1/the-script-element/module/dynamic-import/propagate-nonce-inline-classic.html#L2)). Since we don't implement the `nonce` feature yet ([example](https://github.com/servo/servo/blob/ffccc5c88b8d47efc777b0bc9d2620bed4bc84d7/components/script/dom/htmlscriptelement.rs#L697) and [example #2](https://github.com/servo/servo/blob/ffccc5c88b8d47efc777b0bc9d2620bed4bc84d7/components/script/dom/htmlscriptelement.rs#L718)), the tests now fail in a more correct way. We should update the expected test results to reflect the new results from these changes.

**Comment by elomscansio** [comment]
I updated just two that i can find maybe there is others

**Comment by jdm** [comment]
Yes, all six tests from "Stable unexpected results." I recommend running each test with `./mach test-wpt path/to/test.html --headless --log-raw wpt.log` then running `./mach update-wpt wpt.log` before running the next test. That will update any existing ini files or add new ones if one does not already exist.

**Review by jdm — APPROVED** [review]
