### PR TITLE
crown: Check closure bodies for unrooted types and fix root TransmitBodyPromise*

### LINKED ISSUE #37331: `TransmitBodyPromiseRejectionHandler` is unrooted
https://github.com/servo/servo/blob/bd6639aadbbda905a82bfe911caf033cd33cfde1/components/script/body.rs#L250

and other expressions should root the struct. The reason the code compiles now is https://github.com/servo/servo/issues/37330

For how to do it, see the example of https://github.com/servo/servo/blob/bd6639aadbbda905a82bfe911caf033cd33cfde1/components/script/dom/writablestream.rs#L54 (note the `impl js::gc::Rootable`).

### PR DESCRIPTION
**Pull request by sagudev**
We should also check closure bodies for unrooted expressions. 

Testing: New crown tests
Fixes: #37331
Fixes (partial): #37330

### CODE REVIEW

File: components/script/body.rs [hunk 1]
```diff
@@ -234,27 +234,28 @@ impl TransmitBodyConnectHandler {
...
-                let rejection_handler = Box::new(TransmitBodyPromiseRejectionHandler {
+                rooted!(in(*cx) let mut rejection_handler = Some(TransmitBodyPromiseRejectionHandler {
                     bytes_sender,
                     stream: Dom::from_ref(&rooted_stream.clone()),
                     control_sender,
-                });
+                }));
 
                 let handler =
-                    PromiseNativeHandler::new(&global, Some(promise_handler), Some(rejection_handler), CanGc::note());
```
Comment (sagudev) [inline components/script/body.rs:257]: I did this as suggested in https://github.com/servo/servo/issues/37331 to make it compile, but I think it's wrong. We moved out actual value from rooted with take, we have root/trace `None` when doing alloc (and possibly GC) in `PromiseNativeHandler::new`, actual boxed handlers are just floating around freely and not being traced.

Comment (sagudev) [reply components/script/body.rs:257]: cc @jdm @gterzian

Comment (sagudev) [reply components/script/body.rs:257]: The biggest problem is that args (inner fields) need to be rooted (traced) before `reflect_dom_object`. One idea is that we would always make sure that unrooted dom struct is rooted (traced), before creating it's reflector (JSObject).

Comment (jdm) [reply components/script/body.rs:257]: Yeah, we don't yet have a good way to enforce this. The only idea I've had is creating the DOM object with all default values, rooting it, then initializing the real values, but that requires unnecessary mutability for otherwise-immutable fields, and is also a poor development experience.

**Review by jdm — APPROVED** [review]
