### PR TITLE
layout: Add support for `background-attachment: fixed`

### LINKED ISSUE #19669: Correct background-attachment: fixed
Element backgrounds with `background-attachment: fixed` should not be scrolled with the window contents. They should stay attached to the viewport all the time.

Testing this:

1. Go to https://staktrace.github.io/moz-pages/bug/1368496/
2. In the upper left corner a quadratic image should be shown.
3. Scroll a bit. The square should not move.
4. Scroll to the end of the page. The whole page should be blank. (Assuming usual screen resolution.)

(Currently something like absolute positioning is implemented.)

### PR DESCRIPTION
**Pull request by mrobinson**
Co-authored-by: Oriol Brufau <obrufau@igalia.com>

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #19669 (but not for legacy layout).
- [x] There are tests for these changes

### CODE REVIEW

File: components/layout_2020/display_list/background.rs [hunk 1]
```diff
@@ -43,49 +46,120 @@ pub(super) struct BackgroundPainter<'a> {
...
         &self,
         fragment_builder: &'a super::BuilderForBoxFragment,
         layer_index: usize,
-    ) -> &units::LayoutRect {
-        self.positioning_area_override.as_ref().unwrap_or_else(|| {
-            match get_cyclic(
+    ) -> units::LayoutRect {
+        if let Some(positioning_area_override) = self.positioning_area_override.as_ref() {
+            return positioning_area_override.clone();
+        }
```
Comment (Loirooriol) [inline components/layout_2020/display_list/background.rs:139]:
```suggestion
        if let Some(positioning_area_override) = self.positioning_area_override {
            return positioning_area_override;
        }
```

File: components/layout_2020/display_list/background.rs [hunk 2]
```diff
@@ -43,49 +46,120 @@ pub(super) struct BackgroundPainter<'a> {
...
+            BackgroundAttachment::Scroll => match get_cyclic(
                 &self.style.get_background().background_origin.0,
                 layer_index,
             ) {
                 Origin::ContentBox => fragment_builder.content_rect(),
                 Origin::PaddingBox => fragment_builder.padding_rect(),
                 Origin::BorderBox => &fragment_builder.border_rect,
             }
-        })
+            .clone(),
```
Comment (Loirooriol) [inline components/layout_2020/display_list/background.rs:153]:
```rs
                Origin::ContentBox => *fragment_builder.content_rect(),
                Origin::PaddingBox => *fragment_builder.padding_rect(),
                Origin::BorderBox => fragment_builder.border_rect,
            },
```

**Comment by mrobinson** [comment]
@Loirooriol Thanks for the review. I think this one is ready to look at again.

**Review by Loirooriol — APPROVED** [review]
