### PR TITLE
Fixes for off-thread compilation of scripts

### LINKED ISSUE #27349: Off-thread compiled scripts don't have dynamic import integration
When reading through the changes from https://github.com/servo/servo/pull/26710, I realized that only the scripts that are compiled as part of evaluation get the script private set on them. We should extend this to the off-thread compiled scripts as well.

### LINKED ISSUE #27355: Non-null terminated strings are being passed to CompileOptionsWrapper::new
https://github.com/servo/servo/blob/a24291362946f92bf155b390ea469b7be50a4c2d/components/script/dom/htmlscriptelement.rs#L428

We need to convert the rust string into a CString before passing the pointer to it.

### PR DESCRIPTION
**Pull request by jdm**
Fixes #27355. Fixes #27349.

### CODE REVIEW

File: components/script/dom/globalscope.rs [hunk 1]
```diff
@@ -2596,59 +2596,55 @@ impl GlobalScope {
...
+                            None,
+                        ));
+
+                        SetScriptPrivate(
+                            *compiled_script,
+                            &PrivateValue(Rc::into_raw(module_script_data) as *const _),
+                        );
+                    }
+
+                    let result = JS_ExecuteScript(*cx, compiled_script.handle(), rval);
```
Comment (CYBAI) [inline components/script/dom/globalscope.rs:2646]: Because of the early return in `SourceCode::Text` branch above and also the null check for returning a network error in `off_thread_compilation_callback`, we should always get a non-null `compiled_script`.

I'm wondering, would it be worth adding an assert before executing the script 👀?

**Review by CYBAI — APPROVED** [review]
Thanks! This all looks good to me! Only one question!

(Btw, the patch for CString reminds me that I did a redundant `as_bytes` for transforming a string into CString in script_module 😂)

Edit: as a reviewer, I should say `r=me` 😆

File: components/script/dom/globalscope.rs (hunk 1 above)
Comment (jdm) [reply components/script/dom/globalscope.rs:2646]: Sounds reasonable!

**Comment by jdm** [comment]
@bors-servo retry
* #24622

**Comment by jdm** [comment]
@bors-servo retry
* #26895

**Comment by jdm** [comment]
@bors-servo retry
* #26895

**Comment by jdm** [comment]
@bors-servo retry
* #26895

**Comment by jdm** [comment]
@bors-servo retry
* #26895
