### PR TITLE
Fix panic in parser-reentrancy-customelement.window.js

### LINKED ISSUE #33064: Panic in tests/wpt/mozilla/tests/mozilla/parser-reentrancy-customelement.js?async
To reproduce: `./mach test-wpt tests/wpt/mozilla/tests/mozilla/parser-reentrancy-customelement.window.js`

```
pid:79050 internal error: entered unreachable code (thread Script(1,1), at components/script/dom/servoparser/async_html.rs:338)
 0:13.35 pid:79050   12: core::panicking::panic
 0:13.35 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:146:5
 0:13.40 pid:79050   13: script::dom::servoparser::async_html::Tokenizer::end
 0:13.40 pid:79050              at /Users/jdm/src/servo/components/script/dom/servoparser/async_html.rs:338:22
 0:13.43 pid:79050   14: script::dom::servoparser::Tokenizer::end
 0:13.43 pid:79050              at /Users/jdm/src/servo/components/script/dom/servoparser/mod.rs:705:52
 0:13.43 pid:79050   15: script::dom::servoparser::ServoParser::abort
 0:13.43 pid:79050              at /Users/jdm/src/servo/components/script/dom/servoparser/mod.rs:405:9
 0:13.46 pid:79050   16: script::dom::document::Document::abort
 0:13.46 pid:79050              at /Users/jdm/src/servo/components/script/dom/document.rs:2667:13
 0:13.46 pid:79050   17: <script::dom::document::Document as script::dom::bindings::codegen::Bindings::DocumentBinding::Document_Binding::DocumentMethods>::Open
 0:13.46 pid:79050              at /Users/jdm/src/servo/components/script/dom/document.rs:5228:13
 0:13.49 pid:79050   18: script::dom::bindings::codegen::Bindings::DocumentBinding::Document_Binding::open::{{closure}}::{{closure}}
 0:13.49 pid:79050              at /Users/jdm/src/servo/target/debug/build/script-691217678d484feb/out/Bindings/DocumentBinding.rs:2857:64
 0:13.49 pid:79050   19: script::dom::bindings::codegen::Bindings::DocumentBinding::Document_Binding::open::{{closure}}
 0:13.49 pid:79050              at /Users/jdm/src/servo/target/debug/build/script-691217678d484feb/out/Bindings/DocumentBinding.rs:2818:33
 0:13.50 pid:79050   20: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
 0:13.50 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/ops/function.rs:305:13
 0:13.50 pid:79050   21: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
 0:13.50 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panic/unwind_safe.rs:272:9
 0:13.50 pid:79050   22: std::panicking::try::do_call
 0:13.50 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:559:40
 0:13.50 pid:79050   23: ___rust_try
 0:13.50 pid:79050   24: std::panicking::try
 0:13.50 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:523:19
 0:13.50 pid:79050   25: std::panic::catch_unwind
 0:13.51 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panic.rs:149:14
 0:13.51 pid:79050   26: mozjs::panic::wrap_panic
 0:13.51 pid:79050              at /Users/jdm/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/c715ae4/mozjs/src/panic.rs:22:11
 0:13.53 pid:79050   27: script::dom::bindings::codegen::Bindings::DocumentBinding::Document_Binding::open
 0:13.53 pid:79050              at /Users/jdm/src/servo/target/debug/build/script-691217678d484feb/out/Bindings/DocumentBinding.rs:2818:5
 0:13.58 pid:79050   28: CallJitMethodOp
 0:13.58 pid:79050              at /Users/runner/work/mozjs/mozjs/mozjs-sys/src/jsglue.cpp:638:10
 0:13.61 pid:79050   29: script::dom::bindings::utils::generic_call
 0:13.61 pid:79050              at /Users/jdm/src/servo/components/script/dom/bindings/utils.rs:522:5
 0:13.61 pid:79050   30: script::dom::bindings::utils::generic_method
 0:13.61 pid:79050              at /Users/jdm/src/servo/components/script/dom/bindings/utils.rs:538:5
 0:13.61 pid:79050   31: __ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
 0:13.61 pid:79050   32: __ZN2js9InterpretEP9JSContextRNS_8RunStateE
 0:13.61 pid:79050   33: __ZN2js9RunScriptEP9JSContextRNS_8RunStateE
 0:13.61 pid:79050   34: __ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
 0:13.61 pid:79050   35: __ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
 0:13.61 pid:79050   36: __Z20JS_CallFunctionValueP9JSContextN2JS6HandleIP8JSObjectEENS2_INS1_5ValueEEERKNS1_16HandleValueArrayENS1_13MutableHandleIS6_EE
 0:13.64 pid:79050   37: mozjs::rust::wrappers::JS_CallFunctionValue
 0:13.64 pid:79050              at /Users/jdm/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/c715ae4/mozjs/src/rust.rs:1070:51
 0:13.67 pid:79050   38: script::dom::bindings::codegen::Bindings::FunctionBinding::Function::Call
 0:13.67 pid:79050              at /Users/jdm/src/servo/target/debug/build/script-691217678d484feb/out/Bindings/FunctionBinding.rs:61:18
 0:13.69 pid:79050   39: script::dom::bindings::codegen::Bindings::FunctionBinding::Function::Call_
 0:13.69 pid:79050              at /Users/jdm/src/servo/target/debug/build/script-691217678d484feb/out/Bindings/FunctionBinding.rs:33:18
 0:13.72 pid:79050   40: script::dom::customelementregistry::CustomElementReaction::invoke
 0:13.72 pid:79050              at /Users/jdm/src/servo/components/script/dom/customelementregistry.rs:997:25
 0:13.75 pid:79050   41: script::dom::element::Element::invoke_reactions
 0:13.75 pid:79050              at /Users/jdm/src/servo/components/script/dom/element.rs:416:17
 0:13.75 pid:79050   42: script::dom::customelementregistry::ElementQueue::invoke_reactions
 0:13.75 pid:79050              at /Users/jdm/src/servo/components/script/dom/customelementregistry.rs:1243:13
 0:13.75 pid:79050   43: script::dom::customelementregistry::CustomElementReactionStack::pop_current_element_queue
 0:13.75 pid:79050              at /Users/jdm/src/servo/components/script/dom/customelementregistry.rs:1047:13
 0:13.78 pid:79050   44: script::script_thread::ScriptThread::pop_current_element_queue::{{closure}}
 0:13.78 pid:79050              at /Users/jdm/src/servo/components/script/script_thread.rs:1217:17
 0:13.83 pid:79050   45: std::thread::local::LocalKey<T>::try_with
 0:13.83 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/local.rs:283:12
 0:13.83 pid:79050   46: std::thread::local::LocalKey<T>::with
 0:13.83 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/local.rs:260:9
 0:13.86 pid:79050   47: script::script_thread::ScriptThread::pop_current_element_queue
 0:13.86 pid:79050              at /Users/jdm/src/servo/components/script/script_thread.rs:1214:9
 0:13.86 pid:79050   48: script::dom::servoparser::insert
 0:13.86 pid:79050              at /Users/jdm/src/servo/components/script/dom/servoparser/mod.rs:1034:17
 0:13.86 pid:79050   49: script::dom::servoparser::async_html::Tokenizer::append
 0:13.86 pid:79050              at /Users/jdm/src/servo/components/script/dom/servoparser/async_html.rs:387:9
 0:13.86 pid:79050   50: script::dom::servoparser::async_html::Tokenizer::process_operation
 0:13.86 pid:79050              at /Users/jdm/src/servo/components/script/dom/servoparser/async_html.rs:443:17
 0:13.86 pid:79050   51: script::dom::servoparser::async_html::Tokenizer::feed
 0:13.86 pid:79050              at /Users/jdm/src/servo/components/script/dom/servoparser/async_html.rs:306:63
 0:13.86 pid:79050   52: script::dom::servoparser::Tokenizer::feed
 0:13.86 pid:79050              at /Users/jdm/src/servo/components/script/dom/servoparser/mod.rs:697:52
 0:13.88 pid:79050   53: script::dom::servoparser::ServoParser::do_parse_sync::{{closure}}
 0:13.88 pid:79050              at /Users/jdm/src/servo/components/script/dom/servoparser/mod.rs:560:35
 0:13.88 pid:79050   54: script::dom::servoparser::ServoParser::tokenize
 0:13.89 pid:79050              at /Users/jdm/src/servo/components/script/dom/servoparser/mod.rs:599:32
 0:13.89 pid:79050   55: script::dom::servoparser::ServoParser::do_parse_sync
 0:13.89 pid:79050              at /Users/jdm/src/servo/components/script/dom/servoparser/mod.rs:560:9
 0:13.89 pid:79050   56: script::dom::servoparser::ServoParser::parse_sync::{{closure}}
 0:13.89 pid:79050              at /Users/jdm/src/servo/components/script/dom/servoparser/mod.rs:542:16
 0:13.91 pid:79050   57: profile_traits::time::profile
 0:13.91 pid:79050              at /Users/jdm/src/servo/components/shared/profile/time.rs:147:15
 0:13.91 pid:79050   58: script::dom::servoparser::ServoParser::parse_sync
 0:13.91 pid:79050              at /Users/jdm/src/servo/components/script/dom/servoparser/mod.rs:534:9
 0:13.91 pid:79050   59: script::dom::servoparser::ServoParser::parse_bytes_chunk
 0:13.91 pid:79050              at /Users/jdm/src/servo/components/script/dom/servoparser/mod.rs:586:13
 0:13.91 pid:79050   60: <script::dom::servoparser::ParserContext as net_traits::FetchResponseListener>::process_response_chunk
 0:13.91 pid:79050              at /Users/jdm/src/servo/components/script/dom/servoparser/mod.rs:933:9
 0:13.91 pid:79050   61: script::script_thread::ScriptThread::page_load_about_srcdoc
 0:13.91 pid:79050              at /Users/jdm/src/servo/components/script/script_thread.rs:4078:9
 0:13.91 pid:79050   62: script::script_thread::ScriptThread::handle_new_layout
 0:13.91 pid:79050              at /Users/jdm/src/servo/components/script/script_thread.rs:2844:13
 0:13.91 pid:79050   63: script::script_thread::ScriptThread::handle_msgs::{{closure}}
 0:13.91 pid:79050              at /Users/jdm/src/servo/components/script/script_thread.rs:1845:29
 0:13.91 pid:79050   64: script::script_thread::ScriptThread::profile_event
 0:13.91 pid:79050              at /Users/jdm/src/servo/components/script/script_thread.rs:2214:13
 0:13.91 pid:79050   65: script::script_thread::ScriptThread::handle_msgs
 0:13.91 pid:79050              at /Users/jdm/src/servo/components/script/script_thread.rs:1815:21
 0:13.91 pid:79050   66: script::script_thread::ScriptThread::start
 0:13.91 pid:79050              at /Users/jdm/src/servo/components/script/script_thread.rs:1454:15
 0:13.91 pid:79050   67: <script::script_thread::ScriptThread as script_layout_interface::ScriptThreadFactory>::create::{{closure}}::{{closure}}
 0:13.91 pid:79050              at /Users/jdm/src/servo/components/script/script_thread.rs:845:25
 0:13.94 pid:79050   68: profile_traits::mem::ProfilerChan::run_with_memory_reporting
 0:13.94 pid:79050              at /Users/jdm/src/servo/components/shared/profile/mem.rs:91:9
 0:13.94 pid:79050   69: <script::script_thread::ScriptThread as script_layout_interface::ScriptThreadFactory>::create::{{closure}}
 0:13.94 pid:79050              at /Users/jdm/src/servo/components/script/script_thread.rs:843:17
 0:13.97 pid:79050   70: std::sys_common::backtrace::__rust_begin_short_backtrace
 0:13.97 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:155:18
 0:13.99 pid:79050   71: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
 0:13.99 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/mod.rs:542:17
 0:14.02 pid:79050   72: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
 0:14.02 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panic/unwind_safe.rs:272:9
 0:14.05 pid:79050   73: std::panicking::try::do_call
 0:14.05 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:559:40
 0:14.05 pid:79050   74: ___rust_try
 0:14.05 pid:79050   75: std::panicking::try
 0:14.05 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:523:19
 0:14.05 pid:79050   76: std::panic::catch_unwind
 0:14.05 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panic.rs:149:14
 0:14.05 pid:79050       std::thread::Builder::spawn_unchecked_::{{closure}}
 0:14.05 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/mod.rs:541:30
 0:14.41 pid:79050   77: core::ops::function::FnOnce::call_once{{vtable.shim}}
 0:14.41 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/ops/function.rs:250:5
 0:14.41 pid:79050   78: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
 0:14.41 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2063:9
 0:14.41 pid:79050       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
 0:14.41 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2063:9
 0:14.41 pid:79050       std::sys::pal::unix::thread::Thread::new::thread_start
 0:14.41 pid:79050              at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys/pal/unix/thread.rs:108:17
 0:14.41 pid:79050   79: __pthread_joiner_wake
```

### PR DESCRIPTION
**Pull request by Taym95**
Although this change fixes the panic and makes the test pass, I am not sure about it.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #33064

- [x] There are tests for these changes

### CODE REVIEW

File: components/script/dom/servoparser/async_html.rs [hunk 1]
```diff
@@ -334,8 +334,7 @@ impl Tokenizer {
                 .expect("Unexpected channel panic in main thread.")
             {
                 ToTokenizerMsg::ProcessOperation(parse_op) => self.process_operation(parse_op),
-                ToTokenizerMsg::End => return,
-                _ => unreachable!(),
+                _ => return,
```
Comment (gterzian) [inline components/script/dom/servoparser/async_html.rs:337]: `continue` is the right one, because you want to loop to continue processing `ProcessOperation` and only return with `End`.

File: components/script/dom/servoparser/async_html.rs [hunk 2]
```diff
@@ -318,7 +318,7 @@ impl Tokenizer {
                     let script = self.get_node(&script.id);
                     return TokenizerResult::Script(DomRoot::from_ref(script.downcast().unwrap()));
                 },
-                ToTokenizerMsg::End => unreachable!(),
```
Comment (gterzian) [inline components/script/dom/servoparser/async_html.rs:321]: This one hasn't been a problem yet, so we can assume it remains unreachable even with the new re-entrant parser.

**Review by gterzian — CHANGES_REQUESTED** [review]
Couple of comments. Also the proposed fix hasn't been validated yet, @jdm what do you think?

File: components/script/dom/servoparser/async_html.rs (hunk 2 above)
Comment (Taym95) [reply components/script/dom/servoparser/async_html.rs:321]: this crashed after I changed the first `_ => unreachable!(),` to `_ => return`

Comment (gterzian) [reply components/script/dom/servoparser/async_html.rs:321]: Ok, thanks for the info. Then it seems like a good idea indeed.

**Comment by gterzian** [comment]
One question I have, perhaps @jdm can answer, is that it's not clear to me whether ending the parsing of the re-entrant call should affect the "outer" parsing(if that makes sense). In other words: if the inner call ends, do we shut down the parser, or do we keep parsing the document from which the re-entrant call originated? I think the current changes go in the direction of ending it all, so let's be clear that that is what we want(or not).

File: components/script/dom/servoparser/async_html.rs (hunk 1 above)
Comment (Taym95) [reply components/script/dom/servoparser/async_html.rs:337]: Indeed

File: components/script/dom/servoparser/async_html.rs (hunk 2 above)
Comment (Taym95) [reply components/script/dom/servoparser/async_html.rs:321]: after I only returned with `ToTokenizerMsg::End` and `continue` for others, this is not panicking anymore

Comment (gterzian) [reply components/script/dom/servoparser/async_html.rs:321]: Thank for confirming. let's just see what @jdm has to say re the comment below.

Comment (jdm) [reply components/script/dom/servoparser/async_html.rs:321]: I will try to make time tonight to understand the implications.

**Comment by jdm** [comment]
My experiments with testcases like:
```html
<script>
  document.write("<div>hi</div><script>window.stop()<" + "/script>");
</script>
<div>hello!!</div>
```
in other browsers make me confident that aborting the parser at any level should cause all future parsing to be interrupted as well.

**Review by jdm — APPROVED** [review]
This seems reasonable to me.

**Comment by Taym95** [comment]
@gterzian I think you should approve it so it can be merged.

**Review by gterzian — APPROVED** [review]
thanks!
