### PR TITLE
layout: Do not consider pseudo-elements widgets for the purposes of replaced content

### LINKED ISSUE #41231: panic: already immutably borrowed (atomic_refcell-0.1.13/src/lib.rs:155)
This is very flaky, I'm relying on https://github.com/fred-wang/servo-fuzzing/blob/main/repeat.sh (with a 20 count) to reproduce. The panic message and location is similar (but slightly different) to #41183.

Minimal testcase:

```html
<!DOCTYPE html>
<style>
  #container, details { display: list-item; }
  details { list-style: url(data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOxAAADsQBlSsOGwAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjIyt5EXfQAAAU5JREFUeF7t07ENACAMxMDA/jsDBTtcY6TUlmx+zcx510MGNuKG/QYKgL9CAQqADWB8CygANoDxLaAA2ADGt4ACYAMY3wIKgA1gfAsoADaA8S2gANgAxreAAmADGN8CCoANYHwLKAA2gPEtoADYAMa3gAJgAxjfAgqADWB8CygANoDxLaAA2ADGt4ACYAMY3wIKgA1gfAsoADaA8S2gANgAxreAAmADGN8CCoANYHwLKAA2gPEtoADYAMa3gAJgAxjfAgqADWB8CygANoDxLaAA2ADGt4ACYAMY3wIKgA1gfAsoADaA8S2gANgAxreAAmADGN8CCoANYHwLKAA2gPEtoADYAMa3gAJgAxjfAgqADWB8CygANoDxLaAA2ADGt4ACYAMY3wIKgA1gfAsoADaA8S2gANgAxreAAmADGN8CCoANYHwLKAA2gPEtAAe4i54BvwLfXFAAAAAASUVORK5CYII=); }
</style>
<div id="container">}&#xA;<details></details></div>
```

System: Linux
Version: Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725 Version: Servo 0.0.3-c62fbe725
Command: `./repeat.sh ./servo/servo`

```
already immutably borrowed (thread Script#1, at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/atomic_refcell-0.1.13/src/lib.rs:155)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::panic_with_hook
   3: std::panicking::panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: __rustc::rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::panic_display
   8: <script::layout_dom::node::ServoThreadSafeLayoutNode as layout::dom::NodeExt>::take_restyle_damage
   9: layout::dom_traversal::traverse_children_of
  10: layout::dom_traversal::traverse_children_of
  11: layout::flow::construct::<impl layout::flow::BlockContainer>::construct
  12: layout::formatting_contexts::IndependentFormattingContext::construct
  13: layout::flow::construct::BlockContainerBuilder::handle_inline_level_element
  14: layout::dom_traversal::traverse_pseudo_element_contents
  15: layout::flow::construct::<impl layout::flow::BlockContainer>::construct
  16: layout::flow::construct::BlockLevelJob::finish
  17: rayon::iter::plumbing::bridge_producer_consumer::helper
  18: rayon_core::join::join_context::{{closure}}
  19: rayon::iter::plumbing::bridge_producer_consumer::helper
  20: layout::flow::construct::BlockContainerBuilder::finish
  21: layout::flow::construct::<impl layout::flow::BlockContainer>::construct
  22: layout::flow::construct::BlockLevelJob::finish
  23: rayon::iter::plumbing::bridge_producer_consumer::helper
  24: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  25: rayon_core::registry::WorkerThread::wait_until_cold
  26: rayon_core::join::join_context::{{closure}}
  27: rayon::iter::plumbing::bridge_producer_consumer::helper
  28: layout::flow::construct::BlockContainerBuilder::finish
  29: layout::flow::construct::<impl layout::flow::BlockContainer>::construct
  30: layout::flow::construct::BlockLevelJob::finish
  31: rayon::iter::plumbing::bridge_producer_consumer::helper
  32: layout::flow::construct::BlockContainerBuilder::finish
  33: layout::flow::construct::<impl layout::flow::BlockContainer>::construct
  34: layout::flow::construct::BlockLevelJob::finish
  35: rayon::iter::plumbing::bridge_producer_consumer::helper
  36: layout::flow::construct::BlockContainerBuilder::finish
  37: layout::flow::construct::<impl layout::flow::BlockContainer>::construct
  38: layout::formatting_contexts::IndependentFormattingContext::construct
  39: layout::layout_impl::LayoutThread::restyle_and_build_trees::{{closure}}
  40: layout::layout_impl::LayoutThread::handle_reflow
  41: <layout::layout_impl::LayoutThread as layout_api::Layout>::reflow
  42: script::dom::window::Window::reflow
  43: script::dom::document::Document::update_the_rendering
  44: script::script_thread::ScriptThread::update_the_rendering
  45: script::script_thread::ScriptThread::handle_msgs
  46: std::sys::backtrace::__rust_begin_short_backtrace
  47: core::ops::function::FnOnce::call_once{{vtable.shim}}
  48: std::sys::thread::unix::Thread::new::thread_start
  49: start_thread
             at ./nptl/pthread_create.c:447:8
  50: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
./repeat.sh : ligne 4 : 539866 Erreur de segmentation  (core dumped) $@
```

### PR DESCRIPTION
**Pull request by lukewarlow**
When an element has an image content value or list-style-image value they end up duplicating the content of the element inside the generated '::marker'.

This is caused by code inside IndependentFormattingContext for user agent widgets (all user agent shadow dom), this code is specifically aimed at video and audio elements.

This patch adapts that code to be more specific to elements without a pseudo-element chain (e.g. audio and video)

Testing: newly added test crashes on main servo (slightly flakily), but passes consistently now.
Fixes: #42329 
Fixes: #41231

### CODE REVIEW

**Review by Loirooriol — COMMENTED** [review]
It feels like we just keep putting band-aids, while the root of the problem remains unaddressed.

Which is that, `ServoLayoutElement::shadow_root()` (and several other methods) shouldn't blindly redirect to `self.element`, ignoring `self.pseudo_element_chain`.

But while not fixing that, instead of checking for video and audio replaced kinds, I would check that the `pseudo_element_chain` is empty. Because I'm not sure we can't rely on pseudo-elements never supporting videos in the future.

**Comment by lukewarlow** [comment]
@Loirooriol is there an issue about the issue we keep bandaging?

**Comment by Loirooriol** [comment]
I don't think there is an issue about these methods ignoring `pseudo_element_chain`.

But for example I fixed #41183 in the past, which was analogous to #41231, so it was just a band aid.

File: components/layout/formatting_contexts.rs [hunk 1]
```diff
@@ -91,33 +91,39 @@ impl IndependentFormattingContext {
...
-                            ),
-                        );
-                        let widget_base =
-                            LayoutBoxBase::new((&widget_info).into(), widget_info.style);
-                        ArcRefCell::new(IndependentFormattingContext::new(
-                            widget_base,
-                            widget_contents,
-                        ))
-                    });
+                let widget = if node_and_style_info.pseudo_element_chain().is_empty() {
```
Comment (Loirooriol) [inline components/layout/formatting_contexts.rs]: Can avoid the extra indentation like this:

```rs
                let widget = Some(node_and_style_info.node)
                    .filter(|node| node.pseudo_element_chain.is_empty())
                    .and_then(|node| node.as_element())
                    ...
```

File: tests/wpt/tests/html/rendering/the-details-element/details-display-list-item-crash.html [hunk 2]
```diff
@@ -0,0 +1,19 @@
+<!DOCTYPE html>
+<meta charset="utf-8">
```
Comment (Loirooriol) [inline tests/wpt/tests/html/rendering/the-details-element/details-display-list-item-crash.html]: Don't place the `<meta>` outside the `<html>`. Omit the `<html>` or nest correctly.

Add `<link rel="help" href="https://github.com/servo/servo/issues/41231">` for context.

File: tests/wpt/tests/html/rendering/the-details-element/details-display-list-item-crash.html [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+</style>
+</head>
+<body>
+<!-- This test passes if it does not crash. -->
+
+<details></details>
+<script>
+    window.reload();
+</script>
+</body>
```
Comment (Loirooriol) [inline tests/wpt/tests/html/rendering/the-details-element/details-display-list-item-crash.html]: If you don't omit the `<html>`, then close it with `</html>`.

And seems better to end the file with a newline.

**Review by Loirooriol — APPROVED** [review]

**Review by mrobinson — APPROVED** [review]
