### PR TITLE
layout: Properly propagate baselines of flex items that do not participate in baseline alignment

### LINKED ISSUE #41905: Baselines no longer propagate out from flex containers
```html
<!DOCTYPE html>

<div style="display: inline-block; outline: solid; font-size: 50px;">
    <div style="display: flex;  height: 100px;">Flex</div>
</div>
<span style="outline: solid; font-size: 50px">Inline</span>
```

Servo:

Image

Firefox:

Image

I suspect this is a regression from #33031 or thereabouts which seems to be conflating the flex alignment baseline with the one that is propagated out to other boxes.

### PR DESCRIPTION
**Pull request by lukewarlow**
Fix baseline propagation from flex containers

Flex item layout previously conflated baselines that got propagated and baseline alignment within flex.

Testing: Before and after layout of the manual test cases.

[test.html](https://github.com/user-attachments/files/24796669/test.html) (from original issue)

image

[test2.html](https://github.com/user-attachments/files/24796679/test2.html) (from Oriol's comment)

image

Fixes: #41905

### CODE REVIEW

**Comment by lukewarlow** [comment]
This does introduce a few new test failures but from what I can work out these are actual bugs that were previously hidden by the existing behaviour?

File: components/layout/flexbox/layout.rs [hunk 1]
```diff
@@ -220,6 +226,20 @@ impl FlexLineItem<'_> {
             all_baselines.last = Some(item_baseline);
         }
 
+        if all_baselines.first.is_none() {
+            let content_baselines = &self.layout_result.content_baselines_relative_to_margin_box;
+
+            if let Some(baseline) = content_baselines.first {
```
Comment (Loirooriol) [inline components/layout/flexbox/layout.rs]: This doesn't seem to be handling last baselines

```html
<!DOCTYPE html>
<div style="baseline-source: last; display: inline-flex; outline: solid">
  <div>A<br>B</div>
</div>
<span style="outline: solid">Inline</span>
```

**Comment by lukewarlow** [comment]
Note to self, push up the code accounting for flex direction reversal and simplifications after discussion with Martin.

File: components/layout/flexbox/layout.rs [hunk 2]
```diff
@@ -115,8 +115,10 @@ struct FlexItemLayoutResult {
     fragments: Vec<Fragment>,
     positioning_context: PositioningContext,
 
+    content_baselines_relative_to_margin_box: Baselines,
```
Comment (mrobinson) [inline components/layout/flexbox/layout.rs:120]: Can you add some rustdoc explaining the purpose of this field and how it differs from the other baseline?

**Review by mrobinson — APPROVED** [review]

File: components/layout/flexbox/layout.rs (hunk 2 above)
Comment (lukewarlow) [reply components/layout/flexbox/layout.rs:120]: Hopefully something like I've added is right?

**Review by mrobinson — APPROVED** [review]

**Comment by mrobinson** [comment]
There are some new failures here, but I suspect they are just exposing some of the existing bugs we discussed in our call. @lukewarlow can you please just update the expected results and then we can address the new failures later?
