### PR TITLE
Fix frame-pointer stackwalking

### LINKED ISSUE #22604: Hang monitor stack trace doesn't make sense
I received these backtraces while loading https://newyorktimes.com:
```
Stack trace
stack backtrace:
   0:        0x110b8cfae - __ZN9backtrace9backtrace5trace17h1031ecbd57e70b1aE
   1:        0x110b8bf0c - __ZN72_$LT$backtrace..capture..Backtrace$u20$as$u20$core..default..Default$GT$7default17hd2735b19f50df4baE
   2:        0x10ea3c560 - __ZN5servo21install_crash_handler7handler17h5983254e49d3dc15E
   3:     0x7fffae9e2b39 - __sigtramp
   4:        0x110b89ae8 - __ZN112_$LT$background_hang_monitor..sampler_mac..MacOsSampler$u20$as$u20$background_hang_monitor..sampler..Sampler$GT$25suspend_and_sample_thread17h9efe9ca9cfb5f555E
   5:        0x110b83368 - __ZN23background_hang_monitor23background_hang_monitor27BackgroundHangMonitorWorker3run17h047341667e28d833E
   6:        0x110b80397 - __ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17h0fbad0ac2f51a49bE
   7:        0x110b77f37 - __ZN3std9panicking3try7do_call17ha9b1c2b3d6b80215E.llvm.13158428631819150874
   8:        0x11160303e - ___rust_maybe_catch_panic
   9:        0x110b8a32b - __ZN50_$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$8call_box17h1cdf58f3bd83d145E
  10:        0x1116025eb - __ZN3std3sys4unix6thread6Thread3new12thread_start17ha7a33ee7c2fd74e3E
  11:     0x7fffae9ec93a - __pthread_body
  12:     0x7fffae9ec886 - __pthread_start
Stack trace
stack backtrace:
   0:        0x110b8cfae - __ZN9backtrace9backtrace5trace17h1031ecbd57e70b1aE
   1:        0x110b8bf0c - __ZN72_$LT$backtrace..capture..Backtrace$u20$as$u20$core..default..Default$GT$7default17hd2735b19f50df4baE
   2:        0x10ea3c560 - __ZN5servo21install_crash_handler7handler17h5983254e49d3dc15E
   3:     0x7fffae9e2b39 - __sigtramp
   4:        0x10ea3c5d4 - __ZN5servo21install_crash_handler7handler17h5983254e49d3dc15E
   5:     0x7fffae9e2b39 - __sigtramp
   6:        0x110b89ae8 - __ZN112_$LT$background_hang_monitor..sampler_mac..MacOsSampler$u20$as$u20$background_hang_monitor..sampler..Sampler$GT$25suspend_and_sample_thread17h9efe9ca9cfb5f555E
   7:        0x110b83368 - __ZN23background_hang_monitor23background_hang_monitor27BackgroundHangMonitorWorker3run17h047341667e28d833E
   8:        0x110b80397 - __ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17h0fbad0ac2f51a49bE
   9:        0x110b77f37 - __ZN3std9panicking3try7do_call17ha9b1c2b3d6b80215E.llvm.13158428631819150874
  10:        0x11160303e - ___rust_maybe_catch_panic
  11:        0x110b8a32b - __ZN50_$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$8call_box17h1cdf58f3bd83d145E
  12:        0x1116025eb - __ZN3std3sys4unix6thread6Thread3new12thread_start17ha7a33ee7c2fd74e3E
  13:     0x7fffae9ec93a - __pthread_body
  14:     0x7fffae9ec886 - __pthread_start
```
They seem to show backtraces from the hang monitor thread, rather than the hanging thread.

### PR DESCRIPTION
**Pull request by gterzian**
This seems to fix the problem, it's a check that is also done at https://dxr.mozilla.org/mozilla-central/rev/c2593a3058afdfeaac5c990e18794ee8257afe99/mozglue/misc/StackWalk.cpp#904

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #22604 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22637)

### CODE REVIEW

**Comment by gterzian** [comment]
@jdm r?

File: components/background_hang_monitor/sampler_mac.rs [hunk 1]
```diff
@@ -112,6 +112,9 @@ unsafe fn frame_pointer_stack_walk(regs: Registers) -> NativeStack {
         if let Err(()) = native_stack.process_register(*pc, *stack) {
             break;
         }
+        if next <= current {
```
Comment (gterzian) [inline components/background_hang_monitor/sampler_mac.rs]: See https://dxr.mozilla.org/mozilla-central/rev/c2593a3058afdfeaac5c990e18794ee8257afe99/mozglue/misc/StackWalk.cpp#904

**Comment by gterzian** [comment]
I got the crash again after all, so this requires further investigation...

**Comment by jdm** [comment]
It should be possible to cast a pointer to usize and perform the same & 3 != 0 check.

**Comment by gterzian** [comment]
Ok so I think I finally solved the issue. 

The problem seemed to be that during a stack walk, the frame pointer would "suddenly" jump to point to a place very high in the stack, I'm guessing before the beginning(higher than the beginning). Actually, when cast to `usize`, the value would either be `usize::max_value()`, or very close to it. 

For example, the frame pointer would in a previous step of the walk look like:
-  0x700008c5aaa8 (as usize 123145449482920)

and then at the next, look like:
- 0xfffb00011c6bed90 (as usize 18445336703597800848)

While `libc::pthread_get_stackaddr_np` gives us the "end"(low value) of the stack, I haven't found the equivalent to get the "beginning"(high value). So I've resorted to a check using `if (usize::max_value() / current as usize) <= 1`, which seems indeed work.

**Comment by gterzian** [comment]
@jdm thoughts on this? I didn't add the `& 3 != 0` check because it didn't prevent this particular crash, while the fix described above seemed to.

File: components/background_hang_monitor/sampler_mac.rs [hunk 2]
```diff
@@ -104,6 +105,11 @@ unsafe fn frame_pointer_stack_walk(regs: Registers) -> NativeStack {
     let mut current = regs.frame_ptr as *mut *mut std::ffi::c_void;
     while !current.is_null() {
         if (current as usize) < stackaddr as usize {
+            // Reached the end of the stack.
+            break;
+        }
+        if (usize::max_value() / current as usize) <= 1 {
```
Comment (jdm) [inline components/background_hang_monitor/sampler_mac.rs]: We can call [pthread_get_stacksize_np](https://docs.rs/libc/0.2.48/i686-apple-darwin/libc/fn.pthread_get_stacksize_np.html) to determine the other end of the stack. That seems like it will be more reliable than this heuristic.

**Review by jdm — CHANGES_REQUESTED** [review]
Let's go ahead and add the & 3 check as well; Gecko's implementation is well-tested, and it would be frustrating to encounter a non-pointer value later that causes a crash in the wild.

**Comment by jdm** [comment]
Sorry about the delay; for some reason I thought this was still in progress.

File: components/background_hang_monitor/sampler_mac.rs (hunk 2 above)
Comment (gterzian) [reply components/background_hang_monitor/sampler_mac.rs]: I replaced this with `if current as usize >= stackaddr.add(stacksize * 8) as usize`, with the thinking behind `* 8` being 64 bit mac... Does that make sense?

**Comment by gterzian** [comment]
@jdm I've added the check, and used `pthread_get_stacksize_np` for the other check(which is a stackoverflow I think).

File: components/background_hang_monitor/sampler_mac.rs [hunk 3]
```diff
@@ -112,6 +121,9 @@ unsafe fn frame_pointer_stack_walk(regs: Registers) -> NativeStack {
         if let Err(()) = native_stack.process_register(*pc, *stack) {
             break;
         }
+        if (next <= current) && (next as usize & 3 != 0) {
```
Comment (jdm) [inline components/background_hang_monitor/sampler_mac.rs]: This should be ||.

**Review by jdm — CHANGES_REQUESTED** [review]

**Comment by jdm** [comment]
@bors-servo delegate+
Otherwise it looks fine!

File: components/background_hang_monitor/sampler_mac.rs (hunk 3 above)
Comment (gterzian) [reply components/background_hang_monitor/sampler_mac.rs]: Thanks, during development I actually had those into two separate `if` with print statements to see which one would hit, and when I collapsed them into one at the end I off-course made a mistake!

**Comment by CYBAI** [comment]
```
  ▶ CRASH [expected OK] /html/semantics/embedded-content/the-iframe-element/iframe_sandbox_navigate_ancestor-1.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 18.3.0-devel
  │ Failed to receive a response from live font cache (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(2), index: PipelineIndex(3) }, at components/gfx/font_cache_thread.rs:522)
  │ stack backtrace:
  │    0:     0x7fee67bc620d - backtrace::backtrace::trace::h1cd733210e7d0ee7
  │    1:     0x7fee67bc5062 - <backtrace::capture::Backtrace as core::default::Default>::default::h5b232415cbbfce88
  │    2:     0x7fee65644b3f - servo::main::{{closure}}::hd5e20857bd27bc9d
  │    3:     0x7fee688a661d - rust_panic_with_hook
  │                         at src/libstd/panicking.rs:482
  │    4:     0x7fee66f68b94 - std::panicking::begin_panic::h21f612861f96a666
  │    5:     0x7fee66f9003c - <gfx::font_cache_thread::FontCacheThread as gfx::font_context::FontSource>::get_font_instance::ha6973ecc87f1c7eb
  │    6:     0x7fee66ad15cb - <gfx::font_context::FontContext<S>>::font::hd8ecc87862973361
  │    7:     0x7fee66b378dc - <core::iter::adapters::FilterMap<I, F> as core::iter::traits::iterator::Iterator>::try_fold::{{closure}}::h0cec8089fb511385
  │    8:     0x7fee66b3b7cf - gfx::font::FontGroup::first::h3b25f082eba5fcf5
  │    9:     0x7fee66aa9693 - layout::text::font_metrics_for_style::haf2c6a49bac29bbe
  │   10:     0x7fee66aa46ba - <std::thread::local::LocalKey<T>>::with::h42e1172744a6ccac
  │   11:     0x7fee66b177b8 - layout::fragment::Fragment::content_inline_metrics::inline_metrics_of_text::h562382c4cd18c767
  │   12:     0x7fee66b176dc - layout::fragment::Fragment::content_inline_metrics::ha502e5782be8b83e
  │   13:     0x7fee66b17aeb - layout::fragment::Fragment::aligned_inline_metrics::h1def908cb5b9fad3
  │   14:     0x7fee66af9652 - <layout::inline::InlineFlow as layout::flow::Flow>::assign_block_size::hc324649038bdbe9b
  │   15:     0x7fee66adc3ad - layout::sequential::reflow::doit::h197e843dc2aba690
  │   16:     0x7fee66adc3ad - layout::sequential::reflow::doit::h197e843dc2aba690
  │   17:     0x7fee66adc3ad - layout::sequential::reflow::doit::h197e843dc2aba690
  │   18:     0x7fee66adc26a - layout::sequential::reflow::h5b7fd751e648f24a
  │   19:     0x7fee659f60d3 - layout_thread::LayoutThread::solve_constraints::h1c66c241981a73b9
  │   20:     0x7fee65b0f135 - profile_traits::time::profile::h6092dfa42f6eb1d2
  │   21:     0x7fee659fa98e - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::heceb825ff80aed2e
  │   22:     0x7fee659f83a9 - layout_thread::LayoutThread::handle_reflow::h62c3d1cc58f61fc3
  │   23:     0x7fee65b0fa83 - profile_traits::time::profile::hffc430e0c064183e
  │   24:     0x7fee659f0d5e - layout_thread::LayoutThread::handle_request_helper::h1c3936b59135d1a7
  │   25:     0x7fee659ef601 - layout_thread::LayoutThread::start::hb7a45a6f10a3eb02
  │   26:     0x7fee65a47486 - profile_traits::mem::ProfilerChan::run_with_memory_reporting::hcaa5a25d8445fc05
  │   27:     0x7fee65a94e57 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5b45bb2f5353e077
  │   28:     0x7fee65a95415 - _ZN3std9panicking3try7do_call17h7597226340421ee0E.llvm.11828671310939098513
  │   29:     0x7fee688b1119 - __rust_maybe_catch_panic
  │                         at src/libpanic_unwind/lib.rs:92
  │   30:     0x7fee65b182c7 - <F as alloc::boxed::FnBox<A>>::call_box::hb5ade8794d26455d
  │   31:     0x7fee688b04cd - call_once<(),()>
  │                         at /rustc/da6ab956e1002517803ecd38b904504a1223274b/src/liballoc/boxed.rs:744
  │                          - start_thread
  │                         at src/libstd/sys_common/thread.rs:14
  │                          - thread_start
  │                         at src/libstd/sys/unix/thread.rs:81
  │   32:     0x7fee63006183 - start_thread
  │   33:     0x7fee618cd03c - clone
  │   34:                0x0 - <unknown>
  │ [2019-01-29T15:20:14Z ERROR servo] Failed to receive a response from live font cache
  │ Pipeline failed in hard-fail mode.  Crashing!
  └ thread panicked while processing panic. aborting.
```
