### PR TITLE
layout: Consider Gaussian blur when computing clip rectangle for `box-shadow` display list item

### LINKED ISSUE #44472: Gaussian blur radius wasn't considered when computing clip rectangle for box-shadow
**Describe the bug:**
Gaussian blur should be considered according to [spec](https://drafts.csswg.org/css-backgrounds/#shadow-blur).
#44457 computed only used scale 1.

Firefox do below:
```cpp
constexpr double sqrt_2_PI = 0x1.40d931ff62705p+1;  // sqrt is not constexpr
static constexpr Float GAUSSIAN_SCALE_FACTOR = Float((3 * sqrt_2_PI / 4) * 1.5);

IntSize GaussianBlur::CalculateBlurRadius(const Point& aStd) {
  IntSize size(
      static_cast<int32_t>(floor(aStd.x * GAUSSIAN_SCALE_FACTOR + 0.5f)),
      static_cast<int32_t>(floor(aStd.y * GAUSSIAN_SCALE_FACTOR + 0.5f)));

  return size;
}
```

This resulted in very subtle cutoff:

| Without multipler | Using a multiplier 2.0 |
| -------- | -------- |
|  |  |

**To Reproduce:**
```html
<!DOCTYPE html>
<style>
  body {
    background: black;
  }

  div {
    width: 100px;
    height: 100px;
    background: #fff;
    margin: 150px;
    box-shadow: 0 0 100px 20px cyan;
  }
</style>
<div></div>
```

**Platform:**
All.

### PR DESCRIPTION
**Pull request by yezhizhen**
According to [spec](https://drafts.csswg.org/css-backgrounds/#shadow-blur), the exact algorithm is not defined. 

1. We use a scale consistent with webrender defined in [`fn add_box_shadow`](https://github.com/servo/webrender/blob/e1c924ebad9ffdfe8c8c606aba77eb3f888c396a/webrender/src/box_shadow.rs#L305) of `box_shadow.rs`.
2. For `inset`, we avoid extra computation as it should always be within the original rect anyway.

Testing: Successful [try](https://github.com/servo/servo/actions/runs/24875566269). Manually tested on Android with following image. I don't think it is possible to add a test for this.

| Previously | Now |
| -------- | -------- |
|  |  |

Fixes: #44472.

### CODE REVIEW

**Comment by yezhizhen** [comment]
> We use a more accurate spread based on clip_mode

I feel dumb to do this extra thing. `inset` box-shadow should always be within the original `rect` anyway.

**Comment by yezhizhen** [comment]
The difference is subtle: but if you look closely, the left image has a clear rectangle boundary to the left of the viewport. The right image doesn't.

File: components/layout/display_list/mod.rs [hunk 1]
```diff
@@ -1902,10 +1902,24 @@ impl<'a> BuilderForBoxFragment<'a> {
...
+                // Inset shadows are always inside the rect.
+                BoxShadowClipMode::Inset => rect,
+                // Match webrender's `fn add_box_shadow` in box_shadow.rs logic:
+                //
+                // shadow_rect = rect.translate(offset).inflate(spread_amount, spread_amount)
+                // blur_offset = (BLUR_SAMPLE_SCALE * blur).ceil()  (BLUR_SAMPLE_SCALE = 3.0)
+                // dest_rect = shadow_rect.inflate(blur_offset, blur_offset)
+                BoxShadowClipMode::Outset => {
+                    let blur_offset = (blur * 3.0).ceil();
+                    let dest_rect = rect
```
Comment (mrobinson) [inline components/layout/display_list/mod.rs]: Where does this code originate from? It would be good to indicate that in the comment, I think.

File: components/layout/display_list/mod.rs [hunk 2]
```diff
@@ -1902,10 +1902,24 @@ impl<'a> BuilderForBoxFragment<'a> {
...
             let spread = box_shadow.spread.px();
             let blur = box_shadow.base.blur.px();
-            let shifted = rect.translate(offset);
-            let spread_rect = shifted.inflate(spread, spread);
-            let shadow_rect = spread_rect.inflate(blur, blur);
-            let common = builder.common_properties(rect.union(&shadow_rect), &style);
+            let clip_rect = match clip_mode {
+                // Inset shadows are always inside the rect.
+                BoxShadowClipMode::Inset => rect,
+                // Match webrender's `fn add_box_shadow` in box_shadow.rs logic:
```
Comment (yezhizhen) [inline components/layout/display_list/mod.rs]: > Where does this code originate from? It would be good to indicate that in the comment, I think.

I already added it here. @mrobinson

File: components/layout/display_list/mod.rs [hunk 3]
```diff
@@ -1902,10 +1902,24 @@ impl<'a> BuilderForBoxFragment<'a> {
...
+                // shadow_rect = rect.translate(offset).inflate(spread_amount, spread_amount)
+                // blur_offset = (BLUR_SAMPLE_SCALE * blur).ceil()  (BLUR_SAMPLE_SCALE = 3.0)
+                // dest_rect = shadow_rect.inflate(blur_offset, blur_offset)
+                BoxShadowClipMode::Outset => {
+                    let blur_offset = (blur * 3.0).ceil();
+                    let dest_rect = rect
+                        .translate(offset)
+                        .inflate(spread, spread)
+                        .inflate(blur_offset, blur_offset);
+                    rect.union(&dest_rect)
```
Comment (mrobinson) [inline components/layout/display_list/mod.rs]: Could you just do something like this:

```rust
            let clip_rect = match clip_mode {
                // Inset shadows are always inside the rect.
                BoxShadowClipMode::Inset => rect,
                // Match webrender's `fn add_box_shadow` in box_shadow.rs logic:
                //
                // shadow_rect = rect.translate(offset).inflate(spread_amount, spread_amount)
                // blur_offset = (BLUR_SAMPLE_SCALE * blur).ceil()  (BLUR_SAMPLE_SCALE = 3.0)
                // dest_rect = shadow_rect.inflate(blur_offset, blur_offset)
                BoxShadowClipMode::Outset => {
                    let offset = LayoutVector2D::new(
                        box_shadow.base.horizontal.px(),
                        box_shadow.base.vertical.px(),
                    );
                    let inflation = 
                        box_shadow.spread.px() +
                        (3.0 * box_shadow.base.blur.px());
                    rect
                        .translate(offset))
                        .inflate(inflation, inflation)
                },
            };
            let common = builder.common_properties(clip_rect, &style);
```

I suspect you might not need to union the two rectangles and also some of these variables are only used by the non-inset path.

Comment (yezhizhen) [reply components/layout/display_list/mod.rs]: > also some of these variables are only used by the non-inset path.

Ah. Instead, I just realise we can replace some redundant computation for params in `push_box_shadow` right below.

**Comment by yezhizhen** [comment]
Successful [try](https://github.com/servo/servo/actions/runs/24957568268).

File: components/layout/display_list/mod.rs [hunk 4]
```diff
@@ -1902,21 +1902,27 @@ impl<'a> BuilderForBoxFragment<'a> {
...
-            let spread_rect = shifted.inflate(spread, spread);
-            let shadow_rect = spread_rect.inflate(blur, blur);
-            let common = builder.common_properties(rect.union(&shadow_rect), &style);
+            let clip_rect = match clip_mode {
+                // Inset shadows are always inside the rect.
+                BoxShadowClipMode::Inset => rect,
+                // Match webrender's box_shadow.rs Gaussian blur inflation.
+                // (BLUR_SAMPLE_SCALE * blur).ceil(). BLUR_SAMPLE_SCALE is 3.0.
+                BoxShadowClipMode::Outset => {
+                    let blur_offset = (blur * 3.0).ceil();
```
Comment (mrobinson) [inline components/layout/display_list/mod.rs]: Let's not call this `blur_offset` please since it's an expansion (not an offset / translation) and it's a confusing name collision with the real blur offset.


```suggestion
                    let extra_size_from_blur = (blur * 3.0).ceil();
```

**Review by mrobinson — APPROVED** [review]
Thanks. One minor nit before landing:

File: components/layout/display_list/mod.rs (hunk 4 above)
Comment (yezhizhen) [reply components/layout/display_list/mod.rs]: https://github.com/servo/webrender/blob/e1c924ebad9ffdfe8c8c606aba77eb3f888c396a/webrender%2Fsrc%2Fbox_shadow.rs#L476-L477

That is how it is called in webrender tho. I just copied the name.

WDYT?

Comment (mrobinson) [reply components/layout/display_list/mod.rs]: WebRender doesn't have to deal with the name collision from the CSS blur offset, so I think we should look to be less confusing here and just name it more clearly than WebRender does.
