### PR TITLE
devtools: Respect SOURCE_DATE_EPOCH for build_id

### LINKED ISSUE #44458: devtools BUILD_ID does not honor SOURCE_DATE_EPOCH
**Describe the bug:**
https://github.com/servo/servo/blob/main/components/devtools/build.rs unconditionally uses the current time for BUILD_ID. It should use [SOURCE_DATE_EPOCH](https://reproducible-builds.org/docs/source-date-epoch/) if it is set.

### PR DESCRIPTION
**Pull request by jschwe**
We are probably not anywhere close to reproducible builds, but we should try to follow best practices where trivially possible.
See also: https://reproducible-builds.org/docs/source-date-epoch/

Firefox devtools expects the build_id to be provided in a datetime specific format.
This PR also switches the time to UTC instead of `Local`, since there seems to be no clear reason to use Local, and SOURCE_DATE_EPOCH is UTC.

Testing: No functional changes, the devtools build_id is not covered by any tests.
Fixes: #44458

### CODE REVIEW

File: components/devtools/build.rs [hunk 1]
```diff
@@ -8,13 +8,16 @@ use std::{env, fs};
...
     let path = Path::new(&env::var_os("OUT_DIR").unwrap()).join("build_id.rs");
-    fs::write(
-        path,
-        format!(
-            "const BUILD_ID: &str = \"{}\";",
-            Local::now().format("%Y%m%d%H%M%S")
-        ),
-    )
-    .unwrap();
+    let timestamp = env::var_os("SOURCE_DATE_EPOCH")
```
Comment (jschwe) [inline components/devtools/build.rs]: I guess we might want to parse this into chrono, if we wanted to format the build id in some standard way. But it's a bit unclear to me where the build_id is actually exposed in devtools, so perhaps some input from people familiar with devtools on the use case would also be nice.

Comment (jdm) [reply components/devtools/build.rs]: It's sent as one property in the description of the device hosting the devtools server in https://github.com/servo/servo/blob/464ae8204f42c09d98004d2497496205eb6ceefe/components/devtools/actors/device.rs#L62 . It only matters in this particular check for whether a build is too recent to connect: https://searchfox.org/firefox-main/rev/be31b3948198286e39a9855e414823cb17b6e94c/devtools/client/shared/remote-debugging/version-checker.js#133-139

Comment (jschwe) [reply components/devtools/build.rs]: Thanks for the link! I updated the PR to take that into account. The other notable change is that I switched to UTC since that is what SOURCE_DATE_EPOCH is based on. That shouldn't affect devtools in any way though I think.

**Review by jdm — APPROVED** [review]
