### PR TITLE
script: Avoid double borrow crash on iframe focus

### LINKED ISSUE #35543: Segfault when trying to load HCaptcha at Discord login
**Describe the bug:**
Servo segfaults when logging into discordapp.com at the point it tries to load hcaptcha.

**To Reproduce:**
1. Go to https://discordapp.com
2. Login
3. Click on the HCaptcha checkbox

**Platform:**
macOS 15.3.1 (24D70) aarch64
Servo Nightly 0.0.1-29e0fad

```
cd /Applications/Servo.app/Contents/MacOS
satadru@mbp183 MacOS % ./servo
2025-02-19 08:23:59.766 servo[11448:1377841] +[IMKClient subclass]: chose IMKClient_Modern
2025-02-19 08:23:59.766 servo[11448:1377841] +[IMKInputSession subclass]: chose IMKInputSession_Modern
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
[2025-02-19T13:24:07Z ERROR script::dom::bindings::error] Error at https://discord.com/webflow-scripts/newHomepage.js:1:9067 IntersectionObserver is not defined
2025-02-19 08:24:07.993 osascript[11464:1378447] +[IMKClient subclass]: chose IMKClient_Modern
2025-02-19 08:24:08.080 osascript[11464:1378447] +[IMKInputSession subclass]: chose IMKInputSession_Modern
2025-02-19 08:24:10.496 osascript[11467:1378512] +[IMKClient subclass]: chose IMKClient_Modern
2025-02-19 08:24:10.573 osascript[11467:1378512] +[IMKInputSession subclass]: chose IMKInputSession_Modern
[2025-02-19T13:24:18Z ERROR script::dom::dedicatedworkerglobalscope] error loading script blob:https://newassets.hcaptcha.com/5e531685-c5d9-4a85-bdc5-92f7f38f2b0b (Internal("InvalidFileID"))
(new Error("", "https://newassets.hcaptcha.com/c/b3279e2c5bd762b7a2a6c53d0c86b20e2ac30195f33627d597a48377d7e83d9a/hsw.js line 1 > eval line 1 > eval line 1 > eval", 1))
already borrowed: BorrowMutError (thread Script(1,2), at components/script/dom/document.rs:3090)
[2025-02-19T13:24:19Z ERROR servoshell::panic_hook] already borrowed: BorrowMutError
panic in a function that cannot unwind (thread Script(1,2), at core/src/panicking.rs:221)
[2025-02-19T13:24:19Z ERROR servoshell::panic_hook] panic in a function that cannot unwind
thread caused non-unwinding panic. aborting.
Redirecting call to abort() to mozalloc_abort

Caught signal 11 in thread "Script(1,2)"
   0: <servoshell::backtrace::Print as core::fmt::Debug>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: servoshell::backtrace::print
   4: servoshell::crash_handler::install::handler
   5: __sigtramp
   6: _mozalloc_abort
   7: _abort
   8: std::sys::pal::unix::abort_internal
   9: std::panicking::rust_panic_with_hook
  10: std::panicking::begin_panic_handler::{{closure}}
  11: std::sys::backtrace::__rust_end_short_backtrace
  12: _rust_begin_unwind
  13: core::panicking::panic_nounwind_fmt
  14: core::panicking::panic_nounwind
  15: core::panicking::panic_cannot_unwind
  16: script::window_named_properties::get_own_property_descriptor
  17: __ZNK22ForwardingProxyHandler24getOwnPropertyDescriptorEP9JSContextN2JS6HandleIP8JSObjectEENS3_INS2_11PropertyKeyEEENS2_13MutableHandleIN7mozilla5MaybeINS2_18PropertyDescriptorEEEEE
  18: __ZNK2js16BaseProxyHandler3getEP9JSContextN2JS6HandleIP8JSObjectEENS4_INS3_5ValueEEENS4_INS3_11PropertyKeyEEENS3_13MutableHandleIS8_EE
  19: __ZNK22ForwardingProxyHandler3getEP9JSContextN2JS6HandleIP8JSObjectEENS3_INS2_5ValueEEENS3_INS2_11PropertyKeyEEENS2_13MutableHandleIS7_EE
  20: __ZN2js5Proxy3getEP9JSContextN2JS6HandleIP8JSObjectEENS4_INS3_5ValueEEENS4_INS3_11PropertyKeyEEENS3_13MutableHandleIS8_EE
  21: __ZN2js17NativeGetPropertyEP9JSContextN2JS6HandleIPNS_12NativeObjectEEENS3_INS2_5ValueEEENS3_INS2_11PropertyKeyEEENS2_13MutableHandleIS7_EE
  22: script::dom::windowproxy::get
  23: __ZNK19WrapperProxyHandler3getEP9JSContextN2JS6HandleIP8JSObjectEENS3_INS2_5ValueEEENS3_INS2_11PropertyKeyEEENS2_13MutableHandleIS7_EE
  24: __ZN2js23ProxyGetPropertyByValueEP9JSContextN2JS6HandleIP8JSObjectEENS3_INS2_5ValueEEENS2_13MutableHandleIS7_EE
zsh: segmentation fault  ./servo
```

Image

Clicking on the checkbox causes the segfault:

Image

More debug info:

[servo-macos-discord-hcaptcha-segfault.log.txt](https://github.com/user-attachments/files/18869177/servo-macos-discord-hcaptcha-segfault.log.txt)

### PR DESCRIPTION
**Pull request by leftmostcat**
When an iframe with an `onfocus` event is focused, servo will crash due to attempting a mutable borrow on an already-borrowed `RefCell`. Avoid this by providing a new root for the needed `Element` borrow.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #35543

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

File: components/script/script_thread.rs [hunk 1]
```diff
@@ -2498,10 +2498,18 @@ impl ScriptThread {
...
-            document.request_focus(Some(iframe.element.upcast()), FocusType::Parent, can_gc);
-        }
+        let Some(iframe_element_root) = ({
+            // Enclose `iframes()` call and create a new root to avoid retaining
+            // borrow.
+            let iframes = document.iframes();
+            iframes
+                .get(browsing_context_id)
+                .map(|iframe| DomRoot::from_ref(iframe.element.upcast()))
+        }) else {
```
Comment (sagudev) [inline components/script/script_thread.rs:2508]: I think we can remove parenthesis:

```suggestion
        let Some(iframe_element_root) = {
            // Enclose `iframes()` call and create a new root to avoid retaining
            // borrow.
            let iframes = document.iframes();
            iframes
                .get(browsing_context_id)
                .map(|iframe| DomRoot::from_ref(iframe.element.upcast()))
        } else {
```

Comment (leftmostcat) [reply components/script/script_thread.rs:2508]: The parentheses were initially added because without them, I get a build error: "error: right curly brace `}` before `else` in a `let...else` statement not allowed" with suggested fix of "wrap the expression in parentheses".

Comment (sagudev) [reply components/script/script_thread.rs:2508]: Right.

**Review by sagudev — APPROVED** [review]
