### PR TITLE
Fix panic in formelement.rs

### LINKED ISSUE #37430: panic: already borrowed: BorrowMutError (at components/script/dom/htmlformelement.rs:1333)
Minimal testcase:

```html
<!DOCTYPE html>
<div id="container">
  <form id="formId"></form>
</div>
<input id="inputId" required form="formId" oninvalid="container.remove()">
<script>
  formId.checkValidity();
</script>
```

System: Linux
Version: Servo 0.0.1-73c286423
Command: `./servo/servo`

```
already borrowed: BorrowMutError (thread Script(1,1), at components/script/dom/htmlformelement.rs:1333)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::cell::panic_already_borrowed
   8: script::dom::htmlformelement::FormControl::reset_form_owner
   9: script::dom::document::Document::reset_form_owner_for_listeners
  10: script::dom::document::Document::unregister_element_id
  11: <script::dom::element::Element as script::dom::virtualmethods::VirtualMethods>::unbind_from_tree
  12: <script::dom::htmlelement::HTMLElement as script::dom::virtualmethods::VirtualMethods>::unbind_from_tree
  13: <script::dom::htmlformelement::HTMLFormElement as script::dom::virtualmethods::VirtualMethods>::unbind_from_tree
  14: script::dom::node::Node::complete_remove_subtree
  15: script::dom::node::Node::remove
  16: script::dom::node::Node::remove_self
  17: script_bindings::codegen::GenericBindings::ElementBinding::Element_Binding::remove::{{closure}}
  18: mozjs::panic::wrap_panic
  19: script_bindings::codegen::GenericBindings::ElementBinding::Element_Binding::remove
  20: CallJitMethodOp
  21: script_bindings::utils::generic_call
  22: script_bindings::utils::generic_method
  23: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  24: _ZN2js9InterpretEP9JSContextRNS_8RunStateE
  25: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  26: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  27: _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
  28: _ZN2JS4CallEP9JSContextNS_6HandleINS_5ValueEEES4_RKNS_16HandleValueArrayENS_13MutableHandleIS3_EE
  29: script::dom::event::inner_invoke
  30: script::dom::event::invoke
  31: script::dom::event::Event::dispatch
  32: script::dom::eventtarget::EventTarget::fire_event_with_params
  33: script::dom::htmlformelement::HTMLFormElement::static_validation
  34: <script::dom::htmlformelement::HTMLFormElement as script_bindings::codegen::GenericBindings::HTMLFormElementBinding::HTMLFormElement_Binding::HTMLFormElementMethods<script::dom::bindings::codegen::DomTypeHolder::DomTypeHolder>>::CheckValidity
  35: script_bindings::codegen::GenericBindings::HTMLFormElementBinding::HTMLFormElement_Binding::checkValidity::{{closure}}
  36: mozjs::panic::wrap_panic
  37: script_bindings::codegen::GenericBindings::HTMLFormElementBinding::HTMLFormElement_Binding::checkValidity
  38: CallJitMethodOp
  39: script_bindings::utils::generic_call
  40: script_bindings::utils::generic_method
  41: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  42: _ZN2js9InterpretEP9JSContextRNS_8RunStateE
  43: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  44: _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEENS3_IP8JSObjectEENS2_13MutableHandleINS2_5ValueEEE
  45: _Z16JS_ExecuteScriptP9JSContextN2JS6HandleIP8JSScriptEENS1_13MutableHandleINS1_5ValueEEE
  46: script::dom::globalscope::GlobalScope::evaluate_script_on_global_with_result
  47: script::dom::htmlscriptelement::HTMLScriptElement::execute
  48: script::dom::htmlscriptelement::HTMLScriptElement::prepare
  49: script::dom::servoparser::ServoParser::parse_sync
  50: <script::dom::servoparser::ParserContext as net_traits::FetchResponseListener>::process_response_chunk
  51: script::script_thread::ScriptThread::handle_msg_from_script
  52: script::script_thread::ScriptThread::handle_msgs::{{closure}}
  53: script::script_thread::ScriptThread::handle_msgs
  54: std::sys::backtrace::__rust_begin_short_backtrace
  55: core::ops::function::FnOnce::call_once{{vtable.shim}}
  56: std::sys::pal::unix::thread::Thread::new::thread_start
  57: start_thread
             at ./nptl/pthread_create.c:447:8
  58: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
```

### PR DESCRIPTION
**Pull request by webbeef**
Use borrowing directly with iterators instead of holding the borrowed value for a longer scope.

Testing: Covered by existing tests, and manual testing with the test case from https://github.com/servo/servo/issues/37430
Fixes: https://github.com/servo/servo/issues/37430

### CODE REVIEW

**Comment by jdm** [comment]
Can we add the testcase as a new crashtest? https://web-platform-tests.org/writing-tests/crashtest.html

**Comment by webbeef** [comment]
> Can we add the testcase as a new crashtest? https://web-platform-tests.org/writing-tests/crashtest.html

Sure. Should it be under `tests/wpt/mozilla` or shared with others?

**Comment by jdm** [comment]
/html/semantics/forms/the-form-element/ looks reasonable.

**Comment by webbeef** [comment]
> /html/semantics/forms/the-form-element/ looks reasonable.

done.

**Review by jdm — APPROVED** [review]
This can merge with a `./mach update-manifest`.

File: components/script/dom/htmlformelement.rs [hunk 1]
```diff
@@ -565,7 +563,7 @@ impl HTMLFormElementMethods<crate::DomTypeHolder> for HTMLFormElement {
         }
 
         // Step 3
-        for child in controls.iter() {
+        for child in self.controls.borrow().iter() {
```
Comment (simonwuelker) [inline components/script/dom/htmlformelement.rs:566]: Maybe my mental model of the borrow lifetimes here is wrong, but wouldn't the borrow in the for loop from Step 2. still be active right until Step 3? In other words, what does calling `.borrow` twice in both step 2 and step 3 achieve?

Comment (rodio) [reply components/script/dom/htmlformelement.rs:566]: I don't know, but I maybe this is done to achieve uniformity and to potentially avoid future "already borrowed" panics. Since we need to remove the `let controls = self.controls.borrow()` statement at the beginning of the function `static_validation()` in order to fix this panic and do `self.controls.borrow().iter()` inline instead, the author decided to make it uniform and remove the `let controls = self.controls.borrow()` bindings everywhere.
