### PR TITLE
script: Update name validation for attribute, element, and doctype

### LINKED ISSUE #37746: Update validation of element, attribute, and doctype names
A recent change (https://github.com/whatwg/dom/pull/1079) brought new rules for validation of element, attribute and doctype names. The current implementation fails to pass the corresponding WPT testcases (eg. https://wpt.fyi/results/dom/nodes/Document-createAttribute.html?product=servo)

### PR DESCRIPTION
**Pull request by minghuaw**
A recent update in the spec (https://github.com/whatwg/dom/pull/1079) introduced new rules for name validation of attribute, element, and doctype. This PR implements the new name validation rules in `components/script/dom/bindings/domname.rs`. The old XML name validation rules are not fully removed because there remains a few usage of it in `ProcessingInstructions` and `xpath`.

Testing: Covered by WPT tests
Fixes: #37746

### CODE REVIEW

**Comment by yezhizhen** [comment]
You need to `git commit -s` to sign off, for each commits to pass DCO.

**Comment by minghuaw** [comment]
Below is a summary of how the current draft performs on a few related WPT test files (the live version)

| WPT Test File | Status (Passed/Total) |
|----------------|--------|
|`wpt/dom/nodes/Document-createAttribute.html` | 36/36 |
|`wpt/dom/nodes/Document-createElement.html` | 147/147 |
|`wpt/dom/nodes/Document-createElementNS.html` | 575/596 |
|`wpt/dom/nodes/name-validation.html` | 5/5 |
|`wpt/dom/nodes/DOMImplementation-createDocumentType.html` | 82/82 |

The test cases that are still failing in `wpt/dom/nodes/Document-createElementNS.html` seem to be caused by confusion and/or bug in the testing implementation (see https://github.com/web-platform-tests/wpt/issues/53464).

Would this draft be considered good enough for review or is it better to wait until it passes all `wpt/dom/nodes/Document-createElementNS.html` test cases?

File: components/script/dom/document.rs [hunk 1]
```diff
@@ -120,9 +123,7 @@ use crate::dom::bindings::str::{DOMString, USVString};
 use crate::dom::bindings::trace::{HashMapTracedValues, NoTrace};
 #[cfg(feature = "webgpu")]
 use crate::dom::bindings::weakref::WeakRef;
-use crate::dom::bindings::xmlname::{
-    matches_name_production, namespace_from_domstring, validate_and_extract,
```
Comment (xiaochengh) [inline components/script/dom/document.rs:124]: Are these methods still being used?

If not, let's remove them. Otherwise we need to somehow unify them with the new methods introduced by this PR.

The main consideration is to avoid maintaining multiple mechanisms for the same thing.

Comment (minghuaw) [reply components/script/dom/document.rs:124]: `matches_name_production` is still being used in two places that still requires XML naming rules (`CreateProcessingInstruction` and `set_custom_attribute`, which do require XML naming after the spec  update see https://github.com/whatwg/dom/pull/1079 and https://html.spec.whatwg.org/multipage/dom.html#custom-data-attribute).

`namespace_from_domstring` is just a convenient conversion that's used in many places, but we could also move it into the `name_validation` mod.

There remains one usage of `xmlname::validate_and_extract` during evaluation of xpath, which I assume that XML naming rules is used. The relevant docs are not well maintained (see https://dom.spec.whatwg.org/#xpath)

File: components/script/dom/bindings/name_validation.rs [hunk 2]
```diff
@@ -0,0 +1,242 @@
...
+            c,
+            '\u{0009}' |
+                '\u{000A}' |
+                '\u{000C}' |
+                '\u{000D}' |
+                '\u{0020}' |
+                '\u{0000}' |
+                '\u{002F}' |
+                '\u{003E}'
+        )
```
Comment (xiaochengh) [inline components/script/dom/bindings/name_validation.rs]:
```suggestion
        c.is_ascii_whitespace() || matches!(
            c,
                '\u{0000}' |
                '\u{002F}' |
                '\u{003E}'
        )
```
Ditto below.

File: components/script/dom/bindings/name_validation.rs [hunk 3]
```diff
@@ -0,0 +1,242 @@
...
+
+//! Functions for validating names
+
+use html5ever::{LocalName, Namespace, Prefix};
+use script_bindings::error::{Error, Fallible};
+use script_bindings::str::DOMString;
+
+use crate::dom::bindings::xmlname::namespace_from_domstring;
+
+/// See <https://infra.spec.whatwg.org/#xml-namespace>
```
Comment (xiaochengh) [inline components/script/dom/bindings/name_validation.rs]:
```suggestion
/// <https://infra.spec.whatwg.org/#xml-namespace>
```
Ditto below.

File: components/script/dom/document.rs (hunk 1 above)
Comment (xiaochengh) [reply components/script/dom/document.rs:124]: It appears that after this change, usage of `xmlname` will be the special case. We need to decide the fate of the exposed functions there:
1. `matches_name_production` is well-scoped by XML and should remain there
2. `namespace_from_domstring` seems still widely used and should be moved to the new file
3. `validate_and_extract` and `validate_and_extract_qualified_name` no longer implement the spec, and in the best case should be removed. Could you list out links to all the the renaming usages and let's decide?

File: components/script/dom/bindings/name_validation.rs [hunk 4]
```diff
@@ -0,0 +1,242 @@
+/* This Source Code Form is subject to the terms of the Mozilla Public
```
Comment (xiaochengh) [inline components/script/dom/bindings/name_validation.rs]: How about renaming this file `domname.rs` to be consistent with the existing `xmlname.rs`?

File: components/script/dom/bindings/name_validation.rs [hunk 5]
```diff
@@ -0,0 +1,242 @@
...
+ * License, v. 2.0. If a copy of the MPL was not distributed with this
+ * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
+
+//! Functions for validating names
```
Comment (xiaochengh) [inline components/script/dom/bindings/name_validation.rs]:
```suggestion
//! Functions for validating names as defined in the DOM Standard: https://dom.spec.whatwg.org/
```

File: components/script/dom/document.rs (hunk 1 above)
Comment (minghuaw) [reply components/script/dom/document.rs:124]: >     3. `validate_and_extract` and `validate_and_extract_qualified_name` no longer implement the spec, and in the best case should be removed. Could you list out links to all the the renaming usages and let's decide?

This is the only remaining usage of the `xmlname::validate_and_extract` `script::xpath::eval` https://github.com/servo/servo/blob/e6090173c97a1bf73eec7f255e07dbfe1db16644/components/script/xpath/eval.rs#L270 We could probably move `validate_and_extract` and `validate_and_extract_qualified_name` into this file?

File: components/script/dom/bindings/name_validation.rs (hunk 4 above)
Comment (minghuaw) [reply components/script/dom/bindings/name_validation.rs]: Sounds good. It was named `"name_validation"` simply because that was the name of the section in the spec

File: components/script/dom/bindings/name_validation.rs (hunk 2 above)
Comment (minghuaw) [reply components/script/dom/bindings/name_validation.rs]: Updated the remaining in [67a6afb](https://github.com/servo/servo/pull/37747/commits/67a6afb3940582d82fdb3f83daa5934a333f6efa)

File: components/script/dom/bindings/name_validation.rs (hunk 3 above)
Comment (minghuaw) [reply components/script/dom/bindings/name_validation.rs]: Updated the remaining in [5311e94](https://github.com/servo/servo/pull/37747/commits/5311e9427adf62b9e0c6e40f255158b6707bf279)

File: components/script/dom/bindings/name_validation.rs (hunk 4 above)
Comment (minghuaw) [reply components/script/dom/bindings/name_validation.rs]: Done in [c4d4bf9](https://github.com/servo/servo/pull/37747/commits/c4d4bf9f015085d3d649ce419b969f0c9af41923)

File: components/script/dom/document.rs (hunk 1 above)
Comment (minghuaw) [reply components/script/dom/document.rs:124]: Moved `validate_and_extract` and `validate_and_extract_qualified_name` from `script/dom/bindings/xmlname.rs` to `script/xpath/eval.rs` and restricted their visibility to private. See commit [73f22a5](https://github.com/servo/servo/pull/37747/commits/73f22a59eec2d4b20af4a2563f0888b57dac22d1)

**Review by xiaochengh — APPROVED** [review]
LGTM, thanks!

**Comment by yezhizhen** [comment]
Remember to update PR message as well, which would be the commit message in main.

**Comment by xiaochengh** [comment]
Please let me know when this is ready for merging, thanks

**Comment by minghuaw** [comment]
> Remember to update PR message as well, which would be the commit message in main.

@yezhizhen Do you mind taking a look at the updated PR message? Just trying to see if it's explanatory enough for someone who didn't review the changes? Thanks

**Comment by yezhizhen** [comment]
@minghuaw It is very concise and understandable to me.

**Comment by minghuaw** [comment]
> Please let me know when this is ready for merging, thanks

@xiaochengh It's ready for merging. Thanks

**Comment by yezhizhen** [comment]
@minghuaw Seems Lint issue after your rebase.

**Comment by minghuaw** [comment]
> @minghuaw Seems Lint issue after your rebase.

Thanks. Should be fixed now

**Comment by yezhizhen** [comment]
@minghuaw There are still tests that need to be updated.

You can just update `/dom/nodes/attributes.html.ini` and `/dom/nodes/DOMImplementation-createDocument.html.ini`.

**Comment by minghuaw** [comment]
> @minghuaw There are still tests that need to be updated.
> 
> You can just delete `/dom/nodes/attributes.html.ini` and `/dom/nodes/DOMImplementation-createDocument.html.ini`.

It didn't pass all subtests under `DOMImplementation-createDocument.html`. So I ended up only modifying the `DOMImplementation-createDocument.html.ini`

**Comment by minghuaw** [comment]
Shall we wait a bit before merging this? There seems to be more upstream changes coming to fix the misalignment between the WPT tests and the spec. See https://github.com/whatwg/dom/issues/1387

**Comment by yezhizhen** [comment]
> Shall we wait a bit before merging this? There seems to be more upstream changes coming to fix the misalignment between the WPT tests and the spec. See [whatwg/dom#1387](https://github.com/whatwg/dom/issues/1387)

I think it's fine. There will be automatic syncing and updating happening regularly https://github.com/servo/servo/pull/37901.

**Comment by yezhizhen** [comment]
https://github.com/servo/servo/pull/37901
I recommend you rebase again and update test results again with latest wpt sync..
@minghuaw

**Comment by minghuaw** [comment]
Given that there is still active discussion in the upstream about the spec and aligning the WPT test cases with the spec, I think we could probably wait a few days to avoid merging unnecessary changes

**Comment by xiaochengh** [comment]
Sounds good, let's wait for the discussion to settle.

**Comment by minghuaw** [comment]
Here's the updated WPT test result: https://github.com/minghuaw/servo/actions/runs/16188707259/job/45702433544.

@xiaochengh This is ready to get merged
