### PR TITLE
fonts: Remove web fonts when their stylesheet is removed

### LINKED ISSUE #15139: We never remove web fonts from the font cache.
This is not only a leak, but also may produce incorrect styling. Consider the following code:

```html
<style>
@font-face {
    name: foo;
    /* ... */
}
</style>
<style>
div {
    font-family: foo, arial;
}
</style>
<div class="foo">
TEXT
</div>
<script>
let s = document.querySelector('style');
s.parentNode.removeChild(s);
</script>
```

We should render the text in Arial, but as far as I know we'd render it with the `foo` font.

I remember to have seen an issue about the font cache leak, but I couldn't find it, so I'm filling this one.

### PR DESCRIPTION
**Pull request by mrobinson**
This is the first part of ensuring that unused fonts do not leak. This
change makes it so that when a stylesheet is removed, the corresponding
web fonts are removed from the `FontContext`.

Note: WebRender assets are still leaked, which was the situation before
for all fonts. A followup change will fix this issue.

Fixes #15139.

Signed-off-by: Martin Robinson <mrobinson@igalia.com>
Co-authored-by: Mukilan Thiyagarajan <mukilan@igalia.com>

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #15139.
- [x] There are tests for these changes

### CODE REVIEW

**Comment by mrobinson** [comment]
I have added a test for this change.

File: components/gfx/font_store.rs [hunk 1]
```diff
@@ -8,22 +8,96 @@ use std::sync::Arc;
...
+        new_template: FontTemplate,
+    ) -> bool {
+        // Abort processing this web font if the originating stylesheet was removed.
+        if self.font_load_cancelled_for_stylesheet(&state.stylesheet) {
+            return false;
+        }
+
+        let family_name = state.css_font_face_descriptors.family_name.clone();
+        self.families
+            .entry(family_name.clone())
```
Comment (mukilan) [inline components/gfx/font_store.rs:91]:
```suggestion
            .entry(family_name))
```

File: components/gfx/font_store.rs [hunk 2]
```diff
@@ -127,4 +201,14 @@ impl FontTemplates {
         self.templates
             .push(Arc::new(AtomicRefCell::new(new_template)));
     }
+
+    pub(crate) fn remove_add_templates_for_stylesheet(
```
Comment (mukilan) [inline components/gfx/font_store.rs:205]:
```suggestion
    pub(crate) fn remove_templates_for_stylesheet(
```

**Review by mukilan — APPROVED** [review]

File: components/gfx/font_store.rs (hunk 2 above)
Comment (mrobinson) [reply components/gfx/font_store.rs]: :sweat_smile: Fixed this one.

File: components/gfx/font_store.rs (hunk 1 above)
Comment (mrobinson) [reply components/gfx/font_store.rs]: Fixed this as well as a couple other places where we didn't need to pass as a reference.
