### PR TITLE
script: Wrap debugger global scope pointers in debuggee's realm.

### LINKED ISSUE #44385: Assertion failure: `gcMarker->tracingCompartment == comp` in debug-mozjs
1. ./mach build -d --debug-mozjs
2. ./mach test-wpt /WebCryptoAPI/digest/kangarootwelve.tentative.https.any.worker.html

```
pid:28891 [28891] Assertion failure: gcMarker->tracingCompartment == comp, at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/Marking.cpp:222
 0:07.95 pid:28891 #01: void CheckMarkedThing<JSObject>(js::GCMarker*, JSObject*)[/Users/jdm/src/servo/target/debug/servoshell +0x6a393d4]
 0:07.96 pid:28891 #02: void js::gc::MarkingTracerT<0u>::onEdge<JSObject>(JSObject**, char const*)[/Users/jdm/src/servo/target/debug/servoshell +0x6a38fd0]
 0:07.96 pid:28891 #03: js::GenericTracerImpl<js::gc::MarkingTracerT<0u>>::onObjectEdge(JSObject**, char const*)[/Users/jdm/src/servo/target/debug/servoshell +0x6a92d60]
 0:07.96 pid:28891 #04: js::gc::TraceEdgeInternal(JSTracer*, JSObject**, char const*)[/Users/jdm/src/servo/target/debug/servoshell +0x5d80810]
 0:07.96 pid:28891 #05: void TraceExternalEdgeHelper<JSObject*>(JSTracer*, JSObject**, char const*)[/Users/jdm/src/servo/target/debug/servoshell +0x6a33258]
 0:07.97 pid:28891 #06: js::gc::TraceExternalEdge(JSTracer*, JSObject**, char const*)[/Users/jdm/src/servo/target/debug/servoshell +0x6a331b8]
 0:07.97 pid:28891 #07: void JS::TraceEdge<JSObject*>(JSTracer*, JS::Heap<JSObject*>*, char const*)[/Users/jdm/src/servo/target/debug/servoshell +0x7c37c44]
 0:07.97 pid:28891 #08: CallObjectTracer[/Users/jdm/src/servo/target/debug/servoshell +0x7c37b98]
 0:07.99 pid:28891 #09: script_bindings::trace::trace_object::hbf44ca55e0037072[/Users/jdm/src/servo/target/debug/servoshell +0x5ae3e94]
 0:08.00 pid:28891 #10: script_bindings::trace::trace_reflector::h92d314b86a85ecf2[/Users/jdm/src/servo/target/debug/servoshell +0x3bd8ed4]
 0:08.00 pid:28891 #11: _$LT$script_bindings..root..Dom$LT$T$GT$$u20$as$u20$mozjs_sys..trace..Traceable$GT$::trace::hb413b938ae30f84f[/Users/jdm/src/servo/target/debug/servoshell +0x2ecda10]
 0:08.00 pid:28891 #12: _$LT$script..dom..workers..dedicatedworkerglobalscope..DedicatedWorkerGlobalScope$u20$as$u20$mozjs_sys..trace..Traceable$GT$::trace::h6d9004f7e31e84e8[/Users/jdm/src/servo/target/debug/servoshell +0x33a4f40]
 0:08.00 pid:28891 #13: script_bindings::codegen::GenericBindings::DedicatedWorkerGlobalScopeBinding::DedicatedWorkerGlobalScope_Binding::_trace::_$u7b$$u7b$closure$u7d$$u7d$::h296053ff38c0bb49[/Users/jdm/src/servo/target/debug/servoshell +0x40e8d70]
 0:08.01 pid:28891 #14: core::ops::function::impls::_$LT$impl$u20$core..ops..function..FnOnce$LT$A$GT$$u20$for$u20$$RF$mut$u20$F$GT$::call_once::h0369a0f05ad5ad27[/Users/jdm/src/servo/target/debug/servoshell +0x5c51fa0]
 0:08.02 pid:28891 #15: _$LT$core..panic..unwind_safe..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h7753eded3e75cd79[/Users/jdm/src/servo/target/debug/servoshell +0x5c40d58]
 0:08.03 pid:28891 #16: std::panicking::catch_unwind::do_call::h31c4fdbfad0fb406[/Users/jdm/src/servo/target/debug/servoshell +0x5c4dfe4]
 0:08.03 pid:28891 #17: __rust_try[/Users/jdm/src/servo/target/debug/servoshell +0x5c54224]
 0:08.04 pid:28891 #18: std::panic::catch_unwind::h9537d83de3c5d8e6[/Users/jdm/src/servo/target/debug/servoshell +0x5c51504]
 0:08.05 pid:28891 #19: mozjs::panic::wrap_panic::hf63c912e6f4d3026[/Users/jdm/src/servo/target/debug/servoshell +0x5c470cc]
 0:08.05 pid:28891 #20: script_bindings::codegen::GenericBindings::DedicatedWorkerGlobalScopeBinding::DedicatedWorkerGlobalScope_Binding::_trace::hbf36b925f42f0f45[/Users/jdm/src/servo/target/debug/servoshell +0x40e8c68]
 0:08.05 pid:28891 #21: JS_GlobalObjectTraceHook(JSTracer*, JSObject*)[/Users/jdm/src/servo/target/debug/servoshell +0x64e7b60]
 0:08.06 pid:28891 #22: JSClass::doTrace(JSTracer*, JSObject*) const[/Users/jdm/src/servo/target/debug/servoshell +0x607a218]
 0:08.06 pid:28891 #23: CallTraceHook(JSTracer*, JSObject*)[/Users/jdm/src/servo/target/debug/servoshell +0x6a891b8]
 0:08.06 pid:28891 #24: bool js::GCMarker::processMarkStackTop<0u>(JS::SliceBudget&)[/Users/jdm/src/servo/target/debug/servoshell +0x6a88354]
 0:08.06 pid:28891 #25: bool js::GCMarker::markOneColor<0u, (js::gc::MarkColor)2>(JS::SliceBudget&)[/Users/jdm/src/servo/target/debug/servoshell +0x6a87890]
 0:08.07 pid:28891 #26: bool js::GCMarker::doMarking<0u>(JS::SliceBudget&, js::gc::ShouldReportMarkTime)[/Users/jdm/src/servo/target/debug/servoshell +0x6a428a0]
 0:08.07 pid:28891 #27: js::GCMarker::markUntilBudgetExhausted(JS::SliceBudget&, js::gc::ShouldReportMarkTime)[/Users/jdm/src/servo/target/debug/servoshell +0x6a1a0c4]
 0:08.07 pid:28891 #28: js::gc::GCRuntime::markUntilBudgetExhausted(JS::SliceBudget&, js::gc::GCRuntime::ParallelMarking, js::gc::ShouldReportMarkTime)[/Users/jdm/src/servo/target/debug/servoshell +0x6a195f4]
 0:08.08 pid:28891 #29: js::gc::GCRuntime::incrementalSlice(JS::SliceBudget&, JS::GCReason, bool)[/Users/jdm/src/servo/target/debug/servoshell +0x6a1db74]
 0:08.08 pid:28891 #30: js::gc::GCRuntime::gcCycle(bool, JS::SliceBudget const&, JS::GCReason)[/Users/jdm/src/servo/target/debug/servoshell +0x6a20b24]
 0:08.08 pid:28891 #31: js::gc::GCRuntime::collect(bool, JS::SliceBudget const&, JS::GCReason)[/Users/jdm/src/servo/target/debug/servoshell +0x6a21c10]
 0:08.09 pid:28891 #32: js::gc::GCRuntime::gcSlice(JS::GCReason, JS::SliceBudget const&)[/Users/jdm/src/servo/target/debug/servoshell +0x6a22784]
 0:08.09 pid:28891 #33: js::gc::GCRuntime::gcIfRequestedImpl(bool)[/Users/jdm/src/servo/target/debug/servoshell +0x6a0e78c]
 0:08.09 pid:28891 #34: js::gc::GCRuntime::gcIfRequested()[/Users/jdm/src/servo/target/debug/servoshell +0x61c8d64]
 0:08.09 pid:28891 #35: MajorGCIfRequested(JSContext*)[/Users/jdm/src/servo/target/debug/servoshell +0x69ad760]
 0:08.10 pid:28891 #36: void* js::gc::CellAllocator::AllocTenuredCell<(js::AllowGC)1>(JSContext*, js::gc::AllocKind)[/Users/jdm/src/servo/target/debug/servoshell +0x69adcc4]
 0:08.10 pid:28891 #37: js::GetterSetter* js::gc::CellAllocator::NewTenuredCell<js::GetterSetter, (js::AllowGC)1, JS::Handle<JSObject*>&, JS::Handle<JSObject*>&>(JSContext*, JS::Handle<JSObject*>&, JS::Handle<JSObject*>&)[/Users/jdm/src/servo/target/debug/servoshell +0x5fa3534]
 0:08.10 pid:28891 #38: js::GetterSetter* js::gc::CellAllocator::NewCell<js::GetterSetter, (js::AllowGC)1, JS::Handle<JSObject*>&, JS::Handle<JSObject*>&>(JSContext*, JS::Handle<JSObject*>&, JS::Handle<JSObject*>&)[/Users/jdm/src/servo/target/debug/servoshell +0x5fa347c]
 0:08.11 pid:28891 #39: js::GetterSetter* JSContext::newCell<js::GetterSetter, (js::AllowGC)1, JS::Handle<JSObject*>&, JS::Handle<JSObject*>&>(JS::Handle<JSObject*>&, JS::Handle<JSObject*>&)[/Users/jdm/src/servo/target/debug/servoshell +0x5f91e40]
 0:08.11 pid:28891 #40: js::GetterSetter::create(JSContext*, JS::Handle<JSObject*>, JS::Handle<JSObject*>)[/Users/jdm/src/servo/target/debug/servoshell +0x5f91de0]
 0:08.11 pid:28891 #41: bool AddOrChangeProperty<(IsAddOrChange)0>(JSContext*, JS::Handle<js::NativeObject*>, JS::Handle<JS::PropertyKey>, JS::Handle<JS::PropertyDescriptor>, js::PropertyResult*)[/Users/jdm/src/servo/target/debug/servoshell +0x6108d1c]
 0:08.12 pid:28891 #42: js::NativeDefineProperty(JSContext*, JS::Handle<js::NativeObject*>, JS::Handle<JS::PropertyKey>, JS::Handle<JS::PropertyDescriptor>, JS::ObjectOpResult&)[/Users/jdm/src/servo/target/debug/servoshell +0x6107b40]
 0:08.12 pid:28891 #43: js::DefineAccessorProperty(JSContext*, JS::Handle<JSObject*>, JS::Handle<JS::PropertyKey>, JS::Handle<JSObject*>, JS::Handle<JSObject*>, unsigned int, JS::ObjectOpResult&)[/Users/jdm/src/servo/target/debug/servoshell +0x6070ffc]
 0:08.12 pid:28891 #44: js::DefineAccessorProperty(JSContext*, JS::Handle<JSObject*>, JS::Handle<JS::PropertyKey>, JS::Handle<JSObject*>, JS::Handle<JSObject*>, unsigned int)[/Users/jdm/src/servo/target/debug/servoshell +0x607151c]
 0:08.12 pid:28891 #45: InitGetterSetterOperation(JSContext*, unsigned char*, JS::Handle<JSObject*>, JS::Handle<JS::PropertyKey>, JS::Handle<JSObject*>)[/Users/jdm/src/servo/target/debug/servoshell +0x5cdbd70]
 0:08.13 pid:28891 #46: js::InitPropGetterSetterOperation(JSContext*, unsigned char*, JS::Handle<JSObject*>, JS::Handle<js::PropertyName*>, JS::Handle<JSObject*>)[/Users/jdm/src/servo/target/debug/servoshell +0x5cd698c]
 0:08.13 pid:28891 #47: js::Interpret(JSContext*, js::RunState&)[/Users/jdm/src/servo/target/debug/servoshell +0x5cc5c04]
 0:08.13 pid:28891 #48: MaybeEnterInterpreterTrampoline(JSContext*, js::RunState&)[/Users/jdm/src/servo/target/debug/servoshell +0x5caf668]
 0:08.13 pid:28891 #49: js::RunScript(JSContext*, js::RunState&)[/Users/jdm/src/servo/target/debug/servoshell +0x5caf0fc]
 0:08.14 pid:28891 #50: js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct, js::CallReason)[/Users/jdm/src/servo/target/debug/servoshell +0x5cafebc]
 0:08.14 pid:28891 #51: InternalCall(JSContext*, js::AnyInvokeArgs const&, js::CallReason)[/Users/jdm/src/servo/target/debug/servoshell +0x5cb0c50]
 0:08.14 pid:28891 #52: js::Call(JSContext*, JS::Handle<JS::Value>, JS::Handle<JS::Value>, js::AnyInvokeArgs const&, JS::MutableHandle<JS::Value>, js::CallReason)[/Users/jdm/src/servo/target/debug/servoshell +0x5cb0df8]
 0:08.15 pid:28891 #53: js::jit::InvokeFunction(JSContext*, JS::Handle<JSObject*>, bool, bool, unsigned int, JS::Value*, JS::MutableHandle<JS::Value>)[/Users/jdm/src/servo/target/debug/servoshell +0x6edfc7c]
 0:08.15 pid:28891 #54: js::jit::InvokeFromInterpreterStub(JSContext*, js::jit::InterpreterStubExitFrameLayout*)[/Users/jdm/src/servo/target/debug/servoshell +0x6ee0018]
 0:08.15 pid:28891 Caught signal 11 in thread "WW:web-platform.test:8443/WebCryptoAPI/digest/kangarootwelve.tentative.https.any.worker.js"
 0:10.39 pid:28891    0: backtrace::backtrace::libunwind::trace
 0:10.39 pid:28891              at /Users/jdm/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.76/src/backtrace/libunwind.rs:117:9
 0:10.39 pid:28891       backtrace::backtrace::trace_unsynchronized
 0:10.39 pid:28891              at /Users/jdm/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.76/src/backtrace/mod.rs:66:14
 0:10.39 pid:28891    1: <servoshell::backtrace::Print as core::fmt::Debug>::fmt
 0:10.39 pid:28891              at /Users/jdm/src/servo/ports/servoshell/backtrace.rs:66:13
 0:10.40 pid:28891    2: core::fmt::rt::Argument::fmt
 0:10.40 pid:28891              at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/core/src/fmt/rt.rs:173:76
 0:10.40 pid:28891       core::fmt::write
 0:10.40 pid:28891              at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/core/src/fmt/mod.rs:1469:25
 0:10.40 pid:28891    3: std::io::default_write_fmt
 0:10.40 pid:28891              at /Users/jdm/.rustup/toolchains/1.92.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/io/mod.rs:639:11
 0:10.41 pid:28891    4: std::io::Write::write_fmt
 0:10.41 pid:28891              at /Users/jdm/.rustup/toolchains/1.92.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/io/mod.rs:1954:13
 0:10.41 pid:28891    5: servoshell::backtrace::print
 0:10.41 pid:28891              at /Users/jdm/src/servo/ports/servoshell/backtrace.rs:18:5
 0:10.41 pid:28891    6: servoshell::crash_handler::install::handler
 0:10.41 pid:28891              at /Users/jdm/src/servo/ports/servoshell/crash_handler.rs:38:21
 0:10.43 pid:28891    7: core::ops::function::Fn::call
 0:10.43 pid:28891              at /Users/jdm/.rustup/toolchains/1.92.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:79:5
 0:10.43 pid:28891    8: signal_hook_registry::handler
 0:10.43 pid:28891              at /Users/jdm/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/signal-hook-registry-1.4.8/src/lib.rs:416:13
 0:10.43 pid:28891    9: __os_alloc_slow
 0:10.54 pid:28891   10: _ZL16CheckMarkedThingI8JSObjectEvPN2js8GCMarkerEPT_
 0:10.54 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/Marking.cpp:221:3
 0:10.54 pid:28891   11: _ZN2js2gc14MarkingTracerTILj0EE6onEdgeI8JSObjectEEvPPT_PKc
 0:10.54 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/Marking.cpp:870:3
 0:10.54 pid:28891   12: _ZN2js17GenericTracerImplINS_2gc14MarkingTracerTILj0EEEE12onObjectEdgeEPP8JSObjectPKc
 0:10.54 pid:28891              at /Users/runner/work/mozjs/mozjs/target/debug/build/mozjs_sys-1d668fdc5a1a7b0b/out/build/dist/include/js/TracingAPI.h:221:3
 0:10.63 pid:28891   13: _ZN2js2gc17TraceEdgeInternalEP8JSTracerPP8JSObjectPKc
 0:10.63 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/Tracer.h:110:1
 0:10.63 pid:28891   14: _ZL23TraceExternalEdgeHelperIP8JSObjectEvP8JSTracerPT_PKc
 0:10.63 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/Marking.cpp:371:3
 0:10.63 pid:28891   15: _ZN2js2gc17TraceExternalEdgeEP8JSTracerPP8JSObjectPKc
 0:10.63 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/Marking.cpp:398:1
 0:10.64 pid:28891   16: _ZN2JS9TraceEdgeIP8JSObjectEEvP8JSTracerPNS_4HeapIT_EEPKc
 0:10.64 pid:28891              at /Users/runner/work/mozjs/mozjs/target/debug/build/mozjs_sys-1d668fdc5a1a7b0b/out/build/dist/include/js/TracingAPI.h:353:5
 0:10.64 pid:28891   17: CallObjectTracer
 0:10.64 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/./src/jsglue.cpp:986:3
 0:10.64 pid:28891   18: script_bindings::trace::trace_object
 0:10.64 pid:28891              at /Users/jdm/src/servo/components/script_bindings/trace.rs:65:9
 0:10.67 pid:28891   19: script_bindings::trace::trace_reflector
 0:10.67 pid:28891              at /Users/jdm/src/servo/components/script_bindings/trace.rs:51:14
 0:10.74 pid:28891   20: <script_bindings::root::Dom<T> as mozjs_sys::trace::Traceable>::trace
 0:10.74 pid:28891              at /Users/jdm/src/servo/components/script_bindings/root.rs:239:13
 0:10.76 pid:28891   21: <script::dom::workers::dedicatedworkerglobalscope::DedicatedWorkerGlobalScope as mozjs_sys::trace::Traceable>::trace
 0:10.76 pid:28891              at /Users/jdm/src/servo/components/script/dom/workers/dedicatedworkerglobalscope.rs:194:1
 0:10.79 pid:28891   22: script_bindings::codegen::GenericBindings::DedicatedWorkerGlobalScopeBinding::DedicatedWorkerGlobalScope_Binding::_trace::{{closure}}
 0:10.79 pid:28891              at /Users/jdm/src/servo/target/debug/build/servo-script-bindings-bbf865aa7417ff42/out/Bindings/DedicatedWorkerGlobalScopeBinding.rs:518:17
 0:10.79 pid:28891   23: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
 0:10.79 pid:28891              at /Users/jdm/.rustup/toolchains/1.92.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:310:21
 0:10.80 pid:28891   24: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
 0:10.80 pid:28891              at /Users/jdm/.rustup/toolchains/1.92.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274:9
 0:10.80 pid:28891   25: std::panicking::catch_unwind::do_call
 0:10.80 pid:28891              at /Users/jdm/.rustup/toolchains/1.92.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:590:40
 0:10.80 pid:28891   26: ___rust_try
 0:10.80 pid:28891   27: std::panicking::catch_unwind
 0:10.80 pid:28891              at /Users/jdm/.rustup/toolchains/1.92.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:553:19
 0:10.80 pid:28891       std::panic::catch_unwind
 0:10.80 pid:28891              at /Users/jdm/.rustup/toolchains/1.92.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panic.rs:359:14
 0:10.80 pid:28891   28: mozjs::panic::wrap_panic
 0:10.80 pid:28891              at /Users/jdm/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/mozjs-0.15.8/src/panic.rs:22:11
 0:10.80 pid:28891   29: script_bindings::codegen::GenericBindings::DedicatedWorkerGlobalScopeBinding::DedicatedWorkerGlobalScope_Binding::_trace
 0:10.80 pid:28891              at /Users/jdm/src/servo/target/debug/build/servo-script-bindings-bbf865aa7417ff42/out/Bindings/DedicatedWorkerGlobalScopeBinding.rs:514:5
 0:10.89 pid:28891   30: _Z24JS_GlobalObjectTraceHookP8JSTracerP8JSObject
 0:10.89 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/jsapi.cpp:1848:5
 0:11.00 pid:28891   31: _ZNK7JSClass7doTraceEP8JSTracerP8JSObject
 0:11.00 pid:28891              at /Users/runner/work/mozjs/mozjs/target/debug/build/mozjs_sys-1d668fdc5a1a7b0b/out/build/dist/include/js/Class.h:660:5
 0:11.01 pid:28891   32: _ZL13CallTraceHookP8JSTracerP8JSObject
 0:11.01 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/Marking.cpp:1245:12
 0:11.01 pid:28891   33: _ZN2js8GCMarker19processMarkStackTopILj0EEEbRN2JS11SliceBudgetE
 0:11.01 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/Marking.cpp:1642:3
 0:11.01 pid:28891   34: _ZN2js8GCMarker12markOneColorILj0ELNS_2gc9MarkColorE2EEEbRN2JS11SliceBudgetE
 0:11.01 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/Marking.cpp:1345:10
 0:11.01 pid:28891   35: _ZN2js8GCMarker9doMarkingILj0EEEbRN2JS11SliceBudgetENS_2gc20ShouldReportMarkTimeE
 0:11.01 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/Marking.cpp:1312:29
 0:11.01 pid:28891   36: _ZN2js8GCMarker24markUntilBudgetExhaustedERN2JS11SliceBudgetENS_2gc20ShouldReportMarkTimeE
 0:11.01 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/Marking.cpp:1303:10
 0:11.01 pid:28891   37: _ZN2js2gc9GCRuntime24markUntilBudgetExhaustedERN2JS11SliceBudgetENS1_15ParallelMarkingENS0_20ShouldReportMarkTimeE
 0:11.01 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/GC.cpp:3309:19
 0:11.01 pid:28891   38: _ZN2js2gc9GCRuntime16incrementalSliceERN2JS11SliceBudgetENS2_8GCReasonEb
 0:11.01 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/GC.cpp:3989:13
 0:11.01 pid:28891   39: _ZN2js2gc9GCRuntime7gcCycleEbRKN2JS11SliceBudgetENS2_8GCReasonE
 0:11.01 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/GC.cpp:4584:3
 0:11.01 pid:28891   40: _ZN2js2gc9GCRuntime7collectEbRKN2JS11SliceBudgetENS2_8GCReasonE
 0:11.01 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/GC.cpp:4773:9
 0:11.01 pid:28891   41: _ZN2js2gc9GCRuntime7gcSliceEN2JS8GCReasonERKNS2_11SliceBudgetE
 0:11.01 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/GC.cpp:4876:3
 0:11.01 pid:28891   42: _ZN2js2gc9GCRuntime17gcIfRequestedImplEb
 0:11.01 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/GC.cpp:5089:5
 0:11.11 pid:28891   43: _ZN2js2gc9GCRuntime13gcIfRequestedEv
 0:11.11 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/GCRuntime.h:332:33
 0:11.19 pid:28891   44: _ZL18MajorGCIfRequestedP9JSContext
 0:11.19 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/Allocator.cpp:133:23
 0:11.19 pid:28891   45: _ZN2js2gc13CellAllocator16AllocTenuredCellILNS_7AllowGCE1EEEPvP9JSContextNS0_9AllocKindE
 0:11.19 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/Allocator.cpp:175:5
 0:11.26 pid:28891   46: _ZN2js2gc13CellAllocator14NewTenuredCellINS_12GetterSetterELNS_7AllowGCE1EJRN2JS6HandleIP8JSObjectEESA_EEEPT_P9JSContextDpOT1_
 0:11.26 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/Allocator-inl.h:107:16
 0:11.26 pid:28891   47: _ZN2js2gc13CellAllocator7NewCellINS_12GetterSetterELNS_7AllowGCE1EJRN2JS6HandleIP8JSObjectEESA_EEEPT_P9JSContextDpOT1_
 0:11.26 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/gc/Allocator-inl.h:57:12
 0:11.26 pid:28891   48: _ZN9JSContext7newCellIN2js12GetterSetterELNS1_7AllowGCE1EJRN2JS6HandleIP8JSObjectEES9_EEEPT_DpOT1_
 0:11.26 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/vm/JSContext-inl.h:359:10
 0:11.26 pid:28891   49: _ZN2js12GetterSetter6createEP9JSContextN2JS6HandleIP8JSObjectEES7_
 0:11.26 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/vm/GetterSetter.cpp:21:14
 0:11.33 pid:28891   50: _ZL19AddOrChangePropertyIL13IsAddOrChange0EEbP9JSContextN2JS6HandleIPN2js12NativeObjectEEENS4_INS3_11PropertyKeyEEENS4_INS3_18PropertyDescriptorEEEPNS5_14PropertyResultE
 0:11.33 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/vm/NativeObject.cpp:1330:15
 0:11.33 pid:28891   51: _ZN2js20NativeDefinePropertyEP9JSContextN2JS6HandleIPNS_12NativeObjectEEENS3_INS2_11PropertyKeyEEENS3_INS2_18PropertyDescriptorEEERNS2_14ObjectOpResultE
 0:11.33 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/vm/NativeObject.cpp:1642:10
 0:11.33 pid:28891   52: _ZN2js22DefineAccessorPropertyEP9JSContextN2JS6HandleIP8JSObjectEENS3_INS2_11PropertyKeyEEES6_S6_jRNS2_14ObjectOpResultE
 0:11.33 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/vm/JSObject.cpp:2049:10
 0:11.33 pid:28891   53: _ZN2js22DefineAccessorPropertyEP9JSContextN2JS6HandleIP8JSObjectEENS3_INS2_11PropertyKeyEEES6_S6_j
 0:11.33 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/vm/JSObject.cpp:2066:8
 0:11.40 pid:28891   54: _ZL25InitGetterSetterOperationP9JSContextPhN2JS6HandleIP8JSObjectEENS3_INS2_11PropertyKeyEEES6_
 0:11.40 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:4946:12
 0:11.40 pid:28891   55: _ZN2js29InitPropGetterSetterOperationEP9JSContextPhN2JS6HandleIP8JSObjectEENS4_IPNS_12PropertyNameEEES7_
 0:11.40 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:4960:10
 0:11.40 pid:28891   56: _ZN2js9InterpretEP9JSContextRNS_8RunStateE
 0:11.40 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:3872:12
 0:11.40 pid:28891   57: _ZL31MaybeEnterInterpreterTrampolineP9JSContextRN2js8RunStateE
 0:11.40 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:395:10
 0:11.40 pid:28891   58: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
 0:11.40 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:464:13
 0:11.40 pid:28891   59: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
 0:11.40 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:622:13
 0:11.40 pid:28891   60: _ZL12InternalCallP9JSContextRKN2js13AnyInvokeArgsENS1_10CallReasonE
 0:11.40 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:657:10
 0:11.40 pid:28891   61: _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
 0:11.40 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/vm/Interpreter.cpp:689:8
 0:11.53 pid:28891   62: _ZN2js3jit14InvokeFunctionEP9JSContextN2JS6HandleIP8JSObjectEEbbjPNS3_5ValueENS3_13MutableHandleIS8_EE
 0:11.53 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/jit/VMFunctions.cpp:549:10
 0:11.53 pid:28891   63: _ZN2js3jit25InvokeFromInterpreterStubEP9JSContextPNS0_30InterpreterStubExitFrameLayoutE
 0:11.53 pid:28891              at /Users/runner/work/mozjs/mozjs/mozjs-sys/mozjs/js/src/jit/VMFunctions.cpp:573:8
 0:11.54 TEST_END: CRASH, expected OK - Traceback (most recent call last):
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 1183, in run_func
    self.result = True, self.func(self.protocol, self.url, self.timeout)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 1280, in do_testharness
    raw_results = protocol.testdriver.run(url, self.script_resume, test_window)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 685, in run
    test_driver_message = self.get_next_message(url, script_resume, test_window)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 729, in get_next_message
    return self._get_next_message_classic(url, script_resume)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 736, in _get_next_message_classic
    return self.parent.base.execute_script(script_resume, asynchronous=True, args=[strip_server(url)])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 81, in execute_script
    return method(script, args=args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/webdriver/webdriver/client.py", line 780, in execute_async_script
    return self.send_session_command("POST", "execute/async", body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/webdriver/webdriver/client.py", line 650, in send_session_command
    return self.send_command(method, url, body, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/webdriver/webdriver/client.py", line 588, in send_command
    response = self.transport.send(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/webdriver/webdriver/transport.py", line 230, in send
    response = self._request(method, uri, payload, headers, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/webdriver/webdriver/transport.py", line 265, in _request
    response = self.connection.getresponse()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/Users/jdm/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/http/client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

 0:11.54 INFO No more tests
 0:11.54 INFO Closing logging queue
 0:11.54 INFO queue closed
 0:11.56 SUITE_END

web-platform-test
~~~~~~~~~~~~~~~~~
Ran 1 checks (1 tests)
Expected results: 0
Unexpected results: 1
  test: 1 (1 crash)

Error Summary
-------------
CRASH /WebCryptoAPI/digest/kangarootwelve.tentative.https.any.worker.html - Traceback (most recent call last):
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 1183, in run_func
    self.result = True, self.func(self.protocol, self.url, self.timeout)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 1280, in do_testharness
    raw_results = protocol.testdriver.run(url, self.script_resume, test_window)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 685, in run
    test_driver_message = self.get_next_message(url, script_resume, test_window)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 729, in get_next_message
    return self._get_next_message_classic(url, script_resume)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 736, in _get_next_message_classic
    return self.parent.base.execute_script(script_resume, asynchronous=True, args=[strip_server(url)])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 81, in execute_script
    return method(script, args=args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/webdriver/webdriver/client.py", line 780, in execute_async_script
    return self.send_session_command("POST", "execute/async", body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/webdriver/webdriver/client.py", line 650, in send_session_command
    return self.send_command(method, url, body, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/webdriver/webdriver/client.py", line 588, in send_command
    response = self.transport.send(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/webdriver/webdriver/transport.py", line 230, in send
    response = self._request(method, uri, payload, headers, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/src/servo/tests/wpt/tests/tools/webdriver/webdriver/transport.py", line 265, in _request
    response = self.connection.getresponse()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/Users/jdm/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/jdm/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/http/client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

### PR DESCRIPTION
**Pull request by jdm**
Debug mozjs builds don't like when we try to trace members of one global object (realm) that originate from another global object (realm). This triggers when we use `Dom<DebuggerGlobalScope>` in our global objects, since all `Dom<T>` pointers are expected to in the same realm as the containing object. To address this, we store a JS value of the debugger global's reflector wrapped in the current global's relam, and use value to reconstitute a `DebuggerGlobalScope` pointer as needed.

Testing: We don't run debug-mozjs in CI, but this change makes a bunch of tests stop asserting.
Fixes: #44385

### CODE REVIEW

File: components/script/dom/workers/workerglobalscope.rs [hunk 1]
```diff
@@ -1050,6 +1059,51 @@ impl WorkerGlobalScope {
...
+        let cx = &mut realm.current_realm();
+
+        // Convert the debugger global’s reflector to a Value, wrapping it from its originating realm (debugger realm)
+        // into the active realm (debuggee realm) so that it can be passed across compartments.
+        rooted!(&in(cx) let mut wrapped_global: Value);
+        debugger_global.reflector().safe_to_jsval(
+            cx.into(),
+            wrapped_global.handle_mut(),
+            CanGc::from_cx(cx),
+        );
```
Comment (sagudev) [inline components/script/dom/workers/workerglobalscope.rs:1085]: So we still trace (keep alive) debbuger_global, it's just that SM will trace it indirectly using JSVal hop, which makes debug mozjs to not complain or did I misunderstood something?

Comment (jdm) [reply components/script/dom/workers/workerglobalscope.rs:1085]: That is correct.

Comment (sagudev) [reply components/script/dom/workers/workerglobalscope.rs:1085]: Can we also put this into code comment, so there is no need do do mental gymnastic again.

**Review by sagudev — APPROVED** [review]
LGTM
