### PR TITLE
script: Implement drop-down select multiple

### LINKED ISSUE #38509: Attribute multiple has no effect on `<select>`
**Describe the bug:**
See https://github.com/servo/servo/pull/38497#discussion_r2257866612

**To Reproduce:**
```
</head><body><select multiple="multiple">
  <option>first
  </option><option selected="selected">second
</option></select></body></html>
```

### PR DESCRIPTION
**Pull request by lukewarlow**
Implement drop-down select multiple: 
 - Updates the embedder API to support multi-selects.
 - Updates the select element to correctly reset when multiple attribute is removed.
 - Select now renders "n selected" as button text when more than 1, or 0 options are selected.

Note that listbox selects are not yet supported, once they are these new features will be for `<select multiple size=1>`.

Testing: WPTs and also manually using https://demo.lukewarlow.dev/css-forms.html. The two test regressions are due to the lack of listbox support rather than an issue with this PR.
Fixes: #38509

### CODE REVIEW

File: components/shared/embedder/embedder_controls.rs [hunk 1]
```diff
@@ -153,9 +153,16 @@ pub struct FilePickerRequest {
     pub accept_current_paths_for_testing: bool,
 }
 
+#[derive(Debug, Deserialize, Serialize)]
+pub struct SelectPickerRequest {
+    pub options: Vec<SelectElementOptionOrOptgroup>,
+    pub selected_options: Vec<usize>,
+    pub allow_select_multiple: bool,
+}
+
```
Comment (mrobinson) [inline components/shared/embedder/embedder_controls.rs:170]: I think we are gradually moving away from the "Picker" terminology:


```suggestion
#[derive(Debug, Deserialize, Serialize)]
pub struct SelectElementRequest {
    pub options: Vec<SelectElementOptionOrOptgroup>,
    pub selected_options: Vec<usize>,
    pub allow_select_multiple: bool,
}

```

File: components/servo/webview_delegate.rs [hunk 2]
```diff
@@ -403,19 +402,20 @@ impl SelectElement {
...
+        &self.select_picker_request.options
     }
 
-    /// Mark a single option as selected.
-    ///
-    /// If there is already a selected option and the `<select>` element does not
-    /// support selecting multiple options, then the previous option will be unselected.
-    pub fn select(&mut self, id: Option<usize>) {
-        self.selected_option = id;
+    /// Set the options that are selected
```
Comment (mrobinson) [inline components/servo/webview_delegate.rs]:
```suggestion
    /// Set the options that are selected.
    ///
    /// If other options have previously been selected, this set of options
    /// will replace them.
```

File: components/script/dom/html/htmlselectelement.rs [hunk 3]
```diff
@@ -421,26 +437,83 @@ impl HTMLSelectElement {
...
+            self.send_update_notifications();
+        }
+    }
+
+    fn multiple_attribute_mutated(&self, cx: &mut JSContext, mutation: AttributeMutation) {
+        if mutation.is_removal() {
+            let mut first_enabled: Option<DomRoot<HTMLOptionElement>> = None;
+            let mut first_selected: Option<DomRoot<HTMLOptionElement>> = None;
+
+            for opt in self.list_of_options() {
```
Comment (mrobinson) [inline components/script/dom/html/htmlselectelement.rs]:
```suggestion
            for option in self.list_of_options() {
```

File: components/script/dom/html/htmlselectelement.rs [hunk 4]
```diff
@@ -421,26 +437,83 @@ impl HTMLSelectElement {
...
+                }
+            }
+
+            if let Some(first_selected) = first_selected {
+                first_selected.set_selectedness(true);
+            } else if self.display_size() == 1 {
+                if let Some(first_enabled) = first_enabled {
+                    first_enabled.set_selectedness(true);
+                }
+            }
```
Comment (mrobinson) [inline components/script/dom/html/htmlselectelement.rs:514]: Hrm. With `multiple` isn't it possible that none of the options are selected. Normally this displays as a list box on the page and when I create one of these Firefox initially shows that none are selected.

File: components/script/dom/html/htmlselectelement.rs [hunk 5]
```diff
@@ -421,26 +437,83 @@ impl HTMLSelectElement {
...
+                    selected_options,
+                    allow_select_multiple: self.Multiple(),
+                }),
                 None,
             );
         self.upcast::<Element>().set_open_state(true);
     }
 
-    pub(crate) fn handle_menu_response(&self, cx: &mut JSContext, response: Option<usize>) {
+    pub(crate) fn handle_menu_response(&self, cx: &mut JSContext, selected_values: Vec<usize>) {
```
Comment (mrobinson) [inline components/script/dom/html/htmlselectelement.rs]: This is unrelated to your change, but let's take the opportunity to improve the name of this method. It isn't guaranteed that the embedder will even show a menu.

```suggestion
    pub(crate) fn handle_embedder_response(&self, cx: &mut JSContext, selected_values: Vec<usize>) {
```

File: components/script/dom/html/htmlselectelement.rs [hunk 6]
```diff
@@ -421,26 +437,83 @@ impl HTMLSelectElement {
...
+            selected_values
+        } else {
+            selected_values.into_iter().take(1).collect()
         };
 
-        self.SetSelectedIndex(cx, selected_value as i32);
-        self.send_update_notifications();
+        let mut selection_did_change = false;
+        for (index, option) in self.list_of_options().enumerate() {
+            let should_be_selected = selected_values.contains(&index);
```
Comment (mrobinson) [inline components/script/dom/html/htmlselectelement.rs:472]: It's unclear to me if it makes sense to convert the values into a `HashSet` here.

File: components/script/dom/html/htmlselectelement.rs [hunk 7]
```diff
@@ -421,26 +437,83 @@ impl HTMLSelectElement {
...
+            if option.Selected() != should_be_selected {
+                selection_did_change = true;
+            }
+
+            option.set_selectedness(should_be_selected);
+
+            if should_be_selected {
+                option.set_dirtiness(true);
+            }
+        }
```
Comment (mrobinson) [inline components/script/dom/html/htmlselectelement.rs]: It seems that `HTMLOptionElement::SetSelected` unconditionally sets the dirtiness flag on the option. The dirtiness flag seems to control whether or not changes to the attribute affect the selected state. Shouldn't changes to the attribute also be ignored if the option was initially selected via an attribute and then unselected by the user?

**Review by mrobinson — CHANGES_REQUESTED** [review]
Nice. I have a few comments here:

**Comment by mrobinson** [comment]
Do you mind determining why these two new WPT tests are failing? This just be due to subpixel issues, but it would be good to know.

File: components/script/dom/html/htmlselectelement.rs (hunk 4 above)
Comment (lukewarlow) [reply components/script/dom/html/htmlselectelement.rs:514]: Yes, this is running when the multiple attribute is removed. So this is to do the select first enabled option logic for single select.

File: components/script/dom/html/htmlselectelement.rs (hunk 7 above)
Comment (lukewarlow) [reply components/script/dom/html/htmlselectelement.rs]: Good catch. You're correct.

**Comment by lukewarlow** [comment]
> Do you mind determining why these two new WPT tests are failing?

They fail now because they were only ever passing by accident, they're meant to be testing listbox rendering, which still isn't supported (dropdown multiple should in the end only render when size=1. 

Looking at text-transform: Previously the select element did render the text THIS TEXT SHOULD BE UPPER CASE in it's button, but now it renders "0 selected".

Likewise option-checked-styling is doing the same, it previously did see "Option #1 (should be green)" in the test and in the ref, but as the ref does set selected on any option, it now renders "0 selected".

So these are just tests that accidentally passed.

File: components/script/dom/html/htmlselectelement.rs (hunk 6 above)
Comment (lukewarlow) [reply components/script/dom/html/htmlselectelement.rs:472]: I think it depends how many options are commonly inside select elements. I know some can be large, but creating the hashset has a cost.

I'll defer to your judgement.

File: ports/servoshell/desktop/dialog.rs [hunk 8]
```diff
@@ -510,8 +510,21 @@ impl Dialog {
...
 
                     if clickable_area.clicked() && !option.is_disabled {
-                        *selected_option = Some(option.id);
-                        *is_open = false;
+                        if allow_multiple {
+                            if let Some(pos) =
+                                selected_options.iter().position(|id| *id == option.id)
+                            {
+                                selected_options.remove(pos);
+                            } else {
```
Comment (mrobinson) [inline ports/servoshell/desktop/dialog.rs]:
```suggestion
                            if let Some(position) =
                                selected_options.iter().position(|id| *id == option.id)
                            {
                                selected_options.remove(position);
```

**Review by mrobinson — APPROVED** [review]

**Comment by lukewarlow** [comment]
Just pushed a typo fix this should be good to merge now.

**Comment by lukewarlow** [comment]
Hmm seems I missed a test expectation, have added that

**Comment by lukewarlow** [comment]
There's no more stable failing tests and the flaky unexpected fails don't seem related?

**Comment by delan** [comment]
hi! i’m working on the monthly update. i tested this in servoshell 0.2.0 on linux wayland, but i was unable to actually select any options in a &lt;select multiple> – clicking any option in the popup does nothing. is that a known issue?

**Comment by lukewarlow** [comment]
I tested it originally on macOS and it was working there. It's possible something has regressed since this was merged but I'm not aware of a reason it would be broken.
