### PR TITLE
Fix radial gradient's <size>/<ending-shape> parsing

### LINKED ISSUE #13664: Fix radial gradient's <size>/<ending-shape> parsing
Spec: https://drafts.csswg.org/css-images/#radial-gradient-syntax
Normally size can come before shape keywords but currently parsing fails if size comes before shape keyword. We need to parse them regardless of sequence.
current parsing behavior:
`radial-gradient(circle closest-corner at 50px 30px, red, yellow);`
but it can be like this:
`radial-gradient(closest-corner circle at 50px 30px, red, yellow);`

### PR DESCRIPTION
**Pull request by canova**
Parsing now handles sizes and shapes in various order.
I had to delete `EndingShape`'s parse implementation and mix it with `Position` in `parse_radial`. It became a bit complicated to read but I couldn't make it simpler.
r? @Manishearth 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13664 (github issue number if applicable).

- [X] There are tests for these changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13804)

### CODE REVIEW

File: components/style/values/specified/image.rs [hunk 1]
```diff
@@ -163,23 +163,54 @@ impl GradientKind {
...
+                    "ellipse" => {
+                        let length = input.try(LengthOrPercentageOrKeyword::parse)
+                                     .unwrap_or(LengthOrPercentageOrKeyword::Keyword(SizeKeyword::FarthestCorner));
+                         (EndingShape::Ellipse(length), input.try(parse_position).unwrap_or(Position::center()))
+                    },
+                    _ => {
+                        // If there is no indent, it should set to default.
+                        // But also it should restore parser's internal state.
+                        needs_comma = false;
+                        input.reset(position);
```
Comment (canaltinova) [inline components/style/values/specified/image.rs]: I had to backtrack here because of unintended increase of token position. I don't know if there is a better way for this. Any suggestions @Manishearth?

File: components/style/values/specified/image.rs [hunk 2]
```diff
@@ -191,6 +222,31 @@ impl GradientKind {
...
+
+fn parse_position(input: &mut Parser) -> Result<Position, ()> {
+    if input.try(|input| input.expect_ident_matching("at")).is_ok() {
+        input.try(Position::parse)
+    } else {
+        Err(())
+    }
+}
+
+impl Position {
```
Comment (canaltinova) [inline components/style/values/specified/image.rs]: Should I move this to position.rs?

File: components/style/values/specified/image.rs (hunk 1 above)
Comment (Manishearth) [inline components/style/values/specified/image.rs]: You shouldn't be doing this, just wrap everything else in a `input.try`. This can be an error case then, and you can handle it when the try fails.

File: components/style/values/specified/image.rs (hunk 2 above)
Comment (Manishearth) [inline components/style/values/specified/image.rs]: yes

File: components/style/values/specified/image.rs (hunk 1 above)
Comment (Manishearth) [inline components/style/values/specified/image.rs]: I think the best way to structure this broadly is to try to parse the whole thing as if it were an ellipse, first (also eating the comma), else try to parse as a circle (again eating the comma), else default it.

**Review by Manishearth — CHANGES_REQUESTED** [review]
I think this could be restructured a bit

File: components/style/values/specified/image.rs (hunk 1 above)
Comment (canaltinova) [inline components/style/values/specified/image.rs]: Yes, you're right. I'll change it this way. Thanks!

**Comment by Manishearth** [comment]
Also, please add parse tests for this behavior.

**Comment by canaltinova** [comment]
Restructured and added some comments to code. Also added tests for parsing. `assert_roundtrip` macro wouldn't fit(because parse function's parameters aren't same) so I had to create another macro for it.

File: tests/unit/style/parsing/image.rs [hunk 3]
```diff
@@ -0,0 +1,93 @@
...
+fn test_radial_gradient() {
+    // Parsing with all values
+    assert_roundtrip_image!("radial-gradient(circle closest-side at 20px 30px, red, green)");
+    assert_roundtrip_image!("radial-gradient(ellipse closest-side at 20px 30px, red, green)");
+    assert_roundtrip_image!("radial-gradient(closest-side circle at 20px 30px, red, green)",
+                            "radial-gradient(circle closest-side at 20px 30px, red, green)");
+    assert_roundtrip_image!("radial-gradient(closest-side ellipse at 20px 30px, red, green)",
+                            "radial-gradient(ellipse closest-side at 20px 30px, red, green)");
+
+    // Parsing with <basic-shape> and <size> reversed
```
Comment (Manishearth) [inline tests/unit/style/parsing/image.rs]: shape-keyword

File: tests/unit/style/parsing/image.rs [hunk 4]
```diff
@@ -0,0 +1,93 @@
...
+ * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
+
+use cssparser::Parser;
+use media_queries::CSSErrorReporterTest;
+use style::parser::ParserContext;
+use style::stylesheets::Origin;
+use style::values::specified::image::*;
+use url::Url;
+
+macro_rules! assert_roundtrip_image {
```
Comment (Manishearth) [inline tests/unit/style/parsing/image.rs]: Can we generalize this as `assert_roundtrip_with_context` and have it take a `$fun` arg (which we use instead of `Image::parse`)

**Comment by Manishearth** [comment]
Minor nits, overall lgtm

**Comment by canaltinova** [comment]
Changed them thanks. Should I move `assert_roundtrip_with_context` to mod.rs or somewhere else?

**Comment by Manishearth** [comment]
mod.rs

**Comment by canaltinova** [comment]
Done
