### PR TITLE
devtools: Include layer rules in CSS panel using rule tree 

### LINKED ISSUE #43541: Devtools: CSS properties in layers don't show in the devtools panel
**Describe the bug:**
When using Firefox `about:debugging` to debug Servo, and use the Inspector to scrutinise elements, the CSS rules panel doesn't include properties from `layer` declarations.

**To Reproduce:**
When visiting https://www.sharyap.com/ :

Servo devtools:
Image
Firefox devtools:
Image

**Platform:**
Servo latest

### PR DESCRIPTION
**Pull request by arabson99**
DevTools was collecting CSS rules by walking stylesheets and matching selector text. This ignored cascade order and did not correctly handle rules inside layer blocks.

This change uses computed values (rule tree) to get the actual applied rules in cascade order. It then maps those rules back to CSSStyleRule using the declaration block identity, and walks the CSSOM to get selector text and layer ancestry.

This fills ancestor_data with layer names and lets the inspector show layered rules correctly.

Testing: 
- Verified using the minimized testcase from the issue

- Verified on https://www.sharyap.com/

- Confirmed that rules inside layer blocks are now shown with correct order and hierarchy.

Fixes: #43541

### CODE REVIEW

File: components/devtools/actors/inspector/page_style.rs [hunk 1]
```diff
@@ -177,27 +177,35 @@ impl PageStyleActor {
...
-                    let rule = match node_actor.style_rules.borrow_mut().entry(selector) {
-                        Entry::Vacant(e) => {
-                            let name = registry.new_name::<StyleRuleActor>();
-                            let actor = StyleRuleActor::new(
-                                name.clone(),
-                                node_actor.name(),
-                                (!e.key().0.is_empty()).then_some(e.key().clone()),
-                            );
-                            let rule = actor.applied(registry)?;
+            let inline_sentinel = MatchedRule {
```
Comment (eerii) [inline components/devtools/actors/inspector/page_style.rs]: Maybe we could call this `style_attribute_rule` or something along those lines?

File: components/devtools/actors/inspector/page_style.rs [hunk 2]
```diff
@@ -177,27 +177,35 @@ impl PageStyleActor {
...
+                            name.clone(),
+                            node_actor.name(),
+                            (rule_match.stylesheet_index != usize::MAX)
+                                .then_some(rule_match.clone()),
+                        );
+                        let rule = actor.applied(registry)?;
+                        registry.register(actor);
+                        node_actor.style_rules.borrow_mut().insert(rule_match, name);
+                        rule
                     };
```
Comment (eerii) [inline components/devtools/actors/inspector/page_style.rs]: I was just thinking about this part for a different issue. I think we could make it a bit better by using `Entry::or_insert`. See my comment here for an example: https://github.com/servo/servo/issues/43800#issuecomment-4188543967

File: components/devtools/actors/inspector/page_style.rs [hunk 3]
```diff
@@ -232,11 +240,13 @@ impl PageStyleActor {
             .as_str()
             .ok_or(ActorError::BadParameterType)?;
         let node_actor = registry.find::<NodeActor>(target);
-        let computed = (|| match node_actor
-            .style_rules
-            .borrow_mut()
-            .entry(("".into(), usize::MAX))
-        {
+        let inline_sentinel = devtools_traits::MatchedRule {
```
Comment (eerii) [inline components/devtools/actors/inspector/page_style.rs]: Same rename here

File: components/devtools/actors/inspector/page_style.rs [hunk 4]
```diff
@@ -177,27 +177,35 @@ impl PageStyleActor {
...
-                            e.insert(name);
-                            rule
-                        },
-                        Entry::Occupied(e) => {
-                            let actor = registry.find::<StyleRuleActor>(e.get());
-                            actor.applied(registry)?
-                        },
+            once(inline_sentinel)
+                .chain(selectors)
+                .filter_map(move |rule_match| {
```
Comment (eerii) [inline components/devtools/actors/inspector/page_style.rs]: We could name this `matched_rule` to be more consistent with other places.

File: components/shared/devtools/lib.rs [hunk 5]
```diff
@@ -271,6 +271,26 @@ pub struct NodeStyle {
     pub priority: String,
 }
 
+#[derive(Clone, Debug, Deserialize, Serialize, MallocSizeOf, PartialEq, Eq, Hash)]
+#[serde(tag = "type", rename_all = "camelCase")]
+pub enum AncestorData {
+    Layer {
+        #[serde(skip_serializing_if = "Option::is_none")]
```
Comment (eerii) [inline components/shared/devtools/lib.rs]: We can't add `skip_serializing_if` in `shared/devtools`. It works for converting Rust to JSON when sending messages to Firefox, but it breaks when sending messages from different process in Servo in multiprocess mode. We can just remove the annotations.

File: components/script/devtools.rs [hunk 6]
```diff
@@ -313,91 +316,170 @@ pub(crate) fn handle_get_attribute_style(
...
-                }))
-            })
-            .flatten()
-            .collect();
+        let stylesheet = owner.stylesheet_at(matched_rule.stylesheet_index)?;
+        let list = stylesheet.GetCssRules(CanGc::from_cx(cx)).ok()?;
 
-        Some(rules)
+        let style_rule = find_rule_by_block_id(cx, &list, matched_rule.block_id)?;
+        let decl = style_rule.Style(cx);
```
Comment (eerii) [inline components/script/devtools.rs]: Let's call this `declaration`.

**Review by eerii — COMMENTED** [review]
Nice job! Ran it locally and the [minimal test](https://github.com/servo/servo/issues/43541#issuecomment-4130902544) works nicely. The DevTools part looks good, I left a few comments. I'm tagging @jdm and @Loirooriol for the CSS part since they have more expertise than me to review it.

File: components/script/devtools.rs [hunk 7]
```diff
@@ -313,91 +316,170 @@ pub(crate) fn handle_get_attribute_style(
     reply.send(Some(msg)).unwrap();
 }
 
+#[cfg_attr(crown, allow(crown::unrooted_must_root))]
```
Comment (jdm) [inline components/script/devtools.rs]: Why are these attributes required? Which pieces of code have errors without them?

File: components/script/devtools.rs [hunk 8]
```diff
@@ -313,91 +316,170 @@ pub(crate) fn handle_get_attribute_style(
...
+        };
+
+        if let Some(style_rule) = rule.downcast::<CSSStyleRule>() {
+            if style_rule.block_id() == target_block_id {
+                return Some(DomRoot::from_ref(style_rule));
+            }
+            continue;
+        }
+
+        if let Some(layer_rule) = rule.downcast::<CSSLayerBlockRule>() {
```
Comment (jdm) [inline components/script/devtools.rs]: Do we actually need this block? All we do is upcast to CssGroupingRules, which is handled the same in the next block.

File: components/shared/devtools/lib.rs (hunk 5 above)
Comment (arabson99) [reply components/shared/devtools/lib.rs]: Thanks, I removed those serde annotations.

File: components/script/devtools.rs (hunk 6 above)
Comment (arabson99) [reply components/script/devtools.rs]: Done, renamed it to `declaration`

File: components/script/devtools.rs (hunk 7 above)
Comment (arabson99) [reply components/script/devtools.rs]: I removed those attributes. The build passes without them.

File: components/script/devtools.rs (hunk 8 above)
Comment (arabson99) [reply components/script/devtools.rs]: True... I removed the redundant block.

File: components/devtools/actors/inspector/page_style.rs (hunk 2 above)
Comment (arabson99) [reply components/devtools/actors/inspector/page_style.rs]: Done. Refactored to use `.or_insert_with` and updated `StyleRuleActor` to use the `register` pattern.

File: components/devtools/actors/inspector/page_style.rs (hunk 1 above)
Comment (arabson99) [reply components/devtools/actors/inspector/page_style.rs]: Done, renamed.

**Comment by arabson99** [comment]
Thanks for the reviews @eerii and @jdm. I’ve pushed an update addressing the feedback.

**Review by eerii — APPROVED** [review]
Thanks for all of the changes! :)
