### PR TITLE
DevTools: Allow modification of attributes

### LINKED ISSUE #32885: Crash when queuing a mutation record
**Describe the bug:**

Servo crashes when editing or removing a tag in the DevTools inspector.

This comes from [`script/dom/element.rs::remove_first_matching_attribute`](https://github.com/servo/servo/blob/main/components/script/dom/element.rs#L1577), which calls [`script/dom/mutationobserver.rs::queue_a_mutation_record`](https://github.com/servo/servo/blob/main/components/script/dom/mutationobserver.rs#L135). The problematic check is in the first line:

```rs
if !target.global().as_window().get_exists_mut_observer() {
	return;
}
```

This calls an unsafe [function](https://github.com/servo/servo/blob/main/components/script/realms.rs#L22) down the stack, which ends up crashing the program. It calls the [`GetCurrentRealmOrNull`](https://github.com/servo/mozjs/blob/main/mozjs-sys/mozjs/js/src/vm/Realm.cpp#L620) from `mozjs`. The last call seems to be to [`JSContext::realm()`](https://github.com/servo/mozjs/blob/main/mozjs-sys/mozjs/js/src/vm/JSContext.h#L288).

If this check is removed the crash goes away and everything seems to work, but I imagine that it is there for a reason and that there is a problem with how the node was constructed, it might be missing some information. But I may be a bit outside my depth here since I don't have that much experience with mozjs or realms.

**To Reproduce:**

- Launch Servo with the DevTools server enabled: `./mach run --devtools=1234`
- In Firefox, go to `about:debugging` and connect to `localhost:1234` (or the port number you specified)
- Click inspect on one of the tabs, and go to the inspector tab
- Edit one of the tag attributes (for example, change `<p style="color:red;">` to `<p style="color:blue;">`)
- Servo crashes

**Platform:**

Linux 6.10 (NixOS 24.05), happening on `main` ([29a4cca](https://github.com/servo/servo/commit/29a4cca42d01ab7acf6610362cd1165d2c2e85f7)).

<details>
<summary><b>Crash log</b></summary>

```
assertion failed: !GetCurrentRealmOrNull(*cx).is_null() (thread Script(1,1), at components/script/realms.rs:24)
   0: servoshell::backtrace::print
             at /persist/home/eri/Code/servo/ports/servoshell/backtrace.rs:18:5
   1: servoshell::panic_hook::panic_hook
             at /persist/home/eri/Code/servo/ports/servoshell/panic_hook.rs:38:17
   2: core::ops::function::Fn::call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:79:5
   3: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2034:9
      std::panicking::rust_panic_with_hook
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:783:13
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:649:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:171:18
   6: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   7: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   8: core::panicking::panic
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:145:5
   9: script::realms::AlreadyInRealm::assert_for_cx
             at /persist/home/eri/Code/servo/components/script/realms.rs:24:13
  10: script::dom::bindings::reflector::DomObject::global
             at /persist/home/eri/Code/servo/components/script/dom/bindings/reflector.rs:103:21
  11: script::dom::mutationobserver::MutationObserver::queue_a_mutation_record
             at /persist/home/eri/Code/servo/components/script/dom/mutationobserver.rs:136:13
  12: script::dom::element::Element::remove_first_matching_attribute::{{closure}}
             at /persist/home/eri/Code/servo/components/script/dom/element.rs:1628:13
  13: core::option::Option<T>::map
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/option.rs:1073:29
  14: script::dom::element::Element::remove_first_matching_attribute
             at /persist/home/eri/Code/servo/components/script/dom/element.rs:1615:9
  15: script::dom::element::Element::remove_attribute_by_name
             at /persist/home/eri/Code/servo/components/script/dom/element.rs:1607:9
  16: <script::dom::element::Element as script::dom::bindings::codegen::Bindings::ElementBinding::Element_Binding::ElementMethods>::RemoveAttribute
             at /persist/home/eri/Code/servo/components/script/dom/element.rs:2282:9
  17: script::devtools::handle_modify_attribute
             at /persist/home/eri/Code/servo/components/script/devtools.rs:223:21
  18: script::script_thread::ScriptThread::handle_msg_from_devtools
             at /persist/home/eri/Code/servo/components/script/script_thread.rs:2518:17
  19: script::script_thread::ScriptThread::handle_msgs::{{closure}}
             at /persist/home/eri/Code/servo/components/script/script_thread.rs:1959:48
  20: script::script_thread::ScriptThread::profile_event
             at /persist/home/eri/Code/servo/components/script/script_thread.rs:2214:13
  21: script::script_thread::ScriptThread::handle_msgs
             at /persist/home/eri/Code/servo/components/script/script_thread.rs:1951:26
  22: script::script_thread::ScriptThread::start
             at /persist/home/eri/Code/servo/components/script/script_thread.rs:1454:15
  23: <script::script_thread::ScriptThread as script_layout_interface::ScriptThreadFactory>::create::{{closure}}::{{closure}}
             at /persist/home/eri/Code/servo/components/script/script_thread.rs:845:25
  24: profile_traits::mem::ProfilerChan::run_with_memory_reporting
             at /persist/home/eri/Code/servo/components/shared/profile/mem.rs:91:9
  25: <script::script_thread::ScriptThread as script_layout_interface::ScriptThreadFactory>::create::{{closure}}
             at /persist/home/eri/Code/servo/components/script/script_thread.rs:843:17
  26: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:155:18
  27: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/mod.rs:528:17
  28: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panic/unwind_safe.rs:272:9
  29: std::panicking::try::do_call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
  30: __rust_try
  31: std::panicking::try
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
  32: std::panic::catch_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/mod.rs:527:30
  33: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
  34: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2020:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2020:9
      std::sys::pal::unix::thread::Thread::new::thread_start
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys/pal/unix/thread.rs:108:17
  35: start_thread
  36: __GI___clone3
```

</details>

### PR DESCRIPTION
**Pull request by eerii**
This PR fixes the handling of attributes in the inspector. Now it is possible to add, remove and modify attributes of HTML nodes. There were two issues with it:

- Servo crashed when updating the values (#32885). This was because it was not properly entering a realm before making DOM modifications.
- The messages have changed. Now after receiving a `modifyAttributes` message, the node has to inform the walker that there have been mutations on the DOM. The walker then sends `newMutations` (which is part of the event messages that are not directly responding to another message, see `browsing_context` for more examples), which then triggers the DevTools client to ask for `getMutations`. Here we send a list of all of the changes to the attributes that we made.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #32885 and are a part of #32404
- [x] These changes do not require tests because there are no tests yet for DevTools

### CODE REVIEW

File: components/devtools/actors/inspector.rs [hunk 1]
```diff
@@ -86,14 +86,26 @@ impl Actor for InspectorActor {
                 self.script_chan.send(GetRootNode(pipeline, tx)).unwrap();
                 let root_info = rx.recv().unwrap().ok_or(())?;
 
-                let root = root_info.encode(registry, false, self.script_chan.clone(), pipeline);
+                let name = match self.walker.borrow().as_ref() {
+                    Some(walker) => walker.clone(),
+                    None => registry.new_name("walker"),
+                };
```
Comment (mrobinson) [inline components/devtools/actors/inspector.rs:92]: Can this be something like:

```suggestion
                let name = self.walker.borrow().cloned().unwrap_or_else(||  registry.new_name("walker"));
```

**Review by mrobinson — APPROVED** [review]
Looks good to me, just a small nit:

File: components/devtools/actors/inspector.rs (hunk 1 above)
Comment (eerii) [reply components/devtools/actors/inspector.rs]: Yes, that looks very nice!

**Comment by eerii** [comment]
Sorry about that, for some reason that error wasn't showing in my local build until now.
