### PR TITLE
constellation: Wait for canvas thread to shut down before shutting down system font service

### LINKED ISSUE #36849: panic: failed to send message to system font service: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }) (thread Canvas, at components/fonts/system_font_service.rs:516)
Minimal testcase:

```
<!DOCTYPE html>
<script>
  window.addEventListener("load", _ => {
    let canvas = document.createElement("canvas");
    var context = canvas.getContext("2d");
    context.fillText(String.fromCodePoint(1012043, 175310), 0, 0);
  });
</script>
```

System: Linux
Version: Servo 0.0.1-43edab336
Command: `./servo/servo --headless`

```
failed to send message to system font service: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }) (thread Canvas, at components/fonts/system_font_service.rs:516)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: fonts::system_font_service::SystemFontServiceProxy::find_matching_font_templates
   9: fonts::font::FontGroupFamily::members
  10: fonts::font::FontGroupFamily::find
  11: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  12: fonts::font::FontGroup::find_by_codepoint
  13: canvas::canvas_data::CanvasData<B>::build_unshaped_text_runs
  14: canvas::canvas_data::CanvasData<B>::fill_text_with_size
  15: canvas::canvas_paint_thread::CanvasPaintThread::process_canvas_2d_message
  16: std::sys::backtrace::__rust_begin_short_backtrace
  17: core::ops::function::FnOnce::call_once{{vtable.shim}}
  18: std::sys::pal::unix::thread::Thread::new::thread_start
```

The repro testcase is a bit flaky. Sometimes it does not produce any panic, sometimes (with the extra `--enable-experimental-web-platform-features` option?) it produces this panic message instead:

```
SystemFontService has already exited. (thread Canvas, at components/fonts/system_font_service.rs:528)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: fonts::system_font_service::SystemFontServiceProxy::find_matching_font_templates
   8: fonts::font::FontGroupFamily::members
   9: fonts::font::FontGroupFamily::find
  10: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  11: fonts::font::FontGroup::find_by_codepoint
  12: canvas::canvas_data::CanvasData<B>::build_unshaped_text_runs
  13: canvas::canvas_data::CanvasData<B>::fill_text_with_size
  14: canvas::canvas_paint_thread::CanvasPaintThread::process_canvas_2d_message
  15: std::sys::backtrace::__rust_begin_short_backtrace
  16: core::ops::function::FnOnce::call_once{{vtable.shim}}
  17: std::sys::pal::unix::thread::Thread::new::thread_start
  18: start_thread
             at ./nptl/pthread_create.c:447:8
  19: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
```

### PR DESCRIPTION
**Pull request by mrobinson**
The canvas thread might need access to the system font service before it
shuts down. Ensure that it finishes shutting down before triggering the
shutdown of the system font service. This should avoid issues where
canvas tries to access fonts right before shutting down.

Fixes: #36849.
Testing: Since this fixes a flaky crash on shutdown, there isn't a good
way to write a test for it.

### CODE REVIEW

File: components/constellation/constellation.rs [hunk 1]
```diff
@@ -2800,6 +2804,10 @@ where
         debug!("Exiting GLPlayer thread.");
         WindowGLContext::get().exit();
 
+        // Wait for the canvas thread to exit before shutting down the font service, as
+        // canvas might still be using the system font service before shutting down.
+        let _ = canvas_exit_receiver.recv();
```
Comment (xiaochengh) [inline components/constellation/constellation.rs:2809]: Should we check error here?

Comment (mrobinson) [reply components/constellation/constellation.rs:2809]: This is happening in the process of shutdown, so an error here likely means that the canvas thread has panicked or deadlocked, in which case I think the right thing to do is to keep trying to shut down.

**Review by jdm — APPROVED** [review]
