### PR TITLE
Fix crash caused by arithmetic underflow in layout2020

### LINKED ISSUE #30878: Servo crash when loading servo.org
```bash
git pull origin main

./mach run
# or ./mach run servo.org 
```
Error message: 

```rust
attempt to subtract with overflow (thread Style#0, at components/layout_2020/flow/inline.rs:182)
   0: servo::backtrace::print
             at /home/tannal/tannalwork/projects/servo/ports/servoshell/backtrace.rs:18:5
   1: servo::main2::main::{{closure}}
             at /home/tannal/tannalwork/projects/servo/ports/servoshell/main2.rs:101:21
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2021:9
      std::panicking::rust_panic_with_hook
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:735:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:601:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
   5: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   6: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   7: core::panicking::panic
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:127:5
   8: layout_2020::flow::inline::LineUnderConstruction::trim_trailing_whitespace
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/inline.rs:182:9
   9: layout_2020::flow::inline::InlineFormattingContextState::finish_current_line_and_reset
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/inline.rs:551:34
  10: layout_2020::flow::inline::InlineFormattingContextState::finish_last_line
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/inline.rs:544:9
  11: layout_2020::flow::inline::InlineFormattingContext::layout
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/inline.rs:1399:9
  12: layout_2020::flow::BlockContainer::layout
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:372:61
  13: layout_2020::flow::layout_in_flow_non_replaced_block_level_same_formatting_context
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:711:23
  14: layout_2020::flow::BlockLevelBox::layout::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:539:21
  15: layout_2020::positioned::PositioningContext::layout_maybe_position_relative_fragment
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/positioned.rs:226:28
  16: layout_2020::flow::BlockLevelBox::layout
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:534:32
  17: layout_2020::flow::layout_block_level_children_sequentially::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:491:32
  18: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/adapters/map.rs:84:28
  19: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/slice/iter/macros.rs:232:27
  20: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/adapters/map.rs:124:9
  21: core::iter::traits::iterator::Iterator::for_each
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/traits/iterator.rs:857:9
  22: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/mod.rs:2881:17
  23: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/spec_extend.rs:26:9
  24: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  25: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/spec_from_iter.rs:33:9
  26: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/mod.rs:2749:9
  27: core::iter::traits::iterator::Iterator::collect
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/traits/iterator.rs:2053:9
  28: layout_2020::flow::layout_block_level_children_sequentially
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:487:21
  29: layout_2020::flow::layout_block_level_children
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:409:50
  30: layout_2020::flow::BlockContainer::layout
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:364:61
  31: layout_2020::flow::layout_in_flow_non_replaced_block_level_same_formatting_context
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:711:23
  32: layout_2020::flow::BlockLevelBox::layout::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:539:21
  33: layout_2020::positioned::PositioningContext::layout_maybe_position_relative_fragment
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/positioned.rs:226:28
  34: layout_2020::flow::BlockLevelBox::layout
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:534:32
  35: layout_2020::flow::layout_block_level_children_sequentially::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:491:32
  36: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/adapters/map.rs:84:28
  37: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/slice/iter/macros.rs:232:27
  38: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/adapters/map.rs:124:9
  39: core::iter::traits::iterator::Iterator::for_each
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/traits/iterator.rs:857:9
  40: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/mod.rs:2881:17
  41: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/spec_extend.rs:26:9
  42: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  43: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/spec_from_iter.rs:33:9
  44: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/mod.rs:2749:9
  45: core::iter::traits::iterator::Iterator::collect
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/traits/iterator.rs:2053:9
  46: layout_2020::flow::layout_block_level_children_sequentially
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:487:21
  47: layout_2020::flow::layout_block_level_children
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:409:50
  48: layout_2020::flow::BlockContainer::layout
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:364:61
  49: layout_2020::flow::layout_in_flow_non_replaced_block_level_same_formatting_context
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:711:23
  50: layout_2020::flow::BlockLevelBox::layout::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:539:21
  51: layout_2020::positioned::PositioningContext::layout_maybe_position_relative_fragment
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/positioned.rs:226:28
  52: layout_2020::flow::BlockLevelBox::layout
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:534:32
  53: layout_2020::flow::layout_block_level_children_sequentially::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:491:32
  54: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/adapters/map.rs:84:28
  55: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/slice/iter/macros.rs:232:27
  56: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/adapters/map.rs:124:9
  57: core::iter::traits::iterator::Iterator::for_each
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/traits/iterator.rs:857:9
  58: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/mod.rs:2881:17
  59: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/spec_extend.rs:26:9
  60: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  61: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/spec_from_iter.rs:33:9
  62: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/mod.rs:2749:9
  63: core::iter::traits::iterator::Iterator::collect
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/traits/iterator.rs:2053:9
  64: layout_2020::flow::layout_block_level_children_sequentially
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:487:21
  65: layout_2020::flow::layout_block_level_children
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:409:50
  66: layout_2020::flow::BlockContainer::layout
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:364:61
  67: layout_2020::flow::layout_in_flow_non_replaced_block_level_same_formatting_context
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:711:23
  68: layout_2020::flow::BlockLevelBox::layout::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:539:21
  69: layout_2020::positioned::PositioningContext::layout_maybe_position_relative_fragment
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/positioned.rs:226:28
  70: layout_2020::flow::BlockLevelBox::layout
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:534:32
  71: layout_2020::flow::layout_block_level_children_sequentially::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:491:32
  72: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/adapters/map.rs:84:28
  73: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/slice/iter/macros.rs:232:27
  74: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/adapters/map.rs:124:9
  75: core::iter::traits::iterator::Iterator::for_each
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/traits/iterator.rs:857:9
  76: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/mod.rs:2881:17
  77: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/spec_extend.rs:26:9
  78: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  79: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/spec_from_iter.rs:33:9
  80: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/mod.rs:2749:9
  81: core::iter::traits::iterator::Iterator::collect
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/traits/iterator.rs:2053:9
  82: layout_2020::flow::layout_block_level_children_sequentially
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:487:21
  83: layout_2020::flow::layout_block_level_children
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:409:50
  84: layout_2020::flow::BlockContainer::layout
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:364:61
  85: layout_2020::flow::layout_in_flow_non_replaced_block_level_same_formatting_context
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:711:23
  86: layout_2020::flow::BlockLevelBox::layout::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:539:21
  87: layout_2020::positioned::PositioningContext::layout_maybe_position_relative_fragment
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/positioned.rs:226:28
  88: layout_2020::flow::BlockLevelBox::layout
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:534:32
  89: layout_2020::flow::layout_block_level_children_sequentially::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:491:32
  90: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/adapters/map.rs:84:28
  91: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/slice/iter/macros.rs:232:27
  92: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/adapters/map.rs:124:9
  93: core::iter::traits::iterator::Iterator::for_each
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/traits/iterator.rs:857:9
  94: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/mod.rs:2881:17
  95: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/spec_extend.rs:26:9
  96: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  97: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/spec_from_iter.rs:33:9
  98: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/vec/mod.rs:2749:9
  99: core::iter::traits::iterator::Iterator::collect
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/traits/iterator.rs:2053:9
 100: layout_2020::flow::layout_block_level_children_sequentially
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:487:21
 101: layout_2020::flow::layout_block_level_children
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:409:50
 102: layout_2020::flow::BlockContainer::layout
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:364:61
 103: layout_2020::flow::BlockFormattingContext::layout
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:215:27
 104: layout_2020::formatting_contexts::NonReplacedFormattingContext::layout
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/formatting_contexts.rs:198:17
 105: layout_2020::flow::<impl layout_2020::formatting_contexts::NonReplacedFormattingContext>::layout_in_flow_block_level
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:839:22
 106: layout_2020::flow::BlockLevelBox::layout::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:574:29
 107: layout_2020::positioned::PositioningContext::layout_maybe_position_relative_fragment
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/positioned.rs:226:28
 108: layout_2020::flow::BlockLevelBox::layout
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:569:35
 109: layout_2020::flow::layout_block_level_children_in_parallel::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:441:28
 110: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:272:13
 111: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:305:13
 112: core::option::Option<T>::map
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/option.rs:1075:29
      <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/iter/adapters/map.rs:103:26
 113: rayon::iter::plumbing::Folder::consume_iter
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/plumbing/mod.rs:178:21
 114: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/map.rs:248:21
 115: rayon::iter::plumbing::Producer::fold_with
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/plumbing/mod.rs:110:9
 116: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/plumbing/mod.rs:438:13
 117: rayon::iter::plumbing::bridge_producer_consumer
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/plumbing/mod.rs:397:12
 118: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/plumbing/mod.rs:373:13
 119: <rayon::slice::Iter<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/slice/mod.rs:732:9
 120: rayon::iter::plumbing::bridge
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/plumbing/mod.rs:357:12
 121: <rayon::slice::Iter<T> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/slice/mod.rs:708:9
 122: <rayon::iter::map::Map<I,F> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/map.rs:49:9
 123: rayon::iter::collect::special_extend::{{closure}}
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/collect/mod.rs:39:46
 124: rayon::iter::collect::collect_with_consumer
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/collect/mod.rs:84:18
 125: rayon::iter::collect::special_extend
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/collect/mod.rs:39:5
 126: rayon::iter::extend::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/extend.rs:582:17
 127: rayon::iter::from_par_iter::collect_extended
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/from_par_iter.rs:19:5
 128: rayon::iter::from_par_iter::<impl rayon::iter::FromParallelIterator<T> for alloc::vec::Vec<T>>::from_par_iter
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/from_par_iter.rs:32:9
 129: rayon::iter::ParallelIterator::collect
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/mod.rs:2056:9
 130: layout_2020::flow::layout_block_level_children_in_parallel
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:436:63
 131: layout_2020::flow::layout_block_level_children
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:417:17
 132: layout_2020::flow::BlockContainer::layout
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:364:61
 133: layout_2020::flow::BlockFormattingContext::layout
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/mod.rs:215:27
 134: layout_2020::flow::root::BoxTree::layout
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/flow/root.rs:285:34
 135: layout_thread_2020::LayoutThread::handle_reflow::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/layout_thread_2020/lib.rs:1013:17
 136: core::ops::function::FnOnce::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
 137: rayon_core::thread_pool::ThreadPool::install::{{closure}}
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/thread_pool/mod.rs:110:40
 138: rayon_core::registry::Registry::in_worker_cold::{{closure}}::{{closure}}
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/registry.rs:521:21
 139: rayon_core::job::JobResult<T>::call::{{closure}}
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/job.rs:218:41
 140: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panic/unwind_safe.rs:271:9
 141: std::panicking::try::do_call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
 142: __rust_try
 143: std::panicking::try
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
 144: std::panic::catch_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
 145: rayon_core::unwind::halt_unwinding
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/unwind.rs:17:5
 146: rayon_core::job::JobResult<T>::call
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/job.rs:218:15
 147: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/job.rs:120:32
 148: rayon_core::job::JobRef::execute
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/job.rs:64:9
 149: rayon_core::registry::WorkerThread::execute
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/registry.rs:859:9
 150: rayon_core::registry::WorkerThread::wait_until_cold
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/registry.rs:793:21
 151: rayon_core::registry::WorkerThread::wait_until
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/registry.rs:768:13
 152: rayon_core::registry::WorkerThread::wait_until_out_of_work
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/registry.rs:817:9
 153: rayon_core::registry::main_loop
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/registry.rs:922:5
 154: rayon_core::registry::ThreadBuilder::run
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/registry.rs:52:18
 155: style::global_style_data::thread_spawn::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/style/global_style_data.rs:64:34
 156: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:154:18
 157: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:529:17
 158: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panic/unwind_safe.rs:271:9
 159: std::panicking::try::do_call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
 160: __rust_try
 161: std::panicking::try
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
 162: std::panic::catch_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:528:30
 163: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
 164: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys/unix/thread.rs:108:17
 165: <unknown>
 166: <unknown>
[2023-12-16T11:39:21Z ERROR servo::main2] attempt to subtract with overflow
called `Result::unwrap()` on an `Err` value: PoisonError { .. } (thread Script(1,1), at components/layout_2020/query.rs:167)
   0: servo::backtrace::print
             at /home/tannal/tannalwork/projects/servo/ports/servoshell/backtrace.rs:18:5
   1: servo::main2::main::{{closure}}
             at /home/tannal/tannalwork/projects/servo/ports/servoshell/main2.rs:101:21
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2021:9
      std::panicking::rust_panic_with_hook
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:735:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:609:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
   5: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   6: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   7: core::result::unwrap_failed
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1652:5
   8: core::result::Result<T,E>::unwrap
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1077:23
   9: <layout_2020::query::LayoutRPCImpl as script_layout_interface::rpc::LayoutRPC>::inner_window_dimensions
             at /home/tannal/tannalwork/projects/servo/components/layout_2020/query.rs:167:23
  10: script::dom::window::Window::inner_window_dimensions_query
             at /home/tannal/tannalwork/projects/servo/components/script/dom/window.rs:2161:9
  11: script::dom::htmliframeelement::HTMLIFrameElement::start_new_pipeline
             at /home/tannal/tannalwork/projects/servo/components/script/dom/htmliframeelement.rs:195:31
  12: script::dom::htmliframeelement::HTMLIFrameElement::create_nested_browsing_context
             at /home/tannal/tannalwork/projects/servo/components/script/dom/htmliframeelement.rs:394:9
  13: <script::dom::htmliframeelement::HTMLIFrameElement as script::dom::virtualmethods::VirtualMethods>::bind_to_tree::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/script/dom/htmliframeelement.rs:732:17
  14: core::ops::function::FnOnce::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
  15: <<script::dom::htmliframeelement::HTMLIFrameElement as script::dom::virtualmethods::VirtualMethods>::bind_to_tree::IFrameDelayedInitialize<F> as script::task::TaskOnce>::run_once
             at /home/tannal/tannalwork/projects/servo/components/script/task.rs:24:17
  16: <T as script::task::TaskBox>::run_box
             at /home/tannal/tannalwork/projects/servo/components/script/task.rs:57:9
  17: script::dom::document::Document::remove_script_and_layout_blocker
             at /home/tannal/tannalwork/projects/servo/components/script/dom/document.rs:3252:13
  18: script::dom::node::Node::insert
             at /home/tannal/tannalwork/projects/servo/components/script/dom/node.rs:2103:9
  19: script::dom::node::Node::pre_insert
             at /home/tannal/tannalwork/projects/servo/components/script/dom/node.rs:1994:9
  20: <script::dom::node::Node as script::dom::bindings::codegen::Bindings::NodeBinding::Node_Binding::NodeMethods>::InsertBefore
             at /home/tannal/tannalwork/projects/servo/components/script/dom/node.rs:2618:9
  21: script::dom::servoparser::insert
             at /home/tannal/tannalwork/projects/servo/components/script/dom/servoparser/mod.rs:1043:13
  22: <script::dom::servoparser::Sink as markup5ever::interface::tree_builder::TreeSink>::append
             at /home/tannal/tannalwork/projects/servo/components/script/dom/servoparser/mod.rs:1210:9
  23: html5ever::tree_builder::TreeBuilder<Handle,Sink>::insert_at
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/html5ever-0.26.0/src/tree_builder/mod.rs:432:34
  24: html5ever::tree_builder::TreeBuilder<Handle,Sink>::insert_element
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/html5ever-0.26.0/src/tree_builder/mod.rs:1319:9
  25: html5ever::tree_builder::TreeBuilder<Handle,Sink>::insert_element_for
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/html5ever-0.26.0/src/tree_builder/mod.rs:1330:9
  26: html5ever::tree_builder::TreeBuilder<Handle,Sink>::parse_raw_data
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/html5ever-0.26.0/src/tree_builder/mod.rs:641:9
  27: html5ever::tree_builder::TreeBuilder<Handle,Sink>::step
             at /home/tannal/tannalwork/projects/servo/target/debug/build/html5ever-9ae0cfe8168d829a/out/rules.rs:693:30
  28: html5ever::tree_builder::TreeBuilder<Handle,Sink>::process_to_completion
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/html5ever-0.26.0/src/tree_builder/mod.rs:336:17
  29: <html5ever::tree_builder::TreeBuilder<Handle,Sink> as html5ever::tokenizer::interface::TokenSink>::process_token
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/html5ever-0.26.0/src/tree_builder/mod.rs:523:9
  30: html5ever::tokenizer::Tokenizer<Sink>::process_token
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/html5ever-0.26.0/src/tokenizer/mod.rs:237:13
  31: html5ever::tokenizer::Tokenizer<Sink>::emit_current_tag
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/html5ever-0.26.0/src/tokenizer/mod.rs:439:15
  32: html5ever::tokenizer::Tokenizer<Sink>::step
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/html5ever-0.26.0/src/tokenizer/mod.rs:977:28
  33: html5ever::tokenizer::Tokenizer<Sink>::run
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/html5ever-0.26.0/src/tokenizer/mod.rs:369:23
  34: html5ever::tokenizer::Tokenizer<Sink>::feed
             at /home/tannal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/html5ever-0.26.0/src/tokenizer/mod.rs:224:9
  35: script::dom::servoparser::html::Tokenizer::feed
             at /home/tannal/tannalwork/projects/servo/components/script/dom/servoparser/html.rs:83:15
  36: script::dom::servoparser::Tokenizer::feed
             at /home/tannal/tannalwork/projects/servo/components/script/dom/servoparser/mod.rs:707:51
  37: script::dom::servoparser::ServoParser::do_parse_sync::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/script/dom/servoparser/mod.rs:571:35
  38: script::dom::servoparser::ServoParser::tokenize
             at /home/tannal/tannalwork/projects/servo/components/script/dom/servoparser/mod.rs:609:32
  39: script::dom::servoparser::ServoParser::do_parse_sync
             at /home/tannal/tannalwork/projects/servo/components/script/dom/servoparser/mod.rs:571:9
  40: script::dom::servoparser::ServoParser::parse_sync::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/script/dom/servoparser/mod.rs:553:16
  41: profile_traits::time::profile
             at /home/tannal/tannalwork/projects/servo/components/shared/profile/time.rs:147:15
  42: script::dom::servoparser::ServoParser::parse_sync
             at /home/tannal/tannalwork/projects/servo/components/script/dom/servoparser/mod.rs:545:9
  43: script::dom::servoparser::ServoParser::parse_bytes_chunk
             at /home/tannal/tannalwork/projects/servo/components/script/dom/servoparser/mod.rs:596:13
  44: <script::dom::servoparser::ParserContext as net_traits::FetchResponseListener>::process_response_chunk
             at /home/tannal/tannalwork/projects/servo/components/script/dom/servoparser/mod.rs:944:9
  45: script::script_thread::ScriptThread::handle_fetch_chunk
             at /home/tannal/tannalwork/projects/servo/components/script/script_thread.rs:3892:13
  46: script::script_thread::ScriptThread::handle_msg_from_constellation
             at /home/tannal/tannalwork/projects/servo/components/script/script_thread.rs:1944:25
  47: script::script_thread::ScriptThread::handle_msgs::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/script/script_thread.rs:1660:53
  48: script::script_thread::ScriptThread::profile_event
             at /home/tannal/tannalwork/projects/servo/components/script/script_thread.rs:1912:13
  49: script::script_thread::ScriptThread::handle_msgs
             at /home/tannal/tannalwork/projects/servo/components/script/script_thread.rs:1654:26
  50: script::script_thread::ScriptThread::start
             at /home/tannal/tannalwork/projects/servo/components/script/script_thread.rs:1448:15
  51: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/script/script_thread.rs:842:25
  52: profile_traits::mem::ProfilerChan::run_with_memory_reporting
             at /home/tannal/tannalwork/projects/servo/components/shared/profile/mem.rs:91:9
  53: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/script/script_thread.rs:840:17
  54: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:154:18
  55: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:529:17
  56: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panic/unwind_safe.rs:271:9
  57: std::panicking::try::do_call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  58: __rust_try
  59: std::panicking::try
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  60: std::panic::catch_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:528:30
  61: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
  62: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys/unix/thread.rs:108:17
  63: <unknown>
  64: <unknown>
[2023-12-16T11:39:22Z ERROR servo::main2] called `Result::unwrap()` on an `Err` value: PoisonError { .. }
called `Result::unwrap()` on an `Err` value: PoisonError { .. } (thread LayoutPipeline(1,2), at components/layout_thread_2020/lib.rs:962)
   0: servo::backtrace::print
             at /home/tannal/tannalwork/projects/servo/ports/servoshell/backtrace.rs:18:5
   1: servo::main2::main::{{closure}}
             at /home/tannal/tannalwork/projects/servo/ports/servoshell/main2.rs:101:21
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2021:9
      std::panicking::rust_panic_with_hook
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:735:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:609:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
   5: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   6: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   7: core::result::unwrap_failed
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1652:5
   8: core::result::Result<T,E>::unwrap
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1077:23
   9: layout_thread_2020::LayoutThread::handle_reflow
             at /home/tannal/tannalwork/projects/servo/components/layout_thread_2020/lib.rs:962:26
  10: layout_thread_2020::LayoutThread::handle_request_helper::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/layout_thread_2020/lib.rs:655:24
  11: profile_traits::time::profile
             at /home/tannal/tannalwork/projects/servo/components/shared/profile/time.rs:147:15
  12: layout_thread_2020::LayoutThread::handle_request_helper
             at /home/tannal/tannalwork/projects/servo/components/layout_thread_2020/lib.rs:651:17
  13: layout_thread_2020::LayoutThread::handle_request
             at /home/tannal/tannalwork/projects/servo/components/layout_thread_2020/lib.rs:599:41
  14: layout_thread_2020::LayoutThread::start
             at /home/tannal/tannalwork/projects/servo/components/layout_thread_2020/lib.rs:498:15
  15: <layout_thread_2020::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/layout_thread_2020/lib.rs:263:29
  16: profile_traits::mem::ProfilerChan::run_with_memory_reporting
             at /home/tannal/tannalwork/projects/servo/components/shared/profile/mem.rs:91:9
  17: <layout_thread_2020::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/layout_thread_2020/lib.rs:261:21
  18: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:154:18
  19: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:529:17
  20: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panic/unwind_safe.rs:271:9
  21: std::panicking::try::do_call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  22: __rust_try
  23: std::panicking::try
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  24: std::panic::catch_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:528:30
  25: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
  26: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys/unix/thread.rs:108:17
  27: <unknown>
  28: <unknown>
[2023-12-16T11:39:22Z ERROR servo::main2] called `Result::unwrap()` on an `Err` value: PoisonError { .. }
[2023-12-16T11:39:22Z ERROR constellation::constellation] crash page crashed
condition was Some(DirtyDescendants) (thread Script(1,2), at components/script/dom/window.rs:1997)
   0: servo::backtrace::print
             at /home/tannal/tannalwork/projects/servo/ports/servoshell/backtrace.rs:18:5
   1: servo::main2::main::{{closure}}
             at /home/tannal/tannalwork/projects/servo/ports/servoshell/main2.rs:101:21
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2021:9
      std::panicking::rust_panic_with_hook
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:735:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:609:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
   5: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   6: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   7: script::dom::window::Window::reflow
             at /home/tannal/tannalwork/projects/servo/components/script/dom/window.rs:1997:13
   8: script::dom::document::Document::finish_load
             at /home/tannal/tannalwork/projects/servo/components/script/dom/document.rs:2102:21
   9: script::dom::servoparser::ServoParser::finish
             at /home/tannal/tannalwork/projects/servo/components/script/dom/servoparser/mod.rs:661:9
  10: script::dom::servoparser::ServoParser::do_parse_sync
             at /home/tannal/tannalwork/projects/servo/components/script/dom/servoparser/mod.rs:580:13
  11: script::dom::servoparser::ServoParser::parse_sync::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/script/dom/servoparser/mod.rs:553:16
  12: profile_traits::time::profile
             at /home/tannal/tannalwork/projects/servo/components/shared/profile/time.rs:147:15
  13: script::dom::servoparser::ServoParser::parse_sync
             at /home/tannal/tannalwork/projects/servo/components/script/dom/servoparser/mod.rs:545:9
  14: <script::dom::servoparser::ParserContext as net_traits::FetchResponseListener>::process_response_eof
             at /home/tannal/tannalwork/projects/servo/components/script/dom/servoparser/mod.rs:974:13
  15: script::script_thread::ScriptThread::handle_fetch_eof
             at /home/tannal/tannalwork/projects/servo/components/script/script_thread.rs:3906:13
  16: script::script_thread::ScriptThread::handle_msg_from_constellation
             at /home/tannal/tannalwork/projects/servo/components/script/script_thread.rs:1946:66
  17: script::script_thread::ScriptThread::handle_msgs::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/script/script_thread.rs:1660:53
  18: script::script_thread::ScriptThread::profile_event
             at /home/tannal/tannalwork/projects/servo/components/script/script_thread.rs:1912:13
  19: script::script_thread::ScriptThread::handle_msgs
             at /home/tannal/tannalwork/projects/servo/components/script/script_thread.rs:1654:26
  20: script::script_thread::ScriptThread::start
             at /home/tannal/tannalwork/projects/servo/components/script/script_thread.rs:1448:15
  21: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/script/script_thread.rs:842:25
  22: profile_traits::mem::ProfilerChan::run_with_memory_reporting
             at /home/tannal/tannalwork/projects/servo/components/shared/profile/mem.rs:91:9
  23: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}
             at /home/tannal/tannalwork/projects/servo/components/script/script_thread.rs:840:17
  24: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:154:18
  25: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:529:17
  26: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panic/unwind_safe.rs:271:9
  27: std::panicking::try::do_call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  28: __rust_try
  29: std::panicking::try
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  30: std::panic::catch_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:528:30
  31: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
  32: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys/unix/thread.rs:108:17
  33: <unknown>
  34: <unknown>
[2023-12-16T11:39:22Z ERROR servo::main2] condition was Some(DirtyDescendants)
[2023-12-16T11:39:22Z ERROR constellation::constellation] crash page crashed

```

### PR DESCRIPTION
**Pull request by atbrakhi**
Currently we are trying to subtract a non-zero number from 0 in `self.justification_opportunities -= spaces_trimmed`, which is resulting in an arithmetic underflow in the `trim_trailing_whitespace` inside `inline.rs`, hence the crash.

This PR prevents the underflow by using `checked_sub` for safe subtraction.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #30878
- [x] There are tests for these changes

### CODE REVIEW

File: components/layout_2020/flow/inline.rs [hunk 1]
```diff
@@ -179,7 +179,10 @@ impl LineUnderConstruction {
                 break;
             }
         }
-        self.justification_opportunities -= spaces_trimmed;
+        self.justification_opportunities = self
+            .justification_opportunities
+            .checked_sub(spaces_trimmed)
+            .unwrap_or(0);
```
Comment (mrobinson) [inline components/layout_2020/flow/inline.rs:185]: I think this might be papering over the issue. We shouldn't be subtracting more justification opportunities than we counted up to this point.

**Comment by mrobinson** [comment]
Looks like the issue is that when processing the last line, I zeroed out the number of justification opportunities. That's not going to work when subtracting later in `finish_line_and_reset()`. :) Here's another fix which I think gets closer to fixing the root of the issue:

```diff
diff --git a/components/layout_2020/flow/inline.rs b/components/layout_2020/flow/inline.rs
index 2b99cd63cd..ca5360469a 100644
--- a/components/layout_2020/flow/inline.rs
+++ b/components/layout_2020/flow/inline.rs
@@ -535,23 +535,23 @@ impl<'a, 'b> InlineFormattingContextState<'a, 'b> {
         // there is no line wrapping, so this forces the segment into the current line.
         self.commit_current_segment_to_line();
 
-        // This has the effect of preventing the application of `text-align: justify` to
-        // this line because no justification opportunities means no justification.
-        self.current_line.justification_opportunities = 0;
-
         // Finally we finish the line itself and convert all of the LineItems into
         // fragments.
-        self.finish_current_line_and_reset();
+        self.finish_current_line_and_reset(true /* last_line */);
     }
 
     /// Finish layout of all inline boxes for the current line. This will gather all
     /// [`LineItem`]s and turn them into [`Fragment`]s, then reset the
     /// [`InlineFormattingContextState`] preparing it for laying out a new line.
-    fn finish_current_line_and_reset(&mut self) {
+    fn finish_current_line_and_reset(&mut self, last_line: bool) {
         let whitespace_trimmed = self.current_line.trim_trailing_whitespace();
-        let (inline_start_position, justification_adjustment) = self
+        let (inline_start_position, mut justification_adjustment) = self
             .calculate_current_line_inline_start_and_justification_adjustment(whitespace_trimmed);
 
+        if last_line {
+            justification_adjustment = Length::zero();
+        }
+
         let block_start_position = self
             .current_line
             .line_block_start_considering_placement_among_floats();
@@ -1029,7 +1029,7 @@ impl<'a, 'b> InlineFormattingContextState<'a, 'b> {
                 &self.current_line,
                 self.inline_box_state_stack.len(),
             );
-        self.finish_current_line_and_reset();
+        self.finish_current_line_and_reset(false /* last_line */);
     }
 
     /// Process a soft wrap opportunity. This will either commit the current unbreakble
```

**Review by mrobinson — APPROVED** [review]
Looks good to me, though I would remove the WPT test. I think this one is covered by existing tests. We just don't run them in debug mode so we didn't catch it.
