### PR TITLE
Fix devtool crashs after clicking `Enable connection prompt`

### LINKED ISSUE #33304: Clicking on `Enable connection prompt` in Firefox crashes DevTools.
**Describe the bug:**
Clicking on `Enable connection prompt` on Firefox crashs  Servo Devtool

**To Reproduce:**
Run Servo with Devtool `./mach run -d --devtools=6080` then open Firefox connect then click `Enable connection prompt`

image

**Platform:**
macOS

`handle_message` expects `msg.get("value")` to always return a `String`, but clicking on `Enable connection prompt` sends `"value": Bool(true)`, which causes this line to crash.

https://github.com/servo/servo/blob/e857cdf022f319ae3fbd54e10e279ab43485995b/components/devtools/actors/preference.rs#L40

### PR DESCRIPTION
**Pull request by Taym95**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #33304
- [x] These changes do not have tests, because there are no DevTools tests.

### CODE REVIEW

**Comment by mrobinson** [comment]
" These changes do not require tests because no behavior change."

I think these changes do change behavior. I'll just change this to say that there aren't tests ATM for devtools.

File: components/devtools/actors/preference.rs [hunk 1]
```diff
@@ -37,7 +38,13 @@ impl Actor for PreferenceActor {
...
         _id: StreamId,
     ) -> Result<ActorMessageStatus, ()> {
-        let mut key = msg.get("value").unwrap().as_str().unwrap();
+        let mut key = match msg.get("value").unwrap() {
+            Value::String(value) => value.as_str(),
+            _ => {
+                warn!("PreferenceActor: handle_message: value is not a string");
+                return Ok(ActorMessageStatus::Ignored);
+            },
+        };
```
Comment (mrobinson) [inline components/devtools/actors/preference.rs:47]: Perhaps this could be a bit simpler?

```suggestion
        let mut Some(key) = match msg.get("value").unwrap().as_str() else {
            warn!("PreferenceActor: handle_message: value is not a string");
            return Ok(ActorMessageStatus::Ignored);
        };
```

Comment (Taym95) [reply components/devtools/actors/preference.rs:47]: I tried it, but doesn’t it seem like the correct syntax?

Comment (jdm) [reply components/devtools/actors/preference.rs:47]: Yeah, the match keyword needs to be removed.

File: components/devtools/actors/preference.rs [hunk 2]
```diff
@@ -37,25 +38,28 @@ impl Actor for PreferenceActor {
...
-        // Mapping to translate a Firefox preference name onto the corresponding Servo preference name
-        let pref_name_mapping: HashMap<&str, &str> =
-            [("dom.serviceWorkers.enabled", "dom.serviceworker.enabled")]
-                .iter()
-                .copied()
-                .collect();
-        if pref_name_mapping.contains_key(key) {
-            key = pref_name_mapping.get(key).unwrap();
-        }
+        if let Some(mut key) = msg.get("value").unwrap().as_str() {
```
Comment (Taym95) [inline components/devtools/actors/preference.rs:41]: @mrobinson do you think we can merge this one?

File: components/devtools/actors/preference.rs [hunk 3]
```diff
@@ -37,25 +38,28 @@ impl Actor for PreferenceActor {
...
+            Ok(handle_preference_value(
+                pref_value,
+                self.name(),
+                msg_type,
+                stream,
+            ))
+        } else {
+            warn!("PreferenceActor: handle_message: value is not a string");
+            return Ok(ActorMessageStatus::Ignored);
+        }
```
Comment (mrobinson) [inline components/devtools/actors/preference.rs:62]: I think it makes a bit more sense to have this as an early return rather than wrapping the entire logic of the function in the error condition check.

Comment (Taym95) [reply components/devtools/actors/preference.rs]: done, thanks!

**Review by mrobinson — APPROVED** [review]
Thanks!
