### PR TITLE
servoshell: Update the debug options (`-Z`) help to reflect current set of options

### LINKED ISSUE #39311: Some servoshell debug options ( `-Z`) are broken.
`./mach run -r -Z show-fragment-borders` and ` ./mach run -r -Z show-parallel-layout` fail with the following error:
```
❯ ./mach run -r -Z show-fragment-borders 
NOTE: Entering nix-shell ./shell.nix
error: urnecognized debug option: show-fragment-borders
Servo exited with non-zero status 1
```

```
❯ ./mach run -r -Z show-parallel-layout 
NOTE: Entering nix-shell ./shell.nix
error: urnecognized debug option: show-parallel-layout
Servo exited with non-zero status 1
```

Also, the `wr-stats` option doesn't seem to do anything. The description says it displays the stats on the screen, but I don't see anything (for servo.org).

**Platform:**
Tested on NixOS , but presumably all platforms.

### PR DESCRIPTION
**Pull request by Narfinger**
The command-line help output for `-Z` and `DebugOptions were out of sync again. This change makes sure they match again.

Testing: No tests necessary as this mainly just updates the help output.
Fixes: #39311

### CODE REVIEW

File: ports/servoshell/prefs.rs [hunk 1]
```diff
@@ -747,14 +743,6 @@ fn print_debug_options_usage(app: &str) {
         "dump-stacking-context-tree",
         "Print the stacking context tree after each layout.",
     );
-    print_option(
-        "dump-display-list",
```
Comment (mukilan) [inline ports/servoshell/prefs.rs:751]: This one still works. Is this being removed intentionally? Only the `dump-display-list-json` option was removed in #34994.

File: ports/servoshell/prefs.rs [hunk 2]
```diff
@@ -781,18 +765,11 @@ fn print_debug_options_usage(app: &str) {
...
-    );
-    print_option(
-        "show-parallel-layout",
-        "Mark which thread laid each flow out with colors.",
-    );
     print_option(
         "signpost",
         "Emit native OS signposts for profile events (currently macOS only)",
     );
+    print_option("dump-style-stats", "Print style stats after each restyle.");
```
Comment (mukilan) [inline ports/servoshell/prefs.rs]: Any reason to move this here, instead of having it grouped with the other "dump" options?

File: ports/servoshell/prefs.rs [hunk 3]
```diff
@@ -767,12 +755,8 @@ fn print_debug_options_usage(app: &str) {
         "dump-style-tree",
         "Print the DOM with computed styles after each restyle.",
     );
-    print_option("dump-style-stats", "Print style statistics each restyle.");
```
Comment (mukilan) [inline ports/servoshell/prefs.rs:770]: This also works. Any reason this is being removed?

File: components/config/opts.rs [hunk 4]
```diff
@@ -6,6 +6,7 @@
 //! from command line arguments.
 
 use std::default::Default;
+use std::fmt::Debug;
```
Comment (mukilan) [inline components/config/opts.rs]: This doesn't seem to be used anywhere. Is this needed?

**Review by mukilan — APPROVED** [review]
Thank you!

File: components/config/opts.rs [hunk 5]
```diff
@@ -174,6 +175,66 @@ impl DebugOptions {
...
+            "Emit native OS signposts for profile events (currently macOS only)",
+        );
+        print_option(
+            "trace-layout",
+            "Write layout trace to an external file for debugging.",
+        );
+        print_option("wr-stats", "Show WebRender profiler on screen.");
+
+        println!();
+    }
```
Comment (mrobinson) [inline components/config/opts.rs]: This was moved to `servoshell` as `Opts` doesn't handle command-line arguments and thus shouldn't be responsible for dumping help output for them. I think it makes sense to keep this in servoshell.

**Review by mrobinson — CHANGES_REQUESTED** [review]

File: components/config/opts.rs (hunk 5 above)
Comment (Narfinger) [reply components/config/opts.rs]: I think the problem is that it will always be out of sync if it is not close. I think if we really want to keep it in servo she'll, I can at least add a comment to the DebugOptions struct.

Comment (mrobinson) [reply components/config/opts.rs]: They shouldn't be out of sync for long, as I have plans to integrate these options into the Servo API via a `ServoLoggingSettings` struct that will have parsing capability as well. Once that happens this code will likely go away. For the moment, I think it's better to keep all of the command-line parsing and help code together though.

@Narfinger I'm happy to do this as you are on vacation now.

Comment (Narfinger) [reply components/config/opts.rs]: Ok that makes sense. 
Feel free to do it.

**Review by mrobinson — APPROVED** [review]
