### PR TITLE
script(webdriver): Element send keys append to the end of `filelist` if Multiple

### LINKED ISSUE #38190: Webdriver Send Keys: files should be appended to element's selected files instead of overwritten
**Describe the bug:**
https://w3c.github.io/webdriver/#element-send-keys
Step 8.6 (file is true):
If multiple is true files are be appended to element's [selected files](https://w3c.github.io/webdriver/#dfn-selected-files).

----
Rn, it would overwritten instead.

**To Reproduce:**
- Create session
- Find `<input>` element
- send element key twice.

```html
<!DOCTYPE html>
<html>
<body>
    <input type="file" multiple>
    <button onclick="logFiles()">Log Files</button>
    
    <script>
        function logFiles() {
            const files = document.querySelector('input').files;
            return files;
        }
    </script>
</body>
</html>
```

### PR DESCRIPTION
**Pull request by PotatoCP**
Step 8.6 of [Element Send Keys](https://w3c.github.io/webdriver/#dfn-element-send-keys) remote end's implementation.
> 6. Complete implementation specific steps equivalent to setting the [selected files](https://w3c.github.io/webdriver/#dfn-selected-files) on the [input](https://w3c.github.io/webdriver/#dfn-input) element. **If multiple is true files are be appended to element's [selected files](https://w3c.github.io/webdriver/#dfn-selected-files).**

Testing: `webdriver/tests/classic/element_send_keys/file_upload.py`
Fixes: https://github.com/servo/servo/issues/38190

### CODE REVIEW

**Comment by PotatoCP** [comment]
cc: @xiaochengh @longvatrong111 @yezhizhen

File: components/script/dom/htmlinputelement.rs [hunk 1]
```diff
@@ -2278,6 +2278,7 @@ impl HTMLInputElement {
     pub(crate) fn select_files(
         &self,
         opt_test_paths: Option<Vec<DOMString>>,
+        append: bool,
```
Comment (yezhizhen) [inline components/script/dom/htmlinputelement.rs]:
```suggestion
```

File: components/script/dom/htmlinputelement.rs [hunk 2]
```diff
@@ -1963,7 +1963,7 @@ impl HTMLInputElementMethods<crate::DomTypeHolder> for HTMLInputElement {
     // check-tidy: no specs after this line
     fn SelectFiles(&self, paths: Vec<DOMString>, can_gc: CanGc) {
         if self.input_type() == InputType::File {
-            let _ = self.select_files(Some(paths), can_gc);
+            let _ = self.select_files(Some(paths), false, can_gc);
```
Comment (yezhizhen) [inline components/script/dom/htmlinputelement.rs]:
```suggestion
            let _ = self.select_files(Some(paths), can_gc);
```

File: components/script/dom/htmlinputelement.rs [hunk 3]
```diff
@@ -3463,7 +3479,7 @@ impl Activatable for HTMLInputElement {
             },
             // https://html.spec.whatwg.org/multipage/#file-upload-state-(type=file):input-activation-behavior
             InputType::File => {
-                let _ = self.select_files(None, can_gc);
+                let _ = self.select_files(None, false, can_gc);
```
Comment (yezhizhen) [inline components/script/dom/htmlinputelement.rs]:
```suggestion
                let _ = self.select_files(None, can_gc);
```

File: components/script/dom/htmlinputelement.rs [hunk 4]
```diff
@@ -2291,6 +2292,21 @@ impl HTMLInputElement {
         let target = self.upcast::<EventTarget>();
 
         if self.Multiple() {
+            // When using WebDriver command element send keys,
+            // we are expected to append the files to the existing filelist.
+            if append {
```
Comment (yezhizhen) [inline components/script/dom/htmlinputelement.rs]:
```suggestion
            if pref!(dom_testing_html_input_element_select_files_enabled) {
```

This suggestion is inspired by 291b42f6e972b2b46d2ff774404adebd53b51676 and is not ideal. I am thinking about creating another entry in `Preferences` reflecting "webdriver mode", and always override user preference.

Another option is to revert https://github.com/servo/servo/issues/37843. Then we can `opts::get().webdriver_port.is_some()`

What would you suggest? @jdm

**Review by yezhizhen — CHANGES_REQUESTED** [review]
This can be made much simpler. I basically reverted most changes.

But I need some suggestions from @jdm. Pls see below https://github.com/servo/servo/pull/38407#discussion_r2247675270.

File: components/script/webdriver_handlers.rs [hunk 5]
```diff
@@ -1105,7 +1105,7 @@ fn handle_send_keys_file(
     // Step 6. Set the selected files on the input event.
     // TODO: If multiple is true files are be appended to element's selected files.
     // Step 7. Fire input and change event (should already be fired in `htmlinputelement.rs`)
-    if file_input.select_files(Some(files), can_gc).is_err() {
+    if file_input.select_files(Some(files), true, can_gc).is_err() {
```
Comment (yezhizhen) [inline components/script/webdriver_handlers.rs]:
```suggestion
    if file_input.select_files(Some(files), can_gc).is_err() {
```

File: components/script/dom/htmlinputelement.rs (hunk 4 above)
Comment (PotatoCP) [reply components/script/dom/htmlinputelement.rs]: Hmm, my implementation is similar to chromium https://source.chromium.org/chromium/chromium/src/+/main:chrome/test/chromedriver/chrome/web_view_impl.cc;l=1910-1934;bpv=0;bpt=1. With your approach, that means that file input through other ways than WebDriver will also be appended when we open the WebDriver port?

Comment (yezhizhen) [reply components/script/dom/htmlinputelement.rs]: I see your points. If we enable webdriver port but use it interactively, the interactive behaviour is also changed.

Then it is the same situation for 291b42f6e972b2b46d2ff774404adebd53b51676. If we want it to also preserve interactive behaviour when webdriver port enabled, we may have to revert #37843..
Personally I don't mind the interactive behaviour change as it makes things simpler.
But I'll defer to @jdm to decide.

Comment (yezhizhen) [reply components/script/dom/htmlinputelement.rs]: For now, I think we should still apply the suggestion so that we don't need to revert many things. Just use preference `dom_testing_html_input_element_select_files_enabled` for now to keep things simple.

Comment (PotatoCP) [reply components/script/dom/htmlinputelement.rs]: > For now, I think we should still apply the suggestion so that we don't need to revert many things. Just use preference `dom_testing_html_input_element_select_files_enabled` for now to keep things simple.

I've just pushed. Thanks

**Review by yezhizhen — APPROVED** [review]

**Review by yezhizhen — APPROVED** [review]
@xiaochengh This is ready to merge now.

**Review by jdm — APPROVED** [review]
