### PR TITLE
script: Implement pointer events

### LINKED ISSUE #38435: `pointerdown` and `pointerup` event are never sent
**To Reproduce:**
```html
<!DOCTYPE html>
<html>
<body>
    <input type="button" value="sigh" onpointerdown="console.log('pointerdown')" onpointerup="console.log('pointerup')" onclick="console.log('click')">
    <span onpointerdown="console.log('pointerdown')" onpointerup="console.log('pointerup')" onclick="console.log('click')">lol</span>
</body>
</html>
```

**Platform:**
All.

### PR DESCRIPTION
**Pull request by webbeef**
Remaining failures are due to the missing implementation of the pointer capture and pointer lock APIs, as well as:

Requires User Activation support:
/html/user-activation/activation-trigger-pointerevent.html?mouse

Blocked on https://github.com/servo/servo/issues/41227 : /pointerevents/compat/pointerevent_mouse-pointer-on-scrollbar.html

Requires persistentDeviceId:
/pointerevents/persistentDeviceId/get-persistendeviceid-from-pointer-event.tentative.html /pointerevents/persistentDeviceId/get-persistendeviceid-from-pointer-mouse-event.tentative.html

Requires pointerenter, pointerover, pointerout, pointerleave events: /pointerevents/pointerevent_pointerId_scope.html

Requires pointerrawupdate event:
/pointerevents/pointerevent_pointerrawupdate.html
/pointerevents/pointerevent_pointerrawupdate.https.html

Consider implementing non-standard attributes toElement and fromElement: See https://w3c.github.io/pointerevents/#attributes-and-default-actions

Fails because the pointerId is always 0 for pointermove, maybe caused by commit 7b00b54ee83 : /pointerevents/pointerevent_pointermove_isprimary_same_as_pointerdown.html?touch https://github.com/servo/servo/issues/41250

Testing: Updated wpt expectations
Fixes: https://github.com/servo/servo/issues/38435

### CODE REVIEW

File: components/script/dom/document_event_handler.rs [hunk 1]
```diff
@@ -96,6 +97,11 @@ pub(crate) struct DocumentEventHandler {
     /// The active keyboard modifiers for the WebView. This is updated when receiving any input event.
     #[no_trace]
     active_keyboard_modifiers: Cell<Modifiers>,
+    /// Map from touch identifier to pointer ID for active touch points
+    #[ignore_malloc_size_of = "Defined in std"]
```
Comment (simonwuelker) [inline components/script/dom/document_event_handler.rs]: This should not be necessary (https://github.com/servo/servo/blob/main/components/malloc_size_of/lib.rs#L528)

File: components/script/dom/document_event_handler.rs [hunk 2]
```diff
@@ -1639,4 +1720,42 @@ impl DocumentEventHandler {
...
+        let active_pointer_ids = self.active_pointer_ids.borrow();
+        if active_pointer_ids.is_empty() {
+            return false;
+        }
+
+        let min_pointer_id = active_pointer_ids
+            .values()
+            .min()
+            .copied()
+            .unwrap_or(i32::MAX);
```
Comment (simonwuelker) [inline components/script/dom/document_event_handler.rs]: I think 
```rust
self.active_pointer_ids
    .borrow()
    .values()
    .min()
    .is_some_and(|primary_pointer| primary_pointer == pointer_id)
```
would be more understandable.

File: components/script/dom/mouseevent.rs [hunk 3]
```diff
@@ -293,6 +293,63 @@ impl MouseEvent {
...
+    /// <https://w3c.github.io/pointerevents/#the-primary-pointer>
+    /// For mouse, the pointer ID is always -1, and is_primary is always true.
+    pub(crate) fn to_pointer_event(
+        &self,
+        event_type: &str,
+        can_gc: CanGc,
+    ) -> DomRoot<crate::dom::pointerevent::PointerEvent> {
+        use std::f64::consts::PI;
+
+        use crate::dom::pointerevent::{PointerEvent, PointerId};
```
Comment (simonwuelker) [inline components/script/dom/mouseevent.rs]: Please put these imports at the top of the file

**Review by simonwuelker — COMMENTED** [review]
I'm not familiar enough with this part of the code to actually review it, but here are some immediate thoughts I had.

File: components/script/dom/document_event_handler.rs (hunk 1 above)
Comment (webbeef) [reply components/script/dom/document_event_handler.rs]: good catch, thanks!

File: components/script/dom/document_event_handler.rs (hunk 2 above)
Comment (webbeef) [reply components/script/dom/document_event_handler.rs]: indeed, that's better.

File: components/script/dom/mouseevent.rs (hunk 3 above)
Comment (webbeef) [reply components/script/dom/mouseevent.rs]: :man_facepalming:

**Comment by yezhizhen** [comment]
What is the status of this PR? Can you rebase given that #41801 is merged.

**Comment by webbeef** [comment]
> What is the status of this PR? Can you rebase given that #41801 is merged.

There are new unexpected failures in https://github.com/webbeef/servo/actions/runs/21124024992 and it looks like we still don't pass `pointerevents/pointerevent_pointermove_isprimary_same_as_pointerdown.html?touch` . I haven't debugged to know if this is an issue with this patch or with the webdriver event injection.

I won't have much time to check, so feel free to take over if you want @yezhizhen

File: components/script/dom/pointerevent.rs [hunk 4]
```diff
@@ -204,6 +205,8 @@ impl PointerEvent {
             related_target,
             point_in_target,
         );
+        ev.mouseevent.upcast::<Event>().set_trusted(true);
+        ev.mouseevent.upcast::<Event>().set_composed(true);
```
Comment (Gae24) [inline components/script/dom/pointerevent.rs]: I was wondering if these are the default values, and after looking up, `pointerenter` and `pointerleave` [shouldn't be composed](https://w3c.github.io/pointerevents/#attributes-and-default-actions)

File: components/script/dom/document_event_handler.rs [hunk 5]
```diff
@@ -145,6 +145,7 @@ pub(crate) struct DocumentEventHandler {
     click_counting_info: DomRefCell<ClickCountingInfo>,
     #[no_trace]
     last_mouse_button_down_point: Cell<Option<Point2D<f32, CSSPixel>>>,
+    down_button_count: Cell<u32>,
```
Comment (Gae24) [inline components/script/dom/document_event_handler.rs:150]: The only thing missing is a comment that would expand on its purpose.

File: components/script/dom/pointerevent.rs (hunk 4 above)
Comment (webbeef) [reply components/script/dom/pointerevent.rs]: thanks!

**Comment by webbeef** [comment]
@Gae24 I feel it's ready and would do some of the missing parts in follow ups.

File: components/script/dom/document_event_handler.rs [hunk 6]
```diff
@@ -1695,4 +1779,41 @@ impl DocumentEventHandler {
...
+        self.active_pointer_ids.borrow_mut().remove(&touch_id);
+    }
+
+    /// Check if this is the primary pointer (for touch events).
+    /// The first touch to make contact is the primary pointer.
+    fn is_primary_pointer(&self, pointer_id: i32) -> bool {
+        // For touch, the primary pointer is the one with the smallest pointer ID
+        // that is still active.
+        let active_pointer_ids = self.active_pointer_ids.borrow();
+        if active_pointer_ids.is_empty() {
```
Comment (Gae24) [inline components/script/dom/document_event_handler.rs]: Isn't this check redundant?

File: components/script/dom/pointerevent.rs [hunk 7]
```diff
@@ -189,6 +190,8 @@ impl PointerEvent {
         can_gc: CanGc,
     ) -> DomRoot<PointerEvent> {
         let ev = PointerEvent::new_uninitialized_with_proto(window, proto, can_gc);
+        // See <https://w3c.github.io/pointerevents/#attributes-and-default-actions>
+        let composed = !(type_ == "pointerenter" || type_ == "pointerleave");
```
Comment (Gae24) [inline components/script/dom/pointerevent.rs]:
```suggestion
        let composed = type_ != "pointerenter" && type_ != "pointerleave";
```
Nit: I think it is clearer this way.

**Review by Gae24 — CHANGES_REQUESTED** [review]

File: components/script/dom/document_event_handler.rs (hunk 6 above)
Comment (webbeef) [reply components/script/dom/document_event_handler.rs]: indeed

File: components/script/dom/pointerevent.rs (hunk 7 above)
Comment (webbeef) [reply components/script/dom/pointerevent.rs]: ok, wfm

**Review by Gae24 — APPROVED** [review]

File: tests/wpt/tests/pointerevents/pointerevent_capture_mouse.html [hunk 8]
```diff
@@ -139,7 +139,7 @@ <h4>
                 on_event(target1, "pointermove", function (event) {
                     test(function() {
                         assert_false(isPointerCapture, "pointermove shouldn't trigger for this target when capture is enabled");
-                    }, "pointermove shouldn't trigger for the purple rectangle while the black rectangle has capture");
+                    }, `pointermove shouldn't trigger for the purple rectangle while the black rectangle has capture, isPointerCapture=${isPointerCapture}`);
```
Comment (Gae24) [inline tests/wpt/tests/pointerevents/pointerevent_capture_mouse.html:142]: I guess this should be reverted before merge.

File: components/script/dom/pointerevent.rs [hunk 9]
```diff
@@ -204,6 +207,8 @@ impl PointerEvent {
             related_target,
             point_in_target,
         );
+        ev.mouseevent.upcast::<Event>().set_trusted(true);
```
Comment (jdm) [inline components/script/dom/pointerevent.rs]: This isn't safe—new_with_proto is called from PointerEvent::Constructor, so this makes user-constructed events trusted.

File: tests/wpt/meta/pointerevents/pointerevent_releasepointercapture_release_right_after_capture.html.ini [hunk 10]
```diff
@@ -1,16 +1,10 @@
 [pointerevent_releasepointercapture_release_right_after_capture.html?touch]
-  expected: TIMEOUT
-  [Release pointer capture right after setpointercapture]
-    expected: NOTRUN
-
+  expected: ERROR
```
Comment (jdm) [inline tests/wpt/meta/pointerevents/pointerevent_releasepointercapture_release_right_after_capture.html.ini:2]: There are a lot of new ERROR results in this PR; it would be good to understand where they're coming from and if it's just one thing we haven't implemented correctly or a bunch of things.

**Review by jdm — APPROVED** [review]

File: tests/wpt/meta/pointerevents/pointerevent_releasepointercapture_release_right_after_capture.html.ini (hunk 10 above)
Comment (webbeef) [reply tests/wpt/meta/pointerevents/pointerevent_releasepointercapture_release_right_after_capture.html.ini:2]: As far as I can tell, they are mostly due to us not implementing some of the events and the pointercapture/capturelock apis. We used to not run the tests at all, now we eg. pass the `pointerdown` steps but still fail at capturing.

I listed things to follow up in the first comment, will turn them into issues once this one is merged.

File: components/script/dom/pointerevent.rs (hunk 9 above)
Comment (webbeef) [reply components/script/dom/pointerevent.rs]: Ok TIL. I moved the `set_trusted()` to `new()` instead. Is that correct?

Comment (jdm) [reply components/script/dom/pointerevent.rs]: We set it automatically when calling event.fire, so we shouldn't actually need to set it anywhere in this code.

Comment (webbeef) [reply components/script/dom/pointerevent.rs]: updated in latest commit.

File: components/script/dom/document_event_handler.rs [hunk 11]
```diff
@@ -676,7 +696,24 @@ impl DocumentEventHandler {
...
+                    "pointermove"
+                };
+                let pointer_event = dom_event
+                    .downcast::<MouseEvent>()
+                    .unwrap()
+                    .to_pointer_event(event_type, can_gc);
+
+                pointer_event
+                    .upcast::<Event>()
+                    .dispatch(node.upcast(), false, can_gc);
```
Comment (jdm) [inline components/script/dom/document_event_handler.rs]: Oh, interesting. https://w3c.github.io/uievents/#maybe-send-pointerdown-event specifically links to dispatching, which doesn't set the trusted value, but the spec also relies on https://w3c.github.io/uievents/#create-pointerevent-from-mouseevent which invokes https://dom.spec.whatwg.org/#concept-event-create, which does set isTrusted. Meanwhile there's also https://w3c.github.io/pointerevents/#dfn-fire-a-pointer-event which uses the https://dom.spec.whatwg.org/#concept-event-fire concept which creates the event in the same manner.

For now, just use `.fire` instead, since all it does is set the trusted value and then call dispatch.

File: components/script/dom/document_event_handler.rs [hunk 12]
```diff
@@ -717,7 +754,26 @@ impl DocumentEventHandler {
...
```
Comment (jdm) [inline components/script/dom/document_event_handler.rs]: Same here for .fire.

File: components/script/dom/document_event_handler.rs (hunk 11 above)
Comment (jdm) [reply components/script/dom/document_event_handler.rs]: Alternatively, you could add the set_trusted to to_pointer_event.

**Comment by yezhizhen** [comment]
We should revert test file export.

**Comment by webbeef** [comment]
> We should revert test file export.

Why? That prevents updating the wpt metadata.

**Comment by yezhizhen** [comment]
why change this pointerevent_capture_mouse.html?
It is for debug only right?

**Comment by webbeef** [comment]
> why change this pointerevent_capture_mouse.html? It is for debug only right?

No, I explained it here: [#general > Conflicting metadata values when updating wpt expectations @ 💬](https://servo.zulipchat.com/#narrow/channel/263398-general/topic/Conflicting.20metadata.20values.20when.20updating.20wpt.20expectations/near/564104575)

File: tests/wpt/tests/pointerevents/pointerevent_capture_mouse.html (hunk 8 above)
Comment (arihant2math) [reply tests/wpt/tests/pointerevents/pointerevent_capture_mouse.html:142]: Still not reverted ...

Comment (Gae24) [reply tests/wpt/tests/pointerevents/pointerevent_capture_mouse.html:142]: [Here](https://github.com/servo/servo/pull/41290#issuecomment-3866259014) the reason why it was introduced.

**Comment by webbeef** [comment]
I'm running a new try build to check if the latest wpt update changes our results.

**Comment by webbeef** [comment]
> I'm running a new try build to check if the latest wpt update changes our results.

The last WPT update included https://github.com/web-platform-tests/wpt/commit/c556bde7f77ee15541f6e5a99a314a36c4d602da that caused our expectations to change.

File: components/webdriver_server/actions.rs
Comment (yezhizhen) [inline components/webdriver_server/actions.rs:1]: It seems we get a lot more failure with pen due to the change just added. Can you explain why do you change this file?
https://github.com/servo/servo/compare/3008e52abcb9eb2e5c77ced1ea97512615ca0ec1..4dc1b0f9df6ef7e46eae59b96a2cb8bf037667c4#diff-fdf5b879f93165227755e9bdbfa1af8f40d53ff2f6a87b88031842d0a57a618e

**Review by yezhizhen — DISMISSED** [review]
It seems we get a lot more failure with pen due to the change in WebDriver.

File: components/webdriver_server/actions.rs
Comment (webbeef) [reply components/webdriver_server/actions.rs:1]: In https://github.com/servo/servo/blob/7488c127db4609584f113dfdeb451a81b6d99f79/tests/wpt/tests/pointerevents/pointerevent_attributes.html#L80 the behavior of "pen" is expected to be similar to "mouse", not "touch". I don't think we get more real failures than before, since we had no support at all.

Comment (yezhizhen) [reply components/webdriver_server/actions.rs:1]: But we do get more failures.

Comment (yezhizhen) [reply components/webdriver_server/actions.rs:1]: https://github.com/servo/servo/compare/3008e52abcb9eb2e5c77ced1ea97512615ca0ec1..4dc1b0f9df6ef7e46eae59b96a2cb8bf037667c4#diff-ce64ae572739b98e3c8367a2eb69b5333b06c9d3d9572ee7c9feac138dc86cdf

https://github.com/servo/servo/compare/3008e52abcb9eb2e5c77ced1ea97512615ca0ec1..4dc1b0f9df6ef7e46eae59b96a2cb8bf037667c4#diff-5bbb020da09a0f7908da8fd59614a8c8b94e2ba757ec4302952a9b39ded19124

https://github.com/servo/servo/compare/3008e52abcb9eb2e5c77ced1ea97512615ca0ec1..4dc1b0f9df6ef7e46eae59b96a2cb8bf037667c4#diff-4b26e0a4fe7fad226db22b01fa42e87b0ea25b56c43adc38ebcdf3a643d3b09d

https://github.com/servo/servo/compare/3008e52abcb9eb2e5c77ced1ea97512615ca0ec1..4dc1b0f9df6ef7e46eae59b96a2cb8bf037667c4#diff-e1ef1931961f84eaa5ba55fd26c850764bf5ac98ce11cd4ae0a4c1600ba6f702

https://github.com/servo/servo/compare/3008e52abcb9eb2e5c77ced1ea97512615ca0ec1..4dc1b0f9df6ef7e46eae59b96a2cb8bf037667c4#diff-fdf5b879f93165227755e9bdbfa1af8f40d53ff2f6a87b88031842d0a57a618e


https://github.com/servo/servo/compare/3008e52abcb9eb2e5c77ced1ea97512615ca0ec1..4dc1b0f9df6ef7e46eae59b96a2cb8bf037667c4#diff-8af743a1ea91955a4e7cb8b4ae62ecb68ef47bdc2a4e3916fc3b2cac914354fa

and more.

Comment (webbeef) [reply components/webdriver_server/actions.rs:1]: Taking one example like tests/wpt/meta/pointerevents/pointerevent_attributes.optional.html.ini :

We have "new failures" because now we actually fire the events, but we don't implement `fromElement` and `toElement`. That's expected. Same with a lot of pointerCapture related failures, etc.

Comment (yezhizhen) [reply components/webdriver_server/actions.rs:1]: It didn't happen before your latest force-push tho. Also, webdriver [spec](https://w3c.github.io/webdriver/#dfn-deserialize-as-timeouts-configuration:~:text=In%20the%20case%20where%20the%20pointerType%20is%20%22pen%22%20or%20%22touch%22%2C%20and%20buttons%20is%20empty%2C%20this%20may%20be%20a%20no%2Dop) expects pen to be more like touch.

If you made the change of webdriver part after it was approved last time, at least mention it in the description, or separate it in another PR, as it drastically change the nature of this PR.

Comment (webbeef) [reply components/webdriver_server/actions.rs:1]: I explained in https://github.com/servo/servo/pull/41290#issuecomment-3869602126 that the last wpt sync changed some of these tests.

Maybe the webdriver spec is saying that pen is like touch, but clearly the tests expect something else and other browsers are passing them. I can split out the webdriver changes in their own PR if you prefer.

**Comment by webbeef** [comment]
I reverted the webdriver changes, try run here: https://github.com/webbeef/servo/actions/runs/21849393293/job/63056309331

I think we should take https://github.com/servo/servo/pull/42485 before.

**Comment by yezhizhen** [comment]
@webbeef It's ok. Let's do this incrementally and merge this first.

I have a touch related PR that also depends on this.
