### PR TITLE
htmlmediaelement: Make dirty element on any intrinsic size changes

### LINKED ISSUE #34434: Intermittent failure in /html/semantics/embedded-content/the-video-element/intrinsic_sizes.htm
```
▶ OK /html/semantics/embedded-content/the-video-element/intrinsic_sizes.htm
│ ▶ FAIL [expected PASS] default object size after src is removed
│ │ → assert_equals: expected "300px" but got "320px"
```

### PR DESCRIPTION
**Pull request by tharkum**
To properly compute (the video) element's content size for
layout requires to dirty the element on any intrinstic size changes.

Full list of the operations which cause layout invalidation:
- media metadata update (NEW)
- removing "src" attribute
- video frame update
- show poster image

Testing: html/semantics/embedded-content/the-video-element/intrinsic_sizes.htm
Fixes: https://github.com/servo/servo/issues/34434

### CODE REVIEW

**Comment by tharkum** [comment]
cc @xiaochengh

File: components/script/dom/htmlmediaelement.rs [hunk 1]
```diff
@@ -1770,6 +1770,7 @@ impl HTMLMediaElement {
 
                 // Step 5.
                 self.handle_resize(Some(metadata.width), Some(metadata.height));
+                self.upcast::<Node>().dirty(NodeDamage::OtherNodeDamage);
```
Comment (jdm) [inline components/script/dom/htmlmediaelement.rs:1773]: If we move this into handle_resize (which is what I assume we care about dirtying the node for) we can remove a bunch of other explicit dirty calls from this file.

**Comment by tharkum** [comment]
Linux WPT results (**PASSED**): https://github.com/tharkum/servo/actions/runs/15154968507

**Review by jdm — APPROVED** [review]
