### PR TITLE
script: Fix borrow hazard in script_modules

### LINKED ISSUE #43377: Borrow hazard in fetch_a_single_module_script
https://github.com/servo/servo/blob/e61298ef69cc0df08f5c1befd457e774b879b8b1/components/script/script_module.rs#L1422-L1425

We hold a mutable borrow on a hashtable while we allocate new JS promise objects, which will panic if the garbage collector runs during this time.

https://book.servo.org/design-documentation/borrow_hazard.html

### PR DESCRIPTION
**Pull request by Narfinger**
Fix the borrow hazard by simply taking the option and inserting it again.

Testing: This is a refactor and crown does not complain so it should be fine.
Fixes: https://github.com/servo/servo/issues/43377

### CODE REVIEW

**Comment by Narfinger** [comment]
I am not quite sure why this doesn't have to be rooted. So somebody should look at this carefully.

File: components/script/script_module.rs [hunk 1]
```diff
@@ -1524,10 +1524,12 @@ pub(crate) fn fetch_a_single_module_script(
     let comp = InRealm::Entered(&realm);
     run_a_callback::<DomTypeHolder, _>(&global, || {
         let has_pending_fetch = pending.borrow().is_some();
-        pending
-            .borrow_mut()
-            .get_or_insert_with(|| Promise::new_in_current_realm(comp, CanGc::note()))
-            .append_native_handler(&handler, comp, CanGc::note());
+        // be careful of Borrow Hazard here
```
Comment (mrobinson) [inline components/script/script_module.rs]: Why is "borrow hazard" capitalized here? I think it also makes sense to explain what the borrow hazard actually is. I'm not familiar with this code and it isn't immediately obvious to me.

Comment (Narfinger) [reply components/script/script_module.rs]: added short explanation.

**Comment by jdm** [comment]
> I am not quite sure why this doesn't have to be rooted. So somebody should look at this carefully.

`Rc<Promise>` does not require any special rooting considerations.

File: components/script/script_module.rs [hunk 2]
```diff
@@ -1524,10 +1524,12 @@ pub(crate) fn fetch_a_single_module_script(
...
     run_a_callback::<DomTypeHolder, _>(&global, || {
         let has_pending_fetch = pending.borrow().is_some();
-        pending
-            .borrow_mut()
-            .get_or_insert_with(|| Promise::new_in_current_realm(comp, CanGc::note()))
-            .append_native_handler(&handler, comp, CanGc::note());
+        // be careful of a borrow hazard here (do not hold a RefCell over a possible GC pause)
+        let pending_option = pending.borrow_mut().take();
+        let new_pending =
+            pending_option.unwrap_or(Promise::new_in_current_realm(comp, CanGc::note()));
```
Comment (jdm) [inline components/script/script_module.rs]:
```suggestion
            pending_option.unwrap_or_else(|| Promise::new_in_current_realm(comp, CanGc::note()));
```

**Review by jdm — APPROVED** [review]
