### PR TITLE
Console message packets should have a '_type' attribute

### LINKED ISSUE #13137: Console message packets should have a '_type' attribute
**STR:**
1. Start Servo with the `--devtools` option - starts the devtools protocol server
2. Connect to Servo from Firefox WebIDE
3. After connecting, open Devtools for the listed tab
4. Open the Console tab

**Expected result:**
The console actor sends two testing messages in response to `getCachedMessages` packet. They should be both displayed in the console.

**Actual result:**
The messages are not displayed, because the packets don't have the `_type` property and are ignored ([source](http://searchfox.org/mozilla-central/source/devtools/client/webconsole/webconsole.js#1242)). The property is incorrectly named `type`.

### PR DESCRIPTION
**Pull request by jsnajdr**
Renamed the `type_` attribute of `PageError` and `ConsoleAPI` structs to make them correct Firefox RDP packets.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #13137 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because devtools component doesn't have any

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13138)

### CODE REVIEW

File: components/devtools_traits/lib.rs [hunk 1]
```diff
@@ -252,8 +252,7 @@ bitflags! {
 
 #[derive(Deserialize, Serialize)]
 pub struct PageError {
-    #[serde(rename = "type")]
-    pub type_: String,
+    pub _type: String,
```
Comment (nox) [inline components/devtools_traits/lib.rs]: Do `#[serde(rename = "type_")]`, undescore as a prefix has special meaning in Rust (silences dead_code warnings).

**Comment by nox** [comment]
@bors-servo r+

Thanks!
