### PR TITLE
Use same-origin as default credential mode for RequestInit fix

### LINKED ISSUE #29633: Use `same-origin` as default credential mode for RequestInit
In https://github.com/whatwg/fetch/pull/1153, the default credential mode is changed from `omit` to `same-origin` so we need to fix the default value at

https://github.com/servo/servo/blob/4251159513dc2c7d25f2926baf500f76beec8947/components/net_traits/request.rs#L272

also, with fixing the default value, we can remove the `fallback_credentials` logic in the constructor at

https://github.com/servo/servo/blob/4251159513dc2c7d25f2926baf500f76beec8947/components/script/dom/request.rs#L82-L85

### PR DESCRIPTION
**Pull request by AnthonyJ3**
- Updated the default credential mode from omit to same-origin as per: https://github.com/whatwg/fetch/pull/1153
- Deleted instances of fallback credentials
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #29633  (GitHub issue number if applicable)
- [X] There are tests for these changes

### CODE REVIEW

**Comment by CYBAI** [comment]
Thanks for the PR! Currently, the CI failed with format issues. You can fix it with `./mach fmt`

```
Diff in /home/runner/work/servo/servo/components/script/dom/request.rs at line 232:
         }
 
         // Step 19
-        let credentials = init
-            .credentials
-            .as_ref()
-            .map(|m| m.clone().into());
+        let credentials = init.credentials.as_ref().map(|m| m.clone().into());
 
         if let Some(c) = credentials {
             request.credentials_mode = c;
Ubuntu clang-format version 11.0.0-2~ubuntu20.04.1
clang-format: wrong version (v15 required). Skipping CPP formatting.
Run `./mach fmt` to fix the formatting
```

File: components/script/dom/request.rs [hunk 1]
```diff
@@ -239,11 +232,7 @@ impl Request {
         }
 
         // Step 19
-        let credentials = init
-            .credentials
-            .as_ref()
-            .map(|m| m.clone().into())
-            .or(fallback_credentials);
+        let credentials = init.credentials.as_ref().map(|m| m.clone().into());
```
Comment (mukilan) [inline components/script/dom/request.rs:235]: Suggestion: this can be combined with the subsequent if statement i.e
```
if let Some(init_credentials) = init.credentials.as_ref() {
    let credentials = init_credentials.clone().into();
    request.credentials_mode = credentials;
}
```

It is verbose, but seems to be consistent with the style of the surrounding code for other RequestInit options.

**Comment by mrobinson** [comment]
@bors-servo try

Should these changes result in expectations changes?

File: components/script/dom/request.rs (hunk 1 above)
Comment (AnthonyJ3) [reply components/script/dom/request.rs]: Thanks for pointing this out. It looks alot more natural. Just added in fix-up commit

**Comment by CYBAI** [comment]
> Stable unexpected results (6)
> * OK /fetch/api/request/request-init-003.sub.html* FAIL [expected PASS] subtest: Check request values when initialized from url string
> * OK /fetch/api/request/request-structure.any.html* FAIL [expected PASS] subtest: Check credentials attribute
> * OK /fetch/api/request/request-structure.any.worker.html* FAIL [expected PASS] subtest: Check credentials attribute
> * OK /html/anonymous-iframe/cookie-store.tentative.https.window.html* FAIL [expected PASS] subtest: Get Cookie via subresource requests* FAIL [expected PASS] subtest: Set Cookie via subresource requests
> * OK /html/anonymous-iframe/worker-cookies.tentative.https.window.html?worker=dedicated_worker* FAIL [expected PASS] subtest: Worker spawned from normal iframe can access global cookies* PASS [expected FAIL] subtest: Worker spawned from credentialless iframe can't access global cookies
> * OK /xhr/access-control-preflight-request-must-not-contain-cookie.htm* FAIL [expected PASS] subtest: Preflight request must not contain any cookie header

I didn't expect this patch would break tests. I wonder there are some places we don't match the spec to set credentials mode yet. 👀 I will also help to figure out what's missing in Servo.

**Comment by CYBAI** [comment]
@AnthonyJ3 oops, sorry, I just realized I forgot to mention this field in the `new` method should be updated as well. Please also update this line to `same-origin` 🙏 

https://github.com/servo/servo/blob/7114b31cf75504fd7b52c40f3a46daff101fc1cf/components/net_traits/request.rs#L512

**Review by mukilan — APPROVED** [review]
