### PR TITLE
layout: Paint flex and grid items like inline blocks

### LINKED ISSUE #38573: Wrong painting order with flex layout
```html
<!DOCTYPE html>
<style>
.container { display: flex; width: 100px; height: 100px; border: 50px solid; }
</style>
<div class="container">
  <div class="item" style="height: 250px; flex: 1; background: cyan"></div>
</div>
<div class="container" style="border-color: orange"></div>
```

| Servo | Blink, WebKit, Gecko |
| - | - |
|  |  |

### PR DESCRIPTION
**Pull request by Loirooriol**
As specified in https://drafts.csswg.org/css-flexbox-1/#painting and https://drafts.csswg.org/css-grid/#z-order

Testing: Makes some WPT pass.
Fixes: #38573

### CODE REVIEW

File: components/layout/display_list/stacking_context.rs [hunk 1]
```diff
@@ -943,7 +944,7 @@ impl BoxFragment {
             return Some(StackingContextType::FloatStackingContainer);
         }
 
-        if self.is_atomic_inline_level() {
+        if self.is_atomic_inline_level() || flags.contains(FragmentFlags::IS_FLEX_OR_GRID_ITEM) {
```
Comment (mrobinson) [inline components/layout/display_list/stacking_context.rs:950]: Maybe put a link here to where this is described in the specification before landing?

**Review by mrobinson — APPROVED** [review]
