### PR TITLE
 Always pass InRealm to GlobalScope::from_context to avoid getting a null global

### LINKED ISSUE #25348: GlobalScope::from_context does not handle a null global object
https://github.com/servo/servo/blob/bac9903fbeed0a394a86c0091e727aada665433d/components/script/dom/globalscope.rs#L1297-L1302

It calls CurrentGlobalOrNull, but the return type is a `DomRoot<GlobalScope>`. In the short term adding an assert that the result is not null would be more safe than a segfault.

### PR DESCRIPTION
**Pull request by CYBAI**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #25348
- [x] These changes do not require tests because ___

### CODE REVIEW

**Comment by CYBAI** [comment]
@jdm I tried to make it return an option though, does this make sense to you? Or, we shouldn't get a null global in that case so should just use assert instead 👀?

**Comment by CYBAI** [comment]
@bors-servo try=wpt

- Should not break anything 👀

File: components/script/dom/globalscope.rs [hunk 1]
```diff
@@ -1296,9 +1296,13 @@ impl GlobalScope {
 
     /// Returns the global scope for the given JSContext
     #[allow(unsafe_code)]
-    pub unsafe fn from_context(cx: *mut JSContext) -> DomRoot<Self> {
+    pub unsafe fn from_context(cx: *mut JSContext) -> Option<DomRoot<Self>> {
```
Comment (jdm) [inline components/script/dom/globalscope.rs]: Thinking about this further, I think we can do something more useful. `CurrentGlobalOrNull` uses the global from the current realm. This means that if we add an `InCompartment` argument to this method, we can force callers to provide proof that they have already entered a realm. Then we can remove the Option from the return value and assert that `global` is never null.

**Review by jdm — CHANGES_REQUESTED** [review]
Thanks for making this pull request! It helped me to see all of the callers of this code and clarify how it could be improved.

File: components/script/dom/globalscope.rs (hunk 1 above)
Comment (CYBAI) [reply components/script/dom/globalscope.rs]: Thanks! Good point and understood! Will update!

File: components/script/dom/windowproxy.rs [hunk 2]
```diff
@@ -386,7 +386,14 @@ impl WindowProxy {
                     opener_id,
                 ) {
                     Some(opener_top_id) => {
-                        let global_to_clone_from = unsafe { GlobalScope::from_context(cx) };
+                        let global_to_clone_from = unsafe {
+                            let in_compartment_proof =
+                                AlreadyInCompartment::assert_for_cx(SafeJSContext::from_ptr(cx));
```
Comment (jdm) [inline components/script/dom/windowproxy.rs]: Instead, let's add an `InCompartment` argument to `opener`, and since it's only called by Window::Opener we can modify https://github.com/servo/servo/blob/12693b51f510761d5dd58a9103596a192edb803c/components/script/dom/bindings/codegen/Bindings.conf#L60 to include that method.

File: components/script/dom/windowproxy.rs [hunk 3]
```diff
@@ -983,8 +990,10 @@ pub fn new_window_proxy_handler() -> WindowProxyHandler {
 #[allow(unsafe_code)]
 unsafe fn throw_security_error(cx: *mut JSContext) -> bool {
     if !JS_IsExceptionPending(cx) {
-        let global = GlobalScope::from_context(cx);
-        throw_dom_exception(SafeJSContext::from_ptr(cx), &*global, Error::Security);
+        let safe_context = SafeJSContext::from_ptr(cx);
+        let in_compartment_proof = AlreadyInCompartment::assert_for_cx(safe_context);
```
Comment (jdm) [inline components/script/dom/windowproxy.rs]: Instead, let's add an `InCompartment` argument to `throw_security_error` and make the callers prove that they're in a realm.

File: components/script/dom/bindings/error.rs [hunk 4]
```diff
@@ -285,7 +286,9 @@ pub unsafe fn report_pending_exception(cx: *mut JSContext, dispatch_event: bool)
     }
 
     if dispatch_event {
-        GlobalScope::from_context(cx).report_an_error(error_info, value.handle());
+        let in_compartment_proof = AlreadyInCompartment::assert_for_cx(SafeJSContext::from_ptr(cx));
```
Comment (jdm) [inline components/script/dom/bindings/error.rs]: Let's add an `InCompartment` argument to `report_pending_exception` instead.

**Review by jdm — CHANGES_REQUESTED** [review]

**Comment by CYBAI** [comment]
@bors-servo try=wpt

- Should not break anything 👀

**Review by jdm — APPROVED** [review]
This looks great! Please rebase and we'll merge :)

**Comment by jdm** [comment]
```
error: unused import: `JSAutoRealm`
  --> components/script/dom/globalscope.rs:67:17
   |
67 | use js::jsapi::{JSAutoRealm, JSContext};
   |                 ^^^^^^^^^^^
   |
   = note: `-D unused-imports` implied by `-D warnings`
error: aborting due to previous error
error: could not compile `script`.
```

**Comment by jdm** [comment]
@nors-servo r+

**Comment by jdm** [comment]
@bors-servo retry
* network

**Comment by jdm** [comment]
@bors-servo retry
* #24726
