### PR TITLE
Fix linear gradient's specified form #13892

### LINKED ISSUE #13892: Fix linear gradient's specified form
Currently linear gradient is not preserving the current corner directions if just one corner is specified. We should fix thix. The specified form of the linear gradient should preserve the corners and it should convert to angle in ToComputedValue implementation.

To give a  more details, you need to convert [this](https://github.com/servo/servo/blob/dee1a65a6983188a125f820b8bc9505f4909e171/components/style/values/specified/image.rs#L231) enum's `HorizontalDirection` and `VerticalDirection` to `Option<HorizontalDirection>` and `Option<HorizontalDirection>` and set it [here](https://github.com/servo/servo/blob/dee1a65a6983188a125f820b8bc9505f4909e171/components/style/values/specified/image.rs#L262-L279) directly without converting to Angle. 

This corner to angle conversion should be moved to ToComputedValue implementation, to do this you should remove [this](https://github.com/servo/servo/blob/dee1a65a6983188a125f820b8bc9505f4909e171/components/style/values/specified/image.rs#L289) line and write the implementation in `components/style/values/computed/image.rs` [GradientKind implemetation](https://github.com/servo/servo/blob/5f2e7af864e3d190957f58b317bf56cce8a84795/components/style/values/computed/image.rs#L181-L208) should give a hint to how to do it.

Also you can see [this part](https://github.com/servo/servo/wiki/Property-hacking-guide#tocomputedvalue-conversions) of the Property hacking guide to see how to implement a ToComputedValue conversion.

It may require some additional changes but compile errors will give you hint about that. And of course you can ask here if you have any questions.

### PR DESCRIPTION
**Pull request by DominoTree**
WIP for #13892 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #13892  (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14598)

### CODE REVIEW

File: components/style/values/computed/image.rs [hunk 1]
```diff
@@ -454,3 +455,73 @@ impl ToComputedValue for specified::LengthOrPercentageOrKeyword {
         }
     }
 }
+
+#[derive(Clone, Debug, PartialEq)]
+#[cfg_attr(feature = "servo", derive(HeapSizeOf))]
+pub enum AngleOrCorner {
```
Comment (Wafflespeanut) [inline components/style/values/computed/image.rs]: This type (and its `impl`) should be moved to `components/style/values/computed/mod.rs`

File: components/style/values/computed/image.rs [hunk 2]
```diff
@@ -454,3 +455,73 @@ impl ToComputedValue for specified::LengthOrPercentageOrKeyword {
         }
     }
 }
+
+#[derive(Clone, Debug, PartialEq)]
```
Comment (Wafflespeanut) [inline components/style/values/computed/image.rs]: This should be a `Copy` type. Once that's done, you won't have to reference it.

File: components/style/values/computed/image.rs (hunk 1 above)
Comment (Wafflespeanut) [inline components/style/values/computed/image.rs]: This type (and its `impl`) should be moved to `components/style/values/computed/mod.rs`

File: components/style/values/specified/image.rs [hunk 3]
```diff
@@ -230,18 +229,33 @@ fn parse_position(context: &ParserContext, input: &mut Parser) -> Result<Positio
...
+    Corner(Option<HorizontalDirection>, Option<VerticalDirection>),
 }
 
 impl ToCss for AngleOrCorner {
     fn to_css<W>(&self, dest: &mut W) -> fmt::Result where W: fmt::Write {
         match *self {
             AngleOrCorner::Angle(angle) => angle.to_css(dest),
             AngleOrCorner::Corner(horizontal, vertical) => {
+
+                //TODO: Not sure if breaking all of these out was necessary
```
Comment (Wafflespeanut) [inline components/style/values/specified/image.rs]: It's fine. This can be removed :)

File: components/style/values/computed/image.rs (hunk 1 above)
Comment (canaltinova) [inline components/style/values/computed/image.rs]: Well, specified `AngleOrCorner` is inside of image.rs and it looks like it's related to image. Shouldn't it be here? We can reimport it in mod.rs to use like `computed::AngleOrCorner` I think.

File: components/style/values/computed/mod.rs [hunk 4]
```diff
@@ -169,3 +170,73 @@ impl ToCss for BorderRadiusSize {
...
+                        AngleOrCorner::Angle(Angle(0.0)),
+                    (Some(HorizontalDirection::Right), Some(VerticalDirection::Top)) =>
+                        AngleOrCorner::Angle(Angle(PI * 0.25)),
+                    (Some(HorizontalDirection::Right), None) =>
+                        AngleOrCorner::Angle(Angle(PI * 0.5)),
+                    (Some(HorizontalDirection::Right), Some(VerticalDirection::Bottom)) =>
+                        AngleOrCorner::Angle(Angle(PI * 0.75)),
+                    (None, Some(VerticalDirection::Bottom)) =>
+                        AngleOrCorner::Angle(Angle(PI)),
+                    (Some(HorizontalDirection::Left), Some(VerticalDirection::Bottom)) =>
```
Comment (canaltinova) [inline components/style/values/computed/mod.rs]: If both vertical and horizontal position is specified, we need to store them as keywords instead of converting them to angle(like deleted specified parsing part)

**Review by canova — COMMENTED** [review]
Hm, it looks it doesn't work as we intended I think.
The tests should preserve keywords instead of changing them to angle. I need to take a deeper look.

File: components/style/values/computed/mod.rs (hunk 4 above)
Comment (DominoTree) [inline components/style/values/computed/mod.rs]: Is it okay that `from_computed_value` will return an `Angle` when `to_computed_value` was provided a `Corner` with only one direction?

Comment (DominoTree) [inline components/style/values/computed/mod.rs]: In other words, I'm wondering if we should preserve the `Option`s instead, and account for the None values in places like `components/layout/display_list_builder.rs`

Comment (canaltinova) [inline components/style/values/computed/mod.rs]: `ToComputedValue` impl functions are not reversible. Specified forms should preserve the user input but computed forms are a bit more abstract from the user and well, it should compute when going to that form 😄 . It's okay to lose some information about user input when converting to computed form as long as result are the exactly same.

Comment (DominoTree) [inline components/style/values/computed/mod.rs]: Fine by me, I'll go ahead and split this back up :)

Comment (DominoTree) [inline components/style/values/computed/mod.rs]: That's what I meant, I didn't say it very well - I think we're on the same page :)

Comment (canaltinova) [inline components/style/values/computed/mod.rs]: Oh, ok then :)
I'll review this deeply soon :)

Comment (DominoTree) [inline components/style/values/computed/mod.rs]: Thanks for helping me work through this stuff.  I went ahead and updated the Match block.

Looks like the test is still unhappy here.  From what I can tell, I think that `specified::AngleOrCorner.to_computed_value()` isn't being called. I'm not really sure where to look to debug that further.

```
---- parsing::image::test_linear_gradient stdout ----
        thread 'parsing::image::test_linear_gradient' panicked at 'assertion failed: `(left == right)` (left: `"linear-gradient(to left, red, green)"`, right: `"linear-gradient(4.712389rad, red, green)"`)', /Users/nprice/Projects/servo/tests/unit/style/parsing/image.rs:15
```

File: tests/unit/style/parsing/image.rs [hunk 5]
```diff
@@ -20,18 +20,19 @@ fn test_linear_gradient() {
...
 
     // Parsing with <angle>
     assert_roundtrip_with_context!(Image::parse, "linear-gradient(45deg, red, green)",
                                                  "linear-gradient(0.7853982rad, red, green)");
 
-   // Parsing with more than two entries in <color-stop-list>
-   assert_roundtrip_with_context!(Image::parse, "linear-gradient(red, yellow, green)",
+    // Parsing with more than two entries in <color-stop-list>
+    assert_roundtrip_with_context!(Image::parse, "linear-gradient(red, yellow, green)",
                                                 "linear-gradient(3.1415927rad, red, yellow, green)");
```
Comment (canaltinova) [inline tests/unit/style/parsing/image.rs]: nit: align these double quotes with upper ones please

File: components/style/values/specified/image.rs [hunk 6]
```diff
@@ -239,9 +238,20 @@ impl ToCss for AngleOrCorner {
...
+                        try!(vertical.to_css(dest));
+                    }
+                    (Some(horizontal), None) => {
+                        try!(horizontal.to_css(dest));
+                    }
+                    (None, Some(vertical)) => {
+                        try!(vertical.to_css(dest));
+                    }
+                    (None, None) => unreachable!()
+                }
```
Comment (canaltinova) [inline components/style/values/specified/image.rs]: You can restructure this with match something like this:
```rust
let mut horizontal_present = false;
if let Some(horizontal) = horizontal {
    try!(horizontal.to_css(dest));
    horizontal_present = true;
}
if let Some(vertical) = vertical {
    if horizontal_present {
        try!(dest.write_str(" "));
    }
    try!(vertical.to_css(dest));
}
```
This looks a bit clearer.

**Review by canova — COMMENTED** [review]
```
---- parsing::image::test_linear_gradient stdout ----
        thread 'parsing::image::test_linear_gradient' panicked at 'assertion failed: `(left == right)` (left: `"linear-gradient(to left, red, green)"`, right: `"linear-gradient(4.712389rad, red, green)"`)', /Users/nprice/Projects/servo/tests/unit/style/parsing/image.rs:15
```
You're getting this because your code works! 🎉 
You need to update these tests, because these were wrong. Now we can display `to left` directly instead of converting it to `4.712389rad`. You can simply remove third parameter from `assert_roundtrip_with_context!` macro.

**Comment by canaltinova** [comment]
I'm thinking that we might want to add None variant to `specified::AngleOrCorner` enum. Currently we are converting `linear-gradient(red, yellow, green)` to `linear-gradient(3.1415927rad, red, yellow, green)`. Pi shouldn't be displayed here. We can convert `AngleOrCorner::None` to `AngleOrCorner::Angle(Angle(PI))` in ToComputedValue part. But we can split this to another issue if you want. No problem.

**Comment by DominoTree** [comment]
Looks like I misunderstood how these tests worked - that was an easy fix :D

I think these last commits should sort everything out.  If the tests run and everything looks good to you, I think we'll be ready to squash them.

One last thing - should we leave `AngleOrCorner` in `mod.rs` or should we move it to `computed/image.rs` (or should we move `AngleOrCorner` on the other side to `specified/mod.rs`?)

File: components/style/values/computed/image.rs (hunk 1 above)
Comment (Wafflespeanut) [inline components/style/values/computed/image.rs]: No, it was imported as `computed::AngleOrCorner` and so I suggested moving it to `computed/mod.rs` to fix the build failure. We have plenty of other options - I'm cool with anything :)

**Comment by Wafflespeanut** [comment]
It could be moved to `computed/image.rs` but, if you really want it to be imported as `computed::AngleOrCorner`, it could also be re-exported as `pub use image::AngleOrCorner` in `computed/mod.rs`

Yes, and please squash the commits :)

File: components/style/values/specified/image.rs [hunk 7]
```diff
@@ -81,7 +85,11 @@ impl ToCss for Gradient {
             },
         }
         for stop in &self.stops {
-            try!(dest.write_str(", "));
+            if skipcomma == false {
```
Comment (KiChjang) [inline components/style/values/specified/image.rs]: `if !skipcomma`

File: components/style/values/specified/image.rs [hunk 8]
```diff
@@ -188,15 +194,15 @@ impl GradientKind {
             if input.try(|input| input.expect_ident_matching("ellipse")).is_ok() {
                 // Handle <ellipse> <LengthOrPercentageOrKeyword>? <position>?
                 let length = input.try(|i| LengthOrPercentageOrKeyword::parse(context, i))
-                                  .unwrap_or(LengthOrPercentageOrKeyword::Keyword(SizeKeyword::FarthestCorner));
+                    .unwrap_or(LengthOrPercentageOrKeyword::Keyword(SizeKeyword::FarthestCorner));
```
Comment (canaltinova) [inline components/style/values/specified/image.rs]: nit: these indentations were fine btw (so is this)

**Review by canova — APPROVED** [review]
Changes looks good to me! Thanks for your contributions! Could you squash your commits?

**Comment by DominoTree** [comment]
Assuming this passes checks, think that should do it!
