### PR TITLE
htmlvideoelement: Fix poster frame processing algorithm

### LINKED ISSUE #37165: Video elements in tests drop initial frames when showing the poster
> I'm surprised that there was no change in result for the tests with cross-origin redirects. I'll try to step through one of those tomorrow to figure out what's going wrong.

Actually change for cross-origin redirects is working, but test results are blocked by media rendering issue.
Some initial frames from media pipeline decoder come to us before we are ready to accept them (discards all of them) because `show_poster` flag is enabled.

https://github.com/servo/servo/blob/2d3a7c87c2887d851eddc36ce760771ae3e861df/components/script/dom/htmlmediaelement.rs#L204

After we will be ready to accept new media frames, media decoder doesn't send to us anything (media renderer current frame is empty), so on createPattern() we have `InvalidStateError` exception
and haven't possibility to test canvas against origin clean state.

If you comment this check the cross-origin redirects tests will be passed.

_Originally posted by @tharkum in https://github.com/servo/servo/issues/37135#issuecomment-2914982367_

### PR DESCRIPTION
**Pull request by tharkum**
According to HTML specification the poster attribute determines the element's poster frame
(regardless of the value of the element's show poster flag).
https://html.spec.whatwg.org/multipage/#poster-frame

So the poster frame and the show poster flag is orthogonal to each other, the latest one only controls
when browser should display the poster frame and should do not block accepting video frames
from media pipeline (e.g. on new_preroll callback from video sink).

During layout the video element should select the current frame which will be presented
based on first matching condition from the list:
https://html.spec.whatwg.org/multipage/#the-video-element:the-video-element-7

Testing: Improvements in the following WPT tests
- html/canvas/element/manual/imagebitmap/createImageBitmap*
- html/semantics/embedded-content/the-canvas-element/*

Fixes: #37165

### CODE REVIEW

**Review by jdm — APPROVED** [review]
Excellent!

**Comment by tharkum** [comment]
- Fixed lint errors

File: components/script/dom/htmlmediaelement.rs [hunk 1]
```diff
@@ -170,7 +170,8 @@ pub(crate) struct MediaFrameRenderer {
     old_frame: Option<ImageKey>,
     very_old_frame: Option<ImageKey>,
     current_frame_holder: Option<FrameHolder>,
-    show_poster: bool,
+    // <https://html.spec.whatwg.org/multipage/#poster-frame>
```
Comment (mrobinson) [inline components/script/dom/htmlmediaelement.rs]: Nit: This should likely be rustdoc so that it shows up on hover when using the IDE.

```suggestion
    /// <https://html.spec.whatwg.org/multipage/#poster-frame>
```

File: components/script/dom/htmlmediaelement.rs [hunk 2]
```diff
@@ -2097,6 +2087,7 @@ impl HTMLMediaElement {
         }
     }
 
+    // Gets the video frame at the current playback position.
```
Comment (mrobinson) [inline components/script/dom/htmlmediaelement.rs]:
```suggestion
    /// Gets the video frame at the current playback position.
```

**Review by mrobinson — APPROVED** [review]
Nice! Just a couple nits:
