### PR TITLE
Fix shadow root binding children to the tree

### LINKED ISSUE #34882: Shadow roots don't properly bind their children to the tree
The implementation of `ShadowRoot::bind_to_tree` contains the following:
https://github.com/servo/servo/blob/cd39b1de643f50354b0620e6063d5443721ea39b/components/script/dom/shadowroot.rs#L324-L327

I believe there are two issues with this code:
* Only direct children are traversed ("bound to tree"), instead of all descendants of the shadow root
* `node.bind_to_tree(context);` should be `vtable_for(&node).bind_to_tree(context`, otherwise we don't execute potential binding steps of elements. 

For reference, refer to `Node::add_child`, which does something similar:
https://github.com/servo/servo/blob/cd39b1de643f50354b0620e6063d5443721ea39b/components/script/dom/node.rs#L297-L318
(updating `IS_IN_DOCUMENT_TREE` and `IS_IN_SHADOW_TREE` do not need to be updated here, as they can't change while the descendants are inside the shadow root)

### PR DESCRIPTION
**Pull request by Taym95**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #34882

- [x] There are tests for these changes

### CODE REVIEW

File: components/script/dom/shadowroot.rs [hunk 1]
```diff
@@ -326,9 +326,24 @@ impl VirtualMethods for ShadowRoot {
         let shadow_root = self.upcast::<Node>();
 
         shadow_root.set_flag(NodeFlags::IS_CONNECTED, context.tree_connected);
-        for node in shadow_root.children() {
+
+        for node in shadow_root.traverse_preorder(ShadowIncluding::No) {
```
Comment (simonwuelker) [inline components/script/dom/shadowroot.rs:330]: This should be `ShadowIncluding::Yes`, otherwise children inside two nested shadow roots won't be bound to the tree

File: components/script/dom/shadowroot.rs [hunk 2]
```diff
@@ -326,9 +326,24 @@ impl VirtualMethods for ShadowRoot {
...
             node.set_flag(NodeFlags::IS_CONNECTED, context.tree_connected);
-            node.bind_to_tree(context);
+
+            if context.tree_is_in_a_shadow_tree {
+                if let Some(shadow_root) = node.containing_shadow_root() {
+                    node.set_containing_shadow_root(Some(&*shadow_root));
+                }
+                debug_assert!(node.containing_shadow_root().is_some());
+            }
```
Comment (simonwuelker) [inline components/script/dom/shadowroot.rs:338]: I think this block does nothing?

Either way, all the shadowroots children should already be bound to the root, so I think you can remove this.

File: components/script/dom/shadowroot.rs [hunk 3]
```diff
@@ -326,9 +326,24 @@ impl VirtualMethods for ShadowRoot {
...
+
+            // Out-of-document elements never have the descendants flag set
+            debug_assert!(!node.get_flag(NodeFlags::HAS_DIRTY_DESCENDANTS));
+            vtable_for(&node).bind_to_tree(&BindContext {
+                tree_connected: context.tree_connected,
+                tree_is_in_a_document_tree: context.tree_is_in_a_document_tree,
+                tree_is_in_a_shadow_tree: context.tree_is_in_a_shadow_tree,
```
Comment (simonwuelker) [inline components/script/dom/shadowroot.rs:345]: Since children of a shadow root are always in a shadow tree and never in a document tree, you can change this to
```diff
                tree_is_in_a_document_tree: false,
                tree_is_in_a_shadow_tree: true,
```
The only flag that we care about here is whether the tree is connected (meaning it's shadow inclusive ancestor is a document)

**Review by simonwuelker — CHANGES_REQUESTED** [review]

File: components/script/dom/shadowroot.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (simonwuelker) [reply components/script/dom/shadowroot.rs:330]: Good catch. I suppose `.traverse_preorder(ShadowIncluding::Yes).into_iter().skip(1)` would fix that

**Review by simonwuelker — APPROVED** [review]
