### PR TITLE
script: add force option for assign-slottables for a tree

### LINKED ISSUE #35188: Fast path in `Node::assign_slottables_for_a_tree` is wrong
code:
https://github.com/servo/servo/blob/3bcab362485bb48b1eabd83b7a2a03b1aaf178f8/components/script/dom/node.rs#L1321-L1328

This assumption is wrong. If the root is not a shadow tree then we will never assign *new* slottables to it, but existing assigned slottables may be removed.

This snippet demonstrates the issue:
```html
<body>
<div id="host">
Before
<div id="content" slot="foo">This is some Text</div>
</div>

<script defer>
let host = document.getElementById("host");
let root = host.attachShadow({mode: "closed"});
let slot = document.createElement("slot");
slot.style = "color: green;"
slot.name = "foo";
root.appendChild(slot);
slot.remove();

// Should be empty, the slot is not in the DOM tree anymore
console.log(slot.assignedNodes());
</script>
```

Without the fast path many tests start to fail in CI because they take too long, so we will have to come up with a new optimization instead. (At least this was the case in the past)

Also, the same optimization is present in ladybird (I originally copied it from them), so they're likely wrong too. 

https://github.com/LadybirdBrowser/ladybird/blob/d4649db55e261e7fb747825f80cc6858ffe93fae/Libraries/LibWeb/DOM/Slottable.cpp#L178-L185

Part of #34318

### PR DESCRIPTION
**Pull request by rayguo17**
In the case of node removal, if the subtree of the removed node contains `<slot>` element, force traverse down to each `<slot>` element is needed to reset the assignment of the slottables that currently being assigned to the `<slot>` element. This changes add this force option to `assign_slottables_for_a_tree`, and only set true to node removal.

Testing: Should be covered by current WPT test, [try run](https://github.com/rayguo17/servo/actions/runs/21504337658)
Fixes https://github.com/servo/servo/issues/35188 
Fixes https://github.com/servo/servo/issues/42182

cc @TimvdLippe @simonwuelker @xiaochengh

### CODE REVIEW

File: components/script/dom/node.rs [hunk 1]
```diff
@@ -1552,14 +1552,17 @@ impl Node {
     }
 
     /// <https://dom.spec.whatwg.org/#assign-slotables-for-a-tree>
-    pub(crate) fn assign_slottables_for_a_tree(&self) {
+    pub(crate) fn assign_slottables_for_a_tree(&self, force: bool) {
```
Comment (TimvdLippe) [inline components/script/dom/node.rs]: Nit: use enum with two booleans to be more descriptive. Suggestion:

```rust
enum ForceSlottableNodeRecalcilation {
  Force,
  Skip,
}
```

**Review by TimvdLippe — CHANGES_REQUESTED** [review]
Since WPT doesn't have any tests for this apparently, please add a WPT test with https://github.com/servo/servo/issues/35188#issuecomment-3452964221

**Review by TimvdLippe — APPROVED** [review]

**Comment by rayguo17** [comment]
This PR should be ready to merge.

**Review by TimvdLippe — APPROVED** [review]
Nice!
