### PR TITLE
script: Properly fire `input` events for clipboard use in input elements

### LINKED ISSUE #37074: `ClipboardEvent` to input Element doesn't trigger repaint
**Describe the bug:**
As titled. In the video, I pressed `ctrl + x`. However, repaint only triggered after press some other key or click the input box again. 

https://github.com/user-attachments/assets/b3ea8c0b-910b-4135-9181-c28cb78706a5

Also, it does not trigger input event despite unempty selection.

**To Reproduce:**
```html
<html>
  <body>
    <input id="i">
    <div id="o"></div>
    <script>
      document.getElementById("i").addEventListener("input", e =>
        document.getElementById("o").textContent = e.target.value
      );
    </script>
  </body>
</html>
```

**Platform:**
All.

### PR DESCRIPTION
**Pull request by mrobinson**
When using the clipboard to paste or modify the contents of an input
element the specification says says[^1] to

> Queue tasks to fire any events that should fire due to the
> modification, see § 5.3 Integration with other scripts and events for
> details.

This change does that, by turning `handle_text_clipboard_action` into
`TextInput::handle_clipboard_event` and having the caller responsible
for executing events. In addition, when content is changed, the node is
dirtied, forcing a relayout.

[^1]: https://www.w3.org/TR/clipboard-apis/#paste-action

Testing: This is difficult to test because we do not have test harness support for input events currently. There is a manual test for this in the linked bug which is now passing.
Fixes: #37074.

### CODE REVIEW

**Comment by mrobinson** [comment]
This is now ready for review.

File: components/script/textinput.rs [hunk 1]
```diff
@@ -1172,81 +1180,103 @@ impl<T: ClipboardProvider> TextInput<T> {
...
-    }
+                ClipboardEventReaction::FireClipboardChangedEvent |
+                    ClipboardEventReaction::QueueInputEvent
+            },
+            "paste" => {
+                // These steps are from <https://www.w3.org/TR/clipboard-apis/#paste-action>:
+                let Some(data_transfer) = clipboard_event.get_clipboard_data() else {
+                    return ClipboardEventReaction::empty();
+                };
+                let Some(drag_data_store) = data_transfer.data_store() else {
```
Comment (xiaochengh) [inline components/script/textinput.rs:1273]: It seems that our `DataTransfer` struct was implemented with only drag-and-drop in mind...

**Review by xiaochengh — APPROVED** [review]
LGTM, thanks!
