### PR TITLE
layout: Expand text clipping boundaries based on the largest advance in run

### LINKED ISSUE #41413: Italic letter "f" is drawn clipped
**Describe the bug:**
Noticed that the "f" on the body text of a web page was clipped. This seems consistent across several built-in fonts.

**To Reproduce:**
```html
<!doctype html>
<style>
    body { background: white }
    p { font: normal 130px "Arial"; }
</style>
<p><i>f</i></p>
```

Chrome
Image

Servo
Image

**Platform:**
Win 10

### PR DESCRIPTION
**Pull request by mrobinson**
Servo does not yet calculate the ink overflow area, as this sort of
thing is usually a result of `contain: paint` which Servo does not
support yet. We just need to ensure that text clipping is large
enough to contain the ink of all of the glyphs in the run. This change
just expands the rectangle based on glyph advances by 2 times the
largest advance, which should be big enough for most glyphs.

This is a big of a workaround until we have support for `contain:
paint`.

Testing:
- This change adds a Servo-specific test to ensure glyphs are fully
inked. While this test would run just fine in other browsers, it isn't very
useful to them as this is test is very specific to the way that Servo draws
glyphs.
- This also fixes a variety of existing WPT tests.

Fixes: #41413.

### CODE REVIEW

File: components/layout/display_list/mod.rs [hunk 1]
```diff
@@ -1726,10 +1738,13 @@ fn glyphs(
             if glyph.char_is_word_separator() {
                 baseline_origin.x += justification_adjustment;
             }
-            baseline_origin.x += glyph.advance();
+
+            let advance = glyph.advance();
+            baseline_origin.x += advance;
+            largest_advance = largest_advance.max(advance);
```
Comment (Loirooriol) [inline components/layout/display_list/mod.rs]: Nit:

```suggestion
            largest_advance.max_assign(advance)
```

File: tests/wpt/mozilla/tests/appearance/text-advance-less-than-ink-clipping.html
Comment (Loirooriol) [inline tests/wpt/mozilla/tests/appearance/text-advance-less-than-ink-clipping.html:1]: Seems like this could go to normal WPT instead of internal tests, but fine either way.

**Review by Loirooriol — APPROVED** [review]

File: components/layout/display_list/mod.rs (hunk 1 above)
Comment (mrobinson) [reply components/layout/display_list/mod.rs]: Oh. Nice. Fixed.

File: tests/wpt/mozilla/tests/appearance/text-advance-less-than-ink-clipping.html
Comment (mrobinson) [reply tests/wpt/mozilla/tests/appearance/text-advance-less-than-ink-clipping.html:1]: Yes, I waffled a bit on this, but in the end I went with adding this as a Servo-only test. This problem is very specific to Servo's rendering to the point that it seems almost too basic for other browsers. I suspect that when we implement `contain: paint` we'll gain a bunch of similar tests as well.

**Comment by mrobinson** [comment]
```
PASS [expected FAIL] /_mozilla/css/pseudo_inherit.html
PASS [expected FAIL] /css/CSS2/css1/c542-letter-sp-001.xht
PASS [expected FAIL] /css/CSS2/normal-flow/blocks-018.xht
PASS [expected FAIL] /css/CSS2/normal-flow/blocks-019.xht
PASS [expected FAIL] /css/CSS2/normal-flow/replaced-intrinsic-002.xht
PASS [expected FAIL] /css/CSS2/text/text-transform-bicameral-003.xht
PASS [expected FAIL] /css/CSS2/text/text-transform-bicameral-004.xht
PASS [expected FAIL] /css/CSS2/text/text-transform-bicameral-011.xht
PASS [expected FAIL] /css/CSS2/text/text-transform-bicameral-014.xht
PASS [expected FAIL] /css/CSS2/text/text-transform-bicameral-016.xht
PASS [expected FAIL] /css/WOFF2/datatypes-alt-255uint16-001.xht
PASS [expected FAIL] /css/WOFF2/tabledata-transform-hmtx-001.xht
PASS [expected FAIL] /css/WOFF2/tabledata-transform-hmtx-002.xht
PASS [expected FAIL] /css/WOFF2/valid-005.xht
PASS [expected FAIL] /css/WOFF2/valid-006.xht
PASS [expected FAIL] /css/WOFF2/valid-007.xht
PASS [expected FAIL] /css/WOFF2/valid-008.xht
PASS [expected FAIL] /css/css-content/quotes-034.html
PASS [expected FAIL] /css/css-text/shaping/shaping-012.html
PASS [expected FAIL] /css/css-text/shaping/shaping-013.html
FAIL [expected PASS] /css/css-text/shaping/shaping-arabic-diacritics-002.html
```

I believe these are all progressions. The behavior tested by the Arabic diacritic tests is not supported in Servo.
