### PR TITLE
script: Implement jsglue traps for saveJobQueue()

### LINKED ISSUE #38311: main is busted with --debug-mozjs / MOZJS_FROM_SOURCE=1
it looks like #38284 bumped the mozjs-sys source dependency from [128e1e230a015](https://github.com/servo/mozjs/commit/128e1e230a0155ed9395c718184f34bddc045860) to [9c017973a4bf9](https://github.com/servo/mozjs/commit/9c017973a4bf9186df2335d8c96ed3554b84434e) ([diff](https://github.com/servo/mozjs/compare/128e1e230a0155ed9395c718184f34bddc045860...9c017973a4bf9186df2335d8c96ed3554b84434e)), but only bumped the artifact dependency from [v0.128.13-0](https://github.com/servo/mozjs/releases/tag/mozjs-sys-v0.128.13-0) ([128e1e230a015](https://github.com/servo/mozjs/commit/128e1e230a0155ed9395c718184f34bddc045860)) to [v0.128.13-1](https://github.com/servo/mozjs/releases/tag/mozjs-sys-v0.128.13-1) ([b14aebff23ac4](https://github.com/servo/mozjs/commit/b14aebff23ac4d5b0652060ef949334bda08b22f)).

but since [ace07c828648a](https://github.com/servo/mozjs/commit/ace07c828648a4bfc5eab040bae73e6c846ecc62) includes breaking changes in mozjs-sys, main is now busted if we build mozjs-sys from source. this divergence also seems to be why we can’t land #38232: it depends on the new mozjs-sys and addresses the breaking changes, but we build with the outdated mozjs-sys artifacts in CI.

busted as of 93d234d270cccd26ed73a3390bc340045440e8a2:

```
➜  servo git:(main) ✗ MOZJS_FROM_SOURCE=1 ./mach build
No build type specified so assuming `--dev`.
Building `debug` build with crown disabled (no JS garbage collection linting).
   Compiling mozjs_sys v0.128.13-1 (https://github.com/servo/mozjs#9c017973)
   Compiling mozjs v0.14.1 (https://github.com/servo/mozjs#9c017973)
   Compiling script_bindings v0.0.1 (/Users/atbrakhi/Documents/codespace/servo/components/script_bindings)
   Compiling script v0.0.1 (/Users/atbrakhi/Documents/codespace/servo/components/script)
error[E0063]: missing fields `dropInterruptQueues`, `popInterruptQueue` and `pushNewInterruptQueue` in initializer of `JobQueueTraps`
  --> components/script/script_runtime.rs:87:41
   |
87 | static JOB_QUEUE_TRAPS: JobQueueTraps = JobQueueTraps {
   |                                         ^^^^^^^^^^^^^ missing `dropInterruptQueues`, `popInterruptQueue` and `pushNewInterruptQueue`

error[E0061]: this function takes 3 arguments but 2 arguments were supplied
    --> components/script/script_runtime.rs:584:25
     |
584  |           let job_queue = CreateJobQueue(
     |  _________________________^^^^^^^^^^^^^^-
585  | |             &JOB_QUEUE_TRAPS,
586  | |             &*microtask_queue as *const _ as *const c_void,
587  | |         );
     | |_________- argument #3 of type `*mut c_void` is missing
     |
note: function defined here
    --> /Users/atbrakhi/Documents/codespace/servo/target/debug/build/mozjs_sys-0806f33ec0b889c8/out/build/gluebindings.rs:1192:16
     |
1192 |         pub fn CreateJobQueue(
     |                ^^^^^^^^^^^^^^
help: provide the argument
     |
584  |         let job_queue = CreateJobQueue(&JOB_QUEUE_TRAPS, &*microtask_queue as *const _ as *const c_void, /* *mut c_void */);
     |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Some errors have detailed explanations: E0061, E0063.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `script` (lib) due to 2 previous errors
      Timing report saved to /Users/atbrakhi/Documents/codespace/servo/target/cargo-timings/cargo-timing-20250728T074340Z.html
Failed in 0:01:36
```

### PR DESCRIPTION
**Pull request by delan**
in the [SpiderMonkey Debugger API](https://firefox-source-docs.mozilla.org/js/Debugger/), hooks like [onNewGlobalObject()](https://firefox-source-docs.mozilla.org/js/Debugger/Debugger.html#onnewglobalobject-global) use an AutoDebuggerJobQueueInterruption to [switch to a new microtask queue](https://github.com/servo/mozjs/blob/b14aebff23ac4d5b0652060ef949334bda08b22f/mozjs-sys/mozjs/js/src/debugger/Debugger.cpp#L2834-L2841) and avoid clobbering the debuggee’s microtask queue. this in turn relies on JobQueue::saveJobQueue(), which is [not yet implemented in RustJobQueue](https://github.com/servo/mozjs/blob/b14aebff23ac4d5b0652060ef949334bda08b22f/mozjs-sys/src/jsglue.cpp#L83-L86).

this patch bumps mozjs to servo/mozjs#595, which implements [saveJobQueue() and SavedJobQueue](https://github.com/servo/mozjs/blob/b14aebff23ac4d5b0652060ef949334bda08b22f/mozjs-sys/mozjs/js/public/Promise.h#L92-L114) for RustJobQueue by calling into Servo via two new JobQueueTraps that create and destroy extra “interrupt” queues for use by the debugger.

SpiderMonkey [does not own external job queues](https://github.com/servo/mozjs/blob/b14aebff23ac4d5b0652060ef949334bda08b22f/mozjs-sys/mozjs/js/public/Promise.h#L117-L123), so the lifetime of these queues is managed in Servo, where they are stored in a Vec-based stack. stack-like behaviour is adequate for SpiderMonkey’s save and restore patterns, as far as we can tell, but we’ve added an assertion just in case.

Testing: manually tested working in devtools debugger patch (#37667), where it will undergo automated tests
Fixes: #38311

### CODE REVIEW

**Comment by delan** [comment]
hmm, clippy is busted in ci, but not locally?

<https://github.com/servo/servo/actions/runs/16467745226/job/46549217975>

File: components/script/script_runtime.rs [hunk 1]
```diff
@@ -581,9 +615,15 @@ impl Runtime {
         InitConsumeStreamCallback(cx, Some(consume_stream), Some(report_stream_error));
 
         let microtask_queue = Rc::new(MicrotaskQueue::default());
+        let mut interrupt_microtask_queues: Rc<Vec<Rc<MicrotaskQueue>>> = Rc::new(vec![]);
+        // TODO: SAFETY: is this ok? It subverts the Rc::get_mut() check
+        let interrupt_queues_raw = Rc::get_mut(&mut interrupt_microtask_queues)
```
Comment (jdm) [inline components/script/script_runtime.rs]: This feels like a subversion of the type system. If we're going to use Rc and mutate the contents then we should use `Rc<RefCell<...>>` and avoid this sketchy get_mut dance. Alternatively, if we actually believe we're modelling unique ownership, we should use a Box instead and do the forget/from_raw pattern in the constructor and destructor.

File: components/script/script_runtime.rs [hunk 2]
```diff
@@ -248,6 +250,35 @@ unsafe extern "C" fn empty(extra: *const c_void) -> bool {
     result
 }
 
+#[allow(unsafe_code)]
+unsafe extern "C" fn push_new_interrupt_queue(interrupt_queues: *mut c_void) -> *mut c_void {
+    let mut result = std::ptr::null_mut();
+    wrap_panic(&mut || {
+        let interrupt_queues = &mut *(interrupt_queues as *mut Vec<Rc<MicrotaskQueue>>);
+        let mut new_queue = Rc::new(MicrotaskQueue::default());
+        // TODO: SAFETY: is this ok? It subverts the Rc::get_mut() check
```
Comment (jdm) [inline components/script/script_runtime.rs]: With my suggestions from https://github.com/servo/mozjs/pull/595#pullrequestreview-3048546030 I don't believe get_mut is necessary here.

File: components/script/script_runtime.rs [hunk 3]
```diff
@@ -248,6 +250,35 @@ unsafe extern "C" fn empty(extra: *const c_void) -> bool {
...
+#[allow(unsafe_code)]
+unsafe extern "C" fn pop_interrupt_queue(interrupt_queues: *mut c_void) -> *mut c_void {
+    let mut result = std::ptr::null_mut();
+    wrap_panic(&mut || {
+        let interrupt_queues = &mut *(interrupt_queues as *mut Vec<Rc<MicrotaskQueue>>);
+        let mut popped_queue: Rc<MicrotaskQueue> =
+            interrupt_queues.pop().expect("Guaranteed by SpiderMonkey?");
+        // Dangling, but jsglue.cpp will only use this for pointer comparison.
+        // TODO: SAFETY: is this ok? It subverts the Rc::get_mut() check
+        result = Rc::get_mut(&mut popped_queue).expect("Guaranteed by usage of `popped_queue`")
```
Comment (jdm) [inline components/script/script_runtime.rs]: Same as above.

**Review by jdm — CHANGES_REQUESTED** [review]
I'd like to see the code with my suggestions addressed. My hope is that it will raise fewer eyebrows!

File: components/script/script_runtime.rs (hunk 1 above)
Comment (delan) [reply components/script/script_runtime.rs]: thanks! done the latter in c6f599b2bd8c7b22c64ef1a34f976262246eb5e9 :)

File: components/script/script_runtime.rs (hunk 2 above)
Comment (delan) [reply components/script/script_runtime.rs]: fixed in c6f599b2bd8c7b22c64ef1a34f976262246eb5e9

File: components/script/script_runtime.rs (hunk 3 above)
Comment (delan) [reply components/script/script_runtime.rs]: fixed in cacdb8f39f73c7260e825a41d0fb172f20fb13bd

Comment (delan) [reply components/script/script_runtime.rs]: fixed in c6f599b2bd8c7b22c64ef1a34f976262246eb5e9

**Review by jdm — APPROVED** [review]
Much more clear!

**Comment by jdm** [comment]
@delan Clippy warnings are preventing merging.

**Comment by delan** [comment]
@jdm fixed in 77be5d157c27647da33723be46cc7ccb3f103012 :)
