### PR TITLE
script: Allow loading of `<iframe srcdoc>` with a `sandbox` attribute

### LINKED ISSUE #27791: about:srcdoc in scheme_fetch unsupported
https://github.com/servo/servo/blob/66616c65a1fec6a9ecb9260ced98c4dc7a21fef0/components/net/fetch/methods.rs#L624 doesn't support srcdoc urls.

This is part of the test fails in /secure-contexts/basic-popup-and-iframe-tests.https.html

This gets called from components/net/resource_thread.rs fetch().

The test is creating srcdoc iframes.

### LINKED ISSUE #36529: Sandboxed iframes fetch about:srcdoc instead of loading the srcdoc contents
STR:
1. Add `        "about" if url.path() == "srcdoc" => unreachable!(),` to the match in https://github.com/servo/servo/blob/2362e4c134b3534287465092d6305043e5a580a6/components/net/fetch/methods.rs#L752
2. Run `./mach test-wpt /secure-contexts/basic-popup-and-iframe-tests.html`

Output:
```
  ▶ CRASH [expected TIMEOUT] /secure-contexts/basic-popup-and-iframe-tests.html
  │
  │ UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
  │ internal error: entered unreachable code (thread tokio-runtime-4, at components/net/fetch/methods.rs:800)
  │   12: core::panicking::panic
  │              at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/panicking.rs:145:5
  │   13: net::fetch::methods::scheme_fetch::{{closure}}
  │              at /Users/jdm/src/alt-servo/components/net/fetch/methods.rs:800:46
  │   14: net::fetch::methods::main_fetch::{{closure}}
  │              at /Users/jdm/src/alt-servo/components/net/fetch/methods.rs:372:79
  │   15: net::fetch::methods::fetch_with_cors_cache::{{closure}}
  │              at /Users/jdm/src/alt-servo/components/net/fetch/methods.rs:166:77
  │   16: net::fetch::methods::fetch::{{closure}}
  │              at /Users/jdm/src/alt-servo/components/net/fetch/methods.rs:98:80
  │   17: net::resource_thread::CoreResourceManager::fetch::{{closure}}
  │              at /Users/jdm/src/alt-servo/components/net/resource_thread.rs:822:59
```

### PR DESCRIPTION
**Pull request by mrobinson**
Before, `about: srcdoc` was only handled when loading `<iframe>`
contents in the same `ScriptThread` as the parent. This is not always
the case though with sandboxed `<iframe>`s. This change makes it so that
both code paths properly handle `about: srcdoc`.

Testing: This causes around 12 new WPT passes.
Fixes: #36529.
Fixes: #27791.

### CODE REVIEW

File: components/script/script_thread.rs [hunk 1]
```diff
@@ -3544,6 +3537,16 @@ impl ScriptThread {
     /// Instructs the constellation to fetch the document that will be loaded. Stores the InProgressLoad
     /// argument until a notification is received that the fetch is complete.
     fn pre_page_load(&self, mut incomplete: InProgressLoad) {
+        let url = &incomplete.load_data.url;
```
Comment (Loirooriol) [inline components/script/script_thread.rs]: Can call `as_str()` once here instead of twice below.

```suggestion
        let url = &incomplete.load_data.url.as_str();
```

**Review by Loirooriol — APPROVED** [review]

**Comment by TimvdLippe** [comment]
Does this also fix #37499 ?
