### PR TITLE
fix: Crashing due to input element hack

### LINKED ISSUE #36449: Multi glyph runs in text input could crash
**Describe the bug:**
Not sure why search bar from google.com and textarea doesn't have this bug.
But I found text input might crash in a subtle manner.
The caret is missing even after pressing a few times of right arrow.

**To Reproduce:**
- Create a html file with following code and run with servoshell:

```
<input id="input_element" value="xxxxxxxxxxxxxxxxxxxx">
```

- Focus text input and the press right arrow 1 time
- type Bopomo "ㄎ"
- It will crash with following log:
```
iter_glyphs_for_range: range.end beyond length! (thread Script(1,1), at \servo\components\fonts\glyph.rs:614)
[2025-04-10T16:16:25Z ERROR servoshell::panic_hook] iter_glyphs_for_range: range.end beyond length!
```

**Platform:**
Windows 11

### PR DESCRIPTION
**Pull request by dklassic**
This PR addresses a crash in text input element due to a hack to prevent text input being trimmed.

The updated behavior will only add `zero width space` unicode character to the node if there's no text content instead of adding it constantly. Also by adding the same `zero width space` unicode character to text area when there's no text content within will allow text area element to properly display caret.

截圖 2025-04-11 中午12 51 00

This PR also addresses issues with multiple glyph runs:

https://github.com/user-attachments/assets/658db56f-b166-47ec-bc77-c6c13114d669

Testing: This PR is tested using:
- `./mach run -d 'data:text/html,<input id="input_element" value="xxxxxxxxxxxxxxxxxxxx">'`
- `./mach run -d 'data:text/html,<textarea id="input_element" value="xxxxxxxxxxxxxxxxxxxx">'`

without causing crashes, while the results should be covered by WPT tests

Fixes: https://github.com/servo/servo/issues/36449

### CODE REVIEW

File: components/layout_2020/display_list/mod.rs [hunk 1]
```diff
@@ -1234,10 +1232,17 @@ fn glyphs_advance_by_index(
 ) -> PhysicalPoint<Au> {
     let mut point = baseline_origin;
     for run in glyph_runs {
-        let total_advance = run.advance_for_byte_range(
-            &ServoRange::new(fonts::ByteIndex(0), index),
-            justification_adjustment,
-        );
+        let total_advance = if index < run.len() {
+            run.advance_for_byte_range(
+                &ServoRange::new(fonts::ByteIndex(0), index),
```
Comment (wusyong) [inline components/layout_2020/display_list/mod.rs:1237]:
```suggestion
                &ServoRange::new(fonts::ByteIndex(0), index.min(run.len())),
```

File: tests/wpt/meta/html/rendering/widgets/button-layout/input-type-button-clip.html.ini [hunk 2]
```diff
@@ -1,2 +1,2 @@
 [input-type-button-clip.html]
-  expected: FAIL
+  expected: PASS
```
Comment (jdm) [inline tests/wpt/meta/html/rendering/widgets/button-layout/input-type-button-clip.html.ini:2]: This file can be removed.

File: tests/wpt/meta/css/css-inline/baseline-source/baseline-source-first-textarea-001.tentative.html.ini [hunk 3]
```diff
@@ -3,7 +3,10 @@
     expected: FAIL
 
   [.target > * 1]
-    expected: FAIL
+    expected: PASS
```
Comment (jdm) [inline tests/wpt/meta/css/css-inline/baseline-source/baseline-source-first-textarea-001.tentative.html.ini:6]: This passing subtest can be removed.

**Review by jdm — APPROVED** [review]
