### PR TITLE
fix crash occurs when the focus element is adopted

### LINKED ISSUE #36607: A crash occurs when the focus element is adpoted.
**Describe the bug:**
A crash occurs when the focus element is adpoted.

**To Reproduce:**
testcase:
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
    </style>
</head>

<body>
<input id="username" type="text" placeholder="username">
<input id="password" type="text" placeholder="password">
</body>
<script>
    let search = document.getElementById("search");
    let username = document.getElementById("username");
    let tmp;
    username.addEventListener("click", function (e) {
        window.setTimeout(function () {
            tmp = document.adoptNode(username);
        }, 2000);
    });
    username.addEventListener("blur", function (e) {
        document.body.append(`event:${e.type} fire.`)
    });
</script>
</html>
```
step1: Click the username text box to focus.
step2: Wait for two seconds. The timer removes the username text box through the document.adopt interface.
step3: script thread carsh.

crash stack:
```
assertion `left == right` failed: Attempt to use script or layout while DOM not in a stable state
  left: 3
 right: 0 (thread Script(1,1), at components/script/dom/document.rs:4024)
   0: servoshell::backtrace::print
             at /home/code/myservo/servo/ports/servoshell/backtrace.rs:18:5
   1: servoshell::panic_hook::panic_hook
             at /home/code/myservo/servo/ports/servoshell/panic_hook.rs:40:17
   2: core::ops::function::Fn::call
             at /home/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79:5
   3: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/alloc/src/boxed.rs:2007:9
      std::panicking::rust_panic_with_hook
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panicking.rs:836:13
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panicking.rs:701:13
   5: std::sys::backtrace::__rust_end_short_backtrace
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/sys/backtrace.rs:168:18
   6: rust_begin_unwind
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panicking.rs:692:5
   7: core::panicking::panic_fmt
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/panicking.rs:75:14
   8: core::panicking::assert_failed_inner
   9: core::panicking::assert_failed
             at /home/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:364:5
  10: script::dom::document::Document::ensure_safe_to_run_script_or_layout
             at /home/code/myservo/servo/components/script/dom/document.rs:4024:9
  11: <script::dom::document::Document as script::dom::document::DocumentHelpers<script::dom::bindings::codegen::DomTypeHolder::DomTypeHolder>>::ensure_safe_to_run_script_or_layout
             at /home/code/myservo/servo/components/script/dom/document.rs:6396:9
  12: script::dom::bindings::callback::CallSetup<D>::new
             at /home/code/myservo/servo/components/script/dom/bindings/callback.rs:255:13
  13: script::dom::bindings::codegen::GenericBindings::EventListenerBinding::EventListener<D>::HandleEvent_
             at /home/code/myservo/servo/target/debug/build/script_bindings-b4bc17896ebfb359/out/Bindings/EventListenerBinding.rs:30:17
  14: script::dom::eventtarget::CompiledEventListener::call_or_handle_event
             at /home/code/myservo/servo/components/script/dom/eventtarget.rs:201:25
  15: script::dom::event::inner_invoke
             at /home/code/myservo/servo/components/script/dom/event.rs:1278:9
  16: script::dom::event::invoke
             at /home/code/myservo/servo/components/script/dom/event.rs:1164:17
  17: script::dom::event::Event::dispatch
             at /home/code/myservo/servo/components/script/dom/event.rs:558:17
  18: script::dom::eventtarget::EventTarget::dispatch_event
             at /home/code/myservo/servo/components/script/dom/eventtarget.rs:438:9
  19: script::dom::event::Event::fire
             at /home/code/myservo/servo/components/script/dom/event.rs:679:9
  20: script::dom::document::Document::fire_focus_event
             at /home/code/myservo/servo/components/script/dom/document.rs:3189:9
  21: script::dom::document::Document::commit_focus_transaction
             at /home/code/myservo/servo/components/script/dom/document.rs:1161:13
  22: script::dom::document::Document::request_focus
             at /home/code/myservo/servo/components/script/dom/document.rs:1140:13
  23: script::dom::document::Document::perform_focus_fixup_rule
             at /home/code/myservo/servo/components/script/dom/document.rs:1112:9
  24: script::dom::element::Element::update_sequentially_focusable_status
             at /home/code/myservo/servo/components/script/dom/element.rs:2265:13
  25: <script::dom::element::Element as script::dom::virtualmethods::VirtualMethods>::unbind_from_tree
             at /home/code/myservo/servo/components/script/dom/element.rs:3928:9
  26: <script::dom::htmlelement::HTMLElement as script::dom::virtualmethods::VirtualMethods>::unbind_from_tree
             at /home/code/myservo/servo/components/script/dom/htmlelement.rs:1158:13
  27: <script::dom::htmlinputelement::HTMLInputElement as script::dom::virtualmethods::VirtualMethods>::unbind_from_tree
             at /home/code/myservo/servo/components/script/dom/htmlinputelement.rs:2554:9
  28: script::dom::node::Node::complete_remove_subtree
             at /home/code/myservo/servo/components/script/dom/node.rs:359:13
  29: script::dom::node::Node::remove_child
             at /home/code/myservo/servo/components/script/dom/node.rs:416:9
  30: script::dom::node::Node::remove
             at /home/code/myservo/servo/components/script/dom/node.rs:2520:9
  31: script::dom::node::Node::remove_self
             at /home/code/myservo/servo/components/script/dom/node.rs:1190:13
  32: script::dom::node::Node::adopt
             at /home/code/myservo/servo/components/script/dom/node.rs:2057:9
  33: <script::dom::document::Document as script::dom::bindings::codegen::GenericBindings::DocumentBinding::Document_Binding::DocumentMethods<script::dom::bindings::codegen::DomTypeHolder::DomTypeHolder>>::AdoptNode
             at /home/code/myservo/servo/components/script/dom/document.rs:5226:9
  34: script::dom::bindings::codegen::GenericBindings::DocumentBinding::Document_Binding::adoptNode::{{closure}}::{{closure}}
             at /home/code/myservo/servo/target/debug/build/script_bindings-b4bc17896ebfb359/out/Bindings/DocumentBinding.rs:1521:55
  35: script::dom::bindings::codegen::GenericBindings::DocumentBinding::Document_Binding::adoptNode::{{closure}}
             at /home/code/myservo/servo/target/debug/build/script_bindings-b4bc17896ebfb359/out/Bindings/DocumentBinding.rs:1494:33
  36: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /home/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:305:13
  37: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
  38: std::panicking::try::do_call
             at /home/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:584:40
  39: __rust_try
  40: std::panicking::try
             at /home/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:547:19
      std::panic::catch_unwind
             at /home/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:358:14
  41: mozjs::panic::wrap_panic
             at /home/.cargo/git/checkouts/mozjs-dd2a25693c61d87d/39db843/mozjs/src/panic.rs:22:11
  42: script::dom::bindings::codegen::GenericBindings::DocumentBinding::Document_Binding::adoptNode
             at /home/code/myservo/servo/target/debug/build/script_bindings-b4bc17896ebfb359/out/Bindings/DocumentBinding.rs:1494:5
  43: CallJitMethodOp
             at /home/runner/work/mozjs/mozjs/mozjs-sys/src/jsglue.cpp:581:22
  44: script::dom::bindings::utils::generic_call
             at /home/code/myservo/servo/components/script/dom/bindings/utils.rs:530:5
  45: script::dom::bindings::utils::generic_method
             at /home/code/myservo/servo/components/script/dom/bindings/utils.rs:546:5
  46: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  47: _ZN2js9InterpretEP9JSContextRNS_8RunStateE
  48: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  49: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  50: _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
  51: _ZN2JS4CallEP9JSContextNS_6HandleINS_5ValueEEES4_RKNS_16HandleValueArrayENS_13MutableHandleIS3_EE
  52: mozjs::rust::wrappers::Call
             at /home/.cargo/git/checkouts/mozjs-dd2a25693c61d87d/39db843/mozjs/src/rust.rs:1135:51
  53: script::dom::bindings::codegen::GenericBindings::FunctionBinding::Function<D>::Call
             at /home/code/myservo/servo/target/debug/build/script_bindings-b4bc17896ebfb359/out/Bindings/FunctionBinding.rs:62:18
  54: script::dom::bindings::codegen::GenericBindings::FunctionBinding::Function<D>::Call_
             at /home/code/myservo/servo/target/debug/build/script_bindings-b4bc17896ebfb359/out/Bindings/FunctionBinding.rs:35:18
  55: script::timers::JsTimerTask::invoke
             at /home/code/myservo/servo/components/script/timers.rs:561:25
  56: script::timers::OneshotTimerCallback::invoke
             at /home/code/myservo/servo/components/script/timers.rs:92:52
  57: script::timers::OneshotTimers::fire_timer
             at /home/code/myservo/servo/components/script/timers.rs:226:13
  58: script::dom::globalscope::GlobalScope::fire_timer
             at /home/code/myservo/servo/components/script/dom/globalscope.rs:2761:9
  59: script::timers::TimerListener::handle::{{closure}}
             at /home/code/myservo/servo/components/script/timers.rs:616:17
  60: core::ops::function::FnOnce::call_once
             at /home/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  61: <script::timers::TimerListener::handle::timer_event<F> as script::task::TaskOnce>::run_once
             at /home/code/myservo/servo/components/script/task.rs:24:17
  62: <script::task::CancellableTask<T> as script::task::TaskOnce>::run_once
             at /home/code/myservo/servo/components/script/task.rs:106:13
  63: <T as script::task::TaskBox>::run_box
             at /home/code/myservo/servo/components/script/task.rs:57:9
  64: script::script_thread::ScriptThread::handle_msg_from_script
             at /home/code/myservo/servo/components/script/script_thread.rs:1975:17
  65: script::script_thread::ScriptThread::handle_msgs::{{closure}}
             at /home/code/myservo/servo/components/script/script_thread.rs:1512:60
  66: script::script_thread::ScriptThread::profile_event
             at /home/code/myservo/servo/components/script/script_thread.rs:1724:13
  67: script::script_thread::ScriptThread::handle_msgs
             at /home/code/myservo/servo/components/script/script_thread.rs:1503:27
  68: script::script_thread::ScriptThread::start
             at /home/code/myservo/servo/components/script/script_thread.rs:981:15
  69: <script::script_thread::ScriptThread as script_layout_interface::ScriptThreadFactory>::create::{{closure}}::{{closure}}
             at /home/code/myservo/servo/components/script/script_thread.rs:435:25
  70: profile_traits::mem::ProfilerChan::run_with_memory_reporting
             at /home/code/myservo/servo/components/shared/profile/mem.rs:91:9
  71: <script::script_thread::ScriptThread as script_layout_interface::ScriptThreadFactory>::create::{{closure}}
             at /home/code/myservo/servo/components/script/script_thread.rs:433:17
  72: std::sys::backtrace::__rust_begin_short_backtrace
             at /home/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:152:18
  73: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /home/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:564:17
  74: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
  75: std::panicking::try::do_call
             at /home/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:584:40
  76: __rust_try
  77: std::panicking::try
             at /home/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:547:19
      std::panic::catch_unwind
             at /home/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:358:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /home/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:562:30
  78: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /home/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  79: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/alloc/src/boxed.rs:1993:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/alloc/src/boxed.rs:1993:9
      std::sys::pal::unix::thread::Thread::new::thread_start
             at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/sys/pal/unix/thread.rs:106:17
  80: start_thread
             at ./nptl/pthread_create.c:442:8
  81: __GI___clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81:0
[2025-04-19T01:04:47Z ERROR servoshell::panic_hook] assertion `left == right` failed: Attempt to use script or layout while DOM not in a stable state
      left: 3
     right: 0

```
**Platform:**
ALL

### PR DESCRIPTION
**Pull request by kongbai1996**
fix crash occurs when the focus element is adopted.

Testing: wpt dom/nodes/insertion-removing-steps/blur-event.window.html not crash

Fixes:  #36607 #32972

### CODE REVIEW

**Comment by kongbai1996** [comment]
wpt result: https://github.com/kongbai1996/servo/actions/runs/14547466825

File: components/script/dom/document.rs [hunk 1]
```diff
@@ -1127,15 +1127,32 @@ impl Document {
...
+    pub(crate) fn perform_focus_fixup_rule(&self, not_focusable: &Element) {
         if Some(not_focusable) != self.focused.get().as_deref() {
             return;
         }
-        self.request_focus(
-            self.GetBody().as_ref().map(|e| e.upcast()),
-            FocusType::Element,
-            can_gc,
-        )
+        if self.script_and_layout_blockers.get() > 0 {
```
Comment (jdm) [inline components/script/dom/document.rs:1134]: I don't think we should split the logic like this, and I don't think that moving it into a delayed task is the right choice. I suspect that https://github.com/servo/servo/issues/32972#issuecomment-2275468206 is the right fix.

Comment (kongbai1996) [reply components/script/dom/document.rs:1134]: Okay, I'll modify it according to the new plan. 
My question is how to achieve
> document's focused area to document's viewport

Comment (jdm) [reply components/script/dom/document.rs:1134]: The best path forward might be to rebase https://github.com/servo/servo/pull/28571 and build on top of those changes.

Comment (kongbai1996) [reply components/script/dom/document.rs:1134]: request_focus receives an `Element` parameter.

Comment (kongbai1996) [reply components/script/dom/document.rs:1134]: > The best path forward might be to rebase #28571 and build on top of those changes.

I will try.

Comment (kongbai1996) [reply components/script/dom/document.rs:1134]: I reviewed and rewritten the PR, but it didn't solve the crash problem.

> The best path forward might be to rebase #28571 and build on top of those changes.

Comment (kongbai1996) [reply components/script/dom/document.rs]: In this PR, I only let him not trigger the blur event.

**Comment by kongbai1996** [comment]
wpt result: https://github.com/kongbai1996/servo/actions/runs/14591474178

**Comment by kongbai1996** [comment]
Please review.

**Comment by kongbai1996** [comment]
@jdm @webbeef Please review it again.
> The best path forward might be to rebase #28571 and build on top of those changes.

Rewrite in another PR: #36649

**Review by xiaochengh — COMMENTED** [review]
Code change LGTM, but the current approach no longer match the PR description.

Please update the description accordingly, and also remove placeholder text.

**Comment by jdm** [comment]
Can you check if this fixes #36729 and add the test case as a crashtest in tests/mozilla/tests/mozilla?

**Comment by kongbai1996** [comment]
> Can you check if this fixes #36729 and add the test case as a crashtest in tests/mozilla/tests/mozilla?



> tests/mozilla/tests/mozilla?

Okay, I'll check. Is the test case to be added to the WPT test case?

**Comment by kongbai1996** [comment]
> Can you check if this fixes #36729 and add the test case as a crashtest in tests/mozilla/tests/mozilla?

I've checked and can fix the problem with # 36729

**Comment by kongbai1996** [comment]
> Can you check if this fixes #36729 and add the test case as a crashtest in tests/mozilla/tests/mozilla?

Perhaps merge and then test cases are completed in another PR.

**Comment by jdm** [comment]
I would prefer to add the testcase in this PR since it fixes it.

**Comment by jdm** [comment]
We can make it an automatic crashtest like in https://github.com/servo/servo/blob/main/tests/wpt/mozilla/tests/mozilla/datatransferitem-crash.html. there's no additional code required, just `-crash.html` in the filename.

**Comment by kongbai1996** [comment]
> We can make it an automatic crashtest like in https://github.com/servo/servo/blob/main/tests/wpt/mozilla/tests/mozilla/datatransferitem-crash.html. there's no additional code required, just `-crash.html` in the filename.

Has been added, please review.

**Comment by xiaochengh** [comment]
Is there any reason to keep test in the private `mozilla` directory, instead of to upstream it to WPT? Since the test doesn't use any private APIs.

**Comment by kongbai1996** [comment]
> Is there any reason to keep test in the private `mozilla` directory, instead of to upstream it to WPT? Since the test doesn't use any private APIs.

AFAIK,test cases in the tests/wpt/mozilla directory are not synchronized to the upstream WPT.

**Review by jdm — APPROVED** [review]
Thanks!
