### PR TITLE
Android: fix url resolution

### LINKED ISSUE #21948: Android's address bar is confused by localhost
I first run:

```
./mach run --android --release http://localhost:8000/examples/webgl_animation_cloth.html
```

Then I tap on the address bar and press enter.

Servo then tried to load that same URL but with domain `www.localhost.com` and fails.

### PR DESCRIPTION
**Pull request by Gae24**
The behavior is a bit different from before, previously any string with a . was considered a url, but I don't think is always a correct assumption.
Regarding localhost urls, only http scheme is accepted for now, should https also be accepted? 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #21948 (GitHub issue number if applicable)
- [X] These changes do not require tests because no new features.

### CODE REVIEW

**Comment by Gae24** [comment]
Found this issue #21304, wouldn't it better to send the url field string to the rust side and parse it like in minibrowser?

File: ports/jniapi/src/simpleservo.rs [hunk 1]
```diff
@@ -379,9 +380,17 @@ impl ServoGlue {
     }
 
     /// Load an URL. This needs to be a valid url.
```
Comment (mrobinson) [inline ports/jniapi/src/simpleservo.rs:382]:
```suggestion
    /// Load an URL. If this is not a valid URL, try to "fix" it by adding a scheme or if all else fails,
    /// interpret the string as a search term.
```

**Review by mrobinson — APPROVED** [review]
