### PR TITLE
layout: Persist `ExternalScrollId` for `::before` and `::after` pseudo element. 

### LINKED ISSUE #43308: The scroll of `::before` and `::after` pseudo element should persist after reflow
**Describe the bug:**
Because of how we set the ids of pseudo element, we lost tracks of the scroll id of older pseudo elements therefore losing the information about scroll offsets as well. 

**To Reproduce:**
Run the example the test file that have a constant reflow from animation:
```html
<div id="target">
    Content
</div>
<style>
#target::after, #target::before {
    display: block;
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";
    text-wrap: wrap;
    height: 100px;
    width: 100px;
    overflow: scroll;
    background-color: wheat;
}
@keyframes anim {
  0% { width: 100px; background-color: aliceblue; }
  100% { width: 50px; background-color: blue; }
}
#target {
  width: 100px;
  animation-name: anim;
  animation-duration: 4s;
  animation-iteration-count: infinite;
  animation-direction: alternate;
</style>
```

**Platform:**
Not platform specific.

### PR DESCRIPTION
**Pull request by stevennovaryo**
In general, for a normal `BoxFragment`, a `ExternalScrollId` is created by directly using the `OpaqueNode::id` which is the heap address of the `Node`. But for a `BoxFragment` from a `::before` or `::after` pseudo element, we are using the next unused id (starting from zero) with an increment of two. 

This patch modifies so that we are using the bitwise or of `OpaqueNode::id` and `FragmentType` as the `ExternalScrollId`. With these changes, the `ExternalScrollId` for the pseudo elements would remain the same after reflow (instead of getting a new scroll id). 

Testing: New WPT test
Fixes: #43308

### CODE REVIEW

File: components/shared/layout/lib.rs
Comment (mrobinson) [inline components/shared/layout/lib.rs]: It seems that this is function is incorrect now?

Comment (stevennovaryo) [reply components/shared/layout/lib.rs]: I guess the current changes make it always return the `OpaqueNode` id for a `ExternalScrollId`, regardless of the pseudo element. Maybe we could extend it to return the `FragmentType` as well.

Comment (stevennovaryo) [reply components/shared/layout/lib.rs]: Speaking of the function, `SPECIAL_SCROLL_ROOT_ID_MASK` in this case seems to be not too purposeful (maybe a bit of sanity checks).

File: tests/wpt/tests/css/css-overflow/before-and-after-pseudo-element-scrolling.html [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+        let scroll_delta_promise = () => new Promise((resolve) => {
+          target.addEventListener("scroll", () => resolve());
+        });
+
+        // Scrolls the `::before` pseudo element and wait for the event.
+        let promise_scroll_before = scroll_delta_promise();
+        await new test_driver
+          .Actions()
+          .scroll(rect.left + 10, middle_point - rect.height / 4, 0, 1000)
+          .send();
```
Comment (stevennovaryo) [inline tests/wpt/tests/css/css-overflow/before-and-after-pseudo-element-scrolling.html]: Added a WPT! Though I have no idea why this kept timing out the WPT. 😵‍💫

Comment (stevennovaryo) [reply tests/wpt/tests/css/css-overflow/before-and-after-pseudo-element-scrolling.html]: Fixed the WPTs, it is a problem about `WhellAction` not supporting decimal number.

File: tests/wpt/tests/css/css-overflow/before-after-pseudo-element-scrolling.html [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+    <script src="/resources/testdriver-actions.js"></script>
+    <script src="/dom/events/scrolling/scroll_support.js"></script>
+    <style>
+    #target::before, #target::after {
+      display: block;
+      content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et "
+                "dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip "
+                "ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu "
+                "fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt "
+                "mollit anim id est laborum.";
```
Comment (mrobinson) [inline tests/wpt/tests/css/css-overflow/before-after-pseudo-element-scrolling.html]: Instead of text it would probably be better to use a background that changes color. You can construct one that is all red apart from the green section which should the bit scrolled into view. Then the reference can just be two green squares.

File: components/script/dom/document_event_handler.rs [hunk 3]
```diff
@@ -1853,8 +1853,10 @@ impl DocumentEventHandler {
         if scrolled_node.is_root() {
             document.handle_viewport_scroll_event();
         } else {
-            // Otherwise, check whether it is for a relevant element within the document.
-            let Some(node_id) = node_id_from_scroll_id(scrolled_node.0 as usize) else {
+            // Otherwise, check whether it is for a relevant element within the document. For a `::before` or `::after`
+            // pseudo element we follow Gecko or Chromium's behavior to ensure that the event reach the originating
+            // element.
+            let Some((node_id, _)) = node_id_from_scroll_id(scrolled_node.0 as usize) else {
```
Comment (mrobinson) [inline components/script/dom/document_event_handler.rs]: Isn't this going to be an issue if both the pseudo-element and the non-pseudo-element have an associated scroller?

File: components/shared/layout/lib.rs [hunk 4]
```diff
@@ -667,6 +669,23 @@ pub enum FragmentType {
...
+    fn try_from(value: usize) -> Result<Self, Self::Error> {
+        match value {
+            x if x == FragmentType::FragmentBody as usize => Ok(FragmentType::AfterPseudoContent),
+            x if x == FragmentType::BeforePseudoContent as usize => {
+                Ok(FragmentType::BeforePseudoContent)
+            },
+            x if x == FragmentType::AfterPseudoContent as usize => {
+                Ok(FragmentType::AfterPseudoContent)
+            },
+            _ => Err(()),
```
Comment (mrobinson) [inline components/shared/layout/lib.rs]: I think you don't really need a match if you are just doing if statements inside.

File: components/shared/layout/lib.rs [hunk 5]
```diff
@@ -677,36 +696,16 @@ impl From<Option<PseudoElement>> for FragmentType {
     }
 }
 
-/// The next ID that will be used for a special scroll root id.
-///
-/// A special scroll root is a scroll root that is created for generated content.
-static NEXT_SPECIAL_SCROLL_ROOT_ID: AtomicU64 = AtomicU64::new(0);
-
-/// If none of the bits outside this mask are set, the scroll root is a special scroll root.
-/// Note that we assume that the top 16 bits of the address space are unused on the platform.
```
Comment (mrobinson) [inline components/shared/layout/lib.rs:686]: Does the new code rely on this assumption? If so we need to maintain this comment as it explains why the code works at all.

File: components/shared/layout/lib.rs [hunk 6]
```diff
@@ -677,36 +696,16 @@ impl From<Option<PseudoElement>> for FragmentType {
...
-}
-
 pub fn combine_id_with_fragment_type(id: usize, fragment_type: FragmentType) -> u64 {
     debug_assert_eq!(id & (fragment_type as usize), 0);
-    if fragment_type == FragmentType::FragmentBody {
-        id as u64
-    } else {
-        next_special_id() | (fragment_type as u64)
-    }
+    (id as u64) | (fragment_type as u64)
```
Comment (mrobinson) [inline components/shared/layout/lib.rs:682]: On a 64bit platform id is 64 bits so we need some justification about why this isn't throwing away information here, I think.

File: components/shared/layout/lib.rs [hunk 7]
```diff
@@ -677,36 +696,16 @@ impl From<Option<PseudoElement>> for FragmentType {
...
 
-pub fn node_id_from_scroll_id(id: usize) -> Option<usize> {
-    if (id as u64 & !SPECIAL_SCROLL_ROOT_ID_MASK) != 0 {
-        return Some(id & !3);
-    }
-    None
+pub fn node_id_from_scroll_id(id: usize) -> Option<(usize, FragmentType)> {
+    let node_id = id & !3;
+    let pseudo = FragmentType::try_from(id & 3)
+        .expect("The scroll id should have convertible back to `FragmentType`.");
```
Comment (mrobinson) [inline components/shared/layout/lib.rs]: I think just return `None` here instead of panicking when we have corrupted data.

**Review by mrobinson — CHANGES_REQUESTED** [review]

File: tests/wpt/tests/css/css-overflow/before-after-pseudo-element-scrolling.html (hunk 2 above)
Comment (stevennovaryo) [reply tests/wpt/tests/css/css-overflow/before-after-pseudo-element-scrolling.html]: I am not sure we have much alternative due to the limitation in `content`. The `<gradient>` value doesn't seems to be implemented for Servo. So I pivot to using image for now. Let me know what you think.

File: components/script/dom/document_event_handler.rs (hunk 3 above)
Comment (stevennovaryo) [reply components/script/dom/document_event_handler.rs]: For now, in terms of event, we doesn't have a way to differentiate this. There are ongoing works in `CSSPseudoElement` that add `.pseudotargets` attribute to `Events` that represent the targeted pseudo element. Though we won't specify one for `scroll` event yet. https://github.com/w3c/csswg-drafts/issues/12163

File: components/shared/layout/lib.rs (hunk 5 above)
Comment (stevennovaryo) [reply components/shared/layout/lib.rs:686]: In the new code, we doesn't store a special root id anymore, so this is quite irrelevant. I am not sure it would be good for 16-bit machine either (if we want to support it).

File: components/shared/layout/lib.rs (hunk 6 above)
Comment (stevennovaryo) [reply components/shared/layout/lib.rs:682]: Thanks, it is right. I suppose this is more relevant to the comment describing the `FragmentType`, I have updated such comment. It should still follow the old statement.

File: components/shared/layout/lib.rs [hunk 8]
```diff
@@ -677,36 +693,15 @@ impl From<Option<PseudoElement>> for FragmentType {
...
 
-pub fn node_id_from_scroll_id(id: usize) -> Option<usize> {
-    if (id as u64 & !SPECIAL_SCROLL_ROOT_ID_MASK) != 0 {
-        return Some(id & !3);
-    }
-    None
+pub fn node_id_from_scroll_id(id: usize) -> Option<(usize, FragmentType)> {
+    let node_id = id & !3;
+    let pseudo = FragmentType::try_from(id & 3).ok()?;
+    Some((node_id, pseudo))
```
Comment (mrobinson) [inline components/shared/layout/lib.rs]: The second part of this tuple is unused so I think this can just return `usize` now. Later, if we need the `FragmentType` we can add a new `fragment_type_from_scroll_id` function.

File: components/shared/layout/lib.rs [hunk 9]
```diff
@@ -667,6 +667,22 @@ pub enum FragmentType {
...
+            Ok(FragmentType::FragmentBody)
+        } else if value == FragmentType::BeforePseudoContent as usize {
+            Ok(FragmentType::BeforePseudoContent)
+        } else if value == FragmentType::AfterPseudoContent as usize {
+            Ok(FragmentType::AfterPseudoContent)
+        } else {
+            Err(())
+        }
+    }
+}
```
Comment (mrobinson) [inline components/shared/layout/lib.rs]: I think this can be removed for now.

File: components/script/dom/document_event_handler.rs [hunk 10]
```diff
@@ -1853,8 +1853,10 @@ impl DocumentEventHandler {
         if scrolled_node.is_root() {
             document.handle_viewport_scroll_event();
         } else {
-            // Otherwise, check whether it is for a relevant element within the document.
-            let Some(node_id) = node_id_from_scroll_id(scrolled_node.0 as usize) else {
+            // Otherwise, check whether it is for a relevant element within the document. For a `::before` or `::after`
+            // pseudo element we follow Gecko or Chromium's behavior to ensure that the event reach the originating
```
Comment (mrobinson) [inline components/script/dom/document_event_handler.rs]: Nit:

```suggestion
            // pseudo element we follow Gecko or Chromium's behavior to ensure that the event reaches the originating
```

File: tests/wpt/tests/css/css-overflow/before-after-pseudo-element-scrolling.html [hunk 11]
```diff
@@ -0,0 +1,59 @@
...
+        // Scrolls the `::after` pseudo element and wait for the event.
+        let promise_scroll_after = waitForScrollEndOrTimeout(target, MAX_FRAME);
+        new test_driver
+          .Actions()
+          .scroll(rect.left + 10, Math.round(middle_point + rect.height / 4), 0, 1000)
+          .send();
+        await promise_scroll_after;
+
+        // This should force a reflow.
+        dummy.style.display = "none";
```
Comment (mrobinson) [inline tests/wpt/tests/css/css-overflow/before-after-pseudo-element-scrolling.html:53]: Is this necessary? Shouldn't `waitForNewFrame()` be enough?

File: tests/wpt/tests/css/css-overflow/reference/before-after-pseudo-element-scrolling-ref.html [hunk 12]
```diff
@@ -0,0 +1,6 @@
+<!DOCTYPE html>
+<meta charset="utf-8">
+<title>CSS Reftest Reference</title>
+<link rel="author" title="Steven Novaryo" href="mailto:steven.novaryo@gmail.com">
+<p>Test passes if there is a filled green square and <strong>no red</strong>.</p>
+<div style="width: 100px; height: 100px; background-image: url(/images/green.png);"></div>
```
Comment (mrobinson) [inline tests/wpt/tests/css/css-overflow/reference/before-after-pseudo-element-scrolling-ref.html:6]: I'm a bit nervous about creating this new reference here. Let's just move this to the  `tests/wpt/tests/css/css-overflow/reference` or use an image that is the right color green for the standard references.

File: components/shared/layout/lib.rs (hunk 8 above)
Comment (stevennovaryo) [reply components/shared/layout/lib.rs]: Sure, maybe a refactoring of `ExternalScrollId` type to scope such conversion utilities would be helpful later. But lets just leave it like before for now.

File: tests/wpt/tests/css/css-overflow/before-after-pseudo-element-scrolling.html (hunk 11 above)
Comment (stevennovaryo) [reply tests/wpt/tests/css/css-overflow/before-after-pseudo-element-scrolling.html:53]: It is supposed to be relayout. Updated the comments.

File: tests/wpt/tests/css/css-overflow/reference/before-after-pseudo-element-scrolling-ref.html (hunk 12 above)
Comment (stevennovaryo) [reply tests/wpt/tests/css/css-overflow/reference/before-after-pseudo-element-scrolling-ref.html:6]: Sure, I have moved the reference.

File: components/script/dom/document/document_event_handler.rs [hunk 13]
```diff
@@ -1862,10 +1862,9 @@ impl DocumentEventHandler {
         if scrolled_node.is_root() {
             document.handle_viewport_scroll_event();
         } else {
-            // Otherwise, check whether it is for a relevant element within the document.
-            let Some(node_id) = node_id_from_scroll_id(scrolled_node.0 as usize) else {
-                return;
-            };
+            // Otherwise, check whether it is for a relevant element within the document. For a `::before` or `::after`
+            // pseudo element we follow Gecko or Chromium's behavior to ensure that the event reaches the originating
```
Comment (mrobinson) [inline components/script/dom/document/document_event_handler.rs:1866]:
```suggestion
            // pseudo element we follow Gecko or Chromium's behavior to ensure that the event reaches the originating
            // node.
```

File: tests/wpt/tests/css/css-overflow/reference/before-after-pseudo-element-scrolling-ref.html (hunk 12 above)
Comment (mrobinson) [reply tests/wpt/tests/css/css-overflow/reference/before-after-pseudo-element-scrolling-ref.html:6]: Thanks. Though, please rename this to `tests/wpt/tests/css/css-overflow/before-after-pseudo-element-scrolling-ref.html`

**Review by mrobinson — APPROVED** [review]
Thank you!

File: tests/wpt/tests/css/css-overflow/reference/before-after-pseudo-element-scrolling-ref.html (hunk 12 above)
Comment (stevennovaryo) [reply tests/wpt/tests/css/css-overflow/reference/before-after-pseudo-element-scrolling-ref.html:6]: Updated, thanks!
