### PR TITLE
Fixed bug in textinput::adjust_vertical concerning selection_origin

### LINKED ISSUE #22457: Assertion failed when pressing directional keys inside a textarea
When running `./mach run "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_textarea"` after a `--dev` build, and playing around with the selection inside the text area, I usually get this error : 

```
assertion failed: self.edit_point <= begin
```

It seems that the function `adjust_vertical` of file `components/script/textinput.rs` is breaking the debug assertions in `assert_ok_selection`.

### PR DESCRIPTION
**Pull request by denismerigoux**
The `adjust_vertical` function of the `TextInput` module was forgetting to update the `selection_origin`.

I discovered the bug and figured out how it fix it using formal verification. More precisely, I manually translated the Rust code in a [F*](https://www.fstar-lang.org/) program that was functionally equivalent. Then I used the `assert_ok_selection` as a post-condition on the following functions :

* `select_all`
* `clear_selection`
* `adjust_selection_for_horizontal_change`
* `clear_selection_to_limit`
* `adjust_vertical`
* `perform_horizontal_adjustment`
* `adjust_horizontal`
* `adjust_horizontal_to_line_end`

I managed to prove automatically (using the Z3 backend of F*) that the post-condition held for all the functions except for `adjust_vertical`. I used the error messages from F* to infer the missing code so that the postcondition could hold and manually translated it to this PR diff.

I also added a simple unit test that would fail without this patch, and observed that the assertion failures noted in https://github.com/servo/servo/issues/22457 disappeared with this patch.

This verification work also allows me to say that the code of all the functions is now functionally correct in the sense that they all yield a valid selection in the sense of `asssert_ok_selection`, in all cases.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #22457 (GitHub issue number if applicable)

- [x] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22458)

### CODE REVIEW

File: components/script/textinput.rs [hunk 1]
```diff
@@ -442,12 +442,24 @@ impl<T: ClipboardProvider> TextInput<T> {
         let target_line: isize = self.edit_point.line as isize + adjust;
 
         if target_line < 0 {
-            self.edit_point.index = 0;
-            self.edit_point.line = 0;
+            let zero_point = TextPoint { index: 0, line: 0 };
+            self.edit_point = zero_point.clone();
```
Comment (KiChjang) [inline components/script/textinput.rs]: Can we keep the original field assignments instead of cloning the zero point? That seems to be more efficient to me.

File: components/script/textinput.rs [hunk 2]
```diff
@@ -442,12 +442,24 @@ impl<T: ClipboardProvider> TextInput<T> {
...
+            }
             return;
         } else if target_line as usize >= self.lines.len() {
             self.edit_point.line = self.lines.len() - 1;
             self.edit_point.index = self.current_line_length();
+            match (self.selection_origin, self.selection_direction) {
+                (Some(_), SelectionDirection::Backward) => {
+                    self.selection_origin = Some(self.edit_point)
+                },
+                _ => (),
```
Comment (KiChjang) [inline components/script/textinput.rs]: Same here about `if let`.

File: components/script/textinput.rs [hunk 3]
```diff
@@ -442,12 +442,24 @@ impl<T: ClipboardProvider> TextInput<T> {
...
         if target_line < 0 {
-            self.edit_point.index = 0;
-            self.edit_point.line = 0;
+            let zero_point = TextPoint { index: 0, line: 0 };
+            self.edit_point = zero_point.clone();
+            match (self.selection_origin, self.selection_direction) {
+                (Some(_), SelectionDirection::None) | (Some(_), SelectionDirection::Forward) => {
+                    self.selection_origin = Some(zero_point)
+                },
+                _ => (),
```
Comment (KiChjang) [inline components/script/textinput.rs]: Can make use of the if let shorthand here.

**Review by KiChjang — CHANGES_REQUESTED** [review]
Nice work! I only have some code syntax comments below.

File: components/script/textinput.rs (hunk 1 above)
Comment (denismerigoux) [reply components/script/textinput.rs]: Ok

File: components/script/textinput.rs (hunk 3 above)
Comment (denismerigoux) [reply components/script/textinput.rs]: Ok, I changed to `if`

File: components/script/textinput.rs [hunk 4]
```diff
@@ -442,12 +442,24 @@ impl<T: ClipboardProvider> TextInput<T> {
...
+                    self.selection_direction == SelectionDirection::Forward
+                {
+                    self.selection_origin = Some(TextPoint { line: 0, index: 0 })
+                }
+            }
             return;
         } else if target_line as usize >= self.lines.len() {
             self.edit_point.line = self.lines.len() - 1;
             self.edit_point.index = self.current_line_length();
+            if let Some(_) = self.selection_origin {
```
Comment (CYBAI) [inline components/script/textinput.rs]: If we don't use the value inside `Some`, maybe we can just check with `is_some()`?

```suggestion
            if self.selection_origin.is_some() {
```

Same for the previous `if let Some(_)`.

File: components/script/textinput.rs [hunk 5]
```diff
@@ -442,12 +442,24 @@ impl<T: ClipboardProvider> TextInput<T> {
...
+                if self.selection_direction == SelectionDirection::Backward {
+                    self.selection_origin = Some(self.edit_point)
```
Comment (CYBAI) [inline components/script/textinput.rs]: Missing semicolon ? but it seems `test-tidy` didn't complain about it 😂

Comment (denismerigoux) [reply components/script/textinput.rs]: Since the assignment has the `unit` type you don't need a semicolon here, but I put it all the same if it's the coding style.

File: components/script/textinput.rs (hunk 4 above)
Comment (denismerigoux) [reply components/script/textinput.rs]: Right, fixed it

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
Neat that you used formal methods to prove properties about the code! Thanks for fixing this!

**Comment by KiChjang** [comment]
@bors-servo r-

Sorry, do you mind squashing your commits into one?

**Comment by denismerigoux** [comment]
The commits are squashed :)

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Review by johanatan — COMMENTED** [review]
LGTM.
