### PR TITLE
Align Servo version between user agent string and servoshell about dialog

### LINKED ISSUE #33337: Minibrowser UA string / about
**Describe the bug:**
The minibrowser's about menu shows the version as `Nightly version: Servo 0.0.1-75c7712`, but the UA string reports as `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv: 109.0) Servo/1.0 Firefox/111.0`.  It's a small thing perhaps but it feels like we should bind in the proper version and at least not disagree on 0.0.1 and 1.0 - those seem quite different.

Screenshot 2024-09-05 at 2 59 07 PM

**Platform:**
MacOS, but presumably all platforms

### PR DESCRIPTION
**Pull request by Taym95**
image

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #33337

- [x] These changes do not require tests because there are no behavior changes.

### CODE REVIEW

File: components/servo/lib.rs [hunk 1]
```diff
@@ -1293,39 +1293,62 @@ enum UserAgent {
...
+}
+
+fn default_user_agent_string_for(agent: UserAgent) -> String {
+    let servo_version = get_servo_version();
+
     #[cfg(all(target_os = "linux", target_arch = "x86_64", not(target_env = "ohos")))]
-    const DESKTOP_UA_STRING: &str =
-        "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Servo/1.0 Firefox/111.0";
+    let desktop_ua_string = format!(
+        "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Servo/{} Firefox/111.0",
```
Comment (mrobinson) [inline components/servo/lib.rs:1305]: I think this would look nicer inline here and elsewhere.

```suggestion
        "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Servo/{servo_version} Firefox/111.0",
```

**Review by mrobinson — APPROVED** [review]

**Review by mrobinson — APPROVED** [review]
