### PR TITLE
selectors::Element::parent() shouldn't cross shadow tree boundary

### LINKED ISSUE #40896: Descendant combinator is incorrectly applied to elements inside a shadow tree
**Describe the bug:**
Descendant combinator shouldn't apply to an element if the element is inside a shadow tree and the matching ancestor is outside the shadow tree.

Servo can mainly handle this case, but fail if bring <style> into the shadow tree.

**To Reproduce:**
Test case:

```
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>Shadow DOM Style Test</title>
</head>
<body>
    <div class="parent">
        <common-cart id="hostElement"></common-cart>
    </div>

    <script>
        const hostElement = document.getElementById('hostElement');
        const shadowRoot = hostElement.attachShadow({mode: 'open'});

        shadowRoot.innerHTML = `
            <div class="child">
                <style>
                  .parent .child {
                      border: 5px solid red;
                      background-color: yellow;
                  }
                </style>
                This element is inside the Shadow DOM. <br>
                It should NOT have a red border and yellow background from descendant combinator style.
            </div>
        `;
    </script>
</body>
</html>
```

Chromium:
Image

Servo:
Image

### PR DESCRIPTION
**Pull request by longvatrong111**
ServoLayoutElement::parent_element() method shouldn't cross shadow tree boundary.
`inheritance_parent` uses `traversal_parent`

Testing: 
`tests/wpt/meta/css/css-lists/counter-list-item-slot-order.html.ini`
`tests/wpt/meta/css/css-nesting/host-nesting-003.html.ini`
`tests/wpt/meta/css/selectors/is-where-shadow.html.ini`
and manual test in the below issue
The regression in `tests/wpt/meta/html/rendering/the-details-element/details-blockification.html.ini` has 1 more cause https://github.com/servo/servo/pull/40977#issuecomment-3608471378

Fixes: [#40896](https://github.com/servo/servo/issues/40896)

cc: @xiaochengh

### CODE REVIEW

File: components/script/layout_dom/element.rs [hunk 1]
```diff
@@ -720,6 +720,7 @@ impl<'dom> ::selectors::Element for ServoLayoutElement<'dom> {
 
     fn parent_element(&self) -> Option<Self> {
         ServoLayoutElement::parent_element(self)
+            .filter(|e| Some(*e) != self.containing_shadow_host())
```
Comment (yezhizhen) [inline components/script/layout_dom/element.rs]:
```suggestion
            .filter(|element| Some(*element) != self.containing_shadow_host())
```

**Review by yezhizhen — APPROVED** [review]

File: components/script/layout_dom/element.rs [hunk 2]
```diff
@@ -720,6 +720,7 @@ impl<'dom> ::selectors::Element for ServoLayoutElement<'dom> {
 
     fn parent_element(&self) -> Option<Self> {
         ServoLayoutElement::parent_element(self)
```
Comment (emilio) [inline components/script/layout_dom/element.rs:717]: Let's fix `ServoLayoutElement::parent_element` instead, it shouldn't use the composed tree. `inheritance_parent` should tho.

**Review by emilio — CHANGES_REQUESTED** [review]

**Comment by emilio** [comment]
So something along these lines:

```diff
diff --git a/components/script/layout_dom/element.rs b/components/script/layout_dom/element.rs
index 14a6809df14..45179d2cd96 100644
--- a/components/script/layout_dom/element.rs
+++ b/components/script/layout_dom/element.rs
@@ -135,10 +135,7 @@ impl<'dom> ServoLayoutElement<'dom> {

     /// Returns the parent element of this element, if it has one.
     fn parent_element(&self) -> Option<Self> {
-        self.element
-            .upcast()
-            .composed_parent_node_ref()
-            .and_then(|node| node.downcast().map(ServoLayoutElement::from_layout_js))
+        self.as_node().parent_element()
     }

     fn is_root(&self) -> bool {
@@ -220,9 +217,7 @@ impl<'dom> style::dom::TElement for ServoLayoutElement<'dom> {
             return self.pseudo_element_originating_element();
         }

-        // FIXME: By default the inheritance parent would be the Self::parent_element
-        //        but probably we should use the flattened tree parent.
-        self.parent_element()
+        self.traversal_parent()
     }

     fn is_html_element(&self) -> bool {
@@ -711,7 +706,7 @@ impl<'dom> ::selectors::Element for ServoLayoutElement<'dom> {
     }

     fn parent_element(&self) -> Option<Self> {
-        ServoLayoutElement::parent_element(self)
+        self.as_node().parent_element()
     }

     fn parent_node_is_shadow_root(&self) -> bool {
```

**Review by emilio — APPROVED** [review]
Seem like mostly more passes, nice.

**Comment by longvatrong111** [comment]
> Seem like mostly more passes, nice.

`/html/rendering/the-details-element/details-blockification.html` because `details[open]::details-content` is not applied to the second slot element:
https://html.spec.whatwg.org/multipage/rendering.html#the-details-and-summary-elements

We can mark it fail now and address it in another issue.

**Comment by yezhizhen** [comment]
Can you fix the PR body?
@longvatrong111

**Comment by yezhizhen** [comment]
> Testing: css/css-nesting/host-nesting-003.html and manual test in the below issue

Update this too. More passing and one failing

**Comment by longvatrong111** [comment]
> > Testing: css/css-nesting/host-nesting-003.html and manual test in the below issue
> 
> Update this too. More passing and one failing

@yezhizhen thank you, updated.
