### PR TITLE
Fix parsing of ClipRect

### LINKED ISSUE #15728: Property parsing for clip: rect(auto, stuff) is broken
The _parser_ converts auto values of top/left to 0.  Per spec, that should happen at _used_ value time, not specified value time!  Simple testcase that's buggy:
```html
    <div style="clip: rect(auto, auto, auto, auto)"></div>
    <script>
      console.log(document.querySelector("div").style.clip);
    </script>
```
This should log `rect(auto, auto, auto, auto)` but logs `rect(0px, auto, auto, 0px)`.

@canaltinova @Manishearth @SimonSapin

### PR DESCRIPTION
**Pull request by canova**
Fix parsing of ClipRect for clip property.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15728 (github issue number if applicable).

- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15732)

### CODE REVIEW

File: components/layout/display_list_builder.rs [hunk 1]
```diff
@@ -1259,8 +1259,10 @@ impl FragmentDisplayListBuilding for Fragment {
         };
 
         // FIXME(pcwalton, #2795): Get the real container size.
-        let clip_origin = Point2D::new(stacking_relative_border_box.origin.x + style_clip_rect.left,
-                                       stacking_relative_border_box.origin.y + style_clip_rect.top);
+        let clip_origin = Point2D::new(stacking_relative_border_box.origin.x +
```
Comment (Manishearth) [inline components/layout/display_list_builder.rs]: nit: wrap

Comment (Manishearth) [inline components/layout/display_list_builder.rs]: oh never mind I see
