### PR TITLE
Stall PaintTask exit until it can release all buffers

### LINKED ISSUE #2641: Pixmap leak when clicking wikipedia links and going back in history repeatedly
Started from http://en.wikipedia.org/wiki/Hamster and kept clicking links in the first animal classification table then pressing backspace until I hit this failure:

```
task '<main>' failed at 'You should have disposed of the pixmap properly with destroy()! This pixmap will leak!', /home/jdm/sdb/servo/src/support/layers/rust-layers/platform/linux/surface.rs:200

Breakpoint 1, 0x0000000000b3cf40 in rust_fail ()
(gdb) bt
#0  0x0000000000b3cf40 in rust_fail ()
#1  0x0000000000b3cf13 in rt::unwind::Unwinder::begin_unwind::h60563c464593bdfaxoy::v0.11.0.pre ()
#2  0x0000000000b1d3e8 in rt::unwind::begin_unwind_inner::h614b985bc056a568Ovy::v0.11.0.pre ()
#3  0x0000000000a7c5b3 in rt::unwind::begin_unwind::h13767223029640461605::v0.1 ()
#4  0x0000000000a7f811 in layers::platform::linux::surface::NativeSurface.Drop::drop (self=<optimized out>) at /home/jdm/sdb/servo/src/support/layers/rust-layers/platform/linux/surface.rs:6
#5  0x000000000045081c in _$UP$msg..compositor_msg..LayerBufferSet::glue_drop.23252::h4a5044e5475bef48 ()
#6  0x000000000046481d in servo::compositing::compositor::IOCompositor::run (self=<optimized out>) at /home/jdm/sdb/servo/src/components/main/compositing/compositor.rs:777
#7  0x000000000048126b in create (app=<optimized out>, port=..., constellation_chan=..., profiler_chan=..., opts=..., port=..., constellation_chan=..., profiler_chan=...)
    at /home/jdm/sdb/servo/src/components/main/compositing/compositor.rs:174
#8  servo::compositing::CompositorTask::create (port=..., constellation_chan=..., profiler_chan=..., opts=...) at /home/jdm/sdb/servo/src/components/main/compositing/compositor_task.rs:233
#9  0x000000000057aea1 in servo::run (opts=...) at /home/jdm/sdb/servo/src/components/main/servo.rs:217
#10 0x00000000005784e7 in fn31793 () at /home/jdm/sdb/servo/src/components/main/servo.rs:136
#11 0x0000000000a78923 in start::closure.7873 ()
#12 0x0000000000b383e3 in rt::task::Task::run::closure.25277 ()
#13 0x0000000000b467fc in rust_try ()
#14 0x0000000000b3834f in rt::task::Task::run::hd9374ac35cf4aederkw::v0.11.0.pre ()
#15 0x0000000000a7873b in start::hedd8fcabd0e6c841qqe::v0.11.0.pre ()
#16 0x00000000005782a9 in main () at /home/jdm/sdb/servo/src/components/main/servo.rs:135
```

### PR DESCRIPTION
**Pull request by mrobinson**
It is possible for a PaintTask to start exiting soon after sending new
buffers to the compositor. In that case, the compositor should return
the now unnecessary buffers to the PaintTask so that it can properly
free them.

To accomplish this, the compositor now keeps a hash map of paint task
channels per pipeline id. When a PaintTask exists, the constellation
informs the compositor that it can forget about it. Additionally, the
PaintTask should not wait for any buffers when the engine is doing a
complete shutdown. In that case, the compositor is already halted and
has simply let all buffers leak. We pipe through the shutdown type when
destroying the pipeline to make this decision.

Fixes #2641.

### CODE REVIEW

File: components/gfx/paint_task.rs [hunk 1]
```diff
@@ -265,13 +272,29 @@ impl<C> PaintTask<C> where C: PaintListener + Send {
 
                     self.compositor.set_paint_state(self.id, IdlePaintState);
 
-                    debug!("paint_task: returning surfaces");
+                    for reply in replies.iter() {
+                        match reply {
```
Comment (pcwalton) [inline components/gfx/paint_task.rs]: nit: you can just use `let &(_, ref buffer_set) = reply` here.

File: components/compositing/compositor.rs [hunk 2]
```diff
@@ -614,6 +661,24 @@ impl<Window: WindowMethods> IOCompositor<Window> {
...
+                        let message = UnusedBufferMsg(new_layer_buffer_set.buffers);
+                        let _ = entry.get().send_opt(message);
+                    },
+                    Vacant(_) => panic!("Received a buffer from an unknown pipeline!"),
+                }
+            }
+        }
+    }
+
+    fn paint_to_layer(&mut self,
```
Comment (pcwalton) [inline components/compositing/compositor.rs]: nit: weird indentation for arguments here, I would line up to `(`

File: components/compositing/compositor.rs [hunk 3]
```diff
@@ -456,6 +467,41 @@ impl<Window: WindowMethods> IOCompositor<Window> {
...
+                                                   WantsScrollEventsFlag::WantsScrollEvents,
+                                                   opts::get().tile_size);
+        if !self.paint_channels.contains_key(&pipeline.id) {
+            self.paint_channels.insert(pipeline.id, pipeline.paint_chan.clone());
+        }
+
+        // All root layers mask to bounds.
+        *root_layer.masks_to_bounds.borrow_mut() = true;
+
+        match frame_rect {
```
Comment (pcwalton) [inline components/compositing/compositor.rs]: nit: could be `if let Some(ref frame_rect) = ...`

File: components/compositing/compositor.rs [hunk 4]
```diff
@@ -341,6 +345,13 @@ impl<Window: WindowMethods> IOCompositor<Window> {
                 self.window.set_cursor(cursor)
             }
 
+            (Msg::PaintTaskExited(pipeline_id), ShutdownState::NotShuttingDown) => {
+                match self.paint_channels.remove(&pipeline_id) {
```
Comment (pcwalton) [inline components/compositing/compositor.rs]: nit: could just be `if self.paint_channels.remove(&pipeline_id).is_none()`

**Comment by mrobinson** [comment]
Thanks for the review. I believe I have fixed all of the nits.
