### PR TITLE
layout: Support storing layout data for two-level nested pseudo-elements

### LINKED ISSUE #38177: Crash when run wpt test case: css/css-lists/nested-marker-styling.html
**Describe the bug:**
This is an extremely rare edge case. When running this [test case](https://github.com/servo/servo/blob/main/tests/wpt/tests/css/css-lists/nested-marker-styling.html), the following crash call stack was generated:
```
 0:05.51 pid:84083    0: <servoshell::backtrace::Print as core::fmt::Debug>::fmt
 0:05.51 pid:84083    1: core::fmt::write
 0:05.51 pid:84083    2: std::io::Write::write_fmt
 0:05.51 pid:84083    3: servoshell::backtrace::print
 0:05.51 pid:84083    4: servoshell::panic_hook::panic_hook
 0:05.51 pid:84083    5: std::panicking::rust_panic_with_hook
 0:05.51 pid:84083    6: std::panicking::begin_panic_handler::{{closure}}
 0:05.51 pid:84083    7: std::sys::backtrace::__rust_end_short_backtrace
 0:05.51 pid:84083    8: _rust_begin_unwind
 0:05.51 pid:84083    9: core::panicking::panic_fmt
 0:05.51 pid:84083   10: <script::layout_dom::node::ServoLayoutNode as layout::dom::NodeExt>::layout_data_mut
 0:05.52 pid:84083   11: <script::layout_dom::node::ServoLayoutNode as layout::dom::NodeExt>::pseudo_element_box_slot
 0:05.52 pid:84083   12: layout::flow::construct::BlockContainerBuilder::push_block_level_job_for_inline_formatting_context
 0:05.52 pid:84083   13: layout::flow::construct::BlockContainerBuilder::finish
 0:05.52 pid:84083   14: layout::flow::construct::<impl layout::flow::BlockContainer>::construct
 0:05.52 pid:84083   15: layout::flow::construct::BlockLevelJob::finish
 0:05.52 pid:84083   16: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
 0:05.52 pid:84083   17: rayon::iter::plumbing::bridge_producer_consumer::helper
 0:05.52 pid:84083   18: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
 0:05.52 pid:84083   19: rayon_core::registry::WorkerThread::wait_until_cold
 0:05.52 pid:84083   20: rayon_core::registry::ThreadBuilder::run
 0:05.52 pid:84083   21: std::sys::backtrace::__rust_begin_short_backtrace
 0:05.52 pid:84083   22: core::ops::function::FnOnce::call_once{{vtable.shim}}
 0:05.52 pid:84083   23: std::sys::pal::unix::thread::Thread::new::thread_start
 0:05.52 pid:84083   24: __pthread_start
```

After analysis, this bug was caused by concurrent borrowing of [InnerLayoutData](https://github.com/servo/servo/blob/main/components/layout/dom.rs#L169) across multiple threads. For this error to occur, the following conditions must be met: 
- A DOM node has display-outside: block; 
- It has two pseudo-elements whose display-outside is also block; 
- The box trees generated by these pseudo-elements contain nested anonymous boxes. 

When all these conditions are satisfied, it can lead to concurrent borrowing of `InnerLayoutData` across threads.

I've attempted to resolve this issue by repeatedly trying to obtain a mutable borrow of `InnerLayoutData` in [`NodeExt::pseudo_element_box`](https://github.com/servo/servo/blob/main/components/layout/dom.rs#L361) until success, which does fix the problem. However, I believe this approach is neither elegant nor robust. A better solution might be to introduce a lock-free `SmallVec` to replace the thread-unsafe [`SmallVec`](https://github.com/servo/servo/blob/main/components/layout/dom.rs#L46), and then replace the mutable borrow of `InnerLayoutData` with an immutable one.

**To Reproduce:**
```
./mach test-wpt --release tests/wpt/tests/css/css-lists/nested-marker-styling.html
```

**Platform:**
I catch this issue on Mac, but I think it is platform-independent.

### PR DESCRIPTION
**Pull request by mrobinson**
Add basic support for storing layout data for pseudo-elements nested to
up to two levels. This removes the last unstored layout result and fixes
a double-borrow issue. This change does not add properly parsing nor
styling of these element types, but does prepare for those changes which
must come from stylo.

Testing: This fixes a intermittent panic in
`tests/wpt/tests/css/css-lists/nested-marker-styling.html`
Fixes: #38177. 
Closes: #38183.

### CODE REVIEW

File: components/layout/dom.rs [hunk 1]
```diff
@@ -350,22 +384,38 @@ impl<'dom> NodeExt<'dom> for ServoThreadSafeLayoutNode<'dom> {
...
-        box_slot.into()
+        let Some(secondary) = pseudo_element_chain.secondary else {
+            let primary_layout_data = self
+                .ensure_inner_layout_data()
+                .create_pseudo_layout_data(primary);
+            return primary_layout_data.borrow().self_box.clone().into();
+        };
+
+        // It's *very* important that this not borrow the element's main
+        // `InnerLayoutData`. Primary psuedo-elements are processed at the same recursion
```
Comment (Loirooriol) [inline components/layout/dom.rs]:
```suggestion
        // `InnerLayoutData`. Primary pseudo-elements are processed at the same recursion
```

File: components/layout/dom_traversal.rs [hunk 2]
```diff
@@ -83,7 +85,7 @@ impl<'dom> From<&NodeAndStyleInfo<'dom>> for BaseFragmentInfo {
         // cases, but currently this means that the order of hit test results isn't as expected for
         // some WPT tests. This needs more investigation.
         if matches!(
-            pseudo,
+            pseudo_element_chain.primary,
```
Comment (Loirooriol) [inline components/layout/dom_traversal.rs]: Should this check secondary too?

File: components/shared/layout/wrapper_traits.rs [hunk 3]
```diff
@@ -294,52 +293,62 @@ pub trait ThreadSafeLayoutElement<'dom>:
...
+        let data = self.style_data();
+        let primary_style = data.styles.primary();
+        let pseudo_element_chain = self.pseudo_element_chain();
+
+        let style = match pseudo_element_chain.primary {
+            Some(pseudo_element) => get_style_for_pseudo_element(primary_style, pseudo_element),
+            None => return primary_style.clone(),
+        };
+        match pseudo_element_chain.secondary {
+            Some(pseudo_element) => get_style_for_pseudo_element(primary_style, pseudo_element),
```
Comment (Loirooriol) [inline components/shared/layout/wrapper_traits.rs]: This should use the style of the primary pseudo as a base, right?

```suggestion
            Some(pseudo_element) => get_style_for_pseudo_element(style, pseudo_element),
```

File: components/layout/fragment_tree/base_fragment.rs [hunk 4]
```diff
@@ -114,23 +114,29 @@ malloc_size_of_is_0!(FragmentFlags);
...
+    pub(crate) fn new_pseudo(node: OpaqueNode, pseudo_element_chain: PseudoElementChain) -> Self {
+        Tag {
+            node,
+            pseudo_element_chain,
+        }
     }
 
     pub(crate) fn to_display_list_fragment_id(self) -> u64 {
-        combine_id_with_fragment_type(self.node.id(), self.pseudo.into())
+        combine_id_with_fragment_type(self.node.id(), self.pseudo_element_chain.primary.into())
```
Comment (Loirooriol) [inline components/layout/fragment_tree/base_fragment.rs:140]: Shouldn't this also check the secondary pseudo?

**Review by Loirooriol — APPROVED** [review]

File: components/layout/dom.rs (hunk 1 above)
Comment (mrobinson) [reply components/layout/dom.rs]: Fixed.

File: components/layout/dom_traversal.rs (hunk 2 above)
Comment (mrobinson) [reply components/layout/dom_traversal.rs]: Yeah, changed to be `innermost()`.

File: components/shared/layout/wrapper_traits.rs (hunk 3 above)
Comment (mrobinson) [reply components/shared/layout/wrapper_traits.rs]: Yep!

File: components/layout/fragment_tree/base_fragment.rs (hunk 4 above)
Comment (mrobinson) [reply components/layout/fragment_tree/base_fragment.rs:140]: This we can't do quite yet, because the code that we call here is only capable of dealing with `::before` and `::after` pseudo-elements.
