### PR TITLE
script: Add support for setting the edit point with the mouse in `<input>` and `<textarea>`

### LINKED ISSUE #10083: input / textarea - mouse interaction doesn't work
clicking on a specific position doesn't move the cursor to that specific position.
selection with the mouse doesn't work

### LINKED ISSUE #35432: layout: implement `process_text_index_request`
**Describe the new feature:**
Function [`process_text_index_request`](https://github.com/servo/servo/blob/main/components/layout_2020/query.rs#L1056) only return `None` for now instead of actually returning the index like [legacy layout](https://github.com/servo/servo/pull/14291) did. It would be nice to implement it, so the mouse click event can really change the position of caret in text input.

partially related to #33237

### PR DESCRIPTION
**Pull request by mrobinson**
This change updates and implements the old `query_text_index` layout
query to properly look for the glyph index of a point within a node's
`Fragment`s. This should work properly with the shadow DOM of both
`<input>` and `<textarea>` elements. In particular, multiple lines are
supported.

Caveats:
 - `<input>` and `<textarea>` that are transformed are currently not
   supported. This will happen in a followup.
 - For multi-line inputs, we should be finding the text offset of the
   nearest line that is within the block range of the click. This will
   happen in a followup.

Testing: This change adds two Servo-specific WPT-style tests. These are
Servo-specific because the behavior of clicking in text fields isn't
fully specified.

Fixes: #35432
Fixes: #10083

### CODE REVIEW

File: components/layout/flow/inline/text_run.rs [hunk 1]
```diff
@@ -136,6 +136,15 @@ impl TextRunSegment {
         for (run_index, run) in self.runs.iter().enumerate() {
             ifc.possibly_flush_deferred_forced_line_break();
 
+            // Advance the glyph offset of the current inline container. Note that this must
+            // be done before handling preserved newlines, as they count as glpyhs for the
```
Comment (Loirooriol) [inline components/layout/flow/inline/text_run.rs]:
```suggestion
            // be done before handling preserved newlines, as they count as glyphs for the
```

File: components/layout/fragment_tree/fragment.rs [hunk 2]
```diff
@@ -342,15 +359,37 @@ impl TextFragment {
...
+
+        for glyph_store in &self.glyphs {
+            for glyph in glyph_store.iter_glyphs_for_byte_range(TextByteRange::new(
+                ByteIndex::zero(),
+                glyph_store.len(),
+            )) {
+                current_offset += glyph.advance();
+                if current_offset - (glyph.advance().scale_by(0.5)) >= point.x {
+                    return current_glyph;
+                }
```
Comment (Loirooriol) [inline components/layout/fragment_tree/fragment.rs]: Can avoid calling `glyph.advance()` twice, and I think it looks better by increasing afterwards instead of subtracting in the condition

```suggestion
                let advance = glyph.advance();
                if current_offset + advance.scale_by(0.5) >= point.x {
                    return current_glyph;
                }
                current_offset += advance;
```

**Review by Loirooriol — APPROVED** [review]

File: components/layout/fragment_tree/fragment.rs (hunk 2 above)
Comment (mrobinson) [reply components/layout/fragment_tree/fragment.rs]: 👍

File: components/layout/flow/inline/text_run.rs (hunk 1 above)
Comment (mrobinson) [reply components/layout/flow/inline/text_run.rs]: 👍
