### PR TITLE
servoshell: Actually set the Servo delegate in servoshell

### LINKED ISSUE #35481: Servoshell never overrides the default ServoDelegate
This means that the devtools prompt is broken, since it's deny by default.

### PR DESCRIPTION
**Pull request by mrobinson**
This was implemented, but unset.

Fixes #35481.
Signed-off-by: Martin Robinson <mrobinson@igalia.com>

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because servoshell is untested.

### CODE REVIEW

File: ports/servoshell/desktop/app_state.rs [hunk 1]
```diff
@@ -6,7 +6,6 @@ use std::cell::{Ref, RefCell, RefMut};
 use std::collections::HashMap;
 use std::path::PathBuf;
 use std::rc::Rc;
-use std::thread;
```
Comment (mrobinson) [inline ports/servoshell/desktop/app_state.rs:9]: This change was unintentional and I will revert it.

**Review by jdm — APPROVED** [review]
