### PR TITLE
Don't log in the middle of mutating a reentrant lock

### LINKED ISSUE #13463: Intermittent timeout in /css-flexbox-1_dev/html/flexbox-basic-iframe-vert-001.htm
```
▶ TIMEOUT [expected FAIL] /css-flexbox-1_dev/html/flexbox-basic-iframe-vert-001.htm
  │ 
  │ Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(11) }"
  │ stack backtrace:
  │    0:        0x10685904e - backtrace::backtrace::trace::h0e60ef08c7c34e9f
  │    1:        0x10685933c - backtrace::capture::Backtrace::new::h8bf319c36d8f5d1b
  │    2:        0x10545619c - servo::install_crash_handler::handler::hfe019f650ed820a4
  │    3:     0x7fff99b3df19 - _sigtramp
  │    4:        0x106ab4e0d - util::remutex::HandOverHandMutex::lock::h88f6a8e9502fd439
  │    5:        0x106623788 - _<constellation..constellation..FromCompositorLogger as log..Log>::log::h256c0f2c59e0787a
  │    6:        0x106cffb21 - log::__log::h68a9f892b25070c1
  │    7:        0x1057dd29d - _<html5ever..tree_builder..TreeBuilder<Handle, Sink> as html5ever..tree_builder..rules..TreeBuilderStep>::step::h49da2fbb81ca7ce7
  │    8:        0x1057c7573 - _<html5ever..tree_builder..TreeBuilder<Handle, Sink> as html5ever..tokenizer..interface..TokenSink>::process_token::hef6a7cb2d5b0c202
  │    9:        0x1059fd910 - _<html5ever..tokenizer..Tokenizer<Sink>>::process_token::h647f0acc777b51b9
  │   10:        0x1059ff95a - _<html5ever..tokenizer..Tokenizer<Sink>>::end::h9b1fc1a4d2c6cc01
  │   11:        0x105c200d7 - _<&'a script..dom..servohtmlparser..ServoHTMLParser as script..parse..Parser>::finish::h6f731eb3df0873cf
  │   12:        0x105c2110c - script::dom::servohtmlparser::ServoHTMLParser::parse_sync::h59511fd912e1d673
  │   13:        0x105c1face - _<script..dom..servohtmlparser..ParserContext as net_traits..AsyncResponseListener>::response_complete::h58b268ddeed7b554
  │   14:        0x105c886c9 - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::h23d426c2ae56cc62
  │   15:        0x105cb13a5 - script::script_thread::ScriptThread::handle_msg_from_script::h1192beddc36c8c3b
  │   16:        0x105e4b46e - script::script_thread::ScriptThread::handle_msgs::_{{closure}}::h5dfecb26b72554f1
  │   17:        0x105ca58f9 - script::script_thread::ScriptThread::handle_msgs::h7dac20a7c5e01d37
  │   18:        0x10584a437 - std::panicking::try::do_call::h0c8dd4a1eee81358
  │   19:        0x106d2688a - __rust_maybe_catch_panic
  │   20:        0x1059f9e86 - _<F as alloc..boxed..FnBox<A>>::call_box::h90a9a1912d72d678
  │   21:        0x106d244a4 - std::sys::thread::Thread::new::thread_start::h022e3887023c6290
  │   22:     0x7fff99f21059 - _pthread_body
  │   23:     0x7fff99f20fd6 - _pthread_start
```
@asajeffrey This points the finger at a panic while locking the the mutex in the logging machinery :(

### PR DESCRIPTION
**Pull request by asajeffrey**
Moved assertion that we are the lock owner to after the lock release. The problem is that Servo uses a reentrant lock for logging, so logging in the middle of mutating the lock is A Bad Idea.

While I was at it, I tidied up the reentrant lock code.

cc @jdm 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13463.
- [X] These changes do not require tests because they fix an existing intermittent.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13472)

### CODE REVIEW

**Comment by notriddle** [comment]
Could you add this to the [former intermittent file](https://github.com/servo/servo/blob/master/etc/ci/former_intermittents_css.txt)?

File: components/util/remutex.rs [hunk 1]
```diff
@@ -87,13 +86,34 @@ impl HandOverHandMutex {
...
+        self.owner.store(Some(ThreadId::current()), Ordering::Relaxed);
+    }
+    #[allow(unsafe_code)]
+    unsafe fn unset_guard_and_owner(&self) {
+        let guard_ptr = &mut *self.guard.get();
+        let old_owner = self.owner();
+        self.owner.store(None, Ordering::Relaxed);
+        // Make sure we release the lock before checking the assertions,
+        // in Servo, we protect logging by a re-entrant lock, so we don't want
+        // to do any logging while we hold a re-entrant lock.
```
Comment (jdm) [inline components/util/remutex.rs]:
```rust
// Make sure we release the lock before checking the assertions.
// We protect logging by a re-entrant lock, so we don't want to
// do any incidental logging while we while the lock is held.
```

**Review by jdm — CHANGES_REQUESTED** [review]

**Comment by jdm** [comment]
Squash commits 1 & 3 and this can merge.
