### PR TITLE
script: revamp module script loading to follow current spec

### LINKED ISSUE #31397: Ocassional crash in script::script_module::ModuleTree::find_first_parse_error
```
Running WPT tests with /home/user/Desktop/servo/target/release/servo
Running 1 tests in web-platform-tests


This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after vfork from child process 240167]
[Detaching after vfork from child process 240169]
[Detaching after vfork from child process 240175]
[New Thread 0x7fffea3ff6c0 (LWP 240176)]
[New Thread 0x7fffe9bfe6c0 (LWP 240177)]
[New Thread 0x7fffe93fd6c0 (LWP 240179)]
[New Thread 0x7fffe8bfc6c0 (LWP 240180)]
[New Thread 0x7fffdbdff6c0 (LWP 240181)]
[New Thread 0x7fffdb5fe6c0 (LWP 240182)]
[New Thread 0x7fffdabfd6c0 (LWP 240183)]
[Thread 0x7fffdabfd6c0 (LWP 240183) exited]
[New Thread 0x7fffdabfd6c0 (LWP 240184)]
[New Thread 0x7fffda3ff6c0 (LWP 240188)]
[New Thread 0x7fffda1fe6c0 (LWP 240191)]
[New Thread 0x7fffd9ffd6c0 (LWP 240195)]
[New Thread 0x7fffd987c6c0 (LWP 240196)]
[New Thread 0x7fffd967b6c0 (LWP 240197)]
[New Thread 0x7fffd947a6c0 (LWP 240198)]
[New Thread 0x7fffd8fff6c0 (LWP 240199)]
[New Thread 0x7fffaffff6c0 (LWP 240200)]
[New Thread 0x7fffafdfe6c0 (LWP 240201)]
[New Thread 0x7fffaefff6c0 (LWP 240202)]
[New Thread 0x7fffaebfe6c0 (LWP 240203)]
[New Thread 0x7fffadfff6c0 (LWP 240204)]
[Thread 0x7fffadfff6c0 (LWP 240204) exited]
[New Thread 0x7fffadfff6c0 (LWP 240205)]
[New Thread 0x7fffad3ff6c0 (LWP 240206)]
[New Thread 0x7fffac9ff6c0 (LWP 240207)]
[New Thread 0x7fffac7fe6c0 (LWP 240208)]
[New Thread 0x7fff8bfff6c0 (LWP 240209)]
[New Thread 0x7fff83fff6c0 (LWP 240210)]
[New Thread 0x7fff8b7ff6c0 (LWP 240211)]
[New Thread 0x7fff8b5fe6c0 (LWP 240212)]
[New Thread 0x7fff8afff6c0 (LWP 240213)]
[New Thread 0x7fff8a3fe6c0 (LWP 240214)]
[New Thread 0x7fff8a5ff6c0 (LWP 240215)]
[New Thread 0x7fff899ff6c0 (LWP 240216)]
[New Thread 0x7fff88dff6c0 (LWP 240217)]
[New Thread 0x7fff83bfd6c0 (LWP 240219)]
[New Thread 0x7fff83dfe6c0 (LWP 240218)]
[New Thread 0x7fff831ff6c0 (LWP 240220)]
[New Thread 0x7fff829ff6c0 (LWP 240221)]
[New Thread 0x7fff825fe6c0 (LWP 240222)]
[New Thread 0x7fff81fff6c0 (LWP 240223)]
[New Thread 0x7fff811ff6c0 (LWP 240224)]
[New Thread 0x7fff80bff6c0 (LWP 240225)]
[New Thread 0x7fff803ff6c0 (LWP 240226)]
[New Thread 0x7fff7bbff6c0 (LWP 240227)]
[New Thread 0x7fff7b3ff6c0 (LWP 240228)]
[New Thread 0x7fff78fff6c0 (LWP 240229)]
[New Thread 0x7fff78dfe6c0 (LWP 240230)]
[Thread 0x7fffd987c6c0 (LWP 240196) exited]
[New Thread 0x7fffd987c6c0 (LWP 240231)]
[New Thread 0x7fff73fff6c0 (LWP 240232)]
[New Thread 0x7fffd8bfe6c0 (LWP 240233)]
[New Thread 0x7fffad7fe6c0 (LWP 240234)]
[New Thread 0x7fffacffe6c0 (LWP 240235)]
[New Thread 0x7fff8bdfe6c0 (LWP 240236)]
[New Thread 0x7fff8abfe6c0 (LWP 240237)]
[New Thread 0x7fff895fe6c0 (LWP 240238)]
[New Thread 0x7fff889fe6c0 (LWP 240239)]
[New Thread 0x7fff82dfe6c0 (LWP 240240)]
[New Thread 0x7fff706ff6c0 (LWP 240241)]
[New Thread 0x7fff704fe6c0 (LWP 240242)]
[New Thread 0x7fff702fd6c0 (LWP 240243)]
[New Thread 0x7fff615ff6c0 (LWP 240244)]
[New Thread 0x7fff613fe6c0 (LWP 240245)]
[New Thread 0x7fff611fd6c0 (LWP 240246)]
[New Thread 0x7fff60ffc6c0 (LWP 240247)]
[New Thread 0x7fff60dfb6c0 (LWP 240248)]
[New Thread 0x7fff60bfa6c0 (LWP 240249)]
[New Thread 0x7fff609f96c0 (LWP 240250)]
[New Thread 0x7fff607f86c0 (LWP 240251)]
[New Thread 0x7fff605f76c0 (LWP 240252)]
[New Thread 0x7fff603f66c0 (LWP 240253)]
[New Thread 0x7ffeebfff6c0 (LWP 240254)]
[New Thread 0x7ffeebdfe6c0 (LWP 240255)]
[New Thread 0x7ffeebbfd6c0 (LWP 240256)]
[New Thread 0x7fffae9766c0 (LWP 240262)]
[New Thread 0x7fffae8f56c0 (LWP 240263)]
[New Thread 0x7fffac5fd6c0 (LWP 240264)]

Thread 48 "Script(1,1)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd987c6c0 (LWP 240231)]
0x0000555559593cc1 in hashbrown::map::HashMap<K,V,S,A>::insert ()
#0  0x0000555559593cc1 in hashbrown::map::HashMap<K,V,S,A>::insert ()
#1  0x00005555596036db in script::script_module::ModuleTree::find_first_parse_error ()
#2  0x0000555559603a99 in script::script_module::ModuleTree::find_first_parse_error ()
#3  0x0000555559603a99 in script::script_module::ModuleTree::find_first_parse_error ()
#4  0x0000555559603a99 in script::script_module::ModuleTree::find_first_parse_error ()
#5  0x0000555559603a99 in script::script_module::ModuleTree::find_first_parse_error ()
#6  0x0000555559603a99 in script::script_module::ModuleTree::find_first_parse_error ()
#7  0x0000555559603a99 in script::script_module::ModuleTree::find_first_parse_error ()
#8  0x0000555559603a99 in script::script_module::ModuleTree::find_first_parse_error ()
#9  0x0000555559603a99 in script::script_module::ModuleTree::find_first_parse_error ()
#10 0x000055555960590b in script::script_module::ModuleTree::advance_finished_and_link ()
---------------------- ommited -----------------------------------
#7543 0x0000555559605851 in script::script_module::ModuleTree::advance_finished_and_link ()
#7544 0x00005555596050a8 in script::script_module::ModuleTree::fetch_module_descendants ()
#7545 0x0000555559608c19 in <script::script_module::ModuleContext as net_traits::FetchResponseListener>::process_response_eof ()
#7546 0x000055555993b474 in <net_traits::FetchResponseMsg as net_traits::Action<T>>::process ()
#7547 0x000055555960011a in <script::network_listener::ListenerTask<A,Listener> as script::task::TaskOnce>::run_once ()
#7548 0x0000555558f9ad2b in <T as script::task::TaskBox>::run_box ()
#7549 0x000055555942f0a0 in script::script_thread::ScriptThread::handle_msg_from_script ()
#7550 0x00005555594271bf in script::script_thread::ScriptThread::handle_msgs::{{closure}} ()
#7551 0x0000555559423f04 in script::script_thread::ScriptThread::handle_msgs ()
#7552 0x000055555941de80 in script::script_thread::ScriptThread::start ()
#7553 0x0000555558f5b8ff in profile_traits::mem::ProfilerChan::run_with_memory_reporting ()
#7554 0x0000555558fe2ee6 in std::sys_common::backtrace::__rust_begin_short_backtrace ()
#7555 0x0000555558fe84a2 in core::ops::function::FnOnce::call_once{{vtable.shim}} ()
#7556 0x000055555bc07075 in alloc::boxed::{impl#47}::call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global> () at library/alloc/src/boxed.rs:2007
#7557 alloc::boxed::{impl#47}::call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global> () at library/alloc/src/boxed.rs:2007
#7558 std::sys::unix::thread::{impl#2}::new::thread_start () at library/std/src/sys/unix/thread.rs:108
#7559 0x00007ffff6c97b5a in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#7560 0x00007ffff6d285fc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
  ▶ TIMEOUT [expected ERROR] /_webgpu/webgpu/cts.https.html?q=webgpu:shader,execution,expression,call,builtin,dot:f32_vec4:*


Ran 1 tests finished in 9.4 seconds.
  • 0 ran as expected. 0 tests skipped.
  • 1 tests timed out unexpectedly

Tests with unexpected results:
  ▶ TIMEOUT [expected ERROR] /_webgpu/webgpu/cts.https.html?q=webgpu:shader,execution,expression,call,builtin,dot:f32_vec4:*
```

### PR DESCRIPTION
**Pull request by Gae24**
Rewrite module script fetching logic to follow current spec.

Testing: Covered by existing wpt tests
Fixes: #31397

### CODE REVIEW

File: components/script/module_loading.rs [hunk 1]
```diff
@@ -0,0 +1,634 @@
...
+
+/// <https://tc39.es/ecma262/#graphloadingstate-record>
+// FIXME
+#[cfg_attr(crown, allow(crown::unrooted_must_root))]
+struct GraphLoadingState {
+    promise: Rc<Promise>,
+    is_loading: Cell<bool>,
+    pending_modules_count: Cell<u32>,
+    visited: RefCell<Vec<ModuleObject>>,
+}
```
Comment (Gae24) [inline components/script/module_loading.rs]: I need to implement this step:

> Step 5. If moduleMap[(url, moduleType)] is "fetching", wait in parallel until that entry's value changes, then queue a task on the networking task source to proceed with running the following steps.
> Step 6. If moduleMap[(url, moduleType)] exists, run onComplete given moduleMap[(url, moduleType)], and return.

which can be done by running the onComplete steps inside `process_response_eof`, but requires `GraphLoadingState` to be Send.
Another way would be to wait and implement step 5 with `NonSendTaskBox`, otherwise wrap `GraphLoadingState` with `Trusted` or maybe move it inside `GlobalScope`.

File: components/script/module_loading.rs [hunk 2]
```diff
@@ -0,0 +1,704 @@
...
+) {
+    // Step 1. If result is a normal completion, then
+    if let Ok(ref module) = result {
+        if let Some(private_data) = unsafe { module_script_from_reference_private(&referrer) } {
+            let mut loaded_modules = private_data.loaded_modules.borrow_mut();
+
+            // a. If referrer.[[LoadedModules]] contains a LoadedModuleRequest Record record such that
+            // ModuleRequestsEqual(record, moduleRequest) is true, then
+            loaded_modules
+                .get(&module_request_specifier)
```
Comment (Gae24) [inline components/script/module_loading.rs]: Currently crashing here with:
`unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed isize::MAX`

Comment (Gae24) [reply components/script/module_loading.rs]: it was a rooting error, fixed it.

**Comment by Gae24** [comment]
There are still a couple of failures, but I will look into dynamic imports.

**Comment by jdm** [comment]
That's super exciting!

**Comment by Gae24** [comment]
Let's see how it goes.

**Comment by TimvdLippe** [comment]
I saw your comment in #31397. Could it be that the implementation in mozjs itself is wrong? If Firefox fails the exact same tests implementing the same spec, that seems the most plausible scenario.

**Comment by Gae24** [comment]
> I saw your comment in #31397. Could it be that the implementation in mozjs itself is wrong? If Firefox fails the exact same tests implementing the same spec, that seems the most plausible scenario.

Yeah, I suppose so. Got failures down to three, and the substeps that fail are exactly the same ones of Firefox.

**Comment by Gae24** [comment]
This pr is already pretty big. 
More changes will come afterward.

**Comment by sagudev** [comment]
This PR is too much in the event loop for me to review.

File: components/script/script_module.rs [hunk 3]
```diff
@@ -198,13 +213,18 @@ pub(crate) struct ModuleTree {
...
+    #[ignore_malloc_size_of = "mozjs"]
     rethrow_error: DomRefCell<Option<RethrowError>>,
     #[no_trace]
     network_error: DomRefCell<Option<NetworkError>>,
     // A promise for owners to execute when the module tree
     // is finished
     #[conditional_malloc_size_of]
     promise: DomRefCell<Option<Rc<Promise>>>,
+    #[no_trace]
+    #[ignore_malloc_size_of = "mozjs"]
```
Comment (TimvdLippe) [inline components/script/script_module.rs]: Nit: we should be able to malloc these types

File: components/script/module_loading.rs [hunk 4]
```diff
@@ -0,0 +1,567 @@
...
+    pub(crate) fetch_client: ModuleOwner,
+}
+
+/// <https://tc39.es/ecma262/#graphloadingstate-record>
+pub(crate) struct GraphLoadingState {
+    promise: Rc<Promise>,
+    is_loading: Cell<bool>,
+    pending_modules_count: Cell<u32>,
+    visited: RefCell<HashSet<ServoUrl>>,
+    load_state: Option<Rc<LoadState>>,
```
Comment (TimvdLippe) [inline components/script/module_loading.rs:78]: Can you add in Rustdoc which fields these are? It took me a while to figure out that `load_state` is actually `HostDefined`. For example:

```suggestion
    /// `[[HostDefined]]`
    load_state: Option<Rc<LoadState>>,
```

File: components/script/module_loading.rs [hunk 5]
```diff
@@ -0,0 +1,567 @@
...
+}
+
+/// <https://tc39.es/ecma262/#sec-LoadRequestedModules>
+pub(crate) fn LoadRequestedModules(
+    global: &GlobalScope,
+    module: Rc<ModuleTree>,
+    load_state: Option<Rc<LoadState>>,
+) -> Rc<Promise> {
+    // Step 1. If hostDefined is not present, let hostDefined be empty.
```
Comment (TimvdLippe) [inline components/script/module_loading.rs:87]: If we are not implementing a step, please add a comment why

```suggestion
    // Step 1. If hostDefined is not present, let hostDefined be empty.
    //
    // Not required, since we implement it as an `Option`
```

File: components/script/module_loading.rs [hunk 6]
```diff
@@ -0,0 +1,567 @@
...
+        .borrow()
+        .as_ref()
+        .map(|module| module.handle())
+        .unwrap();
+
+    let module_url = module.get_url();
+    let visited_contains_module = state.visited.borrow().contains(&module_url);
+
+    // Step 2. If module is a Cyclic Module Record, module.[[Status]] is new, and state.[[Visited]] does not contain module, then
+    if unsafe { IsCyclicModule(module_handle.get()) } && !visited_contains_module {
```
Comment (TimvdLippe) [inline components/script/module_loading.rs:134]: I don't think this implements the `module.[[Status]] is new` check, does it?

File: components/script/module_loading.rs [hunk 7]
```diff
@@ -0,0 +1,567 @@
+/* This Source Code Form is subject to the terms of the Mozilla Public
+ * License, v. 2.0. If a copy of the MPL was not distributed with this
+ * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
+
+//! An implementation of ecma262's [LoadRequestedModules](https://tc39.es/ecma262/#sec-LoadRequestedModules)
+//! Partly inspired by mozjs implementation. Due to the inability to access ModuleObject internals (eg. ModuleRequest records),
```
Comment (jdm) [inline components/script/module_loading.rs]: Can we link the the mozjs implementation?

File: components/script/module_loading.rs [hunk 8]
```diff
@@ -0,0 +1,567 @@
...
+        // d. For each ModuleRequest Record request of module.[[RequestedModules]], do
+        for index in 0..requested_modules_count {
+            // i. If AllImportAttributesSupported(request.[[Attributes]]) is false, then
+            // Note: Gecko will call hasFirstUnsupportedAttributeKey on each module request,
+            // GetRequestedModuleSpecifier will do it for us.
+            let jsstr = unsafe { GetRequestedModuleSpecifier(*cx, module_handle, index) };
+
+            if jsstr.is_null() {
+                // 1. Let error be ThrowCompletion(a newly created SyntaxError object).
+                let error = RethrowError::from_pending_exception(cx);
```
Comment (TimvdLippe) [inline components/script/module_loading.rs:156]: Since the spec text mentions a `SyntaxError` and some of the WPT failures relate to that, could it be that we should be setting a `SyntaxError` here instead? Or is that handled by mozjs?

File: components/script/module_loading.rs [hunk 9]
```diff
@@ -0,0 +1,567 @@
...
+
+                // ii. Else if module.[[LoadedModules]] contains a LoadedModuleRequest Record record
+                // such that ModuleRequestsEqual(record, request) is true, then
+                let loaded_module = module.find_descendant_inside_module_map(global, &specifier);
+
+                match loaded_module {
+                    // 1. Perform InnerModuleLoading(state, record.[[Module]]).
+                    Some(module) => InnerModuleLoading(global, state, module),
+                    // 1. Perform HostLoadImportedModule(module, request, state.[[HostDefined]], state).
+                    None => {
```
Comment (TimvdLippe) [inline components/script/module_loading.rs]: To make it a bit easier why there are two `1.1 and where the `Else` is

```suggestion
                    // iii. Else,
                    None => {
                        // 1. Perform HostLoadImportedModule(module, request, state.[[HostDefined]], state).
```

File: components/script/module_loading.rs [hunk 10]
```diff
@@ -0,0 +1,567 @@
...
+pub(crate) struct GraphLoadingState {
+    promise: Rc<Promise>,
+    is_loading: Cell<bool>,
+    pending_modules_count: Cell<u32>,
+    visited: RefCell<HashSet<ServoUrl>>,
+    load_state: Option<Rc<LoadState>>,
+}
+
+/// <https://tc39.es/ecma262/#sec-LoadRequestedModules>
+pub(crate) fn LoadRequestedModules(
```
Comment (jdm) [inline components/script/module_loading.rs]:
```suggestion
pub(crate) fn load_requested_modules(
```

File: components/script/module_loading.rs [hunk 11]
```diff
@@ -0,0 +1,567 @@
...
+    let pending_modules_count = state.pending_modules_count.get();
+    state.pending_modules_count.set(pending_modules_count - 1);
+
+    // Step 5. If state.[[PendingModulesCount]] = 0, then
+    if state.pending_modules_count.get() == 0 {
+        // a. Set state.[[IsLoading]] to false.
+        state.is_loading.set(false);
+
+        // b. For each Cyclic Module Record loaded of state.[[Visited]], do
+        // i. If loaded.[[Status]] is new, set loaded.[[Status]] to unlinked.
```
Comment (TimvdLippe) [inline components/script/module_loading.rs:209]: Why are these steps not implemented? Please add a comment explaining why, or implement them

File: components/script/module_loading.rs [hunk 12]
```diff
@@ -0,0 +1,567 @@
...
+
+    // Step 4. Perform InnerModuleLoading(state, module).
+    InnerModuleLoading(global, &Rc::new(state), module);
+
+    // Step 5. Return pc.[[Promise]].
+    promise
+}
+
+/// <https://tc39.es/ecma262/#sec-InnerModuleLoading>
+fn InnerModuleLoading(global: &GlobalScope, state: &Rc<GraphLoadingState>, module: Rc<ModuleTree>) {
```
Comment (jdm) [inline components/script/module_loading.rs]:
```suggestion
fn inner_module_loading(global: &GlobalScope, state: &Rc<GraphLoadingState>, module: Rc<ModuleTree>) {
```

File: components/script/module_loading.rs [hunk 13]
```diff
@@ -0,0 +1,567 @@
...
+    payload: Payload,
+    result: Result<Rc<ModuleTree>, RethrowError>,
+) {
+    match payload {
+        // Step 2. If payload is a GraphLoadingState Record, then
+        Payload::GraphRecord(state) => {
+            let module_tree =
+                referrer_module.expect("Module must not be None in non dynamic imports");
+
+            // Step 1. If result is a normal completion, then
```
Comment (TimvdLippe) [inline components/script/module_loading.rs:264]: Why is step 1.b. not implemented? Please do add the spec text at the relevant point and explain why it is skipped

File: components/script/module_loading.rs [hunk 14]
```diff
@@ -0,0 +1,567 @@
...
+    // Step 6.1. Set referencingScript to referrer.[[HostDefined]].
+    let referencing_script = unsafe { module_script_from_reference_private(&referrer) };
+
+    // Step 6. If referrer is a Script Record or a Cyclic Module Record, then:
+    let (original_fetch_options, fetch_referrer) = match referencing_script {
+        Some(module) => (
+            // Step 6.4. Set originalFetchOptions to referencingScript's fetch options.
+            module.options.clone(),
+            // Step 6.3. Set fetchReferrer to referencingScript's base URL.
+            Referrer::ReferrerUrl(module.base_url.clone()),
```
Comment (TimvdLippe) [inline components/script/module_loading.rs:431]: Step 6.2. appears to be missing

File: components/script/module_loading.rs [hunk 15]
```diff
@@ -0,0 +1,567 @@
...
+    // Step 13. If loadState is not undefined, then:
+    let (destination, fetch_client) = match load_state.as_ref() {
+        // Step 13.1. Set destination to loadState.[[Destination]].
+        // Step 13.2. Set fetchClient to loadState.[[FetchClient]].
+        Some(load_state) => (load_state.destination, load_state.fetch_client.clone()),
+        None => (
+            Destination::Script,
+            ModuleOwner::new_dynamic(&global_scope, CanGc::note()),
+        ),
+    };
```
Comment (TimvdLippe) [inline components/script/module_loading.rs]: Nit: move these to lines 479 and 480

```suggestion
    // Step 13. If loadState is not undefined, then:
    let (destination, fetch_client) = match load_state.as_ref() {
        // Step 13.1. Set destination to loadState.[[Destination]].
        // Step 13.2. Set fetchClient to loadState.[[FetchClient]].
        Some(load_state) => (load_state.destination, load_state.fetch_client.clone()),
        None => (
            // Step 11. Let destination be "script".
            Destination::Script,
            // Step 12. Let fetchClient be settingsObject.
            ModuleOwner::new_dynamic(&global_scope, CanGc::note()),
        ),
    };
```

**Review by TimvdLippe — CHANGES_REQUESTED** [review]
I did a first pass to check if spec steps are present and understandable. Most of it already looks very good, some nits.

Since I am not the expert in actual mozjs integration, I will leave such a review to folks like @jdm

File: components/script/module_loading.rs (hunk 13 above)
Comment (Gae24) [reply components/script/module_loading.rs:264]: Actually, I ended up moving these steps inside `insert_module_dependency`, so I should move step 1.a. comment inside it, too.

File: components/script/module_loading.rs (hunk 11 above)
Comment (Gae24) [reply components/script/module_loading.rs:209]: `ModuleStatus` is handled internally by mozjs.
Furthermore, the release that we use doesn't have `[[Status]]` New but defaults to Unlinked.

File: components/script/script_module.rs (hunk 3 above)
Comment (Gae24) [reply components/script/script_module.rs]: Oh yeah, leftover from an older implementation.

File: components/script/module_loading.rs (hunk 8 above)
Comment (Gae24) [reply components/script/module_loading.rs:156]: I've actually checked if this was the culprit in some tests; I don't think I've done it for `error-type-1.html`, will check.
Regarding `choice-of-error-1.html`, it expects two different objects while we provide the same `SyntaxError` object.

File: components/script/module_loading.rs [hunk 16]
```diff
@@ -0,0 +1,567 @@
...
+
+        // c. Perform ! Call(state.[[PromiseCapability]].[[Resolve]], undefined, « undefined »).
+        state.promise.resolve_native(&(), CanGc::note());
+    }
+
+    // Step 6. Return unused.
+}
+
+/// <https://tc39.es/ecma262/#sec-ContinueModuleLoading>
+fn ContinueModuleLoading(
```
Comment (jdm) [inline components/script/module_loading.rs]:
```suggestion
fn continue_module_loading(
```

File: components/script/module_loading.rs [hunk 17]
```diff
@@ -0,0 +1,567 @@
...
+        // Step 3. Else,
+        // a. Perform ContinueDynamicImport(payload, result).
+        Payload::PromiseRecord(promise) => ContinueDynamicImport(global, promise, result),
+    }
+
+    // 4. Return unused.
+}
+
+/// <https://tc39.es/ecma262/#sec-ContinueDynamicImport>
+fn ContinueDynamicImport(
```
Comment (jdm) [inline components/script/module_loading.rs]:
```suggestion
fn continue_dynamic_import(
```

File: components/script/module_loading.rs (hunk 14 above)
Comment (Gae24) [reply components/script/module_loading.rs:431]: Do i simply add the step comment? The `GlobalScope` should be the same one, right?

File: components/script/module_loading.rs (hunk 8 above)
Comment (Gae24) [reply components/script/module_loading.rs:156]: If we ignore `loadState.[[ErrorToRethrow]]` inside `loading_promise_rejection`, `error-type-1.html` will pass but more tests will fail.
There is an issue open at [wpt repo](https://github.com/web-platform-tests/wpt/issues/53447)

File: components/script/script_module.rs [hunk 18]
```diff
@@ -1716,114 +1264,265 @@ struct DynamicModule {
...
     url: ServoUrl,
-    visited_urls: HashSet<ServoUrl>,
-    destination: Destination,
+    script_id: ScriptId,
     options: ScriptFetchOptions,
-    parent_identity: Option<ModuleIdentity>,
-    top_level_module_fetch: bool,
-    dynamic_module: Option<RootedTraceableBox<DynamicModule>>,
-    introduction_type: Option<&'static CStr>,
+    line_number: u64,
```
Comment (jdm) [inline components/script/script_module.rs]:
```suggestion
    line_number: u32,
```

File: components/script/script_module.rs [hunk 19]
```diff
@@ -1716,114 +1264,265 @@ struct DynamicModule {
...
-        let module_map = global.get_module_map().borrow();
+    // Step 1. Let script be the result of creating a JavaScript module script using sourceText, settingsObject, baseURL, and options.
+    let module_tree = Rc::new(ModuleTree::new(url.clone(), false, HashSet::new()));
+    module_tree.compile_module_script(
+        owner.clone(),
+        module_script_text,
+        &url,
+        options,
+        true,
+        line_number as u32,
```
Comment (jdm) [inline components/script/script_module.rs]:
```suggestion
        line_number,
```

File: components/script/script_module.rs (hunk 18 above)
Comment (jdm) [reply components/script/script_module.rs]: If we're just going to cast it, let's make the caller deal with that.

File: components/script/script_module.rs [hunk 20]
```diff
@@ -1716,114 +1264,265 @@ struct DynamicModule {
...
+    // Step 9. Set request's destination to the result of running the fetch destination from module type steps given destination and moduleType.
+
+    // Step 10. If destination is "worker", "sharedworker", or "serviceworker", and isTopLevel is true,
+    // then set request's mode to "same-origin".
+    let mode = match destination {
+        Destination::Worker | Destination::SharedWorker if is_top_level => RequestMode::SameOrigin,
+        _ => RequestMode::CorsMode,
+    };
+
+    // Step 11. Set request's initiator type to "script".
```
Comment (jdm) [inline components/script/script_module.rs]:
```suggestion
    // TODO Step 11. Set request's initiator type to "script".
```

File: components/script/module_loading.rs [hunk 21]
```diff
@@ -0,0 +1,567 @@
...
+        })),
+        CanGc::note(),
+    );
+    load_promise.append_native_handler(&handler, comp, CanGc::note());
+
+    // Step 9. Return unused.
+}
+
+/// <https://html.spec.whatwg.org/multipage/#hostloadimportedmodule>
+pub(crate) fn HostLoadImportedModule(
```
Comment (jdm) [inline components/script/module_loading.rs]:
```suggestion
pub(crate) fn host_load_imported_module(
```

**Review by jdm — APPROVED** [review]
This is great work! I only have nits; it's so much clearer to read this code now with the updated specification steps. Thank you!

File: components/script/module_loading.rs (hunk 14 above)
Comment (TimvdLippe) [reply components/script/module_loading.rs:431]: Tbh, I don't know. You can also add a step comment stating that it is the same

File: components/script/module_loading.rs (hunk 8 above)
Comment (TimvdLippe) [reply components/script/module_loading.rs:156]: If you can provide guidance to them, feel free to do so. Seems like they are eager to learn from implementers what they think makes the most sense

**Review by TimvdLippe — APPROVED** [review]
This is amazing work! Thanks a lot for contributing. Feel free to push other fixes you come up with in follow-up PRs.

**Comment by Gae24** [comment]
Maybe build failed due to #41861?

**Comment by pylbrecht** [comment]
Very impressive work, @Gae24! :pray:
