### PR TITLE
canvas: prevent unwrap on offscreen canvas

### LINKED ISSUE #37415: panic: called `Option::unwrap()` on a `None` value at components/script/canvas_context.rs:157
This is very similar to #36846 but it is not fixed in the latest nightly. cc @simonwuelker

Minimal testcase:

```html
<!DOCTYPE html>
<canvas id="canvas"></canvas>
<script>
  canvas.transferControlToOffscreen();
  canvas.toBlob(_ => {});
</script>
```

System: Linux
Version: Servo 0.0.1-73c286423
Command: `./servo/servo`

```
called `Option::unwrap()` on a `None` value (thread Script(1,1), at components/script/canvas_context.rs:157)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::panic
   8: core::option::unwrap_failed
   9: script::dom::htmlcanvaselement::HTMLCanvasElement::origin_is_clean
  10: script_bindings::codegen::GenericBindings::HTMLCanvasElementBinding::HTMLCanvasElement_Binding::toBlob::{{closure}}
  11: mozjs::panic::wrap_panic
  12: script_bindings::codegen::GenericBindings::HTMLCanvasElementBinding::HTMLCanvasElement_Binding::toBlob
  13: CallJitMethodOp
  14: script_bindings::utils::generic_call
  15: script_bindings::utils::generic_method
  16: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  17: _ZN2js9InterpretEP9JSContextRNS_8RunStateE
  18: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  19: _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEENS3_IP8JSObjectEENS2_13MutableHandleINS2_5ValueEEE
  20: _Z16JS_ExecuteScriptP9JSContextN2JS6HandleIP8JSScriptEENS1_13MutableHandleINS1_5ValueEEE
  21: script::dom::globalscope::GlobalScope::evaluate_script_on_global_with_result
  22: script::dom::htmlscriptelement::HTMLScriptElement::execute
  23: script::dom::htmlscriptelement::HTMLScriptElement::prepare
  24: script::dom::servoparser::ServoParser::parse_sync
  25: <script::dom::servoparser::ParserContext as net_traits::FetchResponseListener>::process_response_chunk
  26: script::script_thread::ScriptThread::handle_msg_from_script
  27: script::script_thread::ScriptThread::handle_msgs::{{closure}}
  28: script::script_thread::ScriptThread::handle_msgs
  29: std::sys::backtrace::__rust_begin_short_backtrace
  30: core::ops::function::FnOnce::call_once{{vtable.shim}}
  31: std::sys::pal::unix::thread::Thread::new::thread_start
  32: start_thread
             at ./nptl/pthread_create.c:447:8
  33: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
```

### PR DESCRIPTION
**Pull request by wusyong**
Remove all unwrap usage on offscreen canvas to prevent panic.

Testing: `tests/wpt/tests/html/canvas/offscreen/manual/the-offscreen-canvas/offscreencanvas.transfercontrol.to.offscreen-crash.html`
Fixes: #37415

### CODE REVIEW

File: components/script/canvas_context.rs [hunk 1]
```diff
@@ -112,9 +118,15 @@ impl CanvasContext for RenderingContext {
...
-    fn canvas(&self) -> HTMLCanvasElementOrOffscreenCanvas {
+    fn canvas(&self) -> Option<HTMLCanvasElementOrOffscreenCanvas> {
         match self {
-            RenderingContext::Placeholder(context) => (*context.context().unwrap()).canvas(),
+            RenderingContext::Placeholder(offscreen_canvas) => {
+                if let Some(context) = offscreen_canvas.context() {
+                    context.canvas()
+                } else {
+                    None
+                }
```
Comment (mrobinson) [inline components/script/canvas_context.rs]:
```suggestion
                offscreen_canvas.context()?.canvas() 
```

File: components/script/canvas_context.rs [hunk 2]
```diff
@@ -140,8 +152,12 @@ impl CanvasContext for RenderingContext {
...
     fn get_image_data(&self) -> Option<Snapshot> {
         match self {
-            RenderingContext::Placeholder(context) => {
-                (*context.context().unwrap()).get_image_data()
+            RenderingContext::Placeholder(offscreen_canvas) => {
+                if let Some(context) = offscreen_canvas.context() {
+                    context.get_image_data()
+                } else {
+                    None
+                }
```
Comment (mrobinson) [inline components/script/canvas_context.rs]:
```suggestion
                offscreen_canvas.context()?.get_image_data()
```

File: components/script/canvas_context.rs [hunk 3]
```diff
@@ -153,8 +169,12 @@ impl CanvasContext for RenderingContext {
...
     fn origin_is_clean(&self) -> bool {
         match self {
-            RenderingContext::Placeholder(context) => {
-                (*context.context().unwrap()).origin_is_clean()
+            RenderingContext::Placeholder(offscreen_canvas) => {
+                if let Some(context) = offscreen_canvas.context() {
+                    context.origin_is_clean()
+                } else {
+                    true
+                }
```
Comment (mrobinson) [inline components/script/canvas_context.rs]:
```suggestion
            RenderingContext::Placeholder(offscreen_canvas) => {
                offscreen_canvas.context().is_none_or(|context| context.origin_is_clean())
```

File: components/script/canvas_context.rs [hunk 4]
```diff
@@ -49,11 +49,16 @@ pub(crate) trait CanvasContext {
     }
 
     fn size(&self) -> Size2D<u32> {
-        self.canvas().size()
+        if let Some(canvas) = self.canvas() {
+            canvas.size()
+        } else {
+            Size2D::default()
+        }
```
Comment (mrobinson) [inline components/script/canvas_context.rs]:
```suggestion
        self.canvas().map(HTMLCanvasElementOrOffscreenCanvas::size).unwrap_or_default()
```

File: components/script/canvas_context.rs [hunk 5]
```diff
@@ -62,12 +67,13 @@ pub(crate) trait CanvasContext {
 
     fn onscreen(&self) -> bool {
         match self.canvas() {
```
Comment (mrobinson) [inline components/script/canvas_context.rs]:
```suggestion
    fn onscreen(&self) -> bool {
        let Some(canvas) = self.canvas() else {
            return false;
        }
        
        match canvas {
```

File: components/script/canvas_context.rs [hunk 6]
```diff
@@ -166,7 +186,13 @@ impl CanvasContext for RenderingContext {
...
     fn size(&self) -> Size2D<u32> {
         match self {
-            RenderingContext::Placeholder(context) => (*context.context().unwrap()).size(),
+            RenderingContext::Placeholder(offscreen_canvas) => {
+                if let Some(context) = offscreen_canvas.context() {
+                    context.size()
+                } else {
+                    Size2D::default()
+                }
+            },
```
Comment (mrobinson) [inline components/script/canvas_context.rs]: Please use `map` and `unwrap_or_default` here as well.

File: components/script/canvas_context.rs [hunk 7]
```diff
@@ -201,7 +233,13 @@ impl CanvasContext for RenderingContext {
 
     fn onscreen(&self) -> bool {
         match self {
-            RenderingContext::Placeholder(context) => (*context.context().unwrap()).onscreen(),
+            RenderingContext::Placeholder(offscreen_canvas) => {
+                if let Some(context) = offscreen_canvas.context() {
+                    context.onscreen()
+                } else {
+                    false
+                }
```
Comment (mrobinson) [inline components/script/canvas_context.rs]:
```suggestion
                offscreen_canvas.context().is_some_and(|context| context.onscreen()),
```

Also, when is an offscreen canvas onscreen?

**Review by mrobinson — CHANGES_REQUESTED** [review]
Looks good to me, but I have a few cleanups to suggest:

File: components/script/canvas_context.rs (hunk 7 above)
Comment (wusyong) [reply components/script/canvas_context.rs]: It will go through default `CanvasContext::on_screen` and return false by `HTMLCanvasElementOrOffscreenCanvas::OffscreenCanvas(_) => false,` eventually.

File: tests/wpt/mozilla/tests/mozilla/canvas/transfer-control-to-offscreencanvas-then-to-blob-crash.html [hunk 8]
```diff
@@ -0,0 +1,6 @@
+<!DOCTYPE html>
+<canvas id="canvas"></canvas>
+<script>
+  canvas.transferControlToOffscreen();
+  canvas.toBlob(_ => {});
+</script>
```
Comment (mrobinson) [inline tests/wpt/mozilla/tests/mozilla/canvas/transfer-control-to-offscreencanvas-then-to-blob-crash.html]: Sorry, I missed this before. I think this should be added to the WPT instead of our internal tests as it doesn't use any internal APIs. It's okay to add crashtests that only trigger engine-specific issues.

**Review by mrobinson — DISMISSED** [review]

File: tests/wpt/tests/html/canvas/offscreen/manual/the-offscreen-canvas/offscreencanvas.transfercontrol.to.offscreen.nocrash.html [hunk 9]
```diff
@@ -0,0 +1,12 @@
+<title>Transfer Canvas without Context</title>
```
Comment (jdm) [inline tests/wpt/tests/html/canvas/offscreen/manual/the-offscreen-canvas/offscreencanvas.transfercontrol.to.offscreen.nocrash.html]: Instead of making this a testharness test (since we don't make any assertions about the results), we can still make this a crashtest: https://web-platform-tests.org/writing-tests/crashtest.html#crashtest-tests . It will require renaming the test file.

**Review by jdm — APPROVED** [review]
