### PR TITLE
canvas: Don't do operations on paths with uninvertible transforms

### LINKED ISSUE #36995: anic: should have called ensure_path (thread Canvas, at components/canvas/canvas_data.rs:143)
Minimal testcase:

```html
<!DOCTYPE html>
<script>
  let context = document.createElement("canvas").getContext("2d");
  context.moveTo(0, 0);
  context.setTransform(4, 2, 6, 3, 0, 0); // non-invertible (4 * 3 - 6 * 2 = 0)
  context.fill("nonzero");
</script>
```

System: Linux
Version: Servo 0.0.1-bee491b0f

```
should have called ensure_path (thread Canvas, at components/canvas/canvas_data.rs:143)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: canvas::canvas_data::CanvasData<B>::path
   8: canvas::canvas_paint_thread::CanvasPaintThread::process_canvas_2d_message
   9: std::sys::backtrace::__rust_begin_short_backtrace
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: std::sys::pal::unix::thread::Thread::new::thread_start
  12: start_thread
             at ./nptl/pthread_create.c:447:8
  13: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
```

### PR DESCRIPTION
**Pull request by mrobinson**
When the path is created with an uninvertible transform, don't do any
path-based operations. Now `ensure_path()` returns a `Path` object and
this change adds early returns which prevent trying to use it.

Testing: This change adds a WPT crash test.
Fixes #36995.

### CODE REVIEW

File: components/canvas/canvas_data.rs [hunk 1]
```diff
@@ -843,7 +825,9 @@ impl<'a, B: Backend> CanvasData<'a, B> {
         self.path_builder().close();
     }
 
-    fn ensure_path(&mut self) {
+    /// Turn the [`Self::path_state`] into a user-space poath, returning `None` if the
```
Comment (simonwuelker) [inline components/canvas/canvas_data.rs]: `poath` -> `path`

Comment (mrobinson) [reply components/canvas/canvas_data.rs]: What a funny typo. Fixed. :)

**Review by simonwuelker — APPROVED** [review]
