### PR TITLE
html: Track the script/UA initiated media `seek` request

### LINKED ISSUE #37057: Media: `<video>` emit "seeked" event after the video is loaded when no seek is performed.
**Describe the bug:**
Currently, when first load the webpage that have mp4 video, servo's `<video>` tag will emit `seeked` even when no seek action is performed.

**To Reproduce:**
Minimum Test Case:
```
<!DOCTYPE html>
<html lang="en">
<body>
    <video src="mov_bbb.mp4"></video>
    <script>
        let video = document.querySelector("video");
        video.addEventListener("seeked", () => {
            console.log("Video seeked");
        });
    </script>
</body>
</html>
```
| Chromium | Servo |
|-----------------|----------|
|                     | Video seeked| 

**Step to Reproduce**
build servo, open the above html page, and do nothing. 

Note: currently servo rely on http range request to `seek`, for http server that does not support http range request, Gstreamer will emit error.

### PR DESCRIPTION
**Pull request by tharkum**
The low-level media `seek` request could be initiated by script (DOM method call or setting of an IDL attribute), by the user agent (seeking data) or by the media engine itself (e.g. gst_play_set_rate()).
And to distinguish between them we will use the latest seek position (in seconds) to be able abort processing the `seek` algorithm steps (13-17) for a `seek` request initiated by the media engine.

See https://html.spec.whatwg.org/multipage/#dom-media-seek

If the `seeking` is in progress, any callback which affects the current playback position (`position changed`, `end of the playback`) shouldn't be processed (event marshalling over IPC router is non-state conditional).

Testing: Regression in the following test causes by gstreamer issue when the `gst_play_set_rate()` overrides the latest seek requested position unconditionally and the user agent receives the `seek completion` event with the unexpected seek position (0.5+ instead of 0.0).
- html/semantics/embedded-content/media-elements/preserves-pitch.html

See https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/4762

Fixes: https://github.com/servo/servo/issues/37057

### CODE REVIEW

File: components/script/dom/html/htmlmediaelement.rs [hunk 1]
```diff
@@ -548,6 +548,7 @@ pub(crate) struct HTMLMediaElement {
     volume: Cell<f64>,
     /// <https://html.spec.whatwg.org/multipage/#dom-media-seeking>
     seeking: Cell<bool>,
+    current_seek_position: Cell<f64>,
```
Comment (mrobinson) [inline components/script/dom/html/htmlmediaelement.rs:554]: Do you mind adding rustdoc to this field? For instance what are the units here?

File: components/script/dom/html/htmlmediaelement.rs [hunk 2]
```diff
@@ -2009,11 +2014,13 @@ impl HTMLMediaElement {
         self.current_playback_position.set(time);
 
         if let Some(ref player) = *self.player.borrow() {
-            if let Err(e) = player.lock().unwrap().seek(time) {
-                error!("Seek error {:?}", e);
+            if let Err(err) = player.lock().unwrap().seek(time) {
+                error!("Seek error {:?}", err);
```
Comment (mrobinson) [inline components/script/dom/html/htmlmediaelement.rs]: Nit:

```suggestion
            if let Err(error) = player.lock().unwrap().seek(time) {
                error!("Seek error {error:?}");
```

File: components/script/dom/html/htmlmediaelement.rs [hunk 3]
```diff
@@ -2546,22 +2561,27 @@ impl HTMLMediaElement {
...
+        // queue a media element task given the media element to fire an event named durationchange
+        // at the media element.
+        // <https://html.spec.whatwg.org/multipage/#offsets-into-the-media-resource:media-resource-22>
         self.queue_media_element_task_to_fire_event(atom!("durationchange"));
+
+        // If the duration is changed such that the current playback position ends up being greater
+        // than the time of the end of the media resource, then the user agent must also seek to the
+        // time of the end of the media resource.
+        if self.current_playback_position.get() > duration {
+            self.seek(duration, /* approximate_for_speed */ false);
```
Comment (mrobinson) [inline components/script/dom/html/htmlmediaelement.rs:2585]: Nit: Please put the name of the variable after the value.

File: components/script/dom/html/htmlmediaelement.rs [hunk 4]
```diff
@@ -548,6 +548,7 @@ pub(crate) struct HTMLMediaElement {
     volume: Cell<f64>,
     /// <https://html.spec.whatwg.org/multipage/#dom-media-seeking>
```
Comment (mrobinson) [inline components/script/dom/html/htmlmediaelement.rs:549]: Maybe clarify here what kinds of situations that seeking happens where this is also false? I understand that this is when triggered by the media engine. I think it's worth a rustdoc explanation.

**Review by mrobinson — CHANGES_REQUESTED** [review]
Looks good, my main concern here is that this is a tricky issue and I think we should have a bit of a rustdoc explanation of it. This GStreamer behavior is extremely non-obvious.

File: components/script/dom/html/htmlmediaelement.rs (hunk 3 above)
Comment (tharkum) [reply components/script/dom/html/htmlmediaelement.rs:2585]: Other `seek` calls also use `/* approximate_for_speed */ value` ordering, so I guess need to change everywhere or do nothing or change only here... Suggestions?

File: components/script/dom/html/htmlmediaelement.rs (hunk 2 above)
Comment (tharkum) [reply components/script/dom/html/htmlmediaelement.rs]: Ok

File: components/script/dom/html/htmlmediaelement.rs (hunk 4 above)
Comment (tharkum) [reply components/script/dom/html/htmlmediaelement.rs:549]: Ok. I will add rustdoc for `seeking` and `current_seek_position` as well

File: components/script/dom/html/htmlmediaelement.rs (hunk 2 above)
Comment (tharkum) [reply components/script/dom/html/htmlmediaelement.rs]: Done

File: components/script/dom/html/htmlmediaelement.rs (hunk 1 above)
Comment (tharkum) [reply components/script/dom/html/htmlmediaelement.rs:554]: Done. Units of measurement are seconds.

File: components/script/dom/html/htmlmediaelement.rs (hunk 4 above)
Comment (tharkum) [reply components/script/dom/html/htmlmediaelement.rs:549]: Done

**Review by mrobinson — APPROVED** [review]

File: components/script/dom/html/htmlmediaelement.rs (hunk 3 above)
Comment (mrobinson) [reply components/script/dom/html/htmlmediaelement.rs:2585]: I was think just this callsite,
but this is a very minor issue.
