### PR TITLE
Use the flat tree for layout and style invalidation

### LINKED ISSUE #35727: Nested <details> elements don't update properly
The test case is this file:

```html
<!DOCTYPE html>
<html>
  <body>
    <details>
      <summary>Top Level</summary>
      <details>
        <summary>Sub Level 1</summary>
        <p>Some text about something.</p>
      </details>
      <details>
        <summary>Sub Level 2</summary>
        <p>Some text about something else.</p>
      </details>
    </details>
  </body>
</html>
```

To reproduce the issue, follow these steps:

1. tap on the `Top Level` heading -> this opens the details and shows the 2 sub level headings.
2. tap on the `Sub Level 1` heading -> nothing happens!
3. tap again twice on `Top Level` -> now the content of `Sub Level 1` appears.

cc @simonwuelker

### PR DESCRIPTION
**Pull request by simonwuelker**
Layout invalidation currently happens on the regular dom. That is incorrect and we should use the flat tree instead.

The flat tree is equivalent to the DOM, except for the following:
* Assigned slottables are children of their slots (and their slot is their parent)
* Children of shadow roots are children of their hosts (and the hosts are their parents)

For example, when an assigned slottable becomes dirty then we want to mark its assigned slot as dirty, not it's parent.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #35727
- [ ] There are no tests for these changes - I can't seem to replicate the issue with a script and to simulate "real" clicks we would need webdriver support

### CODE REVIEW

File: components/script/dom/node.rs [hunk 1]
```diff
@@ -1395,6 +1395,28 @@ impl Node {
             .slottable_data
             .manual_slot_assignment = manually_assigned_slot.map(Dom::from_ref);
     }
+
+    /// Gets the parent of this node with the layout tree
```
Comment (mrobinson) [inline components/script/dom/node.rs:1399]: What do you mean by the "layout tree" in this case?

Comment (simonwuelker) [reply components/script/dom/node.rs:1399]: The dom as it is seen by `layout_2020`.
That means that assigned slottables are children of their slots (not their parents) and shadow roots are children of their hosts.

I'm not really sure about the terminology here, feel free to suggest something better (:

Comment (simonwuelker) [reply components/script/dom/node.rs:1399]: I suppose "layout tree" incorrectly sounds like it refers to the [box tree](https://www.w3.org/TR/css-display-3/#box-tree) from CSS.

Comment (mrobinson) [reply components/script/dom/node.rs]: Is this similar to the "flat tree" concept used by Gecko? It seems reasonable to share terminology. You're right that the conflation with the trees built during layout prompted me to ask the question. Flow tree / render tree / layout trees all essentially suggest those trees.

Comment (simonwuelker) [reply components/script/dom/node.rs]: > Is this similar to the "flat tree" concept used by Gecko?

Yes it's the same concept. I've changed to the names to reflect that.

**Comment by simonwuelker** [comment]
I included a few more related changes that fix the crash on wpt.fyi (:

(Well "load" is a bit of an exaggeration, servo gets *very* busy assigning slottables to a tree. But no crash!)

**Review by mrobinson — APPROVED** [review]
