### PR TITLE
layout: Move hit testing for scrollable areas to display list construction

### LINKED ISSUE #38967: Some pages do not scroll smoothly.
**Describe the bug:**
After #38518  Some pages do not scroll smoothly.

**To Reproduce:**
page url：https://m.huaweimossel.com/#/pages/product/product?scene=10584

**Platform:**
openharmony

### PR DESCRIPTION
**Pull request by coding-joedow**
Move the construction of hit test items for scroll nodes to the display list construction stage. This way they respect the `z-index` of their originating fragments and stacking context ordering in general.

Testing: We currently do not have great testing for this as this tests the combination of hit testing of input events and scrolling at that point. The completion of WebDriver support should make this easier to test.
Fixes: #38967

### CODE REVIEW

**Comment by mrobinson** [comment]
Generally the `Testing` field should be used to describe checked-in automated tests, manual tests (`tests/html`), or describe why writing such tests is difficult.

**Comment by mrobinson** [comment]
I'm not sure this is tested by WPT as no test results have changed. I've updated the PR description to describe my understanding of the situation.

File: components/layout/display_list/mod.rs [hunk 1]
```diff
@@ -1066,6 +1053,24 @@ impl<'a> BuilderForBoxFragment<'a> {
...
+        }
+        builder.wr().push_hit_test(
+            common.clip_rect,
+            common.clip_chain_id,
+            common.spatial_id,
+            common.flags,
+            (external_scroll_node_id.0, 0), /* tag */
+        );
+    }
+
```
Comment (mrobinson) [inline components/layout/display_list/mod.rs:1076]: Should this be check if `if self.style.get_inherited_ui().pointer_events != PointerEvents::None` before adding the hit test?

**Comment by coding-joedow** [comment]
> We currently do not have great testing for this as this tests the combination of hit testing of input events and scrolling at that point. The completion of WebDriver support should make this easier to test.

Perhaps it is necessary to add T-webdriver and conduct a trial run of WebDriver tests.

File: components/layout/display_list/mod.rs (hunk 1 above)
Comment (coding-joedow) [reply components/layout/display_list/mod.rs:1076]: I'm not sure, but I tested this https://github.com/servo/servo/pull/38480#issuecomment-3213734994 and it seems to be working fine.

Comment (coding-joedow) [reply components/layout/display_list/mod.rs:1076]: I have constructed test cases for verification, and it is necessary to add it when required; I will proceed with the addition.

**Comment by yezhizhen** [comment]
The webdriver result looks normal. If you rebase, `close.py` would not fail.

Also, those flaky tests would be fixed by a PR this week.

**Review by mrobinson — APPROVED** [review]

**Comment by yezhizhen** [comment]
@coding-joedow Can you rebase and I will run the test again? Flaky should be gone now.
