### PR TITLE
webgl: out-of-bounds readPixels() fixes

### LINKED ISSUE #13901: webgl: Uninitialized data leak from ReadPixels()
From the GLES 2.0.25 spec on `glReadPixels()`:

> If any of these pixels lies outside of the window allocated to the current GL context, the values obtained for those pixels are undefined.

but from the WebGL spec:

> For any pixel lying outside the frame buffer, the corresponding destination buffer range remains untouched; see Reading Pixels Outside the Framebuffer. 

This is triggered by the `object-deletion-behaviour.html` test once `checkFramebufferStatus()` starts returning `GL_FRAMEBUFFER_COMPLETE`.

### PR DESCRIPTION
**Pull request by anholt**
Fix crashes in two WebGL readPixels() tests by adding framebuffer size validation.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13901

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14081)

### CODE REVIEW

File: components/script/dom/webglframebuffer.rs [hunk 1]
```diff
@@ -21,7 +21,7 @@ use webrender_traits::{WebGLCommand, WebGLFramebufferBindingRequest, WebGLFrameb
 #[derive(JSTraceable, Clone, HeapSizeOf)]
 enum WebGLFramebufferAttachment {
     Renderbuffer(JS<WebGLRenderbuffer>),
-    Texture(JS<WebGLTexture>),
+    Texture(JS<WebGLTexture>, i32),
```
Comment (emilio) [inline components/script/dom/webglframebuffer.rs]: A note saying this is the texture level would be nice. Alternatively:

`Texture { texture: JS<WebGLTexture>, level: i32 }`

File: components/script/dom/webglframebuffer.rs [hunk 2]
```diff
@@ -190,7 +190,7 @@ impl WebGLFramebuffer {
             // Note, from the GLES 2.0.25 spec, page 113:
             //      "If texture is zero, then textarget and level are ignored."
             Some(texture) => {
-                *binding.borrow_mut() = Some(WebGLFramebufferAttachment::Texture(JS::from_ref(texture)));
+                *binding.borrow_mut() = Some(WebGLFramebufferAttachment::Texture(JS::from_ref(texture), level));
```
Comment (emilio) [inline components/script/dom/webglframebuffer.rs]: should we move this after the level validation? Otherwise in your next patch we can't be convert it to an unsigned integer right away.

File: components/script/dom/webglframebuffer.rs [hunk 3]
```diff
@@ -135,6 +140,32 @@ impl WebGLFramebuffer {
...
         }
 
+        let mut fb_size = None;
+        for attachment in &attachments {
+            // Get the size of this attachment.
+            let size = match **attachment {
+                Some(WebGLFramebufferAttachment::Renderbuffer(ref att_rb)) => {
+                    att_rb.size()
+                }
+                Some(WebGLFramebufferAttachment::Texture(ref att_tex, ref level)) => {
```
Comment (emilio) [inline components/script/dom/webglframebuffer.rs]: nit: Binding level by value is probably ok

File: components/script/dom/webglframebuffer.rs [hunk 4]
```diff
@@ -251,7 +251,8 @@ impl WebGLFramebuffer {
         Ok(())
     }
 
-    pub fn detach_renderbuffer(&self, rb: &WebGLRenderbuffer) {
+    fn call_on_matching_renderbuffers<F>(&self, rb: &WebGLRenderbuffer, closure: F)
+        where F: Fn(&DOMRefCell<Option<WebGLFramebufferAttachment>>) {
```
Comment (emilio) [inline components/script/dom/webglframebuffer.rs]: nit: naming convention for this kind of function is `with`, like `with_matching_{renderbuffers/textures}`.

Also, when there's a `where` clause usually the opening brace goes on the next line aligned with the `fn`:

```rust
fn with_matching_renderbuffers<F>(&self, rb: &WebGLRenderbuffer, closure: F)
    where F: Fn(&DOMRefCell<Option<WebGLFramebufferAttachment>>)
{
    // ...
```

File: components/script/dom/webglframebuffer.rs [hunk 5]
```diff
@@ -267,13 +268,13 @@ impl WebGLFramebuffer {
...
-                *attachment.borrow_mut() = None;
-                self.update_status();
+                closure(attachment);
             }
         }
     }
 
-    pub fn detach_texture(&self, texture: &WebGLTexture) {
+    fn call_on_matching_textures<F>(&self, texture: &WebGLTexture, closure: F)
+        where F: Fn(&DOMRefCell<Option<WebGLFramebufferAttachment>>) {
```
Comment (emilio) [inline components/script/dom/webglframebuffer.rs]: same comment as above.

File: components/script/dom/webglframebuffer.rs (hunk 4 above)
Comment (emilio) [inline components/script/dom/webglframebuffer.rs]: Also, you can probably use `FnMut` instead of `Fn`, which would allow you to use closures that mutate other state.

File: components/script/dom/webglframebuffer.rs [hunk 6]
```diff
@@ -289,12 +290,37 @@ impl WebGLFramebuffer {
...
-                self.update_status();
+                closure(attachment);
             }
         }
     }
 
+    pub fn detach_renderbuffer(&self, rb: &WebGLRenderbuffer) {
+        self.call_on_matching_renderbuffers(rb, |att| {
+            *att.borrow_mut() = None;
+            self.update_status();
```
Comment (emilio) [inline components/script/dom/webglframebuffer.rs]: I think with the `FnMut` clause we can track here and below whether at least one has been matched and update the status only once?

**Review by emilio — APPROVED** [review]
r=me with those. Looks great, thanks!

File: components/script/dom/webglframebuffer.rs (hunk 1 above)
Comment (anholt) [inline components/script/dom/webglframebuffer.rs]: Oh, nice.  I thought the JS<> in there meant the struct would be harder than just doing that.

File: components/script/dom/webglframebuffer.rs (hunk 6 above)
Comment (anholt) [inline components/script/dom/webglframebuffer.rs]: Neat idea.  I think I'll stick with the simple version here, since you couldn't have a complete FBO with the same object attached twice anyway.

**Comment by emilio** [comment]
@bors-servo r+

Bors forgot about this apparently, huh

**Comment by jdm** [comment]
@bors-servo: retry
* #14152
