### PR TITLE
Coalesce animated image frame data into a single shared memory region

### LINKED ISSUE #36792: "index out of bounds: the len is 64 but the index is 64" when loading discord..gg
To reproduce: `./mach build && ./mach run discord.gg`

<details><summary>Backtrace</summary>

```
index out of bounds: the len is 64 but the index is 64 (thread <unnamed>, at /home/alaska/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ipc-channel-0.19.0/src/ipc.rs:562)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::panic_bounds_check
   8: <ipc_channel::ipc::IpcSharedMemory as serde::de::Deserialize>::deserialize
   9: <&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_struct
  10: <serde::de::impls::<impl serde::de::Deserialize for alloc::vec::Vec<T>>::deserialize::VecVisitor<T> as serde::de::Visitor>::visit_seq
  11: <&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_seq
  12: <&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_struct
  13: serde::de::impls::<impl serde::de::Deserialize for alloc::boxed::Box<T>>::deserialize
  14: serde::de::impls::<impl serde::de::Deserialize for alloc::sync::Arc<T>>::deserialize
  15: <&mut bincode::de::Deserializer<R,O> as serde::de::VariantAccess>::tuple_variant
  16: <net_traits::image_cache::_::<impl serde::de::Deserialize for net_traits::image_cache::ImageResponse>::deserialize::__Visitor as serde::de::Visitor>::visit_enum
  17: <&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_struct
  18: ipc_channel::ipc::IpcMessage::to
  19: ipc_channel::router::RouterProxy::add_typed_route::{{closure}}
  20: ipc_channel::router::Router::run
  21: std::sys::backtrace::__rust_begin_short_backtrace
  22: core::ops::function::FnOnce::call_once{{vtable.shim}}
  23: std::sys::pal::unix::thread::Thread::new::thread_start
  24: start_thread
  25: __clone3
```

### PR DESCRIPTION
**Pull request by simonwuelker**
This makes servo use less file descriptors for animated images and avoids the crash described in
https://github.com/servo/servo/issues/36792.

Doing this also forces the end users to be more explicit about whether they want to deal with all image frames or just the first one. Previously, `Image::bytes` silently returned only the data for the first frame. With this change there's now a `frames` method which returns an iterator over all frames in the image.

Testing: No tests - this simply reduces the number of fds used. Servo doesn't currently display animated gifs anyways.
Fixes: https://github.com/servo/servo/issues/36792

### CODE REVIEW

**Comment by simonwuelker** [comment]
cc @rayguo17

File: components/pixels/lib.rs [hunk 1]
```diff
@@ -142,12 +154,17 @@ impl Image {
...
+            delay: frame.delay,
+            bytes: self.bytes.get(frame.byte_range.clone()).unwrap(),
+            width: frame.width,
+            height: frame.height,
+        })
+    }
+
+    pub fn first_frame(&self) -> ImageFrameView {
+        self.frames().next().unwrap()
     }
```
Comment (mrobinson) [inline components/pixels/lib.rs:168]:
```suggestion
    pub fn first_frame(&self) -> ImageFrameView {
        self.frames().next().expect("All images should have at least one frame")
    }
```

File: components/pixels/lib.rs [hunk 2]
```diff
@@ -376,8 +395,11 @@ fn decode_gif(buffer: &[u8], cors_status: CorsStatus) -> Option<Image> {
             };
             rgba8_byte_swap_colors_inplace(frame.buffer_mut());
 
+            let frame_start = bytes.len();
+            bytes.extend_from_slice(&frame.buffer());
+
```
Comment (mrobinson) [inline components/pixels/lib.rs:400]: It's a bit inefficient to keep extending the bytes array. Can you collect a collect an array of bytes and then join them all, which should only do a single extra allocation?

**Review by mrobinson — CHANGES_REQUESTED** [review]
Nice! I have a couple tiny suggestions:

File: components/pixels/lib.rs [hunk 3]
```diff
@@ -364,45 +384,61 @@ fn decode_gif(buffer: &[u8], cors_status: CorsStatus) -> Option<Image> {
...
-            format: PixelFormat::BGRA8,
-        })
+        return None;
     }
+
+    // Coalesce the frame data into one single shared memory region.
+    let mut bytes = Vec::with_capacity(total_number_of_bytes);
+    for frame in frame_data {
+        bytes.extend_from_slice(frame.buffer());
+    }
```
Comment (mrobinson) [inline components/pixels/lib.rs:431]: Could this just be ` frame_data.iter().flatten().collect()`?

**Review by mrobinson — APPROVED** [review]

File: components/pixels/lib.rs (hunk 3 above)
Comment (simonwuelker) [reply components/pixels/lib.rs:431]: That would be less efficient I think.

`Flatten::size_hint` can't know how large the individual chunks are (as can be seen in https://github.com/rust-lang/rust/blob/444a62712a29e14d3b6147b51fd24e623496bf58/library/core/src/iter/adapters/flatten.rs#L67-L70). Therefore it needs to reallocate a few times as the `bytes` vector grows. But in this case, we already know how many bytes we'll need, so we avoid the allocations by calling `Vec::with_capacity`.
