### PR TITLE
Use webrender `UploadMethod::Immediate` with ANGLE

### LINKED ISSUE #33170: Rendering issue on wikipedia.org
**Describe the bug:**
Top logo/image and text at bottom left don't render correctly (main branch 2db9032e72bda6108b4eb5988eaf164141a61d64):
wikipedia

**To Reproduce:**
`servo https://wikipedia.org`

**Platform:**
Windows 11, x86_64

I tracked down the issue to `webrender`. Servo uses default texture upload method `UploadMethod::PixelBuffer`. In this mode `webrender` uses a single `TextureUploader` (https://github.com/servo/webrender/blob/c0bcdd024adac1297ceb2f34a2de46731243c970/webrender/src/renderer/upload.rs#L79-L83) to upload glyphs and images to GPU. The uploads are staged in one or more buffers before data is sent to GPU (https://github.com/servo/webrender/blob/c0bcdd024adac1297ceb2f34a2de46731243c970/webrender/src/device/gl.rs#L4561-L4598). On Windows if the staged textures are not aligned at bytes per pixel boundary in upload buffer the GPU will read the wrong data.

Using this patch (https://github.com/crbrz/webrender/commit/f88b451e77390283e7bbed9646853f44949ab6e9) for `webrender` fixes the issue on wikipedia:
wiki_good
This issue https://github.com/servo/servo/issues/33094 seems to be fixed as well.

### PR DESCRIPTION
**Pull request by crbrz**
Use the same webrender texture upload method as Gecko (https://searchfox.org/mozilla-central/source/gfx/webrender_bindings/src/bindings.rs#1215-1219) with ANGLE.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #33170 and #33094

- [X] These changes do not require tests because they shouldn't change behavior.

### CODE REVIEW

File: components/servo/lib.rs [hunk 1]
```diff
@@ -333,6 +334,11 @@ where
                 clear_color[2] as f32,
                 clear_color[3] as f32,
             );
+            let upload_method = if webrender_gl.get_string(RENDERER).starts_with("ANGLE") {
```
Comment (Taym95) [inline components/servo/lib.rs:337]: can't we create something like Firefox [is_glcontext_angle](https://searchfox.org/mozilla-central/source/gfx/layers/wr/WebRenderBridgeParent.cpp#80) ?

File: components/servo/lib.rs [hunk 2]
```diff
@@ -333,6 +334,11 @@ where
...
+                UploadMethod::Immediate
+            } else {
+                UploadMethod::PixelBuffer(ONE_TIME_USAGE_HINT)
+            };
```
Comment (Taym95) [inline components/servo/lib.rs:341]: Maybe worth referring to Firefox code in comment ?

File: components/servo/lib.rs (hunk 1 above)
Comment (crbrz) [reply components/servo/lib.rs:337]: Probably with changes to `surfman` otherwise through GL bindings I didn't find another way. `webrender` uses the same check when testing for ANGLE: https://github.com/servo/webrender/blob/c0bcdd024adac1297ceb2f34a2de46731243c970/webrender/src/device/gl.rs#L1724-L1725

Comment (Taym95) [reply components/servo/lib.rs:339]: Yes I see, just that we may end up with lot of `starts_with("ANGLE")` checks in code

**Review by jdm — APPROVED** [review]
This seems reasonable for the first time we're checking the renderer name.
