### PR TITLE
Convert node serialization to a purely iterative algorithm.

### LINKED ISSUE #16696: Node serialization can trigger stack overflow
```html
<body>
<script>
var last = document.body;
for (var i = 0; i < 3000; i++) {
  console.log(i);
  var e = document.createElement('div');
  last.appendChild(e);
  last = e;
}
var elem = document.body.children[1];
elem.outerHTML;
console.log("done");
</script>
```
This yields:
```
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }' has overflowed its stack
fatal runtime error: stack overflow
Redirecting call to abort() to mozalloc_abort
```
because https://github.com/servo/servo/blob/47f0b4155cb2925dc0702aedf1a539b5ac22a286/components/script/dom/servoparser/html.rs#L319 is a recursive call to Serializable::serialize. We should turn this into an iterative algorithm instead using `traverse_preorder`.

### PR DESCRIPTION
**Pull request by ahicks92**
We maintain a stack of open element nodes with their children count, popping from the top of the stack and closing when the count reaches zero.

Contrary to my comment in #16696, this is a purely iterative algorithm.  I just wasn't feeling sufficiently clever with respect to finding a relatively clean way until later.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #16696 (github issue number if applicable).

- [x] There are tests for these changes.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17520)

### CODE REVIEW

**Comment by camlorn** [comment]
Is the Travis failure spurious?  I'm not sure what this is about a manifest change.

**Comment by camlorn** [comment]
Never mind, I didn't realize the manifests contained hashes that need to be updated after changing tests.

**Comment by camlorn** [comment]
Just bumping this; can we get it merged?

**Comment by asajeffrey** [comment]
Sorry about the delay, the Mozilla all-hands was last week, we've been a bit swamped!

Would it be possible to simplify this, by using an iterator whose `Item` is something like:
```rust
enum BeginOrEndNode {
   Begin(Root<Node>),
   End(Root<Node>),
}
```
this would avoid having to use the stack in `serialize`, since the stack would be kept in the iterator. The iterator can store a stack of `BeginOrEndNode`, initialized as `vec![Begin(root)]`. When `next` is called, we pop from the stack: if it's an `End(node)`, we just return it, but if it's a `Begin(node)`, we push `End(node)`, then `Begin(child)` for each child.

File: components/script/dom/servoparser/html.rs [hunk 1]
```diff
@@ -115,79 +115,132 @@ unsafe impl JSTraceable for HtmlTokenizer<TreeBuilder<JS<Node>, Sink>> {
...
-                }
-
-                let children = if let Some(tpl) = node.downcast::<HTMLTemplateElement>() {
-                    // https://github.com/w3c/DOM-Parsing/issues/1
-                    tpl.Content().upcast::<Node>().children()
-                } else {
-                    node.children()
-                };
+fn start_element<S: Serializer>(node: &Node, serializer: &mut S) -> io::Result<()> {
+    let elem = node.downcast::<Element>().expect("Node should be an Element");
```
Comment (asajeffrey) [inline components/script/dom/servoparser/html.rs]: Take an `&Element` parameter rather than a `&Node`?

File: components/script/dom/servoparser/html.rs [hunk 2]
```diff
@@ -115,79 +115,132 @@ unsafe impl JSTraceable for HtmlTokenizer<TreeBuilder<JS<Node>, Sink>> {
...
+impl<'a> Serialize for &'a Node {
+    fn serialize<S: Serializer>(&self, serializer: &mut S,
+                                traversal_scope: TraversalScope) -> io::Result<()> {
+        let node = *self;
 
-            (IncludeNode, NodeTypeId::DocumentFragment) => Ok(()),
+        // As we encounter elements, we push them to this stack with a count of their children.
+        // Every time through the following loop, we decrement the child count of the topmost element.
+        // When it gets to 0, it's time to close the node.
+        let mut open_stack: Vec<(Root<Node>, u32)> = vec![];
```
Comment (asajeffrey) [inline components/script/dom/servoparser/html.rs]: It would be nice if we could roll this stack into the iterator, rather than have it explicit.

**Review by asajeffrey — COMMENTED** [review]
Could possibly be simplified a bit.

**Comment by camlorn** [comment]
@asajeffrey 
I'll have to think about the stack.  I'm not entirely sure how this makes things better.  It seems like the code is going to be just as complicated or worse with your alternative.

Is the intent to increase reuse?  I can refactor for that in mind if that's the goal.

**Comment by asajeffrey** [comment]
I suspect the code will be more readable with a clean separation between iterating over the nodes and serializing them. I don't think there's much scope for reuse here.

**Comment by camlorn** [comment]
@asajeffrey 
I'm going to try to do it tomorrow and keep the commit separate; I'm either being insufficiently clever at the moment or we might end up wanting to revert my refactor.  I think it'll make the serialization function conceptually simpler, but it's going to need nested matches and I think it's going to make the code more complicated overall.

This is one of those places where coroutines would be a godsend.

**Comment by camlorn** [comment]
That's the nicest I can make it.  I need to rebase these commits together, if we like it.

**Comment by camlorn** [comment]
This Travis failure looks spurious to me, or at least unrelated to this PR.  Can someone rerun it?

**Comment by jdm** [comment]
That's https://github.com/servo/servo/issues/17594. Most PRs are showing it.

**Comment by asajeffrey** [comment]
This is looking a lot nicer! I think it can be simplified even further by something like:
```rust
struct SerializationIterator {
    stack: Vec<SerializationCommand>,
}
```
then the iterator is something like (ignoring templates for the moment):
```rust
impl Iterator for SerializationIterator {
    type Item = SerializationCommand;
    fn next(&mut self) -> Option<SerializationCommand> {
        let result = self.stack.pop();
        if let Some(SerializationCommand::OpenElement(element)) {
            self.stack.push(SerializationCommand::CloseElement(element));
            for child in element.children().iter().rev() {
                match child.downcast::<Element>() {
                    Some(child) => self.stack.push(SerializationCommand::OpenElement(child)),
                    None => self.stack.push(SerializationCommand::SerializeNonelement(child)),
                }
            }
        }
        result
    }
}
```

**Comment by camlorn** [comment]
Before I try to rewrite this again, what counts as satisfactory?  I feel like we're chasing perfection.  It's complicated no matter how you slice it.

I'm not trying to be disagreeable and if you say rewrite it I'll go rewrite it, but this feels like the sort of thing where we're both making equally valid judgement calls and where a third party would find both our judgement calls to be equally difficult to grasp without explanation.

**Comment by asajeffrey** [comment]
The goal here is just code cleanliness/readability/maintainability, which is, as you say, often subjective. Hopefully the remaining change isn't that major, it's replacing:
```rust
open_element_stack: Vec<(Root<Element>, u32)>,
```
by:
```rust
command_stack: Vec<SerializationCommand>,
```
and the matching changes in `next`. Does this seem like an improvement to you, or do you prefer the version storing a `u32`?

**Comment by KiChjang** [comment]
I'm really not ok with storing a `u32` since it means nothing to me while I'm reading the code.

**Comment by camlorn** [comment]
@asajeffrey
Since we have multiple people now, I'll rewrite it.

I don't like the `i32` approach either, but I have an easier time convincing myself that nodes are getting visited in the right order with mine as compared to yours.  It's not that I have a preference between them, so much as it is that I've already spent rather a lot of time on this and the solution works.

The only non-aesthetic argument here is if performance matters, in which case we should profile it.

**Comment by camlorn** [comment]
This might still be able to be made cleaner. I'm going to give it another pass in the morning.

**Comment by asajeffrey** [comment]
Thanks!

**Comment by camlorn** [comment]
I just pushed the cleanup work.  If this is good, I'll rebase them together.  I don't think it can be made cleaner.

Sorry about the turnaround time.  Lots of things going on, etc.

**Comment by asajeffrey** [comment]
Yay, this looks really nice now, thanks for all your work!

`./mach test-tidy` is failing, apart from that this looks good to merge!

**Comment by asajeffrey** [comment]
Oh yes, and the commits need squashed too.

**Comment by camlorn** [comment]
Think that does it.

**Comment by asajeffrey** [comment]
LGTM! @bors-servo r+

**Comment by jdm** [comment]
@bors-servo: retry
* #17756

**Comment by asajeffrey** [comment]
Yay!
