### PR TITLE
servoshell: Properly handle `WindowEvent::Focused`

### LINKED ISSUE #41398: Regression: Create a WebDriver session redirects page to about:blank
**Describe the bug:**
Regression from #41235

**To Reproduce:**
Create a webdriver session.

**Platform:**

1. On PC, this creates a new window with "about:blank".
2. On OHOS, this redirects the current page to "about:blank"

### PR DESCRIPTION
**Pull request by yezhizhen**
There are two bugs listed below. Basically, we never ever set https://github.com/servo/servo/blob/1b0bd11e111508fa3ee7e77ccdf6cf4149d137bb/ports/servoshell/running_app_state.rs#L253-L255 except by WebDriver command, so it's always been `None`. 

This PR lets `WindowEvent::Focused` determine `focused_window` for `HeadedWindow`.
For those without `winit::Window`, such as Android/OHOS/`HeadlessWindow`, the newly created window is automatically focused.

Fixes: #41398
Fixes: #41399

### CODE REVIEW

**Comment by yezhizhen** [comment]
I don't know how to add a UT for window. Are there any rn?

File: ports/servoshell/running_app_state.rs [hunk 1]
```diff
@@ -237,6 +237,7 @@ impl RunningAppState {
         initial_url: Url,
     ) -> Rc<ServoShellWindow> {
         let window = Rc::new(ServoShellWindow::new(platform_window));
+        self.focus_window(window.clone());
```
Comment (mrobinson) [inline ports/servoshell/running_app_state.rs]: I think it should be up to the window manager to decide which windows get focus in servoshell. You're right though that we also aren't listening to signals that a window has been focused. We should add `RunningAppState::handle_focus`:

```rust
    pub(crate) fn handle_focused(&self, window: Rc<ServoShellWindow>) {
        *self.focused_window.borrow_mut() = Some(window);
    }
```

This is the same as `focus()`, but doesn't trigger a system focus request.

And then we handle `WindowEvent::Focused`:

```diff
diff --git a/ports/servoshell/desktop/headed_window.rs b/ports/servoshell/desktop/headed_window.rs
index f0ff1e212a8..5f60be38a7d 100644
--- a/ports/servoshell/desktop/headed_window.rs
+++ b/ports/servoshell/desktop/headed_window.rs
@@ -629,6 +629,7 @@ impl PlatformWindow for Window {
         // Handle the event
         let mut consumed = false;
         match event {
+            WindowEvent::Focused(true) => running_app_state.handle_focused(window),
             WindowEvent::ScaleFactorChanged { scale_factor, .. } => {
                 // Intercept any ScaleFactorChanged events away from EguiGlow::on_window_event, so
                 // we can use our own logic for calculating the scale factor and set egui’s
```

**Review by mrobinson — CHANGES_REQUESTED** [review]

File: ports/servoshell/running_app_state.rs (hunk 1 above)
Comment (yezhizhen) [reply ports/servoshell/running_app_state.rs]: Ehh don't know how to get this compiled.

```rust
// The signature here cannot be changed.
fn handle_winit_window_event(
        &self,
        state: Rc<RunningAppState>,
        window: &ServoShellWindow,
```

`focused_window` must be an `Rc`.

Comment (mrobinson) [reply ports/servoshell/running_app_state.rs]: Maybe try something like this:

```diff
diff --git a/ports/servoshell/desktop/app.rs b/ports/servoshell/desktop/app.rs
index e8998c7f8ba..b17681adf6c 100644
--- a/ports/servoshell/desktop/app.rs
+++ b/ports/servoshell/desktop/app.rs
@@ -193,7 +193,7 @@ impl ApplicationHandler<AppEvent> for App {
             if let Some(window) = state.window(window_id.into()) {
                 window.platform_window().handle_winit_window_event(
                     state.clone(),
-                    &window,
+                    window.clone(),
                     window_event,
                 );
             }
diff --git a/ports/servoshell/desktop/headed_window.rs b/ports/servoshell/desktop/headed_window.rs
index f0ff1e212a8..84ca6946264 100644
--- a/ports/servoshell/desktop/headed_window.rs
+++ b/ports/servoshell/desktop/headed_window.rs
@@ -594,7 +594,7 @@ impl PlatformWindow for Window {
     fn handle_winit_window_event(
         &self,
         state: Rc<RunningAppState>,
-        window: &ServoShellWindow,
+        window: Rc<ServoShellWindow>
         event: WindowEvent,
     ) {
         if event == WindowEvent::RedrawRequested {
@@ -629,6 +629,7 @@ impl PlatformWindow for Window {
         // Handle the event
         let mut consumed = false;
         match event {
+            WindowEvent::Focused(true) => running_app_state.handle_focused(window),
             WindowEvent::ScaleFactorChanged { scale_factor, .. } => {
                 // Intercept any ScaleFactorChanged events away from EguiGlow::on_window_event, so
                 // we can use our own logic for calculating the scale factor and set egui’s
diff --git a/ports/servoshell/window.rs b/ports/servoshell/window.rs
index 4e888bea672..1aaebd38e0e 100644
--- a/ports/servoshell/window.rs
+++ b/ports/servoshell/window.rs
@@ -374,7 +374,7 @@ pub(crate) trait PlatformWindow {
     fn handle_winit_window_event(
         &self,
         _: Rc<RunningAppState>,
-        _: &ServoShellWindow,
+        _: Rc<servoShellWindow>,
         _: winit::event::WindowEvent,
     ) {
     }

```

I'm compiling now so if you can't get this working I can give you a real diff in a bit.

Comment (yezhizhen) [reply ports/servoshell/running_app_state.rs]: Oh mb. I thought we cannot change the signature of `handle_winit_window_event` because it was part of external library interface. (The doc of the function deceives me as it looks standard.)

Let me give a shot :D

**Review by mrobinson — APPROVED** [review]
Thank you!

**Comment by yezhizhen** [comment]
> On OHOS, this redirects the current page to "about:blank"

This still needs some work for ohos, as part of #41399 not fixed yet.

**Comment by yezhizhen** [comment]
It seems the easiest solution is to add back https://github.com/servo/servo/pull/41401/changes/360e1ed26f02818e6d1d320633a7ac75137ce5bb as well. It is consistent with Desktop behaviour of `open_window`.

We are still able to handle `WindowEvent::Focused` message from winit users.

Another way: gated after `#cfg`

File: ports/servoshell/running_app_state.rs (hunk 1 above)
Comment (mrobinson) [reply ports/servoshell/running_app_state.rs]: Hrm. Note that headless windows will never be focused either. This might need to change here as well.

File: ports/servoshell/window.rs [hunk 2]
```diff
@@ -437,4 +437,7 @@ pub(crate) trait PlatformWindow {
     fn notify_media_session_event(&self, _: MediaSessionEvent) {}
     fn notify_crashed(&self, _: WebView, _reason: String, _backtrace: Option<String>) {}
     fn show_console_message(&self, _level: ConsoleLogLevel, _message: &str) {}
+    fn has_winit_window(&self) -> bool {
```
Comment (yezhizhen) [inline ports/servoshell/window.rs:440]: > Hrm. Note that headless windows will never be focused either. This might need to change here as well.

I added a simple API for `PlatformWindow`. We can then handle `HeadlessWindow`/Android/OHOS consistently.
