### PR TITLE
layout: Fix painting order of collapsed table borders

### LINKED ISSUE #35173: Stacking contexts don't paint collapsed table borders at the right time
The spec is wrong. But the approach that I came up with in #35075 doesn't match other browsers either :(

See https://github.com/w3c/csswg-drafts/issues/11570 for details

### PR DESCRIPTION
**Pull request by Loirooriol**
In #35075 I painted them in front of the decorations (backgrounds and borders) of any block-level box in the same stacking context. I did that because other browsers paint them in front of the decorations of the descendants of the table, but my approach also painted them in front of decorations of following siblings of the table, which was wrong.

This patch makes it so that collapsed table orders are painted in the same step as decorations. However, tables defer painting their collapsed borders after the decorations of their descendants.

This matches Blink and WebKit, and brings us closer to Gecko (which is slightly different in some corner cases).

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #35173
- [X] There are tests for these changes

### CODE REVIEW

File: components/layout_2020/display_list/stacking_context.rs [hunk 1]
```diff
@@ -1293,6 +1292,25 @@ impl BoxFragment {
...
+            Some(SpecificLayoutInfo::TableGridWithCollapsedBorders(_))
+        )) {
+            stacking_context
+                .contents
+                .push(StackingContextContent::Fragment {
+                    scroll_node_id: new_scroll_node_id,
+                    reference_frame_scroll_node_id: reference_frame_scroll_node_id_for_fragments,
+                    clip_chain_id: new_clip_chain_id,
+                    // TODO: should this use `self.get_stacking_context_section()`?
+                    section: StackingContextSection::DescendantBackgroundsAndBorders,
```
Comment (mrobinson) [inline components/layout_2020/display_list/stacking_context.rs:1307]: I guess you could check if this is correct by determining if a table that establishes a stacking context has border that behave properly when elements inside the table also form stacking contexts with `z-index` as well.

**Review by mrobinson — APPROVED** [review]

File: components/layout_2020/display_list/stacking_context.rs (hunk 1 above)
Comment (Loirooriol) [reply components/layout_2020/display_list/stacking_context.rs:1307]: So after thinking more, we are painting the borders with the grid. The grid doesn't inherit `position`, `float`, etc. so `get_stacking_context_section()` should be `StackingContextSection::DescendantBackgroundsAndBorders` anyways. It may actually be `StackingContextSection::OwnBackgroundsAndBorders`  because it inherits `display`, but this seems like a bug, I can address it in a follow-up. I guess it's better to land this as is, which makes us match Blink and WebKit. It seems Firefox paints the collapsed borders with the table wrapper instead of the table grid, that would explain the difference in behavior.
