### PR TITLE
Let protocol handlers decide if they are fetchable

### LINKED ISSUE #33564: `fetch()` calls to custom protocols don't appear to work as expected
While working on my own Servo-based browser I wanted to add the ability to change prefs at runtime. My initial attempt at this was to create an HTML page that would make fetch calls to an embedder-specific route with its own handler (in my example it was `moto:pref`) whenever a user clicked a button, but it seems the fetch calls to the embedder route just never seemed to happen. I could see in JS that the button onclick was working, and I don't recall seeing any errors when making the fetch call either.

In essence, to reproduce:
- In a custom protocol, add a route that does a println before sending the response
- Create a page that calls `fetch()` to that route
- Observe that println never occurs even when `fetch()` is called

### PR DESCRIPTION
**Pull request by webbeef**
This adds a 'is_fetchable()' method on the ProtocolHandler trait that is then used in the fetch code. The 'data:' protocol handler is updated to return true instead of hardcoding the scheme comparison, as well as the 'urlinfo:' handler since it's just a testing one.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #33564 (GitHub issue number if applicable)

### CODE REVIEW

**Review by jdm — APPROVED** [review]

File: components/net/protocols/mod.rs [hunk 1]
```diff
@@ -35,6 +35,10 @@ pub trait ProtocolHandler: Send + Sync {
         done_chan: &mut DoneChannel,
         context: &FetchContext,
     ) -> Pin<Box<dyn Future<Output = Response> + Send>>;
+
+    fn is_fetchable(&self) -> bool {
```
Comment (wusyong) [inline components/net/protocols/mod.rs:39]: We should add the documentation to explain how this works.

**Review by jdm — APPROVED** [review]
