### PR TITLE
layout: Allow same `ScriptThread` `<iframe>`s to be resized synchronously

### LINKED ISSUE #14719: Our resize story for iframes is not great.
Right now, we handle resizes asynchronously, even when they're set explicitly by the user. This has observable effects for same-origin iframes, and not-interoperable behavior.

See, for example, #14556.

Right now, when the width attribute changes, we do the following:

 * We run layout, build the display list, including the iframe display item, which contains the pipeline id.
 * WebRender flattens the display list and, if the size changed, calls the render notifier in the compositor...
 * Which sends to the constellation the resize.
 * Which in turns sets the window's `window_size` field, and trigger a reflow.

That's (I think) fine for cross-origin iframes, since there are no visible effects from the web page's point of view (apart from a moment with the straneous styling). I'm not sure how Gecko handles cross-origin iframe resizing, maybe the resize needs to be synchronous as well? @bzbarsky may know better than I.

Concretely: what happens when an iframe is resized as a consequence of a style/layout change (e.g., because it uses a percentage width?). Is it different for same and cross-origin iframes (I guess so)? I might investigate it tomorrow, but today's christmas :)

But for same-origin iframes, it seems we can't do all this async story all that straight away.

cc @pcwalton, and also @asajeffrey and @jdm, which know about the effort that was needed to make same-origin frames share script threads, given it's probably a similar effort for layout threads.

### LINKED ISSUE #24569: Intermittent failure in /css/cssom-view/MediaQueryList-addListener-removeListener.html
```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "listeners are called correct number of times", 
    "test": "/css/cssom-view/MediaQueryList-addListener-removeListener.html", 
    "line": 69783, 
    "action": "test_result", 
    "expected": "FAIL"
}
```

### LINKED ISSUE #24571: Intermittent failure in /css/cssom-view/MediaQueryList-addListener-handleEvent.html
```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "looks up handleEvent method on every event dispatch", 
    "test": "/css/cssom-view/MediaQueryList-addListener-handleEvent.html", 
    "line": 151512, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "doesn't look up handleEvent method on callable event listeners", 
    "test": "/css/cssom-view/MediaQueryList-addListener-handleEvent.html", 
    "line": 151513, 
    "action": "test_result", 
    "expected": "FAIL"
}
```

### LINKED ISSUE #25269: Intermittent failure in /css/cssom-view/MediaQueryList-extends-EventTarget.html
```
  ▶ Unexpected subtest result in /css/cssom-view/MediaQueryList-extends-EventTarget.html:
  │ FAIL [expected PASS] listeners for "change" type are called
  │   → assert_equals: expected 1 but got 0
  │ 
  │ @http://web-platform.test:8000/css/cssom-view/MediaQueryList-extends-EventTarget.html:58:5
  │ async*Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1984:25
  │ promise_test/tests.promise_tests</<@http://web-platform.test:8000/resources/testharness.js:605:36
  └ promise_test/tests.promise_tests<@http://web-platform.test:8000/resources/testharness.js:604:20
```

### LINKED ISSUE #25275: Intermittent fail in /css/cssom-view/MediaQueryListEvent.html
```
  ▶ Unexpected subtest result in /css/cssom-view/MediaQueryListEvent.html:
  │ FAIL [expected PASS] argument of onchange
  │   → assert_true: expected true got false
  │ 
  │ @http://web-platform.test:8000/css/cssom-view/MediaQueryListEvent.html:68:5
  │ async*Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1984:25
  │ promise_test/tests.promise_tests</<@http://web-platform.test:8000/resources/testharness.js:605:36
  └ promise_test/tests.promise_tests<@http://web-platform.test:8000/resources/testharness.js:604:20
```

### LINKED ISSUE #25285: Intermittent failure in /css/cssom-view/MediaQueryList-extends-EventTarget-interop.html
```
  ▶ Unexpected subtest result in /css/cssom-view/MediaQueryList-extends-EventTarget-interop.html:
  │ FAIL [expected PASS] listener added with addListener and addEventListener is called once
  │   → assert_equals: triggerMQLEvent expected 1 but got 0
  │ 
  │ @http://web-platform.test:8000/css/cssom-view/MediaQueryList-extends-EventTarget-interop.html:42:5
  │ async*Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1984:25
  │ promise_test/tests.promise_tests</<@http://web-platform.test:8000/resources/testharness.js:605:36
  └ promise_test/tests.promise_tests<@http://web-platform.test:8000/resources/testharness.js:604:20
```

### LINKED ISSUE #30571: Debug assertion failures in components/constellation/constellation.rs:3171
(#30567, #30509)

```
% ( set -- 2020/filtered-test-wpt.*.json; for i; do < $i jq -r '.[] | select(.stack != null) | .stack' | rg -o --pcre2 '(?<=, at )[^()]+(?=[)]$)'; done | sort -u | while read -r site; do echo ">>> $site"; for i; do < $i jq -r '.[] | select(.stack != null) | select(.stack | contains("'"$site"'")) | .stack'; done | rg ', at |^assertion failed:|^  left:|^ right:' | sort -u; done )
>>> /home/runner/work/servo/servo/components/constellation/constellation.rs:3171
assertion failed: `(left == right)`
  left: `200.0x100.0`,
  left: `200.0x150.0`,
  left: `200.0x200.0`,
  left: `250.0x250.0`,
  left: `256.0x256.0`,
  left: `300.0x100.0`,
  left: `300.0x150.0`,
  left: `300.0x300.0`,
  left: `300.0x400.0`,
  left: `400.0x250.0`,
  left: `400.0x400.0`,
  left: `500.0x300.0`,
  left: `800.0x600.0`,
 right: `0.0x0.0` (thread Constellation, at /home/runner/work/servo/servo/components/constellation/constellation.rs:3171)
```

```
% ( set -- 2013/filtered-test-wpt.*.json; for i; do < $i jq -r '.[] | select(.stack != null) | .stack' | rg -o --pcre2 '(?<=, at )[^()]+(?=[)]$)'; done | sort -u | while read -r site; do echo ">>> $site"; for i; do < $i jq -r '.[] | select(.stack != null) | select(.stack | contains("'"$site"'")) | .stack'; done | rg ', at |^assertion failed:|^  left:|^ right:' | sort -u; done )
>>> /home/runner/work/servo/servo/components/constellation/constellation.rs:3171
assertion failed: `(left == right)`
  left: `300.0x150.0`,
 right: `0.0x0.0` (thread Constellation, at /home/runner/work/servo/servo/components/constellation/constellation.rs:3171)
```

* layout 2020
    * /cookies/schemeful-same-site/schemeful-iframe-subresource.tentative.html
    * /css/CSS2/linebox/iframe-in-block-in-inline.html
    * /css/css-backgrounds/background-image-shared-stylesheet.html
    * /css/css-fonts/font-size-adjust-reload.html
    * /css/css-images/image-orientation/image-orientation-iframe.html
    * /css/css-position/crashtests/scroll-tree-parent-construction.html
    * /css/css-position/position-absolute-iframe-print-002.sub.html
    * /css/css-variables/variable-reference-refresh.html
    * /css/mediaqueries/mq-dynamic-empty-children.html
    * /custom-elements/reactions/Document.html
    * /dom/abort/crashtests/timeout-close.html
    * /dom/events/event-global-is-still-set-when-coercing-beforeunload-result.html
    * /dom/events/EventListener-incumbent-global-1.sub.html
    * /domparsing/DOMParser-parseFromString-url-moretests.html
    * /fetch/connection-pool/network-partition-key.html
    * /fetch/metadata/generated/element-iframe.sub.html
    * /fetch/private-network-access/xhr.tentative.window.html
    * /fetch/redirect-navigate/302-found-post.html
    * /fetch/redirect-navigate/preserve-fragment.html
    * /FileAPI/url/multi-global-origin-serialization.sub.html
    * /fullscreen/api/document-fullscreen-enabled-removing-allowfullscreen.sub.html
    * /gamepad/gamepad-default-feature-policy.https.sub.html
    * /hr-time/navigation-start-post-before-unload.html
    * /html/anonymous-iframe/cookie-store.tentative.https.window.html
    * /html/anonymous-iframe/cookie.tentative.https.window.html
    * /html/anonymous-iframe/embedding.tentative.https.window.html?12-12
    * /html/browsers/browsing-the-web/history-traversal/001.html
    * /html/browsers/browsing-the-web/history-traversal/browsing_context_name_cross_origin_2.html
    * /html/browsers/browsing-the-web/history-traversal/browsing_context_name_cross_origin_3.html
    * /html/browsers/browsing-the-web/history-traversal/browsing_context_name_cross_origin.html
    * /html/browsers/browsing-the-web/history-traversal/browsing_context_name.html
    * /html/browsers/browsing-the-web/history-traversal/persisted-user-state-restoration/scroll-restoration-fragment-scrolling-cross-origin.html
    * /html/browsers/browsing-the-web/history-traversal/persisted-user-state-restoration/scroll-restoration-navigation-cross-origin.html
    * /html/browsers/browsing-the-web/history-traversal/same-url.html
    * /html/browsers/browsing-the-web/history-traversal/window-name-after-cross-origin-sub-frame-navigation.sub.html
    * /html/browsers/browsing-the-web/history-traversal/window-name-after-same-origin-sub-frame-navigation.sub.html
    * /html/browsers/browsing-the-web/navigating-across-documents/003.html
    * /html/browsers/browsing-the-web/navigating-across-documents/004.html
    * /html/browsers/browsing-the-web/navigating-across-documents/005.html
    * /html/browsers/browsing-the-web/navigating-across-documents/006.html
    * /html/browsers/browsing-the-web/navigating-across-documents/007.html
    * /html/browsers/browsing-the-web/navigating-across-documents/008.html
    * /html/browsers/browsing-the-web/navigating-across-documents/009.html
    * /html/browsers/browsing-the-web/navigating-across-documents/011.html
    * /html/browsers/browsing-the-web/navigating-across-documents/about-srcdoc-navigation-blocked.window.html
    * /html/browsers/browsing-the-web/navigating-across-documents/anchor-fragment-form-submit.html
    * /html/browsers/browsing-the-web/navigating-across-documents/anchor-fragment-form-submit-longfragment.html
    * /html/browsers/browsing-the-web/navigating-across-documents/anchor-fragment-form-submit-withpath.html
    * /html/browsers/browsing-the-web/navigating-across-documents/anchor-jsurl-form-submit.html
    * /html/browsers/browsing-the-web/navigating-across-documents/child-navigates-parent-same-origin.window.html
    * /html/browsers/browsing-the-web/navigating-across-documents/initial-empty-document/iframe-nosrc.html
    * /html/browsers/browsing-the-web/navigating-across-documents/initial-empty-document/iframe-src-204.html
    * /html/browsers/browsing-the-web/navigating-across-documents/initial-empty-document/iframe-src-aboutblank-wait-for-load.html
    * /html/browsers/browsing-the-web/navigating-across-documents/javascript-url-abort/javascript-url-abort-return-value-string.tentative.html
    * /html/browsers/browsing-the-web/navigating-across-documents/javascript-url-abort/javascript-url-abort-return-value-undefined.tentative.html
    * /html/browsers/browsing-the-web/navigating-across-documents/javascript-url-no-beforeunload.window.html
    * /html/browsers/browsing-the-web/navigating-across-documents/javascript-url-security-check-failure.sub.html
    * /html/browsers/browsing-the-web/navigating-across-documents/javascript-url-security-check-multi-globals.sub.html
    * /html/browsers/browsing-the-web/navigating-across-documents/navigate-cross-origin-iframe-to-same-url.html
    * /html/browsers/browsing-the-web/navigating-across-documents/navigate-cross-origin-iframe-to-same-url-with-fragment-fire-load-event.html
    * /html/browsers/browsing-the-web/navigating-across-documents/navigate-cross-origin-iframe-to-same-url-with-fragment.html
    * /html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-cross-origin.sub.window.html
    * /html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-data-url.window.html
    * /html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-form-submit.html
    * /html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-javascript-url.window.html
    * /html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-same-origin-fragment.html
    * /html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-same-origin.window.html
    * /html/browsers/browsing-the-web/navigating-across-documents/redirect-to-unparseable-url.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/a-click-during-load.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/a-click-during-pageshow.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/a-click.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/form-requestsubmit-during-load.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/form-requestsubmit-during-pageshow.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/form-requestsubmit.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/form-submit-button-click-during-load.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/form-submit-button-click-during-pageshow.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/form-submit-button-click.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/form-submit-cross-frame-crossorigin.sub.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/form-submit-cross-frame.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/form-submit-during-load.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/form-submit-during-pageshow.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/form-submit.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/history-pushstate-during-load.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/history-pushstate-during-pageshow.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/history-pushstate.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/iframe-src-during-load.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/iframe-src-during-pageshow.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/iframe-src.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/location-assign-during-load.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/location-assign-during-pageshow.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/location-assign.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/location-setter-during-load.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/location-setter-during-pageshow.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/location-setter.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/window-open-self-during-load.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/window-open-self-during-pageshow.html
    * /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/window-open-self.html
    * /html/browsers/browsing-the-web/navigating-across-documents/source/navigate-child-function.html
    * /html/browsers/browsing-the-web/navigating-across-documents/source/navigate-child-function-parent.html
    * /html/browsers/browsing-the-web/navigating-across-documents/source/navigate-child-function-src.html
    * /html/browsers/browsing-the-web/navigating-across-documents/source/navigate-child-src-about-blank.html
    * /html/browsers/browsing-the-web/overlapping-navigations-and-traversals/cross-document-nav-stop.html
    * /html/browsers/browsing-the-web/overlapping-navigations-and-traversals/cross-document-traversal-same-document-traversal.html
    * /html/browsers/browsing-the-web/overlapping-navigations-and-traversals/nav-cancelation-1.html
    * /html/browsers/browsing-the-web/overlapping-navigations-and-traversals/nav-cancelation-2.sub.html
    * /html/browsers/browsing-the-web/overlapping-navigations-and-traversals/same-document-nav-stop.html
    * /html/browsers/browsing-the-web/overlapping-navigations-and-traversals/same-document-traversal-cross-document-nav.html
    * /html/browsers/browsing-the-web/overlapping-navigations-and-traversals/same-document-traversal-same-document-nav.html
    * /html/browsers/browsing-the-web/overlapping-navigations-and-traversals/same-document-traversal-same-document-traversal-pushstate.html
    * /html/browsers/browsing-the-web/unloading-documents/beforeunload-canceling.html
    * /html/browsers/browsing-the-web/unloading-documents/beforeunload-on-history-back.html
    * /html/browsers/browsing-the-web/unloading-documents/beforeunload-on-navigation-of-parent.html
    * /html/browsers/browsing-the-web/unloading-documents/beforeunload-sticky-activation-iframe.html
    * /html/browsers/browsing-the-web/unloading-documents/navigation-within-beforeunload.html
    * /html/browsers/browsing-the-web/unloading-documents/pagehide-on-history-forward.html
    * /html/browsers/browsing-the-web/unloading-documents/prompt/001.html
    * /html/browsers/browsing-the-web/unloading-documents/prompt/004.html
    * /html/browsers/browsing-the-web/unloading-documents/prompt-and-unload-script-uncloseable.html
    * /html/browsers/browsing-the-web/unloading-documents/unload/001.html
    * /html/browsers/browsing-the-web/unloading-documents/unload/002.html
    * /html/browsers/browsing-the-web/unloading-documents/unload/003.html
    * /html/browsers/browsing-the-web/unloading-documents/unload/004.html
    * /html/browsers/browsing-the-web/unloading-documents/unload/006.html
    * /html/browsers/browsing-the-web/unloading-documents/unload/007.html
    * /html/browsers/browsing-the-web/unloading-documents/unload/008.html
    * /html/browsers/browsing-the-web/unloading-documents/unload/009.html
    * /html/browsers/history/joint-session-history/joint-session-history-only-fully-active.html
    * /html/browsers/history/joint-session-history/joint-session-history-remove-iframe.html
    * /html/browsers/history/the-history-interface/002.html
    * /html/browsers/history/the-history-interface/009.html
    * /html/browsers/history/the-history-interface/iframe_history_go_0.html
    * /html/browsers/history/the-history-interface/joint_session_history/001.html
    * /html/browsers/history/the-location-interface/assign_after_load.html
    * /html/browsers/history/the-location-interface/assign_before_load.html
    * /html/browsers/history/the-location-interface/location_assign_about_blank.html
    * /html/browsers/history/the-location-interface/location-pathname-setter-question-mark.html
    * /html/browsers/history/the-location-interface/location-protocol-setter-non-broken.html
    * /html/browsers/history/the-location-interface/location-protocol-setter-sameish.html
    * /html/browsers/history/the-location-interface/location-protocol-setter-with-colon.sub.html
    * /html/browsers/history/the-location-interface/location_reload.html
    * /html/browsers/history/the-location-interface/location_reload_javascript_url.html
    * /html/browsers/origin/cross-origin-objects/cross-origin-objects.html
    * /html/browsers/origin/cross-origin-objects/cross-origin-objects-on-new-window.html
    * /html/browsers/origin/inheritance/javascript-url.html
    * /html/browsers/origin/origin-keyed-agent-clusters/getter-special-cases/data-to-javascript-yes.https.html
    * /html/browsers/origin/origin-keyed-agent-clusters/getter-special-cases/javascript-url-no.https.html
    * /html/browsers/origin/origin-keyed-agent-clusters/going-back.sub.https.html
    * /html/browsers/origin/origin-keyed-agent-clusters/iframe-navigation/parent-no-1-subdomain-yes-2-subdomain2-no.sub.https.html
    * /html/browsers/origin/relaxing-the-same-origin-restriction/document_domain_access_details.sub.html
    * /html/browsers/sandboxing/sandbox-inherited-from-initiator-response.html
    * /html/browsers/sandboxing/sandbox-inherited-from-required-csp.html
    * /html/browsers/the-window-object/garbage-collection-and-browsing-contexts/discard_iframe_history_1.html
    * /html/browsers/the-window-object/garbage-collection-and-browsing-contexts/discard_iframe_history_2.html
    * /html/browsers/the-window-object/garbage-collection-and-browsing-contexts/discard_iframe_history_3.html
    * /html/browsers/the-window-object/garbage-collection-and-browsing-contexts/discard_iframe_history_4.html
    * /html/browsers/the-window-object/named-access-on-the-window-object/navigated-named-objects.window.html
    * /html/browsers/windows/browsing-context-names/choose-default-002.html
    * /html/browsers/windows/browsing-context-names/choose-_parent-002.html
    * /html/browsers/windows/browsing-context-names/choose-_parent-004.html
    * /html/browsers/windows/browsing-context-names/choose-_self-002.html
    * /html/browsers/windows/embedded-opener-a-form.html
    * /html/browsers/windows/embedded-opener.html
    * /html/browsers/windows/noreferrer-window-name.html
    * /html/browsers/windows/targeting-cross-origin-nested-browsing-contexts.html
    * /html/browsers/windows/targeting-with-embedded-null-in-target.html
    * /html/infrastructure/urls/base-url/document-base-url-changes-after-nav-about-srcdoc.https.window.html
    * /html/infrastructure/urls/terminology-0/nontraditional-about-srcdoc.html
    * /html/rendering/non-replaced-elements/the-page/body-margin-1d.html
    * /html/rendering/non-replaced-elements/the-page/body-margin-1l.html
    * /html/rendering/non-replaced-elements/the-page/body-margin-2h.html
    * /html/rendering/non-replaced-elements/the-page/body-margin-2i.html
    * /html/rendering/replaced-elements/svg-embedded-sizing/svg-in-iframe-auto.html
    * /html/rendering/replaced-elements/svg-embedded-sizing/svg-in-iframe-fixed.html
    * /html/rendering/replaced-elements/svg-embedded-sizing/svg-in-iframe-percentage.html
    * /html/semantics/document-metadata/the-base-element/base_target_does_not_affect_location_assignment.html
    * /html/semantics/embedded-content/the-iframe-element/change_parentage.html
    * /html/semantics/embedded-content/the-iframe-element/iframe-allowfullscreen.html
    * /html/semantics/embedded-content/the-iframe-element/iframe-allow.html
    * /html/semantics/embedded-content/the-iframe-element/iframe-first-load-canceled-second-load-blank.html
    * /html/semantics/embedded-content/the-iframe-element/iframe_javascript_url_01.htm
    * /html/semantics/embedded-content/the-iframe-element/iframe-loading-lazy.html
    * /html/semantics/embedded-content/the-iframe-element/iframe_navigate_ancestor-1.sub.html
    * /html/semantics/embedded-content/the-iframe-element/iframe-network-error.sub.html
    * /html/semantics/embedded-content/the-iframe-element/iframe_remove_src.html
    * /html/semantics/embedded-content/the-iframe-element/iframe_sandbox_navigate_ancestor-2.html
    * /html/semantics/embedded-content/the-iframe-element/iframe_sandbox_navigate_itself.html
    * /html/semantics/embedded-content/the-iframe-element/iframe_sandbox_navigation_download_allow_downloads.sub.tentative.html
    * /html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_escaping-1.html
    * /html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_escaping-2.html
    * /html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_escaping-3.html
    * /html/semantics/embedded-content/the-iframe-element/multiple-iframes-with-allow-scripts-crash.html
    * /html/semantics/embedded-content/the-iframe-element/srcdoc_process_attributes.html
    * /html/semantics/embedded-content/the-iframe-element/src-repeated-in-ancestor.html
    * /html/semantics/forms/attributes-common-to-form-controls/dirname-ltr.html
    * /html/semantics/forms/attributes-common-to-form-controls/dirname-only-if-applies.html
    * /html/semantics/forms/attributes-common-to-form-controls/dirname-rtl-auto.html
    * /html/semantics/forms/attributes-common-to-form-controls/dirname-rtl-inherited.html
    * /html/semantics/forms/form-submission-0/constructing-form-data-set.html
    * /html/semantics/forms/form-submission-0/form-data-set-usv.html
    * /html/semantics/forms/form-submission-0/form-double-submit-2.html
    * /html/semantics/forms/form-submission-0/form-double-submit-3.html
    * /html/semantics/forms/form-submission-0/form-double-submit-default-action.html
    * /html/semantics/forms/form-submission-0/form-double-submit.html
    * /html/semantics/forms/form-submission-0/form-double-submit-preventdefault-click.html
    * /html/semantics/forms/form-submission-0/form-double-submit-preventdefault.html
    * /html/semantics/forms/form-submission-0/form-double-submit-requestsubmit.html
    * /html/semantics/forms/form-submission-0/form-double-submit-to-different-origin-frame.html
    * /html/semantics/forms/form-submission-0/form-submission-algorithm.html
    * /html/semantics/forms/form-submission-0/form-submit-iframe-then-location-navigate.html
    * /html/semantics/forms/form-submission-0/getactionurl.html
    * /html/semantics/forms/form-submission-0/jsurl-form-submit.tentative.html
    * /html/semantics/forms/form-submission-0/request-submit-activation.html
    * /html/semantics/forms/form-submission-0/submit-entity-body.html
    * /html/semantics/forms/form-submission-0/url-encoded.html
    * /html/semantics/forms/the-button-element/button-activate.html
    * /html/semantics/forms/the-button-element/button-submit-children.html
    * /html/semantics/forms/the-button-element/button-submit-remove-children.html
    * /html/semantics/forms/the-button-element/button-submit-remove-children-jssubmit.html
    * /html/semantics/forms/the-button-element/button-submit-remove-jssubmit.html
    * /html/semantics/forms/the-form-element/form-action-submission.html
    * /html/semantics/forms/the-form-element/form-action-submission-with-base-url.html
    * /html/semantics/forms/the-form-element/form-requestsubmit.html
    * /html/semantics/forms/the-input-element/hidden-charset-case-sensitive.html
    * /html/semantics/forms/the-input-element/input-submit-remove-jssubmit.html
    * /html/semantics/forms/the-input-element/show-picker-cross-origin-iframe.html
    * /html/semantics/forms/the-select-element/show-picker-cross-origin-iframe.tentative.html
    * /html/semantics/forms/the-textarea-element/wrap-enumerated-ascii-case-insensitive.html
    * /html/semantics/links/following-hyperlinks/activation-behavior.window.html
    * /html/semantics/links/hyperlink-auditing/headers.optional.html
    * /html/semantics/links/links-created-by-a-and-area-elements/htmlanchorelement_noopener.html
    * /html/semantics/scripting-1/the-script-element/execution-timing/083.html
    * /html/semantics/scripting-1/the-script-element/json-module-assertions/credentials.sub.html
    * /html/syntax/speculative-parsing/generated/document-write/link-rel-stylesheet-nomatch-media.tentative.sub.html
    * /html/syntax/speculative-parsing/generated/document-write/picture-source-nomatch-media.tentative.sub.html
    * /html/syntax/speculative-parsing/generated/document-write/picture-source-unsupported-type.tentative.sub.html
    * /html/syntax/speculative-parsing/generated/document-write/xmp-script-src.tentative.sub.html
    * /html/webappapis/dynamic-markup-insertion/closing-the-input-stream/load-event-after-location-set-during-write.window.html
    * /html/webappapis/dynamic-markup-insertion/document-write/write-active-document.html
    * /html/webappapis/dynamic-markup-insertion/opening-the-input-stream/abort-while-navigating.window.html
    * /html/webappapis/dynamic-markup-insertion/opening-the-input-stream/active.window.html
    * /html/webappapis/dynamic-markup-insertion/opening-the-input-stream/bailout-exception-vs-return-origin.sub.window.html
    * /html/webappapis/dynamic-markup-insertion/opening-the-input-stream/bailout-exception-vs-return-xml.window.html
    * /html/webappapis/dynamic-markup-insertion/opening-the-input-stream/bailout-side-effects-ignore-opens-during-unload.window.html
    * /html/webappapis/dynamic-markup-insertion/opening-the-input-stream/crbug-583445-regression.window.html
    * /html/webappapis/dynamic-markup-insertion/opening-the-input-stream/event-listeners.window.html
    * /html/webappapis/dynamic-markup-insertion/opening-the-input-stream/location-set-and-document-open.html
    * /html/webappapis/dynamic-markup-insertion/opening-the-input-stream/url.window.html
    * /html/webappapis/scripting/event-loops/fully_active_document.window.html
    * /html/webappapis/scripting/events/compile-event-handler-settings-objects.html
    * /html/webappapis/scripting/processing-model-2/integration-with-the-javascript-job-queue/promise-job-entry.html
    * /_mozilla/css/iframe/frameborder_a.html
    * /_mozilla/css/iframe/hide_after_load.html
    * /_mozilla/css/iframe/navigation.html
    * /_mozilla/css/iframe/simple_inline_min.html
    * /_mozilla/css/iframe/size_attributes_vertical_writing_mode.html
    * /_mozilla/css/iframe/stacking_context.html
    * /_mozilla/mozilla/cross-origin-objects/cross-origin-objects.html
    * /_mozilla/mozilla/cross-origin-objects/cross-origin-postMessage.html
    * /_mozilla/mozilla/FileAPI/file-upload.html
    * /_mozilla/mozilla/form_submit_about.html
    * /_mozilla/mozilla/history.html
    * /_mozilla/mozilla/htmllabel-activation.html
    * /_mozilla/mozilla/webgl/history.html
    * /navigation-timing/nav2-test-document-replaced.html
    * /navigation-timing/nav2-test-navigate-iframe.html
    * /navigation-timing/nav2-test-navigation-type-backforward.html
    * /navigation-timing/nav2-test-navigation-type-reload.html
    * /navigation-timing/navigation-type-post-backforward.html
    * /navigation-timing/test-navigation-type-backforward.html
    * /navigation-timing/test-navigation-type-reload.html
    * /navigation-timing/test-timing-attributes-dependent-on-document-load.html
    * /navigation-timing/test-timing-attributes-order.html
    * /navigation-timing/test-timing-reload.html
    * /navigation-timing/unload-event-same-origin-check.html
    * /referrer-policy/4K+1/gen/top.http-rp/no-referrer-when-downgrade/a-tag.http.html
    * /referrer-policy/4K-1/gen/top.http-rp/no-referrer-when-downgrade/a-tag.http.html
    * /referrer-policy/4K+1/gen/top.http-rp/origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/4K-1/gen/top.http-rp/origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/4K+1/gen/top.http-rp/same-origin/a-tag.http.html
    * /referrer-policy/4K-1/gen/top.http-rp/same-origin/a-tag.http.html
    * /referrer-policy/4K-1/gen/top.http-rp/same-origin/iframe-tag.http.html
    * /referrer-policy/4K+1/gen/top.http-rp/strict-origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/4K-1/gen/top.http-rp/strict-origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/4K+1/gen/top.http-rp/unsafe-url/a-tag.http.html
    * /referrer-policy/4K-1/gen/top.http-rp/unsafe-url/a-tag.http.html
    * /referrer-policy/4K+1/gen/top.http-rp/unset/a-tag.http.html
    * /referrer-policy/4K-1/gen/top.http-rp/unset/a-tag.http.html
    * /referrer-policy/4K+1/gen/top.meta/no-referrer-when-downgrade/a-tag.http.html
    * /referrer-policy/4K-1/gen/top.meta/no-referrer-when-downgrade/a-tag.http.html
    * /referrer-policy/4K-1/gen/top.meta/no-referrer-when-downgrade/iframe-tag.http.html
    * /referrer-policy/4K+1/gen/top.meta/origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/4K-1/gen/top.meta/origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/4K+1/gen/top.meta/same-origin/a-tag.http.html
    * /referrer-policy/4K-1/gen/top.meta/same-origin/a-tag.http.html
    * /referrer-policy/4K+1/gen/top.meta/same-origin/iframe-tag.http.html
    * /referrer-policy/4K-1/gen/top.meta/same-origin/iframe-tag.http.html
    * /referrer-policy/4K+1/gen/top.meta/strict-origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/4K-1/gen/top.meta/strict-origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/4K-1/gen/top.meta/strict-origin-when-cross-origin/iframe-tag.http.html
    * /referrer-policy/4K+1/gen/top.meta/unsafe-url/a-tag.http.html
    * /referrer-policy/4K-1/gen/top.meta/unsafe-url/a-tag.http.html
    * /referrer-policy/4K+1/gen/top.meta/unset/a-tag.http.html
    * /referrer-policy/4K-1/gen/top.meta/unset/a-tag.http.html
    * /referrer-policy/4K/gen/top.http-rp/no-referrer-when-downgrade/a-tag.http.html
    * /referrer-policy/4K/gen/top.http-rp/origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/4K/gen/top.http-rp/same-origin/a-tag.http.html
    * /referrer-policy/4K/gen/top.http-rp/strict-origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/4K/gen/top.http-rp/unsafe-url/a-tag.http.html
    * /referrer-policy/4K/gen/top.http-rp/unset/a-tag.http.html
    * /referrer-policy/4K/gen/top.http-rp/unset/iframe-tag.http.html
    * /referrer-policy/4K/gen/top.meta/no-referrer-when-downgrade/a-tag.http.html
    * /referrer-policy/4K/gen/top.meta/origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/4K/gen/top.meta/origin-when-cross-origin/iframe-tag.http.html
    * /referrer-policy/4K/gen/top.meta/same-origin/a-tag.http.html
    * /referrer-policy/4K/gen/top.meta/same-origin/iframe-tag.http.html
    * /referrer-policy/4K/gen/top.meta/strict-origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/4K/gen/top.meta/unsafe-url/a-tag.http.html
    * /referrer-policy/4K/gen/top.meta/unset/a-tag.http.html
    * /referrer-policy/generic/inheritance/iframe-inheritance-history-about-blank.html
    * /referrer-policy/generic/inheritance/iframe-inheritance-history-about-srcdoc.html
    * /referrer-policy/generic/subresource-test/link-navigate.html
    * /referrer-policy/gen/iframe.http-rp/no-referrer/iframe-tag.http.html
    * /referrer-policy/gen/iframe.http-rp/origin/a-tag.http.html
    * /referrer-policy/gen/iframe.http-rp/origin/iframe-tag.http.html
    * /referrer-policy/gen/iframe.http-rp/origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/gen/iframe.http-rp/origin-when-cross-origin/iframe-tag.http.html
    * /referrer-policy/gen/iframe.http-rp/strict-origin/a-tag.http.html
    * /referrer-policy/gen/iframe.http-rp/strict-origin-when-cross-origin/iframe-tag.http.html
    * /referrer-policy/gen/iframe.http-rp/unsafe-url/iframe-tag.http.html
    * /referrer-policy/gen/iframe.http-rp/unset/fetch.http.html
    * /referrer-policy/gen/iframe.http-rp/unset/iframe-tag.http.html
    * /referrer-policy/gen/iframe.meta/always/a-tag.http.html
    * /referrer-policy/gen/iframe.meta/never/fetch.http.html
    * /referrer-policy/gen/iframe.meta/origin-when-crossorigin/iframe-tag.http.html
    * /referrer-policy/gen/iframe.meta/same-origin/a-tag.http.html
    * /referrer-policy/gen/iframe.meta/same-origin/iframe-tag.http.html
    * /referrer-policy/gen/iframe.meta/strict-origin/iframe-tag.http.html
    * /referrer-policy/gen/iframe.meta/strict-origin/xhr.http.html
    * /referrer-policy/gen/iframe.meta/unsafe-url/iframe-tag.http.html
    * /referrer-policy/gen/iframe.meta/unset/iframe-tag.http.html
    * /referrer-policy/gen/req.attr/no-referrer/a-tag.http.html
    * /referrer-policy/gen/req.attr/no-referrer/iframe-tag.http.html
    * /referrer-policy/gen/req.attr/no-referrer-when-downgrade/a-tag.http.html
    * /referrer-policy/gen/req.attr/origin/a-tag.http.html
    * /referrer-policy/gen/req.attr/origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/gen/req.attr/same-origin/a-tag.http.html
    * /referrer-policy/gen/req.attr/same-origin/iframe-tag.http.html
    * /referrer-policy/gen/req.attr/strict-origin/a-tag.http.html
    * /referrer-policy/gen/req.attr/strict-origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/gen/req.attr/unsafe-url/a-tag.http.html
    * /referrer-policy/gen/req.rel-noref/no-referrer/a-tag.http.html
    * /referrer-policy/gen/top.http-rp/no-referrer/a-tag.http.html
    * /referrer-policy/gen/top.http-rp/no-referrer-when-downgrade/a-tag.http.html
    * /referrer-policy/gen/top.http-rp/origin/a-tag.http.html
    * /referrer-policy/gen/top.http-rp/origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/gen/top.http-rp/same-origin/a-tag.http.html
    * /referrer-policy/gen/top.http-rp/strict-origin/a-tag.http.html
    * /referrer-policy/gen/top.http-rp/strict-origin/iframe-tag.http.html
    * /referrer-policy/gen/top.http-rp/strict-origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/gen/top.http-rp/unsafe-url/a-tag.http.html
    * /referrer-policy/gen/top.http-rp/unset/a-tag.http.html
    * /referrer-policy/gen/top.http-rp/unset/iframe-tag.http.html
    * /referrer-policy/gen/top.meta/always/a-tag.http.html
    * /referrer-policy/gen/top.meta/always/iframe-tag.http.html
    * /referrer-policy/gen/top.meta/default/a-tag.http.html
    * /referrer-policy/gen/top.meta/never/a-tag.http.html
    * /referrer-policy/gen/top.meta/never/iframe-tag.http.html
    * /referrer-policy/gen/top.meta/no-referrer/a-tag.http.html
    * /referrer-policy/gen/top.meta/no-referrer-when-downgrade/a-tag.http.html
    * /referrer-policy/gen/top.meta/origin/a-tag.http.html
    * /referrer-policy/gen/top.meta/origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/gen/top.meta/origin-when-crossorigin/a-tag.http.html
    * /referrer-policy/gen/top.meta/same-origin/a-tag.http.html
    * /referrer-policy/gen/top.meta/strict-origin/a-tag.http.html
    * /referrer-policy/gen/top.meta/strict-origin/iframe-tag.http.html
    * /referrer-policy/gen/top.meta/strict-origin-when-cross-origin/a-tag.http.html
    * /referrer-policy/gen/top.meta/unsafe-url/a-tag.http.html
    * /referrer-policy/gen/top.meta/unset/a-tag.http.html
    * /resource-timing/iframe-non-html.html
    * /resource-timing/nested-context-navigations-iframe.html
    * /resource-timing/resource-reload-TAO.html
    * /url/percent-encoding.window.html
    * /wasm/jsapi/functions/entry.html
    * /_webgl/conformance/context/context-release-upon-reload.html
    * /_webgl/conformance/context/context-release-with-workers.html
    * /webmessaging/broadcastchannel/cross-partition.https.tentative.html
    * /webmessaging/multi-globals/messageport-current.html
    * /webmessaging/multi-globals/messageport-incumbent.html
    * /websockets/cookies/003.html?default
    * /websockets/cookies/003.html?wpt_flags=h2
    * /websockets/cookies/003.html?wss&wpt_flags=https
    * /websockets/cookies/004.html?default
    * /websockets/cookies/004.html?wss&wpt_flags=https
    * /websockets/cookies/005.html?default
    * /websockets/cookies/005.html?wss&wpt_flags=https
    * /websockets/multi-globals/message-received.html
    * /websockets/unload-a-document/003.html
    * /websockets/unload-a-document/004.html
    * /webstorage/event_basic.html
    * /webstorage/event_body_attribute.html
    * /webstorage/event_case_sensitive.html
    * /webstorage/event_setattribute.html
    * /workers/semantics/navigation/001.html
    * /workers/semantics/navigation/002.html
    * /xhr/open-url-multi-window-5.htm
* layout 2013
    * /resource-timing/opaque-origin.html

### PR DESCRIPTION
**Pull request by mrobinson**
Post layout, when a `Window` has all of the new `<iframe>` sizes, size
any `Window`s for `Pipeline`s in the same `ScriptThread` synchronously.
This ensures that when laying out from the outermost frame to the
innermost frames, the frames sizes are set properly.

There is still an issue where a non-same-`ScriptThread` `<iframe>` sits
in between two `<iframe>`s of the same origin. According to the
specification these frames should all be synchrnously laid out --
something quite difficult in Servo. This is issue #34655.

This is the first change in a series of changes to improve the
consistency of `<iframe>` loading and sizing.

Fixes #14719.
Fixes #24569.
Fixes #24571.
Fixes #25269.
Fixes #25275.
Fixes #25285.
Fixes #30571.

Signed-off-by: Martin Robinson <mrobinson@igalia.com>

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] There are tests for these changes.

### CODE REVIEW

File: components/script/dom/window.rs [hunk 1]
```diff
@@ -1984,6 +1986,23 @@ impl Window {
             return;
         }
 
+        // Send resize message to any local `Pipeline`s synchronously, so that the value
```
Comment (gterzian) [inline components/script/dom/window.rs:1989]: "synchronously" makes it sound like you are blocking on the sending of messages, so I think it's more precise to write that you are batching those messages locally for them to be handled at the next update the rendering(which is better than writing "layout", because the concept is more clearly defined across layout and script boundaries thanks to the html spec).

File: components/script/dom/window.rs [hunk 2]
```diff
@@ -1984,6 +1986,23 @@ impl Window {
...
+                        initial_viewport: iframe_size.size,
+                        device_pixel_ratio,
+                    },
+                    // TODO: This might send an extra resize event. This can fixed by explicitly
+                    // supporting `<iframe>` creation when the size isn't known yet.
+                    WindowSizeType::Resize,
+                );
+            }
+        });
         // Send asynchronous updates to `Constellation.`
```
Comment (gterzian) [inline components/script/dom/window.rs:2006]: I think all of these will now result in receiving resize messages back from the constellation, in which case we need to write down somewhere what the proposed re-design is, which probably should include making a distinction between resizes that have already been batched locally at the script-thread(for same-origin iframes), and those that need to be propagated to other script-threads via the constellation. Describing this in an issue for a follow-up is a good idea I think.

**Review by gterzian — APPROVED** [review]
LGTM with some comments

File: components/script/dom/window.rs (hunk 2 above)
Comment (gterzian) [reply components/script/dom/window.rs:2006]: Also one last note on the topic of "According to the
specification these frames should all be synchrnously laid out", I think the way to do that in Servo would be to still first batch the resizes locally, but somehow only process them as part of an rendering update when the cross-origin resizes have been taken into account as well. So in other words, instead of batching them for the next udpate, they'd have to be batched for "an update in the future" which would somehow take into account the resizing of the cross-origin iframes, and this "transaction" across script-thread would have be to brokered by the constellation. I think it's also a good idea to start discussing in more details in an issue.

File: components/script/dom/window.rs (hunk 1 above)
Comment (mrobinson) [reply components/script/dom/window.rs:1989]: Okay. I've reworded this a bit to be clearer.

File: components/script/dom/window.rs (hunk 2 above)
Comment (mrobinson) [reply components/script/dom/window.rs:2006]: It's a great idea to document the new design. This change fixes the issue in the majority of cases, but there are still some tricky cases where many resize events flooding the `Constellation` could lead to flashing layout. I hope to address those in a followup change, but the solution will affect the final design. Maybe I can have a section of the book ready with the design once I've worked through all of the issues.

Regarding whether or not we need synchronous layout of the entire frame tree (I'm not convinced we don't need it yet), I agree it's good to discuss more in #34655.

**Comment by mrobinson** [comment]
Thanks for the review!
