### PR TITLE
script: do not update `Document` rendering when waiting on asynchronous canvas image updates

### LINKED ISSUE #39021: update the rendering of document does not wait for images
I think we have a problem with https://sagudev.github.io/briefcase/canvas2d/objectmark.html?step=100. Now at 400 object it just freeze (that's the point we go under 30 FPS on my pc).

this is regression by https://github.com/servo/servo/commit/8beef6c21f312e33e9b445e2b0d0165116c9b087
also before hitting that mark frame skip is very visible

from https://html.spec.whatwg.org/multipage/webappapis.html#rendering-opportunity: 
> This specification does not mandate any particular model for selecting rendering opportunities. But for example, if the browser is attempting to achieve a 60Hz refresh rate, then rendering opportunities occur at a maximum of every 60th of a second (about 16.7ms). If the browser finds that a [navigable](https://html.spec.whatwg.org/multipage/document-sequences.html#navigable) is not able to sustain this rate, it might drop to a more sustainable 30 rendering opportunities per second for that [navigable](https://html.spec.whatwg.org/multipage/document-sequences.html#navigable), rather than occasionally dropping frames. Similarly, if a [navigable](https://html.spec.whatwg.org/multipage/document-sequences.html#navigable) is not visible, the user agent might decide to drop that page to a much slower 4 rendering opportunities per second, or even less.

I think we never actually read waiting_on_canvas_image_updates in script

Fix is incoming.

### PR DESCRIPTION
**Pull request by sagudev**
This is fixup for #37776. We forget to skip documents with waiting_on_canvas_image_updates flag.

Testing: Existing WPT tests and manual testing
Fixes: #39021

### CODE REVIEW

File: components/script/dom/document.rs [hunk 1]
```diff
@@ -570,6 +570,10 @@ pub(crate) struct Document {
 
 #[allow(non_snake_case)]
 impl Document {
+    pub(crate) fn waiting_on_canvas_image_updates(&self) -> bool {
+        self.waiting_on_canvas_image_updates.get()
+    }
```
Comment (mrobinson) [inline components/script/dom/document.rs]: Please move this right below the definition of `fn handle_no_longer_waiting_on_asynchronous_image_updates` so that the related code stays together.

**Review by mrobinson — APPROVED** [review]
Thanks for the fix!

File: components/script/dom/document.rs (hunk 1 above)
Comment (sagudev) [reply components/script/dom/document.rs]: Done in https://github.com/servo/servo/pull/39022/commits/9f96de20dc3382a6ff6f5259f229f9e910ceb8cc.
