### PR TITLE
Position insertion point in input field with mouse

### LINKED ISSUE #10083: input / textarea - mouse interaction doesn't work
clicking on a specific position doesn't move the cursor to that specific position.
selection with the mouse doesn't work

### PR DESCRIPTION
**Pull request by fiji-flo**
Implements cursor positioning in input elements (text/password) via mouse. The related issue is #10083 but is only covered partly.
This PR does **not** cover:
* positioning in textarea elements via mouse
* text selection in input/textarea elements via mouse

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #10083 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because I can't think of a way to test mouse interaction in the current test pipeline.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14291)

### CODE REVIEW

**Comment by jdm** [comment]
@nox review ping.

**Comment by fiji-flo** [comment]
I rebased my branch to solve some merge conflicts.

**Comment by jdm** [comment]
@nox Review ping.

**Comment by nox** [comment]
I know nothing about gfx and layout. r? @pcwalton

File: components/script/dom/window.rs [hunk 1]
```diff
@@ -1332,6 +1332,16 @@ impl Window {
         self.layout_rpc.margin_style()
     }
 
+    pub fn text_index_query(&self, node: TrustedNodeAddress, mouse_x: i32, mouse_y: i32) -> TextIndexResponse {
+        if !self.reflow(ReflowGoal::ForScriptQuery,
+                        ReflowQueryType::TextIndexQuery(node, mouse_x, mouse_y),
+                        ReflowReason::Query) {
+            println!("failed in reflow");
```
Comment (emilio) [inline components/script/dom/window.rs]: remove.

File: components/script_layout_interface/rpc.rs [hunk 2]
```diff
@@ -92,3 +94,6 @@ impl MarginStyleResponse {
         }
     }
 }
+
+#[derive(Clone)]
+pub struct TextIndexResponse(pub Option<(usize)>);
```
Comment (emilio) [inline components/script_layout_interface/rpc.rs]: Why not just `TextIndexResponse(pub Option<usize>)`?

File: components/gfx/text/text_run.rs [hunk 3]
```diff
@@ -304,6 +304,24 @@ impl<'a> TextRun {
         })
     }
 
+    /// Returns the index in the range of the first glyph advancing over given advance
+    pub fn range_index_of_advance(&self, range: &Range<ByteIndex>, advance: Au) -> Option<usize> {
+        if range.is_empty() {
```
Comment (emilio) [inline components/gfx/text/text_run.rs]: Is this check necessary? Doesn't `natural_words_in_range` handle empty ranges?

Also, this function seems to always return `Some(..)`, so why not returning just an `usize`?

**Review by emilio — COMMENTED** [review]
Only minor nits. The approach in general makes sense to me (I'd need to review way more carefully though). Seems like @pcwalton can review this with less effort than I.

**Comment by fiji-flo** [comment]
@emilio Thanks for the first round of feedback. I'll go over it today.

**Comment by fiji-flo** [comment]
@jdm @pcwalton: I rebased and squashed the changes I did after emilio's comments. Could I get some feedback here?

**Comment by jdm** [comment]
I'm really sorry about how this work has been received so far @fiji-flo ! I'll make sure it gets some traction today.

File: components/gfx/text/glyph.rs [hunk 4]
```diff
@@ -547,6 +547,27 @@ impl<'a> GlyphStore {
...
+                } else {
+                    current_advance += glyph.advance()
+                }
+                if current_advance > advance {
+                    false
+                } else {
+                    index += 1;
+                    true
+                }
+            }).collect::<Vec<_>>();
```
Comment (pcwalton) [inline components/gfx/text/glyph.rs]: It looks like you're collecting this into a vector and then throwing it away.

I recommend just using a for loop:

    for glyph in self.iter_glyphs_for_byte_range(range) {
        ...
    }

File: components/gfx/display_list/mod.rs [hunk 5]
```diff
@@ -139,8 +204,22 @@ impl DisplayList {
...
         };
+    }
 
-        self.hit_test_contents(traversal, &translated_point, client_point, scroll_offsets, result);
+    #[inline]
+    fn scroll_root<'a>(scroll_root: &ScrollRoot,
+                       translated_point: &mut Point2D<Au>,
+                       scroll_offsets: &ScrollOffsetMap) {
+        // Adjust the translated point to account for the scroll offset if
+        // necessary. This can only happen when WebRender is in use.
```
Comment (pcwalton) [inline components/gfx/display_list/mod.rs]: While you're here, could you remove the "This can only happen when WebRender is in use." bit? WebRender is always enabled now.

File: components/gfx/display_list/mod.rs [hunk 6]
```diff
@@ -99,38 +176,26 @@ impl DisplayList {
...
-        // the DOM-side code has already translated the point for us (e.g. in
-        // `Window::hit_test_query()`) by now.
-        if let Some(scroll_offset) = scroll_offsets.get(&scroll_root.id) {
-            translated_point.x -= Au::from_f32_px(scroll_offset.x);
-            translated_point.y -= Au::from_f32_px(scroll_offset.y);
-        }
-        self.hit_test_contents(traversal, &translated_point, client_point, scroll_offsets, result);
-    }
-
     fn hit_test_stacking_context<'a>(&self,
```
Comment (pcwalton) [inline components/gfx/display_list/mod.rs]: Could you add a comment explaining that this function translates the point to account for the scroll offset?

File: components/gfx/display_list/mod.rs (hunk 5 above)
Comment (fiji-flo) [inline components/gfx/display_list/mod.rs]: Sure.

File: components/gfx/text/glyph.rs (hunk 4 above)
Comment (fiji-flo) [inline components/gfx/text/glyph.rs]: Indeed. My bad.

File: components/gfx/display_list/mod.rs (hunk 6 above)
Comment (fiji-flo) [inline components/gfx/display_list/mod.rs]: I'm not sure if get which function you're referring to? While adopting to your comments if removed `hit_test_stacking_context` to make it more readable.

**Comment by fiji-flo** [comment]
@jdm thanks for pushing
@pcwalton thanks for the feedback

I adopted my changes to the feedback, rebased and squashed.

File: components/gfx/text/glyph.rs [hunk 7]
```diff
@@ -547,6 +547,25 @@ impl<'a> GlyphStore {
...
+        let mut current_advance = Au(0);
+        for glyph in self.iter_glyphs_for_byte_range(range) {
+            if glyph.char_is_space() {
+                current_advance += glyph.advance() + extra_word_spacing
+            } else {
+                current_advance += glyph.advance()
+            }
+            if current_advance > advance {
+                break;
+            } else {
```
Comment (pcwalton) [inline components/gfx/text/glyph.rs]: nit: No need for `else` after `break`.

File: components/gfx/text/glyph.rs [hunk 8]
```diff
@@ -547,6 +547,25 @@ impl<'a> GlyphStore {
     }
 
     #[inline]
+    pub fn range_index_of_advance(&self, range: &Range<ByteIndex>, advance: Au, extra_word_spacing: Au) -> (usize, Au) {
```
Comment (pcwalton) [inline components/gfx/text/glyph.rs]: Please document what the return values of this function are in a comment.

File: components/gfx/text/text_run.rs [hunk 9]
```diff
@@ -304,6 +304,20 @@ impl<'a> TextRun {
...
+    pub fn range_index_of_advance(&self, range: &Range<ByteIndex>, advance: Au) -> usize {
+        // TODO(Issue #199): alter advance direction for RTL
+        // TODO(Issue #98): using inter-char and inter-word spacing settings when measuring text
+        let mut remaining = advance;
+        self.natural_word_slices_in_range(range)
+            .fold(0, |index, slice| {
+                let (new_index, new_remaining) =
+                    slice.glyphs.range_index_of_advance(&slice.range, remaining, self.extra_word_spacing);
+                remaining = new_remaining;
+                new_index + index
```
Comment (pcwalton) [inline components/gfx/text/text_run.rs]: Isn't there a `sum` method on iterators?

**Review by pcwalton — COMMENTED** [review]
This is looking pretty good, just a couple more nits

File: components/gfx/text/glyph.rs (hunk 8 above)
Comment (fiji-flo) [inline components/gfx/text/glyph.rs]: While describing what this function returns I realized that it's more intuitive if it returns `(index, current_advance)` instead of `(index, advance -current_advance)`. This just needed a slight modification in the part that invokes this.
I'll add some comments after I push the modifications.

File: components/gfx/text/text_run.rs (hunk 9 above)
Comment (fiji-flo) [inline components/gfx/text/text_run.rs]: I guess you mean doing a `map` and `sum` which would indeed look nicer. That's just a habit from my early haskell days.

**Comment by fiji-flo** [comment]
Thanks for the feedback. Adopted and squashed.

File: components/gfx/text/text_run.rs [hunk 10]
```diff
@@ -304,6 +304,21 @@ impl<'a> TextRun {
...
+    /// Returns the index in the range of the first glyph advancing over given advance
+    pub fn range_index_of_advance(&self, range: &Range<ByteIndex>, advance: Au) -> usize {
+        // TODO(Issue #199): alter advance direction for RTL
+        // TODO(Issue #98): using inter-char and inter-word spacing settings when measuring text
+        let mut remaining = advance;
+        self.natural_word_slices_in_range(range)
+            .map(|slice| {
+                let (slice_index, slice_advance) =
+                    slice.glyphs.range_index_of_advance(&slice.range, remaining, self.extra_word_spacing);
+                remaining -= slice_advance;
```
Comment (fiji-flo) [inline components/gfx/text/text_run.rs]: @pcwalton `glyphs.range_index_of_advance` now returns `(index, advanced)` instead of `(index, remaining)` to make it more intuitive. Therefore we need to update `remaining` here.

**Comment by paulrouget** [comment]
This caused a regression: https://github.com/servo/servo/issues/15015
