### PR TITLE
mach: Android: Support custom profiles

### LINKED ISSUE #34564: mach: Android packaging does not support custom build profiles
**Describe the bug:**
https://github.com/servo/servo/blob/e10e989abb884f3c83a5c35d4c1b1be887ec0bb1/python/servo/package_commands.py#L163 currently only supports the dev and release profile.
This information is used later during the packaging to determine the location of the `libservoshell.so` artifact.

**To Reproduce:**
./mach build --android --profile=medium

**Platform:**
Android

### PR DESCRIPTION
**Pull request by jschwe**
Use Release mode for gradle for production builds and Debug for any other builds.
This fixes an exception when building for android with a custom cargo profile.
`SERVO_TARGET_DIR` is read in `apk/jni/Android.mk` and specifies the folder 
libservoshell.so is expected to be in.

Testing: Tested manually with `./mach build --android --production`
Fixes: #34564

### CODE REVIEW

File: support/android/apk/buildSrc/src/main/kotlin/Interop.kt [hunk 1]
```diff
@@ -15,7 +15,11 @@ fun Project.getTargetDir(debug: Boolean, arch: String): String {
 
 fun Project.getNativeTargetDir(debug: Boolean, arch: String): String {
     val basePath = project.rootDir.parentFile.parentFile.parentFile.absolutePath
-    return basePath + "/target/" + getSubTargetDir(debug, arch)
+    val fallback = basePath + "/target/" + getSubTargetDir(debug, arch)
+    // Prefer the value provided by `mach`, which supports custom cargo profiles.
+    // The Fallback is for packaging in Android studio, after a mach build (only debug / release).
```
Comment (mukilan) [inline support/android/apk/buildSrc/src/main/kotlin/Interop.kt]:
```suggestion
    // The fallback is for packaging in Android studio, after a mach build (only debug / release).
```

File: python/servo/command_base.py [hunk 2]
```diff
@@ -77,7 +77,7 @@ def is_release(self) -> bool:
         return self.kind == BuildType.Kind.RELEASE
 
     def is_prod(self) -> bool:
-        return self.kind == BuildType.Kind.CUSTOM and self.profile == "production"
+        return self.is_custom() and (self.profile == "production" or self.profile == "production-stripped")
```
Comment (mukilan) [inline python/servo/command_base.py]:
```suggestion
        return self.is_custom() and (self.profile in ["production", "production-stripped"])
```

**Review by mukilan — APPROVED** [review]
Thanks!
