### PR TITLE
Fix brew formula update

### LINKED ISSUE #535: Homebrew nightly build not updated anymore (since 11/4)
```
./etc/ci/update_brew.sh
 in dir /Users/servo/buildbot/slave/mac-nightly/build (timeout 1200 secs)
 watching logfiles {}
 argv: ['./etc/ci/update_brew.sh']
 using PTY: False
ls: target/brew/servo-????-??-??.tar.gz: No such file or directory
program finished with exit code 1
elapsedTime=0.017824
```

### PR DESCRIPTION
**Pull request by paulrouget**
Fix https://github.com/servo/saltfs/issues/535

I decided to merge update_brew within upload_nightly.

I hope this will fix the brew formula upadte.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14403)

### CODE REVIEW

File: etc/ci/upload_nightly.sh [hunk 1]
```diff
@@ -16,16 +16,60 @@ usage() {
...
+    local -r nightly_upload_dir="s3://servo-builds/nightly/${platform}"
     local -r package_upload_path="${nightly_upload_dir}/${nightly_filename}"
     s3cmd --mime-type="application/octet-stream" \
-          put "${2}" "${package_upload_path}"
-    s3cmd cp "${package_upload_path}" "${nightly_upload_dir}/servo-latest.${3}"
+      put "${package}" "${package_upload_path}"
+    s3cmd cp "${package_upload_path}" \
+      "${nightly_upload_dir}/servo-latest.${extension}"
+
+    if [[ "${platform}" == "macbrew" ]]
```
Comment (aneeshusa) [inline etc/ci/upload_nightly.sh]: style nit: put the `then` on the same line

File: etc/ci/upload_nightly.sh [hunk 2]
```diff
@@ -16,16 +16,60 @@ usage() {
...
+  local -r nightly_filename="${1}"
+  local -r package="${2}"
+  local -r nightly_timestamp="${3}"
+
+  local package_url sha version script_dir tmp_dir
+
+  package_url="https://download.servo.org/nightly/macbrew/${nightly_filename}"
+  sha=$(shasum -a 256 ${package} | sed -e 's/ .*//')
+  version=$(echo "${nightly_timestamp}" | \
+    sed -n 's/\([0-9]\{4\}\)-\([0-9]\{2\}\)-\([0-9]\{2\}\).*/\1.\2.\3/p')
```
Comment (aneeshusa) [inline etc/ci/upload_nightly.sh]: Can you add a comment about what this regex is doing?

File: etc/ci/upload_nightly.sh [hunk 3]
```diff
@@ -16,16 +16,60 @@ usage() {
...
+  echo "Updating brew formula"
+
+  local -r nightly_filename="${1}"
+  local -r package="${2}"
+  local -r nightly_timestamp="${3}"
+
+  local package_url sha version script_dir tmp_dir
+
+  package_url="https://download.servo.org/nightly/macbrew/${nightly_filename}"
+  sha=$(shasum -a 256 ${package} | sed -e 's/ .*//')
```
Comment (aneeshusa) [inline etc/ci/upload_nightly.sh]: Make sure to double-quote variables and command substitutions per the [style guide](https://github.com/servo/servo/blob/master/docs/STYLE_GUIDE.md).

File: etc/ci/upload_nightly.sh [hunk 4]
```diff
@@ -16,16 +16,60 @@ usage() {
...
+  cat ${script_dir}/servo-binary-formula.rb.in | sed \
+    "s|PACKAGEURL|${package_url}|g
+     s|SHA|${sha}|g
+     s|VERSION|${version}|g" > Formula/servo-bin.rb
+
+  git add ./Formula/servo-bin.rb
+  git commit -m "Version bump: ${version}"
+
+  git push -qf \
+      "https://${TOKEN}@github.com/servo/homebrew-servo.git" master \
```
Comment (aneeshusa) [inline etc/ci/upload_nightly.sh]: Please rename the `TOKEN` to be less generic, something like `HOMEBREW_PUSH_TOKEN`.

**Review by aneeshusa — COMMENTED** [review]
Sorry about the delay, the approach looks reasonable. This will require a PR to saltfs to pass the homebrew token to this script instead of the `update_brew.sh` script.

File: etc/ci/upload_nightly.sh [hunk 5]
```diff
@@ -16,25 +16,61 @@ usage() {
...
 }
 
+update_brew() {
+  echo "Updating brew formula"
+
+  local package_url sha version script_dir tmp_dir nightly_filename
+
+  nightly_filename="${2}-$(basename "${1}")"
+  package_url="https://download.servo.org/nightly/macbrew/${nightly_filename}"
+  sha="$(shasum -a 256 ${1} | sed -e 's/ .*//')"
```
Comment (aneeshusa) [inline etc/ci/upload_nightly.sh]: nit: Double-quote `"${1}"`

File: etc/ci/upload_nightly.sh [hunk 6]
```diff
@@ -16,25 +16,61 @@ usage() {
...
+
+  # This will transform a timestamp (2016-12-13T08-01-10Z for example)
+  # into a valid brew version number (2016.12.13).
+  version="$(echo "${2}" | \
+    sed -n 's/\([0-9]\{4\}\)-\([0-9]\{2\}\)-\([0-9]\{2\}\).*/\1.\2.\3/p')"
+
+  script_dir="${PWD}/$(dirname "${0}")"
+  tmp_dir="$(mktemp -d -t homebrew-servo)"
```
Comment (aneeshusa) [inline etc/ci/upload_nightly.sh]: Add some uppercase `X`s to the end of the template, i.e. `homebrew-servo.XXXXXXXXX`, so not the temporary directory used is randomized.

File: etc/ci/upload_nightly.sh [hunk 7]
```diff
@@ -16,25 +16,61 @@ usage() {
...
+       > Formula/servo-bin.rb
+
+  git add ./Formula/servo-bin.rb
+  git commit -m "Version bump: ${version}"
+
+  git push -qf \
+      "https://${GITHUB_HOMEBREW_TOKEN}@github.com/servo/homebrew-servo.git" \
+      master >/dev/null 2>&1
+
+  rm -rf ${tmp_dir}
```
Comment (aneeshusa) [inline etc/ci/upload_nightly.sh]: Please double-quote `"${tmp_dir}"`.
Also, we're still inside the directory at this point (it's the pwd), so I'm not sure how we're able to delete it...we should `cd` back to somewhere else (e.g. the `"${script_dir}"`) first.

Comment (aneeshusa) [inline etc/ci/upload_nightly.sh]: An alternative to using `cd` entirely is using the `-C` argument for the git invocations, e.g. `git -C "${tmp_dir}" add ...` and editing the path in the sed invocation to `"${tmp_dir}/Formula/servo-bin.rb"`. This avoids `cd` completely, which I find nicer to reason about.

**Review by aneeshusa — CHANGES_REQUESTED** [review]
Just a few last nits.

File: etc/ci/upload_nightly.sh (hunk 5 above)
Comment (paulrouget) [inline etc/ci/upload_nightly.sh]: Not sure how to properly do that. `\"` doesn't work for some reason.

File: etc/ci/upload_nightly.sh (hunk 6 above)
Comment (paulrouget) [inline etc/ci/upload_nightly.sh]: iirc, that's only try on Line. mktemp on mack adds a postfix automatically.

File: etc/ci/upload_nightly.sh (hunk 7 above)
Comment (paulrouget) [inline etc/ci/upload_nightly.sh]: ok

File: etc/ci/upload_nightly.sh (hunk 5 above)
Comment (aneeshusa) [inline etc/ci/upload_nightly.sh]: `$()` creates a new quoting context, so you should be able to just do `"$(shasum -a 256 "${1}" | sed ...)"`

File: etc/ci/upload_nightly.sh (hunk 6 above)
Comment (aneeshusa) [inline etc/ci/upload_nightly.sh]: Oh, I didn't know that, that's a nice feature. Still might be nice to have in case this gets blindly copy-pasted out of context later, but up to you if you want to change it.

File: etc/ci/upload_nightly.sh (hunk 5 above)
Comment (paulrouget) [inline etc/ci/upload_nightly.sh]: oh right. It works.

**Comment by paulrouget** [comment]
Comments addressed.

**Comment by aneeshusa** [comment]
LGTM, thanks for fixing this! @bors-servo r+

**Review by aneeshusa — APPROVED** [review]

**Comment by paulrouget** [comment]
@bors-servo: retry
- Checking if intermittent.
