### PR TITLE
Solved wrong referrer policy in cors_preflight_fetch

### LINKED ISSUE #13026: Wrong referrer policy used in cors_preflight_request
The specification for [step 1](https://fetch.spec.whatwg.org/#cors-preflight-fetch) says we should use `request`'s referrer policy. There's an obvious copy/paste typo that uses the default request policy for the new `preflight` variable instead.

Code: `components/net/fetch/methods.rs`
Test: modify `test_cors_preflight_fetch` in `tests/unit/net/fetch.rs` by setting the original referrer policy used to `origin` and setting a URL referrer a path (`a.html`), and checking that the referrer header that the server receives does not contain the path. Run the test with `./mach test-unit -p net`.

### PR DESCRIPTION
**Pull request by wdv4758h**
Solved wrong referrer policy in cors_preflight_fetch
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13026 
- [X] There are tests for these changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13071)

### CODE REVIEW

File: tests/unit/net/fetch.rs [hunk 1]
```diff
@@ -213,15 +213,20 @@ fn test_cors_preflight_fetch() {
     };
     let (mut server, url) = make_server(handler);
 
+    let target_url = url.clone().join("a.html").unwrap();
+    let desired_response_url = url.clone();
```
Comment (KiChjang) [inline tests/unit/net/fetch.rs]: This looks unnecessary since it's the same as `url`.

**Comment by jdm** [comment]
This is good, but we're not testing the actual referrer that is sent with the preflight request right now. We should add an appropriate assertion inside the first `if` branch in the handler function, too.

File: tests/unit/net/fetch.rs (hunk 1 above)
Comment (wdv4758h) [inline tests/unit/net/fetch.rs]: The `url` will be moved to `request`, but I think it will be better to clone when building `request`.

**Comment by wdv4758h** [comment]
@jdm checking the header ?

**Comment by jdm** [comment]
@wdv4758h [This](https://dxr.mozilla.org/servo/source/tests/unit/net/fetch.rs?q=path%3Afetch.rs&redirect_type=single#204) is an example - it's checking that the server receives a preflight request that includes the Access-Control-Request-Method HTTP header.

File: tests/unit/net/fetch.rs [hunk 2]
```diff
@@ -203,6 +204,7 @@ fn test_cors_preflight_fetch() {
         if request.method == Method::Options && state.clone().fetch_add(1, Ordering::SeqCst) == 0 {
             assert!(request.headers.has::<AccessControlRequestMethod>());
             assert!(request.headers.has::<AccessControlRequestHeaders>());
+            assert!(request.headers.has::<HyperReferer>());
```
Comment (jdm) [inline tests/unit/net/fetch.rs]: The important piece here is that we want to verify that the header does not contain `a.html`, since that should have been stripped out when we used the `Origin` referrer policy.

File: tests/unit/net/fetch.rs [hunk 3]
```diff
@@ -213,15 +215,19 @@ fn test_cors_preflight_fetch() {
...
+    let mut request = Request::new(url.clone(), Some(origin), false, None);
+    *request.referer.borrow_mut() = Referer::RefererUrl(target_url);
+    *request.referrer_policy.get_mut() = Some(ReferrerPolicy::Origin);
     request.use_cors_preflight = true;
     request.mode = RequestMode::CORSMode;
     let fetch_response = fetch_sync(request, None);
     let _ = server.close();
 
     assert!(!fetch_response.is_network_error());
+    assert_eq!(url, fetch_response.url.unwrap());
```
Comment (jdm) [inline tests/unit/net/fetch.rs]: Doesn't this assertion fail if you run `./mach test-unit -p net`?

**Comment by wdv4758h** [comment]
@jdm check again :)

File: tests/unit/net/fetch.rs (hunk 3 above)
Comment (wdv4758h) [inline tests/unit/net/fetch.rs]: no

File: tests/unit/net/fetch.rs (hunk 2 above)
Comment (wdv4758h) [inline tests/unit/net/fetch.rs]: So I should take it out and check the string.

File: tests/unit/net/fetch.rs (hunk 3 above)
Comment (jdm) [inline tests/unit/net/fetch.rs]: Oh right, because we're still using `url` for the target of the Request. Too many URLs to keep track of!

File: tests/unit/net/fetch.rs (hunk 2 above)
Comment (jdm) [inline tests/unit/net/fetch.rs]: You'll want the [get method](http://doc.servo.org/hyper/header/struct.Headers.html#method.get) and then look at the [internal value](http://doc.servo.org/hyper/header/struct.Referer.html).

File: tests/unit/net/fetch.rs (hunk 3 above)
Comment (wdv4758h) [inline tests/unit/net/fetch.rs]: I think I should remove it, right ?

Comment (wdv4758h) [inline tests/unit/net/fetch.rs]: As the checking is in the handler.

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

**Comment by jdm** [comment]
`./mach test-tidy` didn't like the change.

**Comment by wdv4758h** [comment]
Oops, I tought I run the `test-tidy` ...

**Comment by wdv4758h** [comment]
Fixed `test-tidy` .
