### PR TITLE
Avoid borrow panic when Path2D.addPath is called with self

### LINKED ISSUE #36842: panic: already mutably borrowed: BorrowError (at components/script/dom/path2d.rs:69)
Minimal testcase:

```
<!DOCTYPE html>
<script>
let path2D = new Path2D();
path2D.addPath(path2D);
</script>
```

System: Linux
Version: Servo 0.0.1-43edab336

```
already mutably borrowed: BorrowError (thread Script(1,1), at components/script/dom/path2d.rs:69)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::cell::panic_already_mutably_borrowed
   8: script_bindings::codegen::GenericBindings::CanvasRenderingContext2DBinding::Path2D_Binding::addPath::{{closure}}
   9: mozjs::panic::wrap_panic
  10: script_bindings::codegen::GenericBindings::CanvasRenderingContext2DBinding::Path2D_Binding::addPath
  11: CallJitMethodOp
  12: script_bindings::utils::generic_call
  13: script_bindings::utils::generic_method
  14: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  15: _ZN2js9InterpretEP9JSContextRNS_8RunStateE
  16: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  17: _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEENS3_IP8JSObjectEENS2_13MutableHandleINS2_5ValueEEE
  18: _Z16JS_ExecuteScriptP9JSContextN2JS6HandleIP8JSScriptEENS1_13MutableHandleINS1_5ValueEEE
  19: script::dom::globalscope::GlobalScope::evaluate_script_on_global_with_result
  20: script::dom::htmlscriptelement::HTMLScriptElement::execute
  21: script::dom::htmlscriptelement::HTMLScriptElement::prepare
  22: script::dom::servoparser::ServoParser::parse_sync
  23: <script::dom::servoparser::ParserContext as net_traits::FetchResponseListener>::process_response_chunk
  24: script::script_thread::ScriptThread::handle_msg_from_script
  25: script::script_thread::ScriptThread::handle_msgs::{{closure}}
  26: script::script_thread::ScriptThread::handle_msgs
  27: std::sys::backtrace::__rust_begin_short_backtrace
  28: core::ops::function::FnOnce::call_once{{vtable.shim}}
  29: std::sys::pal::unix::thread::Thread::new::thread_start
  30: start_thread
             at ./nptl/pthread_create.c:447:8
  31: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
```

### PR DESCRIPTION
**Pull request by Taym95**
Fixes: #36842

### CODE REVIEW

File: components/script/dom/path2d.rs [hunk 1]
```diff
@@ -65,8 +65,15 @@ impl Path2DMethods<crate::DomTypeHolder> for Path2D {
     /// <https://html.spec.whatwg.org/multipage/#dom-path2d-addpath>
     fn AddPath(&self, other: &Path2D) {
         // Step 7. Add all the subpaths in c to a.
-        let mut dest = self.path.borrow_mut();
-        dest.extend(other.path.borrow().iter().copied());
+        if &self.path == &other.path {
+            // Note: this is not part of the spec, but it is a workaround to
+            // avoids borrow conflict when path is same as other.path
+            let cloned_path = self.path.borrow().clone();
+            self.path.borrow_mut().extend(cloned_path.iter().copied());
```
Comment (simonwuelker) [inline components/script/dom/path2d.rs:72]: Can we use [`Vec::extend_from_within`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.extend_from_within) here instead?

**Review by simonwuelker — CHANGES_REQUESTED** [review]

File: components/script/dom/path2d.rs (hunk 1 above)
Comment (simonwuelker) [reply components/script/dom/path2d.rs:72]: `self.path.borrow_mut().extend_from_within(..)`

Comment (simonwuelker) [reply components/script/dom/path2d.rs:72]: > If it's a question, then no, you can't use extend_from_within here. You need the Vec’s length to call extend_from_within(0..len)

Since you want to clone the whole vec you don't need it's length. As i showed above you can use an infinite range instead (`..`).

This diff compiles and works as expected:

```diff
diff --git a/components/script/dom/path2d.rs b/components/script/dom/path2d.rs
index fabfac1b136..3e30db437bf 100644
--- a/components/script/dom/path2d.rs
+++ b/components/script/dom/path2d.rs
@@ -68,8 +68,7 @@ impl Path2DMethods<crate::DomTypeHolder> for Path2D {
         if &self.path == &other.path {
             // Note: this is not part of the spec, but it is a workaround to
             // avoids borrow conflict when path is same as other.path
-            let cloned_path = self.path.borrow().clone();
-            self.path.borrow_mut().extend(cloned_path.iter().copied());
+            self.path.borrow_mut().extend_from_within(..);
         } else {
             let mut dest = self.path.borrow_mut();
             dest.extend(other.path.borrow().iter().copied());
```

There's not a big difference between the two, but `extend_from_within` can save the intermediary allocation.

**Review by simonwuelker — APPROVED** [review]
