### PR TITLE
Fix GC borrow hazard in ResizeObserver::broadcast_active_resize_observations

### LINKED ISSUE #33864: GC borrow hazard in ResizeObserver::broadcast_active_resize_observations
We mutably borrow a member field in https://github.com/servo/servo/pull/33862/files#diff-2a44f61a5e5b7cf6b7a47e74a04dbec244b81507f0517bdc92484ba58e6e90c6R99 to iterate over them, the we allocate create new DOM objects in https://github.com/servo/servo/pull/33862/files#diff-2a44f61a5e5b7cf6b7a47e74a04dbec244b81507f0517bdc92484ba58e6e90c6R111 while that borrow is still active.

I see two possible solutions here:
1. change the borrow_mut() to a borrow() and wrap the members of ResizeObservation in Cell/RefCell (this delays the need for a mutable borrow until it's actually necessary to update a value)
2. instead of iterating over the values of self.observation_targets, loop over the indexes 0..self.observation_targets.borrow().len() and and then borrow to obtain the element at that index as necessary 

I think option 1 will result in more clear code.

### PR DESCRIPTION
**Pull request by taniishkaaa**
Fixes GC borrow hazard in ResizeObserver::broadcast_active_resize_observations

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #33864 
- [X] These changes do not require tests because they do not modify functionality

### CODE REVIEW

File: components/script/dom/resizeobserver.rs [hunk 1]
```diff
@@ -96,8 +97,10 @@ impl ResizeObserver {
         can_gc: CanGc,
     ) {
         let mut entries: Vec<DomRoot<ResizeObserverEntry>> = Default::default();
-        for (observation, target) in self.observation_targets.borrow_mut().iter_mut() {
-            let ObservationState::Active(box_size) = observation.state else {
+        let observation_targets = self.observation_targets.borrow();
+        for (observation, target) in observation_targets.iter() {
+            let mut observation_state = observation.state.borrow_mut();
```
Comment (jdm) [inline components/script/dom/resizeobserver.rs:102]: This mutable borrow has the same problem as the original issue—it's still active when we reach `let observer_size = ResizeObserverSize::new(&window, size_impl, can_gc);`.

File: components/script/dom/resizeobserver.rs [hunk 2]
```diff
@@ -151,7 +154,7 @@ impl ResizeObserver {
         self.observation_targets
             .borrow()
             .iter()
-            .any(|(observation, _)| observation.state == ObservationState::Skipped)
+            .any(|(observation, _)| observation.state == ObservationState::Skipped.into())
```
Comment (jdm) [inline components/script/dom/resizeobserver.rs:157]:
```suggestion
            .any(|(observation, _)| *observation.state.borow() == ObservationState::Skipped)
```

**Review by jdm — CHANGES_REQUESTED** [review]
Nearly there!

File: components/script/dom/resizeobserver.rs (hunk 1 above)
Comment (taniishkaaa) [reply components/script/dom/resizeobserver.rs]: updated 👍

File: components/script/dom/resizeobserver.rs [hunk 3]
```diff
@@ -138,7 +138,7 @@ impl ResizeObserver {
             // The spec plans to store multiple reported sizes,
             // but for now there can be only one.
             observation.last_reported_sizes.borrow_mut()[0] = size_impl;
-            *observation_state = ObservationState::Done;
+            *observation.state.borrow_mut() = ObservationState::Done;
```
Comment (jdm) [inline components/script/dom/resizeobserver.rs:141]: This won't work—the borrow() from earlier is still active, so this will conflict and cause a panic.

**Review by jdm — CHANGES_REQUESTED** [review]
I recommend running the tests at tests/wpt/tests/resize-observer as you work on this.

File: components/script/dom/resizeobserver.rs (hunk 3 above)
Comment (taniishkaaa) [reply components/script/dom/resizeobserver.rs:141]: I've tried enclosing the `borrow()` within a block so that it's no longer active when we borrow mutably but the tests still seem to be crashing. What else can be done here? 🤔

Comment (taniishkaaa) [reply components/script/dom/resizeobserver.rs]: Okay, I've refactored the code like you recommended, lmk if there's more room for improvements :)

File: components/script/dom/resizeobserver.rs [hunk 4]
```diff
@@ -97,52 +97,48 @@ impl ResizeObserver {
...
     ) {
         let mut entries: Vec<DomRoot<ResizeObserverEntry>> = Default::default();
-        let observation_targets = self.observation_targets.borrow();
-        for (observation, target) in observation_targets.iter() {
-            let observation_state = observation.state.borrow();
-            let ObservationState::Active(box_size) = &*observation_state else {
-                continue;
-            };
+        for (observation, target) in self.observation_targets.borrow().iter() {
+            if let ObservationState::Active(box_size) = &*observation.state.borrow() {
```
Comment (jdm) [inline components/script/dom/resizeobserver.rs:101]: Oh, shoot, I misread the original code when I made my suggestion. I meant this:
```rust
let ObservationState::Active(box_size) = &*observation.state.borrow() else {
  continue;
};
```
which avoids the need to indent all the code after it.

**Review by jdm — CHANGES_REQUESTED** [review]

File: components/script/dom/resizeobserver.rs (hunk 4 above)
Comment (taniishkaaa) [reply components/script/dom/resizeobserver.rs:101]: oop no problem, let me revert that

**Review by jdm — APPROVED** [review]

**Comment by taniishkaaa** [comment]
Do we need to update some test expectations here? I ran the wpt-tests(tests/wpt/tests/resize-observer) locally and there were no unexpected timeouts/crashes

**Comment by jdm** [comment]
> Do we need to update some test expectations here? I ran the wpt-tests(tests/wpt/tests/resize-observer) locally and there were no unexpected timeouts/crashes

I think you must have forgotten to rebuild before running the tests. When I build this PR and run them, I get crashes like this:
```
 ▶ CRASH [expected TIMEOUT] /resize-observer/multiple-observers-with-mutation-crash.html
  │
  │ already borrowed: BorrowMutError (thread Script(1,1), at components/script/dom/resizeobserver.rs:139)
  │ UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
  │    0: backtrace::backtrace::libunwind::trace
  │              at /Users/jdm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.74/src/backtrace/libunwind.rs:116:5
  │       backtrace::backtrace::trace_unsynchronized
  │              at /Users/jdm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.74/src/backtrace/mod.rs:66:5
  │    1: <servoshell::backtrace::Print as core::fmt::Debug>::fmt
  │              at /Users/jdm/src/servo/ports/servoshell/backtrace.rs:65:13
  │    2: core::fmt::rt::Argument::fmt
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/fmt/rt.rs:165:63
  │       core::fmt::write
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/fmt/mod.rs:1168:21
  │    3: std::io::Write::write_fmt
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/io/mod.rs:1835:15
  │    4: servoshell::backtrace::print
  │              at /Users/jdm/src/servo/ports/servoshell/backtrace.rs:18:5
  │    5: servoshell::panic_hook::panic_hook
  │              at /Users/jdm/src/servo/ports/servoshell/panic_hook.rs:40:17
  │    6: core::ops::function::Fn::call
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:79:5
  │    7: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/alloc/src/boxed.rs:2077:9
  │       std::panicking::rust_panic_with_hook
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:799:13
  │    8: std::panicking::begin_panic_handler::{{closure}}
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:664:13
  │    9: std::sys_common::backtrace::__rust_end_short_backtrace
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:171:18
  │   10: rust_begin_unwind
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
  │   11: core::panicking::panic_fmt
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
  │   12: core::cell::panic_already_borrowed
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/cell.rs:785:5
  │   13: core::cell::RefCell<T>::borrow_mut
  │              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/cell.rs:1076:25
  │   14: script::dom::resizeobserver::ResizeObserver::broadcast_active_resize_observations
  │              at /Users/jdm/src/servo/components/script/dom/resizeobserver.rs:139:14
  │   15: script::dom::document::Document::broadcast_active_resize_observations
  │              at /Users/jdm/src/servo/components/script/dom/document.rs:3039:13
  │   16: script::script_thread::ScriptThread::update_the_rendering
  │              at /Users/jdm/src/servo/components/script/script_thread.rs:1733:25
  │   17: script::script_thread::ScriptThread::rendering_opportunity::{{closure}}::{{closure}}
  │              at /Users/jdm/src/servo/components/script/script_thread.rs:1791:25
```

**Comment by jdm** [comment]
Now, onto solving the issue: the problem here (which I forgot) is that since we're using `&*`, Rust is helpfully borrowing the `box_size` value for us, which keeps the overall borrow active for longer than that statement. That means if we explicitly copy the value out of the borrowed value and do not refer to the borrowed value afterwards, Rust will terminate the borrow like we want.

I have a patch that does this which I'll provide in the hidden block below this. Try solving it by yourself before you take a look at my solution!

<details>

```diff
diff --git a/components/script/dom/resizeobserver.rs b/components/script/dom/resizeobserver.rs
index fdc3fbd004..be31e4933c 100644
--- a/components/script/dom/resizeobserver.rs
+++ b/components/script/dom/resizeobserver.rs
@@ -98,8 +98,11 @@ impl ResizeObserver {
     ) {
         let mut entries: Vec<DomRoot<ResizeObserverEntry>> = Default::default();
         for (observation, target) in self.observation_targets.borrow().iter() {
-            let ObservationState::Active(box_size) = &*observation.state.borrow() else {
-                continue;
+            let box_size = {
+                let ObservationState::Active(box_size) = &*observation.state.borrow() else {
+                    continue;
+                };
+                *box_size
             };
```

</details>

**Comment by taniishkaaa** [comment]
I tried moving the `borrow()` within a block earlier but didn't think of copying the value out of the borrowed value. It could've been fixed early on, sorry for the delay. I'll update this!

**Comment by taniishkaaa** [comment]
So, there's an unexpected PASS when I run the tests. Do I need to update the test expectations as well?

**Comment by jdm** [comment]
That test is known to pass intermittently: https://github.com/servo/servo/issues/32629 . You can ignore that result.

**Review by jdm — APPROVED** [review]
