### PR TITLE
layout: Unify scrollable overflow calculation and include `position: absolute`

### LINKED ISSUE #35928: [Bug] Elements with `position: fixed` and negative `bottom` value causes the wrong calculation of `scrollable_overflow`
**Describe the bug:**
For the below test case, Servo creates a redundant scroll frame.
It is caused by the wrong calculation of `FragmentTree::scrollable_overflow()`

Chromium:
https://github.com/user-attachments/assets/db0c1406-cd15-4225-98f6-e57e4bfac2fc

Servo:
https://github.com/user-attachments/assets/450351f6-f6c1-455e-a44a-b99a0ebc2a40

Test case:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Scrollable Content with Fixed Bottom</title>
    <style>
        /* Reset default margin and padding */
        body, html {
            margin: 0;
            padding: 0;
            height: 100%;
            font-family: Arial, sans-serif;
        }

        .fixed-bottom-wrapper {
          display: block;
          box-sizing: border-box;
          position: fixed;
          width: 100%;
          height: 50px;
          z-index: 998;
          bottom: -50px;
        }

        /* Fixed bottom container */
        .fixed-bottom {
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            height: 50px;
            background-color: #333;
            color: white;
            text-align: center;
            line-height: 50px; /* Vertically center text */
            z-index: 1000; /* Ensure it stays on top */
        }

        .scrollable-content-wrapper {
          display: block;
          box-sizing: border-box;
          height: 100%;
          overflow-y: auto;
        }

        /* Scrollable content container */
        .scrollable-content {
            overflow-y: auto; /* Enable vertical scrolling */
            padding: 10px;
            box-sizing: border-box;
            height: calc(100% - 50px);
        }

        /* Styling for each div inside the scrollable container */
        .scrollable-content div {
            height: 200px;
            padding: 20px;
            margin-bottom: 10px;
            background-color: #f0f0f0;
            border: 1px solid #ccc;
            box-sizing: border-box;
        }
    </style>
</head>
<body>
    <!-- Scrollable content -->
    <div class="scrollable-content-wrapper">
      <div class="scrollable-content">
        <!-- Add a lot of divs to create overflow -->
        <div>Content 1</div>
        <div>Content 2</div>
        <div>Content 3</div>
        <div>Content 4</div>
        <div>Content 5</div>
        <div>Content 6</div>
        <div>Content 7</div>
        <div>Content 8</div>
        <div>Content 9</div>
        <div>Content 10</div>
        <div>Content 11</div>
        <div>Content 12</div>
        <div>Content 13</div>
        <div>Content 14</div>
        <div>Content 15</div>
        <div>Content 16</div>
        <div>Content 17</div>
        <div>Content 18</div>
        <div>Content 19</div>
        <div>Content 20</div>
      </div>
    </div>

    <!-- Fixed bottom container -->
    <div class="fixed-bottom-wrapper">
    <!-- <div> -->
      <div class="fixed-bottom">
        Fixed Bottom Content
      </div>
    </div>
</body>
</html>
```

**To Reproduce:**
1.  `./mach run ../../../test/test.html --screen-size=425x1200 --window-size=425x1200`
2.  Scroll down to the bottom
3.  Scroll up, there are 2 scroll layers now, 1 is unexpected.

**Platform:**
Linux

### LINKED ISSUE #37204: Shouldn't ignore abspos children when computing scrolling area
```html
<!DOCTYPE html>
<style>
#target {
  position: relative;
  border: 5px solid;
  overflow: hidden;
  width: 200px;
  height: 200px;
}
#target::before {
  content: "";
  position: absolute;
  width: 1000px;
  height: 1000px;
}
</style>
<div id="target"></div>
<script>
document.write(target.scrollWidth + " x " + target.scrollHeight);
</script>
```

Servo says 200 x 200
Other browsers say 1000 x 1000

The original reason was that we were computing overflow before laying out abspos.
#37203 changes that, but it explicitly skips abspos to keep the old behavior: https://github.com/servo/servo/blob/de2da3b1e1c9785b2ff6d68887b7c1f94425abbd/components/layout/fragment_tree/box_fragment.rs#L284-L287

### PR DESCRIPTION
**Pull request by mrobinson**
Previously, layout was handling scrollable overflow and srolling area
calculation separately, only excluding the "unreachable scrollable
overflow region" at the last step. In addition, `position: absolute` was
not included in scrollable overflow calculation.

This change combines the two concepts into a single scrollable overflow
calculation and starts taking into account `position: absolute`.
Finally, `BoxFragment::scrollable_overflow_for_parent` is converted to
use early returns which reduces the amount of indentation.

Fixes #35928.
Fixes #37204.
Testing: This causes some WPT test to pass, but also two to start failing:
 - `/css/css-masking/clip-path/clip-path-fixed-scroll.html`: This seems to fail
   because script is scrolling past the boundaries of the document. This is a
   failure that was uncovered by the fixed element now being added to the
   page's scroll area.
 - `/css/css-overflow/overflow-outside-padding.html`: One test has started to fail
   here because now the absolutely positioned element is included in the scroll area,
   and I think there is an issue with how we are placing RTL items with negative margins.

### CODE REVIEW

**Review by xiaochengh — APPROVED** [review]

File: components/layout/fragment_tree/box_fragment.rs [hunk 1]
```diff
@@ -88,7 +88,10 @@ pub(crate) struct BoxFragment {
 
     block_margins_collapsed_with_children: Option<Box<CollapsedBlockMargins>>,
 
-    /// The scrollable overflow of this box fragment.
+    /// The scrollable overflow of this box fragment in the same coordiante system as
+    /// [`Self::content_rect`] ie a rectangle within the parent fragment's content
```
Comment (Loirooriol) [inline components/layout/fragment_tree/box_fragment.rs:92]: I have always seen it as "i.e.", not "ie".

Comment (mrobinson) [reply components/layout/fragment_tree/box_fragment.rs:92]: "i.e." is technically correct, but "ie" is also used informally. It's common if a bit cheeky.
