### PR TITLE
servoshell: Send all button events to the `WebView` regardless of what button is pressed

### LINKED ISSUE #37996: Middle mouse button clicks not detected
When testing mouse input in Servo, the middle mouse button (button value 1 in `mousedown` events) is not being detected or triggered. Left and right mouse buttons work as expected, but middle-clicks do not register in event listeners. This was observed using a test HTML page (provided below) that displays the clicked mouse button. In other browsers like Chrome, the middle mouse button is detected correctly.

**Platform:**
Windows

**To Reproduce:**
<details>
<summary>Manual TC</summary>

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Middle Mouse Button Test</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
            background-color: #f0f0f0;
        }
        #status {
            font-size: 24px;
            margin-top: 20px;
            padding: 10px;
            border: 1px solid #ccc;
            background-color: white;
            border-radius: 5px;
        }
        #clickArea {
            width: 300px;
            height: 300px;
            background-color: #e0e0e0;
            border: 2px solid #333;
            display: flex;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            user-select: none;
        }
    </style>
</head>
<body>
    <div id="clickArea">Click here with any mouse button</div>
    <div id="status">No click detected</div>

    <script>
        const clickArea = document.getElementById('clickArea');
        const status = document.getElementById('status');

        clickArea.addEventListener('mousedown', (event) => {
            event.preventDefault(); // Prevent default middle click actions (like scrolling)
            switch (event.button) {
                case 0:
                    status.textContent = 'Left button clicked';
                    break;
                case 1:
                    status.textContent = 'Middle button clicked';
                    status.style.backgroundColor = '#90EE90'; // Light green for middle click
                    break;
                case 2:
                    status.textContent = 'Right button clicked';
                    break;
                default:
                    status.textContent = 'Unknown button clicked';
            }

            // Reset status after 1 second
            setTimeout(() => {
                status.textContent = 'No click detected';
                status.style.backgroundColor = 'white';
            }, 1000);
        });

        // Prevent context menu on right-click for cleaner testing
        clickArea.addEventListener('contextmenu', (event) => {
            event.preventDefault();
        });
    </script>
</body>
</html>
```

### PR DESCRIPTION
**Pull request by abdelrahman1234567**
Sending all mouse button events (Left, Right, Middle, Back, Forward) to the constellation for processing. Before, only left and right mouse buttons were handled.

Testing: There is no new test for this. Manually testing was done. We currently
do not have a good way to test user interaction in servoshell.
Fixes: #37996

### CODE REVIEW

File: ports/servoshell/desktop/headed_window.rs [hunk 1]
```diff
@@ -599,7 +599,12 @@ impl WindowPortsMethods for Window {
             WindowEvent::KeyboardInput { event, .. } => self.handle_keyboard_input(state, event),
             WindowEvent::ModifiersChanged(modifiers) => self.modifiers_state.set(modifiers.state()),
             WindowEvent::MouseInput { state, button, .. } => {
-                if button == MouseButton::Left || button == MouseButton::Right {
+                if button == MouseButton::Left ||
+                    button == MouseButton::Right ||
+                    button == MouseButton::Middle ||
+                    button == MouseButton::Back ||
+                    button == MouseButton::Forward
+                {
```
Comment (mrobinson) [inline ports/servoshell/desktop/headed_window.rs]: Can you just remove the if statement entirely here and send the button event unconditionally?

**Review by mrobinson — CHANGES_REQUESTED** [review]

File: ports/servoshell/desktop/headed_window.rs (hunk 1 above)
Comment (abdelrahman1234567) [reply ports/servoshell/desktop/headed_window.rs]: I was thinking of the same thing but was wondering if it was handled for a certain reason.

**Review by mrobinson — APPROVED** [review]

**Comment by mrobinson** [comment]
@abdelrahman1234567 Is this ready for review? If so please, press the "Ready for review" button.

**Review by Taym95 — APPROVED** [review]

File: ports/servoshell/desktop/headed_window.rs [hunk 2]
```diff
@@ -599,9 +599,7 @@ impl WindowPortsMethods for Window {
             WindowEvent::KeyboardInput { event, .. } => self.handle_keyboard_input(state, event),
             WindowEvent::ModifiersChanged(modifiers) => self.modifiers_state.set(modifiers.state()),
             WindowEvent::MouseInput { state, button, .. } => {
-                if button == MouseButton::Left || button == MouseButton::Right {
```
Comment (Taym95) [inline ports/servoshell/desktop/headed_window.rs:597]: this makes sense but why was done like this in first place?

Comment (jdm) [reply ports/servoshell/desktop/headed_window.rs:597]: Servo only supported left and right mouse clicks 6 years ago when that check was added.
