### PR TITLE
Fix brotli decoding

### LINKED ISSUE #22228: google.com does not load
According to previous IRC discussions, this happens because the decoder receives too little data and poisons any further decoding that might happen during page load.

https://mozilla.logbot.info/servo/20181108#c15587681-c15587715

@Eijebong Could you point to the code in reqwest that deals with this properly?

### PR DESCRIPTION
**Pull request by jdm**
This replaces our current decoding setup by https://github.com/seanmonstar/reqwest/blob/master/src/async_impl/decoder.rs, and integrates brotli and deflate decoding to maintain our existing support.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #22228
- [x] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22616)

### CODE REVIEW

**Comment by jdm** [comment]
Waiting to hear about https://github.com/dropbox/rust-brotli-decompressor/issues/4 to see if we need to maintain the brotli fork long-term.

File: components/net/decoder.rs [hunk 1]
```diff
@@ -0,0 +1,508 @@
...
+/// as a `Chunk`.
+struct Gzip {
+    inner: Box<gzip::Decoder<Peeked<ReadableChunks<Body>>>>,
+    buf: BytesMut,
+    url: ServoUrl,
+}
+
+impl fmt::Debug for Decoder {
+    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
+        f.debug_struct("Decoder").finish()
```
Comment (Eijebong) [inline components/net/decoder.rs]: Not sure what this is exactly doing but I don't think it gives the type of decode and it might  be useful to know it ? i.e plain, gzip...

File: tests/wpt/mozilla/tests/mozilla/response-data-brotli.htm [hunk 2]
```diff
@@ -9,34 +9,27 @@
...
-              }
+      async_test(function(test) {
+        var client = new XMLHttpRequest()
+        client.open("GET", "resources/brotli.py?raw", false);
+        client.onerror = test.unreached_func();
+        client.onload = test.step_func(function () {
+          var input = client.responseText;
+          var client2 = new XMLHttpRequest()
+          client2.open("GET", "resources/brotli.py?pipe=trickle(1:d1)", false);
+          client2.onload = test.step_func(function() {
```
Comment (nox) [inline tests/wpt/mozilla/tests/mozilla/response-data-brotli.htm]: Nit: this can be `step_func_done`.

File: tests/wpt/mozilla/tests/mozilla/response-data-brotli.htm [hunk 3]
```diff
@@ -9,34 +9,27 @@
...
-          client.onreadystatechange = test.step_func(function () {
-              if (client.readyState === 4) {
-                  var len = parseInt(client.getResponseHeader('content-length'), 10);
-
-                  assert_equals(client.getResponseHeader('content-encoding'), 'br');
-                  assert_true(len < input.length);
-                  assert_equals(client.responseText, input);
-                  test.done();
-              }
+      async_test(function(test) {
```
Comment (nox) [inline tests/wpt/mozilla/tests/mozilla/response-data-brotli.htm]: Nit: you could do `var test = async_test();` and not have to indent the entire test.

**Review by nox — COMMENTED** [review]
The failures seem relevant to the patch, do you want me to look into them?

File: tests/wpt/mozilla/tests/mozilla/response-data-brotli.htm (hunk 3 above)
Comment (jdm) [reply tests/wpt/mozilla/tests/mozilla/response-data-brotli.htm]: That's how the test was originally written, but that excludes the code outside of the test from reporting errors. This format provides better coverage.

**Comment by jdm** [comment]
@bors-servo r-
Forgot the test result change.

**Comment by CYBAI** [comment]
Travis is complaining the wpt manifest 👀

```
$ ./mach test-tidy --no-progress --all
 0:12.69 INFO Diffing old and new manifests /home/travis/build/servo/servo/tests/wpt/mozilla/meta/MANIFEST.json
 0:12.84 WARNING Manifest /home/travis/build/servo/servo/tests/wpt/mozilla/meta/MANIFEST.json contains correct tests but file hashes changed.
 0:12.85 INFO Diffing old and new manifests /home/travis/build/servo/servo/tests/wpt/metadata/MANIFEST.json
 0:17.28 INFO Diffing old and new manifests /home/travis/build/servo/servo/tests/wpt/webgl/meta/MANIFEST.json
 0:17.49 ERROR Manifest /home/travis/build/servo/servo/tests/wpt/webgl/meta/MANIFEST.json is outdated, use |./mach update-manifest| to fix.
Checking the config file...
Checking the wpt manifest file...
Checking directories for correct file extensions...

The command "./mach test-tidy --no-progress --all" exited with 1.
```

**Comment by jdm** [comment]
I have had no response to https://github.com/dropbox/rust-brotli-decompressor/issues/4 so the git dependency would be a fork.

**Comment by jdm** [comment]
@bors-servo retry
#22236

**Comment by jdm** [comment]
@bors-servo r-
A fix is being merged upstream.

**Comment by CYBAI** [comment]
Both task cluster and Travis failed with following error 👀
```
+ ./mach test-tidy --no-progress --all
Error running mach:

    ['test-tidy', '--no-progress', '--all']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

AttributeError: 'NoneType' object has no attribute 'to_json'

  File "/repo/python/servo/testing_commands.py", line 330, in test_tidy
    manifest_dirty = run_update(self.context.topdir, check_clean=True)
  File "/repo/python/servo/testing_commands.py", line 90, in run_update
    return manifestupdate.update(logger, wpt_dir, check_clean, rebuild)
  File "/repo/tests/wpt/manifestupdate.py", line 54, in update
    return _check_clean(logger, test_paths)
  File "/repo/tests/wpt/manifestupdate.py", line 81, in _check_clean
    old_manifest.to_json())
```

**Comment by jdm** [comment]
*sounds of wailing and gnashing of teeth*

**Comment by jdm** [comment]
@bors-servo retry
* #22700
