### PR TITLE
config: fix panic in PrefValue to [f64; 4] conversion

### LINKED ISSUE #32570: Servo panics when launched in multiprocess mode.
**Describe the bug:**
Panic message:
```
NOTE: Entering nix-shell etc/shell.nix
index out of bounds: the len is 0 but the index is 0 (thread main, at components/config/pref_util.rs:164)
   0: servoshell::backtrace::print
             at /home/mukilan/dev/servo-emulator/ports/servoshell/backtrace.rs:18:5
   1: servoshell::panic_hook::panic_hook
             at /home/mukilan/dev/servo-emulator/ports/servoshell/panic_hook.rs:38:17
   2: core::ops::function::Fn::call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:79:5
   3: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2034:9
      std::panicking::rust_panic_with_hook
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:783:13
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:657:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:171:18
   6: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   7: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   8: core::panicking::panic_bounds_check
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:209:5
   9: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/slice/index.rs:264:10
  10: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/slice/index.rs:18:9
      <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/vec/mod.rs:2829:9
  11: servo_config::pref_util::<impl core::convert::From<servo_config::pref_util::PrefValue> for [f64; 4]>::from
             at /home/mukilan/dev/servo-emulator/components/config/pref_util.rs:164:23
  12: <T as core::convert::Into<U>>::into
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/convert/mod.rs:759:9
  13: <servo_config::prefs::gen::PREF_ACCESSORS as core::ops::deref::Deref>::deref::__static_ref_initialize::{{closure}}
             at /home/mukilan/dev/servo-emulator/components/config/prefs.rs:176:5
  14: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2034:9
  15: servo_config::pref_util::Preferences<P>::set_inner
             at /home/mukilan/dev/servo-emulator/components/config/pref_util.rs:279:13
  16: servo_config::pref_util::Preferences<P>::set_all
             at /home/mukilan/dev/servo-emulator/components/config/pref_util.rs:301:13
  17: servo::run_content_process
             at /home/mukilan/dev/servo-emulator/components/servo/lib.rs:1192:5
  18: servoshell::desktop::cli::main
             at /home/mukilan/dev/servo-emulator/ports/servoshell/desktop/cli.rs:70:16
  19: servoshell::main
             at /home/mukilan/dev/servo-emulator/ports/servoshell/lib.rs:38:5
  20: servo::main
             at /home/mukilan/dev/servo-emulator/ports/servoshell/main.rs:26:13
  21: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
  22: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:155:18
  23: std::rt::lang_start::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:166:18
  24: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
      std::rt::lang_start_internal
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:20
  25: std::rt::lang_start
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:165:17
  26: main
  27: __libc_start_call_main
  28: __libc_start_main_impl
  29: _start
```

**To Reproduce:**
1. Launch servo in multiprocess mode e.g  `./mach run --dev -M`

**Platform:**
This happens on all platforms.

### PR DESCRIPTION
**Pull request by mukilan**
The `Iterator::all()` method consumes the input iterator `f` so when we reuse `f` in `f.flatten().collect()` it yields an empty Vector in the case where all the elements are successfully converted using try_into(). This causes out of bounds access when indexing into the resulting Vector to extract the individual components.

Fixes #32570.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #32570
- [x] These changes do not have tests but ideally we should add unit tests for all PrefValue  conversion functions

### CODE REVIEW

File: components/config/pref_util.rs [hunk 1]
```diff
@@ -158,9 +158,12 @@ impl From<PrefValue> for [f64; 4] {
...
         match other {
             PrefValue::Array(values) if values.len() == 4 => {
-                let mut f = values.into_iter().map(|v| v.try_into());
-                if f.all(|v| v.is_ok()) {
-                    let f = f.flatten().collect::<Vec<f64>>();
+                let f = values
+                    .into_iter()
+                    .map(|v| v.try_into())
+                    .flatten()
+                    .collect::<Vec<f64>>();
```
Comment (mrobinson) [inline components/config/pref_util.rs:165]: Could this be slightly shorter with:

```suggestion
                    .filter_map(|value| value.try_into())
                    .collect::<Vec<f64>>();
```

**Review by mrobinson — APPROVED** [review]
Nice fix!

**Comment by mukilan** [comment]
Thanks for the review!
