### PR TITLE
layout: Handle selection during display list construction

### LINKED ISSUE #41920: Caret of text input element is appearing and disappearing correctly when focusing with mouse
**Describe the bug:**
Caret of `<input>` element doesn't appear on focus and stays after a unfocusing the element (`blur`). 

https://github.com/user-attachments/assets/11090a2c-b63b-48e2-ad2c-698942f63969

**To Reproduce:**
Open `data:text/html,<input>`:
1. Focus on the input with mouse and notice that the caret is nowhere to be seen.
2. Unfocus by clicking empty space and notice that the caret is still there.

**Platform:**
Platform independent bug.

### PR DESCRIPTION
**Pull request by mrobinson**
Instead of handling selection in text input during box tree / fragment
tree construction, fully handle it during display list construction.
This means that when the selection changes in script, it updates
automatically in the `FragmentTree` and only a new display list is
necessary. This avoids a layout while changing the selection in text
fields.

Testing: This fixes a few rendering issues, but these are very hard
to isolate and test for. It causes one test to start failing, but this is
because a cursor that wasn't rendered properly now starts showing
up.
Fixes: #41920.

### CODE REVIEW

**Comment by mrobinson** [comment]
This failure is actually a progression. The caret has started showing up correctly, but we now aren't handling `caret-color` correctly.

File: components/layout/display_list/mod.rs [hunk 1]
```diff
@@ -37,7 +37,7 @@ use style::values::computed::{
 use style::values::generics::NonNegative;
 use style::values::generics::rect::Rect;
 use style::values::specified::text::TextDecorationLine;
-use style_traits::{CSSPixel as StyloCSSPixel, DevicePixel as StyloDevicePixel};
+use style_traits::{CSSPixel, CSSPixel as StyloCSSPixel, DevicePixel as StyloDevicePixel};
```
Comment (Loirooriol) [inline components/layout/display_list/mod.rs]: `CSSPixel` was already imported as `StyloCSSPixel`

File: components/layout/display_list/mod.rs [hunk 2]
```diff
@@ -977,6 +921,97 @@ impl Fragment {
...
     }
+
+    // TODO: This caret/text selection implementation currently does not account for vertical text
+    // and RTL text properly.
+    fn build_display_list_for_text_selection(
+        &self,
+        fragment: &TextFragment,
+        builder: &mut DisplayListBuilder<'_>,
+        containing_block: &euclid::Rect<Au, StyloCSSPixel>,
+        baseline_origin: Point2D<Au, CSSPixel>,
```
Comment (Loirooriol) [inline components/layout/display_list/mod.rs]:
```suggestion
        containing_block: &PhysicalRect<Au>,
        baseline_origin: PhysicalPoint<Au>,
```

**Review by Loirooriol — APPROVED** [review]
