### PR TITLE
Fix origin/clip parsing behavior in mask and background shorthands

### LINKED ISSUE #13466: Fix origin/clip behavior in mask and background shorthands in style
In both specs, if one <geometry-box> value is present then it sets both mask-origin and mask-clip to that value. If two <geometry-box> values are present, then the first sets mask-origin and the second mask-clip. But in both parsing process,  we are setting just origin if one <geometry-box> value is present. This effects just parsing functions, serialization functions' behaviors are correct.
Files: `components/style/properties/shorthand/mask.mako.rs` and 
`components/style/properties/shorthand/background.mako.rs`

Specs:
https://drafts.fxtf.org/css-masking-1/#the-mask
https://drafts.csswg.org/css-backgrounds-3/#the-background

### PR DESCRIPTION
**Pull request by canova**
We have tests for mask shorthand parsing, but we don't have tests for background parsing. Should I add some for it?
Also deleted inaccessible match arms in serialization function.
r? @Manishearth 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13466 (github issue number if applicable).

- [X] There are tests for these changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13541)

### CODE REVIEW

**Comment by Manishearth** [comment]
Feel free to add background parse tests.

File: tests/unit/style/parsing/mask.rs [hunk 1]
```diff
@@ -106,8 +106,8 @@ fn mask_shorthand_should_parse_origin_and_clip_correctly() {
     let mut parser = Parser::new("padding-box");
     let result = mask::parse_value(&context, &mut parser).unwrap();
 
-    // TODO(#13466): We should fix origin/clip parsing behavior.
     assert_eq!(result.mask_origin.unwrap(), parse_longhand!(mask_origin, "padding-box"));
+    assert_eq!(result.mask_clip.unwrap(), parse_longhand!(mask_clip, "padding-box"));
```
Comment (Manishearth) [inline tests/unit/style/parsing/mask.rs]: add a test ensuring that `no-clip` is only stored in mask_clip and not mask_origin.

(It should obviously pass since mask_origin has no mechanism for holding this, but it's good to be sure)

Comment (canaltinova) [inline tests/unit/style/parsing/mask.rs]: `no-clip` in both mask and brackground is still not implemented due to this note: https://github.com/servo/servo/blob/master/components/style/properties/longhand/svg.mako.rs#L111-L112 Should we implement them?

Comment (Manishearth) [inline tests/unit/style/parsing/mask.rs]: Oh, never mind then.

**Comment by Manishearth** [comment]
r=me. What do you wish to do about the background tests? I'm fine with them being implemented here, in a separate PR, or in an easy bug for someone else to pick up (that both of us can help with)

**Comment by canaltinova** [comment]
Writing background parse tests is simple since mask parse tests are very similar to background ones and it should be a nice easy issue to someone who is new to servo code base. I think easy bug is better for new contributors (I was sometimes struggling to find one too :) ) I'll file an issue for it.

**Comment by Manishearth** [comment]
@bors-servo r+

cool, thanks!

**Comment by Manishearth** [comment]
If you want something to work on next, an interesting bug for you might be implementing parsing for the other kinds of gradients https://www.w3.org/TR/2012/CR-css3-images-20120417/#gradient-type . In this case, we could even try getting the Gecko glue in place (unlike mask, where I did this for you) -- this requires some hacking on C++ (or at least looking through C++ code). Are you up for it? We could simply stop after the parsing bit if it's too much. If you want to work on this, I'll file an issue with the relevant links. 

The reason I pick this is because gradients are pretty and it's always nice to get a visual result instead of a robotic TESTS PASS 😝 . Sadly with the mask stuff we can't get much of a visual result until urls are implemented -- there's enough implemented to use gradient masks and test that it _works_, but not enough to do cool things.

**Comment by canaltinova** [comment]
Yes, I can definitely work on that. I don't know much about gecko glue or stylo, but I love to learn new things 😃

**Comment by Manishearth** [comment]
Nice, you made a test pass. Amend the commit to remove the failure entry for the test, and we should be good to go.

@bors-servo delegate+
