### PR TITLE
Return Option for Window's layout channel

### LINKED ISSUE #19092: called `Result::unwrap()` on an `Err` value: "SendError(..)"
called `Result::unwrap()` on an `Err` value: "SendError(..)"
### Servo Version:
Servo 0.0.1-c18f412
### Backtrace:
```

WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }>: Trying to set metric before navigation start
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(3))) }>: Network error: Internal("Unexpected scheme")
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(3))) }>: Resuming an already resumed timer.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(3))) }>: stop_parsing not implemented, full speed ahead!
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×4 at (949.63336,158.7))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×4 at (987.6667,138))
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }>: Trying to set metric before navigation start
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }>: Trying to set metric before navigation start
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }>: Trying to set metric before navigation start
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }>: Trying to set metric before navigation start
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }>: Trying to set metric before navigation start
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }>: Trying to set metric before navigation start
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }>: Trying to set metric before navigation start
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }>: Trying to set metric before navigation start
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }>: Trying to set metric before navigation start
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }>: Trying to set metric before navigation start
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }>: Trying to set metric before navigation start
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }>: Trying to set metric before navigation start
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×4 at (949.63336,158.7))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×4 at (987.6667,138))
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }>: Trying to set metric before navigation start
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }>: Trying to set metric before navigation start
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×4 at (949.63336,158.7))
WARNING: <RenderBackend>: invalid primitive rect TypedRect(0×4 at
...
```
This report was generated by the browser.html issue reporter.

### LINKED ISSUE #21208: NYTimes article about cedars of lebanon panics while communicating with layout thread
https://www.nytimes.com/interactive/2018/07/18/climate/lebanon-climate-change-environment-cedars.html?hp&action=click&pgtype=Homepage&clickSource=story-heading&module=photo-spot-region&region=top-news&WT.nav=top-news

```
godot:master-servo jdm$ ./mach run -r "https://www.nytimes.com/interactive/2018/07/18/climate/lebanon-climate-change-environment-cedars.html?hp&action=click&pgtype=Homepage&clickSource=story-heading&module=photo-spot-region&region=top-news&WT.nav=top-news"
init
init
init
init
evaluating function

       0000000                         000        0000000
     111111111      11111111100          000      111111111
     00000        111111111111111111      00000      000000
     000        1111111111111111111111111100000         000
     000        1111       1111111111111111100          000
     000         11       0     1111111100              000
     000          1      00             1               000
     000               00      00       1               000
     000             000    00000       1               000
  00000            0000  00000000       1                00000
11111            000 00    000000      000                 11111
  00000          0000      000000     00000              00000
     000        10000      000000      000              0000
     000        00000      000000       1               000
     000        000000     10000        1     0         000
     000        1000000 00              1    00         000
     000         1111111                1 0000          000
     000          1111111100           000000           000
     0000          111111111111111110000000            0000
     111111111        111111111111100000          111111111
       0000000              00000000              0000000



NYTimes.com: All the code that's fit to printf()
We're hiring: developers.nytimes.com/careers



No Gateway Parameter
opty_payload
[object Object]
cover is loading
[OptimizelyNYT] growl Impression ID:Nons | Default NYT5 Experience | All Geos | 2018-05-11 – ongoing
ERROR 2018-07-19T12:55:21Z: script::dom::bindings::error: Error at https://www.nytimes.com/vi-assets/static-assets/nyt5/20180709/js/interactive/main.js:1:19440 e.originalEvent is undefined
error in _handler
TypeError: frames.__bkframe is undefined
ERROR 2018-07-19T12:55:24Z: script::dom::bindings::error: Error at https://www.nytimes.com/vi-assets/static-assets/nyt5/20180709/js/interactive/main.js:1:19440 e.originalEvent is undefined
ERROR 2018-07-19T12:55:25Z: script::dom::bindings::error: Error at https://www.nytimes.com/vi-assets/static-assets/nyt5/20180709/js/interactive/main.js:1:19440 e.originalEvent is undefined
ERROR 2018-07-19T12:55:25Z: script::dom::bindings::error: Error at https://www.nytimes.com/vi-assets/static-assets/nyt5/20180709/js/interactive/main.js:1:19440 e.originalEvent is undefined
ERROR 2018-07-19T12:55:26Z: script::dom::bindings::error: Error at :0:0 SecurityError: The operation is insecure.
called `Result::unwrap()` on an `Err` value: "SendError(..)" (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }, at libcore/result.rs:945)
stack backtrace:
   0:        0x106b54dde - backtrace::backtrace::trace::h53c90f7e693c3e4a
   1:        0x106b5588c - _$LT$backtrace..capture..Backtrace$u20$as$u20$core..default..Default$GT$::default::hf26626fd61b15e6b
   2:        0x106b558dd - backtrace::capture::Backtrace::new::he239b90a51ed8f1d
   3:        0x1042a6ace - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h6df244054f8391a2
   4:        0x106b7af7e - std::panicking::rust_panic_with_hook::hb67a9393fa2dec62
   5:        0x106b7aace - std::panicking::continue_panic_fmt::ha4f4d262ed9b35ca
   6:        0x106b7a9b8 - rust_begin_unwind
   7:        0x106b97261 - core::panicking::panic_fmt::hdf64b1a464eabfa2
   8:        0x104fef40d - core::result::unwrap_failed::h8cb037d721abe74c
   9:        0x10523da5d - script::dom::window::Window::force_reflow::h46440a2a261796a3
  10:        0x10523e1aa - script::dom::window::Window::reflow::h97b64431161dc42b
  11:        0x10502f81c - script::dom::element::Element::has_css_layout_box::h8a65f99ec3e294f6
  12:        0x104a2ffa8 - script::script_thread::ScriptThread::handle_msg_from_constellation::h8336d0e2e57611ca
  13:        0x104a2b6d2 - script::script_thread::ScriptThread::handle_msgs::h367d0d3e4e49408d (.llvm.10296180611949601579)
  14:        0x104dda317 - profile_traits::mem::ProfilerChan::run_with_memory_reporting::h57fb89243b38497d
  15:        0x1050f3c70 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1d499fe555221e5f
  16:        0x1046e613d - std::panicking::try::do_call::h91ad2b717e34d2d5 (.llvm.480075607669524226)
  17:        0x106b8700e - __rust_maybe_catch_panic
  18:        0x1052925e6 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h7f75dc49f5bc085e
  19:        0x106b5e50b - std::sys::unix::thread::Thread::new::thread_start::hfdfbf4ce872c8486
  20:     0x7fff9fbbb93a - _pthread_body
  21:     0x7fff9fbbb886 - _pthread_start
ERROR 2018-07-19T12:55:26Z: servo: called `Result::unwrap()` on an `Err` value: "SendError(..)"
```

### LINKED ISSUE #22559: intermittent CRASH in /html/browsers/history/the-location-interface/location-origin-idna.sub.window
```
Layout thread disconnected.: "SendError(..)" (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at libcore/result.rs:1009)
  │ stack backtrace:
  │    0:     0x7f0eb2cb011c - backtrace::backtrace::trace::h77d04c33b09dac10
  │    1:     0x7f0eb2caf342 - <backtrace::capture::Backtrace as core::default::Default>::default::hd8f68beaec462ca3
  │    2:     0x7f0eb2caf3b8 - backtrace::capture::Backtrace::new::hc8cf18d80aa809da
  │    3:     0x7f0eb056ec19 - servo::main::{{closure}}::hda11f6f8f712e194
  │    4:     0x7f0eb3987743 - std::panicking::rust_panic_with_hook::hd470ff3b3e7a1b18
  │                         at libstd/panicking.rs:480
  │    5:     0x7f0eb39872a9 - std::panicking::continue_panic_fmt::hf0cf39ae1e114602
  │                         at libstd/panicking.rs:390
  │    6:     0x7f0eb39871a5 - rust_begin_unwind
  │                         at libstd/panicking.rs:325
  │    7:     0x7f0eb39a890b - core::panicking::panic_fmt::hf53111ba26d35bb0
  │                         at libcore/panicking.rs:77
  │    8:     0x7f0eb0fff3b8 - core::result::unwrap_failed::h6eb3e061bc845144
  │    9:     0x7f0eb0aba33a - script::dom::window::Window::force_reflow::h21768a0ecd1269de
  │   10:     0x7f0eb0abaae0 - script::dom::window::Window::reflow::he36e3221780585a8
  │   11:     0x7f0eb0dce29a - script::dom::document::Document::finish_load::h0714983f589f8ef7
  │   12:     0x7f0eb0b4a7db - script::dom::servoparser::ServoParser::do_parse_sync::h4f0393c86a5d8b5f
  │   13:     0x7f0eb0fd6c08 - profile_traits::time::profile::h99945713db334899
  │   14:     0x7f0eb0b49ed7 - _ZN6script3dom11servoparser11ServoParser10parse_sync17h750f46cfafc8de22E.llvm.1313662908741159400
  │   15:     0x7f0eb0b4fea8 - <script::dom::servoparser::ParserContext as net_traits::FetchResponseListener>::process_response_eof::h169b7fcd9a434dbb
  │   16:     0x7f0eb0f8dbf5 - script::script_thread::ScriptThread::handle_msg_from_constellation::h15439d71e03fd597
  │   17:     0x7f0eb0f84425 - _ZN6script13script_thread12ScriptThread11handle_msgs17h0c8dfce8ea3cb7a2E.llvm.15832312269310248529
  │   18:     0x7f0eb0f7fd51 - script::script_thread::ScriptThread::start::h948bb235dc81f954
  │   19:     0x7f0eb10f40ae - std::sys_common::backtrace::__rust_begin_short_backtrace::h0207fb1284d6f7bb
  │   20:     0x7f0eb16d6c47 - _ZN3std9panicking3try7do_call17hfbd4d552802c3b02E.llvm.12184908431515536536
  │   21:     0x7f0eb39999b9 - __rust_maybe_catch_panic
  │                         at libpanic_unwind/lib.rs:102
  │   22:     0x7f0eb143bbf0 - <F as alloc::boxed::FnBox<A>>::call_box::h51f2eda267501ab4
  │   23:     0x7f0eb398462a - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$RP$$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h9d1cd498499ed135
  │                         at liballoc/boxed.rs:682
  │                          - std::sys_common::thread::start_thread::ha4bfe77455e6e434
  │                         at libstd/sys_common/thread.rs:24
  │   24:     0x7f0eb39711f5 - std::sys::unix::thread::Thread::new::thread_start::hebe133da3ea5230a
  │                         at libstd/sys/unix/thread.rs:90
  │   25:     0x7f0eae1d3183 - start_thread
  │   26:     0x7f0eaca9a03c - clone
  │   27:                0x0 - <unknown>
  │ [2018-12-26T07:16:34Z ERROR servo] Layout thread disconnected.: "SendError(..)"
  └ Pipeline failed in hard-fail mode.  Crashing!

```

Appears related to https://github.com/servo/servo/issues/22507

### LINKED ISSUE #22584: Intermittent crash in /html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_nonescaping-1.html
```
  ▶ CRASH [expected OK] /html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_nonescaping-1.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 18.3.0-devel
  │ Layout thread disconnected.: "SendError(..)" (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at src/libcore/result.rs:999)
  │ stack backtrace:
  │    0:     0x7fdcc060940d - backtrace::backtrace::trace::h79f1388f62af1802
  │    1:     0x7fdcc06084f2 - backtrace::capture::Backtrace::new::hc3bba4c59ac369f9
  │    2:     0x7fdcbe0ec707 - servo::main::{{closure}}::hf19b374ab533c127
  │    3:     0x7fdcc12e3169 - std::panicking::rust_panic_with_hook::h4ae0c8352236ab41
  │                         at src/libstd/panicking.rs:482
  │    4:     0x7fdcc12e2c11 - std::panicking::continue_panic_fmt::h3111c2662a27401f
  │                         at src/libstd/panicking.rs:385
  │    5:     0x7fdcc12e2af5 - rust_begin_unwind
  │                         at src/libstd/panicking.rs:312
  │    6:     0x7fdcc130288c - core::panicking::panic_fmt::h9b22f2eab14691b2
  │                         at src/libcore/panicking.rs:85
  │    7:     0x7fdcbecab549 - core::result::unwrap_failed::hd73a15296c74d9b9
  │    8:     0x7fdcbe6cd5d4 - script::dom::window::Window::force_reflow::h53978208f3a3c509
  │    9:     0x7fdcbe6cdd70 - script::dom::window::Window::reflow::heddd495561cc9402
  │   10:     0x7fdcbe9d0667 - script::dom::document::Document::finish_load::h6d5c5438ae1a0bd3
  │   11:     0x7fdcbe762a8f - script::dom::servoparser::ServoParser::do_parse_sync::h5fa2c01154ba2fd0
  │   12:     0x7fdcbeae5652 - profile_traits::time::profile::h77044da60d2c5250
  │   13:     0x7fdcbe762130 - _ZN6script3dom11servoparser11ServoParser10parse_sync17ha4fd06fc285ee4c9E.llvm.9339690625470186472
  │   14:     0x7fdcbe76829f - <script::dom::servoparser::ParserContext as net_traits::FetchResponseListener>::process_response_eof::h2d88f23e27a56c4e
  │   15:     0x7fdcbebfed50 - script::script_thread::ScriptThread::handle_msg_from_constellation::h42a0e4ca9312c959
  │   16:     0x7fdcbebf5cd5 - script::script_thread::ScriptThread::handle_msgs::{{closure}}::h50dd6c3e534ef2de
  │   17:     0x7fdcbebf21d0 - _ZN6script13script_thread12ScriptThread11handle_msgs17h470952e4622057d7E.llvm.16015583961693140166
  │   18:     0x7fdcbebedb16 - script::script_thread::ScriptThread::start::h15ea86fa7a7fa212
  │   19:     0x7fdcbec7e92e - profile_traits::mem::ProfilerChan::run_with_memory_reporting::hca3d66b9290e91c7
  │   20:     0x7fdcbed77ee4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8489019698b0aeef
  │   21:     0x7fdcbf2c41c5 - _ZN3std9panicking3try7do_call17h352587cb1a98b0eeE.llvm.18296174844099702026
  │   22:     0x7fdcc12ede79 - __rust_maybe_catch_panic
  │                         at src/libpanic_unwind/lib.rs:92
  │   23:     0x7fdcbeef8387 - <F as alloc::boxed::FnBox<A>>::call_box::hbb3f60dda289794c
  │   24:     0x7fdcc12ed22d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$RP$$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h6f2a2148ffb0bc67
  │                         at /rustc/fb86d604bf65c3becd16180b56267a329cf268d5/src/liballoc/boxed.rs:734
  │                          - std::sys_common::thread::start_thread::h484e653ee0a7a7a3
  │                         at src/libstd/sys_common/thread.rs:14
  │                          - std::sys::unix::thread::Thread::new::thread_start::h9d911af69d8eb4e6
  │                         at src/libstd/sys/unix/thread.rs:81
  │   25:     0x7fdcbbd38183 - start_thread
  │   26:     0x7fdcba5ff03c - clone
  │   27:                0x0 - <unknown>
  │ [2018-12-28T15:09:39Z ERROR servo] Layout thread disconnected.: "SendError(..)"
  └ Pipeline failed in hard-fail mode.  Crashing!
```

### LINKED ISSUE #22652: Intermittent crash in /workers/WorkerLocation-origin.sub.window.html
```
  ▶ CRASH [expected OK] /workers/WorkerLocation-origin.sub.window.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 18.3.0-devel
  │ Layout thread disconnected.: "SendError(..)" (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at src/libcore/result.rs:999)
  │ stack backtrace:
  │    0:     0x7fb131f2be8d - backtrace::backtrace::trace::h8cf5e823e7b927c4
  │    1:     0x7fb131f2af72 - backtrace::capture::Backtrace::new::h57ad61985be7a0fb
  │    2:     0x7fb12f9f69a7 - servo::main::{{closure}}::h35768982dca81cb7
  │    3:     0x7fb132c05b49 - std::panicking::rust_panic_with_hook::h3efc9269f3975b4e
  │                         at src/libstd/panicking.rs:482
  │    4:     0x7fb132c055f1 - std::panicking::continue_panic_fmt::h0bb834397df0d69a
  │                         at src/libstd/panicking.rs:385
  │    5:     0x7fb132c054d5 - rust_begin_unwind
  │                         at src/libstd/panicking.rs:312
  │    6:     0x7fb132c2526c - core::panicking::panic_fmt::hce8ba5bc9a54c6f2
  │                         at src/libcore/panicking.rs:85
  │    7:     0x7fb1305c8149 - core::result::unwrap_failed::h9343c8b2b9049a14
  │    8:     0x7fb130004f94 - script::dom::window::Window::force_reflow::h8755c08dc1efa2b9
  │    9:     0x7fb130005710 - script::dom::window::Window::reflow::h3ade2e9258f01183
  │   10:     0x7fb13030e337 - script::dom::document::Document::finish_load::h1d51dc7e970bdb1b
  │   11:     0x7fb13009a3cf - script::dom::servoparser::ServoParser::do_parse_sync::h9828e4659df15389
  │   12:     0x7fb13059c792 - profile_traits::time::profile::h001f3c91848f4ca1
  │   13:     0x7fb130099a70 - _ZN6script3dom11servoparser11ServoParser10parse_sync17hffab3caf6a26fe09E.llvm.13894101220294098938
  │   14:     0x7fb13009fbdf - <script::dom::servoparser::ParserContext as net_traits::FetchResponseListener>::process_response_eof::h182b25e8d0d95369
  │   15:     0x7fb130542389 - script::script_thread::ScriptThread::handle_msg_from_constellation::h00b1d194fc128cea
  │   16:     0x7fb1305382c4 - _ZN6script13script_thread12ScriptThread11handle_msgs17h9e6b09790e3f4ea7E.llvm.3496197557420798891
  │   17:     0x7fb130533226 - script::script_thread::ScriptThread::start::h1484b91d67faaaad
  │   18:     0x7fb13059c2ce - profile_traits::mem::ProfilerChan::run_with_memory_reporting::ha803eda8ad327b82
  │   19:     0x7fb1306a9134 - std::sys_common::backtrace::__rust_begin_short_backtrace::h918092a582e94f30
  │   20:     0x7fb130beedd5 - _ZN3std9panicking3try7do_call17h1e1a4a7559b185dcE.llvm.9973224621453256981
  │   21:     0x7fb132c10859 - __rust_maybe_catch_panic
  │                         at src/libpanic_unwind/lib.rs:92
  │   22:     0x7fb1309107c7 - <F as alloc::boxed::FnBox<A>>::call_box::hcc4b12433ee715fb
  │   23:     0x7fb132c0fc0d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$RP$$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::hf75cbe88140b524c
  │                         at /rustc/c0bbc3927e28c22edefe6a1353b5ecc95ea9a104/src/liballoc/boxed.rs:734
  │                          - std::sys_common::thread::start_thread::h9fb334ae2abaae80
  │                         at src/libstd/sys_common/thread.rs:14
  │                          - std::sys::unix::thread::Thread::new::thread_start::h772c7ae2e9d50018
  │                         at src/libstd/sys/unix/thread.rs:81
  │   24:     0x7fb12d640183 - start_thread
  │   25:     0x7fb12bf0703c - clone
  │   26:                0x0 - <unknown>
  │ [2019-01-08T14:22:26Z ERROR servo] Layout thread disconnected.: "SendError(..)"
  └ Pipeline failed in hard-fail mode.  Crashing!
```

### LINKED ISSUE #23053: Layout queries on elements in disconnected frames panics
```html
<iframe></iframe>
<script>
  var i = document.querySelector('iframe');
  var d = i.contentDocument;
  var e = d.createElement('div');
  d.body.appendChild(e);
  i.remove();
  setTimeout(function() { e.getBoundingClientRect(); }, 10);
</script>
```
When we remove an iframe, we shut down its browsing context and layout thread. Layout queries assume that the layout thread always exists, however.

### LINKED ISSUE #26429: Refreshing a babylon playground page can panic
```
joshmatthews@joshmatthews-fcmd6r servo-master % ./mach run -d "https://playground.babylonjs.com/full.html#PT4RRN"
Babylon.js v4.2.0-alpha.14 - WebGL1
Layout thread disconnected.: "SendError(..)" (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at components/script/dom/window.rs:1650)
   0: backtrace::backtrace::trace_unsynchronized
   1: <servo::backtrace::Print as core::fmt::Debug>::fmt
   2: core::fmt::write
   3: std::io::Write::write_fmt
   4: servo::backtrace::print
   5: servo::main::{{closure}}
   6: std::panicking::rust_panic_with_hook
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::option::expect_none_failed
  10: core::result::Result<T,E>::expect
  11: script::dom::window::Window::force_reflow
  12: script::dom::window::Window::reflow
  13: script::dom::window::Window::layout_reflow
  14: script::dom::window::Window::client_rect_query
  15: script::dom::node::Node::client_rect
  16: script::dom::element::Element::client_rect
  17: <script::dom::element::Element as script::dom::bindings::codegen::Bindings::ElementBinding::ElementBinding::ElementMethods>::ClientWidth
  18: script::dom::bindings::codegen::Bindings::ElementBinding::ElementBinding::get_clientWidth::{{closure}}
  19: core::ops::function::FnOnce::call_once
  20: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  21: std::panicking::try::do_call
  22: __rust_try
  23: std::panicking::try
  24: std::panic::catch_unwind
  25: mozjs::panic::wrap_panic
  26: script::dom::bindings::codegen::Bindings::ElementBinding::ElementBinding::get_clientWidth
  27: CallJitGetterOp
  28: script::dom::bindings::utils::generic_call
  29: script::dom::bindings::utils::generic_getter
  30: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  31: _ZN2js10CallGetterEP9JSContextN2JS6HandleINS2_5ValueEEES5_NS2_13MutableHandleIS4_EE
  32: _ZN2js17NativeGetPropertyEP9JSContextN2JS6HandleIPNS_12NativeObjectEEENS3_INS2_5ValueEEENS3_INS2_11PropertyKeyEEENS2_13MutableHandleIS7_EE
  33: _ZN2js11GetPropertyEP9JSContextN2JS6HandleINS2_5ValueEEENS3_IPNS_12PropertyNameEEENS2_13MutableHandleIS4_EE
  34: _ZL9InterpretP9JSContextRN2js8RunStateE
  35: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  36: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  37: _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
  38: _ZNK2js22ForwardingProxyHandler4callEP9JSContextN2JS6HandleIP8JSObjectEERKNS3_8CallArgsE
  39: _ZNK2js23CrossCompartmentWrapper4callEP9JSContextN2JS6HandleIP8JSObjectEERKNS3_8CallArgsE
  40: _ZN2js5Proxy4callEP9JSContextN2JS6HandleIP8JSObjectEERKNS3_8CallArgsE
  41: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  42: _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
  43: _Z20JS_CallFunctionValueP9JSContextN2JS6HandleIP8JSObjectEENS2_INS1_5ValueEEERKNS1_16HandleValueArrayENS1_13MutableHandleIS6_EE
  44: mozjs::rust::wrappers::JS_CallFunctionValue
  45: script::dom::bindings::codegen::Bindings::WindowBinding::FrameRequestCallback::Call
  46: script::dom::bindings::codegen::Bindings::WindowBinding::FrameRequestCallback::Call__
  47: script::dom::document::AnimationFrameCallback::call
  48: script::dom::document::Document::run_the_animation_frame_callbacks
  49: script::script_thread::ScriptThread::handle_tick_all_animations
  50: script::script_thread::ScriptThread::handle_msg_from_constellation
  51: script::script_thread::ScriptThread::handle_msgs::{{closure}}
  52: script::script_thread::ScriptThread::profile_event
  53: script::script_thread::ScriptThread::handle_msgs
  54: script::script_thread::ScriptThread::start
  55: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}::{{closure}}
  56: profile_traits::mem::ProfilerChan::run_with_memory_reporting
  57: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}
  58: std::sys_common::backtrace::__rust_begin_short_backtrace
  59: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
  60: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  61: std::panicking::try::do_call
  62: __rust_try
  63: std::panicking::try
  64: std::panic::catch_unwind
  65: std::thread::Builder::spawn_unchecked::{{closure}}
  66: core::ops::function::FnOnce::call_once{{vtable.shim}}
  67: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  68: std::sys::unix::thread::Thread::new::thread_start
  69: _pthread_start
```
It looks like RAF can execute after a pipeline is closed sometimes?

### LINKED ISSUE #26969: Panic removing a stylesheet
Loading http://universidad.continental.edu.pe/, I get the following:
```
called `Result::unwrap()` on an `Err` value: "SendError(..)" (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }, at components/script/dom/document.rs:3720)
   0: backtrace::backtrace::libunwind::trace
             at /Users/cybai/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.48/src/backtrace/libunwind.rs:86
      backtrace::backtrace::trace_unsynchronized
             at /Users/cybai/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.48/src/backtrace/mod.rs:66
   1: <servo::backtrace::Print as core::fmt::Debug>::fmt
             at /Volumes/Transcend/codespace/mozilla/servo/ports/winit/backtrace.rs:49
   2: core::fmt::write
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libcore/fmt/mod.rs:1069
   3: std::io::Write::write_fmt
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/io/mod.rs:1537
   4: servo::backtrace::print
             at /Volumes/Transcend/codespace/mozilla/servo/ports/winit/backtrace.rs:17
   5: servo::main::{{closure}}
             at /Volumes/Transcend/codespace/mozilla/servo/ports/winit/main2.rs:166
   6: std::panicking::rust_panic_with_hook
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/panicking.rs:481
   7: rust_begin_unwind
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/panicking.rs:385
   8: core::panicking::panic_fmt
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libcore/panicking.rs:89
   9: core::option::expect_none_failed
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libcore/option.rs:1272
  10: core::result::Result<T,E>::unwrap
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/result.rs:1005
  11: script::dom::document::Document::remove_stylesheet
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/document.rs:3720
  12: script::dom::stylesheetlist::StyleSheetListOwner::remove_stylesheet
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/stylesheetlist.rs:51
  13: script::dom::htmlstyleelement::HTMLStyleElement::set_stylesheet
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/htmlstyleelement.rs:144
  14: script::dom::htmlstyleelement::HTMLStyleElement::parse_own_css
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/htmlstyleelement.rs:136
  15: <script::dom::htmlstyleelement::HTMLStyleElement as script::dom::virtualmethods::VirtualMethods>::children_changed
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/htmlstyleelement.rs:185
  16: script::dom::node::Node::insert
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/node.rs:2084
  17: script::dom::node::Node::pre_insert
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/node.rs:1989
  18: <script::dom::node::Node as script::dom::bindings::codegen::Bindings::NodeBinding::NodeBinding::NodeMethods>::AppendChild
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/node.rs:2617
  19: script::dom::bindings::codegen::Bindings::NodeBinding::NodeBinding::appendChild::{{closure}}::{{closure}}
             at /Volumes/Transcend/codespace/mozilla/servo/target/debug/build/script-a25fedc82d89c4a8/out/Bindings/NodeBinding.rs:2010
  20: script::dom::bindings::codegen::Bindings::NodeBinding::NodeBinding::appendChild::{{closure}}
             at /Volumes/Transcend/codespace/mozilla/servo/target/debug/build/script-a25fedc82d89c4a8/out/Bindings/NodeBinding.rs:1983
  21: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ops/function.rs:285
  22: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panic.rs:318
  23: std::panicking::try::do_call
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panicking.rs:297
  24: ___rust_try
  25: std::panicking::try
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panicking.rs:274
  26: std::panic::catch_unwind
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panic.rs:394
  27: mozjs::panic::wrap_panic
             at /Users/cybai/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/28248e1/src/panic.rs:22
  28: script::dom::bindings::codegen::Bindings::NodeBinding::NodeBinding::appendChild
             at /Volumes/Transcend/codespace/mozilla/servo/target/debug/build/script-a25fedc82d89c4a8/out/Bindings/NodeBinding.rs:1983
  29: CallJitMethodOp
             at /Users/cybai/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/28248e1/src/jsglue.cpp:585
  30: script::dom::bindings::utils::generic_call
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/bindings/utils.rs:527
  31: script::dom::bindings::utils::generic_method
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/bindings/utils.rs:543
  32: _Z12CallJSNativeP9JSContextPFbS0_jPN2JS5ValueEEN2js10CallReasonERKNS1_8CallArgsE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:456
      _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:548
  33: _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:634
  34: _ZNK2js22ForwardingProxyHandler4callEP9JSContextN2JS6HandleIP8JSObjectEERKNS3_8CallArgsE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/proxy/Wrapper.cpp:162
  35: _ZNK2js23CrossCompartmentWrapper4callEP9JSContextN2JS6HandleIP8JSObjectEERKNS3_8CallArgsE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/proxy/CrossCompartmentWrapper.cpp:237
  36: _ZN2js5Proxy4callEP9JSContextN2JS6HandleIP8JSObjectEERKNS3_8CallArgsE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/proxy/Proxy.cpp:492
  37: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:522
  38: _ZN2js13CallFromStackEP9JSContextRKN2JS8CallArgsE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:621
      _ZL9InterpretP9JSContextRN2js8RunStateE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:3117
  39: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:423
  40: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:589
  41: _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:634
  42: _ZN2js8fun_callEP9JSContextjPN2JS5ValueE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/JSFunction.cpp:1123
  43: _Z12CallJSNativeP9JSContextPFbS0_jPN2JS5ValueEEN2js10CallReasonERKNS1_8CallArgsE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:456
      _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:548
  44: _ZN2js13CallFromStackEP9JSContextRKN2JS8CallArgsE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:621
      _ZL9InterpretP9JSContextRN2js8RunStateE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:3117
  45: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:423
  46: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:589
  47: _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:634
  48: _ZN2js8fun_callEP9JSContextjPN2JS5ValueE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/JSFunction.cpp:1123
  49: _ZN2js9fun_applyEP9JSContextjPN2JS5ValueE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/JSFunction.cpp:1143
  50: _Z12CallJSNativeP9JSContextPFbS0_jPN2JS5ValueEEN2js10CallReasonERKNS1_8CallArgsE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:456
      _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:548
  51: _ZN2js13CallFromStackEP9JSContextRKN2JS8CallArgsE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:621
      _ZL9InterpretP9JSContextRN2js8RunStateE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:3117
  52: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:423
  53: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:589
  54: _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EENS_10CallReasonE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/vm/Interpreter.cpp:634
  55: _Z20JS_CallFunctionValueP9JSContextN2JS6HandleIP8JSObjectEENS2_INS1_5ValueEEERKNS1_16HandleValueArrayENS1_13MutableHandleIS6_EE
             at /Users/cybai/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/jsapi.cpp:2689
  56: mozjs::rust::wrappers::JS_CallFunctionValue
             at /Users/cybai/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/28248e1/src/rust.rs:1453
  57: script::dom::bindings::codegen::Bindings::FunctionBinding::Function::Call
             at /Volumes/Transcend/codespace/mozilla/servo/target/debug/build/script-a25fedc82d89c4a8/out/Bindings/FunctionBinding.rs:321
  58: script::dom::bindings::codegen::Bindings::FunctionBinding::Function::Call_
             at /Volumes/Transcend/codespace/mozilla/servo/target/debug/build/script-a25fedc82d89c4a8/out/Bindings/FunctionBinding.rs:293
  59: script::timers::JsTimerTask::invoke
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/timers.rs:541
  60: script::timers::OneshotTimerCallback::invoke
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/timers.rs:87
  61: script::timers::OneshotTimers::fire_timer
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/timers.rs:222
  62: script::dom::globalscope::GlobalScope::fire_timer
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/globalscope.rs:2653
  63: script::dom::globalscope::TimerListener::handle::{{closure}}
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/dom/globalscope.rs:473
  64: core::ops::function::FnOnce::call_once
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
  65: <script::dom::globalscope::TimerListener::handle::timer_event<F> as script::task::TaskOnce>::run_once
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/task.rs:24
  66: <script::task::CancellableTask<T> as script::task::TaskOnce>::run_once
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/task.rs:116
  67: <T as script::task::TaskBox>::run_box
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/task.rs:57
  68: script::script_thread::ScriptThread::handle_msg_from_script
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/script_thread.rs:1975
  69: script::script_thread::ScriptThread::handle_msgs::{{closure}}
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/script_thread.rs:1540
  70: script::script_thread::ScriptThread::profile_event
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/script_thread.rs:1784
  71: script::script_thread::ScriptThread::handle_msgs
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/script_thread.rs:1533
  72: script::script_thread::ScriptThread::start
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/script_thread.rs:1356
  73: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}::{{closure}}
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/script_thread.rs:796
  74: profile_traits::mem::ProfilerChan::run_with_memory_reporting
             at /Volumes/Transcend/codespace/mozilla/servo/components/profile_traits/mem.rs:88
  75: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/script_thread.rs:794
  76: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/sys_common/backtrace.rs:130
  77: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/mod.rs:475
  78: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panic.rs:318
  79: std::panicking::try::do_call
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panicking.rs:297
  80: ___rust_try
  81: std::panicking::try
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panicking.rs:274
  82: std::panic::catch_unwind
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panic.rs:394
  83: std::thread::Builder::spawn_unchecked::{{closure}}
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/mod.rs:474
  84: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
  85: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/liballoc/boxed.rs:1034
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/liballoc/boxed.rs:1034
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/sys/unix/thread.rs:87
  86: __pthread_body
  87: __pthread_start
```
The first panic corresponds with https://github.com/servo/servo/blob/332aec212c4fff6bca32817749a361f35542f469/components/script/dom/document.rs#L3659-L3662.

### PR DESCRIPTION
**Pull request by alarsyo**
`Window::layout_chan()` now returns an `Option<Sender<Msg>>`, returning `None` if the window is dead.

FIX #26969 
FIX #26429 
FIX #21208
FIX #19092
FIX #22559
FIX #22584
FIX #22652

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #23053 

- [x] There are tests for these changes

This is my first contribution, I'm trying to figure things out!

This fix passes the test case shown in #23053, however I don't know what the behavior should be in `Document` and `ScriptThread` if `Window::is_alive()` is false : simply ignore it, don't do anything ? Or is this something that should not happen now that we return false in `Window::force_reflow()` ?

I'm not sure about the directory where the test case should go, any advice?

### CODE REVIEW

File: components/script/dom/window.rs [hunk 1]
```diff
@@ -2102,8 +2109,12 @@ impl Window {
...
 
-    pub fn layout_chan(&self) -> &Sender<Msg> {
-        &self.layout_chan
+    pub fn layout_chan(&self) -> Option<&Sender<Msg>> {
+        if self.is_alive() {
+            Some(&self.layout_chan)
+        } else {
+            None
+        }
     }
```
Comment (alarsyo) [inline components/script/dom/window.rs:2118]: This could be simplified to:

```diff
     pub fn layout_chan(&self) -> Option<&Sender<Msg>> {
-        if self.is_alive() {
-            Some(&self.layout_chan)
-        } else {
-            None
-        }
+        self.is_alive().then_some(&self.layout_chan)
     }
```

If we add the `#![feature(bool_to_option)]` to the crate, but I'm not sure what's the policy on nightly features is for servo :)

Comment (jdm) [reply components/script/dom/window.rs:2118]: We are open to nightly features if they significantly improve the code in some way, but I don't think this particular case warrants it :)

File: tests/wpt/web-platform-tests/fixme/detached-layout.html [hunk 2]
```diff
@@ -0,0 +1,23 @@
+<!doctype html>
```
Comment (jdm) [inline tests/wpt/web-platform-tests/fixme/detached-layout.html:1]: This test can be moved to tests/wpt/mozilla/tests/mozilla. These are WPT tests that we don't upstream and are used for checking regressions in specific cases in our engine, rather than conformance tests for all engines.

File: components/script/script_thread.rs [hunk 3]
```diff
@@ -2472,7 +2473,7 @@ impl ScriptThread {
             .borrow()
             .iter()
             .next()
-            .map(|(_, document)| document.window().layout_chan().clone())
+            .map(|(_, document)| document.window().layout_chan().unwrap().clone())
```
Comment (jdm) [inline components/script/script_thread.rs:2476]: This map can become and_then and we can remove the unwrap.

File: components/script/dom/window.rs [hunk 4]
```diff
@@ -1553,7 +1556,8 @@ impl Window {
         // TODO Step 1
         // TODO(mrobinson, #18709): Add smooth scrolling support to WebRender so that we can
         // properly process ScrollBehavior here.
-        self.layout_chan
+        self.layout_chan()
+            .unwrap()
```
Comment (jdm) [inline components/script/dom/window.rs:1560]: We'll want to replace these unwraps in this PR with warn! statements and return from the code as soon as possible.

**Review by jdm — CHANGES_REQUESTED** [review]

File: components/script/script_thread.rs [hunk 5]
```diff
@@ -1172,9 +1172,13 @@ impl ScriptThread {
...
-        let _ = window
-            .layout_chan()
-            .send(Msg::RegisterPaint(name, properties, painter));
+
+        match window.layout_chan() {
+            Some(chan) => chan
+                .send(Msg::RegisterPaint(name, properties, painter))
+                .unwrap(),
+            None => warn!("Layout channel unavailable"),
+        }
```
Comment (alarsyo) [inline components/script/script_thread.rs:1181]: Not sure why the `Result` was ignored here and not unwrapped like everywhere else, I've changed it to match with other uses of this channel

**Comment by gterzian** [comment]
I think we can add FIX statements in the opening comment of this PR for all the open issues mentioned at https://github.com/servo/servo/issues/22507#issuecomment-646943564 

while leaving https://github.com/servo/servo/issues/22507 itself open, since we still have the underlying problem of perhaps closing the layout thread too early(or in other words exiting the pipeline, while the related browsing context is still alive even though not fully active), which requires some further investigation.

**Comment by alarsyo** [comment]
Have I done this right? :)

**Comment by gterzian** [comment]
> Have I done this right? :)

Looks like it, Github as added them to list of closing issues on the right panel..


Great work, thanks!

@bors-servo r=jdm

**Comment by CYBAI** [comment]
@bors-servo retry

- #24622
