### PR TITLE
Fix memory leak in flow tree by adding weak refs.

### LINKED ISSUE #4915: Arbitrarily high physical memory usage while scrolling
On both Linux and Mac I can get physical memory usage to become arbitrarily high by repeatedly scrolling up and down the "Guardians of the Galaxy" wikipedia page from servo-static-suite. Here's sample -m output on Linux (with my patches from #4894 applied):
```
_size (MiB)_: _category_
     4530.26: vsize
     1508.38: resident
     1513.60: resident-according-to-smaps
     1465.70: - anonymous (rw-p)
       25.54: - /home/njn/moz/servo/components/servo/target/servo (r-xp)
        6.58: - [heap] (rw-p)
        6.29: - other
        3.55: - /usr/lib/x86_64-linux-gnu/dri/i965_dri.so (r-xp)
        1.36: - /lib/x86_64-linux-gnu/libc-2.19.so (r-xp)
        0.92: - /home/njn/moz/servo/components/servo/target/servo (r--p)
        0.80: - /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.20 (r-xp)
        0.78: - /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0 (r-xp)
        0.68: - /lib/x86_64-linux-gnu/libm-2.19.so (r-xp)
        0.48: - /lib/x86_64-linux-gnu/libglib-2.0.so.0.4200.1 (r-xp)
        0.46: - /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (r-xp)
        0.45: - /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0 (r-xp)
      124.09: system-heap-allocated
       47.72: jemalloc-heap-allocated
       50.70: jemalloc-heap-active
      168.00: jemalloc-heap-mapped
```
The relatively low `system-heap-allocated` and `jemalloc-heap-allocated` numbers indicate that the memory is not on either heap, so it must be coming from mmap(). I did some measurement with `vmmap` on Mac and it gave me similar indications that it's not heap memory.

I normally use Massif to investigate such cases but I'm getting various task failures when I run Servo under Massif and view this page, alas.

### PR DESCRIPTION
**Pull request by metajack**
Cycles were being created in the flow tree since absolutely positioned
descendants had pointers to their containing blocks. This adds
WeakFlowRef (based on Weak<T>) and makes these backpointers weak
references. This also harmonizes our custom Arc<T>, FlowRef, to be
consistent with the upstream implementation.

Fixes #4915.

### CODE REVIEW

**Comment by metajack** [comment]
I suggest reviewing while looking at liballoc/arc.rs for reference.

File: components/layout/flow_ref.rs [hunk 1]
```diff
@@ -37,6 +48,15 @@ impl FlowRef {
             result
         }
     }
+
+    /// Downgrades the FlowRef to a WeakFlowRef.
+    pub fn downgrade(&self) -> WeakFlowRef {
+        unsafe {
+            flow::base(&**self).weak_ref_count().fetch_add(1, Ordering::Relaxed);
+        }
+        //thread_log(format!("{:p} - {:?} downgrading FlowRef", flow::base(&**self), (**self).class()));
```
Comment (pcwalton) [inline components/layout/flow_ref.rs]: Remove

File: components/layout/flow_ref.rs [hunk 2]
```diff
@@ -92,3 +134,72 @@ impl Clone for FlowRef {
         }
     }
 }
+
+impl WeakFlowRef {
+    /// Upgrades a WeakFlowRef to a FlowRef.
+    pub fn upgrade(&self) -> Option<FlowRef> {
+        unsafe {
+            let object = flow::base(&**self);
```
Comment (pcwalton) [inline components/layout/flow_ref.rs]: Can you copy the comment from `arc.rs`:

        // We use a CAS loop to increment the strong count instead of a fetch_add because once the
        // count hits 0 is must never be above 0.

File: components/layout/flow_ref.rs [hunk 3]
```diff
@@ -92,3 +134,72 @@ impl Clone for FlowRef {
...
+            if flow::base(&**self).weak_ref_count().fetch_sub(1, Ordering::Release) == 1 {
+                atomic::fence(Ordering::Acquire);
+
+                let weak_ref: WeakFlowRef = mem::replace(self, WeakFlowRef {
+                    object: raw::TraitObject {
+                        vtable: ptr::null_mut(),
+                        data: ptr::null_mut(),
+                    }
+                });
+                let vtable: &[usize; 3] = mem::transmute::<*mut (), &[usize; 3]>(weak_ref.object.vtable);
```
Comment (pcwalton) [inline components/layout/flow_ref.rs]: Can you add a comment here explaining that this dance is designed to deallocate the flow without running its drop glue?

**Comment by metajack** [comment]
All comments should be addressed. I can will squash before they get merged.

**Comment by pcwalton** [comment]
r=me, squash away!

**Comment by nnethercote** [comment]
@metajack: I have some draft code for measuring the flow tree in #5152 (that PR is now closed but I plan to rework that code eventually). That code was not catching this leak -- it was saying that the flow tree remained a constant size while "jemalloc-heap-allocated" was rising. Should it have been? If so, any ideas which parts of the structure I might be failing to measure? Thank you.

**Comment by metajack** [comment]
@nnethercote So the flow tree was never increasing in size. There were strong cycles in it that prevented it from ever being freed when there were absolutely positioned elements. The cycle was caused by BaseFlow.absolute_cb, which was a backlink to the nearest containing block.

It's possible you weren't following this when calculating the size of the tree or were intentionally allowing cycles by checking against already included Flows.

Each reflow (of which there were ~3 even without any activity due to other bugs) was causing a whole new flow tree to be built which would also be leaked. Mouse move events were changing hover state, which currently causes full reflows. So while the flow tree wasn't growing, we were producing and leaking one for each of these reflows.

**Comment by nnethercote** [comment]
Unreachable cycles, then... can't be expected to measure those. Thank you for the explanation.

**Comment by metajack** [comment]
They weren't unreachable always, only after a new reflow removes them from the DOM nodes. It's not clear to me whether your code wanted to include those in its size calculations or not. Certainly the Option<FlowRef> should have been counted as part of the size of BaseFlow. I think it makes sense not to count the Flow that potentially points to.

**Comment by jdm** [comment]
I guess that would be equivalent to the window/dom/orphan-nodes tree in about:memory in Firefox - it measures DOM trees that are reachable through some mysterious mechanism, but aren't part of an actual DOM tree for a page.

**Comment by nnethercote** [comment]
> Certainly the Option should have been counted as part of the size of BaseFlow.

Which Option is that?

**Comment by Ms2ger** [comment]
`Option<FlowRef>`

**Comment by metajack** [comment]
I think it might be `Option<ContainingBlockLink>` which is a struct with one field that holds a `FlowRef`.
