### PR TITLE
Hold stderr lock when using stdout through Console APIs.

### LINKED ISSUE #12797: Intermittent timeout in /html/browsers/browsing-the-web/navigating-across-documents/014.html and /html/browsers/browsing-the-web/navigating-across-documents/013.html and /html/browsers/browsing-the-web/navigating-across-documents/015.html
This looks like an issue caused by interleaving output?

```
  ▶ TIMEOUT [expected OK] /html/browsers/browsing-the-web/navigating-across-documents/014.html
  │ 
  │ ERROR:script::dom::bindings::error: Error at :0:1 parent.events is undefinedALERT: RESULT: ["/html/browsers/browsing-the-web/navigating-across-documents/014.html",0,null,null,[[" Link with javascript onclick form submission script order ",1,"assert_array_equals: lengths differ, expected 2 got 1","onload<@http://web-platform.test:8000/html/browsers/browsing-the-web/navigating-across-documents/014.html:9:3\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20\nTest.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1426:20\n"]]]
  └ 
```

### PR DESCRIPTION
**Pull request by jdm**
This addresses a longstanding source of intermittent test failures where the stderr and stdout outputs get interleaved and the test harness becomes confused.

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #12797
- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17360)

### CODE REVIEW

File: components/script/dom/console.rs [hunk 1]
```diff
@@ -27,74 +28,96 @@ impl Console {
     }
 }
 
+fn with_stderr_lock<F>(f: F) where F: FnOnce() {
```
Comment (emilio) [inline components/script/dom/console.rs]: Could you add a comment here on why is it needed?

File: components/script/dom/console.rs [hunk 2]
```diff
@@ -27,74 +28,96 @@ impl Console {
...
+
 impl Console {
     // https://developer.mozilla.org/en-US/docs/Web/API/Console/log
     pub fn Log(global: &GlobalScope, messages: Vec<DOMString>) {
-        for message in messages {
-            println!("{}", message);
-            Self::send_to_devtools(global, LogLevel::Log, message);
-        }
+        with_stderr_lock(move || {
+            for message in messages {
```
Comment (emilio) [inline components/script/dom/console.rs]: Also, I wonder whether we should split this loop (and the others) into two, one that does the printing with the lock held, and other that calls `send_to_devtools`.

I say that, because as far as I can tell, that function can panic and log (it uses `downcast`, which calls `get_dom_class`, which does `trace!`, which writes to stderr I think). I'd expect this to deadlock with `RUST_LOG=trace`, wouldn't it? or is the lock re-entrant? If it is, please comment on it.

Comment (jdm) [inline components/script/dom/console.rs]: The stderr lock is reentrant, yes.

File: components/script/dom/console.rs (hunk 1 above)
Comment (jdm) [inline components/script/dom/console.rs]: Done.
