### PR TITLE
Only access hit test items for the current epoch in the compositor

### LINKED ISSUE #29796: Error browsing divMosaics experiment
I was testing a Servo release build with Layout 2020 enabled.

Going to this page https://demo.servo.org/experiments/divMosaics/ and playing around with it, some things I did:
* Click on different images
* Scroll a little bit down
* Click on other images

I cannot reproduce it exactly, but I've got the following backtrace at some point:
```
index out of bounds: the len is 1025 but the index is 1629 (thread main, at ~/checkout/servo/components/compositing/compositor.rs:1059)
   0: servo::backtrace::print
   1: servo::main::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:692:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:579:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:137:18
   5: rust_begin_unwind
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:575:5
   6: core::panicking::panic_fmt
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:64:14
   7: core::panicking::panic_bounds_check
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:159:5
   8: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
   9: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  10: compositing::compositor::IOCompositor<Window>::hit_test_at_point_with_flags_and_pipeline
  11: compositing::compositor::IOCompositor<Window>::dispatch_mouse_window_move_event_class
  12: servo::Servo<Window>::handle_events
  13: servo::app::App::handle_events
  14: servo::events_loop::EventsLoop::run_forever::{{closure}}
  15: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run
  16: winit::platform_impl::platform::EventLoop<T>::run
  17: winit::event_loop::EventLoop<T>::run
  18: servo::events_loop::EventsLoop::run_forever
  19: servo::main
  20: std::sys_common::backtrace::__rust_begin_short_backtrace
  21: std::rt::lang_start::{{closure}}
  22: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/ops/function.rs:287:13
      std::panicking::try::do_call
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/rt.rs:148:20
  23: main
  24: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  25: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:381:3
  26: _start
[2023-05-25T14:23:15Z ERROR servo] index out of bounds: the len is 1025 but the index is 1629
```

### PR DESCRIPTION
**Pull request by mrobinson**
When display lists update quickly, a hit test result might be returned
for a previous display list / list of hit test items. When that happens,
ignore the hit test result.

This fixes a crash, but there might be situations where we can do
something better, such as wait for display list processing to finish
before performing the hit test. A future change might do this for events
like mouse clicks and touch events that should never be thrown away.
Ultimately, the best thing is likely moving hit testing back to layout
or script so a valid hit test can always be performed against the
current DOM.

Fixes #29796.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #29796.
- [x] These changes do not require tests because there still isn't a good way to test behavior of rapidly changing display lists and mouse movement over the compositor.

### CODE REVIEW

File: third_party/webrender/webrender_api/src/lib.rs [hunk 1]
```diff
@@ -92,6 +92,13 @@ impl Epoch {
     pub fn invalid() -> Epoch {
         Epoch(u32::MAX)
     }
+
+    /// The value of this [`Epoch`] as a u16 value. Note that if this Epoch's
+    /// value is more than u16::MAX, then the return value will be modulo
+    /// u16::MAX.
+    pub fn as_u16(&self) -> u16 {
```
Comment (mukilan) [inline third_party/webrender/webrender_api/src/lib.rs:99]: Does this require a patch file [here](https://github.com/servo/servo/tree/master/third_party/webrender/patches) ?

**Comment by mrobinson** [comment]
> Just curious if we know which of the two approaches Gecko uses for hit-testing - does it block until DL is processed or does it do hit-testing via layout/script as you've suggested?

I believe that Gecko does some minor hit testing in WebRender (for APZ, perhaps), but the hit testing for DOM events is done with the flow tree -- which means that it doesn't have this issue.

> Does this require a patch file [here](https://github.com/servo/servo/tree/master/third_party/webrender/patches) ?

Oh, this shouldn't be here at all. I'll upload a new version of this change that doesn't modify WebRender. Thanks!

File: third_party/webrender/webrender_api/src/lib.rs (hunk 1 above)
Comment (mrobinson) [reply third_party/webrender/webrender_api/src/lib.rs:99]: Okay. I've uploaded a new version of this change that turns this into a trait in `gfx_traits`.

**Review by mukilan — APPROVED** [review]
