### PR TITLE
Dont draw interior borders for text run fragments

### LINKED ISSUE #4658: Border renders incorrectly on `<code>` tag with escape characters
Code I used to test:
```html
<html>
<head>
<style>
code {
	border-radius:3px;
	border: 1px solid #ccc;
}
</style>
</head>
<body>
<code>
I like green eggs &amp; ham.
</code>
</body>
</html>
```

This is the output:
2015-01-18-214947_1440x900_scrot

The same problem happens with other escape codes, and if you replace `<code>` with an invalid tag, like `<dummy>`.

### PR DESCRIPTION
**Pull request by bjwbell**
Inline fragments that are part of a text run don't have interior borders.
So don't draw interior borders or include them when calculating positioning.

Fixes https://github.com/servo/servo/issues/4658, where multiple text nodes that are adjacent have distinct borders.

r? @Ms2ger, @pcwalton

### CODE REVIEW

**Comment by pcwalton** [comment]
Thank you, I've been meaning to do this for a long time! :)

File: components/layout/fragment.rs [hunk 1]
```diff
@@ -1079,6 +1080,25 @@ impl Fragment {
...
+                };
+                if begin > 0 {
+                    border.inline_start = Zero::zero();
+                }
+                if end < run_len {
+                    border.inline_end = Zero::zero();
+                }
+            },
+            _ => ()
+        };
```
Comment (pcwalton) [inline components/layout/fragment.rs]: This should be factored out into a separate function and shared between DL building and here. (Part of `Fragment` is fine.)

**Comment by pcwalton** [comment]
This code shouldn't be specific to text fragments, actually. Consider this document:

    <!DOCTYPE html>
    <html>
    <head>
    <style>
    .bordery {
        border: solid black 1px;
    }
    </style>
    </head>
    <body>
    <p>
    <span class=bordery>FooBar</span>
    </p>
    </body>
    </html>

Per the spec, there's not supposed to be an an interior border between "Foo" and the image.

To handle this case, instead of looking at the boundaries of the text run, I think the easiest place the handle this in the current design would be in flow construction. Set the border width to zero and the border style to `None` on border sides that are not the outermost for a given span. Looking at the code (which has changed since I last worked on it) it may be easiest to do this in `Fragment::add_inline_context_style`—try adding an extra parameter that specifies whether this is the first fragment for the inline element in the inline-start/inline-end direction.

**Comment by bjwbell** [comment]
Thanks for the review @pcwalton! I'll move it to flow construction. TBH I know the code right now wasn't what I wanted & I was hoping you'd have an idea of where was better. Which you did :-)

**Comment by bjwbell** [comment]
@pcwalton Improvement.

File: components/layout/construct.rs [hunk 2]
```diff
@@ -198,8 +198,17 @@ impl InlineFragmentsAccumulator {
 
         match enclosing_style {
             Some(enclosing_style) => {
```
Comment (pcwalton) [inline components/layout/construct.rs]: nit: While you're here, can you change this to `if let Some(enclosing_style) = enclosing_style` and reduce indentation in the code below?

File: components/layout/construct.rs [hunk 3]
```diff
@@ -198,8 +198,17 @@ impl InlineFragmentsAccumulator {
...
+                let mut frag_idx = 0;
+                let frag_len = fragments.len();
                 for frag in fragments.iter_mut() {
```
Comment (pcwalton) [inline components/layout/construct.rs]: I'd change this to `for (frag_idx, frag) in fragments.iter_mut().enumerate() {` and eliminate the `frag_idx` temporary.

File: components/layout/fragment.rs [hunk 4]
```diff
@@ -877,11 +878,32 @@ impl Fragment {
...
+    pub fn add_inline_context_style(&mut self,
+                                    style: Arc<ComputedValues>,
+                                    first_frag: bool,
+                                    last_frag: bool) {
+
+        let mut frag_style : Arc<ComputedValues>;
         if self.inline_context.is_none() {
             self.inline_context = Some(InlineFragmentContext::new());
+        }        
+        if first_frag && last_frag {
```
Comment (pcwalton) [inline components/layout/fragment.rs]: Could just be `let frag_style = if first_frag && last_frag { ... } else { ... }` and avoid having to make `frag_style` mutable.

**Comment by pcwalton** [comment]
Excellent! Just a couple of nits and I'll be happy to get this in.

File: components/layout/construct.rs (hunk 3 above)
Comment (bjwbell) [inline components/layout/construct.rs]: Whoops! Sry about that.

**Comment by bjwbell** [comment]
Great :-) I'll do the changes & update the PR (probably not till after lunch).

Thanks

**Comment by bjwbell** [comment]
@pcwalton Fixed the nits
