### PR TITLE
layout: Do not include `position:fixed` children when calculating scrollable overflow for root element

### LINKED ISSUE #38182: Servo allows horizontal scrolling where it shouldn't
Testcase:
```html
<!doctype html>
<html>
    <head>
        <style>
            html {
                height: 100%;
            }
            .page-gradient {
                width: 100%;
                height: 200px;
                background-color: black;
            }

            .sitebar {
                position: relative;
                left: 100%;
            }
            .ad-flex {
                position: fixed;
                height: 100%;
                width: 100%;
            }
        </style>
    </head>

    <body>
        <div class="page-gradient"></div>

        <div id="sitebar-wrapper">
            <div class="sitebar">
                <div class="ad-flex"></div>
            </div>
        </div>
    </body>
</html>
```

Minimized from https://wetter.com

### PR DESCRIPTION
**Pull request by stevennovaryo**
Reimplementation of: #35931

For a `FragmentTree` we define a scrollable overflow calculation that includes the overflow all of it's children `Fragments`. In practice we are using this calculation for scrolling area of the viewport and defining the root scroll frames. However, since uncontained fixed positioned element is located outside of the document and should not be scrolled, and therefore it would make no sense to include them in the calculation of its scrollable overflow as well.

Testing: New and existing WPT tests
Fixes: #38617
Fixes: #38182

### CODE REVIEW

**Comment by simonwuelker** [comment]
Can you check whether this fixes https://github.com/servo/servo/issues/38182 too?

File: components/layout/fragment_tree/fragment_tree.rs [hunk 1]
```diff
@@ -117,9 +118,25 @@ impl FragmentTree {
...
+                        fragment
+                            .retrieve_box_fragment()
+                            .is_some_and(|box_fragment| {
+                                box_fragment.borrow().style.get_box().position != Position::Fixed
+                            });
+
+                    match should_include_overflow {
+                        true => overflow.union(&calculated_overflow),
+                        false => overflow,
+                    }
```
Comment (mrobinson) [inline components/layout/fragment_tree/fragment_tree.rs]: I think it would make more sense to move this to `BoxFragment::scrollable_overflow_for_parent`. You can add an early return of `Zero::zero()` if the box uses fixed positioning.

What does "uncontained" mean in this case?

**Review by mrobinson — CHANGES_REQUESTED** [review]

File: components/layout/fragment_tree/fragment_tree.rs (hunk 1 above)
Comment (stevennovaryo) [reply components/layout/fragment_tree/fragment_tree.rs]: > I think it would make more sense to move this to `BoxFragment::scrollable_overflow_for_parent`. You can add an early return of `Zero::zero()` if the box uses fixed positioning.

AFAIU, the fragment tree is arranged so that a fragment's parent is its containing block, so we doesn't to care about position there. But for fragment tree it would be different, since it contains all of the fragments, and this would the corner cases of the scrollable overflow.

> What does "uncontained" mean in this case?

Just to define fixed element without ancestor that would "contain it". Adding more context..

**Comment by stevennovaryo** [comment]
> Can you check whether this fixes #38182 too?

Missed that issue, seems to be working fine after this fix.  👍

File: components/layout/fragment_tree/fragment_tree.rs (hunk 1 above)
Comment (mrobinson) [reply components/layout/fragment_tree/fragment_tree.rs]: `scrollable_overflow_for_parent` is only called one place, this place, so it is safe to move it there.

Comment (stevennovaryo) [reply components/layout/fragment_tree/fragment_tree.rs]: > scrollable_overflow_for_parent is only called one place, this place, so it is safe to move it there.

Since it is used to calculate overflow of all `Fragment`s, we will need to checks whether the fixed positioned fragment is contained by its parent or not. And, I am afraid that it would introduce unnecessary checks. We could introduce `scrollable_overflow_for_fragment_tree` (or something similar) though. 🤔

Please correct me if I am missing something though.

File: tests/wpt/tests/css/css-overflow/scrollable-overflow-iframe-uncontained-fixed-positioned.html [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+  </iframe>
+</body>
+<script>
+promise_test(async (t) => {
+  await new Promise(resolve => target.addEventListener('load', resolve));
+
+  assert_less_than(target.contentDocument.documentElement.scrollHeight, 1000);
+  assert_less_than(target.contentDocument.documentElement.scrollWidth, 1000);
+
+}, "Uncontained fixed positioned shouldn't affect scrollable overflow of a document element.");
```
Comment (mrobinson) [inline tests/wpt/tests/css/css-overflow/scrollable-overflow-iframe-uncontained-fixed-positioned.html]: Why use an iframe here? Couldn't you just check the scrollHeight and scrollWidth of the current document? I'm also a bit confused because in this case, the fixed position child does not have a parent in the fragment tree...so should be taken into account in `FragmentTree::calculate_scrollable_overflow`. You can see this by running servo with `-Z dump-flow-tree`.

File: components/layout/fragment_tree/fragment_tree.rs [hunk 3]
```diff
@@ -117,9 +118,26 @@ impl FragmentTree {
...
-                        .calculate_scrollable_overflow_for_parent()
-                        .union(&overflow)
+                    // We need to calculate the overflow for each fragments within the tree
+                    // to be processed in the further stages of reflow.
+                    let calculated_overflow = fragment.calculate_scrollable_overflow_for_parent();
+
+                    // Fixed positioned element that is not contained by any box is placed
+                    // as a child of the fragment tree. But, it is not contained by the
+                    // initial containing block, cannot be scrolled, and should not included
+                    // in the calculation.
```
Comment (mrobinson) [inline components/layout/fragment_tree/fragment_tree.rs]: "not contained by any box" is still a very weird thing in terms of CSS terminology. All boxes have a containing block and we don't commonly say that an element that establishes another element's containing block "contains that element." The problem is that it's very ambiguous. Better to say that outright that an "element establishes the containing block for a fixed position descendant."

Wording aside, I think this change isn't quite right. If the child is fixed position, then the parent here is the fixed positioned element's containing block, ie it's an element that establishes a containing block for all descendants. For instance, an element with a transform establishes a containing block for fixed ancestors and indeed affects its scroll overflow. If it doesn't have a parent (is a child of the root), then it's containing block is the _initial containing block_.

In this test case:

```html
<!DOCTYPE html>

<div id="foo" style="overflow: scroll; transform: translateX(100px); width: 200px; height: 200px; outline: solid; overflow: auto;">
    <div style="position: fixed; height: 300px; width: 100px; background: pink;">hello</div>
</div>
```

The `overflow: scroll` parent establishes a containing block for the fixed position child. This doesn't happen if you remove the transform on the parent.

Indeed the [specification that really matters here](https://www.w3.org/TR/css-overflow-3/#scrollable) says nothing about fixed position boxes, but it does say this:

> The border boxes of all boxes for which it is the containing block and whose border boxes are positioned not wholly in the [negative scrollable overflow region](https://www.w3.org/TR/css-overflow-3/#negative-scrollable-overflow-region), accounting for transforms by projecting each box onto the plane of the element that establishes its [3D rendering context](https://www.w3.org/TR/css-transforms-2/#3d-rendering-context). [[CSS3-TRANSFORMS]](https://www.w3.org/TR/css-overflow-3/#biblio-css3-transforms)

I think this means that fixed positioned boxes that are children of the root (no parent) should not be taken into account for scrollable overflow.

**Review by mrobinson — CHANGES_REQUESTED** [review]

File: components/layout/fragment_tree/fragment_tree.rs (hunk 3 above)
Comment (stevennovaryo) [reply components/layout/fragment_tree/fragment_tree.rs]: > "not contained by any box" is still a very weird thing in terms of CSS terminology. All boxes have a containing block and we don't commonly say that an element that establishes another element's containing block "contains that element." The problem is that it's very ambiguous. Better to say that outright that an "element establishes the containing block for a fixed position descendant."

We also have specific cases when there are no ancestor (element) established one such containing block, but, I agree that "box" could be changed to "ancestor". Maybe like "Fixed positioned element without any ancestor that establishes fixed containing block...". 

Nevertheless, the important things here is about the understanding of the spec. 

> I think this means that fixed positioned boxes that are children of the root (no parent) should not be taken into account for scrollable overflow.

This is not correct, the spec says (albeit in quite convoluted way) that "For a box `A`, any boxes that the box `A` is the containing block, we should include their border boxes if the border boxes are positioned not wholly....".

This is shown by this case:
```html
<style>
    .target-1 {
        width: 100%;
        height: 200px;
        background-color: green;
        margin-top: 200px;
        position: fixed;
    }
    .target-2 {
        width: 100%;
        height: 200px;
        background-color: red;
        position: fixed;
    }
    .container {
        width: 100px;
        height: 100px;
        will-change: transform;
        overflow: scroll;
    }
</style>

<div class="container">
    <div class="target-1"></div>
    <div class="target-2"></div>
</div>
```

Where we could scroll the container that established a fixed containing block. 

>  I'm also a bit confused because in this case, the fixed position child does not have a parent in the fragment tree...so should be taken into account in FragmentTree::calculate_scrollable_overflow. You can see this by running servo with -Z dump-flow-tree

Looking at the implementation, for Servo, the "parent" of fixed positioned child is the `FragmentTree` itself. We calculated the `scrollable_overflow` of a `FragmentTree` as the union of all it's children. This is correct for a `Fragment` but for a `FragmentTree` we also have the fixed positioned child without any ancestor that establishes a fixed containing block.

And, we used these for the root scroll node's `content_rect`, viewport `ScrollHeight`, and viewport `ScrollWidth`. For root scroll node, it does not make sense to include them since the "containing block" for them is the reference frame. See 
https://github.com/servo/servo/blob/60299763658a7239062b3fcd8b769e89d7569038/components/layout/display_list/stacking_context.rs#L166-L178

Thus, they are not scrollable by it in the first hand.

File: tests/wpt/tests/css/css-overflow/scrollable-overflow-iframe-uncontained-fixed-positioned.html (hunk 2 above)
Comment (stevennovaryo) [reply tests/wpt/tests/css/css-overflow/scrollable-overflow-iframe-uncontained-fixed-positioned.html]: > Why use an iframe here? Couldn't you just check the scrollHeight and scrollWidth of the current document?

Little bit afraid of about messing with the `Document` itself, where the ICB size, window size matters. Iframe it not perfect, by the means that it add another dependency, but it acts like a sandboxes here. Do you have a recommendation for adding a test with the document?

File: components/layout/fragment_tree/fragment_tree.rs (hunk 3 above)
Comment (mrobinson) [reply components/layout/fragment_tree/fragment_tree.rs]: > We also have specific cases when there are no ancestor (element) established one such containing block, but, I agree that "box" could be changed to "ancestor". Maybe like "Fixed positioned element without any ancestor that establishes fixed containing block...".

Nope, this is still wrong. A fixed position **element** can have the initial containing block as its containing block, but still have an ancestor in the flat tree. At the very least, unless the fixed position element is the root element, then it always has an ancestor. I think the thing here is that we are getting confused talking about the ancestor of the element and the ancestor of the fragment in the fragment tree. The fixed positioned **element** has an ancestor, but the fixed positioned **fragment** is much more likely to not have an ancestor in the fragment tree.

> > I think this means that fixed positioned boxes that are children of the root (no parent) should not be taken into account for scrollable overflow.
> 
> This is not correct, the spec says (albeit in quite convoluted way) that "For a box `A`, any boxes that the box `A` is the containing block, we should include their border boxes if the border boxes are positioned not wholly....".
> 
> This is shown by this case:
> 
> ```
> <style>
>     .target-1 {
>         width: 100%;
>         height: 200px;
>         background-color: green;
>         margin-top: 200px;
>         position: fixed;
>     }
>     .target-2 {
>         width: 100%;
>         height: 200px;
>         background-color: red;
>         position: fixed;
>     }
>     .container {
>         width: 100px;
>         height: 100px;
>         will-change: transform;
>         overflow: scroll;
>     }
> </style>
> 
> <div class="container">
>     <div class="target-1"></div>
>     <div class="target-2"></div>
> </div>
> ```
> 
> Where we could scroll the container that established a fixed containing block.

This isn't the case that I was trying to refer to though. This is the case where a fixed position child has a containing block which isn't the initial containing block. What I'm suggesting is that when the containing block of a fixed positioned element is the initial containing block, perhaps it should not be considered for scroll overflow calculation. The specification says that "For a box `A`, any boxes that the box `A` is the containing block, we should include their border boxes if the border boxes are positioned not wholly....". When the containing block is the initial containing block, I think that means that there is no box `A` that is the containing block for the fixed positioned element.

> > I'm also a bit confused because in this case, the fixed position child does not have a parent in the fragment tree...so should be taken into account in FragmentTree::calculate_scrollable_overflow. You can see this by running servo with -Z dump-flow-tree

> Looking at the implementation, for Servo, the "parent" of fixed positioned child is the `FragmentTree` itself. We calculated the `scrollable_overflow` of a `FragmentTree` as the union of all it's children. This is correct for a `Fragment` but for a `FragmentTree` we also have the fixed positioned child without any ancestor that establishes a fixed containing block.

In this case, the fixed positioned `Fragment` is right under the root of the `FragmentTree`, but your change doesn't address that case, so I'm confused how it affects the outcome.

Comment (stevennovaryo) [reply components/layout/fragment_tree/fragment_tree.rs]: Okay, ah sorry, I get the point now.

> In this case, the fixed positioned Fragment is right under the root of the FragmentTree, but your change doesn't address that case, so I'm confused how it affects the outcome.

Not sure are we referring to the same cases or not, but for cases like `data:text/html, <div style="position: fixed;"></div>`, the fragment(s) is placed inside the `FragmentTree.root_fragments` alongside root fragment which is the first in the list.

AFAIU, fixed positioned fragment will reside under root fragment when root fragment establishes containing block for fixed positioned fragment, which seems conformant to the spec.  They are scrollable, and could extend the scrollable area.

https://drafts.csswg.org/css-position/#fixed-cb

> If no ancestor establishes one, the [fixed positioning containing block](https://drafts.csswg.org/css-position/#fixed-positioning-containing-block) is:
> - in [continuous media](https://drafts.csswg.org/mediaqueries-5/#continuous-media), the [layout viewport](https://drafts.csswg.org/cssom-view-1/#layout-viewport) (whose size matches the [dynamic viewport size](https://drafts.csswg.org/css-values-4/#dynamic-viewport-size)); as a result, [fixed](https://drafts.csswg.org/css-position/#fixed-position) boxes do not move when the document is scrolled.

<details>
<summary>Print Flow Tree Result</summary>
<pre>
┌ Fragment Tree
│  ├─ Box
│  │         base=BaseFragment { tag: Some(Tag { node: OpaqueNode(43961552470312), pseudo: None }), flags: FragmentFlags(IS_ROOT_ELEMENT) }
│  │         content=Rect(1024pxx8px at (0px, 0px))
│  │         padding rect=Rect(1024pxx8px at (0px, 0px))
│  │         border rect=Rect(1024pxx8px at (0px, 0px))
│  │         margin=(0px,0px,0px,0px)
│  │         scrollable_overflow=Rect(1024pxx8px at (0px, 0px))
│  │         baselines=Baselines { first: None, last: None }
│  │         overflow=AxesOverflow { x: Visible, y: Visible }
│  │  ├─ Box
│  │  │         base=BaseFragment { tag: Some(Tag { node: OpaqueNode(43961552470392), pseudo: None }), flags: FragmentFlags(IS_BODY_ELEMENT_OF_HTML_ELEMENT_ROOT) }
│  │  │         content=Rect(1008pxx0px at (8px, 8px))
│  │  │         padding rect=Rect(1008pxx0px at (8px, 8px))
│  │  │         border rect=Rect(1008pxx0px at (8px, 8px))
│  │  │         margin=(8px,8px,8px,8px)
│  │  │         scrollable_overflow=Rect(1008pxx0px at (8px, 8px))
│  │  │         baselines=Baselines { first: None, last: None }
│  │  │         overflow=AxesOverflow { x: Visible, y: Visible }
│  │  │  └─ AbsoluteOrFixedPositioned
│  ├─ Box
│  │         base=BaseFragment { tag: Some(Tag { node: OpaqueNode(43961552470432), pseudo: None }), flags: FragmentFlags(0x0) }
│  │         content=Rect(0pxx0px at (8px, 8px))
│  │         padding rect=Rect(0pxx0px at (8px, 8px))
│  │         border rect=Rect(0pxx0px at (8px, 8px))
│  │         margin=(0px,0px,0px,0px)
│  │         scrollable_overflow=Rect(0pxx0px at (8px, 8px))
│  │         baselines=Baselines { first: None, last: None }
│  │         overflow=AxesOverflow { x: Visible, y: Visible }
</pre>
</details>

Comment (mrobinson) [reply components/layout/fragment_tree/fragment_tree.rs]: > Not sure are we referring to the same cases or not, but for cases like `data:text/html, <div style="position: fixed;"></div>`, the fragment(s) is placed inside the `FragmentTree.root_fragments` alongside root fragment which is the first in the list.


Perhaps the fix is to ignore just the fixed position fragments that are directly in the `FragmentTree::root_fragments` vector as these are the fragments that have the initial containing block as their containing blocks?

Comment (stevennovaryo) [reply components/layout/fragment_tree/fragment_tree.rs]: > Perhaps the fix is to ignore just the fixed position fragments that are directly in the FragmentTree::root_fragments vector as these are the fragments that have the initial containing block as their containing blocks?

Yes, I believe that is what is PR planning to do. What do you think about the current changes?

File: tests/wpt/tests/css/css-overflow/scrollable-overflow-iframe-uncontained-fixed-positioned.html (hunk 2 above)
Comment (mrobinson) [reply tests/wpt/tests/css/css-overflow/scrollable-overflow-iframe-uncontained-fixed-positioned.html]: I think you could avoid the `<iframe>` and make the test a bit stronger by:

1. Measuring the `scrollHeight` and `scrollWidth` of the main document.
2. Adding the big `position: fixed` element to the page contents. You can make it programmatically twice as large as the dimensions you measured before.
3. Measure the `scrollHeight` and `scrollWidth` of the page after and assert that they are the same.

`<iframe>` loading and such add a lot of complications to the test.

File: components/layout/fragment_tree/fragment_tree.rs [hunk 4]
```diff
@@ -117,9 +118,27 @@ impl FragmentTree {
...
+                        fragment
+                            .retrieve_box_fragment()
+                            .is_some_and(|box_fragment| {
+                                box_fragment.borrow().style.get_box().position != Position::Fixed
+                            });
+
+                    match should_include_overflow {
+                        true => overflow.union(&calculated_overflow),
+                        false => overflow,
+                    }
```
Comment (mrobinson) [inline components/layout/fragment_tree/fragment_tree.rs]: Nit: I think an early return is a little bit nicer here rather than a `match` on a boolean which always feels a bit odd:

```suggestion 
                    if fragment
                            .retrieve_box_fragment()
                            .is_some_and(|box_fragment| {
                                box_fragment.borrow().style.get_box().position != Position::Fixed
                            })
                      {
                            return overflow;
                       }
                      fragment
                          .calculate_scrollable_overflow_for_parent()
                          .union(&overflow),
```

File: components/layout/fragment_tree/fragment_tree.rs [hunk 5]
```diff
@@ -117,9 +118,27 @@ impl FragmentTree {
             let scrollable_overflow = self.root_fragments.iter().fold(
                 self.initial_containing_block,
                 |overflow, fragment| {
-                    fragment
-                        .calculate_scrollable_overflow_for_parent()
-                        .union(&overflow)
+                    // We need to calculate the overflow for each fragments within the tree
+                    // to be processed in the further stages of reflow.
+                    let calculated_overflow = fragment.calculate_scrollable_overflow_for_parent();
```
Comment (mrobinson) [inline components/layout/fragment_tree/fragment_tree.rs]: I wouldn't do this is the fragment is position fixed.

File: components/layout/fragment_tree/fragment_tree.rs [hunk 6]
```diff
@@ -117,9 +118,27 @@ impl FragmentTree {
...
+
+                    // Fixed positioned fragment without any ancestor that establishes
+                    // its containing block is placed as a child of the fragment tree.
+                    // But, it is not contained by the initial containing block, cannot
+                    // be scrolled, and should not included in the calculation. These
+                    // fragments should be ignored.
+                    // <https://drafts.csswg.org/css-position/#fixed-cb>
```
Comment (mrobinson) [inline components/layout/fragment_tree/fragment_tree.rs]:
```suggestion
 
                    // Scrollable overflow should be accumulated in the block that
                    // establishes the containing block for the element. Thus, fixed
                    // positioned fragments whose containing block is the initial
                    // containing block should not be included in overflow calculation.
                    // See <https://www.w3.org/TR/css-overflow-3/#scrollable>.
```

**Review by mrobinson — CHANGES_REQUESTED** [review]
Looks good, just some minor comments here:

File: components/layout/fragment_tree/fragment_tree.rs (hunk 6 above)
Comment (stevennovaryo) [reply components/layout/fragment_tree/fragment_tree.rs]: Done, thanks.

File: components/layout/fragment_tree/fragment_tree.rs (hunk 5 above)
Comment (stevennovaryo) [reply components/layout/fragment_tree/fragment_tree.rs]: The calculation is still required by stacking context tree when we are defining the scroll frame. I have modified it to be more appropriate. Please let me know if you have more concern.

File: components/layout/fragment_tree/fragment_tree.rs (hunk 4 above)
Comment (stevennovaryo) [reply components/layout/fragment_tree/fragment_tree.rs]: Nice, thanks! It does looks weird to have boolean matches.

File: tests/wpt/tests/css/css-overflow/scrollable-overflow-iframe-uncontained-fixed-positioned.html (hunk 2 above)
Comment (stevennovaryo) [reply tests/wpt/tests/css/css-overflow/scrollable-overflow-iframe-uncontained-fixed-positioned.html]: Done, please check!

**Review by mrobinson — APPROVED** [review]

**Comment by mrobinson** [comment]
Thanks!
