### PR TITLE
webdriver: Element Send keys use dispatch actions for KeyboardEvent

### LINKED ISSUE #38354: webdriver: Element send keys should use dispatch actions
For [Element Send Keys](https://w3c.github.io/webdriver/#dfn-element-send-keys)

> [Dispatch actions for a string](https://w3c.github.io/webdriver/#dfn-dispatch-actions-for-a-string) with arguments input state, input id, and source, text, and session's [current browsing context](https://w3c.github.io/webdriver/#dfn-current-browsing-context).

Currently, we immediately send the keys command to embedder, which will call `webview.notify_input_event`. This will cause some instabillity since we don't wait for the event to fire.

Note that we currently use `keyboard_types` crate to get the KeyEvent that we need to dispatch based on [dispatch actions for a string](https://w3c.github.io/webdriver/#dfn-dispatch-actions-for-a-string). The problem is that the crate return KeyEvent, and we need to somehow convert it back to character for [dispatch actions](https://w3c.github.io/webdriver/#dfn-dispatch-a-list-of-actions).

### LINKED ISSUE #38442: Input event not triggered immediately after `keydown` event for text input
Fails on `./tests/wpt/tests/webdriver/tests/classic/element_send_keys/events.py` for subtest `test_form_control_send_text`

<details>

<summary> Fail Log </summary>

```
0:03.22 INFO STDOUT: ================================================================= FAILURES ==================================================================
 0:03.22 INFO STDOUT: ____________________________________________________ test_form_control_send_text[input] _____________________________________________________
 0:03.22 INFO STDOUT: session = <Session 20389cf2-d3f8-47ea-8329-93902eb9c6c5>
 0:03.22 INFO STDOUT: add_event_listeners = <function add_event_listeners.<locals>.add_event_listeners at 0x7e81b335fce0>
 0:03.22 INFO STDOUT: tracked_events = ['blur', 'change', 'focus', 'input', 'keydown', 'keypress', ...]
 0:03.22 INFO STDOUT: inline = <function inline.<locals>.inline at 0x7e81b335f6a0>, tag = 'input'
 0:03.22 INFO STDOUT:     @pytest.mark.parametrize("tag", ["input", "textarea"])
 0:03.22 INFO STDOUT:     def test_form_control_send_text(session, add_event_listeners, tracked_events, inline, tag):
 0:03.22 INFO STDOUT:         expected_events = [
 0:03.22 INFO STDOUT:             "focus",
 0:03.22 INFO STDOUT:             "keydown",
 0:03.22 INFO STDOUT:             "keypress",
 0:03.22 INFO STDOUT:             "input",
 0:03.22 INFO STDOUT:             "keyup",
 0:03.22 INFO STDOUT:             "keydown",
 0:03.22 INFO STDOUT:             "keypress",
 0:03.22 INFO STDOUT:             "input",
 0:03.22 INFO STDOUT:             "keyup",
 0:03.22 INFO STDOUT:             "keydown",
 0:03.22 INFO STDOUT:             "keypress",
 0:03.22 INFO STDOUT:             "input",
 0:03.22 INFO STDOUT:             "keyup",
 0:03.22 INFO STDOUT:         ]
 0:03.22 INFO STDOUT:     
 0:03.22 INFO STDOUT:         session.url = inline("<%s>" % tag)
 0:03.22 INFO STDOUT:         element = session.find.css(tag, all=False)
 0:03.22 INFO STDOUT:         add_event_listeners(element, tracked_events)
 0:03.22 INFO STDOUT:     
 0:03.22 INFO STDOUT:         response = element_send_keys(session, element, "foo")
 0:03.22 INFO STDOUT:         assert_success(response)
 0:03.22 INFO STDOUT: >       assert_events_equal(session, expected_events)
 0:03.22 INFO STDOUT: add_event_listeners = <function add_event_listeners.<locals>.add_event_listeners at 0x7e81b335fce0>
 0:03.22 INFO STDOUT: element    = <WebElement f6752061052d47a4aec77605ec7a090c>
 0:03.22 INFO STDOUT: expected_events = ['focus',
 'keydown',
 'keypress',
 'input',
 'keyup',
 'keydown',
 'keypress',
 'input',
 'keyup',
 'keydown',
 'keypress',
 'input',
 'keyup']
 0:03.22 INFO STDOUT: inline     = <function inline.<locals>.inline at 0x7e81b335f6a0>
 0:03.22 INFO STDOUT: response   = <Response: status=200 body={"value": null}>
 0:03.22 INFO STDOUT: session    = <Session 20389cf2-d3f8-47ea-8329-93902eb9c6c5>
 0:03.22 INFO STDOUT: tag        = 'input'
 0:03.22 INFO STDOUT: tracked_events = ['blur', 'change', 'focus', 'input', 'keydown', 'keypress', 'keyup']
 0:03.22 INFO STDOUT: tests/wpt/tests/webdriver/tests/classic/element_send_keys/events.py
 0:03.22 INFO STDOUT: :75: 
 0:03.22 INFO STDOUT: _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
 0:03.22 INFO STDOUT: session = <Session 20389cf2-d3f8-47ea-8329-93902eb9c6c5>
 0:03.22 INFO STDOUT: expected_events = ['focus', 'keydown', 'keypress', 'input', 'keyup', 'keydown', ...]
 0:03.22 INFO STDOUT:     def assert_events_equal(session, expected_events):
 0:03.22 INFO STDOUT:         actual_events = session.execute_script("return window.events")
 0:03.22 INFO STDOUT: >       assert actual_events == expected_events
 0:03.22 INFO STDOUT: E       AssertionError: assert ['focus', 'keydown', 'keypress', 'keyup', 'keydown', 'keypress', 'keyup', 'keydown', 'keypress', 'keyup', 'input'] == ['focus', 'keydown', 'keypress', 'input', 'keyup', 'keydown', 'keypress', 'input', 'keyup', 'keydown', 'keypress', 'input', 'keyup']
 0:03.22 INFO STDOUT: E         
 0:03.22 INFO STDOUT: E         At index 3 diff: 'keyup' != 'input'
 0:03.22 INFO STDOUT: E         Right contains 2 more items, first extra item: 'input'
 0:03.22 INFO STDOUT: E         
 0:03.22 INFO STDOUT: E         Full diff:
 0:03.22 INFO STDOUT: E           [
 0:03.22 INFO STDOUT: E               'focus',
 0:03.22 INFO STDOUT: E               'keydown',
 0:03.22 INFO STDOUT: E               'keypress',
 0:03.22 TEST_END: Test OK. Subtests passed 3/5. Unexpected 0
 0:03.22 INFO No more tests
 0:03.22 INFO STDOUT: E         -     'input',
 0:03.22 INFO STDOUT: E               'keyup',
 0:03.22 INFO STDOUT: E               'keydown',
 0:03.22 INFO STDOUT: E               'keypress',
 0:03.22 INFO STDOUT: E         -     'input',
 0:03.22 INFO STDOUT: E               'keyup',
 0:03.22 INFO STDOUT: E               'keydown',
 0:03.22 INFO STDOUT: E               'keypress',
 0:03.22 INFO STDOUT: E         +     'keyup',
 0:03.22 INFO STDOUT: E               'input',
 0:03.22 INFO STDOUT: E         -     'keyup',
 0:03.22 INFO STDOUT: E           ]
 0:03.22 INFO STDOUT: actual_events = ['focus',
 'keydown',
 'keypress',
 'keyup',
 'keydown',
 'keypress',
 'keyup',
 'keydown',
 'keypress',
 'keyup',
 'input']
 0:03.22 INFO STDOUT: expected_events = ['focus',
 'keydown',
 'keypress',
 'input',
 'keyup',
 'keydown',
 'keypress',
 'input',
 'keyup',
 'keydown',
 'keypress',
 'input',
 'keyup']
 0:03.22 INFO STDOUT: session    = <Session 20389cf2-d3f8-47ea-8329-93902eb9c6c5>
 0:03.22 INFO STDOUT: tests/wpt/tests/webdriver/tests/support/asserts.py
 0:03.22 INFO STDOUT: :198: AssertionError
 0:03.22 INFO STDOUT:
```

</details>

### PR DESCRIPTION
**Pull request by PotatoCP**
Previously we immediately passed the KeyboardEvent to embedder. Now we make element send keys go through the dispatch action which required by spec. CompositionEvent still immediately passed through embedder

Testing: Should make `./tests/wpt/tests/webdriver/tests/classic/element_send_keys/` more stable.
Fixes: https://github.com/servo/servo/issues/38354
Fixes: https://github.com/servo/servo/issues/38442

### CODE REVIEW

**Comment by PotatoCP** [comment]
cc: @xiaochengh

**Comment by PotatoCP** [comment]
Try:
- https://github.com/PotatoCP/servo/actions/runs/16719933042
- https://github.com/PotatoCP/servo/actions/runs/16719930977
- https://github.com/PotatoCP/servo/actions/runs/16719929148
- https://github.com/PotatoCP/servo/actions/runs/16718123925

We can see that tests for element send keys is not flaky now

**Comment by yezhizhen** [comment]
I will take a look ~this afternoon~. Thanks.

EDIT: Not enough energy today..

**Comment by yezhizhen** [comment]
Can you rebase on latest main 62b181dc85f2667a386a1b00c05b36fb31ec510e and update test again? I will really review it now...

**Comment by PotatoCP** [comment]
> Can you rebase on latest main [62b181d](https://github.com/servo/servo/commit/62b181dc85f2667a386a1b00c05b36fb31ec510e) and update test again? I will really review it now...

Have just rebased. No expectation change when running element_send_keys. I have also run try here https://github.com/PotatoCP/servo/actions/runs/16768733718

File: components/webdriver_server/lib.rs [hunk 1]
```diff
@@ -2101,14 +2103,57 @@ impl Handler {
...
+        // Step 10. Let input id be a the result of generating a UUID.
+        let id = Uuid::new_v4().to_string();
+
+        // Step 12. Add an input source
+        self.session_mut()?
+            .input_state_table
+            .borrow_mut()
+            .insert(id.clone(), InputSourceState::Key(KeyInputState::new()));
+
+        // Step 13. dispatch actions for a string
```
Comment (yezhizhen) [inline components/webdriver_server/lib.rs:2121]:
```suggestion
        // Step 13. dispatch actions for a string
        // https://w3c.github.io/webdriver/#dfn-dispatch-actions-for-a-string
```

File: components/webdriver_server/lib.rs [hunk 2]
```diff
@@ -35,8 +35,9 @@ use http::method::Method;
 use image::{DynamicImage, ImageFormat, RgbaImage};
 use ipc_channel::ipc::{self, IpcReceiver, IpcSender};
 use ipc_channel::router::ROUTER;
-use keyboard_types::webdriver::send_keys;
-use log::{debug, info};
+use keyboard_types::webdriver::{Event as WebDriverInputEvent, KeyInputState, send_keys};
```
Comment (yezhizhen) [inline components/webdriver_server/lib.rs]:
```suggestion
use keyboard_types::webdriver::{Event as DispatchStringEvent, KeyInputState, send_keys};
```

File: components/webdriver_server/lib.rs [hunk 3]
```diff
@@ -2101,14 +2103,57 @@ impl Handler {
...
+            .input_state_table
+            .borrow_mut()
+            .insert(id.clone(), InputSourceState::Key(KeyInputState::new()));
+
+        // Step 13. dispatch actions for a string
+        let input_events = send_keys(&keys.text);
+
+        for event in input_events {
+            match event {
+                WebDriverInputEvent::Keyboard(event) => {
```
Comment (yezhizhen) [inline components/webdriver_server/lib.rs]:
```suggestion
                DispatchStringEvent::Keyboard(event) => {
```

File: components/webdriver_server/lib.rs [hunk 4]
```diff
@@ -2101,14 +2103,57 @@ impl Handler {
...
+                    };
+
+                    let actions_by_tick = self.actions_by_tick_from_sequence(vec![action_sequence]);
+                    if let Err(e) =
+                        self.dispatch_actions(actions_by_tick, self.session()?.browsing_context_id)
+                    {
+                        log::error!("handle_element_click: dispatch_actions failed: {:?}", e);
+                    }
+                },
+                WebDriverInputEvent::Composition(event) => {
```
Comment (yezhizhen) [inline components/webdriver_server/lib.rs]:
```suggestion
                DispatchStringEvent::Composition(event) => {
```

File: components/webdriver_server/lib.rs [hunk 5]
```diff
@@ -2631,3 +2676,79 @@ fn unwrap_first_element_response(res: WebDriverResponse) -> WebDriverResult<WebD
         unreachable!()
     }
 }
+
+fn convert_keyboard_event_to_string(event: &KeyboardEvent) -> String {
```
Comment (yezhizhen) [inline components/webdriver_server/lib.rs:2642]: Same as question earlier.
Is there a reason we have to do this? I thought keyboard crate already handle such things.

File: components/webdriver_server/lib.rs [hunk 6]
```diff
@@ -2101,14 +2103,57 @@ impl Handler {
...
+            .borrow_mut()
+            .insert(id.clone(), InputSourceState::Key(KeyInputState::new()));
+
+        // Step 13. dispatch actions for a string
+        let input_events = send_keys(&keys.text);
+
+        for event in input_events {
+            match event {
+                WebDriverInputEvent::Keyboard(event) => {
+                    let raw_string = convert_keyboard_event_to_string(&event);
```
Comment (yezhizhen) [inline components/webdriver_server/lib.rs:2128]: Is there a reason we have to do this? It seems later we would normalize again in https://github.com/servo/servo/blob/5b148cf5de1612b181fdc88650747ae4a53c266d/components/webdriver_server/actions.rs#L319

**Review by yezhizhen — COMMENTED** [review]
1. `WebDriverInputEvent` is too general. I suggest `DispatchStringEvent` but open for other suggestions.
2. I have a question. See below.

File: components/webdriver_server/lib.rs (hunk 5 above)
Comment (PotatoCP) [reply components/webdriver_server/lib.rs:2642]: We send the string to keyboard crate to handle [dispatch action for a string](https://w3c.github.io/webdriver/#dfn-dispatch-actions-for-a-string). However it gives us the keyboard event which is incompatible if we want to send the keys through dispatch actions (which need the string for the input source for dispatch action). Hence here we convert the keyboard event back to string.

Comment (PotatoCP) [reply components/webdriver_server/lib.rs:2642]: Dispatch action is the last step of [dispatch action the event for typeable string](https://w3c.github.io/webdriver/#dfn-dispatch-the-events-for-a-typeable-string).

Comment (yezhizhen) [reply components/webdriver_server/lib.rs:2642]: Is there anyway around this? This sounds like rough cooperation between webdriver & keyboard crates..

Comment (PotatoCP) [reply components/webdriver_server/lib.rs:2642]: I have been thinking about this for a month. But I don't seem to find any good solutions.

Comment (yezhizhen) [reply components/webdriver_server/lib.rs:2681]: Thanks! Then it looks good to me then.

Comment (yezhizhen) [reply components/webdriver_server/lib.rs:2642]: Thanks! Then it looks good to me. 
cc @xiaochengh

Comment (xiaochengh) [reply components/webdriver_server/lib.rs:2642]: This is pretty much an ad hoc `to_string()` implementation. I'm also concerned with it.

Q1: All the named keys are mapped to the Private Use Area. Is this mapping specified anywhere?

Q2: What does [`NamedKey.to_string()`](https://docs.rs/keyboard-types/0.8.1/keyboard_types/enum.NamedKey.html#method.to_string) produce?

Comment (PotatoCP) [reply components/webdriver_server/lib.rs:2681]: A1. I just reverse this mapping of https://github.com/rust-windowing/keyboard-types/blob/f82b9e4a8ae52364f24d4fc667b800d0c3fbaf31/src/webdriver.rs#L57-L132.

A2. It will just spell out the Enum Item https://github.com/rust-windowing/keyboard-types/blob/f82b9e4a8ae52364f24d4fc667b800d0c3fbaf31/src/named_key.rs#L679

Comment (PotatoCP) [reply components/webdriver_server/lib.rs:2681]: > This is pretty much an ad hoc `to_string()` implementation. I'm also concerned with it.
> 
> Q1: All the named keys are mapped to the Private Use Area. Is this mapping specified anywhere?
> 
> Q2: What does [`NamedKey.to_string()`](https://docs.rs/keyboard-types/0.8.1/keyboard_types/enum.NamedKey.html#method.to_string) produce?

Comment (PotatoCP) [reply components/webdriver_server/lib.rs:2642]: > This is pretty much an ad hoc `to_string()` implementation. I'm also concerned with it.
> 
> Q1: All the named keys are mapped to the Private Use Area. Is this mapping specified anywhere?
> 
> Q2: What does [`NamedKey.to_string()`](https://docs.rs/keyboard-types/0.8.1/keyboard_types/enum.NamedKey.html#method.to_string) produce?


A1. I just reverse this mapping of https://github.com/rust-windowing/keyboard-types/blob/f82b9e4a8ae52364f24d4fc667b800d0c3fbaf31/src/webdriver.rs#L57-L132.

A2. It will just spell out the Enum Item https://github.com/rust-windowing/keyboard-types/blob/f82b9e4a8ae52364f24d4fc667b800d0c3fbaf31/src/named_key.rs#L679

File: tests/wpt/meta/webdriver/tests/classic/element_send_keys/interactability.py.ini [hunk 7]
```diff
@@ -13,6 +13,3 @@
 
   [test_readonly_element]
     expected: FAIL
-
-  [test_obscured_element]
-    expected: FAIL
```
Comment (yezhizhen) [inline tests/wpt/meta/webdriver/tests/classic/element_send_keys/interactability.py.ini]: I believe this one is flaky?

Comment (PotatoCP) [reply tests/wpt/meta/webdriver/tests/classic/element_send_keys/interactability.py.ini]: I ran a couple times and it seems passing now :thinking:

Comment (yezhizhen) [reply tests/wpt/meta/webdriver/tests/classic/element_send_keys/interactability.py.ini]: You are right!

**Comment by PotatoCP** [comment]
Hi, may you kindly review this @jdm @jschwe. This PR will also solve unstable issue related to send keys.

**Review by yezhizhen — APPROVED** [review]
https://github.com/servo/servo/pull/38444#discussion_r2256406590

It is a shame we have `fn convert_keyboard_event_to_string`, but the gain from this PR is much larger than the loss of ugliness.

But pls rebase on latest main since we have rustc 1.89 now..

**Comment by PotatoCP** [comment]
> [#38444 (comment)](https://github.com/servo/servo/pull/38444#discussion_r2256406590)
> 
> It is a shame we have `fn convert_keyboard_event_to_string`, but the gain from this PR is much larger than the loss of ugliness.
> 
> But pls rebase on latest main since we have rustc 1.89 now..

I have rebased based on https://github.com/servo/servo/commit/604b6ea26dadc55e6c8c68b9c7d9f9f84193539e. Thanks

File: components/webdriver_server/lib.rs [hunk 8]
```diff
@@ -2158,14 +2160,58 @@ impl Handler {
...
+                        actions: ActionsType::Key {
+                            actions: vec![KeyActionItem::Key(key_action)],
+                        },
+                    };
+
+                    let actions_by_tick = self.actions_by_tick_from_sequence(vec![action_sequence]);
+                    if let Err(e) =
+                        self.dispatch_actions(actions_by_tick, self.session()?.browsing_context_id)
+                    {
+                        log::error!("handle_element_click: dispatch_actions failed: {:?}", e);
```
Comment (jdm) [inline components/webdriver_server/lib.rs]: handle_element_send_keys

**Review by jdm — APPROVED** [review]

**Comment by yezhizhen** [comment]
@PotatoCP need rebase as conflict with merged #38745.

**Comment by yezhizhen** [comment]
@PotatoCP need rebase as conflict with merged #38745.

Also probably should rerun the test after it, and ping the try result.

**Comment by PotatoCP** [comment]
Hi, this is the try after rebase
https://github.com/PotatoCP/servo/actions/runs/17143637153

**Comment by yezhizhen** [comment]
Do you mind run test again after #38841? I believe there may be new passing test.
