### PR TITLE
Assert fail #18439

### LINKED ISSUE #18439: assertion failed: self.load.is_none()
While trying to reproduce #18438 (http://baskino.co), I hit this assertion instead. I could not reproduce it a second time (but that URL is a gold mine).

Note: This panic happened **after** the `Shutting down the Constellation after generating an output file or exit flag specified` message was printed.

stack trace:
```gdb
assertion failed: self.load.is_none() (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }, at /shared/dev/rust/servo/components/script/document_loader.rs:78)
stack backtrace:
   0:     0x555ab12320dc - backtrace::backtrace::trace::h0f1eee7f17c620ad
   1:     0x555ab1232112 - backtrace::capture::Backtrace::new::h1abdde591da67f3d
   2:     0x555aaff91865 - servo::main::{{closure}}::h2775028620a930e9
   3:     0x555ab2746b26 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:612
   4:     0x555ab065207a - std::panicking::begin_panic::h99ca1191232fecb5
   5:     0x555ab09297f1 - core::ptr::drop_in_place::h9cca0903c5314d35
   6:     0x555ab0783c34 - std::panicking::try::do_call::h933e23f632df6f0e
   7:     0x555ab274dbcc - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
   8:     0x555ab0f77133 - script::dom::bindings::codegen::Bindings::HTMLImageElementBinding::HTMLImageElementBinding::_finalize::hacf9178a2b564947
   9:     0x555ab18ceec9 - _ZNK2js5Class10doFinalizeEPNS_6FreeOpEP8JSObject
                        at /shared/dev/rust/servo/target/release/build/mozjs_sys-6a7905cfd7acaabc/out/dist/include/js/Class.h:815
  10:     0x555ab18d76a6 - _ZN8JSObject8finalizeEPN2js6FreeOpE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsobjinlines.h:85
  11:     0x555ab18f1941 - _ZN2js2gc5Arena8finalizeI8JSObjectEEmPNS_6FreeOpENS0_9AllocKindEm
  12:     0x555ab18c5bc5 - FinalizeTypedArenas<JSObject>
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsgc.cpp:505
  13:     0x555ab1893490 - FinalizeArenas
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsgc.cpp:539
  14:     0x555ab18d9eec - _ZN2js2gc10ArenaLists16forceFinalizeNowEPNS_6FreeOpENS0_9AllocKindENS1_14KeepArenasEnumEPPNS0_5ArenaE
  15:     0x555ab18d9d95 - _ZN2js2gc10ArenaLists11finalizeNowEPNS_6FreeOpENS0_9AllocKindENS1_14KeepArenasEnumEPPNS0_5ArenaE
  16:     0x555ab189ae24 - _ZN2js2gc10ArenaLists30queueForegroundObjectsForSweepEPNS_6FreeOpE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsgc.cpp:2839
  17:     0x555ab18a2e49 - _ZN2js2gc9GCRuntime22beginSweepingZoneGroupERNS_26AutoLockForExclusiveAccessE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsgc.cpp:5127
  18:     0x555ab18a35a3 - _ZN2js2gc9GCRuntime15beginSweepPhaseEbRNS_26AutoLockForExclusiveAccessE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsgc.cpp:5215
  19:     0x555ab18a5e0e - _ZN2js2gc9GCRuntime23incrementalCollectSliceERNS_11SliceBudgetEN2JS8gcreason6ReasonERNS_26AutoLockForExclusiveAccessE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsgc.cpp:5937
  20:     0x555ab18a696e - _ZN2js2gc9GCRuntime7gcCycleEbRNS_11SliceBudgetEN2JS8gcreason6ReasonE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsgc.cpp:6174
  21:     0x555ab18a6eaf - _ZN2js2gc9GCRuntime7collectEbNS_11SliceBudgetEN2JS8gcreason6ReasonE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsgc.cpp:6287
  22:     0x555ab18a723e - _ZN2js2gc9GCRuntime2gcE18JSGCInvocationKindN2JS8gcreason6ReasonE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsgc.cpp:6354
  23:     0x555ab17e0fff - _Z5JS_GCP9JSRuntime
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsapi.cpp:1340
  24:     0x555ab0d510f2 - script::dom::window::Window::clear_js_runtime::h05b206a41cc0f413
  25:     0x555ab0dbde0a - script::script_thread::ScriptThread::handle_exit_pipeline_msg::h6f3c5cff0dd87471
  26:     0x555ab0da94e5 - script::script_thread::ScriptThread::handle_msg_from_constellation::h37d80dc8659cb70e
  27:     0x555ab0da7468 - script::script_thread::ScriptThread::handle_msgs::{{closure}}::hdd3fd9041a1efa8f
  28:     0x555ab0da38cf - script::script_thread::ScriptThread::handle_msgs::h4aadf07f4dff3bf3
  29:     0x555ab0d9eceb - script::script_thread::ScriptThread::start::h543e6bc16496788a
  30:     0x555ab064e8f0 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcbce24426485d7f2
  31:     0x555ab077b605 - std::panicking::try::do_call::h8ef268d0617cbd63
  32:     0x555ab274dbcc - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  33:     0x555ab09850b2 - <F as alloc::boxed::FnBox<A>>::call_box::h4e198348b3252fbb
  34:     0x555ab27457ab - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:692
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84
  35:     0x7fe4b3edc493 - start_thread
  36:     0x7fe4b3a09abe - __clone
  37:                0x0 - <unknown>
ERROR:servo: assertion failed: self.load.is_none()
```

### PR DESCRIPTION
**Pull request by ejmg**
This PR addresses #18439 by removing an assert statement that forces a panic whenever `LoadBlocker` is dropped during a GC sweep and receives a `None` `SCRIPT_THREAD_ROOT` value from `mark_document_with_no_blocked_loads()`. Instead of panicking on the assert, we remove it and let the None value pass silently.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #18439 

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23021)

### CODE REVIEW

**Comment by jdm** [comment]
```
error: unused import: `std::thread`
  --> components/script/document_loader.rs:17:5
   |
17 | use std::thread;
   |     ^^^^^^^^^^^
   |
   = note: `-D unused-imports` implied by `-D warnings`
```

File: components/script/document_loader.rs [hunk 1]
```diff
@@ -77,8 +77,8 @@ impl LoadBlocker {
 
 impl Drop for LoadBlocker {
     fn drop(&mut self) {
-        if !thread::panicking() {
-            debug_assert!(self.load.is_none());
+        if let Some(script_thread) = self.load.take() {
+            self.doc.finish_load(script_thread);
```
Comment (jdm) [inline components/script/document_loader.rs]: We should do `Some(load)` instead of `Some(script_thread)`; the value inside the Option isn't related to the script thread.

File: components/script/script_thread.rs [hunk 2]
```diff
@@ -808,12 +808,13 @@ impl ScriptThread {
...
-                .docs_with_no_blocking_loads
-                .borrow_mut()
-                .insert(Dom::from_ref(doc));
+        SCRIPT_THREAD_ROOT.with(|root| unsafe {
+            if let Some(script_thread) = root.get() {
+                (*script_thread)
+                    .docs_with_no_blocking_loads
+                    .borrow_mut()
+                    .insert(Dom::from_ref(doc));
+            }
```
Comment (jdm) [inline components/script/script_thread.rs]: Let's scope the unsafe block a little bit narrower:
```rust
SCRIPT_THREAD_ROOT.with(|root| {
    if let Some(script_thread) = root.get() {
        let script_thread = unsafe { &*script_thread };
        script_thread
            .docs_with_no_blocking_loads
            .borrow_mut()
            .insert(Dom::from_ref(doc));
    }
});
```

**Review by jdm — CHANGES_REQUESTED** [review]
This looks like what I expected to see :)

**Comment by jdm** [comment]
I've spent a bunch of time trying to write an automated test that tickles this problem, but I have not been able to do so.

File: components/script/script_thread.rs (hunk 2 above)
Comment (ejmg) [reply components/script/script_thread.rs]: thank you! I didn't know I could deref the bound value in an if let like that.

**Comment by ejmg** [comment]
I've made the changes requested so far and rebased them such that there are only three commits, the first two are the actual changes required for the issue (one per file change) and the last one combines all requested changes from code review.

Let me know if this works and or if there are more changes desired :slightly_smiling_face:

**Comment by ejmg** [comment]
testing a release build with my edits and I have been unable to replicate the crashes mentioned in #18439.

**Comment by jdm** [comment]
@bors-servo retry
* #22955

**Comment by jdm** [comment]
@bors-servo retry
* #23054
