### PR TITLE
ohos: Fix JIT detection

### LINKED ISSUE #40029: ohos: servo hap exited immediately running on Matebook Pro
**Describe the bug:**
I have a developer account permission for my Matebook Pro, HAD-W24, running HOS 5.1.0. That makes me could self-signed and push the released version 0.0.1 OHOS hap to my laptop. But I only get a exit immediately with a servo window blinked if I try to run it.

**To Reproduce:**
1. Get a Matebook Pro and the developer account permission binding on it.
2. Download v0.0.1 aarch64-ohos target hap, then self-sign and push it to device.
3. Run `servo` app，then we can see a blinked servo window and exited immediately.

**Platform:**
OS: HarmonyOS 5.1.0.320 SP30
Device: Matebook Pro, HAD-W24

### PR DESCRIPTION
**Pull request by jschwe**
On recent versions of HarmonyOS the previous JIT detection does not appear to work anymore, since the second `mmap` succeeds. This moves the failure in spidermonkey to a later point, when SM remaps memory to be writable. On recent versions of HOS I observed that the `PROT_WRITE` permission was silently ignored by mprotect, which lead to a crash later on the first attempt to write to the memory region.
It's not exactly easy to determine if one can write to a memory location (if mprotect lies to you), but we can use `read` to check if the memory region is writable (without triggering a segfault), since `read` will return an error for invalid addresses (which is possible since the writing is handled in the kernel).

Since this solution does add more unsafe code than before, we only use this detection on OpenHarmony, although we could use it on more platforms later if there are other platforms which also may have JIT forbidden.

Testing: Removing the explicit `--pref js_disable_jit=true` means the detection is tested in CI.
Fixes: #40029

### CODE REVIEW

File: components/script/init.rs [hunk 1]
```diff
@@ -63,34 +62,99 @@ unsafe extern "C" fn is_dom_object(obj: *mut JSObject) -> bool {
...
+            jit_forbidden = true;
+        } else {
+            // Additionally check if `mprotect` actually succeeded in adding `PROT_WRITE`.
+            // We observed before that `mprotect` silently ignores the write permission without
+            // returning an error.
+            let is_writable = mem_is_writable(first_mmap)
+                .inspect_err(|_e| {
+                    debug!("Failed to determine if JIT is allowed. Conservatively assuming it is forbidden.");
+                })
+                .unwrap_or(false); // writable ==false -> JIT is forbidden.
```
Comment (sagudev) [inline components/script/init.rs]:
```suggestion
                .unwrap_or(false); // writable == false -> JIT is forbidden.
```

File: components/script/init.rs [hunk 2]
```diff
@@ -63,34 +62,99 @@ unsafe extern "C" fn is_dom_object(obj: *mut JSObject) -> bool {
...
+            jit_forbidden = !is_writable;
+        }
+    }
+    // Ignore the result, since there is nothing we could do if unmap failed for whatever reason.
+    // SAFETY: We unmap the `mmap`ed region completely again. There is no other `munmap` call in
+    // this function, and we do not have any early returns in this function.
+    let _ = unsafe { libc::munmap(first_mmap, map_size) };
```
Comment (sagudev) [inline components/script/init.rs:152]: My syscalls knowledge is a bit rusty, but I think we need to close both maps, per my understanding of https://man7.org/linux/man-pages/man2/mmap.2.html.

Comment (jschwe) [reply components/script/init.rs:152]: The second `mmap` is `MAP_FIXED` on the same address, with the same length, which should result in the first mapping simply being updated / replaced by the second mmap call. From what I saw in SM, they also don't call `munmap` twice.

Comment (sagudev) [reply components/script/init.rs:152]: Ah, I see.

**Review by sagudev — APPROVED** [review]
