### PR TITLE
layout: Fix CSS `attr()` function case sensitivity matching

### LINKED ISSUE #23365: CSS attr() function not working
See this failing wpt test:

```bash
./mach test-wpt tests/wpt/web-platform-tests/css/css-content/attr-case-insensitive.html
```

In fact if you open:

```bash
./mach run -d -- tests/wpt/web-platform-tests/css/css-content/attr-case-insensitive.html
```

…you will only see an empty page. Open it with firefox and see the expected content `aaabbbccc`.

Related: #22265

### PR DESCRIPTION
**Pull request by stevennovaryo**
Fix how `attr()` being resolved in the pseudo element by considering the case sensitivity of `attr-name` the document language. 

See https://drafts.csswg.org/css-values-5/#typedef-attr-name.

These changes add naive implementations and allow the following WPT tests to pass.
- `/css/css-content/attr-case-sensitivity-001.html`
- `/css/css-content/attr-case-sensitivity-002.html`
- `/css/CSS2/generated-content/content-attr-case-001.html`

The changes is related to the issue #23365 that mentions the `attr` function. I believe previous addition of `attr` already fixed the issue, but left the case sensitivity handling omitted.

More things about the function can also be considered:
- [Resolving it according to the spec](https://drafts.csswg.org/css-values-5/#attr-substitution).
- [Security of the function](https://drafts.csswg.org/css-values-5/#attr-security).

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #23365 
- [X] There are tests for these changes

### CODE REVIEW

File: components/layout_2020/dom_traversal.rs [hunk 1]
```diff
@@ -409,12 +409,20 @@ where
...
                             .to_threadsafe()
                             .as_element()
                             .expect("Expected an element");
-                        let attr_val = element
-                            .get_attr(&attr.namespace_url, &LocalName::from(&*attr.attribute));
+                        let attr_name = if element.is_html_element_in_html_document() {
+                            &*attr.attribute.to_ascii_lowercase()
+                        } else {
+                            &*attr.attribute
+                        };
```
Comment (mrobinson) [inline components/layout_2020/dom_traversal.rs:422]: Can you link to the specification and quote the specification text here that explains this code. In particular, why does this only apply to the HTML element?

I think a match statement would work best here as well.

File: components/layout_2020/dom_traversal.rs [hunk 2]
```diff
@@ -409,12 +409,20 @@ where
                         vec.push(PseudoElementContentItem::Text(s.to_string()));
                     },
                     ContentItem::Attr(attr) => {
+                        use selectors::Element;
```
Comment (mrobinson) [inline components/layout_2020/dom_traversal.rs:412]: Please put this import at the top of the file. If you need to rename it due to a naming conflict, it could be called `SelectorsElement`.

**Review by mrobinson — CHANGES_REQUESTED** [review]
Nice! Just a couple comments here:

File: components/layout_2020/dom_traversal.rs (hunk 1 above)
Comment (stevennovaryo) [reply components/layout_2020/dom_traversal.rs:422]: Thank you for the review!

Comment (stevennovaryo) [reply components/layout_2020/dom_traversal.rs:422]: Thank you for the review!

As for HTML documents, the case sensitivity of the function is clearly stated [here](https://html.spec.whatwg.org/multipage/semantics-other.html#case-sensitivity-of-the-css-'attr()'-function) which also stated how does attribute selectors be matched, which I believe was implemented in [stylo's css attribute selector](https://github.com/servo/stylo/blob/098f1bef3e231bbf86038c0a2b1ddc31031dc422/selectors/matching.rs#L1263). 

I tried to find specifications further, but it seems like there is not unified detailed specifications of all documents for this, except for general consensus that documents based on XML (e.g. SVG, XHTML, and MATHML) is case sensitive for attributes.

Please let me know if there is anything further I can clarify and address.

File: components/layout_2020/dom_traversal.rs (hunk 2 above)
Comment (stevennovaryo) [reply components/layout_2020/dom_traversal.rs]: I have applied the recommendations, was following how does the `selectors::Element` was imported previously and assumed it was imported like these to keep it in the scope. 

What is the convention of naming import like these if there are no conflicts? Should one kept it as `SelectorsElement` which will differentiate it with the other more well known `Element`?

File: components/layout_2020/dom_traversal.rs (hunk 1 above)
Comment (stevennovaryo) [reply components/layout_2020/dom_traversal.rs]: Sorry, I have quoted the specification. Kindly recheck the changes. Thank you!

File: components/layout_2020/dom_traversal.rs [hunk 3]
```diff
@@ -413,8 +414,15 @@ where
                             .to_threadsafe()
                             .as_element()
                             .expect("Expected an element");
-                        let attr_val = element
-                            .get_attr(&attr.namespace_url, &LocalName::from(&*attr.attribute));
+
+                        // <https://html.spec.whatwg.org/multipage/#case-sensitivity-of-the-css-%27attr%28%29%27-function>
```
Comment (mrobinson) [inline components/layout_2020/dom_traversal.rs:418]:
```suggestion
```suggestion
                        // From
                        // <https://html.spec.whatwg.org/multipage/semantics-other.html#case-sensitivity-of-the-css-'attr()'-function>:

                        // > CSS Values and Units leaves the case-sensitivity of attribute names for
                        // > the purpose of the `attr()` function to be defined by the host language.
                        // > [[CSSVALUES]].
                        // > When comparing the attribute name part of a CSS `attr()`function to the
                        // names of namespace-less > attributes on HTML elements in HTML documents,
                        // the name part of the CSS `attr()` function must first > be converted to
                        // ASCII lowercase. The same function when compared to other attributes must
                        // be compared according to its original case. In both cases, to match the
                        // > values must be identical to each other (and therefore the comparison is
                        // > case sensitive).

```

**Review by mrobinson — CHANGES_REQUESTED** [review]

**Review by mrobinson — APPROVED** [review]
Thanks for this fix!
