### PR TITLE
webgl: Add basic support for framebuffer attachments

### LINKED ISSUE #13639: webgl: Add support for framebuffer objects
I've been working on a [series](https://github.com/anholt/servo/tree/webgl-fbo) for FBO support in webgl:

Known issues:

1) Need to clear RBs on allocation (renderbuffer-initialization.html will be an intermittent)
2) Need to invalidate the FBO when its attachments are reallocated
3) Need to check that attachments are not deleted for completeness check
4) `object-deletion-behavior.html` is now a crash because it gets farther into its tests and makes a GL error.

### PR DESCRIPTION
**Pull request by anholt**
This is by no means a complete implementation, but I've slowed down on working on it, so I think we should look at what it takes to merge the current code.  There are some major features missing, like initializing renderbuffers to 0 (uninitialized memory leak), tracking the attachments' attributes (width/height/format) for parameter requests, and lots of missing glCheckFramebufferStatus() validation.  On the other hand, this is enough to run some demos using FBOs.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13639 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13872)

### CODE REVIEW

File: components/script/dom/webglrenderingcontext.rs [hunk 1]
```diff
@@ -806,7 +806,11 @@ impl WebGLRenderingContextMethods for WebGLRenderingContext {
 
         self.bound_framebuffer.set(framebuffer);
         if let Some(framebuffer) = framebuffer {
-            framebuffer.bind(target)
+            if framebuffer.is_deleted() {
```
Comment (emilio) [inline components/script/dom/webglrenderingcontext.rs]: The spec changed and this case should be ignored now (don't change the state of the binding), plus produce an `INVALID_OP`.

File: components/script/dom/webglrenderbuffer.rs [hunk 2]
```diff
@@ -33,6 +35,7 @@ impl WebGLRenderbuffer {
             ever_bound: Cell::new(false),
             is_deleted: Cell::new(false),
             renderer: renderer,
+            internalformat: Cell::new(None),
```
Comment (emilio) [inline components/script/dom/webglrenderbuffer.rs]: I think the usual way to name members is using snake case (i.e. `internal_format`). Not a huge deal though.

File: components/script/dom/webglrenderingcontext.rs [hunk 3]
```diff
@@ -2536,6 +2536,39 @@ impl WebGLRenderingContextMethods for WebGLRenderingContext {
...
+        // From the GLES 2.0.25 spec:
+        //
+        //     "If either width or height is greater than the value of
+        //      MAX_RENDERBUFFER_SIZE , the error INVALID_VALUE is
+        //      generated."
+        //
+        // and we have to throw out negative-size values as well just
+        // like for TexImage.
+        //
+        // FIXME: Handle max_renderbuffer_size, which doesn't seem to
```
Comment (emilio) [inline components/script/dom/webglrenderingcontext.rs]: Yeah, these are being added on demand, I'll file an issue about this.

File: components/script/dom/webglframebuffer.rs [hunk 4]
```diff
@@ -80,10 +105,139 @@ impl WebGLFramebuffer {
...
+                //      TEXTURE_CUBE_MAP_POSITIVE_Y,
+                //      TEXTURE_CUBE_MAP_POSITIVE_Z,
+                //      TEXTURE_CUBE_MAP_NEGATIVE_X,
+                //      TEXTURE_CUBE_MAP_NEGATIVE_Y, or
+                //      TEXTURE_CUBE_MAP_NEGATIVE_Z. Otherwise,
+                //      INVALID_OPERATION is generated."
+                let is_cube = match textarget {
+                    constants::TEXTURE_2D => false,
+
+                    constants::TEXTURE_CUBE_MAP_POSITIVE_Z => true,
```
Comment (emilio) [inline components/script/dom/webglframebuffer.rs]: Shouldn't you test the rest cube texture names?

File: components/script/dom/webglframebuffer.rs [hunk 5]
```diff
@@ -240,6 +241,49 @@ impl WebGLFramebuffer {
         Ok(())
     }
 
+    pub fn detach_renderbuffer(&self, rb: &WebGLRenderbuffer) {
+        let attachments = vec![&self.color,
```
Comment (emilio) [inline components/script/dom/webglframebuffer.rs]: I think this can be in the stack instead being a vector.

File: components/script/dom/webglframebuffer.rs [hunk 6]
```diff
@@ -240,6 +241,49 @@ impl WebGLFramebuffer {
...
+
+            if matched {
+                *attachment.borrow_mut() = None;
+                self.update_status();
+            }
+        }
+    }
+
+    pub fn detach_texture(&self, texture: &WebGLTexture) {
+        let attachments = vec![&self.color,
```
Comment (emilio) [inline components/script/dom/webglframebuffer.rs]: ditto

**Review by emilio — CHANGES_REQUESTED** [review]
Looks good, thanks for doing this @anholt! I have a few comments.

**Comment by emilio** [comment]
Yay, let's land this. Thanks for doing this once again :)

@bors-servo: r+

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /webgl/conformance-1.0.3/conformance/misc/object-deletion-behaviour.html:
  │ FAIL [expected PASS] WebGL test #278: at (16, 16) expected: 0,0,0,0 was 9,0,0,0
  │   → assert_true: at (16, 16) expected: 0,0,0,0 was 9,0,0,0 expected true got false
  │ 
  │ reportTestResultsToHarness/<@http://web-platform.test:8000/webgl/conformance-1.0.3/resources/js-test-pre.js:88:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1401:20
  │ test@http://web-platform.test:8000/resources/testharness.js:501:9
  │ reportTestResultsToHarness@http://web-platform.test:8000/webgl/conformance-1.0.3/resources/js-test-pre.js:87:7
  │ testFailed@http://web-platform.test:8000/webgl/conformance-1.0.3/resources/js-test-pre.js:153:5
  │ checkCanvasRectColor@http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/resources/webgl-test-utils.js:1047:9
  │ checkCanvasRect@http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/resources/webgl-test-utils.js:1073:3
  │ @http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/resources/webgl-test-utils.js line 1349 > eval:1:1
  │ shouldGenerateGLError@http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/resources/webgl-test-utils.js:1349:5
  └ @http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/misc/object-deletion-behaviour.html:387:3
```

**Comment by anholt** [comment]
I made a mistake before with my `handle_object_deletion` macro -- we need to clear the GL's binding, not just WebGL's, which should fix the test's problem.  However, this also made me notice #13901, and fixing that would at least make this failure not intermittent.

I won't have time for this tonight, though.

**Comment by anholt** [comment]
OK, that failure does seem fairly stable, so I've added it and hopefully that will be enough.  There were two more subfailures in the same test that were showing up, too.  Not sure why I didn't get them last night.

**Review by emilio — APPROVED** [review]

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /webgl/conformance-1.0.3/conformance/misc/object-deletion-behaviour.html:
  │ FAIL [expected PASS] WebGL test #281: at (0, 0) expected: 255,0,0,255 was 0,172,146,24
  │   → assert_true: at (0, 0) expected: 255,0,0,255 was 0,172,146,24 expected true got false
  │ 
  │ reportTestResultsToHarness/<@http://web-platform.test:8000/webgl/conformance-1.0.3/resources/js-test-pre.js:88:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1401:20
  │ test@http://web-platform.test:8000/resources/testharness.js:501:9
  │ reportTestResultsToHarness@http://web-platform.test:8000/webgl/conformance-1.0.3/resources/js-test-pre.js:87:7
  │ testFailed@http://web-platform.test:8000/webgl/conformance-1.0.3/resources/js-test-pre.js:153:5
  │ checkCanvasRectColor@http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/resources/webgl-test-utils.js:1047:9
  │ checkCanvasRect@http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/resources/webgl-test-utils.js:1073:3
  │ @http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/resources/webgl-test-utils.js line 1349 > eval:1:1
  │ shouldGenerateGLError@http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/resources/webgl-test-utils.js:1349:5
  └ @http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/misc/object-deletion-behaviour.html:391:3
```

**Comment by anholt** [comment]
OK: Expecting the winsys backbuffer's red after glDeleteFramebuffer() of our FBO: that should be fixed in the new unbind commit.  Previously we were returning undefined.

**Comment by emilio** [comment]
Sounds good.

@bors-servo: r+

**Comment by jdm** [comment]
```
LLVM ERROR: IO failure on output stream.
error: Could not compile `embedding`.
```
That's akward.

**Comment by jdm** [comment]
@bors-servo: retry
Maybe it's not a permanent failure?

**Comment by emilio** [comment]
@bors-servo: retry

 * Builder is out of disk space

**Comment by larsbergstrom** [comment]
@bors-servo retry
- servo-linux2 out of disk space

**Comment by KiChjang** [comment]
@bors-servo retry
* Disk space issues?

**Comment by larsbergstrom** [comment]
@bors-servo retry
- disk space issues on servo-linux2

**Comment by jdm** [comment]
@bors-servo: retry
* #13919
