### PR TITLE
Use Result instead of panicking when the resource dir can't be found

### LINKED ISSUE #12520: env::current_exe().expect() panic when running in Gecko reftest
When I run Stylo-enabled firefox in reftest (`./mach reftest`), firefox crashes because the code in [components/util/resource_files.rs](https://github.com/servo/servo/blob/master/components/util/resource_files.rs#L39) failed to get the `env::current_exe()`. This function is called when `properties.mako.rs` wants to find if a PropertyDeclaration is experimental, by getting the `prefs.json` from `resources` ([example](https://github.com/servo/servo/blob/master/components/style/properties/properties.mako.rs#L968)).

I removed all the `::util::prefs::PREFS.get()` call and it does not crash anymore.

The reftest runner runs Firefox by `subprocess.Popen` inside a python `threading.Thread`, not sure if it's related to the way it's called.

@Manishearth any insight into this?

### PR DESCRIPTION
**Pull request by Manishearth**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #12520 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because it's a refactoring

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12535)

### CODE REVIEW

File: components/constellation/sandboxing.rs [hunk 1]
```diff
@@ -12,7 +12,8 @@ pub fn content_process_sandbox_profile() -> Profile {
     use gaol::platform;
     Profile::new(vec![
         Operation::FileReadAll(PathPattern::Literal(PathBuf::from("/dev/urandom"))),
-        Operation::FileReadAll(PathPattern::Subpath(resource_files::resources_dir_path())),
+        Operation::FileReadAll(PathPattern::Subpath(resource_files::resources_dir_path()
```
Comment (Manishearth) [inline components/constellation/sandboxing.rs]: I'm not sure if I should panic or fallback here

File: components/net/chrome_loader.rs [hunk 2]
```diff
@@ -17,7 +17,7 @@ pub fn resolve_chrome_url(url: &Url) -> Result<Url, ()> {
     if url.host_str() != Some("resources") {
         return Err(())
     }
-    let resources = canonicalize(resources_dir_path())
+    let resources = canonicalize(resources_dir_path().expect("Error finding resource folder"))
```
Comment (Manishearth) [inline components/net/chrome_loader.rs]: I'm panicking here because we already panic here if you can't find the dir

File: components/net/connector.rs [hunk 3]
```diff
@@ -29,7 +29,9 @@ const DEFAULT_CIPHERS: &'static str = concat!(
 
 pub fn create_http_connector() -> Arc<Pool<Connector>> {
     let mut context = SslContext::new(SslMethod::Sslv23).unwrap();
-    context.set_CA_file(&resources_dir_path().join("certs")).unwrap();
+    context.set_CA_file(&resources_dir_path()
+                        .expect("Need certificate file to make network requests")
```
Comment (Manishearth) [inline components/net/connector.rs]: We could fall back to an HTTP-only mode here if we wanted, but that's not too important for now.

**Comment by KiChjang** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/constellation/sandboxing.rs, line 15 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12535#-KNB9jEv9ttN5qLjurVE-r1-15:-KNB_HxQnTDJfLatbXP6:-1240471222) ([raw file](https://github.com/servo/servo/blob/ceb85795b1feed53121f9683cc34d2fd76cef761/components/constellation/sandboxing.rs#L15)):*
<details><summary><i>Previously, Manishearth (Manish Goregaokar) wrote…</i></summary>
> I'm not sure if I should panic or fallback here
</details>
Currently, this function is called in code paths that already assume there's a `resource_dir_path`, so panicking here would be wise.

---

*[components/script/dom/userscripts.rs, line 31 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12535#-KNBYqJVtOcc3LavRaX5:-KNBYqJVtOcc3LavRaX6:633155329) ([raw file](https://github.com/servo/servo/blob/ceb85795b1feed53121f9683cc34d2fd76cef761/components/script/dom/userscripts.rs#L31)):*
> ```Rust
>                 p
>             } else {
>                 return
> ```

This would mean no scripts are loaded if there isn't a valid resource directory path. Is this ok?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12535)*

**Comment by KiChjang** [comment]
r=me otherwise.

**Comment by Manishearth** [comment]
@bors-servo r=KiChjang

that's only userscripts, not scripts. If there is no resource dir there aren't any userscripts, so that's fine.
