### PR TITLE
Remove sources of panic when laying out an iframe without a nested browsing context

### LINKED ISSUE #17482: Panic during layout when encountering an iframe with no parent node and no browsing context
called `Option::unwrap()` on a `None` value
### Servo Version:
Servo 0.0.1-ed5485e
### Backtrace:
```

WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scroll a non-scroll node.
WARNING: <RenderBackend>: Tried to scro
...
```

This error repeatedly occurred on my Windows 7 machine, but only when opening the arstechnica website.

### PR DESCRIPTION
**Pull request by asajeffrey**
At the moment, layout panics if it discovers an iframe without a nested browsing context. Under normal circumstances, this is reasonable, but it requires very tight synchronization between script, layout, the constellation and the compositor. In particular, if a layout is in progress when an iframe's browsing context is discarded, this can trigger panic.

This PR fixes this in two ways:

1. Making the pipeline and browsing context ids optional in layout's representation of an iframe.
2. Shutting down layout before discarding a browsing context, rather than after.

This is belt and braces.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #17482 and #18477
- [X] These changes do not require tests because the PR is fixing a panic caused by a race condition

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18514)

### CODE REVIEW

**Comment by asajeffrey** [comment]
cc @jdm

File: components/layout/fragment.rs [hunk 1]
```diff
@@ -488,14 +488,15 @@ impl ImageFragmentInfo {
...
-    pub pipeline_id: PipelineId,
+    /// The frame ID of this iframe. None if there is no nested browsing context.
+    pub browsing_context_id: Option<BrowsingContextId>,
+    /// The pipelineID of this iframe. None if there is no nested browsing context.
+    pub pipeline_id: Option<PipelineId>,
 }
 
 impl IframeFragmentInfo {
     /// Creates the information specific to an iframe fragment.
+    /// Returns None if the node has no nested browsing context.
```
Comment (emilio) [inline components/layout/fragment.rs]: This doesn't return `None` :)

Comment (asajeffrey) [reply components/layout/fragment.rs]: Oops. It did at one point :) Fixed.

**Comment by asajeffrey** [comment]
The unit test errors should go away once #18523 lands.
