### PR TITLE
layout: Fix negative outline offset

### LINKED ISSUE #19508: Negative outline-offset is not handled correctly.
See ```outline-014.htm``` for the relevant test and spec details.

### PR DESCRIPTION
**Pull request by lumiscosity**
Properly caps the minimum offset on each side as recommended by the standards: https://drafts.csswg.org/css-ui-3/#outline-offset

Testing: Covered by WPT tests. (3 new passing!)
Fixes: #19508

### CODE REVIEW

File: components/layout/display_list/mod.rs [hunk 1]
```diff
@@ -1553,13 +1553,11 @@ impl<'a> BuilderForBoxFragment<'a> {
...
-            .px()
-            .max(-self.border_rect.width() / 2.0)
-            .max(-self.border_rect.height() / 2.0) +
-            width;
-        let outline_rect = self.border_rect.inflate(offset, offset);
+        let offset = outline.outline_offset.px() + width;
+        let outline_rect = self.border_rect.inflate(
+            offset.max(-self.border_rect.width() / 2.0 + width),
+            offset.max(-self.border_rect.height() / 2.0 + width),
+        );
```
Comment (mrobinson) [inline components/layout/display_list/mod.rs:1568]: It would be good to link to and quote the specification text here:

```suggestion
        // From <https://drafts.csswg.org/css-ui-3/#outline-offset>
        // > Negative values must cause the outline to shrink into the border box. Both
        // > the height and the width of outside of the shape drawn by the outline should
        // > not become smaller than twice the computed value of the outline-width
        // > property, to make sure that an outline can be rendered even with large
        // > negative values. User agents should apply this constraint independently in
        // > each dimension. If the outline is drawn as multiple disconnected shapes, this
        // > constraint applies to each shape separately. 
        let offset = outline.outline_offset.px() + width;
        let outline_rect = self.border_rect.inflate(
            offset.max(-self.border_rect.width() / 2.0 + width),
            offset.max(-self.border_rect.height() / 2.0 + width),
        );
```

**Review by mrobinson — CHANGES_REQUESTED** [review]
Nice change! Just one small request:

**Review by Loirooriol — APPROVED** [review]
Oh, when I implemented this I guess I missed the

> User agents should apply this constraint independently in each dimension

**Review by mrobinson — APPROVED** [review]
