### PR TITLE
layout: Implement overflow scroll support for different axes

### LINKED ISSUE #35037: The page effect is incorrect when overflow-x and overflow-y are set to different values.
**Describe the bug:**
When overflow-x and overflow-y are set to different values, scrolling in different directions is not disabled.

**To Reproduce:**
Set `overflow-x` to `auto` and `overflow-x` to `hidden`. The expected effect is that the x-axis direction can slide, but the y-axis direction cannot.
But now it slides in both directions.
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>overflow x y</title>
    <style>
        div {
            border: 2px black solid;
            width: 360px;
            height: 50px;
        }
    </style>
</head>

<body>
<div id="xs" style="overflow-x: auto; overflow-y: hidden; height: 100px; width: 100px">
    <div id="xs1">scroll div1 scroll div2 scroll div3 scroll div4 scroll div5</div>
    <div>scroll div2</div>
    <div>scroll div3</div>
    <div>scroll div4</div>
    <div>scroll div5</div>
</div>
<div style="overflow-x: hidden; overflow-y: auto; height: 100px; width: 100px">
    <div>scroll div1 scroll div1 scroll div1 scroll div1 scroll div1</div>
    <div>scroll div2</div>
    <div>scroll div3</div>
    <div>scroll div4</div>
    <div>scroll div5</div>
</div>
</body>
</html>
```
**Platform:**
ALL

### LINKED ISSUE #35452: layout: implement scroll of viewport for different axes
This is a follow up issue of #35037 and discussion in #35414 

1. Currently, control of scrolling of viewport for both axes is not implemented. https://github.com/servo/servo/blob/8cd280ca3b221712f8111851fccdc757e7fabce8/components/layout_2020/flow/root.rs#L66-L67

2. Nitpicking: The address of comment above should actually be https://drafts.csswg.org/css-overflow/#overflow-propagation

### LINKED ISSUE #35453: PhysicalVec<Overflow> does not make sense
https://github.com/servo/servo/blob/becd09758531acbf029f5cc2cbffba8f4c2985ef/components/layout_2020/style_ext.rs#L304

https://github.com/servo/servo/blob/becd09758531acbf029f5cc2cbffba8f4c2985ef/components/layout_2020/geom.rs#L25

`effective_overflow` returns the pair of `{overflow_x, overflow_y}`, which should not be `euclid::Vector2D`.

This is a follow up issue of https://github.com/servo/servo/issues/35037 and discussion in https://github.com/servo/servo/pull/35414

### PR DESCRIPTION
**Pull request by yezhizhen**
1. Add AxesScrollSensitivity
2. Add logic to enable scroll control in both axes
3. Update layout_2013(layout) to be compatible to `mach try` test

cc @xiaochengh 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #35037
- [x] These changes fix #35452 
- [x] These changes fix #35453 

- [x] There are no tests for these changes as we don't support testdriver yet, [e.g.](https://github.com/web-platform-tests/wpt/blob/4cb608c82eec9cb3638fa4cd4a895f8014429f9b/resources/testdriver-actions.js#L373-L378)

### CODE REVIEW

File: components/layout/display_list/builder.rs [hunk 1]
```diff
@@ -2535,12 +2535,25 @@ impl BlockFlow {
...
+        let sensitivity_y = match self.fragment.style.get_box().overflow_y {
+            StyleOverflow::Hidden => ScrollSensitivity::Script,
+            //TODO
+            //StyleOverflow::Clip => ScrollSensitivity::None,
+            StyleOverflow::Visible => ScrollSensitivity::None,
+            _ => ScrollSensitivity::ScriptAndInputEvents,
+        };
+
+        let sensitivity = AxesScrollSensitivity {
+            vertical: sensitivity_x,
```
Comment (kongbai1996) [inline components/layout/display_list/builder.rs:2555]: How to understand `vertical` and `horizontal`, in my opinion, the x axis direction should be `horizontal`.

Comment (yezhizhen) [reply components/layout/display_list/builder.rs:2555]: You are right. I will modify.
I didn't notice the problem in testing as this wasn't actually used.

File: components/layout_2020/display_list/stacking_context.rs [hunk 2]
```diff
@@ -1402,12 +1404,27 @@ impl BoxFragment {
...
-            if ComputedOverflow::Hidden == overflow.x && ComputedOverflow::Hidden == overflow.y {
-                ScrollSensitivity::Script
-            } else {
-                ScrollSensitivity::ScriptAndInputEvents
-            };
+
+        let sensitivity_x = match overflow.x {
+            ComputedOverflow::Hidden => ScrollSensitivity::Script,
+            //TODO
+            //ComputedOverflow::Clip => ScrollSensitivity::None,
```
Comment (xiaochengh) [inline components/layout_2020/display_list/stacking_context.rs:1411]: We should never have `overflow: clip` here, as it would have been rejected at L1378. So we should have
```rust
ComputedOverflow::Clip => unreachable!("A scroll container should not be established with overflow: clip"),
```
Ditto below

File: components/layout/display_list/builder.rs [hunk 3]
```diff
@@ -2535,12 +2535,25 @@ impl BlockFlow {
...
-        let sensitivity = if StyleOverflow::Hidden == self.fragment.style.get_box().overflow_x &&
-            StyleOverflow::Hidden == self.fragment.style.get_box().overflow_y
-        {
-            ScrollSensitivity::Script
-        } else {
-            ScrollSensitivity::ScriptAndInputEvents
+        let sensitivity_x = match self.fragment.style.get_box().overflow_x {
+            StyleOverflow::Hidden => ScrollSensitivity::Script,
+            //TODO
+            //StyleOverflow::Clip => ScrollSensitivity::None,
```
Comment (xiaochengh) [inline components/layout/display_list/builder.rs:2541]: We should never have `overflow: clip` here, as it would have been rejected at L2522. So we should have
```rust
ComputedOverflow::Clip => unreachable!("A scroll container should not be established with overflow: clip"),
```
Ditto below

File: components/layout/display_list/builder.rs (hunk 1 above)
Comment (xiaochengh) [reply components/layout/display_list/builder.rs]: Please leave `components/layout` unchanged. This is the legacy layout module which is no longer under maintenance.

File: components/layout_2020/display_list/stacking_context.rs (hunk 2 above)
Comment (xiaochengh) [reply components/layout_2020/display_list/stacking_context.rs:1411]: A second thought: I think this match-case should be turned into a utility function (probably named `ScrollSensitivity::from_overflow()`), so that we don't need to repeat it. And these lines can be simplified into:

```rust
let sensitivity = AxesScrollSensitivity {
  horizontal: ScrollSensitivity::from_overflow(overflow.x),
  vertical: ScrollSensitivity::from_overflow(overflow.y),
};
```

File: components/layout/display_list/builder.rs (hunk 1 above)
Comment (yezhizhen) [reply components/layout/display_list/builder.rs]: > Please leave `components/layout` unchanged. This is the legacy layout module which is no longer under maintenance.

I left it unchanged in a previous try. But `mach try` would fail, because it depends on other code we changed.
Previous run [here](https://github.com/yezhizhen/servo/actions/runs/13238305691/job/36947878434)

File: components/layout_2020/display_list/stacking_context.rs (hunk 2 above)
Comment (yezhizhen) [reply components/layout_2020/display_list/stacking_context.rs:1411]: > We should never have `overflow: clip` here, as it would have been rejected at L1378. So we should have
> 
> ```rust
> ComputedOverflow::Clip => unreachable!("A scroll container should not be established with overflow: clip"),
> ```
> 
> Ditto below

It is still possible, as function `establishes_scroll_container` at L1378  [now](https://github.com/servo/servo/pull/35414/files#diff-0b9973b272d5729b256ff75a0d7bf05b7455ec228cf57d6989ae07c6fb756c2a
)
checks both direction for scrollable.

File: components/layout/display_list/builder.rs [hunk 4]
```diff
@@ -2535,12 +2535,25 @@ impl BlockFlow {
...
+            StyleOverflow::Visible => ScrollSensitivity::None,
+            _ => ScrollSensitivity::ScriptAndInputEvents,
+        };
+
+        let sensitivity_y = match self.fragment.style.get_box().overflow_y {
+            StyleOverflow::Hidden => ScrollSensitivity::Script,
+            //TODO
+            //StyleOverflow::Clip => ScrollSensitivity::None,
+            StyleOverflow::Visible => ScrollSensitivity::None,
+            _ => ScrollSensitivity::ScriptAndInputEvents,
```
Comment (mrobinson) [inline components/layout/display_list/builder.rs:2551]: I don't think a wildcard is a good idea here. Instead handle every case...the missing one is StyleOverflow::Clip and that should be `ScrollSensitivity::None`, right?

File: components/layout_2020/display_list/stacking_context.rs [hunk 5]
```diff
@@ -1402,12 +1404,27 @@ impl BoxFragment {
...
+            ComputedOverflow::Visible => ScrollSensitivity::None,
+            _ => ScrollSensitivity::ScriptAndInputEvents,
```
Comment (mrobinson) [inline components/layout_2020/display_list/stacking_context.rs:1413]: Please see my comment above about the wildcard.

File: components/layout_2020/display_list/stacking_context.rs (hunk 2 above)
Comment (xiaochengh) [reply components/layout_2020/display_list/stacking_context.rs:1411]: No. Per spec, if one axis is `clip`, the other axis must be adjusted to a non-scrollable value. 

> The [visible](https://drafts.csswg.org/css-overflow/#valdef-overflow-visible)/[clip](https://drafts.csswg.org/css-overflow/#valdef-overflow-clip) values of [overflow](https://drafts.csswg.org/css-overflow/#propdef-overflow) compute to [auto](https://drafts.csswg.org/css-overflow/#valdef-overflow-auto)/hidden (respectively) if one of [overflow-x](https://drafts.csswg.org/css-overflow/#propdef-overflow-x) or [overflow-y](https://drafts.csswg.org/css-overflow/#propdef-overflow-y) is neither visible nor clip.

File: components/shared/webrender/display_list.rs [hunk 6]
```diff
@@ -17,6 +17,13 @@ pub enum ScrollSensitivity {
     ScriptAndInputEvents,
     /// This node can only be scrolled by script events.
     Script,
+    /// This node cannot be scrolled
```
Comment (mrobinson) [inline components/shared/webrender/display_list.rs:20]: You're missing a period for this docstring and the others have it, so this should be consistent.

I think the documentation of this structure should be updated to reflect that it is no longer about the "node" but about a particular axis on the node, otherwise it will be confusing. Here's my recommendation:

```rust
/// The scroll sensitivity of a scroll node in a particular axis ie whether it can be scrolled due to 
/// input events and script events or only script events.
#[derive(Clone, Copy, Debug, Deserialize, PartialEq, Serialize)]
pub enum ScrollSensitivity {
    /// The axis of this node can be scrolled by input and script events.
    ScriptAndInputEvents,
    /// The axis of this node can only be scrolled by script events.
    Script,
    /// This node cannot be scrolled in this axis.
```

File: components/shared/webrender/display_list.rs [hunk 7]
```diff
@@ -17,6 +17,13 @@ pub enum ScrollSensitivity {
...
+    None,
+}
```
Comment (mrobinson) [inline components/shared/webrender/display_list.rs:22]: You're missing a newline after this data structure.

File: components/shared/webrender/display_list.rs [hunk 8]
```diff
@@ -17,6 +17,13 @@ pub enum ScrollSensitivity {
...
+#[derive(Clone, Copy, Debug, Deserialize, PartialEq, Serialize)]
+pub struct AxesScrollSensitivity {
+    pub vertical: ScrollSensitivity,
+    pub horizontal: ScrollSensitivity,
```
Comment (mrobinson) [inline components/shared/webrender/display_list.rs:26]: You're adding a new public data structure so it would be nice to add a simple docstring. How about this:

```rust
/// The [`ScrollSensitivity`] of particular node in the vertical and horizontal axes.
```

File: components/shared/webrender/display_list.rs [hunk 9]
```diff
@@ -119,10 +126,6 @@ impl ScrollTreeNode {
             None => return None,
         };
 
-        if info.scroll_sensitivity != ScrollSensitivity::ScriptAndInputEvents {
-            return None;
-        }
-
```
Comment (mrobinson) [inline components/shared/webrender/display_list.rs:125]: An early return might still be useful here to avoid doing extra work. Just check both axes.

**Review by mrobinson — CHANGES_REQUESTED** [review]
Looks pretty good to me. A few minor changes requested below. Does this affects tests at all?

I think that @Loirooriol should take a look at this one a well since he has reviewed issues regarding overflow in different axes in the past.

File: components/layout_2020/display_list/stacking_context.rs (hunk 2 above)
Comment (yezhizhen) [reply components/layout_2020/display_list/stacking_context.rs:1411]: > No. Per spec, if one axis is `clip`, the other axis must be adjusted to a non-scrollable value.
> 
> > The [visible](https://drafts.csswg.org/css-overflow/#valdef-overflow-visible)/[clip](https://drafts.csswg.org/css-overflow/#valdef-overflow-clip) values of [overflow](https://drafts.csswg.org/css-overflow/#propdef-overflow) compute to [auto](https://drafts.csswg.org/css-overflow/#valdef-overflow-auto)/hidden (respectively) if one of [overflow-x](https://drafts.csswg.org/css-overflow/#propdef-overflow-x) or [overflow-y](https://drafts.csswg.org/css-overflow/#propdef-overflow-y) is neither visible nor clip.

I read this part of spec before. But doesn't it mean, if one axis is "**scrollable**"(auto/scroll/hidden), then the other **unscrollable (visible/clip)** axis would be computed to auto/hidden respectively?

File: components/layout/display_list/builder.rs (hunk 4 above)
Comment (yezhizhen) [reply components/layout/display_list/builder.rs:2551]: Ok. The missing one is `StyleOverflow::Scroll", which should be `ScrollSensitivity::ScriptAndInputEvents`.

`Clip` not supported yet. Once it is supported, we can just remove TODO comments.

**Comment by yezhizhen** [comment]
> > No. Per spec, if one axis is `clip`, the other axis must be adjusted to a non-scrollable value.
> > > The [visible](https://drafts.csswg.org/css-overflow/#valdef-overflow-visible)/[clip](https://drafts.csswg.org/css-overflow/#valdef-overflow-clip) values of [overflow](https://drafts.csswg.org/css-overflow/#propdef-overflow) compute to [auto](https://drafts.csswg.org/css-overflow/#valdef-overflow-auto)/hidden (respectively) if one of [overflow-x](https://drafts.csswg.org/css-overflow/#propdef-overflow-x) or [overflow-y](https://drafts.csswg.org/css-overflow/#propdef-overflow-y) is neither visible nor clip.
> 
> I read this part of spec before. But doesn't it mean, if one axis is "**scrollable**"(auto/scroll/hidden), then the other **unscrollable (visible/clip)** axis would be computed to auto/hidden respectively?

Now that I further think about this, I think I should not change `establishes_scroll_container`.
If one axis is scrollable, the computed value of the other **must be** scrollable.
So checking one direction is fine.
 
Therefore the computed result has two possibilities:
1. Both directions are scrollable
2. Both directions are unscrollable

As a further implication, I neither need to check `ComputedOverflow::Visible` nor `ComputedOverflow::Clip` in the match.

File: components/layout_2020/display_list/stacking_context.rs (hunk 2 above)
Comment (Loirooriol) [reply components/layout_2020/display_list/stacking_context.rs:1411]: > I think this match-case should be turned into a utility function

I agree with creating a function for this logic. Could e.g. use the `From` trait.

> Previously, it only checked x-axis.

Checking one axis suffices.

File: components/layout_2020/flow/root.rs [hunk 10]
```diff
@@ -93,10 +93,10 @@ impl BoxTree {
                 contains_floats,
             },
             canvas_background: CanvasBackground::for_root_element(context, root_element),
+            //TODO: Overflow::Clip support
```
Comment (Loirooriol) [inline components/layout_2020/flow/root.rs:96]: It's not obvious what's going on and what needs to be done for `clip`. I would quote the spec: https://drafts.csswg.org/css-overflow-3/#overflow-propagation

> If [`visible`](https://drafts.csswg.org/css-overflow-3/#valdef-overflow-visible) is applied to the viewport, it must be interpreted as [`auto`](https://drafts.csswg.org/css-overflow-3/#valdef-overflow-auto). If [`clip`](https://drafts.csswg.org/css-overflow-3/#valdef-overflow-clip) is applied to the viewport, it must be interpreted as [`hidden`](https://drafts.csswg.org/css-overflow-3/#valdef-overflow-hidden).

It could also be good to turn `sensitive_to_scroll_input: bool` into a `ScrollSensitivity` (or `AxesScrollSensitivity`). If you implement `From<Overflow> for ScrollSensitivity`,

```rs
let root_overflow = match root_overflow {
  Overflow::Visible => Overflow::Auto,
  Overflow::Clip => Overflow::Hidden,
  overflow => overflow,
};
...
ScrollSensitivity::from(root_overflow)
```

File: components/layout_2020/flow/root.rs [hunk 11]
```diff
@@ -93,10 +93,10 @@ impl BoxTree {
...
             sensitive_to_scroll_input: root_overflow != Overflow::Hidden,
         }
     }
-
```
Comment (Loirooriol) [inline components/layout_2020/flow/root.rs:99]: Don't remove

File: components/layout_2020/style_ext.rs [hunk 12]
```diff
@@ -583,7 +583,7 @@ impl ComputedValuesExt for ComputedValues {
 
     /// Whether or not the `overflow` value of this style establishes a scroll container.
     fn establishes_scroll_container(&self) -> bool {
-        self.effective_overflow().x.is_scrollable()
+        self.effective_overflow().x.is_scrollable() || self.effective_overflow().y.is_scrollable()
```
Comment (Loirooriol) [inline components/layout_2020/style_ext.rs:586]: Unnecessary: both axes need to have the same scrollability. You can add a comment (or assert) to make it clearer.

File: components/shared/webrender/display_list.rs [hunk 13]
```diff
@@ -17,6 +17,13 @@ pub enum ScrollSensitivity {
     ScriptAndInputEvents,
     /// This node can only be scrolled by script events.
     Script,
+    /// This node cannot be scrolled
+    None,
+}
+#[derive(Clone, Copy, Debug, Deserialize, PartialEq, Serialize)]
+pub struct AxesScrollSensitivity {
```
Comment (Loirooriol) [inline components/shared/webrender/display_list.rs:24]: Maybe just `pub type AxesScrollSensitivity = euclid::Vector2D<ScrollSensitivity>` or similar?

**Review by Loirooriol — CHANGES_REQUESTED** [review]

**Comment by yezhizhen** [comment]
New test running [here](https://github.com/yezhizhen/servo/actions/runs/13279573476)

File: components/layout_2020/style_ext.rs [hunk 14]
```diff
@@ -583,6 +583,7 @@ impl ComputedValuesExt for ComputedValues {
 
     /// Whether or not the `overflow` value of this style establishes a scroll container.
     fn establishes_scroll_container(&self) -> bool {
+        // Checking one axis suffice
```
Comment (xiaochengh) [inline components/layout_2020/style_ext.rs:586]: nit: suffices

File: components/shared/webrender/display_list.rs [hunk 15]
```diff
@@ -6,19 +6,42 @@
...
+            //TODO: Uncomment after Clip enabled in Stylo
+            //Overflow::Clip => unreachable!("A scroll container should not be established with overflow: clip"),
+        }
+    }
+}
+
+pub struct ScrollUnit;
+
+/// The [ScrollSensitivity] of particular node in the vertical and horizontal axes.
+pub type AxesScrollSensitivity = euclid::Vector2D<ScrollSensitivity, ScrollUnit>;
```
Comment (xiaochengh) [inline components/shared/webrender/display_list.rs:43]: I don't think we should use `euclid::Vector2D` here. `euclid::Vector2D` implements a vector in the geometrical sense (i.e., what the word "vector" actually means prior to C++ STL). But our struct here is just a pair of enums.

File: components/shared/webrender/display_list.rs [hunk 16]
```diff
@@ -6,19 +6,42 @@
...
+    None,
 }
 
+/// Convert [Overflow] to [ScrollSensitivity].
+impl From<Overflow> for ScrollSensitivity {
+    fn from(overflow: Overflow) -> Self {
+        match overflow {
+            Overflow::Hidden => ScrollSensitivity::Script,
+            Overflow::Scroll | Overflow::Auto => ScrollSensitivity::ScriptAndInputEvents,
+            Overflow::Visible => {
```
Comment (xiaochengh) [inline components/shared/webrender/display_list.rs:31]: Hmm... With this part isolated into a utility function, I think we should keep the branches of `visible` and `clip` reachable and return `None` for them. The reasons are:
1. When these lines were directly written in `stacking_context.rs`, there's a clear context that we are establishing a scroll container. So `visible` and `clip` should be unreached
2. But when isolated into a utility function, there's no context how the function is supposed to be used, and future commits may add calls to the function in other cases. As we can't assume a context, we shouldn't assume that these cases won't be reached, which means we should implement all the branches.

File: components/shared/webrender/display_list.rs (hunk 15 above)
Comment (yezhizhen) [reply components/shared/webrender/display_list.rs:43]: I agree. Vector2D have a lot methods realted to angle etc, which is unnecessary for our case.

@Loirooriol Any suggestions? If not, I would revert to previous definition of AxesScrollSensitivity.

Comment (Loirooriol) [reply components/shared/webrender/display_list.rs:43]: I mentioned `Vector2D` because it's what we use in https://github.com/servo/servo/blob/8c46749740b6a97f6881cf3b305f0eadc198678d/components/layout_2020/style_ext.rs#L304 (`PhysicalVec` is a `euclid::Vector2D`). But OK you can switch back to previous definition.

File: components/shared/webrender/display_list.rs (hunk 16 above)
Comment (yezhizhen) [reply components/shared/webrender/display_list.rs:31]: I would then wildcast Visible/Clip. So that no need to change this piece of code, after Clip gets enabled in the future. 

```rust
match overflow {
            Overflow::Hidden => ScrollSensitivity::Script,
            Overflow::Scroll | Overflow::Auto => ScrollSensitivity::ScriptAndInputEvents,
            _ => ScrollSensitivity::None
},
```
@mrobinson

File: components/layout_2020/style_ext.rs (hunk 14 above)
Comment (Loirooriol) [reply components/layout_2020/style_ext.rs:586]:
```suggestion
        // Checking one axis suffices, because the computed value ensures that
        // either both axes are scrollable, or none is scrollable.
```

File: components/shared/webrender/display_list.rs [hunk 17]
```diff
@@ -6,19 +6,42 @@
...
+                unreachable!("A scroll container should not be established with overflow: visible")
+            },
+            //TODO: Uncomment after Clip enabled in Stylo
+            //Overflow::Clip => unreachable!("A scroll container should not be established with overflow: clip"),
```
Comment (Loirooriol) [inline components/shared/webrender/display_list.rs:35]: `clip` has been enabled.

File: components/shared/webrender/display_list.rs (hunk 15 above)
Comment (xiaochengh) [reply components/shared/webrender/display_list.rs:43]: Then I would argue the usage you referenced above is a misuse and should be changed into a simple pair. In general, we shouldn't pass a non-numerical type to `Vector2D`.

**Comment by Loirooriol** [comment]
A bunch of comments were marked as resolved but weren't addressed, did you forget to push?

**Comment by yezhizhen** [comment]
> A bunch of comments were marked as resolved but weren't addressed, did you forget to push?

Yah I didn't. I mark as resolved when solved locally😅 Easier for me to track.

**Comment by yezhizhen** [comment]
> It's not obvious what's going on and what needs to be done for `clip`. I would quote the spec: https://drafts.csswg.org/css-overflow-3/#overflow-propagation
> 
> > If [`visible`](https://drafts.csswg.org/css-overflow-3/#valdef-overflow-visible) is applied to the viewport, it must be interpreted as [`auto`](https://drafts.csswg.org/css-overflow-3/#valdef-overflow-auto). If [`clip`](https://drafts.csswg.org/css-overflow-3/#valdef-overflow-clip) is applied to the viewport, it must be interpreted as [`hidden`](https://drafts.csswg.org/css-overflow-3/#valdef-overflow-hidden).
> 
> It could also be good to turn `sensitive_to_scroll_input: bool` into a `ScrollSensitivity` (or `AxesScrollSensitivity`). If you implement `From<Overflow> for ScrollSensitivity`,
> 
> ```rust
> let root_overflow = match root_overflow {
>   Overflow::Visible => Overflow::Auto,
>   Overflow::Clip => Overflow::Hidden,
>   overflow => overflow,
> };
> ...
> ScrollSensitivity::from(root_overflow)
> ```

I think the match above is just `to_scrollable` in Stylo.
https://github.com/servo/stylo/blob/main/style/values/specified/box.rs#L1849-L1855

I think I will open another issue A and resolve it there later.

**Question 2:** 
https://drafts.csswg.org/css-overflow/#overflow-propagation

> ... The element from which the value is propagated must then have a used overflow value of visible.

Is this implemented? I checked the `root.rs` file, it seems not.

https://github.com/servo/servo/blob/main/components/layout_2020/flow/root.rs#L48-L98

If not, I will open another issue B later and resolve it.

**Comment by Loirooriol** [comment]
> I think the match above is just `to_scrollable` in Stylo

Ah, sure. So I guess `sensitive_to_scroll_input: root_overflow.to_scrollable() != Overflow::Hidden` to handle `clip` correctly?

> Is this implemented

Doesn't seem so. Testcase (should see some green):

```html
<!DOCTYPE html>
<html style="overflow: hidden; height: 0">
  <body style="border: solid 50px green"></body>
</html>
```

**Comment by yezhizhen** [comment]
> > I think the match above is just `to_scrollable` in Stylo
> 
> Ah, sure. So I guess `sensitive_to_scroll_input: root_overflow.to_scrollable() != Overflow::Hidden` to handle `clip` correctly?
> 
> > Is this implemented
> 
> Doesn't seem so. Testcase (should see some green):
> 
> ```
> <!DOCTYPE html>
> <html style="overflow: hidden; height: 0">
>   <body style="border: solid 50px green"></body>
> </html>
> ```

That was also incorrect. I was planning to fixing it in **issue A.**

**Review by xiaochengh — COMMENTED** [review]
LGTM but please address Oriol's comments regarding root scroll sensitivity.

**Review by xiaochengh — COMMENTED** [review]
Still LGTM

**Comment by yezhizhen** [comment]
@Loirooriol Can you help me review the code? I think I have fixed all issues except **issue B**(will open in future and resolve then).

File: components/shared/webrender/display_list.rs [hunk 18]
```diff
@@ -6,17 +6,38 @@
...
+    None,
+}
+
+/// Convert [Overflow] to [ScrollSensitivity].
+impl From<Overflow> for ScrollSensitivity {
+    fn from(overflow: Overflow) -> Self {
+        match overflow {
+            Overflow::Hidden => ScrollSensitivity::Script,
+            Overflow::Scroll | Overflow::Auto => ScrollSensitivity::ScriptAndInputEvents,
+            _ => ScrollSensitivity::None,
```
Comment (Loirooriol) [inline components/shared/webrender/display_list.rs:31]: I would be explicit and handle `Overflow::Visible | Overflow::Clip`.

File: components/shared/webrender/display_list.rs [hunk 19]
```diff
@@ -6,17 +6,38 @@
...
+        }
+    }
+}
+
+/// The [ScrollSensitivity] of particular node in the vertical and horizontal axes.
+#[derive(Clone, Copy, Debug, Deserialize, PartialEq, Serialize)]
+pub struct AxesScrollSensitivity {
+    pub x: ScrollSensitivity,
+    pub y: ScrollSensitivity,
 }
```
Comment (Loirooriol) [inline components/shared/webrender/display_list.rs:41]: Nit: There are 3 cases where `AxesScrollSensitivity` is created using the same sensitivity for both axes. Might be worth doing `impl From<ScrollSensitivity> for AxesScrollSensitivity`. But fine either way.

**Review by Loirooriol — APPROVED** [review]
Thanks!

**Comment by Loirooriol** [comment]
> There are tests for these changes [here](https://github.com/yezhizhen/servo/actions/runs/13279573476)

This item in the template refers to whether the PR has test coverage if it changes behavior.
This is fixing #35037 so ideally it would need tests to avoid regressing it.
But I think this can only be tested with testdriver e.g. https://github.com/web-platform-tests/wpt/blob/4cb608c82eec9cb3638fa4cd4a895f8014429f9b/resources/testdriver-actions.js#L373-L378, but AFAIK we don't support testdriver...
So I guess we will have to make do without tests.
But please update the description.

**Comment by yezhizhen** [comment]
Thanks! I just updated the description, and delivered the final tiny patch.

File: components/shared/webrender/display_list.rs (hunk 18 above)
Comment (yezhizhen) [reply components/shared/webrender/display_list.rs]: Ok done~

**Review by mrobinson — APPROVED** [review]

File: components/shared/webrender/Cargo.toml [hunk 20]
```diff
@@ -27,3 +27,4 @@ serde = { workspace = true }
 servo_geometry = { path = "../../geometry" }
 servo-media = { workspace = true }
 surfman = { workspace = true, features = ["sm-x11"] }
+style = { workspace = true }
```
Comment (mrobinson) [inline components/shared/webrender/Cargo.toml:30]: I suggest keeping these in alphabetical order. It's surprising that this wasn't caught by the lint.

```suggestion
style = { workspace = true }
surfman = { workspace = true, features = ["sm-x11"] }
```
