### PR TITLE
script: Fix crash when failed requests finish from a previous generation

### LINKED ISSUE #42477: panic: What finished? (thread Script#1, at components/script/dom/html/htmllinkelement.rs:901)
This is slightly different from https://github.com/servo/servo/issues/42259 ; cc @mrobinson cc @TimvdLippe 
 
Minimal testcase:

```html
<!DOCTYPE html>
<link id="link" href="A"></link>
<script>
  link.rel = "stylesheet";
  link.href = "B";
</script>
```

System: Linux
Version: Version: Servo 0.0.5-7488c127d
Command: `./servo/servo`

```
What finished? (thread Script#1, at components/script/dom/html/htmllinkelement.rs:901)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::panic_with_hook
   3: std::panicking::panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: __rustc::rust_begin_unwind
   6: core::panicking::panic_fmt
   7: <script::dom::html::htmllinkelement::HTMLLinkElement as script::stylesheet_loader::StylesheetOwner>::load_finished
   8: script::stylesheet_loader::StylesheetContext::do_post_parse_tasks
   9: <T as script::task::TaskBox>::run_box
  10: script::script_thread::ScriptThread::handle_msg_from_script
  11: script::script_thread::ScriptThread::handle_msgs::{{closure}}
  12: script::script_thread::ScriptThread::handle_msgs
  13: std::sys::backtrace::__rust_begin_short_backtrace
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: std::sys::thread::unix::Thread::new::thread_start
  16: start_thread
             at ./nptl/pthread_create.c:447:8
  17: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
```

### PR DESCRIPTION
**Pull request by TimvdLippe**
Most likely a regression introduced in #42208 where the pending loads counter has been reset. For successful request this wasn't an issue, but for failed requests it was. Therefore, guard against these generation request problems by bailing out as soon as we post-process the request (which we do for all failed requests).

Fixes #42477

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Verified that `./mach test-wpt /css/cssom/HTMLLinkElement-load-event-002.html --repeat-until-unexpected` passes for 30 runs, which was the original issue in #42187

**Review by mrobinson — APPROVED** [review]

File: components/script/stylesheet_loader.rs [hunk 1]
```diff
@@ -226,14 +226,16 @@ impl StylesheetContext {
         // This might happen when we time out a resource, but that happens in `fetch` instead
     }
 
-    fn decrement_load_and_render_blockers(&self, document: &Document) {
+    fn decrement_load_and_render_blockers(self, document: &Document) {
```
Comment (mrobinson) [inline components/script/stylesheet_loader.rs]:
```suggestion
    fn decrement_load_and_render_blockers_and_finish_load(self, document: &Document) {
```

**Review by mrobinson — COMMENTED** [review]
Just a minor nit:
