### PR TITLE
webdriver: Fix JS serialization for object with special key

### LINKED ISSUE #38083: WebDriver: error when passing elements to Execute Script
Servo throws a JS syntax error when you pass an object that [represents a web element](https://w3c.github.io/webdriver/#dfn-represents-a-web-element) to the WebDriver server as an [Execute Script](https://w3c.github.io/webdriver/#execute-script) argument.

Minimal repro as of Servo fcb2a4cd95a19c8ef43f73c1c116117785a61cc4:

```sh
$ cargo new app
$ cd app
$ cargo add webdriver_client@0.2.5
```

<details><summary>src/main.rs</summary>

```rust
use std::{
    error::Error,
    net::{Shutdown, TcpStream},
    process::Command,
    thread::sleep,
    time::Duration,
};

use webdriver_client::{
    Driver, HttpDriverBuilder, LocationStrategy,
    messages::{ExecuteCmd, NewSessionCmd},
};

fn main() -> Result<(), Box<dyn Error>> {
    // Run servoshell.
    Command::new("../../servo/target/release/servo")
        .args(["--webdriver", "about:blank"])
        .spawn()?;

    let driver = HttpDriverBuilder::default()
        .url("http://127.0.0.1:7000")
        .build()?;
    let mut params = NewSessionCmd::default();

    // Remove the unsupported `goog:chromeOptions` capability, which Servo rejects with a
    // “Session not created due to invalid capabilities” error.
    params.reset_always_match();

    // Wait for the WebDriver server to start.
    loop {
        sleep(Duration::from_millis(250));
        if let Ok(stream) = TcpStream::connect("127.0.0.1:7000") {
            stream.shutdown(Shutdown::Both)?;
            break;
        }
    }

    // Connect to the WebDriver server and control Servo.
    let session = driver.session(&params)?;
    session.go("data:text/html,<p>")?;

    let p = session.find_element(r"p", LocationStrategy::Css)?;
    session.execute(ExecuteCmd {
        script: "console.log(1)".to_owned(),
        // With no argument (`vec![]`), the execute succeeds.
        args: vec![p.reference()?],
    })?;

    Ok(())
}
```
</details>

```
[2025-07-15T08:29:26Z ERROR script::dom::bindings::error] Error at :2:58 missing : after property id
Error:
   0: Error: JS evaluation raised an unknown exception

Location:
   src/main.rs:46

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

The client’s request appears to be serialised correctly:

```sh
$ cargo add log@0.3.8
$ cargo add env_logger@0.4.3
```

```rust
env_logger::LogBuilder::new().filter(None, log::LogLevelFilter::Debug).init()?;
```

```
DEBUG:webdriver_client: POST url: http://127.0.0.1:7000/session/dea57e6a-bca1-4aef-b4e9-3211326fcc38/execute/sync
body: {"script":"console.log(1)","args":[{"ELEMENT":"e87fbbcc02e44b6ba5f8a8fe4a2c29ea","element-6066-11e4-a52e-4f735466cecf":"e87fbbcc02e44b6ba5f8a8fe4a2c29ea"}]}
```

It looks like passing _any_ JSON object with properties containing `-` fails in Servo:

```sh
$ cargo add serde_json@1.0.140
```

```rust
session.execute(ExecuteCmd {
    script: "console.log(1)".to_owned(),
    // With no argument (`vec![]`), the execute succeeds.
    args: vec![serde_json::json!({"-": 0})],
})?;
```

```
DEBUG:webdriver_client: POST url: http://127.0.0.1:7000/session/12b803a2-afbb-4f04-b5d4-90cf3fc02679/execute/sync
body: {"script":"console.log(1)","args":[{"-":0}]}
[2025-07-15T08:35:13Z ERROR script::dom::bindings::error] Error at :2:6 expected property name, got '-'
Error:
   0: Error: JS evaluation raised an unknown exception

Location:
   src/main.rs:47

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

### PR DESCRIPTION
**Pull request by yezhizhen**
Previously, the JS deserialization is wrong for object like `{"-": 3}`. This was because we never generate a valid JSON string literal from the request.

Now I share @Loirooriol's laughter: "We just fixed something very basic, but there is no existing test covering this", after fixing a bunch of things in past few days.

Testing: Added two new subtests to [wdspec](https://web-platform-tests.org/writing-tests/wdspec.html).
Fixes: #38083

### CODE REVIEW

File: components/webdriver_server/elements.rs [hunk 1]
```diff
@@ -123,18 +124,14 @@ impl Handler {
...
-                        Ok(format!("{}: {}", k, arg))
+                        Ok(format!("{key}: {arg}"))
                     })
                     .collect::<WebDriverResult<Vec<String>>>()?;
                 format!("{{{}}}", elems.join(", "))
             },
-            _ => serde_json::to_string(v).map_err(|_| {
-                WebDriverError::new(
-                    ErrorStatus::InvalidArgument,
-                    "Failed to serialize script argument",
```
Comment (yezhizhen) [inline components/webdriver_server/elements.rs:135]: This was mapping was unnecessary as already done in https://hg-edge.mozilla.org/mozilla-central/file/tip/testing/webdriver/src/error.rs#l363

**Review by jdm — APPROVED** [review]
Whoops!
