### PR TITLE
script: Do not conflate shadow roots and the `Document` element in `element.scrollLeft` and similar methods 

### LINKED ISSUE #41002: `ClientWidth` of first descendant of shadow root incorrectly returns viewport width
**Describe the bug:**
Consider the below example: When getting the clientWidth Attribute of the first descendants of Shadow Root, Servo return the viewport width, while Chromium return the actual size of that element.

**To Reproduce:**
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <style>
        #host {
            width: 300px;
            height: 200px;
            border: black 2px solid;
        }
    </style>
    <div id="host">
    </div>
    <script>
        const shadow_host = document.getElementById("host");
        let shadow_root = shadow_host.attachShadow({mode:"open"})
        const div = document.createElement("div");
        div.textContent = "I'm in the shadow DOM";
        shadow_root.appendChild(div);
        console.log("shadow_host_client_width: ",shadow_host.clientWidth);
        console.log("shadow_root_element_client_width: ", div.clientWidth);
    </script>
    
</body>
</html>
```
Servo return 1024 for clientWidth of shadow_root_element(div), while chromium return 300, both with unit px.

**Platform:**
All

There seems to have no WPT test guarding this behaviour. Recording this for future reference.

related Spec: 
[spec for clientWidth](https://drafts.csswg.org/cssom-view/#dom-element-clientwidth):
> 2. If the element is the [root element](https://drafts.csswg.org/css-display-4/#root-element) and the element’s [node document](https://dom.spec.whatwg.org/#concept-node-document) is not in [quirks mode](https://dom.spec.whatwg.org/#concept-document-quirks), or if the element is [the `body` element](https://html.spec.whatwg.org/multipage/dom.html#the-body-element-2) and the element’s node document *is* in quirks mode, return the [viewport](https://drafts.csswg.org/css2/#viewport%E2%91%A0) width excluding the size of a rendered scroll bar (if any).

In servo, the first descendants of Shadow Root is considered to be root_element of itself. Hence falling into above step of ClientWidth algorithm. **We probably want to change the spec, adding a constraint: only if 1) the element is the root element, 2) it is not in a shadow tree and 3) not in quirk mode, shall we fall into that step.**

Second part related to the discrepancy with the [definition of root element in](https://drafts.csswg.org/css-display-4/#root-element) and the [implementation in servo](https://github.com/servo/servo/blob/385a4bf64b47f4740dbe7a5ac8593a2d3b434ba5/components/script/dom/element.rs#L1679-L1692):
As per the spec for root element:
> The [element](https://drafts.csswg.org/css-display-4/#elements) at the root of the [document tree](https://dom.spec.whatwg.org/#concept-document-tree). In a document tree produced under the DOM, this is the [document element](https://dom.spec.whatwg.org/#document-element); in HTML it is the `[html](https://html.spec.whatwg.org/multipage/semantics.html#the-html-element)` element. [[DOM]](https://drafts.csswg.org/css-display-4/#biblio-dom) [[HTML]](https://drafts.csswg.org/css-display-4/#biblio-html)

For element in shadow tree, the root_element probably should be the root of the document tree that element is adopted to. But currently servo implementation would try to find the last node that does not have parent.

cc @xiaochengh @stevennovaryo @simonwuelker

### PR DESCRIPTION
**Pull request by zen-zap**
This PR fixes an issue where the Shadow DOM roots were incorrectly identified as the document roots in scroll and dimension calculations. The previous check `*self.root_element() == *self` returned true for shadow roots which caused `scrollTop`, `scrollLeft`, `clientWidth` to return viewport dimensions instead of actual dimensions. The previous check was replaced with the already existing `self.is_document_element()` to check for actual roots.

Testing: 
 - This causes `shadow-dom/scroll-restore-shadow.html` to start passing.
 - It was also locally tested on the tests given by @rayguo17 ( [clientWidth Test](https://github.com/servo/servo/issues/41002#issue-3684265503) and [scrollTop Test](https://github.com/servo/servo/issues/41002#issuecomment-3605214797) )

   Test results: 
   ```
   No build type specified so assuming `--dev`.
   shadow_host_client_width:  300
   shadow_root_element_client_width:  300
   
   No build type specified so assuming `--dev`.
   shadow host scrollTop:  0
   shadow_root_element_scrollTop:  0
   document root element scrollTop:  536
   Button in shadow DOM clicked
   ```

Fixes: #41002

### CODE REVIEW

File: components/script/dom/element.rs [hunk 1]
```diff
@@ -1691,6 +1691,20 @@ impl Element {
...
+        }
+
+        // we need to be in a document tree but not in a shadow tree
+        if self.upcast::<Node>().is_in_a_shadow_tree() {
+            return false;
+        }
+
+        self.node.is_in_a_document_tree()
+    }
+
```
Comment (mrobinson) [inline components/script/dom/element.rs]: Maybe it would make more sense to have a  `shadow_including_root_element` and `shadow_excluding_root_element`. "CSS root element" is not a specification concept AFAIK (correct me if I'm wrong), so we should avoid adding it.

Comment (rayguo17) [reply components/script/dom/element.rs]: I agree that "CSS root element" is not a good name, a rename to `is_shadow_excluding_root_element` would make more sense.

File: components/script/dom/element.rs [hunk 2]
```diff
@@ -1691,6 +1691,20 @@ impl Element {
         }
     }
 
+    pub(crate) fn is_css_root_element(&self) -> bool {
+        // check if we're top of the tree that we're in
```
Comment (rayguo17) [inline components/script/dom/element.rs]: It would be great if we can have a comment to the link to the spec here. like: 
```
/// <https://drafts.csswg.org/css-display-4/#root-element>
pub(crate) fn is_shadow_excluding_root_element(&self) -> bool
```

**Review by yezhizhen — COMMENTED** [review]
Can you update test expectation?

File: components/script/dom/element.rs [hunk 3]
```diff
@@ -1691,6 +1691,20 @@ impl Element {
...
+        if *self.root_element() != *self {
+            return false;
+        }
+
+        // we need to be in a document tree but not in a shadow tree
+        if self.upcast::<Node>().is_in_a_shadow_tree() {
+            return false;
+        }
+
+        self.node.is_in_a_document_tree()
```
Comment (simonwuelker) [inline components/script/dom/element.rs]: The if check above is unnecessary, nodes can never be in a shadow tree and a document tree at the same time.

* "in a shadow tree" => the tree's root is a shadow root
* "in a document tree"  => the tree's root is a document node

File: components/script/dom/element.rs (hunk 1 above)
Comment (Loirooriol) [reply components/script/dom/element.rs]: Don't overcomplicate it, just `is_document_element`: https://dom.spec.whatwg.org/#document-element

Comment (simonwuelker) [reply components/script/dom/element.rs]: > a rename to is_shadow_excluding_root_element would make more sense.

But that is not really what this function does, is it?

"shadow excluding" usually means that the connection between shadow hosts and their respective shadow roots is not considered. There are a bunch of examples in `node.rs` where `ShadowIncluding::No` or `ShadowIncluding::Yes` is used. So naming this function `shadow_excluding_root_element` makes it sound as if it should return `true` for elements that are the root element of their tree, regardless of whether its a shadow tree or a document tree. Which is misleading, because it only returns true for document trees.

How about `is_root_element_of_document_tree` instead?

Comment (Loirooriol) [reply components/script/dom/element.rs]: Actually, it already exists: https://github.com/servo/servo/blob/e81e92fbc2ce3414a783f25731fe014cd052c1ff/components/script/dom/element.rs#L1721-L1727

**Comment by zen-zap** [comment]
As mentioned by @Loirooriol, I replaced the helper with the existing `is_document_element()`. 

They now pass the tests given by @rayguo17 ( [clientWidth Test](https://github.com/servo/servo/issues/41002#issue-3684265503) and [scrollTop Test](https://github.com/servo/servo/issues/41002#issuecomment-3605214797) )

test results: 

```
No build type specified so assuming `--dev`.
shadow_host_client_width:  300
shadow_root_element_client_width:  300

No build type specified so assuming `--dev`.
shadow host scrollTop:  0
shadow_root_element_scrollTop:  0
document root element scrollTop:  536
Button in shadow DOM clicked
```

Also updated the test expectation for `scroll-restore-shadow`

File: tests/wpt/meta/shadow-dom/scroll-restore-shadow.html.ini [hunk 4]
```diff
@@ -1,3 +1,2 @@
 [scroll-restore-shadow.html]
   [Scroll position restore on shadow tree]
-    expected: FAIL
```
Comment (mrobinson) [inline tests/wpt/meta/shadow-dom/scroll-restore-shadow.html.ini:3]: You can remove this file entirely now.

**Review by mrobinson — CHANGES_REQUESTED** [review]
Nice. This makes more sense to me now.

**Comment by mrobinson** [comment]
@zen-zap Can you please also update the PR description? It does not accurately reflect the change any longer.

**Review by mrobinson — APPROVED** [review]
Nice. This makes more sense to me now.
