### PR TITLE
devtools: Fix DevTools failing to respond when inspecting multiple tabs

### LINKED ISSUE #35879: DevTools fails to respond when inspecting multiple tabs
**Describe the bug:**
DevTools stops responding when inspecting the second tab in the minibrowser after navigating to a URL.

**To Reproduce:**

- Run Servo with DevTools enabled
- In Firefox after connecting, click the inspect button for the first tab (in this case, we have "servo.org" as the default)
- Now, in the minibrowser, open a new tab but do not type anything in the URL yet
- In Firefox, click "inspect" for that tab(should be "servo:newtab")
- Now, go back to the minibrowser, in second tabe type a URL (e.g., example.org), and press enter.
- In Firefox, if you now click "inspect" next to the second tab (in this case, the example.org tab), you will see that it causes DevTools to fail with the error: `[ERROR devtools] DevTools actor stopped responding.`

**Platform:**
Can confirm for MacOS M2

### PR DESCRIPTION
**Pull request by atbrakhi**
Currently, DevTools fails to respond when multiple tabs are open. This can also happen if you have a single tab open but then open a different one in the same tab. This issue occurs because we are using `active_pipeline` as the `browser_id`.

Every time we navigate, `active_pipeline` (also known as `pipeline_id` in some parts of the codebase) gets updated, while `browser_id` remains the same for a tab. This PR uses `browser_context_id` for `browser_id`, which aligns with what servo sends to the client. `outer_window_id` is `active_pipeline`, which is correct. Initially, we were using `active_pipeline` for `browser_id`,  which caused the bug.

Signed-off-by: atbrakhi <atbrakhi@igalia.com>

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #35879

### CODE REVIEW

File: components/devtools/actors/tab.rs [hunk 1]
```diff
@@ -140,7 +140,8 @@ impl TabDescriptorActor {
 
     pub fn encodable(&self, registry: &ActorRegistry, selected: bool) -> TabDescriptorActorMsg {
         let ctx_actor = registry.find::<BrowsingContextActor>(&self.browsing_context_actor);
-        let browser_id = ctx_actor.active_pipeline.get().index.0.get();
+        let browser_id = ctx_actor.browsing_context_id.index.0.get();
+        let outer_window_id = ctx_actor.active_pipeline.get().index.0.get();
```
Comment (mrobinson) [inline components/devtools/actors/tab.rs:144]: Are we able to use any value as the `browser_id`? I wonder if it makes more sense to use the `WebViewId` as that is for the entire WebView. I understand that devtools is supposed to target an entire WebView and you should be able to look at all of the subframes internally. Here is what things are essentially:

1. `WebViewId` /` TopLevelBrowsingContextId`: entire `WebView`
2. `BrowsingContextId`: a single frame in the `WebView`, maybe the main frame
3. `PipelineId`: A single document loaded in the frame, which can change from navigation

Comment (delan) [reply components/devtools/actors/tab.rs:144]: yeah, i think we can land the patch like this, since it’s still an improvement over the old impl. just leave a TODO in there :)

**Review by mrobinson — APPROVED** [review]

File: components/devtools/actors/tab.rs (hunk 1 above)
Comment (atbrakhi) [reply components/devtools/actors/tab.rs:144]: I did not add TODO at the end as i was already working on this refactor in another branch. I have a PR now https://github.com/servo/servo/pull/35956
