### PR TITLE
webdriver: Wait animation frame callbacks before taking (element) screenshot

### LINKED ISSUE #39306: Intermittent PASS in `/webdriver/tests/classic/take_element_screenshot/scroll_into_view.py`
https://github.com/servo/servo/runs/50352086106

```
OK /webdriver/tests/classic/take_element_screenshot/scroll_into_view.py
    PASS [expected FAIL] subtest: test_scroll_into_view
```

This is the only test in the file.

### PR DESCRIPTION
**Pull request by yezhizhen**
According to spec, we should wait animation frame callbacks before taking (element) screenshot. As "element screenshot" would automatically scroll into view, this solves intermittency.

Testing: Manually tested on pages, and `take_element_screenshot/scroll_into_view.py` passes stably now.
Fixes: #39306

### CODE REVIEW

File: components/servo/lib.rs [hunk 1]
```diff
@@ -1065,6 +1065,7 @@ impl Servo {
                     if let Err(e) = response_sender.send(Err(())) {
                         error!("Sending reply to create png failed {e:?}");
                     }
+                    return;
```
Comment (yezhizhen) [inline components/servo/lib.rs:1068]: Forgot to add this in #39499. We should early return if bounding rectangle has area 0.

**Review by jdm — APPROVED** [review]
Nice solution.
