### PR TITLE
wpt: Capture test output when running WPT in WebDriver mode

### LINKED ISSUE #39176: Running WPT with servodriver hides panic backtraces
All you see is the python traceback:

```
  ▶ CRASH [expected OK] /wasm/serialization/module/serialization-via-idb.any.worker.html
  │   → Traceback (most recent call last):
  │   →   File "/home/runner/work/servo/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 1085, in run_func
  │   →     self.result = True, self.func(self.protocol, self.url, self.timeout)
  │   →                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/home/runner/work/servo/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 1181, in do_testharness
  │   →     raw_results = protocol.testdriver.run(url, self.script_resume, test_window)
  │   →                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/home/runner/work/servo/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 657, in run
  │   →     test_driver_message = self.get_next_message(url, script_resume, test_window)
  │   →                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/home/runner/work/servo/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 701, in get_next_message
  │   →     return self._get_next_message_classic(url, script_resume)
  │   →            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/home/runner/work/servo/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 708, in _get_next_message_classic
  │   →     return self.parent.base.execute_script(script_resume, asynchronous=True, args=[strip_server(url)])
  │   →            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/home/runner/work/servo/servo/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 78, in execute_script
  │   →     return method(script, args=args)
  │   →            ^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/home/runner/work/servo/servo/tests/wpt/tests/tools/webdriver/webdriver/client.py", line 675, in execute_async_script
  │   →     return self.send_session_command("POST", "execute/async", body)
  │   →            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/home/runner/work/servo/servo/tests/wpt/tests/tools/webdriver/webdriver/client.py", line 555, in send_session_command
  │   →     return self.send_command(method, url, body, timeout)
  │   →            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/home/runner/work/servo/servo/tests/wpt/tests/tools/webdriver/webdriver/client.py", line 504, in send_command
  │   →     response = self.transport.send(
  │   →                ^^^^^^^^^^^^^^^^^^^^
  │   →   File "/home/runner/work/servo/servo/tests/wpt/tests/tools/webdriver/webdriver/transport.py", line 230, in send
  │   →     response = self._request(method, uri, payload, headers, timeout=timeout)
  │   →                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/home/runner/work/servo/servo/tests/wpt/tests/tools/webdriver/webdriver/transport.py", line 265, in _request
  │   →     response = self.connection.getresponse()
  │   →                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │   →   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/http/client.py", line 1395, in getresponse
  │   →     response.begin()
  │   →   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/http/client.py", line 325, in begin
  │   →     version, status, reason = self._read_status()
  │   →                               ^^^^^^^^^^^^^^^^^^^
  │   →   File "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/http/client.py", line 294, in _read_status
  │   →     raise RemoteDisconnected("Remote end closed connection without"
  └   → http.client.RemoteDisconnected: Remote end closed connection without response
```

Running locally, I can see the backtrace if I add `--log-mach -` to the test-wpt command, but that gives way more output than we want for our CI runs.

Blocks https://github.com/servo/servo/issues/34683.

### PR DESCRIPTION
**Pull request by mrobinson**
We were capturing test output (such as stack traces) by using the "test"
key in the data provided to the `process_output` log handler. This
doesn't work for WebDriver mode because the test runner runs in another
process entirely and it may reuse Servo executable instances for tests.

This change maps browser process output to tests using the "browser_pid"
key that is often provided while in WebDriver mode.

Testing: This modifies the test harness, so the tests are running tests.
Fixes: #39176

### CODE REVIEW

File: components/layout/flexbox/layout.rs
Comment (yezhizhen) [inline components/layout/flexbox/layout.rs:1]: You used this for testing stacktrace and accidentally committed.

Comment (mrobinson) [reply components/layout/flexbox/layout.rs:1]: Thanks. Fixed.

File: python/wpt/grouping_formatter.py [hunk 1]
```diff
@@ -336,9 +352,20 @@ def test_status(self, data: TestStatusData) -> None:
...
     def process_output(self, data: ProcessOutputData) -> None:
+        # In non-WebDriver mode the output might be directly associated with a test.
         if "test" in data:
             self.test_output[data["test"]] += data["data"] + "\n"
 
+        # In WebDriver mode we have to map from the browser process output to the test
+        # that was currently running at that time.
+        #
+        # There is often also a "pid" key, but that refers to the process that this
+        # Python code is running in. We want the process that actually had the output
```
Comment (yezhizhen) [inline python/wpt/grouping_formatter.py:363]: I think the "pid" below is already the `browser_pid` but not runner pid? Otherwise it simplify won't work.

Comment (mrobinson) [reply python/wpt/grouping_formatter.py:363]: Yes, that's right. the `pid` local variable (`data["process"]`) is equivalent to `browser_pid`, but `data["pid"`] is not equivalent to `browser_pid`. I'm happy to change the name of `pid` variable if you think this is confusing.

Comment (yezhizhen) [reply python/wpt/grouping_formatter.py:363]: Oh thanks for clarification. Now I understand the comment!

**Review by yezhizhen — APPROVED** [review]

**Comment by mrobinson** [comment]
@yezhizhen Thank you for the review!
