### PR TITLE
Fully implement request constructor body handling

### LINKED ISSUE #39448: Request body for aborted fetch is never canceled
This is tested by https://github.com/servo/servo/blob/1728ad5b01d657939c6283df3d218947238ba0d4/tests/wpt/tests/fetch/api/abort/general.any.js#L203-L218 .

This fails because `fetch(request)` creates a new Request object using the provided request as the input, and we haven't implemented the steps that set the request body object correctly:
https://github.com/servo/servo/blob/1728ad5b01d657939c6283df3d218947238ba0d4/components/script/dom/request.rs#L583-L588

The original request has a ReadableStream body object, but when the new request checks whether the provided signal is aborted, there's no body stream present:
https://github.com/servo/servo/blob/1728ad5b01d657939c6283df3d218947238ba0d4/components/script/fetch.rs#L207-L223
https://github.com/servo/servo/blob/1728ad5b01d657939c6283df3d218947238ba0d4/components/script/fetch.rs#L154-L159

I confirmed in lldb that ReadableStream::cancel is never called in this test.

### PR DESCRIPTION
**Pull request by TimvdLippe**
This aligns the implementation with the spec, where both input body and init body are now set. In doing so, it fixes a fetch abort test, since the stream was missing for the input body.

It also introduces the `unusable` method, as that's the one the spec uses. The other two getters no longer exist in the spec.

Fixes #39448

### CODE REVIEW

File: components/script/dom/request.rs [hunk 1]
```diff
@@ -419,46 +419,43 @@ impl Request {
         r.request.borrow_mut().headers = r.Headers(can_gc).get_headers_list();
 
         // Step 34. Let inputBody be input’s request’s body if input is a Request object; otherwise null.
-        let mut input_body = if let RequestInfo::Request(ref mut input_request) = input {
+        let input_body = if let RequestInfo::Request(ref mut input_request) = input {
             let mut input_request_request = input_request.request.borrow_mut();
+            r.body_stream.set(input_request.body().as_deref());
```
Comment (TimvdLippe) [inline components/script/dom/request.rs:424]: This was the missing line. After I had updated the whole constructor to be aligned with the spec, the test still wasn't working. Then I discovered that for `init` we were correctly setting the stream, but for `input` we weren't.

File: components/script/dom/request.rs [hunk 2]
```diff
@@ -750,16 +755,18 @@ impl RequestMethods<crate::DomTypeHolder> for Request {
 }
 
 impl BodyMixin for Request {
-    fn is_disturbed(&self) -> bool {
+    fn is_body_used(&self) -> bool {
```
Comment (Taym95) [inline components/script/dom/request.rs:758]: but readable stream has `disturbed`. this should be `is_disturbed `, any reason why this changed?

Comment (Taym95) [reply components/script/dom/request.rs:758]: Ah I see https://fetch.spec.whatwg.org/#dom-body-bodyused

**Review by jdm — APPROVED** [review]
Very nice cleanup!
