### PR TITLE
Fix serialization of namespace and universal selectors

### LINKED ISSUE #16017: Incorrect serialization of :not(*)
Testcase (in stylo; I'm not sure how to get at this in servo proper):

    <style>
      :not(*) {}
    </style>
    <script>
      alert(document.styleSheets[0].cssRules[0].selectorText);
    </script>

This alerts `:not()` which is not a valid selector.

### LINKED ISSUE #16020: Incorrect serialization of wildcard-namespace type selectors when there is a default namespace
Testcase (in stylo; I'm not sure how to get at this in servo proper):

    <!DOCTYPE html>
    <style>
      @namespace url(foo);
      *|a {}
    </style>
    <script>
      alert(document.styleSheets[0].cssRules[1].selectorText);
    </script>

This alerts `a` which is not the same selector as `*|a` in this case.

### PR DESCRIPTION
**Pull request by SimonSapin**
Fix #16017
Fix #16020

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16890)

### CODE REVIEW

File: components/style/stylist.rs [hunk 1]
```diff
@@ -1366,9 +1366,20 @@ impl SelectorMap<Rule> {
 
         let mut rules_list = vec![];
         for rule in self.other.iter() {
-            if rule.selector.inner.complex.iter_raw().next().is_none() {
-                rules_list.push(rule.to_applicable_declaration_block(cascade_level));
+            let mut iter = rule.selector.inner.complex.iter_raw();
+            match iter.next() {
```
Comment (emilio) [inline components/style/stylist.rs]: can you move it to a method in `Selector`? I'm also tweaking this code for the pseudo-element things. Also, it might look cleaner that way.

Comment (SimonSapin) [inline components/style/stylist.rs]: Done (in a separate commit).

**Review by emilio — APPROVED** [review]
r=me, with the `Combinator` bit either explained, or fixed.

**Comment by emilio** [comment]
Also, presumably a Gecko try run would be nice :)

**Comment by SimonSapin** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=a94e5188bdb08ab61b1bd4e8bb1fa6de4f5daf67

**Comment by SimonSapin** [comment]
> https://treeherder.mozilla.org/#/jobs?repo=try&revision=a94e5188bdb08ab61b1bd4e8bb1fa6de4f5daf67

```
TEST-UNEXPECTED-FAIL | layout/style/test/test_namespace_rule.html | failures in this test - expected 16 failures but got 8 [log…]
TEST-UNEXPECTED-FAIL | layout/style/test/test_selectors.html | failure pattern `:not()` in this test - expected 8 failures but got 0 [log…]
TEST-UNEXPECTED-FAIL | layout/style/test/test_selectors.html | failure pattern `:not(html|)` in this test - expected 1 failures but got 0 [log…]
TEST-UNEXPECTED-FAIL | layout/style/test/test_selectors.html | failure pattern `reserialization of *|a` in this test - expected 6 failures but got 0 [log…]
TEST-UNEXPECTED-FAIL | layout/style/test/test_selectors.html | failure pattern `this_better_be_unvisited` in this test - expected 1 failures but got 0 [log…] 
```

**Comment by SimonSapin** [comment]
@bors-servo p=2

so I can push expectation updates tonight.

**Comment by emilio** [comment]
@bors-servo retry

 * `mach package`?

**Comment by emilio** [comment]
@bors-servo p=10

 * I want to land my pseudo stuff after this.

**Comment by SimonSapin** [comment]
Previous failure was #16644.

**Comment by jdm** [comment]
@bors-servo: retry
* #16901

**Comment by heycam** [comment]
I landed the expectation changes: https://hg.mozilla.org/integration/autoland/rev/692a837347e3544cd7d1b86a63775ff5255caf7a
