### PR TITLE
Changed return value of GetActiveCues

### LINKED ISSUE #22706: Intermittent timeout in /html/semantics/embedded-content/media-elements/track/track-element/track-active-cues.html
```

  ▶ OK [expected TIMEOUT] /html/semantics/embedded-content/media-elements/track/track-element/track-active-cues.html

  ▶ Unexpected subtest result in /html/semantics/embedded-content/media-elements/track/track-element/track-active-cues.html:
  │ FAIL [expected TIMEOUT] Ensure that no text track cues are active after the video is unloaded
  │   → trackElement.track.activeCues is null
  │ 
  │ eventCallback@http://web-platform.test:8000/html/semantics/embedded-content/media-elements/track/track-element/track-active-cues.html:13:13
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1566:20
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1590:20
```

### PR DESCRIPTION
**Pull request by aditj**
Return an empty TextTrackCueList rather than Some inside the GetActiveCues.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [X] These changes fix #22706 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22730)

### CODE REVIEW

File: components/script/dom/texttrack.rs [hunk 1]
```diff
@@ -112,9 +112,7 @@ impl TextTrackMethods for TextTrack {
 
     // https://html.spec.whatwg.org/multipage/#dom-texttrack-activecues
     fn GetActiveCues(&self) -> Option<DomRoot<TextTrackCueList>> {
-        // XXX implement active cues logic
-        //      https://github.com/servo/servo/issues/22314
```
Comment (ferjm) [inline components/script/dom/texttrack.rs]: This comment is still valid. Do not remove it, please.

**Review by ferjm — CHANGES_REQUESTED** [review]

**Review by ferjm — APPROVED** [review]
Looks good. This is ready to merge after squashing the commits. Thanks!

**Comment by aditj** [comment]
> Looks good. This is ready to merge after squashing the commits. Thanks!

Ya I was trying that , is there any way I can squash commits of a remote branch(which has not been edited locally) ?

**Comment by ferjm** [comment]
`git rebase -i HEAD~2` should open the interactive rebase tool in your default text editor. Substitute the `pick` word before the second commit by an `s` or `squash`, save and exit.
