### PR TITLE
script: Notify embedder coalesced events to resolve potential WebDriver deadlock

### LINKED ISSUE #43136: Need to replace `input_id` when coalescing existing input event to unblock the thread
**Describe the bug:**
I've been intensively writing WebDriver input events with duration for past few months.
Sometimes, the test just randomly TIMEOUT.
Previously it is just mousemove, but now it happens for Wheel too, seems to be after ##43074.

The problem is, when we replace existing event,
https://github.com/servo/servo/blob/6f15489be65b9acb38e162ac0f4e734bc5fae84b/components/script/dom/document_event_handler.rs#L231, we did not replace the `input_id`.

This is important, because we synchronously block the thread for last event: https://github.com/servo/servo/blob/6f15489be65b9acb38e162ac0f4e734bc5fae84b/components/webdriver_server/lib.rs#L497-L503

### PR DESCRIPTION
**Pull request by yezhizhen**
Notify embedder the coalesced wheel/mousemove event.

We also stop cloning every single entry in `pending_input_event`.

Testing: This should unblock the potential WebDriver thread deadlock
when receiving simultaneous wheel or pointer inputs from multiple sources.
We added a new test that stably deadlock on https://github.com/servo/servo/commit/74c16ffd8aa7909c55fa70d6098cd745651ff791.
Firefox/Safari/Chrome all pass the new test.
Fixes: https://github.com/servo/servo/issues/43136#issuecomment-4031702204

### CODE REVIEW

**Comment by yezhizhen** [comment]
> Testing: ?. This should unblock the potential WebDriver thread deadlock,
when we have two sources of wheel/pointer input.

We can add a test for this that stably deadlocks.

File: components/shared/embedder/input_events.rs [hunk 1]
```diff
@@ -33,6 +33,8 @@ bitflags! {
         /// behavior (such as keybindings) when the WebView has already consumed the event for its
         /// own purpose.
         const Consumed = 1 << 1;
+        /// Whether or not this input event is coalesced in script.
+        const Coalesced = 1 << 2;
```
Comment (mrobinson) [inline components/shared/embedder/input_events.rs]: I don't think we want to expose this to the API actually, as this is an internal implementation detail of Servo. Instead each event should have the same result.

File: components/script/dom/document_event_handler.rs [hunk 2]
```diff
@@ -277,55 +296,84 @@ impl DocumentEventHandler {
...
+        // event or fire events later. We have to make a good decision about what to
+        // return to the embedder when that happens.
+        for event in pending_input_events {
+            // Insert coalesced [`InputEventId`]s that occurred BEFORE the current event processing.
+            match event.event.event {
+                InputEvent::MouseMove(_) => {
+                    input_event_outcomes.extend(coalesced_move_event_ids.drain(..).map(|id| {
+                        InputEventOutcome {
+                            id,
+                            result: Default::default(),
```
Comment (mrobinson) [inline components/script/dom/document_event_handler.rs]: Hrm. The result should match the result we get for the `MouseMove` event below though. Maybe wait until you are processing the `MouseMove` event below (line 343) and then pussh an outcome for each of the coalesced ids? I think we can do the same for wheel events.

Comment (yezhizhen) [reply components/script/dom/document_event_handler.rs]: Oh now I get what you mean by 
> each event should have the same result.

File: components/script/dom/document_event_handler.rs [hunk 3]
```diff
@@ -150,8 +150,19 @@ pub(crate) struct DocumentEventHandler {
     pending_input_events: DomRefCell<Vec<ConstellationInputEvent>>,
     /// The index of the last mouse move event in the pending input events queue.
     mouse_move_event_index: DomRefCell<Option<usize>>,
+    /// The [`InputEventId`]s of mousemove events that have been coalesced.
+    #[no_trace]
+    #[ignore_malloc_size_of = "InputEventId contains data from outside crates"]
+    coalesced_move_event_ids: DomRefCell<Vec<InputEventId>>,
     /// The index of the last wheel event in the pending input events queue.
+    /// This is non-standard behaviour.
+    /// According to <https://www.w3.org/TR/pointerevents/#dfn-coalesced-events>,
```
Comment (mrobinson) [inline components/script/dom/document_event_handler.rs:159]: Oh, I had no idea this was in the specification. I guess we are going to have to expose these events somehow.

**Review by mrobinson — APPROVED** [review]

File: components/script/dom/document_event_handler.rs (hunk 3 above)
Comment (yezhizhen) [reply components/script/dom/document_event_handler.rs:159]: Yeah. These are supposed to be a list of `PointerEvent`s, accessed through [getCoalescedEvents()](https://www.w3.org/TR/pointerevents/#dom-pointerevent-getcoalescedevents) in the fired `PointerEvent`.
We need to store extra events tho. 

Personally, I hope we **don't rush this** for performance consideration :|

Comment (yezhizhen) [reply components/script/dom/document_event_handler.rs:159]: I guess it is needed for things like shooting game/drawing.. Which should not be our current concern.
