### PR TITLE
layout: capitalize string for `TextTransformCase::Capitalize` in `fn rendered_text_collection_steps`

### LINKED ISSUE #37469: `text-transform: capitalize` does not change the `innerText` despite correct rendered text
**Describe the bug:**
The rendered text is correct, but `innerText()` is not correct.

Blocks WebDriver Conformance Test
 https://github.com/servo/servo/blob/c74a422e4cc97ceb48718b9e2f995ce294bcacec/tests/wpt/tests/webdriver/tests/classic/get_element_text/get.py#L103

**To Reproduce:**
```html
<!-- line break using <br> -->
<a id="multiline" href="#">First line<br>Second line</a>
<br>
<!-- capitalize -->
<a id="capitalize" href="#" style="text-transform: capitalize;">foo-bar</a>
<br>
<!-- uppercase -->
<a id="uppercase" href="#" style="text-transform: uppercase;">lowercase text</a>

<script>
  // Get all anchor elements and log their textContent to the console.
  document.querySelectorAll('a').forEach(function (anchor) {
    console.log(
      anchor.id + " innerText:",
      JSON.stringify(anchor.innerText)
    );
  });
</script>
```

**Platform:**
All.

### PR DESCRIPTION
**Pull request by yezhizhen**
Previously, `rendered_text_collection_steps` ignores `TextTransformCase::Capitalize` due to limitation of iterator. Now we handle the case outside.

Testing: Added a new test as not covered by existing wpt-test, except for the indirectly related WebDriver test. 
`./mach test-wpt -r tests\wpt\tests\webdriver\tests\classic\get_element_text\get.py --product servodriver`

Fixes: #37469

### CODE REVIEW

**Comment by yezhizhen** [comment]
cc @xiaochengh

File: components/layout/query.rs [hunk 1]
```diff
@@ -783,6 +784,11 @@ fn rendered_text_collection_steps(
                 )
                 .collect();
 
+                // Since iterator for capitalize not doing anything, we must handle it outside here
+                if TextTransformCase::Capitalize == style.clone_text_transform().case() {
+                    transformed_text = capitalize_string(&transformed_text, true);
+                }
```
Comment (Loirooriol) [inline components/layout/query.rs:791]: No need to do `style.clone_text_transform().case()` again

```rs
                let text_transform = style.clone_text_transform().case();
                let mut transformed_text: String =
                    TextTransformation::new(with_white_space_rules_applied, text_transform)
                        .collect();

                // Since iterator for capitalize not doing anything, we must handle it outside here
                if text_transform == TextTransformCase::Capitalize {
                    transformed_text = capitalize_string(&transformed_text, true);
                }
```

**Review by Loirooriol — APPROVED** [review]

File: components/layout/query.rs (hunk 1 above)
Comment (yezhizhen) [reply components/layout/query.rs:791]: Thanks! Also I wanna ask, for `capitalize_string`, I am just using `true` as parameter. In what case would that fail?

Comment (Loirooriol) [reply components/layout/query.rs:791]: Ah, yes, this is wrong:

```html
<!DOCTYPE html>
aaa<span style="text-transform: capitalize">bbb</span>ccc
<hr>
<script>
document.write(document.querySelector("span").innerText);
</script>
```

**Review by Loirooriol — CHANGES_REQUESTED** [review]
It would be good if you can fix the case of the element not starting at a word boundary. And add test coverage

File: components/layout/query.rs (hunk 1 above)
Comment (yezhizhen) [reply components/layout/query.rs:791]: I am not sure how to do this properly in `query.rs`. Can you push a commit for this?

Comment (Loirooriol) [reply components/layout/query.rs:791]: Yeah, seems a bit tricky. I guess it's fine to leave it for a follow-up, but at least add some test coverage and a TODO.

**Review by Loirooriol — APPROVED** [review]
