### PR TITLE
layout: Stop call normal block size assignment for flex container

### LINKED ISSUE #14813: Flexbox assertion failure on "Do you want to use HTML Gmail?" page
Follow the steps in #14782 with the patch from #14480 applied to reproduce this.
```
assertion failed: !self.is_inline_flex_item() (thread <unnamed>, at /Users/jdm/src/servo/components/layout/block.rs:1490)
stack backtrace:
   0:        0x1092855b1 - backtrace::backtrace::trace::hf69d5756c40bafc7
   1:        0x109285c58 - backtrace::capture::Backtrace::new::h92e5f83ad3bb233c
   2:        0x108f1c4fc - servo::main::{{closure}}::hf6443ebf81e66199
   3:        0x10e521273 - std::panicking::rust_panic_with_hook::h3e771863e3ed8403
   4:        0x10a082573 - std::panicking::begin_panic::h94258923a88c8674
   5:        0x10a1a5e94 - layout::block::BlockFlow::assign_inline_position_for_formatting_context::hdfa4488a6f343e76
   6:        0x10a1a9809 - <layout::block::BlockFlow as layout::flow::Flow>::assign_block_size_for_inorder_child_if_necessary::h21112feff39fe6dc
   7:        0x10a1e45e7 - <layout::flex::FlexFlow as layout::flow::Flow>::assign_block_size::h53a93f40ecba6b0e
   8:        0x10a24ff8b - <layout::traversal::AssignBSizes<'a> as layout::flow::PostorderFlowTraversal>::process::h3477b9c360ab6b67
   9:        0x10a226a18 - layout::parallel::ParallelPostorderFlowTraversal::run_parallel::h02750156af966f8b
  10:        0x10a227437 - layout::parallel::assign_block_sizes_and_store_overflow::h16cf9d6b5c647ed0
  11:        0x10a2270a3 - <layout::traversal::AssignISizes<'a> as layout::parallel::ParallelPreorderFlowTraversal>::run_parallel::ha7bd8211f93032e9
  12:        0x10a227394 - layout::parallel::assign_inline_sizes::h9330b2f2712555d8
  13:        0x10a226c63 - layout::parallel::ParallelPreorderFlowTraversal::run_parallel_helper::{{closure}}::h0a273d197733753e
  14:        0x10a101448 - rayon::scope::Scope::execute_job_closure::{{closure}}::h031fa7c9043cd650
  15:        0x10a18d19a - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::h716a976925ce282d
  16:        0x10a0837b3 - std::panicking::try::do_call::h125fe1a12eaa9148
  17:        0x10e52214a - __rust_maybe_catch_panic
  18:        0x10a082a22 - std::panicking::try::h41fe2cb324b77397
  19:        0x10a08227e - std::panic::catch_unwind::h5d8e17f3aa9e3536
  20:        0x10a101fee - rayon::unwind::halt_unwinding::h7031a2c78032c25c
  21:        0x10a101282 - rayon::scope::Scope::execute_job_closure::hfbdc8bb7889dd988
  22:        0x10a100e56 - rayon::scope::Scope::execute_job::h1a57802368286286
  23:        0x10a101963 - rayon::scope::Scope::spawn::{{closure}}::h119c5db8ff12409d
  24:        0x10a134550 - <rayon::job::HeapJob<BODY> as rayon::job::Job>::execute::hcd89fb7223a32830
  25:        0x10df10daa - rayon::job::JobRef::execute::h1b189c9197a8f3d2
  26:        0x10df128a0 - rayon::thread_pool::WorkerThread::pop_spawned_jobs::heff48614893112f8
  27:        0x10df12a8c - rayon::thread_pool::WorkerThread::steal_until::he91d67c8f01a52bf
  28:        0x10df1108a - rayon::scope::Scope::steal_till_jobs_complete::h68c6cfc741caf4f6
  29:        0x10a101c53 - rayon::scope::scope::h1e28c08a4ee87f0a
  30:        0x10a227a74 - layout::parallel::traverse_flow_tree_preorder::{{closure}}::h514ebf367cc99d85
  31:        0x10a17bd7f - <rayon::job::StackJob<L, F, R> as rayon::job::Job>::execute::{{closure}}::hb6de5ad01024b682
  32:        0x10a18d0d5 - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::h2ebeb3b712fb7246
  33:        0x10a083b91 - std::panicking::try::do_call::hc5159f07e6d1e21d
  34:        0x10e52214a - __rust_maybe_catch_panic
  35:        0x10a082e4d - std::panicking::try::h70bb178a65a01cc5
  36:        0x10a082469 - std::panic::catch_unwind::hf5881981ba25f10a
  37:        0x10a101ed9 - rayon::unwind::halt_unwinding::h554713cdd6382638
  38:        0x10a17b62f - <rayon::job::StackJob<L, F, R> as rayon::job::Job>::execute::h8cd0ddee93b96cf8
  39:        0x10df10daa - rayon::job::JobRef::execute::h1b189c9197a8f3d2
  40:        0x10df131cc - rayon::thread_pool::main_loop::hf84e0044726bb803
  41:        0x10df11a0d - rayon::thread_pool::Registry::new::{{closure}}::h5e2e1b92eee5b257
  42:        0x10df0ebaa - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::hb25ca362fdf20e26
  43:        0x10defeaf5 - std::panicking::try::do_call::h978cb777aa487beb
  44:        0x10e52214a - __rust_maybe_catch_panic
  45:        0x10defe7e2 - std::panicking::try::hac2c6307154f3dd2
  46:        0x10defd6f6 - std::panic::catch_unwind::h05d886dbc7a696ba
  47:        0x10defe3ed - std::thread::Builder::spawn::{{closure}}::hf0f15a624fbfcb57
  48:        0x10df079f3 - <F as alloc::boxed::FnBox<A>>::call_box::h3c4f2e6bf53138c7
  49:        0x10e5201f4 - std::sys::imp::thread::Thread::new::thread_start::h5f22426d80277e16
  50:     0x7fff8e409898 - _pthread_body
  51:     0x7fff8e409729 - _pthread_start
```

### PR DESCRIPTION
**Pull request by stshine**
No need to call the `assign_block_size_block_base()` method of normal block in flex.rs since it is implemented for CSS2.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14813 (github issue number if applicable).

- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18175)

### CODE REVIEW

**Comment by mbrubeck** [comment]
The WPT failures look like they might be spurious, but these CSS failures do not:

http://build.servo.org/builders/mac-rel-css1/builds/1261

```
Ran 3262 tests finished in 534.0 seconds.
  • 3104 ran as expected. 114 tests skipped.
  • 143 tests failed unexpectedly
  • 2 tests timed out unexpectedly
  • 13 tests passed unexpectedly
```

<details>

```
Tests with unexpected results:
  ▶ TIMEOUT [expected PASS] /compositing-1_dev/html/mix-blend-mode-animation.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 17.2.0-devel

  ▶ FAIL [expected TIMEOUT] /css-animations-1_dev/html/vh-interpolate-pct.htm
  └   → /css-animations-1_dev/html/vh-interpolate-pct.htm f17b571b709c853a05ae9c0f417a1e422833e879
/css-animations-1_dev/html/reference/all-green.htm 16698156583755674f3837b45ba940d68a1d3b1f
Testing f17b571b709c853a05ae9c0f417a1e422833e879 == 16698156583755674f3837b45ba940d68a1d3b1f

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flex-container-margin.htm
  └   → /css-flexbox-1_dev/html/flex-container-margin.htm 6b8e794813d7871fa7f87b100ec4291ed3dbe9ed
/css-flexbox-1_dev/html/reference/flex-container-margin-ref.htm b5d236c5a41ebb6d5f31250673f1c8b9d64ad65f
Testing 6b8e794813d7871fa7f87b100ec4291ed3dbe9ed == b5d236c5a41ebb6d5f31250673f1c8b9d64ad65f

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox-abspos-child-001b.htm
  └   → /css-flexbox-1_dev/html/flexbox-abspos-child-001b.htm 23b755622cc81841a23cc8431a6546dfb1401c66
/css-flexbox-1_dev/html/reference/flexbox-abspos-child-001-ref.htm 8fa35f8cb0c92b4078baa9498f6e8e07e5e4f703
Testing 23b755622cc81841a23cc8431a6546dfb1401c66 == 8fa35f8cb0c92b4078baa9498f6e8e07e5e4f703

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox-abspos-child-001a.htm
  └   → /css-flexbox-1_dev/html/flexbox-abspos-child-001a.htm d25dd536511b25414cb93398a0e830f72c51ba82
/css-flexbox-1_dev/html/reference/flexbox-abspos-child-001-ref.htm 8fa35f8cb0c92b4078baa9498f6e8e07e5e4f703
Testing d25dd536511b25414cb93398a0e830f72c51ba82 == 8fa35f8cb0c92b4078baa9498f6e8e07e5e4f703

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox-baseline-empty-001b.htm
  └   → /css-flexbox-1_dev/html/flexbox-baseline-empty-001b.htm 30f38cf81c98d2c3bd7459f91f4afc7e3bb3c59b
/css-flexbox-1_dev/html/reference/flexbox-baseline-empty-001-ref.htm 0bb5802fafd7db9d2866a0b368a42be88776c719
Testing 30f38cf81c98d2c3bd7459f91f4afc7e3bb3c59b == 0bb5802fafd7db9d2866a0b368a42be88776c719

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox-flex-wrap-horiz-001.htm
  └   → /css-flexbox-1_dev/html/flexbox-flex-wrap-horiz-001.htm ee9c4fc4ff72bad1b6d047c6f3e56f2f0b1729e9
/css-flexbox-1_dev/html/reference/flexbox-flex-wrap-horiz-001-ref.htm a853688202d29fb9f2c752bec1986f8e9e4e1e8b
Testing ee9c4fc4ff72bad1b6d047c6f3e56f2f0b1729e9 == a853688202d29fb9f2c752bec1986f8e9e4e1e8b

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox-items-as-stacking-contexts-002.htm
  └   → /css-flexbox-1_dev/html/flexbox-items-as-stacking-contexts-002.htm 27cff23fc4b2d9d9ad5eb543edae83f989906aa5
/css-flexbox-1_dev/html/reference/flexbox-items-as-stacking-contexts-002-ref.htm 9476e4e2dfec8b896846f5af7b157f31830cb39a
Testing 27cff23fc4b2d9d9ad5eb543edae83f989906aa5 == 9476e4e2dfec8b896846f5af7b157f31830cb39a

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox-margin-auto-horiz-002.htm

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox-mbp-horiz-003-reverse.htm
  └   → /css-flexbox-1_dev/html/flexbox-mbp-horiz-003-reverse.htm 73dadd9e392955aea9451ec7eb409acd63558d90
/css-flexbox-1_dev/html/reference/flexbox-mbp-horiz-003-reverse-ref.htm 9ebe9e3fc406fe7454ab8fb7a89da014a4dcbd9d
Testing 73dadd9e392955aea9451ec7eb409acd63558d90 == 9ebe9e3fc406fe7454ab8fb7a89da014a4dcbd9d

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox-mbp-horiz-003.htm
  └   → /css-flexbox-1_dev/html/flexbox-mbp-horiz-003.htm ae266f698b15821991401db77bbb535c704060e2
/css-flexbox-1_dev/html/reference/flexbox-mbp-horiz-003-ref.htm 34625414053f2c0dad24eefdb888fc5a424f3326
Testing ae266f698b15821991401db77bbb535c704060e2 == 34625414053f2c0dad24eefdb888fc5a424f3326

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox-overflow-vert-004.htm

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox-single-line-clamp-2.htm
  └   → /css-flexbox-1_dev/html/flexbox-single-line-clamp-2.htm 70c826a5b21a5d73957c1eefba2c91a879f7e019
/css-flexbox-1_dev/html/reference/flexbox-single-line-clamp-2-ref.htm d031d55bdfc0cc537ae0e5d66ee648272fdd778e
Testing 70c826a5b21a5d73957c1eefba2c91a879f7e019 == d031d55bdfc0cc537ae0e5d66ee648272fdd778e

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox-writing-mode-007.htm
  └   → /css-flexbox-1_dev/html/flexbox-writing-mode-007.htm 8ec161896b914a769543cf8a30e5925d75fe4d2d
/css-flexbox-1_dev/html/reference/flexbox-writing-mode-007-ref.htm 99f0cfa4a0cdc1e9edc842c78abb6bc5a91b03b0
Testing 8ec161896b914a769543cf8a30e5925d75fe4d2d == 99f0cfa4a0cdc1e9edc842c78abb6bc5a91b03b0

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-content-center.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-content-center.htm 250004a64acbd904fbf545ea2bf5b47540f84c6c
/css-flexbox-1_dev/html/reference/flexbox_align-content-center-ref.htm d871a59bdcbfe7342f1092107d9440a496821051
Testing 250004a64acbd904fbf545ea2bf5b47540f84c6c == d871a59bdcbfe7342f1092107d9440a496821051

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-content-flexend.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-content-flexend.htm 58a1c0d46604c9c01ed983b7d7f4aa2fe49822b7
/css-flexbox-1_dev/html/reference/flexbox_align-content-flexend-ref.htm 4bf72129eb85d0fbd567f4c74500d506036636fe
Testing 58a1c0d46604c9c01ed983b7d7f4aa2fe49822b7 == 4bf72129eb85d0fbd567f4c74500d506036636fe

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-content-flexstart.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-content-flexstart.htm 75fae6836020006325cdd8240e601a8016528041
/css-flexbox-1_dev/html/reference/flexbox_align-content-flexstart-ref.htm cbd793cf9a2219a77879680d54cf77641c222720
Testing 75fae6836020006325cdd8240e601a8016528041 == cbd793cf9a2219a77879680d54cf77641c222720

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-content-spacearound.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-content-spacearound.htm f0ff3bb382acfaa5664a229e93bf775d3a7464f3
/css-flexbox-1_dev/html/reference/flexbox_align-content-spacearound-ref.htm a2a005c60a9040c78b7df4778d2762a83e5d48eb
Testing f0ff3bb382acfaa5664a229e93bf775d3a7464f3 == a2a005c60a9040c78b7df4778d2762a83e5d48eb

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-content-stretch-2.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-content-stretch-2.htm 79026f05aa8711818e3dd774d19e2b52a34f6035
/css-flexbox-1_dev/html/reference/flexbox_align-content-stretch-2-ref.htm 3116da04f0732391a0a01f0d837a62043e5614b4
Testing 79026f05aa8711818e3dd774d19e2b52a34f6035 == 3116da04f0732391a0a01f0d837a62043e5614b4

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-content-spacebetween.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-content-spacebetween.htm c3383b6447624e47e256b8e825c02d69d923d013
/css-flexbox-1_dev/html/reference/flexbox_align-content-spacebetween-ref.htm d95094db75fd4cbd3d4c013d4cebf445268cd527
Testing c3383b6447624e47e256b8e825c02d69d923d013 == d95094db75fd4cbd3d4c013d4cebf445268cd527

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-content-stretch.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-content-stretch.htm 277738ba6288b55880330aa90f34e4977c130dc9
/css-flexbox-1_dev/html/reference/flexbox_align-content-stretch-ref.htm c9df81f374387415e7dd8549dee619946da5b30f
Testing 277738ba6288b55880330aa90f34e4977c130dc9 == c9df81f374387415e7dd8549dee619946da5b30f

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-items-center-2.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-items-center-2.htm 97d1a0f6ef1943372a5b51d16d1cd8f0812f6a97
/css-flexbox-1_dev/html/reference/flexbox_align-items-center-2-ref.htm 36a6ac06642fd0f0ab9ad65fe270b9bbe2ae3284
Testing 97d1a0f6ef1943372a5b51d16d1cd8f0812f6a97 == 36a6ac06642fd0f0ab9ad65fe270b9bbe2ae3284

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-items-center.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-items-center.htm 41fc8609af4e31653482ab443add076a7738541d
/css-flexbox-1_dev/html/reference/flexbox_align-items-center-ref.htm ba06e8961b8945fcc19131978f9987aef793e069
Testing 41fc8609af4e31653482ab443add076a7738541d == ba06e8961b8945fcc19131978f9987aef793e069

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-items-flexend-2.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-items-flexend-2.htm 9202c4c9b97e3bbbd1fffe3747dd84c0686d0109
/css-flexbox-1_dev/html/reference/flexbox_align-items-flexend-2-ref.htm 1f4b75dab5164597fa760e5ec58a9f9f74cb4531
Testing 9202c4c9b97e3bbbd1fffe3747dd84c0686d0109 == 1f4b75dab5164597fa760e5ec58a9f9f74cb4531

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-items-flexend.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-items-flexend.htm 8e39e37a2c782e23ea61921a9f1183ad61166d32
/css-flexbox-1_dev/html/reference/flexbox_align-items-flexend-ref.htm ea2a36360637ae489b30298e5fbf3bfa4b64647d
Testing 8e39e37a2c782e23ea61921a9f1183ad61166d32 == ea2a36360637ae489b30298e5fbf3bfa4b64647d

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-items-flexstart-2.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-items-flexstart-2.htm 70ef00295344221f76d695613c8b626f505ebeb8
/css-flexbox-1_dev/html/reference/flexbox_align-items-flexstart-2-ref.htm 2178d5ae13c01852f365c9147c179da304640644
Testing 70ef00295344221f76d695613c8b626f505ebeb8 == 2178d5ae13c01852f365c9147c179da304640644

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-items-flexstart.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-items-flexstart.htm bc361b859544e0cb22d1997f8b47057fe0dc5a27
/css-flexbox-1_dev/html/reference/flexbox_align-items-flexstart-ref.htm 7bfba0fc8a1b3ff80aa7da301b1e932d88f6c61b
Testing bc361b859544e0cb22d1997f8b47057fe0dc5a27 == 7bfba0fc8a1b3ff80aa7da301b1e932d88f6c61b

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-items-stretch-2.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-items-stretch-2.htm b8a5fa28423ce6ddc216426c42ea7e5315943126
/css-flexbox-1_dev/html/reference/flexbox_align-items-stretch-2-ref.htm fab247e947d8e8f64dbb1c75c633b4e5c62ebcdb
Testing b8a5fa28423ce6ddc216426c42ea7e5315943126 == fab247e947d8e8f64dbb1c75c633b4e5c62ebcdb

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-items-stretch.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-items-stretch.htm 08c6d794f15d49e0eb8755458e6b0adad0b1673f
/css-flexbox-1_dev/html/reference/flexbox_align-items-stretch-ref.htm 3cbd666026439101bda623161ffce4ad4ee48c00
Testing 08c6d794f15d49e0eb8755458e6b0adad0b1673f == 3cbd666026439101bda623161ffce4ad4ee48c00

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-self-auto.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-self-auto.htm 8e39e37a2c782e23ea61921a9f1183ad61166d32
/css-flexbox-1_dev/html/reference/flexbox_align-self-auto-ref.htm ea2a36360637ae489b30298e5fbf3bfa4b64647d
Testing 8e39e37a2c782e23ea61921a9f1183ad61166d32 == ea2a36360637ae489b30298e5fbf3bfa4b64647d

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-self-baseline.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-self-baseline.htm b9b26e8795f2be36fe347f6a8fb7f5b976520cea
/css-flexbox-1_dev/html/reference/flexbox_align-self-baseline-ref.htm faabc81d06f2537fd97724106d6f187c1df4cfa9
Testing b9b26e8795f2be36fe347f6a8fb7f5b976520cea == faabc81d06f2537fd97724106d6f187c1df4cfa9

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-self-center.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-self-center.htm bb97e208979c12931417152b96d7bd33617cd2a4
/css-flexbox-1_dev/html/reference/flexbox_align-self-center-ref.htm f084bd6c7adfcbcb1c875aa9750caaaa5a1ebbb6
Testing bb97e208979c12931417152b96d7bd33617cd2a4 == f084bd6c7adfcbcb1c875aa9750caaaa5a1ebbb6

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-self-flexend.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-self-flexend.htm 01560b63f67bc18ccd038959b2388f0ba3473a07
/css-flexbox-1_dev/html/reference/flexbox_align-self-flexend-ref.htm 39ef7e0774a18c6f97408785e5164f5898679f67
Testing 01560b63f67bc18ccd038959b2388f0ba3473a07 == 39ef7e0774a18c6f97408785e5164f5898679f67

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-self-flexstart.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-self-flexstart.htm 077940960882ca5e05a3faa45b2623b12088efb3
/css-flexbox-1_dev/html/reference/flexbox_align-self-flexstart-ref.htm 2befe0125d2fe951d3a387487727db6c248a368b
Testing 077940960882ca5e05a3faa45b2623b12088efb3 == 2befe0125d2fe951d3a387487727db6c248a368b

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_align-self-stretch.htm
  └   → /css-flexbox-1_dev/html/flexbox_align-self-stretch.htm e352a561f12794ab63b171b43778f937f2123765
/css-flexbox-1_dev/html/reference/flexbox_align-self-stretch-ref.htm 37629fe2c94470e277337bb71ac31c36e288b33a
Testing e352a561f12794ab63b171b43778f937f2123765 == 37629fe2c94470e277337bb71ac31c36e288b33a

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_block.htm
  └   → /css-flexbox-1_dev/html/flexbox_block.htm 10e99b6146ed51b5cf707b4d9e0f548aa55c17b8
/css-flexbox-1_dev/html/reference/flexbox_empty-ref.htm 23b755622cc81841a23cc8431a6546dfb1401c66
Testing 10e99b6146ed51b5cf707b4d9e0f548aa55c17b8 == 23b755622cc81841a23cc8431a6546dfb1401c66

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_first-line.htm
  └   → /css-flexbox-1_dev/html/flexbox_first-line.htm 931cd451466ebccacd5613c0cca5ddc6d6a8b10b
/css-flexbox-1_dev/html/reference/flexbox_first-line-ref.htm c91069f8ccb551c13a27f77bc6f4c2619f7efadb
Testing 931cd451466ebccacd5613c0cca5ddc6d6a8b10b == c91069f8ccb551c13a27f77bc6f4c2619f7efadb

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-0-1-unitless-basis.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-0-1-unitless-basis.htm e0ae82b43e8e5f76bbfe00cea87c2d96ec399be2
/css-flexbox-1_dev/html/reference/flexbox_flex-unitless-basis-ref.htm 7352c8926fa43a0c04e4e1305472a4fd11538826
Testing e0ae82b43e8e5f76bbfe00cea87c2d96ec399be2 == 7352c8926fa43a0c04e4e1305472a4fd11538826

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-0-N-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-0-N-shrink.htm 0ace4c899640b251a28f693f9c92638c85eb3acc
/css-flexbox-1_dev/html/reference/flexbox_flex-0-0-N-shrink-ref.htm d9d24f7e007e0a62f33126c3fd08683ebf15a68c
Testing 0ace4c899640b251a28f693f9c92638c85eb3acc == d9d24f7e007e0a62f33126c3fd08683ebf15a68c

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-0-N-unitless-basis.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-0-N-unitless-basis.htm e0ae82b43e8e5f76bbfe00cea87c2d96ec399be2
/css-flexbox-1_dev/html/reference/flexbox_flex-unitless-basis-ref.htm 7352c8926fa43a0c04e4e1305472a4fd11538826
Testing e0ae82b43e8e5f76bbfe00cea87c2d96ec399be2 == 7352c8926fa43a0c04e4e1305472a4fd11538826

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-0-N.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-0-N.htm 776c01ef173fd2b9b82caca7f0f7b90eae32ccba
/css-flexbox-1_dev/html/reference/flexbox_flex-0-0-N-ref.htm d9ba18f35c5a48a8dedd6b3a8338567a056b7645
Testing 776c01ef173fd2b9b82caca7f0f7b90eae32ccba == d9ba18f35c5a48a8dedd6b3a8338567a056b7645

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-0-Npercent-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-0-Npercent-shrink.htm 8c56e5ebbb941450bc0ba6d294644b7174d466f3
/css-flexbox-1_dev/html/reference/flexbox_flex-0-0-Npercent-shrink-ref.htm 5ad2717c02fe17167baad244d9e1b2440a26f047
Testing 8c56e5ebbb941450bc0ba6d294644b7174d466f3 == 5ad2717c02fe17167baad244d9e1b2440a26f047

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-0-Npercent.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-0-Npercent.htm 72a75fa2155da71f88edef62bef549efd0b46b90
/css-flexbox-1_dev/html/reference/flexbox_flex-0-0-Npercent-ref.htm 7ff1394c8bdb4b8d86710bcd4d186c0ff37dba03
Testing 72a75fa2155da71f88edef62bef549efd0b46b90 == 7ff1394c8bdb4b8d86710bcd4d186c0ff37dba03

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-0-auto-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-0-auto-shrink.htm c547c348f4a94924f5545e47feb6de3d110d88ae
/css-flexbox-1_dev/html/reference/flexbox_flex-0-0-auto-shrink-ref.htm 5a92d8316fc8fc653ef0be699436ef8b68b5454d
Testing c547c348f4a94924f5545e47feb6de3d110d88ae == 5a92d8316fc8fc653ef0be699436ef8b68b5454d

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-0-auto.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-0-auto.htm e0ae82b43e8e5f76bbfe00cea87c2d96ec399be2
/css-flexbox-1_dev/html/reference/flexbox_flex-0-0-auto-ref.htm 7352c8926fa43a0c04e4e1305472a4fd11538826
Testing e0ae82b43e8e5f76bbfe00cea87c2d96ec399be2 == 7352c8926fa43a0c04e4e1305472a4fd11538826

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-1-1-unitless-basis.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-1-1-unitless-basis.htm e0ae82b43e8e5f76bbfe00cea87c2d96ec399be2
/css-flexbox-1_dev/html/reference/flexbox_flex-unitless-basis-ref.htm 7352c8926fa43a0c04e4e1305472a4fd11538826
Testing e0ae82b43e8e5f76bbfe00cea87c2d96ec399be2 == 7352c8926fa43a0c04e4e1305472a4fd11538826

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-1-N-unitless-basis.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-1-N-unitless-basis.htm e0ae82b43e8e5f76bbfe00cea87c2d96ec399be2
/css-flexbox-1_dev/html/reference/flexbox_flex-unitless-basis-ref.htm 7352c8926fa43a0c04e4e1305472a4fd11538826
Testing e0ae82b43e8e5f76bbfe00cea87c2d96ec399be2 == 7352c8926fa43a0c04e4e1305472a4fd11538826

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-1-N-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-1-N-shrink.htm 06006286b5abbc7470fd151ac149b23dac5f18d2
/css-flexbox-1_dev/html/reference/flexbox_flex-0-1-N-shrink-ref.htm 69114cdfc29aa2365fdf756e9c02d86789ab979a
Testing 06006286b5abbc7470fd151ac149b23dac5f18d2 == 69114cdfc29aa2365fdf756e9c02d86789ab979a

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-1-N.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-1-N.htm 776c01ef173fd2b9b82caca7f0f7b90eae32ccba
/css-flexbox-1_dev/html/reference/flexbox_flex-0-1-N-ref.htm d9ba18f35c5a48a8dedd6b3a8338567a056b7645
Testing 776c01ef173fd2b9b82caca7f0f7b90eae32ccba == d9ba18f35c5a48a8dedd6b3a8338567a056b7645

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-1-Npercent-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-1-Npercent-shrink.htm 06006286b5abbc7470fd151ac149b23dac5f18d2
/css-flexbox-1_dev/html/reference/flexbox_flex-0-1-Npercent-shrink-ref.htm 69114cdfc29aa2365fdf756e9c02d86789ab979a
Testing 06006286b5abbc7470fd151ac149b23dac5f18d2 == 69114cdfc29aa2365fdf756e9c02d86789ab979a

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-1-Npercent.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-1-Npercent.htm 72a75fa2155da71f88edef62bef549efd0b46b90
/css-flexbox-1_dev/html/reference/flexbox_flex-0-1-Npercent-ref.htm 7ff1394c8bdb4b8d86710bcd4d186c0ff37dba03
Testing 72a75fa2155da71f88edef62bef549efd0b46b90 == 7ff1394c8bdb4b8d86710bcd4d186c0ff37dba03

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-1-auto-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-1-auto-shrink.htm 680a1f64c52e4a598e0abd81398c2863d5bef118
/css-flexbox-1_dev/html/reference/flexbox_flex-0-1-auto-shrink-ref.htm bbcebf002a656df8f88b1cd18898acf357d4bed1
Testing 680a1f64c52e4a598e0abd81398c2863d5bef118 == bbcebf002a656df8f88b1cd18898acf357d4bed1

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-1-auto.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-1-auto.htm e0ae82b43e8e5f76bbfe00cea87c2d96ec399be2
/css-flexbox-1_dev/html/reference/flexbox_flex-0-1-auto-ref.htm 7352c8926fa43a0c04e4e1305472a4fd11538826
Testing e0ae82b43e8e5f76bbfe00cea87c2d96ec399be2 == 7352c8926fa43a0c04e4e1305472a4fd11538826

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-N-N-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-N-N-shrink.htm 06006286b5abbc7470fd151ac149b23dac5f18d2
/css-flexbox-1_dev/html/reference/flexbox_flex-0-N-N-shrink-ref.htm 69114cdfc29aa2365fdf756e9c02d86789ab979a
Testing 06006286b5abbc7470fd151ac149b23dac5f18d2 == 69114cdfc29aa2365fdf756e9c02d86789ab979a

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-N-N.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-N-N.htm 776c01ef173fd2b9b82caca7f0f7b90eae32ccba
/css-flexbox-1_dev/html/reference/flexbox_flex-0-N-N-ref.htm d9ba18f35c5a48a8dedd6b3a8338567a056b7645
Testing 776c01ef173fd2b9b82caca7f0f7b90eae32ccba == d9ba18f35c5a48a8dedd6b3a8338567a056b7645

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-N-Npercent-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-N-Npercent-shrink.htm 06006286b5abbc7470fd151ac149b23dac5f18d2
/css-flexbox-1_dev/html/reference/flexbox_flex-0-N-Npercent-shrink-ref.htm 69114cdfc29aa2365fdf756e9c02d86789ab979a
Testing 06006286b5abbc7470fd151ac149b23dac5f18d2 == 69114cdfc29aa2365fdf756e9c02d86789ab979a

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-N-Npercent.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-N-Npercent.htm 72a75fa2155da71f88edef62bef549efd0b46b90
/css-flexbox-1_dev/html/reference/flexbox_flex-0-N-Npercent-ref.htm 7ff1394c8bdb4b8d86710bcd4d186c0ff37dba03
Testing 72a75fa2155da71f88edef62bef549efd0b46b90 == 7ff1394c8bdb4b8d86710bcd4d186c0ff37dba03

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-N-auto-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-N-auto-shrink.htm 680a1f64c52e4a598e0abd81398c2863d5bef118
/css-flexbox-1_dev/html/reference/flexbox_flex-0-N-auto-shrink-ref.htm bbcebf002a656df8f88b1cd18898acf357d4bed1
Testing 680a1f64c52e4a598e0abd81398c2863d5bef118 == bbcebf002a656df8f88b1cd18898acf357d4bed1

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-N-auto.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-N-auto.htm e0ae82b43e8e5f76bbfe00cea87c2d96ec399be2
/css-flexbox-1_dev/html/reference/flexbox_flex-0-N-auto-ref.htm 7352c8926fa43a0c04e4e1305472a4fd11538826
Testing e0ae82b43e8e5f76bbfe00cea87c2d96ec399be2 == 7352c8926fa43a0c04e4e1305472a4fd11538826

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-0-auto.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-0-auto.htm 170db494ccd3de6c1c5acff3aa8e33e33c0a086f
/css-flexbox-1_dev/html/reference/flexbox_flex-initial-ref.htm 7749ce9a06445af8b914364664c5e5e6e937296f
Testing 170db494ccd3de6c1c5acff3aa8e33e33c0a086f == 7749ce9a06445af8b914364664c5e5e6e937296f

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-0-0-unitless.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-0-0-unitless.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-1-0-0-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-0-0.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-0-0.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-1-0-0-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-0-N-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-0-N-shrink.htm 0ace4c899640b251a28f693f9c92638c85eb3acc
/css-flexbox-1_dev/html/reference/flexbox_flex-1-0-N-shrink-ref.htm d9d24f7e007e0a62f33126c3fd08683ebf15a68c
Testing 0ace4c899640b251a28f693f9c92638c85eb3acc == d9d24f7e007e0a62f33126c3fd08683ebf15a68c

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-0-N.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-0-N.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-1-0-N-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-0-Npercent-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-0-Npercent-shrink.htm 8c56e5ebbb941450bc0ba6d294644b7174d466f3
/css-flexbox-1_dev/html/reference/flexbox_flex-1-0-Npercent-shrink-ref.htm 5ad2717c02fe17167baad244d9e1b2440a26f047
Testing 8c56e5ebbb941450bc0ba6d294644b7174d466f3 == 5ad2717c02fe17167baad244d9e1b2440a26f047

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-0-Npercent.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-0-Npercent.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-1-0-Npercent-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-0-auto-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-0-auto-shrink.htm c547c348f4a94924f5545e47feb6de3d110d88ae
/css-flexbox-1_dev/html/reference/flexbox_flex-1-0-auto-shrink-ref.htm 5a92d8316fc8fc653ef0be699436ef8b68b5454d
Testing c547c348f4a94924f5545e47feb6de3d110d88ae == 5a92d8316fc8fc653ef0be699436ef8b68b5454d

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-0-auto.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-0-auto.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-1-0-auto-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-0.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-0.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-1-0-0-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-1-0-unitless.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-1-0-unitless.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-1-1-0-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-1-0.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-1-0.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-1-1-0-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-1-N-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-1-N-shrink.htm 06006286b5abbc7470fd151ac149b23dac5f18d2
/css-flexbox-1_dev/html/reference/flexbox_flex-1-1-N-shrink-ref.htm 69114cdfc29aa2365fdf756e9c02d86789ab979a
Testing 06006286b5abbc7470fd151ac149b23dac5f18d2 == 69114cdfc29aa2365fdf756e9c02d86789ab979a

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-1-N.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-1-N.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-1-1-N-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-1-Npercent-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-1-Npercent-shrink.htm 06006286b5abbc7470fd151ac149b23dac5f18d2
/css-flexbox-1_dev/html/reference/flexbox_flex-1-1-Npercent-shrink-ref.htm 69114cdfc29aa2365fdf756e9c02d86789ab979a
Testing 06006286b5abbc7470fd151ac149b23dac5f18d2 == 69114cdfc29aa2365fdf756e9c02d86789ab979a

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-1-Npercent.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-1-Npercent.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-1-1-Npercent-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-1-auto-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-1-auto-shrink.htm 680a1f64c52e4a598e0abd81398c2863d5bef118
/css-flexbox-1_dev/html/reference/flexbox_flex-1-1-auto-shrink-ref.htm bbcebf002a656df8f88b1cd18898acf357d4bed1
Testing 680a1f64c52e4a598e0abd81398c2863d5bef118 == bbcebf002a656df8f88b1cd18898acf357d4bed1

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-1-auto.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-1-auto.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-1-1-auto-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-1.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-1.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-1-1-0-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-N-0-unitless.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-N-0-unitless.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-1-N-0-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-N-0.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-N-0.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-1-N-0-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-N-N-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-N-N-shrink.htm 06006286b5abbc7470fd151ac149b23dac5f18d2
/css-flexbox-1_dev/html/reference/flexbox_flex-1-N-N-shrink-ref.htm 69114cdfc29aa2365fdf756e9c02d86789ab979a
Testing 06006286b5abbc7470fd151ac149b23dac5f18d2 == 69114cdfc29aa2365fdf756e9c02d86789ab979a

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-N-N.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-N-N.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-1-N-N-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-N-Npercent-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-N-Npercent-shrink.htm 06006286b5abbc7470fd151ac149b23dac5f18d2
/css-flexbox-1_dev/html/reference/flexbox_flex-1-N-Npercent-shrink-ref.htm 69114cdfc29aa2365fdf756e9c02d86789ab979a
Testing 06006286b5abbc7470fd151ac149b23dac5f18d2 == 69114cdfc29aa2365fdf756e9c02d86789ab979a

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-N-Npercent.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-N-Npercent.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-1-N-Npercent-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-N-auto-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-N-auto-shrink.htm 680a1f64c52e4a598e0abd81398c2863d5bef118
/css-flexbox-1_dev/html/reference/flexbox_flex-1-N-auto-shrink-ref.htm bbcebf002a656df8f88b1cd18898acf357d4bed1
Testing 680a1f64c52e4a598e0abd81398c2863d5bef118 == bbcebf002a656df8f88b1cd18898acf357d4bed1

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-N-auto.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-N-auto.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-1-N-auto-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-1-N.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-1-N.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-1-N-0-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-0-0-unitless.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-0-0-unitless.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-N-0-0-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-0-0.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-0-0.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-N-0-0-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-0-N-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-0-N-shrink.htm 0ace4c899640b251a28f693f9c92638c85eb3acc
/css-flexbox-1_dev/html/reference/flexbox_flex-N-0-N-shrink-ref.htm d9d24f7e007e0a62f33126c3fd08683ebf15a68c
Testing 0ace4c899640b251a28f693f9c92638c85eb3acc == d9d24f7e007e0a62f33126c3fd08683ebf15a68c

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-0-N.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-0-N.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-N-0-N-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-0-Npercent-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-0-Npercent-shrink.htm 8c56e5ebbb941450bc0ba6d294644b7174d466f3
/css-flexbox-1_dev/html/reference/flexbox_flex-N-0-Npercent-shrink-ref.htm 5ad2717c02fe17167baad244d9e1b2440a26f047
Testing 8c56e5ebbb941450bc0ba6d294644b7174d466f3 == 5ad2717c02fe17167baad244d9e1b2440a26f047

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-0-Npercent.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-0-Npercent.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-N-0-Npercent-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-0-auto-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-0-auto-shrink.htm c02031c1f415d9f859c2a85a19a74da9360e4970
/css-flexbox-1_dev/html/reference/flexbox_flex-N-0-auto-shrink-ref.htm c8a2b26fc62fc2132439859162932e2b695b01c4
Testing c02031c1f415d9f859c2a85a19a74da9360e4970 == c8a2b26fc62fc2132439859162932e2b695b01c4

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-0-auto.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-0-auto.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-N-0-auto-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-0.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-0.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-N-0-0-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-1-0-unitless.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-1-0-unitless.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-N-1-0-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-1-N-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-1-N-shrink.htm 06006286b5abbc7470fd151ac149b23dac5f18d2
/css-flexbox-1_dev/html/reference/flexbox_flex-N-1-N-shrink-ref.htm 69114cdfc29aa2365fdf756e9c02d86789ab979a
Testing 06006286b5abbc7470fd151ac149b23dac5f18d2 == 69114cdfc29aa2365fdf756e9c02d86789ab979a

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-1-0.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-1-0.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-N-1-0-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-1-N.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-1-N.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-N-1-N-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-1-Npercent-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-1-Npercent-shrink.htm 06006286b5abbc7470fd151ac149b23dac5f18d2
/css-flexbox-1_dev/html/reference/flexbox_flex-N-1-Npercent-shrink-ref.htm 69114cdfc29aa2365fdf756e9c02d86789ab979a
Testing 06006286b5abbc7470fd151ac149b23dac5f18d2 == 69114cdfc29aa2365fdf756e9c02d86789ab979a

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-1-auto-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-1-auto-shrink.htm 680a1f64c52e4a598e0abd81398c2863d5bef118
/css-flexbox-1_dev/html/reference/flexbox_flex-N-1-auto-shrink-ref.htm bbcebf002a656df8f88b1cd18898acf357d4bed1
Testing 680a1f64c52e4a598e0abd81398c2863d5bef118 == bbcebf002a656df8f88b1cd18898acf357d4bed1

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-1-Npercent.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-1-Npercent.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-N-1-Npercent-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-1-auto.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-1-auto.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-N-1-auto-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-N-0-unitless.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-N-0-unitless.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-N-N-0-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-N-0.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-N-0.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-N-N-0-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-1.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-1.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-N-1-0-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-N-N-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-N-N-shrink.htm 06006286b5abbc7470fd151ac149b23dac5f18d2
/css-flexbox-1_dev/html/reference/flexbox_flex-N-N-N-shrink-ref.htm 69114cdfc29aa2365fdf756e9c02d86789ab979a
Testing 06006286b5abbc7470fd151ac149b23dac5f18d2 == 69114cdfc29aa2365fdf756e9c02d86789ab979a

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-N-Npercent-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-N-Npercent-shrink.htm 06006286b5abbc7470fd151ac149b23dac5f18d2
/css-flexbox-1_dev/html/reference/flexbox_flex-N-N-Npercent-shrink-ref.htm 69114cdfc29aa2365fdf756e9c02d86789ab979a
Testing 06006286b5abbc7470fd151ac149b23dac5f18d2 == 69114cdfc29aa2365fdf756e9c02d86789ab979a

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-N-N.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-N-N.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-N-N-N-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-N-Npercent.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-N-Npercent.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-N-N-Npercent-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-N-auto-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-N-auto-shrink.htm 680a1f64c52e4a598e0abd81398c2863d5bef118
/css-flexbox-1_dev/html/reference/flexbox_flex-N-N-auto-shrink-ref.htm bbcebf002a656df8f88b1cd18898acf357d4bed1
Testing 680a1f64c52e4a598e0abd81398c2863d5bef118 == bbcebf002a656df8f88b1cd18898acf357d4bed1

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-N-auto.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-N-auto.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-N-N-auto-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-N-N.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-N-N.htm 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33
/css-flexbox-1_dev/html/reference/flexbox_flex-N-N-0-ref.htm 3526e19f719e7ae2e4aef362ab87a962c128d274
Testing 35b61d31ae6a97eb2eef549cebc2eb2c9266ae33 == 3526e19f719e7ae2e4aef362ab87a962c128d274

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-auto.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-auto.htm 0e46d47a08813124f096b98beaedc119f0f5100f
/css-flexbox-1_dev/html/reference/flexbox_flex-auto-ref.htm ef925429ad697fd3de9795578b9e1d3a3e23a497
Testing 0e46d47a08813124f096b98beaedc119f0f5100f == ef925429ad697fd3de9795578b9e1d3a3e23a497

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-basis-shrink.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-basis-shrink.htm 64b9354068a320d1cf36a00bc90ba9e35b0a737e
/css-flexbox-1_dev/html/reference/flexbox_flex-basis-shrink-ref.htm 27a5da45d357173360d1ebe75ea0c91a5c1cc432
Testing 64b9354068a320d1cf36a00bc90ba9e35b0a737e == 27a5da45d357173360d1ebe75ea0c91a5c1cc432

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-basis.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-basis.htm 31e6f9adb96a68dbcae485261dd4ecb2379a9cff
/css-flexbox-1_dev/html/reference/flexbox_flex-basis-ref.htm f9e4898538f7fec9bd4dfb8bb99394e1770cdcd5
Testing 31e6f9adb96a68dbcae485261dd4ecb2379a9cff == f9e4898538f7fec9bd4dfb8bb99394e1770cdcd5

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-initial-2.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-initial-2.htm ace8f6cb568088ba21b3bd44c27e0480017d5653
/css-flexbox-1_dev/html/reference/flexbox_flex-initial-2-ref.htm a7fd7338a91f4999022b3a666c2eeac12e2b4657
Testing ace8f6cb568088ba21b3bd44c27e0480017d5653 == a7fd7338a91f4999022b3a666c2eeac12e2b4657

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-initial.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-initial.htm 170db494ccd3de6c1c5acff3aa8e33e33c0a086f
/css-flexbox-1_dev/html/reference/flexbox_flex-initial-ref.htm 7749ce9a06445af8b914364664c5e5e6e937296f
Testing 170db494ccd3de6c1c5acff3aa8e33e33c0a086f == 7749ce9a06445af8b914364664c5e5e6e937296f

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-natural.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-natural.htm 8a6be852765b9ba76372b1c7b66ed0462a537e73
/css-flexbox-1_dev/html/reference/flexbox_flex-natural-ref.htm 89dc74ddbe19a052e4d92efb51bd8ee4f16a5696
Testing 8a6be852765b9ba76372b1c7b66ed0462a537e73 == 89dc74ddbe19a052e4d92efb51bd8ee4f16a5696

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flex-none.htm
  └   → /css-flexbox-1_dev/html/flexbox_flex-none.htm bf6771002e10c21c32da99a757ac4aeb8209ae0e
/css-flexbox-1_dev/html/reference/flexbox_flex-none-ref.htm 35ef626c335ece2d4e71d733e65ccd63dd77ad9d
Testing bf6771002e10c21c32da99a757ac4aeb8209ae0e == 35ef626c335ece2d4e71d733e65ccd63dd77ad9d

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flow-row-wrap-reverse.htm
  └   → /css-flexbox-1_dev/html/flexbox_flow-row-wrap-reverse.htm 701984476192a76405dcdcf3ffaeb7f3afdbcd96
/css-flexbox-1_dev/html/reference/flexbox_flow-row-wrap-reverse-ref.htm d8a672572557b2f9a28993d78826ad3296ae21ac
Testing 701984476192a76405dcdcf3ffaeb7f3afdbcd96 == d8a672572557b2f9a28993d78826ad3296ae21ac

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_flow-row-wrap.htm
  └   → /css-flexbox-1_dev/html/flexbox_flow-row-wrap.htm 599fa090092185372b9ca16fe09db61dae7a387b
/css-flexbox-1_dev/html/reference/flexbox_flow-row-wrap-ref.htm 7c273222b3aeda4d4fe18f9f46c47814254523f0
Testing 599fa090092185372b9ca16fe09db61dae7a387b == 7c273222b3aeda4d4fe18f9f46c47814254523f0

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_generated-flex.htm
  └   → /css-flexbox-1_dev/html/flexbox_generated-flex.htm 8ca06ebef6dd1c09b32d23fdd11c79f876c9c0a5
/css-flexbox-1_dev/html/reference/flexbox_generated-flex-ref.htm e4eb9f3b68c40a6725b6c4e41c7b8a90060e18bf
Testing 8ca06ebef6dd1c09b32d23fdd11c79f876c9c0a5 == e4eb9f3b68c40a6725b6c4e41c7b8a90060e18bf

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_inline-abspos.htm
  └   → /css-flexbox-1_dev/html/flexbox_inline-abspos.htm e43f956a4cf2b4c3b0079d92ca86b7f2c148fc04
/css-flexbox-1_dev/html/reference/flexbox_empty-ref.htm 23b755622cc81841a23cc8431a6546dfb1401c66
Testing e43f956a4cf2b4c3b0079d92ca86b7f2c148fc04 == 23b755622cc81841a23cc8431a6546dfb1401c66

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_item-bottom-float.htm
  └   → /css-flexbox-1_dev/html/flexbox_item-bottom-float.htm 1069116fe05b47b4840fc0722555146b16585642
/css-flexbox-1_dev/html/reference/flexbox_item-bottom-float-ref.htm 590039e092eeca8b2adc82f3ba6050c7b9ae74f8
Testing 1069116fe05b47b4840fc0722555146b16585642 == 590039e092eeca8b2adc82f3ba6050c7b9ae74f8

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_inline.htm
  └   → /css-flexbox-1_dev/html/flexbox_inline.htm d54e443239b73a8b34227adb7938f2e4149e50c4
/css-flexbox-1_dev/html/reference/flexbox_inline-ref.htm 3ddb57590301f8113fe94ebc5886dc040018380e
Testing d54e443239b73a8b34227adb7938f2e4149e50c4 == 3ddb57590301f8113fe94ebc5886dc040018380e

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_item-top-float.htm
  └   → /css-flexbox-1_dev/html/flexbox_item-top-float.htm 1069116fe05b47b4840fc0722555146b16585642
/css-flexbox-1_dev/html/reference/flexbox_item-top-float-ref.htm 590039e092eeca8b2adc82f3ba6050c7b9ae74f8
Testing 1069116fe05b47b4840fc0722555146b16585642 == 590039e092eeca8b2adc82f3ba6050c7b9ae74f8

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_justifycontent-center.htm
  └   → /css-flexbox-1_dev/html/flexbox_justifycontent-center.htm 5bd26a82dceda864ef9a2f38e18b0d921c079a11
/css-flexbox-1_dev/html/reference/flexbox_justifycontent-center-ref.htm 88c9b7f2242ec632ef849662a4edcca1a1aeb0b5
Testing 5bd26a82dceda864ef9a2f38e18b0d921c079a11 == 88c9b7f2242ec632ef849662a4edcca1a1aeb0b5

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_justifycontent-flex-end.htm
  └   → /css-flexbox-1_dev/html/flexbox_justifycontent-flex-end.htm bcebcf35e44a4d1e40baf008bce859039f1b9c88
/css-flexbox-1_dev/html/reference/flexbox_justifycontent-flex-end-ref.htm 28551719968c3241ab570c028841f6d007149ddd
Testing bcebcf35e44a4d1e40baf008bce859039f1b9c88 == 28551719968c3241ab570c028841f6d007149ddd

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_justifycontent-spacearound-negative.htm
  └   → /css-flexbox-1_dev/html/flexbox_justifycontent-spacearound-negative.htm bed12bcafe05138552f71428d936d6b436805b6b
/css-flexbox-1_dev/html/reference/flexbox_justifycontent-spacearound-negative-ref.htm f6066b4412ebe49b948a936e3e976f539c532eb1
Testing bed12bcafe05138552f71428d936d6b436805b6b == f6066b4412ebe49b948a936e3e976f539c532eb1

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_justifycontent-spacearound-only.htm
  └   → /css-flexbox-1_dev/html/flexbox_justifycontent-spacearound-only.htm eeda6b1257aaa2db529b284fc6c3924d3d369eec
/css-flexbox-1_dev/html/reference/flexbox_justifycontent-spacearound-only-ref.htm 8daf2f3db562dda13de5fe487749bae2c1cc581c
Testing eeda6b1257aaa2db529b284fc6c3924d3d369eec == 8daf2f3db562dda13de5fe487749bae2c1cc581c

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_justifycontent-spacebetween-negative.htm
  └   → /css-flexbox-1_dev/html/flexbox_justifycontent-spacebetween-negative.htm 119550f7bca9e33766b06ac979b4dce6adfab040
/css-flexbox-1_dev/html/reference/flexbox_justifycontent-spacebetween-negative-ref.htm 5a128cc7bc2963caef7e798ed6ac6ffa49cca1ef
Testing 119550f7bca9e33766b06ac979b4dce6adfab040 == 5a128cc7bc2963caef7e798ed6ac6ffa49cca1ef

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_justifycontent-spacearound.htm
  └   → /css-flexbox-1_dev/html/flexbox_justifycontent-spacearound.htm 421a04faa60d6ed69f27c8b0d19c78d8e729c7b9
/css-flexbox-1_dev/html/reference/flexbox_justifycontent-spacearound-ref.htm 0820996ce44ff170ca884ff48c6470aee2a0c1ee
Testing 421a04faa60d6ed69f27c8b0d19c78d8e729c7b9 == 0820996ce44ff170ca884ff48c6470aee2a0c1ee

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_justifycontent-spacebetween-only.htm
  └   → /css-flexbox-1_dev/html/flexbox_justifycontent-spacebetween-only.htm 20b78037c50431109448b0c6ab1213da2d09b6fc
/css-flexbox-1_dev/html/reference/flexbox_justifycontent-spacebetween-only-ref.htm b3b89f67c095e1a23f14960e99ad1ba71a96fd7b
Testing 20b78037c50431109448b0c6ab1213da2d09b6fc == b3b89f67c095e1a23f14960e99ad1ba71a96fd7b

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_justifycontent-spacebetween.htm
  └   → /css-flexbox-1_dev/html/flexbox_justifycontent-spacebetween.htm d1e3461058c06c3b85126d63f809605779d84704
/css-flexbox-1_dev/html/reference/flexbox_justifycontent-spacebetween-ref.htm ed6c829bd7f1d6ce19c34f7ab8e3c1b3fa3030f0
Testing d1e3461058c06c3b85126d63f809605779d84704 == ed6c829bd7f1d6ce19c34f7ab8e3c1b3fa3030f0

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_margin-auto-overflow-2.htm
  └   → /css-flexbox-1_dev/html/flexbox_margin-auto-overflow-2.htm e3b012011c96c234e68167b6060bf0c59dd9bfa3
/css-flexbox-1_dev/html/reference/flexbox_margin-auto-overflow-2-ref.htm f1cb49a24b7221b47a7bb27fcfcf425f9f94220f
Testing e3b012011c96c234e68167b6060bf0c59dd9bfa3 == f1cb49a24b7221b47a7bb27fcfcf425f9f94220f

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_margin-auto-overflow.htm
  └   → /css-flexbox-1_dev/html/flexbox_margin-auto-overflow.htm 10f93fb3680274c76474eaba227e682222f8eb2d
/css-flexbox-1_dev/html/reference/flexbox_margin-auto-overflow-ref.htm 83d0ebaba7bc3997ebcbd6d526b3da6cd9488a23
Testing 10f93fb3680274c76474eaba227e682222f8eb2d == 83d0ebaba7bc3997ebcbd6d526b3da6cd9488a23

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_margin.htm
  └   → /css-flexbox-1_dev/html/flexbox_margin.htm 39a3ef437d82684af4d1c6d9d24dc858f8efd367
/css-flexbox-1_dev/html/reference/flexbox_margin-ref.htm a930976ad774603c3b99adfb362e39f1246d4d1f
Testing 39a3ef437d82684af4d1c6d9d24dc858f8efd367 == a930976ad774603c3b99adfb362e39f1246d4d1f

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_margin-left-ex.htm
  └   → /css-flexbox-1_dev/html/flexbox_margin-left-ex.htm c04c7ca78dded1088de7f440aa8e0fd1504f80a4
/css-flexbox-1_dev/html/reference/flexbox_margin-left-ex-ref.htm 49f2acd3c46ca67548065558ff43e0510e022cfc
Testing c04c7ca78dded1088de7f440aa8e0fd1504f80a4 == 49f2acd3c46ca67548065558ff43e0510e022cfc

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_order-box.htm
  └   → /css-flexbox-1_dev/html/flexbox_order-box.htm ce7337e86f4fc3e4480bda6aadc8f485336717d3
/css-flexbox-1_dev/html/reference/flexbox_order-box-ref.htm 1bb07b40a29874beffb58fcb7af5aee76ed4b58a
Testing ce7337e86f4fc3e4480bda6aadc8f485336717d3 == 1bb07b40a29874beffb58fcb7af5aee76ed4b58a

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox_rowspan-overflow-automatic.htm

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox_rowspan-overflow.htm

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox_rowspan.htm

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox_stf-abspos.htm

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox_stf-float.htm

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox_stf-inline-block.htm

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox_stf-table-cell.htm

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox_stf-table-row-group.htm

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox_stf-table-row.htm

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox_stf-table.htm

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_wrap-long.htm
  └   → /css-flexbox-1_dev/html/flexbox_wrap-long.htm 6eb84208628169f76c653b547d936c8a1c480d10
/css-flexbox-1_dev/html/reference/flexbox_wrap-long-ref.htm 66b85d6b7d85768b9e52b5cb179858e539de7102
Testing 6eb84208628169f76c653b547d936c8a1c480d10 == 66b85d6b7d85768b9e52b5cb179858e539de7102

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_wrap-reverse.htm
  └   → /css-flexbox-1_dev/html/flexbox_wrap-reverse.htm 701984476192a76405dcdcf3ffaeb7f3afdbcd96
/css-flexbox-1_dev/html/reference/flexbox_wrap-reverse-ref.htm d8a672572557b2f9a28993d78826ad3296ae21ac
Testing 701984476192a76405dcdcf3ffaeb7f3afdbcd96 == d8a672572557b2f9a28993d78826ad3296ae21ac

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_wrap.htm
  └   → /css-flexbox-1_dev/html/flexbox_wrap.htm 599fa090092185372b9ca16fe09db61dae7a387b
/css-flexbox-1_dev/html/reference/flexbox_wrap-ref.htm 7c273222b3aeda4d4fe18f9f46c47814254523f0
Testing 599fa090092185372b9ca16fe09db61dae7a387b == 7c273222b3aeda4d4fe18f9f46c47814254523f0

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexible-box-float.htm

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/order-with-column-reverse.htm
  └   → /css-flexbox-1_dev/html/order-with-column-reverse.htm 90588b2339d2a78695195ef2cb5abec76442bdbd
/css-flexbox-1_dev/html/reference/order-with-column-reverse-ref.htm 5dd2cf6fa9429a4f48db1d6e929a3e5bcae00b1b
Testing 90588b2339d2a78695195ef2cb5abec76442bdbd == 5dd2cf6fa9429a4f48db1d6e929a3e5bcae00b1b

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/ttwf-reftest-flex-inline.htm
  └   → /css-flexbox-1_dev/html/ttwf-reftest-flex-inline.htm d9fd5956fa0c5f863db35ad3f69e071fd38bae06
/css-flexbox-1_dev/html/reference/ttwf-reftest-flex-inline-ref.htm 06a2dc596e10fcd2b216d0ed294e35b3f64611e6
Testing d9fd5956fa0c5f863db35ad3f69e071fd38bae06 == 06a2dc596e10fcd2b216d0ed294e35b3f64611e6

  ▶ TIMEOUT [expected PASS] /css-text-decor-3_dev/html/text-emphasis-style-property-010Cn.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 17.2.0-devel
  │ assertion failed: glyphs[0] != 0 (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at /Users/servo/buildbot/slave/mac-rel-css1/build/components/gfx/platform/macos/font.rs:253)
  │ 2017-08-21 14:35:06.517 servo[51158:2088038751] Metadata.framework [Error]: couldn't get the client port
  │ stack backtrace:
  │    0:        0x10e40ceae - backtrace::backtrace::trace::hb2a815d7a25bb200
  │    1:        0x10e40ceec - backtrace::capture::Backtrace::new::h8d167d15706e03e2
  │    2:        0x10de36ae4 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h358312fbff696eee
  │    3:        0x10fe4cc91 - std::panicking::rust_panic_with_hook::h7ead43b379200c35
  │    4:        0x10f9bc6e7 - std::panicking::begin_panic::h3c2c3749862b64cd
  │    5:        0x10f9e8084 - _$LT$gfx..platform..macos..font..FontHandle$u20$as$u20$gfx..font..FontHandleMethods$GT$::glyph_index::hc9a741e9e3b3ae48
  │    6:        0x10f8ba379 - _$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$::position::_$u7b$$u7b$closure$u7d$$u7d$::hee68b6e535482402
  │    7:        0x10f927a61 - layout::text::TextRunScanner::scan_for_runs::hba291605ccedc9c4
  │    8:        0x10e5aad9c - _$LT$layout..construct..FlowConstructor$LT$$u27$a$C$$u20$ConcreteThreadSafeLayoutNode$GT$$GT$::build_flow_for_block_starting_with_fragments::h4c94d73c67477bcb
  │    9:        0x10e5a9069 - _$LT$layout..construct..FlowConstructor$LT$$u27$a$C$$u20$ConcreteThreadSafeLayoutNode$GT$$GT$::build_flow_for_block_like::hef393e46babc9c1d
  │   10:        0x10e5a802e - _$LT$layout..construct..FlowConstructor$LT$$u27$a$C$$u20$ConcreteThreadSafeLayoutNode$GT$$GT$::build_flow_for_block::h2e3e7983dd0bb597
  │   11:        0x10e52b60b - _$LT$layout..construct..FlowConstructor$LT$$u27$a$C$$u20$ConcreteThreadSafeLayoutNode$GT$$u20$as$u20$layout..traversal..PostorderNodeMutTraversal$LT$ConcreteThreadSafeLayoutNode$GT$$GT$::process::hfb9c7b5e7f68b490
  │   12:        0x10e57dfad - style::traversal::DomTraversal::handle_postorder_traversal::h36d6f0097747c0a1
  │   13:        0x10e5d67e7 - layout_thread::LayoutThread::handle_reflow::h90a165b77d7dec98
  │   14:        0x10e5c9a41 - layout_thread::LayoutThread::handle_request_helper::h3e72b977ca2442ae
  │   15:        0x10e5c4537 - _$LT$layout_thread..LayoutThread$u20$as$u20$layout_traits..LayoutThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::h0c62b5c2d0afae88
  │   16:        0x10e540bcd - std::sys_common::backtrace::__rust_begin_short_backtrace::had27210fb05c5253
  │   17:        0x10e54170d - std::panicking::try::do_call::h393db425f0421b9b
  │   18:        0x10fe4de2c - __rust_maybe_catch_panic
  │   19:        0x10e571845 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::hffd8dd99b3cd1311
  │   20:        0x10fe49c4b - std::sys::imp::thread::Thread::new::thread_start::hd002bdea82a6ac49
  │   21:     0x7fff95aed059 - _pthread_body
  │   22:     0x7fff95aecfd6 - _pthread_start
  │ ERROR:servo: assertion failed: glyphs[0] != 0
  │ assertion failed: !self.Document().needs_reflow() ||
  │     (!for_display && self.Document().needs_paint()) ||
  │     self.window_size.get().is_none() || self.suppress_reflow.get() (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at /Users/servo/buildbot/slave/mac-rel-css1/build/components/script/dom/window.rs:1344)
  │ stack backtrace:
  │    0:        0x10e40ceae - backtrace::backtrace::trace::hb2a815d7a25bb200
  │    1:        0x10e40ceec - backtrace::capture::Backtrace::new::h8d167d15706e03e2
  │    2:        0x10de36ae4 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h358312fbff696eee
  │    3:        0x10fe4cc91 - std::panicking::rust_panic_with_hook::h7ead43b379200c35
  │    4:        0x10e643bf7 - std::panicking::begin_panic::hd3a90b83681bb743
  │    5:        0x10ece89a4 - script::dom::window::Window::reflow::h9d1352544dc2c34b
  │    6:        0x10eb40d99 - script::dom::document::Document::finish_load::h17d4125520fb3370
  │    7:        0x10ec6198a - script::dom::servoparser::ServoParser::do_parse_sync::he4b73cdc53ffc356
  │    8:        0x10ec61356 - script::dom::servoparser::ServoParser::parse_sync::h74275d215f292ccb
  │    9:        0x10ec64d5d - _$LT$script..dom..servoparser..ParserContext$u20$as$u20$net_traits..FetchResponseListener$GT$::process_response_eof::h889f89ab4d6c31b1
  │   10:        0x10ed38650 - script::script_thread::ScriptThread::handle_msg_from_constellation::ha6bd8c31419ddb0e
  │   11:        0x10ed346a1 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hc6c12abbeaaaf168
  │   12:        0x10ed31452 - script::script_thread::ScriptThread::handle_msgs::hd9cfbf1fb396aa71
  │   13:        0x10e63b0b7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5304fe1956489acb
  │   14:        0x10e82056d - std::panicking::try::do_call::hfbc8fa3bf056bb11
  │   15:        0x10fe4de2c - __rust_maybe_catch_panic
  │   16:        0x10e9521e5 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h5fa8f3962b4a02bb
  │   17:        0x10fe49c4b - std::sys::imp::thread::Thread::new::thread_start::hd002bdea82a6ac49
  │   18:     0x7fff95aed059 - _pthread_body
  │   19:     0x7fff95aecfd6 - _pthread_start
  │ ERROR:servo: assertion failed: !self.Document().needs_reflow() ||
  │     (!for_display && self.Document().needs_paint()) ||
  └     self.window_size.get().is_none() || self.suppress_reflow.get()
```
</details>

**Comment by stshine** [comment]
Looks like the margin handling code is not correct in `flex.rs` which was covered before, and this change also makes floats in flexbox behaves more correct. Trying to fix the issue.

**Comment by stshine** [comment]
Seems to be more troublesome than I thought since a bunch of functionalities need to implemented.

**Comment by stshine** [comment]
@bors-servo retry
* infra

**Comment by stshine** [comment]
Patch is ready \o/

File: components/layout/flex.rs [hunk 1]
```diff
@@ -939,13 +940,29 @@ impl Flow for FlexFlow {
...
-        self.block_flow
-            .assign_block_size_block_base(layout_context,
-                                          None,
-                                          MarginsMayCollapseFlag::MarginsMayNotCollapse);
         match self.main_mode {
-            Direction::Inline => self.inline_mode_assign_block_size(layout_context),
-            Direction::Block => self.block_mode_assign_block_size(),
+            Direction::Inline => {
+                self.inline_mode_assign_block_size(layout_context);
+                let block_start = AdjoiningMargins::from_margin(self.block_flow.fragment.margin.block_start);
```
Comment (mbrubeck) [inline components/layout/flex.rs]: Should the code inside this branch be moved into `inline_mode_assign_block_size`?

**Review by mbrubeck — APPROVED** [review]
This looks good to me! One optional suggestion below.

File: components/layout/flex.rs (hunk 1 above)
Comment (stshine) [reply components/layout/flex.rs]: No, I believe they should be shared for both containers, only separated for now because column flexbox is not implemented.

Comment (mbrubeck) [reply components/layout/flex.rs]: Okay, that makes sense.

**Comment by mbrubeck** [comment]
@bors-servo retry

* #18228

**Comment by stshine** [comment]
@bors-servo retry

* Internal Compiler Error
