### PR TITLE
Fix cef to follow new Browser::new() interface

### LINKED ISSUE #17273: Browser::new() changes CEF follow up
Since #16477, we need to make some changes in CEF:

- No need to use the `shell.homepage` pref
- don't call `frame.set_url` in `ServoCefBrowser::new`

/cc @sadmansk

### PR DESCRIPTION
**Pull request by sadmansk**
Changes the call to `Browser::new()` in cef to contain the target_url.

cc @paulrouget 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #17273.

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17548)

### CODE REVIEW

File: ports/cef/browser.rs [hunk 1]
```diff
@@ -23,7 +22,6 @@ use std::ptr;
 use std::rc::Rc;
 use std::sync::atomic::{AtomicIsize, Ordering};
 use std::thread;
-
```
Comment (paulrouget) [inline ports/cef/browser.rs]: No need to remove this line.

File: ports/cef/browser.rs [hunk 2]
```diff
@@ -274,11 +269,18 @@ fn browser_host_create(window_info: &cef_window_info_t,
...
+    let blank_url = ServoUrl::parse("about:blank").unwrap();
+    let url_string = if url != ptr::null() {
+        unsafe { String::from_utf16(CefWrap::to_rust(url)).ok() }
+    } else {
+        None
+    };
+    let target_url = match url_string {
+        Some(val) => ServoUrl::parse(&val[..]).unwrap_or(blank_url),
+        None => blank_url
+    };
```
Comment (paulrouget) [inline ports/cef/browser.rs]: Could you do something like this:

```rust
    let target_url = url_string
        .and_then(|val| ServoUrl::parse(&val[..]).ok())
        .or(ServoUrl::parse("about:blank").ok())
        .unwrap();
```

**Review by paulrouget — CHANGES_REQUESTED** [review]

File: ports/cef/browser.rs (hunk 2 above)
Comment (KiChjang) [inline ports/cef/browser.rs]: I think `&val[..]` here can be simplified to `&val` as well.

File: ports/cef/browser.rs (hunk 1 above)
Comment (sadmansk) [inline ports/cef/browser.rs]: sorry, that was an oversight, i'll fix it

**Comment by sadmansk** [comment]
@paulrouget fixed according to your review comments.

**Comment by sadmansk** [comment]
so `./mach test-unit` is failing on Travis, but it's passing on my local machine, any idea why that could be the case?

**Comment by jdm** [comment]
I'm pretty sure the error while linking is caused by travis running out of disk space.

**Comment by sadmansk** [comment]
Can that error be ignored then? Or is there a fix that I can do?

**Comment by jdm** [comment]
It can be ignored.

**Review by paulrouget — APPROVED** [review]
