### PR TITLE
net: Close the control stream of RequestBody to fix resource leak

### LINKED ISSUE #41202: thread 'router-proxy' panicked in ipc-channel
libservo 0.0.2
**Describe the bug:**

On Linux, this happens approximately after 2200 requests. 
```
thread 'router-proxy' panicked at /home/arhadm/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ipc-channel-0.20.2/src/platform/unix/mod.rs:789:9:
assertion failed: address != MAP_FAILED
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Redirecting call to abort() to mozalloc_abort

Segmentation fault
```
on windows there is no panic, just a steady increase in RAM consumption. 

**To Reproduce:**
Cyclic REST requests with js

**Platform:**
linux & windows

### PR DESCRIPTION
**Pull request by Narfinger**
For a network fetch, the body chunk request sender keeps being alive as long as the request is alive. This leads to a big resource leak as this keeps a couple of IpcChannels and SharedMemory around. These would only be cleaned up when the Gc cleans up the Request which can be too long for tight fetch loops.

This gives a method to destroy the channel at the end of the complete fetch (keeping in mind redirects). Currently we have to do this by hand as a simple guard structure did not work correctly.

Additionally, this renames `RequestBody::take_stream` to the correct clone_stream and cleans up some smaller names and documentation.

Testing: WPT should catch anything that is not spec conform.
Fixes: https://github.com/servo/servo/issues/41202

### CODE REVIEW

File: components/net/http_loader.rs [hunk 1]
```diff
@@ -698,12 +698,20 @@ async fn obtain_response(
             let (body_chan, body_port) = ipc::channel().unwrap();
 
             {
-                let requester = chunk_requester.lock();
-                let _ = requester.send(BodyChunkRequest::Connect(body_chan));
+                let mut lock = chunk_requester.lock();
+                if let Some(chunk_requester) = lock.as_mut() {
+                    let _ = chunk_requester.send(BodyChunkRequest::Connect(body_chan));
```
Comment (Taym95) [inline components/net/http_loader.rs]: I am not sure, but since the function continues as if body streaming is happening, I think this can cause request proceeds with no body or hangs waiting for chunks

File: components/shared/net/request.rs [hunk 2]
```diff
@@ -340,15 +343,25 @@ impl RequestBody {
...
                 let _ = selfchan.send(BodyChunkRequest::Extract(port));
                 *selfchan = chan;
             },
         }
     }
 
-    pub fn take_stream(&self) -> Arc<Mutex<IpcSender<BodyChunkRequest>>> {
-        self.chan.clone()
+    pub fn clone_stream(&self) -> Arc<Mutex<Option<IpcSender<BodyChunkRequest>>>> {
+        self.body_chunk_request_channel.clone()
```
Comment (Taym95) [inline components/shared/net/request.rs:368]: can we document this is "this is a shared optional sender" ?

**Comment by mrobinson** [comment]
@Narfinger  Gentle nit suggestion to find a different word than "neuter", which probably has connotations you don't intend.

**Comment by Taym95** [comment]
@Narfinger what’s youe status on this PR? Do you mind if I also take a look with you?

**Comment by Narfinger** [comment]
Oh please take a look at it. I am kind of at my wits end on how to figure out the problem.

File: components/net/http_loader.rs [hunk 3]
```diff
@@ -1044,6 +1056,10 @@ pub async fn http_fetch(
         };
     }
 
+    if let Some(ref body) = fetch_params.request.body {
+        body.close_stream();
```
Comment (Taym95) [inline components/net/http_loader.rs]: This is assuming that the request ends here, but that’s not totally true, the body is still needed after this, for example in the redirect_count case.

Comment (Taym95) [reply components/net/http_loader.rs]: /fetch/origin/assorted.window.html confirms it.

Comment (Taym95) [reply components/net/http_loader.rs]: confirmed,  this is happening before redirect handling is finished

Comment (Taym95) [reply components/net/http_loader.rs]: this commit https://github.com/servo/servo/pull/42474/changes/86902c0f11a22edee7b4a6b0db66af04a4964ed2 shoudl fix it.

**Comment by Narfinger** [comment]
Awesome! Does this then fix the testcase resource leak?

File: components/net/fetch/methods.rs [hunk 4]
```diff
@@ -941,11 +950,17 @@ fn handle_allowcert_request(request: &mut Request, context: &FetchContext) -> io
...
-    let _ = stream.send(BodyChunkRequest::Connect(body_chan));
-    let _ = stream.send(BodyChunkRequest::Chunk);
+    let Some(chunk_requester) = stream.as_mut() else {
+        log::error!(
+            "Could not send BodyChunkRequest to chunk_requester as stream got already neutered."
+        );
+        return Err(std::io::Error::other("Could not send BodyChunkRequest"));
+    };
+    let _ = chunk_requester.send(BodyChunkRequest::Connect(body_chan));
+    let _ = chunk_requester.send(BodyChunkRequest::Chunk);
```
Comment (gterzian) [inline components/net/fetch/methods.rs]: would be good to log errors for failed sends as well.

File: components/shared/net/request.rs [hunk 5]
```diff
@@ -340,15 +343,26 @@ impl RequestBody {
...
-    pub fn take_stream(&self) -> Arc<Mutex<IpcSender<BodyChunkRequest>>> {
-        self.chan.clone()
+    /// This is a shared optional sender to request BodyChunks.
+    pub fn clone_stream(&self) -> Arc<Mutex<Option<IpcSender<BodyChunkRequest>>>> {
+        self.body_chunk_request_channel.clone()
+    }
+
+    /// This needs to be called the last time the body stream sender is used to not leak resources.
+    /// Can be called multiple times.
+    pub fn close_stream(&self) {
```
Comment (gterzian) [inline components/shared/net/request.rs:375]: For simplicity, can we just have a single call to this; like at https://github.com/servo/servo/blob/a122bde4b1016f6fc6f46583b77dbfcc7a4e8a69/components/net/resource_thread.rs#L768 ?

File: components/script/script_thread.rs [hunk 6]
```diff
@@ -3043,6 +3043,17 @@ impl ScriptThread {
...
         };
 
+        {
+            let loads = self.incomplete_loads.borrow();
+            if let Some(body) = loads[idx].load_data.data.as_ref() {
+                // Lifecycle: Non-Navigate redirects can span multiple net fetch calls.
+                // This hook runs only for terminal (Non-Navigate) navigation responses, so no
+                // later redirect replay can reach `extract_source()`.
+                // we can close the stream.
+                body.close_stream();
```
Comment (gterzian) [inline components/script/script_thread.rs]: So here we are in the script-thread, so closing this cannot affect the arc for something in another process, so I'm not sure if this call has a point. The body is dropped by script below anyway right?

File: components/shared/net/request.rs [hunk 7]
```diff
@@ -323,12 +326,12 @@ pub struct RequestBody {
...
 impl RequestBody {
     pub fn new(
-        chan: IpcSender<BodyChunkRequest>,
+        body_chunk_request_channel: IpcSender<BodyChunkRequest>,
         source: BodySource,
         total_bytes: Option<usize>,
     ) -> Self {
         RequestBody {
-            chan: Arc::new(Mutex::new(chan)),
+            body_chunk_request_channel: Arc::new(Mutex::new(Some(body_chunk_request_channel))),
```
Comment (gterzian) [inline components/shared/net/request.rs:336]: So what I find interesting is that `new` here is called in the script-process, and then this is sent across process to the the network part. 

How does that work with the arc? I assume the memory it points to is copied as part of serialization, so that the arc on the receiving end points to basically a clone of the underlying channel, with a new arc around it?

File: components/net/http_loader.rs [hunk 8]
```diff
@@ -741,7 +748,12 @@ async fn obtain_response(
 
                     // Step 5.1.2.3
                     // Request the next chunk.
-                    let _ = chunk_requester2.lock().send(BodyChunkRequest::Chunk);
+                    let mut chunk_requester2 = chunk_requester2.lock();
+                    if let Some(chunk_requester2) = chunk_requester2.as_mut() {
+                        let _ = chunk_requester2.send(BodyChunkRequest::Chunk);
+                    } else {
+                        error!("Could not send chunk request to closed ChunkRequester.");
```
Comment (gterzian) [inline components/net/http_loader.rs]: This is a good message for the `let _ ` above, however here we should rather write something along the lines of: "body has already been closed"

**Review by gterzian — COMMENTED** [review]
Couple of questions, especially one about whether we cannot consolidate the `close_stream` into one.

File: components/shared/net/request.rs (hunk 7 above)
Comment (jdm) [reply components/shared/net/request.rs:336]: That is correct.

File: components/net/http_loader.rs [hunk 9]
```diff
@@ -2090,6 +2102,9 @@ async fn http_network_fetch(
             {
                 Ok(response) => response,
                 Err(error) => {
+                    if let Some(body_chunk_request_stream) = request.body.as_ref() {
```
Comment (jdm) [inline components/net/http_loader.rs]: If we have to.do this every time we early-return from this code it would be nice to use a type with a Drop implementation to make sure we don't overlook one.

Comment (jdm) [reply components/net/http_loader.rs]: Something like AutoRequestBodyStreamCloser.

File: components/shared/net/request.rs [hunk 10]
```diff
@@ -310,11 +311,13 @@ pub enum BodyChunkRequest {
...
 /// The net component's view into <https://fetch.spec.whatwg.org/#bodies>
+/// After the last call to `extract_source`, `close_stream` must be called
+/// to not leak resources.
 #[derive(Clone, Debug, Deserialize, MallocSizeOf, Serialize)]
 pub struct RequestBody {
     /// Net's channel to communicate with script re this body.
-    #[conditional_malloc_size_of]
-    chan: Arc<Mutex<IpcSender<BodyChunkRequest>>>,
+    #[ignore_malloc_size_of = "Channels are hard"]
+    body_chunk_request_channel: Arc<Mutex<Option<IpcSender<BodyChunkRequest>>>>,
```
Comment (jdm) [inline components/shared/net/request.rs:322]: The arc was introduced in https://github.com/servo/servo/commit/903e0cd8570353b0ecef33d094464166869b9eb3 and I keep thinking that this problem would be easier to solve if we just cloned the sender instead of trying to share it.

Comment (jdm) [reply components/shared/net/request.rs:322]: Bah, it's definitely harder to remove the sharing than I hoped.

**Comment by Narfinger** [comment]
@Taym95 will you be responsible for this getting merged or should I take over the comments?

**Comment by Taym95** [comment]
> @Taym95 will you be responsible for this getting merged or should I take over the comments?

I will take care of it.

File: components/net/fetch/methods.rs [hunk 11]
```diff
@@ -126,6 +127,52 @@ impl CancellationListener {
         self.cancelled.store(true, Ordering::Relaxed)
     }
 }
+
+/// Closes the current process request body sender state when the net side fetch invocation ends.
+/// Redirect replay for navigation requests happens in a later fetch invocation with a newly
+/// deserialized "RequestBody", so each invocation owns closing only its local copy.
+pub(crate) struct AutoRequestBodyStreamCloser {
```
Comment (Taym95) [inline components/net/fetch/methods.rs:134]: @jdm  I introduced AutoRequestBodyStreamCloser, please have another look

**Review by jdm — APPROVED** [review]
This seem more robust and easier to follow now. Thanks!

**Comment by Narfinger** [comment]
Thank you so much for the cleanup and the details comments!
