### PR TITLE
Let textarea wrap lines

### LINKED ISSUE #10053: textarea text overflow
when rendering this page this is what I get in servo compared to chrome/firefox
textarea problem

code to reproduce this issue:
```html
<textarea cols="20" rows="5">This is a sentence that is more than 20 cols, for showing that this is a real problem.</textarea>
```

I'm using release build of e273517fe06720afe0ef74815cce5e007df7dc3d

### PR DESCRIPTION
**Pull request by kilobtye**
1. Change textarea's style from white-space: pre to white-space: pre-wrap.
2. Display insertion point when a line is wrapped.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #10053 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12388)

### CODE REVIEW

**Comment by SimonSapin** [comment]
The style and stylesheet changes look ok to me, but I don’t understand insertion points.

r? @jdm

---

Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12388#-:-KMUWWsdXYV54KZs_EJ-:-294256213)*

**Comment by jdm** [comment]
I also know nothing about the layout-related parts of insertion points. r? @pcwalton

File: components/layout/fragment.rs [hunk 1]
```diff
@@ -882,16 +882,26 @@ impl Fragment {
...
+        let (flags, insertion_point) = match self.specific {
+            SpecificFragmentInfo::ScannedText(ref info) => {
+                match info.insertion_point {
+                    Some(index) => {
+                        if split.range.contains(index) {
+                            (info.flags, info.insertion_point)
+                        } else {
+                            (info.flags, None)
+                        }
+                    }
```
Comment (pcwalton) [inline components/layout/fragment.rs]: nit: could use a guard here and remove a level of indentation: `Some(index) if split.range.contains(index) => (info.flags, info.insertion_point), Some(_) =>(info.flags, None),`

File: components/layout/fragment.rs [hunk 2]
```diff
@@ -882,16 +882,26 @@ impl Fragment {
         let size = LogicalSize::new(self.style.writing_mode,
                                     split.inline_size,
                                     self.border_box.size.block);
-        let flags = match self.specific {
-            SpecificFragmentInfo::ScannedText(ref info) => info.flags,
-            _ => ScannedTextFlags::empty()
+        let (flags, insertion_point) = match self.specific {
```
Comment (pcwalton) [inline components/layout/fragment.rs]: Could you add a comment here explaining what this code does with the insertion point?

**Comment by notriddle** [comment]
On wrapped lines, the cursor is not visible if it's on the end. In other words...

When I first type into the textarea, I can see the cursor:

     ________
    | a b c| |
    |        |
    |________|

When it wraps, it vanishes:

     ________
    | a b c d|
    | e f    |
    |________|

If I press the left arrow, it reappears:

     ________
    | a b c d|
    | e|f    |
    |________|

If I press the right arrow, it disappears again:

     ________
    | a b c d|
    | e f    |
    |________|

**Comment by kilobtye** [comment]
Fixed line end issue.

File: components/style/properties/properties.mako.rs [hunk 3]
```diff
@@ -2130,10 +2130,6 @@ pub fn modify_style_for_input_text(style: &mut Arc<ServoComputedValues>) {
     margin_style.margin_right = computed::LengthOrPercentageOrAuto::Length(Au(0));
     margin_style.margin_bottom = computed::LengthOrPercentageOrAuto::Length(Au(0));
     margin_style.margin_left = computed::LengthOrPercentageOrAuto::Length(Au(0));
-
-    // whitespace inside text input should not be collapsed
-    let inherited_text = Arc::make_mut(&mut style.inheritedtext);
-    inherited_text.white_space = longhands::white_space::computed_value::T::pre;
```
Comment (pcwalton) [inline components/style/properties/properties.mako.rs]: Why remove this?

Comment (kilobtye) [inline components/style/properties/properties.mako.rs]: I want to change textarea's `white-space` to `pre-wrap`. However it is set to `pre` for input and textarea here and override any values set in servo.css. I think setting `white-space` in servo.css properly is enough.

Comment (pcwalton) [inline components/style/properties/properties.mako.rs]: OK, that's fine.

**Comment by pcwalton** [comment]
r=me after squashing all these commits together.

**Comment by kilobtye** [comment]
Squashed.
