### PR TITLE
Make Assign throw error on invalid url

### LINKED ISSUE #13420: Make Location::Assign throw an error if URL parsing fails
Step 2 of https://html.spec.whatwg.org/multipage/browsers.html#dom-location-assign says we should [throw an exception](http://doc.servo.org/script/dom/bindings/index.html#throwing-exceptions), but the current implementation does not do that.

Code: `components/script/dom/location.rs`, `components/script/dom/webidls/Location.webidl` (add a `[Throws]` annotation)
Test: `./mach test-wpt tests/wpt/web-platform-tests/html/browsers/history/the-location-interface/location_assign.html`

### PR DESCRIPTION
**Pull request by Mythra**
Step 2 of: https://html.spec.whatwg.org/multipage/browsers.html#dom-location-assign says we should throw an error. This makes it do that.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #13420  (github issue number if applicable).
- [x] There are tests for these changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13422)

### CODE REVIEW

File: components/script/dom/location.rs [hunk 1]
```diff
@@ -46,12 +47,15 @@ impl Location {
 
 impl LocationMethods for Location {
     // https://html.spec.whatwg.org/multipage/#dom-location-assign
-    fn Assign(&self, url: USVString) {
+    fn Assign(&self, url: USVString) -> Fallible<()> {
```
Comment (KiChjang) [inline components/script/dom/location.rs]: You can use `ErrorResult` instead of `Fallible<()>` here.

Comment (SecurityInsanity) [inline components/script/dom/location.rs]: Good to know, I'll amend this commit.

**Comment by KiChjang** [comment]
```

Ran 7565 tests finished in 1082.0 seconds.
  • 7563 ran as expected. 1677 tests skipped.
  • 1 tests crashed unexpectedly
  • 1 tests had unexpected subtest results

Tests with unexpected results:
  ▶ CRASH [expected OK] /WebCryptoAPI/import_export/rsa_importKey.worker
  │ 
  │ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".
  │ Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }"
  │ stack backtrace:
  │    0:     0x7fa8ae0e2eed - backtrace::backtrace::trace::h0e60ef08c7c34e9f
  │    1:     0x7fa8ae0e3572 - backtrace::capture::Backtrace::new::h8bf319c36d8f5d1b
  │    2:     0x7fa8ac8cf994 - servo::install_crash_handler::handler::h40399914f600372a
  │    3:     0x7fa8ada10cc3 - AsmJSFaultHandler
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
  │    4:     0x7fa8aa7f032f - <unknown>
  │    5:     0x7fa8ad65a9d3 - _ZNK13JSCompartment28unsafeUnbarrieredMaybeGlobalEv
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscompartmentinlines.h:34
  │                          - _ZNK8JSObject6globalEv
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsobjinlines.h:427
  │                          - 13JSCompartment4wrapEP9JSContextN2JS13MutableHandleIP8JSObjectEENS2_6HandleIS5_E
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscompartment.cpp:408
  │    6:     0x7fa8ad608ecd - 13JSCompartment4wrapEP9JSContextN2JS13MutableHandleINS2_5ValueEEENS2_6HandleIP8JSObjectE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscompartmentinlines.h:117
  │                          - _Z12JS_WrapValueP9JSContextN2JS13MutableHandleINS1_5ValueEEE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsapi.cpp:819
  │    7:     0x7fa8acd30263 - std::panicking::try::do_call::h5005f86deb2ae9ae
  │    8:     0x7fa8ae342bb6 - __rust_maybe_catch_panic
  │    9:     0x7fa8ad22e790 - script::dom::bindings::codegen::Bindings::MessageEventBinding::MessageEventBinding::get_data::h6c3d46e59af103d4
  │   10:     0x7fa898b159ee - <unknown>
  │ Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }"
  │ stack backtrace:
  │    0:     0x7fa8ae0e2eed - backtrace::backtrace::trace::h0e60ef08c7c34e9f
  │    1:     0x7fa8ae0e3572 - backtrace::capture::Backtrace::new::h8bf319c36d8f5d1b
  │    2:     0x7fa8ac8cf994 - servo::install_crash_handler::handler::h40399914f600372a
  │    3:     0x7fa8aa23bcaf - <unknown>
  │    4:     0x7fa8ac8cfa1f - servo::install_crash_handler::handler::h40399914f600372a
  │    5:     0x7fa8ada10cc3 - AsmJSFaultHandler
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
  │    6:     0x7fa8aa7f032f - <unknown>
  │    7:     0x7fa8ad65a9d3 - _ZNK13JSCompartment28unsafeUnbarrieredMaybeGlobalEv
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscompartmentinlines.h:34
  │                          - _ZNK8JSObject6globalEv
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsobjinlines.h:427
  │                          - 13JSCompartment4wrapEP9JSContextN2JS13MutableHandleIP8JSObjectEENS2_6HandleIS5_E
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscompartment.cpp:408
  │    8:     0x7fa8ad608ecd - 13JSCompartment4wrapEP9JSContextN2JS13MutableHandleINS2_5ValueEEENS2_6HandleIP8JSObjectE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jscompartmentinlines.h:117
  │                          - _Z12JS_WrapValueP9JSContextN2JS13MutableHandleINS1_5ValueEEE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/jsapi.cpp:819
  │    9:     0x7fa8acd30263 - std::panicking::try::do_call::h5005f86deb2ae9ae
  │   10:     0x7fa8ae342bb6 - __rust_maybe_catch_panic
  │   11:     0x7fa8ad22e790 - script::dom::bindings::codegen::Bindings::MessageEventBinding::MessageEventBinding::get_data::h6c3d46e59af103d4
  └   12:     0x7fa898b159ee - <unknown>

  ▶ Unexpected subtest result in /html/browsers/history/the-location-interface/location_assign.html:
  └ PASS [expected FAIL] URL that fails to parse
```
The first error is irrelevant, but you'll need to change the test expectation for the second unexpected PASS.

**Comment by SecurityInsanity** [comment]
Yep looks like I missed that in the readme, :disappointed: Should be updated now.

File: tests/wpt/metadata/html/browsers/history/the-location-interface/location_assign.html.ini [hunk 2]
```diff
@@ -4,5 +4,4 @@
     expected: FAIL
 
   [URL that fails to parse]
-    expected: FAIL
-
+    expected: PASS
```
Comment (KiChjang) [inline tests/wpt/metadata/html/browsers/history/the-location-interface/location_assign.html.ini]: You can delete this file. By default, tests are expected to PASS.

Comment (Ms2ger) [inline tests/wpt/metadata/html/browsers/history/the-location-interface/location_assign.html.ini]: Don't delete the file, but do remove those two lines.

**Comment by KiChjang** [comment]
Needs squash.

**Comment by KiChjang** [comment]
@bors-servo r+

Thanks!
