### PR TITLE
webgl: shutdown webrender before acknowledging Exit message

### LINKED ISSUE #34847: Panic on shutdown in WebGL thread
**Describe the bug:**
Servo panics when the minibrowser window is closed on a page that uses WebGL. The issue appears to happen more consistently when the page is not the focused tab.

```
main on  main [$?⇕] is 📦 v0.0.1 via 🐍 v3.11.10 via 🦀 v1.83.0 took 17s
❯ ./mach run -r
NOTE: Entering nix-shell ./shell.nix
called `Option::unwrap()` on a `None` value (thread WRSceneBuilder#0, at /home/mukilan/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8468e81/webrender/src/scene_builder_thread.rs:531)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::panic
   8: core::option::unwrap_failed
   9: webrender::scene_builder_thread::SceneBuilderThread::process_transaction
  10: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  11: alloc::vec::in_place_collect::from_iter_in_place
  12: webrender::scene_builder_thread::SceneBuilderThread::run
  13: std::sys::backtrace::__rust_begin_short_backtrace
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: std::sys::pal::unix::thread::Thread::new::thread_start
  16: start_thread
  17: __GI___clone3
[2025-01-06T14:26:24Z ERROR servoshell::panic_hook] called `Option::unwrap()` on a `None` value
called `Result::unwrap()` on an `Err` value: RecvError (thread WebGL, at /home/mukilan/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8468e81/webrender/src/render_api.rs:1185)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: webrender::render_api::RenderApi::shut_down
   9: canvas::webgl_thread::WebGLThread::process
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: std::sys::pal::unix::thread::Thread::new::thread_start
  13: start_thread
  14: __GI___clone3
[2025-01-06T14:26:24Z ERROR servoshell::panic_hook] called `Result::unwrap()` on an `Err` value: RecvError
```

**To Reproduce:**
1.  `./mach run` to open servo.org with minibrowser
2. Click 'Demos' to open demo.servo.org in a new tab
3. Open the 'TWGL Tunnel' demo
4. Switch back to servo.org
5. Close the servo window

This should panic with the above backtrace.

**Platform:**
Observed on Linux (X11, KDE). I have not tested on other platforms.

### PR DESCRIPTION
**Pull request by mukilan**
Fixes #34847.

Signed-off-by: Mukilan Thiyagarajan <mukilan@igalia.com>

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #34847

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

File: components/canvas/webgl_thread.rs [hunk 1]
```diff
@@ -30,6 +30,7 @@ use glow::{
     NativeVertexArray, PixelUnpackData, ShaderPrecisionFormat,
 };
 use half::f16;
+use ipc_channel::ipc::IpcSender;
```
Comment (jdm) [inline components/canvas/webgl_thread.rs:33]:
```suggestion
```

**Review by jdm — APPROVED** [review]
