### PR TITLE
script: fix spurious animation checks to correctly invoke rAF callbacks

### LINKED ISSUE #35386: Spurious animation frames optimatization breaks `rAF` based animations in some scenarios.
**Describe the bug:**
In some scenarios, Servo's logic to detect spurious animation frames breaks animations using `rAF` callbacks. This causes the application to page 'unresponsive' or 'frozen'. I noticed this while testing this [Canvas and WebGL based demo](https://blits-demo.lightningjs.io/#/demos/tmdb) for #34488 on top of my PR #35262.

I was able to reduced the reproducer:

**To Reproduce:**
Run the below html `./mach run -r test.html`
test.html:
```html
<!DOCTYPE html>
<div id=t>not ready</div>
<script>
        let frames = 0;
        let draw = (t) => {
                frames += 1;
                if (frames < 6) {
                        requestAnimationFrame(draw);
                } else if (frames == 6) {
                        // don't schedule next rAF so Servo stops
                        // the compositor callbacks
                        setTimeout(() => {
                                requestAnimationFrame(draw);
                        }, 10);
                } else {
                        document.getElementById('t').innerText = t;
                        requestAnimationFrame(draw);
                }

        };
        requestAnimationFrame(draw);
</script>
```

On FireFox and Chromium, the animation ticks continually after a small initial delay, while in Servo it stops updating after ~120ms.

### PR DESCRIPTION
**Pull request by mukilan**
After running an `rAF` callback, if no new callbacks were registered, we send a `NoAnimationFramesCallback` to the compositor to stop ticking animations using video refresh callbacks. This interacts badly with the mechanism to track spurious animations frames i.e. rAF callbacks that don't mutate the DOM. Such 'faked' rAF callbacks are triggered by registering a oneshot timer instead of the compositor callback.

The compositor's refresh callback is never enabled back again once a non-spurious rAF callback runs and registers a new rAF callback. If the former callback resets the `spurious_animations_frames` counter, then when the latter rAF callback runs, it will not schedule a OneShotTimer timer for any rAF callback that itself registers, since the counter was reset previously. Hence that third rAF callback that never runs as it relies on the compsitor's refresh callback, which was disabled previously.

The current logic also doesn't actually recognize spurious animation frames because the `spurious_animations_frames` counter is updated at the end of the `run_the_animation_frame_callbacks`, effectively meaning `was_faking_animation_frames` and `self.is_faking_animation_frames` will always be the same value but the logic effectively only runs when `(!was_faking && is_faking)` is true.

This patch fixes the logic to detect spurious animations frames by moving logic to update the counter to be before the check for spurious frames. It also ensures that the compositor's refesh callbacks is re-enabled once we see a non-spurious callback.

Fixes #35386

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #35386
- [x] There are tests for these changes

### CODE REVIEW

File: components/script/dom/document.rs [hunk 1]
```diff
@@ -2316,6 +2320,16 @@ impl Document {
...
 
+        // Update the counter of spurious animation frames.
+        if callbacks_did_not_trigger_reflow {
+            if self.spurious_animation_frames.get() < SPURIOUS_ANIMATION_FRAME_THRESHOLD {
+                self.spurious_animation_frames
+                    .set(self.spurious_animation_frames.get() + 1)
+            }
+        } else {
+            self.spurious_animation_frames.set(0);
+        }
```
[the remark this answers is not in the document]
Comment (mukilan) [reply components/script/dom/document.rs]: Good point, this can be rewritten to be simpler.  `current_frames` seemed misleading, so I've used `spurious_frames` as the name instead in fb2f56b.

Thanks!

File: tests/wpt/tests/html/webappapis/animation-frames/spurious-frame-callbacks-optimization.html [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+    <div id="target">0</div>
+</body>
+<script>
+"use strict";
+let frame = 0;
+const draw = (t) => {
+  frame += 1;
+  if (frame < 11) {
+    // Don't mutate the DOM for 10 frames to meet the threshold for the
+    // spurious frame optimization to kick in.
```
Comment (mrobinson) [inline tests/wpt/tests/html/webappapis/animation-frames/spurious-frame-callbacks-optimization.html:18]:
```suggestion
    // Don't mutate the DOM for 10 frames to meet the threshold for Servo's
    // spurious frame optimization to kick in.
```

File: tests/wpt/tests/html/webappapis/animation-frames/spurious-frame-callbacks-optimization.html [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+    requestAnimationFrame(draw);
+  } else if (frame == 11) {
+    // Don't schedule next rAF so the compositor's tick is disabled.
+    // This is specific to Servo as the spurious frame detection at the
+    // time of this test was broken.
```
Comment (mrobinson) [inline tests/wpt/tests/html/webappapis/animation-frames/spurious-frame-callbacks-optimization.html:23]: Might want to clarify here that this behavior is Servo-specific as well.

**Review by mrobinson — APPROVED** [review]
