### PR TITLE
webdriver: Keep constellation alive and Open new top-level browsing context with new session request when none is open

### LINKED ISSUE #37408: [WebDriver] Constellation already dead when last browsing context closed
**Describe the bug:**
https://github.com/servo/servo/blob/73c2864233f8f27e61a1389e3dbacb83fe2e1d45/tests/wpt/tests/webdriver/tests/classic/close_window/close.py#L70-L81

Test 1 may close all browsing contexts. Soon, it runs Test 2, which starts a new session and try to reach constellation, which is already dead.

``` 
0:06.19 pid:17316 [2025-06-12T07:02:02Z INFO  webdriver_server] CloseWindow
 0:06.19 pid:17316 [2025-06-12T07:02:02Z DEBUG webdriver::server] Last window was closed, deleting session
 0:06.19 pid:17316 [2025-06-12T07:02:02Z DEBUG webdriver::server] Teardown session
 0:06.19 pid:17316 [2025-06-12T07:02:02Z INFO  webdriver_server] DeleteSession
 0:06.19 pid:17316 [2025-06-12T07:02:02Z DEBUG webdriver::server] <- 200 OK {"value":[]}
 0:06.19 INFO STDOUT: PASSED
 0:06.19 INFO STDOUT: tests\wpt\tests\webdriver\tests\classic\close_window\close.py::test_element_usage_after_closing_browsing_context
 0:06.19 pid:17316 [2025-06-12T07:02:02Z DEBUG webdriver::server] -> POST /session {"capabilities": {"alwaysMatch": {}}}
 0:06.19 pid:17316 [2025-06-12T07:02:02Z INFO  webdriver_server] NewSession(NewSessionParameters { capabilities: SpecNewSessionParameters { alwaysMatch: {}, firstMatch: [{}] } })
 0:06.19 pid:17316 [2025-06-12T07:02:02Z DEBUG webdriver_server] Getting focused context.
```

**To Reproduce:**
`./mach test-wpt -r --log-raw "D:\servo test log\close.txt" .\tests\wpt\tests\webdriver\tests\classic\close_window\close.py --product servodriver`

**Platform:**
Linux + Windows

### PR DESCRIPTION
**Pull request by yezhizhen**
Keep Constellation alive even when all browsing context closed in WebDriver mode. In this case, when creating a new session, we would open a new top-level browsing context.

Fixes: #37408
Testing: `./mach test-wpt -r .\tests\wpt\tests\webdriver\tests\classic\close_window\close.py --product servodriver`

### CODE REVIEW

File: components/servo/lib.rs [hunk 1]
```diff
@@ -732,6 +738,9 @@ impl Servo {
                     let _ = response_sender.send(webview_id_and_viewport_details);
                 }
             },
+            EmbedderMsg::OpenNewTopLevelWebview => {
+                self.RunningAppState.new_toplevel_webview();
```
Comment (yezhizhen) [inline components/servo/lib.rs]: Need help: How can I create a new top level browsing context from here? 
I see that most other commands are done through delegate, but there is no delegate here because all tabs are closed.. Also `new_toplevel_webview` is not part of `WebViewDelegate` trait..
cc @mrobinson @jdm @delan 
The RunningAppState has handle to Servo, but not the other way around.

**Comment by yezhizhen** [comment]
cc @xiaochengh

File: components/servo/lib.rs (hunk 1 above)
Comment (yezhizhen) [reply components/servo/lib.rs]: The Constellation won't die now when all tabs closed.. But I need help above. 

https://github.com/user-attachments/assets/1823c687-fafc-4cb7-b5a6-9c8ddb2b5dc6

In the video, when I manually open a new tab after all tab is closed, the test would pass now.

~One **ugly** but working idea is to open a new auxiliary window instead (need to allow empty opener), and then focus it... But I want to do this elegantly.~ We can't do this because there is no living WebView (delegate) anymore!!

**Comment by mrobinson** [comment]
Hrm...These are the sort of things that could be addressed by moving WebDriver to servoshell. Is there anyway we can prioritize that and then we wouldn't need these workarounds?

**Comment by xiaochengh** [comment]
+1 to @mrobinson

**Comment by yezhizhen** [comment]
@longvatrong111 What do you think? Need your assistance about the moving part :)

**Comment by longvatrong111** [comment]
> Hrm...These are the sort of things that could be addressed by moving WebDriver to servoshell. Is there anyway we can prioritize that and then we wouldn't need these workarounds?

Yes moving webdriver make many commands in [Navigation](https://www.w3.org/TR/webdriver2/#navigation) and [Context](https://www.w3.org/TR/webdriver2/#contexts) simpler.
The only disadvantage I know so far is `browsing context`, since `Embedder` doesn't contain details about `browsing contexts` of `webview` now. 
So for most commands, event route is "webdriver -> main -> response to webdriver", for "browsing context", it's "webdriver -> main -> constellation -> webdriver"

Btw, can you take a look at:
https://github.com/servo/servo/pull/36714

p/s: we need to enable webdriver conformance test in the CI before making this change

**Comment by yezhizhen** [comment]
> p/s: we need to enable webdriver conformance test in the CI before making this change

But we can solve many panic issues if this change is made, tho I am not really sure which one has higher priority.

**Comment by xiaochengh** [comment]
The approach in this PR looks really hacky to me.

Let's see if we can finish the WebDriver to ServoShell move soon.

**Comment by yezhizhen** [comment]
> The approach in this PR looks really hacky to me.

@xiaochengh 
https://github.com/servo/servo/pull/37373 Btw I also have another hacky (according to @simonwuelker ) PR🤣Also related to focus issue..

**Comment by longvatrong111** [comment]
> > p/s: we need to enable webdriver conformance test in the CI before making this change
> 
> But we can solve many panic issues if this change is made, tho I am not really sure which one has higher priority.

Yes this PR can make webdriver test more stable, which required to enable webdriver test in CI then make huge change,  it's the first option.
Another option is we run the CI manually or skip unstable test.

**Comment by xiaochengh** [comment]
Usually we land a hacky fix only if:
1. It's urgency (eg causing issues to users), and will be properly addressed later
2. The root cause is very hard to fix and therefore not planned to fix

Otherwise we should fix the root cause.

**Comment by longvatrong111** [comment]
@yezhizhen I think now you can re-open this PR again:
Webdirver uses this function to close webview.
We can add an option to this function to keep Servo alive even when the last webview is closed.

https://github.com/servo/servo/blob/8a0bb0319cc268bed09fb84495e237a821d354e6/ports/servoshell/desktop/app_state.rs#L222-L246

File: ports/servoshell/desktop/app.rs [hunk 2]
```diff
@@ -402,8 +402,19 @@ impl App {
                         warn!("Failed to send response of GetViewportSize: {error}");
                     }
                 },
+                // This is only received when start new session.
                 WebDriverCommandMsg::GetFocusedWebView(sender) => {
-                    let focused_webview = running_state.focused_webview();
+                    // This can be called when there is no open webview.
+                    // We need to create a new one. See https://github.com/servo/servo/issues/37408
+                    let focused_webview =
```
Comment (longvatrong111) [inline ports/servoshell/desktop/app.rs]: In case we want a new webview, why don't we call `NewWebview`?

Comment (xiaochengh) [reply ports/servoshell/desktop/app.rs]: Is it possible if there are open webviews but none is focused?

Btw a getter shouldn't do more than getting something. If a valid result must be ensured, it should be renamed to `EnsuredFocusedWebView`.

Comment (yezhizhen) [reply ports/servoshell/desktop/app.rs:409]: > Is it possible if there are open webviews but none is focused?

Yes. `fn focused_webview` returns `Option<WebView>`

Comment (yezhizhen) [reply ports/servoshell/desktop/app.rs]: > In case we want a new webview, why don't we call `NewWebview`?

We can. But that introduces another RTT, since we are already at embedder.

Comment (yezhizhen) [reply ports/servoshell/desktop/app.rs]: > Is it possible if there are open webviews but none is focused?

Yes. `fn focused_webview` returns `Option<WebView>`

But for webdriver, we always want a focused webview for a new session.
That's why we [need retry](https://github.com/servo/servo/pull/37506#issuecomment-2982943374) as a workaround before&now.

Comment (yezhizhen) [reply ports/servoshell/desktop/app.rs]: > it should be renamed to EnsuredFocusedWebView.

Indeed, eventually we do want a ensured focused webview, even tho it is bugged right now..

Guess will just rename it and add FIXME.

Comment (xiaochengh) [reply ports/servoshell/desktop/app.rs]: I'm also inclined to calling `NewWebView` from WebDriver when there are no open webviews. Reasons below:

1. One extra round of IPC per session shouldn't create too much delay. This part doesn't seem to be performance sensitive.
2. IIUC the correct semantics here is "ensure focused webview for new session". But there's probably no good way to enforce that in the code, leading to maintenance risks

Comment (yezhizhen) [reply ports/servoshell/desktop/app.rs]: 1. I guess we need to change the enum variant `GetFocusedWebView` from `IpcSender<Option<WebViewId>>` to `IpcSender<GetFocusedWebViewResult>` then?

2. Create a new Enum `GetFocusedWebViewResult`:

```rust
enum GetFocusedWebViewResult {
    WebViewId(WebViewId),
    NoFocused, // Fix this bug then we can remove this.
    NoOpenWindow
}
```
3. When server receives `GetFocusedWebViewResult::NoOpenWindow`, **create a new IPC channel for** `WebDriverCommandMsg::NewWebView` as we cannot reuse the old one due to different types.

But above feels even harder to maintain...

Comment (longvatrong111) [reply ports/servoshell/desktop/app.rs]: I guess the purpose of creating a new webview here is to fix this: https://github.com/servo/servo/pull/36330#issue-2971361781.

1. According to the comment, the root cause is `constellation` can't return a `focused webview` at the right time. But now, we get `focused webview` from `embedder`. For my testing, I can't  see the problem anymore:
https://github.com/longvatrong111/servo/actions/runs/15869168577
https://github.com/longvatrong111/servo/actions/runs/15869166772
https://github.com/longvatrong111/servo/actions/runs/15869057433
https://github.com/longvatrong111/servo/actions/runs/15869058865

2. Even if the issue still occurs, I feel like this is another work around. Because when we create a new session, a focus webview is supposed to exist. We should find out why we can't get the focused webview, instead of creating a new one. That way will hide the bug (if we really need to do it, let us add a FIXME to remove this part later)
In case we know for sure there is no webview, can explicitly call `NewWebView`.
 
3. Actually, we don't need a `focused webview`, we can take any webview for `webdriver`.
https://www.w3.org/TR/webdriver2/#new-session (step 8)

File: components/webdriver_server/lib.rs [hunk 3]
```diff
@@ -518,7 +518,7 @@ impl Handler {
 
     fn focus_webview_id(&self) -> WebDriverResult<WebViewId> {
```
Comment (mrobinson) [inline components/webdriver_server/lib.rs]: I think this method has been accidentally misnamed. `focus_webview_id` is a request to focus a WebView, but `focused_webview_id` is a getter to retrieve the currently focused `WebViewId`.
```suggestion
    fn focus_webview_id(&self) -> WebDriverResult<WebViewId> {
```

File: ports/servoshell/desktop/app_state.rs [hunk 4]
```diff
@@ -151,6 +152,10 @@ impl RunningAppState {
         &self.servo
     }
 
+    pub(crate) fn no_open_webview(&self) -> bool {
+        self.inner().webviews.is_empty()
+    }
+
```
Comment (mrobinson) [inline ports/servoshell/desktop/app_state.rs]: I would flip this:

```suggestion
    pub(crate) fn has_webview(&self) -> bool {
        ~self.inner().webviews.is_empty()
    }

```

File: ports/servoshell/desktop/app_state.rs [hunk 5]
```diff
@@ -268,7 +273,13 @@ impl RunningAppState {
 
         match last_created {
             Some(last_created_webview) => last_created_webview.focus(),
-            None => self.servo.start_shutting_down(),
+            None => {
+                // For WebDriver, don't shutdown when last webview closed
```
Comment (mrobinson) [inline ports/servoshell/desktop/app_state.rs]: Super nit:

```suggestion
                // For WebDriver, don't shut down when last webview closed
```

File: ports/servoshell/desktop/app_state.rs [hunk 6]
```diff
@@ -268,7 +273,13 @@ impl RunningAppState {
 
         match last_created {
             Some(last_created_webview) => last_created_webview.focus(),
-            None => self.servo.start_shutting_down(),
+            None => {
```
Comment (mrobinson) [inline ports/servoshell/desktop/app_state.rs:278]:
```suggestion
            None if opts::get().webdriver_port.is_none() => self.servo.start_shutting_down(),
            None => {},
```

**Review by mrobinson — CHANGES_REQUESTED** [review]
A couple drive by comments while you all resolve this issue.

I agree that simpler building blocks in the API makes sense, even if that means sending two IPC messages instead of one.

File: components/webdriver_server/lib.rs [hunk 7]
```diff
@@ -574,7 +568,20 @@ impl Handler {
         } else {
             match processed_capabilities {
                 Some(mut processed) => {
-                    let webview_id = self.focus_webview_id()?;
+                    let webview_id = match self.focused_webview_id()? {
+                        Some(webview_id) => webview_id,
+                        None => {
+                            // This can be called when there is no open webview.
```
Comment (longvatrong111) [inline components/webdriver_server/lib.rs]: Let's create a webview and focus it using 2 messages `NewWebView` and `FocusWebView`.

File: ports/servoshell/desktop/app.rs [hunk 8]
```diff
@@ -366,14 +366,19 @@ impl App {
                     running_state.servo().execute_webdriver_command(msg);
                 },
                 WebDriverCommandMsg::NewWebView(response_sender, load_status_sender) => {
-                    let new_webview =
-                        running_state.create_toplevel_webview(Url::parse("about:blank").unwrap());
+                    let url = Url::parse("about:blank").unwrap();
```
Comment (longvatrong111) [inline ports/servoshell/desktop/app.rs]: Always create a webview without focusing it here.
Set a load status sender if it exist.

File: ports/servoshell/desktop/app_state.rs [hunk 9]
```diff
@@ -127,10 +127,11 @@ impl RunningAppState {
         }
     }
 
-    pub(crate) fn create_and_focus_toplevel_webview(self: &Rc<Self>, url: Url) {
+    pub(crate) fn create_and_focus_toplevel_webview(self: &Rc<Self>, url: Url) -> WebView {
         let webview = self.create_toplevel_webview(url);
```
Comment (longvatrong111) [inline ports/servoshell/desktop/app_state.rs]: Change this to focus webview with id.

File: components/shared/embedder/webdriver.rs [hunk 10]
```diff
@@ -144,17 +144,17 @@ pub enum WebDriverCommandMsg {
...
+    /// load is complete if Load Status Sender is provided.
+    NewWebView(IpcSender<WebViewId>, Option<IpcSender<WebDriverLoadStatus>>),
     /// Close the webview associated with the provided id.
     CloseWebView(WebViewId),
     /// Focus the webview associated with the provided id.
     /// Sends back a bool indicating whether the focus was successfully set.
     FocusWebView(WebViewId, IpcSender<bool>),
-    /// Get focused webview.
+    /// Get focused webview. This is only used when start new session.
     GetFocusedWebView(IpcSender<Option<WebViewId>>),
```
Comment (longvatrong111) [inline components/shared/embedder/webdriver.rs:159]: Just keep the old comment, we may need to use this msg later for other command.

**Review by longvatrong111 — COMMENTED** [review]
I feel it's a bit hard for me to use `NewWebView` with current modification. A `load status sender` param will determine whether the newly created webview is focus or not seems confusing.
I realize you just added `FocusWebView` in 1 of your previous PRs.
Let's break down `NewWebView`.

File: ports/servoshell/desktop/app.rs (hunk 8 above)
Comment (yezhizhen) [reply ports/servoshell/desktop/app.rs]: Thanks. That's very clear!

**Review by longvatrong111 — APPROVED** [review]

**Review by xiaochengh — APPROVED** [review]

File: components/webdriver_server/lib.rs [hunk 11]
```diff
@@ -2423,6 +2426,18 @@ impl Handler {
             Ok(())
         }
     }
+
+    fn focus_webview(&self, webview_id: WebViewId) -> Result<(), WebDriverError> {
+        let (sender, receiver) = ipc::channel().unwrap();
+        let msg = WebDriverCommandMsg::FocusWebView(webview_id, sender);
+        self.send_message_to_embedder(msg)?;
```
Comment (mrobinson) [inline components/webdriver_server/lib.rs]: Nit, no need for a temporary.
```suggestion
        self.send_message_to_embedder(WebDriverCommandMsg::FocusWebView(webview_id, sender)?;
```

**Review by mrobinson — APPROVED** [review]

**Comment by yezhizhen** [comment]
Rebased, resolved conflict with #38225 and updated tests.
