### PR TITLE
Fix unsafe AtomicRefCell<T>  transmutes in Layout component

### LINKED ISSUE #16817: Unsafe AtomicRefCell<T> transmute in Layout component
Hi,

I'm fixing Android SEGV crashes on Servo (see https://github.com/servo/servo/pull/16816) and found that one of them is caused by a highly unsafe cast between ` AtomicRefCell<PersistentLayoutData>` and` AtomicRefCell<PartialPersistentLayoutData> `
```

impl<T: LayoutNode> LayoutNodeHelpers for T {
    fn initialize_data(&self) {
        if self.get_raw_data().is_none() {
            let ptr: *mut NonOpaqueStyleAndLayoutData =
                Box::into_raw(box AtomicRefCell::new(PersistentLayoutData::new()));
            let opaque = OpaqueStyleAndLayoutData {
                ptr: unsafe { NonZero::new(ptr as *mut AtomicRefCell<PartialPersistentLayoutData>) }
            };
            unsafe { self.init_style_and_layout_data(opaque) };
        };
    }
}
```
Even after adding the required repr(C) to guarantee the memory consistency between pure PersistentLayoutData and PartialPersistentLayoutData structs, the cast between both structs contained in AtomicRefCell<T> is unsafe. The problem is that memory alignment is not guaranteed even using C layout because memory alignment may be different between fields in both templates when the structs are contained in the parent [AtomicRefCell](https://github.com/bholley/atomic_refcell/blob/master/src/lib.rs#L59)  (AutomicUsize + RefCell<T>)

I checked the pointer addresses on Android before and after the `ptr as *mut AtomicRefCell<PartialPersistentLayoutData>` by calling and printing AtomicRefCell.as_ptr(). The new pointer address after the transmute is 4 bytes misplaced from the real one. So this leads to some SEGV crashes. On Desktop linux (64 bits) the pointers addresses are equal.

I checked adding a combined` repr(C, packed) ` macro to PartialPersitentData or AtomicRefCell and with that representation the pointers are equal on Android too.

Adding packed representation is not the best solution because it can have other side-effects. Adding a new level of indirection is another solution but it can cause more overhead. Maybe adding a dummy struct to match the alignment (protected with a static assert) or rewriting this part of the code is the best solution. What do you think?

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes unsafe transmute between `AtomicRefCell<PersistentLayoutData>` and `AtomicRefCell<PartialPersistentLayoutData>` which have different memory alignment in 32 bit archs leading to SEGV crashes. See https://github.com/servo/servo/issues/16817 and https://github.com/servo/servo/pull/16816

mem::align_of values in 32 bit archs (e.g. Android):
```
PersistentLayoutData 8
PersistentLayoutData 4
AtomicRefCell<PersistentLayoutData> 8
AtomicRefCell<PartialPersistentLayoutData> 4
```
mem::align_of values in 64 bit archs
```
PersistentLayoutData 8
PersistentLayoutData 8
AtomicRefCell<PersistentLayoutData> 8
AtomicRefCell<PartialPersistentLayoutData> 8
```

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #16817 (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16833)

### CODE REVIEW

File: components/script_layout_interface/lib.rs [hunk 1]
```diff
@@ -59,13 +60,27 @@ pub struct PartialPersistentLayoutData {
 
     /// Information needed during parallel traversals.
     pub parallel: DomParallelInfo,
+
+    // Required alignment in 32 bit architectures for safe
+    // transmute between PersistentLayoutData and PartialPersistentLayoutData.
+    #[cfg(target_pointer_width = "32")] _align: u64
```
Comment (SimonSapin) [inline components/script_layout_interface/lib.rs]: Why not have this dummy field unconditionally?

Comment (emilio) [inline components/script_layout_interface/lib.rs]: Or, better yet, make it a `[u64; 0]`, which affects alignment without size penalties.

Comment (MortimerGoro) [inline components/script_layout_interface/lib.rs]: I did that way as a size optimization. Do you think that it isn't worth it?

Comment (MortimerGoro) [inline components/script_layout_interface/lib.rs]: @emilio nice! I didn't know that

**Comment by SimonSapin** [comment]
Nice one @emilio, for `[u64; 0]` :)

@bors-servo r+
