### PR TITLE
Throw `SyntaxError` from `Location::SetHref`

### LINKED ISSUE #39050: `Location::SetHref` should throw a SyntaxError exception
This should fix `tests/wpt/tests/url/failure.html` completely: https://wpt.fyi/results/url/failure.html?label=master&label=experimental&product=servo&aligned

### PR DESCRIPTION
**Pull request by arihant2math**
It was originally throwing a TypeError, which was making WPT fail.

Testing: Many happy WPT subtests
Fixes: #39050

### CODE REVIEW

File: components/script/dom/location.rs [hunk 1]
```diff
@@ -413,13 +413,14 @@ impl LocationMethods<crate::DomTypeHolder> for Location {
         if self.has_document() {
             // Note: no call to self.check_same_origin_domain()
             // Step 2: Parse the given value relative to the entry settings object.
```
Comment (sagudev) [inline components/script/dom/location.rs]:
```suggestion
            // Step 2: Let url be the result of encoding-parsing a URL given the given value, relative to the entry settings object.
```

File: tests/wpt/meta/html/browsers/browsing-the-web/navigating-across-documents/empty-iframe-load-event.html.ini
Comment (sagudev) [inline tests/wpt/meta/html/browsers/browsing-the-web/navigating-across-documents/empty-iframe-load-event.html.ini:1]: This is intermittent failure: https://github.com/servo/servo/issues/29066, so I think we should remove expectations here.

File: components/script/dom/location.rs [hunk 2]
```diff
@@ -413,13 +413,14 @@ impl LocationMethods<crate::DomTypeHolder> for Location {
...
-            // If that failed, throw a TypeError exception.
+            // Step 3: If url is failure, then throw a "SyntaxError" DOMException.
             let base_url = self.entry_settings_object().api_base_url();
             let url = match base_url.join(&value.0) {
                 Ok(url) => url,
-                Err(e) => return Err(Error::Type(format!("Couldn't parse URL: {}", e))),
+                // TODO: include details?
+                Err(_e) => return Err(Error::Syntax),
```
Comment (sagudev) [inline components/script/dom/location.rs]: This is problem with our error types as they do not support writing any messages.

Comment (sagudev) [reply components/script/dom/location.rs]: I opened #39053 about this.

**Review by jdm — APPROVED** [review]
