### PR TITLE
layout: Stop clearing floats on anonymous blocks for intrinsic sizes

### LINKED ISSUE #41280: Anonymous block boxes shouldn't clear floats when computing intrinsic sizes
**Describe the bug:**
See example. Note that removing `position:absolute` from the test case fixes the behaviour.

**To Reproduce:**
Test case
```
<!doctype html>
<div style="position:absolute;top:5px;left:5px;border:1px solid red">
<div style="float:left;border:1px solid black">Price</div>: $10.00</div>
</div>
```
Servo
Image
FF
Image

**Platform:**
Windows 10.

### PR DESCRIPTION
**Pull request by Loirooriol**
When computing the intrinsic sizes of a block container which doesn't establish an inline formatting context, block-level children which don't establish an independent formatting context clear floats. That's because these blocks overlap the floats instead of being placed next to them.

However, we shouldn't do that if the block-level child is an anonymous box that establishes an inline formatting context. This matches what other browsers do.

Testing: 4 tests are now passing
Fixes: #41280

### CODE REVIEW

File: components/layout/flow/mod.rs [hunk 1]
```diff
@@ -516,8 +519,14 @@ fn compute_inline_content_sizes_for_block_level_boxes(
                 );
                 // A block in the same BFC can overlap floats, it's not moved next to them,
                 // so we shouldn't add its size to the size of the floats.
-                // Instead, we treat it like an independent block with 'clear: both'.
-                Some((inline_content_sizes_result, None, Clear::Both))
+                // Instead, we treat it like an independent block with 'clear: both',
+                // except if it's an anonymous block.
```
Comment (mrobinson) [inline components/layout/flow/mod.rs:523]: Might be worth linking to this issue or an explanation of why other browsers do it.

**Review by mrobinson — APPROVED** [review]
Nice!

File: components/layout/flow/mod.rs (hunk 1 above)
Comment (Loirooriol) [reply components/layout/flow/mod.rs:523]: I guess it's because the inline-level contents are placed next to floats. But the same could be said about a non-anonymous block which establishes an inline formatting context. So it's a bit arbitrary
