### PR TITLE
storage: fix incorrect data sharing by passing document origin to storage thread

### LINKED ISSUE #44001: localStorage in about:srcdoc is shared across unrelated origins
As discovered in https://github.com/servo/servo/issues/42924#issuecomment-4194059185 and https://github.com/servo/servo/issues/42924#issuecomment-4200052921, we are incorrectly sharing the storage data between any document with a URL that has an opaque origin. #43988 should fix this by ensuring we don't pass opaque origins to the storage thread when using storage APIs from about:srcdoc documents, but writing a test that demonstrates that it's fixed is a bit trickier.

### PR DESCRIPTION
**Pull request by niyabits**
Changes all the uses of `ServoUrl` to `ImmutableOrigin` in `WebStorageThreadMsg`

Testing: Adds a test case as described in the issue.

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
</head>

<body>
  <main>
    <h1>Tab and Program crashes!</h1>
    <iframe srcdoc="
          <body>
            <p>Hello Web users! <br/> I am an iframe, <br /> I set a key and then retreive it. </p> 
            <script>
              for (let i = 0; i < 1000; i++) {
                window.localStorage.setItem('truth', 'Servo is awesome! 🌐')
                const example = window.localStorage.getItem('truth')
                
                console.log(example === 'Servo is awesome! 🌐')
              }
            </script>
          </body> 
          "></iframe>
  </main>
</body>

</html>

```

Fixes: #44001

### CODE REVIEW

File: components/storage/webstorage/mod.rs [hunk 1]
```diff
@@ -594,14 +594,14 @@ impl WebStorageManager {
         sender: GenericSender<Option<String>>,
         storage_type: WebStorageType,
         webview_id: WebViewId,
-        url: ServoUrl,
+        url: ImmutableOrigin,
         name: String,
     ) {
-        let data = self.select_data_mut(storage_type, webview_id, url.origin());
+        let data = self.select_data_mut(storage_type, webview_id, url.clone());
```
Comment (niyabits) [inline components/storage/webstorage/mod.rs]: I have used `.clone()` method here because the previous, `url.origin()` method was creating a new `ImmutableOrigin` every time it is called:

https://github.com/servo/servo/blob/main/components/url/lib.rs#L90-L92
```rust
    pub fn origin(&self) -> ImmutableOrigin {
        ImmutableOrigin::new(self.0.origin())
    }
```

**Comment by niyabits** [comment]
I noticed the failing tests, and I will update them once my PR fixes the issue.

**Comment by niyabits** [comment]
@jdm I read the issue #43988

I think I will do the test case in a separate PR as it is a bit more complex.
I have updated the test cases and the CI is all green, the PR is ready for review :)

**Comment by jdm** [comment]
Hmm. We have a policy that code changes that change behaviour should be accompanied by tests that verify the behaviour change. I can't think of any way to write a unit test for this change, so I think we should wait to merge it until the WPT test exists.

File: components/script/dom/storage.rs [hunk 2]
```diff
@@ -56,6 +56,10 @@ impl Storage {
         self.global().get_url()
     }
 
+    fn get_immutable_origin(&self) -> ImmutableOrigin {
+        self.global().get_url().origin()
```
Comment (jdm) [inline components/script/dom/storage.rs]: This is not the correct origin, and the WPT test will fail until we use the correct one :)

File: components/storage/webstorage/mod.rs [hunk 3]
```diff
@@ -517,9 +517,9 @@ impl WebStorageManager {
         sender: GenericSender<Vec<String>>,
         storage_type: WebStorageType,
         webview_id: WebViewId,
-        url: ServoUrl,
+        url: ImmutableOrigin,
```
Comment (jdm) [inline components/storage/webstorage/mod.rs]: We should rename these arguments to `origin` for clarity.

File: components/script/dom/storage.rs (hunk 2 above)
Comment (niyabits) [reply components/script/dom/storage.rs]: Thank You!

I believe I should use this instead:
```rust
self.global().origin().immutable().clone()
```

I assume this is because when I create an origin with `get_url()` it is based on the global scope URL.
While in some instances we might need an opaque origin that can be created by calling `origin()` on global.

I am still learning :)

Comment (jdm) [reply components/script/dom/storage.rs]: That's mostly correct! It's not that we need to pass an opaque origin to the storage thread; it's that URLs like `about:srcdoc` only have an opaque origin, but the actual document that's loaded inherits the non-opaque origin from the document that created it, and _that_ is the origin that we should be sending to the storage thread.

**Comment by niyabits** [comment]
@jdm I rebased this PR against main and the test (#44038) is still failing.

I tried adding a `console.log` here:
```javascript
  const value = window.localStorage.getItem('test');
  console.log(value)
  const pageURL = get_host_info().HTTP_ORIGIN;
```
File for reference:
https://github.com/servo/servo/blob/99c53f8cdf998f34bfc2bfeb7828b2d4218d7d35/tests/wpt/tests/webstorage/resources/localstorage_origin_page_two.html#L7-L8

And I could see the value 'user' being logged. 
The iframe is still sharing the localstorage.

**Comment by jdm** [comment]
Oh, I missed that you changed this line in the main test page:
`const pageURL = get_host_info().HTTP_REMOTE_ORIGIN + "/webstorage/resources/localstorage_origin_page_two.html";`

That means that the two pages are sharing the same origin.

Edit: No, nevermind, it's just late at night and I'm misreading things.

**Comment by jdm** [comment]
When I run the test after building on this branch, I see:
```
 0:05.21 TEST_END: Test OK. Subtests passed 1/1. Unexpected 1
UNEXPECTED-PASS Ensure two about:srcdoc origins cannot share localstorage
```
So that looks like it's working to me?

**Comment by niyabits** [comment]
@jdm oops, I forgot to build Servo after switching the branch.

The test passes now :)
I have updated the test expectations. 

Thank you for all the help and the review!

**Review by jdm — APPROVED** [review]
Hooray! Thanks for sticking with this.
