### PR TITLE
Make ImageData more spec compliant

### LINKED ISSUE #37618: Crash in imagedata due to typed array
While testing vello I get this: 
```
Process 112668 stopped
* thread #45, name = 'Script(1,1)', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
    frame #0: 0x000055555aa10dd2 servo`js::UnwrapUint8ClampedArray(JSObject*) + 18
servo`js::UnwrapUint8ClampedArray:
->  0x55555aa10dd2 <+18>: movq   (%rax), %rdx
    0x55555aa10dd5 <+21>: cmpq   %rbx, %rdx
    0x55555aa10dd8 <+24>: jae    0x55555aa10de6 ; <+38>
    0x55555aa10dda <+26>: leaq   -0x480(%rbx), %rax
```

src line: https://github.com/servo/servo/blob/2b209449b59de5e7569d168fd8cfd0d6cbeaee5c/components/script/dom/imagedata.rs#L81

removing this lines makes it work:
```
let data = CreateWith::Slice(&d[..]);
Uint8ClampedArray::create(*cx, data, js_object.handle_mut()).unwrap();
```

although I think whole part needs to be rewritten to use HeapBufferSource to avoid unsafe.

### PR DESCRIPTION
**Pull request by sagudev**
I updated webidl, and all changes that bring, currently we still not support float16array (there is no support in FF either). Most notable change is refactored new_*/Constructors methods, that should now handle HeapBufferSource more properly (with less unsafe).

Testing: Existing WPT tests
try run: https://github.com/sagudev/servo/actions/runs/15806083404
Fixes: #37618 (although not tested)

### CODE REVIEW

**Comment by gterzian** [comment]
> that should now handle HeapBufferSource more properly (with less unsafe).

Sounds like a good one for @Taym95 to review.

File: components/script/dom/imagedata.rs [hunk 1]
```diff
@@ -229,4 +267,14 @@ impl ImageDataMethods<crate::DomTypeHolder> for ImageData {
     fn GetData(&self, _: JSContext) -> Fallible<Uint8ClampedArray> {
         self.data.get_typed_array().map_err(|_| Error::JSFailed)
     }
+
+    /// <https://html.spec.whatwg.org/multipage/#dom-imagedata-pixelformat>
```
Comment (gterzian) [inline components/script/dom/imagedata.rs:288]: The link here, and the one below, seem wrong, but the problem is in the spec.

File: components/script/dom/imagedata.rs [hunk 2]
```diff
@@ -47,122 +51,92 @@ impl ImageData {
...
-
-        let imagedata = Box::new(ImageData {
-            reflector_: Reflector::new(),
-            width,
-            height,
-            data: heap_typed_array,
-        });
+        // 1. If source was given:
+        let data = if let Some(source) = source {
+            HeapBufferSource::<ClampedU8>::from_view(source)
```
Comment (gterzian) [inline components/script/dom/imagedata.rs:96]: This seems to be missing the first two checks, and you may also want to add a doc for "// 1.3 Initialize the data attribute of imageData to source"

File: components/script/dom/imagedata.rs [hunk 3]
```diff
@@ -47,122 +51,92 @@ impl ImageData {
...
+        } else {
+            // 2. Otherwise (source was not given):
+            match settings.pixelFormat {
+                ImageDataPixelFormat::Rgba_unorm8 => {
+                    // 1. If settings["pixelFormat"] is "rgba-unorm8",
+                    // then initialize the data attribute of imageData to a new Uint8ClampedArray object.
+                    // The Uint8ClampedArray object must use a new ArrayBuffer for its storage,
+                    // and must have a zero byte offset and byte length equal to the length of its storage, in bytes.
+                    // The storage ArrayBuffer must have a length of 4 × rows × pixelsPerRow bytes.
+                    create_heap_buffer_source_with_length(
```
Comment (gterzian) [inline components/script/dom/imagedata.rs:108]: Add a note for "[rgba-float16](https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#dom-imagedatapixelformat-rgba-unorm8)"?

Also, you could add "3. If the storage [ArrayBuffer](https://webidl.spec.whatwg.org/#idl-ArrayBuffer) could not be allocated, then rethrow the [RangeError](https://tc39.es/ecma262/#sec-native-error-types-used-in-this-standard-rangeerror) thrown by JavaScript, and return.", and add a note that is  done with the result of `create_heap_buffer_source_with_length`(is it?).

**Review by gterzian — APPROVED** [review]
LGTM with a few nits(and perhaps @Taym95  can take a look as well as mentioned).

File: components/script/dom/imagedata.rs (hunk 3 above)
Comment (sagudev) [reply components/script/dom/imagedata.rs:108]: It is.
