### PR TITLE
Use snapshot size instead of canvas size when converting canvas to blob

### LINKED ISSUE #36702: assertion `left == right` failed: Invalid buffer length
With the following minimal testcase

```
<!DOCTYPE html>
<canvas id="canvas"></canvas>
<script>
  canvas.toBlob(() => {});
  canvas.width = 0;
</script>
```

the latest nightly build (2025-04-26) is crashing with the following message (sorry I cannot copy the text of the full stack trace from Servo):

```
assertion `left == right` failed: Invalid buffer length: expected 0 got 180000 for 0x150 image
  left: 0
 right: 180000 (thread Script(1,1), at components/script/dom/htmlcanvaselement.rs:418)
Erreur de segmentation (core dumped)
``

### PR DESCRIPTION
**Pull request by simonwuelker**
The blob data is encoded asynchronously, therefore the canvas size may have changed since it's data was saved to a snapshot. Using the canvas size confuses the encoder, because the provided data does not match the expected size anymore.

Testing: This change includes a new web platform test
Fixes https://github.com/servo/servo/issues/36702

### CODE REVIEW

File: components/script/dom/htmlcanvaselement.rs [hunk 1]
```diff
@@ -407,15 +407,23 @@ impl HTMLCanvasElement {
...
+        snapshot: &Snapshot,
         encoder: &mut W,
     ) {
+        // We can't use self.Width() or self.Height() here, since the size of the canvas
+        // may have changed since the canvas was created. Truncating the dimensions to a
+        // u32 can't panic, since the data comes from a canvas which is always smaller than
+        // u32::MAX.
+        let canvas_data = snapshot.data();
+        let width = snapshot.size().width as u32;
+        let height = snapshot.size().height as u32;
```
Comment (sagudev) [inline components/script/dom/htmlcanvaselement.rs:419]: Reading this reminds me that we are pretty chaotic about canvas size type (u32 vs u64). We should unify this (by using u32 evrywhere) and also make it reflect the snapshot.

**Review by sagudev — APPROVED** [review]
