### PR TITLE
fix block size for absolute replaced element

### LINKED ISSUE #18706: Absolute positioned images with padding do not have correct size
servo-imgsz
```
<!DOCTYPE html>
<html><body>
	<style>
		img{
			position: absolute; top: 0px; left: 0px; padding: 100px;
		}
		
		.box{
			width: 350px; height: 350px; position: relative; background: lightgray;
		}
	</style>

	<div class="box">
		<img src="https://upload.wikimedia.org/wikipedia/commons/2/23/Skoda_logo.gif" alt="img">
	</div>

</body></html>
```

### PR DESCRIPTION
**Pull request by bobthekingofegypt**
Absolutely replaced elements with padding were incorrectly setting their
block size to include twice the padding values.  This attempts to stop
that extra padding for replaced elements but leave the working flow for
non replaced elements

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #18706 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19184)

### CODE REVIEW

**Comment by jdm** [comment]
This apparently makes an existing test pass, too!
```
  ▶ Unexpected subtest result in /css/cssom-view/elementsFromPoint-iframes.html:
  └ PASS [expected FAIL] elementsFromPoint on the root document for points in iframe elements
```

**Comment by bobthekingofegypt** [comment]
Is that why mac-dev-unit failed, I didn't understand the report?

I believe it's fixed that test because that test has an absolutely positioned replaced element (iframe) which I assume has a default border like firefox of 2px which was being added to the size of the element.  I can check for sure tomorrow.

**Comment by jdm** [comment]
mac-dev-unit failed because the manifest needs to be updated whenever test content is changed. You need to run `./mach manifest-update` to do that.

File: components/layout/block.rs [hunk 1]
```diff
@@ -1300,7 +1300,12 @@ impl BlockFlow {
             self.base.position.start.b = solution.block_start + self.fragment.margin.block_start
         }
 
-        let block_size = solution.block_size + self.fragment.border_padding.block_start_end();
+        let block_size = if self.fragment.is_replaced() {
```
Comment (emilio) [inline components/layout/block.rs]: Seems like it'd be cleaner to not include the padding in the block size in the first time? Looks like this is done in `assign_replaced_inline_size_if_necessary` (though it probably should be done in `assign_replaced_block_size_if_necessary`?).

File: components/layout/block.rs [hunk 2]
```diff
@@ -1300,7 +1300,12 @@ impl BlockFlow {
...
+            solution.block_size
+        } else {
+            (solution.block_size + self.fragment.border_padding.block_start_end())
```
Comment (emilio) [inline components/layout/block.rs]: nit: No need for parenthesis.

File: components/layout/block.rs (hunk 1 above)
Comment (bobthekingofegypt) [reply components/layout/block.rs]: I agree at the moment it looks more like fixing the cause rather than the effect.

I'm not sure if I understand though, from those functions I'm guessing you mean change the block size set in border_box (the value that is passed to solve_vertical_constraints_abs_replaced as the block size).  I was afraid to mess with the value of border_box as its doc string said it should contain the padding and border.

```
The position of this fragment relative to its owning flow. The size includes padding and border, but not margin.
```

I tried to find a way to pass the something other than border_box value on https://github.com/bobthekingofegypt/servo/blob/70097503396aab585cc565aaeaa693cce4757800/components/layout/block.rs#L1262 but I don't have enough knowledge of layout to figure out one.  I could adjust the value directly on line 1262 I guess but it's a similar confusion of just removing padding and borders to re-add them a few lines later.

Comment (emilio) [reply components/layout/block.rs]: Err, you're totally right, I guess we should substract the padding in solve_vertical_constraints_abs_replaced? @mbrubeck, could you take a look? You reviewed those functions when they were added, and I should also read a bit to see what's the right thing here :)

Comment (mbrubeck) [reply components/layout/block.rs]: Ugh, this code is all a bit of a mess, isn't it?  Umm, maybe this is a better place to subtract the padding:

https://github.com/servo/servo/blob/5c7e79e91c12d19830fdb4c6c17be2a551f88aa2/components/layout/block.rs#L1262

(See also the TODO comments above this line which hint at some of the bigger issues here.)

**Comment by jdm** [comment]
@mbrubeck Are you able to review these changes?

**Comment by jdm** [comment]
@bors-servo retry
* #20796
