### PR TITLE
Warn when a timer event is processed for a discarded document.

### LINKED ISSUE #14677: ScriptThread panics when a timer fires after a pipeline has closed
ScriptThread: received fire timer msg for a pipeline not in this script thread. This is a bug.
### URL: http://peacekeeper.futuremark.com/run.action
http://peacekeeper.futuremark.com/run.action
### Servo Version:
Servo 0.0.1-641010e
### Backtrace:
```

WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) }>: layout thread unreachable - leaking layout data
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: 
...
```
This report was generated by the browser.html issue reporter.

### PR DESCRIPTION
**Pull request by jdm**
Turn a panic into a warning for a situation that is easy to hit in web content.

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14677
- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14679)

### CODE REVIEW

File: components/script/script_thread.rs [hunk 1]
```diff
@@ -1049,8 +1049,12 @@ impl ScriptThread {
             TimerSource::FromWorker => panic!("Worker timeouts must not be sent to script thread"),
         };
 
-        let window = self.documents.borrow().find_window(pipeline_id)
-            .expect("ScriptThread: received fire timer msg for a pipeline not in this script thread. This is a bug.");
+        let window = self.documents.borrow().find_window(pipeline_id);
+        let window = match window {
+            Some(w) => w,
+            None => return warn!("ScriptThread: received fire timer msg for a pipeline not in \
+                                  this script thread. This is a bug."),
```
Comment (asajeffrey) [inline components/script/script_thread.rs]: I'm not sure this warning message is accurate any more. It's pretty easy for racing threads to produce this.

**Comment by asajeffrey** [comment]
@jdm: I think the warning message could do with rewording, apart from that r=me.

**Comment by jdm** [comment]
Updated the message.

**Comment by KiChjang** [comment]
@bors-servo retry
* the annoying git
