### PR TITLE
constellation: add source browsing context info in forwarded post message

### LINKED ISSUE #39748: constellation receives messages from closed pipelines(closed via webview closure)
`/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_escaping-3.html` would in certain cases CRASH, described and fixed at: https://github.com/servo/servo/pull/39745

Now it should only intermittently TIMEOUT(when no message event is fired), ~~and the reason for that seems to be that the iframe and the pop-up share a webview(post navigation of the pop-up?),~~ and then the pop-up sends a message to the iframe, and closes itself. The closure ends-up closing the webview at the constellation, and then if the message hasn't been received by the iframe, then receiving it will result in the iframe receiving none(and previously crashing) in response to `GetBrowsingContextInfo`. ~~The weird part is that the webview that the constellation reports as closed is the one in which the iframe conceptually finds itself.~~

This is the underlying problem of symptoms like 

- https://github.com/servo/servo/issues/24057
- https://github.com/servo/servo/issues/24066

### PR DESCRIPTION
**Pull request by gterzian**
For cross-document messaging, when the constellation forwards the message, it can add the source browsing context and ancestry info to the message. This saves a round-trip back to the constellation from script later, and also allows for messages to be delivered when the source pipeline is closed by the time of delivery(but not by the time of forwarding by the constellation).

Testing: Updated  various tests in `/html/semantics/embedded-content/the-iframe-element/` WPT: from TIMEOUT(because message was not delivered) or intermittent CRASH(because the source pipeline would be closed by the time of attempted delivery.) to FAIL.
Fixes: https://github.com/servo/servo/issues/39748

### CODE REVIEW

**Comment by gterzian** [comment]
I tried some of the failing tests but cannot reproduce locally, so just giving it another run...

File: components/constellation/constellation.rs [hunk 1]
```diff
@@ -4263,14 +4264,46 @@ where
...
+                    break;
+                },
+                None => {
+                    return warn!(
+                        "{}: PostMessage from pipeline with closed parent",
+                        source_pipeline
+                    );
+                },
+            }
+        }
```
Comment (mrobinson) [inline components/constellation/constellation.rs]: I think this can be a bit shorter and avoid the use of `loop {}` (which makes reasoning about the terminating condition a bit harder):


```rust

        let browsing_context_for_pipeline = |pipeline_id| {
            self.pipelines
                .get(&pipeline_id)
                .and_then(|pipeline| self.browsing_contexts.get(&pipeline.browsing_context_id))
        };

        let mut maybe_browsing_context = browsing_context_for_pipeline(source_pipeline);
        if maybe_browsing_context.is_none() {
            return warn!("{source_pipeline}: PostMessage from pipeline with closed parent");
        }

        let mut source_with_ancestry = vec![];
        while let Some(browsing_context) = maybe_browsing_context {
            source_with_ancestry.push(browsing_context.id);
            maybe_browsing_context = browsing_context
                .parent_pipeline_id
                .and_then(browsing_context_for_pipeline);
        }
```

File: components/script/script_thread.rs [hunk 2]
```diff
@@ -2731,23 +2732,29 @@ impl ScriptThread {
...
-                ) {
-                    None => {
-                        return warn!(
-                            "postMessage after source pipeline {} closed.",
-                            source_pipeline_id,
-                        );
-                    },
-                    Some(source) => source,
-                };
+                let mut last: Option<DomRoot<WindowProxy>> = None;
```
Comment (mrobinson) [inline components/script/script_thread.rs]: The type annotation isn't necessary here:

```suggestion
                let mut last = None;
```

**Review by mrobinson — CHANGES_REQUESTED** [review]
Great! You can also remove `ScriptWindowProxies::remote_window_proxy`, `ScriptWindowProxies::ask_constellation_for_browsing_context_info`, and the associated `ScriptToConstellationMessage::GetBrowsingContextInfo` message.

File: components/script/script_thread.rs [hunk 3]
```diff
@@ -2731,23 +2732,29 @@ impl ScriptThread {
...
+                        CreatorBrowsingContextInfo::from(last.as_deref(), None),
+                    );
+                    self.window_proxies
+                        .insert(browsing_context_id, window_proxy.clone());
+                    last = Some(window_proxy);
+                }
+
+                // Step 8.3: Let source be the WindowProxy object corresponding to
+                // incumbentSettings's global object (a Window object).
+                let source = last.expect("Source with ancestry should contain at least one bc.");
```
Comment (Taym95) [inline components/script/script_thread.rs:2756]: should this be early return?

File: components/script/script_thread.rs [hunk 4]
```diff
@@ -2731,23 +2732,29 @@ impl ScriptThread {
...
-                        return warn!(
-                            "postMessage after source pipeline {} closed.",
-                            source_pipeline_id,
-                        );
-                    },
-                    Some(source) => source,
-                };
+                let mut last: Option<DomRoot<WindowProxy>> = None;
+                for browsing_context_id in source_with_ancestry.into_iter().rev() {
+                    if let Some(window_proxy) = self.window_proxies.get(browsing_context_id) {
```
Comment (Taym95) [inline components/script/script_thread.rs:2737]: When reusing a cached WindowProxy from self.window_proxies, do we need to verify that it was created under the same WebViewId as source_webview?

**Review by Taym95 — APPROVED** [review]

File: components/script/script_thread.rs (hunk 3 above)
Comment (gterzian) [reply components/script/script_thread.rs:2756]: That there is at least one bc in the vec is an invariant; so no because it would mean something is wrong beyond repair.

File: components/script/script_thread.rs (hunk 4 above)
Comment (gterzian) [reply components/script/script_thread.rs:2737]: I think it's an interesting idea; we're not doing it now, but it could be investigated in a follow-up.

**Comment by gterzian** [comment]
@mrobinson @Taym95 Thanks for the reviews; comments have been addressed.

> You can also remove

It is still used in `local_window_proxy`.

**Review by mrobinson — APPROVED** [review]

**Comment by mrobinson** [comment]
> It is still used in `local_window_proxy`.

I see. Probably that should also get the entire parentage chain in one message as well.

**Comment by gterzian** [comment]
> Probably that should also get the entire parentage chain in one message as well.

https://github.com/servo/servo/issues/39957
