### PR TITLE
Fix Android back button behavior

### LINKED ISSUE #21401: Pressing the Android back button should call servo.goBack instead of hiding the app
… and if we can't go back, it should hide the app.

### PR DESCRIPTION
**Pull request by carloabelli**
Pressing the back button should call mServoView.goBack if possible.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [X] These changes fix #21401  (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21439)

### CODE REVIEW

File: support/android/apk/servoapp/src/main/java/com/mozilla/servo/MainActivity.java [hunk 1]
```diff
@@ -173,4 +173,12 @@ public void onResume() {
         super.onResume();
     }
 
+    @Override
+    public void onBackPressed() {
+        if (mBackButton.isEnabled()) {
```
Comment (paulrouget) [inline support/android/apk/servoapp/src/main/java/com/mozilla/servo/MainActivity.java]: Instead of using the button state, can you introduce a boolean field `mCanGoBack` that you set to true/false on `onHistoryChanged`?

**Review by paulrouget — CHANGES_REQUESTED** [review]

**Review by paulrouget — APPROVED** [review]
Thank you!
