### PR TITLE
script: Implement preparation-time document

### LINKED ISSUE #32974: Panic in html/dom/render-blocking/remove-pending-async-render-blocking-script.html
To reproduce: `./mach test-wpt tests/wpt/tests/html/dom/render-blocking/remove-pending-async-render-blocking-script.html`

The test has an async script element present in the test source, then a subsequent synchronous script moves the script element to another document. It looks like the issue is that the `owner_doc` field in `Node` is not updated appropriately when this move occurs, so `HTMLScriptElement` calls `asap_script_loaded` on the wrong document.

Backtrace:
```
0:06.47 pid:11006   14: core::option::Option<T>::unwrap
 0:06.47 pid:11006              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/option.rs:933:21
 0:06.47 pid:11006       script::dom::document::Document::asap_script_loaded
 0:06.47 pid:11006              at /Users/jdm/src/servo/components/script/dom/document.rs:2527:23
 0:06.50 pid:11006   15: script::dom::htmlscriptelement::finish_fetching_a_classic_script
 0:06.50 pid:11006              at /Users/jdm/src/servo/components/script/dom/htmlscriptelement.rs:325:37
 0:06.50 pid:11006   16: <script::dom::htmlscriptelement::ClassicContext as net_traits::FetchResponseListener>::process_response_eof
 0:06.50 pid:11006              at /Users/jdm/src/servo/components/script/dom/htmlscriptelement.rs:470:13
 0:06.52 pid:11006   17: <net_traits::FetchResponseMsg as net_traits::Action<T>>::process
 0:06.53 pid:11006              at /Users/jdm/src/servo/components/shared/net/lib.rs:304:25
 0:06.55 pid:11006   18: <script::network_listener::ListenerTask<A,Listener> as script::task::TaskOnce>::run_once
 0:06.55 pid:11006              at /Users/jdm/src/servo/components/script/network_listener.rs:117:13
 0:06.58 pid:11006   19: <script::task::CancellableTask<T> as script::task::TaskOnce>::run_once
 0:06.58 pid:11006              at /Users/jdm/src/servo/components/script/task.rs:114:13
 0:06.58 pid:11006   20: <T as script::task::TaskBox>::run_box
 0:06.58 pid:11006              at /Users/jdm/src/servo/components/script/task.rs:57:9
 0:06.61 pid:11006   21: script::script_thread::ScriptThread::handle_msg_from_script
 0:06.61 pid:11006              at /Users/jdm/src/servo/components/script/script_thread.rs:2479:17
 0:06.64 pid:11006   22: script::script_thread::ScriptThread::handle_msgs::{{closure}}
 0:06.64 pid:11006              at /Users/jdm/src/servo/components/script/script_thread.rs:1958:46
 0:06.64 pid:11006   23: script::script_thread::ScriptThread::profile_event
 0:06.64 pid:11006              at /Users/jdm/src/servo/components/script/script_thread.rs:2214:13
 0:06.64 pid:11006   24: script::script_thread::ScriptThread::handle_msgs
 0:06.64 pid:11006              at /Users/jdm/src/servo/components/script/script_thread.rs:1951:26
 0:06.64 pid:11006   25: script::script_thread::ScriptThread::start
 0:06.64 pid:11006              at /Users/jdm/src/servo/components/script/script_thread.rs:1454:15
 0:06.64 pid:11006   26: <script::script_thread::ScriptThread as script_layout_interface::ScriptThreadFactory>::create::{{closure}}::{{closure}}
 0:06.64 pid:11006              at /Users/jdm/src/servo/components/script/script_thread.rs:845:25
 0:06.67 pid:11006   27: profile_traits::mem::ProfilerChan::run_with_memory_reporting
 0:06.67 pid:11006              at /Users/jdm/src/servo/components/shared/profile/mem.rs:91:9
 0:06.67 pid:11006   28: <script::script_thread::ScriptThread as script_layout_interface::ScriptThreadFactory>::create::{{closure}}
 0:06.67 pid:11006              at /Users/jdm/src/servo/components/script/script_thread.rs:843:17
 0:06.71 pid:11006   29: std::sys_common::backtrace::__rust_begin_short_backtrace
 0:06.71 pid:11006              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:155:18
 0:06.74 pid:11006   30: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
 0:06.74 pid:11006              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/mod.rs:528:17
 0:06.77 pid:11006   31: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
 0:06.77 pid:11006              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panic/unwind_safe.rs:272:9
 0:06.80 pid:11006   32: std::panicking::try::do_call
 0:06.80 pid:11006              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
 0:06.80 pid:11006   33: ___rust_try
 0:06.80 pid:11006   34: std::panicking::try
 0:06.80 pid:11006              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
 0:06.80 pid:11006   35: std::panic::catch_unwind
 0:06.80 pid:11006              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
 0:06.80 pid:11006       std::thread::Builder::spawn_unchecked_::{{closure}}
 0:06.80 pid:11006              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/mod.rs:527:30
 0:07.15 pid:11006   36: core::ops::function::FnOnce::call_once{{vtable.shim}}
 0:07.15 pid:11006              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
 0:07.15 pid:11006   37: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
 0:07.15 pid:11006              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2020:9
 0:07.15 pid:11006       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
 0:07.16 pid:11006              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2020:9
 0:07.16 pid:11006       std::sys::pal::unix::thread::Thread::new::thread_start
 0:07.16 pid:11006              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys/pal/unix/thread.rs:108:17
 0:07.16 pid:11006   38: __pthread_joiner_wake
```

### PR DESCRIPTION
**Pull request by xiaochengh**
This PR implements the following as per spec:

> A [script](https://html.spec.whatwg.org/multipage/scripting.html#the-script-element) element has a preparation-time document, which is either null or a [Document](https://html.spec.whatwg.org/multipage/dom.html#document), initially null. It is used to prevent scripts that move between documents during [preparation](https://html.spec.whatwg.org/multipage/scripting.html#prepare-the-script-element) from [executing](https://html.spec.whatwg.org/multipage/scripting.html#execute-the-script-element).

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #32974

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

File: components/script/dom/htmlscriptelement.rs [hunk 1]
```diff
@@ -184,6 +184,9 @@ pub(crate) struct HTMLScriptElement {
     /// Document of the parser that created this element
     parser_document: Dom<Document>,
 
+    /// Prevents scripts that move between documents during preparation from executing.
```
Comment (simonwuelker) [inline components/script/dom/htmlscriptelement.rs:187]: Add a link to https://html.spec.whatwg.org/multipage/scripting.html#preparation-time-document please.

File: components/script/dom/htmlscriptelement.rs [hunk 2]
```diff
@@ -338,17 +342,27 @@ fn finish_fetching_a_classic_script(
     load: ScriptResult,
     can_gc: CanGc,
 ) {
-    // Step 11, Asynchronously complete this algorithm with script,
+    // Step 33, Asynchronously complete this algorithm with script,
```
Comment (simonwuelker) [inline components/script/dom/htmlscriptelement.rs:345]: The comment above this function says it implements https://html.spec.whatwg.org/multipage/#fetch-a-classic-script, but that this comment belongs to https://html.spec.whatwg.org/multipage/scripting.html#prepare-the-script-element.

File: components/script/dom/htmlscriptelement.rs [hunk 3]
```diff
@@ -651,15 +665,20 @@ impl HTMLScriptElement {
...
         }
 
-        // Step 10.
+        // Step 14.
         self.already_started.set(true);
 
-        // Step 12.
+        // Step 15.
         let doc = self.owner_document();
+        self.preparation_time_document.set(Some(&doc));
```
Comment (simonwuelker) [inline components/script/dom/htmlscriptelement.rs:673]: Add spec text to these steps please.

File: components/script/dom/htmlscriptelement.rs (hunk 2 above)
Comment (simonwuelker) [reply components/script/dom/htmlscriptelement.rs:345]: Also, one small nit, our usual convention is to put a dot after the step number, not a comma.

File: components/script/dom/htmlscriptelement.rs [hunk 4]
```diff
@@ -920,7 +939,7 @@ impl HTMLScriptElement {
     pub(crate) fn execute(&self, result: ScriptResult, can_gc: CanGc) {
         // Step 1.
         let doc = self.owner_document();
-        if self.parser_inserted.get() && *doc != *self.parser_document {
+        if *doc != *self.preparation_time_document.get().unwrap() {
```
Comment (simonwuelker) [inline components/script/dom/htmlscriptelement.rs:942]: Please include spec text for this step too.

**Review by simonwuelker — CHANGES_REQUESTED** [review]
Very cool!

File: components/script/dom/htmlscriptelement.rs (hunk 3 above)
Comment (xiaochengh) [reply components/script/dom/htmlscriptelement.rs]: Done.

File: components/script/dom/htmlscriptelement.rs (hunk 4 above)
Comment (xiaochengh) [reply components/script/dom/htmlscriptelement.rs:968]: Done.

**Review by xiaochengh — COMMENTED** [review]
Updated. Fixed the quoted spec text as much as I can.

**Review by simonwuelker — APPROVED** [review]
Thanks (:
