### PR TITLE
servoshell: Sync window toolbar height with minibrowser

### LINKED ISSUE #38297: Fullscreen API results in hit-test offsets
**Describe the bug:**
Run following example. After enter Fullscreen, you have to move below the elements in order to click it.

**To Reproduce:**
```html
<button id="enter">Enter API Fullscreen</button>
<button id="check">Check fullscreenElement</button>

<script>
  document.getElementById('enter').addEventListener('click', () => {
    document.documentElement.requestFullscreen();
  });

  document.getElementById('check').addEventListener('click', () => {
    console.log('fullscreenElement:', document.fullscreenElement);
  });

  window.addEventListener('fullscreenchange', () => {
    console.log('fullscreenchange event: fullscreenElement =', document.fullscreenElement);
  });
</script>
```

**Platform:**
Windows. Needs confirmation from other platforms.

### PR DESCRIPTION
**Pull request by yezhizhen**
Toolbar size can be changed if resized, such as entering fullscreen. Hit-test had wrong offsets after fullscreen/resize as `WindowEvent::CursorMoved` set wrong coordinates for `webview_relative_mouse_point` due to outdated toolbar height.

Testing: #38297 now works properly.
Fixes: #38297

### CODE REVIEW

**Review by yezhizhen — COMMENTED** [review]
It is kinda funny the fix only takes one line...

File: ports/servoshell/desktop/app.rs [hunk 1]
```diff
@@ -722,6 +722,7 @@ impl ApplicationHandler<AppEvent> for App {
                             state,
                             "Sync WebView size with Window Resize event",
                         );
+                        window.set_toolbar_height(minibrowser.toolbar_height);
```
Comment (mrobinson) [inline ports/servoshell/desktop/app.rs]: If this only happens when going into fullscreen mode, that is probably when we should be changing the toolbar size rather than on every resize event. We control the toolbar visibility so we should be able to know when it changes size.

**Review by mrobinson — CHANGES_REQUESTED** [review]

File: ports/servoshell/desktop/app.rs (hunk 1 above)
Comment (yezhizhen) [reply ports/servoshell/desktop/app.rs]: But minibrowser toobar size can only be possibly updated when initializing the app or minibrowser::update. 

It is just that Window also has a toolbar which was not synced.

This function is very cheap anyway.

Comment (mrobinson) [reply ports/servoshell/desktop/app.rs]: I think in that case when the minibrowser toolbar changes it should also set the toolbar size on the window.

Comment (yezhizhen) [reply ports/servoshell/desktop/app.rs]: https://github.com/servo/servo/blob/7ce5de4e2dda0dde4c7a8acbab612ff7414a1275/ports/servoshell/desktop/minibrowser.rs#L392

But minibrowser don't have access to `dyn WindowPortsMethods`. Do you think we should pass it as a param to `minibrowser::update` instead of only Winit Window?

Comment (yezhizhen) [reply ports/servoshell/desktop/app.rs]: > If this only happens when going into fullscreen mode, that is probably when we should be changing the toolbar size rather than on every resize event. We control the toolbar visibility so we should be able to know when it changes size.

We only know the new toolbar size after `minibrowser::update` (which happens in Resized Event handler).

Comment (yezhizhen) [reply ports/servoshell/desktop/app.rs]: > But minibrowser don't have access to `dyn WindowPortsMethods`. Do you think we should pass it as a param to `minibrowser::update` instead of only Winit Window?

Anyway I added this in the new commit. Pls check.

File: ports/servoshell/desktop/minibrowser.rs [hunk 2]
```diff
@@ -265,8 +266,14 @@ impl Minibrowser {
     /// Update the minibrowser, but don’t paint.
     /// If `servo_framebuffer_id` is given, set up a paint callback to blit its contents to our
     /// CentralPanel when [`Minibrowser::paint`] is called.
-    pub fn update(&mut self, window: &Window, state: &RunningAppState, reason: &'static str) {
+    pub fn update(
+        &mut self,
+        window_ports: &dyn WindowPortsMethods,
```
Comment (mrobinson) [inline ports/servoshell/desktop/minibrowser.rs]: Nit: I think this is typically called `window` in servoshell:

```suggestion
        window: &dyn WindowPortsMethods,
```

File: ports/servoshell/desktop/minibrowser.rs [hunk 3]
```diff
@@ -390,6 +397,7 @@ impl Minibrowser {
             // For reasons that are unclear, the TopBottomPanel’s ui cursor exceeds this by one egui
             // point, but the Context is correct and the TopBottomPanel is wrong.
             *toolbar_height = Length::new(ctx.available_rect().min.y);
+            window_ports.set_toolbar_height(*toolbar_height);
```
Comment (mrobinson) [inline ports/servoshell/desktop/minibrowser.rs]:
```suggestion
            window.set_toolbar_height(*toolbar_height);
```

**Review by mrobinson — APPROVED** [review]

**Comment by mrobinson** [comment]
Thanks and sorry for the delay!

File: ports/servoshell/desktop/minibrowser.rs (hunk 2 above)
Comment (yezhizhen) [reply ports/servoshell/desktop/minibrowser.rs]: Thanks for review! But there are many other things in the function already using `window` which is winit::Window, so I intentionally name as `window_ports` to not change other names and introduce too many changes..

And created a new local variable `window: winit::Window` at line 276 below.

EDIT: renamed window to `winit_window`.

**Review by mrobinson — APPROVED** [review]
