### PR TITLE
Fix crash when id attribute is set via SetAttributeNode

### LINKED ISSUE #17366: Panic: "Atom not found" when setting attribute node
Test case:
```html
<script>
var element = document.createElement('div');
var attr = document.createAttribute("id");
attr.value = "foo";
element.setAttributeNode(attr);
</script>
```

### PR DESCRIPTION
**Pull request by cbrewster**
fixes #17366

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17421)

### CODE REVIEW

**Comment by emilio** [comment]
r=me with a comment on why it's needed, and a test

File: components/script/dom/element.rs [hunk 1]
```diff
@@ -1543,6 +1543,10 @@ impl ElementMethods for Element {
 
     // https://dom.spec.whatwg.org/#dom-element-setattributenode
     fn SetAttributeNode(&self, attr: &Attr) -> Fallible<Option<Root<Attr>>> {
+        // Workaround for https://github.com/servo/servo/issues/17366
+        // This ensures that if this is an "id" attr, its value is an Atom
```
Comment (emilio) [inline components/script/dom/element.rs]: Well, to be honest is not really a workaround. It's the right fix, just not so efficient as it could be... Shrug.

Comment (cbrewster) [inline components/script/dom/element.rs]: Ahh feel free to r- if you'd like me to fix the comment, I can do that tomorrow
