### PR TITLE
Update heartbeats-simple dependencies for bug fixes

### LINKED ISSUE #15471: Heartbeats code uses unsynchronized static mut
In particular,
```rust
  static mut HBS: Option<*mut HashMap<ProfilerCategory, Heartbeat>> = None; 
```

I'm pretty sure that invokes nasal demons.

### PR DESCRIPTION
**Pull request by connorimes**
Updates heartbeats-simple dependencies for some bug fixes in native code (primarily for Windows).
Now we create heartbeats as needed so we don't have to maintain a hardcoded list which keeps getting out of sync.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15471 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because it updates a dependency and performs some code maintenance.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15458)

### CODE REVIEW

**Comment by emilio** [comment]
> let mut hbs: Box<HashMap<ProfilerCategory, Heartbeat>> = mem::transmute(hbs_ptr);

I believe the standard way of doing that is using `Box::from_raw` and `Box::into_raw`

**Comment by jdm** [comment]
I suspect that the Box goes out of scope at some point and frees the memory that it points to.

**Comment by connorimes** [comment]
I figured it was something like that but don't understand Rust in enough detail to say for sure.  I tried reproducing it with a minimal test program but wasn't able to.  I'll check out `Box::from_raw` and `Box::into_raw`.

**Comment by connorimes** [comment]
I switched to using `into_raw` and `from_raw` instead of `transmute`.

**Comment by connorimes** [comment]
Although we've never had any problems that I'm aware of, I am a little concerned about race conditions in accessing the raw HashMap pointer which is dropped in the `cleanup` function (esp. now given that `from_raw` documentation states that it transfers ownership of the pointer).  There could potentially be a race condition if some thread is still issuing profiling commands.  Due to aforementioned problems with -sys bindings, I can't use `lazy_static` around the `HBS` HashMap or put a `Mutex` in there.

I could create a separate `Mutex` that is init'd with `lazy_static` and perform a more classic manual acquisition of the lock where needed.  In my local checkout, I implemented this, though had to do something silly to avoid an unused warnings, like performing `assert_eq!(*lock, 0);` where I would normally release a lock so that the compiler doesn't optimize-out the call.   Alternatively I could do a spinlock with an atomic variable.  I'm open to suggestions.  Thanks.

**Comment by Ms2ger** [comment]
I filed https://github.com/servo/servo/issues/15471 about the preexisting unsynchronized access here.

**Comment by connorimes** [comment]
Thanks @Ms2ger .  I can commit a locking strategy as described above to this PR if you want to see it.  Unfortunately I don't think I can wrap the `Option` or pointer in a Mutex though, so it's a manual approach.

**Comment by connorimes** [comment]
I pushed a new commit which adds synchronization using a spinlock.  Please comment.

I suspect this would be better done with a function like `lock_and_work` which could take a closure as an argument and perform locking/unlocking around the closure rather than manually locking/unlocking in the few different functions that require synchronization.  However I'm not sure how to do this correctly with my limited Rust as at least one work operation needs to return a value (a bool).  I suppose I could have the other work operations return dummy values, but that's kind of dirty and doesn't seem very extensible should we have to introduce a new work routine that returns something other than a bool.

**Comment by Ms2ger** [comment]
You can use something like

```rust
pub fn foo<F, R>(function: F) -> R
    where F: FnOnce() -> R
{
    lock;
    let result = function();
    unlock;
    result
}
```

**Comment by connorimes** [comment]
Thanks @Ms2ger , that's what I'm looking for.  I've updated the commit to use that approach.  I think this PR is ready for a final review.

File: components/profile/heartbeats.rs [hunk 1]
```diff
@@ -12,39 +12,67 @@ use std::env::var_os;
 use std::error::Error;
 use std::fs::File;
 use std::path::Path;
+use std::sync::atomic::{ATOMIC_BOOL_INIT, AtomicBool, Ordering};
 
 
 static mut HBS: Option<*mut HashMap<ProfilerCategory, Heartbeat>> = None;
 
+// unfortunately can't encompass the actual hashmap in a Mutex (Heartbeat isn't Send/Sync), so we'll use a spinlock
+static mut HBS_SPINLOCK: AtomicBool = ATOMIC_BOOL_INIT;
```
Comment (Ms2ger) [inline components/profile/heartbeats.rs]: This should not need to be `mut`.

File: components/profile/heartbeats.rs [hunk 2]
```diff
@@ -12,39 +12,67 @@ use std::env::var_os;
...
 /// Initialize heartbeats
 pub fn init() {
     let mut hbs: Box<HashMap<ProfilerCategory, Heartbeat>> = Box::new(HashMap::new());
     maybe_create_heartbeat(&mut hbs, ProfilerCategory::ApplicationHeartbeat);
-    unsafe {
-        HBS = Some(Box::into_raw(hbs));
-    }
+    lock_and_work(||
+        unsafe {
+            HBS = Some(Box::into_raw(hbs));
```
Comment (Ms2ger) [inline components/profile/heartbeats.rs]: Let's pass `&mut HBS` to the callback, then the code that uses it can be... more safe.

File: components/profile/heartbeats.rs (hunk 1 above)
Comment (connorimes) [inline components/profile/heartbeats.rs]: Awesome, that also avoids needing unsafe during lock/unlock.  Thanks.

File: components/profile/heartbeats.rs (hunk 2 above)
Comment (connorimes) [inline components/profile/heartbeats.rs]: Can we safely touch HBS like that outside of the locking?  Also, are you talking about doing this everywhere we use `lock_and_work`?  My Rust is apparently really rusty - would I need to first define the closure outside of the call to `lock_and_work` in order to pass `&mut HBS` to it?  Thanks.

File: components/profile/heartbeats.rs [hunk 3]
```diff
@@ -11,86 +11,68 @@ use std::collections::HashMap;
...
 use std::path::Path;
+use std::sync::atomic::{ATOMIC_BOOL_INIT, AtomicBool, Ordering};
 
 
 static mut HBS: Option<*mut HashMap<ProfilerCategory, Heartbeat>> = None;
 
+// unfortunately can't encompass the actual hashmap in a Mutex (Heartbeat isn't Send/Sync), so we'll use a spinlock
+static mut HBS_SPINLOCK: AtomicBool = ATOMIC_BOOL_INIT;
+
+fn lock_and_work<F, R>(work: F) -> R where F: FnOnce() -> R {
```
Comment (emilio) [inline components/profile/heartbeats.rs]: To enforce that `HBS` is only used in a sound way you can move the declaration inside this function I believe (or in another module, so it's private to everything except this function), and give it as a parameter to `work`.

File: components/profile/heartbeats.rs (hunk 2 above)
Comment (Ms2ger) [inline components/profile/heartbeats.rs]: Something like

```rust
fn lock_and_work<F, R>(work: F) -> R
    where F: FnOnce(&mut Option<*mut HashMap<ProfilerCategory, Heartbeat>>) -> R
{
    work(&mut HBS)
}

File: components/profile/heartbeats.rs (hunk 3 above)
Comment (connorimes) [inline components/profile/heartbeats.rs]: Thanks.  I'm trying out this approach which makes sense.  However, when trying to assign the global `HBS` by way of the closure parameter, I get
```
133 |         lock_and_work(|&mut hbs_opt|
    |                             ------- first assignment to `hbs_opt`
134 |             hbs_opt = Some(Box::into_raw(hbs))
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ re-assignment of immutable variable
```
The only way I have around this is to move the `init` and `cleanup` functions to the private module and still assign `HBS` directly using an unsafe block.  So the old approach works for these two functions, but doesn't completely limit access to `HBS` to the `lock_and_work` function, which is what I think we were after.  For reference within `lock_and_work`, I do:
```
work(&mut HBS)
```

Comment (emilio) [inline components/profile/heartbeats.rs]: That code needs to use `*hbs_opt`, right?

Comment (connorimes) [inline components/profile/heartbeats.rs]: Ah, I was using `|&mut hbs_opt|` instead of just `|hbs_opt|` as the closure parameter.

**Comment by connorimes** [comment]
Thanks again for the all the feedback (this has turned into way more than the original PR was for).  I've pushed a new commit in response to your suggestions.

File: components/profile/heartbeats.rs [hunk 4]
```diff
@@ -2,61 +2,42 @@
...
 
 /// Initialize heartbeats
 pub fn init() {
-    let mut hbs: Box<HashMap<ProfilerCategory, Heartbeat>> = Box::new(HashMap::new());
-    maybe_create_heartbeat(&mut hbs, ProfilerCategory::ApplicationHeartbeat);
-    lock_and_work(||
-        unsafe {
-            HBS = Some(Box::into_raw(hbs));
+    lock_and_work(|hbs_opt|
+        if (*hbs_opt).is_none() {
```
Comment (emilio) [inline components/profile/heartbeats.rs]: nit: You shouldn't need `(*hbs_opt)`, `hbs_opt` should be enough in this case (the compiler auto-dereferences).

File: components/profile/heartbeats.rs [hunk 5]
```diff
@@ -2,61 +2,42 @@
...
-            match HBS {
-                Some(hbs_ptr) => {
-                    let ret = Some(Box::from_raw(hbs_ptr));
-                    HBS = None;
-                    ret
-                },
-                None => None,
-            }
+    let hbs_opt_box: Option<Box<HashMap<ProfilerCategory, Heartbeat>>> = lock_and_work(|hbs_opt|
+        match *hbs_opt {
```
Comment (emilio) [inline components/profile/heartbeats.rs]: nit: you can write this as:

```rust
unsafe {
    hbs_opt.take().map(Box::from_raw)
}
```

File: components/profile/heartbeats.rs [hunk 6]
```diff
@@ -67,10 +48,12 @@ pub fn cleanup() {
 
 /// Check if a heartbeat exists for the given category
 pub fn is_heartbeat_enabled(category: &ProfilerCategory) -> bool {
-    let is_enabled = lock_and_work(||
-        unsafe {
-            HBS.map_or(false, |hbs_ptr| (*hbs_ptr).contains_key(category))
-        }
+    let is_enabled = lock_and_work(|hbs_opt|
+        (*hbs_opt).map_or(false, |hbs_ptr|
```
Comment (emilio) [inline components/profile/heartbeats.rs]: no need for parens or dereference here.

File: components/profile/heartbeats.rs (hunk 5 above)
Comment (connorimes) [inline components/profile/heartbeats.rs]: I see what you're getting at, though that produced an error:
```
30 |             hbs_opt.take().map(Box::from_raw)
   |                            ^^^ the trait `std::ops::FnOnce<(*mut std::collections::HashMap<profile_traits::time::ProfilerCategory, heartbeats_simple::HeartbeatPow>,)>` is not implemented for `unsafe fn(*mut _) -> std::boxed::Box<_> {<std::boxed::Box<T>><_>::from_raw}`
```
It works if I give it a closure though:
```rust
    let hbs_opt_box: Option<Box<HashMap<ProfilerCategory, Heartbeat>>> = lock_and_work(|hbs_opt|
        hbs_opt.take().map(|hbs_ptr| unsafe {Box::from_raw(hbs_ptr)})
    );
```

The `take` documentation seems to support this approach, but it's not obvious to the the layman (me), so I'll double check - you're certain this will set the `hbs_opt` (and thus `HBS`) option to None afterward?

**Comment by connorimes** [comment]
OK, I cleaned up those lines.  I'd still like to verify https://github.com/servo/servo/pull/15458#discussion_r101134499 though.  Cheers.

File: components/profile/heartbeats.rs (hunk 5 above)
Comment (emilio) [inline components/profile/heartbeats.rs]: Yes, I'm pretty confident that it will do that :)

**Comment by emilio** [comment]
This looks ok to me, r=me unless @Ms2ger has any more comments?

**Comment by connorimes** [comment]
FYI, I rebased yesterday but I guess the S-need-rebase tag doesn't get removed automatically.  @Ms2ger did you have any further comments on this PR?  Thanks.

**Comment by larsbergstrom** [comment]
@bors-servo retry
- Was doing maintenance on failing builder servo-windows2 during this test's run.
