### PR TITLE
deny warnings

### LINKED ISSUE #19572: check build warning about unused import
If there is unused import, somewhere check for it and then return fail.

### PR DESCRIPTION
**Pull request by tigercosmos**
deny warnings
related to #19573

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #19572 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19612)

### CODE REVIEW

**Comment by tigercosmos** [comment]
Maybe not check on `appveyor`?
```
Build started
git clone -q https://github.com/servo/servo.git C:\projects\servo
git fetch -q origin +refs/pull/19612/merge:
git checkout -qf FETCH_HEAD
Restoring build cache
Cache '.servo' - Restored
Cache '.cargo' - Restored
set RUSTFLAGS='-D warnings'
mach build -d -v
error: failed to run `rustc` to learn about target-specific information
Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names '-D warnings' -W unused-extern-crates --target x86_64-pc-windows-msvc --crate-type bin --crate-type dylib --crate-type proc-macro --crate-type rlib` (exit code: 101)
--- stderr
error: multiple input filenames provided
cargo.exe build --manifest-path C:\projects\servo\ports\servo\Cargo.toml -v
Build FAILED in 0:00:13
Command exited with code 101
```

**Comment by emilio** [comment]
r? @jdm

This looks reasonable to me.

**Comment by tigercosmos** [comment]
It's weird.

it should be 
```
env ANDROID_SDK=/home/servo/android/sdk/r25.2.3 RUSTFLAGS='-D warnings' ./mach build --android --dev
```
but it becomes
```
env ANDROID_SDK=/home/servo/android/sdk/r25.2.3 'RUSTFLAGS='"'"'-D' 'warnings'"'"'' ./mach build --android --dev
```

**Comment by jdm** [comment]
If you use `-Dwarnings` then you won't need any quote characters.

**Comment by tigercosmos** [comment]
Seems Ok this time.

**Comment by tigercosmos** [comment]
```
error: unused import: `std::ptr`
  --> components/hashglobe/src/alloc.rs:31:9
   |
31 |     use std::ptr;
   |         ^^^^^^^^
   |
   = note: `-D unused-imports` implied by `-D warnings`

   Compiling net2 v0.2.29
   Compiling num_cpus v1.4.0
   Compiling time v0.1.37
error: aborting due to previous error
```

**Comment by tigercosmos** [comment]
@jdm  Is `std::ptr` only used for android?

**Comment by jdm** [comment]
Yes.

**Comment by SimonSapin** [comment]
It is only used in one function with `#[cfg(not(any(target_os = "android", target_os = "redox")))]`, so you should copy that onto the import, or move the import into the function.

**Comment by tigercosmos** [comment]
`linux-dev` intermittent error

**Comment by tigercosmos** [comment]
[mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/10546/steps/compile__2/logs/stdio) `env ./mach build-cef`
```
--- stderr
indent: Command line: unknown parameter "--version"
No module named mako
configure: error: Package requirements (zlib >= 1.2.3) were not met:

No package 'zlib' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ZLIB_CFLAGS
and ZLIB_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
thread 'main' panicked at 'failed with: exit code: 1', /Users/servo/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/6d23dae/build.rs:58:8
stack backtrace:
```

**Comment by tigercosmos** [comment]
android, arm, windows success.
linux, mac intermittent error

I believe it is OK. r+? @jdm,  @SimonSapin, @emilio

**Comment by emilio** [comment]
Let's try!

@bors-servo r=SimonSapin,jdm,emilio

**Comment by tigercosmos** [comment]
@emilio How you think the error again? It seems not related to this PR.
```--- stderr
error: Connection to server timed out
make[2]: *** [CMakeFiles/ogg.dir/gecko/src/media/libogg/src/ogg_alloc.c.o] Error 2
make[2]: *** Waiting for unfinished jobs....
error: Connection to server timed out
```

**Comment by tigercosmos** [comment]
@emilio: I really don't know why it error.

**Comment by tigercosmos** [comment]
I guess I know why!
without `-Dwarning` makes `./mach test` will build again!
That's why 
```
--- stderr
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_C_COMPILER= /usr/bin/cc
CMAKE_CXX_COMPILER= /usr/bin/c++

CMake Error at cmake_install.cmake:36 (file):
  file INSTALL cannot make directory "/usr/local/include/freetype2":
  Permission denied
```

**Comment by tigercosmos** [comment]
`mac-dev-unit` build succeeded in previous try. But now other error: 
```
error: failed to run custom build command for `osmesa-src v17.3.1-devel (https://github.com/servo/osmesa-src#6d23daed)`
process didn't exit successfully: `/Users/servo/buildbot/slave/mac-dev-unit/build/target/debug/build/osmesa-src-166e2e867fa22953/build-script-build` (exit code: 101)
```
```
--- stderr
indent: Command line: unknown parameter "--version"
No module named mako
In file included from /Users/servo/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/6d23dae/mesa-src/src/util/disk_cache.c:46:
In file included from /Users/servo/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/6d23dae/mesa-src/src/util/u_queue.h:38:
/Users/servo/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/6d23dae/mesa-src/src/util/list.h:163:9: warning: 'LIST_ENTRY' macro redefined [-Wmacro-redefined]
```
```

**Comment by tigercosmos** [comment]
@bors-servo retry
- only mac failed

**Comment by tigercosmos** [comment]
The command is fine in my mac .. 
```
RUSTFLAGS=-Dwarnings ./mach build-geckolib
 in dir /Users/servo/buildbot/slave/mac-dev-unit/build (timeout 1200 secs)
 watching logfiles {}
 argv: ['RUSTFLAGS=-Dwarnings', './mach', 'build-geckolib']
 environment:
  BUILD_MACHINE=<buildbot.process.properties.Property instance at 0x7f2a0994ee18>
  CARGO_HOME=/Users/servo/.cargo
  CCACHE=/usr/local/bin/ccache
  HOME=/Users/servo
  LOGNAME=servo
  OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include
  OPENSSL_LIB_DIR=/usr/local/opt/openssl/lib
  PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
  PWD=/Users/servo/buildbot/slave/mac-dev-unit/build
  RUST_BACKTRACE=1
  SCCACHE_IDLE_TIMEOUT=0
  SERVO_CACHE_DIR=/Users/servo/.servo
  SHELL=/bin/bash
  TMPDIR=/var/folders/ph/__1w3jq91ws48mzxgrjs1jmm0000gp/T/
  USER=servo
  XPC_FLAGS=0x0
  XPC_SERVICE_NAME=buildbot-slave
  __CF_USER_TEXT_ENCODING=0x1F6:0x0:0x0
 using PTY: False
Upon execvpe RUSTFLAGS=-Dwarnings ['RUSTFLAGS=-Dwarnings', './mach', 'build-geckolib'] in environment id 4556671808
:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/process.py", line 430, in _fork
    environment)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/process.py", line 508, in _execChild
    os.execvpe(executable, args, environment)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 355, in execvpe
    _execvpe(file, args, env)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 382, in _execvpe
    func(fullname, *argrest)
OSError: [Errno 2] No such file or directory
program finished with exit code 1
elapsedTime=0.029188
```

**Comment by SimonSapin** [comment]
```
 argv: ['RUSTFLAGS=-Dwarnings', './mach', 'build-geckolib']
```

This indicates that `RUSTFLAGS=-Dwarnings` is interpreted as the program name. Try adding `env ` at the start of the line: this is a program that sets environment variables and then starts another program.

**Comment by tigercosmos** [comment]
@SimonSapin  You are right!
I add `env` at the beginning. It must work. Hope so..
Could you r?

**Comment by jdm** [comment]
When we change RUSTFLAGS between building and compiling unit tests, we have to recompile everything. This makes TravisCI time out, and will make all of our builds take longer.

**Comment by tigercosmos** [comment]
@jdm Ok I will fix it.

**Comment by tigercosmos** [comment]
now it it OK

File: components/style/lib.rs [hunk 1]
```diff
@@ -23,7 +23,6 @@
 //! [cssparser]: ../cssparser/index.html
 //! [selectors]: ../selectors/index.html
 
-#![deny(warnings)]
```
Comment (jdm) [inline components/style/lib.rs]: Let's leave these explicit instances of denying warnings, since developers have grown used to developing with them present.

**Review by jdm — CHANGES_REQUESTED** [review]

File: components/style/lib.rs (hunk 1 above)
Comment (SimonSapin) [reply components/style/lib.rs]: @jdm Shouldn’t we rather be consistent between crates? As far as I’m concerned it’s an historical accident that some crates have it and not others, not something useful.

Comment (emilio) [reply components/style/lib.rs]: I don't personally care, but at least nsstring is vendored code, so I'd rather leave it in that crate at least.
