### PR TITLE
script: Use frozen array in gamepad axes for spec complience

### LINKED ISSUE #44336: Gamepad: `axes` should be array, but is Float64Array instead
**Describe the bug:**
See https://developer.mozilla.org/en-US/docs/Web/API/Gamepad/axes

**To Reproduce:**
```html
<!doctype html>
<script>
    window.addEventListener("gamepadconnected", (e) => B.innerText=`Connected at ${Date.now()}`);
    setInterval(() => {
        let b = navigator.getGamepads()[0]?.axes
        if (b) {
            A.innerText = b.constructor.name + ' ' + Array.isArray(b)
        }
    },500)
</script>
<pre id="B"></pre>
<pre id="A"></pre>
```
Firefox
Image

Servo
Image

**Platform:**
Windows 10

### PR DESCRIPTION
**Pull request by log101**
To comply with the Gamepad spec, this commit changes the type of Gamepad axes from Float64Array to CachedFrozenArray as per [Gamepad Interface](https://w3c.github.io/gamepad/#gamepad-interface).

Fixes: #44336
Testing: automated tests are not possible because the axes values can only be accessed with a real gamepad attached.

### CODE REVIEW

**Comment by mrobinson** [comment]
@log101 Where did this commit template come from?

**Comment by log101** [comment]
> @log101 Where did this commit template come from?

Hi @mrobinson, the first paragraph explains the commit, second paragraph explains the testing part and I've put the Fixes: #commit_number at the end as it is told in PR template. I've seen the checkboxes in a related pull request #32046 and after seeing your comment in [#44357](https://github.com/servo/servo/pull/44357#issuecomment-4276641484) I thought I should mention that I've run related tests.
This is my first commit so if there is anything that's not right, please feel free to correct.

File: components/script/dom/gamepad/gamepad.rs [hunk 1]
```diff
@@ -233,19 +232,15 @@ impl Gamepad {
 
     /// Initialize the number of axes in the "standard" gamepad mapping.
     /// <https://www.w3.org/TR/gamepad/#dfn-initializing-axes>
-    fn init_axes(&self, can_gc: CanGc) {
-        let initial_axes: Vec<f64> = vec![
+    fn init_axes(&self, _can_gc: CanGc) {
```
Comment (jdm) [inline components/script/dom/gamepad/gamepad.rs]: This CanGc parameter should be removed if it's no longer needed.

**Review by jdm — APPROVED** [review]
Thanks for fixing this!

**Comment by jdm** [comment]
I've updated the pull request description to use the original template format, and removed the description of the code changes since they don't need to be included in the final commit message; anybody reading the commit will see those are the changes being made. Leaving them here for posterity:
```
Following [similar usages of CachedFrozenArray](https://github.com/servo/servo/blob/bec5a6ce373f1281d47aa20345cd655225e79748/components/script/dom/event/extendablemessageevent.rs#L42-L44), there are now two properties regarding axes, frozen axes and axes. Frozen axes is holding CachedFrozenArray while axes is a vector of f64 values.
Also CachedFrozenArray::get_or_init method required CanGc, so Bindings.conf file also modified to provide Gamepad Axes can_gc parameter.

As this change is just modifies a type, I guess no new tests need to be added.

- [x]  ./mach build -d does not report any errors
- [x] ./mach test-tidy does not report any errors
- [x] ./mach test-wpt tests/wpt/tests/gamepad does not report any errors
```

File: components/script/dom/gamepad/gamepad.rs (hunk 1 above)
Comment (log101) [reply components/script/dom/gamepad/gamepad.rs]: Removed.

**Comment by Gae24** [comment]
Ready to merge once rebased.
