### PR TITLE
libservo: Wait for `WebView` to be ready before interacting in `test_largest_contentful_paint_js_api`

### LINKED ISSUE #42758: largest_contentful_paint test_largest_contentful_paint_js_api is flaky
https://github.com/servo/servo/actions/runs/22286539311/job/64465937912

```
     Summary [  28.616s] 864 tests run: 863 passed (1 flaky), 1 failed, 0 skipped
   FLAKY 2/4 [   0.920s] ( 79/864) libservo::largest_contentful_paint test_largest_contentful_paint_js_api
```

### PR DESCRIPTION
**Pull request by shubhamg13**
Simplified the TestPage using DataURL for Image
This makes sure we load the page completely before evaluating LCP.

Testing: `tests/largest_contentful_paint.rs`
Fixes: #42758

### CODE REVIEW

File: components/servo/tests/largest_contentful_paint.rs [hunk 1]
```diff
@@ -18,6 +18,11 @@ use crate::common::{
     show_webview_and_wait_for_rendering_to_be_ready,
 };
 
+// Page with a single 50x50 red square image using a data URL.
+static URL: &str = "data:text/html,<!DOCTYPE html>\
+<div><img src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAEklEQVQIW2P8z8AARAwMjDAGACwBA/+8RVWvAAAAAElFTkSuQmCC\"\
+style=\"width: 50px; height: 50px;\"></div>";
+
```
Comment (mrobinson) [inline components/servo/tests/largest_contentful_paint.rs:25]: I would either give this variable a better name or inline it again. A global called `URL` is pretty ambiguous. For instance, `DATA_URL_FOR_PAGE_WITH_SINGLE_RED_SQUARE`.

File: components/servo/tests/largest_contentful_paint.rs [hunk 2]
```diff
@@ -29,17 +34,12 @@ fn test_largest_contentful_paint_js_api() {
...
-                <div><img src=\"data:image/svg+xml,<svg width='50' height='50'><circle cx='25' cy='25' r='20' fill='green'/></svg>\"\
-                style=\"width: 50px; height: 50px;\"></div>"
-            )
-            .unwrap(),
-        )
+        .url(Url::parse(URL).unwrap())
         .build();
 
+    // Wait for the page to load and render before evaluating the LCP to ensure we don't miss LCP candidate.
+    show_webview_and_wait_for_rendering_to_be_ready(&servo_test, &webview, &delegate);
```
Comment (mrobinson) [inline components/servo/tests/largest_contentful_paint.rs:41]: Indeed. This is meant to be the first thing run before interacting with the `WebView`. Sorry that this was not caught in earlier reviews.

**Review by mrobinson — CHANGES_REQUESTED** [review]
Looks good with one change:

File: components/servo/tests/largest_contentful_paint.rs (hunk 1 above)
Comment (shubhamg13) [reply components/servo/tests/largest_contentful_paint.rs:25]: Sure done.

File: components/servo/tests/largest_contentful_paint.rs (hunk 2 above)
Comment (shubhamg13) [reply components/servo/tests/largest_contentful_paint.rs:41]: That's cool. I learned something new.

**Review by mrobinson — APPROVED** [review]

**Comment by mrobinson** [comment]
@shubhamg13 You do not need to constantly request a re-review from me for this change, especially after I have approved it.

**Comment by shubhamg13** [comment]
> @shubhamg13 You do not need to constantly request a re-review from me for this change, especially after I have approved it.

Actually, I handled a unnoticed nit and pushed again, which moved it out of queue. That's why I asked. 🙃

**Comment by mrobinson** [comment]
> Actually, I handled a unnoticed nit and pushed again, which moved it out of queue. That's why I asked. 🙃

In that case you should request that it be re-added to the queue and explain why you pushed again rather than hitting the "Request review" button. Getting multiple requests in a row is a bit like being spammed.
