### PR TITLE
Fix `starting_column` comparison in `ColspanToDistribute::comparison_for_sort`

### LINKED ISSUE #39261: Always true? table/layout.rs:3036 in main(19f70dc)
https://github.com/servo/servo/blob/19f70dccf6954b046a76d81a810f0cf22084e923/components/layout/table/layout.rs#L3036

### PR DESCRIPTION
**Pull request by yerke**
Testing: Added unit tests.
Fixes: https://github.com/servo/servo/issues/39261
Closes #39294

### CODE REVIEW

**Review by TimvdLippe — APPROVED** [review]

File: components/layout/table/layout.rs [hunk 1]
```diff
@@ -3007,10 +3007,70 @@ impl ColspanToDistribute {
     fn comparison_for_sort(a: &Self, b: &Self) -> Ordering {
         a.span
             .cmp(&b.span)
-            .then_with(|| b.starting_column.cmp(&b.starting_column))
+            .then_with(|| a.starting_column.cmp(&b.starting_column))
```
Comment (Taym95) [inline components/layout/table/layout.rs:3010]: let's not pick a issue when it is assigned and has a PR, to avoid wasting other's work https://github.com/servo/servo/pull/39294/files

Comment (Taym95) [reply components/layout/table/layout.rs:3010]: we should check with @TG199 first then make a PR, or co-auther this PR

Comment (TimvdLippe) [reply components/layout/table/layout.rs:3010]: Apologies, I assumed that @TG199 abandoned their PR as your review received no further follow-up. Given that it was a one-character fix, I assumed that they were okay with that. Let me know @TG199 if I misinterpreted the situation.

Comment (TG199) [reply components/layout/table/layout.rs:3010]: A check in would have fine but it is all good from here
