### PR TITLE
Make bootstrap handle linux setup, include gstreamer, make bootstrap run standalone

### LINKED ISSUE #21417: Build instructions for gstreamer on Ubuntu
Our build instructions for Debian-cased linuxes (https://github.com/servo/servo#on-debian-based-linuxes) say to install:
```
libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
```
but on xenial `./mach build -d` produces:
```
error: failed to run custom build command for `gstreamer-sys v0.5.0`                                                              
process didn't exit successfully: `/home/ajeffrey/github/asajeffrey/servo/target/debug/build/gstreamer-sys-7c386c02b961daa0/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "gstreamer-1.0 >= 1.12"` did not exit successfully: exit code: 1
--- stderr
Requested 'gstreamer-1.0 >= 1.12' but version of GStreamer is 1.8.3
```

### LINKED ISSUE #21446: Download linux gstreamer binaries during mach build
Telling people to execute [these steps](https://github.com/servo/servo/blob/master/.travis.yml#L20-L22) manually isn't a great solution if their distribution doesn't have a recent gstreamer available. It would be nice if we could make it Just Work by downloading those binaries automatically, similar to the way we acquire openssl for android builds.

### PR DESCRIPTION
**Pull request by Manishearth**
Previously `./mach bootstrap` wasn't very useful on Linux, it would just install salt. This PR moves that to `./mach bootstrap-salt`, and has `./mach bootstrap` perform the installation steps mentioned in the README.

With these changes `./mach bootstrap` is a valid way of setting up the servo build. Additionally, this adds gstreamer setup to this for cases where gstreamer is not up to date.

Edit: And now, mach bootstrap is able to be run on a fresh system with just python installed (no need for virtualenv or libffi). 

Fixes https://github.com/servo/servo/issues/21446 , fixes https://github.com/servo/servo/issues/21417

r? @jdm

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21586)

### CODE REVIEW

File: support/linux/gstreamer/gstreamer.sh [hunk 1]
```diff
@@ -0,0 +1,4 @@
+wget https://github.com/ferjm/gstreamer-1.14.1-ubuntu-trusty/raw/master/gstreamer.tar.gz -O gstreamer.tar.gz
```
Comment (Manishearth) [inline support/linux/gstreamer/gstreamer.sh]: Should I just make this part of the python file?

Also, should we try to host these binaries on our s3 bucket? (I don't know how, but I can ask)

File: python/servo/bootstrap.py [hunk 2]
```diff
@@ -243,7 +295,15 @@ def bootstrap(context, force=False):
...
-            bootstrapper = salt
+            context.distro_version = version
+            if specific == "salt":
+                bootstrapper = salt
+            elif specific == "gstreamer":
+                bootstrapper = gstreamer
+            else:
+                bootstrapper = linux
+        else:
+            raise Exception("mach bootstrap does not support %s, please file a bug" % distro)
```
Comment (Manishearth) [inline python/servo/bootstrap.py]: I'll open an issue for filling this in for macs

**Comment by Manishearth** [comment]
An annoying bit is that mach itself is pretty heavyweight and needs a bunch of deps like libffi to work. I can try and make mach bootstrap work independently of mach, if that is desired, that way folks just have to have rust installed and run `./mach bootstrap`.

(I'm currently testing this on a VM)

**Comment by Manishearth** [comment]
I've got the independent bootstrap working in my [bootstrap-next](http://github.com/manishearth/servo/tree/bootstrap-next) branch but I'm still working out some small issues.

I wonder if the gstreamer setup should be in `./mach bootstrap` or `mach_bootstrap.py`. Stuff is kinda scattered between the two, currently. I feel like it belongs in `./mach bootstrap` because while the `support/linux/gstreamer` based setup doesn't require sudo, the `apt-get` one does, and `mach_bootstrap.py` is all about silent non-sudo installation.

**Comment by Manishearth** [comment]
Merged in the branch. We can now recommend _just_ running `./mach bootstrap` for Ubuntu and Fedora.

We don't install rust, though (but mach bootstrap could if we wanted it to). 

Also found out a couple trusty-only dependency changes from the spidermonkey upgrade, which are also now installed via bootstrap.

**Comment by Manishearth** [comment]
wow, try=linux is _fast_

File: python/servo/bootstrap.py [hunk 3]
```diff
@@ -17,13 +17,43 @@
...
+    if gcc:
+        run_as_root(["add-apt-repository", "ppa:ubuntu-toolchain-r/test"], force)
+        run_as_root(["apt-get", "update"])
+        run_as_root(["apt-get", "install", "gcc-4.9", "g++-4.9"], force)
+        run_as_root(['update-alternatives', '--install', '/usr/bin/gcc', 'gcc',
+                     '/usr/bin/gcc-4.9', '60', '--slave', '/usr/bin/g++', 'g++',
+                     '/usr/bin/g++-4.9'])
+    if clang:
+        run_as_root(["bash", "-c", 'wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -'])
+        run_as_root(["apt-add-repository" "deb http://apt.llvm.org/trusty/ llvm-toolchain-xenial-4.0 main"], force)
```
Comment (jdm) [inline python/servo/bootstrap.py]: Missing comma(s?)

**Review by jdm — CHANGES_REQUESTED** [review]
These changes look like a really nice improvement for common pain points. Thanks!

File: servo-tidy.toml [hunk 4]
```diff
@@ -59,6 +59,7 @@ files = [
   "./resources/hsts_preload.json",
   "./tests/wpt/metadata/MANIFEST.json",
   "./support/android/openssl.sh",
+  "./support/linux/gstreamer/gstreamer.sh",
```
[the remark this answers is not in the document]
Comment (Manishearth) [reply servo-tidy.toml]: It can't, it contains giant URLs that can't really be split up further. Most of its lines are too long anyway, the tidy script doesn't get us much

**Comment by Manishearth** [comment]
Updated

**Comment by Manishearth** [comment]
I'm bypassing the checks on Windows, AIUI we can't do the same pkg-config thing there.

@bors-servo r=jdm

**Comment by Manishearth** [comment]
A better solution is to just silently ignore it when there's no pkg-config. The GStreamer build script does the same (it just hopes for the best and asks cargo to link to whatever it finds)

@bors-servo r=jdm

**Comment by Manishearth** [comment]
Hmmm... we bail out early for non-x86 systems, what gives?

**Comment by Manishearth** [comment]
Just sshd to the server to try this, it works fine if I run it directly. Hm.

**Comment by Manishearth** [comment]
@bors-servo try=android

mach build calls mach package, which doesn't pass down the target.

**Comment by Manishearth** [comment]
@bors-servo try=android

also test-wpt-android has similar issues

**Comment by jdm** [comment]
@bors-servo retry
* #20734
