### PR TITLE
Fix ./mach build --no-default-features

### LINKED ISSUE #35910: `./mach build --no-default-features` is broken
```
error[E0433]: failed to resolve: could not find `webxr` in `servo`
   --> ports/servoshell/desktop/app.rs:19:12
    |
19  | use servo::webxr::glwindow::GlWindowDiscovery;
    |            ^^^^^ could not find `webxr` in `servo`
    |
note: found an item that was configured out
   --> /home/alaska/servo/components/servo/lib.rs:113:9
    |
113 | pub use webxr;
    |         ^^^^^
note: the item is gated behind the `webxr` feature
   --> /home/alaska/servo/components/servo/lib.rs:112:7
    |
112 | #[cfg(feature = "webxr")]
    |       ^^^^^^^^^^^^^^^^^

error[E0433]: failed to resolve: could not find `webxr` in `servo`
   --> ports/servoshell/desktop/embedder.rs:10:12
    |
10  | use servo::webxr::glwindow::GlWindowDiscovery;
    |            ^^^^^ could not find `webxr` in `servo`
    |
note: found an item that was configured out
   --> /home/alaska/servo/components/servo/lib.rs:113:9
    |
113 | pub use webxr;
    |         ^^^^^
note: the item is gated behind the `webxr` feature
   --> /home/alaska/servo/components/servo/lib.rs:112:7
    |
112 | #[cfg(feature = "webxr")]
    |       ^^^^^^^^^^^^^^^^^

error[E0433]: failed to resolve: could not find `webxr` in `servo`
   --> ports/servoshell/desktop/headed_window.rs:664:24
    |
664 |     ) -> Rc<dyn servo::webxr::glwindow::GlWindow> {
    |                        ^^^^^ could not find `webxr` in `servo`
    |
note: found an item that was configured out
   --> /home/alaska/servo/components/servo/lib.rs:113:9
    |
113 | pub use webxr;
    |         ^^^^^
note: the item is gated behind the `webxr` feature
   --> /home/alaska/servo/components/servo/lib.rs:112:7
    |
112 | #[cfg(feature = "webxr")]
    |       ^^^^^^^^^^^^^^^^^

```
and so on.

### PR DESCRIPTION
**Pull request by jschwe**
Fix build failures when building without default features.

Testing: This was manually tested, but this PR does not add automated tests of `--no-default-features` to CI.

### CODE REVIEW

File: ports/servoshell/desktop/app.rs [hunk 1]
```diff
@@ -114,6 +113,7 @@ impl App {
         self.suspended.set(false);
         let (_, window) = self.windows.iter().next().unwrap();
 
+        #[cfg(feature = "webxr")]
```
Comment (jdm) [inline ports/servoshell/desktop/app.rs:116]: I'm unclear why we want a webxr feature for servoshell at all. It's just our sample embedding; I think we should minimize the customizations that are possible for it.

**Review by mrobinson — APPROVED** [review]
I agree with @jdm, but I think we could fix the build here and then remove the `webxr` feature in a followup.

**Comment by jschwe** [comment]
I mostly care about ensuring that `libservo` works with no default features (and tracking the binary size, so that regressions can be prevented or at least are easily visible). 
The alternative I see is building `libservo` in CI with no default features, which is probably not a bad thing either, but will again be another thing that eats CI resources.

**Comment by nicoburns** [comment]
Just ran into this today. I would also be in favour of fixing things here and then iterating on available features.

**Comment by jschwe** [comment]
If people are okay with this approach, then I would rebase and get this working again.

**Comment by mrobinson** [comment]
@jschwe Yes, let's fix the build and then remove the feature in a followup. It could be that `webxr` becomes totally platform-dependent in which case the feature itself would go away but the code is guarded by platform configuration.

**Review by mrobinson — APPROVED** [review]
