### PR TITLE
correctly send secure cookies after hsts url match

### LINKED ISSUE #8100: Github sign in is broken from http
STR:
Visit http://github.com in servo, click "sign in" button. Enter username and password, click submit button.

Actual:
Get directed to page that says "Cookies must be enabled".

Expected:
Logged in.

This doesn't appear to happen for https://github.com.

### PR DESCRIPTION
**Pull request by bobthekingofegypt**
Fixes #8100, where sites in the hsts list were not recieving secure
cookies if the site was originally loading using a plain http url.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9780)

### CODE REVIEW

**Comment by jdm** [comment]
Thank you for finding and solving this! I've filed #9783 to ensure we're not making this mistake in other places, too.

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /XMLHttpRequest/anonymous-mode-unsupported.htm:
  │ FAIL [expected PASS] XMLHttpRequest: anonymous mode unsupported
  │   → assert_equals: The deprecated anonymous:true should be ignored, cookie sent anyway expected "cookie: test=anonymous-mode-unsupported\n" but got ""
  │ 
  │ client.onreadystatechange<@http://web-platform.test:8000/XMLHttpRequest/anonymous-mode-unsupported.htm:22:13
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1405:1
```
We should look into why this test now fails with this change.

**Comment by bobthekingofegypt** [comment]
As discussed on IRC, the test was failing due to the hostname being modified by the HOST file entry in the test runner.  This meant the cookies were incorrectly failing to match the host in the updated request cookies method, and not being sent.

Tried updating the code to move hostname changes inside obtain_response and remove the duplicate urls.

Ran this against the unit tests and WPT tests, I get some failures and timeouts on WPT but I get the same failures on master.  I tried to test github site itself but I can't seem to press the final login button as the browser won't react to it.

File: components/net/http_loader.rs [hunk 1]
```diff
@@ -513,14 +513,14 @@ fn request_must_be_secured(url: &Url, hsts_list: &Arc<RwLock<HSTSList>>) -> bool
...
 
 pub fn modify_request_headers(headers: &mut Headers,
-                              doc_url: &Url,
+                              url: &Url,
                               user_agent: &str,
                               cookie_jar: &Arc<RwLock<CookieStorage>>,
                               load_data: &LoadData) {
     // Ensure that the host header is set from the original url
     let host = Host {
-        hostname: doc_url.serialize_host().unwrap(),
```
Comment (jdm) [inline components/net/http_loader.rs]: This change doesn't respect the comment above it; we need to pass the original URL as well.

Comment (jdm) [inline components/net/http_loader.rs]: Nevermind, I hadn't finished reading the rest of the changes.

File: components/net/http_loader.rs [hunk 2]
```diff
@@ -632,7 +632,7 @@ pub fn obtain_response<A>(request_factory: &HttpRequestFactory<R=A>,
         if let Some(pipeline_id) = *pipeline_id {
             send_request_to_devtools(
                 devtools_chan.clone(), request_id.clone().into(),
-                url.clone(), method.clone(), request_headers.clone(),
+                connection_url.clone(), method.clone(), request_headers.clone(),
```
Comment (jdm) [inline components/net/http_loader.rs]: This should be using `url` instead.

**Comment by jdm** [comment]
This looks great, with one small change necessary!

File: tests/unit/net/http_loader.rs [hunk 3]
```diff
@@ -814,6 +814,50 @@ fn test_load_sets_requests_cookies_header_for_url_by_getting_cookies_from_the_re
...
+    {
+        let mut cookie_jar = cookie_jar.write().unwrap();
+        let cookie_url = secured_url.clone();
+        let mut cookie_pair = CookiePair::new("mozillaIs".to_owned(), "theBest".to_owned());
+        cookie_pair.secure = true;
+
+        let cookie = Cookie::new_wrapped(
+            cookie_pair,
+            &cookie_url,
+            CookieSource::NonHTTP
```
Comment (jdm) [inline tests/unit/net/http_loader.rs]: Let's make this HTTP as well, or else it's pretty confusing to read.

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!
