### PR TITLE
devtools: Fix id collisions by using incrementing counters

### LINKED ISSUE #35954: Page-related ids in devtools messages can collide
TabDescriptorActor::encodable() uses the `index` of PipelineId, BrowsingContextId, and WebViewId without the `namespace_id`, but these can collide when ids are generated on different threads. WebViewId is currently safe from this, because they are now always generated in libservo and libservo is single-threaded, but PipelineId and BrowsingContextId can still collide, which will cause problems.

Given the following:
- `git apply` [ids.patch.txt](https://github.com/user-attachments/files/19226815/ids.patch.txt)

```html
<!-- iframe4.html -->
<!doctype html><meta charset=utf-8>
<iframe src=iframe4a.html></iframe>
<iframe src=iframe4b.html></iframe>
```
```html
<!-- iframe4a.html -->
a
```
```html
<!-- iframe4b.html -->
b
```

Starting servoshell on iframe4.html:
```
[components/shared/base/id.rs:268:9] browsing_context_id = (0,1)
[components/shared/base/id.rs:306:9] webview_id = TopLevel(0,1)
[components/shared/base/id.rs:220:9] pipeline_id = (1,1)
[components/shared/base/id.rs:268:9] browsing_context_id = (2,1)
[components/shared/base/id.rs:220:9] pipeline_id = (2,2)
[components/shared/base/id.rs:220:9] pipeline_id = (2,3)
[components/shared/base/id.rs:268:9] browsing_context_id = (2,4)
[components/shared/base/id.rs:220:9] pipeline_id = (2,5)
[components/shared/base/id.rs:220:9] pipeline_id = (2,6)
[components/shared/base/id.rs:220:9] pipeline_id = (3,1)   <== collides with (1,1)
[components/shared/base/id.rs:220:9] pipeline_id = (2,7)
[components/shared/base/id.rs:220:9] pipeline_id = (4,1)
[components/shared/base/id.rs:220:9] pipeline_id = (2,8)
```

New tab:
```
[components/shared/base/id.rs:268:9] browsing_context_id = (0,2)
[components/shared/base/id.rs:306:9] webview_id = TopLevel(0,2)
[components/shared/base/id.rs:220:9] pipeline_id = (1,2)
[components/shared/base/id.rs:220:9] pipeline_id = (1,3)
[components/shared/base/id.rs:220:9] pipeline_id = (5,1)
```

Navigate the new tab to iframe4.html:
```
[components/shared/base/id.rs:268:9] browsing_context_id = (6,1)   <== collides with (2,1)
[components/shared/base/id.rs:220:9] pipeline_id = (6,2)
[components/shared/base/id.rs:220:9] pipeline_id = (6,3)
[components/shared/base/id.rs:268:9] browsing_context_id = (6,4)
[components/shared/base/id.rs:220:9] pipeline_id = (6,5)
[components/shared/base/id.rs:220:9] pipeline_id = (6,6)
[components/shared/base/id.rs:220:9] pipeline_id = (7,1)
[components/shared/base/id.rs:220:9] pipeline_id = (6,7)
[components/shared/base/id.rs:220:9] pipeline_id = (8,1)
[components/shared/base/id.rs:220:9] pipeline_id = (6,8)
```

See also #35953, which affects this function.

### PR DESCRIPTION
**Pull request by delan**
Devtools clients need a `browserId`, `browsingContextID`, and `outerWindowID`, which correspond to WebViewId, BrowsingContextId, and PipelineId in Servo. These u32 values were previously derived from our sharded (u32,u32) id values by taking only the `index` (second u32) and ignoring the `namespace_id` (first u32), leading to collisions.

This patch fixes that by mapping those Servo ids to sequential u32 values.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #35954

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

File: components/devtools/lib.rs [hunk 1]
```diff
@@ -552,3 +559,166 @@ fn handle_client(actors: Arc<Mutex<ActorRegistry>>, mut stream: TcpStream, strea
 
     actors.lock().unwrap().cleanup(stream_id);
 }
+
+#[derive(Debug, Default)]
+struct IdMap {
```
Comment (jdm) [inline components/devtools/lib.rs:564]: Would you mind moving the new type and unit tests into a new file? I'm trying to keep this file from continuing to grow.

**Review by jdm — APPROVED** [review]
Nice solution!

File: components/devtools/lib.rs (hunk 1 above)
Comment (delan) [reply components/devtools/lib.rs]: done in a44813dcdd3b7f79832664a190c72cc6d7ef3f18
