### PR TITLE
change parse_own_css to queue event not fire synchronously

### LINKED ISSUE #18930: DomRefCell<T> already borrowed: BorrowMutError
Found with modified domato.
```html
<style onload="document.write()">
```

```gdb
DomRefCell<T> already borrowed: BorrowMutError (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZeroU32(NonZero(1))) }, at /checkout/src/libcore/result.rs:906)
stack backtrace:
   0:     0x5609f47c24a4 - backtrace::backtrace::trace<closure>
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
   1:     0x5609f47c017f - backtrace::capture::{{impl}}::new
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:     0x5609ee44fcbe - servo::main::{{closure}}
                        at /shared/dev/rust/servo/ports/servo/main.rs:130
   3:     0x5609f48b7756 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x5609f48b75e4 - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x5609f48b74e9 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x5609f48b747a - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:498
   7:     0x5609f48f1250 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x5609f03cb03f - core::result::unwrap_failed<core::cell::BorrowMutError>
                        at /checkout/src/libcore/macros.rs:23
   9:     0x5609f0357133 - core::result::{{impl}}::expect<core::cell::RefMut<script::dom::servoparser::Tokenizer>,core::cell::BorrowMutError>
                        at /checkout/src/libcore/result.rs:799
  10:     0x5609f0a18cc9 - script::dom::bindings::cell::{{impl}}::borrow_mut<script::dom::servoparser::Tokenizer>
                        at /shared/dev/rust/servo/components/script/dom/bindings/cell.rs:96
  11:     0x5609ef3f4559 - script::dom::servoparser::{{impl}}::abort
                        at /shared/dev/rust/servo/components/script/dom/servoparser/mod.rs:307
  12:     0x5609ef21d99c - script::dom::document::{{impl}}::abort
                        at /shared/dev/rust/servo/components/script/dom/document.rs:1912
  13:     0x5609ef22e6f6 - script::dom::document::{{impl}}::Open
                        at /shared/dev/rust/servo/components/script/dom/document.rs:3770
  14:     0x5609ef22f60f - script::dom::document::{{impl}}::Write
                        at /shared/dev/rust/servo/components/script/dom/document.rs:3891
  15:     0x5609f0bdf603 - script::dom::bindings::codegen::Bindings::DocumentBinding::DocumentBinding::write::{{closure}}
                        at /shared/dev/rust/servo/target/debug/build/script-9dcd9e3089aed129/out/Bindings/DocumentBinding.rs:2785
  16:     0x5609efd4af6f - core::ops::function::FnOnce::call_once<closure,()>
                        at /checkout/src/libcore/ops/function.rs:223
  17:     0x5609f11cb18a - std::panic::{{impl}}::call_once<bool,closure>
                        at /checkout/src/libstd/panic.rs:296
  18:     0x5609ef88abcc - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,bool>
                        at /checkout/src/libstd/panicking.rs:480
  19:     0x5609f48be89c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  20:     0x5609ef7c4c0d - std::panicking::try<bool,std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:459
  21:     0x5609f1249951 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,bool>
                        at /checkout/src/libstd/panic.rs:361
  22:     0x5609f073e372 - js::panic::wrap_panic<std::panic::AssertUnwindSafe<closure>,bool>
                        at /shared/dev/rust/servo/./.cargo/git/checkouts/rust-mozjs-8611526964119dd6/3de4ff3/src/panic.rs:22
  23:     0x5609f0bc9aa4 - script::dom::bindings::codegen::Bindings::DocumentBinding::DocumentBinding::write
                        at /shared/dev/rust/servo/target/debug/build/script-9dcd9e3089aed129/out/Bindings/DocumentBinding.rs:2762
  24:     0x5609f16f7b44 - CallJitMethodOp
                        at /shared/dev/rust/servo/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/3de4ff3/src/jsglue.cpp:516
  25:     0x5609ef189619 - script::dom::bindings::utils::generic_call
                        at /shared/dev/rust/servo/components/script/dom/bindings/utils.rs:450
  26:     0x5609ef1896a1 - script::dom::bindings::utils::generic_method
                        at /shared/dev/rust/servo/components/script/dom/bindings/utils.rs:458
  27:     0x5609f1d9fc57 - _ZN2js12CallJSNativeEP9JSContextPFbS1_jPN2JS5ValueEERKNS2_8CallArgsE
  29:     0x5609f1d6e3d6 - InternalCall
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:498
  30:     0x5609f1d6e400 - _ZN2js13CallFromStackEP9JSContextRKN2JS8CallArgsE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:504
  31:     0x5609f1d7b42c - Interpret
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:2873
  32:     0x5609f1d6dd31 - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:399
  33:     0x5609f1d6e17e - _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:471
  34:     0x5609f1d6e3d6 - InternalCall
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:498
  35:     0x5609f1d6e468 - _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:517
  36:     0x5609f1ae02d6 - _Z20JS_CallFunctionValueP9JSContextN2JS6HandleIP8JSObjectEENS2_INS1_5ValueEEERKNS1_16HandleValueArrayENS1_13MutableHandleIS6_EE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsapi.cpp:2781
  37:     0x5609f0c1fc2c - script::dom::bindings::codegen::Bindings::EventHandlerBinding::{{impl}}::Call
                        at /shared/dev/rust/servo/target/debug/build/script-9dcd9e3089aed129/out/Bindings/EventHandlerBinding.rs:300
  38:     0x5609f0c23b0f - script::dom::bindings::codegen::Bindings::EventHandlerBinding::{{impl}}::Call_<script::dom::eventtarget::EventTarget>
                        at /shared/dev/rust/servo/target/debug/build/script-9dcd9e3089aed129/out/Bindings/EventHandlerBinding.rs:273
  39:     0x5609ef288604 - script::dom::eventtarget::{{impl}}::call_or_handle_event<script::dom::eventtarget::EventTarget>
                        at /shared/dev/rust/servo/components/script/dom/eventtarget.rs:207
  40:     0x5609ef279e65 - script::dom::event::inner_invoke
                        at /shared/dev/rust/servo/components/script/dom/event.rs:511
  41:     0x5609ef279cb0 - script::dom::event::invoke
                        at /shared/dev/rust/servo/components/script/dom/event.rs:485
  42:     0x5609ef27985a - script::dom::event::dispatch_to_listeners
                        at /shared/dev/rust/servo/components/script/dom/event.rs:447
  43:     0x5609ef2784e8 - script::dom::event::{{impl}}::dispatch
                        at /shared/dev/rust/servo/components/script/dom/event.rs:152
  44:     0x5609ef282408 - script::dom::eventtarget::EventTarget::dispatch_event::h5137e76d2de1839a
  45:     0x5609ef278c2c - script::dom::event::{{impl}}::fire
                        at /shared/dev/rust/servo/components/script/dom/event.rs:220
  46:     0x5609ef2840fb - script::dom::eventtarget::EventTarget::fire_event_with_params::h5537e4fc9965ec44
  47:     0x5609ef283e76 - script::dom::eventtarget::EventTarget::fire_event::hf1f35b8b48f7e36a
  48:     0x5609ef341b85 - script::dom::htmlstyleelement::{{impl}}::parse_own_css
                        at /shared/dev/rust/servo/components/script/dom/htmlstyleelement.rs:110
  49:     0x5609ef3424a4 - script::dom::htmlstyleelement::{{impl}}::pop
                        at /shared/dev/rust/servo/components/script/dom/htmlstyleelement.rs:183
  50:     0x5609ef3fb723 - script::dom::servoparser::{{impl}}::pop
                        at /shared/dev/rust/servo/components/script/dom/servoparser/mod.rs:949
  51:     0x5609f0573f8c - html5ever::tree_builder::{{impl}}::pop<script::dom::bindings::root::Dom<script::dom::node::Node>,script::dom::servoparser::Sink>
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.20.0/src/tree_builder/mod.rs:820
  52:     0x5609f057eb87 - html5ever::tree_builder::{{impl}}::step<script::dom::bindings::root::Dom<script::dom::node::Node>,script::dom::servoparser::Sink>
                        at /shared/dev/rust/servo/target/debug/build/html5ever-27227a324e2655d2/out/rules.rs:781
  53:     0x5609f056b8f3 - html5ever::tree_builder::{{impl}}::process_to_completion<script::dom::bindings::root::Dom<script::dom::node::Node>,script::dom::servoparser::Sink>
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.20.0/src/tree_builder/mod.rs:313
  54:     0x5609f054b356 - html5ever::tree_builder::{{impl}}::process_token<script::dom::bindings::root::Dom<script::dom::node::Node>,script::dom::servoparser::Sink>
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.20.0/src/tree_builder/mod.rs:475
  55:     0x5609f0532bfb - html5ever::tokenizer::{{impl}}::process_token<html5ever::tree_builder::TreeBuilder<script::dom::bindings::root::Dom<script::dom::node::Node>, script::dom::servoparser::Sink>>
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.20.0/src/tokenizer/mod.rs:233
  56:     0x5609f0537193 - html5ever::tokenizer::{{impl}}::process_token_and_continue<html5ever::tree_builder::TreeBuilder<script::dom::bindings::root::Dom<script::dom::node::Node>, script::dom::servoparser::Sink>>
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.20.0/src/tokenizer/mod.rs:238
  57:     0x5609f0547448 - html5ever::tokenizer::{{impl}}::emit_eof<html5ever::tree_builder::TreeBuilder<script::dom::bindings::root::Dom<script::dom::node::Node>, script::dom::servoparser::Sink>>
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.20.0/src/tokenizer/mod.rs:542
  58:     0x5609f0547f41 - html5ever::tokenizer::{{impl}}::eof_step<html5ever::tree_builder::TreeBuilder<script::dom::bindings::root::Dom<script::dom::node::Node>, script::dom::servoparser::Sink>>
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.20.0/src/tokenizer/mod.rs:632
  59:     0x5609f053782e - html5ever::tokenizer::{{impl}}::end<html5ever::tree_builder::TreeBuilder<script::dom::bindings::root::Dom<script::dom::node::Node>, script::dom::servoparser::Sink>>
                        at /shared/dev/rust/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.20.0/src/tokenizer/mod.rs:1285
  60:     0x5609ef3fc79c - script::dom::servoparser::html::{{impl}}::end
                        at /shared/dev/rust/servo/components/script/dom/servoparser/html.rs:86
  61:     0x5609ef3f60ca - script::dom::servoparser::{{impl}}::end
                        at /shared/dev/rust/servo/components/script/dom/servoparser/mod.rs:521
  62:     0x5609ef3f5e2f - script::dom::servoparser::{{impl}}::finish
                        at /shared/dev/rust/servo/components/script/dom/servoparser/mod.rs:462
  63:     0x5609ef3f58d0 - script::dom::servoparser::{{impl}}::do_parse_sync
                        at /shared/dev/rust/servo/components/script/dom/servoparser/mod.rs:404
  64:     0x5609ef3fecc7 - script::dom::servoparser::{{impl}}::parse_sync::{{closure}}
                        at /shared/dev/rust/servo/components/script/dom/servoparser/mod.rs:381
  65:     0x5609f09ede17 - profile_traits::time::profile<(),closure>
                        at /shared/dev/rust/servo/components/profile_traits/time.rs:124
  66:     0x5609ef3f5560 - script::dom::servoparser::{{impl}}::parse_sync
                        at /shared/dev/rust/servo/components/script/dom/servoparser/mod.rs:378
  67:     0x5609ef3f8aca - script::dom::servoparser::{{impl}}::process_response_eof
                        at /shared/dev/rust/servo/components/script/dom/servoparser/mod.rs:711
  68:     0x5609ef4ecf84 - script::script_thread::{{impl}}::handle_fetch_eof
                        at /shared/dev/rust/servo/components/script/script_thread.rs:2450
  69:     0x5609ef4d6d03 - script::script_thread::{{impl}}::handle_msg_from_constellation
                        at /shared/dev/rust/servo/components/script/script_thread.rs:1178
  70:     0x5609ef4f3384 - script::script_thread::{{impl}}::handle_msgs::{{closure}}
                        at /shared/dev/rust/servo/components/script/script_thread.rs:1056
  71:     0x5609ef4f36e0 - script::script_thread::{{impl}}::profile_event<closure,core::option::Option<bool>>
                        at /shared/dev/rust/servo/components/script/script_thread.rs:1168
  72:     0x5609ef4d41e7 - script::script_thread::{{impl}}::handle_msgs
                        at /shared/dev/rust/servo/components/script/script_thread.rs:1050
  73:     0x5609ef4d21d5 - script::script_thread::{{impl}}::start
                        at /shared/dev/rust/servo/components/script/script_thread.rs:885
  74:     0x5609ef4f0914 - script::script_thread::{{impl}}::create::{{closure}}::{{closure}}
                        at /shared/dev/rust/servo/components/script/script_thread.rs:570
  75:     0x5609f09ec447 - profile_traits::mem::{{impl}}::run_with_memory_reporting<closure,fn(profile_traits::mem::ReportsChan) -> script::script_runtime::CommonScriptMsg,script::script_runtime::CommonScriptMsg,std::sync::mpsc::Sender<script::script_thread::MainThreadScriptMsg>>
                        at /shared/dev/rust/servo/components/profile_traits/mem.rs:63
  76:     0x5609ef4f0ee6 - script::script_thread::{{impl}}::create::{{closure}}
                        at /shared/dev/rust/servo/components/script/script_thread.rs:569
  77:     0x5609f143bf2a - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /checkout/src/libstd/sys_common/backtrace.rs:134
  78:     0x5609efc80913 - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:400
  79:     0x5609f11c9efa - std::panic::{{impl}}::call_once<(),closure>
                        at /checkout/src/libstd/panic.rs:296
  80:     0x5609ef8dd652 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panicking.rs:480
  81:     0x5609f48be89c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  82:     0x5609ef83ab5c - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:459
  83:     0x5609f12aa265 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panic.rs:361
  84:     0x5609efc7f90b - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:399
  85:     0x5609efc80f93 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /checkout/src/liballoc/boxed.rs:762
  86:     0x5609f48b646b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:772
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:24
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  87:     0x7f961adaf493 - start_thread
  88:     0x7f961a8dcabe - __clone
  89:                0x0 - <unknown>
ERROR:servo: DomRefCell<T> already borrowed: BorrowMutError
```

### PR DESCRIPTION
**Pull request by avadacatavra**
fixes a panic and aligns with spec

I've also added checks around each mutable borrow of the tokenizer to see if we can catch any other panics

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #18930 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19307)

### CODE REVIEW

**Comment by avadacatavra** [comment]
r? jdm

File: components/script/dom/servoparser/mod.rs [hunk 1]
```diff
@@ -175,6 +175,7 @@ impl ServoParser {
         document.set_current_parser(Some(&parser));
         if !type_.eq_ignore_ascii_case("text/html") {
             parser.parse_string_chunk("<pre>\n".to_owned());
+            assert!(parser.tokenizer.try_borrow_mut().is_ok());
```
Comment (jdm) [inline components/script/dom/servoparser/mod.rs]: Asserting here is no different than performing the infallible borrow. Rather than adding these extra asserts everywhere, I would like a single API on ServoParser called something like `parser_is_not_active` (and an API on Document named something like `can_invoke_script`, which has access to the parser), and we should assert that that API returns true when we're asked to dispatch an event in EventTarget.

**Review by jdm — CHANGES_REQUESTED** [review]

**Comment by avadacatavra** [comment]
@jdm not sure if i should queue the events if the parser is in use?

**Comment by jdm** [comment]
No, we don't want to change behaviour based on this. We want to simply expose potential problems that _could_ end up interacting with the parser if they invoke document.write.

File: components/script/dom/eventtarget.rs [hunk 2]
```diff
@@ -315,11 +315,35 @@ impl EventTarget {
     pub fn dispatch_event_with_target(&self,
                                       target: &EventTarget,
                                       event: &Event) -> EventStatus {
-        event.dispatch(self, Some(target))
```
Comment (jdm) [inline components/script/dom/eventtarget.rs]: Assert here, and let's match on `target.global().downcast::<Window>()` instead of trying Element (keeping in mind that None is valid).

File: components/script/dom/eventtarget.rs [hunk 3]
```diff
@@ -315,11 +315,35 @@ impl EventTarget {
...
+            false => {
+                let window = document.window();
+                window.dom_manipulation_task_source().queue_simple_event(self.upcast(), event.type_(), &window);
+                EventStatus::NotCanceled
+            }
+        }
     }
 
     pub fn dispatch_event(&self, event: &Event) -> EventStatus {
-        event.dispatch(self, None)
```
Comment (jdm) [inline components/script/dom/eventtarget.rs]: Assert here, and do the same as the previous comment but using self.

**Review by jdm — CHANGES_REQUESTED** [review]
To make sure this works locally, please run `./mach test-wpt workers/`. This would have caught the problem with unwrapping the the downcast to Window, which doesn't work in a non-window global.

**Comment by jdm** [comment]
According to the linux machines, these are the only tests that trigger the new assertion (and they both hit it on the same codepath):
```
/custom-elements/microtasks-and-constructors.html
/custom-elements/parser/parser-fallsback-to-unknown-element.html
```

**Comment by jdm** [comment]
Of course, those backtraces correspond to the spec at https://dom.spec.whatwg.org/#concept-create-element and https://html.spec.whatwg.org/multipage/webappapis.html#report-the-error, which wants a synchronous event dispatch. We may need to modify the html5ever tokenizer to use internal mutability to avoid the problem here.

**Comment by avadacatavra** [comment]
ok i'll take a look at the spec tomorrow and try to figure out a fix

**Comment by avadacatavra** [comment]
@jdm what do you think about just making the assert a warn? we've fixed the original issue, and the only times the assert is triggered is when we need the synchronous event dispatch

**Comment by jdm** [comment]
The point of the assert is to alert us to cases where invoking arbitrary content JS could yield further panics like the original test cases. In this case, it shouldn't be difficult to put together a tescase that invokes document.write from an "error" event handler.

**Comment by jdm** [comment]
Indeed: adding `onerror = function() { document.write('hi'); };` to parser-fallsback-to-unknown-element.html makes the same panic appear.

**Comment by jdm** [comment]
Given #19392, let's mark the two affected tests as expected CRASH (and add `bug: https://github.com/servo/servo/issues/19392` annotations). We should also add an automated test for the original testcase; we should make it verify that the `<style>` element's load event is asynchronous, and we can add it as a new file in `tests/wpt/web-platform-tests/tree/master/html/semantics/document-metadata/the-style-element`.

File: tests/wpt/web-platform-tests/html/semantics/document-metadata/the-style-element/style_load_async.html [hunk 4]
```diff
@@ -0,0 +1,27 @@
+<!doctype html>
+<html>
+<meta charset="utf-8">
+<title>Style load event should be async</title>
+<script src="/resources/testharness.js"></script>
+<script src="/resources/testharnessreport.js"></script>
+<style onload="document.blah = true">
+</style>
```
Comment (jdm) [inline tests/wpt/web-platform-tests/html/semantics/document-metadata/the-style-element/style_load_async.html]: This style block can be removed now.

File: tests/wpt/metadata/custom-elements/parser/parser-fallsback-to-unknown-element.html.ini [hunk 5]
```diff
@@ -0,0 +1,3 @@
+;bug: https://github.com/servo/servo/issues/19392
```
Comment (jdm) [inline tests/wpt/metadata/custom-elements/parser/parser-fallsback-to-unknown-element.html.ini]: This (and the other ini file) should be:
```
[parser-fallsback-to-unknown-element.html]
  expected: CRASH
  bug: https://github.com/servo/servo/issues/19392
```

File: components/script/dom/servoparser/mod.rs [hunk 6]
```diff
@@ -102,6 +102,10 @@ enum LastChunkState {
 }
 
 impl ServoParser {
+    pub fn parser_is_not_active(&self) -> bool {
+        self.tokenizer.try_borrow_mut().is_ok()
```
Comment (jdm) [inline components/script/dom/servoparser/mod.rs]: Let's add `|| self.can_write()`, so that this is handled correctly when https://github.com/servo/servo/issues/19393 is fixed.

File: components/script/dom/eventtarget.rs [hunk 7]
```diff
@@ -315,10 +315,23 @@ impl EventTarget {
     pub fn dispatch_event_with_target(&self,
                                       target: &EventTarget,
                                       event: &Event) -> EventStatus {
+        match target.global().downcast::<Window>() {
+            Some(window) => if window.has_document() {
```
Comment (jdm) [inline components/script/dom/eventtarget.rs]: Let's use `if let`

File: components/script/dom/eventtarget.rs [hunk 8]
```diff
@@ -315,10 +315,23 @@ impl EventTarget {
...
+                assert!(window.Document().can_invoke_script());
+            },
+            None => (),
+        };
+
         event.dispatch(self, Some(target))
     }
 
     pub fn dispatch_event(&self, event: &Event) -> EventStatus {
+        match self.global().downcast::<Window>() {
```
Comment (jdm) [inline components/script/dom/eventtarget.rs]: `if let`

**Review by jdm — CHANGES_REQUESTED** [review]
Looks good!
