### PR TITLE
constellation: prevent panic when constellation receives message from closed pipeline

### LINKED ISSUE #22647: Intermittent panic in /html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_escaping-1.html
```
  ▶ CRASH [expected TIMEOUT] /html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_escaping-1.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 18.3.0-devel
  │ Failed to get browsing context info from constellation.: Io(Custom { kind: ConnectionReset, error: StringError("All senders for this socket closed") }) (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(2), index: PipelineIndex(3) }, at src/libcore/result.rs:999)
  │ stack backtrace:
  │    0:     0x7f8b62d03e5d - backtrace::backtrace::trace::h8cf5e823e7b927c4
  │    1:     0x7f8b62d02f42 - <backtrace::capture::Backtrace as core::default::Default>::default::hc91a77fe18f6f82e
  │    2:     0x7f8b607bf3e7 - servo::main::{{closure}}::h35768982dca81cb7
  │    3:     0x7f8b639ddb19 - std::panicking::rust_panic_with_hook::h3efc9269f3975b4e
  │                         at src/libstd/panicking.rs:482
  │    4:     0x7f8b639dd5c1 - std::panicking::continue_panic_fmt::h0bb834397df0d69a
  │                         at src/libstd/panicking.rs:385
  │    5:     0x7f8b639dd4a5 - rust_begin_unwind
  │                         at src/libstd/panicking.rs:312
  │    6:     0x7f8b639fd23c - core::panicking::panic_fmt::hce8ba5bc9a54c6f2
  │                         at src/libcore/panicking.rs:85
  │    7:     0x7f8b61391d4e - core::result::unwrap_failed::h9325188f0d97b600
  │    8:     0x7f8b61318360 - script::script_thread::ScriptThread::remote_window_proxy::h586ae72ffbd6f061
  │    9:     0x7f8b61308150 - script::script_thread::ScriptThread::handle_msg_from_constellation::h00b1d194fc128cea
  │   10:     0x7f8b61301f74 - _ZN6script13script_thread12ScriptThread11handle_msgs17h9e6b09790e3f4ea7E.llvm.3656274141805418547
  │   11:     0x7f8b612fced6 - script::script_thread::ScriptThread::start::h1484b91d67faaaad
  │   12:     0x7f8b61365f7e - profile_traits::mem::ProfilerChan::run_with_memory_reporting::ha803eda8ad327b82
  │   13:     0x7f8b61472de4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h918092a582e94f30
  │   14:     0x7f8b619b8a85 - _ZN3std9panicking3try7do_call17h1e1a4a7559b185dcE.llvm.9973224621453256981
  │   15:     0x7f8b639e8829 - __rust_maybe_catch_panic
  │                         at src/libpanic_unwind/lib.rs:92
  │   16:     0x7f8b616da477 - <F as alloc::boxed::FnBox<A>>::call_box::hcc4b12433ee715fb
  │   17:     0x7f8b639e7bdd - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$RP$$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::hf75cbe88140b524c
  │                         at /rustc/c0bbc3927e28c22edefe6a1353b5ecc95ea9a104/src/liballoc/boxed.rs:734
  │                          - std::sys_common::thread::start_thread::h9fb334ae2abaae80
  │                         at src/libstd/sys_common/thread.rs:14
  │                          - std::sys::unix::thread::Thread::new::thread_start::h772c7ae2e9d50018
  │                         at src/libstd/sys/unix/thread.rs:81
  │   18:     0x7f8b5e409183 - start_thread
  │   19:     0x7f8b5ccd003c - clone
  │   20:                0x0 - <unknown>
  │ [2019-01-07T18:22:43Z ERROR servo] Failed to get browsing context info from constellation.: Io(Custom { kind: ConnectionReset, error: StringError("All senders for this socket closed") })
  └ Pipeline failed in hard-fail mode.  Crashing!
```
This looks like another instance of the underlying problem from #13480.

### PR DESCRIPTION
**Pull request by gterzian**
As part of https://github.com/servo/servo/issues/31973, I noticed that the intermittent crash of `/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_escaping-3.html` appears due to the closing of the of the source webview of the message, which prior to these changes would result in an early return and drop the reply sender, resulting in a panic. 

This change makes the check for whether the webview is still open specific to certain messages that need the webview and `GetBrowsingContextInfo` is not one of them. 

As to exactly what allows a webview to be closed and still send a `GetBrowsingContextInfo` message, it appears that the iframe and the pop-up opened by the iframe share the same webview, and when the pop-up calls `close`, that closes the webview but the iframe is still running and then receives a post message from a webview that was already closed(intermittently). See https://github.com/servo/servo/issues/39748

Testing: WPT
Fixes: https://github.com/servo/servo/issues/22647

### CODE REVIEW

**Comment by mrobinson** [comment]
This is a bit odd. It should be impossible for a popup to be opened in same WebView as the opener. The popup code creates an entirely new top level browsing context which is assigned to a new WebView by the embedding layer. I think there must be something deeper going wrong.

**Comment by gterzian** [comment]
>  think there must be something deeper going wrong.

Defenitely, this PR only fixes the panic. The underlying problem is discussed at https://github.com/servo/servo/issues/39748

**Comment by gterzian** [comment]
Looks like this one is now persistently not crashing:
- https://github.com/servo/servo/issues/24066

**Comment by gterzian** [comment]
Ok I can comfirm that `/focus/activeelement-after-focusing-different-site-iframe-contentwindow.html` on main hits the `ScriptMsg from closed pipeline` for a `ScriptMsg::FocusRemoteDocument` at 

https://github.com/servo/servo/blob/12e5d1b05edfe5479f3c9f7cdb9f9f522be36ac6/components/constellation/constellation.rs#L1644

which goes away with these changes.

File: components/constellation/constellation.rs [hunk 1]
```diff
@@ -1753,9 +1744,35 @@ where
...
+                    .map(|pipeline| pipeline.webview_id)
+                {
+                    None => {
+                        return warn!(
+                            "{}: DiscardTopLevelBrowsingContext from closed pipeline",
+                            source_pipeline_id
+                        );
+                    },
+                    Some(ctx) => ctx,
+                };
```
Comment (Taym95) [inline components/constellation/constellation.rs]: this looks like lot of code duplication, can we do something about it?

Comment (mrobinson) [reply components/constellation/constellation.rs]: I recommend a helper at the top of the loop like:

```rust
let get_webview_id = || {
    let webview_id = self
        .pipelines
        .get(&source_pipeline_id)
        .map(|pipeline| pipeline.webview_id);
    if webview_id.is_none() {
        warn!(ScriptToConstellationMessage on closed pipeline ({source_pipeline_id})"); 
    }
    webview_id
};
```

Then in each match arm this could be:

```rust
let Some(webview_id) = get_webview_id() else {
    return;
}
```

**Comment by gterzian** [comment]
@mrobinson @Taym95 Thanks for the review; comments have been addressed. 

Note the the new TIMEOUT is dealt with over at https://github.com/servo/servo/pull/39833

**Review by jdm — APPROVED** [review]
