### PR TITLE
layout: Rewrite anonymous table code, simplify and fix table intrinsic width calculation, and improve safety of flexbox code.

### LINKED ISSUE #13782: Elements with `display: table-cell` don't respect explicit widths
Minimal test case:

    <!DOCTYPE html>
    <div style="width: 100%; display: table-cell">Hello world

This breaks Etsy.

### PR DESCRIPTION
**Pull request by pcwalton**
Closes #13782.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13870)

### CODE REVIEW

**Comment by Ms2ger** [comment]
r? @mbrubeck 

All I'd complain about is spec-related :)

File: components/layout/construct.rs [hunk 1]
```diff
@@ -1161,11 +1064,28 @@ impl<'a, ConcreteThreadSafeLayoutNode: ThreadSafeLayoutNode>
...
-        let mut wrapper_flow: FlowRef = Arc::new(
-            TableWrapperFlow::from_fragment(fragment, FloatKind::from_property(float_value)));
+    fn build_flow_for_table(&mut self, node: &ConcreteThreadSafeLayoutNode, float_value: float::T)
+                            -> ConstructionResult {
+        let mut legalizer = Legalizer::new();
+
+        let table_style = node.style(self.style_context());
+        let wrapper_style = self.style_context()
+                                .stylist
+                                .precomputed_values_for_pseudo(&PseudoElement::ServoTableWrapper,
```
Comment (emilio) [inline components/layout/construct.rs]: This pattern is becoming increasingly common, maybe add a helper for it in `SharedStyleContext`? Can be left as a followup, but please fill it if you decide to do so.

**Review by emilio — COMMENTED** [review]
Just a first pass with a few comments. The style parts look good to me. The layout parts make sense to me, though I'd have to do a lot of spec-reading to ensure it's correct.

**Comment by mbrubeck** [comment]
Some test results that weren't auto-linked above:

[mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/3695)
```
  ▶ PASS [expected FAIL] /mediaqueries-3_dev/html/min-width-tables-001.htm
```

[linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/355)
<details>
```
Tests with unexpected results:
  ▶ PASS [expected FAIL] /css21_dev/html4/color-applies-to-014.htm

  ▶ FAIL [expected PASS] /css21_dev/html4/table-anonymous-objects-009.htm
  └   → /css21_dev/html4/table-anonymous-objects-009.htm 9a467359e61bf1cd03e915a871942253e111a547
/css21_dev/html4/reference/no_red_antialiasing_a_bc_d-ref.htm 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1
Testing 9a467359e61bf1cd03e915a871942253e111a547 == 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1

  ▶ FAIL [expected PASS] /css21_dev/html4/table-anonymous-objects-020.htm
  └   → /css21_dev/html4/table-anonymous-objects-020.htm 9a467359e61bf1cd03e915a871942253e111a547
/css21_dev/html4/reference/no_red_antialiasing_a_bc_d-ref.htm 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1
Testing 9a467359e61bf1cd03e915a871942253e111a547 == 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1

  ▶ FAIL [expected PASS] /css21_dev/html4/table-anonymous-objects-019.htm
  └   → /css21_dev/html4/table-anonymous-objects-019.htm 9a467359e61bf1cd03e915a871942253e111a547
/css21_dev/html4/reference/no_red_antialiasing_a_bc_d-ref.htm 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1
Testing 9a467359e61bf1cd03e915a871942253e111a547 == 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1

  ▶ FAIL [expected PASS] /css21_dev/html4/table-anonymous-objects-010.htm
  └   → /css21_dev/html4/table-anonymous-objects-010.htm 9a467359e61bf1cd03e915a871942253e111a547
/css21_dev/html4/reference/no_red_antialiasing_a_bc_d-ref.htm 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1
Testing 9a467359e61bf1cd03e915a871942253e111a547 == 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1

  ▶ FAIL [expected PASS] /css21_dev/html4/table-anonymous-objects-018.htm
  └   → /css21_dev/html4/table-anonymous-objects-018.htm 9a467359e61bf1cd03e915a871942253e111a547
/css21_dev/html4/reference/no_red_antialiasing_a_bc_d-ref.htm 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1
Testing 9a467359e61bf1cd03e915a871942253e111a547 == 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1

  ▶ FAIL [expected PASS] /css21_dev/html4/table-anonymous-objects-012.htm
  └   → /css21_dev/html4/table-anonymous-objects-012.htm 9a467359e61bf1cd03e915a871942253e111a547
/css21_dev/html4/reference/no_red_antialiasing_a_bc_d-ref.htm 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1
Testing 9a467359e61bf1cd03e915a871942253e111a547 == 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1

  ▶ FAIL [expected PASS] /css21_dev/html4/table-anonymous-objects-011.htm
  └   → /css21_dev/html4/table-anonymous-objects-011.htm 9a467359e61bf1cd03e915a871942253e111a547
/css21_dev/html4/reference/no_red_antialiasing_a_bc_d-ref.htm 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1
Testing 9a467359e61bf1cd03e915a871942253e111a547 == 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1

  ▶ FAIL [expected PASS] /css21_dev/html4/table-anonymous-objects-017.htm
  └   → /css21_dev/html4/table-anonymous-objects-017.htm 9a467359e61bf1cd03e915a871942253e111a547
/css21_dev/html4/reference/no_red_antialiasing_a_bc_d-ref.htm 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1
Testing 9a467359e61bf1cd03e915a871942253e111a547 == 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1

  ▶ FAIL [expected PASS] /css21_dev/html4/table-anonymous-objects-197.htm
  └   → /css21_dev/html4/table-anonymous-objects-197.htm 9a467359e61bf1cd03e915a871942253e111a547
/css21_dev/html4/reference/no_red_antialiasing_a_bc_d-ref.htm 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1
Testing 9a467359e61bf1cd03e915a871942253e111a547 == 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1

  ▶ FAIL [expected PASS] /css21_dev/html4/table-anonymous-objects-198.htm
  └   → /css21_dev/html4/table-anonymous-objects-198.htm 9a467359e61bf1cd03e915a871942253e111a547
/css21_dev/html4/reference/no_red_antialiasing_a_bc_d-ref.htm 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1
Testing 9a467359e61bf1cd03e915a871942253e111a547 == 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1

  ▶ FAIL [expected PASS] /css21_dev/html4/table-anonymous-objects-199.htm
  └   → /css21_dev/html4/table-anonymous-objects-199.htm 9a467359e61bf1cd03e915a871942253e111a547
/css21_dev/html4/reference/no_red_antialiasing_a_bc_d-ref.htm 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1
Testing 9a467359e61bf1cd03e915a871942253e111a547 == 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1

  ▶ FAIL [expected PASS] /css21_dev/html4/table-anonymous-objects-200.htm
  └   → /css21_dev/html4/table-anonymous-objects-200.htm 9a467359e61bf1cd03e915a871942253e111a547
/css21_dev/html4/reference/no_red_antialiasing_a_bc_d-ref.htm 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1
Testing 9a467359e61bf1cd03e915a871942253e111a547 == 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1

  ▶ FAIL [expected PASS] /css21_dev/html4/table-anonymous-objects-203.htm
  └   → /css21_dev/html4/table-anonymous-objects-203.htm 9a467359e61bf1cd03e915a871942253e111a547
/css21_dev/html4/reference/no_red_antialiasing_a_bc_d-ref.htm 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1
Testing 9a467359e61bf1cd03e915a871942253e111a547 == 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1

  ▶ FAIL [expected PASS] /css21_dev/html4/table-anonymous-objects-202.htm
  └   → /css21_dev/html4/table-anonymous-objects-202.htm 9a467359e61bf1cd03e915a871942253e111a547
/css21_dev/html4/reference/no_red_antialiasing_a_bc_d-ref.htm 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1
Testing 9a467359e61bf1cd03e915a871942253e111a547 == 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1

  ▶ FAIL [expected PASS] /css21_dev/html4/table-anonymous-objects-201.htm
  └   → /css21_dev/html4/table-anonymous-objects-201.htm 9a467359e61bf1cd03e915a871942253e111a547
/css21_dev/html4/reference/no_red_antialiasing_a_bc_d-ref.htm 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1
Testing 9a467359e61bf1cd03e915a871942253e111a547 == 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1

  ▶ FAIL [expected PASS] /css21_dev/html4/table-anonymous-objects-204.htm
  └   → /css21_dev/html4/table-anonymous-objects-204.htm 9a467359e61bf1cd03e915a871942253e111a547
/css21_dev/html4/reference/no_red_antialiasing_a_bc_d-ref.htm 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1
Testing 9a467359e61bf1cd03e915a871942253e111a547 == 398e25f2937dcbd574d5e6d4aeb2542b5e1752f1

  ▶ PASS [expected FAIL] /mediaqueries-3_dev/html/min-width-tables-001.htm
```
</details>

**Comment by pcwalton** [comment]
I've investigated the failures.

* `/css21_dev/html4/color-applies-to-014.htm`: As far as I can tell, this is an incorrect test because it fails when browsers perform pixel snapping. Specifically, it tests to make sure that (effectively) `<div>Filler Text</div>` renders identitally to `<table><tr><td>Filler</td><td>&nbsp;Text</td></tr></table>` (with all borders/padding/margins/spacing on the tables removed). This can fail in browser engines like Servo that perform pixel snapping on table cells, since the "T" glyph can be subpixel aligned in the former case but not the latter.

* `/css21_dev/html4/table-anonymous-objects-???.htm`: These tests rely on summing a set of fractional pixel quantities to overlay the green text "abcd" directly on top of red text "abcd". They then check that the result is precisely equal to the green text "abcd". *The display lists come out correct from layout*, but WebRender introduces a small amount of rounding error somewhere on Linux (only) and there end up being tiny one-pixel differences around the edges of the letters.

I propose:

1. Ignoring `color-applies-to-014.htm` outright, as it's an incorrect test.

2. Marking `table-anonymous-objects-???.htm` as failing on Linux, as they trigger minor WebRender bugs on that platform.

Thoughts?

**Comment by Ms2ger** [comment]
As long as you mean "mark as failing" rather than "ignore".

**Comment by pcwalton** [comment]
What's the benefit of marking a test we believe to be invalid as failing instead of ignoring it? Its success depends on the details of the font on the platform.

File: components/layout/construct.rs [hunk 2]
```diff
@@ -1923,3 +1849,189 @@ impl ComputedValueUtils for ServoComputedValues {
...
+            (FlowClass::Table, FlowClass::TableRow) |
+            (FlowClass::Table, FlowClass::TableCaption) |
+            (FlowClass::TableRowGroup, FlowClass::TableRow) |
+            (FlowClass::TableRow, FlowClass::TableCell) => {
+                parent.add_new_child((*child).clone());
+                true
+            }
+
+            (FlowClass::Flex, FlowClass::Block) |
+            (FlowClass::Flex, FlowClass::Flex) => {
```
Comment (pcwalton) [inline components/layout/construct.rs]: If I don't allow `FlowClass::Flex` it breaks all the flexbox tests. This patch is too big already. I don't want to rewrite all the flexbox code.

**Comment by pcwalton** [comment]
Rebased and addressed review comments. Next steps: address test failures and split up the patch.

File: components/layout/construct.rs (hunk 2 above)
Comment (stshine) [inline components/layout/construct.rs]: Oh, I mean IMO the wrapper block should only be needed for `FlowClass::Inline` since other children are guaranteed to be block-like.

**Comment by pcwalton** [comment]
OK, comments addressed and patch cleaned up. This should be ready for review.

r? @mbrubeck

**Comment by stshine** [comment]
@bors-servo try

#13900 is merged.

File: components/style/selector_matching.rs [hunk 3]
```diff
@@ -252,25 +253,62 @@ impl Stylist {
...
+                                    Box::new(StdoutErrorReporter),
+                                    flags);
             Some(Arc::new(computed))
         } else {
             parent.map(|p| p.clone())
         }
     }
 
+    /// Returns the style for an anonymous box of the given type.
+    pub fn style_for_anonymous_box(&self,
```
Comment (emilio) [inline components/style/selector_matching.rs]: You should mark this function as `#[cfg(feature = "servo")]` so this compiles on Gecko.

**Comment by pcwalton** [comment]
@emilio Done.

File: components/script/dom/storage.rs [hunk 4]
```diff
@@ -196,7 +196,7 @@ impl Runnable for StorageEventRunnable {
         let root_context = script_thread.root_browsing_context();
         for it_context in root_context.iter() {
             let it_window = it_context.active_window();
-            assert!(UrlHelper::SameOrigin(&ev_url, &it_window.get_url()));
+            //assert!(UrlHelper::SameOrigin(&ev_url, &it_window.get_url()));
```
Comment (emilio) [inline components/script/dom/storage.rs]: Is this comment intentional?

File: components/layout/flow_list.rs [hunk 5]
```diff
@@ -52,27 +59,26 @@ impl FlowList {
...
+    /// to do so! See the comment above in `FlowList`.
     #[inline]
     pub fn iter<'a>(&'a self) -> impl DoubleEndedIterator<Item = &'a Flow> {
         self.flows.iter().map(|flow| &**flow)
     }
 
     /// Provide a forward iterator with mutable references
+    ///
+    /// SECURITY-NOTE(pcwalton): This does not hand out `FlowRef`s by design. Do not add a method
+    /// to do so! See the comment above in `FlowList`.
```
Comment (emilio) [inline components/layout/flow_list.rs]: ++

File: components/layout/flow_list.rs [hunk 6]
```diff
@@ -93,6 +99,21 @@ impl FlowList {
     }
 }
 
+impl Index<usize> for FlowList {
+    /// FIXME(pcwalton): O(n)!
```
Comment (emilio) [inline components/layout/flow_list.rs]: :(.

This is only used for flexbox for now right? I wonder if we could rename it to `nth_slow` and `nth_slow_mut` so it's more obvious and so it's not misused without knowledge.

**Review by emilio — COMMENTED** [review]
The layout code makes also sense to me, though I'd need to read a lot more about anonymous table wrappers so I can confidently r+ it.

If nobody reviews it this week I guess I'll do...

File: components/script/dom/storage.rs (hunk 4 above)
Comment (pcwalton) [inline components/script/dom/storage.rs]: Argh, no. I'll remove it. I keep having to make this change locally because this assertion fires all the time when saving pages locally to disk.

**Comment by emilio** [comment]
@pcwalton: @mbrubeck said he was going to take a look at this today, but if he doesn't this looks good to me.

**Comment by jdm** [comment]
`./mach build-geckolib` is failing, as is `manifest_changed.sh`.

File: tests/wpt/mozilla/meta/MANIFEST.json [hunk 7]
```diff
@@ -1424,6 +1424,18 @@
             "url": "/_mozilla/css/dirty_viewport.html"
           }
         ],
+        "css/display_table_cell_intrinsic_width_a.html": [
```
Comment (jdm) [inline tests/wpt/mozilla/meta/MANIFEST.json]: The new reftest appears to be missing from this PR.

**Comment by pcwalton** [comment]
Both issues should be fixed now.
