### PR TITLE
Fix intermittent macOS reftest failures

### LINKED ISSUE #23290: Intermittent reftest failures due to font selection choices
Test:
Screen Shot 2019-04-29 at 10 48 40 AM
Reference:
Screen Shot 2019-04-29 at 10 48 56 AM

https://searchfox.org/mozilla-central/source/testing/web-platform/tests/css/CSS2/syntax/at-charset-001.xht
https://searchfox.org/mozilla-central/source/testing/web-platform/tests/css/CSS2/syntax/at-charset-001-ref.xht
https://searchfox.org/mozilla-central/source/testing/web-platform/tests/css/CSS2/syntax/support/at-charset-001.css

It's not clear to me how this can happen, but it does.

### PR DESCRIPTION
**Pull request by jdm**
CTCreateFontWithName intermittently returns the wrong font for a given postscript name. These changes rely on obtaining a font descriptor, using it to get the path to the actual font file on disk, getting the bytes that make up the font, and using Core Graphics to create a font handle and obtaining the Core Graphics font from the CGFont reference. This is the same strategy that font-kit uses.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #23290
- [x] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24347)

### CODE REVIEW

File: components/gfx/platform/macos/font_template.rs [hunk 1]
```diff
@@ -86,7 +94,33 @@ impl FontTemplateData {
                         Err(_) => None,
                     }
                 },
-                None => core_text::font::new_from_name(&*self.identifier, clamped_pt_size).ok(),
+                None => {
```
Comment (pcwalton) [inline components/gfx/platform/macos/font_template.rs]: Add a comment linking to the issue. r=me with that.

File: tests/wpt/metadata/css/css-text/white-space/control-chars-089.html.ini [hunk 2]
```diff
@@ -1,2 +1,2 @@
 [control-chars-089.html]
-  expected: FAIL
+  sexpected: FAIL
```
Comment (atouchet) [inline tests/wpt/metadata/css/css-text/white-space/control-chars-089.html.ini]: Typo?

Comment (jdm) [reply tests/wpt/metadata/css/css-text/white-space/control-chars-089.html.ini]: Whoops.
