### PR TITLE
Window should own Location, Document shouldn't

### LINKED ISSUE #18438: Option::unwrap() on None in WindowBinding::get_location
Found on http://baskino.co, could not reproduce this a second time.

Stack trace (release mode):
```gdb
called `Option::unwrap()` on a `None` value (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(2) }, at /checkout/src/libcore/option.rs:335)
stack backtrace:
   0:     0x55675a6e60dc - backtrace::backtrace::trace::h0f1eee7f17c620ad
   1:     0x55675a6e6112 - backtrace::capture::Backtrace::new::h1abdde591da67f3d
   2:     0x556759445865 - servo::main::{{closure}}::h2775028620a930e9
   3:     0x55675bbfab26 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:612
   4:     0x55675bbfa944 - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:572
   5:     0x55675bbfa8b9 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x55675bbfa84a - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:498
   7:     0x55675bc34e30 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x55675bc34d66 - core::panicking::panic
                        at /checkout/src/libcore/panicking.rs:51
   9:     0x55675a200a50 - <script::dom::window::Window as script::dom::bindings::codegen::Bindings::WindowBinding::WindowBinding::WindowMethods>::Location::h12a65cfe69f6aeac
  10:     0x556759b45bd6 - std::panicking::try::do_call::h20bdd601404dd43b
  11:     0x55675bc01bcc - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  12:     0x55675a5a8261 - script::dom::bindings::codegen::Bindings::WindowBinding::WindowBinding::get_location::h5ea9a21ab502b7ae
  13:     0x55675a8e636c - CallJitGetterOp
                        at /shared/dev/rust/servo/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/3de4ff3/src/jsglue.cpp:498
  14:     0x556759fd16e1 - script::dom::bindings::utils::generic_call::h3cf5c8561aec2955
  15:     0x55675af623a1 - _ZN2js12CallJSNativeEP9JSContextPFbS1_jPN2JS5ValueEERKNS2_8CallArgsE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jscntxtinlines.h:232
  16:     0x55675af307f9 - _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:453
  17:     0x55675af30b20 - InternalCall
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:498
  18:     0x55675af30bb2 - _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:517
  19:     0x55675af313fd - _ZN2js10CallGetterEP9JSContextN2JS6HandleINS2_5ValueEEES5_NS2_13MutableHandleIS4_EE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:631
  20:     0x55675af543d8 - CallGetter
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/NativeObject.cpp:1737
  21:     0x55675af599bb - GetExistingProperty<(js::AllowGC)1>
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/NativeObject.cpp:1785
  22:     0x55675af5450b - _ZN2js25NativeGetExistingPropertyEP9JSContextN2JS6HandleIP8JSObjectEENS3_IPNS_12NativeObjectEEENS3_IPNS_5ShapeEEENS2_13MutableHandleINS2_5ValueEEE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/NativeObject.cpp:1808
  23:     0x55675aabebaf - _ZN2js9FetchNameILb0EEEbP9JSContextN2JS6HandleIP8JSObjectEES7_NS4_IPNS_12PropertyNameEEENS4_IPNS_5ShapeEEENS3_13MutableHandleINS3_5ValueEEE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter-inl.h:202
  24:     0x55675af2f438 - GetNameOperation
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:230
  25:     0x55675af3e9af - Interpret
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:3015
  26:     0x55675af3047b - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:399
  27:     0x55675af308c8 - _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:471
  28:     0x55675af30b20 - InternalCall
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:498
  29:     0x55675af30bb2 - _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:517
  30:     0x55675ad422fb - _ZN2js8fun_callEP9JSContextjPN2JS5ValueE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsfun.cpp:1256
  31:     0x55675af623a1 - _ZN2js12CallJSNativeEP9JSContextPFbS1_jPN2JS5ValueEERKNS2_8CallArgsE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jscntxtinlines.h:232
  32:     0x55675af307f9 - _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:453
  33:     0x55675af30b20 - InternalCall
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:498
  34:     0x55675af30b4a - _ZN2js13CallFromStackEP9JSContextRKN2JS8CallArgsE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:504
  35:     0x55675af3db76 - Interpret
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:2873
  36:     0x55675af3047b - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:399
  37:     0x55675af308c8 - _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:471
  38:     0x55675af30b20 - InternalCall
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:498
  39:     0x55675af30bb2 - _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:517
  40:     0x55675ad422fb - _ZN2js8fun_callEP9JSContextjPN2JS5ValueE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsfun.cpp:1256
  41:     0x55675af623a1 - _ZN2js12CallJSNativeEP9JSContextPFbS1_jPN2JS5ValueEERKNS2_8CallArgsE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jscntxtinlines.h:232
  42:     0x55675af307f9 - _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:453
  43:     0x55675af30b20 - InternalCall
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:498
  44:     0x55675af30b4a - _ZN2js13CallFromStackEP9JSContextRKN2JS8CallArgsE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:504
  45:     0x55675af3db76 - Interpret
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:2873
  46:     0x55675af3047b - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:399
  47:     0x55675af3183e - _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_16AbstractFramePtrEPS9_
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:679
  48:     0x55675af31afe - _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:712
  49:     0x55675aca11e5 - Evaluate
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsapi.cpp:4407
  50:     0x55675aca1520 - Evaluate
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsapi.cpp:4443
  51:     0x55675aca1aa0 - _ZN2JS8EvaluateEP9JSContextRKNS_22ReadOnlyCompileOptionsEPKDsmNS_13MutableHandleINS_5ValueEEE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsapi.cpp:4501
  52:     0x55675a09228b - script::dom::globalscope::GlobalScope::evaluate_script_on_global_with_result::{{closure}}::h83fc4921bb848a61
  53:     0x55675a091fad - script::dom::globalscope::GlobalScope::evaluate_script_on_global_with_result::hd6b6c282abf11e67
  54:     0x55675a0fffec - script::dom::htmlscriptelement::HTMLScriptElement::run_a_classic_script::h52442ddee9733c68
  55:     0x55675a0ff169 - script::dom::htmlscriptelement::HTMLScriptElement::execute::h26e02815c40a4313
  56:     0x55675a04150a - script::dom::document::Document::asap_script_loaded::h2c56184436552f9b
  57:     0x55675a0fa5f3 - <script::dom::htmlscriptelement::ScriptContext as net_traits::FetchResponseListener>::process_response_eof::h1e774f544905b750
  58:     0x55675a23e0db - <script::network_listener::ListenerRunnable<A, Listener> as script::script_thread::Runnable>::handler::h1ea5d021e9e008c6
  59:     0x55675a244351 - <script::script_thread::CancellableRunnable<T> as script::script_thread::Runnable>::main_thread_handler::h32c4de0836642461
  60:     0x55675a26291c - script::script_thread::ScriptThread::handle_msg_from_script::h51bceeab9eb522ae
  61:     0x55675a25b24e - script::script_thread::ScriptThread::handle_msgs::{{closure}}::hdd3fd9041a1efa8f
  62:     0x55675a2578cf - script::script_thread::ScriptThread::handle_msgs::h4aadf07f4dff3bf3
  63:     0x55675a252ceb - script::script_thread::ScriptThread::start::h543e6bc16496788a
  64:     0x556759b028f0 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcbce24426485d7f2
  65:     0x556759c2f605 - std::panicking::try::do_call::h8ef268d0617cbd63
  66:     0x55675bc01bcc - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  67:     0x556759e390b2 - <F as alloc::boxed::FnBox<A>>::call_box::h4e198348b3252fbb
  68:     0x55675bbf97ab - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:692
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84
  69:     0x7f58ba504493 - start_thread
  70:     0x7f58ba031abe - __clone
  71:                0x0 - <unknown>
```

### PR DESCRIPTION
**Pull request by asajeffrey**
Document shouldn't own location, Window should.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #18438
- [X] These changes do not require tests because it's an intermittent

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18578)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo r+

Looks good.

File: components/script/dom/document.rs [hunk 1]
```diff
@@ -3438,7 +3436,7 @@ impl DocumentMethods for Document {
 
     // https://html.spec.whatwg.org/multipage/#dom-document-location
     fn GetLocation(&self) -> Option<Root<Location>> {
-        self.browsing_context().map(|_| self.location.or_init(|| Location::new(&self.window)))
+        self.browsing_context().map(|_| self.window.Location())
```
Comment (KiChjang) [inline components/script/dom/document.rs]: I believe the document needs to be checked whether it's [`fully active`](https://html.spec.whatwg.org/multipage/browsers.html#fully-active), instead of checking whether there's a browsing context.

Comment (asajeffrey) [reply components/script/dom/document.rs]: Fixed.
