### PR TITLE
Use the correct origin in fetch

### LINKED ISSUE #18147: Correctly use request's origin when determining same origin requests
In #17521, under the http_redirect_fetch step 7, we are still using the request's current URL's origin when making a comparison with the location URL's origin. This is incorrect, but when using the following (correct) code of comparing the origins:
```rust
let same_origin = match request.origin {
    Origin::Origin(ref origin) => *origin == location_url.origin,
    Origin::Client => false,
};
```
we encountered some WPT failures due to the code having an origin that is not what the WPT expects.

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #18147.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18882)

### CODE REVIEW

**Comment by KiChjang** [comment]
So the problem here is always with the case where we have to do cross-origin redirects... somehow the tests do not expect the request's origin to be the original document's URL's origin...

File: components/net/http_loader.rs [hunk 1]
```diff
@@ -674,8 +674,10 @@ pub fn http_redirect_fetch(request: &mut Request,
     request.redirect_count += 1;
 
     // Step 7
-    // FIXME: Correctly use request's origin
-    let same_origin = location_url.origin() == request.current_url().origin();
+    let same_origin = match request.origin {
+        Origin::Origin(ref origin) => *origin == location_url.origin(),
+        Origin::Client => false,
```
Comment (nox) [inline components/net/http_loader.rs]: Why is this correct?

https://fetch.spec.whatwg.org/#concept-request-origin says you are not supposed to have a "client" value at this point in time, so at the very least that FIXME needs to stay.

Comment (KiChjang) [reply components/net/http_loader.rs]: Because every time we create a request, we make sure to initialize it with the global's origin, so that the origin can never be client.

Comment (nox) [reply components/net/http_loader.rs]: Make it panic, then.

**Comment by KiChjang** [comment]
I _think_ I've found the problem - in HTTP redirect fetch step 10, we shouldn't be using the `same_origin` variable that we created at step 7, because that compares the location URL's origin against the request's origin, while what we actually need there is the origin of request's current URL and location URL's origin.

**Comment by jdm** [comment]
@bors-servo: r+
Glad you found the missing piece!

**Comment by nox** [comment]
No test?

**Comment by jdm** [comment]
That's a good point - a test for this would require making a fetch (using cors mode) to a same-origin URL that includes credentials, and the response for that contains a 302 to a cross-origin URL. The result should be a rejection of the fetch promise.

**Review by jdm — APPROVED** [review]
This looks good if the test fails without this change!

**Comment by KiChjang** [comment]
@jdm This is actually incredibly hard to test for. You mentioned on IRC:
> so I suspect that a test case that would reveal the problem is if we had a request that started same-origin, 302 to a cross-origin URL (a.com) with no credentials, and that does a 302 to a same-origin (a.com) URL with credentials

Turns out the new code does indeed skip over the check at step 7, but then immediately fails at step 8:
> If CORS flag is set and actualResponse’s location URL includes credentials, then return a network error.

The second redirection has the CORS flag set, and does include credentials, so it'll always fail.

**Comment by KiChjang** [comment]
So an idea I have here is to check the error message and ensure that it's generating the error message from step 8, instead of step 7. But in order to do so, I'll have to change this line here to return the error that was encountered during fetch, instead of making a new one from scratch:
https://github.com/servo/servo/blob/a3f2fae561de26fefb0ac0d569ce2c7a2942eee5/components/script/fetch.rs#L128-L142

**Comment by KiChjang** [comment]
Wow ok, that also comes with another problem - since this error string is specific to Servo, I need to extract this test out of WPT and put it under `tests/wpt/mozilla/`, but it looks like we don't have any testing infrastructure for doing CORS under that directory...

**Comment by jdm** [comment]
Ok, I've looked over the code and I do not believe it's worth all the effort to make a testcase that demonstrates this working correctly. It's particularly challenging because it's only this particular piece of code that gets the origin check wrong; the most important one in main_fetch does it right, which is why the cors flag is set. Therefore, let's remove 91c2b79 (because network errors are supposed to be opaque to content code) and let's remove 833501b91cc5490fb89ab5733505205aad44b86e as well. r=me with those omissions!
