### PR TITLE
script: Fix handling changes to relevant attributes for stylesheets

### LINKED ISSUE #42259: panic: What finished? (thread Script#1, at components/script/dom/html/htmllinkelement.rs:870)
Minimal testcase:

```html
<!DOCTYPE html>
<link id="link" rel="stylesheet"></link>
<script>
  link.type = "text/css";
  link.type = "text/css";
</script>
```

System: Linux
Version: Version: Servo 0.0.4-ecb4549e1
Command: `./servo/servo`

```
What finished? (thread Script#1, at components/script/dom/html/htmllinkelement.rs:870)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::panic_with_hook
   3: std::panicking::panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: __rustc::rust_begin_unwind
   6: core::panicking::panic_fmt
   7: <script::dom::html::htmllinkelement::HTMLLinkElement as script::stylesheet_loader::StylesheetOwner>::load_finished
   8: script::stylesheet_loader::StylesheetContext::do_post_parse_tasks
   9: <T as script::task::TaskBox>::run_box
  10: script::script_thread::ScriptThread::handle_msg_from_script
  11: script::script_thread::ScriptThread::handle_msgs::{{closure}}
  12: script::script_thread::ScriptThread::handle_msgs
  13: std::sys::backtrace::__rust_begin_short_backtrace
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: std::sys::thread::unix::Thread::new::thread_start
  16: start_thread
             at ./nptl/pthread_create.c:447:8
  17: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
```

### PR DESCRIPTION
**Pull request by TimvdLippe**
We weren't removing stylesheets when we should be doing so. This most notably happens when the stylesheet no longer has a href or its "rel" changes.

The crash is also fixed, since the issue was that we were passing the value of the attribute that was changed as if it were an href. However, if we set the type attribute, then that's not the href.

To fix that, we now retrieve the href inside the method so we always have the correct value.

Fixes #42259

### CODE REVIEW

File: components/script/dom/html/htmllinkelement.rs [hunk 1]
```diff
@@ -248,18 +257,37 @@ impl VirtualMethods for HTMLLinkElement {
...
                 self.relations
                     .set(LinkRelations::for_element(self.upcast()));
+
+                // If relations haven't changed, we shouldn't do anything
+                if previous_relations == self.relations.get() {
+                    return;
+                }
+
+                // https://html.spec.whatwg.org/multipage/#link-type-stylesheet:fetch-and-process-the-linked-resource
+                // > When the external resource link is created on a link element that is already browsing-context connected.
```
Comment (mrobinson) [inline components/script/dom/html/htmllinkelement.rs:274]: Nit: This might be a bit more readable with the header text to this list:

```suggestion
                // https://html.spec.whatwg.org/multipage/#link-type-stylesheet:fetch-and-process-the-linked-resource
                // >The appropriate times to fetch and process this type of link are:
                // > ...
                // > When the external resource link is created on a link element that is already browsing-context connected.
                // > ...
```

File: components/script/dom/html/htmllinkelement.rs [hunk 2]
```diff
@@ -157,18 +157,27 @@ impl HTMLLinkElement {
         self.request_generation_id.get()
     }
 
+    fn remove_stylesheet(&self) {
+        if let Some(s) = self.stylesheet.borrow_mut().take() {
```
Comment (mrobinson) [inline components/script/dom/html/htmllinkelement.rs]: Nit:


```suggestion
        if let Some(stylesheet) = self.stylesheet.borrow_mut().take() {
```

**Review by mrobinson — APPROVED** [review]

File: components/script/dom/html/htmllinkelement.rs (hunk 1 above)
Comment (TimvdLippe) [reply components/script/dom/html/htmllinkelement.rs:274]: We don't do this for all the other cases and since there are plenty, I think this is a bit too verbose.
