### PR TITLE
servoshell: Use sRGB colorspace on macOS

### LINKED ISSUE #33676: Incorrect handeling of wide gamut color spaces
**Describe the bug:**
Servo doesn't handle color space correctly. On a MacBook inbuilt screen, it shows all content in Display P3, even if that content is intended to be displayed in sRGB, resulting in over-saturated colors.

**To Reproduce:**
This WebKit example can be used to test proper color space management: [https://webkit.org/blog-files/color-gamut/]( https://webkit.org/blog-files/color-gamut/). Bare in mind these screenshots will need to be viewed on a display and browser capable of handling P3 correctly.

Result on Firefox (Incorrect - Supports sRGB only P3 content not shown):
Screenshot 2024-10-06 at 17 46 40

Result on Safari (Correct):
Screenshot 2024-10-06 at 17 47 26

Result on Servo (Incorrect - Displays sRGB as P3)
Screenshot 2024-10-06 at 17 47 42

To give you a bit of an idea, if squashed these examples into sRGB, obviously not correct but allows you to see the differences on a non-P3 capable monitor.
mScreenshot 2024-10-06 at 17 54 23

**Platform:**
macOS Sequoia, M1 MacBook Pro

### PR DESCRIPTION
**Pull request by IsaacMarovitz**
By default, macOS will use a `NSWindow` in Display P3, in the case of Servo, which lacks proper color space management, this results in sRGB colors becoming oversaturated and bright as they are improperly displayed. To resolve this, we can force macOS to use an sRGB `NSWindow`.

This will of course need to be changed/removed if and when Servo gains proper wide color gamut support.

This change does not fix the improper clipping of wide color gamut values observed in the original issue.

Before:
Screenshot 2025-02-26 at 12 15 27

After:
Screenshot 2025-02-26 at 12 14 26

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes improve, but don't fix #33676,  #33356
- [X] These changes do not require tests because they only affect servoshell presentation

### CODE REVIEW

File: ports/servoshell/desktop/headed_window.rs [hunk 1]
```diff
@@ -100,6 +106,20 @@ impl Window {
             winit_window.set_window_icon(Some(load_icon(icon_bytes)));
         }
 
+        #[cfg(target_os = "macos")]
```
Comment (jdm) [inline ports/servoshell/desktop/headed_window.rs:109]: Could we move this into a `force_srgb_color_space` helper function so this main initialization remains relatively high level? Otherwise this seems fine to me.

**Review by jdm — APPROVED** [review]
This seems fine to me!

File: ports/servoshell/desktop/headed_window.rs (hunk 1 above)
Comment (IsaacMarovitz) [reply ports/servoshell/desktop/headed_window.rs:109]: I can, might be a bit messy tho.

**Comment by IsaacMarovitz** [comment]
Fixing build one sec
