### PR TITLE
Inline split fixes#12699

### LINKED ISSUE #12699: Borders of inline elements are wrong for broken lines
Minimal test:
```
<!doctype html>
<html><body>
<style>
div {
  width: 5em;
}
span {
  border-left: yellow solid 0.5em;
  border-right: yellow solid 0.5em;
}
</style>
<div>
  <span>Very long text</span>
</div>
</body></html>

```
Servo:
screenshot_20160803_010231
Firefox:
firefox

### PR DESCRIPTION
**Pull request by splav**
Fix fragment splitting algorithm to set FIRST/LAST_FRAGMENT_OF_ELEMENT flag correctly, account for border_padding for border_box and set zero border_padding between for new fragments.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #12699 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12760)

### CODE REVIEW

**Comment by splav** [comment]
The thing I'm concerned about is that the test is not fully adequate. The sizes, even in em are font-dependant and the line breakage can happen in different places.
The max_inline_size change makes breakage behave like in Firefox. Honestly, I haven't checked the specs.
And, sorry, I've mixed up commit names, will fix them among other fixes after review.

File: components/layout/fragment.rs [hunk 1]
```diff
@@ -1644,7 +1644,7 @@ impl Fragment {
             _   => return None,
         };
 
-        let mut remaining_inline_size = max_inline_size;
+        let mut remaining_inline_size = max_inline_size - self.border_padding.inline_start_end();
```
Comment (pcwalton) [inline components/layout/fragment.rs]: Could you add a comment saying that `self.border_padding.inline_start_end` (presumably) will only be nonzero in the incremental reflow case (I guess?)

This could easily regress.

Comment (pcwalton) [inline components/layout/fragment.rs]: Disregard previous comment, I was very confused. Sorry about that.

File: components/layout/inline.rs [hunk 2]
```diff
@@ -636,7 +636,23 @@ impl LineBreaker {
         // Push the first fragment onto the line we're working on and start off the next line with
         // the second fragment. If there's no second fragment, the next line will start off empty.
         match (inline_start_fragment, inline_end_fragment) {
-            (Some(inline_start_fragment), Some(inline_end_fragment)) => {
+            (Some(mut inline_start_fragment), Some(mut inline_end_fragment)) => {
+                inline_start_fragment.border_padding.inline_end = Au(0);
+                if let Some(ref mut inline_context) = inline_start_fragment.inline_context {
+                    for node in inline_context.nodes.iter_mut() {
```
Comment (pcwalton) [inline components/layout/inline.rs]: Could just be `for node in &mut inline_context.nodes {` I think

File: components/layout/inline.rs [hunk 3]
```diff
@@ -636,7 +636,23 @@ impl LineBreaker {
...
+                        node.flags.remove(LAST_FRAGMENT_OF_ELEMENT);
+                    }
+                }
+                inline_start_fragment.border_box.size.inline += inline_start_fragment.border_padding.inline_start;
+
+                inline_end_fragment.border_padding.inline_start = Au(0);
+                if let Some(ref mut inline_context) = inline_end_fragment.inline_context {
+                    for node in inline_context.nodes.iter_mut() {
```
Comment (pcwalton) [inline components/layout/inline.rs]: Same as above: I believe this could be `for node in &mut inline_context.nodes {`

**Comment by pcwalton** [comment]
Just had a couple of review nits to address and then this looks good. Thanks!

**Comment by pcwalton** [comment]
Don't worry about the test; as long as it splits in the right place on at least one of our bots it will catch any regressions.

**Comment by notriddle** [comment]
Couldn't you use Ahem, the test font?

**Comment by notriddle** [comment]
About your question, you can ask the bot for a particular reviewer using `r?`. For example:

r? @notriddle

**Comment by splav** [comment]
@notriddle I've changed the tests, looking at other test, using Ahem font. Is this version looking better. I've also changed the div width to get the same result.

File: tests/wpt/mozilla/tests/css/border_inline_split.html [hunk 4]
```diff
@@ -0,0 +1,20 @@
+<!doctype html>
+<html><head>
+<link rel=match href=border_inline_split_ref.html>
+<meta content="ahem dom" name="flags">
+<style>
+    div {
+        width: 9em;
```
Comment (notriddle) [inline tests/wpt/mozilla/tests/css/border_inline_split.html]: Make the div 20px Ahem font. That way the em size is consistent everywhere.

**Comment by notriddle** [comment]
Other than that, looks awesome! Fix it, then r=me.

**Comment by splav** [comment]
Fixed
r=@notriddle

**Comment by jdm** [comment]
@bors-servo: r=notriddle
Thanks for jumping on that, @notriddle!

**Comment by splav** [comment]
@jdm argh... I should finally put the bot commands list somewhere in the bookmarks... Thanks.

**Comment by notriddle** [comment]
@splav Since I can't delegate, you wouldn't have been able to do it anyway.

**Comment by splav** [comment]
@notriddle OK, I see.

**Comment by notriddle** [comment]
Platform-specific pass, probably because of Core Fonts. Just put something like this in:

File: `tests/wpt/metadata-css/css21_dev/html4/c5509-ipadn-l-003.htm.ini`
```
[c5509-ipadn-l-003.htm]
  type: reftest
  expected:
    if os == "mac": FAIL
```

**Comment by emilio** [comment]
Awesome work here @splav, thanks! :)
