### PR TITLE
script: Get the window rectangle from the `WebViewDelegate` instead of via the compositor

### LINKED ISSUE #37824: `ScreenY` and `outerHeight` ignores the title bar height
**Describe the bug:**
Right now, this is done in Script like following:
https://github.com/servo/servo/blob/a13f9bce62b6a7044082925a56e6238377e49100/components/script/dom/window.rs#L1662-L1666

It sends the request to compositor, who ignores the toolbar height etc., giving inaccurate result.
For details, see https://github.com/servo/servo/pull/37812#pullrequestreview-2977497013

**To Reproduce:**
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <button id="logButton">Log Screen Info</button>

    <script>
        document.getElementById('logButton').addEventListener('click', function() {
            console.log('ScreenX:', window.screenX);
            console.log('ScreenY:', window.screenY);
            console.log('OuterWidth:', window.outerWidth);
            console.log('OuterHeight:', window.outerHeight);
        });
    </script>
</body>
</html>
```

**Platform:**
All.

### PR DESCRIPTION
**Pull request by yezhizhen**
Previously, `screenX`, `screenY`, `outerHeight`, `outerWidth`, `moveBy`, `resizeBy` ask compositor for window rectangle, which then return "inner" rectangle after consulting Embedder.

This PR 
1. removes `GetClientWindowRect` from compositor, and directly let script ask embedder.
2. add `window_size` to `ScreenGeometry`
3. add a lot of docs to `ScreenGeometry`

Testing: `tests\wpt\mozilla\tests\mozilla\window_resizeTo.html` can now pass for Headed Window.
Fixes: #37824

### CODE REVIEW

**Comment by yezhizhen** [comment]
Ah just found out one more bug.. Fixing in #37961. We would have new wpt passing when combining both!

**Comment by yezhizhen** [comment]
> Ah just found out one more bug.. Fixing in #37961. We would have new wpt passing when combining both!

https://github.com/servo/servo/pull/37899#issuecomment-3052566865
Just found out that test was passed accidentally a few days ago... But the change here would make it pass for headed window.

**Review by jdm — APPROVED** [review]

File: components/servo/webview_delegate.rs [hunk 1]
```diff
@@ -476,6 +477,11 @@ pub trait WebViewDelegate {
         None
     }
 
+    /// Get the window rectangle.
+    fn window_rect(&self, _webview: WebView) -> DeviceIndependentIntRect {
+        DeviceIndependentIntRect::default()
+    }
+
```
Comment (mrobinson) [inline components/servo/webview_delegate.rs]: Please do not add a new `WebViewDelegate` method for this, as now the embedder needs to implement two things in order to properly communicate window sizes. Instead in libservo, somehow access the `RenderingContext` size and the offset from the existing`screen_geometry()` method.

**Review by mrobinson — CHANGES_REQUESTED** [review]

File: components/servo/webview_delegate.rs (hunk 1 above)
Comment (mrobinson) [reply components/servo/webview_delegate.rs]: The `hidpi_scale_factor` is stored in `WebViewInner` as part of the `WebView` struct, so you should have access to it in libservo.

Comment (yezhizhen) [reply components/servo/webview_delegate.rs]: Thanks. But `RenderingContext`/`WindowRenderingContext` etc. all only holds `inner_size`, same as the previous compositor proxy. 

I also checked `WebViewInner.rect`, which is supposed to be inner_size rect, but currently heavily & wrongly mix-used.. (Will file an issue tomorrow)

TL;DR: It is still difficult to get `outer_size` without adding method to `WebViewDelegate`...

Comment (yezhizhen) [reply components/servo/webview_delegate.rs]: > now the embedder needs to implement two things in order to properly communicate window sizes.

I have a idea: remove `fn window_rect` from `WindowPortsMethods` added last week in #37812. Just move logic to our newly created `WebViewDelegate::window_rect`.

This way, we also supports egl.

Comment (mrobinson) [reply components/servo/webview_delegate.rs]: I see. So the issue is that we really need the outer window rect and also the inner window rect? Can you have `ScreenGeometry` return this information? I think it makes sense that we get all of this information in a similar place (for now) so that the person embedding Servo understands how all the parts fit together.

```
/// Information about a `WebView`'s screen and containing window geometry. This
/// is used for the [Screen](https://drafts.csswg.org/cssom-view/#the-screen-interface)
/// CSSOM APIs and `window.screenLeft` / `window.screenTop`.
#[derive(Clone, Copy, Debug, Default)]
pub struct ScreenGeometry {
    /// The size of the screen in device pixels. This will be converted to
    /// CSS pixels based on the pixel scaling of the `WebView`.
    pub size: DeviceIntSize,
    /// The available size of the screen in device pixels. This size is the size
    /// available for web content on the screen, and should be `size` minus any system
    /// toolbars, docks, and interface elements. This will be converted to
    /// CSS pixels based on the pixel scaling of the `WebView`.
    pub available_size: DeviceIntSize,
    /// The rectangle in device pixels of the `WebView`'s containing window on the screen.
    pub window_rect: DeviceIntRect,
    /// The offset of the `WebView` in its containing window in device pixels..
    pub offset_in_window: DeviceIntPoint,
```

Would that work?

Comment (yezhizhen) [reply components/servo/webview_delegate.rs]: Works like a charm.

File: components/servo/lib.rs [hunk 2]
```diff
@@ -998,6 +999,28 @@ impl Servo {
...
                 }
             },
+            EmbedderMsg::GetWindowRect(webview_id, response_sender) => {
+                let window_rect = if let Some(webview) = self.get_webview_handle(webview_id) {
+                    let dpi = webview.dpi();
+                    let screen = webview.delegate().screen_geometry(webview).unwrap();
+                    let pos = screen.window_offset.to_f32();
+                    let window_size = screen.window_size.to_f32();
+
+                    let pos_in_css_pixel = (pos / dpi).round().to_i32();
```
Comment (yezhizhen) [inline components/servo/lib.rs]: I have an important question, given that I encountered several rounding display/layout issues before (e.g. #37243). Should we round or truncate?
They seem to be mix-used in Servo rn. Compositor always truncates. Layout sometimes rounds.
cc @Loirooriol @sagudev

Personally, I tends to keep fractional value as long as possible (like during layout calculation), and round when we have to. Never truncates.

Comment (yezhizhen) [reply components/servo/lib.rs]: This can be left as an open question. I am only certain that WebDriver [set window rect](https://w3c.github.io/webdriver/#set-window-rect) should always round.
Can you review this pls? @mrobinson

Comment (mrobinson) [reply components/servo/lib.rs]: This is a good question that I don't know the answer to. :/

File: components/script/dom/window.rs [hunk 3]
```diff
@@ -2151,18 +2144,13 @@ impl Window {
...
-        (
-            Size2D::new(rect.size().width as u32, rect.size().height as u32),
-            Point2D::new(rect.min.x, rect.min.y),
-        )
+    fn client_window(&self) -> DeviceIndependentIntRect {
+        let (sender, receiver) = ipc::channel().expect("Failed to create IPC channel!");
+
+        let msg = EmbedderMsg::GetWindowRect(self.webview_id(), sender);
+        self.send_to_embedder(msg);
+
```
Comment (mrobinson) [inline components/script/dom/window.rs]: Nit: no need for a temporary here:

```suggestion
        self.send_to_embedder( EmbedderMsg::GetWindowRect(self.webview_id(), sender));
        
```

File: components/servo/webview.rs [hunk 4]
```diff
@@ -172,6 +172,10 @@ impl WebView {
         self.0.borrow_mut()
     }
 
+    pub(crate) fn dpi(&self) -> Scale<f32, DeviceIndependentPixel, DevicePixel> {
+        self.inner().hidpi_scale_factor
```
Comment (mrobinson) [inline components/servo/webview.rs]: Nit: Since this is a getter, please give the same name as the member returned:

```suggestion
    pub(crate) fn hidpi_scale_factor(&self) -> Scale<f32, DeviceIndependentPixel, DevicePixel> {
        self.inner().hidpi_scale_factor
```

File: components/script/dom/window.rs [hunk 5]
```diff
@@ -1706,33 +1703,29 @@ impl WindowMethods<crate::DomTypeHolder> for Window {
 
     // https://drafts.csswg.org/cssom-view/#dom-window-moveby
     fn MoveBy(&self, x: i32, y: i32) {
-        let (_, origin) = self.client_window();
+        let pos = self.client_window().min;
```
Comment (mrobinson) [inline components/script/dom/window.rs]: I think `origin` might be a better name here honestly. `pos` is a bit general and I think we should try avoid too many abbreviations in the code.

File: components/servo/lib.rs [hunk 6]
```diff
@@ -998,6 +999,28 @@ impl Servo {
                     webview.delegate().show_form_control(webview, form_control);
                 }
             },
+            EmbedderMsg::GetWindowRect(webview_id, response_sender) => {
+                let window_rect = if let Some(webview) = self.get_webview_handle(webview_id) {
+                    let dpi = webview.dpi();
```
Comment (mrobinson) [inline components/servo/lib.rs]:
```suggestion
                    let hidpi_scale_factor = webview.hidpi_scale_factor();
```

File: components/servo/lib.rs [hunk 7]
```diff
@@ -998,6 +999,28 @@ impl Servo {
                     webview.delegate().show_form_control(webview, form_control);
                 }
             },
+            EmbedderMsg::GetWindowRect(webview_id, response_sender) => {
+                let window_rect = if let Some(webview) = self.get_webview_handle(webview_id) {
```
Comment (mrobinson) [inline components/servo/lib.rs]: Let's make this an anonymous function so that you can do early returns if any step of this fails:


```suggestion
                let window_rect = || {
                    let Some(webview) = self.get_webview_handle(webview_id) else {
                        return Default::default()
                    }
                }
```

File: components/servo/lib.rs [hunk 8]
```diff
@@ -998,6 +999,28 @@ impl Servo {
...
+                    let dpi = webview.dpi();
+                    let screen = webview.delegate().screen_geometry(webview).unwrap();
```
Comment (mrobinson) [inline components/servo/lib.rs]: This `unwrap` means that by default Servo will panic as the default implementation of `fn screen_geometry` returns `None`. Please do this:

```suggestion
                    let Some(screen_geometry) = webview.delegate().screen_geometry(webview) else {
                        return Default::default();
                    }
```

File: components/servo/lib.rs [hunk 9]
```diff
@@ -998,6 +999,28 @@ impl Servo {
...
+                    let pos = screen.window_offset.to_f32();
```
Comment (mrobinson) [inline components/servo/lib.rs]: Nit (sorry, I like to avoid generic abbreviations like `pos` as it makes the following code easier to understand):

```suggestion
                    let window_offset = screen.window_offset.to_f32();
```

File: components/servo/lib.rs [hunk 10]
```diff
@@ -998,6 +999,28 @@ impl Servo {
...
+                    let window_size = screen.window_size.to_f32();
+
+                    let pos_in_css_pixel = (pos / dpi).round().to_i32();
+                    let window_size_in_css_pixel = (window_size / dpi).round().to_i32();
+                    DeviceIndependentIntRect::from_origin_and_size(
+                        pos_in_css_pixel,
+                        window_size_in_css_pixel,
+                    )
```
Comment (mrobinson) [inline components/servo/lib.rs]: I think you can simplify all the conversions a bit by doing this:

```suggestion
                    (DeviceIndependentIntRect::from_origin_and_size(window_offset, window_size) / dpi).to_i32()
                        pos_in_css_pixel,
                        window_size_in_css_pixel,
                    )
```

File: components/servo/lib.rs [hunk 11]
```diff
@@ -998,6 +999,28 @@ impl Servo {
...
+                } else {
+                    warn!("{webview_id} is invalid");
```
Comment (mrobinson) [inline components/servo/lib.rs]: I think you can omit the warning since we aren't doing this consistently in this file.

File: components/servo/lib.rs [hunk 12]
```diff
@@ -998,6 +999,28 @@ impl Servo {
...
+                    DeviceIndependentIntRect::default()
+                };
+
+                if let Err(error) = response_sender.send(window_rect) {
+                    warn!("Failed to send response of GetWindowRect: {error}");
```
Comment (mrobinson) [inline components/servo/lib.rs]: Super nit:

```suggestion
                    warn!("Failed to respond to GetWindowRect: {error}");
```

**Review by mrobinson — CHANGES_REQUESTED** [review]
Looking great. This is a nice cleanup. Just one real issue here and bunch of nits. Thanks!

File: components/servo/lib.rs (hunk 8 above)
Comment (yezhizhen) [reply components/servo/lib.rs]: Ok. I wrote like this because all egl/desktop implementation of `screen_geometry` returns `Some`.

Comment (mrobinson) [reply components/servo/lib.rs]: Sure, but we don't have control over what other embedders do (the embedding API is meant to be generic and public) and the interface allows returning `None` as a valid response. We need to obey the contract the API gives.

File: components/servo/lib.rs (hunk 10 above)
Comment (yezhizhen) [reply components/servo/lib.rs]: I tried a bit. Sadly, none of the conversion works.

File: components/shared/embedder/lib.rs [hunk 13]
```diff
@@ -754,22 +757,30 @@ pub struct NotificationAction {
...
     pub available_size: DeviceIntSize,
-    /// The offset of the `WebView` in device pixels for the purposes of the `window.screenLeft`
-    /// and `window.screenTop` APIs. This will be converted to CSS pixels based on the pixel scaling
-    /// of the `WebView`.
-    pub offset: DeviceIntPoint,
+    /// The offset of the `WebView` in device pixels for the purposes of the
+    /// `window.screenLeft`, `window.screenX`, `window.screenTop`,
+    /// `window.screenY`, and `window.moveBy` APIs.
+    /// This will be converted to CSS pixels based on the pixel scaling of the `WebView`.
+    pub window_offset: DeviceIntPoint,
```
Comment (mrobinson) [inline components/shared/embedder/lib.rs]: Now that I'm seeing this...it's kinda weird that this isn't simply a `window_rect`. 😅 Let me make that change and then I'll land this one.

Comment (mrobinson) [reply components/shared/embedder/lib.rs]: Hmm....and that is exactly what I suggested in https://github.com/servo/servo/pull/37960#discussion_r2195623161. Do we not need `offset_in_window` yet?

Comment (yezhizhen) [reply components/shared/embedder/lib.rs]: `offset_in_window` means inner rectangle? We don't need it yet.

File: components/servo/lib.rs [hunk 14]
```diff
@@ -998,6 +1000,29 @@ impl Servo {
...
+                        return DeviceIndependentIntRect::default();
+                    };
+
+                    (Box2D::from_origin_and_size(
+                        screen_geometry.window_offset,
+                        screen_geometry.window_size,
+                    )
+                    .to_f32() /
+                        hidpi_scale_factor)
+                        .to_i32()
```
Comment (yezhizhen) [inline components/servo/lib.rs:1014]: also needs `round()` here before convert to i32. @mrobinson

File: components/shared/embedder/lib.rs (hunk 13 above)
Comment (yezhizhen) [reply components/shared/embedder/lib.rs]: > Let me make that change and then I'll land this one.

Thanks! There was indeed some misunderstanding. Pls also land rounding change.

File: components/servo/lib.rs [hunk 15]
```diff
@@ -998,6 +999,25 @@ impl Servo {
...
+                    let Some(webview) = self.get_webview_handle(webview_id) else {
+                        return DeviceIndependentIntRect::default();
+                    };
+                    let hidpi_scale_factor = webview.hidpi_scale_factor();
+                    let Some(screen_geometry) = webview.delegate().screen_geometry(webview) else {
+                        return DeviceIndependentIntRect::default();
+                    };
+
+                    (screen_geometry.window_rect.to_f32() / hidpi_scale_factor)
+                        .round_out()
```
Comment (yezhizhen) [inline components/servo/lib.rs]: Should `round` instead of `round_out`, because we want "as close as possible" as claimed in https://github.com/servo/servo/pull/37960#discussion_r2199790741 to be consistent with WebDriver get rect. It is ok if things don't fit in.

File: ports/servoshell/desktop/headless_window.rs [hunk 16]
```diff
@@ -68,7 +68,7 @@ impl WindowPortsMethods for Window {
         ScreenGeometry {
             size: self.screen_size,
             available_size: self.screen_size,
-            offset: Default::default(),
+            window_rect: Default::default(),
```
Comment (yezhizhen) [inline ports/servoshell/desktop/headless_window.rs]: The `window_size` here wasn't 0, but `self.inner_size.get()`.
The coordinates has always been 0 so it's ok.

**Review by yezhizhen — COMMENTED** [review]
Thanks! But please address the concern.

File: components/servo/lib.rs (hunk 15 above)
Comment (mrobinson) [reply components/servo/lib.rs]: I search the WebDriver spec for the text "as close as possible" and I only see that this should apply when trying to resize the window. I don't interpret this as referring to rounding floating point pixels though, but for when the operating system imposes other kinds of sizing constraints on the window. In any case, is this terminology used anywhere with regard to actually *getting* the window's size.

FWIW, I used `round_out` here as it seemed to make more sense that the rectangle contained the entire window versus just part of it.

Comment (yezhizhen) [reply components/servo/lib.rs]: But if using `round_out`, this will start to fail some WebDriver tests. Do you suggest that I change other `round` to `round_out` in previous merged PR?

File: ports/servoshell/desktop/headless_window.rs (hunk 16 above)
Comment (mrobinson) [reply ports/servoshell/desktop/headless_window.rs]: Good point. This should be fixed now.

File: components/servo/lib.rs (hunk 15 above)
Comment (yezhizhen) [reply components/servo/lib.rs]: > FWIW, I used round_out here as it seemed to make more sense that the rectangle contained the entire window versus just part of it.

But this can also introduce some danger. You may try to paint on larger than available window, leading to some obscured corner. `round_in` would make more sense to me..

EDIT: Maybe leave as another open question, and use `round()` for now?

Comment (mrobinson) [reply components/servo/lib.rs]: Are these tests using floating point window sizes?

Comment (yezhizhen) [reply components/servo/lib.rs]: I test on my own high DPR device with headed window. The assertion will be off by 1 with this.

For headless window, this should be fine as DPR is always 1.

https://github.com/servo/servo/blob/2366a8bf9e0aab6758bb6f199f1ee06e1e1490f8/tests/wpt/tests/webdriver/tests/classic/get_window_rect/get.py#L19

**Comment by yezhizhen** [comment]
Hi there seems to be 6 new failing cases. Let me fix this and push. @mrobinson

File: components/shared/embedder/lib.rs [hunk 17]
```diff
@@ -754,22 +757,25 @@ pub struct NotificationAction {
...
+    /// the `window.screen.availHeight` / `window.screen.availWidth`. This is the size
     /// available for web content on the screen, and should be `size` minus any system
     /// toolbars, docks, and interface elements. This will be converted to
     /// CSS pixels based on the pixel scaling of the `WebView`.
     pub available_size: DeviceIntSize,
-    /// The offset of the `WebView` in device pixels for the purposes of the `window.screenLeft`
-    /// and `window.screenTop` APIs. This will be converted to CSS pixels based on the pixel scaling
-    /// of the `WebView`.
-    pub offset: DeviceIntPoint,
+    /// The rectangle the `WebView`'s containing in device pixels for the purposes of the
```
Comment (mrobinson) [inline components/shared/embedder/lib.rs]: Oops. I missed a "window" here:

```suggestion
    /// The rectangle the `WebView`'s containing window in device pixels for the purposes of the
```

**Review by mrobinson — APPROVED** [review]

**Comment by mrobinson** [comment]
I am not sure about the rounding solution, as I think it might be covering up some other issue, but it's okay for now. Could it be that when we change the size of the window, we need to round up as well?

**Comment by yezhizhen** [comment]
> I am not sure about the rounding solution, as I think it might be covering up some other issue, but it's okay for now. Could it be that when we change the size of the window, we need to round up as well?

I took a closer look. 

1. I believe there is some spec issue. 
https://github.com/w3c/webdriver/pull/1909#issuecomment-3048195654

2. For example, the test requires response to be integer, which is not mentioned in spec. Nor is it sensible considering DPR.
https://github.com/servo/servo/blob/7eedeca715eadd4f7c617779b0487ddbdb588090/tests/wpt/tests/webdriver/tests/classic/set_window_rect/set.py#L41

3. The set parameter can be floats. But it is not mentioned why we expect rounding in following way.
https://github.com/servo/servo/blob/7eedeca715eadd4f7c617779b0487ddbdb588090/tests/wpt/tests/webdriver/tests/classic/set_window_rect/set.py#L160-L163

-----------
TL;DR: Will file some issues in [w3c/webdriver](https://github.com/w3c/webdriver/) and discuss before getting to this.

EDIT: Opened in https://github.com/w3c/webdriver/issues/1911

**Comment by mrobinson** [comment]
Great! Thank you for the investigation.
