### PR TITLE
script: Ensure that leaving the `WebView` sets the cursor back to the default cursor

### LINKED ISSUE #38710: Element hover state and cursor style no longer cleared correctly on cursor left
**Describe the bug:**
A clear and concise description of the bug.

Seems like a regression happened in the last week:

https://github.com/user-attachments/assets/7f5fc048-ae4e-483b-8fc0-6e123c4fa4bf

**To Reproduce:**
Steps to reproduce the behavior.

Go to https://servo.org and do what's shown in the video

**Platform:**
Specify OS, distribution, and hardware platform.

Windows 10

### PR DESCRIPTION
**Pull request by mrobinson**
This changes makes a variety of changes to ensure that the cursor is set
back to the default cursor when it leaves the `WebView`:

1. Display list updates can come after a mouse leaves the `WebView`, so
   when refreshing the cursor after the update, base the updated cursor
   on the last hovered location in the `DocumentEventHandler`, rather
   than the compositor. This allows us to catch when the last hovered
   position is `None` (ie the cursor has left the `WebView`).
2. When handling `MouseLeftViewport` events for the cursor leaving the
   entire WebView, properly set the
   MouseLeftViewport::focus_moving_to_another_iframe` on the input event
   passed to the script thread.
3. When moving out of the `WebView` entirely, explicitly ask the
   embedder to set the cursor back to the default.

Testing: This change adds a unit test verifying this behavior.
Fixes: #38710.

### CODE REVIEW

**Comment by mrobinson** [comment]
I have added a unit test verifying the behavior of this change.

File: components/servo/tests/webview.rs [hunk 1]
```diff
@@ -141,12 +145,58 @@ fn test_theme_change(servo_test: &ServoTest) -> Result<(), anyhow::Error> {
...
+}
+
 fn main() {
     run_api_tests!(
         test_create_webview,
+        test_cursor_change,
         test_evaluate_javascript_basic,
         test_evaluate_javascript_panic,
         test_theme_change,
+        test_theme_change,
```
Comment (jdm) [inline components/servo/tests/webview.rs]:
```suggestion
```

File: components/shared/constellation/lib.rs [hunk 2]
```diff
@@ -80,7 +78,7 @@ pub enum EmbedderToConstellationMessage {
     ForwardInputEvent(WebViewId, InputEvent, Option<CompositorHitTestResult>),
     /// Request that the given pipeline do a hit test at the location and reset the
     /// cursor accordingly. This happens after a display list update is rendered.
-    RefreshCursor(PipelineId, Point2D<f32, CSSPixel>),
+    RefreshCursor(PipelineId),
```
Comment (jdm) [inline components/shared/constellation/lib.rs:82]: Make sure the docs for this message are up to date?

File: components/shared/script/lib.rs [hunk 3]
```diff
@@ -149,7 +149,7 @@ pub enum ScriptThreadMessage {
     SendInputEvent(PipelineId, ConstellationInputEvent),
     /// Ask that the given pipeline refreshes the cursor (after a display list render) based
     /// on the hit test at the given point.
-    RefreshCursor(PipelineId, Point2D<f32, CSSPixel>),
+    RefreshCursor(PipelineId),
```
Comment (jdm) [inline components/shared/script/lib.rs:153]: Same for these docs.

**Review by jdm — APPROVED** [review]
Nice job on the unit test!
