### PR TITLE
Properly rethrow any exceptions from parsing JSON in Body mixin's `Json()`

### LINKED ISSUE #13464: Properly rethrow any exceptions from parsing JSON in Body mixin's `Json()`
The [Fetch spec](https://fetch.spec.whatwg.org/#body) requires the `Json()` method in Body mixin to rethrow any exceptions from parsing the JSON object. 

Currently, #13345 clears pending exception instead of rethrowing exception from `js::jsapi::JS_ParseJSON()`.

### PR DESCRIPTION
**Pull request by ysimonson**
This fixes #13464 by rethrowing exceptions from parsing JSON.

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #__ (github issue number if applicable).
- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20450)

### CODE REVIEW

File: components/script/body.rs [hunk 1]
```diff
@@ -133,9 +137,10 @@ fn run_json_data_algorithm(cx: *mut JSContext,
                          json_text.as_ptr(),
                          json_text.len() as u32,
                          rval.handle_mut()) {
+            rooted!(in(cx) let mut exception = UndefinedValue());
+            JS_GetPendingException(cx, exception.handle_mut());
```
Comment (jdm) [inline components/script/body.rs]: Let's assert that this return true.

**Review by jdm — CHANGES_REQUESTED** [review]

**Comment by jdm** [comment]
@bors-servo r+
Thanks for working on this!

**Comment by ysimonson** [comment]
Thanks again for all of the help @jdm!
