### PR TITLE
Fix panic in Webrender during shutdown

### LINKED ISSUE #32867: Intermittent panic in webrender during shutdown
```
▶ CRASH [expected FAIL] /html/canvas/element/manual/imagebitmap/imageBitmapRendering-transferFromImageBitmap-webgl.html
  │ 
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ called `Option::unwrap()` on a `None` value (thread WRSceneBuilder#0, at /home/runner/.cargo/git/checkouts/webrender-c3596abe1cf4f320/9d354ad/webrender/src/scene_builder_thread.rs:517)
  │    0: servoshell::backtrace::print
  │    1: servoshell::panic_hook::panic_hook
  │    2: std::panicking::rust_panic_with_hook
  │    3: std::panicking::begin_panic_handler::{{closure}}
  │    4: std::sys_common::backtrace::__rust_end_short_backtrace
  │    5: rust_begin_unwind
  │    6: core::panicking::panic_fmt
  │    7: core::panicking::panic
  │    8: core::option::unwrap_failed
  │    9: webrender::scene_builder_thread::SceneBuilderThread::process_transaction
  │   10: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  │   11: webrender::scene_builder_thread::SceneBuilderThread::run
  │   12: std::sys_common::backtrace::__rust_begin_short_backtrace
  │   13: core::ops::function::FnOnce::call_once{{vtable.shim}}
  │   14: std::sys::pal::unix::thread::Thread::new::thread_start
  │   15: <unknown>
  │   16: <unknown>
  │ mozilla::detail::MutexImpl::~MutexImpl: pthread_mutex_destroy failed: Device or resource busy
  │ Caught signal 11thread panicked while processing panic. aborting.
  │ Redirecting call to abort() to mozalloc_abort
```

This comes from https://github.com/servo/webrender/blob/9d354ad/webrender/src/scene_builder_thread.rs#L517, so it looks like there's some missing synchronization with webrender around documents when we're trying to shutdown?

### PR DESCRIPTION
**Pull request by Taym95**
Fix panic in Webrender during shutdown while exiting `webgl_threads `

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #32867

- [X] These changes do not require tests because don't change behavior.

### CODE REVIEW

File: components/constellation/constellation.rs [hunk 1]
```diff
@@ -2733,6 +2740,9 @@ where
         if let Err(e) = storage_ipc_receiver.recv() {
             warn!("Exit storage thread failed ({:?})", e);
         }
+        if let Err(e) = webgl_threads_receiver.recv() {
```
Comment (Taym95) [inline components/constellation/constellation.rs:2743]: @gterzian If I understand this correctly, this will be blocking until it receives a value from `webgl_threads_sender`, which happens after `webgl_threads.exit()` has succeeded, right?

File: components/constellation/constellation.rs [hunk 2]
```diff
@@ -2711,8 +2713,13 @@ where
 
         if let Some(webgl_threads) = self.webgl_threads.as_ref() {
             debug!("Exiting WebGL thread.");
-            if let Err(e) = webgl_threads.exit() {
-                warn!("Exit WebGL Thread failed ({})", e);
+            match webgl_threads.exit() {
```
Comment (gterzian) [inline components/constellation/constellation.rs:2716]: You need to pass the sender here, and then send the reply when the exit message is handled in the webgl thread. 

See for example https://github.com/servo/servo/pull/32897/files#diff-95aa2eb890fe794918afdadfb6a89e026ec80222ceb8e5a21768d528e9ce036cR2698

**Review by gterzian — CHANGES_REQUESTED** [review]
Thanks for taking this one on!

File: components/constellation/constellation.rs (hunk 1 above)
Comment (gterzian) [reply components/constellation/constellation.rs:2743]: Yes but see below.

File: components/constellation/constellation.rs [hunk 3]
```diff
@@ -2713,13 +2713,8 @@ where
...
             debug!("Exiting WebGL thread.");
-            match webgl_threads.exit() {
-                Ok(_) => {
-                    let _ = webgl_threads_sender.send(());
-                },
-                Err(e) => {
-                    warn!("Exit WebGL Thread failed ({})", e);
-                },
+            if let Err(e) = webgl_threads.exit(webgl_threads_sender) {
+                warn!("Exit WebGL Thread failed ({})", e);
```
Comment (mrobinson) [inline components/constellation/constellation.rs:2717]: Small cleanup suggestion:

```suggestion
                warn!("Exit WebGL Thread failed ({e})");
```

File: components/shared/canvas/webgl.rs [hunk 4]
```diff
@@ -73,9 +73,15 @@ impl WebGLThreads {
...
     /// Sends a exit message to close the WebGLThreads and release all WebGLContexts.
-    pub fn exit(&self) -> Result<(), &'static str> {
+    pub fn exit(
+        &self,
+        webgl_threads_sender: ipc_channel::ipc::IpcSender<()>,
+    ) -> Result<(), &'static str> {
         self.0
             .send(WebGLMsg::Exit)
+            .map_err(|_| "Failed to send Exit message")?;
+        webgl_threads_sender
```
Comment (gterzian) [inline components/shared/canvas/webgl.rs:83]: sorry I wasn't clear, this needs to go into the `Exit` message,

see for example https://github.com/servo/servo/blob/ca6169990ea8b429bbb8c11e4dcc9d8c6f59c7dd/components/net/resource_thread.rs#L375

Comment (gterzian) [reply components/shared/canvas/webgl.rs:83]: also we can follow the naming convention, so just `sender`.

**Review by gterzian — CHANGES_REQUESTED** [review]

File: components/shared/canvas/webgl.rs (hunk 4 above)
Comment (Taym95) [reply components/shared/canvas/webgl.rs]: Yes I pushed the wrong changes

File: components/shared/canvas/webgl.rs [hunk 5]
```diff
@@ -106,7 +106,7 @@ pub enum WebGLMsg {
     /// request is fulfilled
     SwapBuffers(Vec<WebGLContextId>, WebGLSender<u64>, u64),
     /// Frees all resources and closes the thread.
-    Exit,
+    Exit(ipc_channel::ipc::IpcSender<()>),
```
Comment (gterzian) [inline components/shared/canvas/webgl.rs:109]: please import it at the top.

File: components/constellation/constellation.rs [hunk 6]
```diff
@@ -2644,6 +2644,8 @@ where
             ipc::channel().expect("Failed to create IPC channel!");
         let (storage_ipc_sender, storage_ipc_receiver) =
             ipc::channel().expect("Failed to create IPC channel!");
+        let (webgl_threads_sender, webgl_threads_receiver) =
```
Comment (gterzian) [inline components/constellation/constellation.rs:2647]: If there is a clean way to only create those if `Some(webgl_threads)`, we should do this.

File: components/constellation/constellation.rs [hunk 7]
```diff
@@ -2733,6 +2735,9 @@ where
         if let Err(e) = storage_ipc_receiver.recv() {
             warn!("Exit storage thread failed ({:?})", e);
         }
+        if let Err(e) = webgl_threads_receiver.recv() {
```
Comment (gterzian) [inline components/constellation/constellation.rs:2738]: I think this will deadlock if `self.webgl_threads == None`, so we should make this conditional to it being `Some`.

**Review by gterzian — CHANGES_REQUESTED** [review]
One deadlock and some nits

File: components/constellation/constellation.rs (hunk 6 above)
Comment (Taym95) [reply components/constellation/constellation.rs:2647]: only way I see is to use `Option<IpcSender<()>>` and create channel when `Some(webgl_threads)`

Comment (gterzian) [reply components/constellation/constellation.rs:2647]: Yes that is a good idea.

File: components/constellation/constellation.rs (hunk 7 above)
Comment (Taym95) [reply components/constellation/constellation.rs:2738]: should be fixed now, ready for review again.

Comment (jdm) [reply components/constellation/constellation.rs:2738]: I don't think you pushed your changes.

Comment (Taym95) [reply components/constellation/constellation.rs]: sorry my bad, pushed now.

File: components/constellation/constellation.rs [hunk 8]
```diff
@@ -2733,6 +2740,13 @@ where
         if let Err(e) = storage_ipc_receiver.recv() {
             warn!("Exit storage thread failed ({:?})", e);
         }
+        if self.webgl_threads.is_some() {
+            if let Some(webgl_threads_receiver) = webgl_threads_receiver {
+                if let Err(e) = webgl_threads_receiver.recv() {
+                    warn!("Exit WebGL thread failed ({:?})", e);
+                }
+            }
+        }
```
Comment (mrobinson) [inline components/constellation/constellation.rs:2749]: Is it impossible `webgl_threads_receiver` to be `Some(...)` when `webgl_threads` is None? If so, this should probably be an assertion instead. If not, matching a tuple is might be bit cleaner here. Either way, the error can be inline in the format statement.

```suggestion
        if let Some(webgl_threads_receiver) = webgl_threads_receiver {
            assert!(self.webgl_threads.is_some());
            if let Err(e) = webgl_threads_receiver.recv() {
                warn!("Exit WebGL thread failed ({e:?})");
            }
        }
```

```suggestion
        match (self.webgl_threads, webgl_threads_receiver)  {
            (Some(_), Some(webgl_threads_receiver)) => if let Err(e) = webgl_threads_receiver.recv() {
                    warn!("Exit WebGL thread failed ({e:?})");
             },
            _ => {},
        }
```

File: components/canvas/webgl_thread.rs [hunk 9]
```diff
@@ -368,7 +368,10 @@ impl WebGLThread {
             WebGLMsg::SwapBuffers(swap_ids, sender, sent_time) => {
                 self.handle_swap_buffers(swap_ids, sender, sent_time);
             },
-            WebGLMsg::Exit => {
+            WebGLMsg::Exit(sender) => {
+                if let Err(e) = sender.send(()) {
+                    warn!("Failed to send response to WebGLMsg::Exit ({})", e)
```
Comment (mrobinson) [inline components/canvas/webgl_thread.rs:373]:
```suggestion
                    warn!("Failed to send response to WebGLMsg::Exit ({e})");
```

**Review by mrobinson — APPROVED** [review]
Looks good to me with a couple nits:

File: components/constellation/constellation.rs (hunk 8 above)
Comment (Taym95) [reply components/constellation/constellation.rs]: indeed tuple matching is better.

File: components/constellation/constellation.rs [hunk 10]
```diff
@@ -2710,9 +2711,15 @@ where
         }
 
         if let Some(webgl_threads) = self.webgl_threads.as_ref() {
+            let (sender, receiver) = ipc::channel().expect("Failed to create IPC channel!");
+            _webgl_threads_sender = Some(sender);
```
Comment (gterzian) [inline components/constellation/constellation.rs:2715]: Why the `_`?

File: components/constellation/constellation.rs [hunk 11]
```diff
@@ -2644,6 +2644,7 @@ where
             ipc::channel().expect("Failed to create IPC channel!");
         let (storage_ipc_sender, storage_ipc_receiver) =
             ipc::channel().expect("Failed to create IPC channel!");
+        let (mut _webgl_threads_sender, mut webgl_threads_receiver) = (None, None);
```
Comment (gterzian) [inline components/constellation/constellation.rs:2647]: You don't need the sender here, since it is only used inside the ` if let Some(webgl_threads)` block, so you can nest it to it, without wrapping it in an option.

File: components/constellation/constellation.rs [hunk 12]
```diff
@@ -2710,9 +2711,15 @@ where
...
 
         if let Some(webgl_threads) = self.webgl_threads.as_ref() {
+            let (sender, receiver) = ipc::channel().expect("Failed to create IPC channel!");
+            _webgl_threads_sender = Some(sender);
+            webgl_threads_receiver = Some(receiver);
             debug!("Exiting WebGL thread.");
-            if let Err(e) = webgl_threads.exit() {
-                warn!("Exit WebGL Thread failed ({})", e);
+
+            if let Some(sender) = _webgl_threads_sender {
```
Comment (gterzian) [inline components/constellation/constellation.rs:2719]: This conditional is not necessary if you follow my other comment.

File: components/constellation/constellation.rs [hunk 13]
```diff
@@ -2710,9 +2711,15 @@ where
         }
 
         if let Some(webgl_threads) = self.webgl_threads.as_ref() {
```
Comment (gterzian) [inline components/constellation/constellation.rs:2713]: I think you can assign an `Option<IPCReceiver>` here, with the `else` block returning `None`.

File: components/constellation/constellation.rs [hunk 14]
```diff
@@ -2733,6 +2740,14 @@ where
         if let Err(e) = storage_ipc_receiver.recv() {
             warn!("Exit storage thread failed ({:?})", e);
         }
+        match (self.webgl_threads.take(), webgl_threads_receiver) {
```
Comment (gterzian) [inline components/constellation/constellation.rs:2743]: I would do `if.webgl_threads.is_some()` and expect ` webgl_threads_receiver` to be some inside the block.

**Review by gterzian — APPROVED** [review]
Couple of small things to simplify the statements.

File: components/constellation/constellation.rs (hunk 11 above)
Comment (Taym95) [reply components/constellation/constellation.rs]: Indeed, I applied your suggestions

**Comment by gterzian** [comment]
@Taym95 thanks for the work, and @mrobinson thanks for the review.
