### PR TITLE
layout: Use an accurately-sized clipping rectangle for `box-shadow` display list item properties instead of `MaxRect`

### LINKED ISSUE #44431: Box-shadow only appear in Desktop but not Android/Ohos
**Describe the bug:**
This bug only happen on **Ohos/Android** but not Desktop, which is really interesting.

| Android | Desktop |
| -------- | -------- |
|  |  Image   |

**To Reproduce:**
```html
<button type="button"
    style="position:relative;width:44px;height:24px;border-radius:12px;border:none;padding:0;opacity:1;background:#AFECF5;flex-shrink:2;margin:15px"><span
        style="position:absolute;top:2px;left:2px;width:20px;height:20px;border-radius:50%;background:#AFECF5;box-shadow:0 1px 2px rgba(0,0,0,0.2);pointer-events:none"></span></button>
```

### PR DESCRIPTION
**Pull request by yezhizhen**
Mobile phone runs OpenGL Embedded System. The precision is limited comparing to Desktop which runs full OpenGL. This caused a bug where box-shadow is not displayed on Android/OHOS. Instead of using an infinite clip rect, we compute a bounded one. This should save some GPU work as well.

Reference: [How to gracefully handle highp/mediump switch for mobile Android browsers?](https://discourse.threejs.org/t/how-to-gracefully-handle-highp-mediump-switch-for-mobile-android-browsers/77335)

Testing: Desktop WPT [unchanged](https://github.com/servo/servo/actions/runs/24825758325). Manually tested on Android/Ohos. Now look same as Firefox/Chrome.

| Before | After |
| -------- | -------- |
|  |  |

Fixes: #44431
Closes: https://github.com/servo/webrender/pull/4879

### CODE REVIEW

File: components/layout/display_list/mod.rs [hunk 1]
```diff
@@ -1889,8 +1888,30 @@ impl<'a> BuilderForBoxFragment<'a> {
...
+            let shifted = rect.translate(offset);
+            let spread_rect = shifted.inflate(spread, spread);
+            let shadow_rect = spread_rect.inflate(blur, blur);
+            clip_rect = clip_rect.union(&rect).union(&shadow_rect);
+        }
+        if clip_rect.is_empty() {
+            clip_rect = self.border_rect;
+        }
+        let common = builder.common_properties(clip_rect, &style);
+        // Note: According to CSS-BACKGROUNDS, box shadows render in *reverse* order (front to back).
```
Comment (yezhizhen) [inline components/layout/display_list/mod.rs]: I don't know what "NB:" is, so replaced with "Note:".

Comment (sagudev) [reply components/layout/display_list/mod.rs]: https://en.wikipedia.org/wiki/Nota_bene is often used in mathematics.

File: components/layout/display_list/mod.rs [hunk 2]
```diff
@@ -1889,8 +1888,30 @@ impl<'a> BuilderForBoxFragment<'a> {
             return;
         }
 
-        // NB: According to CSS-BACKGROUNDS, box shadows render in *reverse* order (front to back).
-        let common = builder.common_properties(MaxRect::max_rect(), &style);
```
Comment (mrobinson) [inline components/layout/display_list/mod.rs:1893]: Instead of using the same `common` for all shadows, do you mind integrating the rectangle calcuation into the loop and calling `builder.common_properties(shadow_bounds, &style);` for each shadow. I think that will generate tighter boundaries for each shadow.

**Review by mrobinson — CHANGES_REQUESTED** [review]

File: components/layout/display_list/mod.rs (hunk 1 above)
Comment (yezhizhen) [reply components/layout/display_list/mod.rs]: I received my math education in English but never saw this word before🤣

**Comment by yezhizhen** [comment]
Try run [here](https://github.com/servo/servo/actions/runs/24838036879)

**Review by mrobinson — APPROVED** [review]

**Comment by yezhizhen** [comment]
This also seems to fix a bug on Desktop: After you zoom in 4 times, the box-shadow would completely disappear.
