### PR TITLE
Access browsing context safely

### LINKED ISSUE #15877: Servo panics with session-history.max-length=1
Running:
```
./target/debug/servo --pref session-history.max-length=1
```
Then clicking on the `Rust` link, following the redirect, then going back produces panic:
```
   0:     0x562222fe4561 - backtrace::backtrace::libunwind::trace
                        at /home/ajeffrey/github/asajeffrey/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.0/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace<closure>
                        at /home/ajeffrey/github/asajeffrey/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.0/src/backtrace/mod.rs:42
   1:     0x562222fdf804 - backtrace::capture::{{impl}}::new
                        at /home/ajeffrey/github/asajeffrey/servo/target/debug/build/backtrace-17fa5380aeaf9437/out/capture.rs:79
   2:     0x562222575268 - constellation::constellation::log_entry
                        at /home/ajeffrey/github/asajeffrey/servo/components/constellation/constellation.rs:457
   3:     0x562222574a0f - constellation::constellation::{{impl}}::log
                        at /home/ajeffrey/github/asajeffrey/servo/components/constellation/constellation.rs:438
   4:     0x56221e93d800 - servo::{{impl}}::log<env_logger::Logger,constellation::constellation::FromCompositorLogger>
                        at /home/ajeffrey/github/asajeffrey/servo/components/servo/lib.rs:347
   5:     0x562224000312 - log::__log
                        at /home/ajeffrey/github/asajeffrey/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.3.6/src/lib.rs:876
   6:     0x56221e943ea2 - servo::main::{{closure}}
                        at /home/ajeffrey/github/asajeffrey/servo/ports/servo/main.rs:126
   7:     0x56222406d82d - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:546
   8:     0x56222406d674 - std::panicking::begin_panic<collections::string::String>
                        at /checkout/src/libstd/panicking.rs:507
   9:     0x56222406d5e9 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:491
  10:     0x56222406d577 - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:467
  11:     0x56222409a24d - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:69
  12:     0x56222409a184 - core::panicking::panic
                        at /checkout/src/libcore/panicking.rs:49
  13:     0x5622204d5ab5 - core::option::{{impl}}::unwrap<script::dom::bindings::js::Root<script::dom::browsingcontext::BrowsingContext>>
                        at /checkout/src/libcore/macros.rs:21
  14:     0x562220a6c6b1 - script::dom::window::{{impl}}::browsing_context
                        at /home/ajeffrey/github/asajeffrey/servo/components/script/dom/window.rs:323
  15:     0x56221fa7709d - script::dom::document::{{impl}}::browsing_context
                        at /home/ajeffrey/github/asajeffrey/servo/components/script/dom/document.rs:393
  16:     0x56221fa7d2c3 - script::dom::event::{{impl}}::dispatch
                        at /home/ajeffrey/github/asajeffrey/servo/components/script/dom/event.rs:145
  17:     0x56221fa811c8 - script::dom::eventtarget::{{impl}}::dispatch_event
                        at /home/ajeffrey/github/asajeffrey/servo/components/script/dom/eventtarget.rs:306
  18:     0x56221fa7db8a - script::dom::event::{{impl}}::fire
                        at /home/ajeffrey/github/asajeffrey/servo/components/script/dom/event.rs:220
  19:     0x56221ff7186b - script::dom::document::{{impl}}::fire_mouse_event
                        at /home/ajeffrey/github/asajeffrey/servo/components/script/dom/document.rs:1067
  20:     0x56221ff722b5 - script::dom::document::{{impl}}::handle_mouse_move_event
                        at /home/ajeffrey/github/asajeffrey/servo/components/script/dom/document.rs:1137
  21:     0x562220aa175d - script::script_thread::{{impl}}::handle_event
                        at /home/ajeffrey/github/asajeffrey/servo/components/script/script_thread.rs:1866
  22:     0x562220a8feaa - script::script_thread::{{impl}}::handle_msg_from_constellation
                        at /home/ajeffrey/github/asajeffrey/servo/components/script/script_thread.rs:1003
  23:     0x562220a8e3ec - script::script_thread::{{impl}}::handle_msgs::{{closure}}
                        at /home/ajeffrey/github/asajeffrey/servo/components/script/script_thread.rs:885
  24:     0x562220a8ead1 - script::script_thread::{{impl}}::profile_event<closure,core::option::Option<bool>>
                        at /home/ajeffrey/github/asajeffrey/servo/components/script/script_thread.rs:994
  25:     0x562220a8cad3 - script::script_thread::{{impl}}::handle_msgs
                        at /home/ajeffrey/github/asajeffrey/servo/components/script/script_thread.rs:879
  26:     0x562220a8b305 - script::script_thread::{{impl}}::start
                        at /home/ajeffrey/github/asajeffrey/servo/components/script/script_thread.rs:734
  27:     0x56221fb035b4 - script::script_thread::{{impl}}::create::{{closure}}::{{closure}}
                        at /home/ajeffrey/github/asajeffrey/servo/components/script/script_thread.rs:561
  28:     0x56221f58c746 - profile_traits::mem::{{impl}}::run_with_memory_reporting<closure,fn(profile_traits::mem::ReportsChan) -> script::script_runtime::CommonScriptMsg,script::script_runtime::CommonScriptMsg,std::sync::mpsc::Sender<script::script_thread::MainThreadScriptMsg>>
                        at /home/ajeffrey/github/asajeffrey/servo/components/profile_traits/mem.rs:63
  29:     0x562221041879 - script::script_thread::{{impl}}::create::{{closure}}
                        at /home/ajeffrey/github/asajeffrey/servo/components/script/script_thread.rs:560
  30:     0x562220fd6e5a - std::panic::{{impl}}::call_once<(),closure>
                        at /checkout/src/libstd/panic.rs:296
  31:     0x562220f1cbe2 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panicking.rs:450
  32:     0x5622240747fa - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
  33:     0x562220c88c13 - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:429
  34:     0x562220c1d084 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panic.rs:361
  35:     0x562220526c70 - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:357
  36:     0x5622207be402 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /checkout/src/liballoc/boxed.rs:638
  37:     0x56222406c474 - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:648
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84
  38:     0x7fcbc5f246b9 - start_thread
  39:     0x7fcbc5a4482c - clone
  40:                0x0 - <unknown>
```
Somehow we're firing a mouse event on a document which has no browsing context.

cc @cbrewster

### PR DESCRIPTION
**Pull request by mchv**
Current browsing context accessor in `Document` unwraps the browsing context `Option` which prevents document to handle correctly the case when there is no browsing context.

This is the reason servo panics with `session-history.max-length=1` (https://github.com/servo/servo/issues/15877).

As it is my first contribution, I added a `safe` method to retrieve the browsing context rather than change the existing method, but I am happy to change if you think this is the right approach. I did not as well replace all existing method call to the `safe` method, to focus on fixing the issue.

If someone can give me a bit of guidance for the test, I will try to contribute one.

---

- [X] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [X] These changes fix #15877.
- [ ] There are tests for these changes 

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15906)

### CODE REVIEW

File: components/script/dom/window.rs [hunk 1]
```diff
@@ -607,8 +612,9 @@ impl WindowMethods for Window {
 
     // https://html.spec.whatwg.org/multipage/#dom-parent
     fn GetParent(&self) -> Option<Root<BrowsingContext>> {
+        
         // Steps 1. and 2.
-        if self.browsing_context().is_discarded() {
+        if self.safe_browsing_context().map(|c| c.is_discarded()).unwrap_or(true) {
```
Comment (emilio) [inline components/script/dom/window.rs]: nit: you can use `map_or(true, |c| c.is_discarded())`

Comment (mchv) [inline components/script/dom/window.rs]: @emilio thanks updated the code

**Comment by asajeffrey** [comment]
My take on how we got here...

The only place we're creating a `Window` is in https://github.com/servo/servo/blob/master/components/script/script_thread.rs#L1674, and we immediately call `init_browsing_context` at https://github.com/servo/servo/blob/master/components/script/script_thread.rs#L1703 or https://github.com/servo/servo/blob/master/components/script/script_thread.rs#L1708.

The only thing I can think of is that we're accessing the `Window` after it's been discarded https://github.com/servo/servo/blob/master/components/script/dom/window.rs#L272, which is certainly possible if the `Document` calls methods on the `Window` after the browsing context has been discarded.

Since it is possible for (e.g.) a `Document` to be accessed after its browsing context has been discarded, it looks like the thing to do is to make sure that `Window` methods are safe to call even if there is no browsing context.

This PR will certainly help for that! We could be more drastic, and just make `wiindow.browsing_context()` return an `Option<BrowsingContext>`, but that's not a must-do.

@mchv: thanks for looking into this!

File: components/script/dom/window.rs [hunk 2]
```diff
@@ -319,10 +319,15 @@ impl Window {
         &self.image_cache_thread
     }
 
+    /// Retrieve unsafely the browsing context
```
Comment (asajeffrey) [inline components/script/dom/window.rs]: Add a comment, something like "This can panic if it is called after the browsing context has been discarded".

File: components/script/dom/window.rs [hunk 3]
```diff
@@ -608,7 +613,7 @@ impl WindowMethods for Window {
     // https://html.spec.whatwg.org/multipage/#dom-parent
     fn GetParent(&self) -> Option<Root<BrowsingContext>> {
         // Steps 1. and 2.
-        if self.browsing_context().is_discarded() {
+        if self.safe_browsing_context().map_or(true, |c| c.is_discarded()) {
```
Comment (asajeffrey) [inline components/script/dom/window.rs]: Can this be `map_or(true, BrowsingContext::is_discarded)`?

File: components/script/dom/window.rs [hunk 4]
```diff
@@ -622,7 +627,7 @@ impl WindowMethods for Window {
     // https://html.spec.whatwg.org/multipage/#dom-top
     fn GetTop(&self) -> Option<Root<BrowsingContext>> {
         // Steps 1. and 2.
-        if self.browsing_context().is_discarded() {
+        if self.safe_browsing_context().map_or(true, |c| c.is_discarded()) {
```
Comment (asajeffrey) [inline components/script/dom/window.rs]: Ditto?

**Review by asajeffrey — COMMENTED** [review]
Looks good! Just some minor nits.

File: components/script/dom/window.rs [hunk 5]
```diff
@@ -319,10 +319,15 @@ impl Window {
         &self.image_cache_thread
     }
 
+    /// Retrieve unsafely the browsing context
     pub fn browsing_context(&self) -> Root<BrowsingContext> {
         self.browsing_context.get().unwrap()
     }
 
+    pub fn safe_browsing_context(&self) -> Option<Root<BrowsingContext>> {
```
Comment (nox) [inline components/script/dom/window.rs]: The only place this method is used outside of `dom::window` is in `Document::browsing_context`, which checks whether `self.has_browsing_context` is true.

Why is `self.has_browsing_context` ever true without a corresponding browsing context in the document's window?

File: components/script/dom/window.rs (hunk 3 above)
Comment (nox) [inline components/script/dom/window.rs]: No it can't, because `BrowsingContext::is_discarded` takes a `&BrowsingContext` and the contents of the option is a `Root<BrowsingContext>`.

File: components/script/dom/window.rs (hunk 2 above)
Comment (nox) [inline components/script/dom/window.rs]: Don't use the word "unsafely", which has a precise meaning in Rust.

File: components/script/dom/window.rs (hunk 5 above)
Comment (nox) [inline components/script/dom/window.rs]: Please rename method to something like `maybe_browsing_context` or something like that. Safety is a different concept.

**Review by nox — CHANGES_REQUESTED** [review]
Some questions.

File: components/script/dom/window.rs (hunk 2 above)
Comment (mchv) [inline components/script/dom/window.rs]: @nox sure I will update

File: components/script/dom/window.rs (hunk 5 above)
Comment (mchv) [inline components/script/dom/window.rs]: @nox make sense I will do the update

File: components/script/dom/window.rs (hunk 3 above)
Comment (asajeffrey) [inline components/script/dom/window.rs]: Oh that's annoying, oh well.

File: components/script/dom/window.rs (hunk 5 above)
Comment (asajeffrey) [inline components/script/dom/window.rs]: The problem is that `document.has_browsing_context` is immutable, so if a document originally had a browsing context, but then that browsing context was discarded, we don't update the document. We could make `document.has_browsing_context` mutable, or we could just remove it and replace it by a method which checks to see if the window exists and has a browsing context.

Comment (nox) [inline components/script/dom/window.rs]: Given a document can now lose its browsing context, `has_browsing_context` should probably not be immutable.

Comment (asajeffrey) [inline components/script/dom/window.rs]: The problem is we're being a bit vague about the distinction between not having a browsing context, and having one that's been discarded. Sigh.

**Comment by mchv** [comment]
@nox @asajeffrey I have updated the code based on your comments. Let me know if you think we need other changes or add tests before being ready to merge.

**Comment by asajeffrey** [comment]
LGTM. @bors-servo r+

**Comment by asajeffrey** [comment]
Yay!
