### PR TITLE
layout_2020: Do linebreak for atomic inline-level elements

### LINKED ISSUE #29591: No line breaking opportunity between atomic inlines
https://bucket.daz.cat/work/igalia/servo/1.html

```html
<!doctype html><meta charset="utf-8"
><span>.</span><span>.</span><br
><div></div><div></div><br
><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
><style>
    body { width: 1em; }
    span, div { background: black; }
    div, img { width: 1em; height: 1em; }
    div { display: inline-block; }
</style>
```

| layout 2020 | layout 2013 |
| --- | --- |
| image | image |

The reftest reference [/css/CSS2/positioning/absolute-non-replaced-height-003-ref.xht](https://wpt.live/css/CSS2/positioning/absolute-non-replaced-height-003-ref.xht) is broken due to this bug.

### PR DESCRIPTION
**Pull request by stshine**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #29591 (GitHub issue number if applicable)

- [x] There are tests for these changes OR

### CODE REVIEW

**Comment by mrobinson** [comment]
Any update on this change? It's still marked as a draft and it needs test updates, but it seems to fix a lot of tests.

**Comment by stshine** [comment]
I just got some free time and started to work on this.

**Comment by stshine** [comment]
This pull request is ready for review.

File: components/layout_2020/flow/inline.rs [hunk 1]
```diff
@@ -125,6 +127,34 @@ impl<'box_tree, 'a, 'b> InlineFormattingContextState<'box_tree, 'a, 'b> {
 
         self.positioning_context.push(hoisted_box);
     }
+
+    /// Finish layout of all the partial inline boxes in the current line,
+    /// finish current line and start a new one.
+    fn refresh_newline(&mut self, layout_context: &LayoutContext) {
```
Comment (mrobinson) [inline components/layout_2020/flow/inline.rs:133]: This could probably be called `finish_line_and_reset_inline_positions` just to be a bit more obvious what it does and to make it match the naming of `finish_line()`.

File: components/layout_2020/flow/inline.rs [hunk 2]
```diff
@@ -586,20 +619,19 @@ fn layout_atomic(
...
-    };
-    if style.clone_position().is_relative() {
-        start_corner += &relative_adjustement(&style, ifc.containing_block)
-    }
 
-    let fragment = match atomic {
+    let collects_for_nearest_positioned_ancestor = ifc
+        .positioning_context
+        .collects_for_nearest_positioned_ancestor();
+    let mut child_positioning_context =
```
Comment (mrobinson) [inline components/layout_2020/flow/inline.rs:630]: Let's make this an `Option<PositioningContext>` that is only set for non-replaced elements. That will avoid the allocation of 2 vectors for all replaced elements.

File: components/layout_2020/flow/inline.rs [hunk 3]
```diff
@@ -707,6 +734,27 @@ fn layout_atomic(
...
+    let mut start_corner = Vec2 {
+        block: pbm_sums.block_start,
+        inline: ifc.inline_position - ifc.current_nesting_level.inline_start,
+    };
+    if style.clone_position().is_relative() {
+        start_corner += &relative_adjustement(&style, ifc.containing_block)
+    }
+    child_positioning_context
+        .adjust_static_position_of_hoisted_fragments_with_offset(&start_corner);
+    ifc.positioning_context.append(child_positioning_context);
```
Comment (mrobinson) [inline components/layout_2020/flow/inline.rs:755]: This would need to become something like:
```suggestion
    if let Some(child_positioning_context) = child_positioning.take() {
        child_positioning_context
            .adjust_static_position_of_hoisted_fragments_with_offset(&start_corner);
        ifc.positioning_context.append(child_positioning_context);
    }
```

File: components/layout_2020/flow/inline.rs [hunk 4]
```diff
@@ -586,20 +619,19 @@ fn layout_atomic(
     ifc: &mut InlineFormattingContextState,
     atomic: &mut IndependentFormattingContext,
 ) {
-    let style = atomic.style();
+    let style = &atomic.style().clone();
```
Comment (mrobinson) [inline components/layout_2020/flow/inline.rs:622]: Could you get away with not cloning the style here? It seems a little expensive.

**Review by mrobinson — CHANGES_REQUESTED** [review]
This seems pretty reasonable to me! Maybe @Loirooriol would like to take a look as well. I have few minor comments below:

File: components/layout_2020/flow/inline.rs (hunk 1 above)
Comment (stshine) [reply components/layout_2020/flow/inline.rs:133]: How about `finish_line_reset` ?

File: components/layout_2020/flow/inline.rs (hunk 2 above)
Comment (stshine) [reply components/layout_2020/flow/inline.rs:630]: Will do.

File: components/layout_2020/flow/inline.rs (hunk 3 above)
Comment (stshine) [reply components/layout_2020/flow/inline.rs:755]: Will do.

File: components/layout_2020/flow/inline.rs (hunk 4 above)
Comment (stshine) [reply components/layout_2020/flow/inline.rs:622]: I tried but the borrow checker didn't show mercy :( Will try again.

**Comment by stshine** [comment]
Updated according to comments.

File: components/layout_2020/flow/inline.rs (hunk 4 above)
Comment (mrobinson) [reply components/layout_2020/flow/inline.rs:622]: You can avoid the double-borrow here by cloning the position:

```diff
diff --git a/components/layout_2020/flow/inline.rs b/components/layout_2020/flow/inline.rs
index ad1a4f0880..40e562902d 100644
--- a/components/layout_2020/flow/inline.rs
+++ b/components/layout_2020/flow/inline.rs
@@ -619,8 +619,7 @@ fn layout_atomic(
     ifc: &mut InlineFormattingContextState,
     atomic: &mut IndependentFormattingContext,
 ) {
-    let style = &atomic.style().clone();
-    let pbm = style.padding_border_margin(&ifc.containing_block);
+    let pbm = atomic.style().padding_border_margin(&ifc.containing_block);
     let margin = pbm.margin.auto_is(Length::zero);
     let pbm_sums = &(&pbm.padding + &pbm.border) + &margin;
 
@@ -749,8 +748,10 @@ fn layout_atomic(
         block: pbm_sums.block_start,
         inline: ifc.inline_position - ifc.current_nesting_level.inline_start,
     };
-    if style.clone_position().is_relative() {
-        start_corner += &relative_adjustement(&style, ifc.containing_block)
+
+    let position = atomic.style().clone_position();
+    if position.is_relative() {
+        start_corner += &relative_adjustement(atomic.style(), ifc.containing_block)
     }
 
     if let Some(mut child_positioning_context) = child_positioning_context.take() {
```

**Review by mrobinson — APPROVED** [review]
Looks good to me with the change suggested above. Thanks!

**Review by Loirooriol — APPROVED** [review]
Thanks, seems reasonable (with Martin's suggestion)

**Comment by stshine** [comment]
Updated. Thanks!

**Comment by stshine** [comment]
What?
@bors-servo retry
