### PR TITLE
layout: Improve fixed table layout

### LINKED ISSUE #35099: Bug in column distribution of table in fixed mode
```html
<!DOCTYPE html>
<table style="table-layout: fixed; width: 200px">
  <td style="height: 50px; background: cyan; padding-left: 10px"></td>
  <td style="height: 50px; background: magenta"></td>
</table>
```

| Servo | Expected |
| - | - |
|  |  |

### PR DESCRIPTION
**Pull request by Loirooriol**
If `width` is indefinite, treat the outer size as zero, instead of treating the content size as zero and then adding padding and borders.

Also, we don't want a default minimum of zero to get added padding and borders, and then defeat the point above. So just ignore minimums and maximums.

That seems to roughly match what other browsers do, but as usual, the details are not interoperable, e.g. some browsers may obey min or max sizing properties in some cases.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #35099
- [X] There are tests for these changes

### CODE REVIEW

File: components/layout_2020/table/layout.rs [hunk 1]
```diff
@@ -639,6 +627,18 @@ impl<'a> TableLayout<'a> {
...
+        // <https://github.com/w3c/csswg-drafts/issues/10937>.
+        self.is_in_fixed_mode = self.table.style.get_table().clone_table_layout() ==
+            TableLayoutMode::Fixed &&
+            !matches!(
+                self.table
+                    .style
+                    .box_size(self.table.style.writing_mode)
+                    .inline,
+                Size::Initial | Size::MaxContent
+            );
```
Comment (mrobinson) [inline components/layout_2020/table/layout.rs:641]: Could this move to the constructor for `TableLayout` as it only seems to rely on `self.table.style`?

**Review by mrobinson — APPROVED** [review]

**Review by mrobinson — APPROVED** [review]
