### PR TITLE
Fix handling of borders and padding for empty/stripped inline flows

### LINKED ISSUE #10533: Empty span does not show border
Test case:
```html
<span>foo</span><br>
<span></span><br>
<span>bar</span>

<style>
span {
    border-left: 5px solid;
}
</style>
```

Firefox:
firefox

Servo:
servo

### PR DESCRIPTION
**Pull request by mbrubeck**
This forces fragment generation for empty inline flows, if they have borders or padding.  Fixes #10533 and #2001.  Also includes fixes for other bugs that were uncovered by this change; see the individual commit messages for detailed explanations.  r? @pcwalton

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10643)

### CODE REVIEW

File: components/layout/fragment.rs [hunk 1]
```diff
@@ -2482,26 +2482,49 @@ impl Fragment {
...
-                        LAST_FRAGMENT_OF_ELEMENT);
+                    inline_context_node_from_this_fragment.flags.insert(LAST_FRAGMENT_OF_ELEMENT);
                 }
             }
         }
     }
 
+    pub fn meld_with_prev_inline_fragment(&mut self, prev_fragment: &Fragment) {
+        if let Some(ref mut inline_context_of_this_fragment) = self.inline_context {
+            if let Some(ref inline_context_of_prev_fragment) = prev_fragment.inline_context {
```
Comment (pcwalton) [inline components/layout/fragment.rs]: nit: You could remove a level of indentation here by matching on a tuple, if you like. Up to you.

File: components/layout/construct.rs [hunk 2]
```diff
@@ -1851,3 +1869,25 @@ fn control_chars_to_fragment(node: &InlineFragmentNodeInfo,
...
+
+impl ComputedValueUtils for ServoComputedValues {
+    fn has_padding_or_border(&self) -> bool {
+        let padding = self.get_padding();
+        let border = self.get_border();
+
+        padding.padding_top != LengthOrPercentage::Length(Au(0)) ||
+           padding.padding_right != LengthOrPercentage::Length(Au(0)) ||
+           padding.padding_bottom != LengthOrPercentage::Length(Au(0)) ||
+           padding.padding_left != LengthOrPercentage::Length(Au(0)) ||
```
Comment (pcwalton) [inline components/layout/construct.rs]: Handle 0% maybe too?

Comment (notriddle) [inline components/layout/construct.rs]: If that's going to be a thing we do, we should probably add an `is_zero()` method to `LengthOrPercentage` or something.

File: components/layout/fragment.rs (hunk 1 above)
Comment (mbrubeck) [inline components/layout/fragment.rs]: Tried out this suggestion, but ended up making the code less readable because of explicit reborrows needed to avoid moving from borrowed content into the tuple.

File: components/layout/construct.rs (hunk 2 above)
Comment (mbrubeck) [inline components/layout/construct.rs]: Done

**Comment by mbrubeck** [comment]
Addressed review comments.

**Comment by jdm** [comment]
```
  ▶ FAIL [expected PASS] /css21_dev/html4/run-in-listitem-between-002.htm
  └   → /css21_dev/html4/run-in-listitem-between-002.htm ef608dda75ea29fbec3a0a32f64cc80292e62d82
/css21_dev/html4/reference/run-in-text-ref.htm d068883ccfce1b3fdf24f9ea6b401c9a047b593c
Testing ef608dda75ea29fbec3a0a32f64cc80292e62d82 == d068883ccfce1b3fdf24f9ea6b401c9a047b593c

  ▶ FAIL [expected PASS] /css21_dev/html4/run-in-listitem-between-001.htm
  └   → /css21_dev/html4/run-in-listitem-between-001.htm ef608dda75ea29fbec3a0a32f64cc80292e62d82
/css21_dev/html4/reference/run-in-text-ref.htm d068883ccfce1b3fdf24f9ea6b401c9a047b593c
Testing ef608dda75ea29fbec3a0a32f64cc80292e62d82 == d068883ccfce1b3fdf24f9ea6b401c9a047b593c
```

**Comment by mbrubeck** [comment]
@bors-servo r=pcwalton

* Reverted some of the metadata changes.

**Comment by mbrubeck** [comment]
I don't think this is related to my changes:

```
Tests with unexpected results:
  ▶ CRASH [expected OK] /webgl/conformance-1.0.3/conformance/limits/gl-min-attribs.html

  ▶ OK [expected CRASH] /webgl/conformance-1.0.3/conformance/more/conformance/quickCheckAPI-G_I.html

  ▶ Unexpected subtest result in /webgl/conformance-1.0.3/conformance/more/conformance/quickCheckAPI-G_I.html:
  │ FAIL [expected PASS] WebGL test #0: testValidArgs

  ▶ CRASH [expected OK] /webgl/conformance-1.0.3/conformance/textures/texture-draw-with-2d-and-cube.html
```

**Comment by mbrubeck** [comment]
@bors-servo retry

* will file new issue if this turns out to be intermittent

**Comment by jdm** [comment]
Yeah, those are the temperamental new WebGL tests that were just enabled after a long fight in #10373.
