### PR TITLE
Remove unnecessary 'unwrap' calls from ImageCacheThread

### LINKED ISSUE #12390: Remove unnecessary `unwrap` calls from ImageCacheThread
called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Custom(Custom { kind: Other, error: StringError("Unknown Mach error: 46") }) })
### URL:
https://duckduckgo.com/html/
### Backtrace:
```
frame #0  - 0x000000010b6c8dfe - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x000000010b6c8d81 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x0000000109bc6754 - _<F as alloc..boxed..FnBox<A>>::call_box::haeff945be1a63d60
frame #3  - 0x000000010b6a7677 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2c0e77c593c00c08
frame #4  - 0x000000010b71e034 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x000000010b7366a6 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x000000010b71f678 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x000000010b7362ff - rust_begin_unwind
frame #8  - 0x000000010b75d1a0 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x000000010b20e2a7 - core::result::unwrap_failed::h7b817f343b3e9749
frame #10 - 0x000000010b223244 - net_traits::image_cache_thread::ImageCacheThread::find_image_or_metadata::h97b2767e8e9354e8
frame #11 - 0x000000010a5ff4ae - layout::context::LayoutContext::get_or_request_image_or_meta::h29c829e46e602cde
frame #12 - 0x000000010a6008c7 - layout::context::LayoutContext::get_webrender_image_for_url::h997e13bf17e0187d
frame #13 - 0x000000010a604540 - _<layout..fragment..Fragment as layout..display_list_builder..FragmentDisplayListBuilding>::build_display_list_for_background_image::h27dcb835f84a87bf
frame #14 - 0x000000010a603854 - _<layout..fragment..Fragment as layout..display_list_builder..FragmentDisplayListBuilding>::build_display_list_for_background_if_applicable::h08a031a7f7801d98
frame #15 - 0x000000010a607188 - _<layout..fragment..Fragment as layout..display_list_builder..FragmentDisplayListBuilding>::build_display_list::he8df445b3ccfe06c
frame #16 - 0x000000010a5ec73d - _<layout..block..BlockFlow as layout..display_list_builder..BlockFlowDisplayListBuilding>::build_display_list_for_block::hc66b740ca955ac08
frame #17 - 0x000000010a5e7806 - _<layout..block..BlockFlow as layout..flow..Flow>::build_display_list::h209ffd6be3fe9d43
frame #18 - 0x000000010a64d151 - layout::traversal::BuildDisplayList::traverse::h6c3b0020735c3533
frame #19 - 0x000000010a64d1a7 - layout::traversal::BuildDisplayList::traverse::h6c3b0020735c3533
frame #20 - 0x000000010a64d1a7 - layout::traversal::BuildDisplayList::traverse::h6c3b0020735c3533
frame #21 - 0x000000010a64d1a7 - layout::traversal::BuildDisplayList::traverse::h6c3b0020735c3533
frame #22 - 0x000000010a64d1a7 - layout::traversal::BuildDisplayList::traverse::h6c3b0020735c3533
frame #23 - 0x000000010a64d1a7 - layout::traversal::BuildDisplayList::traverse::h6c3b0020735c3533
frame #24 - 0x000000010a64d1a7 - layout::traversal::BuildDisplayList::traverse::h6c3b0020735c3533
frame #25 - 0x000000010a64cea3 - layout::sequential::build_display_list_for_subtree::hd603793842d8bee6
frame #26 - 0x0000000109ce339a - layout_thread::LayoutThread::perform_post_main_layout_passes::h7b5f2ff1da7c5883
frame #27 - 0x0000000109c2f552 - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::ha65b8390660d0026
frame #28 - 0x0000000109c33a4b - layout_thread::LayoutThread::handle_reflow::h6771f195a62bbc92
frame #29 - 0x0000000109c1f5bd - layout_thread::LayoutThread::handle_request_helper::h1029bbb7e9e50e59
frame #30 - 0x0000000109c0494f - layout_thread::LayoutThread::handle_request::ha13841b9d3ecdc81
frame #31 - 0x0000000109bc45ca - std::panicking::try::call::h401e4a3a7768c3f1
frame #32 - 0x000000010b73938b - __rust_try
frame #33 - 0x000000010b739325 - __rust_maybe_catch_panic
frame #34 - 0x0000000109bc5934 - _<F as alloc..boxed..FnBox<A>>::call_box::h8169792cb3dac906
frame #35 - 0x000000010b734e08 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #36 - 0x00007fff99a2e99c - _pthread_body
frame #37 - 0x00007fff99a2e919 - _pthread_start

```
This report was generated by the browser.html issue reporter.

### PR DESCRIPTION
**Pull request by ice9js**
Fixes #12390.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #12390 (github issue number if applicable).

- [X] These changes do not require tests because the build provides enough verification for the changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12431)

### CODE REVIEW

File: components/net_traits/image_cache_thread.rs [hunk 1]
```diff
@@ -37,6 +39,12 @@ pub enum ImageState {
     NotRequested,
 }
 
+impl From<bincode::serde::DeserializeError> for ImageState {
+    fn from(_: bincode::serde::DeserializeError) -> ImageState {
+        ImageState::LoadError
+    }
+}
+
```
Comment (Wafflespeanut) [inline components/net_traits/image_cache_thread.rs]: Why do we need this?

Comment (ice9js) [inline components/net_traits/image_cache_thread.rs]: That's the error type from the Result that was previously unwrapped. It wouldn't compile without converting the error to ImageState.

Comment (Wafflespeanut) [inline components/net_traits/image_cache_thread.rs]: We could use [`map_err`](https://doc.rust-lang.org/core/result/enum.Result.html#method.map_err) instead of introducing another dependency for the sake of returning an error :)

**Comment by Wafflespeanut** [comment]
otherwise, lgtm :smile:

File: components/net_traits/image_cache_thread.rs (hunk 1 above)
Comment (ice9js) [inline components/net_traits/image_cache_thread.rs]: Alright, thanks for the tip :) I've made the necessary adjustments.

**Comment by Wafflespeanut** [comment]
Thanks for doing this work! :)

@bors-servo r+
