### PR TITLE
Properly check storage size against QUOTA_SIZE_LIMIT (fixes #12247)

### LINKED ISSUE #12247: Servo chokes on www.slate.com
The page half-loads and I see repeated complaining about:
ERROR:js::rust: Error at :0:0: QuotaExceededError: The quota has been exceeded.

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12289)

### CODE REVIEW

File: components/net/storage_thread.rs [hunk 1]
```diff
@@ -144,12 +144,16 @@ impl StorageManager {
...
         let origin = self.origin_as_string(url);
 
-        let current_total_size = {
+        let (this_storage_size, other_storage_size) = {
             let local_data = self.select_data(StorageType::Local);
             let session_data = self.select_data(StorageType::Session);
             let local_data_size = local_data.get(&origin).map_or(0, |&(total, _)| total);
             let session_data_size = session_data.get(&origin).map_or(0, |&(total, _)| total);
-            local_data_size + session_data_size
+            if storage_type == StorageType::Local {
```
Comment (Ms2ger) [inline components/net/storage_thread.rs]: Make this a `match` instead
