### PR TITLE
canvas: Make ImageBitmapRenderingContext render to the canvas

### LINKED ISSUE #43565: ImageBitmapRenderingContext: `transferFromImageBitmap()` doesn't work
**Describe the bug:**
See example. 
P.S. Is this related to #37710 ?

**To Reproduce:**
```html
<canvas id="X" width="120" height="120"></canvas>
<script>
    (async function() {
        let f = await fetch('https://servo.org/img/blog/2026-02-diffie.png')
        console.log('Got image data')
        let bm = await createImageBitmap(await f.blob())
        console.log('Got bitmap')
        X.getContext('bitmaprenderer').transferFromImageBitmap(bm)
        console.log('Rendered')
    })()
</script>
```
Chrome
Image
Firefox (for some reason Firefox resizes the `canvas` element once `transferFromImageBitmap()` resolves. Uhh, you read [this](https://html.spec.whatwg.org/multipage/canvas.html#set-an-imagebitmaprenderingcontext's-output-bitmap) and tell me what you think should happen.)
Image
Servo (displays stone cold nuthin')
Image

**Platform:**
Servo Windows 10

### PR DESCRIPTION
**Pull request by Messi002**
I noticed that the transferFromImageBitmap() was running without errors but the canvas stayed blank and this was becacuse of two issues:

The mark_as_dirty was empty meaning the canvas never knew it needed to repaint
The BitmapRenderer context had no rendering pipeline as such no ImageKey was allocated and update_rendering always returned false, so the way I fixed it is by

1. Implemented mark_as_dirty to call self.canvas.mark_as_dirty()
2. Allocated an ImageKey for BitmapRenderer contexts
3.Implemented set_image_key and update_rendering that sends the bitmap's pixel data to WebRender via the paint API
4, Calling mark_as_dirty after set_bitmap in TransferFromImageBitmap

Now the reason we are setting an ImageKey on the ImageBitmaRenderingContext is because it needs one to render to the screen and without it the canvas was always blank

Also I noticed that for some reasons I don't understand yet, the createImageBitmap hangs or is slow to render but after loading servo on an open tab, if I then go ahead and open another tab and paste the file link there, the previous tab which had the bitmap image now renders properly 

Fixes: #43565

Screenshot from 2026-04-06 13-44-28
Screenshot from 2026-04-06 15-38-55

### CODE REVIEW

**Comment by jdm** [comment]
@Messi002 If you press the "update branch" button on your PRs, please don't: https://book.servo.org/contributing/making-a-pull-request.html#addressing-merge-conflicts . It just uses CI resources unnecessarily.

**Comment by Messi002** [comment]
Oh My bad 
My apologies, @jdm

**Comment by jdm** [comment]
I think the test timeouts are coming from the same issue you mentioned about the missing canvas image. Specifically, I am suspicious that we are delaying rendering new frames because of this code: https://github.com/servo/servo/blob/66d232e1e72f6251de10edc2c32ff9a6fe55dc3b/components/script/dom/document/document.rs#L2920-L2932

**Comment by jdm** [comment]
Oh, yeah, that would explain it—we're sending the image data as part of update_rendering, which runs _before_ that code, and then we are instructing the paint thread to wait for more image data from the canvas, but that data won't come until there's some other reason to repaint the canvas.

**Comment by jdm** [comment]
```diff
diff --git a/components/script/dom/canvas/imagebitmaprenderingcontext.rs b/components/script/dom/canvas/imagebitmaprenderingcontext.rs
index 621fde49279..66745eba36e 100644
--- a/components/script/dom/canvas/imagebitmaprenderingcontext.rs
+++ b/components/script/dom/canvas/imagebitmaprenderingcontext.rs
@@ -112,7 +112,7 @@ impl ImageBitmapRenderingContext {
                 self.image_added.set(true);
             }
         }
-        true
+        false
     }

     /// <https://html.spec.whatwg.org/multipage/#set-an-imagebitmaprenderingcontext's-output-bitmap>
diff --git a/components/script/dom/html/htmlcanvaselement.rs b/components/script/dom/html/htmlcanvaselement.rs
index 64c142a6472..f81edc5ad53 100644
--- a/components/script/dom/html/htmlcanvaselement.rs
+++ b/components/script/dom/html/htmlcanvaselement.rs
@@ -405,10 +405,13 @@ impl HTMLCanvasElement {
         }
     }

+    /// Returns Some(ImageKey) if there is an asynchronous image data update
+    /// expected for the image key. Returns None if all image data updates
+    /// for that key have already occurred.
     pub(crate) fn update_rendering(&self, epoch: Epoch) -> Option<ImageKey> {
         let context = self.context()?;
         let image_key = self.image_key.get()?;
-        match &*context {
+        let pending = match &*context {
             RenderingContext::Placeholder(..) => false,
             RenderingContext::Context2d(context) => context.update_rendering(epoch),
             RenderingContext::BitmapRenderer(context) => context.update_rendering(),
@@ -416,8 +419,12 @@ impl HTMLCanvasElement {
             RenderingContext::WebGL2(context) => context.base_context().update_rendering(epoch),
             #[cfg(feature = "webgpu")]
             RenderingContext::WebGPU(context) => context.update_rendering(epoch),
+        };
+
+        if pending {
+            return Some(image_key);
         }
-        .then_some(image_key)
+        None
     }
 }
```
This gave me:
```
  ▶ PASS [expected FAIL] /html/canvas/element/manual/imagebitmap/imageBitmapRendering-transferFromImageBitmap.html

  ▶ PASS [expected FAIL] /html/canvas/element/manual/imagebitmap/imageBitmapRendering-transferFromImageBitmap-flipped.html
```

File: components/script/dom/html/htmlcanvaselement.rs [hunk 1]
```diff
@@ -411,7 +411,7 @@ impl HTMLCanvasElement {
         match &*context {
             RenderingContext::Placeholder(..) => false,
             RenderingContext::Context2d(context) => context.update_rendering(epoch),
-            RenderingContext::BitmapRenderer(..) => false,
+            RenderingContext::BitmapRenderer(context) => context.update_rendering(),
```
Comment (jdm) [inline components/script/dom/html/htmlcanvaselement.rs]: We should pass the epoch here.

File: components/script/dom/canvas/imagebitmaprenderingcontext.rs [hunk 2]
```diff
@@ -60,6 +72,49 @@ impl ImageBitmapRenderingContext {
...
+        };
+        let data = SerializableImageData::Raw(shared.shared_memory());
+
+        // Here we get the paint API from the canvas element's window.
+        if let HTMLCanvasElementOrOffscreenCanvas::HTMLCanvasElement(ref canvas) = self.canvas {
+            let canvas: &HTMLCanvasElement = canvas;
+            let doc = canvas.owner_document();
+            let paint_api = doc.window().paint_api();
+            if self.image_added.get() {
+                paint_api.update_image(image_key, descriptor, data, None);
```
Comment (jdm) [inline components/script/dom/canvas/imagebitmaprenderingcontext.rs]: We can use the epoch as the last argument here.

File: components/script/dom/html/htmlcanvaselement.rs (hunk 1 above)
Comment (Messi002) [reply components/script/dom/html/htmlcanvaselement.rs]: ok @jdm

File: components/script/dom/canvas/imagebitmaprenderingcontext.rs (hunk 2 above)
Comment (Messi002) [reply components/script/dom/canvas/imagebitmaprenderingcontext.rs]: let me update that

**Comment by Messi002** [comment]
Thank you very much @jdm 
it works just fine now

**Comment by Messi002** [comment]
@jdm 
The test timeout here are they also unrelated.

**Comment by Messi002** [comment]
Hello @gterzian 
Can you please tell me if the branch is ready for to be put in the merge queue?

**Review by jdm — APPROVED** [review]
Thanks for fixing this!
