### PR TITLE
Don't create empty stacking contexts in display lists

### LINKED ISSUE #26590: Crash on altspace help page (index out of bounds: the len is 0 but the index is 0)
https://help.altvr.com/hc/en-us/articles/360016344513-How-do-I-upload-my-own-Kits- crashes in the nightly build when I navigate to it from https://help.altvr.com/hc/en-us.

### LINKED ISSUE #26592: Youtube crashes (index out of bounds: the len is 0 but the index is 0)
A bunch of content on the homepage loads in the 5/20 nightly, then there's a pause before some more content appears immediately followed by a crash.

### PR DESCRIPTION
**Pull request by jdm**
A recent change to euclid exposed that our display lists can contain Rects that contain NaN values. These NaNs originate from creating stacking contexts with transforms that scale the horizontal or vertical dimensions to 0. WebRender isn't prepared to handle these, so we need to not produce these empty stacking contexts when building the display list.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #26592 and fix #26590
- [x] There are tests for these changes

### CODE REVIEW

**Comment by jdm** [comment]
No need to review this yet. A lot of tests are failing that I need to investigate.

**Comment by jdm** [comment]
Weird, some tests run fine in headed mode, but panic in headless mode.

**Comment by jdm** [comment]
@mrobinson This PR is now ready for review.

File: components/layout/fragment.rs [hunk 1]
```diff
@@ -2730,6 +2730,14 @@ impl Fragment {
             self.style().get_box().perspective != Perspective::None
     }
 
+    /// Returns true if this fragment has a transform applied that causes it to take up no space.
+    pub fn has_non_invertible_transform(&self) -> bool {
+        let transform = self
+            .transform_matrix(&Rect::default())
+            .unwrap_or(LayoutTransform::identity());
+        !transform.is_invertible()
```
Comment (mrobinson) [inline components/layout/fragment.rs:2738]: This could potentially be: 

```rust
self.transform_matrix(&Rect::default())
    .map(|matrix| transform.is_invertible())
    .unwrap_or_else(false)
```

That would avoid creating an extra transformation matrix. Testing for invertability is sometiems expensive.

File: components/layout_2020/display_list/stacking_context.rs [hunk 2]
```diff
@@ -778,6 +788,18 @@ impl BoxFragment {
         })
     }
 
+    /// Returns true if the given style contains a transform that is not invertible.
+    pub(crate) fn has_non_invertible_transform(
```
Comment (mrobinson) [inline components/layout_2020/display_list/stacking_context.rs:792]: If you made this a method that took `&self` then I think you could avoid passing the style here.

File: components/layout_2020/display_list/mod.rs [hunk 3]
```diff
@@ -330,6 +330,16 @@ impl<'a> BuilderForBoxFragment<'a> {
     }
 
     fn build(&mut self, builder: &mut DisplayListBuilder) {
+        // If this box fragment has a transform applied that makes it take up no space,
```
Comment (mrobinson) [inline components/layout_2020/display_list/mod.rs:333]: I think you can omit this check here, since you will not be adding this fragment to the `StackingContextTree`.

**Review by mrobinson — APPROVED** [review]
Nice! I think there is one check that is redudant, but otherwise this looks correct.

**Comment by jdm** [comment]
@bors-servo retry
* #26834
