### PR TITLE
Fix substraction with overflow in range request

### LINKED ISSUE #23030: Subtraction underflow in cache range request
https://my.panomoments.com/u/MomentCaptureStudio/m/fusterlandia?hideInfo=1

```
attempt to subtract with overflow (thread fetch thread for https://s3.amazonaws.com/data.panomoments.com/processed/58a7514e550d37000bfd46d2/5c2fc6bbc077e8000e8c1729/hd_dashinit.mp4, at components/net/http_cache.rs:431)
stack backtrace:
   0:        0x1097cbb84 - __ZN9backtrace9backtrace5trace17h9f3458ac04360c1aE
                        at /Users/jdm/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:        0x1097c652c - __ZN9backtrace7capture9Backtrace14new_unresolved17h21921a7295046aa9E
                        at /Users/jdm/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:        0x1097c648e - __ZN9backtrace7capture9Backtrace3new17h18226acc03ed089aE
                        at /Users/jdm/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:63
   3:        0x1033f3a25 - __ZN5servo4main28_$u7b$$u7b$closure$u7d$$u7d$17h2b05144528e4d274E
                        at ports/servo/non_android_main.rs:110
   4:        0x10ac5dc10 - __ZN3std9panicking20rust_panic_with_hook17hc96a2ab9717cf47bE
                        at src/libstd/panicking.rs:482
   5:        0x10ac5d65c - __ZN3std9panicking18continue_panic_fmt17h829e4b1e6e9a8f39E
                        at src/libstd/panicking.rs:385
   6:        0x10ac5d548 - _rust_begin_unwind
                        at src/libstd/panicking.rs:312
   7:        0x10ac7b271 - __ZN4core9panicking9panic_fmt17heb4299280251fdc5E
                        at src/libcore/panicking.rs:85
   8:        0x10ac7b1b6 - __ZN4core9panicking5panic17h516d57ef274e41dfE
                        at src/libcore/panicking.rs:49
   9:        0x10714c95a - __ZN3net10http_cache20handle_range_request17hbc68df030868def9E
                        at components/net/http_cache.rs:431
  10:        0x10714d4ce - __ZN3net10http_cache9HttpCache18construct_response17h87273fd8a93d4ebeE
                        at components/net/http_cache.rs:619
  11:        0x1073e929c - __ZN3net11http_loader27http_network_or_cache_fetch17h87596ac57a536456E
                        at components/net/http_loader.rs:961
  12:        0x1073e5687 - __ZN3net11http_loader10http_fetch17h6339fe8955151039E
                        at components/net/http_loader.rs:539
  13:        0x10737b059 - __ZN3net5fetch7methods10main_fetch28_$u7b$$u7b$closure$u7d$$u7d$17h0e14b86ff2491210E
                        at components/net/fetch/methods.rs:271
  14:        0x107277126 - __ZN38_$LT$core..option..Option$LT$T$GT$$GT$14unwrap_or_else17h871bc22ec0ad5c27E
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libcore/option.rs:386
  15:        0x107378de7 - __ZN3net5fetch7methods10main_fetch17h0864c574a1c2bb02E
                        at components/net/fetch/methods.rs:230
  16:        0x107378508 - __ZN3net5fetch7methods21fetch_with_cors_cache17haf3109e8ca4d50c6E
                        at components/net/fetch/methods.rs:138
  17:        0x107378366 - __ZN3net5fetch7methods5fetch17h688ed9ebd2d3feebE
                        at components/net/fetch/methods.rs:98
  18:        0x10718aa4f - __ZN3net15resource_thread19CoreResourceManager5fetch28_$u7b$$u7b$closure$u7d$$u7d$17hd7a3c0f7e1fe99deE
                        at components/net/resource_thread.rs:481
  19:        0x1073bc0d2 - __ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17hd1d4172126b647c6E
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/sys_common/backtrace.rs:136
  20:        0x1072c8cd2 - __ZN3std6thread7Builder15spawn_unchecked28_$u7b$$u7b$closure$u7d$$u7d$28_$u7b$$u7b$closure$u7d$$u7d$17hda23f4b0cafa6aa1E
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/thread/mod.rs:469
  21:        0x1072fc492 - __ZN101_$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$9call_once17h70b0d79d1423d4a4E
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panic.rs:309
  22:        0x1072caac2 - __ZN3std9panicking3try7do_call17h50cd9191bd53de6aE
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panicking.rs:297
  23:        0x10ac66e9e - ___rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:87
  24:        0x1072ca1e4 - __ZN3std9panicking3try17hbe567b78311811d5E
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panicking.rs:276
  25:        0x107307162 - __ZN3std5panic12catch_unwind17he1485a9cc1fa017eE
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panic.rs:388
  26:        0x1072c6c9b - __ZN3std6thread7Builder15spawn_unchecked28_$u7b$$u7b$closure$u7d$$u7d$17h1276185efa6d9387E
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/thread/mod.rs:468
  27:        0x1072e9cd3 - __ZN50_$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$8call_box17h4ea4bd4d93f45feaE
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/liballoc/boxed.rs:749
  28:        0x10ac662cb - __ZN3std3sys4unix6thread6Thread3new12thread_start17hb65474f74178fcb3E
                        at src/libstd/sys_common/thread.rs:14
  29:     0x7fff9257e93a - __pthread_body
  30:     0x7fff9257e886 - __pthread_start
```

### PR DESCRIPTION
**Pull request by gterzian**
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #23030 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23036)

### CODE REVIEW

**Comment by gterzian** [comment]
@jdm r?

Sorry I had missed your self-assignment to the issue...

**Comment by gterzian** [comment]
Ok I think I've addressed all potential overflowing operations, maybe a bit over the top for some, but better safe than sorry!

File: components/net/http_cache.rs [hunk 1]
```diff
@@ -428,12 +433,31 @@ fn handle_range_request(
...
                     _ => continue,
                 };
-                if res_beginning - 1 < beginning && res_end + 1 > end {
+                let (res_beginning_minus_one, res_end_plus_one) = {
+                    match (res_beginning.checked_sub(1), res_end.checked_add(1)) {
+                        (Some(minus_one), Some(plus_one)) => (minus_one, plus_one),
+                        _ => continue,
+                    }
+                };
+                if res_beginning_minus_one < beginning && res_end_plus_one > end {
```
Comment (jdm) [inline components/net/http_cache.rs]: Instead of this block, can't we do `if res_beginning <= beginning && res_end >= end`?

File: components/net/http_cache.rs [hunk 2]
```diff
@@ -428,12 +433,31 @@ fn handle_range_request(
...
                     let resource_body = &*partial_resource.body.lock().unwrap();
                     let requested = match resource_body {
                         &ResponseBody::Done(ref body) => {
-                            let b = beginning as usize - res_beginning as usize;
-                            let e = end as usize - res_beginning as usize + 1;
+                            let (b, e) = {
```
Comment (jdm) [inline components/net/http_cache.rs]: Since we have already established that `res_beginning <= beginning` we do not need a checked_sub. Similarly, if we establish that `end >= res_beginning` then we don't need to check that operation either.

File: components/net/http_cache.rs [hunk 3]
```diff
@@ -474,11 +498,22 @@ fn handle_range_request(
                 } else {
                     continue;
                 };
-                if res_beginning < beginning && res_end == total - 1 {
+                let total_minus_one = {
```
Comment (jdm) [inline components/net/http_cache.rs]: If we check that total != 0 earlier then we don't need a checked subtraction here.

File: components/net/http_cache.rs [hunk 4]
```diff
@@ -474,11 +498,22 @@ fn handle_range_request(
...
+                        _ => continue,
+                    }
+                };
+                if res_beginning < beginning && res_end == total_minus_one {
                     let resource_body = &*partial_resource.body.lock().unwrap();
                     let requested = match resource_body {
                         &ResponseBody::Done(ref body) => {
-                            let from_byte = beginning as usize - res_beginning as usize;
+                            let from_byte = {
+                                match beginning.checked_sub(res_beginning) {
```
Comment (jdm) [inline components/net/http_cache.rs]: Since we have established that `res_beginning < beginning` there is no need to check this operation.

File: components/net/http_cache.rs [hunk 5]
```diff
@@ -519,7 +554,23 @@ fn handle_range_request(
                 } else {
                     continue;
                 };
-                if (total - res_beginning) > (offset - 1) && (total - res_end) < offset + 1 {
+                let (total_minus_res_beginning, total_minus_res_end) = {
```
Comment (jdm) [inline components/net/http_cache.rs]: If we check that `total >= res_beginning` and `total >= res_end` then we don't need these checked operations.

**Review by jdm — CHANGES_REQUESTED** [review]
These changes achieve the goal of removing over/underflow hazards, but lots of checked operations make the code harder to follow in my opinion. I think we can simplify some of the changes by establishing preconditions when extracting the ContentRange values like this:
```rust
match (range.bytes_range(), range.bytes_len()) {
    (Some(bytes_range), Some(total)) if total > 0 => (bytes_range.0, bytes_range.1, total),
    _ => continue,
}
```

**Comment by gterzian** [comment]
@jdm Ok, much simpler indeed!
