### PR TITLE
Expose nested browsing context status in RequestClient

### LINKED ISSUE #41639: Expose nested browsing context status in RequestClient
We're missing step 2.2 of https://w3c.github.io/webappsec-upgrade-insecure-requests/#upgrade-request in our implementation in https://github.com/servo/servo/blob/9ca7628dbdc525e3e1567efcd65add053cd4ce83/components/net/fetch/methods.rs#L1182-L1183

This leads to timeouts in tests like https://github.com/servo/servo/blob/main/tests/wpt/tests/upgrade-insecure-requests/link-upgrade.sub.https.html because the iframes loaded from http URLs are never upgraded to https, so they get blocked as mixed content.

We need to:
* add a new `is_nested_browsing_context: bool` to https://github.com/servo/servo/blob/9ca7628dbdc525e3e1567efcd65add053cd4ce83/components/shared/net/request.rs#L187
* set it to true in https://github.com/servo/servo/blob/main/components/script/dom/globalscope.rs#L2610 if:
  * the global scope is a Window, and
  * `window.is_top_level()` is false
* use the new value in `should_upgrade_navigation_request` via `request.client`

You can test this against `./mach test-wpt tests/wpt/tests/upgrade-insecure-requests` and `./mach test-wpt tests/wpt/tests/mixed-content`; I would expect a bunch of new subtests going from TIMEOUT to a PASS/FAIL result.

### PR DESCRIPTION
**Pull request by WaterWhisperer**
implement step 2.2 of <https://w3c.github.io/webappsec-upgrade-insecure-requests/#upgrade-request> by adding an is_nested_browsing_context field to RequestClient

Testing: `./mach test-wpt tests/wpt/tests/upgrade-insecure-requests` and `./mach test-wpt tests/wpt/tests/mixed-content`
Fixes: #41639

### CODE REVIEW

File: components/script/dom/globalscope.rs [hunk 1]
```diff
@@ -2603,14 +2603,16 @@ impl GlobalScope {
     pub(crate) fn request_client(&self) -> RequestClient {
         // Step 1.2.2. If global is a Window object and global’s navigable is not null,
         // then set request’s traversable for user prompts to global’s navigable’s traversable navigable.
-        let preloaded_resources = self
-            .downcast::<Window>()
+        let window = self.downcast::<Window>();
+        let preloaded_resources = window
             .map(|window: &Window| window.Document().preloaded_resources())
             .unwrap_or_default();
+        let is_nested_browsing_context = window.is_some_and(|w| !w.is_top_level());
```
Comment (yezhizhen) [inline components/script/dom/globalscope.rs]:
```suggestion
        let is_nested_browsing_context = window.is_some_and(|window| !window.is_top_level());
```

Comment (WaterWhisperer) [reply components/script/dom/globalscope.rs]: well, ok

**Comment by yezhizhen** [comment]
There seems to be no tests covering this. Maybe someone else can suggest something.

**Comment by TimvdLippe** [comment]
From the issue:

> You can test this against ./mach test-wpt tests/wpt/tests/upgrade-insecure-requests and ./mach test-wpt tests/wpt/tests/mixed-content; I would expect a bunch of new subtests going from TIMEOUT to a PASS/FAIL result.

@WaterWhisperer Did you debug these tests to see why they are still not running as expected? Do we need to implement a different feature as well to make them pass? If you are unsure how to debug such tests, feel free to start a thread on Zulip so we can help you out.

**Comment by WaterWhisperer** [comment]
> From the issue:
> 
> > You can test this against ./mach test-wpt tests/wpt/tests/upgrade-insecure-requests and ./mach test-wpt tests/wpt/tests/mixed-content; I would expect a bunch of new subtests going from TIMEOUT to a PASS/FAIL result.
> 
> @WaterWhisperer Did you debug these tests to see why they are still not running as expected? Do we need to implement a different feature as well to make them pass? If you are unsure how to debug such tests, feel free to start a thread on Zulip so we can help you out.

Thanks for the feedback! I've investigated this further:

After looking at the test details, I guess that the `link-upgrade` tests are still timing out because they test link navigation from within iframes, which is different from iframe loading itself. These tests require navigation upgrade, which may need additional work beyond just setting `is_nested_browsing_context`.

File: components/net/fetch/methods.rs
Comment (TimvdLippe) [inline components/net/fetch/methods.rs]: Can you maybe also implement step 3?

> Let upgrade state be the result of executing [§ 4.2 Should insecure requests be upgraded for client?](https://w3c.github.io/webappsec-upgrade-insecure-requests/#should-upgrade-for-client) upon request’s [client](https://fetch.spec.whatwg.org/#concept-request-client).

For that you need to modify the request client as well and pass the relevant information from the document (skip detached clients for now): https://w3c.github.io/webappsec-upgrade-insecure-requests/#insecure-requests-policy

That should be sufficient for this PR. If you are eager, you can then also tackle CSP integration, which the tests appear to be using: https://w3c.github.io/webappsec-upgrade-insecure-requests/#delivery Once you implement that header, I expect the tests to start passing. For that, we have a fork of the CSP crate that we need to update as well: https://github.com/servo/rust-content-security-policy/tree/servo-csp

Comment (TimvdLippe) [reply components/net/fetch/methods.rs]: Ah we already implement it on `Document`: https://github.com/servo/servo/blob/de27dc69e5fb7a3490e9ee72fca60dc7053b52f9/components/script/dom/document.rs#L3768 Therefore, I think if you implement step 3 then tests should start passing.

Comment (WaterWhisperer) [reply components/net/fetch/methods.rs]: Thanks! I'll start to implement it.

**Comment by yezhizhen** [comment]
Btw there is conflict.

**Comment by WaterWhisperer** [comment]
> Btw there is conflict.

Thanks, I'll rebase it

**Comment by WaterWhisperer** [comment]
I'm not sure if there's something wrong with my implementation, and running the relevant tests locally not only makes the timed out tests non-timeout, but also causes the tests that otherwise passed to fail :(

**Comment by TimvdLippe** [comment]
Let's run CI so we can analyze the results and help you further. Thanks for tackling!

**Comment by jdm** [comment]
@WaterWhisperer See if my new guide in https://github.com/servo/book/pull/192 can help?

**Comment by jdm** [comment]
Actually I bet one problem is this: https://github.com/servo/servo/blob/8295a98976497bc52d42edffab60b0c12444aee3/components/script/navigation.rs#L197

We're not setting the request client for navigation requests.

**Comment by WaterWhisperer** [comment]
> Actually I bet one problem is this:
> 
> https://github.com/servo/servo/blob/8295a98976497bc52d42edffab60b0c12444aee3/components/script/navigation.rs#L197
> 
> We're not setting the request client for navigation requests.

Thanks, I tried setting the RequestClient for navigation requests in `navigation.rs`. The only change is that a test that previously timed out has now passed. Maybe the remaining worker/websocket failures may require adding a similar RequestClient setting to the creation path of these resources as well?

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/c68748a328caab3df6a156d69ce101b49a98681f/components/script/dom/workers/dedicatedworkerglobalscope.rs#L388 is missing a client, and so is https://github.com/servo/servo/blob/c68748a328caab3df6a156d69ce101b49a98681f/components/script/dom/websocket.rs#L281 . So yes, that seems very likely!

**Review by TimvdLippe — APPROVED** [review]
Nice work and thanks for tackling the additional missing parts!
