### PR TITLE
script: Upgrade `node_ids` to `pipeline_to_node_ids` to track the owner pipeline of the node

### LINKED ISSUE #35749: Webdriver doesn't expect stale element references for ids from other contexts
We support stale element references by stashing all node ids ever observed in a hashset in ScriptThread. However, this means that when a webdriver uses a node id from another frame inside the wrong frame, we return an incorrect stale element reference instead of a missing node error.

### PR DESCRIPTION
**Pull request by yezhizhen**
Upgrade `ScriptThread::node_ids` to `pipeline_to_node_ids` to track the owner pipeline of the node
This will enable webdriver to know if it is requesting element from other origins and properly distinguish "stale element reference" from "no such element".

Testing: [Action run](https://github.com/yezhizhen/servo/actions/runs/15385994907), no regression. We can now pass WebDriver "cross origin" tests. 

Fixes: #35749

### CODE REVIEW

File: components/script/script_thread.rs [hunk 1]
```diff
@@ -315,8 +317,9 @@ pub struct ScriptThread {
     #[no_trace]
     player_context: WindowGLContext,
 
-    /// A set of all nodes ever created in this script thread
-    node_ids: DomRefCell<HashSet<String>>,
+    /// A map from pipelines to all owned nodes ever created in this script thread
+    #[no_trace]
+    pipeline_to_node_ids: DomRefCell<HashMap<PipelineId, NodeIdSet>>,
```
Comment (yezhizhen) [inline components/script/script_thread.rs:322]: I read the doc for `JSTraceable`. I believe this has never been managed by SpiderMonkey GC so added no_trace. CMIIW.

Comment (yezhizhen) [inline components/script/script_thread.rs:322]: I read the doc for JSTraceable. I believe this has never been managed by SpiderMonkey GC so added no_trace. CMIIW.

File: tests/wpt/meta/webdriver/tests/classic/take_element_screenshot/iframe.py.ini [hunk 2]
```diff
@@ -1,9 +1,3 @@
 [iframe.py]
   [test_frame_element]
     expected: FAIL
-
-  [test_source_origin[same_origin\]]
-    expected: FAIL
-
-  [test_source_origin[cross_origin\]]
-    expected: FAIL
```
Comment (yezhizhen) [inline tests/wpt/meta/webdriver/tests/classic/take_element_screenshot/iframe.py.ini:9]: We can now pass "cross origin" tests. There are a lot more "test_* _from_other_frame" I tried from #36673 that would pass once #37095 is merged, as I cherry-pick and tested locally. Right now they just TIMEOUT😭

File: components/script/script_thread.rs (hunk 1 above)
Comment (yezhizhen) [inline components/script/script_thread.rs:322]: I read the doc for JSTraceable. I believe this has never been managed by SpiderMonkey GC so added `no_trace`. CMIIW.
@jdm @sagudev

**Comment by yezhizhen** [comment]
cc @longvatrong111 @xiaochengh @PotatoCP

File: components/script/script_thread.rs (hunk 1 above)
Comment (sagudev) [reply components/script/script_thread.rs:322]: That's correct.

Comment (yezhizhen) [reply components/script/script_thread.rs:322]: In that case, can we just use `RefCell` instead of `DomRefCell`? Somehow the comments don't appear in "Conversasion"..

Comment (sagudev) [reply components/script/script_thread.rs:322]: IIRC `DomRefCell` is not really about SM, but about accessing script stuff from layout (in middle of script run): https://doc.servo.org/script/dom/bindings/cell/struct.DomRefCell.html#method.borrow_for_layout, so I think that generally depends on its uses. But I think it is a convention to always use DomRefCell in dom code (even we do not need it's additional functionality last but not least, DomRefCell is just wrapper around RefCell with additional methods).

Comment (sagudev) [reply components/script/script_thread.rs:322]: TL;DR Keep `DomRefCell` in script code.

**Review by jdm — APPROVED** [review]
Nice change!
