### PR TITLE
layout: Fix size of anonymous not marked as depending on block constraints

### LINKED ISSUE #41629: Layout of anonymous blocks should propagate depends_on_block_constraints
```html
<!DOCTYPE html>
<style>
#flex-container {
  display: flex;
  flex-direction: column;
}
#flex-item {
  width: 200px;
  height: 200px;
  background: red;
}
#target {
  height: 100%;
  background: green;
}
</style>

<p>Test passes if there is a filled green square and <strong>no red</strong>.</p>

<div id="flex-container">
  <div id="flex-item">
    <div><!-- This wraps the inline-level canvas inside an anonymous block --></div>
    <canvas id="target" width="100" height="100"></canvas>
  </div>
</div>
```

| Actual | Expected |
| - | - |
| Image | Image |

The anonymous block around the `<canvas>` doesn't establish a containing block. So it should propagate the `depends_on_block_constraints` up to the flex item.

### PR DESCRIPTION
**Pull request by Loirooriol**
An anonymous block box doesn't establish a containing block for its contents. Therefore, if its contents depend on block constraints, we need to mark it as having a size that depends on block constraints.

Testing: Adding new test
Fixes: #41629

### CODE REVIEW

File: components/layout/flow/mod.rs [hunk 1]
```diff
@@ -1160,7 +1160,12 @@ pub(crate) fn layout_in_flow_non_replaced_block_level_same_formatting_context(
     };
 
     let mut base_fragment_info = base.base_fragment_info;
-    if depends_on_block_constraints {
+
+    // An anonymous block doesn't establish a containing block for its contents. Therefore,
+    // if its contents depend on block constraints, its block size (which is intrinsic) also
+    // depends on block constraints.
+    let is_anonymous = matches!(base.style.pseudo(), Some(PseudoElement::ServoAnonymousBox));
+    if depends_on_block_constraints || is_anonymous && flow_layout.depends_on_block_constraints {
```
Comment (yezhizhen) [inline components/layout/flow/mod.rs]:
```suggestion
    if depends_on_block_constraints || (is_anonymous && flow_layout.depends_on_block_constraints) {
```

**Review by mrobinson — APPROVED** [review]
