### PR TITLE
Replace unwind-sys with backtrace crate on Linux

### LINKED ISSUE #35063: Replace `libunwind-sys` crate with `backtrace`
Currently, the `background-hang-monitor` in Servo requires `libunwind-sys`. This crate is problematic in that it directly wraps nongnu/hp `libunwind`¹, which on some systems has incompatibility with the clang `libunwind` of the same name. In particular (for reasons that seem to be vaguely unreasonable, and which I do intend to also file a bug on Debian about…) Debian and Debian-based Linux distributions like Ubuntu have an exclusion where if you install the `libunwind-dev` package (required to build libunwind-sys, and therefore required to build Linux Servo), it will completely uninstall the `libc++-dev` package (in other words, the Clang STL) and everything that depends on it. This has caused some real difficulty for me in the past as I would like to be able to build Servo but for work I need to work with clang libc++ sometimes.

In discussions on Mastodon, I was assured by the maintainer of YoWASP (an unwinding/runtime nightmare specialist) that everything Servo is doing with `libunwind-sys` could be done with `backtrace`, a more general crate which works not only with nongnu/hp libunwind but also with the clang and libgcc_s native unwind systems. This would avert the Debian compatibility problems, possibly make it possible to build Servo on a wider range of Linux systems, and *possibly* allow `sampler_linux.rs` to be merged with some of the other platform-specific code.

**Platform:**
I have been affected by the above on Debian "Trixie" and Ubuntu 24.04

¹ I [did discuss this with the libunwind-sys maintainer](https://github.com/sfackler/rstack/issues/31) and he is actively uninterested in patches to expand the scope of the libunwind-sys crate to include additional unwind libraries.

### PR DESCRIPTION
**Pull request by CarePackage17**
This PR removes `unwind-sys` usage from background_hang_monitor on Linux, replacing it with the [backtrace crate](https://crates.io/crates/backtrace).

Testing: `hang_monitor-tests.rs` still pass after the change (on Ubuntu 24.04).
Fixes: https://github.com/servo/servo/issues/35063

### CODE REVIEW

**Comment by jschwe** [comment]
> Testing: hang_monitor-tests.rs still pass after the change (on Ubuntu 24.04).

Do the hang monitor tests test the backtrace functionality (i.e. verifying that we get a reasonable backtrace)?

**Comment by CarePackage17** [comment]
Looks like they don't.

Is there an existing way to test this manually?

**Comment by CarePackage17** [comment]
Is the `sampler` feature in `background_hang_monitor` even enabled by default when building on Linux? I couldn't find it in any of the Cargo.toml files that reference that crate.

If not, then it's always been just the dummy sampler that errors out by default when asked to sample a thread.

**Comment by jschwe** [comment]
libservo conditionally enables the sampling feature:  https://github.com/servo/servo/blob/8e2ef5c248aa7a1abae1a7ddc39425ce1f17dcb5/components/servo/Cargo.toml#L28

The libservo feature is enabled from servoshell AFAIK.

> Is there an existing way to test this manually?

I've not tried this before, but how about just inserting a `loop {}` somewhere and wait until the background hang monitor prints something?

**Comment by CarePackage17** [comment]
I did try debugging into unit tests, but those seem to be built without the sampler feature (i.e. I get a dummy sampler at runtime for some reason).
Is there a way to get the Linux sampler while debugging unit tests (or alternatively, how do I check which features are enabled when compiling/running via cargo test)?

**Comment by jschwe** [comment]
You could temporarily add it to the default-features during local testing. Or enable the feature when running cargo test  via --features ....

**Comment by CarePackage17** [comment]
I did the 2nd thing you suggested and added some code to print a HangProfile in one of the tests, which gave me this output:

```
cargo test --features background_hang_monitor/sampler --package background_hang_monitor  -- --nocapture
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.19s
     Running tests/hang_monitor_tests.rs (target/debug/deps/hang_monitor_tests-b7650a9b16efa67b)

running 6 tests
test test_hang_monitoring_exit_signal1 ... ok
profile is some:
HangProfile backtrace:
                         - clone3
                        at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
                         - start_thread
                        at ./nptl/pthread_create.c:447
                         - _ZN90_$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$9call_once17h2649f14f1b1c150dE
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/alloc/src/boxed.rs:1993
                         - _ZN90_$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$9call_once17hb2ade58cb34e1bc4E
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/alloc/src/boxed.rs:1993
                         - _ZN3std3sys3pal4unix6thread6Thread3new12thread_start17ha07e360225fa3528E
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/sys/pal/unix/thread.rs:106
                         - _ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h864dc1cf6b75f549E
                        at /home/krzysztof/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
                         - _ZN3std9panicking3try17hb71c06903976dbf6E
                        at /home/krzysztof/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:547
                         - _ZN3std5panic12catch_unwind17h248639f162bc95e1E
                        at /home/krzysztof/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:358
                         - _ZN3std6thread7Builder16spawn_unchecked_28_$u7b$$u7b$closure$u7d$$u7d$17h5bf4c27a6ef45954E
                        at /home/krzysztof/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:562
                         - __rust_try
                         - _ZN3std9panicking3try7do_call17he11f7020c9241224E
                        at /home/krzysztof/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:584
                         - _ZN115_$LT$core..panic..unwind_safe..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$9call_once17h99807cc8791f6f98E
                        at /home/krzysztof/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272
                         - _ZN3std6thread7Builder16spawn_unchecked_28_$u7b$$u7b$closure$u7d$$u7d$28_$u7b$$u7b$closure$u7d$$u7d$17h93e16fb0d33e6c17E
                        at /home/krzysztof/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:564
                         - _ZN3std3sys9backtrace28__rust_begin_short_backtrace17he6de03384b55408fE
                        at /home/krzysztof/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:152
                         - _ZN23background_hang_monitor23background_hang_monitor19HangMonitorRegister4init28_$u7b$$u7b$closure$u7d$$u7d$17he7d82fb6be68405bE
                        at /home/krzysztof/devel/servo/components/background_hang_monitor/background_hang_monitor.rs:61
                         - _ZN23background_hang_monitor23background_hang_monitor27BackgroundHangMonitorWorker3run17h8f2edb66775818dcE
                        at /home/krzysztof/devel/servo/components/background_hang_monitor/background_hang_monitor.rs:479
                         - _ZN23background_hang_monitor23background_hang_monitor27BackgroundHangMonitorWorker33perform_a_hang_monitor_checkpoint17he0cbe70adb93238aE
                        at /home/krzysztof/devel/servo/components/background_hang_monitor/background_hang_monitor.rs:561
                         - _ZN114_$LT$background_hang_monitor..sampler_linux..LinuxSampler$u20$as$u20$background_hang_monitor..sampler..Sampler$GT$25suspend_and_sample_thread17h194d42f90c1d92ffE
                        at /home/krzysztof/devel/servo/components/background_hang_monitor/sampler_linux.rs:172
                         - _ZN9backtrace9backtrace9libunwind5trace17h4b1b880a458591ceE
                        at /home/krzysztof/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.75/src/backtrace/libunwind.rs:117
                         - _ZN9backtrace9backtrace20trace_unsynchronized17h9a78f20e0dd5b33eE
                        at /home/krzysztof/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.75/src/backtrace/mod.rs:66
test test_hang_monitoring ... ok
test test_hang_monitoring_exit_signal4 ... ok
test test_hang_monitoring_unregister ... ok
test test_hang_monitoring_exit_signal3 ... ok
test test_hang_monitoring_exit_signal2 ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 3.92s
```

Not sure why the names are mangled or if they have been before...but we do get *a* stack trace.

~~Edit: I don't know why exactly, but I can't seem to go back in history to test the code before I got rid of unwind-sys. I get linker errors now even though libunwind-dev is installed on my system.~~

Scratch that, it was entirely self-inflicted (modified the unwind-sys build script in cargo's cache).

**Comment by CarePackage17** [comment]
Here's the output from before I made my changes, using unwind-sys:
```
running 6 tests
profile is some:
HangProfile backtrace:
                         - clone3
                        at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
                         - start_thread
                        at ./nptl/pthread_create.c:447
                         - _ZN90_$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$9call_once17h2649f14f1b1c150dE
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/alloc/src/boxed.rs:1993
                         - _ZN90_$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$9call_once17hb2ade58cb34e1bc4E
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/alloc/src/boxed.rs:1993
                         - _ZN3std3sys3pal4unix6thread6Thread3new12thread_start17ha07e360225fa3528E
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/sys/pal/unix/thread.rs:106
                         - _ZN3std6thread7Builder16spawn_unchecked_28_$u7b$$u7b$closure$u7d$$u7d$28_$u7b$$u7b$closure$u7d$$u7d$17h5738f3abb9603fe6E
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/thread/mod.rs:564
                         - _ZN115_$LT$core..panic..unwind_safe..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$9call_once17h5e9f4b56e45e8108E
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/panic/unwind_safe.rs:272
                         - _ZN3std9panicking3try7do_call17ha36db853b2f34e23E
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panicking.rs:584
                         - _ZN3std9panicking3try17h57e1aa33a0efb1beE
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panicking.rs:547
                         - _ZN3std5panic12catch_unwind17hdb71a6103024936eE
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panic.rs:358
                         - _ZN3std6thread7Builder16spawn_unchecked_28_$u7b$$u7b$closure$u7d$$u7d$17h8caa22218f423ab1E
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/thread/mod.rs:562
                         - _ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17hb3b44780e9c053e5E
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/ops/function.rs:250
                         - _ZN4test8run_test28_$u7b$$u7b$closure$u7d$$u7d$17h3d537cdce8ec5816E
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/test/src/lib.rs:606
                         - _ZN3std3sys9backtrace28__rust_begin_short_backtrace17hb51d9a6c67ec382dE
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/sys/backtrace.rs:152
                         - _ZN4test19run_test_in_process28_$u7b$$u7b$closure$u7d$$u7d$17h2580047890abbefeE
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/test/src/lib.rs:655
                         - _ZN115_$LT$core..panic..unwind_safe..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$9call_once17h936f8c89d0a99c40E
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/panic/unwind_safe.rs:272
                         - _ZN3std9panicking3try7do_call17h868682cc368697f9E
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panicking.rs:584
                         - _ZN3std9panicking3try17h0356ffc38cbb5501E
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panicking.rs:547
                         - _ZN3std5panic12catch_unwind17h74edf102a3082536E
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panic.rs:358
                         - _ZN4test19run_test_in_process17hc27d69576b7224e4E
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/test/src/lib.rs:655
                         - _ZN4test8run_test28_$u7b$$u7b$closure$u7d$$u7d$17h9f3bfaf910429adbE
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/test/src/lib.rs:576
                         - _ZN4core3ops8function6FnOnce9call_once17h8acc80b5a33ff319E
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/ops/function.rs:250
                         - _ZN4test28__rust_begin_short_backtrace17h52b6da716ad42b7dE
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/test/src/lib.rs:632
                         - _ZN4core3ops8function6FnOnce9call_once17ha81019ba8660f435E
                        at /home/krzysztof/.rustup/toolchains/1.85.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
                         - _ZN18hang_monitor_tests20test_hang_monitoring28_$u7b$$u7b$closure$u7d$$u7d$17h8d13367c2662c09bE
                        at /home/krzysztof/devel/servo/components/background_hang_monitor/tests/hang_monitor_tests.rs:23
                         - _ZN18hang_monitor_tests20test_hang_monitoring17hf85446fad6d2d67eE
                        at /home/krzysztof/devel/servo/components/background_hang_monitor/tests/hang_monitor_tests.rs:59
                         - _ZN3std3sys3pal4unix6thread6Thread5sleep17ha0d179b377be6e65E
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/sys/pal/unix/thread.rs:265
                         - _ZN3std6thread5sleep17h0b60591235df53baE
                        at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/thread/mod.rs:892
                         - __GI___nanosleep
                        at ./posix/../sysdeps/unix/sysv/linux/nanosleep.c:25
                         - __GI___clock_nanosleep
                        at ./time/../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
test test_hang_monitoring ... ok
test test_hang_monitoring_exit_signal2 ... ok
test test_hang_monitoring_exit_signal3 ... ok
test test_hang_monitoring_exit_signal1 ... ok
test test_hang_monitoring_unregister ... ok
test test_hang_monitoring_exit_signal4 ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 3.89s

```

For posterity, the command I used was `cargo test --features background_hang_monitor/sampler --package background_hang_monitor  -- --nocapture`

**Review by jdm — APPROVED** [review]
Lovely! Thanks for verifying that the new implementation is working as expected.

File: components/background_hang_monitor/sampler_linux.rs [hunk 1]
```diff
@@ -209,33 +167,17 @@ impl Sampler for LinuxSampler {
...
-                Ok(native_stack)
-            } else {
-                Err(())
+            let mut native_stack = NativeStack::new();
+            unsafe {
+                backtrace::trace_unsynchronized(|frame| {
+                    let ip = frame.ip();
+                    let sp = frame.sp();
+
+                    //This return value here determines whether we proceed to the next stack frame or not.
```
Comment (mrobinson) [inline components/background_hang_monitor/sampler_linux.rs]: Nit:
```suggestion
                    // This return value here determines whether we proceed to the next stack frame or not.
```

**Review by mrobinson — COMMENTED** [review]
Great change!

File: components/background_hang_monitor/sampler_linux.rs (hunk 1 above)
Comment (CarePackage17) [reply components/background_hang_monitor/sampler_linux.rs]: Fixed :)

Is that something rustfmt/mach fmt could do on its own or would that break too many comments?

Comment (mrobinson) [reply components/background_hang_monitor/sampler_linux.rs]: If `rustfmt` has an option to catch that, I would love to turn it on! after a quick glance at mhttps://github.com/rust-lang/rustfmt/blob/master/Configurations.md, I don't see it though.

Comment (CarePackage17) [reply components/background_hang_monitor/sampler_linux.rs]: Didn't find anything either. There seems to be some demand for it though: https://github.com/rust-lang/rustfmt/issues/3350#issuecomment-2650439135
