### PR TITLE
script: fix set muted on html video element creation

### LINKED ISSUE #38448: Media: Video Element still have sound when setting `muted` attribute on video element.
**Describe the bug:**
Video element with `muted` attribute appended will still have sound when start playing.

**To Reproduce:**
Open below webpage:
```html
 <video id="video" src="https://cdn.jsdelivr.net/npm/big-buck-bunny-1080p@0.0.6/video.mp4" muted>
 <button id="play-btn">Play</button>
<script>
    const video = document.getElementById("video");
    playBtn.onclick = () => {
            if (video.paused) {
                video.play();
            } else {
                video.pause();
            }
        }
</script>
```
Once loaded, hit play button, the playing element will still have sound.

**Platform:**
Windows 11

### PR DESCRIPTION
**Pull request by rayguo17**
Set muted on html video element creation. On `video` element creation, the `set_mute` function will be called before the media player is created, hence the player will still act as not being muted. This PR fix this behaviour by passing `muted` info after player is created as part of `setup_media_player`  process.

Testing: Locally test on Windows11
Fixes: https://github.com/servo/servo/issues/38448

### CODE REVIEW

File: components/script/dom/htmlmediaelement.rs [hunk 1]
```diff
@@ -1447,6 +1447,10 @@ impl HTMLMediaElement {
         );
         let player_id = player.lock().unwrap().get_id();
 
+        if let Err(e) = player.lock().unwrap().set_mute(self.muted.get()) {
```
Comment (jschwe) [inline components/script/dom/htmlmediaelement.rs]: Lets merge this with the line above, so we only need to lock once

Comment (rayguo17) [reply components/script/dom/htmlmediaelement.rs]: Legit

**Comment by rayguo17** [comment]
I thought it will go out of scope, when it is not being used...

File: components/script/dom/htmlmediaelement.rs [hunk 2]
```diff
@@ -1445,7 +1445,12 @@ impl HTMLMediaElement {
             audio_renderer,
             Box::new(window.get_player_context()),
         );
-        let player_id = player.lock().unwrap().get_id();
+
+        let player_mut = player.lock().unwrap();
```
Comment (jschwe) [inline components/script/dom/htmlmediaelement.rs]: Wrap the usage in {} so that the lock guard is dropped as soon as possible. Drop impl will always run a the end of scope.

File: components/script/dom/htmlmediaelement.rs [hunk 3]
```diff
@@ -1445,7 +1445,15 @@ impl HTMLMediaElement {
...
         );
-        let player_id = player.lock().unwrap().get_id();
+        let player_id = {
+            let player_mut = player.lock().unwrap();
+
+            if let Err(e) = player_mut.set_mute(self.muted.get()) {
+                log::warn!("Could not set mute state: {:?}", e);
+            }
+
+            player_mut.get_id()
```
Comment (jschwe) [inline components/script/dom/htmlmediaelement.rs]:
```suggestion
            let player_guard = player.lock().unwrap();

            if let Err(e) = player_guard.set_mute(self.muted.get()) {
                log::warn!("Could not set mute state: {:?}", e);
            }

            player_guard.get_id()
```

We don't typically add `mut` to variable names. In this case I think it's also particularly confusing since `mut` and `mute` only differ by one character. Shadowing the original `player` variable name would also be fine imho.

**Review by jschwe — APPROVED** [review]
