### PR TITLE
script: Properly handle removed iframes in `GlobalScope::get_referrer`

### LINKED ISSUE #32432: Panic when attempting to load a srcdoc iframe that has been removed from the document
**Describe the bug:**
When trying to load www.startpage.com, servo shows a message saying it had crashed.
It complains that iframe should have browsing context.
The logger had this to say:

> iframe should have browsing context (thread Script(1,7), at components/script/dom/globalscope.rs:2427)
> [2024-06-03T10:26:02Z ERROR servoshell] iframe should have browsing context

**To Reproduce:**
Browse to www.startpage.com

**Platform:**
Specify OS, distribution, and hardware platform.
Manjaro Linux XFCE, nvidia gtx 1080.

### PR DESCRIPTION
**Pull request by newmoneybigbucks**
This change, modifies the `GlobalScope::get_referrer` to handle
the case where it cannot get the parent document when dealing
with srcdoc. This can happen when the iframe has been removed
from the parent document before reading htis line of code. In this
case `Referrer::NoReferrer` is returned.

In addition, in order to make the crash test work, changes were
made to the panic hook to trigger a segfault when doing a hard
exit rather than exiting with a non-zero return value. This allows
the WPT test harness to interpret the exit as a crash rather than
a non-crash error exit.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #32432
- [x] There are tests for these changes

### CODE REVIEW

**Comment by jdm** [comment]
Let's start by seeing if any existing tests happen to cover this. If not, we can add a regression test in tests/wpt/tests/mozilla that just verified that the page loads without crashing.

**Comment by newmoneybigbucks** [comment]
> Let's start by seeing if any existing tests happen to cover this. If not, we can add a regression test in tests/wpt/tests/mozilla that just verified that the page loads without crashing.

Ok I'll start checking through them this evening. Ill also do the rebase needed to solve this DCO issue (I forgot to use the -s flag for a commit apparently)

**Comment by mrobinson** [comment]
I have cleaned up these changes a bit and added a test. They are ready for review once more.

File: ports/servoshell/panic_hook.rs [hunk 1]
```diff
@@ -40,7 +41,19 @@ pub(crate) fn panic_hook(info: &PanicInfo) {
     drop(stderr);
 
     if opts::get().hard_fail && !opts::get().multiprocess {
-        std::process::exit(1);
+        // When we are exiting due to a hard-failure mode, we trigger a segfault so that crash
```
Comment (jdm) [inline ports/servoshell/panic_hook.rs:44]: Can we extract this change to a separate PR, since it's not related to fixing the original issue?

File: tests/wpt/tests/html/semantics/embedded-content/the-iframe-element/srcdoc-removed-iframe-crash.html [hunk 2]
```diff
@@ -0,0 +1,11 @@
+<!DOCTYPE html>
+<html>
+    <body>
+        <link rel="author" title="Martin Robinson" href="mrobinson@igalia.com">
```
Comment (jdm) [inline tests/wpt/tests/html/semantics/embedded-content/the-iframe-element/srcdoc-removed-iframe-crash.html:4]: I'm pretty sure you're not mrobinson :)

File: tests/wpt/tests/html/semantics/embedded-content/the-iframe-element/srcdoc-removed-iframe-crash.html [hunk 3]
```diff
@@ -0,0 +1,11 @@
+<!DOCTYPE html>
+<html>
```
Comment (jdm) [inline tests/wpt/tests/html/semantics/embedded-content/the-iframe-element/srcdoc-removed-iframe-crash.html:2]: Let's add a title element like "iframe with srcdoc content that loads after iframe is removed from the document".

**Review by jdm — APPROVED** [review]

File: tests/wpt/tests/html/semantics/embedded-content/the-iframe-element/srcdoc-removed-iframe-crash.html (hunk 2 above)
Comment (mrobinson) [reply tests/wpt/tests/html/semantics/embedded-content/the-iframe-element/srcdoc-removed-iframe-crash.html:4]: Apologies, this was sitting for 3 weeks so I "adopted" it to get it landed. 😅

Comment (jdm) [reply tests/wpt/tests/html/semantics/embedded-content/the-iframe-element/srcdoc-removed-iframe-crash.html:4]: Oh, I totally missed your comment before this? My apologies!

**Review by mrobinson — APPROVED** [review]
