### PR TITLE
Script paint worklets arguments

### LINKED ISSUE #17435: Paint worklets: implement input arguments
Spec: https://drafts.css-houdini.org/css-paint-api/#document-paint-definition-input-argument-syntaxes and https://drafts.css-houdini.org/css-paint-api/#ref-for-document-paint-definition-input-argument-syntaxes-3

Causing a couple of WPT reftest failures:
```
  ▶ FAIL [expected PASS] /css-paint-api/paint-arguments.html
  └   → /css-paint-api/paint-arguments.html 84fa762299f9e10c088a87d1603218505533bb41
/css-paint-api/paint-arguments-ref.html 063e7586ef816b736e273be3d254e2ca09f8632a
Testing 84fa762299f9e10c088a87d1603218505533bb41 == 063e7586ef816b736e273be3d254e2ca09f8632a

  ▶ FAIL [expected PASS] /css-paint-api/paint-function-arguments.html
  └   → /css-paint-api/paint-function-arguments.html cf010e95a3ae0bda2d250c1cfb1004d264f93060
/css-paint-api/paint-function-arguments-ref.html 1f2a1fac239a8c3e14c66d57ef1a7ae1282af791
Testing cf010e95a3ae0bda2d250c1cfb1004d264f93060 == 1f2a1fac239a8c3e14c66d57ef1a7ae1282af791
```

### PR DESCRIPTION
**Pull request by asajeffrey**
Implement paint worklet arguments.

This is a dependent PR, only the last commit is in this PR.
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #17435
- [X] These changes do not require tests because there are tests in the most recent wpt.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17546)

### CODE REVIEW

**Comment by asajeffrey** [comment]
This PR's dependencies merged, so it's ready for review.

File: components/layout/display_list_builder.rs [hunk 1]
```diff
@@ -1173,9 +1174,15 @@ impl FragmentDisplayListBuilding for Fragment {
         let device_pixel_ratio = state.layout_context.style_context.device_pixel_ratio();
         let size_in_au = unbordered_box.size.to_physical(style.writing_mode);
         let size_in_px = TypedSize2D::new(size_in_au.width.to_f32_px(), size_in_au.height.to_f32_px());
+
+        // TODO: less copying.
         let name = paint_worklet.name.clone();
+        let arguments = paint_worklet.arguments.iter()
+            .map(|argument| argument.to_css_string())
```
Comment (emilio) [inline components/layout/display_list_builder.rs]: This is kinda unfortunate... but I guess.

**Review by emilio — APPROVED** [review]

File: components/layout/display_list_builder.rs (hunk 1 above)
Comment (asajeffrey) [inline components/layout/display_list_builder.rs]: Yes, it would be nice to serialize something better than a String, but I'm not sure what that would be :/

**Comment by asajeffrey** [comment]
Squashed. @bors-servo r=emilio
