### PR TITLE
Fix vertical alignment at the root of an IFC

### LINKED ISSUE #31604: vertical-align breaks the alignment of text at the very top of the independent FC
```html
<!DOCTYPE html>
<style>
  .wrapper { border: 1px solid; white-space: nowrap; vertical-align: bottom }
  .ib-content { display: inline-block; height: 50px; width: 50px; background: cyan }
</style>
<div class="wrapper" style="display: inline-block">
  foo
  <span>bar</span>
  <div class="ib-content"></div>
</div>
<div class="wrapper" style="display: inline-table">
  foo
  <span>bar</span>
  <div class="ib-content"></div>
</div>
```

| Firefox | Servo |
| - | - |
|  |  |

It happens for `vertical-align: top` and `bottom`, `middle`  is fine.

The text that is wrapped inside a `<span>` is also fine.

It also works well when the wrapper is not inline-level.

### LINKED ISSUE #31634: effective_vertical_align_for_inline_layout is bogus and needs to be removed
```html
<!DOCTYPE html>
<style>
.container {
  width: 50px;
  vertical-align: top;
  border: solid;
}
</style>
<div class="container" style="display: flow-root">
  <canvas width="50" height="50" style="background: cyan"></canvas>
</div>
<div class="container" style="display: inline-block">
  <canvas width="50" height="50" style="background: cyan"></canvas>
</div>
```

The 1st case is good, the 2nd is bad.

What happens is that, in the IFC established by the containers, they generate the strut using the `effective_vertical_align_for_inline_layout()` of the container! That just happens to work if the container is block-level because we get `baseline`, but if fails for inline-level containers.

We should just use `baseline` in all cases and get rid of `effective_vertical_align_for_inline_layout`.

### PR DESCRIPTION
**Pull request by Loirooriol**
At the root of an inline formatting context, we used its vertical-align in order to compute the strut. That was wrong, since vertical-align on a block container shouldn't affect the contents, it should only affect the alignment of the block container (if it's inline-level) within the parent IFC.

This was only working well if the block container was block-level, since effective_vertical_align_for_inline_layout returned `baseline` for block-level boxes.

Instead of the outer display type, this patch changes the logic to check whether we are at the root of the IFC.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #31604 and #31634

- [X] There are tests for these changes

### CODE REVIEW

File: components/layout_2020/flow/inline.rs [hunk 1]
```diff
@@ -1253,7 +1254,13 @@ impl<'a, 'b> InlineFormattingContextState<'a, 'b> {
         let strut_size = if using_fallback_font {
             // TODO(mrobinson): This value should probably be cached somewhere.
             let container_state = self.current_inline_container_state();
-            let mut block_size = container_state.get_block_size_contribution(&font_metrics);
+            let mut block_size = container_state.get_block_size_contribution(
+                effective_vertical_align(
+                    &container_state.style,
+                    self.inline_box_state_stack.last().map(|c| &c.base),
+                ),
```
Comment (mrobinson) [inline components/layout_2020/flow/inline.rs:1261]: I think this will be slightly easier to read if you save `vertical_align` to a temporary.

**Review by mrobinson — APPROVED** [review]
Thanks for the fix!
