### PR TITLE
Fix HSTS

### LINKED ISSUE #14363: Implement HSTS

### LINKED ISSUE #20120: Servo should only support HTTPS connections, zero without "S"
Hello, 

first, this looks like a great future project, next-gen webbrowser, wow. 

Second, I think it should only support HTTPS connections and not plain HTTP.

If it points to the future. 

only problem: OCSP uses plain HTTP: https://moxie.org/papers/ocsp-attack.pdf

### PR DESCRIPTION
**Pull request by Darkspirit**
The headers crate does not [expose](https://github.com/hyperium/headers/blob/0c42ad8cf56f9af28973c3da71616fa478781fdf/src/common/strict_transport_security.rs#L42) HSTS struct fields. At the moment, it's only usable for HSTS header encoding. An update of the headers crate would require a huge update of http, hyper, hyper_serde, net::decoder as well. Therefore I've copied the `typed_get::<StrictTransportSecurity>` decoding feature  for now, but with exposed struct fields. Let's remove this custom struct with the next hyper upgrade. I tried to prevent needless HSTS database lookups when network.enforce_tls.enabled is set.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #14363, fix #20120.

- [x] There are tests for these changes

### CODE REVIEW

File: components/net/hsts.rs [hunk 1]
```diff
@@ -139,15 +142,160 @@ impl HstsList {
     }
 
     /// Step 10 of https://fetch.spec.whatwg.org/#concept-main-fetch.
```
Comment (asajeffrey) [inline components/net/hsts.rs]: Nit: is this the right spec link?

File: components/net/hsts.rs [hunk 2]
```diff
@@ -139,15 +142,160 @@ impl HstsList {
...
-    pub fn switch_known_hsts_host_domain_url_to_https(&self, url: &mut ServoUrl) {
-        if url.scheme() != "http" {
+    pub fn apply_hsts_rules(&self, url: &mut ServoUrl) {
+        if url.scheme() != "http" && url.scheme() != "ws" {
```
Comment (asajeffrey) [inline components/net/hsts.rs]: Is there a spec link for rewriting ws as wss?

File: components/net/hsts.rs [hunk 3]
```diff
@@ -139,15 +142,160 @@ impl HstsList {
...
             return;
         }
-        if url
-            .domain()
-            .map_or(false, |domain| self.is_host_secure(domain))
+
+        let mut upgrade_scheme = false;
```
Comment (asajeffrey) [inline components/net/hsts.rs]: Nit: can we make this not `mut` by assigning a boolean expression?

File: components/net/hsts.rs [hunk 4]
```diff
@@ -139,15 +142,160 @@ impl HstsList {
...
+                    }
+
+                    self.push(entry);
+                }
+            }
+        }
+    }
+}
+
+// TODO: Remove this when the headers crate exposes STS struct fields
```
Comment (asajeffrey) [inline components/net/hsts.rs]: File an issue for this in the headers repo, and link to it here?

**Review by asajeffrey — APPROVED** [review]
Some nits but otherwise LGTM.

File: components/net/hsts.rs (hunk 1 above)
Comment (Darkspirit) [reply components/net/hsts.rs]: I did not touch this line, but it should be corrected to "Step 2.9".
> Set request’s current URL’s scheme to "https" if all of the following conditions are true:
> * request’s current URL’s scheme is "http"
> * request’s current URL’s host is a domain
>  * Matching request’s current URL’s host per Known HSTS Host Domain Name Matching results in either a superdomain match with an asserted includeSubDomains directive or a congruent match (with or without an asserted includeSubDomains directive). [HSTS]

File: components/net/hsts.rs (hunk 2 above)
Comment (Darkspirit) [reply components/net/hsts.rs]: https://fetch.spec.whatwg.org/#websocket-opening-handshake
> 1. Let requestURL be a copy of url, with its scheme set to "http", if url’s scheme is "ws", and to "https" otherwise.
> 
> This change of scheme is essential to integrate well with fetching. E.g., HSTS would not work without it. There is no real reason for WebSocket to have distinct schemes, it’s a legacy artefact. [HSTS]

The spec recommends to work with a http(s) url, but ws-rs expects to get a ws(s) url. I did not change this aspect.
https://github.com/servo/servo/pull/25404/commits/6dc1f49c6eee059e6bfb8bcbbc53239a7d6f18c0#diff-68b5c651915d8b239e5e3b6c84f02981L194-R252
net_url contains the `ws(s)://` url as it is needed for ws-rs. Instead of converting the upgraded url back to wss in websocket_loader.rs, I kept it clean and upgraded ws to wss.
#14897 seems to be about changing the websocket code to be tighter along the spec.

File: components/net/hsts.rs (hunk 3 above)
Comment (Darkspirit) [reply components/net/hsts.rs]: Should I change the other occurrences of `upgrade_scheme` to `let upgrade_scheme` instead?

File: components/net/hsts.rs (hunk 4 above)
Comment (Darkspirit) [reply components/net/hsts.rs]: https://github.com/hyperium/headers/issues/61

File: components/net/hsts.rs (hunk 2 above)
Comment (asajeffrey) [reply components/net/hsts.rs]: Can you add that link (and the discussion about ws urls) to your PR?

File: components/net/hsts.rs (hunk 3 above)
Comment (asajeffrey) [reply components/net/hsts.rs]: No, just initialize `upgrade_scheme` to be the "right" value, rather than initializing it to be false then updating it.

File: components/net/hsts.rs (hunk 4 above)
Comment (asajeffrey) [reply components/net/hsts.rs]: Thanks!

File: components/net/hsts.rs (hunk 2 above)
Comment (Darkspirit) [reply components/net/hsts.rs]: Added here: https://github.com/servo/servo/pull/25404/files#diff-68b5c651915d8b239e5e3b6c84f02981R202

File: components/net/hsts.rs (hunk 4 above)
Comment (asajeffrey) [reply components/net/hsts.rs]: Can you add a link to the hyper issue?

File: components/net/http_loader.rs [hunk 5]
```diff
@@ -1564,9 +1564,10 @@ fn http_network_fetch(
 
     // Substep 2
 
-    // TODO Determine if response was retrieved over HTTPS
-    // TODO Servo needs to decide what ciphers are to be treated as "deprecated"
```
Comment (Darkspirit) [inline components/net/http_loader.rs]: (I removed this comment because deprecated ciphers have been removed from Servo to align with the deprecation process of other browsers.)

File: components/net/hsts.rs (hunk 4 above)
Comment (Darkspirit) [reply components/net/hsts.rs]: Done, and I will create a PR to add getter methods.

File: components/net/http_loader.rs (hunk 5 above)
Comment (asajeffrey) [reply components/net/http_loader.rs]: 👍

**Comment by asajeffrey** [comment]
OK, thanks for dealing with all my niggles! @bors-servo r+

**Comment by jdm** [comment]
@bors-servo retry
* #25459

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Comment by jdm** [comment]
@bors-servo retry
* our old friend ipc-channel on linux
