### PR TITLE
servoshell: Respond resize with authentic result and Adjust minimum window size

### LINKED ISSUE #37804: [WebDriver Task] Window Size related commands gives inaccurate result
Creating this to track progress. I found these bugs by reading code & doing experiment.

**Describe the bug:**

- [x] [Get window rect](https://w3c.github.io/webdriver/#get-window-rect) always returns entire screen dimension because we wrongly use `fn screen_geometry`.
- [x] We always return {x:0, y:0}. We can implement this properly.
- [x] [Set window Rect](https://w3c.github.io/webdriver/#set-window-rect) sets only the inner size, regardless of the toolbar height.
- [x] All operations should done w.r.t. CSS pixel instead of Device pixel, according to spec.
- [x] [Set window Rect](https://w3c.github.io/webdriver/#set-window-rect) right now only set window size but not position.
- [x] Should not use `toolbar_height` to calculate window size. This will always overshoot.
- [x] Add position for Headless window. Right now, it's always (0, 0).
- [ ] [Set window Rect](https://w3c.github.io/webdriver/#set-window-rect) always assumes the resize is successful and returns the requested size. 

**To Reproduce:**
1. `./mach run -r`
2. Send https request to [create session](https://w3c.github.io/webdriver/#new-session) and [get window rect](https://w3c.github.io/webdriver/#get-window-rect)

**Platform:**
Windows. But I believe Mac/Linux also broken in the same way based on code.

### PR DESCRIPTION
**Pull request by yezhizhen**
- We no longer pretend that resize is always successful and simplify the result computation. 
- Adjust minimum window size to match other browsers and the test expectation.
- Restrict some unnecessary access specifier.

Testing: ` ./mach test-wpt -r "tests\wpt\tests\webdriver\tests\classic\set_window_rect\set.py" --log-raw "D:\servo test log\set.txt" --product servodriver  {--headless}`
Fixes: #37804 as Task 8 is last task.

### CODE REVIEW

**Comment by yezhizhen** [comment]
image
Some result for headed window after setting size to 10*10. `reply_rect` is our previous response, which just returns requested size. The second one is true size due to our restriction on inner size, which we're using now.

**Review by jdm — APPROVED** [review]
Nice simplification!

File: ports/servoshell/desktop/headed_window.rs [hunk 1]
```diff
@@ -772,8 +775,11 @@ impl WindowPortsMethods for Window {
         // Prevent the inner area from being 0 pixels wide or tall
         // this prevents a crash in the compositor due to invalid surface size
         self.winit_window.set_min_inner_size(Some(PhysicalSize::new(
-            1.0,
-            1.0 + (self.toolbar_height() * self.hidpi_scale_factor()).0,
+            MIN_INNER_WIDTH,
+            i32::max(
+                MIN_INNER_HEIGHT,
+                (self.toolbar_height() * self.hidpi_scale_factor()).0 as i32,
```
Comment (mrobinson) [inline ports/servoshell/desktop/headed_window.rs:781]: For the future, this can also be expressed more idiomatically like this:

`MIN_INNER_HEIGHT.min((self.toolbar_height() * self.hidpi_scale_factor()).0 as i32)`
