### PR TITLE
fix: add source browsing context to `Request` and HTTP credentials prompt

### LINKED ISSUE #34796: Send `EmbedderMsg::Prompt` > `PromptDefinition::Credentials` with `WebViewId`
**Describe the bug:**
https://github.com/servo/servo/pull/34620
https://github.com/servo/servo/pull/34620#discussion_r1899360829

#34620, servo added `PromptDefinition::Credentials` to handle HTTP Basic Authentication

In [`prompt_user_for_credentials`](https://github.com/arthmis/servo/blob/c0991de649d0b1fc7a01853965462a875a68d187/components/net/http_loader.rs#L1763-L1784), it sends a `EmbedderMsg::Prompt` event without the `WebViewId`. The client-side needs to know which webview requests the authentication, so the prompt will only show in that webview. (only show in the tab).

**To Reproduce:**
Can test with: https://httpbin.org/basic-auth/user/passwd

### PR DESCRIPTION
**Pull request by pewsheen**
This PR could be an approach to provide source browsing context when initiating navigation to a website by setting the `target_browsing_context` to the `Request` struct.

When the embedder receives `EmbedderMsg::Prompt(PromptDefinition::Credentials)`, it knows the prompt belongs to which browsing context and shows on the context only.

To validate:
- Add line to print event's webview ID to verify it brings source WebViewId when initiating a HTTP authentication Basic
https://github.com/servo/servo/blob/59c7ac680ee7cd4eba2c9adb119dbcaf69f029cd/ports/servoshell/desktop/webview.rs#L760
```rust=
println!("webivew_id: {:?}", webview_id);
```
- We can test with the link https://httpbin.org/basic-auth/user/passwd
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #34796 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

File: components/net/http_loader.rs [hunk 1]
```diff
@@ -1762,13 +1767,14 @@ impl Drop for ResponseEndTimer {
 
 fn prompt_user_for_credentials(
     embedder_proxy: &Mutex<EmbedderProxy>,
+    source_top_ctx_id: Option<TopLevelBrowsingContextId>,
```
Comment (mrobinson) [inline components/net/http_loader.rs:1770]:
```suggestion
    top_level_browsing_context_id: Option<TopLevelBrowsingContextId>,
```

**Review by mrobinson — APPROVED** [review]
This seems like a good start. All prompts should be associated with Webviews eventually.

File: components/script/fetch.rs [hunk 2]
```diff
@@ -123,6 +123,7 @@ fn request_init_from_request(request: NetTraitsRequest) -> RequestBuilder {
         referrer: request.referrer.clone(),
         referrer_policy: request.referrer_policy,
         pipeline_id: request.pipeline_id,
+        target_browsing_context: request.target_browsing_context,
```
Comment (mrobinson) [inline components/script/fetch.rs:126]:
```suggestion
        target_browsing_context_id: request.target_browsing_context,
```

File: components/shared/net/request.rs [hunk 3]
```diff
@@ -267,6 +267,7 @@ pub struct RequestBuilder {
     pub referrer: Referrer,
     pub referrer_policy: ReferrerPolicy,
     pub pipeline_id: Option<PipelineId>,
+    pub target_browsing_context: Option<TopLevelBrowsingContextId>,
```
Comment (mrobinson) [inline components/shared/net/request.rs:270]:
```suggestion
    pub target_browsing_context_id: Option<TopLevelBrowsingContextId>,
```

File: components/shared/net/request.rs [hunk 4]
```diff
@@ -382,6 +384,14 @@ impl RequestBuilder {
         self
     }
 
+    pub fn target_browsing_context(
```
Comment (mrobinson) [inline components/shared/net/request.rs:387]:
```suggestion
    pub fn target_browsing_context_id(
```

File: components/constellation/constellation.rs [hunk 5]
```diff
@@ -3209,9 +3214,12 @@ where
     fn handle_navigate_request(
         &self,
         id: PipelineId,
+        top_level_browsing_context_id: TopLevelBrowsingContextId,
         request_builder: RequestBuilder,
         cancel_chan: IpcReceiver<()>,
     ) {
+        let request_builder =
+            request_builder.target_browsing_context(Some(top_level_browsing_context_id));
```
Comment (mrobinson) [inline components/constellation/constellation.rs:3222]: So I'm a bit concerned, because this means that resource loading (images, fonts, etc) are not associated with a WebView, but they probably should be. This requires a more thorough change though -- likely the TopLevelBrowsingContextId needs to be passed in as part of the `RequestBuilder::new` method.

**Review by mrobinson — APPROVED** [review]
I have a few nits, but this seems like a good start. Ideally all requests should be associated with their `WebView` though and not just navigations.

File: components/constellation/constellation.rs (hunk 5 above)
Comment (pewsheen) [reply components/constellation/constellation.rs]: After more digging, I wonder if we should use `TopLevelBrowsingContextId` or `BrowsingContextId` here since we might load an iframe context. (or maybe both?)

Comment (mrobinson) [reply components/constellation/constellation.rs]: In the end, both, likely make sense, but `TopLevelBrowsingContextId` is what we need for now:
 - `TopLevelBrowsingContextId`: the WebView which can be used to associate the prompt dialog with a particular web view.
 - `BrowsingContextId`: the frame, which the embedder might want to have frame specific behavior. I'm not sure if we have a strong concept of a `Frame` in the API yet.

File: components/script/script_thread.rs [hunk 6]
```diff
@@ -3386,13 +3386,15 @@ impl ScriptThread {
...
         let id = incomplete.pipeline_id;
+        let top_level_browsing_context_id = incomplete.top_level_browsing_context_id;
         let req_init = RequestBuilder::new(load_data.url.clone(), load_data.referrer)
             .method(load_data.method)
             .destination(Destination::Document)
             .mode(RequestMode::Navigate)
             .credentials_mode(CredentialsMode::Include)
             .use_url_credentials(true)
             .pipeline_id(Some(id))
+            .target_browsing_context_id(Some(top_level_browsing_context_id))
```
Comment (pewsheen) [inline components/script/script_thread.rs:3397]: I moved the `target_browsing_context_id` setting here. It should be more appropriate.
