### PR TITLE
dom: Avoid crashing on empty favicon `href` attribute

### LINKED ISSUE #41047: Crash: `assertion failed: !options.href.is_empty() || options.source_set.is_some()` when visiting http://chiptune.com/
**Describe the bug:**
http://chiptune.com/ is a website with a characteristic interface that uses JS to imitate the Amiga Workbench. However, simply trying to load it causes a crash.

Image

**To Reproduce:**
Visit  http://chiptune.com/ (Note this is *NOT* https). I don't believe http is the issue itself because other http-only sites like http://www.javaonthebrain.com/ seem to load fine.

**Platform:**
Windows 10, latest Servo.

### PR DESCRIPTION
**Pull request by webbeef**
Add a check to handle_favicon_url() similar to the ones done in similar functions: handle_stylesheet_url() and fetch_and_process_prefetch_link()

Testing: Check that loading http://chiptune.com/  doesn't crash anymore.
Fixes: https://github.com/servo/servo/issues/41047

### CODE REVIEW

File: components/script/dom/html/htmllinkelement.rs
Comment (simonwuelker) [inline components/script/dom/html/htmllinkelement.rs:633]: shouldn't this return here catch an empty string? Or does the empty string somehow parse to a valid url?

And if it doesn't, please use `href` instead of `self.Href()` here.

Comment (webbeef) [reply components/script/dom/html/htmllinkelement.rs:633]: `self.Href()` does the extra work of resolving to an absolute URL, so when `href` is empty it returns the document url and parses successfully. So I think this part should not change, since we want the absolute url that `self.Href()` produces.

Comment (simonwuelker) [reply components/script/dom/html/htmllinkelement.rs:633]: Makes sense, thanks!

Can you add a regression test?

Comment (webbeef) [reply components/script/dom/html/htmllinkelement.rs:633]: I added a crash test in `tests/wpt/mozilla/tests/mozilla/link_empty_href_crash.html` . Not sure if this is the right location!

File: tests/wpt/tests/html/links/icon/empty-href-crash.html [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+<script src="/resources/testharness.js"></script>
+<script src="/resources/testharnessreport.js"></script>
+<script>
+test(function() {
+  var link = document.createElement("link");
+  link.setAttribute("rel", "icon");
+  link.setAttribute("href", "");
+  document.head.appendChild(link);
+}, "Doesn't crash when setting an empty href link");
+</script>
```
Comment (mrobinson) [inline tests/wpt/tests/html/links/icon/empty-href-crash.html]: It looks like this test could be upstreamed into the WPT repository.

Comment (webbeef) [reply tests/wpt/tests/html/links/icon/empty-href-crash.html]: Ok - is that fine to move it under `tests/wpt/tests/dom/link_empty_href_crash.html` instead?

Comment (simonwuelker) [reply tests/wpt/tests/html/links/icon/empty-href-crash.html]: `<link>` elements are a HTML concept, so `html` is the better directory for WPT. How about `tests/wpt/tests/html/links/icon/empty-href-crash.html`. I think the filename has to end with `-crash` to make the harness recognize it as a crashtest.

Comment (jdm) [reply tests/wpt/tests/html/links/icon/empty-href-crash.html]: I suggest https://github.com/servo/servo/tree/main/tests/wpt/tests/html/links/icon

Comment (webbeef) [reply tests/wpt/tests/html/links/icon/empty-href-crash.html]: done!

Comment (webbeef) [reply tests/wpt/tests/html/links/icon/empty-href-crash.html]: done in latest commit

**Review by mrobinson — APPROVED** [review]
