### PR TITLE
script: Support legacy "background" presentational hint on more elements

### LINKED ISSUE #41269: Support deprecated `background` property on table elements
**Describe the bug:**
`background` is a deprecated table attr similar to `bgcolor`. It is ***not listed on MDN***, however, *both Firefox and Chrome support it* and there are extant pages with it. Here is one that uses `background` with `<td>` elements: https://www.bgreco.net/kidradd.htm

Chrome:
Image
Servo:
Image

NOTE: According to https://html.spec.whatwg.org/multipage/obsolete.html#obsolete, the complete set of elements it is available on is "body, table, thead, tbody, tfoot, tr, td, and th elements".

**To Reproduce:**
Test case
```
<!doctype html>
<table background="https://fairysvoice.net/thelostpanels/35/bannertriptych.png"><tr><td style='width:1032px; height:122px'></td></tr></table>
<table>
<tr background="https://fairysvoice.net/thelostpanels/35/bannertriptych.png" ><td style='width:1032px; height:122px'></td></table>
<table>
<td background="https://fairysvoice.net/thelostpanels/35/bannertriptych.png" style='width:1032px; height:122px'></td>
```
Firefox:
Image
Servo:
Image

**Platform:**
Windows 10

### PR DESCRIPTION
**Pull request by simonwuelker**
Testing: New tests start to pass
Fixes https://github.com/servo/servo/issues/41269

### CODE REVIEW

**Comment by simonwuelker** [comment]
That test passes locally. But it seems unrelated, so let's ignore it.

File: components/script/dom/html/htmlelement.rs [hunk 1]
```diff
@@ -1132,6 +1132,23 @@ impl HTMLElement {
         // Step 4:Remove next.
         next.remove_self(can_gc);
     }
+
+    pub(crate) fn is_affected_by_legacy_background_presentational_hint(&self) -> bool {
```
Comment (TimvdLippe) [inline components/script/dom/html/htmlelement.rs]: Nit: move this into element so you can dedupe the implementation in `Element::synthesize_presentational_hints_for_legacy_attributes`

**Review by TimvdLippe — APPROVED** [review]

File: components/script/dom/html/htmlelement.rs (hunk 1 above)
Comment (simonwuelker) [reply components/script/dom/html/htmlelement.rs]: in `synthesize_presentational_hints_for_legacy_attributes` we are operating on an `LayoutDom<'_, Element>`, not an `Element`. So deduplicating the impls would be possible, but would require a bunch of boilerplate code which I don't think is worth it.

File: components/script/dom/html/htmlelement.rs [hunk 2]
```diff
@@ -1268,10 +1285,34 @@ impl VirtualMethods for HTMLElement {
         }
     }
 
+    fn attribute_affects_presentational_hints(&self, attr: &Attr) -> bool {
+        if attr.local_name() == &local_name!("bgcolor") {
```
Comment (tharkum) [inline components/script/dom/html/htmlelement.rs]: Why `bgcolor` didn't mentioned in PR description/title and you added it as hint for any HTML element, is it right?

File: components/script/dom/html/htmlelement.rs (hunk 1 above)
Comment (tharkum) [reply components/script/dom/html/htmlelement.rs]: Here I'm agree with Tim, better to add changes to associated HTML elements - I did the same for `width` and `height` attributes in the following PR (https://github.com/servo/servo/pull/39606/changes#diff-0233e86f016f62527879692f7cc768b31974e2a1dc831224a87cf86c2bcef99cR196).

Comment (TimvdLippe) [reply components/script/dom/html/htmlelement.rs]: Maybe I am missing something, but my thought was that we add a method that takes a namespace and localname and operates on that. Are the namespaces and localnames of these types incompatible?

Comment (simonwuelker) [reply components/script/dom/html/htmlelement.rs]: > Maybe I am missing something, but my thought was that we add a method that takes a namespace and localname and operates on that. Are the namespaces and localnames of these types incompatible?

They are not, I'll make it a free function later today.

File: components/script/dom/html/htmlelement.rs (hunk 2 above)
Comment (simonwuelker) [reply components/script/dom/html/htmlelement.rs]: Removed.

**Review by TimvdLippe — APPROVED** [review]
