### PR TITLE
ISSUE-20455: introduce stronger types for textinput indexing

### LINKED ISSUE #20455: Introduce stronger types in text input code
We have many instances of `usize` values in textinput.rs that either represent a number of UTF-8 codepoints or UTF-16 codepoints, or a number of bytes, and we end up comparing them in various invalid ways. We should introduce two new types described in [this comment](https://github.com/servo/servo/pull/20208#issuecomment-371979102), but retain the existing behaviour. If (when) we encounter a place where we are incorrectly mixing types, we should add a function like `dangerous_add_utf8_to_byte` with a FIXME pointing out that the behaviour is incorrect. This will make it easier to see what needs to be fixed in the future, as well as prevent introducing further mistakes.

@sarkhanbayramli would you be interested in doing this work?

### PR DESCRIPTION
**Pull request by tdelacour**
Added two new types:
- ByteOffset
- UTF16CodeUnitOffset

I've replaced any instance of `usize` that would be better represented by one or the other of these. I also updated any downstream code, including the unit tests for `textinput.rs`. Along the way, I tried to add or edit comments to better reflect my understanding of this file - happy to revisit if I have misrepresented anything.

I did not end up finding any places where types were very obviously being mixed, as the issue description suggested I should do... LMK if I should re-audit the file for that (might need a bit of guidance)!

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #20455 (GitHub issue number if applicable)

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because ___

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23272)

### CODE REVIEW

File: components/script/textinput.rs [hunk 1]
```diff
@@ -137,28 +232,30 @@ pub const CMD_OR_CONTROL: Modifiers = Modifiers::META;
 #[cfg(not(target_os = "macos"))]
 pub const CMD_OR_CONTROL: Modifiers = Modifiers::CONTROL;
 
+// FIXME this function does not behave as described (if given string has fewer than n
```
Comment (tdelacour) [inline components/script/textinput.rs]: happy to change this as a drive-by. Wasn't sure if I should be affected end behavior for this issue or not.

**Comment by jdm** [comment]
@simonsapin Review ping!

**Comment by tdelacour** [comment]
merged master to keep things up to date

**Comment by jdm** [comment]
@simonsapin Review ping!

File: components/script/textinput.rs [hunk 2]
```diff
@@ -29,6 +29,98 @@ pub enum SelectionDirection {
...
+    fn add(self, other: ByteOffset) -> ByteOffset {
+        ByteOffset(self.0 + other.0)
+    }
+}
+
+impl Sub for ByteOffset {
+    type Output = ByteOffset;
+
+    fn sub(self, other: ByteOffset) -> ByteOffset {
+        if self > other {
```
[the remark this answers is not in the document]
Comment (SimonSapin) [reply components/script/textinput.rs]: That is, if saturating to zero is indeed the desired behavior. If calls to this were previously using the `-` operator with `usize`, it’s a behavior change.

File: components/script/textinput.rs [hunk 3]
```diff
@@ -370,27 +469,30 @@ impl<T: ClipboardProvider> TextInput<T> {
...
         } else {
-            usize::MAX
+            UTF16CodeUnits(usize::MAX)
         };
 
-        let last_char_index = len_of_first_n_code_units(&*insert, allowed_to_insert_count);
-        let chars_to_insert = &insert[..last_char_index];
+        let ByteOffset(last_char_index) =
+            len_of_first_n_code_units(&*insert, allowed_to_insert_count);
+        let bytes_to_insert = &insert[..last_char_index];
```
Comment (SimonSapin) [inline components/script/textinput.rs]: Nit: neither `chars_to_insert` nor `bytes_to_insert` to quite the right name for a variable of type `&str`. (Bytes would be `&[u8]`.) Maybe just `to_insert`?

File: components/script/textinput.rs [hunk 4]
```diff
@@ -462,10 +568,12 @@ impl<T: ClipboardProvider> TextInput<T> {
             return;
         }
 
-        let col = self.lines[self.edit_point.line][..self.edit_point.index]
+        let ByteOffset(edit_index) = self.edit_point.index;
+        let col = self.lines[self.edit_point.line][..edit_index]
             .chars()
             .count();
         self.edit_point.line = target_line as usize;
+        // NOTE: this adjusts to the nearest complete UTF-8 "char", rather than grapheme cluster
```
Comment (SimonSapin) [inline components/script/textinput.rs]: Please replace `UTF-8 "char"` here with `Unicode codepoint`.

File: components/script/textinput.rs [hunk 5]
```diff
@@ -483,43 +591,38 @@ impl<T: ClipboardProvider> TextInput<T> {
...
-                    {
-                        Some(c) => -(c.len() as isize),
-                        None => -1, // Going to the previous line is a "one byte" offset
-                    }
-                },
+            let ByteOffset(current_offset) = self.edit_point.index;
+            let next_ch = match direction {
+                Direction::Forward => current_line[current_offset..].graphemes(true).next(),
+                Direction::Backward => current_line[..current_offset].graphemes(true).next_back(),
+            };
```
Comment (SimonSapin) [inline components/script/textinput.rs]: Nice improvement here 👍

File: components/script/textinput.rs [hunk 6]
```diff
@@ -625,79 +746,82 @@ impl<T: ClipboardProvider> TextInput<T> {
...
         }
-        let shift: isize = {
+        let shift: usize = {
             let current_line = &self.lines[self.edit_point.line];
+            let ByteOffset(current_offset) = self.edit_point.index;
             match direction {
-                Direction::Backward => -(current_line[..self.edit_point.index].len() as isize),
-                Direction::Forward => current_line[self.edit_point.index..].len() as isize,
+                Direction::Backward => current_line[..current_offset].len() as usize,
+                Direction::Forward => current_line[current_offset..].len() as usize,
```
Comment (SimonSapin) [inline components/script/textinput.rs]: Can `as usize` be removed here?

File: components/script/textinput.rs [hunk 7]
```diff
@@ -864,20 +988,20 @@ impl<T: ClipboardProvider> TextInput<T> {
     }
 
     /// The length of the content in bytes.
-    pub fn len(&self) -> usize {
-        self.lines.iter().fold(0, |m, l| {
-            m + l.len() + 1 // + 1 for the '\n'
-        }) - 1
+    pub fn len(&self) -> ByteOffset {
```
Comment (SimonSapin) [inline components/script/textinput.rs]: Consider also renaming this method to `utf8_len`?

File: components/script/textinput.rs [hunk 8]
```diff
@@ -864,20 +988,20 @@ impl<T: ClipboardProvider> TextInput<T> {
...
-        }) - 1
+    /// The total number of code units required to encode the content in utf16.
+    pub fn utf16_len(&self) -> UTF16CodeUnits {
+        self.lines.iter().fold(UTF16CodeUnits::zero(), |m, l| {
+            m + UTF16CodeUnits(l.chars().map(char::len_utf16).sum::<usize>() + 1) // + 1 for the '\n'
+        }) - UTF16CodeUnits::one()
     }
 
-    /// The length of the content in chars.
+    /// The length of the content in UTF-8 chars.
```
Comment (SimonSapin) [inline components/script/textinput.rs]: This is not correct. Rust’s `char` is a *Unicode scalar value* (which is close enough to a *Unicode code point* for our purpose here) and is not any more related to UTF-8 than it is to UTF-16. Please change this to `length of the content in Unicode code points`.

Comment (SimonSapin) [reply components/script/textinput.rs]: https://simonsapin.github.io/wtf-8/ has some more background and terminology for these concepts.

File: components/script/textinput.rs [hunk 9]
```diff
@@ -961,9 +1092,9 @@ impl<T: ClipboardProvider> TextInput<T> {
     }
 
     pub fn set_selection_range(&mut self, start: u32, end: u32, direction: SelectionDirection) {
```
Comment (SimonSapin) [inline components/script/textinput.rs]: Should this method take `ByteOffset` parameters instead of `u32`?

File: components/script/textinput.rs [hunk 10]
```diff
@@ -987,11 +1118,12 @@ impl<T: ClipboardProvider> TextInput<T> {
         self.assert_ok_selection();
     }
 
+    /// Set the edit point index position based off of a given grapheme cluster offset
```
Comment (SimonSapin) [inline components/script/textinput.rs]: This is correct documentation for what this method currently does, but that behavior is buggy. `index` appears to come from here:

https://github.com/servo/servo/blob/36c75c4e5f5a322b5b21137615b9c41e5f8a2427/components/gfx/text/text_run.rs#L369-L385

… which is counting glyphs. Grapheme count only sometimes matches glyph count.

Fixing this is probably a larger change than should go into this already non-trivial PR.

**Review by SimonSapin — COMMENTED** [review]
Sorry for the delay!

**Comment by SimonSapin** [comment]
In case you also want to look into that, it looks like a method like this would be useful in a number of places in this PR:

```rust
trait StrExt {
    fn utf8_len(&self) -> ByteOffset;
}
impl StrExt for str {
    fn utf8_len(&self) -> ByteOffset { ByteOffset(self.len()) }
}
```

File: components/script/textinput.rs (hunk 8 above)
Comment (tdelacour) [reply components/script/textinput.rs]: got it, thanks for the clarification!

File: components/script/textinput.rs (hunk 9 above)
Comment (tdelacour) [reply components/script/textinput.rs]: I did consider this, but was unsure to what extent I should mess with upstream callers. Looks like the only immediate caller is here: https://github.com/tdelacour/servo/blob/master/components/script/dom/textcontrol.rs#L207. Would it be reasonable to just update this call to wrap `start` / `end` in `UTF8Bytes`? Going farther upstream is starts to get a bit messy, but I don't mind threading the type in higher up if you think that would be better in the long run!

File: components/script/textinput.rs (hunk 10 above)
Comment (tdelacour) [reply components/script/textinput.rs]: oh huh. Should I add a note to that effect? Can also open an issue.

File: components/script/textinput.rs [hunk 11]
```diff
@@ -29,6 +29,98 @@ pub enum SelectionDirection {
...
+impl AddAssign for ByteOffset {
+    fn add_assign(&mut self, other: ByteOffset) {
+        *self = ByteOffset(self.0 + other.0)
+    }
+}
+
+impl SubAssign for ByteOffset {
+    fn sub_assign(&mut self, other: ByteOffset) {
+        if *self > other {
+            *self = ByteOffset(self.0 + other.0)
```
[the remark this answers is not in the document]
Comment (tdelacour) [reply components/script/textinput.rs]: erm... oops

File: components/script/textinput.rs (hunk 9 above)
Comment (SimonSapin) [reply components/script/textinput.rs]: Ok. Let’s land the changes already here first, then if you’re interested you could work on another PR.

File: components/script/textinput.rs (hunk 10 above)
Comment (SimonSapin) [reply components/script/textinput.rs]: I’ve filed https://github.com/servo/servo/issues/23399.

File: components/script/textinput.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (tdelacour) [reply components/script/textinput.rs]: so, the reason I saturated to zero is really just this line: https://github.com/tdelacour/servo/blob/master/components/script/textinput.rs#L580

In the case where the cursor is at the very beginning of the text input and the adjustment is "Backwards", the cursor has nowhere to go and should stay at position `zero`. The existing code uses type conversions and a `max` function to achieve this. To keep things simpler with the new types and avoid type conversions, I prevented the subtraction from going below 0.

I _think_ saturating to zero is a useful behavior change (and it shouldn't affect anything external to this file), especially with your suggestion, which should make it much clearer what is happening. But I can definitely re-work this if you'd rather we not do that!

**Comment by tdelacour** [comment]
ok @SimonSapin, ready for another look!

File: components/script/textinput.rs (hunk 1 above)
Comment (SimonSapin) [reply components/script/textinput.rs]: Sorry I wasn’t clear by commenting about this here rather than at the top level. Avoiding to modify the existing commit was intended for any change after the first review pass, not just this one.

Comment (tdelacour) [reply components/script/textinput.rs]: So I should revert the fix for now and add it back in once this commit has been approved? Or maybe an entirely different PR?

**Comment by SimonSapin** [comment]
> So I should revert the fix for now and add it back in once this commit has been approved? Or maybe an entirely different PR?

No. Now that an amended commit has been pushed, as far as I know it can’t easily be undone.

What I meant is that, when a reviewer asks for changes one a large PR, it’s preferable to avoid using `git rebase`, `git commit --amend`, or any other command that changes the hash of commits that were already pushed (and cause `--force` to be required on the next push). Instead, edit the files and create new commits on top of the existing ones. That way, the reviewer can look at the new changes in isolation from those that have already been reviewed. After the review is approved, rebase or squash as desired.

But don’t worry about it for this PR, I’ll manage :)

**Comment by tdelacour** [comment]
@SimonSapin ohhhhh, got it! Still learning about the workflow, clearly. Making a big mental note for next time - sorry about that!

**Review by SimonSapin — COMMENTED** [review]
I took the liberty of pushing to your branch directly for the last couple of changes.

**Comment by SimonSapin** [comment]
Thanks!

@bors-servo r+

**Comment by tdelacour** [comment]
OK thanks for the help!

**Comment by CYBAI** [comment]
@bors-servo retry

- #23409

**Comment by CYBAI** [comment]
@bors-servo retry

- #23290

**Comment by jdm** [comment]
@bors-servo retry
* #23290
