### PR TITLE
An observer disconnected after a mark must receive the mark

### LINKED ISSUE #18284: An observer disconnected after a mark must receive the mark
The following test from [web-platform-tests/performance-timeline](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/performance-timeline/po-disconnect.any.js) is failing:

```javascript
async_test(function (t) {
    var observer = new PerformanceObserver(
        t.step_func(function(entryList, obs) {
          checkEntries(entryList.getEntries(),
            [{ entryType: "mark", name: "mark1"}]);
          t.done();
        })
      );
    observer.observe({entryTypes: ["mark"]});
    self.performance.mark("mark1");
    observer.disconnect();
    self.performance.mark("mark2");
  }, "An observer disconnected after a mark must receive the mark");
```

We should probably not remove the observer from the list while the [pending_notification_observers_task flag](https://github.com/servo/servo/blob/master/components/script/dom/performance.rs#L170) is set.

### PR DESCRIPTION
**Pull request by pylbrecht**
I worked on top of #18283 as suggested [here](https://github.com/servo/servo/issues/18284#issuecomment-326043873).

r? @ferjm 

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #18284 (github issue number if applicable).

- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18370)

### CODE REVIEW

**Comment by nox** [comment]
Needless to say, this shouldn't land before the PR it's based on lands.

File: components/script/dom/performance.rs [hunk 1]
```diff
@@ -177,6 +177,10 @@ impl Performance {
 
     /// Remove a PerformanceObserver from the list of observers.
     pub fn remove_observer(&self, observer: &DOMPerformanceObserver) {
+        if self.pending_notification_observers_task.get() {
+            self.notify_observers();
```
Comment (ferjm) [inline components/script/dom/performance.rs]: The spec does not mention anything about this case :\ . But I would assume that instead of notifying all observers, we should notify only the one being removed here.

Note that you'll need to make a copy of the observer, just like we do inside [notify_observers](https://github.com/servo/servo/blob/master/components/script/dom/performance.rs#L186) before calling `observer.notify()`.

**Review by ferjm — COMMENTED** [review]
Thank you @pylbrecht! Glad to see more tests passing :)

I think we can improve this a little bit by notifying only the affected observer. Wdyt?

File: components/script/dom/performance.rs (hunk 1 above)
Comment (pylbrecht) [reply components/script/dom/performance.rs]: Alright, I'll fix that. Thanks for your input!

**Review by ferjm — APPROVED** [review]
Looks good. Thank you!
This can land after #18283 lands, with the commits squashed in one.

File: tests/wpt/metadata/performance-timeline/po-disconnect.any.js.ini [hunk 2]
```diff
@@ -1,13 +1,13 @@
 [po-disconnect.any.html]
```
Comment (ferjm) [inline tests/wpt/metadata/performance-timeline/po-disconnect.any.js.ini]: One last step: since all tests are expected to pass, you need to remove this file. Sorry, I didn't notice this before. Thanks!

Comment (pylbrecht) [reply tests/wpt/metadata/performance-timeline/po-disconnect.any.js.ini]: Alright, I'll do that as soon as I'm home.
