### PR TITLE
Fix margin size calculation for TableWrapper

### LINKED ISSUE #12748: Wikipedia page wrong layout
https://en.wikipedia.org/wiki/Template:Multiple_issues 
screenshot

### PR DESCRIPTION
**Pull request by gpoesia**
Fixes inline size calculation for TableWrapper. The table's width was always reaching the inline size equation solver as a specified variable, which was causing the system to be overdetermined when there was a margin specified for the table, and this caused the overflow reported in #12748. The fix consists in handling three cases when the table's width is not specified: if the preferred size of all columns fits, it is returned; if the minimum size does not fit, it is returned instead (it will overflow), otherwise, it is returned as a free variable (that should be solved together with the margin to some value above the minimum width and below the preferred width).

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #12748
- [X] There are tests for these changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13681)

### CODE REVIEW

**Comment by gpoesia** [comment]
It seems there are more cases to handle, the tests are indeed broken. I'll take a look.

**Comment by jdm** [comment]
@gpoesia Is it worth having someone else review the changes yet, or would you like to fix the failing tests first?

**Comment by emilio** [comment]
Note that a lot of the table code is being rewritten in #13870.

**Comment by pcwalton** [comment]
I think it'd be best to rebase this on top of #13870. I'll do that if you'd like.

**Comment by gpoesia** [comment]
@pcwalton Thank you, I think rebasing makes sense. By now that PR was already merged, right? I can just rebase on top of master then. I should be able to debug this this week.

**Comment by jdm** [comment]
Correct!

**Comment by gpoesia** [comment]
I've came back to this. After rebasing, the same situation persists: the test I added fails in master but not with this change; however, other related tests are broken. I'll look into these others.

**Comment by gpoesia** [comment]
I've identified some more cases and updated the PR description to address them. The 2 test failures were fixed. I believe it is ready for review.

File: components/layout/table_wrapper.rs [hunk 1]
```diff
@@ -778,7 +778,13 @@ fn initial_computed_inline_size(block: &mut BlockFlow,
                                                        containing_block_inline_size);
     match inline_size_from_style {
         MaybeAuto::Auto => {
-            MaybeAuto::Specified(min(containing_block_inline_size, preferred_width_of_all_columns))
+            if preferred_width_of_all_columns + table_border_padding <= containing_block_inline_size {
```
Comment (emilio) [inline components/layout/table_wrapper.rs]: I thought that the idea of the preferred width is that nothing should be greater than it.

That being said, table layout is hard, and I'm probably not the best person to review this.

**Comment by jdm** [comment]
@mbrubeck Review ping!

**Comment by mbrubeck** [comment]
@bors-servo r+

* Thanks, and sorry for the delay!

File: components/layout/table_wrapper.rs (hunk 1 above)
Comment (emilio) [inline components/layout/table_wrapper.rs]: Oh, I know why this is correct now, whoops. Wasn't really inspired the day I wrote this.
