### PR TITLE
Fix incremental layout bugs for absolute and cleared elements

### LINKED ISSUE #17307: Incremental layout bug in matter.js demo.
A small 2d physics demo can be found here - https://gist.github.com/glennw/3435b37650405d0cb33a7397c2e27734.

Running it with Servo results in the following output:

bug1

However, if you run with the ```-i``` command line option to disable incremental layout, you see the correct result, which is:

bug2

### PR DESCRIPTION
**Pull request by mbrubeck**
Fixes #17307.  <del>There were two underlying bugs:</del>

* <del>Nodes were not marked dirty when their style attribute changed.</del>

* BaseFlow flags set during flow construction could get out of sync with the element's style if repair_style was called.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #17307
- [x] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17581)

### CODE REVIEW

File: components/script/dom/element.rs [hunk 1]
```diff
@@ -2214,6 +2214,7 @@ impl VirtualMethods for Element {
         match attr.local_name() {
             &local_name!("style") => {
                 // Modifying the `style` attribute might change style.
+                node.dirty(NodeDamage::NodeStyleDamaged);
```
Comment (emilio) [inline components/script/dom/element.rs]: This shouldn't be needed. We handle that already here: https://github.com/servo/servo/blob/master/components/script/dom/document.rs#L2418.

**Review by emilio — CHANGES_REQUESTED** [review]

File: components/layout/flow.rs [hunk 2]
```diff
@@ -1115,6 +1115,24 @@ impl BaseFlow {
...
+        // to get out of date:
+        if self.flags.contains(IS_ABSOLUTELY_POSITIONED) {
+            let logical_position = style.logical_position();
+            self.flags.set(INLINE_POSITION_IS_STATIC,
+                logical_position.inline_start == LengthOrPercentageOrAuto::Auto &&
+                logical_position.inline_end == LengthOrPercentageOrAuto::Auto);
+            self.flags.set(BLOCK_POSITION_IS_STATIC,
+                logical_position.block_start == LengthOrPercentageOrAuto::Auto &&
+                logical_position.block_end == LengthOrPercentageOrAuto::Auto);
+        }
```
Comment (pcwalton) [inline components/layout/flow.rs]: How about making this a new incremental reflow flag, along the lines of `RECONSTRUCT_FLOW` or `REFLOW_OUT_OF_FLOW`?

**Comment by emilio** [comment]
So with this patch:

```diff
diff --git a/components/layout/query.rs b/components/layout/query.rs
index ae7a506124..f1a5747419 100644
--- a/components/layout/query.rs
+++ b/components/layout/query.rs
@@ -824,11 +824,13 @@ fn process_resolved_style_request_internal<'a, N>(requested_node: N,
             iterator.result.map(|r| r.to_css_string()).unwrap_or(String::new())
         },
 
+        /*
         LonghandId::Bottom | LonghandId::Top | LonghandId::Right | LonghandId::Left
         if applies && positioned && style.get_box().display !=
                 display::computed_value::T::none => {
             used_value_for_position_property(layout_el, layout_root, requested_node, longhand_id)
         }
+        */
         LonghandId::Width | LonghandId::Height
         if applies && style.get_box().display !=
                 display::computed_value::T::none => {
```

And printing the computed style:

```
<!DOCTYPE html>
<style>
  #rect {
    position: absolute;
    border: 1px solid red;
    width: 40px;
    height: 40px;
  }
</style>
<div id="rect"></div>
<script>
  var x = 10;
  var tick = function() {
    x += 4;
    var e = document.getElementById("rect");
    e.style.left = x + "px";
    console.log(getComputedStyle(e).left)
    window.requestAnimationFrame(tick);
  }
  requestAnimationFrame(tick);
</script>
```

I see the computed value updated properly, so now the thing is why the flow tree isn't getting properly updated without the `dirty(..)` call.

**Comment by emilio** [comment]
The demo definitely works with this series but removing the first patch, so it should be dropped IMO.

File: components/script/dom/element.rs (hunk 1 above)
Comment (mbrubeck) [inline components/script/dom/element.rs]: Confirmed. I'll drop this change.

File: components/layout/flow.rs (hunk 2 above)
Comment (mbrubeck) [inline components/layout/flow.rs]: Done. This increases the size of RestyleDamage from `u8` to `u16` and adds a bit more code. Let me know if you think it's worth the slight complexity cost.

File: components/layout/flow.rs [hunk 3]
```diff
@@ -1115,6 +1116,30 @@ impl BaseFlow {
...
+    ///
+    /// These flags are initially set during flow construction.  They only need to be updated here
+    /// if they are based on properties that can change triggering `RECONSTRUCT_FLOW`.
+    pub fn update_flags(&mut self, style: &ServoComputedValues) {
+        if !self.restyle_damage.contains(UPDATE_FLOW_FLAGS) {
+            return
+        }
+
+        // For absolutely-positioned flows, changes to top/bottom/left/right can cause these flags
+        // to get out of date:
```
Comment (emilio) [inline components/layout/flow.rs]: Perhaps note that we don't need to update the `IS_ABSOLUTELY_POSITIONED` flag because we reconstruct on position changes?

File: components/layout/flow.rs [hunk 4]
```diff
@@ -1361,6 +1386,7 @@ impl<'a> MutableFlowUtils for &'a mut Flow {
     /// calling them individually, since there is no reason not to perform both operations.
     fn repair_style_and_bubble_inline_sizes(self, style: &::StyleArc<ServoComputedValues>) {
         self.repair_style(style);
+        mut_base(self).update_flags(style);
```
Comment (emilio) [inline components/layout/flow.rs]: (And maybe call the function `update_flags_if_needed`?)

**Review by emilio — APPROVED** [review]
Comments on my side were addressed, looks good to me assuming @pcwalton is fine with `UPDATE_FLOW_FLAGS`.

File: components/layout/flow.rs (hunk 4 above)
Comment (mbrubeck) [inline components/layout/flow.rs]: Done

File: components/layout/flow.rs (hunk 3 above)
Comment (mbrubeck) [inline components/layout/flow.rs]: Done

**Comment by mbrubeck** [comment]
Removed the new RestyleDamage flag; we can just use `REFLOW_OUT_OF_FLOW` as @pcwalton suggested on IRC.

**Comment by pcwalton** [comment]
Looks good. r=me if you like

**Comment by mbrubeck** [comment]
@bors-servo r=pcwalton

* Updated test metadata
