### PR TITLE
Change Offset_to_text_point function and add unit tests

### LINKED ISSUE #18613: assertion failed: self.edit_point.index <= self.lines[self.edit_point.line].len()
Found by fuzzing with domato.

```html
<textarea>

</textarea>
<script>
document.querySelector("textarea").setSelectionRange(0,1);
</script>
```

```gdb
assertion failed: self.edit_point.index <= self.lines[self.edit_point.line].len() (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(1)) }, at /shared/dev/rust/servo/components/script/textinput.rs:211)
stack backtrace:
   0:     0x5598e11d9884 - backtrace::backtrace::libunwind::trace
                        at /shared/dev/rust/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace<closure>
                        at /shared/dev/rust/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:     0x5598e11cc9ef - backtrace::capture::{{impl}}::new
                        at /shared/dev/rust/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:     0x5598da7d278e - servo::main::{{closure}}
                        at /shared/dev/rust/servo/ports/servo/main.rs:130
   3:     0x5598e14b2456 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x5598dc02d005 - std::panicking::begin_panic<&str>
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x5598dd120f78 - script::textinput::{{impl}}::assert_ok_selection<script_traits::ScriptToConstellationChan>
                        at /shared/dev/rust/servo/components/script/textinput.rs:211
   6:     0x5598dd12567f - script::textinput::{{impl}}::set_selection_range<script_traits::ScriptToConstellationChan>
                        at /shared/dev/rust/servo/components/script/textinput.rs:831
   7:     0x5598dd888df4 - script::dom::htmltextareaelement::{{impl}}::SetSelectionRange
                        at /shared/dev/rust/servo/components/script/dom/htmltextareaelement.rs:277
   8:     0x5598dc5d53e5 - script::dom::bindings::codegen::Bindings::HTMLTextAreaElementBinding::HTMLTextAreaElementBinding::setSelectionRange::{{closure}}
                        at /shared/dev/rust/servo/target/debug/build/script-bde6f1c9971e240a/out/Bindings/HTMLTextAreaElementBinding.rs:1586
   9:     0x5598dc2921bf - core::ops::function::FnOnce::call_once<closure,()>
                        at /checkout/src/libcore/ops/function.rs:223
  10:     0x5598dbf5fb1a - std::panic::{{impl}}::call_once<bool,closure>
                        at /checkout/src/libstd/panic.rs:296
  11:     0x5598dc1f5b4c - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,bool>
                        at /checkout/src/libstd/panicking.rs:480
  12:     0x5598e14b95ec - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  13:     0x5598dc164dad - std::panicking::try<bool,std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:459
  14:     0x5598dbfc7861 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,bool>
                        at /checkout/src/libstd/panic.rs:361
  15:     0x5598dd384a22 - js::panic::wrap_panic<std::panic::AssertUnwindSafe<closure>,bool>
                        at /shared/dev/rust/servo/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/3de4ff3/src/panic.rs:22
  16:     0x5598dbe68044 - script::dom::bindings::codegen::Bindings::HTMLTextAreaElementBinding::HTMLTextAreaElementBinding::setSelectionRange
                        at /shared/dev/rust/servo/target/debug/build/script-bde6f1c9971e240a/out/Bindings/HTMLTextAreaElementBinding.rs:1543
  17:     0x5598dda50632 - CallJitMethodOp
                        at /shared/dev/rust/servo/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/3de4ff3/src/jsglue.cpp:516
  18:     0x5598dbc5abe4 - script::dom::bindings::utils::generic_call
                        at /shared/dev/rust/servo/components/script/dom/bindings/utils.rs:450
  19:     0x5598dbc5acf1 - script::dom::bindings::utils::generic_method
                        at /shared/dev/rust/servo/components/script/dom/bindings/utils.rs:458
  20:     0x5598de0cc603 - _ZN2js12CallJSNativeEP9JSContextPFbS1_jPN2JS5ValueEERKNS2_8CallArgsE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jscntxtinlines.h:232
  21:     0x5598de09aa5b - _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:453
  22:     0x5598de09ad82 - InternalCall
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:498
  23:     0x5598de09adac - _ZN2js13CallFromStackEP9JSContextRKN2JS8CallArgsE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:504
  24:     0x5598de0a7dd8 - Interpret
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:2873
  25:     0x5598de09a6dd - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:399
  26:     0x5598de09baa0 - _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_16AbstractFramePtrEPS9_
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:679
  27:     0x5598de09bd60 - _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:712
  28:     0x5598dde0b447 - Evaluate
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsapi.cpp:4407
  29:     0x5598dde0b782 - Evaluate
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsapi.cpp:4443
  30:     0x5598dde0bd02 - _ZN2JS8EvaluateEP9JSContextRKNS_22ReadOnlyCompileOptionsEPKDsmNS_13MutableHandleINS_5ValueEEE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsapi.cpp:4501
  31:     0x5598dd096e63 - script::dom::globalscope::{{impl}}::evaluate_script_on_global_with_result::{{closure}}
                        at /shared/dev/rust/servo/components/script/dom/globalscope.rs:414
  32:     0x5598dc7def9a - profile_traits::time::profile<bool,closure>
                        at /shared/dev/rust/servo/components/profile_traits/time.rs:124
  33:     0x5598dbcc6fc2 - script::dom::globalscope::{{impl}}::evaluate_script_on_global_with_result
                        at /shared/dev/rust/servo/components/script/dom/globalscope.rs:398
  34:     0x5598dd0b05fd - script::dom::htmlscriptelement::{{impl}}::run_a_classic_script
                        at /shared/dev/rust/servo/components/script/dom/htmlscriptelement.rs:573
  35:     0x5598dd0aff3c - script::dom::htmlscriptelement::{{impl}}::execute
                        at /shared/dev/rust/servo/components/script/dom/htmlscriptelement.rs:543
  36:     0x5598dd0ae0ed - script::dom::htmlscriptelement::{{impl}}::prepare
                        at /shared/dev/rust/servo/components/script/dom/htmlscriptelement.rs:456
  37:     0x5598dd8bcf36 - script::dom::servoparser::{{impl}}::tokenize<closure>
                        at /shared/dev/rust/servo/components/script/dom/servoparser/mod.rs:440
  38:     0x5598dd8bc8a1 - script::dom::servoparser::{{impl}}::do_parse_sync
                        at /shared/dev/rust/servo/components/script/dom/servoparser/mod.rs:395
  39:     0x5598dd0c89b7 - script::dom::servoparser::{{impl}}::parse_sync::{{closure}}
                        at /shared/dev/rust/servo/components/script/dom/servoparser/mod.rs:381
  40:     0x5598dc7dfaa7 - profile_traits::time::profile<(),closure>
                        at /shared/dev/rust/servo/components/profile_traits/time.rs:124
  41:     0x5598dd8bc620 - script::dom::servoparser::{{impl}}::parse_sync
                        at /shared/dev/rust/servo/components/script/dom/servoparser/mod.rs:378
  42:     0x5598dd8bcc8c - script::dom::servoparser::{{impl}}::parse_bytes_chunk
                        at /shared/dev/rust/servo/components/script/dom/servoparser/mod.rs:420
  43:     0x5598dd8bff52 - script::dom::servoparser::{{impl}}::process_response_chunk
                        at /shared/dev/rust/servo/components/script/dom/servoparser/mod.rs:692
  44:     0x5598dd11756b - script::script_thread::{{impl}}::handle_fetch_chunk
                        at /shared/dev/rust/servo/components/script/script_thread.rs:2431
  45:     0x5598dd10112e - script::script_thread::{{impl}}::handle_msg_from_constellation
                        at /shared/dev/rust/servo/components/script/script_thread.rs:1183
  46:     0x5598dd0fe6b4 - script::script_thread::{{impl}}::handle_msgs::{{closure}}
                        at /shared/dev/rust/servo/components/script/script_thread.rs:1058
  47:     0x5598dd0feeb0 - script::script_thread::{{impl}}::profile_event<closure,core::option::Option<bool>>
                        at /shared/dev/rust/servo/components/script/script_thread.rs:1174
  48:     0x5598dd0fc477 - script::script_thread::{{impl}}::handle_msgs
                        at /shared/dev/rust/servo/components/script/script_thread.rs:1052
  49:     0x5598dd0fa465 - script::script_thread::{{impl}}::start
                        at /shared/dev/rust/servo/components/script/script_thread.rs:887
  50:     0x5598dbdb09a4 - script::script_thread::{{impl}}::create::{{closure}}::{{closure}}
                        at /shared/dev/rust/servo/components/script/script_thread.rs:572
  51:     0x5598db46a270 - profile_traits::mem::{{impl}}::run_with_memory_reporting<closure,fn(profile_traits::mem::ReportsChan) -> script::script_runtime::CommonScriptMsg,script::script_runtime::CommonScriptMsg,std::sync::mpsc::Sender<script::script_thread::MainThreadScriptMsg>>
                        at /shared/dev/rust/servo/components/profile_traits/mem.rs:63
  52:     0x5598dd0f6256 - script::script_thread::{{impl}}::create::{{closure}}
                        at /shared/dev/rust/servo/components/script/script_thread.rs:571
  53:     0x5598dca481da - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
  54:     0x5598dc02ced3 - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:394
  55:     0x5598dbf4c41a - std::panic::{{impl}}::call_once<(),closure>
                        at /checkout/src/libstd/panic.rs:296
  56:     0x5598dc1a8a92 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panicking.rs:480
  57:     0x5598e14b95ec - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  58:     0x5598dc04400c - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:459
  59:     0x5598dbfe8055 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panic.rs:361
  60:     0x5598db60925b - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:393
  61:     0x5598db7c4123 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /checkout/src/liballoc/boxed.rs:728
  62:     0x5598e14b10db - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:738
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:24
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  63:     0x7fcd7b75f493 - start_thread
  64:     0x7fcd7b28cabe - __clone
  65:                0x0 - <unknown>
ERROR:servo: assertion failed: self.edit_point.index <= self.lines[self.edit_point.line].len()
```

### PR DESCRIPTION
**Pull request by paavininanda**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #18613.

- [x] Added unit tests and web platform tests

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19946)

### CODE REVIEW

**Comment by jdm** [comment]
If you change the testcase in #18613 to use any other value than 1, does the assertion still fail?

File: components/script/textinput.rs [hunk 1]
```diff
@@ -276,7 +276,7 @@ impl<T: ClipboardProvider> TextInput<T> {
         }
 
         debug_assert!(self.edit_point.line < self.lines.len());
-        debug_assert!(self.edit_point.index <= self.lines[self.edit_point.line].len());
+        debug_assert!(self.edit_point.index <= max(1, self.lines[self.edit_point.line].len()));
```
Comment (emilio) [inline components/script/textinput.rs]: I need to take a look at what's going on on the test-case exactly, but I suspect this is wrong.

In particular, this should be `self.lines[self.edit_point.line].len() + 1` instead, but in any case, I still _suspect_ it's the wrong solution, and the `edit_point` should end up being `1, 0` instead of `0, 1` in this case, since we have two lines in the test-case.

Comment (emilio) [inline components/script/textinput.rs]: I need to take a look at what's going on on the test-case exactly, but I suspect this is wrong.

In particular, this should be `self.lines[self.edit_point.line].len() + 1` instead, but in any case, I still _suspect_ it's the wrong solution, and the `edit_point` should end up being `1, 0` instead of `0, 1` in this case, since we have two lines in the test-case.

**Review by emilio — COMMENTED** [review]
I can try to take a closer look, but also maybe @mbrubeck and @jonleighton can take a look.

**Comment by emilio** [comment]
So the issue is that with two empty lines (`["", ""]`), offset_to_text_point(1) is returning `(0, 1)` instead of `(1, 0)`.

**Comment by paavininanda** [comment]
@jdm Yes it fails then also.

**Comment by paavininanda** [comment]
@emilio So should we alter the offset_to_text_point function instead?

**Comment by emilio** [comment]
Yes, I think so...

**Comment by emilio** [comment]
In particular I think that what offset_to_text_point wants to do is something like this:

```rust
        for line_content in self.lines.iter() {
            // If the index fits on the line, we're done.
            if index < line_content.len() {
                break;
            }

            // else advance a line.
            index -= line_content.len();
            line += 1;
            if index > 1 {
                index -= 1; // Account for the \n
            }
        }
```

But I'm not sure that's 100% right, it may need to go through tests and all that :)

**Comment by jonleighton** [comment]
It would be great to add additional unit test(s) to cover this case I think. (The relevant file is `tests/unit/script/textinput.rs`.)

@emilio: I'm happy to try to review this if you like.

**Comment by jdm** [comment]
Note: unit tests can be run with `./Machi test-unit -p script`

File: components/script/textinput.rs [hunk 2]
```diff
@@ -871,13 +871,12 @@ impl<T: ClipboardProvider> TextInput<T> {
...
         let last_line_idx = self.lines.len() - 1;
         self.lines.iter().enumerate().fold(0, |acc, (i, val)| {
             if i != last_line_idx {
-                let line_end = max(val.len(), 1);
-                let new_acc = acc + line_end;
-                if abs_point > new_acc && index > line_end {
+                let line_end = val.len();
+                let new_acc = acc + line_end + 1;
+                if abs_point >= new_acc && index > line_end {
                     index -= line_end + 1;
```
Comment (emilio) [inline components/script/textinput.rs]: I still think this function is way harder to understand than what it should, but I'll file a followup after this lands to do that.

File: tests/unit/script/textinput.rs [hunk 3]
```diff
@@ -600,6 +600,13 @@ fn test_textinput_set_selection_with_direction() {
     assert!(textinput.selection_origin.is_some());
     assert_eq!(textinput.selection_origin.unwrap().line, 0);
     assert_eq!(textinput.selection_origin.unwrap().index, 6);
+
+    textinput = text_input(Lines::Multiple, "\n\n");
```
Comment (emilio) [inline tests/unit/script/textinput.rs]: Let's test also with only `\n`, which is the case we're concerned about. Also, let's add a crashtest for this based on @mateon1's test-case, into `tests/wpt/web-platform-tests/selection/`. See https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests.

The test should call setSelectionRange, but also that the `selectionStart` and `selectionEnd` values agree with other browsers, that is, something like:

```html
<!doctype html>
<textarea>

</textarea>
<script>
test(function() {
    let textarea = document.querySelector('textarea');
    assert_equals(textarea.selectionStart, 0);
    assert_equals(textarea.selectionEnd, 0);
    textarea.setSelectionRange(0, 1);
    assert_equals(textarea.selectionStart, 0);
    assert_equals(textarea.selectionEnd, 1);
}, "setSelectionRange on line boundaries");
</script>
```

**Review by emilio — APPROVED** [review]
Looks good, thanks!

File: components/script/textinput.rs (hunk 2 above)
Comment (paavininanda) [reply components/script/textinput.rs]: Yeah! Actually changing the function altogether was creating some new issues. So i preferred changing it this way only.

File: tests/unit/script/textinput.rs [hunk 4]
```diff
@@ -607,6 +607,20 @@ fn test_textinput_set_selection_with_direction() {
     assert_eq!(textinput.edit_point.index, 0);
     assert_eq!(textinput.selection_direction, SelectionDirection::Forward);
 
+    assert!(textinput.selection_origin.is_some());
+    assert_eq!(textinput.selection_origin.unwrap().line, 0);
+    assert_eq!(textinput.selection_origin.unwrap().index, 0);
+
+    textinput = text_input(Lines::Multiple, "\n");
+    textinput.set_selection_range(0, 1, SelectionDirection::Forward);
+    assert_eq!(textinput.edit_point.line, 0);
```
Comment (emilio) [inline tests/unit/script/textinput.rs]: Hmm, I suspect this should be 1...

**Review by emilio — COMMENTED** [review]
So the unit test you wrote seems to be failing on travis:

```
	thread 'textinput::test_textinput_set_selection_with_direction' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', tests/unit/script/textinput.rs:616:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:390
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: script_tests::textinput::test_textinput_set_selection_with_direction
             at tests/unit/script/textinput.rs:616
   8: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1441
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:788
   9: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
```

Additionally, you need to make sure the manifest is up-to-date running `./mach update-manifest`.
