### PR TITLE
script: retarget dblclick from input UA shadow DOM to host

### LINKED ISSUE #41303: `dblclick` event doesn't seem to fire on some `<input>` elements
**Describe the bug:**
Double-click events on input elements of at least types `text`, `password`, `number`, `search` and `range`.

**To Reproduce:**
Go here https://quirksmode.org/dom/events/tests/click.html

Or use test case
```html
<!doctype html>
<input type="text" id="X">
<h1 id="Y">…</h1>
<script>
  X.addEventListener('dblclick', () => Y.innerText="2xCLICK")
</script>
```
The listener fires on Firefox but not Servo. Change the type to `password`, `number`, `search` or `range` at will.

**Platform:**
Windows 10

### PR DESCRIPTION
**Pull request by Taym95**
dblclick on text inputs was being dispatched to an internal element used for the input, not to the <input> itself. As a result, page scripts listening for dblclick on the input never received the event.

Testing: tested manually.
Fixes: #41303

### CODE REVIEW

File: components/script/dom/document_event_handler.rs [hunk 1]
```diff
@@ -804,7 +807,9 @@ impl DocumentEventHandler {
                     None,
                     can_gc,
                 );
-                event.upcast::<Event>().fire(target.upcast(), can_gc);
+                println!("FIRING dblclick on {}", target.debug_str());
```
Comment (yezhizhen) [inline components/script/dom/document_event_handler.rs]: Nit.

File: components/script/dom/document_event_handler.rs [hunk 2]
```diff
@@ -804,7 +807,9 @@ impl DocumentEventHandler {
...
+                let ok = event.upcast::<Event>().fire(target.upcast(), can_gc);
+                println!("dblclick fire returned ok={}", ok);
```
Comment (yezhizhen) [inline components/script/dom/document_event_handler.rs]: Ditto.

**Review by yezhizhen — COMMENTED** [review]
Seems there's no existing test. Can you add one?

**Comment by Taym95** [comment]
> Seems there's no existing test. Can you add one?

added test.

File: tests/wpt/tests/uievents/click/dblclick_event_on_text_control_inputs.html
Comment (yezhizhen) [inline tests/wpt/tests/uievents/click/dblclick_event_on_text_control_inputs.html:1]: You can add yourself as author in the newly added test :)

**Review by yezhizhen — APPROVED** [review]
