### PR TITLE
make report_pending_exception safe and adjust callers

### LINKED ISSUE #35339: Make report_pending_exception a safe function
https://github.com/servo/servo/blob/d733abfca02cdb9fd2af4f0d82ff050e25f71829/components/script/dom/bindings/error.rs#L238

This function is marked unsafe because it takes a `*mut JSContext` argument. We should replace that with [this JSContext type](https://github.com/servo/servo/blob/d733abfca02cdb9fd2af4f0d82ff050e25f71829/components/script/script_runtime.rs#L893) instead, which will allow us to mark the function as safe (and use unsafe blocks inside of it to make the actual FFI calls).

If there are any callers that do not already have access to the safe JSContext type, you can use [JSContext::from_ptr](https://github.com/servo/servo/blob/d733abfca02cdb9fd2af4f0d82ff050e25f71829/components/script/script_runtime.rs#L897) to obtain one.

### PR DESCRIPTION
**Pull request by nscaife**
This makes report_pending_exception safe as noted in #35339. I also adjusted the callers, but the body of the function is still unsafe due to unsafe JS_* functions and the scope needed to call those. This might be not in the spirit of the request; open to suggestions. 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #35339  (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because they were specifically not requested in the issue.

### CODE REVIEW

File: components/script/dom/workerglobalscope.rs [hunk 1]
```diff
@@ -501,7 +501,12 @@ impl WorkerGlobalScope {
                     println!("evaluate_script failed");
                     unsafe {
                         let ar = enter_realm(self);
-                        report_pending_exception(cx, true, InRealm::Entered(&ar), can_gc);
+                        report_pending_exception(
+                            JSContext::from_ptr(cx),
```
Comment (jdm) [inline components/script/dom/workerglobalscope.rs:505]: Same here.

File: components/script/script_module.rs [hunk 2]
```diff
@@ -601,7 +601,7 @@ impl ModuleTree {
                     ExceptionStackBehavior::Capture,
                 );
                 report_pending_exception(
-                    *GlobalScope::get_cx(),
+                    SafeJSContext::from_ptr(*GlobalScope::get_cx()),
```
Comment (jdm) [inline components/script/script_module.rs:604]: Same here—we can just pass `GlobalScope::get_cx()`.

**Review by jdm — CHANGES_REQUESTED** [review]
Good start! There are still some cleanup opportunities we can take advantage of, though.

**Comment by jdm** [comment]
By the way—in future, please leave a comment in the issue stating that you're going to work on it!

File: components/script/dom/workerglobalscope.rs (hunk 1 above)
Comment (nscaife) [reply components/script/dom/workerglobalscope.rs:505]: This one is a little tricky. cx in this function is a *mut JSContext from runtime. Does the upstream function need to be modified to return a JSContext?

Comment (jdm) [reply components/script/dom/workerglobalscope.rs:505]: Oops, I was too hasty. This one is fine to leave!

**Comment by nscaife** [comment]
Thanks for the kind feedback @jdm! I believe I have made the changes requested. I did more refactoring in error.rs ( to be able to minimize the unsafe blocks in report_pending_exceptions, otherwise the error_info object needed to be in an unsafe block.

File: components/script/dom/bindings/error.rs [hunk 3]
```diff
@@ -182,8 +182,8 @@ pub(crate) struct ErrorInfo {
 }
 
 impl ErrorInfo {
-    unsafe fn from_native_error(object: HandleObject, cx: *mut JSContext) -> Option<ErrorInfo> {
-        let report = JS_ErrorFromException(cx, object);
+    unsafe fn from_native_error(object: HandleObject, cx: SafeJSContext) -> Option<ErrorInfo> {
```
Comment (jdm) [inline components/script/dom/bindings/error.rs:185]: We no longer need the `unsafe` here.

**Review by jdm — APPROVED** [review]
I love seeing unsafe blocks disappearing!

File: components/script/dom/bindings/error.rs (hunk 3 above)
Comment (nscaife) [reply components/script/dom/bindings/error.rs:185]: I think that entire function would wind up being in an unsafe block otherwise. JS_ErrorFromException is unsafe and so are the offset functions and from_raw_parts further down.

Comment (jdm) [reply components/script/dom/bindings/error.rs:185]: I'm ok with that! The method is not unsafe in a way that should affect a caller, so it's better to push that into the method body.

Comment (nscaife) [reply components/script/dom/bindings/error.rs]: OK -- I made that change and also removed the unsafe block where from_native_error is called, since it's no longer needed.

**Comment by jdm** [comment]
This can merge after a rebase!

**Comment by nscaife** [comment]
> This can merge after a rebase!

I did the rebase and squashed the commits. Do I also need to resolve conflicts/merge?
