### PR TITLE
layout: Clone static position rectangles when caching in `IndependentFormattingContext`

### LINKED ISSUE #39439: Moving the mouse can cause absolutely positioned elements to move around
**Describe the bug:**

1. Load the following  HTML:

```html
<!DOCTYPE html>
<div style="overflow: scroll; width: 150px; height: 150px; outline: solid;">
    <div id=target style="position: absolute; background: green; width: 50px; height: 50px">hi</div>
</div>
```
2. Move the mouse outside and inside the Servo window.
3. Observe that the absolutely positioned `<div>` moves around. The `<div>`s offsets keep increasing in the flow tree output.

Curiously, reloading prevents this bug from happening.

Video:

https://github.com/user-attachments/assets/a6d5853a-a95f-4aa6-a3a6-e3e9a878b419

### LINKED ISSUE #39548: Intermittent FAIL in` /_mozilla/css/stacked_layers.html`

### PR DESCRIPTION
**Pull request by mrobinson**
Hoisted absolutes that are cached in IndependentFormattingContexts may
have their HoistedSharedFragment reused between layouts. This means
that the original value of the adjusted static positioning rectangles
need to be preserved in cache. This change makes it so that these values
are cloned when being retrieved from the cache. Further adjustments up
the tree will now no longer affected the version in teh cache.

Testing: This should cause `/_mozilla/css/stacked_layers.html` to no longer
be flaky.
Fixes: #39548.
Fixes: #39439.

### CODE REVIEW

File: components/layout/positioned.rs [hunk 1]
```diff
@@ -656,6 +670,15 @@ impl HoistedAbsolutelyPositionedBox {
         context.base.set_fragment(fragment.clone());
         fragment
     }
+
+    fn static_position_rect(&self) -> PhysicalRect<Au> {
+        self.adjusted_static_position_rect
+            .unwrap_or(self.fragment.borrow().original_static_position_rect)
```
Comment (Loirooriol) [inline components/layout/positioned.rs]: Maybe `unwrap_or_else` to avoid borrowing when not necessary?

**Review by Loirooriol — APPROVED** [review]

File: components/layout/positioned.rs (hunk 1 above)
Comment (mrobinson) [reply components/layout/positioned.rs]: Makes sense!
