### PR TITLE
Changed error type on qname, per spec

### LINKED ISSUE #25110: Passing invalid qualified name arguments to createDocument, createElementNS, and setAttributeNS throw NamespaceError instead of INVALID_CHARACTER_ERR
These throws of the wrong exception are in WPT dom/nodes/DOMImplementation-createDocument.html, Document-createElementNS.html, and attributes.html respectively; other browsers are in agreement with WPT about the exception type.

### PR DESCRIPTION
**Pull request by pshaughn**
As specified in https://dom.spec.whatwg.org/#validate invalid QNames when creating a namespaced document/element/attribute get an invalid character exception, not a namespace exception.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #25110 

- [X] There are tests for these changes

### CODE REVIEW

File: components/script/dom/bindings/xmlname.rs [hunk 1]
```diff
@@ -10,15 +10,10 @@ use html5ever::{LocalName, Namespace, Prefix};
...
-        XMLName::InvalidXMLName => {
-            // Step 1.
-            Err(Error::InvalidCharacter)
-        },
-        XMLName::Name => {
-            // Step 2.
-            Err(Error::Namespace)
-        },
+        XMLName::InvalidXMLName => Err(Error::InvalidCharacter),
+        XMLName::Name => Err(Error::InvalidCharacter),
```
Comment (jdm) [inline components/script/dom/bindings/xmlname.rs]: My reading of https://dom.spec.whatwg.org/#validate says that XMLName shouldn't throw anything. How do the test results look if that's the case?

Comment (Manishearth) [reply components/script/dom/bindings/xmlname.rs]: Oh, I misread this as being "does not match Name", but that's not the case

Comment (pshaughn) [reply components/script/dom/bindings/xmlname.rs]: Good point, maybe there's more than just the exception-type to fix here. I'll find out.

Comment (pshaughn) [reply components/script/dom/bindings/xmlname.rs]: When I change it to let Name in instead of throwing InvalidCharacter for it, then some tests go from correctly throwing InvalidCharacter to incorrectly not throwing, like Document.implementation.createDocumentType("prefix::local", "", "") is expected to throw Invalid Character. "prefix::local" appears to match the Name production. The test seems more consistent with just "if qualifiedName does not match the QName production."

Comment (pshaughn) [reply components/script/dom/bindings/xmlname.rs]: However I should check the codepaths for those "" parts too, maybe those are what's supposed to cause the error this time.

Comment (pshaughn) [reply components/script/dom/bindings/xmlname.rs]: https://dom.spec.whatwg.org/#interface-documenttype nope those are totally allowed to be empty strings, the error has to be for the prefix::local part

**Comment by pshaughn** [comment]
Could I get someone's opinion on what the specs say to do vs. what the tests say to do vs. what the code does? I'm not sure which part's out of sync.

**Comment by Manishearth** [comment]
Sorry about the delay; been doing various travel things. I would file an issue on the spec and tag whoever has touched that area recently. Typically I've found that the tests for this kind of thing are more "correct" (in that they match what other browsers do). You should also check what other browsers do, and if it doesn't match the spec then get the spec changed.

**Comment by pshaughn** [comment]
It turns out there's already an issue: https://github.com/whatwg/dom/issues/671

**Comment by pshaughn** [comment]
(this push is just a rebase, not a functional update)

**Comment by pshaughn** [comment]
Based on that issue thread I think it's safe to assume the spec change reflects reality and will eventually land; I'm going to rebase again and add a comment about the issue.

**Comment by pshaughn** [comment]
This is old enough some test might have slid out from under it...
@bors-servo try=wpt
