### PR TITLE
net: Keep IP cookie buckets separate

### LINKED ISSUE #44097: reg_host treats IP addresses as domain names, causing cross-IP cookie bucket collisions and eviction
**Describe the bug:**

The `reg_host` function in `cookie_storage.rs` uses `reg_suffix` to determine which storage bucket a cookie belongs to.  Since no IP octet matches a public suffix rule, it returns the last two dot-separated segments as the bucket key. This means unrelated IPs can collide into the same bucket:
`reg_suffix`  maps `192.168.0.1`  `10.0.0.1`  and `172.16.0.1` to   `0.1`   

Each bucket is capped at max_per_host cookies so a server at one IP could force eviction of cookies belonging to a completely unrelated IP that happens to share the same bucket key. 

**To Reproduce:**
```
 fn test_ip_cookie_bucket_collision_eviction() {
     // Two unrelated IPs: 192.168.0.1 and 10.0.0.1
     // reg_suffix treats them as dotted names, both yielding suffix "0.1"
     // So they share the same storage bucket and max_per_host limit.
     let mut storage = CookieStorage::new(5);
     let ip_a = ServoUrl::parse("http://192.168.0.1/path").unwrap();
     let ip_b = ServoUrl::parse("http://10.0.0.1/path").unwrap();
     let source = CookieSource::HTTP;

     // Store 3 cookies for IP A
     for i in 1..=3 {
         let cookie_str = format!("a{}=val{}", i, i);
         let cookie = cookie::Cookie::parse(cookie_str).unwrap();
         let sc = ServoCookie::new_wrapped(cookie, &ip_a, source).unwrap();
         storage.push(sc, &ip_a, source);
     }

     // Verify IP A has 3 cookies
     let cookies_a = storage.cookies_for_url(&ip_a, source);
     assert!(cookies_a.is_some(), "IP A should have cookies stored");

     // Now store 5 cookies for IP B. This should NOT affect IP A's cookies
     // since they are completely different hosts. But because they share the
     // same bucket key, IP B's cookies will compete with IP A's cookies for
     // the max_per_host=5 limit.
     for i in 1..=5 {
         let cookie_str = format!("b{}=val{}", i, i);
         let cookie = cookie::Cookie::parse(cookie_str).unwrap();
         let sc = ServoCookie::new_wrapped(cookie, &ip_b, source).unwrap();
         storage.push(sc, &ip_b, source);
     }

     // Check if IP A's cookies survived. If the bucket is shared, adding 5
     // cookies for IP B (total 8) would exceed max_per_host=5, causing
     // eviction of IP A's cookies.
     let cookies_a_after = storage.cookies_for_url(&ip_a, source);
     let a_count = cookies_a_after
         .as_ref()
         .map(|s| s.split("; ").count())
         .unwrap_or(0);

     assert_eq!(
         a_count, 3,
         "BUG: IP cookie bucket collision — cookies for 192.168.0.1 were \
          evicted when 10.0.0.1 filled the jar. {} of 3 cookies remain.",
         a_count
     );
 }
```
The test currently fails and 0 of 3 cookies for 192.168.0.1 survive after 10.0.0.1 fills the shared bucket. 

**Potential fix:**

 In `reg_host`, check whether the URL host is an IP address. If so, return the full IP as the bucket key instead of calling `reg_suffix`. This mirrors
  what `registered_domain_name` already does:
```
   fn reg_host(url: &ServoUrl) -> String {
       match url.origin() {
           ImmutableOrigin::Tuple(_, Host::Domain(domain), _) => {
               reg_suffix(&domain).to_lowercase()
           },
           ImmutableOrigin::Tuple(_, ip, _) => ip.to_string().to_lowercase(),
           ImmutableOrigin::Opaque(_) => String::new(),
       }
   }
```

### PR DESCRIPTION
**Pull request by officialasishkumar**
Use the full IP address as the cookie storage bucket key instead of passing IP hosts through the public suffix registrable-domain helper. This prevents unrelated IP hosts that share suffix-like address segments from sharing a per-host eviction bucket.

Testing: Added `test_ip_cookie_bucket_collision_eviction`; ran `cargo test -p servo-net --test main test_ip_cookie_bucket_collision_eviction --locked`.
Fixes: #44097

### CODE REVIEW

File: components/net/tests/cookie.rs [hunk 1]
```diff
@@ -222,6 +222,28 @@ fn add_cookie_to_storage(storage: &mut CookieStorage, url: &ServoUrl, cookie_str
     storage.push(cookie, url, source);
 }
 
+#[test]
+fn test_ip_cookie_bucket_collision_eviction() {
```
Comment (jdm) [inline components/net/tests/cookie.rs]: Can we test the ipv6 format as well?

**Review by jdm — APPROVED** [review]
Thanks for fixing this and writing the test!

File: components/net/tests/cookie.rs (hunk 1 above)
Comment (officialasishkumar) [reply components/net/tests/cookie.rs]: Added IPv6 coverage in f3c9b69540 by running the same cookie bucket eviction regression against bracketed IPv6 URLs.
