### PR TITLE
libservo: Fix dead code warning and fix two typos in unit tests

### LINKED ISSUE #42364: Warning when compiling unit tests
`./mach test-unit -d` produces

```
warning: associated function `new` is never used
  --> components/servo/tests/common/mod.rs:25:19
   |
24 | impl ServoTest {
   | -------------- associated function in this implementation
25 |     pub(crate) fn new() -> Self {
   |                   ^^^
   |
   = note: `#[warn(dead_code)]` (part of `#[warn(unused)]`) on by default

warning: `libservo` (test "largest_contentful_paint") generated 1 warning
```

### PR DESCRIPTION
**Pull request by Keerti707**
This PR addresses a dead code warning removed during test builds by ensuring the servo test helper constructor is exercised. None of the functional behaviors are changed and this only improves test clarity and keeps the compiler output warning-free.

Fixes: #42364

### CODE REVIEW

**Comment by Keerti707** [comment]
I have opened a PR for this,please check it, I would really appreciate some feedback!

**Comment by simonwuelker** [comment]
Thank you, this looks good!

You just need to sign-off your commits before we can merge this, see https://book.servo.org/contributing/git-setup.html#starting-a-new-change.
You can do this for an existing commit with `git commit --amend -s --no-edit`.

**Comment by Keerti707** [comment]
> Thank you, this looks good!
> 
> You just need to sign-off your commits before we can merge this, see https://book.servo.org/contributing/git-setup.html#starting-a-new-change. You can do this for an existing commit with `git commit --amend -s --no-edit`.

thank you! I have now tried signing off my commits,I hope its working that way too!

**Comment by simonwuelker** [comment]
Hmm your commits are not signed. You should see a line like `Signed-off by: XYZ`at the end of the commit message.
It also looks like the change doesn't compile (see the failing CI job).

**Comment by Loirooriol** [comment]
I have edited the message to use `Fixes: #42364`, this links the PR to the issue.

Your  commit is still unsigned.

File: components/servo/tests/common/mod.rs [hunk 1]
```diff
@@ -22,10 +22,6 @@ pub struct ServoTest {
 }
 
 impl ServoTest {
-    pub(crate) fn new() -> Self {
```
Comment (shubhamg13) [inline components/servo/tests/common/mod.rs:25]: This function is used by other tests in `webview.rs`

**Review by shubhamg13 — COMMENTED** [review]
If you really want to deal with this error. Add `#[expect(dead_code)]` to this.

File: components/servo/tests/common/mod.rs [hunk 2]
```diff
@@ -199,3 +200,5 @@ pub(crate) fn show_webview_and_wait_for_rendering_to_be_ready(
     let captured_delegate = delegate.clone();
     servo_test.spin(move || !captured_delegate.new_frame_ready.get());
 }
+
```
Comment (shubhamg13) [inline components/servo/tests/common/mod.rs]: nit: please remove extra lines

File: components/servo/tests/common/mod.rs [hunk 3]
```diff
@@ -22,8 +22,9 @@ pub struct ServoTest {
 }
 
 impl ServoTest {
+    #[expect(dead_code)] // Used by some tests and not others
     pub(crate) fn new() -> Self {
-        Self::new_with_builder(|builder| builder)
+        Self::new_with_builder(|b| b)
```
Comment (shubhamg13) [inline components/servo/tests/common/mod.rs]: nit: please revert this

**Review by shubhamg13 — COMMENTED** [review]
Minor nits, rest LGTM.

File: components/servo/tests/common/mod.rs (hunk 3 above)
Comment (Keerti707) [reply components/servo/tests/common/mod.rs]: okay! thank you for the suggestion. 
Really appreciate it!

**Comment by Keerti707** [comment]
Hi! 👋
I have updated the PR :
I initially added a zero-argument ServoTest::new() constructor with #[expect(dead_code)] to fix the compile errors in tests but as per the given suggestion i reverted it and i have now done evrything that i could see from my end
All changes are now DCO-signed (Signed-off-by: Keerti Gupta <24bsm032@iiitdmj.ac.in>).
The branch should now compile cleanly, and the DCO check passes. Please let me know if anything else needs adjustment. Thank you!

File: components/servo/tests/common/mod.rs [hunk 4]
```diff
@@ -23,7 +23,7 @@ pub struct ServoTest {
 
 impl ServoTest {
     pub(crate) fn new() -> Self {
-        Self::new_with_builder(|builder| builder)
+        Self::new_with_builder(|b| b)
```
Comment (mrobinson) [inline components/servo/tests/common/mod.rs]: Looks like this one still needs to be reverted.

**Review by mrobinson — COMMENTED** [review]
@Keerti707 I think you accidentally removed your fixes for the dead code and left the unrelated changes. Please take another look.

File: components/servo/tests/common/mod.rs (hunk 4 above)
Comment (Keerti707) [reply components/servo/tests/common/mod.rs]: Thank you for pointing that out..you are right I reverted the unrelated builder rename,I have now fixed that.

Comment (Keerti707) [reply components/servo/tests/common/mod.rs]: Now the fixes for the dead code are made too!
I am sorry for the confusion I caused by mistake
Please take a look at the PR now!
I hope it works correctly as per the need.

**Review by mrobinson — APPROVED** [review]

File: components/servo/tests/common/mod.rs [hunk 5]
```diff
@@ -22,6 +22,7 @@ pub struct ServoTest {
 }
 
 impl ServoTest {
+    #[expect(dead_code)] // Used by some tests and not others
```
Comment (Loirooriol) [inline components/servo/tests/common/mod.rs:25]: If it's sometimes used, it doesn't make sense to expect it to be dead.
Now I'm getting

```
warning: this lint expectation is unfulfilled
  --> components/servo/tests/common/mod.rs:25:14
   |
25 |     #[expect(dead_code)] // Used by some tests and not others
   |              ^^^^^^^^^
   |
   = note: `#[warn(unfulfilled_lint_expectations)]` on by default
```

So please use `allow(dead_code)` instead.

Comment (Keerti707) [reply components/servo/tests/common/mod.rs:25]: Thank you for noticing that!
I have made the necessary changes!
I hope its working now.

Comment (Loirooriol) [reply components/servo/tests/common/mod.rs:25]: This PR already landed, you need to open a new one
