### PR TITLE
Fix main frame scrolling in quirks mode after WebRender upgrade

### LINKED ISSUE #30368: WebRender upgrade caused regression in Acid2 Test
It seems this patch https://github.com/servo/servo/pull/30323 caused a regression in Acid2: https://wpt.live/acid/acid2/test.html (it works in https://github.com/servo/servo/tree/revert-webrender)

Screenshot of Servo trying to run the test

Nothing happens when you click *Take The Acid2 Test*, not even browsing directly http://acid2.acidtests.org/#top

### PR DESCRIPTION
**Pull request by mrobinson**
Main frame scrolling after the WebRender upgrade was broken because the
main frame no longer has content size content bounds and quirks mode
leads to a body with zero height.

Fixes #30368.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #30368.
- [x] There are tests for these changes

### CODE REVIEW

**Comment by mrobinson** [comment]
Still a draft, because I suspect this will change test results and I'd like to update them before this lands.

**Comment by mrobinson** [comment]
@bors-servo try

The new failures are tests that started failing, probably as false passes, after the WebRender upgrade.

File: components/compositing/compositor.rs [hunk 1]
```diff
@@ -664,8 +664,8 @@ impl<Window: WindowMethods + ?Sized> IOCompositor<Window> {
                 self.waiting_for_results_of_scroll = true;
 
                 let mut txn = Transaction::new();
-                txn.scroll_node_with_id(point, scroll_id, ScrollClamping::ToContentBounds);
-                txn.generate_frame(0);
+                txn.scroll_node_with_id(point, scroll_id, ScrollClamping::NoClamping);
+                txn.generate_frame(200);
```
Comment (mukilan) [inline components/compositing/compositor.rs:668]: Is this argument to `generate_frame` arbitrary? If not, maybe we can comment why this value was chosen?

Comment (mrobinson) [reply components/compositing/compositor.rs:668]: Sorry, this argument is currently unused. I modified it in the process of debugging, but I'll revert this change.

Comment (mrobinson) [reply components/compositing/compositor.rs]: This should be removed now. Thanks for pointing it out.

File: tests/wpt/meta-legacy-layout/html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/sticky-content.html.ini [hunk 2]
```diff
@@ -0,0 +1,4 @@
+tests/wpt/meta-legacy-layout/html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/sticky-content.html.ini
```
Comment (mukilan) [inline tests/wpt/meta-legacy-layout/html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/sticky-content.html.ini:1]: I think we have a syntax error - the path here needs to be wrapped in `[` `]` to form a valid key. This is the reason the latest try run has failed.

Comment (mrobinson) [reply tests/wpt/meta-legacy-layout/html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/sticky-content.html.ini]: Whoops. I've fixed this. Thanks.

**Review by mukilan — APPROVED** [review]
