### PR TITLE
Android: Fix black screen when exiting menu or resuming activity in lifecycle

### LINKED ISSUE #40632: Android servoshell: blank webview after closing settings
after opening and closing the settings, the webview goes blank until you scroll or interact with the page. this also happens when you switch to another app and back to servoshell.

https://github.com/user-attachments/assets/8805883d-5ce3-4519-823d-2320813a0cae

- servoshell nightly 2025-11-12
- OnePlus 8T (IN2010)
- Android 11 (Oxygen OS 11.0.8.13.KB05AA)

### LINKED ISSUE #44300: Black screen when exit menu
**Describe the bug:**

https://github.com/user-attachments/assets/9273f50a-1780-4d7b-9890-7b984a9c72fb

**Platform:**
Android

### PR DESCRIPTION
**Pull request by yezhizhen**
We should request repaint for the platform window when `resume_painting` 
or entering [Resumed](https://developer.android.com/guide/components/activities/activity-lifecycle#onresume) state in Android activity lifecycle.

Fixes: #44300
Fixes: #40632
Fixes: #39737
Testing: Manually tested with following video proof

https://github.com/user-attachments/assets/046c045d-12d1-43fa-9387-fc504cc4bfe5

### CODE REVIEW

File: ports/servoshell/egl/android/mod.rs [hunk 1]
```diff
@@ -525,6 +525,15 @@ pub extern "C" fn Java_org_servo_servoview_JNIServo_resumePainting<'local>(
     });
 }
 
+#[unsafe(no_mangle)]
+pub extern "C" fn Java_org_servo_servoview_JNIServo_requestRepaint<'local>(
+    mut env: JNIEnv<'local>,
+    _: JClass<'local>,
+) {
+    debug!("requestRepaint");
+    call(&mut env, |app| app.request_repaint());
```
Comment (mukilan) [inline ports/servoshell/egl/android/mod.rs]: This is causing a build error as this method is not defined on the App but on the platform window.

```
[8](https://github.com/servo/servo/actions/runs/24597742259/job/71930962611#step:15:1418)
error[E0599]: no method named `request_repaint` found for reference `&egl::app::App` in the current scope
   --> ports/servoshell/egl/android/mod.rs:534:30
    |
534 |     call(&mut env, |app| app.request_repaint());
    |                              ^^^^^^^^^^^^^^^ method not found in `&egl::app::App`
```

Also, is it necessary to request repaint from onResume? Wouldn't the native widget also be recreated in that scenario and thus `resume_painting` will be called anyway? I removed the code here and the call to requestRepaint in `onResume`  and that still fixes both blank screen scenarios - going back from settings and switching to another app and back. Is there any other scenario where this is necessary?

Comment (yezhizhen) [reply ports/servoshell/egl/android/mod.rs]: > This is causing a build error as this method is not defined on the App but on the platform window.

Yeah, I forgot to commit them in the PR. But I did include it in my [previous try run](https://github.com/servo/servo/actions/runs/24561582733).

> Is there any other scenario where this is necessary?

It seems just first commit is needed after I confirm!

**Review by mukilan — APPROVED** [review]
Nice find! Thank you!

**Comment by jschwe** [comment]
Thanks for looking into this!

**Comment by yezhizhen** [comment]
@jschwe What I'm not sure is why Ohos didn't have this bug. My current guess is that ohos has the vsync callback handler.
https://github.com/servo/servo/blob/d3932a2118d05ab49dcbbd739d05959dbccb2c3a/ports/servoshell/egl/ohos/mod.rs#L508

**Comment by jschwe** [comment]
I'm not sure if the surface gets destroyed on ohos if the ability goes to the background. We could disable vsync to test if we run into the same issue.

**Comment by yezhizhen** [comment]
> I'm not sure if the surface gets destroyed on ohos if the ability goes to the background.

Even if does, we didn't have the callback yet https://github.com/servo/servo/blob/d3932a2118d05ab49dcbbd739d05959dbccb2c3a/ports/servoshell/egl/ohos/mod.rs#L656-L657. For Android, this would call `pause_painting` and unbind surface from context.

**Comment by yezhizhen** [comment]
> I'm not sure if the surface gets destroyed on ohos if the ability goes to the background.

I think yes based on [this blog](https://ai6s.net/6922de3d82fbe0098cae0dd4.html) written in Chinese.
