### PR TITLE
layout: Add initial support for first-letter pseudo element

### LINKED ISSUE #43008: Inquiries regarding eager pseudo elements
https://github.com/servo/servo/blob/45f1bdbf41d70529496d32635f34b4a49eb44c50/components/script/layout_dom/element.rs#L1084-L1088

I was trying to implement the `first-letter` pseudo element and had a WPT testcase crash due to the assertion on line 1085. I followed gecko's approach in stylo and define `first-letter` as an eager pseudo element (https://github.com/servo/stylo/blob/9b635629e627a611419745198de1b1ba6c8667c2/style/gecko/pseudo_element_definition.mako.rs#L32), and my current implementation make use of `NodeAndStyleInfo::with_pseudo_element()` which eventually calls the code above and panics at the assertion.

Could someone explain why we need this assertion? And whether the recommended approach is to make `first-letter` not eager or to change/remove the assertion?

### PR DESCRIPTION
**Pull request by minghuaw**
This and the accompanying stylo PR (https://github.com/servo/stylo/pull/320) is a partial implementation of the `first-letter` pseudo element.

Testing: Existing WPT tests. There is one WPT test (fcp-typographic-pseudo.html) that servo currently fails would timeout with this PR because opacity of `TextFragment` is taken from the `InlineFormattingContext` instead of the pseudo element.
Fixes: #43008 
Part of: #15413

### CODE REVIEW

**Comment by servo-highfive** [comment]
Heads up! This PR modifies the following files:
 * @jschwe: deny.toml

File: components/layout/flow/inline/construct.rs [hunk 1]
```diff
@@ -280,38 +288,82 @@ impl InlineFormattingContextBuilder {
...
+        let should_append_zwj = !is_last_letter &&
+            matches!(
+                LanguageIdentifier::from_str(&pseudo_info.style.clone__x_lang().0)
+                    .map(|locid| locid.language),
+                Ok(LANG_ARABIC) | Ok(LANG_PERSIAN)
+            );
+
+        let new_first_letter: String = if should_append_zwj {
+            self.last_inline_text_run_ended_with_zero_width_joiner = true;
+            iter.chain(std::iter::once('\u{200D}')).collect()
```
Comment (minghuaw) [inline components/layout/flow/inline/construct.rs]: This and line 393 below (in the `push_text` method) is a hack to address the problem in languages like Arabic where letters may be written differently when joined together. It right now simply checks if the language tag is "ar" or "fa" (see line 315 above); would it be better if it also checks the unicode script? 

What would be a proper solution for this?

File: tests/wpt/meta/paint-timing/fcp-only/fcp-typographic-pseudo.html.ini [hunk 2]
```diff
@@ -1,3 +1,4 @@
 [fcp-typographic-pseudo.html]
+  expected: TIMEOUT
   [First contentful paint fires only when some of the text is visible, considering ::first-letter.]
-    expected: FAIL
+    expected: TIMEOUT
```
Comment (minghuaw) [inline tests/wpt/meta/paint-timing/fcp-only/fcp-typographic-pseudo.html.ini:4]: This test would timeout with this PR because FCP takes the opacity from the fragment which is taken from the `InlineFormattingContextBuilder` instead of the pseudo element

File: deny.toml [hunk 3]
```diff
@@ -227,7 +227,9 @@ skip = [
 # github.com organizations to allow git sources for
 [sources.allow-org]
 github = [
-    "servo",
+    # "servo",
+    # TODO: remove once stylo PR lands
+    "minghuaw",
```
Comment (minghuaw) [inline deny.toml]: TODO: remove once the stylo PR lands

File: Cargo.toml [hunk 4]
```diff
@@ -330,6 +331,17 @@ egui-winit = { git = "https://github.com/emilk/egui.git", rev = "5d8f393335e0517
 # stylo_static_prefs = { path = "../stylo/stylo_static_prefs" }
 # stylo_traits = { path = "../stylo/style_traits" }
 #
+# TODO: Remove patch once stylo PR lands
```
Comment (minghuaw) [inline Cargo.toml]: TODO: remove once the stylo PR lands

File: tests/wpt/tests/css/css-backgrounds/reference/first-letter-space-not-selected-ref.html [hunk 5]
```diff
@@ -3,6 +3,11 @@
 <head>
     <title>CSS Reftest Reference</title>
     <link rel="author" title="Ethan Malasky" href="mailto:emalasky@adobe.com">
+    <style type="text/css">
```
Comment (minghuaw) [inline tests/wpt/tests/css/css-backgrounds/reference/first-letter-space-not-selected-ref.html]: This WPT test was wrong in the first place. The reference page uses a different font size. Is it ok if we fix it in this PR or this change should be submitted in a separate PR in the WPT repo?

File: components/layout/flow/inline/line.rs [hunk 6]
```diff
@@ -886,8 +886,12 @@ impl TextRunLineItem {
         new_bidi_level: Level,
         new_glyph_store: &Arc<GlyphStore>,
         new_offsets: &Option<TextRunOffsets>,
+        new_inline_styles: &SharedInlineStyles,
     ) -> bool {
-        if self.font_key != new_font_key || self.bidi_level != new_bidi_level {
+        if self.font_key != new_font_key ||
+            self.bidi_level != new_bidi_level ||
+            !self.inline_styles.ptr_eq(new_inline_styles)
```
Comment (minghuaw) [inline components/layout/flow/inline/line.rs:897]: With this PR, the first letter would have a different `SharedInlineStyles` ptr from the rest of the text. It wouldn't merge even if the style content is the same as that of the rest of the text. Is it worth it to compare the content?

File: components/layout/flow/inline/construct.rs [hunk 7]
```diff
@@ -322,22 +374,26 @@ impl InlineFormattingContextBuilder {
...
+                    WhiteSpaceCollapse::PreserveBreaks => {
+                        character.is_ascii_whitespace() && character != '\n'
+                    },
+                    WhiteSpaceCollapse::Preserve | WhiteSpaceCollapse::BreakSpaces => false,
+                };
+        });
+
+        let new_text: String = if self.last_inline_text_run_ended_with_zero_width_joiner {
+            self.last_inline_text_run_ended_with_zero_width_joiner = false;
+            std::iter::once('\u{200D}').chain(iter).collect()
```
Comment (minghuaw) [inline components/layout/flow/inline/construct.rs]: This is a hack (see comment above in the `push_first_letter` method)

**Comment by minghuaw** [comment]
To assist the code review, below is a quick summary of the major changes, which are mainly made in two mods `components/layout/flow/inline/construct.rs` and `components/layout/flow/construct.rs`

In `components/layout/flow/inline/construct.rs`, added `InlineFormattingContextBuilder::push_first_letter` which is similar to `InlineFormattingContextBuilder::push_text` but the main difference is that the inline styles doesn't use that from the `InlineFormattingContextBuilder` but the one for the pseudo element. And this makes the first letter a separate text run from the rest of the text. The hack to add zero-width joiner is added in both `push_first_letter` and `push_text`.

In `components/layout/flow/construct.rs`, the conditions that check whether it needs to call `InlineFormattingContextBuilder::push_first_letter` takes place in `BlockContainerBuilder::handle_text`. A helper function `first_letter_range` is also added to find the begin and end of the first letter

**Comment by minghuaw** [comment]
@xiaochengh Would you please take a look?

**Comment by xiaochengh** [comment]
> The current implementation doesn't support `float`

Do we really need to support `float`?

`float` in first letter is a non-standard and legacy approach to implement drop caps, and has become the source of countless bugs in Blink. The standard way is via `initial-letter`.

See: https://drafts.csswg.org/css-pseudo/#first-letter-styling

File: tests/wpt/meta/paint-timing/fcp-only/fcp-typographic-pseudo.html.ini (hunk 2 above)
Comment (xiaochengh) [reply tests/wpt/meta/paint-timing/fcp-only/fcp-typographic-pseudo.html.ini:4]: Ack

File: tests/wpt/tests/css/css-backgrounds/reference/first-letter-space-not-selected-ref.html (hunk 5 above)
Comment (xiaochengh) [reply tests/wpt/tests/css/css-backgrounds/reference/first-letter-space-not-selected-ref.html]: I think it's OK to fix it in the same PR, since they are highly related.

File: components/layout/flow/inline/line.rs (hunk 6 above)
Comment (xiaochengh) [reply components/layout/flow/inline/line.rs:897]: I don't think there's need to compare the style contents.

File: components/layout/flow/inline/construct.rs (hunk 1 above)
Comment (xiaochengh) [reply components/layout/flow/inline/construct.rs]: This approach looks wrong to me. Complex script joining should be properly handled even if the lang tag is not properly set. And there are other complex scripts, e.g. Mongolian, but we probably don't want to maintain an exhaustive list here.

Regarding a proper approach, do we support continuous shaping correctly? For example:

```html
<div dir=rtl><span style="color:red">ال</span>عربية</div>
```

If we support this then I think we don't need special handling for complex scripts.

---

Since this is not the core of the feature, can we drop it from this PR and investigate it later?

File: components/layout/flow/inline/construct.rs (hunk 7 above)
Comment (xiaochengh) [reply components/layout/flow/inline/construct.rs]: Let's drop this part from this PR. See comment above.

File: components/layout/flow/inline/construct.rs [hunk 8]
```diff
@@ -412,6 +468,41 @@ impl InlineFormattingContextBuilder {
     }
 }
 
+fn apply_whitespace_collapse_and_text_transform<'a>(
+    text: &'a str,
+    capitalized_text: &'a mut String,
+    white_space_collapse: WhiteSpaceCollapse,
+    text_transform: TextTransformCase,
+    on_word_boundary: bool,
+    trim_beginning_white_space: bool,
```
Comment (xiaochengh) [inline components/layout/flow/inline/construct.rs]:
```suggestion
    trim_leading_white_space: bool,
```
nit: "leading white space" is the standard terminology.

File: components/layout/flow/inline/construct.rs [hunk 9]
```diff
@@ -280,38 +288,82 @@ impl InlineFormattingContextBuilder {
         self.push_control_character_string(bidi_control_chars.1);
     }
 
+    pub(crate) fn push_first_letter<'dom>(
```
Comment (xiaochengh) [inline components/layout/flow/inline/construct.rs]: This function has significant code duplicity with `push_text`. Can we avoid copy-pasting code, especially after removing the hack with ZWJ?

File: components/layout/flow/construct.rs [hunk 10]
```diff
@@ -424,8 +510,34 @@ impl<'dom> TraversalHandler<'dom> for BlockContainerBuilder<'dom, '_> {
...
+            if let Some(pseudo_info) = self
+                .info
+                .with_pseudo_element(context, PseudoElement::FirstLetter)
+            {
+                if builder.text_segments.iter().all(|seg| seg.is_empty()) {
+                    let (first_letter_range, is_last_letter) = first_letter_range(&text[..]);
+                    range.start = first_letter_range.end;
+
+                    // The first letter range may be some value larger than zero when
+                    // there are proceding spaces.
```
Comment (xiaochengh) [inline components/layout/flow/construct.rs]:
```suggestion
                    // there are preceding spaces.
```

**Review by xiaochengh — COMMENTED** [review]
The overall approach looks fine except the ZWJ hack. Please see the detailed comments below.

Thanks!

File: tests/wpt/meta/css/css-backgrounds/first-letter-space-not-selected.html.ini [hunk 11]
```diff
@@ -0,0 +1,2 @@
+[first-letter-space-not-selected.html]
+  expected: FAIL
```
Comment (minghuaw) [inline tests/wpt/meta/css/css-backgrounds/first-letter-space-not-selected.html.ini:2]: This fails now because the original wpt test reference does not use the same font size and background color as the test itself (chromium, FF, and safari all fail this test). The expected behavior of the test reference is unclear, and thus the modifications made to the WPT test itself has been restored.

File: tests/wpt/meta/css/css-text/text-transform/text-transform-shaping-001.html.ini [hunk 12]
```diff
@@ -0,0 +1,2 @@
+[text-transform-shaping-001.html]
+  expected: FAIL
```
Comment (minghuaw) [inline tests/wpt/meta/css/css-text/text-transform/text-transform-shaping-001.html.ini:2]: This one fails because servo currently doesn't support "continuous shaping" see #35397

File: tests/wpt/meta/css/css-text/text-transform/text-transform-shaping-002.html.ini [hunk 13]
```diff
@@ -0,0 +1,2 @@
+[text-transform-shaping-002.html]
+  expected: FAIL
```
Comment (minghuaw) [inline tests/wpt/meta/css/css-text/text-transform/text-transform-shaping-002.html.ini:2]: This one fails because servo currently doesn't support "continuous shaping" see #35397

File: tests/wpt/meta/css/css-text/text-transform/text-transform-shaping-003.html.ini [hunk 14]
```diff
@@ -0,0 +1,2 @@
+[text-transform-shaping-003.html]
+  expected: FAIL
```
Comment (minghuaw) [inline tests/wpt/meta/css/css-text/text-transform/text-transform-shaping-003.html.ini:2]: This one fails because servo currently doesn't support "continuous shaping" see #35397

File: components/layout/flow/inline/construct.rs (hunk 1 above)
Comment (minghuaw) [reply components/layout/flow/inline/construct.rs]: Unfortunately this is not supported yet. Dropped the hack in the latest commit

File: components/layout/flow/inline/construct.rs (hunk 7 above)
Comment (minghuaw) [reply components/layout/flow/inline/construct.rs]: Dropped the hack in the latest commit

File: components/layout/flow/inline/construct.rs (hunk 8 above)
Comment (minghuaw) [reply components/layout/flow/inline/construct.rs]: This is removed in the latest commit

File: components/layout/flow/inline/construct.rs (hunk 9 above)
Comment (minghuaw) [reply components/layout/flow/inline/construct.rs]: Removed `push_first_letter`. The updated implementation would now push the `SharedInlineStyles` for the `first-letter` to the `InlineFormattingContextBuilder` 's stack before calling `push_text` and then pop the style from the stack immediately after

**Comment by yezhizhen** [comment]
@minghuaw You need to rebase. Due to 1632e61ed624aab03226d1364338c40f54613b50

**Comment by yezhizhen** [comment]
@minghuaw I think the failure is because, your merge commit 19d959754a2b0495ae34d04daf5d9ed86bd245ad actually does nothing.

Just try to solve the cargo conflict and rebase.

**Comment by yezhizhen** [comment]
Closing and reopening to make upstream work properly..

https://github.com/web-platform-tests/wpt/pull/58281
Due to #42958

**Comment by minghuaw** [comment]
@xiaochengh Would you mind taking another look. The implementation has been updated to address the comments. Below is a summary of the changes since your last review.

1. Removed `push_first_letter` and dropped the ZWJ hack, which also restores `push_text`
2. The first letter's style is now pushed to the `InlineFormattingContextBuilder`'s style stack before pushing the first letter text and is popped from the stack immediately after
3. 3 more WPT tests are expected to fail because of lack of "continuous" shaping support.

File: components/layout/flow/construct.rs [hunk 15]
```diff
@@ -364,6 +364,78 @@ impl<'dom, 'style> BlockContainerBuilder<'dom, 'style> {
     }
 }
 
+/// Computes the range of the first letter. Returns the range and whether
+/// the letter is also the last letter. Returns a range 0..0 when no
+/// letter is found.
+///
+/// <https://drafts.csswg.org/css-pseudo/#first-letter-pattern>
+fn first_letter_range(text: &str) -> std::ops::Range<usize> {
```
Comment (xiaochengh) [inline components/layout/flow/construct.rs:378]: Can we add some unit tests for this function?

File: components/layout/flow/construct.rs [hunk 16]
```diff
@@ -364,6 +364,78 @@ impl<'dom, 'style> BlockContainerBuilder<'dom, 'style> {
     }
 }
 
+/// Computes the range of the first letter. Returns the range and whether
```
Comment (xiaochengh) [inline components/layout/flow/construct.rs]: Please update documentation as now it's only returning a range. Please also clarify:
- Whether the range contains the preceding and succeeding punctuations 
- What's the result in edge cases where the string contains no LNS:
  - The entire string contains white space only
  - The entire string contains only white spaces and punctuations

File: components/layout/flow/construct.rs [hunk 17]
```diff
@@ -424,8 +496,40 @@ impl<'dom> TraversalHandler<'dom> for BlockContainerBuilder<'dom, '_> {
...
 
-        self.ensure_inline_formatting_context_builder()
-            .push_text(text, info);
+        self.ensure_inline_formatting_context_builder();
+        let context = self.context;
+        let builder = self.inline_formatting_context_builder.as_mut().unwrap();
+
+        let mut range = 0..;
+        // first-letter is an eager pseudo element and should not be nested
+        if self.info.pseudo_element_chain().is_empty() {
```
Comment (xiaochengh) [inline components/layout/flow/construct.rs]: What happens if the first letter spans multiple nodes?

It's OK to just document the failure without implementing it, since it's quite complicated

**Review by xiaochengh — COMMENTED** [review]
Thanks for the update. A few comments regarding edge cases.

File: components/layout/flow/construct.rs (hunk 17 above)
Comment (minghuaw) [reply components/layout/flow/construct.rs]: If a char were split into two separate `&str` (this should be impossible in safe rust, and would likely cause panic when such a string is created in unsafe rust), the first half wouldn't compose a complete char and thus the range would return `0..0`, and then the whole string is pushed into the `InlineFormattingContextBuilder` without the styles of the pseudo element. The second half of the char in the second string wouldn't compose a complete char either and a range of `0..0` should be returned too, causing the whole second string to be pushed into the `InlineFormattingContextBuilder` without the styles of the pseudo element.

It would appear as if the pseudo element didn't take effect (if servo hadn't panicked due to memory problems in string creation already)

Comment (xiaochengh) [reply components/layout/flow/construct.rs]: I'm wondering about this case:

```html
<style> div::first-letter { color: red; } </style>
<div>
<span>(</span>A<span>)</span> bcd
</div>
```

Currently Chromium and Firefox both get it wrong.

---

Another case is first letter in a `::before` or `::after` pseudo element. Are we handling it correctly?

**Review by mrobinson — COMMENTED** [review]
@minghuaw Apologies for not having time to look at this yet, @Loirooriol and I will try to take a look soon!

File: components/layout/flow/construct.rs (hunk 17 above)
Comment (minghuaw) [reply components/layout/flow/construct.rs]: This PR would fail this case too, but in a different way from FF and Chromium. FF and Chromium would display the opening parenthesis red, but this PR would render nothing red.

image

For `::before` and `::after` pseudo element, this PR gets it partially correct as it does pass some WPT testcases for these pseudo elements, for example

1. [‎tests/wpt/meta/css/css-display/display-contents-dynamic-before-after-first-letter-001.html.ini](https://github.com/servo/servo/pull/43027/changes#diff-8947aab5099dbcf158e85781a23fd10751f7f3cd77fe22af77d649e89512d22b)
2. [‎tests/wpt/meta/css/css-pseudo/first-letter-skip-marker.html.ini‎](https://github.com/servo/servo/pull/43027/changes#diff-1afd3bf8d07ed94cba3616dbee72b877f65d732d8dd6f34cc29d79f913f82441)
3. [‎tests/wpt/meta/css/css-pseudo/first-letter-with-before-after.html.ini](https://github.com/servo/servo/pull/43027/changes#diff-545d387398147eb8987fe2a6e4f2117d21401b989700b047fdf7f24cbb7fa84c)

However, it fails `css/CSS2/selectors/before-first-letter-selector-001.xht` this testcase, and the problem for this test seems to relate to color property not inheriting from the `::before` pseudo element.

File: components/layout/flow/construct.rs (hunk 15 above)
Comment (minghuaw) [reply components/layout/flow/construct.rs:378]: Added unit test `layout::flow::construct::test_first_letter_range()` in the latest commit

File: components/layout/flow/construct.rs (hunk 16 above)
Comment (minghuaw) [reply components/layout/flow/construct.rs]: Fixed but and updated the documentation in the latest commit.

**Comment by minghuaw** [comment]
@mrobinson @xiaochengh @Loirooriol Added unit test (about 80 lines are just unit test) and updated the documentation for the `first_letter_range()` function. Would you mind taking another look?

File: components/layout/flow/construct.rs (hunk 17 above)
Comment (minghuaw) [reply components/layout/flow/construct.rs]: > ```html
> <style> div::first-letter { color: red; } </style>
> <div>
> <span>(</span>A<span>)</span> bcd
> </div>
> ```

One way to get this correct in servo is to move handling of `::first-letter` to a later stage like `InlineFormattingContext::new_with_builder` where we have the entire text

File: components/layout/flow/construct.rs [hunk 18]
```diff
@@ -364,6 +364,91 @@ impl<'dom, 'style> BlockContainerBuilder<'dom, 'style> {
     }
 }
 
+/// Computes the range of the first letter.
+///
+/// Any preceding punctuation and any intervening spaces in
+/// the preceding punctuations and between the preceding punctuations
+/// and the first letter/number/symbol are included in the range.
```
Comment (Loirooriol) [inline components/layout/flow/construct.rs]: It's not much clear with so many "and"s. I think it looks better as

```suggestion
/// The range includes any preceding punctuation, and any spaces interleaved
/// within the preceding punctuation or between the preceding punctuation
/// and the first letter/number/symbol.
```

File: components/layout/flow/construct.rs [hunk 19]
```diff
@@ -364,6 +364,91 @@ impl<'dom, 'style> BlockContainerBuilder<'dom, 'style> {
...
+/// Succeeding punctuations are included in the range, but any spaces
```
Comment (Loirooriol) [inline components/layout/flow/construct.rs]: "punctuation" is uncountable (even if individual punctuation marks are countable)

```suggestion
/// Succeeding punctuation are included in the range, but any spaces
```

File: Cargo.toml (hunk 4 above)
Comment (Loirooriol) [reply Cargo.toml]: Even if this will go away, next time just replace `rev = "51593b0258309bfbbee767b3c116bc7ce6bc1b80"` with `rev = "refs/pull/320/head"`. Then lint won't complain, and I won't need to download your entire fork to compile the patch.

File: components/layout/flow/construct.rs [hunk 20]
```diff
@@ -364,6 +364,91 @@ impl<'dom, 'style> BlockContainerBuilder<'dom, 'style> {
...
+        Lns,
+        SucceedingPunc,
+    }
+
+    let mut iter = text.char_indices();
+    let mut start = 0;
+    let mut end = None;
+    let mut state = State::Start;
+
+    for (i, c) in &mut iter {
```
Comment (Loirooriol) [inline components/layout/flow/construct.rs]: You can remove the variable

```suggestion
    for (i, c) in text.char_indices() {
```

File: components/layout/flow/construct.rs [hunk 21]
```diff
@@ -364,6 +364,91 @@ impl<'dom, 'style> BlockContainerBuilder<'dom, 'style> {
...
+/// succeeding spaces is not supported yet.
+///
+/// <https://drafts.csswg.org/css-pseudo/#first-letter-pattern>
+fn first_letter_range(text: &str) -> std::ops::Range<usize> {
+    use unicode_categories::UnicodeCategories;
+
+    enum State {
+        Start,
+        PrecedingPunc,
+        Lns,
```
Comment (Loirooriol) [inline components/layout/flow/construct.rs:385]: I would add some documentation that this refers to the Unicode general categories L (letter), N (number), S (symbol).

File: components/layout/flow/construct.rs [hunk 22]
```diff
@@ -364,6 +364,91 @@ impl<'dom, 'style> BlockContainerBuilder<'dom, 'style> {
...
+                    continue;
+                } else {
+                    // Found invalid character
+                    return 0..0;
+                }
+            },
+            State::Lns => {
+                if c.is_punctuation() && !c.is_punctuation_open() && !c.is_punctuation_dash() {
+                    state = State::SucceedingPunc;
+                } else {
```
Comment (Loirooriol) [inline components/layout/flow/construct.rs:424]: I think here you also need a TODO for intervening spaces?

I'm guessing that it's not as easy as `if c.is_separator_space() { continue;  }` because the space should only be included if it's followed by punctuation that will be included.

File: components/layout/flow/construct.rs [hunk 23]
```diff
@@ -364,6 +364,91 @@ impl<'dom, 'style> BlockContainerBuilder<'dom, 'style> {
...
+        }
+    }
+
+    match state {
+        State::Start | State::PrecedingPunc => 0..0,
+        State::Lns => {
+            let end = end.unwrap_or(text.len());
+            start..end
+        },
+        State::SucceedingPunc => {
```
Comment (Loirooriol) [inline components/layout/flow/construct.rs]:
```suggestion
        State::Lns | State::SucceedingPunc => {
```

File: components/layout/flow/construct.rs (hunk 17 above)
Comment (Loirooriol) [reply components/layout/flow/construct.rs]: Another interesting case is

```html
<!DOCTYPE html>
<style>
p {
  width: 0;
  line-break: anywhere;
}
p::first-letter {
  color: lime;
}
</style>
<p>‘T</p>
```

Both the punctuation and the letter are green, like Blink. But see https://github.com/w3c/csswg-drafts/issues/2254, `::first-letter` should be restricted to the 1st line.

File: components/layout/flow/construct.rs [hunk 24]
```diff
@@ -424,8 +509,40 @@ impl<'dom> TraversalHandler<'dom> for BlockContainerBuilder<'dom, '_> {
...
+        let builder = self.inline_formatting_context_builder.as_mut().unwrap();
+
+        let mut range = 0..;
+        // first-letter is an eager pseudo element and should not be nested
+        if self.info.pseudo_element_chain().is_empty() {
+            if let Some(pseudo_info) = self
+                .info
+                .with_pseudo_element(context, PseudoElement::FirstLetter)
+            {
+                if builder.text_segments.iter().all(|seg| seg.is_empty()) {
```
Comment (Loirooriol) [inline components/layout/flow/construct.rs]: This needs a TODO, at least

```html
<!DOCTYPE html>
<style>
p::first-letter {
  color: lime;
}
</style>
<p>T</p>
<script>
document.querySelector("p").prepend(" ");
</script>
```

File: components/layout/flow/construct.rs [hunk 25]
```diff
@@ -424,8 +509,40 @@ impl<'dom> TraversalHandler<'dom> for BlockContainerBuilder<'dom, '_> {
...
+                        builder.push_text(Cow::Borrowed(&text[0..first_letter_range.start]), info);
+                    }
+
+                    let first_letter = Cow::Borrowed(&text[first_letter_range]);
+                    let first_letter_inline_styles =
+                        SharedInlineStyles::from_info_and_context(&pseudo_info, context);
+                    builder
+                        .shared_inline_styles_stack
+                        .push(first_letter_inline_styles);
+                    builder.push_text(first_letter, &pseudo_info);
```
Comment (Loirooriol) [inline components/layout/flow/construct.rs]: I think it should be a box, not just text, because otherwise `background-color` doesn't work.

**Review by Loirooriol — COMMENTED** [review]
Looks like a good start!

File: components/layout/flow/construct.rs (hunk 20 above)
Comment (minghuaw) [reply components/layout/flow/construct.rs]: My bad. The original design was to use the `iter` again at the end to get the index of the next char. Thanks for catching this :)

File: components/layout/flow/construct.rs (hunk 22 above)
Comment (minghuaw) [reply components/layout/flow/construct.rs:424]: You are right. Somehow I had the impression that only the spaces within the succeeding punctuation would count. 

Will add a TODO

File: components/layout/flow/construct.rs [hunk 26]
```diff
@@ -364,6 +364,87 @@ impl<'dom, 'style> BlockContainerBuilder<'dom, 'style> {
...
+                    continue;
+                } else {
+                    // Found invalid character
+                    return 0..0;
+                }
+            },
+            State::PrecedingPunc => {
+                if c.is_letter() || c.is_number() || c.is_symbol() {
+                    state = State::Lns;
+                } else if c.is_punctuation() || c.is_separator_space() {
```
Comment (Loirooriol) [inline components/layout/flow/construct.rs]: https://drafts.csswg.org/css-pseudo/#first-letter-pattern

> any intervening typographic space—​characters belonging to the Zs Unicode general category [[UAX44]](https://drafts.csswg.org/css-pseudo/#biblio-uax44) **other than U+3000 IDEOGRAPHIC SPACE**

File: components/layout/flow/construct.rs (hunk 17 above)
Comment (minghuaw) [reply components/layout/flow/construct.rs]: > ```html
> <!DOCTYPE html>
> <style>
> p {
>   width: 0;
>   line-break: anywhere;
> }
> p::first-letter {
>   color: lime;
> }
> </style>
> <p>‘T</p>
> ```

Would this require reshaping the letter `T` with the non-first-letter styles after linebreak?

File: Cargo.toml (hunk 4 above)
Comment (minghuaw) [reply Cargo.toml]: Didn't know this. Thanks for pointing this out :)

File: components/layout/flow/construct.rs (hunk 17 above)
Comment (minghuaw) [reply components/layout/flow/construct.rs]: Should this be tracked in a separate issue?

File: tests/wpt/meta/css/css-pseudo/first-letter-with-preceding-new-line.html.ini [hunk 27]
```diff
@@ -0,0 +1,2 @@
+[first-letter-with-preceding-new-line.html]
+  expected: FAIL
```
Comment (minghuaw) [inline tests/wpt/meta/css/css-pseudo/first-letter-with-preceding-new-line.html.ini:2]: This might be because of lack of support for `first-line` pseudo element. However, servo (without support for first-line) somehow currently displays this test in the same way as FF, which also fails this test

File: components/layout/flow/construct.rs (hunk 21 above)
Comment (minghuaw) [reply components/layout/flow/construct.rs:385]: Added documentation for LNS in the updated code

File: components/layout/flow/construct.rs (hunk 22 above)
Comment (minghuaw) [reply components/layout/flow/construct.rs:424]: TODO added in the updated code

File: components/layout/flow/construct.rs (hunk 24 above)
Comment (minghuaw) [reply components/layout/flow/construct.rs]: This line has been changed to check whether each `char` in the existing segments is unicode space separator and can handle this case correctly

File: components/layout/flow/construct.rs (hunk 25 above)
Comment (minghuaw) [reply components/layout/flow/construct.rs]: Changed to start and end an inline box before and after the `push_text`. This change passes more than 300 additional WPT tests

File: components/layout/flow/construct.rs (hunk 26 above)
Comment (minghuaw) [reply components/layout/flow/construct.rs]: Changed to check if char is U+3000 in the updated code

**Comment by minghuaw** [comment]
@Loirooriol All your comments should be addressed in the updated code. With your suggestion of making first letter a new box, this PR would pass around 350 additional WPT tests

File: components/layout/flow/construct.rs [hunk 28]
```diff
@@ -424,8 +508,45 @@ impl<'dom> TraversalHandler<'dom> for BlockContainerBuilder<'dom, '_> {
...
+
+                    builder.start_inline_box(
+                        || ArcRefCell::new(InlineBox::new(&pseudo_info, context)),
+                        None,
+                    );
+                    builder.push_text(first_letter, &pseudo_info);
+                    builder.end_inline_box();
+                }
+            }
+        }
```
Comment (Loirooriol) [inline components/layout/flow/construct.rs]: I think it looks a bit better like this, in particular it avoids `.unwrap()` and reduces indentation:

```suggestion
        let info = self.info;
        let context = self.context;
        let builder = self.ensure_inline_formatting_context_builder();

        // ::first-letter is an eager pseudo element and should not be nested
        if let Some(pseudo_info) = (info.pseudo_element_chain().is_empty())
            .then(|| info.with_pseudo_element(context, PseudoElement::FirstLetter))
            .flatten()
            .filter(|_| {
                builder
                    .text_segments
                    .iter()
                    .flat_map(|seg| seg.chars())
                    .all(|c| c.is_separator_space())
            })
        {
            let first_letter_range = first_letter_range(&text[..]);

            // The first letter range may be some value larger than zero when
            // there are preceding spaces.
            if first_letter_range.start != 0 {
                builder.push_text(Cow::Borrowed(&text[0..first_letter_range.start]), info);
            }

            builder.start_inline_box(
                || ArcRefCell::new(InlineBox::new(&pseudo_info, context)),
                None,
            );
            let first_letter_text = Cow::Borrowed(&text[first_letter_range.clone()]);
            builder.push_text(first_letter_text, &pseudo_info);
            builder.end_inline_box();

            builder.push_text(Cow::Borrowed(&text[first_letter_range.end..]), info);
        } else {
            builder.push_text(text, info);
        }
```

File: components/layout/flow/construct.rs [hunk 29]
```diff
@@ -364,6 +365,89 @@ impl<'dom, 'style> BlockContainerBuilder<'dom, 'style> {
     }
 }
 
+/// Computes the range of the first letter.
+///
+/// The range includes any preceding punctuation, and any spaces interleaved
+/// within the preceding punctuation or between the preceding punctuation
+/// and the first letter/number/symbol.
+/// Succeeding punctuation are included in the range, but any spaces
+/// following the letter/number/symbol ends the range. Intervening
```
Comment (Loirooriol) [inline components/layout/flow/construct.rs]: Can't use "spaces" in plural but "ends" in singular

```suggestion
/// Succeeding punctuation are included in the range, but any space
/// following the letter/number/symbol ends the range. Intervening
```

File: components/layout/flow/construct.rs [hunk 30]
```diff
@@ -364,6 +365,89 @@ impl<'dom, 'style> BlockContainerBuilder<'dom, 'style> {
...
+/// succeeding spaces is not supported yet.
```
Comment (Loirooriol) [inline components/layout/flow/construct.rs]:
```suggestion
/// succeeding spaces are not supported yet.
```

**Review by Loirooriol — APPROVED** [review]

File: components/layout/flow/construct.rs (hunk 28 above)
Comment (minghuaw) [reply components/layout/flow/construct.rs]: Thanks for catching this. I didn't realize that rust compiler can infer the lifetime on individual field now

File: components/layout/flow/construct.rs [hunk 31]
```diff
@@ -424,8 +508,42 @@ impl<'dom> TraversalHandler<'dom> for BlockContainerBuilder<'dom, '_> {
...
 
-        self.ensure_inline_formatting_context_builder()
-            .push_text(text, info);
+        let info = self.info;
+        let context = self.context;
+        let builder = self.ensure_inline_formatting_context_builder();
+
+        // ::first-letter is an eager pseudo element and should not be nested
+        if let Some(pseudo_info) = (info.pseudo_element_chain().is_empty())
+            .then(|| info.with_pseudo_element(context, PseudoElement::FirstLetter))
```
Comment (Loirooriol) [inline components/layout/flow/construct.rs]: Sorry, my suggestion had a mistake. I added the `info` variable because `builder` keeps `self` mutably borrowed so `self.info` doesn't work afterwards. But this shadowed the `info` of the text.

I guess it may not matter because text doesn't have its own style, but better do it like

```suggestion
        let container_info = self.info;
        let context = self.context;
        let builder = self.ensure_inline_formatting_context_builder();

        // ::first-letter is an eager pseudo element and should not be nested
        if let Some(pseudo_info) = (container_info.pseudo_element_chain().is_empty())
            .then(|| container_info.with_pseudo_element(context, PseudoElement::FirstLetter))
```

File: components/layout/flow/construct.rs (hunk 17 above)
Comment (xiaochengh) [reply components/layout/flow/construct.rs]: > Should this be tracked in a separate issue?

Makes sense, since it makes things so much more complicated...

**Review by xiaochengh — APPROVED** [review]
Thanks for the updates, LGTM!

**Comment by minghuaw** [comment]
> Do we really need to support `float`?

Not really. I mentioned that just because MDN uses float as one of its examples, but we should definitely follow the more standard approach (`initial-letter`)

**Comment by minghuaw** [comment]
Updated the description to reflect recent changes

**Comment by Loirooriol** [comment]
`/css/css-pseudo/first-letter-skip-marker.html` fails after #43111
