### PR TITLE
htmlbuttonelement: check if document is fully active in activation behavior

### LINKED ISSUE #39643: HTMLButtonElement's activation behaviour needs to check if document is fully active
https://github.com/servo/servo/blob/caee3ad79cb33e65569627b99f4c45190bfbb51e/components/script/dom/html/htmlbuttonelement.rs#L367
https://github.com/servo/servo/blob/caee3ad79cb33e65569627b99f4c45190bfbb51e/components/script/dom/html/htmlbuttonelement.rs#L377

Since https://github.com/servo/servo/blob/caee3ad79cb33e65569627b99f4c45190bfbb51e/components/script/dom/document.rs#L740 exists, we can add this check now. If we downcast `_target` to a `Node`, we can call `node.owner_document()` to obtain a `Document` that we can call `is_fully_active()` on.

I don't know if there are tests for this already. I recommend running a [try build](https://book.servo.org/hacking/testing.html#running-web-platform-tests-on-your-github-fork) and seeing if there are any `Stable unexpected results` reported (and feel free to drop a link to the results for verification!)

### PR DESCRIPTION
**Pull request by WaterWhisperer**
check if document is fully active in HTMLButtonElement's activation behaviour

Testing: ran a [try build](https://github.com/WaterWhisperer/servo/actions/runs/18343522397) and it passed successfully
Fixes: #39643

### CODE REVIEW

**Comment by webbeef** [comment]
The stable failure is:

FAIL [expected PASS] /css/css-text/text-transform/text-transform-upperlower-104.html

Can you check what's going on here? You should be able to verify locally the results by running `./mach test-wpt /css/css-text/text-transform/text-transform-upperlower-104.html` (with a debug build. Add `-r` for release builds).

**Comment by TimvdLippe** [comment]
I suspect that test is flaky given a lot of css tests are flaky lately

File: components/script/dom/html/htmlbuttonelement.rs
Comment (yezhizhen) [inline components/script/dom/html/htmlbuttonelement.rs]: This link is no longer valid. Can you also update it?

File: components/script/dom/html/htmlbuttonelement.rs [hunk 1]
```diff
@@ -364,7 +364,11 @@ impl Activatable for HTMLButtonElement {
         match ty {
             // https://html.spec.whatwg.org/multipage/#attr-button-type-submit-state
             ButtonType::Submit => {
-                // TODO: is document owner fully active?
+                // Step 2. If element's node document is not fully active, then return.
```
Comment (yezhizhen) [inline components/script/dom/html/htmlbuttonelement.rs:367]: We should check the target's document.

File: components/script/dom/html/htmlbuttonelement.rs [hunk 2]
```diff
@@ -374,7 +378,11 @@ impl Activatable for HTMLButtonElement {
                 }
             },
             ButtonType::Reset => {
-                // TODO: is document owner fully active?
+                // Step 2. If element's node document is not fully active, then return.
```
Comment (yezhizhen) [inline components/script/dom/html/htmlbuttonelement.rs:383]: Ditto.

**Review by yezhizhen — CHANGES_REQUESTED** [review]

**Comment by yezhizhen** [comment]
Also `commit -s --amend` to fix the DCO. Thanks @WaterWhisperer!

**Comment by WaterWhisperer** [comment]
> The stable failure is:
> 
> FAIL [expected PASS] /css/css-text/text-transform/text-transform-upperlower-104.html
> 
> Can you check what's going on here? You should be able to verify locally the results by running `./mach test-wpt /css/css-text/text-transform/text-transform-upperlower-104.html` (with a debug build. Add `-r` for release builds).

Thanks for the review! Sorry, I'm unable to run the test locally due to resource constraints on my machine and I guess that's a flaky test.  But I've re-run the [try build](https://github.com/WaterWhisperer/servo/actions/runs/18258976569) and this time it didn't fail.

File: components/script/dom/html/htmlbuttonelement.rs
Comment (WaterWhisperer) [reply components/script/dom/html/htmlbuttonelement.rs]: ok

**Comment by yezhizhen** [comment]
> ⚠️ Try run ([#18260112700](https://github.com/servo/servo/actions/runs/18260112700)) failed.

This doesn't compile. Can you fix it?

**Comment by WaterWhisperer** [comment]
> > ⚠️ Try run ([#18260112700](https://github.com/servo/servo/actions/runs/18260112700)) failed.
> 
> This doesn't compile. Can you fix it?

Yes, I'll try to fix it.

File: components/script/dom/html/htmlbuttonelement.rs [hunk 3]
```diff
@@ -358,13 +358,18 @@ impl Activatable for HTMLButtonElement {
...
-            // https://html.spec.whatwg.org/multipage/#attr-button-type-submit-state
+            // https://html.spec.whatwg.org/multipage/#the-button-element:attr-button-type-submit-state
             ButtonType::Submit => {
-                // TODO: is document owner fully active?
+                // Step 2. If element's node document is not fully active, then return.
+                let node = target.downcast::<Node>().unwrap();
+                let document = node.owner_document();
+                if !document.is_fully_active() {
+                    return;
+                }
```
Comment (mrobinson) [inline components/script/dom/html/htmlbuttonelement.rs]:
```suggestion
                if !target.owner_document().document.is_fully_active() {
                    return;
                }
```

File: components/script/dom/html/htmlbuttonelement.rs [hunk 4]
```diff
@@ -374,7 +379,12 @@ impl Activatable for HTMLButtonElement {
                 }
             },
             ButtonType::Reset => {
-                // TODO: is document owner fully active?
+                // Step 2. If element's node document is not fully active, then return.
+                let node = target.downcast::<Node>().unwrap();
+                let document = node.owner_document();
+                if !document.is_fully_active() {
+                    return;
+                }
```
Comment (mrobinson) [inline components/script/dom/html/htmlbuttonelement.rs]:
```suggestion
                if !target.owner_document().is_fully_active() {
                    return;
                }
```

File: components/script/dom/html/htmlbuttonelement.rs [hunk 5]
```diff
@@ -342,9 +342,9 @@ impl Validatable for HTMLButtonElement {
         // https://html.spec.whatwg.org/multipage/#the-button-element%3Abarred-from-constraint-validation
         // https://html.spec.whatwg.org/multipage/#enabling-and-disabling-form-controls%3A-the-disabled-attribute%3Abarred-from-constraint-validation
         // https://html.spec.whatwg.org/multipage/#the-datalist-element%3Abarred-from-constraint-validation
-        self.button_type.get() == ButtonType::Submit &&
-            !self.upcast::<Element>().disabled_state() &&
-            !is_barred_by_datalist_ancestor(self.upcast())
+        self.button_type.get() == ButtonType::Submit
+            && !self.upcast::<Element>().disabled_state()
+            && !is_barred_by_datalist_ancestor(self.upcast())
```
Comment (mrobinson) [inline components/script/dom/html/htmlbuttonelement.rs]: Please make sure to run `./mach fmt` before uploading your change.

**Review by mrobinson — CHANGES_REQUESTED** [review]

File: components/script/dom/html/htmlbuttonelement.rs (hunk 3 above)
Comment (WaterWhisperer) [reply components/script/dom/html/htmlbuttonelement.rs]: Understood, thanks for the reviews!

File: components/script/dom/html/htmlbuttonelement.rs (hunk 4 above)
Comment (WaterWhisperer) [reply components/script/dom/html/htmlbuttonelement.rs]: This seems to be unsuccessful in compiling.  [try build](https://github.com/WaterWhisperer/servo/actions/runs/18340352933/job/52234150997#step:13:1417)

File: components/script/dom/html/htmlbuttonelement.rs [hunk 6]
```diff
@@ -358,13 +358,21 @@ impl Activatable for HTMLButtonElement {
...
         let ty = self.button_type.get();
         match ty {
-            // https://html.spec.whatwg.org/multipage/#attr-button-type-submit-state
+            // https://html.spec.whatwg.org/multipage/#the-button-element:attr-button-type-submit-state
             ButtonType::Submit => {
-                // TODO: is document owner fully active?
+                // Step 2. If element's node document is not fully active, then return.
+                if !target
+                    .downcast::<Node>()
+                    .unwrap()
```
Comment (mrobinson) [inline components/script/dom/html/htmlbuttonelement.rs]: Why are you still downcasting here? Can't you just call `target.owner_document()`?

Comment (WaterWhisperer) [reply components/script/dom/html/htmlbuttonelement.rs:370]: I've tried to do that but seems to be unsuccessful in compiling.  [try build](https://github.com/WaterWhisperer/servo/actions/runs/18340352933/job/52234150997#step:13:1417)

Comment (WaterWhisperer) [reply components/script/dom/html/htmlbuttonelement.rs]: > Why are you still downcasting here? Can't you just call `target.owner_document()`?你为什么还在这儿向下转型？难道你不能直接调用 `target.owner_document()` 吗？

I've tried to do that but seems to be unsuccessful in compiling.  [try build](https://github.com/WaterWhisperer/servo/actions/runs/18340352933/job/52234150997#step:13:1417)

**Comment by WaterWhisperer** [comment]
Now it seems to compile successfully [try build](https://github.com/WaterWhisperer/servo/actions/runs/18341179698)

File: components/script/dom/html/htmlbuttonelement.rs (hunk 6 above)
Comment (mrobinson) [inline components/script/dom/html/htmlbuttonelement.rs]: If it's possible that the `EventTarget` isn't a node, you should gracefully handle this failure and not panic here.

```
if !target.downcast::<Node>().is_none_or(|node| node.owner_document()).is_fully_active()) {
    return;
}
```

**Review by mrobinson — CHANGES_REQUESTED** [review]

File: components/script/dom/html/htmlbuttonelement.rs (hunk 6 above)
Comment (WaterWhisperer) [reply components/script/dom/html/htmlbuttonelement.rs]: > If it's possible that the `EventTarget` isn't a node, you should gracefully handle this failure and not panic here.
> 
> ```
> if !target.downcast::<Node>().is_none_or(|node| node.owner_document().is_fully_active()) {
>     return;
> }
> ```

I see, thank you for your careful guidance

File: components/script/dom/html/htmlbuttonelement.rs [hunk 7]
```diff
@@ -358,13 +358,19 @@ impl Activatable for HTMLButtonElement {
         !self.upcast::<Element>().disabled_state()
     }
 
-    // https://html.spec.whatwg.org/multipage/#run-post-click-activation-steps
-    fn activation_behavior(&self, _event: &Event, _target: &EventTarget, can_gc: CanGc) {
+    // https://html.spec.whatwg.org/multipage/#the-button-element:activation-behaviour
```
Comment (mrobinson) [inline components/script/dom/html/htmlbuttonelement.rs]:
```suggestion
    /// <https://html.spec.whatwg.org/multipage/#the-button-element:activation-behaviour>
```

**Review by mrobinson — APPROVED** [review]

**Review by yezhizhen — APPROVED** [review]
Pls address Martin's final comment.
And update text in testing.
