### PR TITLE
Move DL items from gfx to layout and implement corner clipping

### LINKED ISSUE #19649: Implement Corner Clipping
https://drafts.csswg.org/css-backgrounds-3/#corner-clipping

### LINKED ISSUE #19680: Browser.html tile corners no longer rendered correctly
Tiles

The rounded corners are now no longer clipped and instead the tiles are rendered as full rectangles. This is a recent regression as previous builds did not exhibit this issue. Tested in Windows 10.

### LINKED ISSUE #19802: Border-radius don't crop background-image
servo-br
```
<!DOCTYPE html>
<html>
	<head>
		<style>
			.img{
				width: 200px;
				height: 200px;
				border-radius: 50%;
				background: url('https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Hrad%C4%8Dansk%C3%A1%2C_Tatra_T3.jpg/320px-Hrad%C4%8Dansk%C3%A1%2C_Tatra_T3.jpg');
				border: 5px solid red;
			}
		</style>
	</head>
	<body>
		<div class="img"></div>
	</body>
</html>
```

### PR DESCRIPTION
**Pull request by pyfisch**
Implement corner clipping.
Remove PixelFormat from WebrenderImageInfo.
Use WebRender text shadow.
Remove MallocSizeOf and Deserialize for DL items.

Closes #19649, closes #19680, closes #19802

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #__ (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20420)

### CODE REVIEW

**Comment by pyfisch** [comment]
http://build.servo.org/builders/linux-rel-wpt/builds/8339/steps/shell__4/logs/filtered-wpt-errorsummary.log

**Comment by pyfisch** [comment]
This is now ready for review.

The two failing tests are some weird bug that only occurs for elements with `direction: rtl` in certain conditions. It appears that the WritingMode is empty for these elements while the border_padding has direction RTL. This causes an assertion in debug mode to fail.

**Comment by pyfisch** [comment]
@Manishearth: You created the "build_display_list_for_background_if_applicable_with_background" method. I guess based on the name it should display the provided background instead of the element background. But in only uses the provided background for color and [not for images and gradients](https://github.com/servo/servo/blob/36a41722b6b93be6e500b4fc0debfa9b5d2ac7bf/components/layout/display_list/builder.rs#L874). (It does not suffice to remove the line because the different images again access the background via `style: &ComputedValues`.

**Comment by Manishearth** [comment]
Ah, oops. It should be using the same background. You're right that that's not enough; fixing the rest is a part of the fix for https://github.com/servo/servo/issues/20093 (which I haven't had time to get to)

**Comment by pyfisch** [comment]
r? @emilio

This PR moves the display list items from the gfx crate to layout. They are only ever used in layout and moving them there will hopefully decrease compile when modifying these items as gfx stays untouched. This also adds corner clipping for backgrounds along with a test. 

Previously this used the same code to clip the background color and the background images but I reverted it because of two failing right-to-left tests.

As you see I tried to start bors but for some reason the bot is not replying?

File: components/gfx/platform/macos/font_context.rs [hunk 1]
```diff
@@ -2,7 +2,9 @@
  * License, v. 2.0. If a copy of the MPL was not distributed with this
  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
 
-#[derive(Clone, Debug, MallocSizeOf)]
+use malloc_size_of::{MallocSizeOf, MallocSizeOfOps};
+
+#[derive(Clone, Debug)]
```
Comment (emilio) [inline components/gfx/platform/macos/font_context.rs]: I don't understand this, why is `#[derive()]` not usable anymore?

File: components/layout/display_list/items.rs [hunk 2]
```diff
@@ -74,15 +71,18 @@ impl ClippingAndScrolling {
         }
     }
 
-    pub fn new(scrolling: ClipScrollNodeIndex, clipping: ClipScrollNodeIndex) -> ClippingAndScrolling {
+    pub fn new(
+        scrolling: ClipScrollNodeIndex,
+        clipping: ClipScrollNodeIndex,
+    ) -> ClippingAndScrolling {
```
Comment (emilio) [inline components/layout/display_list/items.rs]: nit: This can use `Self` and fit into the same line I think.

File: components/layout/display_list/builder.rs [hunk 3]
```diff
@@ -967,13 +980,21 @@ impl FragmentDisplayListBuilding for Fragment {
             Some(image),
             style.logical_border_width().to_physical(style.writing_mode),
             self.border_padding.to_physical(style.writing_mode),
+            build_border_radius(&absolute_bounds, style.get_border()),
             index,
         );
 
+        let previous_clipping_and_scrolling = state.current_clipping_and_scrolling;
```
Comment (emilio) [inline components/layout/display_list/builder.rs]: This looks somewhat easy to mess up returning before we get to the end of the function or what not. Could we use some sort of:

````
state.with_clipping_and_scrolling(|state| {
    do_foo(state);
})
```

that takes care of setting and restoring the state?

File: components/layout/display_list/items.rs [hunk 4]
```diff
@@ -986,19 +995,16 @@ impl WebRenderImageInfo {
...
 
 impl SimpleMatrixDetection for LayoutTransform {
     #[inline]
     fn is_identity_or_simple_translation(&self) -> bool {
-        let (_0, _1) = (Zero::zero(), One::one());
-        self.m11 == _1 && self.m12 == _0 && self.m13 == _0 && self.m14 == _0 &&
-        self.m21 == _0 && self.m22 == _1 && self.m23 == _0 && self.m24 == _0 &&
-        self.m31 == _0 && self.m32 == _0 && self.m33 == _1 && self.m34 == _0 &&
-        self.m44 == _1
+        let (_0, _1) = (0.0, 1.0);
```
Comment (emilio) [inline components/layout/display_list/items.rs]: This looks unrelated, and all the unrelated changes makes this somewhat hard to review.

File: components/layout/display_list/items.rs [hunk 5]
```diff
@@ -935,14 +943,17 @@ impl fmt::Debug for DisplayItem {
...
+            "{} @ {:?} {:?}",
             match *self {
-                DisplayItem::SolidColor(ref solid_color) =>
-                    format!("SolidColor rgba({}, {}, {}, {})",
-                            solid_color.color.r,
-                            solid_color.color.g,
-                            solid_color.color.b,
-                            solid_color.color.a),
+                DisplayItem::SolidColor(ref solid_color) => format!(
+                    "SolidColor rgba({}, {}, {}, {})",
```
Comment (emilio) [inline components/layout/display_list/items.rs]: Same for these, I'm fine with formatting changes, but they should be a different commit.

File: components/layout/display_list/items.rs [hunk 6]
```diff
@@ -550,13 +550,14 @@ impl ClippingRegion {
     pub fn translate(&self, delta: &LayoutVector2D) -> ClippingRegion {
         ClippingRegion {
             main: self.main.translate(delta),
-            complex: self.complex.iter().map(|complex| {
-                ComplexClipRegion {
+            complex: self.complex
+                .iter()
+                .map(|complex| ComplexClipRegion {
```
Comment (emilio) [inline components/layout/display_list/items.rs]: I think this is uglier btw, but I assume this has been done with rustfmt... Oh well.

File: components/layout/display_list/builder.rs [hunk 7]
```diff
@@ -1066,12 +1088,20 @@ impl FragmentDisplayListBuilding for Fragment {
             None,
             style.logical_border_width().to_physical(style.writing_mode),
             self.border_padding.to_physical(style.writing_mode),
+            build_border_radius(&absolute_bounds, style.get_border()),
             index,
         );
 
+        let previous_clipping_and_scrolling = state.current_clipping_and_scrolling;
```
Comment (emilio) [inline components/layout/display_list/builder.rs]: Here we could use that helper too, ideally moving the inner block to another function or what not.

**Review by emilio — COMMENTED** [review]
Generally it looks reasonable, though this is hard to review with all the unrelated formatted and behavior changes that have been introduced here. Any chance you could split this out into different commits?

@mrobinson should at least look at the clipping bits since he's more familiar than me on that.

Thank you for working on this!

**Comment by pyfisch** [comment]
> Any chance you could split this out into different commits?

There were different commits (plus some additional changes made later) but the branch can't be automatically merged with master. I think I combined all those commits before I created this PR so I didn't need to manually merge many times and build and test each time.

These are the commits: https://github.com/pyfisch/servo/tree/abcd

Do these commits help with review?
I can try to create a new PR based on these commits. Which commits can be combined and which ones should stay separate?

File: components/layout/display_list/builder.rs (hunk 3 above)
Comment (pyfisch) [reply components/layout/display_list/builder.rs]: I think using a closure is a great idea. But I would want to set the state manually as in many case only part of the time a new clipping is actually added.

```rust
state.with_clipping_and_scrolling(|state| {
    do_foo(state);
    if something {
        state.current_clipping_and_scrolling = new_clip();
    }
    do_bar(state);
})
```

File: components/gfx/platform/macos/font_context.rs (hunk 1 above)
Comment (pyfisch) [reply components/gfx/platform/macos/font_context.rs]: `#[derive()]` is still usable but it is only once used in the whole crate and only on MacOS. (I didn't first notice because on Linux it built fine.) Should I add the dependency back and use `#[derive()]` again? Btw are there platform specific dependencies?

File: components/layout/display_list/items.rs (hunk 4 above)
Comment (pyfisch) [reply components/layout/display_list/items.rs]: Sorry about making review really hard by rustfmting everything.

File: components/layout/display_list/builder.rs (hunk 7 above)
Comment (pyfisch) [reply components/layout/display_list/builder.rs]: Yes this pattern is used two times already in the file. This PR adds two more I think. The helper could handle those all.

File: components/layout/display_list/builder.rs (hunk 3 above)
Comment (emilio) [reply components/layout/display_list/builder.rs]: Ok, that makes sense :)

**Comment by emilio** [comment]
Thanks! That tree was really helpful :)

Ok, r=me on the moving the display items to layout. I can review the clipping changes tomorrow morning, or @mrobinson can too. Probably the PR title should also be adjusted.

File: components/layout/display_list/builder.rs (hunk 3 above)
Comment (pyfisch) [reply components/layout/display_list/builder.rs]: I have added `with_clipping_and_scrolling` in a new commit.

**Review by emilio — APPROVED** [review]
r=me, with comments addressed. Thank you!

File: components/layout/display_list/builder.rs [hunk 8]
```diff
@@ -858,25 +864,24 @@ impl FragmentDisplayListBuilding for Fragment {
...
-            &bounds,
-            self.node,
-            style.get_cursor(CursorKind::Default),
-            display_list_section,
-        );
-        state.add_display_item(DisplayItem::SolidColor(Box::new(SolidColorDisplayItem {
-            base: base,
-            color: background_color.to_layout(),
-        })));
+        state.with_clipping_and_scrolling(|state| {
```
[the remark this answers is not in the document]
Comment (pyfisch) [reply components/layout/display_list/builder.rs]: Maybe rename with_clipping_and_scrolling as with_element_clip?
I think this is what it does. It allows an element to have its own clip without affecting other parts of the layout

**Comment by emilio** [comment]
Thank you!

**Comment by nox** [comment]
Why do you keep closing and reopening it?

**Comment by pyfisch** [comment]
@nox because bors did not react to your comment half an hour ago. Closing and opening worked last time when the bot ignored the PR and emilo brought it back to attention.

**Comment by pyfisch** [comment]
@emilio, @nox I don't know what "test timed out" means. This PR didn't pass CI now so many times (for reasons probably outside my code) that I give up trying.

Can you merge the PR for me? Tell me if the code needs changes.

**Comment by CYBAI** [comment]
```
{"status": "FAIL", "group": "default", "message": "ReferrerPolicyTestCase is not defined", "stack": "@http://web-platform.test:8000/referrer-policy/origin-when-cross-origin/http-rp/cross-origin/http-https/iframe-tag/cross-origin.no-redirect.http.html:23:7\n", "subtest": "Referrer-Policy: Referrer Policy is set to 'origin-when-cross-origin'", "test": "/referrer-policy/origin-when-cross-origin/http-rp/cross-origin/http-https/iframe-tag/cross-origin.no-redirect.http.html", "line": 179025, "action": "test_result", "expected": "PASS"}
{"status": "OK", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/referrer-policy/origin-when-cross-origin/http-rp/cross-origin/http-https/iframe-tag/cross-origin.no-redirect.http.html", "line": 179026, "action": "test_result", "expected": "TIMEOUT"}
```
