### PR TITLE
devtools: Only highlight fragments that share the first encountered `SpatialId` for a node

### LINKED ISSUE #40851: devtool/layout: Panic on simple scenario
**Describe the bug:**
```
assertion `left == right` failed
  left: SpatialId(2, PipelineId(1, 1))
 right: SpatialId(1, PipelineId(1, 1)) (thread Script(1,1), at components\layout\display_list\mod.rs:565)
```

**To Reproduce:**
1. Save example in https://github.com/servo/servo/issues/40663#issue-3629908336 as `hit_test_z_index.html`
2. `./mach run -r <path to above file> --devtools=6080`
3. open `about:debugging` in Firefox, connect and inspect.
4. Hover over `<div>` like below.

Image

### PR DESCRIPTION
**Pull request by eerii**
Remove the assertion and only highlight the first `SpatialId` if there are multiple ones. It should be the bottom-most.

Testing: This fixes the test case at https://github.com/servo/servo/issues/40851#issuecomment-3846717049, which can only be tested manually. In general, there are not automated Devtools tests for these kind of interactions.
Fixes: #40851
Fixes: #41142

### CODE REVIEW

File: components/layout/display_list/mod.rs [hunk 1]
```diff
@@ -559,8 +559,11 @@ impl InspectorHighlight {
             maybe_box_fragment: None,
         });
 
-        // We expect all fragments generated by one node to be in the same scroll tree node and clip node
-        debug_assert_eq!(spatial_id, state.spatial_id);
+        // We only need to highlight the first `SpatialId`.
```
Comment (mrobinson) [inline components/layout/display_list/mod.rs]:
```suggestion
        // We only need to highlight the first `SpatialId`. Typically this will include the bottommost
        // fragment for a node, which generally surrounds the entire content.
```

**Review by mrobinson — APPROVED** [review]
