### PR TITLE
webgpu: Fix HTML event loop integration

### LINKED ISSUE #33601: webgpu: Update HTML event loop integration
See https://github.com/servo/servo/pull/33521#discussion_r1780911532 and https://github.com/servo/servo/pull/33521#discussion_r1780420725

### PR DESCRIPTION
**Pull request by sagudev**
rebase of https://github.com/servo/servo/pull/33673, now possible because of latest changes to update rendering stuff in servo.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #33601 
- [x] There are tests for these changes in WebGPU CTS

### CODE REVIEW

File: components/script/dom/webgpu/gpucanvascontext.rs [hunk 1]
```diff
@@ -351,33 +362,38 @@ impl GPUCanvasContextMethods<crate::DomTypeHolder> for GPUCanvasContext {
...
         // Step 6
         Ok(current_texture)
     }
 }
 
 impl Drop for GPUCanvasContext {
     fn drop(&mut self) {
+        if let HTMLCanvasElementOrOffscreenCanvas::HTMLCanvasElement(ref canvas) = self.canvas {
+            let document = document_from_node(&**canvas);
+            document.remove_webgpu_context(self);
```
Comment (jdm) [inline components/script/dom/webgpu/gpucanvascontext.rs:395]: Interacting with DOM objects from Drop implementations is unpredictable (#26488). Consider storing the document's hashmap in a `Rc<RefCell>` so that the canvas context can access it directly instead!

Comment (sagudev) [reply components/script/dom/webgpu/gpucanvascontext.rs:395]: Right, this totally slipped my mind.

**Comment by gterzian** [comment]
Re [this](https://github.com/servo/servo/pull/33673#issuecomment-2418906125), note that we have now moved to almost only doing a single reflow at the end of update the rendering. See https://github.com/servo/servo/issues/31871

File: components/script/script_thread.rs [hunk 2]
```diff
@@ -1621,6 +1621,9 @@ impl ScriptThread {
 
             // TODO(#31871): Update the rendering: consolidate all reflow calls into one here?
```
Comment (gterzian) [inline components/script/script_thread.rs:1622]: Note: unrelated but this TODO can be removed now. Was missed previously.

**Comment by gterzian** [comment]
For the worker part(do we have offscreen canvas working with webgpu yet?) I have filed https://github.com/servo/servo/issues/34637

**Comment by sagudev** [comment]
> For the worker part(do we have offscreen canvas working with webgpu yet?) I have filed #34637

IIRC all offscreen support is unfinished/disabled by default, so I didn't really bother with it. Workers are in same state too IIRC, but I might be wrong.

**Review by gterzian — APPROVED** [review]
LGTM

**Comment by sagudev** [comment]
I just checked and firefox does update the wr image (so update the rendering of context) as part of reflow/layout. So inverse of what we did here. cc @gterzian

**Comment by mrobinson** [comment]
> I just checked and firefox does update the wr image (so update the rendering of context) as part of reflow/layout. So inverse of what we did here. cc @gterzian

Funny timing of your comment as I just posted #37703, which consolidates all the canvas flushes into one place. I think it doesn't matter too much whether this happens in `Window::reflow` or `ScriptThread::update_the_rendering` (I have preference for the latter), but it does make sense that all canvases are flushed at the same time.

**Comment by sagudev** [comment]
I actually think this should be done in reflow (step 22 of update the rendering). And yeah, I want to consolidate that too.
