### PR TITLE
compositor|script: Update script's active_touch_points when hit tests on compositor fail

### LINKED ISSUE #37763: When touchup hit test fails, script's event.touches.length is incorrect.
**Describe the bug:**
Tochdown executes normally, but touchup fails during hittest and does not send a touchup event to the script, causing the script to save an incorrect number of active_touch_points.
The application receives an incorrect event.touches.length, causing a logic error and preventing the carousel from sliding.

**To Reproduce:**
Open the https://m.huaweimossel.com page, and the carousel slides normally. After several consecutive quick up and down swipes, the carousel cannot be swiped.

**Platform:**
openharmony

### PR DESCRIPTION
**Pull request by kongbai1996**
[RootCause]:Tochdown executes normally, but touchup fails during hittest and does not send a touchup event to the script, causing the script to save an incorrect number of active_touch_points. The application receives an incorrect event.touches.length, causing a logic error and preventing the carousel from sliding. 
[Solution]:
When hit test on compositor fails, we also need to send the EmbedderToConstellationMessage::ForwardInputEvent message to constellation. In the script's handle_touch_event, if it exits early, we also need to update active_touch_points.

Testing: 
Fixes: #37763

### CODE REVIEW

File: components/compositing/webview_renderer.rs [hunk 1]
```diff
@@ -370,15 +370,12 @@ impl WebViewRenderer {
             .hit_test_at_point(point, get_pipeline_details)
         {
             Ok(hit_test_results) => hit_test_results,
-            Err(HitTestError::EpochMismatch) => {
+            Err(_) => {
```
Comment (xiaochengh) [inline components/compositing/webview_renderer.rs]: What was the exact reason causing this failure?

I think we are intentionally not retrying other errors, and the current retry mechanism is designed for epoch mismatches only. For other types of errors, we need a better analysis to see how to deal with them.

@longvatrong111 correct me if I'm wrong

File: components/script/dom/document.rs [hunk 2]
```diff
@@ -2354,6 +2356,34 @@ impl Document {
         }
     }
 
+    // If hittest fails, we still need to update the active point information.
+    fn update_active_touch_points_when_early_return(&self, event: TouchEvent) {
```
Comment (xiaochengh) [inline components/script/dom/document.rs:2360]: Does this part already fix the issue on its own?

File: components/compositing/webview_renderer.rs (hunk 1 above)
Comment (kongbai1996) [reply components/compositing/webview_renderer.rs]: There are some cases where there is no hittest result list, the specific reason has not been analyzed yet, I will analyze it later.

File: components/script/dom/document.rs (hunk 2 above)
Comment (kongbai1996) [reply components/script/dom/document.rs:2360]: In addition to this, we also need to send a message to constellation when hittest fails in `dispatch_pending_point_input_events`, instead of returning directly.
https://github.com/servo/servo/blob/80a7de8c9c25972cb2d9a545896ec2d344c6b1c7/components/compositing/webview_renderer.rs#L425-L429

**Comment by kongbai1996** [comment]
hittestfailed

**Comment by xiaochengh** [comment]
Could you reupload the diagram with a better resolution? I can't see the text in it...

File: components/script/dom/document.rs (hunk 2 above)
Comment (xiaochengh) [reply components/script/dom/document.rs:2360]: Thanks! If extra retries are not needed, can we remove that from this PR?

**Comment by kongbai1996** [comment]
> Could you reupload the diagram with a better resolution? I can't see the text in it...

Updated

File: components/script/dom/document.rs (hunk 2 above)
Comment (kongbai1996) [reply components/script/dom/document.rs:2360]: A retry mechanism is still needed. Most of the time, retries are successful, and only a small portion of retries fail.

File: components/compositing/webview_renderer.rs (hunk 1 above)
Comment (kongbai1996) [reply components/compositing/webview_renderer.rs]: I checked this situation. When the problem occurs, the touch point information given by the web component of openharmony is incorrect, and the y value is negative, so there is no HitTestResult.

Comment (longvatrong111) [reply components/compositing/webview_renderer.rs]: @xiaochengh I confirm that current retry is designed for only epoch mismatch. Retrying time is the beginning of the next frame, which is only reasonable for epoch mismatch.
For other reasons, we may need different retrying time.

**Review by xiaochengh — COMMENTED** [review]
Thanks for the updates! I think this is how we should move forward:
1. Fix the touch point information given from OHOS, since that seems to be the root cause of this bug. This should be done in a separate PR
2. In this PR, revert everything related to retry, and only let `script` reset active touch points when there are failed hit tests

Unconditionally retrying all hit tests isn't correct as the current mechanism is only supposed to work for epoch mismatches. So let's no do that.

File: components/compositing/webview_renderer.rs (hunk 1 above)
Comment (kongbai1996) [reply components/compositing/webview_renderer.rs]: The original logic is retained. Other errors are not retried. Only epoch mismatch is retried.

**Comment by kongbai1996** [comment]
> Unconditionally retrying all hit tests isn't correct as the current mechanism is only supposed to work for epoch mismatches. So let's no do that.

For the HitTestErrorOthers case, we will not add retry logic and keep the original handling method. Is that correct?

**Comment by kongbai1996** [comment]
If we remove all the content related to retrying, there is a higher probability of hitting a test failure, which could result in a certain probability of the page not being able to slide with touch. I think we still need to retry once, and if the retry fails, then go to the logic of only updating the touch points.
More than 10 percent of the hit tests on the Moselle Mall page failed

File: components/compositing/webview_renderer.rs [hunk 3]
```diff
@@ -389,15 +404,19 @@ impl WebViewRenderer {
             InputEvent::MouseLeave(_) |
             InputEvent::MouseMove(_) |
             InputEvent::Wheel(_) => {
-                self.global
-                    .borrow_mut()
-                    .update_cursor_from_hittest(point, &result);
+                if let Some(ref result) = result {
```
Comment (xiaochengh) [inline components/compositing/webview_renderer.rs:407]: nit: Could you revert this block?

File: components/compositing/webview_renderer.rs [hunk 4]
```diff
@@ -345,7 +345,22 @@ impl WebViewRenderer {
...
+        while let Some(event) = self.pending_point_input_events.borrow_mut().pop_front() {
+            // TODO: Add multiple retry later if needed.
+            self.dispatch_point_input_event_with_retry(event, false);
+        }
+    }
+
+    pub(crate) fn dispatch_point_input_event_with_retry(
+        &self,
+        mut event: InputEvent,
+        need_retry: bool,
```
Comment (xiaochengh) [inline components/compositing/webview_renderer.rs]:
```suggestion
    pub(crate) fn dispatch_point_input_event_internal(
        &self,
        mut event: InputEvent,
        retry_on_error: bool,
```

**Review by xiaochengh — APPROVED** [review]
LGTM with some small nits

**Comment by xiaochengh** [comment]
Discussed with @kongbai1996 offline:
1. This PR will only update active touch status on failed hit tests, but not alter any retry logic
2. We may investigate and fix the root cause of hit test failures in a separate attempt

**Comment by xiaochengh** [comment]
Please also modify the PR title and description, since this PR no longer modifies the retry mechanism

File: components/compositing/webview_renderer.rs (hunk 3 above)
Comment (kongbai1996) [reply components/compositing/webview_renderer.rs:407]: Because I changed the type of `result` from `CompositorHitTestResul` to `Option<CompositorHitTestResult>`, a piece of logic is needed here to determine whether result has a value

File: components/compositing/webview_renderer.rs (hunk 4 above)
Comment (kongbai1996) [reply components/compositing/webview_renderer.rs]: Modified

**Review by xiaochengh — APPROVED** [review]
