### PR TITLE
libservo: Make Servo (and servoshell) more resilient against extreme sizes

### LINKED ISSUE #36763: panic: called `Option::unwrap()` on a `None` value via compositing::compositor::IOCompositor::render_inner
This seems similar to https://github.com/servo/servo/issues/36701 but via a different path:

Minimal testcase:

```
<form id="form" target="_blank"></form>
<script>
  window.addEventListener("load", _ => {
    form.submit();
    window.resizeTo(-1, -1);
  });
</script>
```

System: Linux
Version: Servo 0.0.1-107fd2546
Command: `./servo/servo --headless`

```
called `Option::unwrap()` on a `None` value (thread main, at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/euclid-0.22.11/src/size.rs:323)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::panic
   8: core::option::unwrap_failed
   9: compositing::compositor::IOCompositor::render_inner
  10: servoshell::desktop::app_state::RunningAppState::repaint_servo_if_necessary
  11: servoshell::main
  12: std::sys::backtrace::__rust_begin_short_backtrace
  13: main
  14: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  15: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
  16: _start
```

### LINKED ISSUE #36841: panic: Attempting to create a 0x35000 window/document
It seems we are reaching an out of memory with the following minimal testcase:

```
<!DOCTYPE html>
<form id="form" target="_blank">
<script>
  form.submit();
  window.resizeTo(1,20000);
</script>
```

System: Linux
Version: Servo 0.0.1-43edab336
Command: `./servo/servo`

```
[2025-05-05T06:03:09Z ERROR winit::platform_impl::linux] X11 error: XError {
        description: "BadAlloc (insufficient resources for operation)",
        error_code: 11,
        request_code: 149,
        minor_code: 7,
    }
[2025-05-05T06:03:09Z ERROR winit::platform_impl::linux] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
Attempting to create a 0x35000 window/document (thread main, at /home/runner/.cargo/git/checkouts/webrender-a8b399ecb6c2da85/ae2477d/webrender/src/render_api.rs:1430)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: webrender::render_api::window_size_sanity_check
   8: servo::webview::WebView::resize
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
  12: egui::containers::frame::Frame::show_dyn
  13: egui::containers::panel::CentralPanel::show_inside_dyn
  14: egui::containers::panel::CentralPanel::show_dyn
  15: egui::context::Context::run
  16: servoshell::desktop::minibrowser::Minibrowser::update
  17: <servoshell::desktop::app::App as winit::application::ApplicationHandler<servoshell::desktop::events_loop::WakerEvent>>::window_event
  18: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  19: winit::platform_impl::linux::x11::EventLoop<T>::drain_events::{{closure}}
  20: winit::platform_impl::linux::x11::event_processor::EventProcessor::process_xevent
  21: winit::platform_impl::linux::x11::EventLoop<T>::run_on_demand
  22: servoshell::main
  23: std::sys::backtrace::__rust_begin_short_backtrace
  24: main
  25: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  26: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
  27: _start
```

### LINKED ISSUE #39141: panic: min > max, or either was NaN. min = 0.0, max = -4277071600.0 (at /home/runner/.rustup/toolchains/1.89.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/f32.rs:1405)
Minimal testcase (to run in headless mode)

```html
<!DOCTYPE html>
<form id="form" onchange="" target="T"></form>
<script>
window.scroll();
window.resizeTo(-1, 0);
form.submit();
</script>
```

System: Linux
Version: Servo 0.0.1-aac6aa6c7
Command: `servo/servo -z`

```
min > max, or either was NaN. min = 0.0, max = -4277071600.0 (thread Script(1,5), at /home/runner/.rustup/toolchains/1.89.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/f32.rs:1405)
   0: servoshell::backtrace::print
   1: servoshell::panic_hook::panic_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: __rustc::rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::f32::<impl f32>::clamp::do_panic::runtime
   8: script::dom::window::Window::scroll
   9: script_bindings::codegen::GenericBindings::WindowBinding::Window_Binding::scroll::{{closure}}
  10: mozjs::panic::wrap_panic
  11: script_bindings::codegen::GenericBindings::WindowBinding::Window_Binding::scroll
  12: CallJitMethodOp
  13: script_bindings::utils::generic_call
  14: script_bindings::utils::generic_method
  15: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructENS_10CallReasonE
  16: _ZN2js9InterpretEP9JSContextRNS_8RunStateE
  17: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  18: _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEENS3_IP8JSObjectEENS2_13MutableHandleINS2_5ValueEEE
  19: _Z16JS_ExecuteScriptP9JSContextN2JS6HandleIP8JSScriptEENS1_13MutableHandleINS1_5ValueEEE
  20: script::dom::globalscope::GlobalScope::evaluate_script_on_global_with_result
  21: script::dom::html::htmlscriptelement::HTMLScriptElement::execute
  22: script::dom::html::htmlscriptelement::HTMLScriptElement::prepare
  23: script::dom::servoparser::ServoParser::parse_sync
  24: <script::dom::servoparser::ParserContext as net_traits::FetchResponseListener>::process_response_chunk
  25: script::script_thread::ScriptThread::handle_msg_from_script
  26: script::script_thread::ScriptThread::handle_msgs::{{closure}}
  27: script::script_thread::ScriptThread::handle_msgs
  28: std::sys::backtrace::__rust_begin_short_backtrace
  29: core::ops::function::FnOnce::call_once{{vtable.shim}}
  30: std::sys::pal::unix::thread::Thread::new::thread_start
  31: start_thread
             at ./nptl/pthread_create.c:447:8
  32: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
```

### PR DESCRIPTION
**Pull request by mrobinson**
Make several changes which should address panics and inconsistent
behavior around attempts to set extreme sizes:

1. Limit the minimum size of the `RenderingContext` to 1 pixel by 1
   pixel. This should address problems where users of the API try to
   directly set the size to a zero or negative dimension. In addition,
   improve the documentation around `WebView::resize` to mention this.
2. Clamp values sent in the `WebViewDelegate::request_resize_to` method
   to be at least 1x1. This prevents Servo from sending nonsense values
   to embedders. Improve documentation in this method.
3. In servoshell:
    - More consistently clamp inner and outer window size values.
    - Clamp all resize values to the available screen size, so that
      large screen sizes aren't processed directly.

Testing: This change fixes an existing WPT and adds two new API tests.
Fixes: #36763.
Fixes: #36841.
Fixes: #39141.

### CODE REVIEW

**Comment by Loirooriol** [comment]
> Testing: It is difficult to write an automated test for this

Why not the code from the issues as crashtests?

**Comment by mrobinson** [comment]
> Why not the code from the issues as crashtests?

They use a form to cause a loading loop to cause the crash. I'm not sure the WPT test harness supports this kind of test.

**Comment by mrobinson** [comment]
That said, I might be able to test some of these changes using an API test -- just perhaps not the original crash.

File: ports/servoshell/desktop/app_state.rs [hunk 1]
```diff
@@ -585,10 +586,13 @@ impl WebViewDelegate for RunningAppState {
     }
 
     fn request_resize_to(&self, webview: servo::WebView, requested_outer_size: DeviceIntSize) {
+        // Clamp the size to a reasonable value as these numbers come more-or-less directly from web content.
+        // In our case, we do not let web content grow the window beyond the available screen size.
+        let maximum_size = self.inner().window.screen_geometry().available_size;
```
Comment (sebsebmc) [inline ports/servoshell/desktop/app_state.rs]: In the case of multi-monitor setups, if someone tries to make a window span multiple monitors, what would happen here?

**Comment by Loirooriol** [comment]
> I'm not sure the WPT test harness supports this kind of test.

Pretty tricky the various nonsensical browser bugs that I encountered, but #39211 is at least something.

**Comment by yezhizhen** [comment]
There is a webdriver test for this. Can you check the failed one?

File: components/servo/webview.rs [hunk 2]
```diff
@@ -27,6 +27,8 @@ use crate::javascript_evaluator::JavaScriptEvaluator;
 use crate::webview_delegate::{DefaultWebViewDelegate, WebViewDelegate};
 use crate::{ConstellationProxy, Servo, WebRenderDebugOption};
 
+pub(crate) const MINIMUM_WEBVIEW_SIZE: Size2D<i32, DevicePixel> = Size2D::new(1, 1);
```
Comment (yezhizhen) [inline components/servo/webview.rs:30]: There is a failed webdriver test for this. We should increase the number here.

https://github.com/servo/servo/blob/d469e5e564aa97dcb33c898a5490ea4aea35cbeb/tests/wpt/tests/webdriver/tests/classic/set_window_rect/set.py#L287-L290

**Review by yezhizhen — CHANGES_REQUESTED** [review]

File: ports/servoshell/desktop/app_state.rs (hunk 1 above)
Comment (mrobinson) [reply ports/servoshell/desktop/app_state.rs]: Servoshell isn't meant to be a real browser and doesn't have great multi-monitor support, so it's okay to add limitations in order to ensure that crashes don't happen. If we want to prioritize proper multi-monitor support I think we can do that at a later time.

File: components/servo/webview.rs (hunk 2 above)
Comment (mrobinson) [reply components/servo/webview.rs:30]: It's actually not this that is causing the issue, but the fact that the value isn't clamped when set via WebDriver for headless windows. I've corrected this.

**Comment by mrobinson** [comment]
I've uploaded a new version of this change which marks @Loirooriol's new test as passing as well as adding two new API tests.

File: ports/servoshell/desktop/app_state.rs (hunk 1 above)
Comment (mrobinson) [reply ports/servoshell/desktop/app_state.rs]: I now clamp this value to two times the screen size. It seems that WebDriver is checking whether or not the browser window can grow larger than the screen size (for some reason), though we are currently failing that test due to some unrelated issue.

**Review by yezhizhen — APPROVED** [review]
