### PR TITLE
Fix namespaces of elements created in XML documents

### LINKED ISSUE #14095: Fix namespaces of elements created in XML documents
Step 6 of [the spec](https://dom.spec.whatwg.org/#dom-document-createelement) is not correctly implemented, and elements created in XML documents also get the HTML namespace where they shouldn't.

Files:
 * components/script/dom/document.rs
 * tests/wpt/metadata/dom/nodes/Node-properties.html.ini
 * tests/wpt/web-platform-tests/dom/nodes/Node-properties.html

### PR DESCRIPTION
**Pull request by cu1t**
Correctly implement following step of [Dom Document Spec](https://dom.spec.whatwg.org/#dom-document-createelement):
> Let namespace be the HTML namespace, if the context object is an HTML document or context object’s content type is "application/xhtml+xml", and null otherwise.

Note, this will make following test in `tests/wpt/web-platform-tests/dom/nodes/Document-constructor.html` to fail, so related .ini file added to mark it as such:
```
test(function() {
  var doc = new Document();
  var a = doc.createElement("a");
  // In UTF-8: 0xC3 0xA4
  a.href = "http://example.org/?\u00E4";
  assert_equals(a.href, "http://example.org/?%C3%A4");
}, "new Document(): URL parsing")
```
I'm not very familiar with specs, but from quick look at it, I'm doubtfull that it is valid in the first place. This is an "application/xml" document, so I don't see why it should encode a.href. Firefox also fails that.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14095 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because because there are already tests which were being ignored

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16472)

### CODE REVIEW

File: components/script/dom/document.rs [hunk 1]
```diff
@@ -2772,7 +2772,14 @@ impl DocumentMethods for Document {
         if self.is_html_document {
             local_name.make_ascii_lowercase();
         }
-        let name = QualName::new(ns!(html), LocalName::from(local_name));
+
+        let ns = if self.is_html_document || self.content_type == DOMString::from("application/xhtml+xml") {
```
Comment (nox) [inline components/script/dom/document.rs]: Don't create a `DOMString` just for the equality check, the type `DOMString` implements `PartialEq<&str>`.

```rust
self.content_type == "application/xhtml+xml"
```

**Comment by nox** [comment]
Thanks for your contribution! Just a small change to do and this will be ready to be merged.

**Comment by cu1t** [comment]
Thanks for review! Fixed.

**Comment by jdm** [comment]
@bors-servo: retry
* see if https://github.com/servo/saltfs/issues/636 is consistent

**Comment by jdm** [comment]
Also, this happened:
```

  ▶ Unexpected subtest result in /_mozilla/mozilla/document_head.html:
  │ FAIL [expected PASS] append head to a new document
  │   → assert_true: test2-1, append head to a new document: should be HTMLHeadElement expected true got false
  │ 
  │ @http://web-platform.test:8000/_mozilla/mozilla/document_head.html:20:17
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1409:20
  │ test@http://web-platform.test:8000/resources/testharness.js:501:9
  └ @http://web-platform.test:8000/_mozilla/mozilla/document_head.html:14:13
```

**Comment by aneeshusa** [comment]
@bors-servo retry
- Buildbot didn't fetch the right commit

**Comment by cu1t** [comment]
Failing test seems to be similar case to one with `Document-constructor.html` (marked failing lines with `<--- here`):
```
test(function() {
    var new_document = new Document();
    new_document.appendChild(new_document.createElement("html"));
    var new_head = new_document.createElement("head");

    assert_not_equals(new_head, null, "test2-0, append head to a new document");
    assert_true(new_head instanceof HTMLHeadElement, "test2-1, append head to a new document: should be HTMLHeadElement"); <--- here
    assert_equals(new_head && new_head.tagName, "head", "test2-2, append head to a new document");

    // Document::head is read-only.
    new_document.head = new_head;
    assert_equals(new_document.head, null, "test2-3, append head to a new document");

    new_document.documentElement.appendChild(new_head); <--- this WILL create element
    assert_equals(new_document.head, new_head, "test2-4, append head to a new document"); <--- here
}, "append head to a new document");
```
From what I see, test expects `new_document` to be treated as `html`, but it gets treated as `xml` instead. Should I mark this as failing too then?

**Comment by jdm** [comment]
We can fix that test by doing `var new_head = new_document.createElementNS('http://www.w3.org/1999/xhtml', 'head');`.

**Comment by cu1t** [comment]
Still fails at 2-4. Change last line to `assert_equals(new_document.head, null, "test2-4, append head to a new document");` perhaps? Or remove it altogether?

**Comment by jdm** [comment]
That can be fixed by changing the other use of createElement to use createElementNS as well.

**Comment by jdm** [comment]
In fact, please modify all uses in that file, since the subsequent test also uses the Document constructor.

**Comment by jdm** [comment]
Looks good! You will need to run `./mach update-manifest` and commit the results, then squash all of the commits into one, please.

**Comment by cu1t** [comment]
Done.

**Comment by jdm** [comment]
@bors-servo: r=nox
Thanks!
