### PR TITLE
dom: Optimize IFrameCollection::validate

### LINKED ISSUE #38131: IFrameCollection::validate accounts for 30% of script time in DOM heavy scenarios
**Describe the bug:**
Using perf (and tracing) on a DOM heavy mini-app page showed  that around 30% of the time in script during page loading is spent in the slow-path of `IFrameCollection::validate `. 
validate has a fast-path intended to skip validating when nothing has changed, but currently every dom version increment triggers a re-validation. Relevant todo comment before the early return:
https://github.com/servo/servo/blob/86ea2641f807014ddd2c5a7d7f2c98e91f1072d2/components/script/iframe_collection.rs#L43-L51

@coding-joedow verified that end to end performance improves by multiple seconds when applying the following patch

<details>
  <summary> Invalidation patch</summary>

```
diff --git a/components/script/dom/document.rs b/components/script/dom/document.rs
index df24b04ed83..33eebd96554 100644
--- a/components/script/dom/document.rs
+++ b/components/script/dom/document.rs
@@ -3368,6 +3368,10 @@ impl Document {
         self.iframes.borrow_mut()
     }
 
+    pub(crate) fn invalidate_iframs_collection(&self) {
+        self.iframes.borrow_mut().invalidate();
+    }
+
     pub(crate) fn get_dom_interactive(&self) -> Option<CrossProcessInstant> {
         self.dom_interactive.get()
     }
@@ -4164,7 +4168,7 @@ impl Document {
             scripts: Default::default(),
             anchors: Default::default(),
             applets: Default::default(),
-            iframes: Default::default(),
+            iframes: RefCell::new(IFrameCollection::new()),
             style_shared_lock: {
                 /// Per-process shared lock for author-origin stylesheets
                 ///
diff --git a/components/script/dom/htmliframeelement.rs b/components/script/dom/htmliframeelement.rs
index be2641a0fee..dd7eec5c8b0 100644
--- a/components/script/dom/htmliframeelement.rs
+++ b/components/script/dom/htmliframeelement.rs
@@ -813,6 +813,14 @@ impl VirtualMethods for HTMLIFrameElement {
         }
     }
 
+    fn bind_to_tree(&self, context: &super::node::BindContext, can_gc: CanGc) {
+        if let Some(s) = self.super_type() {
+            s.bind_to_tree(context, can_gc);
+        }
+
+        self.owner_document().invalidate_iframs_collection();
+    }
+
     fn unbind_from_tree(&self, context: &UnbindContext, can_gc: CanGc) {
         self.super_type().unwrap().unbind_from_tree(context, can_gc);
 
@@ -865,5 +873,7 @@ impl VirtualMethods for HTMLIFrameElement {
         // a new iframe. Without this, the constellation gets very
         // confused.
         self.destroy_nested_browsing_context();
+
+        self.owner_document().invalidate_iframs_collection();
     }
 }
diff --git a/components/script/iframe_collection.rs b/components/script/iframe_collection.rs
index 7626a190d81..623a917dc73 100644
--- a/components/script/iframe_collection.rs
+++ b/components/script/iframe_collection.rs
@@ -34,9 +34,22 @@ pub(crate) struct IFrameCollection {
     document_version: Cell<u64>,
     /// The `<iframe>`s in the collection.
     iframes: Vec<IFrame>,
+    invalid: bool,
 }
 
 impl IFrameCollection {
+    pub(crate) fn new() -> Self {
+        Self {
+            document_version: Cell::new(0),
+            iframes: vec![],
+            invalid: true,
+        }
+    }
+
+    pub(crate) fn invalidate(&mut self) {
+        self.invalid = true;
+    }
+
     /// Validate that the collection is up-to-date with the given [`Document`]. If it isn't up-to-date
     /// rebuild it.
     pub(crate) fn validate(&mut self, document: &Document) {
@@ -44,8 +57,12 @@ impl IFrameCollection {
         // when it isn't necessary. A better signal might be if any `<iframe>` nodes have
         // been connected or disconnected.
         let document_node = DomRoot::from_ref(document.upcast::<Node>());
-        let document_version = document_node.inclusive_descendants_version();
-        if document_version == self.document_version.get() {
+        // let document_version = document_node.inclusive_descendants_version();
+        // if document_version == self.document_version.get() {
+        //     return;
+        // }
+
+        if !self.invalid {
             return;
         }
 
@@ -75,7 +92,8 @@ impl IFrameCollection {
                 }
             })
             .collect();
-        self.document_version.set(document_version);
+        // self.document_version.set(document_version);
+        self.invalid = false;
     }
 
     pub(crate) fn get(&self, browsing_context_id: BrowsingContextId) -> Option<&IFrame> {

```

</details>

**To Reproduce:**
Currently no minimized test case available.
The behavior is observed with the following function backtrace:

Entrypoint `get_own_property_descriptor` calls `window.NamedGetter` calls `document.iframes()` calls `IframeCollection.validate()`

**Platform:**
Tested on a HarmonyOS phone

### PR DESCRIPTION
**Pull request by jschwe**
The `IFrameCollection` was previously rebuilt too often. This PR tries to address the todo, to only rebuild the IFrameCollection when necessary.

Testing: `CSS Selector Invalidation: :has() invalidation should not be O(n^2)` wpt-test changed status from timeout to failed.
Fixes: #38131 (IFrameCollection::validate accounts for 30% of script time in DOM heavy scenarios)

Co-authored-by: sharpshooter_pt <ibluegalaxy_taoj@163.com>

### CODE REVIEW

File: components/script/dom/htmliframeelement.rs [hunk 1]
```diff
@@ -813,6 +813,13 @@ impl VirtualMethods for HTMLIFrameElement {
         }
     }
 
+    fn bind_to_tree(&self, context: &BindContext, can_gc: CanGc) {
```
Comment (yezhizhen) [inline components/script/dom/htmliframeelement.rs:816]: It might be worth mentioning this overriding, as it is the key of optimization.

**Review by yezhizhen — APPROVED** [review]
LGTM.

File: components/script/iframe_collection.rs [hunk 2]
```diff
@@ -29,25 +28,31 @@ pub(crate) struct IFrame {
...
     iframes: Vec<IFrame>,
+    /// When true, the collection will need to be rebuilt.
+    invalid: bool,
 }
 
 impl IFrameCollection {
+    pub(crate) fn new() -> Self {
+        Self {
+            iframes: vec![],
+            invalid: true,
```
Comment (yezhizhen) [inline components/script/iframe_collection.rs:41]: Nice optimization for lazy init before first access.

**Review by jdm — APPROVED** [review]
