### PR TITLE
Send early DevToolsHttpRequest and relocate response reporting to main_fetch

### LINKED ISSUE #37869: HTTP requests with cached responses do not appear in the network monitor
To reproduce:
* `./mach run https://servo.org/download/ --devtools=6080`
* connect to the devtools server from firefox, open the network monitor
* refresh the page

The only code in the network stack that notifies the devtools server about the HTTP request and response is in https://github.com/servo/servo/blob/3ba5b89ef20575f96de7889c94eac2a6e56b8312/components/net/http_loader.rs#L2006 and https://github.com/servo/servo/blob/3ba5b89ef20575f96de7889c94eac2a6e56b8312/components/net/http_loader.rs#L2012, inside of http_network_fetch. Meanwhile, cached responses are resolved in http_network_or_cache_fetch, which skips the network when a cached response is discovered.

cc @uthmaniv

### PR DESCRIPTION
**Pull request by uthmaniv**
This change refactors how we notify DevTools about network activity so that all fetches (even those served from cache) appear correctly in the Network panel, and so that DevTools sees request metadata as soon as possible rather than waiting until the end of a full HTTP cycle.
- Before, we only send DevTools events inside http_network_fetch, so cached responses (which skip that path) never show up. By emitting a minimal HttpRequest event at the very start of main_fetch (with URL, method, pipeline and browsing IDs), we guarantee every fetch shows up immediately. 
- Then, by moving HttpResponse notifications out of http_network_fetch into main_fetch (right after process_response and process_response_eof), we ensure DevTools gets status, header, and completion events for both network and cache hits. Leveraging nullable fields in NetworkEventActor lets us incrementally fill in timing, header, and body data later, improving DevTools’ visibility.
Testing: Ran servo with `--devtools=6080` flag, cached responses now appear in the network panel
Fixes: https://github.com/servo/servo/issues/37869

### CODE REVIEW

**Review by jdm — CHANGES_REQUESTED** [review]
Huh, I'm surprised this works as well as it does! Can we move all the code that is involved in creating the message for the devtools into the send_request/response_for_devtools functions? If not, can we move it into different functions instead? It's a lot of code that is repeated and interrupts the reader if they only care about the fetch implementation.

**Comment by atbrakhi** [comment]
It would be really nice to have some tests for the Network panel. We already have some tests for the `Debugger > Source` panel [servo/devtools_tests](https://github.com/servo/servo/tree/main/python/servo/devtools_tests)

**Comment by jdm** [comment]
> It would be really nice to have some tests for the Network panel. We already have some tests for the `Debugger > Source` panel [servo/devtools_tests](https://github.com/servo/servo/tree/main/python/servo/devtools_tests)

We're planning on adding some tests once we have the functionality working as expected. There's been a lot of iteration so far as we figure out what the protocol output should look like.

**Comment by uthmaniv** [comment]
> It would be really nice to have some tests for the Network panel. We already have some tests for the `Debugger > Source` panel [servo/devtools_tests](https://github.com/servo/servo/tree/main/python/servo/devtools_tests)

Yes, we will work on it

**Comment by uthmaniv** [comment]
> Huh, I'm surprised this works as well as it does! Can we move all the code that is involved in creating the message for the devtools into the send_request/response_for_devtools functions? If not, can we move it into different functions instead? It's a lot of code that is repeated and interrupts the reader if they only care about the fetch implementation.

ok sure, thanks for the feedback

File: components/net/http_loader.rs [hunk 1]
```diff
@@ -2057,10 +2052,16 @@ async fn http_network_fetch(
 
     if let Some(ref sender) = devtools_sender {
         let sender = sender.lock().unwrap();
-        if let Some(m) = msg {
-            send_request_to_devtools(m, &sender);
+        if let Some(ChromeToDevtoolsControlMsg::NetworkEvent(_, NetworkEvent::HttpRequest(devtools_request))) = msg {
+            let update_msg = ChromeToDevtoolsControlMsg::NetworkEvent(
+                request.id.0.to_string(),
+                NetworkEvent::HttpRequestUpdate(devtools_request),
```
Comment (jdm) [inline components/net/http_loader.rs]: Can we change the code in obtain_resoonse to return a NetworkEventUpdate instead of creating that message here?

File: components/shared/devtools/lib.rs [hunk 2]
```diff
@@ -432,7 +432,7 @@ pub enum CachedConsoleMessage {
     ConsoleLog(ConsoleLog),
 }
 
-#[derive(Debug, PartialEq)]
+#[derive(Debug, PartialEq,Clone)]
```
Comment (jdm) [inline components/shared/devtools/lib.rs]: I don't see this type being cloned anywhere. Is this needed?

Comment (jdm) [reply components/shared/devtools/lib.rs]: I see this was already addressed.

**Review by jdm — APPROVED** [review]
Nice work!

**Comment by uthmaniv** [comment]
> Nice work!

Thanks for the guidance, sir
