### PR TITLE
Fix the incorrect percentage calculation of width (#34665)

### LINKED ISSUE #34665: Percentage calculation of width is incorrect
**Describe the bug:**

Child boxs will be splitted to two lines. Expected result is that child boxes will be placed in one line. It is because the child size is larger than expected.

actual

image

expect

image

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .child {
            width: 25%;
            height: 30px;
            float: left;
        }
    </style>
</head>
<body>
    <div style="float: left; width: 363.9px;">
        <div class="child" style="background-color: red;"></div>
        <div class="child" style="background-color: green"></div>
        <div class="child" style="background-color: yellow"></div>
        <div class="child" style="background-color: black"></div>
    </div>
</body>
</html>
```

**Platform:**
All

### PR DESCRIPTION
**Pull request by Asun0204**
The conversion from percentage * basis to Au is unreasonably. Round method is used in this process and the size of box is larger.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #34665 (GitHub issue number if applicable)
- [X] There are tests for these changes

### CODE REVIEW

File: components/layout_2020/geom.rs [hunk 1]
```diff
@@ -754,7 +754,18 @@ impl LogicalVec2<Size<LengthPercentage>> {
...
                 .inline
-                .maybe_map(|v| v.maybe_to_used_value(basis.inline))
+                .maybe_map(|v| {
+                    // Resolves child box inside parent with percentage width css style has larger width and will be
+                    // splited to multiply lines. It is a solution to avoid the problem of round and truncated method
+                    // on Au and CSSPercentage.
+                    if v.to_percentage().is_some() && basis.inline.is_some() {
+                        Some(Au::from_f32_px(
+                            v.to_pixel_length(basis.inline?).px().floor(),
+                        ))
```
Comment (jschwe) [inline components/layout_2020/geom.rs:764]:
```suggestion
                    if v.to_percentage().is_some() {
                        basis.inline.map(|inline| Au::from_f32_px(v.to_pixel_length(inline).px().floor()))
```

I'm not familiar with this code, so I can't comment on the correctness, but I believe we can simplify your code by using map

**Review by Loirooriol — CHANGES_REQUESTED** [review]
This would force percentages to resolve to a whole number of app units, which is bad.
Also, this isn't covering all cases of `to_used_value` and `maybe_to_used_value`, which is inconsistent.
It would be better to either:
- Add a new method in Au which is like `from _f32_px` but truncating instead of rounding. Then modify `to_used_value` and `maybe_to_used_value` in Stylo to use that.
- Modify `from_f32_px` itself, if that doesn't break anything in Firefox nor Servo.

File: components/layout_2020/geom.rs (hunk 1 above)
Comment (Asun0204) [reply components/layout_2020/geom.rs:764]: I'm not familiar with rust, do you mean the following usage?

```rust
v.to_percentage().map_or_else(
    || v.maybe_to_used_value(basis.inline),
    |_| {
        Some(Au::from_f32_px(
            v.to_pixel_length(basis.inline?).px().floor(),
        ))
    },
)
```

**Comment by Loirooriol** [comment]
Also, the current behavior isn't technically "incorrect". It indeed seems beneficial to change it, but the specs basically leave subpixel arithmetic up to the UAs.

**Comment by jschwe** [comment]
If I'm not mistaken, I think this issue is causing the mobile jingdong website https://m.jingdong.com/ to have an issue where the bar at the bottom to overflows in servo, but not in Firefox or chrome.

**Comment by Asun0204** [comment]
Althrough subpixel arithmetic is not defined in W3C, the current behavior has something wrong obviously. Truncate method is 
used in percentage calculation of firefox and chromium.

It is the code in firefox.

```cpp
static inline nscoord DefaultPercentLengthToAppUnits(float aPixelLength) {
  return NSToCoordTruncClamped(aPixelLength);
}
```

It is the code in chromium.

```cpp
LayoutUnit MinimumValueForLengthInternal(const Length& length,
                                         LayoutUnit maximum_value) {
  switch (length.GetType()) {
    case Length::kPercent:
      // Don't remove the extra cast to float. It is needed for rounding on
      // 32-bit Intel machines that use the FPU stack.
      return LayoutUnit(
          static_cast<float>(maximum_value * length.Percent() / 100.0f));
      // ...
```

So should we only modify the interface of `percentages_relative_to_basis` and `maybe_percentages_relative_to_basis`?

**Comment by Loirooriol** [comment]
> the current behavior has something wrong obviously

I would say undesirable instead of wrong.

> So should we only modify the implementation of percentages_relative_to_basis and maybe_percentages_relative_to_basis?

No, that's the wrong place, as I said in https://github.com/servo/servo/pull/34714#pullrequestreview-2517148728

**Comment by Asun0204** [comment]
`to_used_value` is called widely in firefox and servo, it is difficult for me to evalute the impact about it.

**Comment by Asun0204** [comment]
Can we just only modify `to_used_value` and `maybe_to_used_value` without interface added in app_units?

**Comment by Asun0204** [comment]
I omplete the code but don't know how to validate and merge it. What to do next?
https://github.com/servo/stylo/pull/102
https://github.com/servo/app_units/pull/60

**Comment by Loirooriol** [comment]
> What to do next?

Please investigate the failures. Interpolating from an inherited 100px to 40px at 1.5 should be `100 * -0.5 + 40 * 1.5 = -50 + 60 = 10`. Everything is an integer so not sure why it's failing.

**Comment by Asun0204** [comment]
> > What to do next?
> 
> Please investigate the failures. Interpolating from an inherited 100px to 40px at 1.5 should be `100 * -0.5 + 40 * 1.5 = -50 + 60 = 10`. Everything is an integer so not sure why it's failing.

I find the reason why the wpt test failed. The problem has been existed already and exposed by the modification. It is because the parameter accuracy about `transition_timing_function_at`.
Firstly the parameter is got from style by `transition_timing_function_at` as a `f32` number. An infinite loop decimal has been calculated on the process of bezier. The precision errors has been generated when the tranfer from `f32` to `f64` by filling zeros operation.

**Comment by Loirooriol** [comment]
Ah, I thought it was linear interpolation. So can you post the value of all the parameters of that function? And the output progress value?

**Comment by Asun0204** [comment]
> Ah, I thought it was linear interpolation. So can you post the value of all the parameters of that function? And the output progress value?

It is `width-interpolation` including linear interpolation and cubic-bezier interpolation.

wpt workflow error log is as follows.

```
  ▶ OK /css/css-sizing/animation/width-interpolation.html
  │   ▶ FAIL [expected PASS] CSS Transitions: property <width> from [inherit] to [40px] at (1.5) should be [10px]
  │   │   → assert_equals: expected "10px " but got "9.98px "
  │   │ FAIL [expected PASS] CSS Transitions with transition: all: property <width> from [inherit] to [40px] at (1.5) should be [10px]
  │   │   → assert_equals: expected "10px " but got "9.98px "
  │   │ FAIL [expected PASS] CSS Animations: property <width> from [inherit] to [40px] at (1.5) should be [10px]
  │   │   → assert_equals: expected "10px " but got "9.98px "
```

Corresponding test case in wpt is `/css/css-sizing/animation/width-interpolation.html`. The key code is as follows.

```html
test_interpolation({
  property: 'width',
  from: 'inherit',
  to: '40px',
}, [
  {at: 1.5, expect: '10px'},
]);
```

```javascript
  var cssTransitionsInterpolation = {
    name: 'CSS Transitions',
    isSupported: function() {return true;},
    supportsProperty: function() {return true;},
    supportsValue: function() {return true;},
    setup: function(property, from, target) {
      target.style.setProperty(property, isNeutralKeyframe(from) ? '' : from);
    },
    nonInterpolationExpectations: function(from, to) {
      return expectFlip(from, to, -Infinity);
    },
    notAnimatableExpectations: function(from, to, underlying) {
      return expectFlip(from, to, -Infinity);
    },
    interpolate: function(property, from, to, at, target, behavior) {
      // Force a style recalc on target to set the 'from' value.
      getComputedStyle(target).getPropertyValue(property);
      target.style.transitionDuration = '100s';
      target.style.transitionDelay = '-50s';
      target.style.transitionTimingFunction = createEasing(at);
      target.style.transitionProperty = property;
      if (behavior) {
        target.style.transitionBehavior = behavior;
      }
      target.style.setProperty(property, isNeutralKeyframe(to) ? '' : to);
    },
  };

  function createEasing(y) {
    if (y == 0) {
      return 'steps(1, end)';
    }
    if (y == 1) {
      return 'steps(1, start)';
    }
    if (y == 0.5) {
      return 'linear';
    }
    // Approximate using a bezier.
    var b = (8 * y - 1) / 6;
    return 'cubic-bezier(0, ' + b + ', 1, ' + b + ')';
  }
```

The parameter of `at` is 1.5, so parameter of `transitionTimingFunction ` is 'cubic-bezier(0, 1.8333334, 1, 1.8333334)'.

**Review by Loirooriol — CHANGES_REQUESTED** [review]
You need to compile so that `Cargo.lock` gets updated. Then I can run tests

**Comment by Asun0204** [comment]
Testing code is commited including:
1. using stylo and app_units pr in servo
2. using app_units in stylo
We can start the test task now to verify the modification.

File: Cargo.lock [hunk 2]
```diff
@@ -6491,7 +6500,7 @@ dependencies = [
 [[package]]
 name = "selectors"
 version = "0.26.0"
-source = "git+https://github.com/servo/stylo?branch=2025-03-01#0190fff684fa7b67f5413a60f215e671b6222534"
+source = "git+https://github.com/servo/stylo?rev=refs%2Fpull%2F102%2Fhead#c297870b9b536c576ec24c6a21067bf19ec80685"
```
Comment (Loirooriol) [inline Cargo.lock:6503]: You need to update this PR so that all of these point to your current Stylo commit, https://github.com/servo/stylo/commit/8ec2526808548b50f4c697e702f5e9b5994f8091

**Review by Loirooriol — CHANGES_REQUESTED** [review]

**Review by Loirooriol — COMMENTED** [review]
You will need to rebase and mark the test from #35809 as passing.

**Review by Loirooriol — APPROVED** [review]
