### PR TITLE
fix: Memory leak from CreateProxyWindowHandler

### LINKED ISSUE #32647: JS Window object does not get garbage collected
**Describe the bug:**
While investigating the generated memory leaks by the leaksan from #32223 we could reproduce the following leak of the attached report, when navigating between three different sites without JS. 

Apparently the Javascript `window` object does not get freed and as such leaks

From the code in [script_thread.rs:3578](https://github.com/servo/servo/blob/3a0f56491614508af069fc393a8cc0dbeb733d71/components/script/script_thread.rs#L3578) and the [article](https://github.com/servo/servo/blob/main/components/script/docs/JS-Servos-only-GC.md) about GC together with JS our current guess is, that when a new `Window` is created it returns a `Root<Dom<Window>>` which is held by `STACK_ROOT` a thread local static variable, which is probably connected with the garbage collection and we don't really understand how the value is removed here so that the GC can collect the window later.

Another guess here is that the objects continue to live because because of caching for the browser history. Interestingly, when using the forward and backward button the leaks seem to increase.

Since we want to investigate this further and fix it if possible, could someone point out how the GC is supposed to work here? Is there some hint to the GC missing that the object can be collected?

Also to get started we wanted to write a unit test in the same file. Is this according to the coding guidelines?

Thanks

**To Reproduce:**
1. Run servo with `--with-asan`
2. Navigate to multiple sites
3. Close window and look at the report. As many similar leaks should occur as sites where visited.

**Platform:**
Linux x86_64 6.9.3-arch1-1

**Leak report**
```
Direct leak of 1056 byte(s) in 4 object(s) allocated from:
    #0 0x5ba72ed82e7f in malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:68:3
    #1 0x7463092ae6e4 in operator new(unsigned long) /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/new_op.cc:50:22
    #2 0x5ba736d7a519 in CreateWrapperProxyHandler /home/runner/work/mozjs/mozjs/mozjs-sys/src/jsglue.cpp:624:41
    #3 0x5ba7331daf3d in script::dom::windowproxy::new_window_proxy_handler::h22749b93b19f6e86 /home/rhetenor/Projects/servo/components/script/dom/windowproxy.rs:1079:33
    #4 0x5ba733be02f2 in script::script_thread::ScriptThread::load::hae78c20f18b03567 /home/rhetenor/Projects/servo/components/script/script_thread.rs:3571:22
    #5 0x5ba7344ca62d in script::script_thread::ScriptThread::handle_page_headers_available::_$u7b$$u7b$closure$u7d$$u7d$::hbd6688c35a37c2be /home/rhetenor/Projects/servo/components/script/script_thread.rs:3120:37
    #6 0x5ba73320cabd in core::option::Option$LT$T$GT$::map::h58bdf9ce2023b58f /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1073:29
    #7 0x5ba733bd3a4a in script::script_thread::ScriptThread::handle_page_headers_available::h9b3e65cd86e65317 /home/rhetenor/Projects/servo/components/script/script_thread.rs:3120:17
    #8 0x5ba7344bb411 in script::script_thread::ScriptThread::page_headers_available::_$u7b$$u7b$closure$u7d$$u7d$::hb4599dbfc0929b4c /home/rhetenor/Projects/servo/components/script/script_thread.rs:944:13
    #9 0x5ba7347edc5f in std::thread::local::LocalKey$LT$T$GT$::try_with::h4c34bf7eeb8a2786 /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:284:16
    #10 0x5ba7347c6cda in std::thread::local::LocalKey$LT$T$GT$::with::h5a91487abcad5402 /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:260:9
    #11 0x5ba733ba3d61 in script::script_thread::ScriptThread::page_headers_available::he86d32fec0f39990 /home/rhetenor/Projects/servo/components/script/script_thread.rs:942:9
    #12 0x5ba734ea56f4 in _$LT$script..dom..servoparser..ParserContext$u20$as$u20$net_traits..FetchResponseListener$GT$::process_response::hb4afaa6867684cc6 /home/rhetenor/Projects/servo/components/script/dom/servoparser/mod.rs:832:28
    #13 0x5ba733be9d69 in script::script_thread::ScriptThread::handle_fetch_metadata::ha6f2ed2987e1a278 /home/rhetenor/Projects/servo/components/script/script_thread.rs:3995:13
    #14 0x5ba733bbb5ab in script::script_thread::ScriptThread::handle_msg_from_constellation::hb718909bbbd7cd07 /home/rhetenor/Projects/servo/components/script/script_thread.rs:2244:25
    #15 0x5ba7344c329a in script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::h52e51e95e79045e1 /home/rhetenor/Projects/servo/components/script/script_thread.rs:1958:53
    #16 0x5ba7344c5431 in script::script_thread::ScriptThread::profile_event::h8ee4a8b2791b2f00 /home/rhetenor/Projects/servo/components/script/script_thread.rs:2215:13
    #17 0x5ba733bb50f6 in script::script_thread::ScriptThread::handle_msgs::hbf1922253ff935ac /home/rhetenor/Projects/servo/components/script/script_thread.rs:1952:26
    #18 0x5ba733babdc5 in script::script_thread::ScriptThread::start::h35e031a1f54530ed /home/rhetenor/Projects/servo/components/script/script_thread.rs:1455:15
    #19 0x5ba7344ba69e in _$LT$script..script_thread..ScriptThread$u20$as$u20$script_layout_interface..ScriptThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h46c65bb617be436e /home/rhetenor/Projects/servo/components/script/script_thread.rs:846:25
    #20 0x5ba7344ba2b4 in _$LT$script..script_thread..ScriptThread$u20$as$u20$script_layout_interface..ScriptThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::h8fc93d7bc3b695db /home/rhetenor/Projects/servo/components/script/script_thread.rs:844:17
    #21 0x5ba73454c218 in std::sys_common::backtrace::__rust_begin_short_backtrace::h2e664b4d9d62a06d /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:155:18
    #22 0x5ba733f1e180 in _$LT$core..panic..unwind_safe..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h24450773718100bd /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
    #23 0x5ba73378c11e in std::panicking::try::do_call::he1de23cd2648e563 /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40
    #24 0x5ba7337a1d1a in __rust_try 2khri761y8r1cabc
    #25 0x5ba7357d39a9 in std::panic::catch_unwind::hc39bf968acdf290b /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:146:14
    #26 0x5ba73225aa9e in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h5046e8ee9392a4ed /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
    #27 0x5ba73fc3ba56 in _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::h2fd2c3854b095d3a /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2020:9
    #28 0x5ba73fb8ba13 in std::sys::pal::unix::thread::Thread::new::thread_start::hc5bdc4f7973b0d3d /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/pal/unix/thread.rs:108:17
    #29 0x5ba72ed80a28 in asan_thread_start(void*) /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:239:28

Direct leak of 528 byte(s) in 2 object(s) allocated from:
    #0 0x5ba72ed82e7f in malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:68:3
    #1 0x7463092ae6e4 in operator new(unsigned long) /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/new_op.cc:50:22
    #2 0x5ba736d7a519 in CreateWrapperProxyHandler /home/runner/work/mozjs/mozjs/mozjs-sys/src/jsglue.cpp:624:41
    #3 0x5ba7331d2f2a in script::dom::windowproxy::WindowProxy::set_window::hcce255b7ff77f74a /home/rhetenor/Projects/servo/components/script/dom/windowproxy.rs:628:27
    #4 0x5ba7331d49af in script::dom::windowproxy::WindowProxy::unset_currently_active::h60ae5ccc1149e3b3 /home/rhetenor/Projects/servo/components/script/dom/windowproxy.rs:694:9
    #5 0x5ba7335b12d8 in script::dom::window::Window::suspend::h30ae27017d4da1bc /home/rhetenor/Projects/servo/components/script/dom/window.rs:2361:13
    #6 0x5ba7356d3954 in script::dom::document::Document::set_activity::h095098d424f51736 /home/rhetenor/Projects/servo/components/script/dom/document.rs:691:13
    #7 0x5ba733bce930 in script::script_thread::ScriptThread::handle_set_document_activity_msg::h0e0247a95c126f24 /home/rhetenor/Projects/servo/components/script/script_thread.rs:2919:13
    #8 0x5ba733bb9433 in script::script_thread::ScriptThread::handle_msg_from_constellation::hb718909bbbd7cd07 /home/rhetenor/Projects/servo/components/script/script_thread.rs:2274:17
    #9 0x5ba7344c329a in script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::h52e51e95e79045e1 /home/rhetenor/Projects/servo/components/script/script_thread.rs:1958:53
    #10 0x5ba7344c5431 in script::script_thread::ScriptThread::profile_event::h8ee4a8b2791b2f00 /home/rhetenor/Projects/servo/components/script/script_thread.rs:2215:13
    #11 0x5ba733bb50f6 in script::script_thread::ScriptThread::handle_msgs::hbf1922253ff935ac /home/rhetenor/Projects/servo/components/script/script_thread.rs:1952:26
    #12 0x5ba733babdc5 in script::script_thread::ScriptThread::start::h35e031a1f54530ed /home/rhetenor/Projects/servo/components/script/script_thread.rs:1455:15
    #13 0x5ba7344ba69e in _$LT$script..script_thread..ScriptThread$u20$as$u20$script_layout_interface..ScriptThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h46c65bb617be436e /home/rhetenor/Projects/servo/components/script/script_thread.rs:846:25
    #14 0x5ba7344ba2b4 in _$LT$script..script_thread..ScriptThread$u20$as$u20$script_layout_interface..ScriptThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::h8fc93d7bc3b695db /home/rhetenor/Projects/servo/components/script/script_thread.rs:844:17
    #15 0x5ba73454c218 in std::sys_common::backtrace::__rust_begin_short_backtrace::h2e664b4d9d62a06d /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:155:18
    #16 0x5ba733f1e180 in _$LT$core..panic..unwind_safe..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h24450773718100bd /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
    #17 0x5ba73378c11e in std::panicking::try::do_call::he1de23cd2648e563 /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40
    #18 0x5ba7337a1d1a in __rust_try 2khri761y8r1cabc
    #19 0x5ba7357d39a9 in std::panic::catch_unwind::hc39bf968acdf290b /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:146:14
    #20 0x5ba73225aa9e in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h5046e8ee9392a4ed /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
    #21 0x5ba73fc3ba56 in _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::h2fd2c3854b095d3a /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2020:9
    #22 0x5ba73fb8ba13 in std::sys::pal::unix::thread::Thread::new::thread_start::hc5bdc4f7973b0d3d /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/pal/unix/thread.rs:108:17
    #23 0x5ba72ed80a28 in asan_thread_start(void*) /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:239:28

Direct leak of 264 byte(s) in 1 object(s) allocated from:
    #0 0x5ba72ed82e7f in malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:68:3
    #1 0x7463092ae6e4 in operator new(unsigned long) /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/new_op.cc:50:22
    #2 0x5ba736d7a519 in CreateWrapperProxyHandler /home/runner/work/mozjs/mozjs/mozjs-sys/src/jsglue.cpp:624:41
    #3 0x5ba7331d2f2a in script::dom::windowproxy::WindowProxy::set_window::hcce255b7ff77f74a /home/rhetenor/Projects/servo/components/script/dom/windowproxy.rs:628:27
    #4 0x5ba7331d454d in script::dom::windowproxy::WindowProxy::set_currently_active::hc6cf9d7b171efe3a /home/rhetenor/Projects/servo/components/script/dom/windowproxy.rs:684:9
    #5 0x5ba7335b1507 in script::dom::window::Window::resume::h958f3d9e4a521bd2 /home/rhetenor/Projects/servo/components/script/dom/window.rs:2376:9
    #6 0x5ba733be2294 in script::script_thread::ScriptThread::load::hae78c20f18b03567 /home/rhetenor/Projects/servo/components/script/script_thread.rs:3733:13
    #7 0x5ba7344ca62d in script::script_thread::ScriptThread::handle_page_headers_available::_$u7b$$u7b$closure$u7d$$u7d$::hbd6688c35a37c2be /home/rhetenor/Projects/servo/components/script/script_thread.rs:3120:37
    #8 0x5ba73320cabd in core::option::Option$LT$T$GT$::map::h58bdf9ce2023b58f /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1073:29
    #9 0x5ba733bd3a4a in script::script_thread::ScriptThread::handle_page_headers_available::h9b3e65cd86e65317 /home/rhetenor/Projects/servo/components/script/script_thread.rs:3120:17
    #10 0x5ba7344bb411 in script::script_thread::ScriptThread::page_headers_available::_$u7b$$u7b$closure$u7d$$u7d$::hb4599dbfc0929b4c /home/rhetenor/Projects/servo/components/script/script_thread.rs:944:13
    #11 0x5ba7347edc5f in std::thread::local::LocalKey$LT$T$GT$::try_with::h4c34bf7eeb8a2786 /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:284:16
    #12 0x5ba7347c6cda in std::thread::local::LocalKey$LT$T$GT$::with::h5a91487abcad5402 /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:260:9
    #13 0x5ba733ba3d61 in script::script_thread::ScriptThread::page_headers_available::he86d32fec0f39990 /home/rhetenor/Projects/servo/components/script/script_thread.rs:942:9
    #14 0x5ba734ea56f4 in _$LT$script..dom..servoparser..ParserContext$u20$as$u20$net_traits..FetchResponseListener$GT$::process_response::hb4afaa6867684cc6 /home/rhetenor/Projects/servo/components/script/dom/servoparser/mod.rs:832:28
    #15 0x5ba733be9d69 in script::script_thread::ScriptThread::handle_fetch_metadata::ha6f2ed2987e1a278 /home/rhetenor/Projects/servo/components/script/script_thread.rs:3995:13
    #16 0x5ba733bbb5ab in script::script_thread::ScriptThread::handle_msg_from_constellation::hb718909bbbd7cd07 /home/rhetenor/Projects/servo/components/script/script_thread.rs:2244:25
    #17 0x5ba7344c329a in script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::h52e51e95e79045e1 /home/rhetenor/Projects/servo/components/script/script_thread.rs:1958:53
    #18 0x5ba7344c5431 in script::script_thread::ScriptThread::profile_event::h8ee4a8b2791b2f00 /home/rhetenor/Projects/servo/components/script/script_thread.rs:2215:13
    #19 0x5ba733bb50f6 in script::script_thread::ScriptThread::handle_msgs::hbf1922253ff935ac /home/rhetenor/Projects/servo/components/script/script_thread.rs:1952:26
    #20 0x5ba733babdc5 in script::script_thread::ScriptThread::start::h35e031a1f54530ed /home/rhetenor/Projects/servo/components/script/script_thread.rs:1455:15
    #21 0x5ba7344ba69e in _$LT$script..script_thread..ScriptThread$u20$as$u20$script_layout_interface..ScriptThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h46c65bb617be436e /home/rhetenor/Projects/servo/components/script/script_thread.rs:846:25
    #22 0x5ba7344ba2b4 in _$LT$script..script_thread..ScriptThread$u20$as$u20$script_layout_interface..ScriptThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::h8fc93d7bc3b695db /home/rhetenor/Projects/servo/components/script/script_thread.rs:844:17
    #23 0x5ba73454c218 in std::sys_common::backtrace::__rust_begin_short_backtrace::h2e664b4d9d62a06d /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:155:18
    #24 0x5ba733f1e180 in _$LT$core..panic..unwind_safe..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h24450773718100bd /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
    #25 0x5ba73378c11e in std::panicking::try::do_call::he1de23cd2648e563 /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40
    #26 0x5ba7337a1d1a in __rust_try 2khri761y8r1cabc
    #27 0x5ba7357d39a9 in std::panic::catch_unwind::hc39bf968acdf290b /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:146:14
    #28 0x5ba73225aa9e in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h5046e8ee9392a4ed /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
    #29 0x5ba73fc3ba56 in _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::h2fd2c3854b095d3a /home/rhetenor/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2020:9
```

### PR DESCRIPTION
**Pull request by ede1998**
@rhetenor and I fixed the memory leak discussed in #32647 and first mentioned in #32223.

The leak happened because the C++ class `WrapperProxyHandler` was allocated on the C++ heap but never freed again after Rust is finished using it. In a previous PR, we exposed a function to destroy `WrapperProxyHandler` (servo/mozjs#470) and this PR introduces the destructor call in Rust.

The implementation was not as straightforward as we expected. The lifetime of the `WrapperProxyHandler` cannot be determined statically (we think) because it is owned by both `Window` and `WindowProxy` `struct`s and both are GC'ed. We opted to reference-count the `WrapperProxyHandler` to handle this situation. Another option would be to also make `WrapperProxyHandler` GC'ed but as we are unfamiliar with the intricacies of the GC, we went for the simpler solution first. If you prefer a GC'ed solution, please let us know and give us some hints on how to implement it.

This is the leak that the changes fix:

```
Direct leak of 264 byte(s) in 1 object(s) allocated from:
    #0 0x5be0a8458e3f in malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:68:3
    #1 0x7ad6d0cae6e4 in operator new(unsigned long) /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/new_op.cc:50:22
    #2 0x5be0b1d795e9 in CreateWrapperProxyHandler /home/runner/work/mozjs/mozjs/mozjs-sys/src/jsglue.cpp:624:41
    #3 0x5be0ad92f98d in script::dom::windowproxy::new_window_proxy_handler::h49ef8469ced81863 /home/erik/dev/rust/servo/components/script/dom/windowproxy.rs:1079:33
    #4 0x5be0af0c0024 in script::script_thread::ScriptThread::load::hacf22fd41ec5a2c0 /home/erik/dev/rust/servo/components/script/script_thread.rs:3573:22
    #5 0x5be0ad2e10ed in script::script_thread::ScriptThread::handle_page_headers_available::_$u7b$$u7b$closure$u7d$$u7d$::h9519cdf466f1b970 /home/erik/dev/rust/servo/components/script/script_thread.rs:3116:37
    #6 0x5be0af493abd in core::option::Option$LT$T$GT$::map::hd18c394a96464f3c /home/erik/dev/rust/servo/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1073:29
    #7 0x5be0af0b2f4a in script::script_thread::ScriptThread::handle_page_headers_available::hac5c08c144536020 /home/erik/dev/rust/servo/components/script/script_thread.rs:3116:17
    #8 0x5be0ad2d1ed1 in script::script_thread::ScriptThread::page_headers_available::_$u7b$$u7b$closure$u7d$$u7d$::h8ce3b1dc64e1055c /home/erik/dev/rust/servo/components/script/script_thread.rs:943:13
    #9 0x5be0afcd2d9f in std::thread::local::LocalKey$LT$T$GT$::try_with::h230935e9243d87cd /home/erik/dev/rust/servo/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:284:16
    #10 0x5be0afcc02ba in std::thread::local::LocalKey$LT$T$GT$::with::ha6fdfc7c2648c1ab /home/erik/dev/rust/servo/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:260:9
    #11 0x5be0af0829b1 in script::script_thread::ScriptThread::page_headers_available::h736bf0d9fa029cec /home/erik/dev/rust/servo/components/script/script_thread.rs:941:9
    #12 0x5be0adee0af4 in _$LT$script..dom..servoparser..ParserContext$u20$as$u20$net_traits..FetchResponseListener$GT$::process_response::h8298ca2e9174c05f /home/erik/dev/rust/servo/components/script/dom/servoparser/mod.rs:832:28
    #13 0x5be0af0c9f4e in script::script_thread::ScriptThread::handle_fetch_metadata::hac77b74a181ef918 /home/erik/dev/rust/servo/components/script/script_thread.rs:3997:13
    #14 0x5be0af09a95a in script::script_thread::ScriptThread::handle_msg_from_constellation::hc979eb82c2f167ed /home/erik/dev/rust/servo/components/script/script_thread.rs:2243:25
    #15 0x5be0ad2d9d5a in script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::h3d1393bc71a18c9d /home/erik/dev/rust/servo/components/script/script_thread.rs:1957:53
    #16 0x5be0ad2da3e1 in script::script_thread::ScriptThread::profile_event::h464b94be8453202f /home/erik/dev/rust/servo/components/script/script_thread.rs:2214:13
    #17 0x5be0af094420 in script::script_thread::ScriptThread::handle_msgs::hb859ccf55c4a2c8a /home/erik/dev/rust/servo/components/script/script_thread.rs:1951:26
    #18 0x5be0af08ab32 in script::script_thread::ScriptThread::start::h8adc6ba65c76220f /home/erik/dev/rust/servo/components/script/script_thread.rs:1454:15
    #19 0x5be0ad2d115e in _$LT$script..script_thread..ScriptThread$u20$as$u20$script_layout_interface..ScriptThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h5307b8a512ce2c7b /home/erik/dev/rust/servo/components/script/script_thread.rs:845:25
    #20 0x5be0ad2d0d74 in _$LT$script..script_thread..ScriptThread$u20$as$u20$script_layout_interface..ScriptThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::h75db08e5e083b23c /home/erik/dev/rust/servo/components/script/script_thread.rs:843:17
    #21 0x5be0aecec7e8 in std::sys_common::backtrace::__rust_begin_short_backtrace::hd35c84dd73dfa745 /home/erik/dev/rust/servo/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:155:18
    #22 0x5be0b0a8eeb0 in _$LT$core..panic..unwind_safe..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h4f2a3fd47243e644 /home/erik/dev/rust/servo/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
    #23 0x5be0ad08447e in std::panicking::try::do_call::h95a908ca9efdddde /home/erik/dev/rust/servo/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40
    #24 0x5be0ad09abea in __rust_try 13tw1g03ezilzh7i
    #25 0x5be0ae366119 in std::panic::catch_unwind::h565f1095b3fe6316 /home/erik/dev/rust/servo/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:146:14
    #26 0x5be0b0232efe in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h22b7ffd16982c2f9 /home/erik/dev/rust/servo/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
    #27 0x5be0b951fd66 in _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::hff7d546c784b2c64 /home/erik/dev/rust/servo/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2020:9
    #28 0x5be0b946ed93 in std::sys::pal::unix::thread::Thread::new::thread_start::h97531aae4617af66 /home/erik/dev/rust/servo/.rustup/toolchains/1.78.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/pal/unix/thread.rs:108:17
    #29 0x5be0a84569e8 in asan_thread_start(void*) /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:239:28
```

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #32647 and #32223 (partly) (GitHub issue number if applicable)

Please let us know if/what kind of tests you expect for this change:

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

File: components/script/dom/bindings/utils.rs [hunk 1]
```diff
@@ -42,34 +43,29 @@ use crate::dom::bindings::error::throw_invalid_this;
...
-    }
-}
-
-#[derive(JSTraceable, MallocSizeOf)]
+#[derive(JSTraceable)]
 /// Static data associated with a global object.
 pub struct GlobalStaticData {
     /// The WindowProxy proxy handler for this global.
-    pub windowproxy_handler: WindowProxyHandler,
+    pub windowproxy_handler: Arc<WindowProxyHandler>,
```
Comment (jdm) [inline components/script/dom/bindings/utils.rs:53]: Why Arc instead of Rc?

File: components/script/dom/bindings/utils.rs [hunk 2]
```diff
@@ -42,34 +43,29 @@ use crate::dom::bindings::error::throw_invalid_this;
...
 impl GlobalStaticData {
     /// Creates a new GlobalStaticData.
     pub fn new() -> GlobalStaticData {
         GlobalStaticData {
-            windowproxy_handler: windowproxy::new_window_proxy_handler(),
+            windowproxy_handler: Arc::new(WindowProxyHandler::new(&PROXY_HANDLER)),
         }
     }
 }
+impl MallocSizeOf for GlobalStaticData {
```
Comment (jdm) [inline components/script/dom/bindings/utils.rs:64]: This looks the same as a derived implementation. Why can't we use the derived version instead?

**Review by jdm — APPROVED** [review]
Nice! This seems like a reasonable solution.

File: components/script/dom/bindings/utils.rs (hunk 2 above)
Comment (ede1998) [reply components/script/dom/bindings/utils.rs:64]: We tried that first but got an error with the derive macro. According to the documentation[^1] it seems like it is intentional that this case must be decided manually. We just passed it through without thinking about it too much as the impl for `ProxyWindowHandler` returns `0` at the moment anyway and this copy of the `Arc` is the only one that would be counted because the other copies (that only exist) in `WindowProxy` are skipped in the derive macro through our annotation.

However in some cases (e.g. `new_dissimilar_origin` constructor) there is no window so the `Arc` would not be counted at all (right now it would return 0 anyway as mentioned before but this might lead to issues when someone eventually fixes #6097). Do you know a better solution? Anyway, thanks for pointing it out. I actually just noticed that I **missed a leak [in the `set_window` method](https://github.com/servo/servo/blob/6b8804d263ac3f2fa5835116f947fc79f7bd1ab4/components/script/dom/windowproxy.rs#L636)**. Here the window that the `WindowProxy` refers to is swapped and entirely new `WindowProxyHandler` is created. Now I'm wondering whether `Arc` was necessary in the first place or if we should just make deep copies instead...? 🤔

[^1]: https://doc.servo.org/malloc_size_of/index.html

File: components/script/dom/bindings/utils.rs (hunk 1 above)
Comment (ede1998) [reply components/script/dom/bindings/utils.rs:53]: Didn't try `Rc` but can try it out. I just saw that `Arc` was used elsewhere in a `Window` struct member and assumed it would be required.

File: components/script/dom/bindings/utils.rs (hunk 2 above)
Comment (jdm) [reply components/script/dom/bindings/utils.rs:64]: Ah, I see. The usual path here is to use a derive and add an `#[ignore_malloc_size_of]` annotation on the field that causes the error. This means that any new fields added to the struct in the future won't be forgotten.

File: components/script/dom/bindings/utils.rs (hunk 1 above)
Comment (ede1998) [reply components/script/dom/bindings/utils.rs]: Ok, fixed.

File: components/script/dom/bindings/utils.rs (hunk 2 above)
Comment (ede1998) [reply components/script/dom/bindings/utils.rs]: Ok, changed that. I also tried to fix the leak in `set_window` (see 2nd commit) but when I switch websites a bit now, I get a segfault. Will have to check that out in the coming week. If you want to merge the PR before that, we can drop the second commit for now and keep the third leak for now.

Comment (ede1998) [reply components/script/dom/bindings/utils.rs]: I added a few log messages about when `set_window` is called and when instances of `WindowProxyHandler` are created and destroyed. Clicking around a bit until SEGFAULT (<http://example.com> -> <http://blog.fefe.de> -> a few subpages there, maybe also back/forwards arrow) got me this log:

```
Acquired window proxy handler 0x512000206a40
Acquired window proxy handler 0x512000294940
Setting window -> potential drop of window proxy Handler
Acquired window proxy handler 0x5120005a67c0
Acquired window proxy handler 0x5120004ec340
Setting window -> potential drop of window proxy Handler
Acquired window proxy handler 0x5120004eba40
Acquired window proxy handler 0x5120003a72c0
Setting window -> potential drop of window proxy Handler
Acquired window proxy handler 0x51200028da40
Dropping window proxy handler 0x5120004eba40
Caught signal 11 in thread "Script(1,2)"
Servo was terminated by signal 11
```

Comment (ede1998) [reply components/script/dom/bindings/utils.rs]: Thinking about it now, maybe it's better to hand the `WindowProxyHandler` pointer to the GC. My reasoning here is that the GC'ed `WindowProxy` (in the `NewWindowProxy` C++ method) stores a pointer to the handler and I'm not sure if this stored pointer can escape in the C++ code and hence live longer than `Window` or `WindowProxy`. What do you think?

**Comment by rhetenor** [comment]
Hey!

After looking into this again for quite some time, we are stuck with the pointer management across the boundaries of the [set_window](https://github.com/servo/servo/blob/6b8804d263ac3f2fa5835116f947fc79f7bd1ab4/components/script/dom/windowproxy.rs#L636) method. 

When we destroy the encapsulated raw pointer through RC, it is still somewhere held in the C++ part. Since the segfault comes from the tracing of GC because the pointer is still alive in the window Proxy and possibly elsewhere.

Because `WrapperProxyHandler` is a `js::Wrapper` we probably cannot give it to the GC since it does not seem to be a GC thing according to SpiderMonkeys definition. Does this hold?

One solution we thought of is to reference count the pointer on the C++ side through smart pointers, but this seems to be too many interface changes.
But there would also be the possibility of instead of recreating the `WindowProxyHandler` everytime the window changes, we update the traps hold by it. These are the only members that get updated and there are actually 2 different static variants of it. This would probably solve the pointer issue, but require another small change to mozjs. 

Have you got any better idea how to solve this lifetime problem between C++ and Rust?

**Comment by jdm** [comment]
Yeah, this is thorny! What if instead of always calling CreateWrapperProxyHandler, we create two singleton lazy values using [OnceLock](https://doc.rust-lang.org/stable/std/sync/struct.OnceLock.html)? I don't yet have an idea of how to ensure the Drop implementation is called to deallocate them (the docs explicitly call out that Drop is not called), but at least we would only be leaking two objects total in that case.

**Comment by ede1998** [comment]
> Yeah, this is thorny! What if instead of always calling CreateWrapperProxyHandler, we create two singleton lazy values using [OnceLock](https://doc.rust-lang.org/stable/std/sync/struct.OnceLock.html)? I don't yet have an idea of how to ensure the Drop implementation is called to deallocate them (the docs explicitly call out that Drop is not called), but at least we would only be leaking two objects total in that case.

Thanks for the suggestion. We implemented this. The leak is no longer reported, presumably because the pointer is always reachable through the static variable, though afaik it will not be freed by servo itself.

We tried visiting a few websites and clicked through history etc. There were no crashes or unexpected behavior. Also, the `WrapperProxyHandler` in C++ seems to not allow modification to its state, so it should be fine to share only 2 instances throughout servo.

**Review by jdm — APPROVED** [review]
