### PR TITLE
layout: Support style inheritance for `display: contents` and `<slot>` elements

### LINKED ISSUE #41797: Text node can't get the Inherited style properly from `slot`
**Describe the bug:**
Text node can't get the Inherited style from `slot` parent.
It still gets the style from direct parent in light DOM.

**To Reproduce:**
Difference between Chromium (left) and Servo (right)

Image

Test case:
```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Slot Inheritance Test</title>
<style>
  my-view {
    display: block;
    color: red;
    font-size: 24px;
    font-weight: bold;
    border: 2px solid red;
    padding: 10px;
    margin: 5px;
  }
</style>
</head>
<body>

<my-view>
    Osaka
</my-view>

<script>
class MyView extends HTMLElement {
  constructor() {
    super();
    const shadow = this.attachShadow({ mode: 'open' });
    // Slot has different styles - if text inherits from slot, it will be green and italic
    shadow.innerHTML = `
      <style>
        slot {
          color: green;
          font-style: italic;
          font-weight: normal;
          font-size: 16px;
        }
      </style>
      <slot></slot>
    `;
  }
}

customElements.define('my-view', MyView);
</script>

</body>
</html>

```

**Platform:**
Linux, Windows, Harmony OS

### PR DESCRIPTION
**Pull request by longvatrong111**
In DOM traversal, `display:contents `elements don't generate boxes, but their styles still need to apply to children.
`ModernContainerBuilder` now keeps track of `display:contents` ancestors during traversal then apply their style to text runs.

In `InlineFormattingContextBuilder::push_text` only use same style parent if both selected and current inline style are identical.

Testing: 

> PASS [expected FAIL] /css/css-display/display-contents-dynamic-before-after-001.html
> PASS [expected FAIL] /css/css-display/display-contents-dynamic-inline-flex-001-inline.html
> PASS [expected FAIL] /css/css-display/display-contents-dynamic-inline-flex-001-none.html
> FAIL [expected PASS] /css/css-display/display-contents-fieldset.html
> PASS [expected FAIL] /css/css-display/display-contents-first-line-002.html
> PASS [expected FAIL] /css/css-display/display-contents-inline-001.html
> PASS [expected FAIL] /css/css-display/display-contents-inline-flex-001.html
> PASS [expected FAIL] /css/css-display/display-contents-line-height.html

Fixes: https://github.com/servo/servo/issues/41797

cc: @xiaochengh

### CODE REVIEW

File: components/layout/flow/inline/construct.rs [hunk 1]
```diff
@@ -347,16 +349,28 @@ impl InlineFormattingContextBuilder {
...
-                return;
+                let mut borrowed_text_run = text_run.borrow_mut();
+                let same_style_parent = borrowed_text_run
+                    .inline_styles
+                    .style
+                    .ptr_eq(&current_inline_styles.style) &&
+                    borrowed_text_run
+                        .inline_styles
+                        .selected
+                        .ptr_eq(&current_inline_styles.selected);
```
Comment (mrobinson) [inline components/layout/flow/inline/construct.rs]: Let's add a `TextRun::shares_inline_styles()` method which abstracts the details away here.

File: components/layout/flow/inline/construct.rs [hunk 2]
```diff
@@ -334,6 +334,8 @@ impl InlineFormattingContextBuilder {
             return;
         }
 
+        let current_inline_styles = self.shared_inline_styles();
+
```
Comment (mrobinson) [inline components/layout/flow/inline/construct.rs]: Move this directly above where you use it.

**Review by mrobinson — COMMENTED** [review]
It's a bit odd to me that `<slot>` provides styles to children, but this is only modifying modern layout. Is this already handled properly for flow, inline, and table layout?

**Comment by longvatrong111** [comment]
> It's a bit odd to me that `<slot>` provides styles to children, but this is only modifying modern layout. Is this already handled properly for flow, inline, and table layout?

@mrobinson yes, the issue only occurs if slot has `display:contents` or the parent of text node in light DOM is `flex` container.

**Comment by xiaochengh** [comment]
> > It's a bit odd to me that `<slot>` provides styles to children, but this is only modifying modern layout. Is this already handled properly for flow, inline, and table layout?
> 
> @mrobinson yes, the issue only occurs if slot has `display:contents` or the parent of text node in light DOM is `flex` container.

Could you give a pointer to how this is handled in other layout modes for reference?

The approach in this PR also looks like manually implementing a style cascade, which looks weird to me (as there are too many ways to get the cascade rules wrong) and I need to think about it...

**Comment by longvatrong111** [comment]
> Could you give a pointer to how this is handled in other layout modes for reference?

@xiaochengh 

Inline Formatting Context maintain a `shared_inline_styles_stack` to consider the inhertitance styles, and provides `enter_display_contents` and `leave_display_contents` to modify.

However, these steps are missing when `ModernContainerBuilder` handles `TextRun` and push texts to Inline Formatting Context.

https://github.com/servo/servo/blob/271c85910f2aa5f29f13207eb8e3aa7582bfd89b/components/layout/flow/inline/construct.rs#L31-L36

https://github.com/servo/servo/blob/271c85910f2aa5f29f13207eb8e3aa7582bfd89b/components/layout/flow/inline/construct.rs#L366-L372

p/s: maybe the PR title is confusing, this PR affects `dispplay: contents` containers, slot is mentioned because in the linked issue I write a test case used slot.

**Review by xiaochengh — APPROVED** [review]
I can see that this PR follows the same approach as #36896.

LGTM. Would be good if @mrobinson can also take a look.

**Comment by yezhizhen** [comment]
@Loirooriol What do you think?

**Review by yezhizhen — APPROVED** [review]
Thanks @longvatrong111! This makes sense to me. 
I changed the title just to reflect my understanding. @Loirooriol can verify implementation details.

**Comment by Loirooriol** [comment]
@mrobinson and me have been taking a look, overall the problem was well spotted but we simplified a bit the solution.

**Review by mrobinson — APPROVED** [review]

**Comment by Loirooriol** [comment]
CI seems broken, I will try a rebase

**Comment by yezhizhen** [comment]
#42052 CI is very broken atm..
