### PR TITLE
layout: Create a webrender stacking context for fragments with `transform-style: preserve-3d`

### LINKED ISSUE #30474: ‘transform-style: preserve-3d’ does not work
```html
<!doctype html><meta charset=utf-8>
<div style="position: absolute; inset: 50px 0 0 50px; transform-style: preserve-3d">
    <div style="position: absolute; width: 100px; height: 100px; background: blue; transform: translateZ(1px)"></div>
    <div style="position: absolute; width: 100px; height: 100px; background: red; transform: translateZ(-1px)"></div>
</div>
<div style="position: absolute; inset: 50px 0 0 200px; transform-style: preserve-3d">
    <div style="position: absolute; width: 100px; height: 100px; background: blue; transform: rotate3d(1,1,1,30deg)"></div>
    <div style="position: absolute; width: 100px; height: 100px; background: red; transform: rotateZ(180deg)"></div>
</div>
```

image image

### PR DESCRIPTION
**Pull request by simonwuelker**
Such elements already establish stacking contexts, but we don't tell webrender about them.

Two new failures appear, which I believe incorrectly passed before. We fail because we don't support the concept of a [3D rendering context](https://drafts.csswg.org/css-transforms-2/#3d-rendering-context). 

If I understand correctly then we act as if a 3D rendering context was the same as a stacking context, but elements in the same stacking context may use different 3D coordinate systems, see https://github.com/web-platform-tests/wpt/blob/1903a5a80470223d7117b91b3e4cda3d7c037f40/css/css-transforms/transform3d-sorting-004.html#L9-L14 for example.

Fixes https://github.com/servo/servo/issues/30474
Testing: New tests start to pass.

### CODE REVIEW

File: components/layout/display_list/stacking_context.rs [hunk 1]
```diff
@@ -597,7 +598,8 @@ impl StackingContext {
             effects.opacity == 1.0 &&
             effects.mix_blend_mode == ComputedMixBlendMode::Normal &&
             !style.has_effective_transform_or_perspective(FragmentFlags::empty()) &&
-            style.clone_clip_path() == ClipPath::None
+            style.clone_clip_path() == ClipPath::None &&
+            style.get_used_transform_style() == TransformStyle::Flat
```
Comment (Loirooriol) [inline components/layout/display_list/stacking_context.rs]: `get_used_transform_style()` is also used below, so store it in a variable.

And no need to address it here, but it uses `overrides_transform_style()` which doesn't take `isolation` into account. They should probably be moved into Servo anyways since Gecko is not using this logic at all.

**Review by Loirooriol — APPROVED** [review]
