### PR TITLE
layout: Fix integer overflow when computing size of replace elements

### LINKED ISSUE #15249: Images with max-width show up squashed
```html
<img src="https://raw.githubusercontent.com/deepsyx/home-automation/master/Schematic.png" style="max-width:100%;">
```
This takes forever to appear, and then has full height and very little width.

### PR DESCRIPTION
**Pull request by stshine**
When calculating size of replaced element that has intrinsic aspect ratio, we need to multiply the ratio if one of the dimensions has definite size. And we can not precompute the ratio and store it as a float, because doing so may result one pixel difference in calculation for certain images, thus make some tests fail. So it may overflow when the dimension lengths are large, and this pull request convert them to `i64` before multiplication.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15249 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15469)

### CODE REVIEW

**Comment by stshine** [comment]
This does not look very clean, but whatever. May not worth for an individual type.

@bors-servo try

File: components/layout/fragment.rs [hunk 1]
```diff
@@ -1051,7 +1051,8 @@ impl Fragment {
                     // Note: We can not precompute the ratio and store it as a float, because
                     // doing so may result one pixel difference in calculation for certain
                     // images, thus make some tests fail.
-                    inline_size * intrinsic_block_size.0 / intrinsic_inline_size.0
```
Comment (emilio) [inline components/layout/fragment.rs]: Isn't enough to change the grouping of the operators to `inline_size * (intrinsic_block_size.0 / intrinsic_inline_size.0)`?

Comment (stshine) [inline components/layout/fragment.rs]: The divide will produce an integer and discard the decimal part, may result in pixel shift.

Comment (emilio) [inline components/layout/fragment.rs]: Ouch, right. Maybe we should add a helper method to app_units for this (`muldiv`?). But of course it doesn't need to block this.

**Review by emilio — APPROVED** [review]

File: components/layout/fragment.rs (hunk 1 above)
Comment (stshine) [inline components/layout/fragment.rs]: Better, make a new `AspectRatio` type with a num and a denum, then define operations on it. We may actually utilize the second chapter of SICP :) . But I keeps thinking that this is kind of redundant.

**Comment by jdm** [comment]
Why no test for this change?

**Comment by stshine** [comment]
Because to make a test needs a image with more than 3,000 pixel in each dimension, and a reference page to compare -- I don't know how to make one. Other the other hand, this is a kind of general bug, not targeting some specific features, so IMO it does not make much sense to make a special test for this.

**Comment by jdm** [comment]
https://dummyimage.com/3100x3100/0A0/0A0.png

**Comment by stshine** [comment]
OK, I'll submit a test later.
