### PR TITLE
fix(wayland): segfault because of double free surfaces

### LINKED ISSUE #34699: bug(wayland): segfault after exiting in headed mode
**Describe the bug:**
This is a regression issue from #34638. Due to new winit eventloop trait, several lifetime from rendering contexts become a bit different. On wayland, this trigger double free of wayland surface when exiting.

**To Reproduce:**
Simply click the exit button of the window and it should get the error. When backtracking in debugger, here's the log I got:

```
Thread 1 "servo" received signal SIGSEGV, Segmentation fault.
Downloading source file /usr/src/wayland-1.22.0-2.1build1/build/../src/wayland-util.c
0x00007ffff7fb19fc in wl_map_insert_at (map=map@entry=0x555562c552b0, flags=flags@entry=1, i=63, data=data@entry=0x0) at ../src/wayland-util.c:276  
warning: 276	../src/wayland-util.c: No such file or directory
(gdb) bt
#0  0x00007ffff7fb19fc in wl_map_insert_at (map=map@entry=0x555562c552b0, flags=flags@entry=1, i=63, data=data@entry=0x0)
    at ../src/wayland-util.c:276
#1  0x00007ffff7fb1b65 in proxy_destroy (proxy=proxy@entry=0x555563507ba0) at ../src/wayland-client.c:538
#2  0x00007ffff7fb38d7 in wl_proxy_destroy_caller_locks (proxy=0x555563507ba0) at ../src/wayland-client.c:562
#3  wl_proxy_marshal_array_flags (proxy=proxy@entry=0x555563507ba0, opcode=opcode@entry=0, interface=interface@entry=0x0, version=version@entry=4, 
    flags=flags@entry=1, args=args@entry=0x7fffffff8f90) at ../src/wayland-client.c:900
#4  0x00007ffff7fb4408 in wl_proxy_marshal_flags (proxy=proxy@entry=0x555563507ba0, opcode=opcode@entry=0, interface=interface@entry=0x0, 
    version=4, flags=flags@entry=1) at ../src/wayland-client.c:823
#5  0x00007ffff751d1a3 in wl_buffer_destroy (wl_buffer=0x555563507ba0) at /usr/include/wayland-client-protocol.h:2035
#6  dri2_wl_destroy_surface (disp=<optimized out>, surf=0x555562d82150) at ../src/egl/drivers/dri2/platform_wayland.c:864
#7  0x00007ffff7505b3b in eglDestroySurface (dpy=<optimized out>, surface=0x555562d82150) at ../src/egl/main/eglapi.c:1301
#8  0x000055555cac1f01 in surfman::egl::Egl::DestroySurface (self=0x7ffff75c2720, dpy=0x555562c768b0, surface=0x555562d82150)
    at /home/wusyong/Desktop/servo/target/debug/build/surfman-09d511515218af3a/out/egl_bindings.rs:447
#9  0x000055555cab7a65 in surfman::platform::generic::egl::surface::{impl#3}::destroy::{closure#0} (egl=0x7ffff75c2720)
    at src/platform/generic/egl/surface.rs:249
#10 0x000055555cac3922 in std::thread::local::LocalKey<surfman::egl::Egl>::try_with<surfman::egl::Egl, surfman::platform::generic::egl::surface::{impl#3}::destroy::{closure_env#0}, ()> (self=0x5555626b3138, f=...)
    at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/local.rs:283
#11 0x000055555cac2308 in std::thread::local::LocalKey<surfman::egl::Egl>::with<surfman::egl::Egl, surfman::platform::generic::egl::surface::{impl#3}::destroy::{closure_env#0}, ()> (self=0x5555626b3138, f=...)
    at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/local.rs:260
#12 0x000055555cab791c in surfman::platform::generic::egl::surface::EGLBackedSurface::destroy (self=0x7fffffff95c0, gl=0x7ffff75c0fc0, 
    egl_display=0x555562c768b0, context_id=...) at src/platform/generic/egl/surface.rs:248
#13 0x000055555cab4cb4 in surfman::platform::unix::wayland::surface::{impl#1}::destroy_surface::{closure#0} (gl=0x7ffff75c0fc0)
    at src/platform/unix/wayland/surface.rs:170
#14 0x000055555cac572a in std::thread::local::LocalKey<surfman::gl::Gl>::try_with<surfman::gl::Gl, surfman::platform::unix::wayland::surface::{impl#1}::destroy_surface::{closure_env#0}, core::result::Result<(), surfman::error::Error>> (self=0x5555626b31d0, f=...)
    at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/local.rs:283
#15 0x000055555cac26ee in std::thread::local::LocalKey<surfman::gl::Gl>::with<surfman::gl::Gl, surfman::platform::unix::wayland::surface::{impl#1}::destroy_surface::{closure_env#0}, core::result::Result<(), surfman::error::Error>> (self=0x5555626b31d0, 
    f=<error reading variable: Cannot access memory at address 0x1>)
    at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/local.rs:260
#16 0x000055555cab907b in surfman::platform::unix::wayland::device::Device::destroy_surface (self=0x7ffff70a7520, context=0x7ffff70a7540, 
    surface=0x7fffffff95c0) at src/platform/unix/wayland/surface.rs:168
#17 0x000055555cab85db in surfman::platform::unix::wayland::device::Device::destroy_context (self=0x7ffff70a7520, context=0x7ffff70a7540)
    at src/platform/unix/wayland/context.rs:107
#18 0x000055555ca93b67 in surfman::platform::unix::wayland::implementation::{impl#1}::destroy_context (self=0x7ffff70a7520, context=0x7ffff70a7540)
    at /home/wusyong/.cargo/git/checkouts/surfman-d15b9f3e86c2e263/c8d6b4b/src/macros.rs:211
#19 0x000055555ca89eae in surfman::platform::generic::multi::device::Device<surfman::platform::unix::wayland::device::Device, surfman::platform::unix::x11::device::Device>::destroy_context<surfman::platform::unix::wayland::device::Device, surfman::platform::unix::x11::device::Device> (
--Type <RET> for more, q to quit, c to continue without paging--
    self=0x7ffff70a7518, context=0x7ffff70a7538)
    at /home/wusyong/.cargo/git/checkouts/surfman-d15b9f3e86c2e263/c8d6b4b/src/platform/generic/multi/context.rs:153
#20 0x000055555ca88ed7 in surfman::platform::generic::multi::device::{impl#2}::destroy_context<surfman::platform::unix::wayland::device::Device, surfman::platform::unix::x11::device::Device> (self=0x7ffff70a7518, context=0x7ffff70a7538)
    at /home/wusyong/.cargo/git/checkouts/surfman-d15b9f3e86c2e263/c8d6b4b/src/platform/generic/multi/device.rs:177
#21 0x000055555ca89df4 in surfman::platform::generic::multi::device::Device<surfman::platform::generic::multi::device::Device<surfman::platform::unix::wayland::device::Device, surfman::platform::unix::x11::device::Device>, surfman::platform::unix::generic::device::Device>::destroy_context<surfman::platform::generic::multi::device::Device<surfman::platform::unix::wayland::device::Device, surfman::platform::unix::x11::device::Device>, surfman::platform::unix::generic::device::Device> (self=0x7ffff70a7518, context=0x7ffff70a7538)
    at /home/wusyong/.cargo/git/checkouts/surfman-d15b9f3e86c2e263/c8d6b4b/src/platform/generic/multi/context.rs:153
#22 0x000055555ca6b291 in webrender_traits::rendering_context::{impl#0}::drop (self=0x7ffff70a7510)
    at components/shared/webrender/rendering_context.rs:38
#23 0x000055555ca697b7 in core::ptr::drop_in_place<webrender_traits::rendering_context::RenderingContextData> ()
    at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ptr/mod.rs:574
#24 0x000055555adbb520 in alloc::rc::{impl#30}::drop<webrender_traits::rendering_context::RenderingContextData, alloc::alloc::Global> (
    self=0x7ffff70b1310) at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/rc.rs:2217
#25 0x000055555adbb3fb in core::ptr::drop_in_place<alloc::rc::Rc<webrender_traits::rendering_context::RenderingContextData, alloc::alloc::Global>>
    () at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ptr/mod.rs:574
#26 0x000055555adba80b in core::ptr::drop_in_place<webrender_traits::rendering_context::RenderingContext> ()
    at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ptr/mod.rs:574
#27 0x0000555556068eb6 in core::ptr::drop_in_place<servoshell::desktop::headed_window::Window> ()
    at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ptr/mod.rs:574
#28 0x0000555556069dfd in core::ptr::drop_in_place<dyn servoshell::desktop::window_trait::WindowPortsMethods> ()
    at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ptr/mod.rs:574
#29 0x000055555606c3f6 in alloc::rc::{impl#30}::drop<dyn servoshell::desktop::window_trait::WindowPortsMethods, alloc::alloc::Global> (
    self=0x7ffff702c538) at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/rc.rs:2217
#30 0x0000555556062b1b in core::ptr::drop_in_place<alloc::rc::Rc<dyn servoshell::desktop::window_trait::WindowPortsMethods, alloc::alloc::Global>>
    () at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ptr/mod.rs:574
#31 0x000055555606528f in core::ptr::drop_in_place<(winit::window::WindowId, alloc::rc::Rc<dyn servoshell::desktop::window_trait::WindowPortsMethods, alloc::alloc::Global>)> () at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ptr/mod.rs:574
#32 0x00005555560c630c in core::ptr::mut_ptr::{impl#0}::drop_in_place<(winit::window::WindowId, alloc::rc::Rc<dyn servoshell::desktop::window_trait::WindowPortsMethods, alloc::alloc::Global>)> (self=0x7ffff702c530)
    at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ptr/mut_ptr.rs:1368
#33 hashbrown::raw::Bucket<(winit::window::WindowId, alloc::rc::Rc<dyn servoshell::desktop::window_trait::WindowPortsMethods, alloc::alloc::Global>)>::drop<(winit::window::WindowId, alloc::rc::Rc<dyn servoshell::desktop::window_trait::WindowPortsMethods, alloc::alloc::Global>)> (
    self=0x7fffffff9cd8) at /rust/deps/hashbrown-0.14.5/src/raw/mod.rs:590
#34 hashbrown::raw::RawTableInner::drop_elements<(winit::window::WindowId, alloc::rc::Rc<dyn servoshell::desktop::window_trait::WindowPortsMethods, alloc::alloc::Global>)> (self=0x7fffffffcca0) at /rust/deps/hashbrown-0.14.5/src/raw/mod.rs:2377
#35 0x00005555560c7510 in hashbrown::raw::RawTableInner::drop_inner_table<(winit::window::WindowId, alloc::rc::Rc<dyn servoshell::desktop::window_trait::WindowPortsMethods, alloc::alloc::Global>), alloc::alloc::Global> (self=0x7fffffffcca0, alloc=0x7fffffffccc0, table_layout=...)
--Type <RET> for more, q to quit, c to continue without paging--
    at /rust/deps/hashbrown-0.14.5/src/raw/mod.rs:2432
#36 0x0000555556072b5c in hashbrown::raw::{impl#18}::drop<(winit::window::WindowId, alloc::rc::Rc<dyn servoshell::desktop::window_trait::WindowPortsMethods, alloc::alloc::Global>), alloc::alloc::Global> (self=0x7fffffffcca0) at /rust/deps/hashbrown-0.14.5/src/raw/mod.rs:3673
#37 0x00005555560667ab in core::ptr::drop_in_place<hashbrown::raw::RawTable<(winit::window::WindowId, alloc::rc::Rc<dyn servoshell::desktop::window_trait::WindowPortsMethods, alloc::alloc::Global>), alloc::alloc::Global>> ()
    at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ptr/mod.rs:574
#38 0x0000555556066cab in core::ptr::drop_in_place<hashbrown::map::HashMap<winit::window::WindowId, alloc::rc::Rc<dyn servoshell::desktop::window_trait::WindowPortsMethods, alloc::alloc::Global>, std::hash::random::RandomState, alloc::alloc::Global>> ()
    at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ptr/mod.rs:574
#39 0x000055555606699b in core::ptr::drop_in_place<std::collections::hash::map::HashMap<winit::window::WindowId, alloc::rc::Rc<dyn servoshell::desktop::window_trait::WindowPortsMethods, alloc::alloc::Global>, std::hash::random::RandomState>> ()
    at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ptr/mod.rs:574
#40 0x0000555556068458 in core::ptr::drop_in_place<servoshell::desktop::app::App> ()
    at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ptr/mod.rs:574
#41 0x000055555605eda7 in servoshell::desktop::cli::main () at ports/servoshell/desktop/cli.rs:117
#42 0x000055555605db36 in servoshell::main () at ports/servoshell/lib.rs:38
#43 0x000055555605d6f7 in servo::main () at ports/servoshell/main.rs:26
(gdb) 
```

**Platform:**
Wayland

### PR DESCRIPTION
**Pull request by wusyong**
It turns out there are two problems when the window is dropped early on Wayland.
One is double free of EGL surface. The other is double free of smithay-clipboard's states.
The PR makes sure EGL surface is freed only once, and keep the winit window til end to make sure smithay's states are intact.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #34699

### CODE REVIEW

File: ports/servoshell/desktop/cli.rs [hunk 1]
```diff
@@ -103,10 +106,23 @@ pub fn main() {
     let event_loop = EventsLoop::new(opts::get().headless, opts::get().output_file.is_some())
         .expect("Failed to create events loop");
 
+    // Implements window methods, used by compositor.
+    let window = if opts::get().headless {
+        // GL video rendering is not supported on headless windows.
+        set_pref!(media.glvideo.enabled, false);
```
Comment (simonwuelker) [inline ports/servoshell/desktop/cli.rs:112]: It would be nice to log a warning here if `media.glvideo.enabled` was previously `true`

**Comment by simonwuelker** [comment]
I see that you've requested a review from me, but I don't really feel comfortable approving these changes, as I'm not familiar with this part of servo. I'm also not sure I fully understand the interaction that causes the double free of smithay-clipboard's states.

The fact that 100% safe code has seemingly caused multiple double frees is odd to me. If dropping the window at the wrong time causes undefined behaviour then ideally we should fix that instead of dropping it later.

**Comment by wusyong** [comment]
@simonwuelker it's okay to not review it. I just thought you might be interested because there's a comment.

What I did to move the window lifetime is kind of reverting back to the previous servoshell, which the window will live until the full application exits. Indeed we should fully resolve this eventually. But wayland has its own challenges and its community isn't that active on helping. Sometimes I had to spend months to resolve some issues around wayland. Perhaps we could add a fixme comment?

**Review by jdm — APPROVED** [review]
