### PR TITLE
deny_public_fields: display field identifier in help message

### LINKED ISSUE #17438: deny_public_fields proc macro prints misleading field name of structs
In the new proc macro `deny_public_fields` to replace `#[privatise]`, our diagnostics isn't clear.

On introducing `pub` on `name` field of `File` struct in `components/script/dom/file.rs`
```rust
#[dom_struct]
pub struct File {
    blob: Blob,
    pub name: DOMString,
    modified: i64,
}
```
and compiling we get:

```rust
error: proc-macro derive panicked
  --> /home/creativcoder/Desktop/servo/components/script/dom/file.rs:20:1
   |
20 | #[dom_struct]
   | ^^^^^^^^^^^^^
   |
   = help: message: Field __binding_1 should not be public

```

Instead the help message should be something like: 

= help: message: Field `name` should not be public

Code that needs changes: `components/deny_public_fields/lib.rs`

Hey @jdm, If this sounds like an easy bug to you then we can tag it with `E-Easy`.

### PR DESCRIPTION
**Pull request by HarveyHunt**
Use a binding's field identifier to produce more descriptive output.
Fall back to a binding's identifier if a field identifier is not
available.

Additionally, make the privatize.rs compiletest more specific and
wrap the identifier in backticks to aid readability.

As an aside, should I send a PR to rename ```compile-fail/privatize.rs``` to ```compile-fail/deny_public_fields.rs``` as privatize isn't mentioned in the codebase any more?

```
$ find . -name "*privatize*"
./tests/compiletest/plugin/compile-fail/privatize.rs
```

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #17438 (github issue number if applicable).

- [x] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17514)

### CODE REVIEW

File: components/deny_public_fields/lib.rs [hunk 1]
```diff
@@ -17,7 +17,11 @@ fn expand_string(input: &str) -> String {
     let style = synstructure::BindStyle::Ref.into();
     synstructure::each_field(&type_, &style, |binding| {
         if binding.field.vis != syn::Visibility::Inherited {
-            panic!("Field {} should not be public", binding.ident);
+            panic!("Field `{}` should not be public",
+                   match binding.field.ident.clone() {
```
Comment (creativcoder) [inline components/deny_public_fields/lib.rs]: We can write this as `panic!("Field `{}` should not be public", binding.field.ident.as_ref().unwrap_or(&binding.ident));` which is cleaner and avoids clone.

Comment (HarveyHunt) [inline components/deny_public_fields/lib.rs]: I was hoping there was a nicer way than using clone, I'll change it now 👍

**Comment by jdm** [comment]
@bors-servo: r+
Thanks for fixing this!

**Comment by HarveyHunt** [comment]
Thanks for the guidance :+1: 

Should I also send a PR to rename ```privatize.rs``` to ```deny_public_fields.rs```?

**Comment by jdm** [comment]
Sure, that makes sense!
