### PR TITLE
dom: Abort media element load on decode errors

### LINKED ISSUE #31688: Media player errors can prevent documents from reaching DocumentReadyState::Complete for a long time
To reproduce:

1. Uninstall gstreamer-plugins-good
  - #31686
  - #31687
2. `RUST_LOG='warn,servoshell<servo@LoadStart,servoshell<servo@HeadParsed,servoshell<servo@LoadComplete,script::dom::document' ./mach run -d 'data:text/html,<video autoplay src="https://video.fosdem.org/2024/h1308/fosdem-2024-2321-embedding-servo-in-rust-projects.av1.webm">'`

Output when installed:

```
[2024-03-15T05:40:39Z TRACE servoshell<servo@LoadStart] TopLevelBrowsingContext(0,1) LoadStart
[2024-03-15T05:40:39Z TRACE servoshell<servo@HeadParsed] TopLevelBrowsingContext(0,1) HeadParsed
[2024-03-15T05:40:41Z DEBUG script::dom::document] Document got finish_load: Media
[2024-03-15T05:40:41Z DEBUG script::dom::document] Document loads are complete.
[components/script/dom/document.rs:1039] state = Complete
[2024-03-15T05:40:41Z DEBUG script::dom::document] About to dispatch load for "data:text/html,<video autoplay src=https... (48b7fac362fd7c61)"
[2024-03-15T05:40:41Z TRACE servoshell<servo@LoadComplete] TopLevelBrowsingContext(0,1) LoadComplete
```

Output when uninstalled:

```
[2024-03-15T05:38:05Z TRACE servoshell<servo@LoadStart] TopLevelBrowsingContext(0,1) LoadStart
[2024-03-15T05:38:05Z TRACE servoshell<servo@HeadParsed] TopLevelBrowsingContext(0,1) HeadParsed
[2024-03-15T05:38:07Z ERROR script::dom::htmlmediaelement] Player error: "Error from element /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0: Your GStreamer installation is missing a plug-in.\nYour GStreamer installation is missing a plug-in.\n../gst/playback/gsturidecodebin.c(1049): no_more_pads_full (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0:\nno suitable plugins found:\n../gst/playback/gstdecodebin2.c(4704): gst_decode_bin_expose (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0:\nno suitable plugins found:\nMissing decoder: WebM (video/webm)\n"
```

### PR DESCRIPTION
**Pull request by frereit**
Previously, when a `PlayerEvent::Error` was encountered, an `error` Event was fired on the element, but the "delaying-the-load-event" flag was never set to false, so the document was loading until the end of the media source was received in `process_response_eof`:

https://github.com/servo/servo/blob/d6d903c5a11bafe7a23d15c7fd94d87dff6e3ac6/components/script/dom/htmlmediaelement.rs#L2811

I think the issue was that the `PlayerEvent::Error` was not handled according to spec. I believe the relevant portion is "[The media data processing steps list is as follows: ... If the media is corrupted](https://html.spec.whatwg.org/multipage/media.html#loading-the-media-resource%3Amedia-data-13)".

I've implemented most of the steps but am unsure about "6. Abort the overall resource selection algorithm." Is this even applicable here, or is it "automatically" aborted by cancelling the fetch event?

With this patch, the `LoadComplete` event is triggered immediately after a media decode error:

```
[2024-03-18T22:02:48Z ERROR script::dom::htmlmediaelement] Player error: "Error from element /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0: Your GStreamer installation is missing a plug-in.\nYour GStreamer installation is missing a plug-in.\n../gst/playback/gsturidecodebin.c(1049): no_more_pads_full (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0:\nno suitable plugins found:\n../gst/playback/gstdecodebin2.c(4704): gst_decode_bin_expose (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0:\nno suitable plugins found:\nMissing decoder: WebM (video/webm)\n"
[2024-03-18T22:02:48Z DEBUG script::dom::document] Document got finish_load: Media
[2024-03-18T22:02:48Z DEBUG script::dom::document] Document loads are complete.
[2024-03-18T22:02:48Z DEBUG script::dom::document] About to dispatch load for "data:text/html,<video autoplay src=\"http... (f8a72f128b37adab)"
[2024-03-18T22:02:48Z TRACE servoshell<servo@LoadComplete] TopLevelBrowsingContext(0,1) LoadComplete
```

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #31688
- [X] These changes are hard to test becuase WPT currently only tests this through a MediaSource, which is not yet implemented in servo.

### CODE REVIEW

**Comment by frereit** [comment]
> think these changes do change behavior, though perhaps they are hard to test for other reasons. I wonder if there is a way to write a test for this though.

I just spent some time looking into how to test is. Unfortunately it seems pretty difficult to test `MEDIA_ERR_DECODE` right now. As far as I can tell, WPT currently only tests this through a `MediaSource`, which is not yet implemented in servo (?):

File: components/script/dom/htmlmediaelement.rs [hunk 1]
```diff
@@ -1551,11 +1551,29 @@ impl HTMLMediaElement {
...
+                // 3. Set the element's networkState attribute to the NETWORK_IDLE value.
+                self.network_state.set(NetworkState::Idle);
+
+                // 4. Set the element's delaying-the-load-event flag to false. This stops delaying the load event.
+                self.delay_load_event(false);
+
+                // 5. Fire an event named error at the media element.
                 self.upcast::<EventTarget>().fire_event(atom!("error"));
+
+                // TODO: 6. Abort the overall resource selection algorithm.
```
Comment (frereit) [inline components/script/dom/htmlmediaelement.rs:1576]: I believe this is not required here / we can skip this step. There is a similar error path in `HTMLMediaElementFetchListener` that is also supposed to "Abort the overall resource selection algorithm" and it is skipped there too:

https://github.com/servo/servo/blob/06a021db552c1d2f8899484f7c1143424c387eef/components/script/dom/htmlmediaelement.rs#L2813-L2833

**Comment by mrobinson** [comment]
> WPT currently only tests this through a MediaSource, which is not yet implemented in servo

This makes sense to me and the code change is pretty straight-forward. I've updated the PR description to say this.

**Review by mrobinson — APPROVED** [review]

**Review by mrobinson — APPROVED** [review]
